### ISSUE TITLE
Springer ISSN 2199-465X Mapping the Age of Official Desistance for Adult Offenders: Implications for Research and Policy

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#100]
First Online Artikel ohne Zuordnung zu einem Band/Heft, mit Auswirkungen auf 773 und 936
Dasselbe Problem wie bei Sage und Taylor & Francis.
Hier als First Online gelabelt.
Wie gesagt müssen wir bei uns erst noch entscheiden, wie wir damit verfahre wollen
Dennoch:
Die Wegseite bietet die Seitenzahlen des Aufsatzes:
https://link.springer.com/article/10.1007%2Fs40865-018-0095-8
Diese könnte man in 773 und 936 übernehmen.
Der Feed enthält 3 First Online Artikel, die alle eine separate Seitenzählung besitzen (1-36, 1-19, 1-23), womit ausgeschlossen ist, das die Seitenzählung etwa Verwirrung hervorrufen könnte (z. B. bei einer Seitenangabe wie 37-56 ohne eine Bandangabe)

**Comment by shadeMe** [comment]
Ist dieses Issue immer noch aktuell? Wir liefern zurzeit Online First Datensätze mit, solange die eine DOI enthalten.

**Comment by kdr154** [comment]
Auf first online wollten wir erst mal verzichten

**Comment by kdr154** [comment]
gelöst
