### ISSUE TITLE
ISSN 1745-5308 | The Expository times | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1000]
**URL**
https://doi.org/10.1177/0014524619883180

**Ausführliche Problembeschreibung**
Die Keywords werden beim Multi-DL nicht erfasst.

Die Zs ist ein Test-Kandidat für das vollautomatische Verfahren. Solange das aber noch nicht live ist, sollten aktuelle Hefte dennoch ordentlich erfasst werden können.

**Comment by kdr154** [comment]
Keywords werden im halbautomatischen Verfahren bei Sage nicht mit erfasst. Ich habe bestimmt schon mehr als ein Issue dazu angelegt. Da das Problem nicht behoben wurde, bin ich dazu übergegangen hier die Keywords manuell einzufügen. In Word kopieren, das Komma gegen ein Absatzzeichen austauschen, alles markieren und alles in Zotero im Tab Tags einfügen.

**Comment by socheres** [comment]
Anders als beim Erkennen von Rezensionen etc. sollten die Keywords beim Zotkat vorhanden sein, sofern dies auch beim Zotaut der Fall ist. Es kann aber sein, dass das Skript auf dem lokalen Verzeichnis von dem der ubtue-Translators abweichen. Hier werden die Keywords auch im Zotaut nicht erfasst, daher habe ich den Translator angepasst und Ihre lokalen Skripte aktualisiert. Sie können nun nach Neustart und "Update Translators" in "Advanced"-Option nochmal testen. Die Keywords sollten nun mitkommen. @mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by socheres** [comment]
Im Zotaut fehlen die Keywords ebenfalls:


Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_sBvB33" "--output-filename=XRne5h.xml" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://doi.org/10.1177/0014524619883180" "The Expository times"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The Expository times' \| DIRECT @ https://doi.org/10.1177/0014524619883180 set download-delay for domain 'doi.org' to 1000 ms   Harvesting URL 1 [The Expository times...] \| https://doi.org/10.1177/0014524619883180 {9275286917884790720} Harvest successful     Converting item 1 [The Expository times...] \| https://doi.org/10.1177/0014524619883180 {9275286917884790720} use online ISSN "1745-5308" with online PPN "368316432" post-processed author first name = 'Jonathan', last name = 'Kangwa', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: https://journals.sagepub.com/doi/10.1177/0014524619883180, 	item_type: journalArticle, 	title: Resilience and Equality in the Household of God: Peggy Mulambya Kabonde’s Search for Justice:, 	short_title: Resilience and Equality in the Household of God, 	abstract_note: The World Council of Churches (WCC) commemorated its 70th anniversary in 2018. Over the years, the WCC has engaged with issues that affect women in the Church a..., 	publication_title: The Expository Times, 	date: 2019-10-15, 	doi: 10.1177/0014524619883180, 	language: eng, 	issn: 1745-5308, 	superior_ppn: 368316432, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Jonathan, 			last_name: Kangwa, 			type: author, 		}, 	], } Skipping: online-first article unconditionally Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 1 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0

**Comment by socheres** [comment]
bitte wie in #997 verfahren.

**Comment by IxKo** [comment]
Im Single-DL bearbeiten
