### ISSUE TITLE
ISSN 0021-969X | Journal of church and state | vermeintliche Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1001]
**URL**
https://doi.org/10.1093/jcs/csz033

**Ausführliche Problembeschreibung**
Es wird der Anriss vom Full Text als Abstract übernommen. Das sollte unterdrückt werden.

Die Zs ist ein Test-Kandidat für das vollautomatische Verfahren. Solange das aber noch nicht live ist, sollten aktuelle Hefte dennoch ordentlich erfasst werden können.

**Comment by socheres** [comment]
Bitte die Extract mit aufnehmen. Für die Suche sind die auf jeden Fall sehr sinnvoll:https://academic.oup.com/jcs/issue/62/2
Z.B. paar Beispiele aus dem Heft:https://academic.oup.com/jcs/issue/62/2
10.1093/jcs/csaa018
In this contribution to the Lives of Great Religious Books series, Joel Baden, a professor of Hebrew Bible at Yale Divinity School, guides his readers on a them
10.1093/jcs/csz028
The ongoing peace process between the Burmese government (and military) and many ethnic armed organizations ideally aims to bring about a negotiated political s
10.1093/jcs/csaa020
In Faking Liberties, Jolyon Thomas subjects a pervasive idea that in 1945 American religion brought freedom to a religious despot Japanese state to careful crit
im Zotaut wird der "Abstract" auch nicht mehr unterdrückt.

**Comment by IxKo** [comment]
Aus Katalogisierer-Sicht sind dies aber keine inhaltlichen Zusammenfassungen oder ähnliches. Oder wie siehst du es @kdr154 ?

**Comment by socheres** [comment]
Extract ist streng genommen keine "inhaltliche Zusammenfassung", aber gerade im einleitenden Text kommen für das Thema eines Aufsatzes maßgebliche Wörter vor. Z.B. 
Titel "One Volk, One Church? A Critique of the “Folk Church” Ideology in Finland" https://doi.org/10.1093/jcs/csz030
Extract "Is the Evangelical Lutheran Church of Finland (ELCF) a state church or not?1 The answer depends on whom you ask. Looking at international surveys and comparisons, the answer is a clear “yes.” On Chaves and Cann’s six-point scale, Finland scored the highest of all 18 countries compared in terms of the state privileging one or more denominations.2 Christensen’s analysis of historical and current debates on the issue of Finnish church and state relations—in many ways a precursor to my own aims here—says clearly, “The Church exists within a special relationship with the state, and maintains many of the same..." Daher sollte er indexiert werden. Ich adressiere auch @thefass  @Gazeller @relhei

**Comment by socheres** [comment]
Außerdem noch die Definition von  4207 "Das Feld 4207 enthält eine inhaltliche Zusammenfassung der Vorlage (Summary, Abstract usw.)."  Vielleicht könnte man Extract zu "usw." dazunehmen? https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4207&katalog=Standard

**Comment by kdr154** [comment]
Inhaltliche Zusammenfassungen sind das auf keinen Fall. Es ist für mich die Frage, ob man es in Kauf nehmen will, dass der ein oder andere vielleicht die Nase rümpft.

**Comment by thefass** [comment]
Ja, das können wir in Kauf nehmen.

**Comment by IxKo** [comment]
Okay, dann schließe ich.
