### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | zota

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1002]
Könnte auf zota gesetzt werden. Es handelt sich allerdings um eine Prio 2-Zeitschrift. Und es ist eine Kooperation vorgesehen.

**Comment by thefass** [comment]
@relhei Da die Zss vollstänidg ausgewertet werden soll, wäre zota bei uns am Besten. Oder gibt es schon konkrete Absprachen bzgl einer Koopertion?

**Comment by socheres** [comment]
@IxKo @kdr154 habe einen nenen Label angelegt "ready for zota" (= nach dem Vier-Augen-Prinzip zur Übernahme in den Produktivbetrieb freigegebene Zeitschriften). Wenn Sie dieses Label hinzufügen, wird @socheres in Zeder den Wert auf "zota" setzen.

**Comment by kdr154** [comment]
sehr gut

**Comment by socheres** [comment]
Habe dazu einen neuen Issue angelegt #1031

**Comment by socheres** [comment]
@kdr154 @IxKo bitte "ready for zota" hinzufügen.

**Comment by IxKo** [comment]
> 
> 
> sehr gut. Leider gibt es bei dieser Zeitschrift auch die unglückliche Geschichte von Unterschieden bei Berichts- und Erscheinungsjahr. Oder ist schon entschieden worden, wie man da verfährt?

Nach telefonischer Rücksprache mit socheres und aufgrund des oben genannten Porblems (siehe auch #1054) in Zeder von zota auf zotat zurückgesetzt.

**Comment by IxKo** [comment]
> @thefass @IxTheoKm @Gazeller @relhei habe einen nenen Label angelegt "ready for zota" (= nach dem Vier-Augen-Prinzip zur Übernahme in den Produktivbetrieb freigegebene Zeitschriften). Wenn @IxKo @kdr154 dieses Label hinzufügen, wird @socheres in Zeder den Wert auf "zota" setzen. Z.K. auch an @mtrojan-ub @ruschein

Hat die oben beschriebene Vorgehensweise mit dem Label noch Gültigkeit? Oder ersetzt die E-Mail-Benachrichtigung das?

**Comment by kdr154** [comment]
?

**Comment by IxKo** [comment]
Falls wir auch mit dem Label hier in GitHub arbeiten sollen, müssten wir dann zu jeder Zs ein "Issue" öffnen und dann das Label vergeben? 
Das von mir Zitierte stammt von sochereres aus diesem Issue.

**Comment by IxKo** [comment]
Da sich der Geschäftsgang geändert hat (Kommunikation über E-Mail) scheint mir meine Frage und das Label hinfällig.

**Comment by IxKo** [comment]
Ist live.
