### ISSUE TITLE
ISSN 1354-9901 | Studies in World Christianity | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1003]
Die Abstract werden abgeschnitten.
Hier: https://www.euppublishing.com/doi/abs/10.3366/swc.2020.0292
![grafik](https://user-images.githubusercontent.com/29707105/84125879-7a4fd280-aa3d-11ea-868f-3ab79f95d42d.png)

So:

![grafik](https://user-images.githubusercontent.com/29707105/84125670-2c3acf00-aa3d-11ea-9747-1505c9fd9dcc.png)

**Comment by socheres** [comment]
@kdr154 wird der Abstract auch im Zotaut abgeschnitten?

**Comment by kdr154** [comment]
Nein, dort ist es komplett

**Comment by socheres** [comment]
Ich kann den Fehler nicht reproduzieren, bei mir wird der Abstract sowohl im Multi- als auch im Single-DL nicht abgeschnitten und Ihr Translator ist auch akutuell. @IxKo Würden Sie auch testen?
![image](https://user-images.githubusercontent.com/1545743/85843196-27964a80-b7a1-11ea-9ff6-765105d4fb69.png)

**Comment by IxKo** [comment]
Bei mir wird das Abstract sowohl im Multi- als auch im Einzel-DL (via Edinburgh-Translator) ) nicht abgeschnitten.

**Comment by kdr154** [comment]
Danke, ist jetzt ok!
