### ISSUE TITLE
ISSN 1354-9901 | Studies in World Christianity | Lizenzangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1004]
Eine Lizenzangabe, in diesem Fall ZZ, wird nicht vergeben. 
Gibt es für der ISSN_to_licence.map eine Entsprechung zu l und kw für lizenzpflichtige Zeitschriften, die im Zotkat-Verfahren bearbeitet werden?

**Comment by kdr154** [comment]
Ein Test auf nu mit dem aktuellen Heft ist erfolgreich im Hinblick auf die Problematik mit der Lizenzangabe und auf die ebenfalls angeaprochene Problematik mit dem abgschnittenen Abstract. 
Im Grunde müssten nur die Artikel Front Matter und Back Matter und bei Bedarf das Editorial (im Falle dieses Heftes sollte es aufgenommen werden, da es einen eigenen Titel besitzt) übergangen werden, dann wäre diese ZS zota geeignet.
Somit stellt sich für mich die Frage, ob wir diese Zeitschrift(en) noch halbautomatisch bearbeiten sollen.

**Comment by socheres** [comment]
@kdr154 @IxKo verpflichtend im Zotkat ist nur das "LF" für OA-Zeitschriften. Fürs Zotaut sthet die Entscheidung noch aus.

**Comment by socheres** [comment]
in der Abteilungsrunde besprochen, daher ich schließe.
