### ISSUE TITLE
ISSN 2396-9407 | International Bulletin of Mission Research | Überflüssiger Doppelpunkt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1006]
In Zotero wird ein überfüssiger Doppelpunkt am Ende des Titels gesetzt:

![grafik](https://user-images.githubusercontent.com/29707105/84643052-9bad3480-aefd-11ea-8336-8e612ff983c4.png)

**Comment by socheres** [comment]
Um welchen URL handelt es sich hierbei? Bitte immer URL bzw. DOI angeben.

**Comment by kdr154** [comment]
Das galt genrell, bei allen Titeln. Ist aber nicht mehr der Fall:

![grafik](https://user-images.githubusercontent.com/29707105/85844461-0f272f80-b7a3-11ea-86b5-15896abbcec0.png)
 Deshalb schließe ich,
