### ISSUE TITLE
ISSN 1939-3881 | CrossCurrents | Titelzusatz nicht erfasst

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1007]
Der Titelzusatz wird nicht erfasst. Bsp.:
So sieht es in Zotero aus:
![grafik](https://user-images.githubusercontent.com/29707105/84661817-2e100100-af1b-11ea-869e-242770af79b2.png)
So sieht es auf der Seite mit dem Inhaltsverzeichnis des Heftes aus:
![grafik](https://user-images.githubusercontent.com/29707105/84661966-68799e00-af1b-11ea-9adc-429f653aa312.png)
So auf der Seite des Artikels:
![grafik](https://user-images.githubusercontent.com/29707105/84662071-95c64c00-af1b-11ea-8461-9a1a7a1787b6.png)

**Comment by socheres** [comment]
hier kann ich zwar vom Bild die DOI abtippen, aber bitte immer DOI bzw. URL angeben.

**Comment by socheres** [comment]
Ihr Wiley Translator war nicht auf aktuellem Stand. Habe nun aktualisert.

**Comment by socheres** [comment]
Sowohl im Single- als auch Mulit-DL richtig:
![grafik](https://user-images.githubusercontent.com/1545743/85844947-cb80f580-b7a3-11ea-9c55-7d169a165e32.png)

**Comment by kdr154** [comment]
Danke, passt jetzt.

**Comment by IxKo** [comment]
Bei mir wurde heute auch nicht der Titelzusatz erfasst.

**Comment by socheres** [comment]
bitte testen.

**Comment by kdr154** [comment]
Bei mir sind die Titel komplett.

**Comment by IxKo** [comment]
Bei mir auch.
