### ISSUE TITLE
ISSN 1573-6679 | Pastoral Psychology | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1008]
Die Keywords werden nicht erfasst. Sie befinden sich in der Sektion About this article.
Siehe https://link.springer.com/article/10.1007/s11089-020-00899-1
Ich meine, dass man für die Springer-Zeitschriften beim vollautomatischen Verfahren eine Lösung gefunden hat.

**Comment by socheres** [comment]
Ihr raslator "Springer Link.js" wurde am 25.06.2020 aktualisiert.

**Comment by socheres** [comment]
Als Default Translator wird auch hier "Open Journal Systems Multi-Wrapper.js" angeboten. Mit dem Rechtsklick kann "Springer Link.js" ausgewählt werden. Bei mir kommen so die Keywords mit. 
URL:https://link.springer.com/article/10.1007/s11089-020-00899-1
![image](https://user-images.githubusercontent.com/1545743/86233995-948d5400-bb96-11ea-9a4d-edce6352f9b4.png)

**Comment by socheres** [comment]
@IxKo können Sie bitte auch testen?

**Comment by IxKo** [comment]
Mit dem Springer-Multi werden bei mir die Keywords erfasst.

**Comment by kdr154** [comment]
bei mir auch
