### ISSUE TITLE
ISSN 1461-7404 | Social Compass | Sprache 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1010]
Die Sprache wird nicht richig erkannt. Immer en. Hier z. B. muss es fre sein:
https://journals.sagepub.com/doi/full/10.1177/0037768620917281

**Comment by socheres** [comment]
siehe https://github.com/ubtue/DatenProbleme/issues/1020#issuecomment-646645674

**Comment by kdr154** [comment]
schließe
