### ISSUE TITLE
ISSN 1461-7404 | Social Compass | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1011]
Von den beiden Abstracts wird nur eines übernommen.
https://journals.sagepub.com/doi/full/10.1177/0037768620917281
![grafik](https://user-images.githubusercontent.com/29707105/84869899-e86c4900-b07e-11ea-8439-6adc79b73ef0.png)

**Comment by socheres** [comment]
Sage Translator muss gründlich überarbeitet werden, daher bitte manuell im Single-DW bearbeiten.

**Comment by kdr154** [comment]
schließe
