### ISSUE TITLE
ISSN 1461-7404 | Social Compass | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1012]
Keywords werden beim Multi-Download nicht erfasst.
https://journals.sagepub.com/doi/full/10.1177/0037768620917281

![grafik](https://user-images.githubusercontent.com/29707105/84870246-5add2900-b07f-11ea-8a10-bd6403c7f3c9.png)

**Comment by socheres** [comment]
bitte im Single-DW bearbeiten.

**Comment by kdr154** [comment]
schließe
