### ISSUE TITLE
ISSN 1461-7404 | Social Compass | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1013]
Keywords werden beim Einzeldownload zwar erfasst, aber die Begriffe Keywords und Mots-clés ebenfalls. 
Darüber hinaus führt in diesem Fall der Begriff Mots-clés zu einer falschen Separierung der Keywords:

https://journals.sagepub.com/doi/full/10.1177/0037768620916396
![grafik](https://user-images.githubusercontent.com/29707105/84871939-79442400-b081-11ea-8a3c-6ac7103deda4.png)

![grafik](https://user-images.githubusercontent.com/29707105/84872238-eb1c6d80-b081-11ea-85c9-e45afa58b08c.png)
Das letzte Keyword sollten zwei sein: 
social-legal study of religion und acteurs sociaux de base

**Comment by socheres** [comment]
bitte manuell bereinigen.

**Comment by kdr154** [comment]
Dann schließe ich
