### ISSUE TITLE
Allgemein: Lizenzangabe KW in $z statt $4

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1014]
**Ausführliche Problembeschreibung**
In der ISSN_to_licence-Mapping-Liste sind bereits einige Zss mit kw definiert. Probiert man jedoch eine aus, landet das KW nicht in Pica-4950-Unterfeld $4 sondern in $z.

Das Marc-Feld 856 Unterfeld z beim K10plus wird für den Export sowohl für Pica-4950 $z als auch für $4 angegeben.

Demnach könnte der Fehler beim Import zum BSZ liegen und müsste da geklärt werden. Denn Zss die in der Mapping-Liste mit l für LF hinterlegt sind, landen korrekt in $4.
Oder müssen wir in der Mapping-Liste nicht kw sondern eventuell nur k eintragen?

Eine Nebenfrage dazu: Die Zss, die ZZ sind, sollen diese auch in Mapping-Liste eingetragen werden, wenn wie ja oder wird es dafür noch eine andere Lösung geben?

**Comment by socheres** [comment]
Im Zotkat habe ich beide Pica-Skripte (einzeln, batch) angepasst. @IxKo fürs Zotaut bitte ich um ein Beispiel.

**Comment by IxKo** [comment]
Z.B bei diesem Zeitschriften-Heft: https://jps.library.utoronto.ca/index.php/renref/issue/view/2258
eISSN 2293-7374, Renaissance and reformation

**Comment by socheres** [comment]
das ist aber eine Zss. via Crawl https://github.com/ubtue/zotero-enhancement-maps/blob/9fb3cfd2b915dc7cc5482c5d5d7832124087cf70/zotero_harvester.conf#L6323 und laut ZEDER noch ein "zot" Zeitschrift. Daher bitte diesen Issue schließen. Die Lizenzangabe klären wir in einem anderen Issue.

**Comment by IxKo** [comment]
Aber auch bei dem semi-automatischen Verfahren wird die Lizenzangabe falsch übermittelt. Ich habe nur das Label Zotero-Auto-RSS vergeben, weil ich stark annehme, dass es hier dieselben Probleme geben wird.

**Comment by socheres** [comment]
> Aber auch bei dem semi-automatischen Verfahren wird die Lizenzangabe falsch übermittelt. 
Pica-Translator habe ich angepasst. Bitte testen.

**Comment by IxKo** [comment]
KW landet nach einem Test nun in 4950 $4
