### ISSUE TITLE
ISSN 2516-6301 | Scottish Church History | Überflüssige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1015]
Front Matter | Back Matter
https://www.euppublishing.com/toc/sch/49/1

**Comment by socheres** [comment]
mit "Try URL" getestet
`MARC field for 'https://www.euppublishing.com/toc/sch/49/1 matched exclusion filter (245a/^(Front|Back) (M|m)atter/)
Conversion complete`
