### ISSUE TITLE
ISSN 2166-5508 | Traditio | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1016]
Hier hat es einen Verlagswechsel gegeben und die Zeitschrift soll nun möglicherweise von uns katalogisiert werden. Am Besten mit zotaut. Aber es gibt bei zotkat bereits Probleme.
Im Gegensatz zu anderen Zeitschriften die von CUP publiziert werden bekommt man hier beim Multidownload keinen Translator angeboten, der funktioniert. D. h. hier ist ein Multidownload nicht möglich.
Bei den anderen CUP-Zeitschriften stehen Cambridge Core und Equinox Pub zur Verfügung. Bei beiden werden zwar die Keywords nicht mitgeliefert, aber man kann die Artikel zumindest herunterladen. Bei Traditio steht nur Embedded Metadata zur Verfügung, der nur das  Speichern der Webseite als Ganzes zulässt.

**Comment by socheres** [comment]
bitte um URL-links.

**Comment by kdr154** [comment]
https://www.cambridge.org/core/journals/traditio/volume/457140A681503A32A6BB484F73F270A3

**Comment by socheres** [comment]
im Einzel-DW mit Cambridge Core Translator sind alle Angaben (abstract+keywords) vorhanden. Bitte einzel bearbeiten.

**Comment by socheres** [comment]
@kdr154 bitte schließen.

**Comment by kdr154** [comment]
mache ich
