### ISSUE TITLE
ISSN 1804-6444 | Journal of European Baptist Studies | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1017]
Diese ZS ist neu für den IxTheo und soll nach Möglichkeit mit zotaut bearbeitet werden.
Beim halbautomatischen Verfahren im Multidownload melden der Open Journal System Multi-Wrapper einen Fehler und bricht ab.

**Comment by socheres** [comment]
wird in #1018 weiter diskutiert.
