### ISSUE TITLE
ISSN 1804-6444 | Journal of European Baptist Studies | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1018]
Diese ZS ist neu für den IxTheo und soll nach Möglichkeit mit zotaut bearbeitet werden.
Das Abstract wird im Single-Downloadverfahren nicht erfasst.

**Comment by socheres** [comment]
Bei mir wird er angeboten. Am Besten Browser und Zotero neustarten. Wenn das auch nicht hilft, PC neustarten. Vielleicht läuft der alte Zotero-Prozess im Hintergrund. 
![image](https://user-images.githubusercontent.com/1545743/85676692-209b0980-b6c7-11ea-837a-a4ce83d27cf8.png)

**Comment by kdr154** [comment]
Leider weiterhin nicht. Obwohl sich ein Translator Journal of European Baptist Studies in meinem Verzeichnis befindet. Habe jetzt auch noch den Neustart des PCs durchgeführt.

**Comment by socheres** [comment]
Hm... @IxKo Wird bei Ihnen der Translator angeboten?

**Comment by socheres** [comment]
@IxKo @kdr154 Wird Ihnen nun der Translator angeboten, oder immer noch nicht?

**Comment by kdr154** [comment]
Bei mir noch nicht.

**Comment by IxKo** [comment]
Bei mir auch nicht.

**Comment by socheres** [comment]
Hm. Am Besten klären wir in einer VC mit Screensharing (DFN Conf). Ich melde mich.

**Comment by socheres** [comment]
Funktioniert das Translator "Journal of European Baptist Studies.js" immer noch nicht?

**Comment by kdr154** [comment]
Steht mir immer noch nicht zur Verfügung. Habe alles mit dem Multi-Wrapper bearbeitet.

**Comment by socheres** [comment]
mit Multi-Wrapper kommen alle Metadatenfelder vollständig mit, allerdings funktioniert der Multi-DL nicht. Warum der neue Translator Ihnen Beiden nicht angeboten wird, ist mir ein Rätsel.

**Comment by IxKo** [comment]
> 
> 
> Funktioniert das Translator "Journal of European Baptist Studies.js" immer noch nicht?

Wird weiterhin nicht angeboten.

**Comment by socheres** [comment]
Können Sie hier nochmal testen? Die Seite braucht etwas länger bis der Download-Button in ein Ordnersymbol angezeigt wird. So ca. 10-20 Sekunden.

**Comment by kdr154** [comment]
Es tut mir leid. Das Ordnersymbol war gleicht da, aber kein "Journal of European Baptist Studies.js". Zuvor im Browser und in Zotero aktualisiert.

**Comment by IxKo** [comment]
Bei mir kommt auch nach langem Warten kein Ordner-Symbol.

**Comment by socheres** [comment]
Translator "ubtue_Journal of European Baptist Studies.js" wird mir aus unerklärlichen Gründen an zweiter Stelle nach "ubtue_Davarlogos.js" angeboten. Die Datensätze sehen gut aus. Bitte auch testen.

**Comment by IxKo** [comment]
Mir wird der European Baptist Studies Translator nicht angezeigt:
![grafik](https://user-images.githubusercontent.com/57000004/94894402-931b4280-0489-11eb-89f5-1dee97988ec7.png)

**Comment by kdr154** [comment]
Mir auch nicht.

**Comment by socheres** [comment]
ich schließe dieses Issue. Diese Zeitschrift kann mit einem anderen Translator bearbeite werden.
