### ISSUE TITLE
ISSN 2309-9089 | Acta theologica | Seitenangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1019]
**URL**
http://journals.ufs.ac.za/index.php/at/issue/view/437

**Ausführliche Problembeschreibung**
Die Seitenangaben werden im Multi-DL mit Translator OJS nicht übertragen.
Im Einzel-DL schon, da würden aber wiederum die Abstracts fehlen.

**Comment by socheres** [comment]
Open Journal Systems Multi-Wrapper.js ist akutalisiert. Bitte Translators im Zotero aktualisieren und testen.

**Comment by IxKo** [comment]
Beim Versuch mit dem Multi-DL erscheint die Meldung "Ein Fehler ist aufgetreten..."
@kdr154 klappt es bei Dir?

**Comment by kdr154** [comment]
Bei mir ist es dasselbe.

**Comment by socheres** [comment]
@IxKo Felhlen die Seitenangaben im Einzel-DL mit "Mutli-Wrapper" weiterhin? Für Mulit-DL muss ein neuer Translator geschrieben werden. Daher im Einzel-DL bearbeiten.

**Comment by IxKo** [comment]
Im Einzel-DL mit dem OJS-Multi-Wrapper kommen die Seitenangaben mit. Die Keywords jedoch nicht vollständig:
http://journals.ufs.ac.za/index.php/at/article/view/4480
Hier kommt bspw. nur 1 der 4 Keywords mit.

**Comment by kdr154** [comment]
Bei mir dasselbe

**Comment by socheres** [comment]
habe einen neuen Translator für Acta Theologia geschrieben. Testen Sie bitte den Translator im Einzel-DL. Multi-DL geht leider nicht. Bitte vorher Translator im Client und Browser aktualisieren.
![image](https://user-images.githubusercontent.com/1545743/86359321-22d60880-bc71-11ea-9760-00bae62058d0.png)

**Comment by kdr154** [comment]
Wie lautet denn der neue Translator. Bin nach Ihren Vorgaben vorgegangen. Seitenzahlen sind da, aber nur ein Keyword (Gender roles)

**Comment by socheres** [comment]
der neue Translator ist "ubtue_Acta Theologica.js"

**Comment by kdr154** [comment]
Jetzt war er da. Und auch alle keywords und die Seitenzahlen.

**Comment by IxKo** [comment]
Bei mir ist er nicht da. Ich habe über das Plug-In die Translators aktualisiert, den Cache des Browsers gelöscht und die Seite neu geladen.

**Comment by socheres** [comment]
Multi-DL funktioniert bei dem Translator "Acta theologica" nicht.

**Comment by IxKo** [comment]
Ok
