### ISSUE TITLE
ISSN 1752-0738 | Reformation | Problem mit Zotero-Export

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1020]
**URL**
https://www.tandfonline.com/toc/yref20/25/1

**Ausführliche Problembeschreibung**
Die Daten landen sowohl im Einzel- als auch Mutli-DL dem Anschein nach gut in Zotero.
Will ich die Einträge jedoch mit Strg+Shift+C kopieren, um sie ins Script einzufügen, erhalte ich Zotero diese Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/57000004/85135142-eac8d180-b23d-11ea-9575-17be618e8d85.png)

So sieht die Info eines Eintrages aus:
![grafik](https://user-images.githubusercontent.com/57000004/85135229-15b32580-b23e-11ea-846d-01b6355c95d1.png)

Gab es ein solches Problem schon einmal?

Die Zs ist zwar ein Zota-Kandidat, aber so kann sie absolut nicht im semi-Verfahren bearbeitet werden bis sie mal in den Live-Betrieb geht.
@kdr154 Hast du dasselbe Problem?

**Comment by socheres** [comment]
Fall Nr. 4 hat den Fehler verursacht.

> Mail vom 3.6.2020

1. vorrangig wird die Sprache genommen, die in der Mapping aufgelistet
ist:https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map

2. wenn es keine Entsprechung in der "ISSN_to_language_code.map" gibt, dann wird der Wert im Zoterofeld "Sprache" mit der Mapping "language_to_language_code.map" abgeglichen und das PICA-konforme Sprachfeld ausgegeben.
3. Falls keine Entsprechung in "language_to_language_code.map" gibt, dann wird der ursprüngliche Wert im Zoterofeld "Sprache" ausgegeben.
4. Wenn es aber sowohl ein Key-Value-Paar in der
"ISSN_to_language_code.map" fehlt als auch das Zoterofeld "Sprache"
nicht belegt ist, kann der Datensatz nicht nach PICA exportiert
werden. Es gibt dann eine Fehlermeldung in Zotero. Um den Aufsatz
bearbeiten zu können, muss vorher die Mappingtabelle
"ISSN_to_language_code.map" um fehlenden Eintrag ergänzt werden. Default-Wert für Sprache gibt es nun nicht mehr.

**Comment by IxKo** [comment]
Okay, danke für die Erklärung und das Eintragen in die Mapping-Liste. Das schien tatsächlich die Ursache zu sein, denn nun erscheint der Fehler nicht mehr.
