### ISSUE TITLE
ISSN 2034-6468 | Apocrypha | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1021]
**URL**
https://www.brepolsonline.net/toc/apocra/2019/30

**Ausführliche Problembeschreibung**
Artikel haben Abstracts in zwei Sprachen, doch beide werden nicht erfasst oder es wird nur ein Abstract oder sogar nur eine römische Zahl als Abstract erfasst,

Harvester: Atypon, sowohl im Einzel- als auch Mutli-DL

**Comment by kdr154** [comment]
Bei mir sieht es gut aus.

**Comment by IxKo** [comment]
Beide Abstracts sind nun vorhanden, allerdings in einem Feld statt zwei, aber dies kann manuell angepasst werden.
