### ISSUE TITLE
ISSN 2198-0462 | Praktische Theologie | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1022]
Es gibt  zwar einen Translator "DeGruyter", der wird jedoch auch nach einem Update im Broweser und einen Neuladen nicht angeboten. Statt dessen Embedded Metadata. Leider nur im Singlemodus, so dass ein Multidownload nicht möglich ist. 
Sollte das System nicht erkennen, dass es sich hier um eine Zeitschrift handelt, die auf den Seiten von DeGruyter angeboten wird?

**Comment by socheres** [comment]
ist es generell so oder nur bei einer best. Zss.?

**Comment by kdr154** [comment]
Scheint mir generell so zu ein. Bei History of Modern Theology und Kierkegaard Studies Yearbook  ist es genauso.

**Comment by kdr154** [comment]
Der DeGruyter-Translator wird jetzt bei allen drei ZS angeboten und funktioniert auch.
