### ISSUE TITLE
ISSN 1467-9809 | Journal of Religious History | Normaler Artikel wird zur Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1025]
mit Try URL getestet.
Ein normaler Artikel wird zur Rezension:
https://onlinelibrary.wiley.com/toc/14679809/2019/43/3

![grafik](https://user-images.githubusercontent.com/29707105/85667830-4d96ee80-b6be-11ea-93f6-9647d6fadbc6.png)

Die Umsetzung:

![grafik](https://user-images.githubusercontent.com/29707105/85667948-6f907100-b6be-11ea-84c7-b4abc286133d.png)

**Comment by socheres** [comment]
@mtrojan-ub im Abstract gibt es eigentlich kein review pattern, wird aber trotzdem gematcht. https://github.com/ubtue/zotero-enhancement-maps/blob/9fb3cfd2b915dc7cc5482c5d5d7832124087cf70/zotero_harvester.conf#L1867

Converting item 1 [Journal of religious...] | https://onlinelibrary.wiley.com/doi/10.1111/1467-9809.12614 {3346052345206444383}
use online ISSN "1467-9809" with online PPN "300593295"
post-processed author first name = 'Miguel de', last name = 'Asúa', title = '', affix = ''
added GND number 133368289 for author Asúa, Miguel de (SWB lookup)
abstract matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12614,
	item_type: review,
	title: Draper, the “Conflict Thesis” and Secularising Politics in Late Nineteenth-Century Argentina,
	abstract_note: Despite appearances to the contrary, late nineteenth-century Buenos Aires (Argentina) seems to be a suitable scale model to explore the relationships between the “conflict thesis” and secularisation. John W. Draper's History of the Conflict between Religion and Science (1874) arrived in the country in the midst of political battles over the shape of the future relationships between the state and the majoritarian Catholic Church. In the decade between 1875 and 1885 variants of the “conflict thesis” were expounded, discussed, and used as rhetorical weapons in the battles over the issue of religious teaching in elementary schools. This article analyses the discussions over the “conflict thesis” between liberal secularists and Catholics in newspaper articles, public speeches, parliamentary debates, and other forms of public discourse during that period. Against the backdrop of a weak institutional church, a vigorous growth of nascent scientific institutions, and a cultural atmosphere permeated by positivism, the opposing parties argued about the “conflict thesis” while each reclaimed for itself the legitimacy of science. The episode permits a close look at how the intellectual leaders who conceived the project of a secularised state utilised science-based philosophies for purposes of political argument and ideological legitimation.,
	publication_title: Journal of Religious History,
	volume: 43,
	issue: 3,
	pages: 305-327,
	date: 2019-01-01,
	doi: 10.1111/1467-9809.12614,
	language: eng,
	issn: 1467-9809,
	superior_ppn: 300593295,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: Miguel de,
			last_name: Asúa,
			type: author,
			gnd_number: 133368289,
		},
	],
}
Generated record with hash 'F8F583F272C5C13F6EA2CD1295F69AFD24D3BBA7'

Conversion complete

**Comment by mtrojan-ub** [comment]
In der zotero_harvester.conf stimmt etwas mit dem regex nicht. In dem "alten" Permalink der oben verlinkt ist:
`zotero_review_regex       = "pp\."`

Die aktuelle Version:
`zotero_review_regex        = pp.`

Es erschließt sich mir zwar nicht wieso die Zeichenkette "pp." dazu führen soll dass etwas als Review eingestuft wird, aber aus Sicht des Suchmusters ist die alte Form richtig. In PCRE ist ein . ein Platzhalter für ein beliebiges Zeichen und muss daher escaped werden.

**Comment by kdr154** [comment]
gelöst.
