### ISSUE TITLE
ISSN 1467-9809 | Journal of Religious History | Escape character &

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1026]
In diesem Heft: https://onlinelibrary.wiley.com/toc/14679809/2019/43/3 zeigt sich auch wieder das Phänomen, dass das Zeichen "&" zu einem Fehler führt.
Die Vorlage:
![grafik](https://user-images.githubusercontent.com/29707105/85669133-d1050f80-b6bf-11ea-89f2-3081b04053c2.png)

Die Umsetzung:

![grafik](https://user-images.githubusercontent.com/29707105/85669234-ebd78400-b6bf-11ea-82c3-6c3909ed57dc.png)

**Comment by socheres** [comment]
@mtrojan-ub das Problem wurde schon behoben, oder?

**Comment by socheres** [comment]
Ok. Dann gibt @kdr154 Bescheid, wenn es soweit ist. Am Besten dann "ready for Testing" hinzufügen.

**Comment by kdr154** [comment]
Gefixt.
