### ISSUE TITLE
ISSN 2040-4867 | Journal of Church and State | Schlagwort

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1027]
Ein Editorial gibt es bei dieser Zeitschrift so gut wie nie und man könnte die Sache auch so stehen lassen. Trotzdem:
Hier wird für das Editorial ein Schlagwort vergeben:
https://academic.oup.com/jcs/issue/62/1

![grafik](https://user-images.githubusercontent.com/29707105/85679538-c8b1d200-b6c9-11ea-9ce9-54f05feb029d.png)

![grafik](https://user-images.githubusercontent.com/29707105/85679614-dbc4a200-b6c9-11ea-9b43-cedf83fce94b.png)

**Comment by socheres** [comment]
Das Problem tritt nicht mehr auf. Unten das Nu-Output. Daher schließe ich es.

Augmented metadata record: MetadataRecord {
	url: https://academic.oup.com/jcs/article/62/1/1/5735714,
	item_type: journalArticle,
	title: The Global Consequences of Catholic Clerical Sexual Abuse,
	abstract_note: The Catholic Church has failed to protect children from sexual abuse around the world. Its officials, for many reasons, have played a part in damaging the churc,
	publication_title: Journal of church and state : JCS,
	volume: 62,
	issue: 1,
	pages: 1-4,
	date: 2020-01-01,
	doi: 10.1093/jcs/csz087,
	language: eng,
	issn: 2040-4867,
	superior_ppn: 341338435,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Jo Renee,
			last_name: Formicola,
			type: author,
		},
	],
	custom_metadata: [
		{ LF,  },
	],
}
