### ISSUE TITLE
ISSN 1467-9418 | Reviews in religion and theology | Problem mit dem &

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1029]
Auch hier führt das & dazu, dass der darauf folgende Text nicht mehr erfasst wird. Bei allen Artikeln in 773 $t

![grafik](https://user-images.githubusercontent.com/29707105/85689733-2dbdf580-b6d3-11ea-96c4-9fc36443c8dd.png)

Hier wird der Titel der Zeitschrift erfasst, und der heißt in diesem Fall nun mal Reviews in Religion & Theology.
Ein Heft zum Beispiel: https://onlinelibrary.wiley.com/toc/14679418/2017/24/4

773 dient dazu, in Pica 4241 die Beziehung zur übergeordneten Einheit herzustellen. Ich könnte mir vorstellen, dass dieser Fehler bei der Dateneinspielung keine Rolle spielt, das die Beziehung zur übergeordneten Einheit über die PPN hergestellt wird. Und die steht in 773 $w

**Comment by kdr154** [comment]
Gelöst

**Comment by kdr154** [comment]
ready for zota

**Comment by socheres** [comment]
in ZEDER geändert "zota".
