### ISSUE TITLE
Berichts- und Erscheinungsjahr bei sog. online first 

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1031]
sehr gut. Leider gibt es bei dieser Zeitschrift auch die unglückliche Geschichte von Unterschieden bei Berichts- und Erscheinungsjahr. Oder ist schon entschieden worden, wie man da verfährt?

_Originally posted by @kdr154 in https://github.com/ubtue/DatenProbleme/issues/1002#issuecomment-650064977_

**Comment by socheres** [comment]
@kdr154 @IxKo @IxTheoKm bei den meisten Zss. ist das Berichts- und Erscheinungsjahr gleich. Wenn sie aber voneinander abweichen, ist das Berichtsjahr maßgebend. Siehe hier https://github.com/ubtue/DatenProbleme/issues/927#issuecomment-647600944 Es gibt aber noch Translatorprobleme, die noch nicht behoben sind.

**Comment by IxTheoKm** [comment]
Ist das eine Frage an uns? Abweichende Berichts- und Erscheinungsjahre gibt es in einigen Zeitschriften, nicht nur bei "First Published"-Artikeln.

Dazu folgende Info aus den Erfahrungen it Migrationen/Altdaten :
es gab bei Aufsätzen im IxTheo nur die Berichtsjahre, keine zusätzlichen Erscheinungsjahre. Daher wurde aus dem Berichtsjahr für die Migration das Erscheinungsjahr erzeugt, was in solchen Fällen natürlich falsch ist.

Für Nutzer ist das Berichtsjahr maßgeblich, darum läuft die Sortierung im IxTheo darüber.

Problematisch wird es ggf. bei der K10plus Dublettenprüfung, da das Erscheinungsjahr höchste Relevanz hat. Das hat bei der Migration zu vielen (unerkannten) Dubletten geführt. Bei Zeitschriften, die _immer_ oder _regelmäßig_ abweichende Berichts- und Erscheinungsjahre haben, sind für zota wahrscheinlich nicht geeignet, wenn man die Felder nicht maschinell auseinanderhalten kann.

**Comment by socheres** [comment]
bei Zeitschriften, die regelmäßig abweichende Berichts- und Erscheinungsjahre haben, könnte man sie maschinell auseinanderhalten. 
Z.B. in PICA
1100 2019
4070 $j2020 > $n ist nicht mehr erforderlich

**Comment by IxTheoKm** [comment]
Ja, in PICA müssen sie immer auseinander gehalten werden.

"Maschinell auseinander halten" habe ich wohl missverständlich formuliert: ich meinte, dass die _Verlagsdaten_ auch unterschiedliche Berichts- und Erscheinungsjahre (in unterschiedlichen Feldern?) mit Zotero hergeben müssen, dass man sie korrekt nach PICA 1100 und 4070 $j übertragen kann.

**Comment by kdr154** [comment]
Leider sind die Abweichungen oft nicht regelmäßig. Die Regel ist, dass ein Teil der Aufsätze in einem Jahr erschienen ist, ein anderer in einem anderen. 
Ein anderer, auch vorkommender Fall ist der, dass bei den ersten oder letzten Ausgaben im Jahr Beichts- und Erscheinungsjahr immer voneinander abweichen. 
Das muss man im Einzelfall entscheiden.

**Comment by IxKo** [comment]
Ich habe mir eben nochmal das K10plus-Handbuch für unselbständige Werke angeschaut (https://opus.k10plus.de/frontdoor/deliver/index/docId/415/file/K10plus_Unselbststaendige_Werke.pdf)
und frage mich, ob wir diese published online first Artikel überhaupt so berücksichtigen müssen.

Dort steht bei Feld **1100**: "Bei  uW  aus  Monografien  wird  hier  das  Erscheinungsjahr  der  Monografie  (bei  mehrteiligen 
Monografien  das Erscheinungsjahr  des  betreffenden  Teils)  in  Sortierform  und  bei  **uW  aus Zeitschriften  das Erscheinungsjahr  des  vorliegenden Hefts**  in  Sortierform  erfasst. Die  Vorlageform des Datums muss nicht im Unterfeld $n berücksichtigt werden. Spezifischere Angaben sind in Feld 4070 zu erfassen."

Und zum Unterfeld **$j in 4070** steht hier Folgendes:
"Bei uW aus Zeitschriften wird im Unterfeld $j das **Berichtsjahr** erfasst. Ein ggf. abweichendes Erscheinungsdatum des Zeitschriftenhefts oder -jahrgangs bleibt hier unberücksichtigt."

Demnach sind hier nur unterschiedliche Jahreszahlen anzugeben, wenn das **Heft** in dem folgenden Jahr erscheint (1100) als berichtet/angegeben (Berichtsjahr 4070 $j)

Trifft das denn so auf die Online-first-Artikel zu? Oder steht dazu noch irgendwo eine andere Regelung?

**Comment by kdr154** [comment]
Wenn man hier auch keine Unterscheidung treffen müsste bleibt das Problem insofern bestehen, als Zotero das Jahr des ersten Erscheinens abgreift und daraus das Berichtsjahr konstruiert. Was dann falsch ist, wenn sich beides unterscheidet. Eine Frage, ob man das so programmieren kann, dass es stimmt. Und das ist möglicherweise von Zeitschrift zu Zeitschrift unterschiedlich.

**Comment by IxTheoKm** [comment]
Zu dem was kdr154 geschrieben hat habe ich nichts zu ergänzen. Das ist leider in vielen Fällen so.

Was "first published" bzw. "online first article" betrifft, kenne ich mich mit Katalogisierung der Online-Publikationen nicht genug aus. Vielleicht gibt https://opus.k10plus.de/frontdoor/deliver/index/docId/428/file/K10plus_E-Books.pdf etwas her?
Evtl. weiß die Abteilung A&Mmehr.

**Comment by jriedl** [comment]
Da ja auch im KrimDok-Kontext sehr relevant: Unabhängig davon, welche Daten wir am Ende heranziehen, lassen sich die infrage stehenden Informationen scheinbar zumindest für die großen Verlage  recht elegant über eine DOI-Abfrage bestimmen:
`curl -LH 'Accept: application/rdf+xml;q=0.5, application/vnd.citationstyles.csl+json;q=1.0' 'https://doi.org/10.1080%2F08974454.2019.1582454'`: [berichtsjahre.txt](https://github.com/ubtue/DatenProbleme/files/4946015/berichtsjahre.txt)

**Comment by IxKo** [comment]
#1078
