### ISSUE TITLE
ISSN 1502-7244 | Scandinavian journal of the Old Testament | Ready for zota

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1032]
**URL**
https://www.tandfonline.com/loi/sold20

Kann in das zota-Verfahren aufgenommen werden.

**Comment by IxKo** [comment]
Ist in Zeder auf zota gesetzt. Sollen diese "Issues" dann geschlossen werden?

**Comment by socheres** [comment]
Ja, kann geschlossen werden.
