### ISSUE TITLE
ISSN 2074-7705 | Verbum et Ecclesia | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1033]
**URL**
https://verbumetecclesia.org.za/index.php/ve/article/view/1905

**Ausführliche Problembeschreibung**
Review Article wird nicht in 655 als Rezension getagt. (getestet mit Nu-Try URL)

**Offenbare Lösungen**
Der Titel gibt kein Muster her. Auf der Heft- und Artikel-Seite wird der Artikel jedoch mit Review Article ausgezeichnet.

**Comment by socheres** [comment]
für diese Anpassung muss ein neuer Translator geschrieben werden. Da von 2018 an nur einen einzigen Datensatz mit "Review Article" gab, würde ich hier pragmatischer vorgehen und den einen Artikel im WinIBW manuell als Rezension kennzeichnen. Können Sie bitte ein Kommentar in b_zot eintragen? Danke.

**Comment by IxKo** [comment]
Kommentar eingetragen
