### ISSUE TITLE
ISSN 1478-1913 | The Muslim World | irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1035]
**URL**
https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283

**Ausführliche Problembeschreibung**
Der Titel "Issue Information ‐ TOC" ist kein Artikel.

**Offenbare Lösungen**
Per Regex herausfiltern.

**Comment by socheres** [comment]
mit "Try URL" getestet.

Zotero Logger initialized!



Queued journal 'The Muslim World' | DIRECT @ https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283
set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms


Harvesting URL 1 [The Muslim World...] | https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283 {7640456268386469877}
Harvest successful




Converting item 1 [The Muslim World...] | https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283 {7640456268386469877}
use online ISSN "1478-1913" with online PPN "341340766"
Augmented metadata record: MetadataRecord {
	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283,
	item_type: journalArticle,
	title: Issue Information - TOC,
	publication_title: The Muslim World,
	volume: 110,
	issue: 2,
	pages: 127-128,
	date: 2020-01-01,
	doi: 10.1111/muwo.12283,
	language: eng,
	issn: 1478-1913,
	superior_ppn: 341340766,
	superior_type: 2,
	ssg: 1,
}
MARC field for 'https://onlinelibrary.wiley.com/doi/abs/10.1111/muwo.12283 matched exclusion filter (245a/^Issue Information/)
Conversion complete
