### ISSUE TITLE
ISSN 1475-5629 | Culture and religion | zota

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1036]
Die Zeitschrift kann ins zota-Verfahren.

**Comment by IxKo** [comment]
In Zeder ist die Zs nun auf zota gesetzt. Was passiert mit diesem "Issue" hier?

**Comment by socheres** [comment]
Ja, bitte schließen. Über "ready for zota" sind diese closed Issue durchsuchbar.
