### ISSUE TITLE
ISSN 0555-9308 | Zeitschrift für Pastoraltheologie | Translators

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1037]
**Bsp.-URL**
Heft: https://www.uni-muenster.de/Ejournals/index.php/zpth/issue/view/102
Artikel: https://www.uni-muenster.de/Ejournals/index.php/zpth/article/view/1467

**Ausführliche Problembeschreibung**
Mutli-DL funktioniert mit keinem angebotenem Translator:
- Open Journal Systems Multi-Wrapper
--> Ein Fehler ist aufgetreten beim Versuch, diesen Eintrag zu speichern. Siehe Problembehebung für Übersetzer für weitere Informationen.
- EquinoxPub 
--> Ein Fehler ist aufgetreten beim Versuch, diesen Eintrag zu speichern. Siehe Problembehebung für Übersetzer für weitere Informationen.

Single-DL:
- Open Journal Systems Multi-Wrapper
--> speichert Artikel als Website in Zotero
- EquinoxPub 
--> Ein Fehler ist aufgetreten beim Speichern mit EquinoxPub. Es wird versucht stattdessen Save as Webpage zu nutzen.
- Open Journal Systems
--> erfasst Abstracts, aber es fehlen der:die Autor:in, die Seitenangaben, das Datum, die Band- und Heftangabe, die ISSN, der Publikationsname
Titel beinhaltet zum Schluss immer den Zs-Namen: " | Zeitschrift für Pastoraltheologie (ZPTh)"
- COinS
--> Abstracts fehlen und falsches Jahr wird übertragen

Die Zs ist eine OJS-Zs aus Münster.
Wünschenswert wäre ein funktionierender Multi-DL.
Die Artikel besitzen einen URN, dieser befindet sich scheinbar nur im PDF, demnach kann er nicht maschinell abgegriffen werden?

**Comment by IxKo** [comment]
Da Hr. Faß darum bittet, bei Problemen mit den Verantwortlichen Kontakt aufzunehmen, würde mich interessieren, ob es mit dem Zotero-Verfahren möglich ist, den URN abzugreifen und im richtigen Feld zu katalogiseiren, wenn der URN bei den Artikeln im OJS eingebettet wäre,
Einen PI würde ich immer erfassen wollen.

**Comment by kdr154** [comment]
Ich schreibe gerade eine Mail an Herrn Unkenholz,

 

VG

Klaus

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: A. Ko. <notifications@github.com> 
Gesendet: Donnerstag, 2. Juli 2020 11:53
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 0555-9308 | Zeitschrift für Pastoraltheologie | Translators (#1037)

 

Da Hr. Faß darum bittet, bei Problemen mit den Verantwortlichen Kontakt aufzunehmen, würde mich interessieren, ob es mit dem Zotero-Verfahren möglich ist, den URN abzugreifen und im richtigen Feld zu katalogiseiren, wenn der URN bei den Artikeln im OJS eingebettet wäre,
Einen PI würde ich immer erfassen wollen.

**Comment by socheres** [comment]
hier ein Beispiel wie die embeded metadata aussehen muss,  damit wir die Daten abgreifen können:
view-source:https://ojs2.uni-tuebingen.de/ojs/index.php/jebs/article/view/265

alle OJS Seiten aus Müster haben keine eingebettete Metadaten:
view-source:https://www.uni-muenster.de/Ejournals/index.php/zpth/article/view/1448
view-source:https://www.uni-muenster.de/Ejournals/index.php/jcsw/article/view/2314

Außerdem fehlen oft die Seitenangaben

**Comment by IxKo** [comment]
Das heißt, die Metadaten müssen im Html im Header eingebettet sein mit den Tags <meta name=[DC-Metadatenbezeichnug]>?

**Comment by socheres** [comment]
Im Idealfall ja. Ansonsten ist der Aufwand zum Programmieren relativ hoch und nicht stabil.

**Comment by IxKo** [comment]
Eine Mail (7.7.) an Münster geschrieben und darum gebeten, alle Metadaten in den Html-Header zu verankern.

**Comment by thefass** [comment]
wenn aus Münster zeitnah keine Antwort kommt, bitte mich informieren. Dann hacke ich nach

**Comment by kdr154** [comment]
Kann man mit dem HTML nichts anfangen? Hier einer der Aufsätze aus der Zeitschrift Pastoraltheologie, von denen @socheres sagt, dass sie keine eingebetteten Metadaten haben:
Bei folgendem Aufsatz: https://www.uni-muenster.de/Ejournals/index.php/zpth/article/view/1448
ist in meinen Augen alles enthalten, was man braucht:

![grafik](https://user-images.githubusercontent.com/29707105/87904922-c0964980-ca5f-11ea-9e0c-529d95028c32.png)

**Comment by thefass** [comment]
Hatte nicht jemand von uns mit Münster Kontakt? vermutlich haben Sie schon nachgebessert

**Comment by kdr154** [comment]
Könnte sein. @IxKo hat detaillierte Beschreibung abgegeben, welche Inhalte wir gern hätten. 
Beim Multidownload bekomme ich immer noch die Eingangs beschriebenen Fehlermeldungen, im Einzeldownload mit den Translatoren Open Journal System und Embedded Metadata sehen die Daten in Zotero aber jetzt gut aus.

**Comment by IxKo** [comment]
Mit dem Multi-Translator Open Journal sehen die Daten gut aus. Der URN müsste, wenn man ihn wollte, aus dem PDF entnommen werden.
