### ISSUE TITLE
ISSN 2196-6265 | Jahrbuch für Christliche Sozialwissenschaften | Datumsangabe fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1039]
Mit dem neuen Translator wird das Datum der Publikation nicht abgegriffen. 
ISSN 2196-6265 Jahrbuch für Christliche Sozialwissenschaften
https://www.uni-muenster.de/Ejournals/index.php/jcsw/article/view/2498

![grafik](https://user-images.githubusercontent.com/29707105/86442933-c9bcb200-bd0e-11ea-8364-5dcca82fc60f.png)
In der Folge wird kein 1100 in der WinIBW erzeugt:
![grafik](https://user-images.githubusercontent.com/29707105/86443943-48feb580-bd10-11ea-8875-f2f1f6a54d24.png)

**Comment by socheres** [comment]
jetzt kommt das Datum mit. Bitte testen.

**Comment by socheres** [comment]
vor dem Testen immer Translator in Zotero Client und in Connector Addon aktualisieren.

**Comment by kdr154** [comment]
Ist mit dabei.
