### ISSUE TITLE
ISSN 1743-1301 | Palestine Exploration Quarterly | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1041]
Bei diesem Heft https://www.tandfonline.com/toc/ypeq20/152/2?nav=tocList 
werden die Rezensionen im zotkat-Verfahren nicht erkannt und bekommen statt dessen das Schlagwort Book Reviews:
https://www.tandfonline.com/doi/full/10.1080/00310328.2020.1769341

![grafik](https://user-images.githubusercontent.com/29707105/86567081-0f75b680-bf6b-11ea-9d1f-0c56a110221e.png)

**Comment by socheres** [comment]
weder im Multi- noch im Single-DL ist bei mir das "Tags"-Feld leer.  @kdr154 @IxKo Unabhängig davon müssen Rezensionen im Zotkat-Verfahren manuell gekennzeichnet werden. Nur bei der Theologischen Revue wird die Kategorie 1131 automatisch nach PiCA+ exportiert.

**Comment by kdr154** [comment]
Aber Books Reviews ist doch in der Vorlage nicht als Keyword definiert oder hinterlegt. Book Reviews steht über dem Titel. Ich nehme an das interpretiert das System als ein Keyword.

**Comment by socheres** [comment]
Ja. Wenn im HTML-Tag`<div class="tocHeading">` "Book Reviews" steht, wird das Tag "Book Reviews" automatisch erzeugt. Für Zotkat habe ich nun diese Funktion deaktiviert.

**Comment by kdr154** [comment]
Dann schließe ich
