### ISSUE TITLE
ISSN 1868-727x | Theologische Rundschau | Fehler beim Download

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1042]
Dieser Artikel https://www.mohrsiebeck.com/artikel/singularitaet-und-regulierung-101628thr-2020-0004?no_cache=1
verursacht einen Fehler beim Download der Artikel von diesem Heft: https://www.mohrsiebeck.com/zeitschrift/theologische-rundschau-thr?no_cache=1
Im Single und im Multimodus
Default Translator ist Mohr Siebeck. Das System greift dann zu COinS, bei dem die Daten fehlerhaft sind.
Als mögliche Fehlerquelle sehe ich den Fakt, dass dieser Artikel keinen Verfasser besitzt. Ein Test mit dem Download des Inhaltsverzeichnisses ergab, dass es auch hier zu einem Fehler kommt. Auch dieses besitzt keinen Verfasser.

**Comment by socheres** [comment]
Ja, richtig. Wegen fehlender Autornamen - Rezensent - im HTML-Tag kommt es zu diesem Fehler. In solchen Fällen kann man den Artikel nur mit Zauberstab oder Coins herunterladen und fehlende Felder manuell erfassen. Zur Info auch an @IxKo

**Comment by kdr154** [comment]
Dann schließe ich
