### ISSUE TITLE
Allgemein: Zeitschriftennamen

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#1043]
Beispiel: 2056-7731
https://www.tandfonline.com/doi/full/10.1080/0005576X.2019.1607199
Der Translator liefert "Baptist Quarterly"
Laut zotero_harvester.conf heißt die Zeitschrift: "Baptist quarterly : the journal of the Baptist Historical Society"

Die Zeitschriftentitel werden aktuell vom Translator übernommen, aber nicht so wie es in der zotero_harvester.conf steht.

@socheres: Können/Sollen die Zeitschriftennamen des Translators vom Harvester überschrieben werden?

**Comment by socheres** [comment]
> Können/Sollen die Zeitschriftennamen des Translators vom Harvester überschrieben werden?

@mtrojan-ub hat das irgendwelche Relevanz für den internen Vorgang im Harvester?

Die Verknüpfung der Zeitschriftentitel läuft ja über eppn `<datafield tag="773" ind1="0" ind2="8"><subfield code="i">In: </subfield><subfield code="t">Baptist Quarterly</subfield><subfield code="x">2056-7731</subfield><subfield code="w">(DE-627)82702598X</subfield>` und nicht über
`<datafield tag="JOU" ind1=" " ind2=" "><subfield code="a">Baptist quarterly : the journal of the Baptist Historical Society</subfield>`

**Comment by mtrojan-ub** [comment]
Für die aktuellen Crashes würde das das Problem beheben, aber es gibt auch eine alternative interne Möglichkeit das zu lösen.

Es geht hier aber natürlich auch darum welche Zeitschriftennamen konkret ans BSZ geliefert werden sollen => die aus der Conf oder die vom Translator.

**Comment by socheres** [comment]
> Es geht hier aber natürlich auch darum welche Zeitschriftennamen konkret ans BSZ geliefert werden sollen => die aus der Conf oder die vom Translator.
da die Verknüpfung wie gesagt via ePPPN läuft, ist es nicht so wichtig, aber der Titel aus Conf ist korrekter.

**Comment by mtrojan-ub** [comment]
wurde angepasst + getestet, ich schließe
