### ISSUE TITLE
ISSN 1476-6086 | Journal of Management, Spirituality & Religion | Fehler beim Pica Export Feld Ausgabe (Heft)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1044]
Bei dieser Zeitschrift wird das Zotero-Feld Ausgabe = Heftnummer nicht exportiert. Getestet mit verschiednene Heften der Zeitschrift.
Heft 4 von Bd. 17.2020: https://www.tandfonline.com/toc/rmsr20/17/4?nav=tocList
Ein Artikel in Zotero:
https://www.tandfonline.com/doi/full/10.1080/14766086.2020.1734063

![grafik](https://user-images.githubusercontent.com/29707105/86897814-34536080-c108-11ea-81ea-a3dffa048adb.png)

Das Feld Ausgabe ist enthalten mit dem Wert 4

Dieser fehlt nach dem Pica-Export:

![grafik](https://user-images.githubusercontent.com/29707105/86898137-9dd36f00-c108-11ea-83fb-9e7affc268f3.png)

**Comment by socheres** [comment]
Habe den PICA-Translator angepasst.
Hier das Ergebnis:
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2020$n[2020]\n1131 !106186019!\n1500 ger\n1505 $erda\n2051 10.17879/thrv-2020-2643\n3000 !082664773!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [F\u00f6rster, Hans] maschinell zugeordnet\n\n4000 Huebner, Sabine$dPapyri and the Social World of the New Testament\n4070 $v116$j2020$m3\n4241 Enthalten in!1687426953!\n4950 https://www.uni-muenster.de/Ejournals/index.php/thrv/article/view/2643$xH$4LF\n5056 1\n5520 \nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

**Comment by kdr154** [comment]
gelöst
