### ISSUE TITLE
ISSN 1549-6538 | The journal of religion | Front Matter

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1046]
Der Artikel Front Matter sollte entfernt werden:
https://www.journals.uchicago.edu/toc/jr/2020/100/3
https://www.journals.uchicago.edu/doi/abs/10.1086/710657
![grafik](https://user-images.githubusercontent.com/29707105/87302954-9b12b880-c512-11ea-8880-17621508a6e0.png)

**Comment by kdr154** [comment]
Ist immer noch drin:

![grafik](https://user-images.githubusercontent.com/29707105/87424538-64a17000-c5dc-11ea-8a9b-6cd6898c91fe.png)

**Comment by socheres** [comment]
Mit "Try Url" getestet.
```
MARC field for 'https://www.journals.uchicago.edu/doi/abs/10.1086/710657 matched exclusion filter (245a/(^(Front|Back) (M|m)atter)|(^Masthead)/)
Conversion complete
```

**Comment by kdr154** [comment]
Aditional config nicht gesetzt
