### ISSUE TITLE
ISSN 1467-8519 | Bioethics | Unnötiger Artikel 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1048]
Der Artikel "Issue Information" ist unnötig:
https://onlinelibrary.wiley.com/toc/14678519/2020/34/5
https://onlinelibrary.wiley.com/doi/10.1111/bioe.12630

![grafik](https://user-images.githubusercontent.com/29707105/87442418-8d356400-c5f4-11ea-9815-be617f696c64.png)

**Comment by socheres** [comment]
mit "Try URL" getestet.

MARC field for 'https://onlinelibrary.wiley.com/doi/10.1111/bioe.12630 matched exclusion filter (245a/^Issue Information/)
Conversion complete
