### ISSUE TITLE
ISSN 2056-6107 | Journal of religious and political practice | Erscheinen eingestellt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1049]
Diese Zeitschrift entfernen.  Hat mit 3.2018 ihr Erscheinen eingestellt und ist komplett im SWB erfasst.

**Comment by thefass** [comment]
@kdr154 Danke für die Info. Auf der Seite von T&F ist das letzte Heft 4.2018. In der ZDB ist aber kein Hinweis auf die Einstellung der Zss und auch auf der Seite von T&F finde ich das nicht. Woher kommt Ihre Info?

**Comment by thefass** [comment]
Sorry, auf der Seite von T&F doch ein Hinweis (wenn man die richtige Unterseite findet.
![Bildschirmfoto 2020-07-15 um 16 02 49](https://user-images.githubusercontent.com/14169098/87554708-c1705980-c6b4-11ea-9270-232ef8a0ab49.png)

@kdr154 bitte Frau Sch... bei uns informieren, dass sie die Zss in der ZDB/EZB abschließt

**Comment by kdr154** [comment]
Danke, war gerade dabei

**Comment by kdr154** [comment]
Die Korrektur wurde beantragt
