### ISSUE TITLE
Equinox ISSN 1757-2479 Editorial: Material Culture and Art in the Lodge Room Tag 520

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#105]
Hier wird in 520 ein Abstract aufgeführt, obwohl auf der Webseite keins angezeigt wird:
https://journals.equinoxpub.com/index.php/JRFF/article/view/36813
Bei anderen Artikeln ist sehr wohl eines vorhanden. Vgl.:
https://journals.equinoxpub.com/index.php/JRFF/article/view/27087
Bei wiederum Rezensionen steht im Abstract der Titel des rezensierten Werks erweitert um weitere Informationen wie Verlag, Jahrl, ISBN ...
Diese Information sollte im RDA Tag 787 stehen. Der Aufbau dieses Tags ist allerdings recht kompliziert und berührt darüber hinaus die generelle Frage, wie Rezensionen behandelt werden sollen

**Comment by mtrojan-ub** [comment]
Teil 1 hierzu (Abstract) ist bereits behoben, zu Teil 2 (allgemeine Behandlung von Rezensionen) fehlt ja noch die Definition, daher setze ich den Issue mal auf "blocked".

**Comment by shadeMe** [comment]
Ich glaube dies hier ist schon gelöst oder?

**Comment by kdr154** [comment]
ok
