### ISSUE TITLE
ISSN 2375-3242 | Church, Communication and Culture | Ansetzung eines Verfassernamens

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1050]
Bei diesem Artikel sollte die Ansetzung des Verfassers nach Möglichkeit so nicht bleiben:
https://www.tandfonline.com/toc/rchu20/5/1?nav=tocList
https://www.tandfonline.com/doi/full/10.1080/23753234.2020.1713020

![grafik](https://user-images.githubusercontent.com/29707105/87513277-c31c2c00-c678-11ea-859e-90a08b76ff14.png)

Sondern nach Möglichkeit entsprechend der Vorlage umgesetzt werden: The Editorial Team -> subfield code="a">The Editorial Team</subfield

**Comment by IxKo** [comment]
Zs ist bereits live, Problem gelöst.
