### ISSUE TITLE
ISSN 2175-5841 |Horizonte | Heft, Ausgabe, Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1051]
Hier fehlen sowohl im Single- als auch im Multidownload Bandnummer, Heftnummer und Abstract. Die Angabe zur Sprache ist auch problematisch.
Die Problematil mit den Seitenzahlen wurde bereits in #206 diskutiert und ist im Rahmen des Datenharvesting nicht zu lösen.
http://periodicos.pucminas.br/index.php/horizonte/issue/view/1067
http://periodicos.pucminas.br/index.php/horizonte/article/view/P.2175-5841.2018v16n51p1042

![grafik](https://user-images.githubusercontent.com/29707105/87526086-aab50d00-c68a-11ea-868e-409b09fbe6ac.png)

**Comment by socheres** [comment]
Welchen Translator haben Sie verwendet? Bei Sprachen bitte Mapping ergänzen.

**Comment by kdr154** [comment]
Im Multi den Multi-Wrapper, was anderes gab es nicht, im Single den Open Journal System.
Die Seite ist überarbeitet worden. Zuvor waren die Daten besser. Vieles steht auch jetzt im Quelltext. Es wird aber nicht erfasst.

**Comment by kdr154** [comment]
Es kommen mehrere Sprachen vor, por, spa, eng, möglicherweise noch weitere. Mehr als eine in der Mapping-Tabelle zu vergeben macht keinen Sinn, oder?

**Comment by socheres** [comment]
z.I. auch an @IxKo 
es gibt zwei mappings:

"ISSN_to_language_code.map" hier nur bei einsprachigen Zeitschriften.
"language_to_language_code.map"  vielleicht sinnvoll hier "es;en=spa" einzutragen?

> Fall Nr. 4 hat den Fehler verursacht.
> 
> > Mail vom 3.6.2020
> 
> 1. vorrangig wird die Sprache genommen, die in der Mapping aufgelistet
>    ist:https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map
> 2. wenn es keine Entsprechung in der "ISSN_to_language_code.map" gibt, dann wird der Wert im Zoterofeld "Sprache" mit der Mapping "language_to_language_code.map" abgeglichen und das PICA-konforme Sprachfeld ausgegeben.
> 3. Falls keine Entsprechung in "language_to_language_code.map" gibt, dann wird der ursprüngliche Wert im Zoterofeld "Sprache" ausgegeben.
> 4. Wenn es aber sowohl ein Key-Value-Paar in der
>    "ISSN_to_language_code.map" fehlt als auch das Zoterofeld "Sprache"
>    nicht belegt ist, kann der Datensatz nicht nach PICA exportiert
>    werden. Es gibt dann eine Fehlermeldung in Zotero. Um den Aufsatz
>    bearbeiten zu können, muss vorher die Mappingtabelle
>    "ISSN_to_language_code.map" um fehlenden Eintrag ergänzt werden. Default-Wert für Sprache gibt es nun nicht mehr.
https://github.com/ubtue/DatenProbleme/issues/1020#issuecomment-646645674

**Comment by socheres** [comment]
"ubtue_horizonte.js" wurde neu geschrieben und kann getestet werden.

**Comment by socheres** [comment]
bitte in ZEDER vermerken, dass die letzte Seitennummer manuell ergänzt werden muss.

**Comment by kdr154** [comment]
Sieht sowohl im Single-DL als auch im Multi-DL gut aus. 
Dieser Artikel http://periodicos.pucminas.br/index.php/horizonte/article/view/22838
verursacht vermutlich wegen der nicht vorhandenen Seitenzahl einen Fehler beim Download. Sowohl Single als auch beim Multi.
Das mit den Seitenzahlen war in Zeder bereits vermerkt.

**Comment by socheres** [comment]
> Sieht sowohl im Single-DL als auch im Multi-DL gut aus.
> Dieser Artikel http://periodicos.pucminas.br/index.php/horizonte/article/view/22838
> verursacht vermutlich wegen der nicht vorhandenen Seitenzahl einen Fehler beim Download. Sowohl Single als auch beim Multi.
Translator nochmal angepasst. Der Translator sollte jetzt keinen Fehler mehr verursachen.

**Comment by kdr154** [comment]
Perfekt.
