### ISSUE TITLE
ISSN 1475-5629 | Culture and religion | latest articles ZOTA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1052]
**URL**
https://doi.org/10.1080/14755610.2020.1787474
IxTheo#2020-07-15#8821EF42BF75EC197AD6AF21384F17756F5CC15B

**Ausführliche Problembeschreibung**
Dies ist ein Artikel, der heute live (zota) in den K10plus eingespielt wurde und der einzige zu der Zeitschrift.
Die Bandangabe und die Heftnummer ist gleich 0, da es ein "latest article" ist und noch in keinem Heft veröffentlicht wurde.

Ansonsten sieht er gut aus.
**Offenbare Lösungen**
Latest articles sollen unterdrückt werden.

**Comment by socheres** [comment]
@mtrojan-ub @ruschein werden Online-first-Artikel nicht ausgeschlossen? Also, auch bei "0"?

**Comment by ruschein** [comment]
Dazu ist mir nichts bekannt.  Ist es sichergestellt, dass man Online-first-Artikel eindeutig an Bandnummer 0 und Heftnummer 0 erkennen kann?

**Comment by socheres** [comment]
Aufsätze mit Bandnummer 0 und Heftnummer 0 sollen grundsätzlich ausgeschlossen werden. Ob alle Online-first-Artikel an "0"  eindeutig erkannt werden kann, kann ich leider nicht beantworten.

**Comment by mtrojan-ub** [comment]
Führende Nullen werden entfernt (also auch wenn Band oder Heftnummer nur aus '0' besteht), siehe https://github.com/ubtue/ub_tools/blob/485904e18607bfc1953f09008da744b2da04a096/cpp/lib/src/ZoteroHarvesterConversion.cc#L542

Ist danach sowohl Band als auch Heft leer wird es entfernt sofern es keine DOI gibt und skip_online_first_articles_unconditonally_ nicht konfiguriert ist, siehe https://github.com/ubtue/ub_tools/blob/485904e18607bfc1953f09008da744b2da04a096/cpp/lib/src/ZoteroHarvesterConversion.cc#L1069

**Comment by socheres** [comment]
Beim o.g. Beispiel wurde aber trotz dieser Regel mit "0" eingespielt. D.h. ein Bug im Harvester?

**Comment by mtrojan-ub** [comment]
Wie gesagt... Online First Datensätze werden per Definition nur entfernt bzw. übersprungen wenn es **keine** DOI gibt. Da in diesem Datensatz eine DOI vorhanden ist, wurde er per Definition trotzdem hochgeladen.

=> It's not a bug, it's a feature!

**Comment by mtrojan-ub** [comment]
Mir ist noch etwas aufgefallen:
https://github.com/ubtue/zotero-enhancement-maps/blob/59fcfc9504106bad4c41bafad4d85ea51f61c6da/zotero_harvester.conf#L35

Da dieses Setting hier TRUE ist dürfte er die DOI eigentlich nicht berücksichtigen. Ich prüfe das nochmal.

**Comment by mtrojan-ub** [comment]
Kann es bestätigen... Problem liegt im Code, aber nicht direkt im Harvester sondern in StringUtil::LeftTrim

**Comment by mtrojan-ub** [comment]
Der Fix wurde auf nu+ub28 eingespielt. Wenn ich jetzt "Try RSS" auf die Zeitschrift mache taucht der Artikel nicht mehr in der Ausgabedatei auf => ready for testing

**Comment by IxKo** [comment]
Wird auch bei Try URL herausgefiltert.
