### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | 13.2019, 3 ; 4 von 6 Artikel ZOTA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1053]
**URL**
https://link.springer.com/journal/11562/13/3
Bsp.-Hash vom Heft 3 (Band 13.2019)
IxTheo#2020-07-15#09447D9642681BCF98526AC3DA54D8766C066E3B

**Ausführliche Problembeschreibung**
Das Heft besitzt insgesamt 6 Artikel, die hätten erfasst werden müssen, live! eingespielt wurden aber nur 4.

**Comment by socheres** [comment]
@mtrojan-ub kannst du bitte im Log reinschauen, woran das liegen könnte?

**Comment by mtrojan-ub** [comment]
Im Log finde ich nichts auffälliges, das liegt wohl am RSS Feed:
https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=11562&channel-name=Contemporary+Islam

Diese Artikel sind nicht im Feed enthalten:
https://link.springer.com/article/10.1007/s11562-018-0431-0
https://link.springer.com/article/10.1007/s11562-018-0433-y

**Comment by socheres** [comment]
Heft 2. 2020 > alle 6 Artikel vollständig eingespielt https://link.springer.com/journal/11562/14/2
Heft 1. 2020 > alle 5 Artikel vollständig eingespielt  https://link.springer.com/journal/11562/14/1
Heft 3. 2019 > hier fehlen 2 Artikel
Da wir aber künftig immer aktuelle Titel automatisch erfassen werden, gehe ich davon aus, dass im Heft 3. 2020 alle Artikel enthalten sein werden. Außerdem wurden die Aufsätze dieser Zeitschrift vor 2019 nur noch selektiv erfasst, daher bitte @IxKo 2 fehlende Artikel mit zotkat erfassen und Issue schließen.

**Comment by IxKo** [comment]
erledigt
