### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | Berichtsjahr vs Erscheinungsjahr ZOTA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1054]
**URL**
https://doi.org/10.1007/s11562-019-00443-w
IxTheo#2020-07-15#8280B465F6AFD7BED3BE98598701EE19430EBF30
**Ausführliche Problembeschreibung**
Wieder die Problematik mit abweichenden Berichts- und Erscheinungsjahren bei manchen Artikeln der Zeitschrift. (siehe #1002)

**Comment by IxKo** [comment]
https://github.com/ubtue/DatenProbleme/issues/1002#issuecomment-659313033

**Comment by socheres** [comment]
> Ich habe mir eben nochmal das K10plus-Handbuch für unselbständige Werke angeschaut (https://opus.k10plus.de/frontdoor/deliver/index/docId/415/file/K10plus_Unselbststaendige_Werke.pdf)
> und frage mich, ob wir diese published online first Artikel überhaupt so berücksichtigen müssen.
> 
> Dort steht bei Feld **1100**: "Bei uW aus Monografien wird hier das Erscheinungsjahr der Monografie (bei mehrteiligen
> Monografien das Erscheinungsjahr des betreffenden Teils) in Sortierform und bei **uW aus Zeitschriften das Erscheinungsjahr des vorliegenden Hefts** in Sortierform erfasst. Die Vorlageform des Datums muss nicht im Unterfeld $n berücksichtigt werden. Spezifischere Angaben sind in Feld 4070 zu erfassen."
> 
> Und zum Unterfeld **$j in 4070** steht hier Folgendes:
> "Bei uW aus Zeitschriften wird im Unterfeld $j das **Berichtsjahr** erfasst. Ein ggf. abweichendes Erscheinungsdatum des Zeitschriftenhefts oder -jahrgangs bleibt hier unberücksichtigt."
> 
> Demnach sind hier nur unterschiedliche Jahreszahlen anzugeben, wenn das **Heft** in dem folgenden Jahr erscheint (1100) als berichtet/angegeben (Berichtsjahr 4070 $j)
> 
> Trifft das denn so auf die Online-first-Artikel zu? Ist bei first published nicht gemeint, dass es bereits vorher schon online erschien, aber eben noch nicht online in einem Heft?
> Oder steht zu den first-published-Fällen noch irgendwo eine andere Regelung?
> (@IxTheoKm @kdr154)

#1031
das heisst 1100 ist abhängig des Erscheindungsdatums des üW - Heft - anzugeben. Dann ist in diesem Fall `1100 2020` doch richtig, oder? @IxKo wenn ja, bitte Issue schließen.

**Comment by IxKo** [comment]
@socheres 
Scheinbar nicht. Die modernen Online-Publikaitonen wurden im Handbuch aller Wahrscheinlichkeit nach nicht berücksichtigt.
IxTheoKm und kdr154 sehen bei den Online-Artikeln eine Unterscheidung von Erscheinungs- und Berichtsjahr, die es zu berücksichtigen gilt.

**Comment by kdr154** [comment]
Meine Einwände gelten für den Fall, dass das Berichtsjahr aus dem Erscheinungsjahr konstruiert wird, Aber hier scheint mir alles richtig zu sein:
Zitat: Bei uW aus Zeitschriften wird im Unterfeld $j das Berichtsjahr erfasst. Ein ggf. abweichendes Erscheinungsdatum des Zeitschriftenhefts oder -jahrgangs bleibt hier unberücksichtigt
Das ist hier der Fall.

**Comment by IxKo** [comment]
@kdr154 Wird denn nicht das abweichende angegebene Veröffentlichungsjahr berücksichtigt?
![grafik](https://user-images.githubusercontent.com/57000004/87770970-fbaa3a00-c81f-11ea-90a8-688dce183d94.png)

**Comment by kdr154** [comment]
Doch, sollte es. Ich habe mein Augenmerk auf 4070 gerichtet. Laut IxTheoKm in #1031 führt es zu unerkannten Dubletten bei der Dublettenprüfung, wenn das Erscheinungsjahr aus dem Berichtjahr konstruiert wird. Deshalb sollte in diesen Fall in 1100 2019 stehen. Im Grunde genommen bietet der Quelltext in diesem Fall die Möglichkeit, beides zu erfassen. Und im vollautomatischen Verfahren geht man ja nicht über Zotero:
Etwa hier:

![grafik](https://user-images.githubusercontent.com/29707105/87772727-6a889280-c822-11ea-9f04-3042373a3eaa.png)

Aber das ist Sache der IT.
Der Fall bleibt also problematisch.

**Comment by IxKo** [comment]
socherers meinte jedoch, das Problem sei, dass Zotero hierfür kein Feld anbietet und man müsse die Information in ein Feld schreiben, dass normalerweise nicht dafür ausgelegt ist.
Das vollautomatische Verfahren ist doch ein Zoteroverfahren, demnach muss hier irgendwo Zotero enthalten sein. 

Ein Vorschlag an die ITler:innen:
Es wäre toll, für "IT-Laien" eine vereinfachtdargestellte Übersicht zu beiden Verfahren zu erhalten und wo unterschiedliche Schnittstellen (TRanslator, Harvester, Skript etc.) greifen. Könnte so etwas mal erarbeitet werden? Es ist sicher auch für Personen interessant, die nicht mit dem Verfahren arbeiten.

**Comment by IxTheoKm** [comment]
@IxKo Den Vorschlag kann ich nur unterschreiben!
Ich habe schon lange den Überblick verloren - auch beim halbautomatischen Verfahren - an welcher Stelle wer/was womit operiert!

**Comment by kdr154** [comment]
Diesem Vorschlag kann ich mich auch nur anschließen.

**Comment by socheres** [comment]
summa summarum:
in diesem Fall ist das Jahr 2020 im Pica-Feld 1100 und 4070 $j korrekt.
Bei allen anderen Fällen, wo das Erscheinungsjahr des Aufsatzes von dem des Heftes abweicht, wird der Translator entsprechend angepasst, sodass überall im Datumsfeld das Jahr des Veröffentlichungsdatums einer Ausgabe/eines
Heftes steht. @IxTheoKm @kdr154 @IxKo @mtrojan-ub @jriedl Alle einverstanden?

**Comment by kdr154** [comment]
Ok.

**Comment by IxTheoKm** [comment]
"_in diesem Fall ist das Jahr 2020 im Pica-Feld 1100 und 4070 $j korrekt_" verstehe ich nicht ganz.

Dort steht doch "14 ... (2020)" und "Published: 31 August 2019".

Das bedeutet für mich:
1100 2019
4070 $j2020

**Comment by kdr154** [comment]
@socheres zitiert oben aus dem K10plus-Handbuch für unselbständige Werke zu 1100 wie folgt:

Dort steht bei **Feld 1100**: "Bei uW aus Monografien wird hier das Erscheinungsjahr der Monografie (bei mehrteiligen
Monografien das Erscheinungsjahr des betreffenden Teils) in Sortierform und **bei uW aus Zeitschriften das Erscheinungsjahr des vorliegenden Hefts in Sortierform erfasst. Die Vorlageform des Da**tums muss nicht im Unterfeld $n berücksichtigt werden. Spezifischere Angaben sind in Feld 4070 zu erfassen."**

Das hieße in diesem Fall:
1100 2020
4070 $j2020

@IxKo vermutet (siehe ebenfalls oben), dass die modernen Online-Publikationen in diesem Handbuch noch nicht berücksichtigt sein könnten.

**Comment by IxTheoKm** [comment]
Das Handbuch meint einen anderen Fall!
Es geht nur darum, dass im übergeordneten Werk ggf. eine Vorlageform in 1100 $n erfasst sein kann, die nicht genauso in den unselbständigen Werken stehen muss. Dort reicht die Sortierform.

Beispiel:
Übergeordnetes Werk 
1100 2020$n[2020]
Die Klammerung in der Vorlageform erfolgt, weil das Erscheinungsjahr ermittelt wurde (z.B. aus einem Copyright-Jahr oder aus einem Berichtsjahr eines Zeitschriftenbandes)

In den damit verknüpften unselbständigen Werken muss aber nur die Sortierform stehen, also nur
1100 2020
(nicht 1100 2020$n[2020]) 


Außerdem wurden früher vom Berichtsjahr abweichende Erscheinungsjahre in 4070 $y angegeben, was jetzt auch nicht mehr gemacht wird.
Bsp.:
Ein Band 1 mit Berichtsjahr 2020 erscheint 2019:

Aufsatzerfassung früher
1100 **2019**
4070 $v1$j**2020**$p15-20$y1.**2020 (2019)**, Seite 15-20

Heute nur noch
1100 **2019**
4070 $v1$j**2020**$p15-20

**Die Unterscheidung zwischen Erscheinungsjahr in 1100 und Berichtsjahr in 4070 $j erfolgt aber weiterhin!**

**Comment by kdr154** [comment]
Aber in dem Zitat aus dem Handbuch geht es doch um uW unselbständige Werke und nicht um das übergeordnete Werk.

**Comment by IxTheoKm** [comment]
Ja, meine Beispiele listen zuerst die Erfassung des übergeordneten Werks und danach die damit verknüpften untergeordneten Werke auf. 
Die Erfassung von 1100 weicht in Bezug auf $n im übergeordneten Werk von 1100 im untergeordneten Werk ab.

**Comment by socheres** [comment]
@mtrojan-ub @jriedl in RIS können wir die beiden Jahre (Publikationsjahr des Artikels und des Heftes = Berichtsjahr) auseinanderhalten. Für Publikationsjahr des Artikels definieren wir ein freies Zotero-Feld oder geben als Keywords aus, das aber beim Output wieder entfernt wird. Ähnlich wie bei Keywords "Book Reviews".
![image](https://user-images.githubusercontent.com/1545743/89274851-c71ce780-d641-11ea-8f10-4471b97cdbe8.png)

**Comment by socheres** [comment]
Hier noch zwei Links zum Issue:
https://link.springer.com/article/10.1007/s006050200042
https://journals.sagepub.com/page/help/online-first

**Comment by socheres** [comment]
@jriedl https://github.com/socheres/Zoterobearbeitung/blob/master/zotero_master/translators/SAGE%20Journals.js (für Zotkat) bekomme ich die RIS-Daten via ZU.doPost zurück.

**Comment by IxKo** [comment]
#1078
