### ISSUE TITLE
ISSN 1478-1913 | The Muslim world | zota GND-Verküpfungen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1055]
Bei der live Einspielung werden die GND-Verknüpfungen (Verfasser, Rezension) nicht umgesetzt:
Vgl PPN 1724925342

![grafik](https://user-images.githubusercontent.com/29707105/87640438-047b0d00-c747-11ea-9e1b-1849b07d3b0c.png)

Das ist ein generelles Porblem. Z. B. auch hier:
PPN 1724925164

**Comment by socheres** [comment]
die PPN-Verknüpfung passiert erst ein Tag später nach dem sog. Relatedurchlauf.

**Comment by socheres** [comment]
"f abl zota aee 2020-07-16" alle Datensätze mit GND-IDs wurden mit PPN verknüpft, daher schließe ich.
