### ISSUE TITLE
ISSN 1478-1913 | The Muslim world | Rezension Verknüpfung GND-Satz ZOTA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1056]
**URL**
https://doi.org/10.1111/muwo.12330
IxTheo#2020-07-15#0275AFC498A6978F06839194D2943D517E70FBCE
**Ausführliche Problembeschreibung**
Die Rezension wird erkannt, jedoch wird es im live-Betrieb nicht mit dem Normdatensatz verknüpft, stattdessen sieht es im K10plus so aus: 1131 $7gnd4049712-4

**Offenbare Lösungen**
Klärung mit BSZ. sodass unsere gelieferten Daten es korrekt verknüpfen und es dann so aussieht: 1131 !106186019!
Meine Vermutung ist, dass doch alle Nummern in das Marc-Feld 655 müssen, wie in diesem Issue angesprochen #601 

siehe auch #1055

**Comment by socheres** [comment]
die PPN-Verknüpfung passiert erst ein Tag später nach dem sog. Relatedurchlauf.

**Comment by socheres** [comment]
"f abl zota aee 2020-07-16" alle Datensätze mit GND-IDs wurden mit PPN verknüpft, daher schließe ich.
