### ISSUE TITLE
Muslim World und Contemporary Islam Prio 2 zota

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1058]
Beides sind Prio 2-Zeitschriften.
Zeder umstellen, Lokalsatz an die Gesamtaufnahme anhängen, oder beides nochnlassen, da die Einspielung fehlerhaft ist?

**Comment by kdr154** [comment]
Lokalsatz ergänzt, Zeder aktualisiert

**Comment by socheres** [comment]
hierzu gab es noch keine Entscheidung, außerdem sind die Daten soweit gut, daher bitte die Änderung in ZEDER rückgängig machen.
