### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | Pseudo-Abstract ZOTA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1059]
**URL**
https://doi.org/10.1007/s11562-019-00438-7
IxTheo#2020-07-15#624521BA3871C1DCA477F1587C8EB57190F0781C

**Ausführliche Problembeschreibung**
Bei dieser Rezension wurde als Abstract (4207) der Text "null" eingespielt.
![grafik](https://user-images.githubusercontent.com/57000004/87763562-4a9ea200-c815-11ea-9dd9-ba8c27b391dc.png)

**Comment by kdr154** [comment]
Ist auch bei zotkat so:

![grafik](https://user-images.githubusercontent.com/29707105/87764108-1f688280-c816-11ea-8922-502a1b6c860a.png)

**Comment by socheres** [comment]
@mtrojan-ub an welcher Stelle (Translator/Harvester) soll das Problem behoben werden?

**Comment by mtrojan-ub** [comment]
Wenn in der Zusammenfassung in Zotero "null" als Zeichenkette auftaucht, dann eindeutig im Translator.

**Comment by socheres** [comment]
@mtrojan-ub nach commit bitte auf "ready for Testing" setzen.

**Comment by IxKo** [comment]
Nu momentan nicht erreichbar (Internal Server Error)

**Comment by mtrojan-ub** [comment]
Ist wieder erreichbar, hing mit einem Problem in der zotero_harvester.conf zusammen

**Comment by IxKo** [comment]
Mit Try RSS und TRy URL (https://doi.org/10.1007/s11562-019-00438-7) wird hier noch immer "null" ausgegeben:

![grafik](https://user-images.githubusercontent.com/57000004/92243010-051b5e80-eec1-11ea-93ff-ddb32d4b961e.png)

**Comment by IxKo** [comment]
Beim zotkat-Verfahren mit Single-DL Springer Link ist es auch noch. Dieses könnte jedoch auch manuell entfernt werden.

**Comment by socheres** [comment]
- [ ] nach Nu-Update nochmal testen

**Comment by IxKo** [comment]
War das Nu-Update schon?
"null" steht immer noch in 520

**Comment by mtrojan-ub** [comment]
Der Docker Container auf nu wurde am 26.09. zuletzt aktualisiert. Die darin enthaltenen Translators sind vom 3.9. Seitdem wurden uns keine neuen Translators zur Verfügung gestellt. Ich nehme an das @socheres warten will bis der neue benu-Testserver zur Verfügung steht, auf dem seine Translators direkt eingebunden sind (in ca. 1-2 Wochen).

**Comment by IxKo** [comment]
Nu-Test behoben
