### ISSUE TITLE
Allgemein Keywords Tag 650

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#106]
Keywords kommen in 650
650 hat folgenden Aufbau:
650 ind1 ind2
$a
$2

In $a steht das Keyword 
in $2 die Quelle

hat man keine Informationen zur Quelle, erhält ind2 den Wert 4, ind1 bleibt leer
In $a steht das Keyword 
$2 entfällt
Zitat Marc21 Doku der LOC:
$2 - Source of heading or term (NR)
    MARC code that identifies the source list from which the subject added entry was assigned. It is used only when the second indicator position contains value 7 (Source specified in subfield $2). 

Beispiel:
```
<datafield tag="650" ind1=" " ind2="4">
<subfield code="a">Fraternalism</subfield>
</datafield>
```

Besitzt man Informationen zur Quelle, wie in der SSOAR Daten, erhält ind2 den Wert 7, ind1 bleibt leer

Beispiel:
```
<datafield tag="650" ind1=" " ind2="7">
<subfield code="a">Umweltrecht</subfield>
<subfield code="2">thesoz</subfield>

```
In unserem Projekt bin ich bis jetzt noch auf keinen Fall getroffen, bei dem für ein Keyword eine Quelle angegeben wurde. Folglich muss in ind2 der Wert 4 erscheinen.

Sollte doch einmal eine Quelle in den Daten erscheinen, muss dort eben der Wert 7 stehen.

**Comment by mtrojan-ub** [comment]
Der Indikator 4 sollte jetzt immer korrekt gesetzt werden. 650$2 wird von uns aktuell nie gesetzt, bzw. falls wir das setzen sollen bräuchten wir mehr Informationen welche Werte dort in welchen Fällen konkret gesetzt werden müssen.

**Comment by kdr154** [comment]
Sieht gut aus - gelöst
