### ISSUE TITLE
ISSN 2196-8020 | Kerygma und Dogma | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1061]
Beim Multidownload wird das Abstract nicht mit übertragen.
Beim Einzeldownload steht am Beginn der Begriff "Summary". Kann entfernt werden. Der Begriff steht als Überschrift über dem eigentlichen Abstract:
Diesselbe Problemtik wie in #1060. Nur dass es hier nicht Zusammenfassung sondern Summary heißt. Etwa hier:
https://www.vr-elibrary.de/doi/10.13109/kedo.2020.66.2.97

![grafik](https://user-images.githubusercontent.com/29707105/87912179-3228c480-ca6d-11ea-94fd-9181fc6fea1f.png)

**Comment by kdr154** [comment]
Wie in 1060. Summary ist noch da. Auch sonst alles analog.

**Comment by socheres** [comment]
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2020$n[2020]\n1500 ger\n1505 $erda\n2051 10.13109/kedo.2020.66.2.97\n3000 !080714676!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [S\u00e4nger, Dieter] maschinell zugeordnet\n\n4000 Ekklesiale Gemeinschaft und eucharistisches Handeln\n4070 $v66$j2020$a2$p97-117\n4207 After probing the particular meaning of the words and phrases denoting, or referring to, the Eucharist in the New Testament and non-canonical early Christian writings, this article emphasizes the christological context or foundation for the ethical and social dimension of the eucharistic meal (Acts: breaking bread), which, according to Paul and Luke, is intended in part to put forward the participants\u2019 Koinonia and the communion (fellowship, solidarity, and brotherhood) between the members of the Christian congregation.\n4241 Enthalten in!55757076X!\n4950 https://www.vr-elibrary.de/doi/10.13109/kedo.2020.66.2.97$xH\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

**Comment by kdr154** [comment]
ok!
