### ISSUE TITLE
ISSN 2196-8020 | Kerygma und Dogma | Tabulatoren im Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1062]
Wenn man die Artikel in Singledownloadverfahren herunterläd, enthalten die Abstracts bei dieser Zeitschrift viele Tabulatoren. Wenn man es per copy & past überträgt ist dies nicht der Fall. Diese führen beim Upload zu einem Fehler, so dass die Datei in der WinIBW nicht gespeichert werden kann.  Hier:
https://www.vr-elibrary.de/doi/10.13109/kedo.2020.66.2.97
 sieht es so aus, wenn man es sich in Word anschaut:

![grafik](https://user-images.githubusercontent.com/29707105/87913496-85037b80-ca6f-11ea-98d2-7003ec2044d6.png)

Kann man die entfernen?

**Comment by kdr154** [comment]
Wenn man den Atypon-Translator nimmt, sind die Tabulatoren weiterhin enthalten. Beim Embedded Metadata nicht. Der kommt aber wegen des Fehlens der elementaren Elemente Ausgabe, Band, Seiten und auch der fehlenden ISSN, im Grunde genommen nicht in Frage.

**Comment by socheres** [comment]
Tabulatoren werden beim Export des obigen Metadatums entfernt. Ihre Pica-Skripte sind alle aktuell, daher ist es merkwürdig, dass bei mir alles richtig rüberkommt und bei Ihnen nicht. @IxKo Können Sie bitte auch noch testen?

> application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2020$n[2020]\n1500 ger\n1505 $erda\n2051 10.13109/kedo.2020.66.2.97\n3000 !080714676!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [S\u00e4nger, Dieter] maschinell zugeordnet\n\n4000 Ekklesiale Gemeinschaft und eucharistisches Handeln\n4070 $v66$j2020$a2$p97-117\n4207 After probing the particular meaning of the words and phrases denoting, or referring to, the Eucharist in the New Testament and non-canonical early Christian writings, this article emphasizes the christological context or foundation for the ethical and social dimension of the eucharistic meal (Acts: breaking bread), which, according to Paul and Luke, is intended in part to put forward the participants\u2019 Koinonia and the communion (fellowship, solidarity, and brotherhood) between the members of the Christian congregation.\n4241 Enthalten in!55757076X!\n4950 https://www.vr-elibrary.de/doi/10.13109/kedo.2020.66.2.97$xH\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

**Comment by IxKo** [comment]
Beim Single-DL mit dem Atypon Journals Translator habe ich keine Tabulatoren im Abstract.

**Comment by kdr154** [comment]
Das sieht bei mir jetzt gut aus. Auch der Begriff "Summary" wird beim Export entfernt, im Zotero-Client ist es aber vorhanden.

**Comment by socheres** [comment]
ja, wie gesagt. Die Überschrift "Summary" wird exportseitig behoben und nicht importseitig. Bitte schließen.

**Comment by kdr154** [comment]
Wo wie gesagt, hier ist von Tabulatoren die Rede
