### ISSUE TITLE
ISSN 2665-9484 | Trajecta | ISSN, Sprache ..

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1063]
https://www.ingentaconnect.com/content/aup/traj/2019/00000028/00000002
Ein Multi-DL wird nicht angeboten.
Beim Single-DL liefert der Translator IngentaConnect keine ISSN und keine Sprache.
Zudem steht zu Beginn der Zusammenfassung überflüssgerweise der Begriff Abstract:

https://www.ingentaconnect.com/contentone/aup/traj/2019/00000028/00000002/art00001

![grafik](https://user-images.githubusercontent.com/29707105/88067256-0e4da780-cb6f-11ea-9ee1-789132a01d16.png)

**Comment by socheres** [comment]
Translator lokal angepasst. ISSN kommen mit. Sprach-Mapping muss entsprechend noch ergänzt werden.

**Comment by socheres** [comment]
Bitte im Single-DL bearbeiten.

**Comment by kdr154** [comment]
ISSN jetzt dabei. Sprachmapping schwierig, da mehrsprachig.  Der getestete Artikel beispielsweise ist auf niederländisch verfasst, andere auf Englisch. Weitere Sprachen sind denkbar. 
Das Wort "Abstract" steht immer noch am Anfang der Zusammenfassung.

**Comment by socheres** [comment]
Das Wort "Abstract" wird beim Export entfernt. Da die Sprache mehrsprachig ist, muss sie in Zotero-Feld "Sprache" manuell erfasst werden. Bitte schließen.

**Comment by kdr154** [comment]
Schließe
