### ISSUE TITLE
ISSN 1572-8447 | Ethical theory and moral practice | Fehler beim Multi-DL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1064]
https://link.springer.com/journal/10677/23/2?utm_source=toc&utm_medium=email&utm_campaign=toc_10677_23_2&utm_content=etoc_springer_20200721
Das ist bereits die zweite Springer-ZS heute, bei der ein Multi-DL mit dem Translator SpringerLink nicht möglich ist. Auch nach Aktualisieren erscheint die Meldung: es ist ein Fehler aufgetreten beim Versuch ...

**Comment by socheres** [comment]
bei mir klappt der Muliti-DL. @IxKo Können Sie auch mal testen?

**Comment by kdr154** [comment]
Mujltidownload lief jetzt problemlos durch. Ich vermute den Fehler woanders. Mal klappt es, mal nicht. Eine Kollegin hatte dasselbe Problem. Ein Update, schließen, neu starten konnte das Problem beheben. Bei der nächsten Springer-Zeitschrift war es wieder da.

**Comment by IxKo** [comment]
Bei mir funktioniert es gerade nicht.
Es öffnet sich die Auswahl-Liste der Artikel, dann bestätige ich, dann erscheint "Ein Fehler ist aufgetreten" und danach öffnet sich die Artikelliste wieder und wenn ich dann bestätige, verschwindet das Fenster, es passiert jedoch nichts.

**Comment by kdr154** [comment]
Ärgerlich!

**Comment by socheres** [comment]
Merkwürdig. Ich kann alle Aufsätze im Multi herunterladen. Springer Link Translator von IxKo ist auch aktuell. Fehlerursache unbekannt.

**Comment by kdr154** [comment]
Lief gerade durch
