### ISSUE TITLE
ISSN 0953-9468 | Studies in Christian Ethics | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1066]
https://journals.sagepub.com/toc/scea/33/3
Im Multi-DL steht der Translator Sage Journals nicht zur Verfügung, im Single-DL dagegen ist er an erster Stelle. Was bedeutet, dass man beim Multi-DL die Keywords manuell ergänzen müsste, während sie im Single-DL enthaltens sind.
Sprache fehlt beim Multi-DL auch, aber das kann über die Mapping-Tabelle abgefangen werden.

**Comment by socheres** [comment]
bitte im Single-DL bearbeiten. Bitte schließen.

**Comment by kdr154** [comment]
Ok
