### ISSUE TITLE
ISSN 0953-9468 | Studies in Christian Ethics | Berichtsjahr vs Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1067]
https://journals.sagepub.com/toc/scea/33/3
Hier führt der Unterschied zwischen Berichtjahr und Publikationsjahr wieder zu einer falschen Zuordung und Sortierung. Abgegriffen wird immer das Publikationsjahr. Egal ob beim Multi-DL, wo der Atyon-Translator verwendet wird, oder beim Single-DL, wo der Sage-Translator verwendet wird.
So wird dieser Artikel: https://journals.sagepub.com/doi/full/10.1177/0953946818822277 
dem Band 33,2019,3 zugeordnet
dieser https://journals.sagepub.com/doi/full/10.1177/0953946818822276
sogar dem Band 33.2018,3
Richtig wäre aber in beiden Fällen 33.2020,3

**Comment by socheres** [comment]
Translator lokal angepasst. Translators aktualisieren.

**Comment by kdr154** [comment]
Jetzt passt es.
