### ISSUE TITLE
ISSN 1467-9647 | Teaching Theology & Religion | Schlagwort Book Review

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1068]
Hier wird bei den Rezensionen das Schlagwort BOOK REVIEW, BOOK REVIEW vergeben:
https://onlinelibrary.wiley.com/toc/14679647/2020/23/2?campaign=woletoc
https://onlinelibrary.wiley.com/doi/10.1111/teth.12546

![grafik](https://user-images.githubusercontent.com/29707105/88149842-e870e300-cc00-11ea-965b-07fc0d1151ad.png)

![grafik](https://user-images.githubusercontent.com/29707105/88149911-fe7ea380-cc00-11ea-8261-033ca2401af1.png)

**Comment by socheres** [comment]
Ihr Translator "Wiley Online Library.js" ist für Zotero-AUTO optimiert, daher habe ich den Translator lokal angepasst.

**Comment by kdr154** [comment]
Schlagwort nicht mehr vorhanden
