### ISSUE TITLE
ISSN 0020-9643 | Interpretation | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1069]
Hier werden die Keywords nicht erfasst. Sage-ZS: Multi Atypon, Single Sage Translator. Bearbeite deshalb im Single-Verfahren. Sie fehlen aber in beiden Verfahren.
https://journals.sagepub.com/toc/intc/74/3
https://journals.sagepub.com/doi/full/10.1177/0020964320921962

**Comment by socheres** [comment]
Translator lokal angepasst. Im Einzel-DL kommen die Keywords mit. Bitte im Single-Verfahren erfassen.

**Comment by kdr154** [comment]
Danke, passt.

**Comment by kdr154** [comment]
Dort, wo es keine Keywords gibt, kommt es jetzt zu einem Fehler bei dem Sage-Translator. Statt dessen wird Embedded Metadata genommen. Embedded Metadata überträgt keine ISSN.
Zumindest bei den ersten beiden nach den Artikeln, die Keywords besitzen:
https://journals.sagepub.com/doi/full/10.1177/0020964320921967
https://journals.sagepub.com/doi/full/10.1177/0020964320921968

**Comment by socheres** [comment]
der Fehler wurde durch fehlendem Abstract verursacht.

**Comment by kdr154** [comment]
Fehler ist bereinigt
