### ISSUE TITLE
ISSN 0265-3788 | Transformation | Keyword Book Review

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1073]
Bei Rezensionen wird im Single-DL das Keyword Book Review vergeben. Bitte entfernen. Im Multi-DL werden gar keine Keywords übertragen, zudem steht hier kein Sage Translator zur Verfügung. Deshalb Single-DL
https://journals.sagepub.com/toc/trna/37/3
https://journals.sagepub.com/doi/full/10.1177/0265378820930237

![grafik](https://user-images.githubusercontent.com/29707105/88514664-c86b6600-cfea-11ea-89ac-56bab54fc646.png)

**Comment by socheres** [comment]
mit Single-DL erfassen. "Book Review" werden entfernt.

**Comment by kdr154** [comment]
Nach Aktualisieren und Schließen und Öffnen der Anwendungen ist das Schlagwort Book Review leider immer noch enthalten.

**Comment by socheres** [comment]
Habe den Fehler gefunden und gefixt. Würden Sie nochmal testen?

**Comment by kdr154** [comment]
gelöst
