### ISSUE TITLE
ISSN 1573-6679 | Pastoral Psychology | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1074]
Der dafür entwickelte Translator ist Springer Link. Er steht auch an erster Stelle sowohl beim Multi- als auch beim Single-DL.
Aber: ein Multi-DL ist in der Regel nicht möglich, da sofort die Fehlermeldung "Es ist ein Fehler aufgetreten beim Versuch..." Beim 6. oder 7. Versuch ist es nun gelungen und der Download lief durch. Es fehlen jedoch beim Multi- wie beim Single-DL die elementaren Elemente Band, Ausgabe und Seiten.
https://link.springer.com/journal/11089/69/3?utm_source=toc&utm_medium=email&utm_campaign=toc_11089_69_3&utm_content=etoc_springer_20200727

![grafik](https://user-images.githubusercontent.com/29707105/88523771-c6a89f00-cff8-11ea-90b8-4c9b4c32d116.png)

und zusätzlich die Keywords, die im Abschnitt "About this article" stehen:
https://link.springer.com/article/10.1007/s11089-020-00907-4#article-info

**Comment by socheres** [comment]
ich habe den Translator nochmal aktualisert. Bei mir klappt sowohl Mulit- auch Single-DL und alle Datefelder sind vorhandne.

**Comment by kdr154** [comment]
Bis auf die Keywords. Die sind weder im Single- noch im Multi-DL dabei.
.
.
.
und zusätzlich die Keywords, die im Abschnitt "About this article" stehen:
https://link.springer.com/article/10.1007/s11089-020-00907-4#article-info

**Comment by kdr154** [comment]
Jetzt läuft er wieder nicht einmal mehr durch: "Es ist ein Fehler aufgetreten beim Versuch..."

**Comment by socheres** [comment]
Fehler im Translator behoben. Lag an den fehlenden Keywords beim Review-Artikel "Review of Nathan Carlin’s..."

**Comment by kdr154** [comment]
Tut mir leid. Bricht ab.

**Comment by socheres** [comment]
Haben Sie den Zotero-Connector aktualisiert?

**Comment by kdr154** [comment]
Connector?

**Comment by socheres** [comment]
@IxKo Können Sie bitte versuchen, die o.g. Datensätze im Single- und Multi herunterzuladen?

**Comment by IxKo** [comment]
Bei mir fehlen nur die Keywords, wenn ich in Multi und auch in Single herunterlade.

**Comment by socheres** [comment]
Habe den Translator nochmal angepasst. Würden Sie nochmal testen?

**Comment by kdr154** [comment]
Bricht wieder ab

**Comment by kdr154** [comment]
single klappt inklusive Keywords

**Comment by kdr154** [comment]
Es funktioniert alles.
