### ISSUE TITLE
ISSN  2199-4625 | Journal of Religious Education | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1075]
Translator Springer Link.
https://link.springer.com/journal/40839/68/2
Habe nun mehrmals wieder ein Translator Update im Browser und in Zotero gemacht. Browser geschlossen, geöffnet, Zotero geschlossen, geöffnet, nochmal die Prozdur durchgeführt.
Der erste Versuch Multi-DL: Es ist ein Fehler aufgetreten beim Versuch ....
Wiederholt,  dieselbe Meldung, Updates durchgeführt, dieselbe Meldung usw. usf.
Dann einen Single-DL versucht. Der klappte. Aber leider fehlten wieder Ausgabe, Heft, Seiten, Keywords.
Nochmal von vorn. Schließlich ging Multi-DL. Aber leider fehlten auch hier wieder Ausgabe, Heft, Seiten, Keywords.
Wieder von vorn. Update, Schließen, Öffnen, alle Anwendungen wieder neu aufmachen...
Schließlich wieder Single-DL versucht, und siehe da, alles dabei. Nichts wie die anderen Artikel ebenfalls herunterladen. Und das Ergebnis. Mal waren Ausgabe, Heft, Seiten, Keywords dabei, mal nicht. 
Einmal so:

![grafik](https://user-images.githubusercontent.com/29707105/88636134-cec81380-d0b8-11ea-9f4b-6797ac9d7b3c.png)

Der nächste Artikel so:

![grafik](https://user-images.githubusercontent.com/29707105/88636224-e69f9780-d0b8-11ea-8a70-50b6e1c6bac0.png)

Dann wieder so, dann wieder so ....

Dabei hatten wir dasselbe Problem mit diesem Translator bei einer anderen Zeitschrift von Springer doch erst vor einem Tag und alles war gelöst. Zumindest was Ausgabe, Heft und Seiten betraf.

**Comment by socheres** [comment]
@IxKo würden Sie auch mal testen? Habe gerade die Datensätze  von https://link.springer.com/journal/40839/68/2 heruntergeladen und alle Felder (Ausgabe, Heft und Seiten) sind im Single- sowie Multi-DL vorhanden.

**Comment by IxKo** [comment]
Beim Multi-DL erhalte ich auch die Fehlermeldung.
Beim Single-DL fehlen bei mir nur die Keywords.

**Comment by socheres** [comment]
Bei mir lief jetzt auch durch. @kdr154 Bekommen Sie beim Multi-DL weiterhin eine Fehlermeldung?

**Comment by kdr154** [comment]
ja

**Comment by kdr154** [comment]
Jetzt ist es gut.
