### ISSUE TITLE
ISSN 2179-0019 | Plura | Keywords Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1076]
Die Keywords werden ein Teil des Abstracts.
https://revistaplura.emnuvens.com.br/plura/article/view/1679
Sie stehen unterhalb des Abstracts und werden eingeleitet durch "Palavras-chave".
So sieht es in Zotero aus:

![grafik](https://user-images.githubusercontent.com/29707105/88805926-0bc30180-d1b0-11ea-9163-543ca31feebd.png)

**Comment by socheres** [comment]
bitte nach Vorlage einspielen und Issue schließen.

**Comment by kdr154** [comment]
Was bedeutet das: nach Vorlage einspielen? Ich bekomme weiterhin dasselbe  Ergebnis.

**Comment by socheres** [comment]
mit Vorlage meine ich so wie auf Webseite steht. Das muss nicht bereinigt werden.

**Comment by kdr154** [comment]
Danke
