### ISSUE TITLE
ISSN 1756-073X | Practical Theology | Schlagwort Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1077]
Es erleichtert zwar die Nachbearbeitung im Verfahren zotkat, aber das Schlagwort "Book Reviews" sollte gelöscht werden.
https://www.tandfonline.com/doi/full/10.1080/1756073X.2020.1742439

![grafik](https://user-images.githubusercontent.com/29707105/88816190-6f532c00-d1bc-11ea-96bb-f42dbac4cf8f.png)

**Comment by IxTheoKm** [comment]
Wird das denn umgesetzt in 1131 !106186019!_Rezension_?
Bisher haben wir Keywords wie "Review", "Book review", "Book reviews" o.ä. in den Datensätzen gelassen. Wenn sie nicht zu 1131 umgesetzt werden, würde ich diese Information den Nutzern nicht vorenthalten.

**Comment by kdr154** [comment]
Das ist neu. Es handelt sich doch um ein Formaschlagwort und kein Sachschlagwort. 1131 wird beim Nacharbeiten ergänzt.

**Comment by IxTheoKm** [comment]
Wenn es machbar ist, sollte dann diese Information nicht gelöscht, sondern generell in 1131 umgesetzt werden (auch im vollautomatischen Verfahren).

**Comment by kdr154** [comment]
Im vollautomatischen Verfahren ist die Umsetzung in 1131 Standard. Im halbautomatischen muss man nacharbeiten.

**Comment by IxTheoKm** [comment]
@socheres Wenn es im vollautomatischen Verfahren funktioniert, lässt sich das nicht generell einrichten, um Nacharbeit zu sparen?

**Comment by socheres** [comment]
Habe beide Pica-Translator angepasst. Z.K. an @IxTheoKm @kdr154 @IxKo @RelBibRetroKat 
- [x] Indikator |s| bei "Book Reviews" durch |f| ersetzen
- [x] bei Keyword "Book Reviews" > Anreicherung der Pica-Kategorie 1131 !Rezension!

```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1500 eng
1505 $erda
2051 10.1080/1756073X.2020.1742439
3000 Royster, Michael D.$BVerfasserIn$4aut
4000 A @theology of preaching and dialectic$dscriptural tension, heraldic proclamation and the pneumatological moment
4070 $v13$j2020$a1/2$p198-199
4241 Enthalten in!585507937!
4950 https://doi.org/10.1080/1756073X.2020.1742439$xR
5056 1
5520 |f|Book Reviews
E* l01
7100 $Jn
8012 ixzs$aixzo

application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2020$n[2020]\n1500 eng\n1505 $erda\n2051 10.1080/1756073X.2020.1742439\n3000 Royster, Michael D.$BVerfasserIn$4aut\n4000 A @theology of preaching and dialectic$dscriptural tension, heraldic proclamation and the pneumatological moment\n4070 $v13$j2020$a1/2$p198-199\n4241 Enthalten in!585507937!\n4950 https://doi.org/10.1080/1756073X.2020.1742439$xR\n5056 1
\n5520 |f|Book Reviews\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter"); 
```

**Comment by IxKo** [comment]
Könnte man es denn nicht so machen, dass 5520 |f| ganz entfällt und in 1131 umgewandelt wird?

**Comment by socheres** [comment]
Es wird eine leere Kategorie 5520 ausgegeben, wird dann aber beim Speichern in WiniBW im Einzel- bzw. Batch-Verfahren automatisch entfernt. Nach Tests bitte Issue schließen.

```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1131 !106186019!
1500 eng
1505 $erda
2051 10.1080/1756073X.2020.1742439
3000 Royster, Michael D.$BVerfasserIn$4aut
4000 A @theology of preaching and dialectic$dscriptural tension, heraldic proclamation and the pneumatological moment
4070 $v13$j2020$a1/2$p198-199
4241 Enthalten in!585507937!
4950 https://doi.org/10.1080/1756073X.2020.1742439$xR
5056 1
5520 
E* l01
7100 $Jn
8012 ixzs$aixzo

 
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2020$n[2020]\n1131 !106186019!\n1500 eng\n1505 $erda\n2051 10.1080/1756073X.2020.1742439\n3000 Royster, Michael D.$BVerfasserIn$4aut\n4000 A @theology of preaching and dialectic$dscriptural tension, heraldic proclamation and the pneumatological moment\n4070 $v13$j2020$a1/2$p198-199\n4241 Enthalten in!585507937!\n4950 https://doi.org/10.1080/1756073X.2020.1742439$xR\n5056 1\n5520 \nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");
```

**Comment by IxTheoKm** [comment]
@socheres In Ihrer Checkliste oben haben Sie nur "Book Review**s**" aufgeführt.

Es gibt in den Testdaten aber etliche mit "Book Review" (auch als Titelfassung in PICA-Feld 4000 = MARC 245). 
Das müsste wohl auch berücksichtigt werden.

**Comment by kdr154** [comment]
gelöst
