### ISSUE TITLE
ISSN 2272-9011 | Etudes théologiques et religieuses | überflüssige Leerzeichen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1079]
**URL**
1. https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2020-1-page-105.htm
2. https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2020-1-page-135.htm
3. https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2019-4-page-535.htm

**Ausführliche Problembeschreibung**
betrifft Titel(zusatz) in 4000
1. Leerzeichen vor $d sollte entfernt werden.
2. Leerzeichen vor ? oder ! im Titel sollten entfernt werden.
3. Leerzeichen vor » und Leerzeichen nach « sollten entfernt werden.

Dieses Issue wurde im Auftrag von Frau Eg. angelegt.

**Comment by socheres** [comment]
Translator kann nicht angepasst werden. Bitte die Leerzeichen manuell entfernen. Bitte Issue schließen.
