### ISSUE TITLE
Sage ISSN 1552-7522 The Prison Journal Mix aus First Online und zugeordneten Artikeln

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#108]
Auch dieser Feed enthält einen Mix einem Heft zugeordneten Artikeln und keinem Heft zugeordneten Artikeln.
Man kann dies auf der Webseite des Feeds unterscheiden:
https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=tpjd&type=etoc&feed=rss
Unter dem letzten Link steht "Ahead of Print", während bei den anderen Ausgabe- und Seiteninformationen darunter stehen
Ebenso bei #87 und #85

**Comment by shadeMe** [comment]
Die Online-First Problematik ist jetzt gelöst. Bitte nochmal prüfen.

**Comment by kdr154** [comment]
Gelöst
