### ISSUE TITLE
ISSN 2179-0019 | Plura | Titel und Doppelpunkt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1080]
Bei dieser Zeitschrift geht der manchmal der Titelzusatz verloren. Mehr noch, es wird hinter dem Haupttitel ein Doppelpunkt gesetzt:
https://revistaplura.emnuvens.com.br/plura/article/view/1679
In Zotero: Memórias sensíveis em caleidoscópio::
Dadurch entsteht in der Winibw ein überflüssiges $d am Ende des Titels.

Hier geht kein Titelzusatz verloren, den Doppelpunkt wird am Ende aber dennoch gesetzt
https://revistaplura.emnuvens.com.br/plura/article/view/1684
In Zotero: Experiências de regionalização da ABHR: bons ares vêm do Norte:

**Comment by socheres** [comment]
bitte manuell bereinigen. Zu aufwändig einen neuen OJS-Translator für diese Zss. zu erstellen.

**Comment by kdr154** [comment]
Soll man dieses Issure schließen

**Comment by socheres** [comment]
ja, ich schließe.
