### ISSUE TITLE
ISSN 0015-5357 | Foi & vie | fehlender Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1081]
**URL**
https://www.foi-et-vie.fr/archive/byyear.php#year=2019

**Ausführliche Problembeschreibung**
Mir wird kein Translator angeboten (multi oder single)

**Comment by socheres** [comment]
bitte als Quelle "p_zot" in ZEDER verwenden. http://www-ub.ub.uni-tuebingen.de/zeder/?bearbeiter=t.kim&instanz=ixtheo#suche=0015-5357%20
