### ISSUE TITLE
ISSN 1612-9768 | International journal of practical theology | Translator mangelhaft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1082]
**URL**
https://www.degruyter.com/view/journals/ijpt/24/1/ijpt.24.issue-1.xml 
https://www.degruyter.com/view/journals/ijpt/24/1/article-p5.xml?tab_body=pdf-78589

**Ausführliche Problembeschreibung**
Im Multi-DL wird kein Translator angeboten und im Single nur "Embedded Metadata" oder "DOI". Bei letzteren beiden fehlen die Keywords und es wird nur ein Abstract von zweien übertragen.

**Offenbare Lösungen**
Translator anpassen

**Comment by socheres** [comment]
Translator "DeGruyter.js" sollte überarbeitet werden.

**Comment by socheres** [comment]
Neuer Translator "ubtue_DeGruyter.js. Bitte auch andere Zss. von DeGruyter testen.

**Comment by IxKo** [comment]
Der neue Translator für den Multi-DL funktioniert gut. Danke

**Comment by IxKo** [comment]
Bei dem Beispiel-Artikel von oben wird jedoch nur das englische Abstract geharvestet. Im Quellcode ist auch das deutsche hinterlegt.

**Comment by socheres** [comment]
Das deutsche Abstract sollte nun auch dabei sein. Bitte testen und falls diese und andere DeGruyter-Zeitschriften RSS-Feed anbieten, nach commit durch @mtrojan-ub ins Zotaut-Verfahren aufnehmen.

**Comment by IxKo** [comment]
Nun kommen beide Abstracts mit. Zwischen beide müsste noch \n4207 gesetzt werden, damit es zwei Pica-Felder werden. Das kann aber auch manuell beim zotkat-Verfahren gemacht werden.

DeGruyter bietet RSS an, ich werde in Zeder prüfen, ob bei den Zss der RSS-URL hinterlegt ist.

**Comment by IxKo** [comment]
@socheres Sollen die RSS-Feeds zu neuen Artikel oder die RSS ETOCs eingetragen werden?

Beispiel: https://www.degruyter.com/view/journals/ijpt/ijpt-overview.xml 
RSS neuer Artikel: https://www.degruyter.com/journalnewarticlerss/journals/ijpt/ijpt-overview.xml
RSS ETOC: https://www.degruyter.com/journalissuetocrss/journals/ijpt/ijpt-overview.xml

**Comment by socheres** [comment]
@IxKo bitte den "RSS neuer Artikel: https://www.degruyter.com/journalnewarticlerss/journals/ijpt/ijpt-overview.xml" eintragen.

**Comment by socheres** [comment]
> Nun kommen beide Abstracts mit. Zwischen beide müsste noch \n4207 gesetzt werden, damit es zwei Pica-Felder werden. Das kann aber auch manuell beim zotkat-Verfahren gemacht werden.
> 
> DeGruyter bietet RSS an, ich werde in Zeder prüfen, ob bei den Zss der RSS-URL hinterlegt ist.

bitte testen.

**Comment by IxKo** [comment]
Habe die RSS-Links ergänzt.

**Comment by IxKo** [comment]
Mulit-Translator funktioniert, beide Abstracts kommen rüber.
