### ISSUE TITLE
ISSN 2413-9467 | Stellenbosch Theological Journal | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1083]
Mit dem Open Journal Systems Translator wird kein Abstract übertragen.
https://ojs.reformedjournals.co.za/stj/article/view/1972

**Comment by socheres** [comment]
Haben einen neuen Translator "Open Journal Systems Standard.js" geschrieben .Bitte testen.

**Comment by kdr154** [comment]
Auch nach mehrmaligen Update und Öffnen und Schließen in und von Zotero und Browser sieht es sowohl bei den Seitenzahlen und Abstract noch genauso aus. Kein Abstract, Seitenzahlen werden gedoppelt.
#1085 #1084

**Comment by socheres** [comment]
wird Ihnen der neue Translator "Open Journal Systems **Standard**.js" angeboten?

**Comment by kdr154** [comment]
Nein, obwohl er in meinem Translator-Verzeichnis ist.

**Comment by socheres** [comment]
der Translator "Open Journal Systems Standard.js" wird nur beim Multiple-DL angeboten. Testen Sie bitte diesen Link: https://ojs.reformedjournals.co.za/stj/issue/view/70

**Comment by kdr154** [comment]
In diesem Fall wird der "Open Journals System Standard.js" angeboten, Abstract ist enthalten, Seitenzahlen sind korrekt.
