### ISSUE TITLE
ISSN 2413-9467 | Stellenbosch Theological Journal | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1084]
Mit dem Open Journal Systems Translator werden die Seitenzahlen zweimal übertragen.
https://ojs.reformedjournals.co.za/stj/article/view/1972

![grafik](https://user-images.githubusercontent.com/29707105/89872106-c263b080-dbb8-11ea-836f-30d4df3edb02.png)

Bei den Rezensionen ist dies nicht der Fall: https://ojs.reformedjournals.co.za/stj/article/view/1998

**Comment by socheres** [comment]
#1083

**Comment by kdr154** [comment]
Siehe #1085

**Comment by socheres** [comment]
Wenn Ihnen angeboten wird, den Open Journal System **Standard** verwenden.

**Comment by kdr154** [comment]
Wird er leider nicht, siehe #1083

**Comment by kdr154** [comment]
In diesem Fall wird der "Open Journals System Standard.js" angeboten, Abstract ist enthalten, Seitenzahlen sind korrekt.
Vgl #1083
