### ISSUE TITLE
ISSN 2413-9467 | Stellenbosch Theological Journal | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1085]
Mit dem Embedded Metadata Translator werden wie beim Open Journal Systems Translator die Seitenzahlen gedoppelt.
https://ojs.reformedjournals.co.za/stj/article/view/1984

![grafik](https://user-images.githubusercontent.com/29707105/89872719-a90f3400-dbb9-11ea-9cdb-a2a6fecd76e0.png)

Aber Embedded Metadata überträgt im Gegensatz zu Open Journal Systems das Abstract.

**Comment by socheres** [comment]
#1083

**Comment by kdr154** [comment]
Vgl #1083
