### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review | Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1087]
Einspielung in Testdatenbank vom 12.08.2020
Bei diesem Heft https://onlinelibrary.wiley.com/toc/17586623/2020/72/3 sind einige Verfasserangaben ausgesprochen schwierig, da sich in ihnen Funktion, persönlicher Name und ursprünglicher Name mischen.
Hier IxTheo#2020-08-11#6154534FAFCA37BDB3F2B2EFB8B5230E3277B006
ist die Vorlage folgende: https://onlinelibrary.wiley.com/doi/10.1111/erev.12538
Was im K10plus wie folgt umgesetzt wird: 3000 America, Archbishop Elpidophoros (Lambriniadis)$BVerfasserIn$4aut
wobei es sich um Lambriniadis, Elpidophoros handelt PPN 859613895
und Pica 3000 so aussehen sollte: 3000 !859613895!Lambriniadis, Elpidophoros *1967-* ; ID: gnd/1100883770$BVerfasserIn$4aut
Analog:
7811 IxTheo#2020-08-11#125CC8AACB635697E740A07977733F7946DBF9CC
https://onlinelibrary.wiley.com/doi/10.1111/erev.12525
K10plus: 3000 America, Archbishop Demetrios Geron (Elder)$BVerfasserIn$4aut
ist PPN 802917526 Trakatellēs, Dēmētrios
und Pica 3000 wäre korrekt wie folgt: 3000 !802917526!Trakatellēs, Dēmētrios *1928-* ; ID: gnd/1060861526$BVerfasserIn$4aut
Dieselbe Problematik bei folgenden Aufsätzen in diesem Heft:
https://onlinelibrary.wiley.com/doi/10.1111/erev.12523
https://onlinelibrary.wiley.com/doi/10.1111/erev.12521
https://onlinelibrary.wiley.com/doi/10.1111/erev.12541
https://onlinelibrary.wiley.com/doi/10.1111/erev.12522
https://onlinelibrary.wiley.com/doi/10.1111/erev.12528

**Comment by IxKo** [comment]
Hallo, lt. der letzten Mail von socheres am 05.08. sollen noch keine Issues zu den neuen Testdaten aufgemacht werden.
Viele Grüße

Die Angabe mit zusätzlichen Namen in Klammern ist mir auch schon bei anderen Zss im zotkat-Verfahren aufgefallen.

**Comment by kdr154** [comment]
An der Problematik hat sich bei diesem Heft nichts verändert:

![grafik](https://user-images.githubusercontent.com/29707105/126172612-e8d767cd-c687-47ef-8b2f-8238ff66331b.png)

Haben wir uns schon für eine Lösung entschieden?
Was die Verfasser angeht, scheint mir das hier getestete Heft eine Ausnahme zu sein

**Comment by socheres** [comment]
Liebe @IxKo, bitte Zotaut-Übernahme prüfen. Danke!

**Comment by socheres** [comment]
Das ist schon eine Zotaut-Zeitschrift (Wiley).
