### ISSUE TITLE
ISSN 0024-7324 | Lumen vitae | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1089]
Bei dieser Zeitschrift wird keine Sprache übertragen
https://poj.peeters-leuven.be/content.php?url=journal.php&journal_code=LV
https://poj.peeters-leuven.be/content.php?url=article&id=3287702&journal_code=LV

![grafik](https://user-images.githubusercontent.com/29707105/90231576-b1ff4000-de1b-11ea-9d8d-e0a1f017aa18.png)

**Comment by socheres** [comment]
#1088 via ISSN_to_language_code.map lösen.

**Comment by kdr154** [comment]
Mapping-Tabelle ergänzt.
