### ISSUE TITLE
ISSN 2295-5186 | Theoforum | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1093]
Es wird keine Sprache geliefert. Ist in diesem Fall nicht über die Mapping-Tabelle zu lösen, da die Artikel in verschiedenen Sprachen verfasst werden:
https://poj.peeters-leuven.be/content.php?url=issue&journal_code=TF&issue=1&vol=49

**Comment by kdr154** [comment]
Das Feld Sprache ist weiterhin leer.

**Comment by socheres** [comment]
Sprache ist im Quelltext nicht vorhanden, daher nicht abgreifbar. Bitte manuell erfassen.

**Comment by kdr154** [comment]
Dann mache ich einen Vermerk in Zeder und schließe
