### ISSUE TITLE
ISSN 0035-2403 | Revue d'histoire et de philosophie religieuses | Band- und Heftzählung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1095]
**URL**
https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-2-100e-annee-n-2-varia.html
(nur Single-DL möglich)

**Ausführliche Problembeschreibung**
Die Band- und Heftzählung kommt nicht nach Zotero rüber, wenn der Translator **unAPI** genutzt wird.

Bei **Embedded Metadata** kommen die Angaben ganz falsch heraus und die Tags fehlen.
![grafik](https://user-images.githubusercontent.com/57000004/90645881-c89c0180-e236-11ea-874c-77e651fe70bd.png)

**Comment by socheres** [comment]
bitte den Link aus "p_zot2" verwenden. http://www-ub.ub.uni-tuebingen.de/zeder/?bearbeiter=t.kim&instanz=ixtheo#suche=%20Revue%20d%27Histoire%20et%20de%20Philosophie%20religieuses

**Comment by IxKo** [comment]
Den habe ich vor einer halben Stunde zu dem Verlagslink geändert, da es dort Abstracts und Keywords gibt und die Daten des aktuellen Heftes ohne Verzögerung online gestellt werden.

**Comment by socheres** [comment]
Habe einen Translator "ubtue_RHPR.js" neu erstellt. Wahrscheinlich muss bei Band- und Heftzählung noch angepasst werden. Teilen Sie mir bitte mit, was noch verbessert werden soll.

**Comment by socheres** [comment]
Z.I. Translator funktioniert nur beim Multi-DL.

**Comment by IxKo** [comment]
Es sieht ganz gut aus (DOI, Keywords, Abtracts, Sprache), nur Band- und Heftzählung schauen noch nicht gut aus:
![grafik](https://user-images.githubusercontent.com/57000004/90654426-ab6c3080-e240-11ea-92cb-f5af9d403d00.png)
Hier müsste Band=100 und Ausgabe=2 sein.

**Comment by socheres** [comment]
Bitte testen. Gefixt habe ich auch die Wiederholung der Seitenzahl mit Bindestrich beim Artikel mit nur einer Seite. Z.B. 3-3

**Comment by IxKo** [comment]
Sieht gut aus.

**Comment by socheres** [comment]
Gibt es für diese Zeitschrift einen RSS-Link? Wenn ja, dann könnte man sie ins Zotaut-Verfahren aufnehmen.

**Comment by IxKo** [comment]
Im HTML-Code fand ich diesen: https://classiques-garnier.com/feed/catalog/fr_FR/335
Ich trage ihn in Zeder ein und stelle auf zotat

**Comment by socheres** [comment]
bitte noch nicht auf zotat umstellen. Im Harvester fehlt noch der neue Translator.

**Comment by socheres** [comment]
Z.I.: für Zotaut gibt es eigene Translator-Repository. @mtrojan-ub bitte nach commit @IxKo benachrichtigen.

**Comment by IxKo** [comment]
@socheres Mir ist bei der Bearbeitung im zotkat-Verfahren auch noch aufgefallen, dass die französischen bestimmten Artikel, wenn sie abgekürzt am Anfang eines Titels stehen, nicht erkannt werden bzw. das Nicht-Sortierzeichen dann nicht gesetzt wird.

z.B. hier: https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-1-100e-annee-n-1-varia-l-antiquite-chretienne-dans-la-rhpr.html

**Comment by socheres** [comment]
> @socheres Mir ist bei der Bearbeitung im zotkat-Verfahren auch noch aufgefallen, dass die französischen bestimmten Artikel, wenn sie abgekürzt am Anfang eines Titels stehen, nicht erkannt werden bzw. das Nicht-Sortierzeichen dann nicht gesetzt wird.
> 
> z.B. hier: https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-1-100e-annee-n-1-varia-l-antiquite-chretienne-dans-la-rhpr.html

bitte testen.

**Comment by IxKo** [comment]
Danke, das Nicht-Sortierzeichen wird nun mit ausgegeben.

**Comment by IxKo** [comment]
>@socheres Mir ist bei der Bearbeitung im zotkat-Verfahren auch noch aufgefallen, dass die französischen bestimmten Artikel, wenn sie abgekürzt am Anfang eines Titels stehen, nicht erkannt werden bzw. das Nicht-Sortierzeichen dann nicht gesetzt wird.
>z.B. hier: https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-1-100e-annee-n-1-varia-l-antiquite-chretienne-dans-la-rhpr.html

**Comment by IxKo** [comment]
Unter https://original.rdatoolkit.org/document.php?id=rdaappc-de&target=rdac-26&hitnum=4&anchor=hit#hit
gibt es eine Auflistung aller zu überspringender Artikel für die jeweilige Sprache.

**Comment by socheres** [comment]
Regex gefixt. Bitte nochmal testen.

**Comment by socheres** [comment]
> Unter https://original.rdatoolkit.org/document.php?id=rdaappc-de&target=rdac-26&hitnum=4&anchor=hit#hit
> gibt es eine Auflistung aller zu überspringender Artikel für die jeweilige Sprache.

die europäischen Sprachen sind bereits berücksichtigt. Bitte melden Sie sich, falls eine zusätzliche Sprache aufgenommen werden soll. #1095

**Comment by IxKo** [comment]
Nun wird ein Anführungszeichen davor gesetzt, obwohl es hier ursprünglich nie eines gab:
`4000 „L' @Antiquité chrétienne dans la RHPR - Remarques sur un siècle de recherches`

**Comment by socheres** [comment]
`L'` mit Anführungszeichen davor `„L’ Antiquité chrétienne` macht Probleme. Für alle anderen Fälle müsste es jetzt funktionieren.

**Comment by socheres** [comment]
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1500 fre
1505 $erda
2051 10.15122/isbn.978-2-406-10372-1.p.0009
3000 !870233084!$BVerfasserIn$4aut 
8910 $aixzom$bAutor in der Zoterovorlage [Aragione, Gabriella] maschinell zugeordnet
4000 L' @Antiquité chrétienne dans la RHPR - Remarques sur un siècle de recherches
4070 $v100$j2020$a1$p9-22
4207 Les années 1920-1930 et 1960-1980 marquent un tournant dans l’histoire de la recherche sur l’Antiquité chrétienne, en raison, respectivement, de l’essor de la méthode historico-critique et du renouvellement des études patristiques. Les travaux publiés dans la RHPR contribuent activement aux débats scientifiques de l’époque, tantôt en suivant les modèles épistémologiques existants, tantôt en en suggérant des nouveaux.
4241 Enthalten in!51582447X!
4950 https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-1-100e-annee-n-1-varia-l-antiquite-chretienne-dans-la-rhpr.html$xH$3Volltext$4ZZ$534
4950 https://doi.org/10.15122/isbn.978-2-406-10372-1.p.0009$xR$3Volltext$4ZZ$534
5056 1
5520 |s|André Benoît
5520 |s|Antiquité chrétienne
5520 |s|Eugène de Faye
5520 |s|Pères de l’Église
5520 |s|exégèse patristique
5520 |s|histoire du christianisme ancien
5520 |s|littérature chrétienne ancienne
5520 |s|méthode historico-critique
5520 |s|sciences religieuses
5520 |s|théologie protestante
E* l01
7100 $Jn
8012 ixzs$aixzo

**Comment by IxKo** [comment]
Ist nun gefixt
