### ISSUE TITLE
ISSN 1467-8519 | Bioethics | Ungültiger GND Lookup

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1096]
Bei diesem Aufsatz: https://onlinelibrary.wiley.com/doi/10.1111/bioe.12524
kommt es zu einer ungültigen PPN-Verknüpfung beim 2. Verfasser: 

![grafik](https://user-images.githubusercontent.com/29707105/90754809-acea3700-e2da-11ea-8464-5ef82a76edac.png)

Statt der PPN steht der Nachname des Verfassers zwischen den Ausrufungszeichen.

**Comment by socheres** [comment]
Die Funktion PPN-Lookup habe ich angepasst. Außerdem war bei Ihnen der Lookup-Parameter anders (grün im Bild). Wenn Sie die Parameter eigenhändig ändern, bitte vorher mich kurz informieren. Hier könnte das Hinzufügen weiterer Berufsbezeichnungen für die automatische Verknüpfung sinnvoll sein, aber generell würde die Treffergenauigkeit(Precision) beim Matching bei den Theolog* u.a.  eher sinken. Daher bitte nicht vergessen, die Lookup-Änderung nach Bearbeitung dieser Zeitschrift wieder rückgängig zu machen. Z.I. @RelBibRetroKat @IxKo 
![image](https://user-images.githubusercontent.com/1545743/90763592-3dc70f80-e2e7-11ea-8e3d-1227df6554d8.png)

**Comment by kdr154** [comment]
Stimmt, habe die Lookup-Parameter geändert, da ich z. Zt. an einer ZS bin, in der immer wieder Ärzte, Ethiker, Mediziner publizieren. Natürlich habe ich vor, die Änderungen am Ende wieder rückgängig zu machen. 
So ganz verstehe ich aber Ihr Problem nicht. Ich dachte diese Ändereung betrifft nur meine Kopie und hat keine weiteren Auswirkungen.

**Comment by kdr154** [comment]
Jetzt stimmt die Verknüpfung.

**Comment by socheres** [comment]
ich konnte Ihren Fehler nicht reproduzieren. Erst nach langer Fehlerursache bin ich auf die Änderung in Ihrem Skript gestoßen.

**Comment by kdr154** [comment]
Dann ist ja alles in Ordnung. Das die Treffergenauigkeit bei den Theolog* sinken würde, war mir so nicht bewusst, aber ich habe es verstanden. Deshalb werde ich die Änderung auf jeden Fall zurücknehmen.

**Comment by socheres** [comment]
@kdr154 @IxKo PicaTranslator funktioniert wieder.
