### ISSUE TITLE
SSOAR_MARC 21 Feld 773 $g

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#11]
Wurde z.T. aus 500 gesplittet!
Wurden die Bandbezeichnungen erzeugt oder stehen sie so in den Originaldaten?
In der ersten Datei von April stehen sie z.T. nicht (z.B. „edition“).
„pages“, „volume“
„edition“, „year“
„number“

	Wenn sie mitgeliefert werden, dann
	Pages		-> 936 $h
	Volume		-> 936 $d
	Year	        -> 936 $j
	Number	        -> 936 $e
	Edition		-> 936 $d (???)

Beispiel für korrekte Erfassung:
\<datafield tag="**773**" ind1="0" ind2="8"\>
\<subfield code="i">In</subfield\>
\<subfield code="**a**">Revue d&#39;études augustiniennes et patristiques</subfield\>
\<subfield code="d">2016</subfield\>
\<subfield code="g">**62(2016), 2, S. 183-222**</subfield\>
\<subfield code="w">(DE-576)281268371</subfield\>
\<subfield code="w">(DE-600)2176057-3</subfield\>
\<subfield code="x">2428-3606</subfield\>

[NACHTRAG: Lt. BSZ wird der Titel NICHT mehr in 773 $a abgelegt, sondern in 773 **$t** !]

**Comment by IxTheoKm** [comment]
Wenn 773 _nicht_ vorhanden ist, muss es ggf. aus dem unaufgegliederten Feld 500 a mit der Zeichenfolge **\<subfield code="a"\>In:** erzeugt werden.

Beispiel oai:gesis.izsoz.de:document/3674

<datafield tag="500" ind1=" " ind2=" ">
<subfield code="a">In: Sozialwissenschaften und Berufspraxis ; 20 (1997) 4 ; 341-349</subfield>

In: _Titel des übergeordneten Werks_ ; _Bandzählung_ (_Jahr_) _Heftnummer_ ; _Anfangsseiten_-_Endseiten_

**Wenn** \<datafield tag="500" ind1=" " ind2=" "\>
\<subfield code="a"\>**In:** 

**dann**

\<datafield tag="773" ...\>
\<subfield code="i"\>In\</subfield\>
\<subfield code="a"\>_Titel des übergeordneten Werks_\</subfield\>
\<subfield code="d"\>_Jahr_\</subfield\>
\<subfield code="g"\>_Band_(_Jahr_), _Heft_, S. _Seite_-_Seite_\</subfield\>

Obiges Beispiel umgesetzt:

\<datafield tag="773" ...\>
\<subfield code="i"\>In\</subfield\>
\<subfield code="a"\>Sozialwissenschaften und Berufspraxis\</subfield\>
\<subfield code="d"\>1997\</subfield\>
\<subfield code="g"\>20(1997), 4, S. 341-349\</subfield\>

**Zusätzlich Feld 936 erzeugen mit folgenden Subfields:**

936 "d"_Band_
936 "j"_Jahr_
936 "e"_Heft_
936 "h"_Seiten_

Für obiges Beispiel:
\<datafield tag="936" ...\>
\<subfield code="d"\>20
\<subfield code="j"\>1997
\<subfield code="e"\>4
\<subfield code="h"\>341-349

**Comment by kdr154** [comment]
Ergänzung:
Bei Zeitschriftenaufsätzen, leader "nab", die in Doppelheften erschienen sind, wird die Heftnummer in 773 subfield code="g" und 936 subfield code="e" nicht vollständig erzeugt.
Beispiel: 
tag=500
`<subfield code="a">In: Crime, Law and Social Change ; 55 (2011) 2-3 ; 167-184</subfield>`
erzeugt in 773 code g  
`<subfield code="g">(2011), 2</subfield>`
müsste lauten;  
`<subfield code="g">(2011), 2-3</subfield>`

und 936 code e   
`<subfield code="e">2</subfield>`
müsste lauten: 
`<subfield code="e">2-3</subfield>`

analog:
tag=500
`<subfield code="a">In: Soziale Probleme ; 12 (2001) 1/2 ; 183-208</subfield>`
erzeugt in 773 code g  
`<subfield code="g">(2001), 1</subfield> `
müsste lauten:
`<subfield code="g">(2001), 1/2</subfield>`

und in 936
`<subfield code="e">1</subfield>`
müsste lauten:
`<subfield code="e">1/2</subfield>`

Diese beiden Fälle habe ich gefunden, den Bindestrich ("-") zwischen den Heftnummern, und den Slash ("/")
Richtig nach RDA scheint mir in beiden Fällen der Schrägstrich "/"zu sein.
Also 2-3 wird zu 2/3 und 1/2 kann so bleiben.

**Comment by IxTheoKm** [comment]
In Anbetracht der Tatsache, dass es eine Default-Pipeline werden soll, ein ergänzender Hinweis:
es kommt in den Daten ...20181016 auch ein Pluszeichen vor:

```
<datafield tag="500" ind1=" " ind2=" ">
<subfield code="a">In: International Journal of Action Research ; 3 (2007) 1+2 ; 15-37</subfield>
```

Alle drei Zeichen werden zu Schrägstrich.

**Comment by jriedl** [comment]
Programm schreibt jetzt auch '+' um, aber für die aktuellen Daten ist ja kein solcher Fall vorhanden, oder?

**Comment by IxTheoKm** [comment]
Ja, die aktuellen Daten haben keinen Fall mit Pluszeichen.
