### ISSUE TITLE
ISSN 1573-6679 | Pastoral Psychology | Translator für Multi-DL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1101]
Hier https://link.springer.com/journal/11089/volumes-and-issues/69-4 wird für den Multi-DL kein Translator anbeboten, im Single-DL (Translator Springer_Link) fehlen die Angaben zum Band und zum Heft:

![grafik](https://user-images.githubusercontent.com/29707105/91980821-272da900-ed28-11ea-8eb4-2dc25bb6d9f5.png)

**Comment by kdr154** [comment]
Einen Tag später sind Band und Ausgabe vorhanden. Ein Translator für Multi wird aber Weiterhin nicht angeboten.

**Comment by kdr154** [comment]
Ein Translator mit dem Namen "Springer Link" wird jetzt zum Multi-DL angeboten. Er verursacht aber immer einen Fehler. Beim Single-DL funktioniert er problemlos.

**Comment by kdr154** [comment]
Bekomme die Fehlermeldung immer noch. Single-DL problemlos

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
kann es sein, dass dieses Problem mittlerweile behoben ist? Bei mir tritt es nicht auf.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Ist behoben.
