### ISSUE TITLE
Allgemein: Nicht-Sortierzeichen bei Artikel am Anfang mit vorangegangenen Sonderzeichen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1105]
Wenn ein Titel mit einem Sonderzeichen beginnt, wird trotz des darauffolgenden Artikels kein Nicht-Sortierzeichen eingefügt.

z.B.: 
"Der ..."
müsste so umgesetzt werden:
`"Der @..."`

**Comment by socheres** [comment]
Können Sie mir bitte ein konkretes Beispiel nennen?

**Comment by IxKo** [comment]
Z. B. bei diesem Artikel: https://www.degruyter.com/view/journals/spircare/8/2/article-p217.xml

**Comment by IxKo** [comment]
Es wird ebenfalls nicht automatisch gesetzt, wenn der Titel ganzheitlich in **Großbuchstaben** geschrieben ist (THE ...)

Der deutsche Artikel "**dem**" müsste auch übersprungen werden: Bsp: https://doi.org/10.30965/2589045X-1860201

Es existiert im RDA-Toolkit eine **Auflistung** aller einleitender Artikel: https://original.rdatoolkit.org/document.php?id=rdaappc-de&target=rdac-26&hitnum=4&anchor=hit#hit
Es gibt jedoch **Ausnahmefälle**, wo das Nichtsortierzeichen nicht gesetzt werden dürfte, weil der vermeintliche Artikel das Subjekt ist und gar kein Artikel zu einem Substantiv.
Bsp.: Der mit dem Wolf tanzt

**Comment by IxKo** [comment]
>Z. B. bei diesem Artikel: https://doi.org/10.1515/spircare-2018-0078
>Es sollte dann in 4000 "Die @Zeit ...

Nun wird das @-Zeichen gesetzt, aber das erste Anführungszeichen (\u201c) fehlt.

**Comment by socheres** [comment]
Wie sieht Ihr Exportergebnis aus? Bei mir ist das normale Anführungszeichen (\u201e) vorhanden. Beim Exportieren werden hochgestelltes Anführungszeichen normalisiert.
```
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2019$n[2019]\n1500 spa\n1505 $erda\n2051 10.1515/spircare-2018-0078\n3000 !51581721X!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [Gillen, Erny] maschinell zugeordnet\n\n4000 \u201eDie Zeit ist mehr wert als der Raum\u201c \u2013 Zeit rein!\n4070 $v8$j2019$a2$p217-217\n4241 Enthalten in!718595513!\n4950 https://doi.org/10.1515/spircare-2018-0078$xR$3Volltext$4ZZ$534\n4950 https://www.degruyter.com/document/doi/10.1515/spircare-2018-0078/html$xH$3Volltext$4ZZ$534\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

```

**Comment by IxKo** [comment]
Mein Export-Ergebnis sieht wie folgt aus:
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2019$n[2019]\n1500 ger\n1505 $erda\n2051 10.1515/spircare-2018-0078\n3000 !51581721X!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [Gillen, Erny] maschinell zugeordnet\n\n4000 Die @Zeit ist mehr wert als der Raum\u201c \u2013 Zeit rein!\n4070 $v8$j2019$a2$p217-217\n4241 Enthalten in!718595513!\n4950 https://doi.org/10.1515/spircare-2018-0078$xR$3Volltext$4ZZ$534\n4950 https://www.degruyter.com/document/doi/10.1515/spircare-2018-0078/html$xH$3Volltext$4ZZ$534\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");

Also wie bei Ihnen. Die Anführungszeichen werden als "\u201c" angegeben. Vor dem Wort "Die" fehlt es aber.
Auch beim Export mit Pica-Single fehlen die Anführungszeichen: 
4000 Die @Zeit ist mehr wert als der Raum“ – Zeit rein!

**Comment by socheres** [comment]
Bitte nochmal testen. Sorry!

**Comment by socheres** [comment]
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1500 fre
1505 $erda
2051 10.15122/isbn.978-2-406-10372-1.p.0009
3000 !870233084!$BVerfasserIn$4aut 
8910 $aixzom$bAutor in der Zoterovorlage [Aragione, Gabriella] maschinell zugeordnet
4000 L' @Antiquité chrétienne dans la RHPR - Remarques sur un siècle de recherches
4070 $v100$j2020$a1$p9-22
4207 Les années 1920-1930 et 1960-1980 marquent un tournant dans l’histoire de la recherche sur l’Antiquité chrétienne, en raison, respectivement, de l’essor de la méthode historico-critique et du renouvellement des études patristiques. Les travaux publiés dans la RHPR contribuent activement aux débats scientifiques de l’époque, tantôt en suivant les modèles épistémologiques existants, tantôt en en suggérant des nouveaux.
4241 Enthalten in!51582447X!
4950 https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-1-100e-annee-n-1-varia-l-antiquite-chretienne-dans-la-rhpr.html$xH$3Volltext$4ZZ$534
4950 https://doi.org/10.15122/isbn.978-2-406-10372-1.p.0009$xR$3Volltext$4ZZ$534
5056 1
5520 |s|André Benoît
5520 |s|Antiquité chrétienne
5520 |s|Eugène de Faye
5520 |s|Pères de l’Église
5520 |s|exégèse patristique
5520 |s|histoire du christianisme ancien
5520 |s|littérature chrétienne ancienne
5520 |s|méthode historico-critique
5520 |s|sciences religieuses
5520 |s|théologie protestante
E* l01
7100 $Jn
8012 ixzs$aixzo

**Comment by IxKo** [comment]
`4000 „Die @Zeit ist mehr wert als der Raum“ – Zeit rein!`

Wird nun richtig mit den Anführungszeichen und dem @-Zeichen ausgegeben.
