### ISSUE TITLE
ISSN 1868-9027 | Byzantinische Zeitschrift | fehlerhafte PPN-Verknüpfung bei Verfassern

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1106]
Bei diesem Aufsatz https://www.degruyter.com/view/journals/byzs/113/1/article-p175.xml
wird der erste Verfasser nicht korrekt verknüpft. Statt PPN 65589229X generiert das System 3000 !65589229!$BVerfasserIn$4aut. Das "X" am Ende wird nicht erfasst.
Analog hier: bei dieser PPN 1729047483 wurde bei der Autorenverknüpfung ursprünglich das "X" am Ende nicht erfasst.
Da es immer wieder auftritt, erspare mir weitere Beispiele, kann man von einem generellen Problem sprechen.
In diesem Fall wird 3000 !78636422!$BVerfasserIn$4aut Löwy. Moritz gefunden statt PPN 78636422X Zahnd, Ueli

**Comment by socheres** [comment]
#1099 gefixt.

**Comment by kdr154** [comment]
Verknüpfung ist nun korrekt.
