### ISSUE TITLE
ISSN 2198-0454  | Verkündigung und Forschung | Rezensionszeitschrift

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1107]
Die Zeitschrift scheint eine reine Rezensionszeitschrift zu sein. D. h. 1131 !106186019!Rezension sollte immer gesetzt werden. Eleganter wäre es, wenn es automatisch gesetzt würde. Aber es gibt Ausnahmen, etwa die Mitteilungen aus dem Herausgeberkreis.

**Comment by IxTheoKm** [comment]
In den meisten Fällen sind es auch Literaturberichte, die 1131 !104712805!_Literaturbericht_ erhalten

**Comment by kdr154** [comment]
Das mag schon sein. Aber ich habe meine Zweifel an der Notwendigkeit einer solchen Unterscheidung. Wenn ich mir die alten A-Aufnahmen anschaue, besitzen viele Artikel kein 1131, werden also normale Aufsätze gewertet, obwohl sie eindeutig Rezensionen oder Literaturberichte sind. In der Konsequenz würde es aber bedeuten, dass wir in Zukunft dort auf 1131 Rezension verzichten sollten, wo es sich bei der Besprechung einer oder mehrerer Publikationen lediglich um die Wiedergabe des Inhalts der besprochenen Publikationen handelt, und statt dessen 1131 Literaturbericht vergeben sollten.

**Comment by kdr154** [comment]
Das Rezenionstag wird jetzt bei allen Artikeln vergeben.
