### ISSUE TITLE
ISSN 1936-1351 | American journal of criminal justice | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1112]
Die Keywords werden nicht erfasst. Statt dessen werden bei allen Artikeln dieselben Pseudo-Keywords "general" und "Criminology and Criminal Justice" ausgegeben, unabhängig davon, ob der Artikel welche enthält oder nicht.

![grafik](https://user-images.githubusercontent.com/29707105/92698568-d97af700-f34c-11ea-85c5-3feefc1b3134.png)

Dieser Artikel besitzt z. B. welche, die im Abschnitt "About this Article" zu finden sind, aber nicht erfasst werden:
https://link.springer.com/article/10.1007/s12103-020-09518-4
Dieser keine:
https://link.springer.com/article/10.1007/s12103-020-09527-3

**Comment by hlindeboom** [comment]
Die Korrektur sollte auf nu sein.

**Comment by kdr154** [comment]
Die richtigen Keywords werden nun erfasst.
