### ISSUE TITLE
ISSN 1936-1351 | American journal of criminal justice | Pseudo-Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1113]
Sofern kein Abstract vorhanden ist, werden die ersten Worte des Textes in ein Abstract übernommen:
https://link.springer.com/article/10.1007/s12103-020-09527-3

![grafik](https://user-images.githubusercontent.com/29707105/92699627-201d2100-f34e-11ea-907c-11ccd0eeaf17.png)

Bei den Artikeln, die eines enthalten, sieht es korrekt aus.

**Comment by hlindeboom** [comment]
Die Korrektur sollte jetzt auf nu sein.

**Comment by kdr154** [comment]
Stimmt
