### ISSUE TITLE
ISSN 2007-2023 | Archivos de criminología, seguridad privada y criminalística | Ergebnis unbrauchbar

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1114]
Es ist mir nicht gelungen herauszufinden, wo und was der Harvester unter dieser URL https://dialnet.unirioja.es/servlet/revista?codigo=17952 der Archivos de criminología, seguridad privada y criminalística herausgepickt hat, die Daten sind in jedem Fall nicht zu gebrauchen. 
Es findet keine Zuordnung zu einem Heft statt, in den allermeisten Fällen handelt es sich bei den Records nicht um Aufsätze, sondern um Elemente die im Zusammenhang mit der Platform Dialnet und der Publikation stehen. Manchmal vielleicht auch nicht. So wie bei einem Record, den man als Artikel einer Publikation ansehen kann: 
https://dialnet.unirioja.es/servlet/tesis?codigo=282524
Wo der jedoch auf Dialnet zu verorten ist, auch das ist mir auf die Schnelle nicht gelungen herauszufinden. Es handelt sich um eine Referenz zu dieser Dissertation: https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjz-sLGmN7rAhUN-aQKHeG2ARMQFjADegQIBhAB&url=https%3A%2F%2Fidus.us.es%2Fbitstream%2Fhandle%2F11441%2F94150%2FTesis%2520Doctoral%2520Paloma%2520Gallego%2520Yerga_18_12_19_Definitiva.pdf%3Fsequence%3D1%26isAllowed%3Dy&usg=AOvVaw2361ihfAbM8Gf616WWt_qZ
Ob das ein Thema ist, das im Zusammenhang mit der Publikation steht, die geharvestet werden soll, kann ich nicht sagen. Und das ist noch das Beste. Andere records sehen etwa so aus:

![grafik](https://user-images.githubusercontent.com/29707105/92708654-96be1c80-f356-11ea-965b-b50497530afc.png)

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Viel besser. Was noch verbesserungswürdig ist sind die Abstracts. Es gibt eine spanische und eine englische Version. Beide werden unter einem zusammengefasst. Sie in zwei Tags 520 zu trennen wäre gut.

**Comment by hlindeboom** [comment]
Die Änderung wurde auf nu eingespielt. Abstracts sollten jetzt getrennt erfasst werden.

**Comment by kdr154** [comment]
Ist der Fall. Danke!
