### ISSUE TITLE
ISSN 2254-2043 | Boletín criminológico | XML-Datei leer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1115]
#1166 ist hierzu dublett.

Die Ergebnisdatei ist leer. Folgende Meldung nach Abschluss des Harvesting:

![grafik](https://user-images.githubusercontent.com/29707105/92717002-dc331780-f35f-11ea-8e71-5a46049b88d7.png)

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Daten werden erfasst. Es ist jedoch ein Fehler darunter. Die Artikelnummerierung wird als Bandzählung ausgegeben. Das sollte nicht sein. Bsp.:
https://revistas.uma.es/index.php/boletin-criminologico/article/view/10085/10053

Wenn, dann ist die Nummerzählung (No ...) so etwas wie eine fortlaufende Heftzählung, die man in marc 936$e erfassen könnte, vielleicht sogar sollte.
http://www.boletincriminologico.uma.es/lista_boletines.php?edicion=2020

![grafik](https://user-images.githubusercontent.com/29707105/100362454-baab0900-2ffb-11eb-9d8d-633d2f0e4245.png)

**Comment by hlindeboom** [comment]
Die Änderung ist jetzt auf nu. Die Nummerzählung wird nun im Volume Feld (936$d) erfasst. Der vorherige Inhalt dieses Feldes befindet sich nun im Issue Feld (936$e).

**Comment by kdr154** [comment]
Sie haben es jetzt so gemacht, wie ich es beschrieben habe. Aber ich finde es nicht richtig. Tut mir leid. Mea culpa. Es erscheinen doch mehrere Hefte im Jahr. 1/2020 ist Heft 1im Jahr 2020. 2/2020 Heft 2 im Jahr 2020 usw. Demzufolge kann No189, No190 usw. nicht auch noch die Heftzählung sein, sondern muss der Band sein. Ich würde aber gerne beides beibehalten. Aber es genau andersherum aufbauen, als wie es jetzt ist. 
Also folgendermaßen:

```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">189</subfield>
<subfield code="e">1</subfield>
<subfield code="j">2020</subfield>
</datafield>

<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">190</subfield>
<subfield code="e">2</subfield>
<subfield code="j">2020</subfield>
</datafield>

<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">191</subfield>
<subfield code="e">3</subfield>
<subfield code="j">2020</subfield>
</datafield>

```
usw.

**Comment by hlindeboom** [comment]
Kein Problem. Die Änderung wurde auf nu eingespielt, die Zahlen sollten jetzt wie gewünscht eingetragen werden.

**Comment by kdr154** [comment]
Danke. So gefällt es mir!
