### ISSUE TITLE
ISSN 0798-9598 | Capítulo criminológico | Überflüssige Records

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1116]
Es werden viele unnötige Artikel (records) erfasst, die irrelevant sind. Die Base-Url auf nu http://produccioncientificaluz.org/index.php/capitulo/index verweist auf die Startseite, auf der sich dann auch der Band befindet, der geharvestet wird, Band 26.1
Dieser Band enthält 8 Aufsätze, es werden aber 52 records erstellt, dabei die Aufsätze 2 mal. Die anderen scheinen sich mir auf den Links zu basieren, die auf der Seite zu finden sind, wie die keywords oben links, Autoreninformationen ...

**Comment by hlindeboom** [comment]
Ein neuer Translator wurde auf nu eingespielt, die Artikel sollten dort nun richtig erfasst werden.

**Comment by kdr154** [comment]
Stimmt. Es sind nun 8. Ändere das Label zu Zotero_Auto_RSS. Die Zeitschrift bleibt aber problematisch. Siehe #1117
