### ISSUE TITLE
ISSN 0798-9598 | Capítulo criminológico | Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1117]
Bei allen relevanten Datensätzen des Sets, d. h. bei allen Aufsätzen, lautet das Erscheinungsjahr in Marc 936 $j und Marc 773 $g 2015. Eine solche Jahresangabe ist auf der Seite des Heftes, 26.1 nicht zu finden. Dieses ist wie man hier sehen kann: https://produccioncientificaluz.org/index.php/capitulo/issue/archive 1998 erschienen. Das Jahr 2015 ist, wie man am Quelltext unschwer erkennen kann, das Publikationsjahr des Onlinedokuments. Das bedeutet, dass die Angaben zur übergeordneten Einheit immer nicht korrekt sein werden. Und auch Pica 1100, das Erscheinungsjahr, folglich auch die Sortierfolge in der WinIBW, werden falsch werden. 

Die überflüssigen Records vernachlässige ich in diesem Zusammenhang.

**Comment by hlindeboom** [comment]
Soweit ich verstanden habe ist in diesem Fall 1998 das Berichtsjahr und 2015 das Erscheinungsjahr. Trotz der großen Abweichung soll meines Wissens laut #1078  auf das frühere Erscheinungsjahr verzichtet werden. 
Wie möchten Sie, dass hier weiter verfahren wird?

**Comment by kdr154** [comment]
Auf das Erscheinungsjahr soll nicht verzichtet werden, sondern das Berichtsjahr soll auch zugleich das Erscheinungsjahr sein oder werden. Müsste in diesem Fall demzufolge auch 1998 sein. Aber ich sehe keine andere Möglichkeit, dies abzugreifen, als aus dem PDF-Dokument. Darüber hinaus ist mir unklar, woher der Harvester die Angabe 2015 bezieht. Das Archiv listet nur die Ausgaben bis 2010, die Ausgabe auf der Startseite ist die, deren Daten erfasst werden, also 26,1. Diese Ausgabe fehlt im Archiv. Im übrigen wird RSS abgefragt und nicht gecrawlt. Ändere das Label. In meinen Augen ist diese Zeitschrift für das vollautomatische Verfahren nicht geeignet.

**Comment by hlindeboom** [comment]
In der Tat ist es relativ schwierig an die Jahreszahlen zu kommen. Die Frage wäre, ob man die Artikel über https://dialnet.unirioja.es/servlet/revista?codigo=7082 mit dem Dialnet Translator erfasst. Hier finden sich allerdings lediglich die Artikel von 2005-2010 jedoch mit den korrekten Daten, d.h. die restlichen müsste man einmalig von Hand erfassen.
Der Harvester bezieht die Jahresangabe aus den meta tags des Quelltexts der Webseite, vermutlich wurden im Jahre 2015 noch Anpassungen an den Artikeln durchgeführt.

**Comment by kdr154** [comment]
Diese ZS kommt für das vollautomatische Verfahren nicht in Frage. Unklar, on nach 2010 überhaupt noch weitere Ausgaben erschienen sind. Die UB Tü hat den neuesten Bestand in Deutschland (bis 2009) und die ZS abbestellt.
Bitte nicht mehr weiter verfolgen.
Von den Fachreferenten müsste entschieden werden, wie mit dieser ZS verfahren werden soll, sofern sie in einem der Anträge der Kriminologie enthalten ist.

**Comment by socheres** [comment]
Die Zeitschrift auf OJS Plattform ist vermutlich kostenpflichtig nur mit Anmeldung einsehbar: https://produccioncientificaluz.org/index.php/capitulo/login Ich schließe daher dieses Issue.
