### ISSUE TITLE
ISSN 0798-9598 | Capítulo criminológico | Quelle und überhaupt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1118]
Fraglich, ob diese Quelle für aktelle Ausgaben geeignet ist. Der letzte Band der auf den Seiten von https://produccioncientificaluz.org/index.php/capitulo/index 38,3 aus dem Jahr 2010. 
Etwas neueres habe ich nicht gefunden. Daraus folgt die Frage, ob diese Zeitschrift überhaupt als Bestandteil der Antragsliste Krimdok verbleiben sollte.

**Comment by jriedl** [comment]
@socheres @KStelzel: Wie soll hier weiter verfahren werden?

**Comment by kdr154** [comment]
Im Augenblick bekommt man lediglich Zugriff auf die Anmeldeseite.
