### ISSUE TITLE
ISSN 0798-9598 | Capítulo criminológico | Seitenangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1119]
Bei den relevanten Sätzen, den Artikeln, beträgt der Umfang der Aufsätze immer 1 Seite; Marc 936 $e ist immer 1. Auf der Webseite und meiner Ansicht nach auch in den Metadaten, gibt es keine Umfangsangaben. Diese sind nur im PDF-Dokument zu finden.

**Comment by hlindeboom** [comment]
Ein neuer Translator wurde auf nu eingespielt, die Issue Nummern sollten nun richtig erfasst werden.

**Comment by kdr154** [comment]
So ist es richtig. Auf Seitenangaben muss verzichtet werden, da nur im PDF vorhanden.
