### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Irrelevante Datensätze

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1120]
Geharvestet werden nur irrelevante Datensätze, kein einziger Aufsatz.
Das ist die Startseite: https://ojs.ehu.eus/index.php/eguzkilore/index
E-ISSN nicht vorhanden.

**Comment by jriedl** [comment]
Bitte diese Startseite so in Zeder hinterlegen.

**Comment by kdr154** [comment]
steht jetzt in p_zot2

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Es wird geharvestet. Seitenzahlen lassen sich hier wohl auch nicht abgreifen. Aber es gibt ein Problem mit der Sprache. Dazu ein extra Issue.
