### ISSUE TITLE
ISSN 2340-0080 | Estudios penales y criminologicos | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1121]
Die Rezension, die das getestete Heft enthält, wird nicht als solche erkannt; 655 fehlt.
https://revistas.usc.gal/index.php/epc/issue/view/416
https://revistas.usc.gal/index.php/epc/article/view/6508

**Comment by jriedl** [comment]
Nach den dem nächsten Pull der zotero_harvester.conf auf nu.

**Comment by kdr154** [comment]
Rezension wird getagt
