### ISSUE TITLE
ISSN 2066-2203 | European journal of probation | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1123]
Die Rezensionen werden nicht mit 655 getagt.
https://journals.sagepub.com/toc/ejpa/12/2

**Comment by hlindeboom** [comment]
Sollte jetzt soweit stimmen.

**Comment by kdr154** [comment]
Gelöst

**Comment by socheres** [comment]
@jriedl @hlindeboom bei SAGE bitte Änderungen nach commit https://github.com/ubtue/zotero-translators/pull/134 durch ubtue/master vornehmen, sonst läuft der Code auseinander.

**Comment by socheres** [comment]
wenn auf benu ok ist, dann bitte issue schließen. Die Änderung wird nach merge dann auch auf Nu eingespielt.

**Comment by kdr154** [comment]
schließe
