### ISSUE TITLE
ISSN  1874-6306  | Human rights review | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1124]
Rezensionen werden nicht als solche mit 655 getagt. Erhalten dafür aber das Schlagwort "Book  Reviews"
https://link.springer.com/journal/12142/volumes-and-issues/21-3
https://link.springer.com/article/10.1007/s12142-020-00601-1

![grafik](https://user-images.githubusercontent.com/29707105/93076898-55947800-f688-11ea-83d8-395bbe020b63.png)

Bitte 650 entfernen und 655 ergänzen.

**Comment by IxKo** [comment]
Sie erhalten außerdem das Pseudo-Abstract "null".
Das müsste auch entfernt werden.

**Comment by mtrojan-ub** [comment]
Kein Harvester-Problem + beides aktuell nicht mehr reproduzierbar. Bereits erledigt?

**Comment by jriedl** [comment]
Kann das Issue geschlossen werden?

**Comment by kdr154** [comment]
Schließe. Alles behoben.
