### ISSUE TITLE
ISSN 0973-5089 | International journal of criminal justice sciences | Irrelevante Datensätze

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1125]
Es werden nur irrelevante Datensätze und keine Aufsätze geharvestet.
http://www.sascv.org/ijcjs/
Beispiel:

![grafik](https://user-images.githubusercontent.com/29707105/93084224-06ecdb00-f694-11ea-8714-0b2decb799a1.png)

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Sieht ebenfalls schon recht gut aus. Die Seitenzahlen fehlen und Rezensionen werden nicht erkannt und getagt.
Rezensionen sind die letzten beiden Aufsätze in dem geharvesteten Heft. Beide beginnen mit "Book review". Das scheint mir ein wiederkehrendes Merkmal zu sein.
http://www.sascv.org/ijcjs/

**Comment by jriedl** [comment]
Für die Seitenzahlen sehe ich keine Lösung, außer man wählt einen Ansatz mit Textextraktion und Seitensegmentierung aus dem PDF, was wohl kein gangbarer Weg ist. Im Bezug auf die Rezensionen müsste ja mittlerweile die globale Rezensionserkennung greifen: Beim globalen Review-Regex (?i)^Book\s+Reviews?$ wurde jetzt das '$' entfernt, um daraus eine einleitende Wendung zu machen. @mtrojan: Falls da etwas dagegen spricht, gibt bitte kurz Bescheid. Rezensionen für diese Zeitschrift sollten also voraussichtlich morgen auf nu automatisch erkannt werden.

**Comment by kdr154** [comment]
Rezensionen: Test mit additional config erfolgreich.
@socheres Was machen wir mit den Seitenzahlen?

**Comment by socheres** [comment]
ob die Seitenzahlen nachträglich händisch erfasst werden soll oder nicht, soll @KStelzel @thefass entscheiden.

**Comment by kdr154** [comment]
Label ready for testing entfernen?

**Comment by jriedl** [comment]
@socheres Würde sich das auf eine Nachbearbeitung beziehen? Können wir prinzipiell das Issue schließen und die Zeitschrift für den Upload freigeben?

**Comment by thefass** [comment]
Bei den Seitenzahlen scheint es ein schönes Chaos zu geben.

Beispiel:
Das Editorial von 
_XI Issue, IJCJS vOLUME: 6 ISSUE 1 & 2 january - june / July - december 2011 (Combined Issue)  
Editorial
SASCV 2011: Special Conference Issue of the First International Conference of the South Asian Society of Criminology and Victimology (SASCV)
K. Jaishankar_ 
hat die Seitenzahl 12-14

Der sich anschließende Aufsatz hat die Seitenzahl 297-308
_ARTICLES
Khap Adjudication in India: Honouring the Culture with Crimes
Kavita Kachhwaha_

Ich schlage vor, die Seitenzahlen erstmal nicht zu erfassen.

Vermutlich wäre es sinnvoll, im neuen Jahr, dass Du @KStelzel einmal Kontakt mit den Herausgebern aufnimmst. Zwei Dinge sollten angesprochen werden:

1. Seitenzahlen
richtige Reihenfolge und einstellen auf der Website
2. DOI
die lösen nämlich für die Hefte IJCJS vOLUME: 14 ISSUE 1 january - june 2019  und IJCJS vOLUME: 14 ISSUE 2 July - december 2019 nicht auf!

**Comment by thefass** [comment]
sorry @jriedl Kam gerade mit der Funktion von assignees nicht zu Recht

**Comment by KStelzel** [comment]
Ja, okay.

**Comment by kdr154** [comment]
Hier gibt es für uns nichts mehr  zu tun.
