### ISSUE TITLE
ISSN 0974-2891 | International journal of cyber criminology | Irrelevante Datensätze

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1126]
Es werden nur irrelevante Datensätze und keine Aufsätze geharvestet.
http://www.cybercrimejournal.com/index.html
Beispiel:

![grafik](https://user-images.githubusercontent.com/29707105/93085125-61d30200-f695-11ea-94a6-98ca2be07dca.png)

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
War davon ausgegangen, dass im Rahmen gestrigen des Updates die zotero_harvester.conf bereits aktuell ist. Wurde aber wohl erst abends im Rahmen des automatischen Updates eingespielt. D.h. es werden jetzt genau die 21 Datensätze erkannt.

**Comment by kdr154** [comment]
Dann schließe ich
