### ISSUE TITLE
ISSN 0958-5184 | Journal of forensic psychiatry & psychology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1127]
Rezensionen werden nicht mir 655 getagt, bekommen aber ein Schlagwort Book Reviews in 650:
https://www.tandfonline.com/toc/rjfp20/31/4?nav=tocList
https://www.tandfonline.com/doi/full/10.1080/14789949.2020.1770835

![grafik](https://user-images.githubusercontent.com/29707105/93099100-ef1f5200-f6a7-11ea-96aa-5a8ed4c38414.png)

650 entfernen und 655 ergänzen.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Passt.
