### ISSUE TITLE
ISSN 1868-7261 | Philosophische Rundschau (PhR) | Abbruch des Downloads

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1131]
Dieser eine Artikel lässt sich nicht spreichern, weder im Single- noch im Multi-DL:
https://www.mohrsiebeck.com/artikel/kulturzeitdaemmerung-101628phr-2020-0027?no_cache=1
Fehlermeldung: Es ist ein Fehler aufgetreten beim Speichern mit Mohr Siebeck ...
Bei allen anderen von diesem Heft gibt es keine Probleme. Ein anderer Artikel ist etwa: 
https://www.mohrsiebeck.com/artikel/zur-scheinrationalitaet-der-krise-101628phr-2020-0010?no_cache=1
Möglicherweise liegt der Fehler darin begründet, dass dem DOI im ersten Fall kein Link unterliegt, im zweiten aber schon. Oder aber, dass im ersten Fall ein Verfasser fehlt.

**Comment by kdr154** [comment]
Nun bekomme ich zwar keine Fehlermeldung mehr, gespeichert wird der Artikel aber trotzdem nicht, obwohl es so aussieht.

![grafik](https://user-images.githubusercontent.com/29707105/95044238-3913ba80-06df-11eb-81aa-1a1b94917fab.png)

Dieses Fenster bleibt solange geöffnet bis man die Seite schließt oder neu lädt.

**Comment by socheres** [comment]
mit "COins"-Translator lässt sich der Aufsatz auch nicht herunterladen. Daher liegt das Problem woanders. Ich schließe.
