### ISSUE TITLE
ISSN 0148-3331 | Christianity & literature | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1132]
Die Aufsätze werden im Single- und Multi-DL als Webseite in Zotero übertragen. Bei beiden Translatoren, die angeboten werden: Project Muse und Embedded Metadata.

Hier: https://muse.jhu.edu/article/764673

so:

![grafik](https://user-images.githubusercontent.com/29707105/93869683-6a968a00-fccc-11ea-8533-509bf4b7c8c7.png)

**Comment by socheres** [comment]
@kdr154 könnten Sie gleich nochmal testen?

**Comment by kdr154** [comment]
Immer noch so.

**Comment by socheres** [comment]
Project Muse Seite bietet keine Embedded Metadata mehr an. Das ist aber sehr ungewöhnlich!

**Comment by kdr154** [comment]
Im halbautomatischen Verfahren bei Muse werden immer noch keine Ausätze, sondern Webseiten erkannt.

**Comment by IxKo** [comment]
Nun funktioniert es und sogar gut!
DOI gibt es nicht, oder ich bin blind.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/1202#issuecomment-728982240

**Comment by socheres** [comment]
Ich schließe dieses Issue, da es noch offene Issue zu Muse gibt.
