### ISSUE TITLE
ISSN 1553-3913 | Journal of Feminist Studies in Religion | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1133]
Aufsätze werden im Single- und Multi-DL als Webseiter übertragen. Translatoren Project Muse und Embedded Metadata.
Vgl. #1132

**Comment by kdr154** [comment]
Weiterhin der Fall

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/1132#issuecomment-702703555

**Comment by kdr154** [comment]
Gefixt
