### ISSUE TITLE
ISSN 1695-0194 | Revista electrónica de ciencia penal y criminología | irrelevante Daten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1135]
Erfasst werden keine Aufsätze, sondern die Links auf der rechten Seite.
http://criminet.ugr.es/recpc/

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Sieht schon ganz gut aus, wenn man mit Try URL einzelne Hefte harvestet. Es fehlen die Seitenzahlen. Die sind auf den Seiten nicht zu erkennen, sondern nur Artikelnummern.
Bei einem Try Crawling der Zeitschrift fehlen zusätzlich Jahr und Band.

**Comment by jriedl** [comment]
Da das ein reines EJournal zu sein scheint, existieren offenbar keine Seitennummern. Wenn ich "try crawl" auf nu ausführe, werden "issue" und "year" nach 936$d und 936$j übernommen. Ist das so nicht korrekt?

**Comment by kdr154** [comment]
Das ist korrekt so.

**Comment by jriedl** [comment]
Können wir dann hier noch etwas machen?

**Comment by kdr154** [comment]
Nein, ich schließe
