### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | irrelevante Datensätze

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1136]
Erfasst werden auch Links, die verstreut auf der Seite zu finden sind.
https://reic.criminologia.net/index.php/journal
etwa:

![grafik](https://user-images.githubusercontent.com/29707105/93893261-b9a0e700-fced-11ea-8ad5-c85386707254.png)

**Comment by hlindeboom** [comment]
Sollte jetzt funktionieren.

**Comment by kdr154** [comment]
Gelöst
