### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Mehrfacherfassung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1137]
https://reic.criminologia.net/index.php/journal
Alle Aufsätze werden zweimal erfasst.
Das scheint mir darauf zurückzuführen zu sein, dass die Seiten in zwei Sprachen angeboten werden, auf Spanisch und auf Englisch. Dabei scheint es mir das Abstract zu sein, dass diese doppelte Erfassung auslöst. Die jeweils zweimal erfassten Aufsätze unterscheiden sich lediglich dadurch, dass das Abstract einmal auf Englisch und einmal auf Spanisch erfasst wird. Alle anderen Elemente wie Titel und Keywords sind in beiden Fällen Spanisch, obwohl sie, wenn man die Sprache Englisch einstellt, auch Englisch sind. 
Beispiel:
Das ist die englische Fassung:

![grafik](https://user-images.githubusercontent.com/29707105/93974475-23fd6a00-fd76-11ea-9f95-d668f46aadb8.png)

das die spanische:

![grafik](https://user-images.githubusercontent.com/29707105/93974548-4099a200-fd76-11ea-8b53-60bc39a93b3e.png)

**Comment by hlindeboom** [comment]
Sollte jetzt funktionieren.

**Comment by kdr154** [comment]
gelöst
