### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Spanische Namen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1138]
Die Erfassung der spanischen Doppelnamen bei Personen ist nicht korrekt.
Hier: https://reic.criminologia.net/index.php/journal/article/view/299
wäre statt `<subfield code="a">Jiménez, María Verónica Jimeno</subfield>`
in 100 korrekt `<subfield code="a">Jimeno Jiménez, María Verónica</subfield>`
und statt `<subfield code="a">López, María José Cantero</subfield>`
in 700  `<subfield code="a">Cantero López, María José</subfield>`

**Comment by hlindeboom** [comment]
Sollte jetzt funktionieren.

**Comment by kdr154** [comment]
Scheint mir zu stimmen.
