### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Resumen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1139]
In der spanischen Fassung des Abstracts kann der Begriff "Resumen" am Beginn entfallen.

![grafik](https://user-images.githubusercontent.com/29707105/93974860-c0277100-fd76-11ea-9b24-d7f880b1dcc9.png)

**Comment by hlindeboom** [comment]
Sollte jetzt funktionieren.

**Comment by kdr154** [comment]
Nun wurde offensichtlich zwischen den beiden zur Vefügung stehenden Sprachen, Englisch und Spanisch, geswitcht. Bei Abstract wird die Sprache Englisch ausgewählt, beim Titel und den Keywords Spanisch. Spricht nichts dagegen. Der Begriff "Resumen" oder "Abstract" ist beim Abstract nicht mehr vorhanden. Wichtig ist in jedem Fall, dass in 041 "spa" steht, den die Texte sind in Spanisch geschrieben. Das kann man dem Hinweis auf den Button PDF entnehmen.
