### ISSUE TITLE
ISSN 0039-3207 | Studia Liturgica | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1141]
Weder im Single- noch im Multi-DL werden Keywords übertragen.
https://journals.sagepub.com/toc/stla/50/2

**Comment by kdr154** [comment]
Weder noch. Im Multi wird kein Sage Translator angeboten. Es wird statt dessen Atypon genommen. Im Single führt die Verwendung vom Sage-Translator sogar zu einem Fehler.

**Comment by socheres** [comment]
Ihre Datei "Sage Journals.js" auf X:\Fachinformationsdienste\Zoterobearbeitung\zotero_ro\translators habe ich nun manuell aktualisiert. Eigentlich soll durch Ausführung von Batch-Datei "Translator_Aktualisierung.bat" der Sage-Translator vom Ausgangsordner (Master) in allen anderen übertragen werden. Nur bei Ihnen wird die Datei nicht überschrieben. Können Sie bitte Zotero+Translator aktualisieren und testen.

**Comment by kdr154** [comment]
Sieht jetzt gut aus.

**Comment by socheres** [comment]
Ich lege einen neuen Issue zu dem o.g. Problem an.
