### ISSUE TITLE
ISSN 1552-8448 | Violence against women – An international and interdisciplinary journal | Überschrift Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1142]
Die Überschrift "Keywords" wird beim ersten Schlagwort Bestandteil des Schlagworts. Das sollte unterdrückt werden.
https://journals.sagepub.com/doi/full/10.1177/1077801220942848

Vorlage:

![grafik](https://user-images.githubusercontent.com/29707105/93993975-aa727580-fd8f-11ea-9d66-33f80592fc5a.png)

auf nu:

![grafik](https://user-images.githubusercontent.com/29707105/93994146-daba1400-fd8f-11ea-845d-0aaf3e8c2a0e.png)

**Comment by mtrojan-ub** [comment]
Auf benu aktuell nicht mehr reproduzierbar. Evtl ein Translator Problem das schon behoben wurde?

**Comment by kdr154** [comment]
Wahrscheinlich über #1195
