### ISSUE TITLE
ISSN 1867-1756 | Race and social problems | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1143]
Es werden immer dieselben Keywords ausgegeben, die keine sind: "Personality and Social Psychology" und "Social Work":

![grafik](https://user-images.githubusercontent.com/29707105/93999016-9c275800-fd95-11ea-8970-8ac8ed13fa1d.png)

Z. T. ist einer der Begriffe, Social Work, gar nicht auf der Seite zu finden. Etwa hier:
https://link.springer.com/article/10.1007/s12552-020-09295-z

Im Gegenzug werden die Keywords, die wirklich welche sind, gar nicht erfasst. Bei dem oben genannten Artikel gibt es gar keine. Bei anderen befinden sie sich im Abschnitt "About this article".
Etwa hier: 
https://link.springer.com/article/10.1007/s12552-020-09290-4
https://link.springer.com/article/10.1007/s12552-020-09290-4#article-info

Auch hier steht in den Marc 650-Feldern nur "Personality and Social Psychology" und "Social Work"

**Comment by mtrojan-ub** [comment]
Im HTML Code der Seite sieht man die keywords in den Meta headern:

https://link.springer.com/article/10.1007/s12552-020-09295-z
![grafik](https://user-images.githubusercontent.com/26873381/97715101-46477d80-1ac2-11eb-9f54-de97d4b4ab09.png)

Die Website liefert also die unbrauchbaren Keywords selbst.

**Comment by kdr154** [comment]
Sollte man dann über die harvester.conf lösen?

**Comment by jriedl** [comment]
Translator ist angepasst. Sollte behoben sein.

**Comment by kdr154** [comment]
Sieht jetzt gut aus.
