### ISSUE TITLE
ISSN 0029-4845 | Nouvelle revue theologique | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1146]
Abstracts gibt es in zwei Sprachen, erfasst wird aber nur eines.
https://www.cairn.info/revue-nouvelle-revue-theologique-2020-4-page-529.htm?contenu=resume

**Comment by socheres** [comment]
Bitte im Einzel-DL testen.

**Comment by kdr154** [comment]
Für Single-DL gelöst.
