### ISSUE TITLE
ISSN 0771-7776 | Sacris Erudiri | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1152]
https://www.brepolsonline.net/toc/se/2019/58
Im Multi-DL sind die Daten insgesamt unzulänglich:

![grafik](https://user-images.githubusercontent.com/29707105/94422979-31589100-0188-11eb-992f-88c7625f8431.png)

Band, Seiten, ISSN, Abstracts

**Comment by socheres** [comment]
keine Embedded Metadata auf der Webseite beim Multi. Beim Einzel-DL nur für Autor, Titel.

**Comment by IxKo** [comment]
Daten sehen beim Multi-DL nun gut aus.
![image](https://user-images.githubusercontent.com/57000004/141976318-04998434-c0f9-49b8-ae20-e7028bee35f4.png)

Der OA-Artikel wird jedoch noch nicht als LF gekennzeichnet:
https://www.brepolsonline.net/doi/abs/10.1484/J.SE.5.119450

**Comment by IxKo** [comment]
LF wird nun erkannt.
Beim Single-Import wird allerdings vor das einzige Abstract \n4207 erzeugt:
![image](https://user-images.githubusercontent.com/57000004/143040765-2b79e5bc-711c-4f63-a863-ccf3d810a52f.png)

**Comment by IxKo** [comment]
Fehler ist behoben.
