### ISSUE TITLE
ISSN 2340-0080 | Estudios penales y criminologicos | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1153]
**URL**
https://doi.org/10.15304/epc.39.6039

**Ausführliche Problembeschreibung**
Bei diesem Artikel werden die Keywords alle in einem Feld geschrieben, da diese hier nicht mit einem Komma, sondern mit einem Punkt getrennt worden sind.

**Comment by jriedl** [comment]
Punkt-seprarierte Keywords ebenso in den Metatags der Seite. Prinzipiell könnte man natürlich auch den Punkt als Trennzeichen verwenden, das kann aber zu unerwünschten Seiteneffekten führen.

**Comment by socheres** [comment]
wenn der Punkt in Keywords-Sektion ausschließlich für Trennzeichen verwendet wird, dann sehe ich kein Problem den Punkt zusätzlich als Trennzeichen zu verwenden.

**Comment by jriedl** [comment]
Klar, für diese Zeitschrift ist das so. Die Änderung würde sich ja aber auf sämtliche OJS-Zeitschriften beziehen und hier würde ich Allgemeinen nicht mehr davon ausgehen, dass das erwünschte Ergebnis geliefert wird.

**Comment by socheres** [comment]
du kannst beide Trennzeichen nur für diese Zeitschrift anwenden, indem du item.issn = xxxx-xxxx mit in die If-Bedingung übernimmst.

**Comment by jriedl** [comment]
Sollte auf nu behoben sein.

**Comment by IxKo** [comment]
Ist noch nicht behoben:
![image](https://user-images.githubusercontent.com/57000004/100598538-285a7c00-32ff-11eb-9933-31e55c7d777e.png)

**Comment by jriedl** [comment]
Neuer Versuch.

**Comment by IxKo** [comment]
Passt nun.
