### ISSUE TITLE
ISSN 2340-0080 | Estudios penales y criminologicos | fehlende Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1154]
**URL**
https://revistas.usc.gal/index.php/epc/issue/view/416

**Ausführliche Problembeschreibung**
Die Abstracts ("Resumen") werden nicht erfasst.

**Comment by jriedl** [comment]
520 Felder jetzt vorhanden.

**Comment by IxKo** [comment]
Sieht nun gut aus.
