### ISSUE TITLE
ISSN 2066-2203 | European journal of probation | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1155]
**Bsp.-URL**
https://journals.sagepub.com/doi/full/10.1177/2066220320927353

**Ausführliche Problembeschreibung**
Beim jeweils ersten Schlagwort wird die Überschrift "Keywords" vorangestellt.

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by IxKo** [comment]
Danke, ist behoben.
