### ISSUE TITLE
ISSN 1552-6720  | Homicide studies | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1156]
**Bsp.-URL**
https://doi.org/10.1177/1088767919896391

**Ausführliche Problembeschreibung**
Beim ersten Schlagwort wird die Überschrift "Keywords" vorangestellt.

![grafik](https://user-images.githubusercontent.com/57000004/94441511-2101df80-01a3-11eb-83c9-0503ca90d3f3.png)

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by IxKo** [comment]
> 
> 
> Sollte behoben sein.

Stimmt!
