### ISSUE TITLE
ISSN 1874-6306 | Human rights review | fehlender Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1157]
**URL**
https://link.springer.com/article/10.1007/s12142-020-00582-1

**Ausführliche Problembeschreibung**
Beim Jahrgang 21 (2020), Heft 2 wurde ein Artikel nicht erfasst.

Dies liegt wahrscheinlich am RSS-Feed. Mit Try URL wird der Artikel nicht ausgeschlossen.

**Comment by jriedl** [comment]
Ja, scheint am RSS zu liegen.
