### ISSUE TITLE
ISSN 1945-1369 | Journal of drug issues | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1158]
**Bsp.-URL**
https://doi.org/10.1177/0022042620917101

**Ausführliche Problembeschreibung**
Dem ersten Schlagwort wird die Überschrift "Keywords" vorangestellt.

**Comment by jriedl** [comment]
Mit angegebener DOI aktuell im Translation Server nicht reproduzierbar. Wahrscheinlich in anderem Zusammenhang gefixt.

**Comment by IxKo** [comment]
Ja, das stimmt, es scheint behoben.
