### ISSUE TITLE
ISSN 1573-2851 | Journal of family violence | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1159]
**Bsp.-URL**
https://doi.org/10.1007/s10896-020-00137-5

**Ausführliche Problembeschreibung**
Es werden immer diesselben Keywords vergeben, anstelle der vorhandenen Artikel-Keywords (unter dem Punkt "About this article" ganz unten).

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by IxKo** [comment]
Passt nun
