### ISSUE TITLE
ISSN 1552-6518 | Journal of interpersonal violence | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1160]
**Bsp.-URL**
https://doi.org/10.1177/0886260517719542

**Ausführliche Problembeschreibung**
Beim ersten Keyword wird die Überschrift "Keywords" vorangestellt.

Übrigens hat es mit Try RSS auf Nu über 26 Minuten gebraucht bis der File erzeugt war.

**Comment by jriedl** [comment]
Mit angebener DOI im Translation-Server aktuell nicht reproduziertbar. Wahrscheinlich in anderem Zusammenhang behoben.

**Comment by IxKo** [comment]
Ja, der Fall scheint behoben.
