### ISSUE TITLE
ISSN 1867-1756 | Race and social problems | fehlende Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1161]
**RSS**
https://link.springer.com/search.rss?facet-content-type=Article&facet-journal-id=12552&channel-name=Race+and+Social+Problems

**Ausführliche Problembeschreibung**
Vom Heft 2 sind nur 3 von insgesamt 8 Artikeln mit Try RSS geharvest worden. 
Im gleichen File waren auch alle Artikel von Heft 3 und 4.

Es liegt womöglich am RSS-Feed, der diese Artikel nicht (mehr) erfasst hat.

**Comment by jriedl** [comment]
Liegt am RSS-Feed.

**Comment by IxKo** [comment]
Ok
