### ISSUE TITLE
ISSN 0004-0452 | Archivo Ibero-Americano | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1163]
https://revistasfranciscanas.org/index.php/ArchivoIberoAmericano/article/view/117

Hier werden auch die Referencias mit ins Abstract übernommen. Es sollte nur das ins Abstract, was auch wirklich Abstract ist.

**Comment by socheres** [comment]
Mit welchem Translator haben Sie heruntergeladen?

**Comment by kdr154** [comment]
Bin mir nicht sicher. Glaube aber Open Journal System Standard im Multi-DL.  Im Single geht nur Open Journal System, Open Journal System steht nicht zur Verfügung. Aber auch hier ist es so.

**Comment by helenanebel** [comment]
Lieber @kdr154 , lieber @socheres ,
mit dem ubtue_OJS-Standard müsste es jetzt gehen, auch die Zusatztitel werden jetzt ergänzt.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Kann man so machen.
