### ISSUE TITLE
ISSN 0521-8195 | Burgense: Collectanea Scientifica | Fehler beim GND-Lookup zum Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1164]
Hier https://dialnet.unirioja.es/servlet/articulo?codigo=7051805
kommmt es wieder zu einem Fehler beim GND-Lookup
Die K10plus-Aufnahme, die erzeugt wird, sieht folgendermaßen aus:

0500 Asn
0501 Text$btxt
0502 ohne Hilfsmittel zu benutzen$bn
0503 Band$bnc
1100 2018$n[2018]
1500 spa
1505 $erda
3000 !1158337078!$BVerfasserIn$4aut
8910 $aixzom$bAutor in der Zoterovorlage [Ferreras, Avelino de Luis] maschinell zugeordnet

4000 ¿Cómo decir "pecado", "gracia" y "salvación"?
4070 $v59$j2018$a1$p183-210
4241 Enthalten in!12953305X!
5056 1
E* l01
7100$Jn
8012 ixzs$aixzo

Der Verfasser, der in Frage kommt, hat die PPN 102200896X
Hier verknüpft das System die GND-PPN und nicht die K10plus-PPN:

005 Tpv6
006 http://d-nb.info/gnd/1158337078
008 piz
011 f
035 gnd/1158337078
040 $erakwb$frswk
043 XA-IT
100 Luis Ferreras, Avelino$cde
400 Ferreras, Avelino de Luis
400 Luis-Ferreras, Avelino$cde
548 $c1995$4datw
550 !104452242!$4berc
550 Dr.$4akad$vDiss. Pontificia Universitas Gregoriana$Z1993
672 La cuestión de la incomprensibilidad de Dios en Karl Rahner. - 1995
798 503727059

**Comment by socheres** [comment]
Jetzt sollte fehlerfrei laufen, da die Lookup-Funktion jetzt allgemeinere Xpath verwendet und immer die erste Nummer (=K10Plus) übernimmt.

**Comment by kdr154** [comment]
Beim 4. Anlauf ist die Verknüpfung nun korrekt
