### ISSUE TITLE
ISSN 2254-2043 | Boletín criminológico | Test Krimdok

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1166]
Dieses Issue behandelt dieselbe Problematik wie #1115 
Bei dieser Zeitschrift kommt es zu einem Bearbeitungsfehler bzw. zu einer leeren XML-Datei.

Im 2. Fall wirft nu folgende Meldung aus:

Queued journal 'Boletín criminológico' | CRAWL @ http://www.boletincriminologico.uma.es/
set download-delay for domain 'www.boletincriminologico.uma.es' to 1000 ms

Downloading URL 2 [Boletín criminológic...] | http://www.boletincriminologico.uma.es/ {7775355030592399660}
Download successful

Crawling URL 1 [Boletín criminológic...] | http://www.boletincriminologico.uma.es/ {7775355030592398699}
crawled 1 URLs, queued 0 URLs for extraction

Zotero Harvester Metrics:
	Journals: 1
		Direct: 0
		RSS: 0
			Skipped: 0
		Crawl: 1
	Crawls: 1
		Successful: 1
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 0
		Successful: 0
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 0
		Skipped (already delivered): 0

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
das mit der leeren XML-Datei ist geklärt, Probleme siehe #1115

**Comment by kdr154** [comment]
Alles erledigt
