### ISSUE TITLE
ISSN 1783-1423 | Ephemerides Theologicae Lovanienses | ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1173]
Hier wird keine ISSN übertragen. Sie steht leider nur auf der Eingangsseite.
https://poj.peeters-leuven.be/content.php?url=journal&journal_code=ETL
https://poj.peeters-leuven.be/content.php?url=article&id=3288274&journal_code=ETL
![grafik](https://user-images.githubusercontent.com/29707105/94900765-db406200-0495-11eb-8eaf-1e919c9b6b47.png)

**Comment by kdr154** [comment]
gelöst

**Comment by IxKo** [comment]
Das Problem tritt wieder auf. Es wird keine ISSN importiert: https://poj.peeters-leuven.be/content.php?url=article&id=3290794

**Comment by socheres** [comment]
Das Problem mit der ISSN ist gelöst, daher schließe ich.
