### ISSUE TITLE
ISSN 0569-9789 | Analecta calasanctiana: publicación semestral religioso cultural y de investigación histórica | Band Ausgabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1174]
https://dialnet.unirioja.es/ejemplar/556162
https://dialnet.unirioja.es/servlet/articulo?codigo=7558938
Die Bandangabe steht im Feld Ausgabe und sollte in das Zotero-Feld Band:

![grafik](https://user-images.githubusercontent.com/29707105/94903009-6707bd80-0499-11eb-96b0-58369a249ab8.png)

**Comment by socheres** [comment]
Abstract hatte auch gefehlt.

**Comment by kdr154** [comment]
Gelöst
