### ISSUE TITLE
ISSN 0569-9789 | Analecta calasanctiana: publicación semestral religioso cultural y de investigación histórica | URL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1178]
https://dialnet.unirioja.es/ejemplar/556162
https://dialnet.unirioja.es/servlet/articulo?codigo=7558938
In Zotero wird ein URL übertragen, dieser wird aber nicht im 4950 im K10plus umgesetzt. Dies ist insofern nicht gut, als dass die  Texte bei Dialnet ab 2019 frei verfügbar sind, auf einer anderen Quelle ab 2015: https://scolopi.org/en/analecta/
![grafik](https://user-images.githubusercontent.com/29707105/95169473-384c5880-07b3-11eb-909c-a18c132a9a2b.png)

Leider gibt es keine ZDB-Aufnahme für eine Online-Ausgabe. Melde dies an die zuständige Stelle im Haus.

**Comment by socheres** [comment]
@IxKo können Sie bitte auch mal testen? Außerdem in solchen Fällen fehlende Kategorie mit copy&paste in WinIBW bitte manuell nacherfassen, bis das Problem behoben ist. PPN  1734774509 fehlt die Kategorie URL.

**Comment by socheres** [comment]
URL wird nicht umgesetzt, da die Zeitschrift nach "A"-Aufnahme katalogisiert werden. Nach der ZDB-Aufnahme diese Zeitschrift nach "O" katalogisieren (Mapping ergänzen etc.).

**Comment by kdr154** [comment]
Alles umgesetzt

**Comment by socheres** [comment]
Können Sie bitte auch die URL-Kategorie in der A-Aufnahme ergänzen?

**Comment by kdr154** [comment]
Unsere Aufnahmen der Aufsätze an der A-Aufnahme habe ich gelöscht.
