### ISSUE TITLE
ISSN 1783-161X | Louvain studies | ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1181]
**URL**
https://poj.peeters-leuven.be/content.php?url=issue&journal_code=LS&issue=1&vol=43

**Ausführliche Problembeschreibung**
Die ISSN wird nicht nach Zotero übertragen.

**Comment by IxKo** [comment]
Passt.

**Comment by IxKo** [comment]
Wird schon wieder nicht übertragen.
Mir scheint, dass dies sehr oft bei Peeters-Zss passiert, wenn ich mir die ehemaligen Issues so ansehe, und auch aus meiner eigenen Erfahrung.

**Comment by socheres** [comment]
da einige der ISSN ein "X" als letzten Buchstaben haben, habe ich den Regex angepasst. Ich denke, dass das Problem mit diesem Fix nicht mehr auftreten wird.

**Comment by IxKo** [comment]
Passt nun, danke!
