### ISSUE TITLE
ISSN 2366-7796 | Zeitschrift für Pädagogik und Theologie | einleitender Doppelpunkt beim Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1183]
Nach dem Wort "Zusammenfassung" folgt noch ein Doppelpunkt. Dieser sollte ebenfalls entfernt werden.
Beispiel:
https://www.degruyter.com/view/journals/zpt/68/4/article-p399.xml?tab_body=abstract

Dieser bleibt beim Export erhalten: \n4207 : In der katholischen

Die Abstracts gibt es in der Regel in zwei Sprachen. Nur nach dem ersten \n4207 entfernen.

**Comment by kdr154** [comment]
Immer noch so.

**Comment by socheres** [comment]
wird beim Exportieren nach Pica entfernt. Können Sie bitte nochmal testen?

**Comment by kdr154** [comment]
Doppelpunkt wird entfernt.
