### ISSUE TITLE
ISSN 1583-0039 | Journal for the Study of Religions and Ideologies | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1186]
Die Endseitenzahl wird beim Speichern in Zotero 2 Mal vergeben:
http://jsri.ro/ojs/index.php/jsri/issue/view/62
http://jsri.ro/ojs/index.php/jsri/article/view/1212

![grafik](https://user-images.githubusercontent.com/29707105/96140389-2cbe0780-0f00-11eb-9f40-16930222c311.png)

**Comment by socheres** [comment]
Laden Sie nochmal den Artikel mit dem "Open Journal Systems Standard.js" im Multi-DL herunter.

**Comment by kdr154** [comment]
Der Translator wird mir trotz updaten, schließen, akualisieren, neu laden... leider nicht angeboten

**Comment by socheres** [comment]
bitte testen.

**Comment by kdr154** [comment]
Im Multi-DL habe ich den Open Journal System Standard.js wieder nicht in der Auswahl. Im Single-DL ist er zwar vorhanden, das Ergebnis ist aber wieder dasselbe.  Die Endseitenzahl wird zweimal vergeben.

**Comment by kdr154** [comment]
Ist weiterhin so. Sowohl Multi als auch Single. Mit dem Open Journal Systems Standard.js Translator.

**Comment by socheres** [comment]
Ich bekomme im Single- sowie Mutli-DL korrekte Datensätze. Aber der OJS Standard wird mir erst an zweiter Stelle angeboten. Die Skripte in allen Benutzerverzeichnisse sind ja auf dem aktuellen Stand. @IxKo können Sie bitte auch testen?

**Comment by kdr154** [comment]
Es ändert sich nichts

**Comment by IxKo** [comment]
Mir wird der Translator sowohl im Singel- (an 3. Stelle) als auch Multi-DL (an 2. Stelle) zur Auswahl gestellt.
In beiden Fällen wird bei mir aber auch die letzte Seitenangabe wiederholt. 

![grafik](https://user-images.githubusercontent.com/57000004/97159488-3f93d000-177b-11eb-94f4-b241e4a8d073.png)

**Comment by kdr154** [comment]
Bei mir hat sich mit dem Open Journal Systems Standard-Translator im Single- wie in Multi nichts geändert.

**Comment by kdr154** [comment]
Sowohl im Multi als auch im Single-DL nun korrekt.
