### ISSUE TITLE
ISSN 1666-7832 | Renaissance and Reformation | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1194]
Beim Single-DL mit dem Open Journal Systems-Translator wird  beim Abstract immer das Wort "ABSTRACT" und ein Freiraum an dem Anfang gestellt:
https://jps.library.utoronto.ca/index.php/renref/article/view/34080

![grafik](https://user-images.githubusercontent.com/29707105/96596505-14c5f980-12ed-11eb-9e88-d5969eda3c03.png)

**Comment by kdr154** [comment]
Leider immer noch so

**Comment by socheres** [comment]
Mit dem "Open Journal Systems Standard.js" im Multi-DL ist das Wort "Abstract" nicht vorhanden. Im Single-DL wird "Open Journal Systems Standard.js"  leider nicht an erster Stelle angeboten.

**Comment by kdr154** [comment]
Ich mache schon immer einen Rechtclick, wenn der erwartete Translator nicht an der obersten Stelle in der Box steht. Aber Open Journal System Standard.js wird mir und wurde mir im Single-DL nie angeboten. Immer nur der Open Journal Systems.js.

**Comment by socheres** [comment]
Sie können im Mulit-DL den Aufsatz herunterladen. @IxKo wird Ihnen "Open Journal System Standard.js" im Single-Dl auch nicht angeboten?

**Comment by IxKo** [comment]
Mir wird "Open Journal System Standard.js" im Single-DlL angeboten. Allerdings wird hier auch das Abstract mit ABSTRACT+Leerzeile erfasst.

**Comment by socheres** [comment]
Ihre Traslators waren nicht aktualisiert. Probieren Sie bitte nochmal.

**Comment by kdr154** [comment]
Bei mir ist es jetzt in Ordnung

**Comment by IxKo** [comment]
Bei mir auch.
