### ISSUE TITLE
ISSN 1461-7404 | Social Compass | Mots-clés, Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1195]
https://journals.sagepub.com/doi/full/10.1177/0037768620922122
Der französische Begriff für Keywords "Mots-clés" überlagert die Keywords und wird in eines der anderen Keywords integriert.
z. B. so:

![grafik](https://user-images.githubusercontent.com/29707105/96707972-de45b880-1398-11eb-9e13-1b432ba55a1d.png)

aus dem beiden Keywords surveys und croyances religieueses wird ein zusammenhängendes gemacht, in das der Begriff Mots-clés integriert wird.

![grafik](https://user-images.githubusercontent.com/29707105/96708074-fe757780-1398-11eb-9826-59088c3b2a46.png)

Dasselbe kommt auch mit dem Begriff Keywords vor:
https://journals.sagepub.com/doi/full/10.1177/0037768620922935

![grafik](https://user-images.githubusercontent.com/29707105/96709603-32519c80-139b-11eb-8b05-26a3b08c8bb1.png)

Ich sehe keine Möglichkeit, dies über die enhancement-maps zu lösen

**Comment by socheres** [comment]
auf benu nun richtig.

**Comment by kdr154** [comment]
Keywords findet sich immer noch im 2. oben erwähnten Artikel von Lecaros:
![grafik](https://user-images.githubusercontent.com/29707105/96726887-bebb8980-13b2-11eb-9a7d-40d1581986b6.png)

**Comment by kdr154** [comment]
Der 2, Fall ist ebenfalls bereinigt.
