### ISSUE TITLE
ISSN 0043-941X | Worship | Fehler beim Download

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1196]
http://web.a.ebscohost.com/ehost/results?vid=12&sid=54859a90-5d03-406c-8c57-5f1c8d4ececd%40sdc-v-sessmgr02&bquery=JN+%22Worship%22+AND+IK+%2220200701+00094+00000%22&bdata=JmRiPXJlaCZ0eXBlPTEmc2VhcmNoTW9kZT1BbmQmc2l0ZT1laG9zdC1saXZl

Hier kommt es sowohl beim Multi- als auch beim Single-DL zu einem Abbruch mit der Fehlermeldung: Es ist ein Fehler aufgetreten beim Versuch....
Der verwendete Translator ist EBSCOhost

**Comment by socheres** [comment]
der angegebene Link führt ins Leere.

**Comment by kdr154** [comment]
Sorry. Dieser sollte permanent sein:
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000003579%26site%3dehost-live

**Comment by socheres** [comment]
Liebe @helenanebel mit folgender url kann man die Seite im Scaffold aufrufen: https://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26AN%3dATLAiACO210125000692%26site%3dehost-live Im Scaffold aber gibt es keine Errormeldung.

**Comment by socheres** [comment]
Multi- und Einzel-DW funktionieren!

**Comment by IxKo** [comment]
Es erscheint keine Fehlermeldung mehr beim Import mit dem Translator ubtue_EBSCO.js.
Die **Sprache** und der **Publikationstitel** werden jedoch nicht importiert. 
Die ISSN wird seltsamerweise ohne Bindestrich importiert, obwohl sie auf Ebsco mit Bindestrich angegeben wird.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das kurz erledigt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke funktioniert nun!
Wobei ich mich frage, wieso hier ein Issue geöffnet worden ist, obwohl die Zs in Zeder auf kat=prüfen steht..
