### ISSUE TITLE
1745-5294 | Journal for the study of the New Testament | besonderes Heft Booklist

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1197]
**URL**
https://journals.sagepub.com/toc/jnta/42/5

**Ausführliche Problembeschreibung**
Die Zs bringt jährlich ein besonderes Heft (Nr. 5) heraus, in welchem die Artikel aus mehreren Review Essays bestehen, die jeweils von unterschiedlichen Autor:innen geschrieben wurden.

Die Artikel müssten alle das Form-Schlagwort **Rezension** erhalten, was evtl. über eine Regex-Regel lösbar wäre. 
Wobei hier eine Regelung mit zwei Ziffern und Punkt möglicherweise zu allgemein ist und es vorkommen könnte, dass auch ein normaler Artikel in einem regulären Heft der Zs mal so beginnt.

Es müsste aber auch der **Rubrikentitel** in Pica-4212 erscheinen. 4212 Rubrikentitel: Booklist JJJJ

**Lösungsansatz**
Die Zs wegen diesem jährlichen Heft nicht in das automatische Verfahren aufzunehmen, wäre schade.
Eventuell könnte hier eine technische Lösung gefunden werden, dass das 5. Heft eines Jahrgangs im Error-Verzeichnis landet und dann intellektuell erfasst werden müsste.

**Comment by IxKo** [comment]
Gleiches trifft auf die Zs Z=540  1476-6728 Journal for the study of the Old Testament  (Sage)

**Comment by socheres** [comment]
Diese Aufsätze sind eine Art Sammelrezension. Wenn in dieser Zeitschrift das DC.Type "other" `<meta name="dc.Type" content="other" />` ausschließlich für solche Aufsätze verwendet werden, könnte man "other" als Selektionsmerkmal für Rezension nehmen. Können Sie bitte dies überprüfen?

**Comment by IxKo** [comment]
Es scheint nur bei diesen Heften vergeben worden zu sein, für alles (Contributors, Series Abbreviations, Index of... etc.)

**Comment by IxKo** [comment]
In Marc-XML müsste es so aussehen:

```
<datafield tag="246" ind1="1" ind2=" ">
<subfield code="i">Rubrikentitel</subfield>
<subfield code="a">Booklist JJJJ</subfield>
</datafield>
```

**Comment by kdr154** [comment]
Das gilt ganz allgemein und nicht nur für diese Sage-Zeitschriften. Wo in $a dann der Titel stehen müsste.

**Comment by socheres** [comment]
auf Benu sieht wie folgt aus. Ist das so korrekt?
```
<record>
<leader>00000nab a22004452 4500</leader>
<controlfield tag="001">
IxTheo#2020-12-04#CB647D4BB538DBB55B8A995026CF3E5BEDF67950
</controlfield>
<controlfield tag="003">DE-Tue135</controlfield>
<controlfield tag="007">cr|||||</controlfield>
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10.1177/0142064X20928711</subfield>
<subfield code="2">doi</subfield>
</datafield>
<datafield tag="040" ind1=" " ind2=" ">
<subfield code="a">DE-627</subfield>
<subfield code="b">ger</subfield>
<subfield code="c">DE-627</subfield>
<subfield code="e">rda</subfield>
</datafield>
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">eng</subfield>
</datafield>
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">1</subfield>
<subfield code="2">ssgn</subfield>
</datafield>
<datafield tag="245" ind1="0" ind2="0">
<subfield code="a">1. New Testament General</subfield>
</datafield>
<datafield tag="246" ind1="3" ind2=" ">
<subfield code="a">Booklist 2020 </subfield>
<subfield code="i">Rubrikentitel</subfield>
</datafield>
<datafield tag="264" ind1=" " ind2=" ">
</datafield>
<datafield tag="520" ind1=" " ind2=" ">
<subfield code="a">, , ,</subfield>
</datafield>
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
<subfield code="0">(DE-588)4049712-4</subfield>
<subfield code="0">(DE-627)106186019</subfield>
<subfield code="2">gnd-content</subfield>
</datafield>
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">In: </subfield>
<subfield code="t">Journal for the study of the New Testament : JSNT</subfield>
<subfield code="x">1745-5294</subfield>
<subfield code="w">(DE-627)341347906</subfield>
<subfield code="g">42 (2020), 5, Seite 1-3</subfield>
</datafield>
<datafield tag="852" ind1=" " ind2=" ">
<subfield code="a">DE-Tue135</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.1177/0142064X20928711</subfield>
</datafield>
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="a">mteo</subfield>
</datafield>
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="a">ixzs</subfield>
<subfield code="2">LOK</subfield>
</datafield>
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="a">zota</subfield>
<subfield code="2">LOK</subfield>
</datafield>
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">42</subfield>
<subfield code="e">5</subfield>
<subfield code="h">1-3</subfield>
<subfield code="j">2020</subfield>
</datafield>
<datafield tag="JOU" ind1=" " ind2=" ">
<subfield code="a">Journal for the study of the New Testament : JSNT</subfield>
</datafield>
<datafield tag="URL" ind1=" " ind2=" ">
<subfield code="a">
https://journals.sagepub.com/doi/full/10.1177/0142064X20928711
</subfield>
</datafield>
<datafield tag="ZID" ind1=" " ind2=" ">
<subfield code="a">539</subfield>
<subfield code="b">ixtheo</subfield>
</datafield>
</record>
```

**Comment by IxKo** [comment]
Der erste Indikator in 246 müsste "1" lauten und nicht "3"
Ich hoffe, es macht keinen Unterschied, in welcher Reihenfolge die Subfields angegeben werden.
Und das Feld wiederholt sich mit leerem Inhalt darauf.

520 (Abstract) muss noch raus, da es kein Abstract gibt, obwohl es einen Link "View Abstract" gibt. Der führt jedoch nur zu einer PDF-Ansicht der ersten Seite.

**Comment by kdr154** [comment]
264 $c, das Jahr für Pica 1000 fehlt.

**Comment by socheres** [comment]
auf Nu ist das Jahr vorhanden.

**Comment by kdr154** [comment]
Es wird immer noch ein überflüssiges Abstract erzeugt:
https://journals.sagepub.com/doi/full/10.1177/0142064X20928815
Etwa so:
![grafik](https://user-images.githubusercontent.com/29707105/101335000-e4c0be80-3878-11eb-8662-cd543baf9798.png)

**Comment by IxKo** [comment]
Sieht auf Nu gut aus.
Da hier ein neues Marc-feld benutzt wird, müsste das in den QA-Settings speziell bei der Zs ergänzt werden.

**Comment by IxKo** [comment]
Ich öffne das Issue wieder, da man noch nicht sagen kann, ob es auch in der Test-DB so eingepsielt wird wie wir es möchten.
Außerdem fehlt in den QA-Settings noch das Feld, oder dürfen wir neue Felder selbst ergänzen?

Die beiden Zss sind noch nicht auf zota gestellt.

**Comment by kdr154** [comment]
@jriedl ein Test mit den QA-Settings auf nu war erfolgreich. Die Änderungen könnten auf ub28 übernommen werden.
Betroffen sind die Zeitschriften 
ISSN 1476-6728 Journal for the study of the Old Testament 
ISSN 1745-5294 Journal for the study of the New Testament

**Comment by jriedl** [comment]
Kann wie vorhin besprochen einfach auf ub28 eingetragen werden.

**Comment by IxKo** [comment]
Der Rubrikentitel wurde bei der heutigen Live-Einspielung nicht in den K10plus übertragen, obwohl die XML-Daten im Default-Ordner so aussehen:

IxTheo#2021-07-06#1B1723EB767D35EDB734B17D084E69D631D839DE
```
<datafield tag="246" ind1="1" ind2=" ">
<subfield code="a">Booklist 2021 </subfield>
<subfield code="i">Rubrikentitel</subfield>
</datafield>
```

Eine Überprüfung von Test-Einspielungen fand scheinbar nicht statt, bevor die Zss auf zota gesetzt wurde. (https://github.com/ubtue/DatenProbleme/issues/1197#issuecomment-783179351)

Es betrifft immer das Heft 5 siehe auch #1197

_Originally posted by @IxKo in https://github.com/ubtue/DatenProbleme/issues/1521#issuecomment-875429092_

**Comment by IxKo** [comment]
Unser Kooperationspartner aus Innsbruck bearbeitet die 5. Hefte momentan manuell und ergänzt 1131 Literaturbericht.
Falls das Problem nicht gelöst werden kann, sollte die Zs. eventuell aus dem zota-Verfahren genommen werden?

**Comment by IxKo** [comment]
Heft 5 scheint nun als Rezensionen eingespielt worden zu sein Allerdings jeder Eintrag aus dem Heft, auch wenn es augenscheinlich keine Rezension ist wie "Index of Publishers" (IxTheo#2024-06-07#3747AAAE5D35F09E73AA477C0C92AB9865D623C5)

Der Rubrikentitel ist auch vorhanden.

**Comment by jriedl** [comment]
Hier wurde in der Vergangenheit offenbar einmal die Regel eingeführt, dass der Artikeltyp "Other" als Rezension zu interpretieren ist, womit natürlich "alles andere" auch darunterfällt. Denkbar wäre die Einführung eines Titelmusters im QA zur Identifikation von Titeln, die mit "Index" anfangen.

**Comment by IxKo** [comment]
Eventuell könnten die 11 Titel in die Review-Regex speziell nur für diese Zs., da sie sich nach ein paar Stichproben jedes Jahr wiederholen.

**Comment by jriedl** [comment]
Hatte ich auch überlegt - ist ein Abwägungsprozess, wieviel Codechaos mit Sonderfällen wir über die nächsten Jahre so mitschleppen wollen.

**Comment by jriedl** [comment]
Normalerweise geben die geschweiften Klammern die Anzahl der Wiederholungen des linksstehenden Ausdrucks (vgl. https://techbyexample.com/curly-braces-quantifier-regex/). Insofern bedeutet ihr Ausdruck offenbar, dass erst eine Zahl kommt, dann 1-9 null bis beliebig oft vorkommen kann und dann noch 0-1 null mal bis beliebig oft. Eine Zahl ohne führende Null am Anfang des Ausdrucks sollte sich aber auch so formulieren lassen: `^[1-9][0-9]*` . Ich hätte jetzt im konkreten Fall aber ohnehin eher an einen negativen Regex für die Rezensionen in der QA gedacht:  `^(?!Index)`.

**Comment by IxKo** [comment]
Ach so, dann müssten jedoch auch diese Titel ausgeschlossen werden:
* Society for Old Testament Study Book List 2024
* The Society for Old Testament Study

Demnach so, oder:
^(?!Index)|(?!Society for Old Testament Study)

**Comment by jriedl** [comment]
> Demnach so, oder:
> ^(?!Index)|(?!Society for Old Testament Study)

Ja, oder auch `^(?!(Index|Society for Old Testament Study))`.

Ich hatte es so verstanden, dass es darum geht, einen Weg zu finden, zu vermeiden, dass die oben gemachten Anpassungen etwas fälschlicherweise Rezensionen einspielen. Weil das verwendete Kriterium "other", eben zu generisch und damit brüchig ist. Insofern war meine Annahme tatsächlich, dass es in der Errors landen soll. 

Was über die Conf machbar wäre, ist die Verwendung von `remove_marc_field_655a = REGEX`  auf Zeitschriftenebene. Dann müsste der Regex aber wieder umgedreht, d.h. positiv formuliert werden, also `remove_marc_field_655a = ^(Index|Society for Old Testament Study)` . Dieser Ansatz geht implizit der Annahme aus, dass 655 nur für die Kennzeichnung von Rezensionen verwendet wird. Das ist aktuell für unser Setup richtig, könnte sich aber später ändern. Aber wir verwenden es so auch bereits an anderen Stellen.

**Comment by jriedl** [comment]
Habe es für JSOT nun so in der Conf eingetragen.

**Comment by IxKo** [comment]
> ^(Index|Society for Old Testament Study)

Danke, jedoch würde das den Titel "The Society for Old Testament Study" nicht mit einschließen, da es nicht mit "Society" beginnt.

**Comment by jriedl** [comment]
Sehe die spätere Editierung leider erst jetzt: Habe gerade eine Version ohne Klammern eingecheckt, bei dem sich das Anchoring nur auf den linken Teil bezieht. Für einen Titel würde ich davon ausgehen, dass sie Spaces richtig sind.

**Comment by jriedl** [comment]
> `\s` ist nicht erforderlich?

Sollte mit normalem Leerzeichen passen.

**Comment by IxKo** [comment]
Vielen Dank!
Für "Journal for the study of the **New** Testament" schaue ich mir das Rezensionsheft noch an und werde es dann entsprechend ähnlich einrichten.

**Comment by IxKo** [comment]
Ich muss das Issue wieder öffnen, denn bei der Zs. "Journal for the study of the New Testament" ist Heft 5 eingespielt worden, doch Titel, die in der conf stehen, um 655 Rezension entfernt zu bekommen:

conf:
`remove_marc_field_655a    = "^(Index|Contributors|Series Abbreviations|Books received)"`

sind in einer neuen Einspielung diesen Monat wieder mit 1131 Rezension eingespielt:
Beispiel:
IxTheo#2024-09-05#9B63F92C2901946C8A5E7C8F015AE52F9152B888
![image](https://github.com/user-attachments/assets/823ec80b-7643-4b95-871d-25e37a055eaa)


Zudem ist der "Rubrikentitel Booklist 20XX" nur bei 3 Datensätzen eingespielt worden:

IxTheo#2024-09-05#5C72649D034D85832FFDFBF2E2CB5E32B3E878EA
IxTheo#2024-09-05#D55B4F56B663099EED08F114899FD519B4BC0B4D
IxTheo#2024-09-05#9B63F92C2901946C8A5E7C8F015AE52F9152B888

Bei allen restlichen Einträge des Heftes jedoch nicht.

**Comment by IxKo** [comment]
Ich habe mit TRY URL Stichproben gemacht und es scheint auf nu korrekt zu laufen.
Danke, es kann auf ub28 implementiert werden.

**Comment by jriedl** [comment]
Die DOI https://doi.org/10.1177/03090892241240269 gehört noch zu einem Band, bei dem alle Artikel noch mit dem Typ "Other" gekennzeichnet sind (vgl. https://journals.sagepub.com/toc/jota/48/5). Mit Band 49 scheint zu Auszeichnung aber korrekt zu sein (vgl. https://journals.sagepub.com/toc/jota/49/1), deshalb die obige Annahme, dass es sich für zukünftige Sonderhefte korrekt verhält. Da #2144 nun ebenfalls getestet ist, würde ich nun ein Update auf ub28 mit allen letzte Woche vorgenommenen Änderungen machen.

**Comment by jriedl** [comment]
Ist jetzt alles auf ub28.
