### ISSUE TITLE
ISSN 2269-479X | Revue d'Histoire et de Philosophie religieuses | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1199]
Hier werden sowohl im Multi- als auch im Single-DL falsche Seitenzahlen übertragen:
https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-3-100e-annee-n-3-varia.html
https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2020-3-100e-annee-n-3-varia-aux-origines-du-christianisme-l-evenement-la-memoire-et-la-foi.html
Nicht die richtigen des Aufsatzes, sondern die, die im Quelltext in den Tags citation_firstpage und citation_lastpage stehen.
Auf der Webseite sind sie korrekt: Pages: 335 à 362
Im Quelltext steht in den genannten Tags 5 und 32

**Comment by socheres** [comment]
einige Aufsätze wurden bereits erfasst und sollten korrigiert werden.

**Comment by socheres** [comment]
da ich das aktuelle Online-Heft nicht einsehen kann, kann ich nicht 100% sicher sein, dass die Paginierung in der e-Ausgabe wie beim gedruckten Heft fortlaufend innerhalb eines Jahrgangs gezählt werden. Innerhalb eines Heftes stimmen die Seitenangaben in den strukturierten Metadaten-Tags  `citation_firstpage` und `citation_lastpage`

**Comment by socheres** [comment]
das Digitalisat der gedruckte Hefte können hier eingesehen werden. Sogar bis 1921: https://www.persee.fr/collection/rhpr

**Comment by kdr154** [comment]
Die Paginierung von Druck- und Online-Ausgabe ist gleich. Der Kollege von der Sacherschließung hat die bereits erfassten Hefte korrigiert.

**Comment by kdr154** [comment]
Im Multi-DL ist die Paginierung nun richtig. Im Single ist es noch falsch. Allerdings steht mir im Single der Translator ubtue_RHPR nicht zur Verfügung.

**Comment by kdr154** [comment]
Einsicht auf Persée allerdings nur bis 2016.

**Comment by socheres** [comment]
Single-DL müsste auch gehen und für die retrospektive Katalogisierung bitte die o.g. Infos in ZEDER vermerken.

**Comment by kdr154** [comment]
Jetzt auch im Single korrekt.
