### ISSUE TITLE
Allgemein globale Einstellungen für verschiedene Zeitschriften (z.B. exclude_if_marc_field_xxx und weitere)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1200]
Hallo,

wäre es möglich und sinnvoll, wenn wiederkehrende irrelevante Titel gloabl ausgeschlossen werden könnten, statt diese immer wieder für einzelne Zss anzulegen?

Editorial ist bspw. so ein Kandidat, der häufiger vorkommt und wir wissen, dass wir solch einen Titel in keiner Zs aufnehmen wollen.

Es könnte ja auch sein, dass in Zukunft eine Zs ebenfalls einen solchen irrelevanten Datensatz führt, dieser aber in keinem Heft zuvor vorhanden war.
So würde man also auch für die Zukunft diese Titel ausschließen können.

Regex-Bedingung für die irrelevante Titel-"Sammlung" wäre, dass die Titel jeweils exakt so beginnen und enden:

`(?i)^\s?((Titel1)|(Titel2)|(Titel3)|(usw...)\s?$`

Bsp.-Titel:

Editorial
Guest\s+Editorial
From\s+the\s+Editor(s?)
Introduction
(Front|Back)\s+Matter
Issue\s+Information
Books\s+(Received|Reviewed)
Book\s+Reviews
About\s+This\s+Issue

usw.

**Comment by socheres** [comment]
das ist eine gute Idee. @mtrojan-ub lässt sich das global umsetzen ohne die bisherige zu überschreiben?

**Comment by mtrojan-ub** [comment]
Grundsätzlich ja, wenn es Regeln gibt die ohne Ausnahme für alle Zeitschriften gelten könnten wir die auch immer anwenden. Ich würde vorschlagen, dass wir die Details am Montag im Meeting besprechen.

**Comment by mtrojan-ub** [comment]
Im zotaut Regelmeeting besprochen:
- Einstellungen sollen in der zotero_harvester.conf in einer globaler Sektion von den Bibliothekaren selbst erweitert werden können
- Relevante Felder
  - exclude_if_marc_field_xxx
  - zotero_review_regex
  - remove_marc_field_xxx (da oft im Zusammenhang mit zotero_review_regex verwendet um im Anschluss Keywords zu entfernen)

**Comment by mtrojan-ub** [comment]
Es können jetzt entsprechende Einträge in der zotero_harvester.conf vorgenommen werden (greift aktuell auf nu+benu). Aufgrund der internen Datenstrukturen wurden zusätzlich zu den bisher genannten Einstellungen auch exclude_if_json_field_xxx, override_json_field_xxx, suppress_json_field_xxx und add_marc_field_xxx mit freigeschaltet. Falls weitere Felder benötigt werden bitte bescheid sagen (wenn man sie dort einfach nur einträgt hat das keinen Effekt).

In der Conf gibt es jetzt einen neuen Abschnitt samt Doku:
https://github.com/ubtue/zotero-enhancement-maps/blob/2ae92ba7c3c579bc42161bd356988ded449dfeb5/zotero_harvester.conf#L38

Wenn eine der Einstellungen verwendet werden soll, bitte dort die Raute am Anfang der Zeile entfernen und den Beispielwert entsprechend anpassen (inhaltlich genau gleich wie bei den Zeitschriften auch).

(Die Änderungen sind im Rahmen von Pull Request ubtue/ub_tools#3640 eingeflossen.)

=> ready for testing!

**Comment by IxKo** [comment]
Die globale Einstellung für die Auschließung des Marc-Feldes 245a war im Test erfolgreich.
Es muss jedoch bei jeder weiteren neu aktivierten Einstellung beobachtet werden, ob es keine unerwünschten Nebeneffekte gibt.
So wurde beobachtet, dass bestimmte Einstellungen nicht doppelt (global und individuell) vorhanden sein dürfen, da es wie bspw. bei der Einstellung für ein zusätzliches Feld 520 zu einem unerwünschten dritten Feld führt.

**Comment by mtrojan-ub** [comment]
Dieses Verhalten entspricht ja genau der Anforderung:
> Gibt es sowohl eine Globale Einstellung als auch eine Einstellung pro Zeitschrift, so soll diese die globale Einstellung nicht überschreiben sondern zusätzlich gelten.

Die Beobachtung ist also völlig richtig und das heißt auch => wenn man eine globale Einstellung aktiviert muss man gleichzeitig prüfen ob es bei Zeitschriften lokale Einstellungen gibt die entfernt oder angepasst werden müssen.

**Comment by IxKo** [comment]
> 
> 
> Dieses Verhalten entspricht ja genau der Anforderung:
> 
> > Gibt es sowohl eine Globale Einstellung als auch eine Einstellung pro Zeitschrift, so soll diese die globale Einstellung nicht überschreiben sondern zusätzlich gelten.
> 
> Die Beobachtung ist also völlig richtig und das heißt auch => wenn man eine globale Einstellung aktiviert muss man gleichzeitig prüfen ob es bei Zeitschriften lokale Einstellungen gibt die entfernt oder angepasst werden müssen.

@kdr154 zur Kenntnis
