### ISSUE TITLE
Allgemein Lizenzinformation Zs oacc=ZZ mit einzelnen OA-Aufsätzen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1201]
**Bsp-URL**
https://journals.sagepub.com/toc/tdra/138/4

Blau hinterlegtes Schloss => Open Access

**Ausführliche Problembeschreibung**
Die Lizenzinformation aller Aufsätze einer Zs wird über Zeder festgelegt.

Problematisch wird dies aus meiner Sicht, wenn einzelne Aufsätze einer Zs OA sind, die Zs in Zeder aber als lizenzpflichtig angegeben ist, was für den Rest der Aufsätze zutreffend ist.
Nun werden aber auch die OA-Aufsätze als lizenzpflichtig eingespielt.

Dies ist schade, nicht richtig und aus Sicht von Autor:innen und Nutzer:innen sicherlich nicht rechtens.

**Lösungsansatz**
Könnten diese einzelnen OA-Aufsätze über Informationen im HTML-Code identifiert und mit LF gekennzeichnet werden?

----
_Eine etwas andere Sache, die ich aber auch in diesem Zusammenhang erwähnt haben möchte:_
_Ein Problem - welches wir wohl nicht allein lösen können - sind Fälle wie sie bspw. bei einer Moving Wall stattfinden: einzelne Artikel oder Artikel bestimmter Hefte einer Zs verändern ihren Lizenzstatus nachträglich. Demnach ist der angegebene Status zum Zeitpunkt der Katalogisierung nicht mehr wahr._

**Comment by socheres** [comment]
das machen wir im Rahmen des Proektes "unpaywall" @jriedl werden OA-Aufsätze weiterhin über unpaywall aufgespürt und als solche in IxTheo gekennzeichnet?

**Comment by thefass** [comment]
> _Eine etwas andere Sache, die ich aber auch in diesem Zusammenhang erwähnt haben möchte:_
> _Ein Problem - welches wir wohl nicht allein lösen können - sind Fälle wie sie bspw. bei einer Moving Wall stattfinden: einzelne Artikel oder Artikel bestimmter Hefte einer Zs verändern ihren Lizenzstatus nachträglich. Demnach ist der angegebene Status zum Zeitpunkt der Katalogisierung nicht mehr wahr._

Unpaywall ist da nur bedingt eine Hilfe. Es gibt zwei Lösungsansätze, die wir schon mal mit dem BSZ diskutiert haben:
1. Wir führen eine Spalte in Zeder für das Embargo ein. Dort wird die moving wall eingetragen. Z.B. eine 2, wenn die Aufsätze einer Zeitschrift nach 2 Jahren ins Open Access übergehen. Zusammen mit dem Erscheinungsjahr könnte dann automatisch ZZ in LF ersetzt werden. Das wäre die "kleine" und vermutlich schnelle Lösung auf unserer Seite
2. Das BSZ setzt das auf Verbundebene um, dann wäre das dauerhaft ausgezeichnet und würde viel mehr Zss zugute kommen

**Comment by socheres** [comment]
Hier geht es um einzelne OA-Aufsätze innerhalb eines kostenpflichtigen Heftes. Und über Journal Online Print-Button werden solche OA-Aufsätze - z.B. mit blauem Schloss in Sage - als OA auch ohne institutionelle Anbindung mit grünem Pfeilsymbol dargestellt:  https://ixtheo.de/Record/1697305628 
Das, was @thefass anspricht, wird praktisch auch über Journal Online Print-Button gelöst, sobald eine Zeitschrift in National- bzw. Allianzlizenzen überführt und diese Lizenzinfos in EZB eingetragen werden. Diese Info in Metadaten festzuhalten, fände ich nicht notwendig. Dafür gibt es Dienste wie unpaywall oder EZB-DFG-Projekt: https://www.uni-regensburg.de/bibliothek/projekte/oa-ezb/index.html

**Comment by IxKo** [comment]
Ich werde den Beispiel-Datensatz (https://ixtheo.de/Record/1697305628) in der WinIBW zum Testen für einen Tag auf $xZZ (für lizenzpflichtig) setzen.
Morgen werde ich den Datensatz im IxTheo suchen und prüfen, ob er weiterhin in der Facette Open Access auftaucht.

Wenn dem weiterhin so ist, ist es gut und ich schließe das Issue.

**Comment by IxKo** [comment]
Noch eine andere Frage: Wieso wird der Titel als gelb dargestellt, wenn ich eine institutionelle Anbindung habe und grün, wenn ich das nicht habe?

**Comment by IxKo** [comment]
Der Artikel ist weiterhin in der OA-Facette des IxTheos.
Nach Aussage von socheres und dem Eintrag in 856 |x im Internetformat liegt das an dem Unpaywall-Projekt.

Bei einem aktuellerem Datensatz (https://ixtheo.de/Record/1735514594) greift Unpaywall nicht.
Scheinbar hatte das Projekt einen Daten-Ist-Stand bearbeitet, und neue Daten bleiben davon unberührt.
Oder wird Unpaywall in bestimmten zeitabständen "angestoßen"?

**Comment by socheres** [comment]
> Scheinbar hatte der Dienst einen Daten-Ist-Stand bearbeitet, und neue Daten bleiben davon unberührt.
> Das heißt nicht ausdrücklich als OA gekennzeichnete Datensätze werden im IxTheo nicht in der OA-Facette auftauchen.
@jriedl  was ist der aktuelle Stand zum "unpaywall"-Projekt?

**Comment by jriedl** [comment]
@socheres Wie von @thefass bereits erläutert, scheint in diesem Kontext kein direkter Zusammenhang mit Unpaywall zu bestehen: Was Unpaywall liefert, sind Links auf Volltexte anhand der DOI, die anhand des IxTheo-Datenbestandes und den vorhandenen Unpaywalldaten von uns in die Datensätze eingefügt werden. Das ist aber unabhängig vom Zotero-Verfahren und auch nur indirekt mit einer Moving Wall korreliert. Unpaywall kann auch Volltext völlig außerhalb des ursprünlinglichen Publikationsweges zur Verfügung stellen, z.B. über Zweitveröffentlichungen. Insofern ist das für die Bestimmung des Lizenzstatus einer Zeitschrift nicht geeignet und die grundsätzliche Auszeichnung als lizenzpflichtig IMO korrekt. Die oben erwähnte nachträgliche Neuauszeichung von Datensätzen, die in nach einer Embargo-Frist openAccess werden, muss an anderer Stelle behandelt werden.

**Comment by IxKo** [comment]
Auch bei Brill gibt es einzelne OA-Aufsätze (Bsp. 2/7 OA https://brill.com/view/journals/vc/75/1/vc.75.issue-1.xml) und sicher wird das auch bei vielen anderen Zss der Fall sein.
Daher ist es doch besser, wenn (wie momentan) nur reine lizenzfreie Zss mit LF geliefert werden und alle anderen Zss erhalten keine Lizenzangabe. Denn lieber keine Angabe, statt eine falsche.

Schöner wäre natürlich, wenn die OA-Angabe irgendwie ausgelesen und als $4LF bzw. Marc-773 <subfield code="z">Kostenfrei< geliefert werden könnte.

**Comment by IxKo** [comment]
Fortsetzung #1397
