### ISSUE TITLE
ISSN 2397-3498 | Downside review | Funktion (Beruf) Dom

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1205]
Das Wort "Dom" im Namen ist bei folgenden Aufsätzen ebenfalls ein(e) Titel/Funktion/Beruf:
https://journals.sagepub.com/doi/full/10.1177/0012580620934728
https://journals.sagepub.com/doi/full/10.1177/0012580620939336
Siehe:  https://www.downsideabbey.co.uk/benedictine-monastery/monastic-community/profiles-of-the-monks/

Sollte aus dem Namen entfernt werden:
![grafik](https://user-images.githubusercontent.com/29707105/97292571-b00a2200-184b-11eb-89af-331394281caa.png)

und
![grafik](https://user-images.githubusercontent.com/29707105/97292631-c9ab6980-184b-11eb-9818-cb22c34cac27.png)

**Comment by socheres** [comment]
in solchen Fällen die Liste "author_name_blacklist.txt" um den String "Dom" ergänzen, damit das Wort ausgeschlossen wird.

**Comment by kdr154** [comment]
ergänzt

**Comment by IxKo** [comment]
Dom kann aber auch ein Familienname sein und es gibt den Namen tatsächlich auch als Vornamen.
Ist es dann nicht zu riskant, diesen Begriff auszuschließen?

**Comment by kdr154** [comment]
Dom ist eine höfliche Anrede in Verbindung mit dem Vornamen. Etwa so etwas wie Herr Hans Maier. Siehe https://de.wikipedia.org/wiki/Dom_(Titel)
Der Problematik war ich mir schon bewusst. Mir ist Dom als Vorname  oder als Nachname in der Praxis noch nicht begegnet. Als Teil des Namen in der Form als Anrede dagegen schon wieder einige Male.

**Comment by IxKo** [comment]
Danke, dann ist es also ein Titel.

In diesem Fall ist auch interessant, dass Sage sowohl im Metadatenfeld `<meta property="article:author` als auch in `meta name="dc.Creator"` den Titel stehen gelassen hat. Bei anderen Fällen wie _Jr._ oder römischen Zählungen, gab es in den Feldern Unterschiede. (siehe #1223 )

**Comment by kdr154** [comment]
Wir haben beschlossen, dass "Dom" nicht ausgeschlossen werden soll.
