### ISSUE TITLE
ISSN 2056-998X | International journal of christianity & education | Rezensionen Review Article

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1207]
Rezensionen vom Typ Review Article werden nicht erkannt.
https://journals.sagepub.com/doi/full/10.1177/2056997119836960

Der Begriff ist auch im Quelltext zu finden:
![grafik](https://user-images.githubusercontent.com/29707105/97403225-57429400-18f4-11eb-8851-e89680ddc2d2.png)

Auch bei diesem Artikel:
https://journals.sagepub.com/doi/full/10.1177/2056997118755410

**Comment by socheres** [comment]
auf benu ok. #1206

**Comment by kdr154** [comment]
Ist in Ordnung jetzt.
