### ISSUE TITLE
ISSN 2056-998X | International journal of christianity & education | Überflüssiger Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1208]
Dieser Artikel:
https://journals.sagepub.com/doi/full/10.1177/2056997118815415
in diesem Band:
https://journals.sagepub.com/toc/icec/23/1
ist eigentlich überflüssig. Mir fällt aber keine elegante Möglichkeit ein, ihn auszuschließen, es sei denn man schließt ihn über den Titel aus.
Er  firmiert als normaler "Research Artikel" und die Sektion "Briefly noted" kommt seit 2017 nur in diesem Band vor.
Die Alternative wäre, dass man ihn als "Beifang" mit aufnimmt.

**Comment by IxKo** [comment]
Wenn es nur einmal auftaucht, würde ich auch sagen, dass man den Artikel "in Kauf nimmt".

**Comment by socheres** [comment]
Der Artikel ist eine Art Buchbericht zum im Titel genannten Thema, daher bitte mit aufnehmen.

**Comment by kdr154** [comment]
ok
