### ISSUE TITLE
ISSN 1573-6121 | Archive for the psychology of religion | Themenbeziehungen (Beziehung zu der Ressource, die beschrieben wird)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1209]
In dieser Ausgabe: https://journals.sagepub.com/toc/prja/41/1
gibt es eine ganze Reihe von Aufsätzen, die aufeinander Bezug nehmen. Im Zotkat-Verfahren haben wir das so gehandhabt, dass wir die Sätze im Nachhinein bearbeitet haben und mit den Kategorien 4261 Kritik von und der PPN des kritisierten Aufsatzes und 4262 Kritik in und der PPN des Aufsatzes, der die Kritik beinhaltet, die Sätze verknüpft haben. Oft ist es so, und so auch in diesem Fall, dass zum Abschluss die Verfasser des kritisierten Werkes, ihren Kritikern geantwortet haben. Auf diese Weise entstand ein komplexes Geflecht von Beziehungen, welches über die Kategorien 4261 und 4262 erfasst wurde.

Beispiel:

Aufsatz A
Aufsätze B, C, D die den Aufsatz A kritisieren
Aufsatz E, in diesem Aufsatz kritisiert der oder die Verfasser des Aufsatzes A die Kritiken in den Aufsätzen B, C, D. Uns zwar nicht jeden für sich, sondern alle in einem.

In den Aufätzen B, C, D steht dann: Kritik von Aufsatz  A
In Aufsatz A steht: Kritik in Aufsatz B, ... in Aufsatz C, ... in Aufsatz D
In Aufsatz E steht; Kritik von Aufsatz B, ... von Aufsatz C, ... von Aufsatz D
In den Aufsätzen B, C, D dann jeweils: Kritik in Aufsatz E

Diesen Fall haben wir in dem vorliegenden Heft. Es sind die Aufsätze die in den Rubriken Commentaries und Commentary Reply stehen.

Das sind keine Rezensionen, jedenfalls haben wir sie nicht als solche behandelt. Denn dann wäre jede Schrift, in der ein Standpunkt beurteilt wird, eine Rezension. In den Philologien im Grunde genommen jeder kritische wissenschaftliche Beitrag und jede kritische wissenschaftliche Schrift.

Wie wollen wir im Hinblick auf das vollautomatische Verfahren mit solchen Dingen verfahren? Grundsätzlich ist das etwas, was in jeder Zeitschrift vorkommen kann, tatsächlich aber doch immer wieder vorkommt. Gerade bei den Zeitschriften von Sage, Taylor & Francis, Wiley.
Verzichten wir im Zotaut-Verfahren generell darauf, diese Beziehungen zu erfassen? Wenn nicht, müsste man diese Hefte nachbearbeiten, oder sie gar nicht erst erfassen. Im schlechtesten Fall könnte man sagen, Zeitschriften, in denen es so etwas gibt, sind nicht für Zotaut geeignet, Das wiederum wären einige und in meinen Augen auch nicht die Lösung, auf die wir uns einigen sollten.

**Comment by thefass** [comment]
Bevor ich näher antworte: können Sie bitte eine Beispiel PPN für einen solchen Fall wie von Ihnen geschildert nennen?

**Comment by kdr154** [comment]
PPN 1682099903

**Comment by kdr154** [comment]
PPN 1692291416

**Comment by socheres** [comment]
Auf jeden Fall soll diese Zss. weiterhin im Zotaut-Verfahren erfasst werden. Wir klären intern, ob solche Querverweise nachträglich in WiniBW erfasst werden soll oder nicht.

**Comment by kdr154** [comment]
Am 5.11. in einer DB geklärt. Datensätze werden als Aufsätze eingespielt ohne die Beziehungen zu bearbeiten.
