### ISSUE TITLE
ISSN 2175-5841 | Horizonte | Bandangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1211]
Die Bandangabe ist zu umfangreich. Entweder der Importtranslator oder den Exporttranslator anpassen. Sie wird so, wie sie in Zotero steht, nach Pica übernommen.
http://periodicos.pucminas.br/index.php/horizonte/article/view/17687

![grafik](https://user-images.githubusercontent.com/29707105/97447017-65fa6c80-192f-11eb-87b0-e9893d229116.png)

ergibt in Pica:
\n4070 $v18 n. 55 (2020): v. 18$j2020$a55$p378

**Comment by socheres** [comment]
welches Translator wurde dabei verwendet?

**Comment by kdr154** [comment]
ubtue_horizonte

**Comment by kdr154** [comment]
Gelöst.
