### ISSUE TITLE
ISSN 2328-1162 | Journal of psychology and theology | Rezension

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1212]
**URL**
https://journals.sagepub.com/doi/full/10.1177/0091647120908017

**Ausführliche Problembeschreibung**
Hier handelt es sich um eine Rezension, die nicht als solche gekennzeichnet wird.

**Offenbare Lösungen**
Evtl. über einen Translator-Anpassung möglich.
Im HTML-Code findet sich folgender Hinweis:
`<meta name="dc.Type" content="product-review">`

**Comment by IxKo** [comment]
Wird auf Benu nicht als Rezension erkannt.

**Comment by kdr154** [comment]
Mein Test auf benu fällt negativ aus.  Kein Tag 655.
Lösung über harverster.conf möglich?

**Comment by socheres** [comment]
bitte enhancement.map ergänzen. Tag "Book Review" wird erzeugt.

**Comment by IxKo** [comment]
Ich verstehe nicht ganz. Bei mir wird kein Tag erzeugt.
Ich nehme an, dass mit "enhancement.map" die zotero_harvester.conf gemeint ist.
In den globalen Einstellungen sind die beiden Einstellungen für diesen Fall bereits aktiv gesetzt:

`zotero_review_regex                        = (?i)^Book\s+Reviews?`
`#remove_marc_field_650a                     = (?i)^Book\s+Reviews?$`

**Comment by socheres** [comment]
Sorry für die Verwirrung. Hatte vergessen die Translators auf benu zu aktualisieren. Jetzt wird als review erkannt.

**Comment by socheres** [comment]
erfolgreich getestet.
