### ISSUE TITLE
ISSN 2631-8334 | Pro ecclesia | Rezensionen und Beziehungen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1214]
Hier: https://journals.sagepub.com/toc/prea/29/3 
handelt es sich z. T. wieder um einen in #1209 angesprochenen Fall. Bei den Artikeln in der Sektion "Book Symposium" sind die ersten drei Artikel Rezensionen. 
Diese werden nicht erkannt.
Der 4. Artikel bezieht sich auf die drei Rezensionen
Dasselbe bei dieser Ausgabe: https://journals.sagepub.com/toc/prea/29/2

**Comment by socheres** [comment]
Das sind streng genommen keine Rezensionsartikel, sondern Literaturberichte, daher sind sie wie Aufsatzartikel zu behandeln. Bitte so einspielen.

**Comment by kdr154** [comment]
ok

**Comment by socheres** [comment]
die Entscheidung treffen wir erst nach Absprache mit @thefass und @IxTheoKm

**Comment by kdr154** [comment]
Ein gutes Beispiel findet sich auch in diesem Heft: https://journals.sagepub.com/toc/crra/7/2
Ein Symposium (Rubrikentitel) in dem ein Werk von mehreren Teilnehmern diskutiert wird, bei dem am Ende der Verfasser des diskutierten Werks den Kritikern antwortet.

**Comment by kdr154** [comment]
Wurde am 5.11. entschieden. Alles ohne Verweise einspielen
