### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity | Rezensionen 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1215]
Rezensionen werden nicht getagt. 
https://jeac.de/ojs/index.php/jeac/issue/view/16
Sie werden eingeleiter mit "Review of", "Rezension von" oder "Rezension zu".

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe den Translator ubtue_OJS-Standard entsprechend angepasst.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Passt
