### ISSUE TITLE
ISSN 2054-1988 | Journal of Holy Land and Palestine Studies | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1216]
https://www.euppublishing.com/toc/hlps/19/2
Die Rezensionen in der Abschnitten "Review Article(s)" und "Book Review(s)" werden nicht erkannt.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
das Problem dürfte mittlerweile behoben sein, bei mir funktioniert es. Könnten Sie nochmal testen?
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Stimmt.
