### ISSUE TITLE
ISSN 2169-1304 | Theological studies | Zeichenprobleme

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1218]
Ich beobachte folgendes Phänomen: wenn ich versuche, diesen Artikel: https://journals.sagepub.com/doi/10.1177/0040563920941807
mittels Additional config "exclude_if_marc_field_245a                 = (?i)^(From the Editor’s Desk)" auszuschließen, wird er nicht ausgeschlossen, wenn ich "From the Editor's Desk" über die Tastatur eingebe. 
Wenn ich den Ausdruck aber auf der Ergebnisseite von benu markiere und ihn über copy and paste in das Feld Additional config kopiere, wird er unterdrückt.
Dieses Phänomen habe ich gestern bei mir zuhause feststellen können, als auch heute an meinem Arbeitsplatz an der Uni.
Ich vermute, dass der Apostroph in dem Wort "Editor's" die Ursache ist.

**Comment by socheres** [comment]
testen Sie bitte nochmal mit diesem regex: `(?i)^(from\s?the\s?editor(\’?|\'?)s\sdesk)`

**Comment by kdr154** [comment]
Der Artikel wird auch in diesem Fall nicht unterdrückt. Nun auch dann nicht, wenn ich den Ausdruck vom Result file per c&p in Additional config kopiere.

**Comment by IxKo** [comment]
Damit` exclude_if_marc_field_245a = (?i)^(From\s+The\s+Editor\Ss\s+Desk\s?)$` müsste es gehen

**Comment by socheres** [comment]
auf benu funktioniert mit `(?i)^(from\s?the\s?editor(\’?|\'?)s\sdesk)`

```
Queued journal 'Theological studies' | DIRECT @ https://journals.sagepub.com/doi/10.1177/0040563920941807
set download-delay for domain 'journals.sagepub.com' to 1000 ms


Harvesting URL 1 [Theological studies...] | https://journals.sagepub.com/doi/10.1177/0040563920941807 {2090184026242090349}
Harvest successful




Converting item 1 [Theological studies...] | https://journals.sagepub.com/doi/10.1177/0040563920941807 {2090184026242090349}
use online ISSN "2169-1304" with online PPN "341343889"
post-processed author first name = 'Philip J.', last name = 'Rossi', title = '', affix = ''
added GND number 1072525054 for author Rossi, Philip J. (SWB lookup)
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1177/0040563920941807,
	item_type: journalArticle,
	title: From the Editor’s Desk,
	publication_title: Theological studies,
	volume: 81,
	issue: 2,
	pages: 273-277,
	date: 2020-06-01,
	doi: 10.1177/0040563920941807,
	language: eng,
	issn: 2169-1304,
	superior_ppn: 341343889,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Philip J.,
			last_name: Rossi,
			type: author,
			gnd_number: 1072525054,
		},
	],
	custom_metadata: [
		{ 

doi,  10.1177/0040563920941807
 },
	],
}
custom field '5203 a%abs%' has missing placeholder(s) 'abs'
MARC field for 'https://journals.sagepub.com/doi/10.1177/0040563920941807 matched exclusion filter (245a/(?i)^(from\s?the\s?editor(\’?|\'?)s\sdesk)/)
Conversion complete
```

**Comment by kdr154** [comment]
Die Variante von @socheres funktioniert, es war ein Versehen meinerseits

**Comment by kdr154** [comment]
Schließe
