### ISSUE TITLE
ISSN 2044-2696 | Theology | Poetry

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1219]
Ebenfalls immer wieder vorkommend: Poetry. 
https://journals.sagepub.com/doi/full/10.1177/0040571X20953105
https://journals.sagepub.com/toc/tjxa/123/5
Wie in diesem Fall in der Regel Gedichte. Drin lassen, ausschließen? Kann man es beim Typ Article belassen?

**Comment by thefass** [comment]
M.E. sollten wir das ausschließen

**Comment by socheres** [comment]
Kann nicht automatisch ausgeschlossen werden und kommt nur einmal im Heft vor. Bitte so einspielen. Es besteht ja die Möglichkeit solche Aufsätze später zu löschen.
