### ISSUE TITLE
Blanks am Anfang oder/und am Ende in 650 $a

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#122]
Werden Blanks am Anfang und/oder Ende in 650 $a entfernt oder spielt das keine Rolle?
Bsp.:
```
<datafield tag="650" ind1=" " ind2=" ">
<subfield code="a"> Contagion </subfield>
```

**Comment by mtrojan-ub** [comment]
Bisher wurden keine Leerzeichen entfernt, das haben wir jetzt für die Keywords aktiviert.

**Comment by kdr154** [comment]
Am Ende bleiben sie stehen. Vgl. etwa:
```
<datafield tag="650" ind1=" " ind2="4">
<subfield code="a">Online drug markets </subfield>
</datafield>
```
Die dazwischen sollten allerdings erhalten bleiben

**Comment by mtrojan-ub** [comment]
Das ist seltsam... die Funktion die wir da einsetzen sollte eigentlich alles erwischen. Können Sie mir bitte noch eine Beispiel-ISSN schicken bei der der Fehler auftritt? Vielleicht handelt es sich um spezielle Leerzeichen die mit bloßem Auge nicht erkennbar sind (non-breakable spaces o.Ä.)

**Comment by kdr154** [comment]
1573-7799

**Comment by kdr154** [comment]
Gelöst
