### ISSUE TITLE
ISSN 1569-2086 | Hawwa | Multi-DL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1220]
Bei dieser Brill-ZS https://brill.com/view/journals/haww/18/2-3/haww.18.issue-2-3.xml
gibt es Probleme beim Multi-DL: Es ist ein Fehler aufgetreten beim Versuch, diesen Eintrag zu speichern.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
könnten Sie hier auch nochmal testen, ob es bei Ihnen jetzt auch funktioniert?
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Multi-DL funktioniert bei mir nun auch.
