### ISSUE TITLE
ISSN 1745-5235 | Studies in Christian ethics | Namenszusatz + Vorschlag Ergänzung Namens-Blacklist

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1223]
**URL**
1. https://journals.sagepub.com/doi/full/10.1177/0953946820942731f
2. https://journals.sagepub.com/doi/full/10.1177/0953946819896075 

**Ausführliche Problembeschreibung**
Beide Namenszusätze (III und Jr.) sind Unterscheidungsmerkmale und sollten übernommen werden.
In diesem Beispiel werden sie nicht übernommen, da wahrscheinlich bei der Datenübernahme nicht: `<meta name="dc.Creator" content>` die Grundlage ist, sondern `<meta property="article:author" content>` und im letzteren fehlen die Zusätze.

III müsste in Pica-Unterfeld $n und in Marc-Unterfeld $c.
Jr. in Pica-Unterfeld $l und in Marc-Unterfeld $b

**Vorschlag**
Zudem habe ich folgenden Vorschlag:
In der Namens-Blacklist zusätzlich zu den vorhandenen katholischen Ordenskürzeln eine weitgehend vollständige Liste von möglichen Berufbezeichnungen ergänzen.

**Comment by IxKo** [comment]
Etwa Gleiches gilt auch für die Sage-Zs ISSN 2631-8334 | Pro ecclesia
https://journals.sagepub.com/doi/full/10.1177/1063851220952320

**Comment by kdr154** [comment]
#1222 und #1221 beziehen sich auf dasselbe

**Comment by mtrojan-ub** [comment]
Im Meeting besprochen: Es gibt bereits Logik dazu, ich teste warum sie in diesem speziellen Fall nicht greift.

**Comment by mtrojan-ub** [comment]
Es gibt Listen auf deren Basis bereits ein Export in die Unterfelder b und c statt findet:
- https://github.com/ubtue/ub_tools/blob/821a736cc1f2006a80973ab41a06e6aaf9595717/cpp/lib/src/ZoteroHarvesterConversion.cc#L395
- https://github.com/ubtue/ub_tools/blob/821a736cc1f2006a80973ab41a06e6aaf9595717/cpp/lib/src/ZoteroHarvesterConversion.cc#L410

Aufgrund der Debugmeldungen sieht es so aus, als ob der Translator in diesem Fall selbst gar keinen Namenszusatz liefert. Daher kann die Logik im Harvester nicht greifen (=> "title" und "affix" sind laut Meldung leer).

![grafik](https://user-images.githubusercontent.com/26873381/98555813-aac4c280-22a2-11eb-80c5-61afaf901502.png)

![grafik](https://user-images.githubusercontent.com/26873381/98555854-b57f5780-22a2-11eb-9d64-77e95fbfa514.png)


Da die URL bei mir im Home Office nicht abgerufen werden kann, kann ich es aber nur sehr schwer von hier aus weiter testen.

**Comment by IxKo** [comment]
Wird teilweise umgesetzt. Hier jedoch der Fall, dass der Translator die Namen ohne Zusätze liefert.
Im Meeting darauf geeinigt, dass es entfallen kann, wenn es sich als zu kompliziert herausstellt, die Zusätze über den Translator abzugreifen.

**Comment by kdr154** [comment]
Wir haben uns auf die pragmatischen Lösung geeinigt. Wir übernehmen die Sätze so, wie sie geharvestet werden.
