### ISSUE TITLE
ISSN 0040-5736 | Theology Today | Nicht auf benu auf nu vorhanden

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1224]
Diese Sage-ZS befindet sich nur auf nu, nicht auf benu. 
Ebenso ISSN 1759-8931 Transformation : an international journal of holistic mission studies
Überhaupt finden sich auf benu nur 36 Zeitschriften, auf nu 492. Ist das so gewollt? Auf ub28 sind es 490.
Kann es sein, dass es davon abhängt, ob sich in p_zot3 ein Eintrag befindet, oder nicht. Stichproben mit den Sage-Zeitschriften weisen darauf hin.

**Comment by mtrojan-ub** [comment]
Seltsam, auf benu werden derzeit allgemein nur 36 Zeitschriften angezeigt, auf nu sind es 492. Ich werde es mir genauer anschauen.

**Comment by mtrojan-ub** [comment]
Ich weiß woran es liegt => ist ein Bug bzw. unerwünschter Seiteneffekt der seit dem Aktivieren des Ampelsystems Ende letzter Woche auftritt. Ich werde es im Lauf des Nachmittags beheben.

**Comment by mtrojan-ub** [comment]
Müsste jetzt behoben sein

**Comment by kdr154** [comment]
Ist so, es sind wieder 492

**Comment by kdr154** [comment]
Beim Test mit der ersten Zeitschrift, Theology today, ISSN 2044-2556, bekomme ich jedoch einen Bearbeitungsfehler:
XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: http://benu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_1W2BUM/ixtheo/VWXenP.xml
Zeile Nr. 1, Spalte 1:

**Comment by mtrojan-ub** [comment]
Kann das in der Zwischenzeit geschlossen werden?

**Comment by kdr154** [comment]
Ich schließe
