### ISSUE TITLE
ISSN 1777-5825 | Archives de sciences sociales des religions | Status rot

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1225]
Hier scheint mir der RSS-Feed nicht aktuell zu sein, wenn er überhaupt noch aktualisiert wird. Das neueste Heft auf EHESS ist 191.2020 (Juli-September), also aktuell. https://journals.openedition.org/assr/
Der Feed listet Aufsätze aus dem Heft 188 aus dem Jahr 2018

**Comment by IxKo** [comment]
Die Zs bietet 3 RSS-Feeds an: https://journals.openedition.org/assr/backend

Dieser scheint aktuell zu sein für die Artikel: https://journals.openedition.org/assr/backend?format=rssdocuments

**Comment by socheres** [comment]
Ich schließe es.
