### ISSUE TITLE
ISSN 2044-2556 | Theology today | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1229]
Bei diesem Artikel klappt die Rezensionserkennung nicht: https://journals.sagepub.com/doi/full/10.1177/0040573620918177
In meinen Augen nicht über die harvester.conf zu lösen

**Comment by socheres** [comment]
streng genommen ist der verlinkte Artikel mit dem Label "Item-type =Article commentary"  keine Rezension. Daher bitte als Artikel einspielen.

**Comment by kdr154** [comment]
ok

**Comment by IxKo** [comment]
Ich würde schon sagen, dass der Artikel als Rezension gekennzeichnet werden sollte. Das Werk, auf das Bezug genommen wird, wird direkt anfangs mit Erscheinungsjahr, Seitenumfang und Preis genannt.
Ähnliches Beispiel wäre dieses hier: https://journals.sagepub.com/doi/full/10.1177/0040573619886131
Auch der Artikel ist im Inhaltsverzeichnis unter "Review Essay" gelistet, wird aber auf der Artikel-Website als "Article Commentary" ausgezeichnet.

Bitte den Sachverhalt nochmals genau anschauen.

**Comment by IxKo** [comment]
Gleiches gilt auch für die Zs Z.1528 ISSN 2167-776X | Journal of pastoral care & counseling

**Comment by socheres** [comment]
https://journals.sagepub.com/doi/full/10.1177/0040573619886131
https://journals.sagepub.com/doi/full/10.1177/0040573620918177

Beide sind keine Rezensionsartikel, sondern eher der Gattung Literaturbericht zuzuordnen, daher bitte nicht als Rezension kennzeichnen. Man könnte Item.type als Keywords "Article Commentary"  ohne Verknüpfung in 5520 ausgeben oder als GND-Normdatensatz "Literaturbericht" kennzeichnen. 

> Der Literaturbericht vergleicht die Positionen/Forschungsmeinungen der Autoren auf der Grundlage einer Auswahl von zwei bis vier Aufsätzen oder Büchern (Quelle:https://www.sozphil.uni-leipzig.de/cm/kuwi/files/2014/02/Merkblatt-Literaturbericht.pdf)

**Comment by kdr154** [comment]
Das müsste dann in den Translator eingearbeitet werden.

**Comment by IxKo** [comment]
Ein Literaturbericht ist es in meinen Augen nicht, denn es wird nur ein Werk betrachtet. Es wird weder Literatur zu einem bestimmten Thema zusammengestellt und ausgewertet, noch werden Forschungsergebnisse zusammengefasst.

Allerdings ist es fast nebensächlich, ob die Artikel nun als Rezensionen oder Literaturberichte gekennzeichnet werden, es sei denn Nutzer:innen möchten bei Ihrer Recherche genau solche Arten ein- oder ausschließen.

**Comment by socheres** [comment]
Ja, das ist eine Definitionssache. Wenn aber der Verlag diesen Artikel nicht als Book review (=Rezension) getagt hat, sollten wir das auch nicht tun.

**Comment by kdr154** [comment]
Im Meeting vom 16.11. haben wir beschlossen, diesen Typ nicht mit dem Rezenionstag zu versehen.
