### ISSUE TITLE
Controlfields 005, 007, 008 (+264c/936j)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#123]
Die SSOAR-Daten haben einige Controlfields mehr, und zwar:
```
<controlfield tag="005"
<controlfield tag="007"
<controlfield tag="008"

```
Ob die für die Datenlieferung benötigt werden, kann ich nicht sagen

**Comment by kdr154** [comment]
007 ist laut DNB Doku kein Pflichtfeld. Ich denke aber man kann es analog zu den SSOAR-Daten besetzen:
`<controlfield tag="007">cr|||||</controlfield>`
"c" an Position 0 bedeutet, dass es sich bei dem Dokument um eine elektronische Ressource handelt
"r" an Position 1, dass es sich bei dem Dokument um eine Online-Ressource handelt
Die Balken sind Füllzeichen. Über die Anzahl an Positionen bin ich mir auch nicht schlüssig. Bei den SSOAR-Daten sind es 7, bei einem "c" an Position 0 sollten es laut DNB-Doku 14 sein. 
Da, Zitat Frau Katz vom BSZ, das BSZ: "die SSOAR-Schnittstelle auch für den Import weiterer Daten aus anderen Anwendungen, die Tübingen abfragt, verwenden" will, kann man die Daten in unserem Projekt möglicherweise analog handhaben.  Aber ich frage am Besten dort nach.

**Comment by kdr154** [comment]
Habe jetzt Anwort von Frau Katz. Sie schreibt:
"zwingend benötigen wir die 007 mit der Angabe des Datenträgers. 005 mit der Angabe des Änderungsdatum setzen wir nicht um. 006 und 008 enthalten ähnliche Informationen. Bei vielen Datenimporten holen wir das Erscheinungsjahr in der vierstelligen Sortierform aus 008 Pos. 07-10, was dann nützlich ist, wenn in 264 $c textuelle Ergänzungen  sind, aus denen man nicht eindeutig das Erscheinungsjahr selektieren kann."

**Comment by mtrojan-ub** [comment]
Habe nochmal recherchiert. Es gibt bereits Logik die das 007-Feld mit ausspielen soll. Allerdings nur dann, wenn es für die ISSN in dieser Map-Datei einen Eintrag gibt:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_physical_form.map

Das ist auch so eine Datei die aus der alten PicaSWB.js entstanden ist, ähnlich der Thematik mit den SSG-Nummern bei #36.

Wenn das BSZ jetzt sagt dass es sich bei 007 um ein Pflichtfeld handelt, dann müssten wir ja eigentlich mit einem Fehler abbrechen wenn für die ISSN noch keine physical form hinterlegt ist, oder?

**Comment by mtrojan-ub** [comment]
Brauchen wir die Map-Datei überhaupt?

Wir haben bisher eine Regelung die sich auf Online ISSN (eppn) bzw. Print ISSN (pppn) aus Zeder bezieht.
Ist die Online ISSN vorhanden, wird diese für den Uplink mit ausgespielt, ansonsten wird die Print ISSN verwendet.

Sollen wir bei Online ISSNs immer elektronisch setzen und bei Print ISSNs immer nicht-elektronisch? Dann könnten wir uns die Map-Datei sparen.

**Comment by mtrojan-ub** [comment]
**007:**
Das Format für `cr|||||` haben wir jetzt so umgestellt. 
Für die Unterscheidung print/online würde @ruschein eine andere Lösung bevorzugen. Es besteht ja auch eine Abhängigkeit zwischen 007 und 773w+x.
Wenn wir eine online-ISSN und PPN haben, setzen wir den Datensatz auf elektronisch. Sind stattdessen nur print-PPN und ISSN vorhanden, setzen wir ihn auf print.
Falls Zotero eine ISSN liefert, muss diese entweder mit print oder online ISSN übereinstimmen, und die passende ISSN/PPN + physical form wird dann verwendet.
(Mit dieser Lösung können wir ebenfalls auf die Map-Datei verzichten, aber es natürlich voraussetzen dass die Online/Print ISSNs und PPNs in Zeder gut gepflegt sind).

Falls Sie hier noch Diskussionsbedarf sehen, so würde ich Sie bitten dies im Meeting am Donnerstag direkt mit @ruschein zu besprechen.

**008:**
Ist so umgesetzt, allerdings kann es ja sein, dass manche Felder von Zotero nicht erkannt werden. 
Im schlimmsten Fall würden wir also sowas wie `||||||n||||||||eng` liefern.

**Comment by kdr154** [comment]
007
laut DNB-Doku ist das Feld 14 Positionen lang, wenn an Position 0 ein "c" steht.
Wenn der Datensatz auf Print gesetzt wird, muss an Position 0 ein "t" stehen. Das Feld ist dann nur 2 Positionen lang.  An Position 1 wird nur unterschieden zwischen Loseblattsammlung (Wert "d") und nicht spezifiziert (Wert "u").  In unserern Fällen ist es unwahrscheinlich, dass es sich um Loseblattsammlungen handelt. Ich weiß im Augenblick auch nicht, anhand welcher Kategorien man das unterscheiden kann. D. h. der Standardwert für die Position 1 sollte "u" sein. Das Feld 007 müsste folglich im Fall eines Printdokuments  so aussehen: 
`<controlfield tag="007">tu</controlfield>`
Im Falle eines "c" an Position 0 weicht die Länge des Feldes in den SSOAR-Daten von der Vorgabe der DNB-Doku ab. Jedenfalls bei denen, die ich einsehen kann.
008
wird benötigt, wenn 264 c keinen brauchbaren Inhalt hat. In unseren Daten kommt 264 c gar nicht vor. D. h. wir brauchen 008 auf jeden Fall und es liefert auch nur dann brauchbare Ergebnisse, wenn 936 j besetzt ist.
264 c enthält die Veröffentlichungsangabe. Und hier scheitere ich wieder an der Doku des BSZ, welche Picakategorie abgegriffen wird. (1100 oder 4030). Aber egal welche. Wir haben Sie nicht. Deshalb benötigen wir unbedingt 936 j mit einem gültigen Wert. Sonst kommt es zu einem Fehler und der Datensatz kann nicht gespeichert werden. 
Die Frage ist auch und vor allem, warum 264 c im Gegensatz zu den SSOAR-Daten hier nicht enthalten ist.

**Comment by jriedl** [comment]
Nach meiner Erinnerung wurde beim Besuch von Frau Katz und Frau Bühler besprochen, dass 008 vom BSZ generiert wird - hier findet sich ja auch das Ersterfassungsdatum, auf das wir unmittelbar keinen Einfluss haben und 008 findet sich auch nicht in SSOAR-Konkordanz. Deshalb erscheint es sinnvoll, das Feld 264 zu befüllen. Verlagsort und Verlagsname sollten sich ja anhand der PPN der zugrundeliegenden Zeitschrift ermitteln lassen.

**Comment by kdr154** [comment]
Lieber Herr Riedl,

 

vielen Dank für die Information. In den SSOAR-Daten steht hier aber lediglich eine Veröffentlichungsangabe in der Form:

<datafield tag="264" ind1=" " ind2="1">

<subfield code="c">2010</subfield>

etwas anderes finde ich dort nicht.

Wenn man es also befüllen wollte, was in meinen Augen Sinn macht, dann nur mit dem Wert, der im Zoterofeld Datum steht. Die vierstellige Jahresangabe müsste dann ggf. um mögliches Beiwerk (August oder ähnliche Dinge), bereinigt werden

 

 

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: jriedl <notifications@github.com> 
Gesendet: Mittwoch, 28. November 2018 09:43
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Controlfields 005, 007, 008 (#123)

 

Nach meiner Erinnerung wurde beim Besuch von Frau Katz und Frau Bühler besprochen, dass 008 vom BSZ generiert wird - hier findet sich ja auch das Ersterfassungsdatum, auf das wir unmittelbar keinen Einfluss haben und 008 findet sich auch nicht in SSOAR-Konkordanz. Deshalb erscheint es sinnvoll, das Feld 264 zu befüllen. Verlagsort und Verlagsname sollten sich ja anhand der PPN der zugrundeliegenden Zeitschrift ermitteln lassen.

**Comment by jriedl** [comment]
Lieber Herr Rosenkranz, ja genau, wenn es das 264c in den SSOAR-Daten nicht gab, wurde versucht, es aus anderen Jahresangaben zu erzeugen. Ursprünglich und laut Konkordanz war das 264c einmal des "Hauptübergabefeld" für das Jahr gedacht, aber es kam dann noch die Befüllung der 936 dazu, so dass hier das Jahr ebenfalls noch einmal vorhanden ist.

**Comment by mtrojan-ub** [comment]
zu 007:
Aktuell ist es schon so, dass im Fall von print `<controlfield tag="007">tu</controlfield>` und im Fall von online `<controlfield tag="007">cr|||||</controlfield>` (wie bei SSOAR) ausgespielt wird. Somit müsste das ja inhaltlich passen, richtig?

zu 008:
Da 008 nicht vom BSZ importiert wird, entferne ich es also wieder und wir spielen 936j und 264c aus, richtig?
Zu den 936er Feldern gab es bisher die Beschränkung, dass diese nur dann ausgespielt werden wenn Zotero einen "journalArticle" oder "magazineArticle" oder "newspaperArticle" findet. Diese Beschränkung nehmen wir raus, dann sollte auch 936j öfter gesetzt werden. Allerdings haben wir keine Garantie dass Zotero immer ein Jahr liefert. Ist es ok wenn wir, falls das Jahr fehlt, das aktuelle Kalenderjahr setzen?
(264c wird momentan noch gar nicht ausgespielt, ich würde es dann mit ausspielen und auf den gleichen Wert wie 936j setzen, richtig? Wobei die BSZ Konkordanz sagt dass 264c nur dann ausgewertet wird wenn Header Pos. 7 = m, also Monographie...)

**Comment by mtrojan-ub** [comment]
OK, ist jetzt so umgesetzt!

**Comment by kdr154** [comment]
ind2 in 264 muss 1 sein, ind1 bleibt leer

**Comment by kdr154** [comment]
oder auch nicht. In der Umsetzungstabelle von Frau Katz sind beide Indikatoren leer.

**Comment by mtrojan-ub** [comment]
Muss hier noch etwas angepasst werden oder hat es sich damit erledigt?

**Comment by kdr154** [comment]
Wir lassen es so. Z. Zt. entspricht es der Umsetzungstabelle von Frau Katz. Sollte es nach einem Probelauf Widerspruch geben, kann man es immer noch ändern
