### ISSUE TITLE
ISSN 1759-8931 | Transformation | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1231]
Dieser Artikel: https://journals.sagepub.com/doi/full/10.1177/0265378820933284 in diesem Heft: https://journals.sagepub.com/toc/trna/37/3 ist in meinen Augen keine Rezension. 
Dieser schon: https://journals.sagepub.com/doi/full/10.1177/0265378820931890
Bei beiden greift der review_regex, denn sie sind als Review Article gekennzeichnet.

![grafik](https://user-images.githubusercontent.com/29707105/98680970-6e589b80-2362-11eb-9410-3e3c315d194a.png)

So etwas muss man beim vollautomatischen Verfahren wohl in Kauf nehmen?

**Comment by socheres** [comment]
"Review Article" bitte nicht als Rezension markieren. Nur "Book reviews". Weder global noch in der [enhancement ](https://github.com/ubtue/zotero-enhancement-maps/blob/44990401470d73a27a9e5f361b4db013006c4e1d/zotero_harvester.conf#L3806) finde ich entsprechenden Regex, der auf "Review Article" matcht.

**Comment by kdr154** [comment]
Werden aber beide auf benu ohne ein additional config als Rezension mit 655 getagt.

**Comment by socheres** [comment]
bisher sind folgende Item-Type im [Sage translator] (https://github.com/socheres/translators/blob/9b973882052a48e291d8ae4c1f3d6d498a79100e/SAGE%20Journals.js#L144-L152) als Rezension definiert. "Review Article", "Product review", "Book review". Bei den "Review Article" handelt es sich streng genommen nicht um eine Rezension. Daher ändere ich den Regex im Sage Translator.

**Comment by kdr154** [comment]
655 nur noch bei "Book review"
