### ISSUE TITLE
ISSN 0335-5985 | Archives de sciences sociales des religions | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1232]
Hier gibt es jeweils drei Abstracts, Übertragen wird aber nur eines.
Z. B.: https://journals.openedition.org/assr/51621

**Comment by helenanebel** [comment]
Lieber @socheres ,
wie ist denn das Vorgehen in so einem Fall? Wenn Sie mir das erklären, kann ich mich darum kümmern.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Anders als im Zotaut werden weitere Abstracts ins Feld `item.abstractNote` geschrieben. An jedem Satzende eines Abstract fügt man noch "\\n4207 " als Trenner hinzu (ein Blank hinter Zahlen!). Siehe auch https://github.com/ubtue/DatenProbleme/issues/1402

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe das angepasst.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Zur Info @helenanebel
\\4207 ist im Pica-Exportergebnis hardcodiert, daher muss back slash maskiert sein: \\\n4207

**Comment by kdr154** [comment]
Sieht jetzt gut aus.
