### ISSUE TITLE
ISSN 1703-289X | The Journal of Religion and Popular Culture | fehlende Buchstaben bei Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1233]
Einem Kollegen ist aufgefallen, dass bei diesem Artikel https://www.utpjournals.press/doi/full/10.3138/jrpc.2017-0034 der letzte Buchstabe bei den Keywords abgeschnitten wird:
![grafik](https://user-images.githubusercontent.com/29707105/98805102-6444a480-2417-11eb-8ba7-c960d70b3aae.png)

Nun fehlt mir die Möglichkeit, dies wirklich zu überprüfen, weil mir nur der Atypon-Translator für den Download angeboten wird, und der liefert gar keine Keywords mit. In meinen Augen sollte in diesem Fall der ubtue_University_of_Toronto_Press.js-Translator genommen werden. Dieser ist aber nicht in der Auswahl. Falls nicht, hätte man die Keywords manuell nachgetragen. Dass bei diesem Prozess bei allen Keywords der letzte Buchstabe verloren gegangen ist, halte ich für ausgesprochen unwahrscheinlich.

Der Lokalsatz hat zudem das Abrufzeichen zota. Meines Wissens war diese ZS aber noch nie Live.

**Comment by IxKo** [comment]
Beim Testen auf NU werden die Keywords bei diesem Heft ebenfalls abgeschnitten.
Im Heft davor jedoch nicht.
Im Quellcode der jeweiligen Websites sind die Keywords komplett.

**Comment by socheres** [comment]
hierzu gab es eine eMail von @IxTheoKm 
Wie sehen die Keywords jetzt im Zotkat aus?

**Comment by kdr154** [comment]
Keiner der angebotenen Translatoren liefert Keywords. ubtue_University_of_Toronto_Press.js-Translator nicht in der Auswahl. Somit kann ich auch jetzt nichts dazu sagen, schlicht weil die Daten fehlen.

**Comment by IxKo** [comment]
Heute wird mir der Translator Ubtue University of Toronto Press im Multi-DL angeboten.
Keywords kommen mit ohne abgeschnitten zu werden.

**Comment by socheres** [comment]
habe gerade den Translator Ubtue University of Toronto Press aktualisiert.

**Comment by IxKo** [comment]
Einige Artikel kommen mit einer ISSN rüber und andere nicht.

**Comment by kdr154** [comment]
Bei der Ausgabe 31.2019,3 wird nur bei einem Artikel eine ISSN übertragen. Dafür kein DOI. hier: https://www.utpjournals.press/doi/full/10.3138/jrpc.2017-0068
Aber die Keywords werden nicht gekappt.

**Comment by socheres** [comment]
- [ ] Übernahme ins zotaut-Verfahren?

**Comment by kdr154** [comment]
ISSN und DOI nun immer dabei. Prode steht bereits auf zotat.
