### ISSUE TITLE
ISSN 2167-776X | Journal of pastoral care & counseling | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1234]
Das ist ebenfalls eine Rezension https://journals.sagepub.com/doi/abs/10.1177/1542305020947646
Additional config etwa in der Form: zotero_review_regex                        = *abstract:(?i)review, auch in Varianten, führt nicht zum gewünschten Ergebnis.

**Comment by socheres** [comment]
Grundsätzlich Item-Typ "Research Article" nicht als Rezension taggen. Nur Artikeln mit der Rubrik(=Item-Type) "Book Reviews". Z.I. @IxKo

**Comment by kdr154** [comment]
ok
