### ISSUE TITLE
ISSN 2328-1030 | Journal of Spiritual Formation & Soul Care | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1237]
Auch hier wird ein Review Essay/Review Article als Rezension getagt: https://journals.sagepub.com/doi/full/10.1177/1939790920963489
was ja laut @socheres in #1231 nicht sein sollte.

**Comment by socheres** [comment]
bitte auf benu testen.

**Comment by kdr154** [comment]
655 nicht mehr vorhanden.
