### ISSUE TITLE
ISSN 2328-1030 | Journal of Spiritual Formation & Soul Care | Bestandteile des Namens

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1238]
Bei diesem Artikel wird die Zählung der Dritte (III) unterdrückt: https://journals.sagepub.com/doi/full/10.1177/1939790920963484
Dies wurde in #1223 diskutiert, aber noch nicht ableschlossen.
Wie verhält es sich mit den Anführungszeichen bei "Trey", was wohl einen Rufnamen oder Spitznamen kennzeichnet. Spricht etwas dagegen, dass man das so übernimmt, und in diesem Fall in  Pica 3000 dann steht: Clark, Edgar “Trey”

**Comment by IxKo** [comment]
Einen ähnlichen Fall gibt es auch bei einer KrimDok-Zs: https://doi.org/10.1177/1077801219884123
Wilfreda E. (Billie) Thurston

**Comment by IxKo** [comment]
Da dies eine zota-Zs ist, fiel hier eine Entscheidung? @socheres

**Comment by socheres** [comment]
Namenszusätze in Klammern oder Anführungszeichen werden so nach der Vorlage eingespielt.
