### ISSUE TITLE
ISSN 1748-0922 | Religious Studies Review | Artikelauswahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1239]
Bei dieser Zeitschrift handelt es sich um eine reine Rezensionszeitschrift. Von den 201 Einträgen in diesem Heft: https://onlinelibrary.wiley.com/toc/17480922/2020/46/3
sind 185 Short reviews. Umfand 0,5-2 Seiten. In dem zurückliegenden Ausgaben ist das Verhältnis ungefähr genauso. Bei diesen zurückliegenden Ausgaben hat man darauf verzichtet, diese zu erfassen. 
Unglücklicherweise liefert Zotero bei diesem Short reviews keine Verfassser. Sie stehen auf den einzelnen Seiten am Ende der Kurzrezension.
Die Fragen die sich mir stellen:
- sollen diese Kurzrezensionen überhaupt erfasst werden
- wenn ja, soll man sie ohne Verfasser einspielen
- wenn eingespielt werden soll und ein Verfasser gewünscht wird, sollte ein Translator geschrieben werden, der diesen mit erfasst.

Die Webseiten der Kurzrezensionen sehen so aus: https://onlinelibrary.wiley.com/doi/10.1111/rsr.14735

**Comment by thefass** [comment]
1. Die Kurzrezensionen sollten auch aufgenommen werden
2. Verfasser sollten erfasst werden, aber: Verfasser könnten wir nicht manuell nacherfassen > es sollte ein Translator geschrieben werden

**Comment by hlindeboom** [comment]
Die Autorennamen sollten jetzt erfasst werden.

**Comment by kdr154** [comment]
Leider nein, bei den Short reviews nicht. Weder im Multi-DL noch im Single:

![grafik](https://user-images.githubusercontent.com/29707105/100101799-01b1c680-2e63-11eb-97bd-d2b57a7fbf14.png)

**Comment by kdr154** [comment]
Hier würde sich ein weiterer Versuch lohnen

**Comment by hlindeboom** [comment]
Die Änderung wurde auf nu eingespielt. Die Autorennamen sollten diesmal erfasst werden.

**Comment by kdr154** [comment]
Bekomme weiterhin keine Verfasser bei den Kurzrezensionen.

https://onlinelibrary.wiley.com/doi/10.1111/rsr.14681

![grafik](https://user-images.githubusercontent.com/29707105/104205221-713d3e80-542e-11eb-87c6-81931797b72b.png)

**Comment by hlindeboom** [comment]
Auf nu mit Try URL leider nicht reproduzierbar. 
![image](https://user-images.githubusercontent.com/73896204/104315004-95565980-54da-11eb-88f8-eef01c12b705.png)

**Comment by kdr154** [comment]
Wenn sich der Translator im halbautomatischen Verfahren nicht anpassen lässt, wäre es am Besten, man bearbeitet diese Zeitschrift ab sofort vollautomatisch.

**Comment by socheres** [comment]
Die Änderungen auch ins Zotkat übernommen. Bitte testen.

**Comment by kdr154** [comment]
Hat geklappt. Danke.

**Comment by IxKo** [comment]
@kdr154 Dann kann in Zeder auf ausw=voll umgestellt werden?

**Comment by kdr154** [comment]
https://onlinelibrary.wiley.com/toc/17480922/2021/47/1?campaign=woletoc
https://onlinelibrary.wiley.com/doi/10.1111/rsr.15068
Die Kurzrezensionen bekommen wieder keine Verfasser. 
Darüber hinaus wird bei keinem Aufsatz das Rezenionstag gesetzt. Es sind aber fast ausschließlich Rezensionen.
Rezensionen sind die Review Essays und die Shorter Reviews ...

Der verwendete Translator war ubtue_Wiley.

![grafik](https://user-images.githubusercontent.com/29707105/122380135-d9f18f80-cf67-11eb-9f64-206fb7722cee.png)

**Comment by helenanebel** [comment]
Lieber @kdr154 , lieber @socheres ,
ich habe den Translator angepasst. Bei den Tests, die sich nicht auf Zeitschriften beziehen, habe ich die Änderungen ignoriert. Ich musste in getAuthorName hinter der Regex für den Titel der Person eine Word-Boundary (\b) einfügen, sonst wurde bei Namen, die mit "Ma" begannen, dieses immer entfernt.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Es bekommen nun alle Aufsätze das Rezensionstag. 
Aber nur acht haben einen Verfasser. 128 aber, das sind die short reviews, haben weiterhin keinen.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
bei mir haben in Stichproben alle Artikel einen Verfasser. Könnten Sie mir eine konkrete URL nennen?
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe nochmal geprüft:
![grafik](https://user-images.githubusercontent.com/49190455/126171456-afa91325-26bd-42e2-a3f2-12b0c3274958.png)
Bei mir sind alle Rezensenten enthalten. @socheres , kommen bei Ihnen die Rezensenten mit?
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Test auf nu: 
https://onlinelibrary.wiley.com/doi/10.1111/rsr.15041

![grafik](https://user-images.githubusercontent.com/29707105/126174018-eb099019-b017-4b3c-bc95-ce1bdc9dc874.png)

Im Grunde genommen alle Artikel, die auf diesen in dem Heft https://onlinelibrary.wiley.com/toc/17480922/2021/47/1 folgen.

Sie haben alle im Gegensatz zu denen, bei denen es Verfasser gibt, keine "First page", aber die Verfasser stehen auf der Webseite unterhalb der Rezension (wenn man "Full text" aufruft).

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
das Issue steht auf SEMI-AUTO. Dann bitte dieses Label entfernen, wenn es kein SEMI-AUTO-Issue ist.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
da die Verfassernamen im RSS-Feed nicht enthalten sind, kann das auf NU auch m.E. nicht funktionieren, oder?
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Warum nicht? Ich dachte der RSS-Feed dient dazu, die Webseite aufzurufen und dass die Daten von dort abgegriffen werden. Dann würde es funktionieren.

**Comment by kdr154** [comment]
In diesem Fall ist der Wert in prode ausschlaggebend.  Dieser ist zotat. Die Einstellungen auf Zeder sind korrekt. In prodf steht die aktuelle Katalogisierungsmethode. Auch das ist richtig.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich hatte angenommen, dass die Daten direkt aus dem RSS-Feed übernommen werden. Das hatte ich wohl falsch verstanden. Ich prüfe beim Bearbeiten nicht in ZEDER, deshalb bitte korrekt labeln. Dann fällt das Issue gar nicht in meinen Aufgabenbereich.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Was war ursprünglich mal korrekt gelabelt (12.11.2020), wurde am 10.6.2021 in den Test für das vollautomatische Verfahren überführt. Wenn es vollautomatisch nicht möglich ist, ist es in diesem Fall besser, den Translator für das halbautomatische Verfahren anzupassen, denn die überwiegende  Anzahl der Artikel sind die Short review, und die Zeitschrift halbautomatisch zu bearbeiten. Denn die Verfasser sind auf bei den Short reviews erwünscht.  Er hat ja mal funktioniert (s. o.)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
in dem Fall wäre es schon Ready for Testing - für ZotKat ist der Translator angepasst. Aber das wäre dann auch für Zota möglich.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Dann doch "Einspielung_Zotero_Auto" und "Zotero_Auto_Rss"?

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe versucht, das Problem zu lösen.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Das hat geklappt. Bitte bescheid geben, wenn die Anpassungen auch auf ub28 angekommen sind.

**Comment by jriedl** [comment]
ub28 wurde gerade aktualisiert.

**Comment by kdr154** [comment]
Super. Setze die ZS auf live.
