### ISSUE TITLE
ISSN 2366-0597 | Forum Exegese und Hochschuldidaktik: Verstehen von Anfang an (VvAa) | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1242]
Die Keywords werden nicht erfasst. Hier mit dem Begriff "Schlüsselwörter" bezeichnet
https://elibrary.narr.digital/article/10.2357/VvAa-2020-0004
Wenn man die Exportfunktion nimmt, Exportieren nach RIS, sind sie dabei

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe einen neuen Translator ubtue_Narr erstellt, der das Abstract und auch die Keywords mitnimmt.
siehe ubtue/DatenProbleme#1242
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Danke. Passt!
