### ISSUE TITLE
ISSN 2366-0597 | Forum Exegese und Hochschuldidaktik: Verstehen von Anfang an (VvAa) | Zusatztitel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1243]
Der Zusatztitel wird nicht erfasst. 
Bsp. https://elibrary.narr.digital/article/10.2357/VvAa-2019-007
Hier findet sich in Zotero nur "Ist da jemand?" Der Zusatztitel "Ein webbasiertes asynchrones Seminar im Einsatz" fehlt.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe das aktualisiert, ebenfalls im neuen Translator ubtue_Narr.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Sieht jetzt gut aus.
