### ISSUE TITLE
ISSN 1783-1806 | Studies in Interreligious Dialogue | fehlende ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1244]
**URL**
https://poj.peeters-leuven.be/content.php?url=issue&journal_code=SID&issue=1&vol=30

**Ausführliche Problembeschreibung**
Die ISSN wird nicht nach Zotero übertragen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
bei mir funktioniert es mittlerweile.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, bei mir nun auch!
