### ISSUE TITLE
ISSN 2617-3697 | Journal for religion, film and media | fehlende Titelzusätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1245]
**URL**
https://jrfm.eu/index.php/ojs_jrfm/issue/view/11

**Ausführliche Problembeschreibung**
Beim Multi- sowie Single-DL mit dem Translator Open Journal Systems Standard fehlen die Titelzusätze.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
bei mir tritt das nicht OJS-Standard nicht mehr auf, es kommt alles mit.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Schließe, da Zusatztitel nun dabei sind.
