### ISSUE TITLE
ISSN 2109-9502 | Revue d'histoire de l'Eglise de France | mehrere Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1249]
**URL**
https://www.brepolsonline.net/doi/abs/10.1484/J.RHEF.5.121369

**Ausführliche Problembeschreibung**
Die Artikel haben mehrere Abstracts. Diese werden auch nach Zotero übertragen und mit /n4207 getrennt.
Der normale Slash sollte aber ein Backslash sein.

**Comment by IxKo** [comment]
Werden immer noch mit einem normalen Slash getrennt.

**Comment by IxKo** [comment]
Das Problem besteht wieder bzw. es wird beim Import gar nicht mit \n4207 getrennt:
https://www.brepolsonline.net/doi/10.1484/J.RHEF.5.133763

![image](https://user-images.githubusercontent.com/57000004/226387269-10fb4dd0-9cd3-411e-b5f0-45f2eedcd005.png)

**Comment by socheres** [comment]
Das Problem tritt nicht mehr auf.
