### ISSUE TITLE
Allgemein: Nicht-Sortierzeichen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1250]
**Bsp.-URL**
https://www.vr-elibrary.de/doi/10.13109/wdor.2020.50.2.234

**Ausführliche Problembeschreibung**
Hier müsste ein @-Zeichen vor Apparel:
4000 “The Apparel Oft Proclaims the Man”$dClothing and Identity in Ezekiel 23
1500 eng

Durch das Anführungszeichen scheint die Automatik nicht gegriffen zu haben.

**Comment by IxKo** [comment]
Trifft auch auf das vollautomatische Zotero-Verfahren zu.
In die Test-Datenbank wurde bspw. dieser Titel eingespielt:
(IxTheo#2020-11-05#E8326BD09C2DA58EB754B3D194E595B8F98DA141)
![image](https://user-images.githubusercontent.com/57000004/100608132-467aa900-330c-11eb-8f46-4e9fe207df8f.png)

**Comment by socheres** [comment]
Das Nicht-Sortierzeichen bei maschineller Einspielung hat keinerlei Auswirkung auf die Anzeige in IxTheo. Daher ist das Et-Zeichen beim Zotaut-Verfahren nicht ergiebig.

**Comment by IxKo** [comment]
Im halbautomatischen Verfahren wird das @-Zeichen weiterhin nicht mit ausgegeben.
Beim vollautomatischen Verfahren ist doch das BSZ dafür verantwortlich, oder?
Mit so einem alten Aufsatz kann ich das jedoch nicht testen. Hier müssen zukünftige Einspielungen mit einem solchen Anführungszeichen-Fall beobachtet werden.

**Comment by socheres** [comment]
Bitte nochmal testen. Habe das hochgestelle Komma -anderes Unicode - übersehen. Das Nicht-Sortierzeichen funktioniert nur im zotkat. Im Zotaut ist der BSZ-Konverter verantwortlich.

**Comment by IxKo** [comment]
Funktioniert nun mit Zotero, danke!

**Comment by socheres** [comment]
Bitte auch #1468 #1105 #1095 testen.
