### ISSUE TITLE
ISSN 2514-0582 | Journal of Egyptian Archaeology | Nicht dargestellte Teile im Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1251]
Hier werden Teile des Abstracts nicht dargestellt: https://journals.sagepub.com/toc/egaa/104/1
Wahrscheinlich weil es sich um Bilder handelt.

**Comment by socheres** [comment]
Können Sie bitte einen Artikel-Link angeben?

**Comment by kdr154** [comment]
https://journals.sagepub.com/doi/full/10.1177/0307513319829402

**Comment by socheres** [comment]
siehe https://github.com/ubtue/DatenProbleme/issues/996
