### ISSUE TITLE
ISSN 1799-3121 | Approaching Religion | Titelzusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1254]
Der Titelzusatz wird abgeschnitten.
https://journal.fi/ar/article/view/91844
![grafik](https://user-images.githubusercontent.com/29707105/99521511-ca3fa780-2994-11eb-83aa-109407547c15.png)

**Comment by hlindeboom** [comment]
Problem sollte behoben sein.

**Comment by kdr154** [comment]
Leider nicht. Ist weiter der  Fall, mit welchem Translator und welchem Verfahren es man versucht (Multi oder Single)
![grafik](https://user-images.githubusercontent.com/29707105/100097400-cb714880-2e5c-11eb-882d-aeb3837cbf02.png)

**Comment by hlindeboom** [comment]
Die Änderung wurde auf nu eingespielt. Mein Fehler lag darin, dass zwei Translator mit demselben Namen und derselben ISSN existieren, diesmal habe ich den richtigen angepasst.

**Comment by kdr154** [comment]
Bekomme weiter nur Ergebnisse mit abgeschnittenem Titelzusatz:

![grafik](https://user-images.githubusercontent.com/29707105/104202796-aa27e400-542b-11eb-9ae8-568e21606986.png)

**Comment by hlindeboom** [comment]
Auf nu leider nicht reproduzierbar.
![image](https://user-images.githubusercontent.com/73896204/104315242-f3833c80-54da-11eb-911f-0c711d107555.png)
Welcher Translator wird denn verwendet? Das Problem könnte nämlich beim repository liegen.

**Comment by socheres** [comment]
Änderung von hlindeboom ins Zotkat repository übernommen. Bitte testen.

**Comment by socheres** [comment]
die Anpassung ist nicht für zotkat geeignet. Kein Multiple etc, daher mache ich die Änderung wieder rückgängig.

**Comment by kdr154** [comment]
Welchen Translator soll ich da nehmen. Multi wird mir nur der Multi-Wrapper angeboten. Im Single gibt es mehrere. Der OJS-Standard liefert eine Fehlermeldung und folgendes Ergebnis: Eine Webseite als Dokumenttyp.


![grafik](https://user-images.githubusercontent.com/29707105/104330892-c2146c00-54ee-11eb-9bac-cb0ec58c16a9.png)

Der Open Journal System, das ist der, der standardmäßig genommen wird, schneidet leider wieder ab:

![grafik](https://user-images.githubusercontent.com/29707105/104331181-14558d00-54ef-11eb-93d8-545af3355e7e.png)


hier gibt es auch noch ein Problem mit den Seitenzahlen, siehe Screenshot.
Dann gibt es noch den ubtue_horizonte, den DOI und Embedded Metadata. Bei allen aber ist das Ergebnis auch nicht besser.

**Comment by socheres** [comment]
Verwendet Sie "ubtue_Open Journal Systems Standard.js".

**Comment by kdr154** [comment]
Titelzusatz kommt jetzt mit
