### ISSUE TITLE
ISSN 1943-1562 | Psychology of religion and spirituality | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1258]
Für diese Zeitschrift https://psycnet.apa.org/PsycARTICLES/journal/rel/12/4 gibt es den Translator APA PsychNet.js, dieser gibt beim Multi-DL die Fehlermeldung aus: Es ist ein Fehler aufgetreten beim Versuch, diesen Eintrag zu speichern. 
Beim Single-DL funktioniert er, die ISSN wird aber in der folgenden Form übertragen: 

![grafik](https://user-images.githubusercontent.com/29707105/100203237-9fa89e00-2f02-11eb-85ca-834678bab223.png)

Soll man das so in der Mapping-Tabelle ablegen?

**Comment by helenanebel** [comment]
Lieber @kdr154 , lieber @socheres ,
hier hat sich leider die Seitenstruktur so verändert, dass die Inhalte durch ein Skript generiert werden; die Links zu den einzelnen Artikeln sind auf der Issue-Seite im Seitenquelltext nicht mehr vorhanden. Eventuell kennt socheres dafür eine Lösung?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
die Webseite blockiert das Multi-DL. https://forums.zotero.org/discussion/86926/error-importing-references-to-zotero
Man kann nach Anmeldung einzelne Einträge via "+Add To My List" in "My List" sammeln und dann nach Zotero exportieren.
![image](https://user-images.githubusercontent.com/1545743/120500054-d7683500-c3c0-11eb-8122-42831e0fabce.png)

> Soll man das so in der Mapping-Tabelle ablegen?

Ja, so wie in der Vorlageform  "1943-1562(Electronic),1941-1022(Print)"

**Comment by kdr154** [comment]
Mit Export über Zwischenablage klappt es.
