### ISSUE TITLE
Allgemein: Titel wie "In Memory", "In Memoriam"

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1259]
**Bsp.-URL**
https://doi.org/10.1177%2F1077801220952970

**Vorschlag**
Titel wie diese sollten in der Error-Datei aufgefangen werden und dann sollte intellektuell über sie entschieden werden.

Im Beispiel würde entschieden werden, dass der Datensatz nicht aufgenommen werden soll.

**Comment by IxKo** [comment]
Bei heutiger VC
Es soll von der Fachgemeinschaft entschieden werden, ob solche Titel überhaupt ausgeschlossen werden und wenn ja, ob es dabei Ausnahmen geben soll.

Bis dahin werden diese Titel **nicht** prinzipiell gefiltert.

**Comment by IxTheoKm** [comment]
Ich wäre mit generellem Ausschluss vorsichtig: 
es gibt auch ausführlichere Nachrufe, die nur mit dem Titel "In memory" oder "In memoriam" publiziert werden (ggf. ergänzt durch Namen, die typographisch wie Untertitel dargestellt sind). Ausführlichere Nachrufe haben wir bisher erfasst. 
So kurze Todesmitteilungen wie im o.g. Beispiel nicht. Das lässt sich aber nur intellektuell durch den Volltext entscheiden.

**Comment by socheres** [comment]
"In memory" oder ähnliche Nachrufe nehmen wir mit auf.
