### ISSUE TITLE
Allgemein Keywords Tag 655

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#126]
Lässt es sich einrichten, dass einige bestimmte Keywords, die nicht den Inhalt beschreiben sondern eigentlich sogenannte Formschlagwörter sind, in MARC-Feld 655 a statt 650 a abgelegt werden?
Momentan ändern wir die Zuordnung manuell. Das wird aber leicht übersehen.

Dazu gehören derzeit:
"Peer reviewed"
"Open access"

Falls weitere Keywords auftauchen, müsste die Liste entspr. erweitert werden.

Beispiel: https://ixtheo.de/Record/506891046#details

**Comment by mtrojan-ub** [comment]
Ja, das lässt sich machen. Soll auch eine Verlinkung zur GND eingetragen werden?

**Comment by IxTheoKm** [comment]
Nein, bitte keine GND-Verlinkung.

Die externen Keywords mit den Zeichenfolgen "Peer reviewed" und "Open access" (bitte nur Keywords, die _nur_ aus diesen Zeichenfolgen bestehen) werden als Formschlagwörter nicht wie die RSWK-Formschlagwörter behandelt. 

655 **4** |a Peer reviewed
655 **4** |a Open access
landen unverknüpft im PICA-Feld 5520 |f|Peer reviewed bzw. 5520 |f|Open access

Die verlinkten RSWK-Formschlagwörter stehen in
655 **7** |a

Beispiel:
https://ixtheo.de/Record/508354269#details

**Comment by thefass** [comment]
Könnten wir das externe keyword open access in der OA facette auswerten?
In dem obigen ersten Beispiel ist das nämlich noch nicht als open access erkannt:
siehe:
https://ixtheo.de/Search/Results?lookfor=Benjamin%27s+Concept+of+History+as+a+Source+of+Arendt%27s+Idea+of+Judgment+&type=AllFields&botprotect=

**Comment by IxTheoKm** [comment]
Diese Keywords sind bisher ziemlich selten vorhanden.

Als Open Access wurde der Aufsatz nicht erkannt, weil es gar keine URL in 856 in diesem Datensatz gibt. Dort wird das normalerweise verankert. 

Ist es evtl. auch möglich, die Aufsätze in der OA-Facette auszuwerten, wenn die in 773 verlinkte Gesamtaufnahme der Zeitschrift Open Access ist?

**Comment by kdr154** [comment]
Der 2. Teil der Diskussion ist noch nicht beantwortet

**Comment by kdr154** [comment]
@thefass bitte für jede Problemstellung ein eigenes Issue aufmachen. Die ursprüngliche Problematik ist nämlich gelöst und das Issue sollte geschlossen werden. So aber ist die Diskussion weiter offen

**Comment by ruschein** [comment]
@kdr154 Danke!
