### ISSUE TITLE
ISSN 0944-5706 | Jewish Studies Quarterly (JSQ) | Spracherkennung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1262]
Hier funktioniert die Spracherkennung nicht. Die Artikel sind alle auf Englisch. Zotero nennt aber immer "de".
https://www.mohrsiebeck.com/zeitschrift/jewish-studies-quarterly-jsq?no_cache=1
https://www.mohrsiebeck.com/artikel/family-and-community-commemorative-choices-among-the-jewish-epitaphs-from-rome-101628jsq-2019-0013?no_cache=1

![grafik](https://user-images.githubusercontent.com/29707105/100580621-9181c580-32e6-11eb-8089-8783a7074923.png)

**Comment by socheres** [comment]
bitte über Mapping lösen.

**Comment by kdr154** [comment]
Mapping ergänzt
