### ISSUE TITLE
ISSN 2468-9963 | Delito y sociedad – Revista de ciencias sociales | Metadaten

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1263]
Für diese Zeitschrift existiert nun offenbar auch in der Online-Version ein Nachweis in KrimDok: https://krimdok.uni-tuebingen.de/Record/1739024885. In Zeder scheint allerdings die Online-PPN noch nicht hinterlegt. Weiterhin ist im KrimDok-Datensatz als ISSN 0328-0101 hinterlegt. Offenbar ist aber 2468-9963 korrekt (vgl. https://portal.issn.org/resource/ISSN/2468-9963).

**Comment by kdr154** [comment]
Die Online-PPN habe ich hinterlegt. Bei der ISSN wird auf der Homepage der ZS aber auf ein versión digital verwiesen mit der ISSN 2362-3306. Wobei versión digital und Online-Ausgabe in meinen Augen nicht unbedingt dasselbe ist.

**Comment by jriedl** [comment]
Vielen Dank. Das mit der ISSN ist seltsam: https://portal.issn.org/resource/ISSN/2362-3306 vs https://portal.issn.org/resource/ISSN/2468-9963.

**Comment by jriedl** [comment]
Vielen Dank für die Korrektur der ISSN auch in https://krimdok.uni-tuebingen.de/Record/1739024885. Test auf nu liefert jetzt Ergebnisse. Falls inhaltlich alles ok ist, kann das Issue geschlossen werden.

**Comment by kdr154** [comment]
Die hier beschriebene Problematik ist gelöst.
