### ISSUE TITLE
ISSN 2589-0433 | Annuarium historiae conciliorum | Spracherkennung (Brill)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1265]
**URL**
https://brill.com/view/journals/ahc/49/2/ahc.49.issue-2.xml

**Ausführliche Problembeschreibung**
Hier gibt es neben deutschsprachigen Artikeln auch italienisch- und franzözischsprachige.

Es wird jedoch immer 041 ger vergeben.
Ich habe die Additional Config überschrieben mit `zotero_expected_languages = ger,eng,ita,fre
`, es hat sich am Ergebnis jedoch nichts geändert.

**Comment by IxKo** [comment]
Nachdem gestern in Zeder sprz=eng,fre,ger,ita eingetragen wurde, werden heute nur noch 7 von insgesamt 14 Datensätze mit einer Sprache auf Nu versehen.
Dies sind alles deutsche Titel, weshalb der Sprachcode ger hier stimmt. Die anderssprachigen Artikel erhalten keine Sprachkennzeichnung in 041.
Bsp.:
![image](https://user-images.githubusercontent.com/57000004/100712827-ae37ff00-33b3-11eb-85e1-e55dc7e790dd.png)

@mtrojan-ub 
**Im CLI-Output steht dazu Folgendes:** 
Converting item 8 [Annuarium historiae ...] | https://brill.com/view/journals/ahc/49/2/article-p367_7.xml {14078852691049709407}
use online ISSN "2589-0433" with online PPN "1007306068"
Normalized language: de => ger
generated too few ngrams (181 < 400)!
eng scored :0.611669
fre scored :0.658371
ger scored :0.632750
ita scored :0.599074
**The given language ger and the detected language fre are different. No language will be set.**
post-processed author first name = 'Dominique Le', last name = 'Tourneau', title = '', affix = '

**Comment by socheres** [comment]
@mtrojan-ub @ruschein warum wird in dem obigen Fall die Sprache "fre" nicht übernommen?
Es gibt zwei Fälle, wo die automatische Spracherkennung Ngram greifen soll:
1. wenn Ngram mit der von zotero translation server gelieferten Sprache übereinstimmt, wird die Sprache von Ngram übernommen.
2. Bei Abweichung wie in diesem Fall sollte trotzdem die Sprache von Ngram übernommen werden.
3. Nice to have: Ideal wäre noch, wenn die Scorewerte zwischen dem ersten und zweiten Wert zu nah beieinander liegen - zwei Nachkommastellen z.B. eng 0,611669  fre 0,611573 - , die Sprache NICHT auszugeben.
Da mittlerweile viele SAGE-Aufsätze live gegangen sind, sollte das Problem schnellstmöglich behoben werden, sonst produzieren wir viel Ausschuss.

**Comment by mtrojan-ub** [comment]
Regel 2) Hatte ich in unserer VC so verstanden, dass die Sprache nur dann übernommen werden soll, wenn das NGram-Ergebnis (hier fre) mit der Sprache des Artikels (hier ger) übereinstimmt. Das ist hier nicht der Fall, daher wurde keine Sprache ausgegeben. Wenn wir das aushebeln würden, wäre ja die Regel 1) vollkommen nutzlos, da sie immer von Regel 2) überschrieben wird.

**Comment by kdr154** [comment]
Das war ja unsere @IxKo und meine Rede

**Comment by socheres** [comment]
hierzu soll noch ein Meeting mit @ruschein und @mtrojan-ub geben.

**Comment by mtrojan-ub** [comment]
Der aktuelle Stand dazu befindet sich in #1300
