### ISSUE TITLE
ISSN 1983-2850 | Revista Brasileira de História das Religiões | Abbruch Multi-DL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1268]
Ein Versuch, diese Zeitschrift per Multi-DL mit dem Translator Open Journal System Standard zu speichern führt zum Abbruch.
http://www.periodicos.uem.br/ojs/index.php/RbhrAnpuh/issue/view/1635#
Es ist ein Fehler aufgetreten beim Versuch, diesen Eintrag zu speichern

**Comment by hlindeboom** [comment]
Meinten Sie den ubtue_Open Journal Systems Multi-Wrapper? Dieser wird mir für die von Ihnen angegeben Webseite empfohlen. Der Open Journal Systems Standard Translator ist meines Wissens lediglich für einzelne Artikel anwendbar.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,

bei mir funktioniert das mit dem ubtue_Open Journal Systems Multi-Wrapper ebenfalls reibungslos. Falls das Problem nicht mehr vorliegt, könnten Sie dann das Issue schließen?

Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Die Jahresangabe ist nicht korrekt. 
Der Zusatztitel fehlt.
Sowohl im Multi mit dem Multi-Wrapper, als auch im Single mit dem Open_Journal_Systems.

https://www.periodicos.uem.br/ojs/index.php/RbhrAnpuh/article/view/54840

![grafik](https://user-images.githubusercontent.com/29707105/120970047-32a47980-c76b-11eb-95bb-b2bcd2a63cd5.png)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
das Problem ist, dass hier im Translator ein anderer Translator aufgerufen wird, der die DOI abruft, diese ist aber nicht valide. Ich schaue, was sich da machen lässt.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
das Problem ist, dass hier im Translator ein anderer Translator aufgerufen wird, der die DOI abruft, diese ist aber nicht valide. Ich schaue, was sich da machen lässt.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
wenn die Änderungen übernommen wurden, müsste der ubtue_Open Journal Systems Standard die Jahreszahl und den Zusatztitel korrekt übernehmen.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Liebe @helenanebel, beim Testen bitte Einzel-Url aufrufen und die Testergebnisse aller anderen URLs updaten.

**Comment by helenanebel** [comment]
Lieber @socheres ,
die Einzel-URL hatte ich vergessen, danke für den Hinweis. Die anderen Tests hatte ich aber eigentlich geprüft, ob sie noch laufen.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Jahresangabe und Zusatztitel nun dabei. Bei den Seitenzahlen kann man wohl nichts machen.
