### ISSUE TITLE
ISSN 1983-2850 | Revista Brasileira de História das Religiões | Jahr fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1269]
Beim Single-DL findet sich die Bandangabe im Zotero-Feld Datum und keine Datumsangabe.
http://www.periodicos.uem.br/ojs/index.php/RbhrAnpuh/article/view/54656
![grafik](https://user-images.githubusercontent.com/29707105/100629770-f7dc0780-3329-11eb-909b-dd0257b27771.png)

**Comment by jriedl** [comment]
@socheres Im Rahmen der Entwicklung aufgefallen: Problem ist hier das Vorhandensein mehreren Translators für "Open Journal Systems" mit überschneidenden Targets. Es kommen sowohl "Open Journal Systems.js" als auch "ubtue_Open Journal Systems Standard.js" in Frage. Sollte auf "Open Journal Systems.js" nicht zukünfitg ganz verzichtet werden?

**Comment by IxKo** [comment]
Ist behoben, danke!
