### ISSUE TITLE
Scielo ISSN 0718-9273 From rationality to credibility Tag 520 a

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#127]
Immer wieder, so auch im Fall dieser Zeitschrift, erscheint in 520 a der Begriff Resumen, Abstract am Beginn des Textes.
Hier etwa heiß es:
```
<datafield tag="520" ind1="3" ind2=" ">
<subfield code="a">ResumenA partir de la Ilustración, la ...
```
Könnte man diese Begriffe wie "Resumen", "Abstract", "Résumé" am Anfang in 520 a entfernen?

**Comment by mtrojan-ub** [comment]
@shadeMe : Das sieht nach einem Translator-Problem aus. "Resumen" ist die Überschrift, die mit nach Zotero übernommen wird. Kannst Du Dir das bitte anschauen?

https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0718-92732018000200009&lng=en&nrm=iso&tlng=en

**Comment by kdr154** [comment]
Gelöst
