### ISSUE TITLE
Try URL bei Brill-Zeitschriften liefert kein Ergebnis

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1275]
Try URL funktioniert auf nu mit Zeitschriften von Brill nicht. Auch bei Dead Sea Discoveries ISSN 1568-5179 erhält man eine leere XML-Datei.
Ein Test mit einem Band einer Zeitschrift von Sage, etwa Social Compass, ISSN 1461-7404, hingegen war erfolgreich

**Comment by IxKo** [comment]
Kann ich bestätigen.

**Comment by socheres** [comment]
Habe gerade auf nu mit "Try URL" erfolgreich getestet: https://brill.com/view/journals/dsd/27/3/article-p331_1.xml

**Comment by IxKo** [comment]
Es kommt weiterhin zu Problemen auf Nu: https://brill.com/view/journals/bi/28/3/bi.28.issue-3.xml (Biblical Interpretation, eISSN 1568-5152).
Solange das nicht behoben ist, ist ein Testen kaum möglich, da auch ältere Hefte geprüft werden muss, falls dort Besonderheiten auftauchen, die es im aktuellen Heft momentan nicht gibt.

**Comment by kdr154** [comment]
Kann ich bestätigen.

**Comment by socheres** [comment]
Tritt das Problem vielleicht nur temporär auf? Was Nu angeht, an @mtrojan-ub adressieren.

**Comment by kdr154** [comment]
Sieht nicht so aus. Bei den von mir getesten Brill-Zeitschriften ist es aktuell auch der Fall @mtrojan-ub

**Comment by jriedl** [comment]
@socheres  Das hat nichts mit nu zu tun, sondern mit dem Handling der "multiple"-Items im Translator ubtue_Brill.js. Der xPath-Ausdruck in `getSearchResults()` scheint nicht zu matchen, deshalb bricht der Translator ab. Kann in Scaffold reproduziert werden und müsste im Translator behoben werden.

**Comment by socheres** [comment]
Ok. Dann teste ich auch in Scaffold und schaue mir den Code an.

**Comment by socheres** [comment]
@IxKo @kdr154 auf Nu kann getestet werden.

**Comment by jriedl** [comment]
Nein, kann noch nicht getestet werden, da Fehlerbild bislang unverändert

**Comment by socheres** [comment]
"Try RSS" und "Try URL" mit einzelnen Aufsatzlinks funktioniert.

**Comment by kdr154** [comment]
Try RSS stand nicht zu Debatte. Das mit Try URL für einzelne Aufsätze stimmt. Ein ganzes Heft liefert aber immer noch kein Egebnis. Wir können doch nicht jeden einzelnen Aufsatz für sich testen

**Comment by jriedl** [comment]
Das Translator-Problem ist unter Ubuntu-Systemen behoben. Die xPath-Abfrage in den Containern auf den CentOS-Systemen führt jedoch zu je nach Kontext zu einem falschen Ergebnis oder zu einem Abbruch aufgrund mangelnden Speichers. Warum der Translation-Server in den docker-Containern auf CentOS dieses Verhalten zeigt, ist noch unklar.

**Comment by socheres** [comment]
@kdr154 @IxKo der Brill-Translator ist soweit fertig. Testen Sie daher zunächst mit Try RSS (aktuelles Heft). Die älteren Jahrgänge müssen m.E. nicht zwingend systematisch getestet werden (for Meeting discussion). Auf jeden Fall ist IT dabei den Bug zu fixen, um den Test auch via Try URL für ganzes Heft zu ermöglichen.

**Comment by IxKo** [comment]
TRY RSS funktioniert auf Nu bei mir gerade gar nicht mehr. Es passiert nichts, wenn ich auf "Daten absenden" klicke. Es steht nur groß "Result" da:
![image](https://user-images.githubusercontent.com/57000004/101750425-3f535800-3acf-11eb-9927-f1a5a15ffc20.png)

**Comment by kdr154** [comment]
Kann ich bestätigen

**Comment by jriedl** [comment]
Momentan laufen Updates durch @mtrojan.

**Comment by IxKo** [comment]
Try RSS läuft nun wieder durch

**Comment by mtrojan-ub** [comment]
Updates sind abgeschlossen, hat leider etwas gedauert aufgrund von Problemen mit einem neueren C++ Compiler der mit den letzten Betriebssystem-Updates eingespielt wurde.

**Comment by socheres** [comment]
bitte mit "Try URL" testen.

**Comment by kdr154** [comment]
https://brill.com/view/journals/chrc/99/2/chrc.99.issue-2.xml

War erfolgreich

**Comment by socheres** [comment]
Ok. Dann schließe ich dieses Issue.
