### ISSUE TITLE
ISSN 1745-5316 | Ecclesiology | Rezensionen (Brill)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1276]
Rezensionen werden nicht getagt.
https://brill.com/view/journals/ecso/16/3/article-p412_412.xml

![grafik](https://user-images.githubusercontent.com/29707105/100712489-1fc37d80-33b3-11eb-94a1-53f720353067.png)

**Comment by socheres** [comment]
zumindest in diesem Heft kommen im Titel bei Rezensionen durchgehend "...written by" oder "...edited by" vor. In den strukturierten Metadaten sind Rezensionen als "article" gekennzeichnet `<meta content="article" property="og:type"></meta>,` daher lässt sich das Problem nicht über Translator, sondern über zotero_harvester_conf lösen.

**Comment by kdr154** [comment]
Rezensionen werden jetzt getagt.
