### ISSUE TITLE
1043-1578 | Social justice – A journal of crime, conflict and world order

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1277]
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26jid%3dJUS%26site%3dehost-live
Da wird versucht von Ebsco zu harvesten. Bis jetzt war ich der Meinung, dass Ebsco ungeeignet ist. Es wird auch alles verworfen, weil die Dokumente als Webseiten interpretiert werden:

![grafik](https://user-images.githubusercontent.com/29707105/100754294-34bc0300-33eb-11eb-8601-81d4f58d6eb5.png)

Die Homepage der Zeitschrift ist wahrscheinlich nicht geeignet: http://www.socialjusticejournal.org/

_Originally posted by @kdr154 in https://github.com/ubtue/zotero-journal-status/issues/539#issuecomment-736594474_

**Comment by jriedl** [comment]
Es existiert jetzt eine Anpassung am Translation-Server, die ein Harvesten auch mit EBSCO ermöglicht. Auf nu.

**Comment by kdr154** [comment]
Das Harvesten auf EBSCO klappt in diesem Fall
