### ISSUE TITLE
1492-1367 | Criminologie

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1278]
Hier bin ich der Meinung, das sieht schon sehr gut aus. Es gibt soweit ich sehe keine Rezensionen, so dass diese Problematik entfernt. Zwei Dinge könnte man verbessern. 
1. Das Abstract gibt es in drei Sprachen, erfasst werden nur zwei.
2. Dort, wo keines vorhanden ist, wird ein Pseudo-Abstract erzeugt. Formal und inhaltlich immer gleich. Mit dem Inhalt "An article from Criminologie, on Érudit." Dies aber nur einmal. Hier z. B.:
https://www.erudit.org/en/journals/crimino/2020-v53-n1-crimino05397/1070498ar/

![grafik](https://user-images.githubusercontent.com/29707105/100757730-004a4600-33ef-11eb-97a1-dd6bdb0f9028.png)

Das könnte man eventuell mit "remove_marc_field_520a   = (?i)^(An article from Criminologie, on Érudit.)$" Über die harvester.conf bereinigen.
3. Die keywords stehen unter den Abstracts, jeweils in der entsprechenden Sprache des Abstracts. Diese werden in allen vorhandenen Sprachen erfasst. Gut so. Irgendwie schwirrt es in meinem Kopf, dass die freien Schlagwörter auf 20 begrenzt sind. Meine Kollegin weiß davon nichts. Manchmal sind es recht viele. Es könnte dann der Fall sein, dass einige unter den Tisch fallen, was nicht so schön aussieht. Aber sie stehen immer in der jeweiligen Sprache gebündelt, so dass das auch nicht schlimm wäre. Ich denke, wir können das so lassen.

_Originally posted by @kdr154 in https://github.com/ubtue/zotero-journal-status/issues/538#issuecomment-736623292_

**Comment by jriedl** [comment]
ad 2) Sollte morgen auf nu sein

**Comment by kdr154** [comment]
Konnte alles behoben werden
