### ISSUE TITLE
1888-0665 | Quadernos de criminología : revista de criminología y ciencias forenses

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1279]
Hier könnte man die "Biografia" ausschließen. Bsp.: https://dialnet.unirioja.es/servlet/articulo?codigo=7623350
Sonst sehen die Daten gut aus. Zumal alle Artikel auf Spanisch sind.

_Originally posted by @kdr154 in https://github.com/ubtue/zotero-journal-status/issues/536#issuecomment-736644567_

**Comment by kdr154** [comment]
Klappt
