### ISSUE TITLE
ISSN 1904-8181 Bd. 68(2018) Analogi og genealogi Band/Heftproblematik und fehlendes Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#128]
Hier haben wir wieder die bereits bekannte Band-Heftproblematik, dass die Bandzählung als Heftzählung interpretiert wird und in Zotero fälschlicherweise im Feld Ausgabe landet statt im Feld Band.
Möglicherweise wieder ausgelöst durch die Zeichenfolge Nr. von der diesbezüglichen Zählung: 

Nummer
Nr. 68 (2018)

am rechten Rand. Auch oben im Kopf.

https://tidsskrift.dk/rvt/article/view/109103

Die Nummer darf hier nicht als Heft interpretiert werden, sondern als Band.

Zudem kommt das Abstract nicht mit.  Davon gibt es hier zwei. Eines auf Englisch, das andere auf Dänisch oder Schwedisch (bei einem anderen Aufsatz, nämlich hier: https://tidsskrift.dk/rvt/article/view/109111 ).
Eines, am besten das auf Englisch, würde genügen. Weil sonst muss man sehr wahrscheinlich erneut manuell eingreifen.
Leider wird das Englische sowohl mit "ENGLISH ABSTRACT: " eingeleitet als auch mit "ENGELSK SUMMARY:"

**Comment by kdr154** [comment]
Je nachdem, welches Format man zugrunde legt, fällt das Ergebnis unterschiedlich aus. Die Bandangabe steht in allen Fällen immer noch fälschlicherweise im Feld Ausgabe, dem Feld für die Heftangabe. Nur wenn man die Daten als Embedded Metadata überträgt, kommen die Abstracts mit. Im Fall von OJS, COinS und mittels DOI nicht. Bei COinS und DOI fehlt zudem die Sprache

**Comment by shadeMe** [comment]
Hmm, taucht der neue Translator in der Auswahl auf? Der sollte "tidsskrift.dk" heißen. Was die Bandangabe/Ausgabe Problematik angeht, habe ich den Translator gerade angepasst aber die Änderungen werden erst nächste Woche einspielt.

**Comment by kdr154** [comment]
In den Repositories, auf die ich kenne, sehe ich ihn nicht.

**Comment by shadeMe** [comment]
Jetzt ist der Translator in der Hauptbranche. Probieren Sie es bitte nochmal.

**Comment by kdr154** [comment]
Bei der Tidsskrift findet sich die Bandzählung weiterhin im Feld für die Heftzählung

**Comment by shadeMe** [comment]
Wird der richtige Translator aufgerufen, wenn Sie den Zotero Knopf im Browser klicken? Wenn Sie den Cursor darüber bringen, wird es gezeigt, welcher Translator zu verwenden ist.

**Comment by shadeMe** [comment]
Ja, denke ich auch. Also, ich schlage Folgendes vor: 

1. Wenn Sie es noch nicht gemacht haben, machen Sie einen Git-Pull. Danach sollte es sich ein "ubtue_Tidsskrift.js" Datei in dem Translator Pfad befinden.
2. Schließen Sie den Browser und den Zotero-Client.
3. Starten Sie zunächst den Zotero-Client und danach den Browser (Firefox am besten) und probieren Sie's erneut.

**Comment by kdr154** [comment]
Wie mache ich einen Git-Pull? Von wo nach wo?

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Dienstag, 18. Dezember 2018 13:01
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 1904-8181 Bd. 68(2018) Analogi og genealogi Band/Heftproblematik und fehlendes Abstract (#128)

 

Ja, denke ich auch. Also, ich schlage Folgendes vor:

1.	Wenn Sie es noch nicht gemacht haben, machen Sie einen Git-Pull. Danach sollte es sich ein "ubtue_Tidsskrift.js" Datei in dem Translator Pfad befinden.
2.	Schließen Sie den Browser und den Zotero-Client.
3.	Starten Sie zunächst den Zotero-Client und danach den Browser (Firefox am besten) und probieren Sie's erneut.

**Comment by kdr154** [comment]
Sieht jetzt gut aus.
