### ISSUE TITLE
ISSN 1475-5629 | Culture and religion | Personen-Verknüpfung GND (LIVE-Einspielung!)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1280]
**URL**
7811 IxTheo#2020-11-11#6B35357089EF4F11CF36D34C7E79590B85634B4E
7901 TUIXTH:02-12-20

**Ausführliche Problembeschreibung**
Es scheint hier etwas mit dem Personen-Lookup nicht geklappt zu haben. Es wird eine GND-Nr. an den Namen angestellt, anstatt dass die Person mit der dazugehörigen PPN verlnüpft wird: 

![image](https://user-images.githubusercontent.com/57000004/100861141-b4041200-3491-11eb-9708-dda652c08c1b.png)

**Comment by socheres** [comment]
hier muss noch das Relate-Programm von BSZ laufen, damit gnd mit PPN verknüpft wird.

**Comment by IxKo** [comment]
Okay, stimmt. Da war was. Diesen Schritt hatte ich vergessen. Danke für die schnelle Antwort!
