### ISSUE TITLE
ISSN 1475-5629 | Culture and religion | aussortierter Artikel (LIVE-Einspielung!) 

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1281]
**URL**
IxTheo#2020-07-15#8821EF42BF75EC197AD6AF21384F17756F5CC15B

**Ausführliche Problembeschreibung**
Dies ist der einzige Artikel des Heftes 20.2019,4, der nicht eingespielt wurde. Auf ub28 wird er jedoch aufgelistet als delivered:
![image](https://user-images.githubusercontent.com/57000004/100862168-1dd0eb80-3493-11eb-8bdb-b1cbe4bb3a39.png)

Schaue ich mir den Datensatz jedoch in unseren Quelldaten an (in \Default\zotero_ixtheo_200715_001.xml), dann sollte er (wie er es momentan auch ist) nicht eingespielt werden. Denn er hat völlig falsche Seitenangaben und als Band- und Heftnummer wird 0 angegeben: 

```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">0</subfield>
<subfield code="e">0</subfield>
<subfield code="h">1-19</subfield>
<subfield code="j">2020</subfield>
</datafield>
```

Müsste es auf ub28 dann nicht anders dargestellt sein?

**Comment by socheres** [comment]
@mtrojan-ub QS scheint auf ub28 nicht stabil zu laufen. Dieser Aufsatz wurde richtigerweise nicht in k10plus eingespielt, aber er sollte als "Deliver manually" den Ampelstatus "gelb" haben.

**Comment by mtrojan-ub** [comment]
Juli ist zwar schon einige Monate her, aber was ich noch nachvollziehen kann ist, dass die Datei zotero_ixtheo_20200715.xml auf dem BSZ-FTP Server im Verzeichnis UBTuebingen_Default/loaded vorhanden ist.
Somit wurde der Datensatz auch damals tatsächlich geliefert und die Anzeige ist aus unserer Sicht korrekt. Außerdem muss sie ja damals auch vom BSZ verarbeitet worden sein, sonst hätte das BSZ die Datei ja nicht nach loaded verschoben.

D.h. entweder ist auf BSZ-Seite beim Import dieses Datensatzes etwas schiefgelaufen und es gab keine Meldung an uns (könnte er z.B. aufgrund der 0-Werte in 936 d/e übersprungen worden sein?), oder der Datensatz wurde aus irgendwelchen anderen Gründen in der Zwischenzeit wieder beim BSZ gelöscht.

**Comment by IxKo** [comment]
Könnte es vielleicht mit dem Abgleich der URLs in der Datenbank zusammenhängen?
Im aktuellen Heft (https://www.tandfonline.com/toc/rcar20/20/4?nav=tocList) ist der Artikel bereits viel früher (Juli) online publiziert worden als die anderen (Sep, Okt, Nov).
Wobei 3 von den insgesamt 4 Artikeln müssten demnach Online-First-Artikel gewesen sein und dann hätte es auch die anderen beiden Artikel bei dem Abgleich treffen müssen.
Ich glaube, dass sich die Online-First-URL bei der Zs nicht ändert, wenn der Artikel endgültig in einem Heft veröffentlicht wird. In der URL existieren keine Hinweis zur Band- oder Heftangabe o.ä.

**Comment by IxKo** [comment]
Er wurde mittlerweile manuell mit ixzo eingespielt. Warum er grün auf ub28 war/ist, ist weiterhin unklar.
Er konnte nicht als delivered manually markiert werden (türkis), da er als Status grün delivered gekennzeichnet war und auch ist.
Ein anderer Artikel, der über die Funktion manuell im ZotKat-Verfahren eingespielt wurde, ist richtigerweise türkis. (http://ub28.uni-tuebingen.de/zotero_cgi?action=show_downloaded&zeder_id=1393&group=IxTheo)

**Comment by socheres** [comment]
Kann das Issue geschlossen werden? @IxKo
