### ISSUE TITLE
ISSN 1556-3839 | Criminal justice review | Dateneinspielung Test

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1282]
Von den im aktuellen Heft 45.2020,4 
https://journals.sagepub.com/toc/cjra/45/4

sich befindenden 10 Artikel finden sich nach der automatischen Einspielung in die Testdatenbank nur 5 Artikel.
2 Artikel sind in Error-Container gelandet. Zwei Rezensionen:
![grafik](https://user-images.githubusercontent.com/29707105/100878156-136e1c00-34aa-11eb-984a-bb062789469d.png)

Fraglich warum. Denn das marc 520-Feld für die Abstracts ist in den Settings weder auf nu noch auf  ub28 definiert, Aber der Grund für deren Ausschluss:
![grafik](https://user-images.githubusercontent.com/29707105/100878673-c8083d80-34aa-11eb-99f5-55f8be2fb294.png)

Die anderen drei Artikel sind nirgends zu finden. Dabei handelt es sich um zwei Rezensionen, aber auch um einen regulären Artikel. Diesen: https://journals.sagepub.com/doi/full/10.1177/0734016820906601

**Comment by kdr154** [comment]
Die fehlenden Artikel, alle Book reviews und der eine reguläre, wurden heute (3. 12.) eingespielt

**Comment by jriedl** [comment]
Records aus Testgründen gerade noch einmal resettet. Falls nächster Upload problemlos, kann das Issue geschlossen werden

**Comment by kdr154** [comment]
gestern war alles enthalten
