### ISSUE TITLE
ISSN 1552-8448 | Violence against women und ISSN 1552-6518  Journal of interpersonal violence  | Keywords (Krimdok Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1283]
Die Daten von der automatischen Einspielung auf den Testserver enthalten keine keywords. Bei einem Testlauf auf nu werden diese jedoch abgegriffen.
https://journals.sagepub.com/toc/vawa/26/15-16
https://journals.sagepub.com/doi/full/10.1177/1077801219875821
Ergebnis auf nu:
![grafik](https://user-images.githubusercontent.com/29707105/100888081-fe978580-34b5-11eb-8f40-0f1d3f53406e.png)

Dagegen in der Testdatenbank:
![grafik](https://user-images.githubusercontent.com/29707105/100888221-2850ac80-34b6-11eb-8ead-c91854e12ac9.png)

Umso erstaunlicher, als es sich um eine Zeitschrift von Sage handelt.
Es sieht so aus, als ob die Translator nicht dieselben wären.

Dasselbe gilt für ISSN 1552-6518  Journal of interpersonal violence 
Ebenfalls Sage!
https://journals.sagepub.com/toc/jiva/35/23-24
https://journals.sagepub.com/doi/full/10.1177/0886260517723746

Keine Keywords auf dem Testserver:

![grafik](https://user-images.githubusercontent.com/29707105/100895962-681b9200-34be-11eb-967f-001ef129340a.png)

**Comment by kdr154** [comment]
Auch bei ISSN 1556-3839 Criminal justice review der Fall. Ebenfalls Sage.
Das Problem ist auch einen Tag später noch nicht behoben. Denn bei dem heute (3. 12.) nachträglich gelieferten Artikel Examining Policy Preferences https://journals.sagepub.com/doi/full/10.1177/0734016820906601 fehlen sie auch.

**Comment by jriedl** [comment]
Das ist zum gegenwärtigen Zeitpunkt noch wirklich mysteriös, da ein Test auf nu und der Upload-Prozess auf nu den gleichen Translationserver und damit auch die gleichen Translators verwenden. Im Bezug auf den Upload fehlen sie aber schon auf unserer Seite. Gehe dem nach.

**Comment by jriedl** [comment]
Eine befriedigende Erklärung gibt es bislang nicht. Wie es aussieht, wurden wir am 1.12., als die Testeinspielungen erfolgt sind, aufgrund der hohen Anzahl der Anfragen an einer Stelle von SAGE geblockt (HTTP Code 403 - Forbidden), möglichweise aber erst beim Aufruf des RIS-Subtranslators unter einer neuen URL, so dass Rumpf-Informationen vorhanden bleiben. Die Keywords würden aber erst in der Handling-Funktion nach dem RIS-Aufruf gesetzt. Für randomisiertes Aussteigen sehen die Ergebnisse aber zu gut aus. Die ausgegebenen augmentierten Metadata-Records des Zotero-Harvester an diesem Abend haben jedenfalls alle schon keine Keywords mehr. Muss also noch weiter untersucht werden.

**Comment by kdr154** [comment]
In diesem Zusammenhang passt, dass die Performance seit einiger Zeit z. T. ausgesprochen schlecht ist, wenn man auf die Seiten von Sage zugreift. Vor einigen Tagen bin ich bei einem Test auf benu nach mehr als einer Stunde ausgestiegen- Auch gestern Abend dauerte ein Test auf nu bei einer der oben genannten Zeitschriften länger als eine Stunde.

**Comment by jriedl** [comment]
Da vorhin eingefallen und nach einem Kurztest plausibel - Nachtrag zu obigem Kommentar (erklärt wohl auch #1288, #1287): Durch Fehler im RIS-Subtranslator schlägt der gesamte SAGE-Translator fehl. Da der Translation-Server aber schlau genug ist, zu erkennen, dass in der URL eine DOI steht, erfolgt dann als Fallback eine Abfrage über den DOI-Translator.  Da offenbar nur die RIS-URL gesperrt wird, kann der DOI-Translator erfolgreich ausgeführt werden. DIeser liefert wohl keine Keywords und natürlich auch keine ORCIDs.

**Comment by kdr154** [comment]
auch ISSN 1945-1369 Journal of Drug Issues.
https://journals.sagepub.com/toc/joda/50/4

**Comment by jriedl** [comment]
Tritt das Problem noch auf?

**Comment by kdr154** [comment]
In den Daten auf dem Testserver von gestern waren die Keywords dabei.
