### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1284]
https://ojs.ehu.eus/index.php/eguzkilore/index
https://ojs.ehu.eus/index.php/eguzkilore/article/view/21829

Wenn die Sprache des Textes von der in diesem Fall Standardsprache Spanisch abweicht, wird kein 041 und damit auch keine Sprache benannt.
Der oben erwähnte Artikel:

![grafik](https://user-images.githubusercontent.com/29707105/100979002-7d86cf80-3543-11eb-91b8-03b25d46881a.png)

Sonst:

![grafik](https://user-images.githubusercontent.com/29707105/100979074-98f1da80-3543-11eb-8dd2-a045abb2dabf.png)

**Comment by jriedl** [comment]
Scheint mit den "zotero_expected_languages"  in der `zotero-harvester.conf ` zusammenzuhängen. Lokales Einfügen von "eng" führt zu vorhandem `041`-Feld => Nachtragen von `eng` in Zeder sollte das Problem lösen.

**Comment by kdr154** [comment]
Das Nachtragen in Zeder hat das Problem behoben.
