### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Harvesting

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1285]
https://ojs.ehu.eus/index.php/eguzkilore/issue/archive
Ein Suchlauf auf nu ergibt, dass alle Heft erfasst werden, der aktuelle Band aus dem Jahr 2020 aber mehrfach. Dabei aber auch nicht alle Artikel in gleicher Anzahl. 2020 sind sechs Artikel erschienen, es werden aber 28 Records erzeugt. Bei den Bänden der anderen Jahrgänge ist dies nicht der Fall. Bei diesen werden alle Artikel einmal erfasst.

Darüber hinaus geht der Harvester nicht Band für Band vor, sondern es geht wild durcheinander. Erst ein Artikel aus dem Jahr 2020, dann einer aus dem Jahr 2019, dann einer aus 2016, dann wieder 2020 usw.

**Comment by jriedl** [comment]
Auf nu: Es wird jetzt nur dich aktuelle Ausgabe von der Index-Seite geharvestet. Da es sich um ein Crawl-Verfahren handelt, sollten hier nicht alte Artikel immer wieder heruntergeladen werden.

**Comment by kdr154** [comment]
Jetzt werden aber alle Artikel des aktuellen Hefts zweimal erfasst.
Einen Unterschied kann ich im Datafield tag URL ausmachen 
Einmal so: 
```
</datafield>
<datafield tag="URL" ind1=" " ind2=" ">
<subfield code="a">
https://ojs.ehu.eus/index.php/eguzkilore/article/view/21828
```
Beim zweiten Eintrag sieht es so aus:
```
</datafield>
<datafield tag="URL" ind1=" " ind2=" ">
<subfield code="a">
https://ojs.ehu.eus/index.php/eguzkilore/article/view/21828/19648
```

**Comment by jriedl** [comment]
Danke für den Hinweis. Ist jetzt hoffentlich auf nu behoben.

**Comment by kdr154** [comment]
Ja, jetzt passt es
