### ISSUE TITLE
ISSN 2044-2696 | Theology | fehlender Titel (Test-DB)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1286]
**URL**
https://journals.sagepub.com/doi/full/10.1177/0040571X20970883l

**Ausführliche Problembeschreibung**
In der Test-DB fehlt der obige Artikel des aktuellen Heftes.

Beim Testen auf Nu mit TRY RSS wird er nicht aus der XML-Datei ausgeschlossen.

Er scheint von uns nicht geliefert worden zu sein, ich finde ihn nicht unter "delivered records" auf Nu.

Und noch etwas: Könnte die Sortierung für die "delivered records" in umgekehrter Reihenfolge nach Datum angezeigt werden, sodass die neuesten Records oben sind und man nicht runterscrollen muss?

**Comment by socheres** [comment]
@mtrojan-ub auch hier etwas merkwürdiges im Harvester.

**Comment by mtrojan-ub** [comment]
Mittlerweile taucht er auf: 8F8CFD71B9E83B78B9A7E4FBEFC3D6B5D7AF2C09

Ich könnte mir vorstellen, dass wir in diesem View ebenfalls eine DataTables-Tabelle verwenden, so wie auf der Startseite. Dann lässt sich die Sortierung per Click auf einen der Spaltenheader ändern. Die Default-Sortierung könnte ich dann auf Datum (absteigend) einstellen.

**Comment by mtrojan-ub** [comment]
Die Änderung mit der sortierten (DataTables-)Tabelle in der "Delivered Records"-Ansicht ist jetzt auf nu aktiv.

Übrigens: Auf der Startseite kommt man jetzt auch zur "Delivered Records" Ansicht, wenn man hinten auf den Status der Zeitschrift klickt (bisher ging das ja nur durch Klicken auf den Delivery Mode).

**Comment by IxKo** [comment]
Funktioniert
Ich schließe das Issue, weil die Problematik mit fehlenden Artikeln auch in diesem Issue #1292 aufgegriffen wird.
