### ISSUE TITLE
ISSN 2397-3498 | The Downside Review | orcid (Sage, Test-DB)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1287]
**URL**
https://doi.org/10.1177/0012580620972842
IxTheo#2020-12-01#E7B2F27FB30F597C633D489C4E570C44895FE3E6

**Ausführliche Problembeschreibung**
Hier wird die ORCID nicht in der Test-DB ausgegeben, obwohl beim Test auf Nu das entsprechende Marc-Feld erzeugt wird.
In unserer Quelldatei ist es aber nicht enthalten.

Bei anderen Artikeln von Sage-Zss, die am selben Tag eingespielt wurden, gibt es aber ORCID-IDs in Pica-8910

Off-Topic:
Der Artikel ist zudem ein OA-Artikel und es wäre wirklich gut, wenn man solche Titel abfangen könnte, damit sie nicht als lizenzpflichtig markiert werden.

**Comment by socheres** [comment]
@mtrojan-ub wenn der Test auf Nu ORCID ausgibt, wie kann das sein, dass die ORCID nicht in der Quelldatei enthalten ist?

**Comment by mtrojan-ub** [comment]
In der gelieferten `ixtheo_zotero_201201_001.xml` in Default_Test fehlt die ORCID, also hat sich seit dem 1.12. wahrscheinlich etwas auf nu geändert.

Am 3.12. gab eine Änderung am SAGE Translator zur ORCID-Erkennung:
https://github.com/ubtue/zotero-translators/commit/ba52c9abd935633421d11334cd867a5cad9efb10#diff-bbdffa989342ed87865e8fae40809f69ce83c401540dcdd88cf4e7596583f650

Also handelt es sich vermutlich entweder um diese Anpassung, oder um eine frühere Anpassung die aber erst nach dem 1.12. auf nu eingespielt wurde.

**Comment by socheres** [comment]
> In der gelieferten `ixtheo_zotero_201201_001.xml` in Default_Test fehlt die ORCID, also hat sich seit dem 1.12. wahrscheinlich etwas auf nu geändert.
> 
> Am 3.12. gab eine Änderung am SAGE Translator zur ORCID-Erkennung:
> [ubtue/zotero-translators@ba52c9a#diff-bbdffa989342ed87865e8fae40809f69ce83c401540dcdd88cf4e7596583f650](https://github.com/ubtue/zotero-translators/commit/ba52c9abd935633421d11334cd867a5cad9efb10#diff-bbdffa989342ed87865e8fae40809f69ce83c401540dcdd88cf4e7596583f650)
> 
Die Änderung zu Orcid auf Nu war schon am 18.Nov. aktiv.
https://github.com/ubtue/zotero-translators/commit/bb4c6c2e3b755786ef3cb320c97885c7cfdc0d47#diff-bbdffa989342ed87865e8fae40809f69ce83c401540dcdd88cf4e7596583f650

> Also handelt es sich vermutlich entweder um diese Anpassung, oder um eine frühere Anpassung die aber erst nach dem 1.12. auf nu eingespielt wurde.

aufgrund mehrerer gleichzeitiger Abfragen der Links - zuviele Zss. auf einmal auf "zota" gesetzt- , die erst durch den Aufruf von RIS-Subtranslator aufgebaut wird `&include=abs&format=ris&direct=false&submit=Download+Citation,` wurde der SAGE-Translator abgebrochen. In diesem Fall kam dann als zweiter Kandidat der DOI-Translator in Einsatz, weshalb die ORCID usw. fehlen. IT arbeitet zurzeit an einer Lösung.

**Comment by IxKo** [comment]
Neu eingespielte Daten in der Test-DB werden zeigen, ob das Probleme oder ähnliche wieder auftreten.

**Comment by IxKo** [comment]
Orcid nun vorhanden, allerdings 3x siehe dazu auch #1326
