### ISSUE TITLE
ISSN 2397-3498 | The Downside Review | Keywords (Test-DB)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1288]
**URL**
https://journals.sagepub.com/doi/10.1177/0012580620973487
IxTheo#2020-12-01#03A444FDBC31679E05E18F374CDDB147CA316D01

**Ausführliche Problembeschreibung**
Die Keywords fehlen in der Test-DB, sind aber beim Testen auf Nu mit TRY URL vorhanden.
Fehlen jedoch in der Quelldatei ixtheo_zotero_201201_001.xml

Auf Nu: (650)
![image](https://user-images.githubusercontent.com/57000004/101182226-199cfd80-364e-11eb-97a3-7cd2f572adf4.png)

In Test-DB: (5520 |s|)
![image](https://user-images.githubusercontent.com/57000004/101182328-36d1cc00-364e-11eb-83f9-05ca753d374f.png)

**Comment by socheres** [comment]
Kann das Issue geschlossen werden? @IxKo

**Comment by IxKo** [comment]
Es wurde nicht auf Ready for Testing gesetzt. Problem besteht mittlerweile nicht mehr.
