### ISSUE TITLE
ISSN 2158-1681 | Hebrew Studies | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1289]
https://muse.jhu.edu/issue/43337
Der Muse-Translator liefert hier Webseiten statt Aufsätze oder bringt die Fehlermeldung: Es ist ein Problem aufgetreten beim Versuch, diesen Eintrag zu speichern.

**Comment by IxKo** [comment]
Gleiches bei ISSN 1945-9718 | Franciscan studies

**Comment by kdr154** [comment]
Jetzt werden Aufsätze erfasst.
