### ISSUE TITLE
ISSN 2631-8334 | Pro Ecclesia | Rezensionen, Keywords und Orcid (Sage live!)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1290]
**URL**
Die Harvest URL

**Ausführliche Problembeschreibung**
Es wurden alle Artikel des neuen Heftes (2020,4) eingespielt, allerdings wurde ein Artikel erst einen Tag später eingespielt.

Die 3 Rezensionen des Heftes werden nicht als solche in 1131 erkannt.
Keywords werden nicht ausgegeben.
ORCID-IDs werden nicht ins Zusatzfeld geschrieben.

Beim Testen auf Nu mit TRY RSS gibt es diese Probleme jedoch nicht.

**Comment by IxKo** [comment]
Bei einem Artikel der Einspielung sind die Keywords jedoch da gewesen: 
IxTheo#2020-12-04#DFF75D2277462BC91484EC7BD28207823AC2497D

**Comment by socheres** [comment]
@jriedl werden nach pull request merge Translators von ub28 auch sofort aktualisiert? Auf Nu sehen die Daten alle gut aus (Keywords, Orcid, Rezensionen).

**Comment by jriedl** [comment]
Nein, nur nach Absprache. Hatte esauf nu aktualisiert, damit man testen kann.

**Comment by socheres** [comment]
hierzu gibt es bereits eine plausible Erklärung, warum der SAGE Translator abbricht:https://github.com/ubtue/DatenProbleme/issues/1283#issuecomment-738072095
