### ISSUE TITLE
ISSN 1556-3537 | Anthropology of consciousness | Anreicherung mit Abrufzeichen zota

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1293]
Die Anreicherung von Altdaten mit dem Abrufzeichen zota im Zusammenhang mit dem vollautomatischen Verfahren findet weiterhin statt. Ich dachte das wäre abgestellt.
Am 7.12. sind drei bereits zuvor erfasste Sätze der Zeitschrift "Anthropology of consciousness" mit dem Abrufzeichen zota versehen worden.
PPN 1692972952, 1692972944, 1692972936

**Comment by IxTheoKm** [comment]
Ist das ein Problem bei uns, oder muss das BSZ benachrichtigt werden?

**Comment by kdr154** [comment]
Keine Ahnung wie die Daten hineingekommen sind.  Prodf steht bei dieser ZS seit 35 Tagen auf halbautomatisch (zotk) und prode seit 48 Tagen  auf Test für das vollautomatische Verfahren (zotat)

**Comment by IxTheoKm** [comment]
@socheres Können Sie das erklären?

**Comment by socheres** [comment]
die Aktualisierung des Änderungsdatums am 07.12.20 muss nicht zwingend wegen "zota" stattgefunden haben. Viel wahrscheinlicher ist die Änderung auf DA3-Sacherschließung zurückzuführen. Im Datensatz der Testadatenbank (cbst7) ist "zota" auch enthalten.

**Comment by kdr154** [comment]
Die Änderung hat aber am Lok-Satz stattgefunden:
7903 07-12-20 08:58:06.000

**Comment by socheres** [comment]
IxTheo-Notationen sind auch im Lokalsatz und am 07.12 bzw. 06.12 wurde der betreffende Datensatz auch nicht hochgeladen.

**Comment by kdr154** [comment]
aber verändert

**Comment by kdr154** [comment]
Konnte geklärt werden, Das Änderungsdatum bezieht sich auf die Anreicherung mit IxTheo-Notationen, das zota wurde bereits bei der irrtümlichen Einspielung vom 19.3. gesetzt
