### ISSUE TITLE
ISSN 1874-9275 | Erasmus studies | Abbreviations

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1297]
https://brill.com/view/journals/eras/40/2/eras.40.issue-2.xml
https://brill.com/view/journals/eras/40/2/article-p95_2.xml

Sollen Abbreviations global ausgeschlossen werden, oder soll das in der harvester.conf auf der Ebene derZeitschrift gelöst werden?

**Comment by socheres** [comment]
Abbreviations zum Nachschlagen finde ich sehr hilfreich: z.B. http://dx.doi.org/10.1515/kierke-2015-0120 Solche Abbreviations-Titeln sind bereits im Bestand vorhanden `f sfk 1 tit Abbreviations* bbg (os*|as*)` Bitte um euer Votum @thefass @Gazeller

**Comment by thefass** [comment]
Über die Datenlieferungen sind die Abbrviations mitgekommen. Sie sind tatsächlich hilfreich und sollten erfasst werden

**Comment by IxKo** [comment]
Lieber @kdr154 ,
dann muss in der Conf etwas angepasst werden bei: Currents in biblical research (zeder_id = 295)
exclude_if_marc_field_245a = (?i)^((\s?Editorial\s?)|(\s?**Abbreviation**\s+List\s?))

**Comment by IxKo** [comment]
Da diese Abkürzungsverzeichnisse idR keine:n Verfasser:in haben, landen sie in den Error-Dateien und müssen manuell nachkatalogisiert werden.

Ist es eventuell möglich hier eine White List zu erstellen, die Titel enthält, welche auch bei fehlender Verfasserangabe eingespielt werden?

**Comment by IxKo** [comment]
Der Sachverhalt wurde im Zuge dieser beiden Issues geklärt: https://github.com/ubtue/DatenProbleme/issues/1578 und https://github.com/ubtue/DatenProbleme/issues/1612
