### ISSUE TITLE
Globale QA-Settings

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1298]
Hier werden globale QA-Settings vorgeschlagen und diskutiert.
Erste Eintragungen erfolgen am Montag, 14.12. (@kdr154)

**Comment by kdr154** [comment]
024: nur $a und $2,
       $u gibt es in der Doku nicht
       $z haben wir in den Datensätzen noch nie gesehen. 

040: hier stimmt alles

041: hier stimmt alles

084: die SSG-Nummer, die muss auf always stehen, nicht auf sometimes
        $a always
        $2 always
100: hier gehört $4 auf always und nicht auf sometimes
        $0 sometimes
        $4 always
        $a always
        $b sometimes
        $c sometimes
        $e always

245: hier stimmt alles

264: hier stimmt alles

362: sollte entfernt werden. In diesem Feld wird der Erscheinungsverlauf erfasst. Ein solcher existiert bei Aufsätzen nicht.

520: hier stimmt alles

648: muss entfernt werden, hier sollten Zeitschlagwörter erfasst werden. Solche erfassen wir nicht.

650: hier stimmt alles

651: muss entfernt werden, hier sollten Geografika erfasst werden. Solche erfassen wir in dieser Form nicht. Diese erfassen wir, wenn, dann in 650.

655: hier fehlt das 2. $0. 
       muss ebenfaslls auf "always" stehen

700: alle Subfields müssen auf "sometimes" stehen. 
       wenn sie wie jetzt $a und $e auf "always" stehen, würde immer ein weiterer Verfasser erwartet werden.

773: Hier müssen alles Subfields im Gegensatz zu jetzt auf "always" gesetzt werden 

852: Hier stimmt alles

856: $u sollte auf "always" gesetzt werden
        $z stimmt,
        denn eine URL sollte bei Online-Ausgaben immer vorhanden sein.
        Sollte einmal eine Druckausgabe erfasst werden, muss das bei den Journal Settings geändert werden

887: hier stimmt alles

935: hier stimmt alles

936: stellen wir zur Diskussion. Man könnte sich vorstellen, alle Subfields auf "always" zu setzen und dort, wo es Abweichungen gibt, dies über die Journal Settings zu lösen. 
    
       $d always
       $e always
       $h always 
       $j always

Man kann sich aber auch vorstellen, dass man lediglich das Jahr, also $j als verplichtend vorgibt, und alle anderen Felder als optional. Also so, wie es jetzt angegeben ist.

Der Rest ist für die IT.

Anmerkungen:

Problematisch sind die Zeitschriften, die selektiv erfasst werden sollen. Bei denen dürfen 084 $a und $2 zunächst einmal nicht vorhanden sein. Das wird aber über Zeder und die harverster.conf gesteuert. Und auch 935 $a darf zunächst nicht gesetzt sein. Dies wird aber bei den maschinellen Einspielungen automatisch gesetzt. Dies ist doppelt problematisch, weil 935 zweimal benutzt wird. Einmal für Pica 0575 mteo, und einmal für die Abrufzeichen im Lokalsatz. Diese sollten aber immer vorhanden sein.

Bei 041 könnte man über Regex definieren, dass der Code immer aus drei Buchstaben bestehen muss: ^[a-z]{3}$

Bei 264, dass Jahr, könnte man definieren, dass es aus 4 Ziffern bestehen muss : ^[1,2][0-9]{3}$

Bei der Qualitätssicherung könnte man sich Routinen überlegen, die die Übernahme von römischen Zahlen bei Heft und Band (I-XX usw.) ausschließt und diese in arabischen Zahlen umwandelt. Ebenso sollte ein Band- oder Heftangabe "0" oder Ähnliches ausgeschlossen werden. So dass man sicher gehen kann, dass es sich um einen sinnvollen Wert handelt.

**Comment by mtrojan-ub** [comment]
Îch habe soeben die Werte auf nu angepasst (auch die vorgeschlagenen Regex eingetragen), und auch den Durchlauf ab heute Abend wieder aktiviert.

Anmerkungen: 
- Zu 655: Dass ein Feld doppelt vorkommen muss, kann man über die Oberfläche nicht einstellen. Für 655 findet aber eine zusätzliche Prüfung statt, die sowohl das Vorkommen als auch den Inhalt der beiden 0-Felder prüft (siehe Wiki.)
- 856z habe ich so interpretiert, dass es auf "always" gesetzt werden soll (in der Beschreibung stand "stimmt", aber es war bisher sometimes, entgegen der restlichen Beschreibung).

Falls es noch Änderungswünsche gibt, einfach kurz bescheid geben!

**Comment by kdr154** [comment]
Lieber Herr Trojan,

856 $z sollte so bleiben, wie es war, auf "sometimes". Hier kommt ggf. die Angabe rein, ob ein Aufsatz lizenzfrei ist.

Viele Grüße
Klaus-Dieter Rosenkranz

_________________________

Klaus-Dieter Rosenkranz
Eberhard Karls Universität Tübingen
Telefon: Universitätsbibliothek +49 7071 29 72963
Mobil: 0173 3194973

E-Mail: rosenkranz@uni-tuebingen.de


Von: Mario Trojan <notifications@github.com>
Gesendet: Montag, 14. Dezember 2020 15:09
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: Rosenkranz, Klaus-Dieter <klaus-dieter.rosenkranz@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Globale QA-Settings (#1298)


Îch habe soeben die Werte auf nu angepasst (auch die vorgeschlagenen Regex eingetragen), und auch den Durchlauf ab heute Abend wieder aktiviert.

Anmerkungen:

  *   Zu 655: Dass ein Feld doppelt vorkommen muss, kann man über die Oberfläche nicht einstellen. Für 655 findet aber eine zusätzliche Prüfung statt, die sowohl das Vorkommen als auch den Inhalt der beiden 0-Felder prüft (siehe Wiki.)
  *   856z habe ich so interpretiert, dass es auf "always" gesetzt werden soll (in der Beschreibung stand "stimmt", aber es war bisher sometimes, entgegen der restlichen Beschreibung).

Falls es noch Änderungswünsche gibt, einfach kurz bescheid geben!

**Comment by mtrojan-ub** [comment]
Lieber Herr Rosenkranz,

alles klar, 856z wurde jetzt wieder auf sometimes gestellt.

Viele Grüße
Mario Trojan

**Comment by mtrojan-ub** [comment]
Gestern Abend ist ja der Harvester auf nu wieder gelaufen. Es wurden sowohl reguläre Dateien als auch Errors-Dateien erzeugt. Gibt es aus Eurer/Ihrer Sicht noch Auffälligkeiten?

Falls mit dem neuen Mechanismus alles passt, würde ich ihn gerne heute Nachmittag auch auf ub28 in Betrieb nehmen und die Regeln von nu übertragen.

**Comment by IxKo** [comment]
Eine Brill-Zs stand wohl noch auf Crawl. Ich habe nun einen RSS-Link in Zeder eingefügt. Könnten die Daten hier nochmal gelöscht werden? Alle wurden nicht eingespielt und stehen auf gelb. ISSN 1877-5233 (Annual review of the sociology of religion)

**Comment by IxKo** [comment]
Kann eigentlich auch eine Prüfung eingeführt werden, ob alle Artikel eines Heftes geharvestet werden oder nicht?
Beispielsweise wurden bei der Brill-Zs Annuarium historiae conciliorum (2589-0433) nur 2 Artikel geharvestet, die wohl aufgrund der fehlenden Sprachzuordnung auch nicht eingespielt wurden. Insgesamt hat das Heft aber 14 Artikel.

**Comment by kdr154** [comment]
Meine Beobachtungen zu den Aufsätzen aus dem Bereich der KrimDok:
1. Es landen wenig Aufsätze in den Error-Files. Diese stehen aber in Übereinstimmung mit den QA-Settings.
Zwei davon sind die beiden Aufsätze vom "Bergen journal of criminal law & criminal justice". Beide, weil sie kein 041 Sprache haben.
Ein Testlauf auf nu zeigt auch, dass kein 041 enthalten ist. Überträgt man die Aufsätze halbautomatisch nach Zotero, ist die Sprache enthalten. Allerdings in der Form "en-US". Wahrscheinlich ein Translator-Problem.

2. Die bereits bekannte Problematik der fehlenden Keywords bei Sage. Allerdings ist es so, und dies deckt sich mit meinen Beobachtungen aus den früheren Einspielungen, dass nicht alle Zeitschriften davon betroffen sind. Z. B.sind bei ISSN 1478-1603 "International journal of police science & management" sowohl die Keywords als auch die Orcid-ID enthalten.

3. Bei der Zeitschrift "Terrorism and Political Violence" werden vom aktuellen Heft nur die Rezensionen eingespielt, die regulären Artikel fehlen.

**Comment by mtrojan-ub** [comment]
> Eine Brill-Zs stand wohl noch auf Crawl. Ich habe nun einen RSS-Link in Zeder eingefügt. Könnten die Daten hier nochmal gelöscht werden? Alle wurden nicht eingespielt und stehen auf gelb. ISSN 1877-5233 (Annual review of the sociology of religion)

ist gelöscht

**Comment by mtrojan-ub** [comment]
> Kann eigentlich auch eine Prüfung eingeführt werden, ob alle Artikel eines Heftes geharvestet werden oder nicht?
> Beispielsweise wurden bei der Brill-Zs Annuarium historiae conciliorum (2589-0433) nur 2 Artikel geharvestet, die wohl aufgrund der fehlenden Sprachzuordnung auch nicht eingespielt wurden. Insgesamt hat das Heft aber 14 Artikel.

Dann sollten doch eigentlich die restlichen sowieso als Error in der Oberfläche auftauchen, oder? Falls nicht könnte das ein Bug sein, das sollten wir aber in einem separaten Issue weiter verfolgen.

**Comment by kdr154** [comment]
Nicht nur die, auch 1877-5233 Annual review of the sociology of religion
Dabei stelle ich fest, dass Marc 362 offensichtlich beim Crawlen erzeugt wird. Dieses Feld haben wir aus den QA-Settings entfernen lassen (s. o.). 
Die Frage die sich mir stellt. Wird die Jahresangabe Pica 1100 u. U. aus diesem Feld generiert, sofern kein Marc 264 erzeugt werden kann?
Wenn nicht, kann man es aus dem Prozess des Crawlens herausnehmen. Es ist nur in den Error-Files vorhanden und nicht unter den Sätzen, die eingespielt wurden.
Möglicherweise ist das Fehlen einer Regel für Marc 362 mit verantwortlich, dass ein Satz nicht eingespielt wird. Das Fehlen dieser Regel ist aber nie allein der Grund, warum ein Satz nicht eingespielt wird. 
Siehe z. B.:

Record IxTheo#2020-12-15#EEBAD9D0547752B84DA8268FA6401FFF81C14958 is invalid:
773: required subfield g is missing
936: required subfield d is missing; required subfield e is missing; required subfield h is missing
required 100-field is missing
no rule for present field 362 was found

**Comment by IxKo** [comment]
Ja, sobald ein Feld mitgeliefert wird, was nicht in den QA-Settings aufgelistet ist, landet es in der Error-Datei.
Aber die Harvest-Methode bei dieser Zs wird auf RSS gestellt. Es war kein RSS-Link in Zeder hinterlegt gewesen, weshalb es wohl dann auf Crawl stand. Morgen sollte es also ganz anders aussehen - hoffe ich.

**Comment by kdr154** [comment]
Dann schlage ich vor, wir warten mit der Übertragung auf ub28 und Recherchieren noch ein bisschen weiter nach möglichen Unstimmigkeiten.

**Comment by mtrojan-ub** [comment]
In 362a wird das Datum eingetragen, aber nur, wenn der Datensatz weder vom Typ journalArticle noch vom Typ review ist.

**Comment by kdr154** [comment]
Was ist das dann?

**Comment by mtrojan-ub** [comment]
Hier die Liste der insgesamt verfügbaren itemTypes in Zotero:

[
	"artwork",
	"attachment",
	"audioRecording",
	"bill",
	"blogPost",
	"book",
	"bookSection",
	"case",
	"computerProgram",
	"conferencePaper",
	"dictionaryEntry",
	"document",
	"email",
	"encyclopediaArticle",
	"film",
	"forumPost",
	"hearing",
	"instantMessage",
	"interview",
	"journalArticle",
	"letter",
	"magazineArticle",
	"manuscript",
	"map",
	"newspaperArticle",
	"note",
	"patent",
	"podcast",
	"presentation",
	"radioBroadcast",
	"report",
	"statute",
	"thesis",
	"tvBroadcast",
	"videoRecording",
	"webpage"
]

**Comment by kdr154** [comment]
ja, aber von denen kommt  für uns doch nur der JournalArticle in Frage. Und der selbst erzeugte review.
Einer der Artikel, bei denen das Fehlen einer Regel für Tags 362 erwähnt wird ist z. B. dieser:
https://secularismandnonreligion.org/article/10.5334/snr.134/
Der wird in Zotero als Zeitschriftenartikel gespeichert.

**Comment by mtrojan-ub** [comment]
OK, also ich weise darauf hin dass wir auch Speziallogik für magazineArticle haben, und in der Anfangszeit kann ich mich noch erinnern dass auch vereinzelt der Typ book aufgetaucht ist. Aber damals waren auch @socheres, @ruschein und @shadeMe die Hauptakteure im Projekt, von daher kann ich nicht beurteilen welche itemTypes sonst noch relevant sind.

**Comment by mtrojan-ub** [comment]
> Dann schlage ich vor, wir warten mit der Übertragung auf ub28 und Recherchieren noch ein bisschen weiter nach möglichen Unstimmigkeiten.

Falls die Änderungen nicht spätestens morgen auf ub28 eingespielt werden können, wird das aufgrund der Urlaubszeit erst im neuen Jahr möglich sein.

**Comment by kdr154** [comment]
Das ist in meinen Augen kein Fehler.

**Comment by socheres** [comment]
magazineArticle kann entfallen. Bleibt für uns nur journalArticle relevant.

**Comment by mtrojan-ub** [comment]
Heißt das, es können alle Datensätze hart übersprungen werden, die Zotero nicht als journalArticle liefert? (also dass in anderen Fällen die Translators so angepasst werden müssen, dass sie journalArticle zurückgeben?)

**Comment by kdr154** [comment]
Das war eine Überlegung, die ich ebenfalls angestellt habe. Z. B. das Interview, das immer mal wieder vorkommt, kenne ich glaube ich nur als Journalartikel. Der Dokumenttyp Interview hat ja z. T. ganz andere Felder in Zotero. Was allerdings vorkommt, ist, dass machmal der Typ "Buch" erzeugt wird, auch wenn es sich tatsächlich um einen Journalartikel handelt. Der Dokumenttyp "Webseite" wird auch gelegentlich erstellt.
Leider nein, ich denke, wir sollten es bei einem manullen Verfahren belassen. Das escheint mir sicherer.

**Comment by IxKo** [comment]
@mtrojan-ub 
Bitte für **Feld 936 Subfield e** (betrifft die Heft-Zählung) eine RegEx-Regel erstellen, dass hier nur arabische Ziffern oder arabische Ziffern getrennt mit einem Schrägstrich möglich sind, denn etwas anderes ist laut Dokumentation nicht erlaubt.
Bspw. so: **(\d)|(\d\/\d)**
Ich bin mir nicht sicher ob der Ausdruck \/ nun den Schrägstrich erlaubt. Im RegEx-Tester wurde mir der Schrägstrich nicht grün markiert, aber rechts steht: \/ matches the character / literally (case sensitive)

**Comment by IxKo** [comment]
Und das für die 100a/700a auch umsetzen, wenn es korrekt ist: https://github.com/ubtue/DatenProbleme/issues/1412#issuecomment-804022927

**Comment by mtrojan-ub** [comment]
Das mit dem `\/` gilt nur innerhalb der Oberfläche von regex101.com, weil dort `/` als Sonderzeichen eine spezielle Bedeutung hat (wusste ich bisher auch noch nicht).

`\d` matcht nur für Zahlen, wenn also auch arabische Klein- und Großbuchstaben matchen sollen, dann wäre das eher `[0-9a-zA-Z]`. 

Dementsprechend habe ich jetzt mal testweise auf nu für 936e folgenden Regex hinterlegt: `^[0-9a-zA-Z](/[0-9a-zA-Z])*$`

**Comment by IxKo** [comment]
> Das mit dem `\/` gilt nur innerhalb der Oberfläche von regex101.com, weil dort `/` als Sonderzeichen eine spezielle Bedeutung hat (wusste ich bisher auch noch nicht).
> 
> `\d` matcht nur für Zahlen, wenn also auch arabische Klein- und Großbuchstaben matchen sollen, dann wäre das eher `[0-9a-zA-Z]`.
> 
> Dementsprechend habe ich jetzt mal testweise auf nu für 936e folgenden Regex hinterlegt: `^[0-9a-zA-Z](/[0-9a-zA-Z])*$`


Es sollen auch nur Zahlen erlaubt sein. In dem Feld darf laut Dokumentation nichts anderes stehen als Zahlen und zwei Zahlen getrennt mit Schrägstrich. Daher bewirkt \d die korrekte Eingrenzung.

**Comment by mtrojan-ub** [comment]
OK, dann habe ich es falsch verstanden... es ist jetzt auf nu geändert, der neue Regex lautet wie folgt: `^\d+(/\d+)?$`

**Comment by IxKo** [comment]
Vielen Dank! Die Pluszeichen scheinen mir aber überflüssig zu sein?

**Comment by mtrojan-ub** [comment]
Ohne die Pluszeichen wären zwar z.B. `5` oder `5/6` gültig, aber nicht `10` oder `10/11`; ich hatte es so verstanden dass das erlaubt sein soll.

**Comment by IxKo** [comment]
Ja, das ist korrekt!
War mein Fehler, dass ich dachte, dass \d auch für bspw. zweistellige Ziffern gelten würde.
Vielen Dank!

**Comment by mtrojan-ub** [comment]
OK, dann passt es ja jetzt! Bitte nicht vergessen, das ist jetzt erstmal auf nu eingerichtet. Sobald sicher ist dass es gut funktioniert, müssen wir es noch auf ub28 übernehmen.
