### ISSUE TITLE
ISSN 1890-7008 | Nordic journal of religion and society | Keywords und Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1299]
https://www.idunn.no/nordic_journal_of_religion_and_society/2020/02/who_is_baptized_a_study_of_socioeconomic_regional_and_gen

Die Keywords und das Abstract werden nicht mit an Zotero geliefert. 
Abstract mal ja, mal nein.
Hier ja: https://www.idunn.no/nordic_journal_of_religion_and_society/2020/02/religion_as_the_other_source_of_the_modern_western_world
Hier nein: https://www.idunn.no/nordic_journal_of_religion_and_society/2020/02/who_is_baptized_a_study_of_socioeconomic_regional_and_gen
Hier wird auch ein Abstract übertragen, obwohl es auf der Seite nicht als solches gekennzeichnet wird:
https://www.idunn.no/nordic_journal_of_religion_and_society/2020/02/astrid_krabbe_trolle_the_sociology_of_morals_catholic_pra
Im Quelltext findet sich der Text jeweils im Tag "description"
Wird  mir hier der richtige Translator angeboten? Habe Embedded Metadata und Doi zur Auswahl.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe einen neuen Translator erstellt, der funktioniert. Das Abstract steht leider nicht immer in description, deshalb habe ich für die anderen Fälle noch eine Ausnahme hinzugefügt.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Die Rezensionen werden nicht erkannt und getagt.
Bei den Rezensionen wird, es ist glaube ich immer der erste Absatz, ein Teil der Rezension zum Abstract. Die Rezensionen haben aber kein Abstract.
Als Sprache wird immer no-No ausgegeben. Die Sprache der Artikel ist aber durchgehend Englisch.
Die Heftnummer wird immer zweistellig erfasst (02). Besser wäre nur eine Stelle: "2".

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
die Rezensionen werden jetzt erkannt und es kommen keine Abstracts mit, allerdings nur(!) beim Multi-DL, da die Information, dass es Rezensionen sind, nur auf der Ausgabenseite vorhanden ist.

Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
die Sprache und Ausgabebezeichnung habe ich auch angepasst.

**Comment by kdr154** [comment]
Bei mir ist leider weiterhin alles so wie kritisiert (Sprache, Abstract, Ausgabe)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
Sie können immer erst testen, wenn socheres auf "ready for testing" gesetzt hat.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Dafür sieht es jetzt gut aus.
