### ISSUE TITLE
Ingenta 2057-4525 Contributors 773g und 936h

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#130]
Irritierende Seitenangaben in diesen Felder:
```
<subfield code="g">4(2018), 2, S. 7VII-7VII</subfield>
<subfield code="h">7VII-7VII</subfield>
```
Nicht der Fall in den regulären Artikeln. 
Stellt sich die Frage, ob man nicht bestimmte Datensätze, wie etwa hier die "Contributors", von der Erfassung auszuschließen sollte, sofern dies möglich ist.

**Comment by shadeMe** [comment]
Wir haben jetzt die Möglichkeit, Datensätze auszuschließen, wenn sie bestimmten Kriterien erfüllen. In diesem Fall ist das Kriterium, dass entweder "acknowledge" oder "contributors" im Titel steht.

**Comment by kdr154** [comment]
Das scheint mir Sinn zu machen.  Allerdings sollte man vorsichtig sein. "Contributors" kann auch im Titel eines Aufsatzes stehen, der aufgenommen werden sollte. D. h. man sollte es auf die Fälle beschränken, in denen der Titel ausschließlich in dem Wort "contributors" besteht. Ebenso in anderen Fällen. Im Fall dieser ZS heißt es "Acknowledgements". denkbar wäre auch "Acknowledgement". Darüber hinaus fällt mir hier der "Index" auf, der auch wegfallen könnte. 
Auf jeden Fall eine gute Idee und ich denke man sollte die Begriffe und Phrasen sammeln, die in Frage kommen, bevor wir eine endgültige Entscheidung treffen.

**Comment by shadeMe** [comment]
Gute Punkte. Ich habe dementsprechend den Filter angepasst. Allgemein zum Thema - Die Filter-Funktion ist auf der Zeitschriften-Ebene implementiert. Das heißt, die Filter können für jede Zeitschrift angepasst werden. Insoweit können wir sie häppchenweise einsetzen.

**Comment by shadeMe** [comment]
@kdr154 Dieses Problem wurde schon behoben, glaube ich. Könnten Sie es bitte nochmal testen?

**Comment by kdr154** [comment]
Sieht gut aus!
