### ISSUE TITLE
ISSN 2589-0433 | Annuarium historiae conciliorum | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1300]
Ich frage mich, ob es im Augenblick Sinn macht, Issues zur Sprache aufzumachen, und wenn ja, wann.
Folgender Fall:
Dieser Artikel: https://brill.com/view/journals/ahc/49/1/article-p197_10.xml
ist doch offensichtlich auf Italienisch verfasst.
Es wird aber kein 041 ausgegeben:

![grafik](https://user-images.githubusercontent.com/29707105/102237551-1418a080-3ef5-11eb-8965-bfb7a4e3b788.png)

Das CLI Protokoll liefert als Begründung, die Differenz der beiden höchsten ngram-Werte sei zu gering:

use online ISSN "2589-0433" with online PPN "1007306068"
Normalized language: de => ger
generated too few ngrams (211 < 400)!
eng scored :0.656400
fre scored :0.695107
ger scored :0.689266
ita scored :0.685462
The top language's score is very close to the second language's score, so the language code will be left empty! (fre: 0.695107, ger: 0.689266)
post-processed author first name = 'Matthias', last name = 'Bürgel', title = '', affix = ''
Augmented metadata record: MetadataRecord {
	url: https://brill.com/view/journals/ahc/49/1/article-p197_10.xml,
	item_type: journalArticle,
	title: Riflessi del IV Concilio Lateranense nel Tesaur di Peire de Corbian,

Folglich würde dieser Artikel im Error-Container landen, weil die Sprache ein Pflichtfeld ist.
Betrachtet man aber die Werte, so hat Französisch den höchsten Wert und Deutsch den zweithöchsten.
Die eigentliche und korrekte Sprache wird gar nicht in Betracht gezogen. Wenn also eine Sprache ausgegeben worden wäre, wäre sie nicht richtig gewesen.

Im Grunde genommen ist es das Beste, dass solche Artikel manuell nachbearbeitet werden müssen.

**Comment by IxKo** [comment]
Ja, das ist eine gute Frage. Scheinbar sind auch viele Artikel aufgrund der Nicht-Zuweisung einer Sprache nicht in die Test-DB eingespielt worden.

**Comment by socheres** [comment]
Hier ist die Sprache sowohl in Zotero `"language": "de"` als auch das nGram-Ergebnis falsch. Unabhängig von diesem Fall grundsätzliche Frage an @ruschein @mtrojan-ub:
> The top language's score is very close to the second language's score, so the language code will be left empty! (fre: 0.695107, ger: 0.689266)

in diesem Fall ist der Differenzwert 0.005841. Wie habt Ihr den Schwellenwert definiert? Ab wieviel bleibt language code dann leer?

**Comment by mtrojan-ub** [comment]
Die ursprüngliche Anforderung war zwei Nachkommastellen. Da das aber auch bei Werten wie 0.6899999 und 0.69 keinen Fehler gemeldet hätte, haben wir stattdessen einen Mindestabstand von 0.01 hinterlegt.

**Comment by socheres** [comment]
Mindestabstand 0.01 produziert zu viele unnötige Fehler. Die neu implementierte Einstellung mit dem Scorewert stellen wir vorerst zurück. Bitte heute noch deaktivieren.

**Comment by socheres** [comment]
0.001 würde die ursprüngliche Anforderung entsprechen.

**Comment by socheres** [comment]
Mein Gedankenfehler. Das stimmt nur in diesem Fall.

**Comment by mtrojan-ub** [comment]
0.09 würde aber beim oben genannten Fall 0.695107 und 0.689266 trotzdem noch zu einem Fehler führen (Differenzwert 0.005841).

**Comment by socheres** [comment]
Ja, das stimmt. Aufgrund der variablen erst- und zweithöchsten Scorewerte kann der Mindestabstand mathematisch nicht fest definiert werden, daher müsste man nicht den Mindestabstand, sondern die Übereinstimmung (= false|true) der Werte nach zwei Nachkommastellen als Kriterium nehmen.
Z.B.
(fre: 0.695107, ger: 0.689266) => Ausgabe "fre"
(fre: 0.695107, ger: 0.699266) 0> Ausgabe "error"

**Comment by mtrojan-ub** [comment]
Dann würde aber 0.6899999 und 0.6900000 keinen Fehler erzeugen obwohl die nur minimalst voneinander entfernt sind?

**Comment by mtrojan-ub** [comment]
Wie besprochen:
- Logik bezüglich Minimalabstand zur 2. erkannten Sprache wird wieder entfernt
- In diesem konkreten Fall soll trotzdem ein Fehler erzeugt werden, da die Sprache laut Zotero Deutsch ist, aber Französisch automatisch erkannt wurde.

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt auf nu aktiv.

**Comment by kdr154** [comment]
Wird auch so ausgegeben:

![grafik](https://user-images.githubusercontent.com/29707105/106011273-99799e00-60ba-11eb-8d74-6dfac8ca9183.png)
