### ISSUE TITLE
0040-5701 | Theologische Zeitschrift (Basel, E-Periodica) | New Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1302]
**URL**
https://www.e-periodica.ch/digbib/volumes?UID=thz-001

**Ausführliche Problembeschreibung**
Es werden RIS-Daten angeboten. Bei diesen fehlen die End-Seitenangaben.
Zudem sind im RIS-Format die Abstracts nicht enthalten.

**Comment by socheres** [comment]
- [ ] missing end page
- [ ] scrape URL

**Comment by kdr154** [comment]
Sieht schon recht gut aus. Leider kann man nicht einzelne Artikel auswählen. Macht man das, werden immer alle übertragen. Und zwar mehrfach.
Neben der Endseitenzahl und der URL fehlt auch die Sprache

**Comment by socheres** [comment]
Einzeldownload möglich. Endseitenzahl und Sprache weder im RIS noch im HTML-Quelltext enthalten.

**Comment by socheres** [comment]
Translator bricht bei Aufsätzen ohne RIS-Eintrag ab. z.B. "Titelseiten", "Vorwort".

**Comment by IxKo** [comment]
Okay, demnach müssen die Seitenangaben manuell korrigiert werden.
Auf die Abstracts kann verzichtet werden, oder man öffnet das PDF und kopiert sie sich raus.
