### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review (Wiley) | Titelzusätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1303]
**URL**
https://onlinelibrary.wiley.com/toc/17586623/2020/72/4?campaign=woletoc

**Ausführliche Problembeschreibung**
Die Titelzusätze werden nicht nach Zotero übernommen.

**Comment by IxKo** [comment]
Kommen nun mit, danke.

**Comment by kdr154** [comment]
Und dann auch schon wieder nicht. 
https://onlinelibrary.wiley.com/toc/17586623/2021/73/1
https://onlinelibrary.wiley.com/doi/10.1111/erev.12580

![grafik](https://user-images.githubusercontent.com/29707105/127123720-e16a62de-bcde-4636-b0f4-60b9fcb905cb.png)


Translator: ubtue_Wiley_Online_Library

**Comment by socheres** [comment]
https://github.com/socheres/Zoterobearbeitung/commits/master/zotero_master/translators/ubtue_Wiley%20Online%20Library.js

**Comment by IxKo** [comment]
Titelzusätze kommen rüber, danke.
