### ISSUE TITLE
ISSN 2631-8334 | Pro Ecclesia | Schlagwort Review Article (LIVE)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1305]
**URL**
https://doi.org/10.1177/1063851220953822 (IxTheo#2021-01-05#03307759326999C0F65F1A59C88B123F0DB944F1)
https://doi.org/10.1177/1063851220954433 (IxTheo#2021-01-05#4E355FFD7ACBD1B4FBF81D960396FBF673CF0E53)

**Ausführliche Problembeschreibung**
Bei beiden Artikeln wird ein Schlagwort "Review Article" erzeugt, welches sich jedoch nicht auf der Artikel-Seite bei den Schlagwörtern befindet, sondern neben der First-Published-Angabe.

**Offenbare Lösungen**
Das Schlagwort sollte entfernt und in das Form-SW 1131 Rezension umgewandelt werden.

**betrifft auch folgende Zss:**

479 | 2396-9407 | International bulletin of mission research   / International bulletin of missionary research

**Comment by socheres** [comment]
wir hatten in einer Sitzung beschlossen Review Article nicht als Rezension aufzunehmen. https://github.com/ubtue/DatenProbleme/issues/1229#issuecomment-728822557
der Indikator ändere ich aber noch in |f|

**Comment by IxKo** [comment]
Da ging es aber um "Article commentary". Hier steht aber "Review Article".
![image](https://user-images.githubusercontent.com/57000004/105706876-685e6980-5f12-11eb-9b62-764b9ce219d7.png)
VS
![image](https://user-images.githubusercontent.com/57000004/105706951-7f04c080-5f12-11eb-96c4-064df8f465e1.png)

**Comment by IxKo** [comment]
Die Frage ist auch, ob es falsch ist, sie als 1131 Rezension einzuspielen?
Was auf jeden Fall falsch ist, ist wie es jetzt ist:
![image](https://user-images.githubusercontent.com/57000004/105707470-47e2df00-5f13-11eb-93d1-09393aca015e.png)
Es müsste wenigstens als |f| für Form-SW gekennzeichnet sein.

**Comment by socheres** [comment]
Nur "Book Review" in 1131 Rezension umwandeln. Bei nicht eindeutigen "Rezensionen" wie "Review Article" u.a. - m.E. eigenständiger Aufsatzartikel - ohne 1131 einspielen. Bis der Indikator im Harvester angepasst ist, bitte diese Zeitschrift weiterhin auf "zota" setzen.  Den Indikator korrigiere ich dann nachträglich in WinIBW per Skript.
@mtrojan-ub folgende Code-Anpassung notwendig:
- [ ] aus Keyword "Review Article" Feld `655 4$aReview Article` erzeugen und nicht wie bisher `650 4$aReview Article`
- [ ] Listenfunktion für eventuell weitere Formschlagwörter die in Feld 655 ausgegeben werden soll? Z.B. "Open Access" etc.

**Comment by IxKo** [comment]
Das SW taucht auch bei diesen beiden Sage-Zss auf:
Z|ePPN|eISSN|Zss-Titel
-- | -- | -- | --
479 | 341354112 | 2396-9407 | International bulletin of mission research   / International bulletin of missionary research
1164 | 638066778 | 2044-2696 | Theology : a monthly journal of historic   christianity

Noch kann man es manuell bereinigen: 
F BZI sage FSH review article

**Comment by socheres** [comment]
- [ ] in WiniBW per Skript bereinigen.

**Comment by mtrojan-ub** [comment]
Wie heute im zotaut-Meeting besprochen soll es eine Liste von Schlagwörtern geben die als 655 ausgespielt werden soll. Die Liste soll händisch gepflegt werden können.

**Comment by mtrojan-ub** [comment]
Die Änderung kann jetzt auf nu getestet werden. Die Schlagwörter können in dieser Datei gepflegt werden:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/marc655_keywords.txt
(Groß/Kleinschreibung ist wichtig)

**Comment by IxKo** [comment]
@mtrojan-ub Der 2. Indikator muss 4 sein (ind2=4):
`<datafield tag="655" ind1=" " ind2="4"><subfield code="a">Review Article</subfield>`

Momentan ist er leer (Test auf Nu):
![image](https://user-images.githubusercontent.com/57000004/108818140-401d6580-75b9-11eb-86d2-7c2313c59a02.png)

**Comment by mtrojan-ub** [comment]
Die Anpassung wurde auf nu eingespielt, bitte nochmal testen.

**Comment by IxKo** [comment]
Wird auf Nu mit TRY URL nun korrekt ausgegeben. Danke!

**Comment by IxKo** [comment]
@mtrojan-ub Damit es jedoch nicht zu vermehrten Error-Dateien kommt, müsste in den globalen QA-Settings noch etwas geschraubt werden.
Denn Rezensionen besitzen dasselbe MARC-Feld aber mit 2. Indikator 7 statt 4. Zusätzlich werden Rezensionen noch mit den Unterfeldern 0 und 2  geliefert.
Und zu den letzten beiden Unterfeldern ist in den QA-Settings always gesetzt. Dies müsste dann auf sometimes

**Comment by kdr154** [comment]
So wie die Datei marc655_keywords.txt im Augenblick eingebunden ist, kommt es zu einem Fehler. Siehe #1458

**Comment by kdr154** [comment]
Kann man die Unterfelder 0 und 2 bei Marc 655 in den QA-Settings global auf sometimes setzen, oder steht das noch zur Diskussion? 
Sonst müsste man die Anpassung für jede Zeitschrift gesondert vornehmen. Auch bei der hier diskutierten stehen die Unterfelder 0 und 2 in Marc 655 noch auf always.

**Comment by IxKo** [comment]
Bei den QA-Settings wird zwischen Rezensionen und Nicht-Rezensionen unterschieden.
Momentan ist das Feld 655 global für "Review Articles (all Jorunals)" definiert (gelber Hintergrund).
![image](https://user-images.githubusercontent.com/57000004/115251333-bc9c7280-a12a-11eb-9082-9be3da1e9ed1.png)

Es sollten aber globale Einstellungen für 655 bei den Nicht-Rezensionen (grüner Hintergrund) angegeben werden:
a - Sometimes
Sonst kommt ein Datensatz mit dem Feld eventuell nicht durch die Prüfung, weil das Feld nicht als Möglichkeit definiert wurde.
@mtrojan-ub @jriedl

**Comment by jriedl** [comment]
Es ist doch genau andersherum: Nur die als Rezension getaggten Artikel sind "review articles" im Sinne des QS. Ansonsten ist hier einfach keine Regel definiert, deshalb gibt es auch keine Prüfung und es kann nichts ausgefiltert werden.

**Comment by IxKo** [comment]
Okay, vielleicht täuscht mich auch die Erinnerung. Wurde nicht einmal gesagt, dass jedes Feld und Subfield, das wir liefern, in den QA-Settings stehen sollten, weil es ansonsten als "Unbekannte" gilt und der Datensatz dadurch auch in den Errors landet?
