### ISSUE TITLE
1043-1578 | Social justice – A journal of crime, conflict and world order | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1306]
Es wird keine Sprache geliefert, marc 041.

![grafik](https://user-images.githubusercontent.com/29707105/104198072-17387b00-5426-11eb-8837-5a8f82f7bdcb.png)

http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26AN%3d145451354%26site%3dehost-live

**Comment by jriedl** [comment]
Für Testdatensatz auf nu behoben.

**Comment by kdr154** [comment]
Sieht gut aus
