### ISSUE TITLE
ISSN 2468-9963 | Delito y sociedad – Revista de ciencias sociales | Seitenangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1307]
Das, was wahrscheinlich eine Nummer für das Dokument ist, wird zur Seitenangabe in 936 $h:

![grafik](https://user-images.githubusercontent.com/29707105/104199818-36380c80-5428-11eb-9810-e9f7cedf8456.png)

https://bibliotecavirtual.unl.edu.ar/publicaciones/index.php/DelitoYSociedad/article/view/9766

Da wir m. W. noch keine Lösung für diese Fälle im vollautomatischen Verfahren haben, sollte diese Angabe unterdrückt werden oder die ZS halbautomatisch bearbeitet werden.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Danke, hat geklappt.
