### ISSUE TITLE
1043-1578 | Social justice – A journal of crime, conflict and world order | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1308]
Die Zeitschrift enthält Rezenionen. Diese werden nicht getagt:
![grafik](https://user-images.githubusercontent.com/29707105/104285473-fb7bb600-54b3-11eb-98c2-a50695f71362.png)

http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26AN%3d145451368%26site%3dehost-live

**Comment by jriedl** [comment]
Auf nu

**Comment by kdr154** [comment]
Bekommen Fehlermeldung: XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Sowohl bei tryUrl als auch bei tryRSS

**Comment by jriedl** [comment]
tryUrl konnte ich mit dem gleichen Softwarestand soeben problemlos auf nu ausführen. Habe aber jetzt dennoch eine zusätzliche kleine weitere Anpassung integriert und auf nu eingespielt.

**Comment by jriedl** [comment]
Was genau funktioniert denn nicht? Mit oben angegebener URL und tryURL auf nu bekomme ich einen Datensatz mit einem 655-Rezensions-Feld. tryRSS liefert ebenfalls Datensätze.

**Comment by kdr154** [comment]
War gestern Abend nicht der Fall, kein 655. Ich teste noch einmal. Mit TryURL:
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26AN%3d145451360%26site%3dehost-live
Das ist eine Rezension. In den Daten steht aber kein 655:

![grafik](https://user-images.githubusercontent.com/29707105/104597990-50ffc080-5676-11eb-9271-c69fc3cdd775.png)

**Comment by kdr154** [comment]
In der Einspielung von heute Nacht wurde dieser Aufsatz ebenfalls nicht als Rezension gekennzeichnet:
![grafik](https://user-images.githubusercontent.com/29707105/104692861-f5cade00-5708-11eb-85ce-787a1b033df0.png)

**Comment by jriedl** [comment]
Das scheint ein ähnliches Problem zu sein wie bei SAGE-Keywords: ein Einzeltest (lokal, nu) liefert für `http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26AN%3d145451360%26site%3dehost-live` die Auszeichnung als Rezension.
![image](https://user-images.githubusercontent.com/13135579/104899723-7c86f180-597b-11eb-85b7-870414ec1ce2.png)



 Da die Rezensionsinformation aber über einen Subtranslator per RIS extrahiert wird, scheint diese Abfrage je nach vorher schon aufgetretener Last fehlzuschlagen. Versuche hier eine Lösung zu finden.

**Comment by jriedl** [comment]
Codeanpassungen und auf nu noch einmal resettet. Bitte morgen noch einmal in der Testdatenbank überprüfen.

**Comment by kdr154** [comment]
Auf nu werden Rezensionen getagt. Morgen Überprüfung in der Tetdatenbank. Zwei Sätze sollten ein Update erhalten.

**Comment by jriedl** [comment]
vgl. #1351 .

**Comment by jriedl** [comment]
Ist behoben, oder?

**Comment by kdr154** [comment]
Ist behoben
