### ISSUE TITLE
ISSN 2342-7256 | Temenos | Davar Logos

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1309]
Bei vielen, wenn nicht bei allen Zeitschriften, die im halbautomatischen Verfahren mit dem "Open Journal Systems Standard"-Translator übertragen werden sollen, steht der "DavarLogos"-Translator an erster Stelle und ist sozusagen Standard.  So auch bei dieser Zeitschrift. Kann man den nicht von dieser Position entfernen?

![grafik](https://user-images.githubusercontent.com/29707105/104299463-8dd88580-54c5-11eb-99b2-b2635349852c.png)

Tatsächlich funktioniert der Download auch. Nur eben fehlerhaft. Vor allem steht im Feld ISSN die ISSN von Davar Logos. Wenn man nicht daran denkt, auf diesen Umstand zu achten, ist das jedes Mal ärgerlich. Zumal des Datensatz auf den ersten Blick gar nicht schlecht aussieht:

![grafik](https://user-images.githubusercontent.com/29707105/104300196-72ba4580-54c6-11eb-89a8-b0118bc66e18.png)

Als ob es sich um einen Aufsatz der Zeitschrift "Temenos" handelt, nur mit der ISSN von Davar Logos und den kleinen Fehlern in den Feldern "Band", "Ausgabe" und "Datum"

**Comment by socheres** [comment]
Habe die Prio von Davarlogos-Translator heruntergesetzt.

**Comment by kdr154** [comment]
Steht leider immer noch an erster Stelle. Im Übrigen auch hier: https://revistas.pucsp.br/index.php/culturateo/issue/view/2517

**Comment by socheres** [comment]
Kann leider den Fehler nicht reproduzieren. 
![image](https://user-images.githubusercontent.com/1545743/104319677-7dce9f00-54e1-11eb-9b7e-02426853d880.png)

**Comment by kdr154** [comment]
Das macht den Test natürlich schwierig, da ich davon ausgehen muss, dass wir mit unterschiedlichen Systemen arbeiten. De facto bin ich aber nachteilig davon betroffen, da ich die Dinge katagisiere und korrigieren muss.

**Comment by socheres** [comment]
Das ist merkwürdig. Denn die Translators von "ubtue_Davarlogos", "ubtue_Open Journal Systems Standard", "ubtue_Open Journal Systems Multi-Wrapper", "Open Journal Systems" auf ihrem Laufwerk sind mit denen von meiner lokalen Kopie identisch. Das schauen wir am Besten gemeisam via Screensharing an.

**Comment by kdr154** [comment]
Ok. Wie machen wir das?

**Comment by socheres** [comment]
siehe email

**Comment by kdr154** [comment]
gelöst
