### ISSUE TITLE
ISSN 2342-7256 | Temenos | Titelzusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1310]
Der Titelzusatz wird nicht erfasst. Statt dessen wird lediglich ein Doppelpunkt gesetzt, der in der WinIBW die Ausgabe des Codes "$d" bewirkt.

https://journal.fi/temenos/article/view/97275

![grafik](https://user-images.githubusercontent.com/29707105/104301239-afd30780-54c7-11eb-9409-faa979ca4e1d.png)

**Comment by socheres** [comment]
Welches Translator haben Sie verwendet?

**Comment by kdr154** [comment]
Das ist bei allen der Fall. Open Journal Systems Standard als erstes, dann wird noch der Multi-Wrapper angeboten und natürlich an erster Stelle, DavarLogos. Aber auch bei diesem ist es so.

**Comment by socheres** [comment]
"ubtue_Open Journal Systems Standard.js" verwenden.

**Comment by kdr154** [comment]
gelöst
