### ISSUE TITLE
ISSN 2342-7256 | Temenos | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1312]
Die Webseite erfasst bei der Endseitenzahl nur die Ziffern, die sich von denen der Anfangsseitenzahlen unterscheiden.
https://journal.fi/temenos/issue/view/7000
Das ist doch eine schöne Aufgabe für einen Programmierer

**Comment by socheres** [comment]
Das ist Eingabefehler. Das Translator kann daher nicht angepasst werden. Bitte manuell bearbeiten.

**Comment by kdr154** [comment]
Ich denke, das wird von den Betreibern der Webseite absichtlich so gehandhabt. Das System ist doch klar erkennbar. Wird m. W. auch von anderen so gehandhabt.  Aber wenn man den Translator nicht entsprechend programmieren kann. müssen wir es natürlich manuell korrigieren.
