### ISSUE TITLE
ISSN 1552-6518 | Journal of interpersonal violence | Seitenangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1314]
Im Heft 36.2021,1-2 https://journals.sagepub.com/toc/jiva/36/1-2 gibt es zwei formal unterschiedliche Seitenzahlformate. 
Angaben die lediglich aus Ziffern bestehen, etwa 10-30, und solche mit dem Zusatz "NP", in der Form "NP10-NP30".
Diese werden auch so in die Winibw eingespielt. Vgl die Liste unter PPN 324614721. Was wie ein Fehler aussieht entspricht der Vorlage, widerspricht aber der Richtlinie, dass Seitenzahlen aus arabischen Ziffern bestehen sollten.
Sage hat diese Form zur Unterscheidung von Aufsätzen eingeführt, die nur Online publiziert werden im Gegensatz zu denen, die Online und Print erscheinen. Siehe Heft oben.
Soll man das so lassen, oder korrigieren? Wenn man korrigiert, kommt es zu sich überschneidenden Seitenangaben.

**Comment by socheres** [comment]
in PDFs z.B. https://journals.sagepub.com/doi/pdf/10.1177/0886260517730564 steht auch "NP.." und so muss auch zitiert werden. Bitte so stehen lassen.

**Comment by jriedl** [comment]
Kann das dann geschlossen werden?

**Comment by kdr154** [comment]
Da niemand Widerspruch erhoben hat, schließe ich.
