### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Tag 007

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1315]
https://ojs.ehu.eus/index.php/eguzkilore/index
Im Tag 007 steht tu: 
![grafik](https://user-images.githubusercontent.com/29707105/104462362-c5702c00-55b0-11eb-89f6-129aab91e6f6.png)
hier muss "cr|||||" rein.

**Comment by jriedl** [comment]
`tu` wird laut unserem Code eingefügt, wenn das übergeordnete Werk nicht elektronisch ist. Das scheint hier der Fall zu sein (vgl 773) : PPN 170545342 verweist (wohl infolge von ISSN 0210-9700) auf die Druckausgabe (vgl. #1313).

**Comment by kdr154** [comment]
Ich habe jetzt in beiden Fällen die pISSN in das Feld eISSN eingetragen, in der Hoffnung, dass es was bewirkt. Bei "Social Justice" bereits gestern. Der Fall, dass es keine ISSN für die Online-Version gibt und folglich kein Pica 2000 statt dessen in Pica 2013 die pISSN, kommt immer mal wieder vor. Ob es was bewirkt hat, kann ich erst sagen, wenn die Daten wieder, oder neue eingespielt werden. Heute kam gar nichts neues, obwohl ich gestern einiges zurückgesetzt habe. Aber das lag wohl an der RSS-Problematik.
Nach meiner laienhaften Interpretation des Codes auf den mtrojan verweist, könnte dies der Fall sein.
In diesem Fall ist das übergeorndnete Werk auf jeden Fall elektronisch: "Revista electrónica " "e-Eguzkilore"

**Comment by kdr154** [comment]
Habe alle Sätze von "Social Justice" zurückgesetzt und einige auf dem Testserver gelöscht. Nach dem Post von @mtrojan-ub sollten die ja morgen neu eingespielt werden.

**Comment by kdr154** [comment]
Das Eintragen einer ISSN in das Zeder-Feld essn und das ändern der QA-Settings war in beiden Fällen, bei "Social Justice" und bei "Eguzkilore" erfolgreich. Die Daten wurden heute eingespielt und mit der Online-Ausgabe verknüpft.
