### ISSUE TITLE
2232-1969 | Al-Bayān | Sprachmapping schlägt fehl

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#1317]
Hat zum Abbruch des Durchlaufs am 13.01. geführt => High priority

zotero_expected_languages = ara,eng,may

may ist auch erlaubt laut "Supported languages", aber scheinbar gibt es ein Mappingproblem. Im Dezember gab es hierzu eine Änderung, ein möglicher Zusammenhang wird noch geprüft. 

```
====================================================================================================
considered language "may" is not supported!
====================================================================================================
```

**Comment by mtrojan-ub** [comment]
Zur genannten Thematik gab es keinen Issue, aber mehrere E-Mails am 17.+18.12.2020. Das Sprachkürzel "may" wird unterstützt, allerdings war das language_model für das NGram-Verfahren noch als "msa" hinterlegt, das wurde nun korrigiert.

Der Code zur vorigen Änderung war zwar schon zuvor live, allerdings wurde er vermutlich deshalb bisher nicht ausgeführt, weil erst seit gestern die Änderung bezüglich der häufigeren Verarbeitung der RSS-Feeds eingespielt wurde.

**Comment by IxKo** [comment]
Ich weiß nicht so recht, wie ich testen soll. Folgender Artikel ist nicht geliefert worden, da es zu keiner Sprachcode-Generierung in 041 kam:

**4A198CBC745F0486FCE9BE7C0FA8BB5E39DF8B50** (https://brill.com/view/journals/jqhs/18/2/article-p178_4.xml) 
Titel: Analysis Hadith Al-Ṯurāyya Dan Kaitannya Dengan COVID-19

CLI-Output auf Nu: 
Converting item 1 [Al-Bayān...] | https://brill.com/view/journals/jqhs/18/2/article-p178_4.xml {6360580724522503917}
use online ISSN "2232-1969" with online PPN "828844771"
Normalized language: en => eng
generated too few ngrams (183 < 400)!
ara scored :0.000000
eng scored :0.435062
may scored :0.595649
The given language eng and the detected language may are different. No language will be set.

Hier wird mit dem Sprachcode may abgeglichen, demnach gibt es keine Probleme mehr mit dem Code?

**Comment by mtrojan-ub** [comment]
Wenn der Aufruf grundsätzlich funktioniert hat ist das Mapping an sich jetzt korrekt. Falls es Optimierungsbedarf an der Erkennung gibt wäre das ein separates Thema, daher werde ich diesen Issue schließen.
