### ISSUE TITLE
ISSN 0974-2891 | International journal of cyber criminology | Delivered Records

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1318]
Unter Delivered Records zu dieser Zeitschrift befindet sich nur ein Eintrag:
![grafik](https://user-images.githubusercontent.com/29707105/104691835-417c8800-5707-11eb-93d9-6d8474db0867.png)

Tatsächlich wurden mit diesem Datum aber 21 Aufsätze von dieser Zeitschrift eingespielt. Wie ist dieser Unterschied zu erklären?

**Comment by mtrojan-ub** [comment]
Die Zeitschrift wird mit dem CRAWL-Verfahren bearbeitet. Gemäß den Einstellungen wird nur die Startseite bearbeitet. Das Problem ist, dass die einzelnen Artikel allesamt die selbe URL haben, nämlich `http://www.cybercrimejournal.com/index.html`. Da es laut unserer Datenbank pro URL genau 1 Artikel geben darf, kommt der Harvester durcheinander. 

Wahrscheinlich müsste der Translator so angepasst werden, dass er nicht die URL der Startseite sondern die URL des Artikels zurückgibt (also z.B. die URL der PDF oder der DOI)? Das wäre aus Metadaten-Sicht vermutlich ohnehin besser. Es kann sein, dass im Anschluss noch eine Anpassung am Harvester für das CRAWL-Verfahren passieren muss um mehrfache Lieferungen derselben Artikel zu verhindern.

**Comment by jriedl** [comment]
Das scheint nicht mit dem Translator zusammenzuhängen - dieser liefert im URL-Feld unterschiedlichen Werte zurück - erkennbar am `856`-Feld, so z.B.:

![image](https://user-images.githubusercontent.com/13135579/104894668-4c3c5480-5975-11eb-8721-557b3b9350af.png) 
vs.
![image](https://user-images.githubusercontent.com/13135579/104894816-7261f480-5975-11eb-8285-fce6339b4f76.png)

**Comment by jriedl** [comment]
Nachtrag: Als `URL`-Parameter wird vom Harvester offenbar die `harvest_url` verwendet . Diese ist in diesem Fall aus systematischen Gründen immer identisch, da hier alle relevanten Informationen innerhalb einer Website sind

**Comment by mtrojan-ub** [comment]
OK, danke fürs Prüfen! Dann werde ich mal schauen wie sich das auf Harvester-Seite weiter anpassen lässt.

**Comment by mtrojan-ub** [comment]
Die Anpassung wurde auf nu eingespielt, es wird jetzt die URL aus Zotero für die interne Verwaltung verwendet, sofern diese vorhanden ist. Die Datensätze sollten also beim nächsten Durchlauf heute Abend einmalig nochmal geliefert + dann in der DB richtig erfasst werden.

**Comment by kdr154** [comment]
Von dieser Zeitschrift wurden heute Nacht 18./19. 1. keine neue Daten eingespielt. Nu ist ebenfalls auf dem Stand von Gestern:
![grafik](https://user-images.githubusercontent.com/29707105/105007201-f8df0a80-5a37-11eb-968f-6e578f120794.png)

**Comment by mtrojan-ub** [comment]
Das fällt in die Kategorie der RSS-Feeds die ausschließlich erfolgreiche Einträge haben. Mit der heutigen Änderung sollten solche Feeds jetzt auch täglich neu verarbeitet werden und die anderen Einträge sollten morgen früh auftauchen.

**Comment by kdr154** [comment]
Es hat sich nichts geändert. Immer nur noch der eine Satz mit dem Datum vom 14.

**Comment by mtrojan-ub** [comment]
Der DB-Eintrag für den vorhandenen Satz hatte als URL noch die Startseite statt der PDF hinterlegt, daher wurde der Download der Startseite übersprungen. Ich habe das jetzt DB-seitig von Hand korrigiert und gehe davon aus, dass die Startseite daher beim nächsten Durchlauf nicht mehr übersprungen wird.

**Comment by mtrojan-ub** [comment]
Jetzt sind es 21 Einträge

**Comment by kdr154** [comment]
Schön, dass die Ursache gefunden wurde.
