### ISSUE TITLE
THEOLDI-Migration - Schlagwort Bibelpastoral

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#1319]
Für das Nicht-GND-Schlagwort **Bibelpastoral** wurden durch maschinellen Abgleich fälschlich >2.200 Datensätze in Feld 5580 mit dem Körperschaftsdatensatz  PPN 677748531 Archidiocèse$gLuxembourg$bPastorale Biblique Dicoćesaine ; ID: gnd/16332167-X verknüpft, der in einem der Felder 410 Archidiocèse$gLuxembourg$b**Bibelpastoral** enthält.

Diese Falschverknüpfungen müssen wie folgt geändert werden:

**5580 !677748531!**   _Archidiocèse$gLuxembourg$bPastorale Biblique Dicoćesaine ; ID: gnd/16332167-X_

ändern zu:

**5580 !105834912!**   _Bibelarbeit ; ID: gnd/4112752-3_
**5520 |s|Bibelpastoral**

Manuelle Korrektur von Lokaldatenzählung bei Mehrfachexemplaren in 40 Datensätzen erledigt, damit diese nicht zu Validationsfehlern führen.

PPN-Liste der betroffenen Datensätze:
[Bibelpastoral.pdf](https://github.com/ubtue/DatenProbleme/files/5819577/Bibelpastoral.pdf)

**Comment by socheres** [comment]
Wie kann man das Suchergebnis auf die THEOLDI-Migration einschränken? `f s2 cod BIIN"` bekomme ich 2179 Datensätze.

**Comment by IxTheoKm** [comment]
Es müssen nur die Titelsätze aufgerufen werden, die mit PPN 677748531 verknüpft sind.

**Comment by socheres** [comment]
ca. 2000 Datensätze, die mit PPN 677748531 verknüpft waren, konnten wie oben beschrieben mit Funktionsskript bereinigt werden. @IxTheoKm bitte die 2 nicht valide Datensätze manuell korrigieren.

**Comment by IxTheoKm** [comment]
Manuelle Korrektur der restlichen zwei Datensätze erledigt.

Vielen Dank für die Bereinigung!!!
