### ISSUE TITLE
Rezensionen formal Pica - Marc21

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#132]
Rezensionen erfordern in den Titeldaten in der WinIBW folgende zusätzliche Felder und Inhalte:
1131 !209083166!
1140 uwre
4261 Rezension von!!

Für 1131 wird das Marc21-Feld 655 benötigt mit ind2="7", und den Unterfeldern $a und $0
In $a steht in Ausrufrzeichen die PPN des Normdatensatzes einer Rezension. Dieser Wert ist immer  !209083166!
In $0 steht, dass es sich um eine PPN handelt, immer mit dem Wert (DE-576)
Für 1131 müsste folgendes generiert werden:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!209083166!</subfield>
<subfield code="0">(DE-576)</subfield>
</datafield>
```
Für 1140, hier ebenfalls immer der gleiche Wert, braucht man das Marc21-Feld 935 mit dem Subfield c, Indikatoren bleiben leer
Also:
```
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="c">uwre</subfield>
</datafield>
```
In 4261 steht zwischen den Ausrufezeichen die BSZ-PPN des rezensierten Werkes. Ist das Werk nicht erfasst, muss man es auf komplizierte Weise aufbauen. Etwa so:
4261 Rezension von$lAutort$tTitel$dOrt$fPublikationsjahr$uISBN
Benötigt wird das Marc21-Feld 787 mit den Werten 0 und 8 in den Indikatoren
hat man die PPN braucht man $i mit der PPN und $w mit dem Wert (DE-576)
hat man die PPN nicht, $a(Verfasser), $t(Titel), $d für Ort, Verlag und Datum, getrennt durch " :  " und " , " und $z für die ISBN. Alles sofern vorhanden.
In den Lokaldaten müssen in 8002 die Werte ixrz und zota stehen: 8002 ixrz;zota (wenn ich es richtig in Erinnerung habe.
Benötigt wird Marc21-Feld mit $a, Indikatoren bleiben frei.

Aber ich denke, wir sollten das alles zuerst mit Frau Katz abklären. Habe diesbezüglich eine Mail an Frau Katz geschrieben. Unbedingt die Antwort abwarten, bevor mit der Umsetzung begonnen wird.

**Comment by shadeMe** [comment]
Ich setzt die Issues, die Rezensionen betreffen, derzeit auf "blocked" bis wir von Frau Katz hören.

**Comment by kdr154** [comment]
ok

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Freitag, 14. Dezember 2018 13:02
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Assign <assign@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Rezensionen formal Pica - Marc21 (#132)

 

Ich setzt die Issues, die Rezensionen betreffen, derzeit auf "blocked" bis wir von Frau Katz hören.

**Comment by shadeMe** [comment]
@kdr154 Hat Frau Katz sich gemeldet? Wir haben das Thema in dem heutigen Meeting angesprochen und der folgende Konsens ist entstanden: wir strukturieren die Zotero Datensätze nach den vom BSZ erhaltenen Datensätzen, die sich um Rezensionen handeln. Ich nehme an, was oben steht führt genau drauf zurück oder? Wenn das doch der Fall wäre, kann ich gleich mit der Umsetzung anfangen.

**Comment by thefass** [comment]
@kdr154 Das BSZ hat vermutlich gerade nicht viel Zeit und wir sollten versuchen, die Antworten zu den Fragen möglichst aus den vorhandenen Metadaten abzuleiten. Sonst sind wir zulange blockiert

**Comment by kdr154** [comment]
Ich denke, bis auf das Feld 787 sollten wir die Kategorien so übernehmen, wie oben angegeben. 
Für 787 beziehe ich mich auf das PDF-Dokument Katz/Faßnacht in der Mail von Herr Faßnacht.
Daraus ergibt sich, dass der Indikator 1 den Wert 0 haben muss, der Indikator 2 bleibt frei
in $a steht der Verfasser des rezensierten Werkes (sofern vorhanden)
in $i die Bemerkung "Rezension von"
in $t der Titel des rezensierten Werkes
       wenn kein Verfasser vorhanden ist wird $t nach $a transportiert
in $w die SWP-PPN
      hier steht in dem Papier, wird vom SWB geliefert. Dies geht nur, wenn der Titel im SWB erfasst worden  ist. Wobei ich mir die Frage stelle, wie dies in diesem Fall in der Praxis gehen soll. Bei der Bearbeitung von Rezensionen im Augenblick recherchieren wir gesondert und wenn der Titel gefunden wird, verlinken wir manuell.
in $z soll die ISBN stehen, und zwar dann, wenn es keine SWB-PPN gibt. Die ISBN findet man manchmal in der Kategorie 245 unter $a. Dies íst aber Zufall.
Wenn Aufsätze rezensiert werden, ein häufiger Fall, entfällt die Option mit der ISBN, die Option SWB-PPN dagegen besteht, sofern der Aufsatz zuvor erfasst worden ist.
in $d stehen Ort, Verlag, Erscheinungsjahr, laut BSZ-Konkordanz in der Form `<subfield code="d">Ort : Verlag , Erscheinungsjahr</subfield>`
Auch diese Informationen finde ich in den jetzigen Daten in 245 $a. Frage mich aber, wie das System erkennen soll, welcher Teil der Zeichenkette der Verlag ist, welcher der Erscheinungsort, und was andere Bestandsteile sind.
Von den zum Testen vorgeschlagenen Zeitschriften ist für Monographien und Sammelwerke insbesondere  ISSN 1350-7303 für geeignet, Rezensionen von Aufsätzen habe ich in keinem Feed dieser Zeitschriften gefunden

**Comment by thefass** [comment]
> in $w die SWP-PPN
> hier steht in dem Papier, wird vom SWB geliefert. Dies geht nur, wenn der Titel im SWB erfasst worden ist. Wobei ich mir die Frage stelle, wie dies in diesem Fall in der Praxis gehen soll. Bei der Bearbeitung von Rezensionen im Augenblick recherchieren wir gesondert und wenn der Titel gefunden wird, verlinken wir manuell.
> in $z soll die ISBN stehen, und zwar dann, wenn es keine SWB-PPN gibt. Die ISBN findet man manchmal in der Kategorie 245 unter $a. Dies íst aber Zufall.

Das war eine besondere Situation in jenem Projekt, was in dem Papier beschrieben ist, was aber unter den Bedingungen des automatischen Zotero-Verfahrens nicht umgesetzt werden kann. Uns bleibt eigentlich nur, das rezensierte Werk literal zu erfassen. Wann immer Identnummern abgegriffen werden können, sollten wir das tun. Das wird meist die ISBN sein, eine DOI dürfte m.E. ganz selten sein, ebenso selten wie Aufsatzrezensionen vorkommen.
Über die ISBN könnte man später mit einem Putzprogramm eine reziproke Verlinkung zwischen Rezension und rez. Werk ausführen. Ansonsten bleibt nur eine manuelle, händische Verlinkung. 
Die Verlinkung hat natürlich einen großen Vorteil, da der Nutzer dann zu einem Werk, das er gefunden hat, auch gleich den Hinweis auf die Rezension erhält. Aber auch ohne Verlinkung ist wertvoll, die Rezension bei einer Suche finden zu können.

**Comment by shadeMe** [comment]
@kdr154 Wollen wir dies jetzt schließen?

**Comment by kdr154** [comment]
ok
