### ISSUE TITLE
ISSN 1468-0025 | Modern Theology | Rezension (Wiley)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1321]
**URL**
https://onlinelibrary.wiley.com/toc/14680025/2021/37/1?campaign=woletoc

**Ausführliche Problembeschreibung**
Bei den Rezensionen wird der Tag "Book Review, Book Review" in Zotero übertragen.
Es wäre schön, wenn dieses in das RezensionstagPica umgewandelt werden könnte.

Multi-DL mit Translator Wiley Online Library

![image](https://user-images.githubusercontent.com/57000004/104888000-72112b80-596c-11eb-8cda-2d91a5f9ff23.png)

**Comment by socheres** [comment]
Wird beim Exportieren nach PICA gelöst.

**Comment by IxKo** [comment]
Ach okay, aber es erscheint dann beim Upload in den K10plus zusätzlich das Feld 5520 |f|Book Reviews. Meiner Meinung nach könnte man auf diese Zeile ganz verzichten, da 1131 Rezension ausreicht.

**Comment by IxKo** [comment]
Händisch löschen.
