### ISSUE TITLE
ISSN 2044-8333 | Legal and criminological psychology | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1325]
https://bpspsychub.onlinelibrary.wiley.com/toc/20448333/2021/26/1
Bei diesem Artikel: https://bpspsychub.onlinelibrary.wiley.com/doi/10.1111/lcrp.12178
werden keine Seitenzahlen erfasst. Sie stehen aber auf der Seite mit dem Inhaltsverzeichnis (s. o.)

![grafik](https://user-images.githubusercontent.com/29707105/104909910-d9d56f80-5988-11eb-9bb0-aadb13858003.png)

**Comment by hlindeboom** [comment]
Die Änderungen wurden auf nu eingespielt, die Seitenzahlen sollten nun erfasst werden.

**Comment by kdr154** [comment]
Der Artikel besitzt jetzt Seitenzahlen.
