### ISSUE TITLE
ISSN 0973-5089 | International journal of criminal justice sciences | gelistete Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1327]
http://www.sascv.org/ijcjs/
nu zeigt an, dass nur ein Artikel geharvestet wurde: 
![grafik](https://user-images.githubusercontent.com/29707105/104917153-51100100-5993-11eb-891c-519ad544075f.png)

Eine Suche in der Error-xml ergibt jedoch, dass 23 Aufsätze erfasst wurden.

![grafik](https://user-images.githubusercontent.com/29707105/104917395-a3e9b880-5993-11eb-818a-1a7222d7a689.png)

Kein einziger jedoch wurde eingespielt. Demach hätten alle mit dem Delivery State "Error" zu finden sein müssen. Wieso werden die nicht gelistet?

**Comment by mtrojan-ub** [comment]
Ebenfalls CRAWL, sieht auf den ersten Blick nach dem selben Problem aus wie bei #1318 nur in anderem Kontext.

**Comment by kdr154** [comment]
Genau. Hier auch: http://www.boletincriminologico.uma.es/boletines.php?PHPSESSID=d00a87e127d6ef782f5c6279fbfc15a7
2 von 18

**Comment by mtrojan-ub** [comment]
Ähnlich wie beim oben verlinkten issue 1318 sollten die ERRORS ab heute Abend korrekt separat eingetragen werde, da jetzt bevorzugt die URL aus Zotero verwendet wird.

**Comment by kdr154** [comment]
Hier stimmt die Anzahl der auf nu gelisteten Sätze nun mit denen die in der Nacht vom 18./19. eingespielt wurde überein. (22)

**Comment by kdr154** [comment]
Bei Boletín Criminológico stimmt die Anzeige auf nu nun auch
