### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1328]
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/vol/64/suppl/C
Was erfasst wird, sind Artikelnummern und keine Seitenzahlen.
![grafik](https://user-images.githubusercontent.com/29707105/104925741-81f63300-599f-11eb-8671-69f02eeb0c8a.png)

Diese Unterdrücken. 
Wäre in den QA-Settings 936 $h "Ignore" auch eine Lösung?

**Comment by kdr154** [comment]
Laut #1330 muss dieser Fall von der IT gelöst werden.

**Comment by jriedl** [comment]
Da die Entfernung von falsch belegten Unterfeldern ein wiederkehrendes Problem ist, existiert für solche Fälle jetzt eine weitere Direktive in der Config-Datei. Für den aktuellen Fall sollte es behoben sein.

**Comment by kdr154** [comment]
Danke! Ist im aktuellen Fall behoben
