### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Issue in Progress

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1329]
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/vol/64/suppl/C
Die Artikel sind laut Webseite abgeschlossen und zitationsfähig.
Leider sind die Daten, die der Harvester liefert, in diesem Fall unvollständig. So fehlt der/die Verfasser immer, ebenso die Keywords. Zudem wird das Abstract abgeschnitten.
https://www.sciencedirect.com/science/article/pii/S1756061620304778
![grafik](https://user-images.githubusercontent.com/29707105/104928061-7c4e1c80-59a2-11eb-964f-aaed494fdad6.png)

Bei den abgeschlossenen Ausgaben hingegen sind die Daten vollständig vorhanden:

https://www.sciencedirect.com/science/article/abs/pii/S1756061620300586

![grafik](https://user-images.githubusercontent.com/29707105/104928263-b6b7b980-59a2-11eb-986d-c88827a6ef81.png)

**Comment by kdr154** [comment]
Die Probleme mit dem fehlenden Verfasser, Keywords und abgeschnittenem Abstract treten nun auch bei der inzwischen abgeschlossenen Ausgabe 64.2021 auf. Siehe log und xml-Dateien der Einspielung vom 31.1.2021.

**Comment by jriedl** [comment]
Vermutlich im Rahmen der anderen Issues gelöst.

**Comment by kdr154** [comment]
Das Issue in Progress wird jetzt auch korrekt erfasst.
