### ISSUE TITLE
ISSN 2468-9963 | Delito y sociedad | Artikelnummern

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1330]
https://bibliotecavirtual.unl.edu.ar/publicaciones/index.php/DelitoYSociedad/issue/view/817
Bei den Artikeln, die in diesem Durchgang geharvestet werden, fehlt 936 $h, die Seitenangabe. Das ist gut so, denn bei dem, was man auf den Webseiten findet, handelt es sich um Artikelnummern.
Aber auch hier die Frage: würde es genügen, in den QA-Settings 936 h auf "Ignore" zu setzen, um auszuschließen, dass sie bei anderen Aufsätzen dieser Zeitschrift doch erfasst werden?

**Comment by jriedl** [comment]
Nach meinem Verständnis von https://github.com/ubtue/ub_tools/wiki/Zotero-Harvester-Architecture#user-content-validation bedeutet `ignore` im Zusammenhang mit der QS, dass die Qualitätssicherung die fragliche Einstellung einfach gar nicht in Betracht zieht. Es führt also in keinem Fall zu Änderungen am Datensatz selbst. Eine QS-Einstellung, die sicherstellt, dass ein bestimmtes Feld _nicht_ vorhanden ist, lese ich aus den aktuellen Einstellungsmöglichkeiten nicht heraus. Für diesen konkreten Fall wurde die Seitenzahlproblematik ja aber ohnehin  über https://github.com/ubtue/DatenProbleme/issues/1307 gelöst. Damit erscheint mir `ignore` in diesem Kontext plausibel.

**Comment by kdr154** [comment]
Das stimmt. Aber wenn dem so ist, brauche ich in so einem Fall nicht mehr die IT bemühen.

**Comment by jriedl** [comment]
Ja genau, QS soll natürlich nicht selbst Daten ändern, sondern nur auf Probleme aufmerksam machen. Solche Datenänderungen wären bei uns ja in der `zotero_harvester.conf` z.B. mit der `remove_marc_field_XXX`-Direktive angesiedelt. Allerdings existiert nach meinem Kenntnisstand momentan keine Möglichkeit, damit nur einzelne Unterfelder zu löschen.

**Comment by kdr154** [comment]
Daten sind jetzt gut
