### ISSUE TITLE
ISSN 1893-4773 | Tidsskrift for Praktisk Teologi | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1332]
https://journals.mf.no/tpt/issue/view/523
https://journals.mf.no/tpt/article/view/5339
Book reviews werden mit dem Open_Journal_Systems_Standard.js-Translator nicht erfasst.

**Comment by helenanebel** [comment]
Lieber @socheres , lieder @kdr154 ,
das Rezensionstag wurde bisher nur beim Aufruf der englischen Version hinzugefügt, ich habe das für den ubtue_Open Journal Systems Multi-Wrapper angepasst.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Tag wird gesetzt.
