### ISSUE TITLE
Datenlieferung 18.01.2021 Krimdok Test

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1333]
Auf dem Testserver wurden heute Nacht 153 neue Sätze eingespielt.
Laut krimdok_zotero_210118_001.xml sollten es 455 sein. 
Muss man davon ausgehen, dass die Diskrepanz von 302 Sätzen bereits geliefert wurde?

Nebenbei:
Die Error-Log verzeichnet (fälschlicherweise) 503 Sätze, die Error-XML 48.
48 + 455 ergibt 503.

**Comment by jriedl** [comment]
Wegen des Resets im Zusammenhang mit https://github.com/ubtue/DatenProbleme/issues/1308 erscheint das nachvollziehbar, da hier dann in vielen Fällen Match-And-Merge gegriffen haben sollte. Wieviele Krimdokdatensätze mit aktuellem _Änderungsdatum_ existieren denn? Da nach den gestrigen Änderungen ja nun auch gültige Records in der error.log aufgelistet, erscheint die Zahl 503 doch plausibel, oder?

**Comment by kdr154** [comment]
Wie gesagt 153.
Von "Social Justice" gar keiner.
Ich finde auf nu nur jede Menge mit dem Datum 18.1.2021 die geliefert wurden (Delivery Status grün, 268) und einige die manuell eingespielt werden sollen (Delivery Statues gelb, 13). Und einige mit dem Datum vom 14.1., die Auf Reset stehen (Delivery Status blau, 39). Insgesamt sind es dort 320, die gelistet sind.
Die krimdok_zotero_210118_001.xml listet 298 Sätze mit der ISSN von Social Justice
Die Error-XML 13. Das stimmt mit denen auf nu (Status gelb) überein.
Bei den (theoretisch) gelieferten gibt es aber eine Diskrepanz von 30.

**Comment by jriedl** [comment]
Aber die 153 bezieht sich doch auf die Neueinspielungen. Da Social Justice ja bereits vorher eingespielt wurde, ist davon auszugehen, dass hier keinen _neuen_ Datensätze angelegt wurden. Die Inhalte von `krimdok_zotero_210118_001.xml` sind ja aber dennoch zum BSZ hochgeladen worden und sollte zu Änderungen an bereits vorhandenen Datensätzen geführt haben (Match-And-Merge). Im Inhalt von `krimdok_zotero_210118_001.xml` erkennt man z.B., dass `1B8D65F67BA6C8FB53BBC49A74016275C272691C` nun ein 655-Rezensions-Tag hat (vgl. https://github.com/ubtue/DatenProbleme/issues/1308). Ist das in der Testdatenbank angekommen?
Die Problematik, warum die es noch "blaue" Records auf nu gibt, ist wohl davon unabhängig. Das werde ich noch einmal nachgehen.

**Comment by kdr154** [comment]
Die Daten von Social Justice sind komplett unverändert.

**Comment by jriedl** [comment]
Mysteriös. Die Datei wurde ja eingespielt, und gilt laut BSZ-FTP-Server auch als `loaded`. @socheres Gibt es da eine Erklärung im Zusammenhang mit M&M, bzw. kann das BSZ nachvollziehen, was da passiert ist?

**Comment by kdr154** [comment]
Ich habe zwei der Rezensionen zurückgesetzt. Werde es morgen überprüfen. Habe den Eindruck, dass das Match & Merge bei anderen Zeitschriften funktioniert hat. Zudem werden die Rezensionen auf nu getagt. Es sollte also funktionieren.

**Comment by kdr154** [comment]
Mit den beiden Rezensionen ist nichts geschehen. Der Status auf nu ist wie gestern "Reset" (blau)

**Comment by jriedl** [comment]
Beide Rezensionen wurden neu eingespielt (als `F0E01529C1AEAC6F6787389AB3FB7EC967D9BF31`  und `CA66D3A126A6A8AA6D7B2EAB7854A245330D0A80`). Dass der Reset-Status bei den ursprünglichen Records nicht geändert wurde, hängt wohl mit der zwischenzeitlich geänderten Crawl-URL-Bestimmung zusammen. Wir werden diese beiden Records manuell entfernen.

**Comment by jriedl** [comment]
Wurde die beiden in der Testdatenbank gelöschten Artikel letzte Woche korrekt eingespielt?

**Comment by kdr154** [comment]
? Sie schreiben doch, dass sie neu eingespielt wurden. Oder auf was beziehen Sie sich?

**Comment by jriedl** [comment]
Ja, von unserer Seite waren sie in den Daten dabei. Aber sind sie in der Testdatenbank korrekt angekommen? Wir scheinen ja das Problem zu haben, dass das Match & Merge Änderungen am 655-Feld nicht richtig behandelt. Deshalb die Frage, ob es zumindest bei den zwei manuell gelöschten Artikeln korrekt ist.

**Comment by kdr154** [comment]
Ich habe sie nicht gefunden.

**Comment by jriedl** [comment]
Ok, dann müssen wir dem auf BSZ-Seite nachgehen.

**Comment by socheres** [comment]
Die Anfrage läuft. Warte noch auf die Antwort von BSZ.

**Comment by jriedl** [comment]
Vgl. https://dialnet.unirioja.es/servlet/articulo?codigo=7457558

**Comment by socheres** [comment]
Rezensionen werden getaggt, daher kann dieses Issue geschlossen werden.

**Comment by kdr154** [comment]
Ok.
