### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Lizenzfrei

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1338]
https://ojs.ehu.eus/index.php/eguzkilore/index
Die Zeitschrift ist lizenzfrei. Ist in Zeder auch so hinterlegt. Siehe auch PPN 831875356:

![grafik](https://user-images.githubusercontent.com/29707105/105170566-65800500-5b1d-11eb-94e6-7a7edb4aa87d.png)

Die Aufsätze werden aber nicht als solche ausgegeben:

![grafik](https://user-images.githubusercontent.com/29707105/105170245-f1456180-5b1c-11eb-9d3a-d8d897d6b573.png)

**Comment by jriedl** [comment]
Test auf nu (tryCrawl): 856$z: LF (wie in der `zotero_harvester.conf` hinterlegt):
![image](https://user-images.githubusercontent.com/13135579/105173609-8f3b2b00-5b21-11eb-99d9-4a71c4262c54.png)

Scheinbar also ein Problem auf BSZ-Seite. @socheres Lässt sich das abklären?

**Comment by jriedl** [comment]
Nachtrag: Für diesen Artikel auch korrekt in `krimdok_zotero_210114_001.xml`.

**Comment by jriedl** [comment]
Nachtrag 2: Die PPN 831875356 existiert nicht in Krimdok. Es ist nur die Printausgabe mit PPN 170545342 vorhanden. Könnte das bitte jemand für Krimdok auszeichnen?

**Comment by kdr154** [comment]
Wo liegt dann der Fehler begründet?

**Comment by kdr154** [comment]
Nachtrag 2 verstehe ich nicht. Wenn ich die ePPN in Krimdok eingebe, bekomme ich das richtige Ergebnis. In Zeder ist sie ebenfalls eingetragen

**Comment by jriedl** [comment]
Nach aktuellem Stand die Daten auf unserer Seite korrekt. Es könnte also etwas beim Import auf BSZ-Seite schiefgelaufen sein. Es ist aber sicher, dass dieser Aufsatz durch uns das erste Mal letzte Woche eingespielt wurde und nicht schon irgendwie vorher vorhanden war?

**Comment by jriedl** [comment]
Zu Nachtrag 2: https://krimdok.uni-tuebingen.de/Search/Results?lookfor=ids%3A831875356&type=AllFields&limit=20&botprotect=

**Comment by kdr154** [comment]
![grafik](https://user-images.githubusercontent.com/29707105/105177050-649fa100-5b26-11eb-9528-a13cb2cc3761.png)
Ist aber sobek.

**Comment by jriedl** [comment]
Das liegt aber daran, dass die PPN der Onlineausgabe in 773 angegeben ist und deshalb eine Suche nach dieser PPN erfolgreich ist. Das Suchergebnis ist dennoch die Printausgabe (170545342) (auf sobek und ub15 identisch). Der Record selbst ist nicht vorhanden.

**Comment by kdr154** [comment]
Die Aufsätze wurden in der Nacht vom 14./15. eingespielt. Diesen Stand haben auch die Delivered Records-Einträge auf nu. Habe jetzt alle resetted.
Was das Nachtragen auf Krimdok betrifft, weiß ich nicht, wie man das macht.

**Comment by jriedl** [comment]
ad 1) Vielen Dank, vermute aber, dass sich nichts ändern wird, da es auf unserer Seite ja schon bei der Ursprungseinspielung korrekt war. Wahrscheinlich müssen wir auf eine Abklärung durch das BSZ warten.
ad 2) Ich vermute, dass ein Auszeichnen mit ssgn 2,1 ausreichen müsste (c.f. https://github.com/ubtue/tuefind/wiki/Daten-Abzugskriterien). Werde das an die Kriminologen weitergeben.

**Comment by kdr154** [comment]
ad 1)ist behoben. Die Aufsätze werden nun als lizenfrei eingespielt.

**Comment by jriedl** [comment]
Die Online-Ausgabe mit PPN 831875356 ist mittlerweile in Krimdok nachgewiesen: 
https://krimdok.uni-tuebingen.de/Search/Results?lookfor=ids%3A831875356&type=AllFields&limit=20&botprotect=

**Comment by kdr154** [comment]
Dann schließe ich
