### ISSUE TITLE
ISSN 2159-6808 Journal of Religion and Violence - Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#134]
Bei dieser ZS ist die Webseite eines Hefts in Sektionen unterteilt. Eine davon ist die Sektion Book Reviews. 
https://www.pdcnet.org/collection/show?id=jrv_2018_0006_0001_0145_0151&file_type=pdf
Der Abschnitt wird auf der Folgeseite weitergeführt, auch wieder überschrieben mit Book Reviews.
Alle vier Rezensionen, die der Feed enthält, sind hier aufgeführt
Die URL eines einzelnen Dokuments im Feed sieht so aus:
https://www.pdcnet.org/collection/show?id=jrv_2018_0006_0001_0145_0151&file_type=pdf
hier ist die Überschrift Book Review in der Vorschau enthalten
Zwar steht der Verfasser oder Herausgeber des rezensierten Werks immer nach einem Punkt am Ende des Titels, aber aus dem Titel eine Regel abzuleiten, die eine Rezension definiert, sehe ich in diesem Fall im Augenblick nicht.

**Comment by shadeMe** [comment]
> Zwar steht der Verfasser oder Herausgeber des rezensierten Werks immer nach einem Punkt am Ende des Titels, aber aus dem Titel eine Regel abzuleiten, die eine Rezension definiert, sehe ich in diesem Fall im Augenblick nicht.
Ich bin nicht sicher, ob das Muster stabil genug zum Umsetzen ist. Es ist nicht praktikabel, zu prüfen, ob die nachfolgenden Wörter den Name eines Verfassers/Herausgebers enthalten.

**Comment by shadeMe** [comment]
Gibt es sonst andere Muster?

**Comment by shadeMe** [comment]
@kdr154 Ist dieses Issue noch relevant? Kann es geschlossen werden?

**Comment by kdr154** [comment]
Es ist in jedem Fall kein eindeutiges Kriterium. Z. B. kann ja auch der Titel einen Punkt enthalten (Abkürzung eines Vornamens). An anderer Stelle in dieser ZS werden die Verfasser oder Editoren eines rezensierten Werkes eingeleitet mit der Wendung "By ..."
Auf der anderen Seite wäre es doch schön, wenn man da eine Lösung finden würde.
Stört es, wenn es geöffnet bleibt?

**Comment by shadeMe** [comment]
Mich stört es nicht persönlich aber es dient zu keinem Zweck, wenn wir damit sowieso nicht weitermachen können. In der Regel möchten wir Issues nur dann offen halten, wenn es daran gearbeitet wird. Von daher macht es Sinn, es zu schließen.

**Comment by kdr154** [comment]
Dann schließen wir es. Einen Zweck sehe ich schon. Die Erinnerung an ein noch nicht gelöstes Problem.
