### ISSUE TITLE
ISSN 1695-0194 | Revista electrónica de ciencia penal y criminología | Jahresangabe 936j und 264c

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1342]
http://criminet.ugr.es/recpc/index.html
Bei den geharvesteten Daten wird als Jahr immer 2021 ausgegeben. Was immer falsch ist.
Denn in der Einspielung vom 18./19. 1. befinden sich die Hefte 22.2020, 21.2019 und 20.2018

![grafik](https://user-images.githubusercontent.com/29707105/105204322-5496ba00-5b44-11eb-9031-264e45cb2a89.png)

![grafik](https://user-images.githubusercontent.com/29707105/105204381-637d6c80-5b44-11eb-92f4-81498a9995c2.png)

Auch wenn wir, wie wir es beschlossen haben, das Berichtsjahr zum Erscheinungsjahr machen, stimmt es in keinem Fall.

**Comment by jriedl** [comment]
Es gab ein Problem in der Übergabe des Jahres zwischen dem Translator und dem Harvester. Sollte auf nu jetzt behoben sein.

**Comment by kdr154** [comment]
Jetzt stimmt es.
