### ISSUE TITLE
ISSN 1888-0665 | Quadernos de criminología | Daten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1343]
Im Prinzip sehen die Daten gut aus. Zwei Dinge fallen mir auf:
Hier die Webseite: https://dialnet.unirioja.es/servlet/revista?codigo=12507
1. Ich frage mich, warum beim Crawlen das Heft 48.2020 ganz erfasst wird, dann 1 Artikel aus 49.2020 und 50.2020 gar nicht.
Wie kommt diese Auswahl zustande? Warum wird nicht alles erfasst.
2. Die Ansetzung spanischer Namen ist problematisch.
 Gemäß RDA-Toolkit:
![grafik](https://user-images.githubusercontent.com/29707105/105320814-ee06b000-5bc6-11eb-8a57-7a3048b59921.png)
müsste dei  diesem Aufsatz: https://dialnet.unirioja.es/servlet/articulo?codigo=7457558
der Verfasser wir folgt erfasst werden: Fuente, José Carlos Vilorio de la
In unseren Daten wird er anders erfasst:
![grafik](https://user-images.githubusercontent.com/29707105/105321233-7be29b00-5bc7-11eb-9289-59447410a6ef.png)
Ich sehe da zwei Möglichkeiten: 
Entweder wir nehmen solche Fälle beim vollautomatischen Verfahren in Kauf, oder
wir erstellen eine Regel, das wenn der Nachname eines Verfassers aus mehr als einem Wort besteht, wir diese Sätze manuell erfassen und nicht automatisch einspielen.

**Comment by jriedl** [comment]
ad 1) Dialnet ist relativ empfindlich im Bezug auf Anzahlen von Requests, die über menschliches "Surfen" hinausgehen und ist leider unserer Bitte, hier für uns die Bedingungen etwas aufzuweichen, nicht nachgekommen. Vermutlich hat es deshalb einfach mehrere Versuche/Tage gebraucht, bis das Crawling das "zusammengesucht" hat. Zumindest auf den ersten Blick sehen die zugehörigen Daten jetzt vollständig aus.

ad 2) Das spezielle Handling im Harvester für "de" ist wieder entfernt, lässt sich aber aber wegen 1) gerade nicht sinnvoll  testen und anpassen.

**Comment by kdr154** [comment]
ad 2) Kann man davon ausgehen, dass es entsprechend umgesetzt wird und die ZS auf "Ready for Production" setzen? Oder soll man noch warten?

**Comment by jriedl** [comment]
Bitte noch warten. Aktueller Stand ist auf nu eingespielt, eventuell sind aber noch weitere Anpassungen nötig.

**Comment by socheres** [comment]
In Zotero wird die Reihenfolge der Namen korrekt heruntergeladen: ` Fuente, José Carlos Vilorio de la` @jriedl an welcher Stelle im Code wird die Reihenfolge umgedreht?

**Comment by jriedl** [comment]
Im Harvester. Es wurde jetzt auch der zweite Teil der "Inversions"-Logik entfernt und auf nu eingespielt.

**Comment by kdr154** [comment]
Sieht so aus wie gewünscht
