### ISSUE TITLE
ISSN 1936-1351 | American journal of criminal justice | Zweifel an RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1345]
https://link.springer.com/journal/12103/volumes-and-issues
Hege Zweifel an einem funkionierenden RSS-Feed. Habe gestern alle Sätze dieser Zeitschrift auf nu resetted. Daran hat sich über Nacht nichts geändert.
Der Link zum Feed befindet sich auf einer Seite,  auf der die Latest Article angeboten werden und ist auch nur sichtbar, wenn man die Seite über View all Articles aufruft:
https://www.springer.com/journal/12103
https://link.springer.com/search?query=&search-within=Journal&facet-journal-id=12103
Dort sind dann die Artikel in der Reihenfolge ihres Erscheinens aufgelistet. Auf der Startseite zu sehen sind nur Latest Article, also solche, die keinem Heft zugeordnet sind.
Das erklärt möglicherweise, warum die Daten auf nu unberührt blieben.

**Comment by jriedl** [comment]
Scheint so zu sein. Bei einem lokalen Test lädt der Harvester zwar aktuell 20 Records aus dem RSS-Feed herunter, verwirft sie dann aber alle als "online-first". Da zum Teil Artikel mit gleichem Titel in der Status-Datenbank auf nu waren, wirkt es so, als hätte es Anpassungen am RSS-Feed gegeben und auch "ehemalige" Heftartikel werden jetzt nur noch ohne Heftzugehörigkeit verlinkt. Crawling bricht wegen der `robots.txt`-Regeln ab. Sind ähnlich gelagerte Fälle bekannt und wie war hier das Vorgehen?

**Comment by kdr154** [comment]
Mir ist nichts bekannt.

**Comment by jriedl** [comment]
Da der RSS-Feed nicht (mehr) geeignet ist, scheint als Möglichkeit nur, bei Springer anzufragen, ob sie uns in solchen Fällen das Crawlen offiziell erlauben. @socheres Wäre das möglich?

**Comment by jriedl** [comment]
Wie angesprochen, existiert nun ein Ansatz auf Grundlage der Springer-API. Dieser Ansatz ist momentan in `zotero_cgi` noch nicht herausgeführt. Da die Zugriffe an einen einzelnen Schlüssel gebunden sind (d.h. die zulässige tägliche Maximalananzahl der Requests bezieht sich auf Entwicklungs-, Test und Produktivsysteme gleichermaßen) und die Erstabfrage immer alle innerhalb der Zeitschrift erschienenen Artikel herunterlädt, ist der Ansatz für manuelle Tests eher ungeeignet. Ich werde deshalb den `zotero_type` für diese Zeitschrift von `RSS` auf `APIQUERY` ändern und die hinterlegten Online-First-Artikel dieser Zeitschrift auf nu löschen. Daten sollten dann ab morgen in der Testdatenbank zu finden sein.

**Comment by jriedl** [comment]
Wie sich zeigt, wird der Parameter `zotero_type` durch `zeder_to_zotero_importer` implizit gesetzt, d.h. die vorgenommene Änderung in der `zotero_harvester.conf` wurde wieder überschrieben. Es ist also wahrscheinlich doch erforderlich, das entsprechend in Zeder zu repräsentieren. Ich gehe dem nach.

**Comment by jriedl** [comment]
Als mittelfristig sauberste Lösung erscheint mir das Anlegen einer neuen Spalte in der IxTheo- und Krimdok-Instanz, z.B. `zot_api` hinter der rss-Spalte, die bei einem nicht-leeren Feld den `zotero_type` entsprechend anpasst.  Als aktueller Lösungansatz existiert nun eine Anpassung in `zeder_to_zotero_importer` die ein manuell eingetragenes `APIQUERY` vor einem Überschreiben schützt.

**Comment by thefass** [comment]
kann ich veranlassen.
Welcher Wert soll in die neue Spalte zot_api eintragbar sein?
Anders gefragt: soll es ein dropdown Feld werden mit vorgegebenen Werten oder ein freies Feld, wo etwas frei eingetragen werden kann, was auch immer

**Comment by jriedl** [comment]
Vielen Dank. Vermutlich haben wir mit einem beliebig beschreibbaren Feld mehr Freiheitsgrade, die sich zukünftig noch als nützlich erweisen könnten.

**Comment by kdr154** [comment]
Ich vermute dass am 8./9. 6. mit dem neuen Lösungsansatz die gesamte Zeitschrift, von Bd. 1 bis Bd. 46 eingespielt wurde. Dabei wurde für alle Aufsätze das Jahr 2021 gesetzt:

![grafik](https://user-images.githubusercontent.com/29707105/121901633-da4f1800-cd26-11eb-90b5-667b7dbfb899.png)


![grafik](https://user-images.githubusercontent.com/29707105/121901818-07032f80-cd27-11eb-8e15-ed7693edc9e0.png)

**Comment by jriedl** [comment]
Ja, genau: Um den erneuten Download von hunderten Artikeln zu vermeiden, habe ich dieses Problem behoben, aber nur ein paar Artikel manuell auf nu resettet. Das sind die "grünen" Einspielungen vom 11.6.. Für einen erneuten Kompletttest müsste alles resettet und in der Testdatenbank gelöscht werden.

**Comment by kdr154** [comment]
Einen Fehler gibt es aber noch. Hefte mit doppelten Heftnummern:
So fehlt etwa das gesamte Heft 34.2009,1-2.
In den Error-Files wird auf einen Regex-Mismatch verwiesen:

 
![grafik](https://user-images.githubusercontent.com/29707105/122021216-c3abce00-cdc5-11eb-94b6-745471afdf24.png)

**Comment by jriedl** [comment]
Behoben

**Comment by kdr154** [comment]
Kann man schließen?

**Comment by jriedl** [comment]
Im Prinzip ja, aber bitte erst nach dem nächsten Update auf ub28 live setzen.
