### ISSUE TITLE
Allgemein: Global Config greift nicht

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1346]
**URL**
https://doi.org/10.1163/15697312-01404013
Zs=Jorunal of reformed theology

**Ausführliche Problembeschreibung**
Das Editorial wird beim Testen auf Nu mit TRY URL oder auch mit TRY RSS nicht ausgeschlossen. Gebe ich als Additional config aber die Zeile aus der Harvester Conf ein:
`exclude_if_marc_field_245a                 = (?i)^((Editorial)|(Guest\s+Editorial)|(From\s+the\s+Editor(s?))|(Introduction)|((Front|Back)\s+Matter)|(Issue\s+Information)|(Books\s+(Received|Reviewed))|(Book\s+Reviews)|(About\s+This\s+Issue)|(Editor’s\s+notes)|(From\s+The\s+Editor\Ws\s+Desk\s?)$|(Indexes\s+Vol\W))`
wird es ausgeschlossen.

Demnach scheint hier etwas nicht zu stimmen.
Warum wird das Editorial nur ausgeschlossen, wenn ich explizit die Zeile in die Additonal conf beim Testen reinkopiere?

**Comment by kdr154** [comment]
Kann ich bestätigen. Scheint ab der Einspielung 19./20. 1. der Fall gewesen zu sein.

**Comment by IxKo** [comment]
Ich habe nun eine schließende Klammer in der Zeile ergänzt und beobachte/prüfe morgen, ob es daran lag.

**Comment by jriedl** [comment]
Die fehlende Klammer war die Ursache. Durch einen Fehler im Code wurde hier bei einem ungültigen regulären Ausdruck bislang allerdings nicht sofort abgebrochen. Das ist jetzt behoben und sollte in Kürze auf nu sein.

**Comment by IxKo** [comment]
Config scheint in diesen Fällen wieder zu greifen. Die genannten Datensätze sind heute nicht aufgetaucht.
