### ISSUE TITLE
ISSN 2044-8333 | Legal and criminological psychology | Fehlende Seitenzahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1348]
Bei diesem Artikel: https://bpspsychub.onlinelibrary.wiley.com/doi/10.1111/lcrp.12178 werden keine Seitenzahlen 936 $h erfasst:
![grafik](https://user-images.githubusercontent.com/29707105/105699742-23353a00-5f08-11eb-87dd-ed366263ed5b.png)
Bei allen anderen Aufsätzen von diesem Heft https://bpspsychub.onlinelibrary.wiley.com/toc/20448333/2021/26/1 aber schon.

![grafik](https://user-images.githubusercontent.com/29707105/105699947-6becf300-5f08-11eb-86fe-2192acd54ef6.png)

Wie kommt diese Ausnahme zustande.

**Comment by hlindeboom** [comment]
Die Änderungen wurden auf nu eingespielt, die Seitenzahlen sollten nun erfasst werden.

**Comment by kdr154** [comment]
Seitenzahlen jetzt auch bei dem genannten Artikel
