### ISSUE TITLE
ISSN 1350-7303 Reviews in religion and theology - Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#135]
Das scheint, wie der Titel schon sagt, eine reine Rezensionszeitschrift zu sein.
Außer der Einträgen Issue Information und RRT 25.4 (October 2018) sehe ich in diesem Feed nur Rezensionen.
Hier enthält sowohl der Link zur URL als auch der Titel auf der Webseite: https://onlinelibrary.wiley.com/doi/abs/10.1111/rirt.13391?af=R
die ISBN des rezensierten Werks.

Die ersten beiden Einträge, RRT 25.4 (October 2018), sollte man in diesem Fall auf jeden Fall verwerfen, den 3., Issue Information, könnte man auch.

**Comment by shadeMe** [comment]
@kdr154 Ich habe gerade mehrere Issues auf 'ready for testing" gesetzt.

**Comment by kdr154** [comment]
gelöst
