### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Überschriften

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1350]
Bei dieser Zeitschrift scheinen mir die Kapitelüberschriften "Editorial" und "Articulos" als der Titel des daruter folgenden Aufsatzes interpretiert zu werden, so dass dieser ausgeschlossen wird:
https://reic.criminologia.net/index.php/journal/issue/view/21

![grafik](https://user-images.githubusercontent.com/29707105/105706348-b6bf3880-5f11-11eb-822f-a3759f5dcf1a.png)

Wobei in folgendem Fall die URL im Delivered Records File nicht mit dem Main title übereinstimmt:

![grafik](https://user-images.githubusercontent.com/29707105/105706579-043ba580-5f12-11eb-99c8-b7d01ef732bc.png)

**Comment by jriedl** [comment]
Das war etwas tricky: Der dahinterliegende Translator (Open Journal Systems Multiwrapper) hat die Links mit den "Ähnlichen Artikeln" extrahiert und sich damit wieder selbst aufgerufen, womit eine ganze Kaskade an Abfragen ausgelöst wurde und der Harvester das Ergebnis dann in den konkreten beiden Fällen infolgedessen wegen einer unerwarteten multiple-Antwort verworfen hat. Einzelne OJS-Artikel werden jetzt schon über den Translator-Kandidaten-Regex auschlossen. Angepasste Version ist auf nu. Wegen der resetteten Artikel bitte morgen noch einmal überprüfen.

**Comment by jriedl** [comment]
Die beiden reset-Artikel sind jetzt "grün".

**Comment by kdr154** [comment]
wurden nun korrekt eingespielt.
