### ISSUE TITLE
ISSN 1043-1578 | Social Justice | Test 25./26. 01 erfolgreich

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1351]
Die Aufsätze, die geteset werden sollten, sind eingespielt worden, auch mit dem Rezensionstag.

**Comment by jriedl** [comment]
Umd die in der Luft hängenden Abstract/Editorial-Einträge loszuwerden, wurden jetzt auf nu für die Zeitschrift alle "gelben" Einträge gelöscht. Morgen sollten also dann nur noch die "echten" Aufnahmekandidaten auf nu vorkommen. Allgemein wäre mein Vorschlag für diese Zeitschrift, sie im Anschluss (also voraussichtlich Anfang nächster Woche) auf live zu setzen und die Records ohne 100-Feld auf manuelle Einspielung zu setzen. So könnte man diese nachziehen, falls tatsächlich eine Einspielung gewünscht ist.

**Comment by kdr154** [comment]
Schade, dass sie schon gelöscht sind. Denn in meiner Erinnerung entspricht nicht alles, was dort als Abtract betitelt wurde nicht dem, was wir landläufig unter einem Abstract verstehen.
Es waren auch ziemlich viele, die gelb waren. Ein anderer Weg wäre, dass man bei dieser Zeitschrift 100 auf sometimes setzt, also alles einspielt, und im Nachhinein die aus der Winibw wieder herausnimmt, die man nicht haben will. Das sollte aber von jemanden aus der Krimiologie gemacht werden. 
Das ist aber auch bei der vorgeschlagenen Vorgehensweise der Fall. Also können wir aus meiner Sicht so vorgehen, wie vorgeschlagen.

**Comment by jriedl** [comment]
Durch die Löschung sollten  nur die Einträge verschwinden, die zwischendurch reingekommen sind, weil der Ausschluss-Regex der `zotero_harvester.conf` nicht gegriffen hat und die bei einer Einspielung auf ub28 ohnehin nicht auftauchen würden und auch auf nu nicht sein sollten. Der Rest sollte morgen wieder auf nu sichtbar sein (deshalb ein Live-Setzen bitte erst im Anschluss an einen nächsten Lauf auf nu -  ansonsten würde nu die Zeitschrift ja gar nicht mehr beachten).

**Comment by jriedl** [comment]
Nichtausgeschlossene Records ohne MARC 100 Feld mittlerweile wieder auf nu. Allerdings sind immer noch einige Titel dabei, die nur knapp an den in den globalen Ausschlusskriterien in `zotero_harvester.conf` vorbeigehen (z.B. "Editors' Note", Editors' Introduction"), daneben "Abstracts". Spricht etwas dagegen, diese Ausdrücke in das globale `exclude_if_marc_field_245a` mit aufzunehmen?

**Comment by kdr154** [comment]
Spricht  nichts dagegen. Bitte mit aufnehmen.

**Comment by kdr154** [comment]
Habe Editor' note und Abstracts mit aufgenommen. Editors' Introduction hat noch einen Zusatz und  ist somit ein eigenständiger Titlel.

**Comment by jriedl** [comment]
Ah, ok, danke - habe die entsprechenden Records jetzt noch einmal entfernt, so dass wir morgen das Ergebnis sehen sollten.

**Comment by jriedl** [comment]
Offensichtlich  ungeeigenete Titel wurden ausgeschlossen. #1351 scheint ja auch behoben. Vermutlich könnten wir dann mit dieser Zeitschrift auch live gehen. Nach dem ersten Live-Upload müssten nur die "gelben" Einträge auf manuelle Auslieferung gesetzt werden.

**Comment by kdr154** [comment]
Ist ub28 aktuell? Wenn ja, setze ich diese ZS auch auf live.

**Comment by jriedl** [comment]
Ja, gestern war ja das Update und die letzte diese Zeitschrift betreffende Änderung war ja die Anpassung gestern an der `zotero_harvester.conf`, die abends ohnehin automatisch eingespielt wird.

**Comment by kdr154** [comment]
Jetzt live.
