### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Reset 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1353]
Der folgende Aufsatz https://reic.criminologia.net/index.php/journal/article/view/161 wurde gestern nicht ausgeliefert, weil keine Sprache ausgegeben wurde. Habe daraufhin die Spracheinstellungen in Zeder in spr und sprz ergänzt und den Artikel auf nu zurückgesetzt.
Ein Test mit TryURL zeigt, dass die Änderungen gewirkt haben. Es wird jetzt eine Sprache ausgegeben:
![grafik](https://user-images.githubusercontent.com/29707105/105821332-03ab1980-5fbb-11eb-8cf9-aea1e8e20c82.png)

Dennoch wird der Satz bei der Einspielung heute nicht wieder aufgegriffen, sondern mit dem Reset-Datum von gestern so belassen:

![grafik](https://user-images.githubusercontent.com/29707105/105821619-58e72b00-5fbb-11eb-96c5-c00c277f21ec.png)

Hätte der Artikel nicht heute nacht eingespielt werden sollen?

**Comment by jriedl** [comment]
Das Problem scheint zu sein, dass dieser Artikel mit den aktuellen Crawling-Einstellungen gar nicht mehr gefunden wird: Der Einsprungspunkt ist `https://reic.criminologia.net/index.php/journal`, hier wird dann die aktuelle Ausgabe gesucht, und in dieser den der Ausdruck `\/journal\/article/view/\d+$` ausgewertet. Hier existiert der Artikel allerdings nicht mehr - er taucht zum letzten Mal am 20.1. in den Download-Dateien auf, danach scheint die Umstellung stattgefunden zu haben. Zum Testen müsste also ein Artikel verwendet werden, der Teil der aktuellen Ausgabe ist.

**Comment by kdr154** [comment]
gemacht

**Comment by kdr154** [comment]
war erfolgreich
