### ISSUE TITLE
ISSN 1477-8351 | Aramaic studies (Brill (allgemein), Test) |  Titelzusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1354]
**URL**
IxTheo#2021-01-14#7E76AD5E87B76900773FC447BABC814D33BADC2C
https://doi.org/10.1163/17455227-bja10012
![image](https://user-images.githubusercontent.com/57000004/105825338-c5fcbf80-5fbf-11eb-8d13-b9cd276c0d13.png)

IxTheo#2021-01-14#4CA7AA5C82DE1D160064FD19259CA82F4B89E58B
https://doi.org/10.1163/17455227-bja10014
![image](https://user-images.githubusercontent.com/57000004/105825216-a36aa680-5fbf-11eb-925d-9a4ccf88a767.png)

**Ausführliche Problembeschreibung**
Die Titelzusätze werden nicht korrekt mit $d getrennt.
Betrifft auch alle anderen Brill-Zss!

**Comment by socheres** [comment]
Im Zotkat Titelzusätze ohne $d einspielen.

**Comment by IxKo** [comment]
Zotkat ist das semi-automatische Verfahren. 
Meinten Sie Zotaut? Falls ja und dies ist so mit allen Verantwortlichen geklärt, kann das Issue geschlossen werden.

**Comment by socheres** [comment]
Sorry, ich meinte Zotaut.

**Comment by IxKo** [comment]
Okay, dann würde ich schließen.
Gibt es denn einen Grund, warum der Doppelpunkt nicht zum Trennzeichen umgewandelt werden soll?

**Comment by socheres** [comment]
$d wird in Vufind bei der Anzeige in Doppelpunkt umgewandelt, daher ist es unergiebig. Siehe auch https://github.com/ubtue/tuefind/issues/1112
Außerdem wird Doppelpunkt nicht immer als Trennelement für Untertitel benutzt.

**Comment by IxKo** [comment]
Okay, danke, dann schließe ich.
