### ISSUE TITLE
ISSN 1570-0585  Arabica (Brill, Test) | Doppelheft-Zählung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1355]
**URL**
IxTheo#2021-01-14#890DB9183BF55BEC31F33A884EC43D2BDCFB059E
https://doi.org/10.1163/15700585-12341579
![image](https://user-images.githubusercontent.com/57000004/105826898-951d8a00-5fc1-11eb-889c-a7529a8ae29c.png)

**Ausführliche Problembeschreibung**
Die Doppelheft-Zählung sollte mit Schrägstrich (5/6) getrennt werden und nicht mit Bindestrich.

**Comment by socheres** [comment]
auf benu behoben.
```
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">In: </subfield>
<subfield code="t">Arabica : journal of Arabic and islamic studies</subfield>
<subfield code="x">1570-0585</subfield>
<subfield code="w">(DE-627)341356859</subfield>
<subfield code="g">67 (2020), 5/6, Seite 644-647</subfield>
</datafield>
```

**Comment by IxKo** [comment]
Ok

**Comment by IxKo** [comment]
Halt, sollte es nicht aber auch auf Nu korrigiert werden? 
Dort sieht es noch nicht danach aus (TEST mit Try RSS)
![Uploading image.png…]()
:

**Comment by kdr154** [comment]
Die neueste Mail von @jriedl bezog sich auf die QS-Settings.
Sollen wir besser auf ub28 testen? Das ist doch wohl kaum eine gute Lösung?

**Comment by IxKo** [comment]
Benu ist doch die Entwickler-Umgebung für @socheres.
Da es dort gestern auf wohl schon gut aussah, bin ich davon ausgegangen, dass die Änderung über Nacht auch auf Nu greift. Scheint aber nicht so zu sein.

Die Frage ist, wann Änderungen in Benu auf Nu übergehen.

**Comment by kdr154** [comment]
Sorry, daran habe ich nicht mehr gedacht.

**Comment by IxKo** [comment]
Ich zuerst auch nicht :-)

**Comment by kdr154** [comment]
Na gut. Dort wird es jedenfalls auch für Pneuma korrekt verarbeitet.

**Comment by socheres** [comment]
Wenn es soweit ist, dann vergebe ich das Label "ready for testing".

**Comment by jriedl** [comment]
Aktueller Translator-Stand ist auf nu.

**Comment by IxKo** [comment]
Behoben
