### ISSUE TITLE
ISSN 1945-1369 | Journal of drug issues | Orcid 3-fach

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1356]
Wie bereits in #1326 thematisiert.
Dieses Phänomen gibt es auch hier, ebenfalls Sage:
https://journals.sagepub.com/doi/full/10.1177/0022042620971857

![grafik](https://user-images.githubusercontent.com/29707105/105827692-969b8200-5fc2-11eb-9689-d9be0b86203f.png)

**Comment by jriedl** [comment]
Dreifache Orchid vorhanden in `krimdok_zotero_201221_001.xml` und `krimdok_zotero_210112_001.xml`. Ein Test mit TryURL und obigem Artikel auf nu liefert allerdings nur noch ein MARC 887-Feld. Scheinbar also auf unserer Seite behoben. Der Artikel ist noch Teil des RSS-Feeds, Problem müsste sich also durch Reset und Löschen in der Testdatenbank beheben lassen.

**Comment by jriedl** [comment]
Nachtrag: Problem nicht behoben, da mit tryRSS reproduzierbar.

**Comment by kdr154** [comment]
Ok. Aber es wurde wie gesagt bereits in #1326 diskutiert und konnte dort noch nicht abschließend gelöst werden. Das Problem tritt soweit ich sehe nur bei Sage auf. Dann mache ich erst mal nichts.

**Comment by jriedl** [comment]
Da muss auf jeden Fall der Code angefasst werden. Kümmere mich darum.

**Comment by jriedl** [comment]
Ursache ist offenbar ein Problem der Elementextrakion in den Bibliotheken hinter `querySelectorAll` und `ZU.xpath` und tritt nur in bestimmten Kontexten auf. Als Workaround werden die `item.notes` zukünftig dedupliziert. Sollte auf nu behoben sein.

**Comment by kdr154** [comment]
Hier tritt es nicht mehr auf:

![grafik](https://user-images.githubusercontent.com/29707105/106017212-84a00900-60c0-11eb-8666-1b8608009faf.png)

**Comment by kdr154** [comment]
Dann könnte ich doch die SAGE-Zeitschrift der KrimDok live schalten? Wenn ja, dann morgen.

**Comment by jriedl** [comment]
Im Prinzip kann man die Änderung morgen auf ub28 einspielen und die (SAGE-)Zeitschriften live nehmen, wenn wir ganz vorsichtig sind, warten wir bis Montag.

**Comment by jriedl** [comment]
ub28 ist jetzt auf dem aktuellen Stand.

**Comment by kdr154** [comment]
Auf nu auch korrekt. Dann setze ich diese Zeitschrift auch auf zota

**Comment by socheres** [comment]
> Ursache ist offenbar ein Problem der Elementextrakion in den Bibliotheken hinter `querySelectorAll` und `ZU.xpath` und tritt nur in bestimmten Kontexten auf. Als Workaround werden die `item.notes` zukünftig dedupliziert. Sollte auf nu behoben sein.

@jriedl An welcher Stelle hast du Änderung vorgenommen? Am Harvester oder Translator? Außerdem was bedeutet hier Deduplikation?  Greif sie auch bei mehr als 2 UNTERSCHIEDLICHEN ORCIDs?

**Comment by jriedl** [comment]
Das bedeutet, dass identische Einträge, die mehrfach vorhanden sind, am Ende nur einmal vorkommen. Also genau der hier vorliegende Fall. Unterschiedliche ORCIDs sind unterschiedlich, fallen deshalb nicht unter die Definition und sind davon nicht betroffen.

**Comment by socheres** [comment]
Da ich den Fehler mit 3-fachen ORCIDs nicht reproduzieren konnte  #1326, ist es nicht ganz nachvollziehbar; aber wie du oben beschreibst, tritt das Problem nur in einem bestimmten Kontext auf. Was auch das sein mag. Dann schließe ich das Issue.

**Comment by jriedl** [comment]
Mit Abfragen einzelner Artikel und in Zotero war es nicht reproduzierbar, mit Abfragen kompletter Zeitschriften recht zuverlässig und dann schon als Rückgabe aus dem `querySelectorAll`-Aufruf.
