### ISSUE TITLE
Informit Translator ISSN, DOI, Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#136]
Für die Plattform Informit würde es ebenfalls Sinn machen, einen Translator zu schreiben. Die Daten von dieser Plattform scheinen mir sehr einheitlich zu sein.
Beispiele:
Ein Aufsatz:
https://search.informit.com.au/documentSummary;dn=800671128493482;res=IELHSS
hier fehlt der DOI und die ISSN
ein anderer: 
https://search.informit.com.au/documentSummary;dn=480145794388018;res=IELHSS
hier fehlen die Keywords, die ISSN und der DOI
Die Hauptseite einer Zeitschrift sieht so aus:
https://search.informit.org/browseJournalTitle;res=IELHSS;issn=0815-3094

Die Abstract kommen in den Beispielen, die ich getestet habe, mit.
Was fehlt ist die ISSN, der DOI und die Keywords

**Comment by shadeMe** [comment]
Ich habe einen neuen Translator angelegt (Name: ubtue_Informit.js), der die ISSN, DOI, usw extrahiert.

**Comment by kdr154** [comment]
Sieht gut aus! Danke
