### ISSUE TITLE
ISSN 2066-2203 | European journal of probation | Orcid 3-fach Sage

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1360]
Auch bei diesem Artikel auf Sage: https://journals.sagepub.com/doi/full/10.1177/2066220320976101 wird eine Orcid 3-fach ausgegeben:

![grafik](https://user-images.githubusercontent.com/29707105/105840640-a1aade00-5fd3-11eb-9018-38aa18a2fce8.png)

**Comment by jriedl** [comment]
vgl. #1356

**Comment by kdr154** [comment]
Bei diesem Titel tritt es nicht mehr auf:

![grafik](https://user-images.githubusercontent.com/29707105/106016877-33901500-60c0-11eb-9b42-13580181c5ba.png)
