### ISSUE TITLE
ISSN 2340-0080 | Estudios penales y criminologicos | Orcid

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1361]
Bei einigen Artikel dieser Zeitschrift besitzen die Verfasser eine Orcid. Z.B. bei diesem hier:
https://revistas.usc.gal/index.php/epc/article/view/6503
Der Harvester scheint sie zu erkennen, jedoch als fehlerhaft zu verwerfen. Möglicherweise wird sie deshalb nicht ausgegeben. Im CLI-Output steht: custom field '8873 aorcid: %orcid% | taken from website2ixzom' has missing values for placeholder '%orcid%'

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Orcid wird erfasst
