### ISSUE TITLE
ISSN 2254-2043 | Boletín criminológico | Lizenzfrei

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1362]
http://www.boletincriminologico.uma.es/boletines.php
Ist lizenzfrei, steht so in Zeder und auch als solche erfasst, vom BSZ aber nicht umgesetzt. 
Vgl. #1357, #1352, #1344, #1338, #1363

**Comment by jriedl** [comment]
Wohl behoben.

**Comment by kdr154** [comment]
behoben
