### ISSUE TITLE
0040-5701 | Theologische Zeitschrift (Basel, E-Periodica) | URL aus DOI

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1366]
**URL**
https://www.e-periodica.ch/digbib/view?pid=thz-001%3A1945%3A1%3A%3A4

**Ausführliche Problembeschreibung**
Diese Zs soll retro-katalogisiert werden.
Es werden zwar die DOIs übertragen, aber in die WinIBW wird der DOI nicht in 4950 aufgelöst. Aber nur in diesem Feld kann die Lizenzinformation "kostenfrei" eingetragen werden.

**Offenbare Lösungen**
Ist es möglich, dass automatisch das Feld 4950 https://doi.org/[DOI] aus der DOI erzeugt wird?
Andernfalls ist es etwas umständlich, dies manuell einzutragen - zumal bereits die letzte Seitenzahl ermittelt und manuell werden muss.

**Comment by socheres** [comment]
url und doi wird erzeugt.

**Comment by IxKo** [comment]
Es wird zwar nicht der DOI aufgelöst, aber die "normale" URL wird angegeben (bspw.: https://www.e-periodica.ch/digbib/view?pid=thz-001%3A1945%3A1%3A%3A24).
Dadurch wird 4950 erzeugt mit $4LF.
Danke.
