### ISSUE TITLE
ISSN 2413-3108 | South African crime quarterly | Quelle

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1368]
Beim aktuellen Harvesting greift der Harvester offensichtlich auf Sabinet als Quelle zu.
https://journals.co.za/journal/iscrime?page=previous-issues

Diesen Eindruck habe ich, wenn ich mir die URLs im Protokoll auf nu anschaue:
![grafik](https://user-images.githubusercontent.com/29707105/106103253-f0c25180-6140-11eb-8cc3-2b371329c21c.png)

Beim Harvesting vom letzten Jahr 1. 10. 2020, 28.09.2020 ... wurde diese Seite als Quelle benutzt:
https://journals.assaf.org.za/index.php/sacq/issue/archive

Damals wurden die Daten eingespielt:
![grafik](https://user-images.githubusercontent.com/29707105/106103884-e81e4b00-6141-11eb-9a9d-5dbd7ebd02e7.png)

Während die aktuelle Einspielung daran scheitert, dass keine Sprache erfasst wird. 

Wenn man die Zeitschrift mit der alten Quelle testet, ist das aber der Fall:
![grafik](https://user-images.githubusercontent.com/29707105/106104291-8dd1ba00-6142-11eb-98e3-86853119fb1c.png)
Worauf ist der Wechsel der Quelle zurückzuführen? Zumal in Zeder die alte Quelle in p_zot2 steht, Sabinet aber in url2. In url1 steht darüber hinaus noch eine weitere Quelle, die, wenn man die benutzt, aber auch nur auf die alte Quelle, also die in p_zot2 führt. Allerdings ist dort das aktuelle Heft nicht gelistet:
https://issafrica.org/research/south-african-crime-quarterly

In einem Fall steht in dem Protkoll sogar ein Eintrag zu einem Aufsatz, der zu einer anderen Zeitschrift gehört:

![grafik](https://user-images.githubusercontent.com/29707105/106106310-a2fc1800-6145-11eb-8d10-6df449d92ccd.png)

http://ref.scielo.org/qh2n8h

Ich nehme deshalb diese Quelle aus url1 heraus, setze die aus p_zot2 hinein und resette die Daten auf nu.

**Comment by jriedl** [comment]
Laut einer alten lokalen Version der `zotero_harvester.conf` war die alte URL im September letzten Jahres noch als  `zotero_url` eingetragen, im November aber bereits die neue. Vermutlich wurde es in Zeder geändert.

**Comment by jriedl** [comment]
In der aktuellen `zotero_harvester.conf`steht immer noch `https://journals.co.za/content/journal/iscrime/browse?page=previous-issues`. Das scheint mit einer unterschiedlichen Priorität im Bezug auf die URL-Extraktion in `zeder_to_zotero_importer` zusammenzuhängen (es wird das erste nichtleere Feld verwendet):

* Für IxTheo ist die Reihenfolge:  `rss` `p_zot2` `url2` `url1`.
* Bei Krimdok: `rss` `url2` `p_zot2` `url1`.

Gründe für dieses Verhalten sind mir nicht bekannt.

**Comment by jriedl** [comment]
Die letzten Einspielungen im Mai sehen auf den ersten Blick auf nu gut aus.

**Comment by kdr154** [comment]
Sehen gut aus, bis auf die Orcid, die fehlt (sowohl auf nu als auch in der Winibw):
https://journals.assaf.org.za/index.php/sacq/article/view/7744

![grafik](https://user-images.githubusercontent.com/29707105/123961367-8e4fd480-d9b0-11eb-87a7-ee9ba4608b81.png)

**Comment by jriedl** [comment]
Schaue es mir ASAP noch einmal an.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Orcid nun auch enthalten.
