### ISSUE TITLE
ISSN 2157-6475 | International journal of comparative and applied criminal justice | Nur ein Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1369]
Von diesem Heft: https://www.tandfonline.com/toc/rcac20/45/1?nav=tocList wird nur der erste Artikel geharvestet und eingespielt. Warum?
Alle älteren, im letzten Jahr eingespielten, waren gelöscht, so dass sich kein Aufsatz von der Online-Ausgabe mehr in der Testdatenbank befunden hat.

**Comment by jriedl** [comment]
"delivered-at"  für die anderen ist schon älter und der Status der grün, so dass das System davon ausgeht, dass alles bereits korrekt geliefert wurde. Wurden die Records eventuell nur in der Testdatenbank gelöscht, aber auf nu nicht resettet?

**Comment by kdr154** [comment]
Das wirds wohl sein. Die wurden damals als Latest Article geharvestet

**Comment by kdr154** [comment]
Heute wurden alle Sätze des aktuellen Hefts eingespielt.
