### ISSUE TITLE
Sage ISSN 1556-9330 Youth Violence and Juvenile Justice  ungültige Seitenangabe bei First Online Aufsätzen in 936 h

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#137]
Offensichtlich wird bei den First Online Aufsätzen in 936 h ein Teil des DOI als Seitenangabe übernommen.
z. B. steht in 936 folgendes:
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="h">1541204018804870</subfield>
<subfield code="j">2018</subfield>
</datafield>
```
und in 024:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10.1177/1541204018804870</subfield>
<subfield code="2">doi</subfield>
</datafield>
```
Die Webseite aufgerufen über den Feed ist folgende:
https://journals.sagepub.com/doi/abs/10.1177/1541204018804870

Das Problem zeigt sich auch bei anderen von Sage publizierten Onlinezeitschriften, etwa bei:
Theoretical Criminology ISSN 1461-7439

**Comment by mtrojan-ub** [comment]
Scheint ein Translator-Problem zu sein
![grafik](https://user-images.githubusercontent.com/26873381/49745699-db0f1b00-fc9f-11e8-8869-8f4f327bc229.png)

**Comment by shadeMe** [comment]
Gefixt.

**Comment by kdr154** [comment]
Gelöst
