### ISSUE TITLE
ISSN 0973-5089 | International journal of criminal justice sciences | Autoren (live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1371]
http://www.sascv.org/ijcjs/

Bei einem und nur bei diesem Artikel klappt die Interpretation der Verfasser nicht:

Auf der Seite sieht es so aus: Ilya N Mosechkin & Vladimir Y. Krukovskiy

Umgesetzt wird es wie folgt:

![grafik](https://user-images.githubusercontent.com/29707105/106565942-e1bc1480-652f-11eb-81ac-360d363b2004.png)

auch bei diesem Aufsatz ist die Verfasserangabe fehlerhaft. Der zweite wird nicht richtig erfasst, statt dessen ein weiteres 3010 ausschließlich mit Beziehungskennzeichen (in den eingespielten Daten bereits korrigiert):

![grafik](https://user-images.githubusercontent.com/29707105/106589450-543aed80-654c-11eb-82c6-4b5ffe278b6a.png)

**Comment by jriedl** [comment]
Für den konkreten Fall wäre der Vorschlag, dass man das manuell korrgiert. Werde den Translator für zukünftige Fälle anpassen. Für das, wie ich gerade oben im Bild sehe, fehlerhafte DOI-Handling mache ich ein eigenes Issue auf.

**Comment by jriedl** [comment]
Fix auf nu.

**Comment by kdr154** [comment]
Der 2. Fall, der mir noch aufgefallen ist, s. o., ist noch nicht gefixt.

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
Eventuell Überschneidung mit einem Update vorhin. Test gerade war erfolgreich.

**Comment by kdr154** [comment]
gefixt.
