### ISSUE TITLE
ISSN 0210-9700 | Eguzkilore | Autor (live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1372]
https://ojs.ehu.eus/index.php/eguzkilore/index

Hier haben wir es wieder mit einem Problem spanischer Namen zu tun. "Hikal Carreón" ist der Nachname. Umgesetzt wird er wie folgt:

![grafik](https://user-images.githubusercontent.com/29707105/106567429-1a5ced80-6532-11eb-8492-aa13142677e2.png)

Ihn mit Hikal beginnen zu lassen, wäre schon besser. Siehe etwa folgende Seite:

https://scholar.google.com.mx/citations?user=xAOI0yAAAAAJ&hl=es

**Comment by jriedl** [comment]
Solange es keinen klaren, algorithmisierbaren Kriterienkatalog gibt, der für alle Fälle greift (auch im Hinblick darauf, in welchen Formen die Daten von Zotero geliefert werden), bleibt das ein dauerhaftes Herumschrauben, wo mit jedem Hinzufügen und wieder Herausnehmen irgendwas wieder nicht passt. Wir brauchen hier einen Ansatz der dauerhaft trägt.

**Comment by jriedl** [comment]
Die bereits implementierte Namensinversion, die wir im Zusammenhang mit https://github.com/ubtue/DatenProbleme/issues/1343 wieder rausgeworfen haben, wurde jetzt in leicht veränderter Form wieder integriert. Um das korrekte Präpositionshandling bie "Quadernos.." zu erhalten, werden die Fälle, in denen bereits korrekt ist, vom Umschreiben explizit ausgenommen.

**Comment by kdr154** [comment]
Der  in Issue angespochen Fall "Hikal" auf nu nun richtig umgesetzt
