### ISSUE TITLE
ISSN 0973-5089 | International journal of criminal justice sciences - DOI

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1373]
Die DOI-Einträge (vgl. MARC 024) haben ein http-Präfix, was zu einer fehlerhaften Ausgabe in MARC 856 führt.

**Comment by jriedl** [comment]
Auf nu. Vorgehen im Bezug auf bereits produktiv eingespielte Daten müsste besprochen werden.

**Comment by socheres** [comment]
Wie sollte der Link genau aussehen?  Kannst du bitte ein Beispiel geben?

**Comment by jriedl** [comment]
Fehler erkennbar in https://user-images.githubusercontent.com/29707105/106565942-e1bc1480-652f-11eb-81ac-360d363b2004.png Feld 4950 und wohl auch 2051. Falls möglich, müsste man mit einem Skript hier jeweils `http://dx.doi.org/` entfernen.

**Comment by kdr154** [comment]
Auf nu korrekt. Die bereits eingespielten Daten korrigiere ich.
