### ISSUE TITLE
ISSN 1552-6518 | Journal of interpersonal violence | Doppelheft (Sage, Live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1374]
https://journals.sagepub.com/toc/jiva/36/1-2
Doppelhefte sollten mit Schrägstrich "/" angegeben werden und nicht mit Bindestrich "-"

Etwa hier: 

![grafik](https://user-images.githubusercontent.com/29707105/106855517-52dd0280-66bd-11eb-8e35-887aec31f49c.png)

![grafik](https://user-images.githubusercontent.com/29707105/106855592-743dee80-66bd-11eb-9c4d-2b8c6bfc3ad4.png)

Die eingespielten Daten korrigiere ich

**Comment by socheres** [comment]
@jriedl könntest du nach pull request merge in master das Label "ready for testing" vergeben?

**Comment by jriedl** [comment]
Änderung auf nu eingespielt.

**Comment by kdr154** [comment]
auf nu mit TryURL nun richtig,
