### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Verfasser nicht erfasst

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1375]
Bei diesem Heft https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/vol/64/suppl/C werden die Verfasser nicht erfasst.
Z. B.: 
https://www.sciencedirect.com/science/article/pii/S1756061620304778

![grafik](https://user-images.githubusercontent.com/29707105/106865949-267cb280-66cc-11eb-81bc-2e3e34336d84.png)

**Comment by jriedl** [comment]
Vgl. auch #1375. Problem ist ein derzeit nur im Kontext des Translation-Servers repoduzierbares Problem, bei dem sehr tief innerhalb des Node-Stacks (der Laufzeitumgebung des Translationservers) eine Exception geworfen wird, weil ein Element nicht gefunden wird. Problemlösung derzeit offen.

**Comment by jriedl** [comment]
Die Ursache war ein Bug in der durch den Translation-Server verwendeten JSDOM-Biblitothek. Der Translation-Server wurde auf das Zusammenspiel mit einer neueren Version angepasst. Der aktuelle Stand findet sich ab sofort auf nu.

**Comment by kdr154** [comment]
Passt jetzt. Vielen Dank!

**Comment by jriedl** [comment]
Die neue JSDOM-Version 16 hat in anderen Kontexten zu Fehlern geführt (vgl. #1388), weshalb diese Änderung rückgängig gemacht wurde. Als Versuch wird nun anstatt der ursprünglichen Version 13.1 die Nachfolgeversion 14.1 verwendet. #1388 tritt damit lokal nicht mehr auf. Der aktuelle Stand findet sich auf nu. Bis zu einer relativen Sicherheit im Bezug auf den Ausschluss von Seiteneffekten sollte jedoch diese Version nicht auf ub28 eingespielt werden.

**Comment by jriedl** [comment]
Daoben genannte JSDOM Version nun seit mehreren Monaten produktiv ist, sollte das keinen Hinderungsgrund mehr darstellen.

**Comment by kdr154** [comment]
Verfasser sind auf nu da. Einspielung scheitert jedoch im Augenblick wegen Online-First.
