### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Seitenzahl ist Artikelnummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1376]
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/vol/64/suppl/C
https://www.sciencedirect.com/science/article/pii/S1756061620304778

Was hier als Seitenzahl erfasst wird, ist die Artikelnummer. Bitte entfernen.

![grafik](https://user-images.githubusercontent.com/29707105/106866508-d5b98980-66cc-11eb-81cd-33ffe3751efa.png)

**Comment by kdr154** [comment]
Wurde bei der vorliegenden Zeitschrift erfolgreich mit $y gelöst:

![grafik](https://user-images.githubusercontent.com/29707105/110344751-1c810300-802e-11eb-858e-9b6830822258.png)


Leider gibt es seit einigen Tagen die Möglichkeit, diesen Sachverhalt mittels $i umzusetzen. Was bereits erfolgreich geschehen ist. Siehe #1416

In diesem Fall sollte man in meinen Augen zu dieser Lösung greifen.

**Comment by jriedl** [comment]
vgl. #1433

**Comment by kdr154** [comment]
Es wird $i in 936 gesetzt.
