### ISSUE TITLE
ISSN 2007-2023 |  Archivos de Criminología, Seguridad Privada y Criminalística | Spanische Namen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1378]
Derselbe Hikal aus #1372 wird bei dieser Zeitschrift in dieser Form falsch umgesetzt:
https://dialnet.unirioja.es/servlet/articulo?codigo=7497237

![grafik](https://user-images.githubusercontent.com/29707105/107001567-22af6580-678a-11eb-8162-6fcd24be4aa0.png)

Richtig wäre: Hikal-Carreón, Wael Sarwat

**Comment by jriedl** [comment]
Vermutlich wird hier wie erwähnt, keine abschließende Lösung möglich sein. Die Heuristik ist,, wenn der Nachname nur aus einem Token und der Vorname aus mindestens zwei besteht, den letzten in den Nachnamen zu ziehen, außer es werden Präpositionen wie de, de la, des etc. gefunden. Das liefert in vielen Fällen das richtige, in einigen aber auch das falsche Ergebnis. Um eine genaue Zuordnung gewährleisten zu können, müsste man Listen mit Vor- und Nachnamen führen, was nicht realisierbar erscheint. Der Vorschlag wäre daher, diese Records einzuspielen und in der WinIBW anhand eines Sprachcode-Filters auf Spanisch, unserer Abrufzeichen und eventuell des Datums in regelmäßigen Abständen eine intellektuelle Überprüfung vorzunehmen.

**Comment by kdr154** [comment]
Sehe ich auch so. Ich hatte auch daran gedacht, in der GND die Namen anzulegen. Was aber noch unrealistischer ist. Ich denke wir müssen mit diesen Fehlern leben und bei Bedarf korrigieren. In den meisten Fällen stimmt die Umsetzung ja auch. Deshalb schließe ich dieses Issue.
