### ISSUE TITLE
ISSN 2006-5442 Public perseption of the services of vigilante groups in Anambra State - Seitenangabe fehlerhaft

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#138]
Die Seitenangabe kommt wie folgt rüber: 73-106-106
Das ist die Seite des Artikeln:
https://www.ajol.info/index.php/jrhr/article/view/180087
Das die des Hefts:
https://www.ajol.info/index.php/jrhr/issue/view/17544

Es handelt sich um eine OJS-Zeitschrift und dieser Fehler kommt auch bei anderen Zeitschriften vor, die wahrscheinlich ebenfalls mit OJS gemacht werden.

**Comment by shadeMe** [comment]
Gefixt. Der relevante Translator heißt 'Open Journal Systems.js'.

**Comment by kdr154** [comment]
Sieht gut aus!
