### ISSUE TITLE
ISSN 1552-6518 | Journal of interpersonal violence | Seitenzahlen

### ISSUE THREAD

**Issue by jriedl** [ubtue/DatenProbleme#1380]
In den Daten und in Krimdok (vgl. https://krimdok.uni-tuebingen.de/Search/Results?lookfor=superior_ppn:324614721) finden sich seltsame Seitenangaben (NPxx-NPyy). Diese sind allerdings auch auf der SAGE-Seite selbst so hinterlegt (vgl. z.B. https://journals.sagepub.com/doi/10.1177/0886260517736877 unter "Article information"). Es verhindet allerdings z.B. syntaktisch korrekte JOP-Abfragen.

**Comment by kdr154** [comment]
Die Frage nach den JOP-Abfragen ist damit leider nicht abschließend geklärt.

**Comment by jriedl** [comment]
Es existiert nun Workaround in TueFind, so dass die JOP Icons nun wieder angezeigt werden. Deshalb schließe ich.
