### ISSUE TITLE
ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society | Sprache Brill live

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1381]
Bei dieser Zeitschrift schlägt die Spracherkennung vollkommen fehl. Von den 16 Artikeln wurden nur zwei eingespielt, beide mit der falschen Sprache in Pica 1500 marc 041 "ger". Die anderen 14 Artikel wurden nicht eingespielt, weil keine Sprache ausgegeben wurde. Bsp.:
![grafik](https://user-images.githubusercontent.com/29707105/107475805-01c58680-6b75-11eb-9d7b-50ab43a1801c.png)

Der Grund ist jedes Mal, dass die Sprache, die erwartet wird (ger), sich von der die Ngram findet (eng), unterscheidet. Bsp. aus dem CLI-Output auf nu:

![grafik](https://user-images.githubusercontent.com/29707105/107476298-dc854800-6b75-11eb-9770-78466bad3c6b.png)
 
Woher kommt es, dass der Harvester bei dieser Zeitschrift "ger" erwartet und wie kann man das ändern?

Die harvester.conf hat folgende Einstellungen:

![grafik](https://user-images.githubusercontent.com/29707105/107476567-633a2500-6b76-11eb-9187-6a537753d983.png)
 

Dort steht eng an erster Stelle. Wobei man in meinen Augen die anderen Sprachen bei dieser Zeitschrift herausnehmen kann. Ich habe bei stichprobenartiger Durchsicht einzelner Hefte nur englische Artikel gefunden.

**Comment by IxKo** [comment]
Band 5,1 enthält drei deutschsprachige Artikel. Da Brill immer ger liefert, wird der Sprach-Vergleich eh in den meisten Fällen nicht übereinstimmen.

**Comment by kdr154** [comment]
mit tika schlägt die Spracherkennung in einem Fall in Heft 5.1 fehl. Hier https://brill.com/view/journals/jrat/5/1/article-p8_2.xml wird "ger" geliefert statt "eng"

**Comment by jriedl** [comment]
Das ist natürlich ein schwieriger Grenzfall: Deutscher Eigenname und ein in allen europäischen Sprachen ähnlicher Term wie "Mysticism". Wenn man das Abstract noch mit in die Auswertung aufnehmen würde, würde es in diesem konkreten Fall wahrscheinlich funktionieren, aber dann macht man sich die deutschen Beiträge wieder kaputt, deren Abstracts ja auch Englisch sind. Deshalb sehe ich hier wenig Möglichkeiten, die Fehlzuordnung automatisch zu umgehen.

**Comment by IxKo** [comment]
Ich glaube auch, dass es auch bei Rezensionen häufig zu Fehlzuordnungen kommen wird, da die abgeleitete Sprache vom Titel des rezensierten Werkes nicht unbedingt mit der Sprache der Rezension übereinstimmen muss.

**Comment by kdr154** [comment]
Hinreichend diskutiert. In diesem Fall muss nachgearbeitet werden.
