### ISSUE TITLE
ISSN 1570-0585 | Arabica : journal of Arabic and islamic studies | Sprache (Brill Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1382]
https://brill.com/view/journals/arab/67/5-6/arab.67.issue-5-6.xml
Bei dieser Zeitschrift landen alle französischsprachigen Artikel in der Error-Datei, weil die erwartete Sprache von  der, die gefunden wird, abweicht:

![grafik](https://user-images.githubusercontent.com/29707105/107478591-004a8d00-6b7a-11eb-82f0-88ac97997765.png)

obwohl Französisch in der harvester.con hinterlegt ist:

![grafik](https://user-images.githubusercontent.com/29707105/107478740-44d62880-6b7a-11eb-9d9e-cecc24d99623.png)

Auffällig ist, dass hier, wie auch in dem ähnlich gelagertern Fall in Issue #1381 zu wenig ngrams erzeugt werden

**Comment by IxKo** [comment]
Bereits live und gelöst.
