### ISSUE TITLE
ISSN 1573-6679 | Pastoral Psychology | Translator Multi-DL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1384]
https://link.springer.com/journal/11089/volumes-and-issues/70-1?utm_source=toc&utm_medium=email&utm_campaign=toc_11089_70_1&utm_content=etoc_springer_20210211

Mit dem Springer Link-Translator ist kein Multi-DL möglich. Das betrifft nicht nur dieser Springer-Zeitschrift, sondern die Zeitschriften von Springer generell.
Fehlermeldung: Es ist ein Fehler aufgetreten beim Versuch ...

**Comment by socheres** [comment]
Ich kann den Fehler nicht reproduzieren. Ich bekomme keine Fehlermeldung beim Multi-DL sowohl das Heft https://link.springer.com/journal/11089/volumes-and-issues/70-1? als auch https://link.springer.com/journal/11089/volumes-and-issues/69-4 in i#1101
Würden Sie in der erweiterten Einstellung Zotero-Connector im Firefox-Browser die Translators aktualisieren und nochmal testen?

**Comment by socheres** [comment]
Ihr "Springer Link.js" ist übrigens auch auf aktuellem Stand.

**Comment by kdr154** [comment]
Tut mir leid. Wieder dasselbe Problem. Meine mich zu erinnern, dass sich auch @IxKo darüber beklagt hat.

**Comment by socheres** [comment]
Habe jetzt die Datei manuell in Ihr lokales Verzeichnis kopiert. Können Sie bitte nochmal testen?

**Comment by kdr154** [comment]
Tut mir leid. Der Fehler existiert weiterhin.

**Comment by kdr154** [comment]
Habe es gerade auch mit dem Browser Edge versucht.  Auch hier dasselbe Problem.

**Comment by socheres** [comment]
nur zur Info: Multi-DL lief jetzt - anderes als gestern im Meeting - wieder problemlos durch.
![grafik](https://user-images.githubusercontent.com/1545743/108055980-fda3d800-7050-11eb-901c-d8699f7274bc.png)

**Comment by kdr154** [comment]
Bei mir kommt leider immer noch die Fehlermeldung. Dabei habe ich sogar über Nacht gewartet und alles aktualisiert.

**Comment by IxKo** [comment]
Bei mir klappt es auch nicht.
Interessanterweise hat es gestern mit Edge funktioniert. Seit heute schmiert mir jedoch der gesamte Browser Edge ab, wenn ich den Zotero-Button benutze (bspw. bei Ebsco), die könnte mit dem Windows-Update zusammenhängen, was bei mir heute installiert wurde.

**Comment by kdr154** [comment]
Läuft einwandfrei, ZS ist bereits im Test.
