### ISSUE TITLE
ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society | Dateneinspielung Brill live Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1385]
https://brill.com/view/journals/jrat/6/2/jrat.6.issue-2.xml
Von diesem Heft wurden lediglich zwei Artikel erfolgreich eingespielt. Diese beiden:
https://brill.com/view/journals/jrat/6/2/article-p473_12.xml
https://brill.com/view/journals/jrat/6/2/article-p449_11.xml

Alle anderen, insgesamt 14, wurden verworfen, weil keine Sprache ausgegeben wurde!

![grafik](https://user-images.githubusercontent.com/29707105/107744958-df1da400-6d13-11eb-8093-5d41c0e85a9a.png)

**Comment by jriedl** [comment]
In diesem konkreten Fall hat das nichts mit unserer Spracherkennung zu tun. Innerhalb der Embedded-Metadata-Section der Webseite ist eine falsche Sprache (`citation_language` "de") hinterlegt. Im Harvester wird korrekt `eng` erkannt , dann aber keine Sprache nach "041" geschrieben, da diese Angaben nicht übereinstimmen. Lösungsmöglichkeiten:
* Die im Harvester erkannte Sprache ist zukünftig für das 041-Feld autoritativ (eventuell Erzwingen dieses Verhaltens durch eine Config-Direktive)
* Kontaktaufnahme mit Brill mit der Bitte um Korrektur

**Comment by jriedl** [comment]
vgl. #1381

**Comment by kdr154** [comment]
Man kann Brill darauf aufmerksam machen, aber der Spracherkennung  durch ngram den Vorrang zu geben ist möglcherweise der praktikablere und schnellere Weg.

**Comment by jriedl** [comment]
Ist jetzt implementiert (`force_language_detection = true`) und für diese Zeitschrift auch schon in der Config-Datei auf nu. Weiterhin kommt nun der neue Tika-basierte Ansatz für die Spracherkennung zum Einsatz. Vor einer Übertragung auf den Live-Server sollten aber zumindest stichprobenhaft auch bereits aktive Zeitschriften im Bezug auf das Sprachfeld 041 überprüft werden.

**Comment by kdr154** [comment]
Lieber Herr Riedl,

was heißt aktiv. Live oder Test? oder beides?

Viele Grüße
Klaus-Dieter Rosenkranz

_________________________

Klaus-Dieter Rosenkranz
Eberhard Karls Universität Tübingen
Telefon: Universitätsbibliothek +49 7071 29 72963
Mobil: 0173 3194973

E-Mail: rosenkranz@uni-tuebingen.de


Von: jriedl <notifications@github.com>
Gesendet: Dienstag, 16. Februar 2021 10:44
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: Rosenkranz, Klaus-Dieter <klaus-dieter.rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society | Dateneinspielung Brill live Sprache (#1385)


Ist jetzt implementiert (force_language_detection = true) und für diese Zeitschrift auch schon in der Config-Datei auf nu. Weiterhin kommt nun der neue Tika-basierte Ansatz für die Spracherkennung zum Einsatz. Vor einer Übertragung auf den Live-Server sollten aber zumindest stichprobenhaft auch bereits aktive Zeitschriften im Bezug auf das Sprachfeld 041 überprüft werden.

**Comment by jriedl** [comment]
@kdr154 Achtung, die Antwort ging nach Github. Aktiv sollte "live" bedeuten. Im Prinzip kann man jetzt zunächst mal alle Zeitschriften testen, bei denen ohnehin Sprachprobleme bekannt sind. Wenn hier keine größeren Probleme auffallen, könnten noch ein paar Livezeitschriften -auf nu- überprüft werden - interessant sind dann aber wahrscheinlich vor allem die, die irgendwie "exotische" Sprachen haben.

**Comment by kdr154** [comment]
Lieber Herr Riedl,

leider trifft die Spracherkennung durch ngram auch nicht immer zu. Und manchmal kann ich mir die Dinge nicht erklären.
z. B. dieser Artikel: https://brill.com/view/journals/jsj/52/1/article-p136_8.xml
Der wurde bei der Live-Einspielung heute nicht eingespielt, weil die Sprache nicht übereingestimmt hat. Und zwar war die Vorgabe "eng". Den höchsten Wert bei ngram hatte aber "ger". Getestet auf nu. Kann ich nun nicht mehr reproduzieren, weil ein Test auf nu nun anders ausfällt.
Bei dem aktuellen Test passt plötzlich alles:
[cid:image001.png@01D70453.B79D3950]

Ich meine, wo liegt der Unterschied. Basiert die "detected language" jetzt nicht mehr auf dem ngram-Verfahren.

Viele Grüße
Klaus-Dieter Rosenkranz
_________________________

Klaus-Dieter Rosenkranz
Eberhard Karls Universität Tübingen
Telefon: Universitätsbibliothek +49 7071 29 72963
Mobil: 0173 3194973

E-Mail: rosenkranz@uni-tuebingen.de


Von: jriedl <notifications@github.com>
Gesendet: Dienstag, 16. Februar 2021 10:44
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: Rosenkranz, Klaus-Dieter <klaus-dieter.rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society | Dateneinspielung Brill live Sprache (#1385)


Ist jetzt implementiert (force_language_detection = true) und für diese Zeitschrift auch schon in der Config-Datei auf nu. Weiterhin kommt nun der neue Tika-basierte Ansatz für die Spracherkennung zum Einsatz. Vor einer Übertragung auf den Live-Server sollten aber zumindest stichprobenhaft auch bereits aktive Zeitschriften im Bezug auf das Sprachfeld 041 überprüft werden.

**Comment by kdr154** [comment]
@jriedl danke für den Hinweis.

**Comment by jriedl** [comment]
Ja genau, die Änderungen sollen zwei Probleme beheben. Die falsche Sprachausspielung durch Brill und die Probleme der Spracherkennung. Der neue Ansatz verwendet Tika (https://tika.apache.org/download.html), also immer noch ein Ngram-Verfahren, allerdings wohl mit einem anderen Sprachmodell. Sollte die Erkennung über Tika über Tika nichts zurückliefern (sollte nur bei den "exotischen" Sprachen vorkommen, wird auf unseren bisherigen Ansatz zurückgegriffen.

**Comment by kdr154** [comment]
Test für aktuelles Heft dieser ZS auf nu erfolgreich.

**Comment by kdr154** [comment]
Es wird und es gibt auch bei den aktuellen Live-Einpielungen nur wenige Fehler im Hinblick auf die Spracherkennung. Zum einen das Heft, weshalb das Issue aufgemacht wurde und der Einzelfall, der oben erwähnt wird, weil wir uns bislang bewusst auf Zeitschriften beschränkt haben, die nur Aufsätze in einer Sprache enthalten.
Deshalb müssen wir zum Testen ersst noch kompliziertere Fälle suchen.

**Comment by kdr154** [comment]
Ist aber noch nicht global implementiert. Oder?

**Comment by jriedl** [comment]
> Ist aber noch nicht global implementiert. Oder?

Das `force_language_detection = true`? Nein, das müsste man für jede Zeitschrift, für die das gewünscht ist, explizit eintragen, da wir ja im Regelfall davon ausgehen, dass die vom Translator gelieferten Sprachinformationen richtig sind und man es deshalb nicht als default setzen sollte.

**Comment by IxKo** [comment]
Beim Test auf Nu mit Try RSS sehen die Daten gut aus. Alle Datensätze werden als englisch Artikel erkannt.
Brill liefert nur ger, das komplette Heft ist aber auf Englisch (https://brill.com/view/journals/jrat/6/1/jrat.6.issue-1.xml).

![image](https://user-images.githubusercontent.com/57000004/108728063-7d3a1700-7529-11eb-8cba-b5575795f4ca.png)

**Comment by kdr154** [comment]
Sprache auf ub28 korrekt.
