### ISSUE TITLE
ISSN 1745-5243 | Journal of moral philosophy | Missmatch von Zeitschrift und Artikeln

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1388]
Hier existiert ein mismatch zwischen geharvesteter Zeitschrift, Journal of Moral Philosophy und den Artikeln, der dieser Zeitschrift zugeordnet ist:
Das ist ein Artikel des Sets: https://link.springer.com/chapter/10.1007%2F978-1-4020-5697-0_7
Das die Zeitschrift: https://brill.com/view/journals/jmp/jmp-overview.xml
Bei einer genaueren Sicht auf die Artikel, die am 11.2. zu dieser Zeischrift geharvestet wurden, zeigt sich, dass nur ein Artikel zu dieser Zeitschrift gehört, die anderen neun aber zu verschiedenen unterschiedlichen Zeitschriften:

![grafik](https://user-images.githubusercontent.com/29707105/107754815-4cd0cc80-6d22-11eb-916c-bb0d9745f5e5.png)

Siehe auch #1387

**Comment by mtrojan-ub** [comment]
Bei einem Testlauf mit dieser Zeitschrift tauchen in der Oberfläche Fehlermeldungen auf:

`Item 1 [Journal of moral philosophy...] | https://brill.com/view/journals/jmp/18/1/article-p1_1.xml {4905510364580111777} download failed! error: translation server returned an invalid multiple-match response! (response code = 500)`

Ein Blick auf die Translation Server log gibt einen Hinweis auf einen Fehler im Brill Translator:

```
Feb 15 14:33:42 nu conmon[2265153]: (1)(+0000000): Translation using Brill failed
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]: (1)(+0000000): TypeError: Cannot read property 'trim' of undefined
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]:    TypeError: Cannot read property 'trim' of undefined
Feb 15 14:33:42 nu conmon[2265153]:        at extractErscheingunssjahr (eval at  (/app/src/translation/sandboxManager.js:70:4), :103:29)
Feb 15 14:33:42 nu conmon[2265153]:        at postProcess (eval at  (/app/src/translation/sandboxManager.js:70:4), :92:25)
Feb 15 14:33:42 nu conmon[2265153]:        at eval (eval at  (/app/src/translation/sandboxManager.js:70:4), :117:3)
Feb 15 14:33:42 nu conmon[2265153]:        at /app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:339:8
Feb 15 14:33:42 nu conmon[2265153]:        at Zotero.Translate.Web._runHandler (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:1064:32)
Feb 15 14:33:42 nu conmon[2265153]:        at run (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:183:23)
Feb 15 14:33:42 nu conmon[2265153]:        at Object._itemDone (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:237:11)
Feb 15 14:33:42 nu conmon[2265153]:        at Object._itemDone (/app/modules/zotero/chrome/content/zotero/xpcom/translation/translate.js:709:34)
Feb 15 14:33:42 nu conmon[2265153]:        at Object._itemDone (/app/src/translation/sandboxManager.js:96:17)
Feb 15 14:33:42 nu conmon[2265153]:        at Zotero.Item.complete (eval at  (/app/src/translation/sandboxManager.js:70:4), :1:341)
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]: (4)(+0000000): Translate: Parsing code for DOI (c159dcfe-8a53-4301-a499-30f6549c340d, 2019-01-27 14:06:07)
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]: (3)(+0000000): Translate: Beginning translation with DOI
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]: (3)(+0000009): [
Feb 15 14:33:42 nu conmon[2265153]:    "0": "10.1163/17455243_20203008"
Feb 15 14:33:42 nu conmon[2265153]: ]
Feb 15 14:33:42 nu conmon[2265153]: 
Feb 15 14:33:42 nu conmon[2265153]: (3)(+0000000): Translate: Creating translate instance of type search in sandbox
```

Es scheint also ein Problem mit dem Brill-Translator zu geben. Möglicherweise versucht der Translation Server im Anschluss einen falschen Translator zu verwenden der die falsche DOI ausliest. 

@jriedl, kannst Du Dir bitte mal den Brill-Translator anschauen?

**Comment by jriedl** [comment]
Hatte ich vorhin im Zusammenhang mit der beschriebenen EmbeddedMetadata-Problematik gemacht und hängt damit zusammen, dass das `item.date` fehlt. Tritt der Fehler mit der alten JSDOM-Version lokal noch auf?

**Comment by mtrojan-ub** [comment]
Nein, tritt damit wohl nicht mehr auf (habe für den Test lokal den Translation Server mit dem alten Stand bzw. commit 29398c5ef189712bd29d8a3c007c3282e1646ebb neu gebaut)

**Comment by jriedl** [comment]
Bis zu einer Lösung der Probleme mit dem Embedded-Metadata-Subtranslator kommt wieder die vorherige JSDOM-Version zum Einsatz.

**Comment by kdr154** [comment]
Im Augenblick sind die Daten korrekt und vollständig.
