### ISSUE TITLE
ISSN 0932-9951 Kirchliche Zeitgeschichte - Sprache und Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#139]
Bei dieser Zeitschrift wird standardmäßig (Atypon) immer der englische Titel übertragen, auch wenn die Vorlage deutsch ist:
https://www.vr-elibrary.de/doi/abs/10.13109/kize.2018.31.1.221#.XBD_IcQxlaQ
https://www.vr-elibrary.de/toc/kize/31/1
Das Abstract jedoch auf deutsch. 
Das ist nicht so, wenn man mit embedded metadata oder DOI überträgt. Jedoch fehlen dann wichtige Teile.

**Comment by shadeMe** [comment]
Gefixt. Sie können die neueste Version aus unserem Repo herunterladen.

**Comment by kdr154** [comment]
Kann keine Veränderung erkennen.

**Comment by shadeMe** [comment]
Haben Sie den Translator aktualisiert, wie wir abgemacht haben bzw. den Text des Translators von [unserem Repositorium](https://github.com/ubtue/zotero-translators) auf ihrem lokalen Datei? Zu prüfen können Sie sich Zeile 212 in dem aktuellen Datei anschauen - Dort sollte der folgende Text stehen: _The RIS translator mixes up the title's language_.

**Comment by kdr154** [comment]
Ja, das steht da.

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Dienstag, 8. Januar 2019 16:00
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 0932-9951 Kirchliche Zeitgeschichte - Sprache (#139)

 

Haben Sie den Translator aktualisiert, wie wir abgemacht haben bzw. den Text des Translators von unserem Repositorium <https://github.com/ubtue/zotero-translators>  auf ihrem lokalen Datei? Zu prüfen können Sie sich Zeile 212 in dem aktuellen Datei anschauen - Dort sollte der folgende Text stehen: The RIS translator mixes up the title's language.

**Comment by shadeMe** [comment]
N.B https://github.com/ubtue/DatenProbleme/issues/140#issuecomment-453554882, https://github.com/ubtue/DatenProbleme/issues/128#issuecomment-448197241

**Comment by shadeMe** [comment]
@kdr154 Ist dieses Problem jetzt behoben?

**Comment by kdr154** [comment]
nein es besteht weiter, sowohl im single als auch im multidownload.

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Donnerstag, 7. Februar 2019 13:23
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 0932-9951 Kirchliche Zeitgeschichte - Sprache (#139)

 

@kdr154 <https://github.com/kdr154>  Ist dieses Problem jetzt behoben?

**Comment by shadeMe** [comment]
Es schient, die meisten (allen?) Artikel haben deutsche Zusammenfassungen egal die Sprache des Titels. Gibt es Artikel, die zweisprachige Title haben? Jedenfalls ist die Frage, wie wir sie disambiguieren können. Bei manchen Artikeln ist die Sprache in den Metadaten vorhanden, wobei kann ich den Translator anpassen, die richtigen Angaben zu extrahieren. Wenn nicht, wie wollen wir vorgehen?

**Comment by thefass** [comment]
In Zeder ist in der Spalte spr die Sprache der Aufsätze eingetragen. Viele Zss haben Artikel nur in einer Sprache, es gibt aber auch Zss, die vom Konzept her mehrsprachig aufgestellt sind. In diesen Fällen sind in spr auch mehrere Sprachen eingetragen

**Comment by kdr154** [comment]
Die Daten, die über nu generiert werden sehen jetzt gut aus. Zumindest erscheint der Titel der Aufsätze in der Sprache, in der der Aufsatz verfasst wurde. Beim Abstract ist es so, dass es immer ein deutsches und ein englisches gibt. Übertragen wird immer das deutsche, wohl weil es vor dem englischen steht. Darin sehe ich kein Problem.  Im Fall dass beide abgegriffen würden, müsste das Tag 520 ein weiteres mal generiert werden. Sonst stehen beide in einem Eintrag. Dies gibt vielleicht auch Probleme mit Leerzeilen und Absatzwechsel in der Katalogisierungsdatenbank. Daran kann man ja noch zu einem späteren Zeitpunkt arbeiten.
Fraglich ist aber noch der Language Code (Tag 041). Den gibt es in den Daten nicht.
In dem bislang verfügbaren Online-Ausgaben beschränkt sich die Sprache der Aufsätze auf Englisch und Deutsch.  In diesem Fall müsste die Heuristik greifen, die von euch entwickelt wird.

**Comment by thefass** [comment]
Prinzipiell sollte, nicht nur bei dieser Zss, - wann immer möglich - auch das englische oder anderssprachige Abstract mit abgegriffen werden.

**Comment by kdr154** [comment]
In Zotero hat ein aktualisieren des Translators Atypon Journals nichts gebracht. Gibt es einen besseren?

**Comment by kdr154** [comment]
Das Problem mit der Sprache in Zotero ist jetzt behoben.

**Comment by kdr154** [comment]
Jetzt sind die Abstracts in beiden Sprachen vorhanden. Allerdings übergangslos in einem Tag 520. Besser wäre es, wenn für jede Sprachvariante ein eigenes Tag 520 (mit den entspechenden Subfields) erzeugt werden könnte.

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift werden jetzt mehrere 520 Felder erzeugt.

**Comment by kdr154** [comment]
Sieht gut aus
