### ISSUE TITLE
ISSN 1477-2744 | Psychology, crime & law | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1390]
Dieser Artikel: https://www.tandfonline.com/doi/full/10.1080/1068316X.2020.1775829 wird als Rezension getagt: 

![grafik](https://user-images.githubusercontent.com/29707105/107930846-d0d1c100-6f7b-11eb-899a-d068c79efc54.png)

Er ist aber keine Rezension, sondern ein Literaturbericht. Er wird zwar auf der Seite als "review" gelabelt, aber nicht als "Book review".
![grafik](https://user-images.githubusercontent.com/29707105/107931183-3756df00-6f7c-11eb-8589-b66407004323.png)
Darüber hinaus kommt der Begriff "review" auch im Titel vor. Das sollte aber nicht dazu führen, dass dieser Artikel mit dem Rezensionstag versehen wird.

**Comment by jriedl** [comment]
Aktuell auf nu kein 655-Tag mehr.

**Comment by kdr154** [comment]
Stimmt.
