### ISSUE TITLE
ISSN 2628-5819 | Gottesdienst : Information u. Handreichung der liturgischen Institute Deutschlands, Österreichs | New Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1391]
Bei dieser Zeitschrift existiert jetzt auch eine Online-Ausgabe: 
https://www.herder.de/gd/hefte/archiv/
Kann man dafür einen Translator schreiben?

**Comment by socheres** [comment]
@kdr154 bitte testen. Verbesserungsvorschläge bitte an @hlindeboom Danke!

**Comment by socheres** [comment]
@kdr154 Können Sie bitte auch testen, ob der neue Translator auch bei anderen Zeitschriften von Herder gut funktioniert? Z.B.: https://www.herder.de/bn-nf/hefte/archiv/

**Comment by kdr154** [comment]
@hlindeboom
Was für ein Translator soll da verwendet werden. Bekomme nur Embedded Metadata angeboten und der speichert eine Webseite.

**Comment by hlindeboom** [comment]
> @hlindeboom
> Was für ein Translator soll da verwendet werden. Bekomme nur Embedded Metadata angeboten und der speichert eine Webseite.

Es sollte ein neuer Translator mit dem Namen ubtue_Gottesdienst angeboten werden.

**Comment by kdr154** [comment]
Der steht zwar in meinem Translator-Ordner, wird mir aber nicht angeboten.

**Comment by socheres** [comment]
@hlindeboom das liegt an dem Target. Z.B. auf folgenden Seiten wird kein Translator angeboten:
https://www.herder.de/gd/hefte/aktuelles-heft/ 
https://www.herder.de/gd/hefte/archiv/2021/6-7-2021/
Hier dagegen schon:
https://www.herder.de/gd/hefte/archiv/

**Comment by hlindeboom** [comment]
@socheres Sie haben Recht. Vielen Dank für den Hinweis.

**Comment by socheres** [comment]
@hlindeboom da es auf der Herder-Seite noch andere für uns relevante Zeitschriften gibt, wäre es nicht besser, einen für alle Zeitschriften gültigen Herder-Translator zu schreiben? Ich vermute, dass die Webseitenstruktur gleich aufgebaut ist.

**Comment by kdr154** [comment]
Halte ich auch für sinnvoll. Mein Eindruck war auch, dass die Seiten nach demselben Schema gestaltet worden sind (s. o.)

**Comment by hlindeboom** [comment]
Mit ein paar kleinen Anpassung, sollte der Translator auch für andere Herder Webseiten funktionieren.

**Comment by hlindeboom** [comment]
Mit dem neuen Heft vom 3.März hat sich die Struktur der Webseite leicht verändert, insofern als das auf der Archiv Seite keine Artikel mehr aufgelistet werden, dies ist auch bei einigen anderen Herder Zeitschriften der Fall.
Der Herder Translator wurde nun so angepasst, dass es die Artikel aller Herder Zeitschriften auslesen können sollte, allerdings nur von der Heftseit oder Seiten einzelner Artikel aus:
z.B. https://www.herder.de/gd/hefte/archiv/2021/6-7-2021/

**Comment by kdr154** [comment]
Mit der Zeitschrift Gottesdienst funktioniert der neue Herder-Translator. Was noch fehlt, sind die Seiterzahlen:

![grafik](https://user-images.githubusercontent.com/29707105/110334833-7af4b400-8023-11eb-9d5e-f80c53708236.png)

**Comment by kdr154** [comment]
Titel:
Der Haupttitel "Spiritus Domini" findet sich nur im Quelltext. So wird der Haupttitel, der auf den Webseiten zu finden ist, nämlich "Revolutionäre Verspätung oder verspätete Revolution?", zum Titelzusatz.
Das ist im Grunde genommen nicht korrekt, da man die Webseite als Vorlage hat.

https://www.herder.de/gd/hefte/archiv/2021/4-2021/
https://www.herder.de/gd/hefte/archiv/2021/4-2021/revolutionaere-verspaetung-oder-verspaetete-revolution/

**Comment by kdr154** [comment]
Der Translator funktioniert auch mit anderen bei Herder erscheinenden Zeitschriften. z. B. mit der Herder Korrespondenz:
https://www.herder.de/hk/hefte/archiv/2021/3-2021/
oder den Biblischen Notizen:
https://www.herder.de/bn-nf/hefte/archiv/2020/187-2020/
Diakonia:
https://www.herder.de/diakonia/hefte/archiv/51-2020/2-2020/
Römische Quartalsschrift:
https://www.herder.de/rq/hefte/archiv/114-2019/3-4-2019/
...

**Comment by hlindeboom** [comment]
Der Translator wurde angepasst und sollte nun sowohl die Seitenzahlen erfassen, als auch die korrekten Titel auslesen.

**Comment by kdr154** [comment]
Klappt bei mir noch nicht. Habe zuvor den Herder-Translator aus dem Masterverzeichnis in mein lokales Verzeichnis kopiert und im Browser als auch in Zotero aktualisiert.

**Comment by hlindeboom** [comment]
Ich kann den Fehler leider nicht reproduzieren. Bei mir werden im Scaffold als auch im Browser die Seitenzahlen nun korrekt erkannt.
In der IT Runde kam die Idee auf, dass es evtl helfen könnte den Browser neu zu starten, sollten Sie das nicht bereits getan haben.

**Comment by kdr154** [comment]
Einfach mal ein paar Tage Abstand, und schon klappt es.
