### ISSUE TITLE
ISSN 1874-8945 | Social Sciences and Missions | Brill Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1393]
Von den 18 Aufsätzen in diesem Heft: https://brill.com/view/journals/ssm/33/3-4/ssm.33.issue-3-4.xml
erhalten gerade mal 6 ein Marc21-Tag 041 für die Sprache.
Bei allen anderen Aufsätzen unterscheidet sich die Sprache, die vorgegeben wird, von der, die gefunden wird.
Das, was die Spracherkennung findet, ist in allen Fällen korrekt.
Hier sollte man  force_language_detection = true setzen

**Comment by IxKo** [comment]
Bereits live und gelöst.
