### ISSUE TITLE
ISSN 1552-3586 | Criminal justice policy review | Krimdok live fehlender Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1396]
https://journals.sagepub.com/toc/cjpa/32/2
Bei der Einspielung vom 17./18.02 fehlt von diesem Heft der letzte Artikel:
https://journals.sagepub.com/doi/full/10.1177/0887403420903370
Er ist nirgends zu finden. Weder in den log-Dateien noch unter den Delivered records von ub28:
![grafik](https://user-images.githubusercontent.com/29707105/108320668-627f3f80-71c3-11eb-94d9-f01bc9b30de2.png)

Bei einem Test mit TryRSS auf ub28 ist er jedoch mit enthalten:

![grafik](https://user-images.githubusercontent.com/29707105/108320919-b853e780-71c3-11eb-8290-e157461c8f54.png)

Und es werden alle vier Aufsätze geharvestet:

![grafik](https://user-images.githubusercontent.com/29707105/108321066-ef29fd80-71c3-11eb-8168-0dc8628304a3.png)

Er ist auch Bestandteil des aktuellen RSS-Feeds:

![grafik](https://user-images.githubusercontent.com/29707105/108324376-1f739b00-71c8-11eb-8c90-9e55445ac368.png)

Warten, ob er in den nächsten Tagen geliefert wird?

**Comment by jriedl** [comment]
In der `zts_harvester_delivery_pipeline.log` taucht er auf, hier wird ein ZTS-Fehler gemeldet. Da eine direkte manuelle Abfrage am Translation-Server allerdings ist, ist es wahrscheinlich im Augenblick tatsächlich die beste Lösung, zu sehen, ob er heute Abend hochgeladen wird.

**Comment by kdr154** [comment]
ZTS-Fehler?

**Comment by jriedl** [comment]
Zotero Translation Server. Hier kam ein HTTP-500 zurück.

**Comment by kdr154** [comment]
Sage?

**Comment by jriedl** [comment]
Derzeit sind ja keine systematischen Probleme im Zusammenhang mit SAGE bekannt. Da es sich um genau einen Datensatz handelt und das nicht reproduzierbar ist, gehe ich aktuell von einem temporären Fehler aus.

**Comment by kdr154** [comment]
Besteht bei den Springer-Zeitschriften dieselber HTTP-500 Problematik? Wenn ja, könnte man die ein oder andere ja, zumindest versuchsweise, auch live schalten.

**Comment by IxKo** [comment]
Es kann auch sein, dass man bei Sage einen Tag warten muss. Hier werden teilweise einzelne Artikel mit einem Tag Verzögerung eingespielt. Einen solchen Fall hatte ich mit der gestrigen Einspielung von "International bulletin of mission research". Da fehlten die ersten beiden Artikel - heute wurden sie geliefert.
Das ist womöglich gewollt, weil es im Vorfeld mit den Sage-Daten Probleme gab?

**Comment by jriedl** [comment]
> Besteht bei den Springer-Zeitschriften dieselber HTTP-500 Problematik? Wenn ja, könnte man die ein oder andere ja, zumindest versuchsweise, auch live schalten.

Nach meinem Stand sind die Artikel bei Springer ja gar nicht im RSS-Feed, also ist das ein anderes Problem.

**Comment by jriedl** [comment]
> Es kann auch sein, dass man bei Sage einen Tag warten muss. Hier werden teilweise einzelne Artikel mit einem Tag Verzögerung eingespielt. Einen solchen Fall hatte ich mit der gestrigen Einspielung von "International bulletin of mission research". Da fehlten die ersten beiden Artikel - heute wurden sie geliefert.
> Das ist womöglich gewollt, weil es im Vorfeld mit den Sage-Daten Probleme gab?
Wenn ein Download fehlschlägt, erfolgt beim nächsten Durchlauf ein erneuter Versuch.

**Comment by kdr154** [comment]
Der Titel wurde heute eingespielt.
