### ISSUE TITLE
Allgemein: Brill einzelne Open Access Aufsätze als LF (lizenzfrei) ausgeben

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1397]
Auch bei Brill gibt es einzelne OA-Aufsätze (Bsp. 2/7 OA https://brill.com/view/journals/vc/75/1/vc.75.issue-1.xml) und sicher wird das auch bei vielen anderen Zss der Fall sein.
Daher ist es doch besser, wenn (wie momentan) nur reine lizenzfreie Zss mit LF geliefert werden und alle anderen Zss erhalten keine Lizenzangabe. Denn lieber keine Angabe, statt eine falsche.

Schöner wäre natürlich, wenn die OA-Angabe irgendwie ausgelesen und als $4LF bzw. Marc-856 <subfield code="z">Kostenfrei< geliefert werden könnte.

_Originally posted by @IxKo in https://github.com/ubtue/DatenProbleme/issues/1201#issuecomment-781340873_

**Comment by socheres** [comment]
- [ ] ubtue_Brill.js anpassen.
- [ ] Tag "Open Access" erzeugen
- [ ] in der zotero_harvester.conf `add_marc_field_773` einfügen.

**Comment by IxKo** [comment]
Das Marc-Feld wäre 856, hatte mich verguckt, habe es korrigiert.

<subfield code="z">Kostenfrei</subfield>

**Comment by IxKo** [comment]
Wird es dann auch ein Zotero-Tag geben, dass im halbautomatischen Verfahren genutzt werden kann? Also so ähnlich wie das "RezensionstagPica"?

**Comment by kdr154** [comment]
Das wäre gut!

**Comment by IxKo** [comment]
Es wäre auch noch zu berücksichtigen, dass es ja nicht nur bei Brill der Fall ist, sondern bspw. auch bei Sage.

**Comment by jriedl** [comment]
Auf nu.

**Comment by socheres** [comment]
LF wird erzeugt. Nach PR-Merge durch @jriedl auf nu testen.
https://doi.org/10.1080/23312521.2020.1775755,
https://journals.sagepub.com/doi/10.1177/0307513320966618

**Comment by socheres** [comment]
bitte auf nu testen (T&F und Sage).

**Comment by IxKo** [comment]
Bei T&F wird der Artikel nun als LF gekennzeichnet:
![image](https://user-images.githubusercontent.com/57000004/110775824-a663e280-825f-11eb-8b78-da2ad1f32866.png)
Ich resette die Zs und lösche die Datensätze in der Test-DB, um morgen zu sehen, wie es im K10plus eingespielt wird.


Bei Sage war der Test auch erfolgreich:
![image](https://user-images.githubusercontent.com/57000004/110777075-0313cd00-8261-11eb-8c34-887172521a9e.png)

**Comment by IxKo** [comment]
Der Artikel von T&F wurde wie gewünscht eingespielt:
![image](https://user-images.githubusercontent.com/57000004/111146197-71ba9880-8589-11eb-83b7-b97e94eac0ff.png)
