### ISSUE TITLE
ISSN 1696-9219 | Revista Española de investigación criminológica | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1398]
https://reic.criminologia.net/index.php/journal
hier wird immer nur das erste Keyword erfasst. Die anderen fallen unter den Tisch
Bsp.:
https://reic.criminologia.net/index.php/journal/article/view/285

![grafik](https://user-images.githubusercontent.com/29707105/108383085-bf054d80-7209-11eb-8487-77f2fb81dfb2.png)

**Comment by jriedl** [comment]
Auf nu.

**Comment by kdr154** [comment]
Es werden jetzt alle erfasst.
