### ISSUE TITLE
SSOAR_MARC 21 Feld 024 $a_DOI

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#14]
In den SWB-Daten steht der **DOI** in Feld 024 $a immer ohne Präfix (analog zur **URN**):

Bsp.:
10.12759/hsr.22.1997.3/4.32-63
NICHT: https://doi.org/10.12759/hsr.22.1997.3/4.32-63

\<datafield tag="024" ind1="7" ind2=" "\>
\<subfield code="a"\>10.12759/hsr.22.1997.3/4.32-63\</subfield\>
\<subfield code="2"\>doi\</subfield\>

Die Resolving URL mit dem Präfix "https://doi.org/" sollte _zusätzlich_ in MARC-Feld 856 $u abgelegt werden. $u erfordert aber am Ende der Zeile einen Code in $x, der die Herkunft der URL angibt (Verlag, Resolving System u.ä.) 
Wenn die Herkunft aus den Daten nicht hervorgeht, sollte vermutlich nur 024 ohne 856 $u angegeben werden.

**Comment by IxTheoKm** [comment]
1. Handlungsanweisung:

Wenn datafield tag="024" ind1="7" ind2=" " vorhanden UND  ein doi folgt
Bsp.:
\<subfield code="a"\>https://doi.org/10.12759/hsr.34.2009.2.235-264\</subfield\>

dann aus dieser Adresse folgendes Datafield erzeugen:

```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.12759/hsr.34.2009.2.235-264</subfield>
<subfield code="x">Resolving-System</subfield>
<subfield code="z">Kostenfrei</subfield></datafield>
```

**Comment by IxTheoKm** [comment]
Umsetzung der 1. Handlungsanweisung ist okay.

Zweite Handlungsanweisung fehlte noch, darum hier als Ergänzung!

**Comment by IxTheoKm** [comment]
2. Handlungsanweisung

Wenn \<datafield tag="856" ind1="4" ind2="0"\> erzeugt worden ist,
dann aus 
\<datafield tag="024" ind1="7" ind2=" "\> mit \<subfield code="2"\>doi\</subfield\>
das Präfix https://doi.org/ löschen aus \<subfield code="a"\>
und den Anteil dahinter stehen lassen.

Beispiel:
Vorher:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">https://doi.org/10.12759/hsr.26.2001.2/3.102-118</subfield>
<subfield code="2">doi</subfield>

```
Nachher:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10.12759/hsr.26.2001.2/3.102-118</subfield>
<subfield code="2">doi</subfield>
```

**Comment by IxTheoKm** [comment]
Okay
