### ISSUE TITLE
ISSN 0002-7189 Journal of the American Academy of Religion - Abstracts werden abgeschnitten oder fehlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#140]
Bei dieser Zeitschrift werden die Abstracts beim Singledownload abgeschnitten. Bsp:
https://academic.oup.com/jaar/article/86/4/912/4993930
Beim Multidownload kommen sie gar nicht mit.

**Comment by shadeMe** [comment]
Ganz komisch. Ich weiß nicht, wie man diese Problematik löst. Solang Sie die Translator-Scripts in dem lokalen Zotero-Translators Verzeichnis stehen, sollte es tatsächlich gehen. 

Probieren Sie mal Folgendes:
0. Den Browser und den Zotero-Client in der folgenden Reinfolge neustarten: Zotero zuerst und danach Firefox. 
1. Auf den Zotero Knopf im Browser rechtsklicken und zu "Preferences" (oder Einstellungen, je nach der Sprache des Browsers).
2. Auf "Advanced"/"Erweiterte Einstellungen" klicken (steht auf der linken Seite der Webseite, die gerade geöffnet wurde).
3. Einmal auf den "Update Translators"/"Translators Aktualisieren" Knopf klicken.

Danach _sollte_ der Stand der Translators hoffentlich aktuell sein und in Anspruch genommen werden.

**Comment by kdr154** [comment]
Es scheint tatsächlich eine Frage zu sein, ob alles aktualisiert ist. Jetzt wird auch der richtige Translator genommen und es sieht gut aus.
