### ISSUE TITLE
ISSN 1478-0542 | History compass | Artikelnummern (Wiley)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1401]
https://onlinelibrary.wiley.com/toc/14780542/2021/19/2
Die Zeitschrift vergibt auf ihren Webseiten keine Seitenzahlen, sondern Artikelnummern. Wenn man 936 $h ausgeben wollte, müsste man $y 936 $y konstruieren

**Comment by IxKo** [comment]
Bei heutiger Live-Einspielung fehlen die Artikelnummern, obwohl es beim Test mit Try RSS auf ub28 korrekt aussieht sowie die gesendeten XML-Daten im Default-Ordner:

Beispiel-Hash IxTheo#2021-07-06#1793529296B0A2EE3DF6FAB4D4C1AB8C2240E6E6
```
</datafield>
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">19</subfield>
<subfield code="e">6</subfield>
<subfield code="i">e12656</subfield>
<subfield code="j">2021</subfield>
</datafield>

```

Gibt es vielleicht seitens des BSZ ein Problem?

Außerdem wird die ORCID-Information nicht erfasst.

**Comment by kdr154** [comment]
Zeitschrift is bereits live. Artikelnummern sind vorhanden, ORCID ebenfalls.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/1543#issuecomment-928927270

**Comment by IxKo** [comment]
Gelöst
