### ISSUE TITLE
ISSN 2507-0339 | Judaïsme Ancien - Ancient Judaism | Mehrsprachige Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1402]
https://www.brepolsonline.net/doi/abs/10.1484/J.JAAJ.5.122298

Hier ist die Trennung mehrsprachiger Abstracts nicht korrekt programmiert.

![grafik](https://user-images.githubusercontent.com/29707105/108823732-208a3b00-75c1-11eb-93fc-fa6f59f6eaeb.png)

Statt "/n4207" muss es heißen "\n4207". Backslash statt Slash. Ohne Blank direkt an den Text davor einfügen. Blank danach.

**Comment by kdr154** [comment]
Hier ist etwas falschgelaufen. Statt \n4207 und anschließenden Blank wird "\n" entfernt. Statt dessen wird ein Absatz eingefügt und das anschließende Blank wird entfernt:

![grafik](https://user-images.githubusercontent.com/29707105/109967521-d2c4af80-7cf1-11eb-8b07-68caa1134ca3.png)

**Comment by socheres** [comment]
Jetzt müsste es klappen.

**Comment by kdr154** [comment]
Das Blank dahinter muss noch ergänzt werden. Im Augenblick bekomme ich folgendes Ergebnis:
![grafik](https://user-images.githubusercontent.com/29707105/109977066-b8440380-7cfc-11eb-85c6-9db6accc812f.png)

**Comment by socheres** [comment]
Ein Blank ist eingefügt.

**Comment by kdr154** [comment]
Danke!
