### ISSUE TITLE
ISSN 2056-7731 | Baptist quarterly | Testeinspielung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1405]
Diese Zeitschrift steht stellvertretend für viele. Vorgestern habe ich die meisten Zeitschriften, die von Taylor & Francis herausgegeben werden in den Testbetrieb aufgenommen. Gestern noch die restlichen, die  in Frage kommen. Insgesamt sind es 48. Bei dreien hat ein Link zur Quelle Zeder p_zot2 gefehlt. Das habe ich heute ergänzt. 
Dennoch stellt sich mir die Frage, warum von vielen Zeitschriften gar keine Daten eingespielt wurden. So z. B. auch von dieser Zeitschrift: https://www.tandfonline.com/toc/ybaq20/52/1?nav=tocList
Der Testserver enthält zwar schon einen Titel: https://www.tandfonline.com/doi/full/10.1080/0005576X.2021.1854532
Dieser wurde aber bereits am 14.1.2021 eingespielt, und zwar vollautomatisch. Wobei ich mich frage, wie das möglich war. 
Dennoch. Der aktuelle Feed enthält das gesamte Heft 52.2021,1
Diese Titel, bis auf den einen, hätten doch gestern oder vorgestern alle einsgespielt werden müssen. Dies ist aber nicht der Fall. Und so ist es mit vielen dieser neu auf zotat gesetzten Zeitschriften.
Der Feed ist folgender: https://www.tandfonline.com/action/showFeed?type=etoc&feed=rss&jc=ybaq20
Der Status mit den gelieferten Zeitschriften auf nu ist folgender. Nur der Anfang mit den neuesten Einträgen, in denen auch der bereits gelieferte Titel zu sehen ist:

![grafik](https://user-images.githubusercontent.com/29707105/108965496-38bf9000-767d-11eb-91e2-6a6d9ed617a4.png)

Gibt es eine Erklärung, warum von vielen dieser Zeitschriften von Taylor & Francis keine Aufsätze eingespielt wurden?

**Comment by jriedl** [comment]
Wie es scheint, sind diese Zeitschriften schon viel länger im Testbetrieb, z.B. der Hash 8A3762E1AE9A1B01B95CE1AB343C101198ACF2C5 geht zurück auf 18.06.20. Daneben gab es im z.B. im Dezember 2020 noch Einspielungen (sichtbar in Default_Test). Vermutlich haben diese diverse Änderungen und Löschungen in der Testdatenbank nicht überlebt und die Zeitschriften müssten jetzt auf nu resettet werden, damit eine Neueinspielung erfolgt. Knapp 50 Zeitschriften-Neueinspielungen auf einmal in einer Nacht erscheint mir aber extrem viel, hier müssen wir dann mit Einschränkungen auf der Anbieterseite rechnen.

**Comment by kdr154** [comment]
Problem existiert nicht mehr.
