### ISSUE TITLE
ISSN 0720-6259 Pastoraltheologie - Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#141]
Vgl. #139 
Derselbe Publisher, dasselbe Problem. Obwohl die Seitensprache deutsch ist, wird alles englisch übertragen. Wir hätten es aber gern auf deutsch. Das Abstract scheint prinzipiell in englisch hinterlegt.
z. B.:
https://www.vr-elibrary.de/toc/path/106/1

**Comment by shadeMe** [comment]
Bei den Artikel dieser Ausgabe sind die Abstracts nur im Englischen oder?

**Comment by socheres** [comment]
ja, es gibt nur englische abstracts. wenn abstracts in beiden sprachen enthalten ist, dann beides übernehmen.

**Comment by shadeMe** [comment]
@socheres Im Fall von zwei Sprachen, wie sollte das Abstract Feld des Datensatzes formatiert werden? Als zwei Absätze?

**Comment by socheres** [comment]
Ja mit einem Zeilenumbruch zw. zwei Absätzen.

**Comment by shadeMe** [comment]
Gibt es einen Artikel z.B, der zwei Abstracts hat? Ich sehe keinen in der obigen Ausgabe.

**Comment by shadeMe** [comment]
@kdr154 Ich brauche hier weitere Hinweise bzw. Beispeile mit zwei Zusammenfassungen.

**Comment by kdr154** [comment]
Die Sprachproblematik scheint mir gelöst und es gibt wohl nur ein Abstract

**Comment by kdr154** [comment]
Sprachproblematik wieder da (1.8.2019). Alle Titel auf Englisch, Abstract auf deutsch. 
https://www.vr-elibrary.de/toc/path/108/6
Auch die Sache, dass sowohl das deutsche als auch das englische Abstract heruntergeladen werden soll, war bereits gelöst. Hier wird wieder nur das Deutsche übertragen

**Comment by kdr154** [comment]
Im Zotero-Tab Notizen steht bei mir nichts. Sonst sehe ich kein Feld "Notes". 
Die Abstracts sind aber von einer Unmenge von Leerräumen durchzogen. Diese werden durch Tabulatoren hervorgerufen und führen entgegen anderslautenden Behauptungen dazu, dass die Aufnahmen nicht korrekt verarbeitet werden können

**Comment by shadeMe** [comment]
So sollte es aussehen:

![Screenshot_20191017_165835](https://user-images.githubusercontent.com/214450/67021104-73b3ca00-f0ff-11e9-944b-ddec0915ac57.png)
![Screenshot_20191017_165910](https://user-images.githubusercontent.com/214450/67021108-73b3ca00-f0ff-11e9-9888-272256a9a46c.png)

Was die Leerräume angeht, kann ich es leider nicht reproduzieren. Ich nehme an, es liegt daran, dass der falscher Translator (oder dessen alte Version) ausgewählt wird.

**Comment by kdr154** [comment]
gelöst

**Comment by kdr154** [comment]
Muss es leider wieder öffnen:
Einige Ausgaben waren in Ordnung, doch hier geht es wieder los:
https://www.vr-elibrary.de/toc/path/108/12

**Comment by shadeMe** [comment]
@kdr154 Ich muss bis Ende der Woche an dem Zotero Harvester fürs voll-automatischen Verfahren arbeiten. Danach fange ich mit diesem Issue bzw. allen Issues an, die sich auf das halb-automatische Verfahren beziehen.

**Comment by socheres** [comment]
Sprache ist jetzt "de".
```
11:44:14 Returned item:
           {
             "itemType": "journalArticle"
             "creators": [
               {
                 "creatorType": "author"
                 "firstName": "Veronika"
                 "lastName": "Albrecht-Birkner"
               }
             ]
             "notes": []
             "tags": []
             "seeAlso": []
             "attachments": []
             "publicationTitle": "Pastoraltheologie"
             "journalAbbreviation": "Pastoraltheologie"
             "volume": "108"
             "issue": "6"
             "language": "de"
             "ISSN": "0720-6259, 2197-0831"
             "date": "2019-06-05"
             "pages": "240-255"
             "DOI": "10.13109/path.2019.108.6.240"
             "url": "https://www.vr-elibrary.de/doi/10.13109/path.2019.108.6.240"
             "title": "„Pionier der Menschlichkeit …“: Zur Albert-Schweitzer-Rezeption in der DDR"
             "libraryCatalog": "DOI.org (Crossref)"
         -   "accessDate": "2020-04-03T09:44:14Z"
             "shortTitle": "„Pionier der Menschlichkeit …“"
           }
```

**Comment by kdr154** [comment]
Das Folgende gilt alles für das halbautmatische Verfahren:
Das mit der Sprache ist jetzt in Ordnung. V&R hat ja seine Seiten komplett neu gestaltet.
Die Tabulatoren machen aber weiterhin Probleme. Z. B. bei diesem Titel https://www.vr-elibrary.de/doi/10.13109/path.2020.109.1.5 finden die sich sowohl im Abstract als auch im Titel.
Darüber hinaus wird das Abstract nur im Einzeldownload übertragen, beim Multi fehlt es.

**Comment by socheres** [comment]
@kdr bitte diesen Issue schließen und wegen Tabulatoren einen neuen Issue anlegen. Wenn Multi nicht geht, bitte einzeln erfassen.

**Comment by kdr154** [comment]
Issue wegen Tabulatoren angelegt.
