### ISSUE TITLE
ISSN 2040-4786 | Tel Aviv : journal of the Tel Aviv University, Institute of Archeology | Spracherkennung (Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1411]
https://www.tandfonline.com/toc/ytav20/47/2?nav=tocList

Auch hier werden alle Aufsätze verworfen, weil der Harvester die Sprache für ungültig erklärt:

![grafik](https://user-images.githubusercontent.com/29707105/109137741-d9837d80-7759-11eb-816a-5053d0f2e7dc.png)

Leider kann man nicht erkennen warum. Ist das die neue Ausgabe des tika-Spracherkennungsystems?
Wäre das ein Fall, wo man force_language_detection = true einsetzen könnte?

**Comment by jriedl** [comment]
vgl. auch #1410: Das ist von Tika unabhängig. Offenbar liefert der Translator keine Sprache zurück. Mit Angabe von `zotero_expected_languages` wird eine Sprache erkannt und ein `041`-Feld eingefügt.

**Comment by kdr154** [comment]
Kann man da was machen?

**Comment by kdr154** [comment]
Habe in beiden Fällen sprz in Zeder ergänzt.

**Comment by jriedl** [comment]
Bezüglich Translator geht die Frage an @socheres. Ansonsten sollte das Hinterlegen der Sprachen in Zeder doch schon zu einem `zotero_expected_languages`-Eintrag in der `zotero_harvester.conf` führen und damit das Problem lösen.

**Comment by kdr154** [comment]
Durch setzen der Sprache in Zeder gelöst
