### ISSUE TITLE
ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society (Brill, live) | Vor-/Nachname

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1412]
**URL**
https://brill.com/view/journals/jrat/6/2/article-p317_5.xml
IxTheo#2021-02-25#B3DE560E45BC7CD80B5CE6CF28B89E6CE6A1767A

**Ausführliche Problembeschreibung**
Der Datensatz wurde ohne Vorname eingespielt und der Nachname als Vorname verwendet:
![image](https://user-images.githubusercontent.com/57000004/109267473-e9f33100-7809-11eb-857c-d7a34daeb84a.png)

Test auf Nu mit Try RSS sieht ebenfalls so aus:
![image](https://user-images.githubusercontent.com/57000004/109267541-042d0f00-780a-11eb-91b3-bfb2669ccb92.png)

Lade ich halb-automatisch den Artikel mit Zotero, ist der Vorname da.
![image](https://user-images.githubusercontent.com/57000004/109267685-3d657f00-780a-11eb-92cf-459fc150add0.png)

**Comment by socheres** [comment]
Der String "Mar" ist in Negativliste enthalten: https://github.com/ubtue/zotero-enhancement-maps/blob/42bc56a9efaf6bd73f5ac4cc47a5049b435e912e/author_name_blacklist.txt#L318
Steh dort zwar in Großbuchstaben, aber die Mapping scheint nicht casesenstiv zu sein. Ich wüßte nicht, auf welcher Grundlage diese Liste erstellt wurde.

**Comment by IxKo** [comment]
Ich bin keine Theologin, aber ist das denn die Abkürzung eines bekannten Ordens oder Ähnlichem?

Ich habe nur eine inoffizielle Liste gefunden, da wird MAR jedoch nicht geführt: https://catholicdoors.com/misc/abbrev.htm

**Comment by IxTheoKm** [comment]
"Mar" ist m.W. eine Art Bischof in syrischen (u.a.?) Kirchen

**Comment by kdr154** [comment]
Liebe Andrea, liebe Kolleginnen,

Martina hat ganz Recht: https://de.wikipedia.org/wiki/Mar_(Titel)

Viele Grüße
Klaus

_________________________

Klaus-Dieter Rosenkranz
Eberhard Karls Universität Tübingen
Telefon: Universitätsbibliothek +49 7071 29 72963
Mobil: 0173 3194973

E-Mail: rosenkranz@uni-tuebingen.de


Von: A. Ko. <notifications@github.com>
Gesendet: Freitag, 26. Februar 2021 13:22
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2364-2807 | Interdisciplinary Journal for Religion and Transformation in Contemporary Society (Brill, live) | Vor-/Nachname (#1412)


Ich bin keine Theologin, aber ist das denn die Abkürzung eines bekannten Ordens oder Ähnlichem?

Ich habe nur eine inoffizielle Liste gefunden, da wird MAR jedoch nicht geführt: https://catholicdoors.com/misc/abbrev.htm

**Comment by kdr154** [comment]
@socheres Zur Liste:
https://de.wikipedia.org/wiki/Liste_der_Ordensk%C3%BCrzel_(r%C3%B6misch-katholisch)

**Comment by IxKo** [comment]
Da in diesem Fall der Nachname ganz entfallen ist, könnte man nicht über die QA-Settings solche Fälle in den Error-Dateien abfangen - mit einer passenden RegEx für 100a und 700a?
Vielleicht mit dieser RegEx?
`(?<=.),\s.
`

**Comment by socheres** [comment]
Ja, das ist eine gute Idee. TOP im nächsten Meeting.

**Comment by IxKo** [comment]
Die RegEx müsste aber noch überdacht werden, insbesondere hinsichtlich solchen Fällen:

https://github.com/ubtue/DatenProbleme/issues/1418#issuecomment-789700210

aus `William H. Ma` wurde `H., William`
Ein Nachname der nur aus einem Buchstaben und einem Punkt besteht, sollte auch immer überprüft werden.

**Comment by IxKo** [comment]
@mtrojan-ub Ich glaube, ich habe eine RegEx gefunden, die sowohl Fälle ausschließt, bei denen der Nachname nur aus einem Buchstaben und ggf. Punkt bestehen sowie Fälle, bei denen der Nachname gänzlich fehlt, und trotzdem andere Fälle akzeptiert wie mehrere Nachnamen mit oder ohne Bindestrich und mehrere Vornamen:

`\w+\S?\s?\w+?(?<=.),\s.+`
Das müsste dann für die Felder 100a und 700a in den QA-Settings eingestellt werden.

**Comment by IxKo** [comment]
und das bitte auch umsetzen, wenn es korrekt ist: https://github.com/ubtue/DatenProbleme/issues/1412#issuecomment-804022927

**Comment by mtrojan-ub** [comment]
Dazu folgende Fragen:
- `.` ist ein Platzhalter für beliebige Zeichen. Ist das auch wirklich so gemeint oder sollte zumindest innerhalb von `(?<=.)` eher `(?<=\.)` verwendet werden um tatsächlich einen Punkt zu matchen?
- `.+` am Ende lässt relativ viele Fehler zu
- `^` und `$` fehlen
- Lassen sich die vielen abwechselnden Klassen `\w`, `\S`, `\s`, `\w` und . auch etwas einfacher ausdrücken, oder können Sie bitte mit einigen positiven / negativen Beispielen erklären, wann der Regex matchen soll und wann nicht? Es lässt sich sonst nur schwer überprüfen, ob er so tatsächlich korrekt ist.

**Comment by IxKo** [comment]
Es soll matchen bei:
**Vor** dem Komma und Leerzeichen:
Nachname
Nachname-Nachname
Nachname Nachname
Nachname Nachname Nachname

**Nach** dem Komma Leerzeichen:
Vorname
V.
V. V.
V.V.
VV
Vorname Vorname
Vorname V.
usw. 
Hier beliebig viele (abgekürzte) Vornamen, wobei wahrscheinlich kaum jemand mehr als vier Vornamen hat.
 
Es soll nicht matchen bei:
Keinem Inhalt vor dem Komma Leerzeichen bzw. es darf nicht mit Komma beginnen
Einem oder mehreren Buchstaben mit Punkt (Der Nachname soll mind. aus zwei Buchstaben bestehen)

Zahlen im Namen sollten sowohl bei Vor- als auch Nachname ausgeschlossen werden.

Ich habe gerade nochmal rumgebastelt, aber mir stellten sich dann nur Fragen wie:
Kann man vielleicht nur ein negatives Lookaround machen, dass der ganze Ausdruck keine Zahlen enthalten darf?

Werden Sonderzeichen und Umlaute (ä, à etc.) berücksichtigt?

Das \S beim Nachnamen kann mit einem definierten Bindestrich - ersetzt werden, denn ein anderes Trennzeichen außer Bindestrick und Leerzeichen sind nicht gestattet. Das kleine \s soll für das Leerzeichen nach dem Komma stehen.

**Comment by mtrojan-ub** [comment]
Folgender Regex würde alle genannten Varianten abdecken:
`^(\w+(\s|-(\w+))*),\s?(\w(\.|\w*)(\s(\w(\.|\w*)))*)$`

`\w` matcht auch auf Sonderzeichen, aber dafür auch auf Zahlen. Es gibt Leute die um Zahlen auszuschließen stattdessen `[^\d\W]+` verwenden, das wird dann aber noch komplexer. Oder man führt einen zweiten separaten negativen Regex ein, der nicht auf den String matchen darf.

**Comment by IxKo** [comment]
Es kann bei spanischen Namen vorkommen, dass diese zwei Nachnamen haben und das ohne Bindestrich geschrieben wird. Daher muss der Bindestrich bei der Variante mit zwei Nachnamen optional sein:
`^(\w+(\s|-?(\w+))*),\s?(\w(\.|\w*)(\s(\w(\.|\w*)))*)$`

Könnte man statt \w definieren, dass nur Letter stehen dürfen - also keine Zahlen? Nur um einen solchen Fall mit Zahlen auch gleich herauszufiltern.

**Comment by IxKo** [comment]
Auch Nachnamen mit angeblich nur einem Buchstaben werden nicht abgefangen (bspw. B, Anton).
Doch dass ein Nachname nur aus einem Buchstaben besteht, wäre dann eher ein Indiz, dass ein abgekürzter Vorname zum Nachnamen wurde.

**Comment by IxKo** [comment]
@mtrojan-ub oder @jriedl 
Könnte das bald global für 100a und 700a umgesetzt werden?

`^(\w+(\s|-?(\w+))*),\s?(\w(\.|\w*)(\s(\w(\.|\w*)))*)$`

**Comment by jriedl** [comment]
Wäre es nicht sinnvoller, diesen Ausdruck zunächst einmal über eine gewisse Zeit bei einzelnen Zeitschriften zu testen? Wir waren ja schon mehrfach an dem Punkt, festzustellen, dass völlig allgemeine Regeln im Prinzip nicht aufzustellen sind.

**Comment by IxKo** [comment]
@jriedl
Könnte man es erst einmal nur auf NU einstellen?

**Comment by jriedl** [comment]
Ja, falls es im Vorfeld auf der Ebene einzelner Zeitschriften über einen längeren Zeitraum erfolgreich getestet wurde.

**Comment by IxKo** [comment]
Für


IxTheo | Cross currents : the journal of the Association for Religion and Intellectual Life | 0011-1953 | 1939-3881 | 166754854 | 357171608 | CRAWL | TEST | try&nbsp;crawl | try&nbsp;url | 288 | &nbsp;
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --




bei Feld 100 (regular article und review) auf Nu eingestellt. 
Alle automatisch gelieferten Datensätze zurückgesetzt.

**Comment by IxKo** [comment]
Leider scheint etwas mit der RegEx nicht hinzuhauen. Es landen nun alle Datensätze in den Errors. Selbst die einfachsten Namenformen:

Validating record IxTheo#2021-06-28#D802C657D879134BB4646169DB176437C00F8103...
Record IxTheo#2021-06-28#D802C657D879134BB4646169DB176437C00F8103 is invalid:
100: contents of subfield $a(Py, Fábio) did not match regex "^(\w+(\s|-?(\w+))*),\s?(\w(\.|\w*)(\s(\w(\.|\w*)))*)$"
record with URL 'https://muse.jhu.edu/article/783539' already in database with the same hash (D802C657D879134BB4646169DB176437C00F8103)

**Comment by IxKo** [comment]
@mtrojan-ub
Ich glaube es liegt daran, dass \w nur das "einfache" Alphabet erlaubt ohne Umlaute oder Apostrophe.
Kann das irgendwie geändert werden, sodass bspw. ein Björn oder André nicht aufgrund eines Buchstabens in den Error-Dateien landet?

**Comment by mtrojan-ub** [comment]
Ist das seit der Änderung für #1562 erledigt?

**Comment by IxKo** [comment]
Eventuell, die RegEx wurde nur an dieser Zs getestet und dem Issue nach zu schließen konnte es nur an einem Datensatz bestätigt werden.
Sicherheitshalber sollte es weiter getestet werden.

**Comment by kdr154** [comment]
Genauer gesagt nur an einem Aufsatz. Ich halte es auch für verfrüht, das Thema jetzt bereits abzuschließen.

**Comment by IxKo** [comment]
Ich habe am Freitag das Heft 2021,7 der Zs „Religions“ in der Test-DB gelöscht und resettet und ebenfalls die QA angepasst.

Leider sind alle Datensätze des Heftes nun in den Errors gelandet:

> Validating record IxTheo#2021-07-17#7CB71906E021133308FE53CDA67AEAA7DC3AC1C2...
> Record IxTheo#2021-07-17#7CB71906E021133308FE53CDA67AEAA7DC3AC1C2 is invalid:
> 100: contents of subfield $a(Oliver, Michael) did not match regex " ^((\p{L}+)+(\s|-?(\p{L}+))*),\s?(\p{L}+(\.|(\p{L}+)*)(\s((\p{L}+)(\.|(\p{L}+)*)))*)$"
> record with URL 'https://doi.org/10.3390/rel12060447' already in database with the same hash (7CB71906E021133308FE53CDA67AEAA7DC3AC1C2)

Ich weiß leider nicht, woran es liegt. Beim Test der RegEx auf regex101 scheint sie gut zu funktionieren.

**Comment by jriedl** [comment]
![image](https://user-images.githubusercontent.com/13135579/126150124-ebbbc5c0-f8ba-408e-ba2a-9173aebfb05b.png)

**Comment by IxKo** [comment]
Folgende Fälle sollten ausgeschlossen werden:
* Namenseintrag, bei dem der Nachname ausgeschlossen wurde und der Namenswert mit einem Komma beginnt:
 , Abc
* Nachnamen mit nur einem Buchstaben und ggf. Punkt
 X., Abc
 X, Abc

**Comment by jriedl** [comment]
Anbei wie besprochen der Regex-Vorschlag:

`^(?!(?:(\s*)|(\s*,\s*\S+)|(\S(\.?)\s*,\s*\S+))$)`

d.h. Negation folgender Fälle:
-leerer String `\s*`
-kein Nachname  `\s*,\s*\S+`
-Einzelbuchstabe und Punkt, dann beliebiger Vorname bzw. Einzelbuchstabe, dann beliebiger Vorname `\S(\.?)\s*,\s*\S+`

**Comment by IxKo** [comment]
Vielen Dank, ich habe es so in der QA der Zs "Religions" auf Nu geändert.

**Comment by IxKo** [comment]
Das neue Heft von Religions wurde ohne Probleme nun eingespielt:
Auszug:
![image](https://user-images.githubusercontent.com/57000004/126450943-8d7c308d-ef7b-4fdd-bf14-e5469ce22bde.png)


Ein Fall bei einer Muse-Zs wurde korrekt von der RegEx-Anforderung aussortiert:
Rapin, -Jacques statt  Rapin, Ami-Jacques

> Validating record IxTheo#2021-07-20#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3...
> Record IxTheo#2021-07-20#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3 is invalid:
> 100: contents of subfield $a(Rapin, -Jacques) did not match regex " ^((\p{L}+)+(\s|-?(\p{L}+))*),\s?(\p{L}+(\.|(\p{L}+)*)(\s((\p{L}+)(\.|(\p{L}+)*)))*)$"
> record with URL 'https://muse.jhu.edu/article/798272' already in database with the same hash (BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3)

Aus meiner Sicht kann die RegEx auf Nu global für die Felder 100a und 700a geschaltet werden.

**Comment by kdr154** [comment]
Aber es gibt doch oben den Vorschlag eines RegEx, der mögliche Fälle negiert. In meinen Augen ist das die bessere und einfachere Variante.

**Comment by jriedl** [comment]
Ja, da sind jetzt zwei Regexe im Spiel, der neue scheint ja nur für `Religions` gesetzt.

**Comment by kdr154** [comment]
Was die Verfasser angeht, ist das ok, es fehlt bei Religions aber immer noch die Artikel-ID. Siehe #1475

**Comment by IxKo** [comment]
> Aber es gibt doch oben den Vorschlag eines RegEx, der mögliche Fälle negiert. In meinen Augen ist das die bessere und einfachere Variante.

>Ja, da sind jetzt zwei Regexe im Spiel, der neue scheint ja nur für Religions gesetzt.

Ach stimmt, bei Muse ist noch eine andere RegEx im Test.

Ich habe dort (Zs Journal of the history of ideas) die RegEx für 100a der neuen angepasst und erwarte morgen das Ergebnis.

**Comment by kdr154** [comment]
Warum soll nicht der eine für alle genügen?

**Comment by IxKo** [comment]
> Warum soll nicht der eine für alle genügen?

Soll er schon. Ich habe nur vergessen/übersehen, dass bei der Muse-Zss noch der alte zum Testen drin war.

**Comment by jriedl** [comment]
> > Aber es gibt doch oben den Vorschlag eines RegEx, der mögliche Fälle negiert. In meinen Augen ist das die bessere und einfachere Variante.
> 
> > Ja, da sind jetzt zwei Regexe im Spiel, der neue scheint ja nur für Religions gesetzt.
> 
> Ach stimmt, bei Muse ist noch eine andere RegEx im Test.
> 
> Ich habe dort (Zs Journal of the history of ideas) die RegEx für 100a der neuen angepasst und erwarte morgen das Ergebnis.

Das Beispiel "Rapin, -Jacques" wird dann matchen, da es den formulierten Kriterien entspricht.

**Comment by IxKo** [comment]
> Das Beispiel "Rapin, -Jacques" wird dann matchen, da es den formulierten Kriterien entspricht.

Schade, könnte dann zur RegEx noch die Bedingung rein, dass der Vorname niemals mit einem Bindestrich beginnen soll bzw. dass nach dem Komma ein Buchstaben-String folgen soll und kein Zeichen wie ein Bindestrich?

**Comment by jriedl** [comment]
Zur Verbesserung der Lesbarkeit ;-):
`^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)`
`\p{P}` sind Interpunktionsbuchstaben.

**Comment by IxKo** [comment]
Ok! Ich habe es nun in den QA-Settings für beide Zss (Religions und Journal of the History of Ideas) für Feld 100a in das RegEx-Feld gesetzt.

**Comment by jriedl** [comment]
vgl. #1569.

**Comment by IxKo** [comment]
Leider ist heute aufgrund der RegEx kein Datensatz von den beiden Zss in der Test-DB eingespielt worden:


```
Validating record IxTheo#2021-07-21#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3...
Record IxTheo#2021-07-21#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3 is invalid:
100: contents of subfield $a(Rapin, -Jacques) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"
record with URL 'https://muse.jhu.edu/article/798272' already in database with the same hash (BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3)
```

```
Validating record IxTheo#2021-07-21#74972152B575EC4CF0CDF35A995FD0AFEC8C9730...
Record IxTheo#2021-07-21#74972152B575EC4CF0CDF35A995FD0AFEC8C9730 is invalid:
100: contents of subfield $a(Shah, Rebecca Supriya) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"
936: required subfield h is missing
record with URL 'https://doi.org/10.3390/rel12070550' already in database with the same hash (74972152B575EC4CF0CDF35A995FD0AFEC8C9730)
```

**Comment by kdr154** [comment]
Der RegEx ist stimmt nicht siehe #1569. Der abschließende Teil "\p{P}" ist Kommentar und muss weg.

**Comment by mtrojan-ub** [comment]
Habe den hinteren Teil entfernt

**Comment by IxKo** [comment]
Es scheint nun gut zu laufen. Im Error-Log ist nur ein Datensatz aufgrund der RegEx enthalten, den wir so auch gerne herausgefischt haben wollten:

> Validating record IxTheo#2021-07-25#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3...
> Record IxTheo#2021-07-25#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3 is invalid:
> 100: contents of subfield $a(Rapin, -Jacques) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)"
> record with URL 'https://muse.jhu.edu/article/798272' already in database with the same hash (BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3)

**Comment by IxKo** [comment]
Könnte die RegEx nun erst einmal global auf Nu eingesetzt werden zum weiteren Testen?

**Comment by mtrojan-ub** [comment]
Der Regex wurde nun auf nu global für 100a übernommen.
Sollte er bei erfolgreichem Test dann auch global für 700a übernommen werden?

(Die Übernahme der QS-Regeln von nu => ub28 scheint übrigens nicht automatisch zu erfolgen, daher bleibt die Regel wohl auch erstmal nur auf nu aktiv).

**Comment by IxKo** [comment]
Ja, gerne auch für 700a.
Dann haben wir noch mehr Namen, die dadurch getestet werden.

**Comment by jriedl** [comment]
Regel für 700a jetzt auf nu eingetragen

**Comment by IxKo** [comment]
Die RegEx scheint gut zu funktionieren. In den Errors ist nur ein Ausschuss dadurch und dieser ist korrekt, da ein Teil des Nachnamens verschwunden ist:

> Validating record IxTheo#2021-08-12#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3...
> Record IxTheo#2021-08-12#BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3 is invalid:
> 100: contents of subfield $a(**Rapin, -Jacques**) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)"
> record with URL 'https://muse.jhu.edu/article/798272' already in database with the same hash (BBC99DA05115FA8E8D5639F4FEFDB42B4ED7D8D3)

Man könnte es noch ein, zwei Wochen beobachten und dann auch ub28 übernehmen.

**Comment by IxKo** [comment]
Der Fall, dass gar kein Wert als Name steht, ist wohl noch nicht abgedeckt:
IxTheo#2021-08-11#0AAA8D0881E8B1895A7E2B83425ADADCB92BABA4
https://muse.jhu.edu/article/801820

![image](https://user-images.githubusercontent.com/57000004/129577581-c940ffa3-8498-4d2e-b6d9-8c7daade7e1d.png)

Geliefert haben wir den Datensatz so:
```

<datafield tag="100" ind1="1" ind2=" ">
<subfield code="4">aut</subfield>
<subfield code="a">, </subfield>
<subfield code="e">VerfasserIn</subfield>
</datafield>
```

Könnte die RegEx bitte noch um diesen Fall ergänzt werden. Er sollte in den Errors landen.

**Comment by jriedl** [comment]
`^(?!(?:(\s*(?:,\s*)?)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)`

**Comment by IxKo** [comment]
@mtrojan-ub 
Könnte diese neue RegEx wieder global auf Nu eingestellt werden?

**Comment by IxKo** [comment]
Die RegEx scheint gut zu funktionieren. Die folgenden drei Einträge wurden auf der Test-DB als fehlerhaft 
(, Patmisari)
(Rapin, -Jacques)
(, Jahangir)

Ich glaube, der neue Ausdruck ist noch nicht umgesetzt, um auch ganz leere Namen damit zu filtern?
Momentaner RegEx laut Error-Log:
`^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)`

Aus meiner Sicht kann es auf ub28 umgesetzt werden.

**Comment by IxKo** [comment]
Die Namens-Blacklist habe ich gestern deutlich verschlankt.
Dadurch sollte es auch zu weniger Fällen kommen, in denen ein ganzer Namensbestandteil fehlt.

**Comment by jriedl** [comment]
> `^(?!(?:(\s*(?:,\s*)?)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)`

Auf nu und ub28.
