### ISSUE TITLE
EBSCO Translator Multi

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1413]
**URL**
Bsp: Zeder-Zeile 241

**Ausführliche Problembeschreibung**
Mir werden gar keine Translator für den Multi-DL auf EBSCO angeboten. Das war aber mal der Fall.

Im Single-DL wird EBSCOhost angeboten.

**Comment by kdr154** [comment]
Kann ich bestätigen. Bekomme ebenfalls kein Multi angeboten.

**Comment by IxKo** [comment]
Work-Around über Ebsco-Funktion "Folder":
![image](https://user-images.githubusercontent.com/57000004/109513740-b2a0b080-7aa5-11eb-9c72-ddb3300f4b73.png)

gespeicherte Daten im Folder via RIS-Format nach Zotero exportieren

**Comment by socheres** [comment]
Problem mit Multi-DL von offizieller zotero-translators behoben.
