### ISSUE TITLE
ISSN 2150-9301 Religion and society : advances in research - Keine Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#142]
Bei dieser Zeitschrift kommen die Keywords nicht mit:
https://www.berghahnjournals.com/view/journals/religion-and-society/religion-and-society-overview.xml
https://www.berghahnjournals.com/view/journals/religion-and-society/9/1/arrs090109.xml

**Comment by shadeMe** [comment]
Wir haben dieses Problem schon behoben oder?

**Comment by kdr154** [comment]
Bei mir kamen gerade keine Keywords mit.

 

 

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Dienstag, 8. Januar 2019 15:49
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2150-9301 Religion and society : advances in research - Keine Keywords (#142)

 

Wir haben dieses Problem schon behoben oder?

**Comment by shadeMe** [comment]
Wird der richtige Translator benutzt? Es sollte 'Berghahn Journals' zeigen, wenn der Cursor auf dem Zotero Knopf steht. 

Ich hab's gerade probiert und es schient z.B bei https://www.berghahnjournals.com/view/journals/religion-and-society/9/1/arrs090104.xml zu funktionieren.

**Comment by kdr154** [comment]
Ist in Ordnung jetzt
