### ISSUE TITLE
ISSN 2254-2043 | Boletín criminológico | spanische Personennamen (Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1420]
https://revistas.uma.es/index.php/boletin-criminologico/issue/view/763

Personennamen mit einem abgekürzten 2. Vornamen in der Form BuchstabePunkt werden allesamt falsch umgesetzt.
Der abgekürzte Vorname wird zum ersten Bestandteil des Nachnamens. Beispiele:
V. Komatsu, Andre
R. Bazon, Marina
S. Cardoso, Carla
R. Oliveira, Andre

Das ist auch bei anderen spanischsprachigen Zeitschriften so, bei denen der Name analog angegeben wird.

Bei Rafaelle Cs Costa hingegen, wird das "Cs", was immer es bedeuten mag, entfernt

**Comment by jriedl** [comment]
CS ist Teil der `author_name_blacklist.txt`. Für Einzelbuchstaben mit Punkt gibt es jetzt auf nu eine zusätzliche Regel im Harvester, die ein Umstellen unterdrückt.

**Comment by kdr154** [comment]
In dem vorliegenden Fall werden die Autorennamen nun korrekt umgesetzt.
