### ISSUE TITLE
ESSN 2293-7374 | Renaissance and reformation | Verfasser bei Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1422]
https://jps.library.utoronto.ca/index.php/renref/issue/view/1976
https://jps.library.utoronto.ca/index.php/renref/article/view/29529

Die Umsetzung der Verfasser bei Rezenionen in dieser Zeitschrift ist ausgesprochen unglücklich:

![grafik](https://user-images.githubusercontent.com/29707105/109975486-f809eb80-7cfa-11eb-845a-41827d6e2dc3.png)

Verwendet wurde der Open_Journal_System-Translator. Mit den anderen ist das Ergebnis leider dasselbe.

**Comment by helenanebel** [comment]
Lieber Herr Rosenkranz,

Ich werde das entsprechend anpassen, dazu noch zwei Fragen:
Soll bei den Reviews dann hier gleich der RezensionstagPica gesetzt werden?
Soll ich diesen und zusätzlich den Exporttranslator so anpassen, dass der Buchautor für die 3050 gleich mitkommt?

Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Wäre schön, wenn das RezensionstagPica mitgesetzt wird.
Wichtig ist, dass der Review Author immer als erster Verfasser genannt wird. 
3050 haben wir bisher nicht im halbautomatischen Verfahren vergeben. Würde in diesem Fall auch Nachbearbeitung erforden, da es ja auch Editoren gibt und im Hinblick auf das Beziehungskennzeichen in $4
Wenn ich mir dir bisher katalogisierten Hefte anschaue, haben wir die immer unter den Tisch fallen lassen. 
Aber es ist natürlich ein Desiderat und wurde von dem ein oder der anderen Katalogisierin auch gemacht. Jedoch nicht bei dieser Zeitschrift.
Man könnte es versuchen. Wenn es nicht klappt, sind die Einträge auch schnell gelöscht.

P.S.
Wir verwenden hier keine Klarnamen, weil die hier diskutierten Sachen öffentlich sichtbar sind.

**Comment by helenanebel** [comment]
Lieber kdr154,

Vielen Dank für die Info!

**Comment by helenanebel** [comment]
Lieber kdr154,

ich habe das jetzt so gelöst:
![grafik](https://user-images.githubusercontent.com/49190455/116671572-61c41000-a9a1-11eb-84c4-455fed0bfb47.png)
Es kommen nur die rezensierten Autoren, nicht aber Herausgeber usw. mit; diese wären nach Pica sowieso nicht betroffen, es gibt nur VerfasserIn des Bezugswerks | ant als Beziehungskennzeichnung in 3050.
Die rezensierten Autoren landen dann in einem eigenen Zotero-Feld "reviewedAuthor". Dieses wird momentan noch nicht vom Export-Translator verarbeitet.
Das würde ich aber ebenfalls entsprechend anpassen, weil es ja schade wäre, die Information zu vergeuden.

Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Das ist der Import in Zotero. Entscheidend ist, was der Export-Translator PicaSWB_batch.js daraus macht. Das kann ich nicht sagen. Ich könnte mir aber vorstellen, dass die Bezeichnung bei den Feldern nicht ausschlaggebend ist, in welchem Pica-Feld die Verfasser landen. Sondern, dass einfach der 1. Eintrag (hier Rezensierter Autor) in 3000 landet und die beiden anderen in 3010. Möglicherweise wird auch ein Feld "Rezensierter Autor" gar nicht oder falsch verarbeitet. Das müssten wir überprüfen.

**Comment by helenanebel** [comment]
Lieber kdr154,

ich habe das überprüft, bei deer Export-Generierung und auch im Code, der Export-Translator übernimmt nur Angaben mit dem creatorType "author". Das heißt, dass die reviewedAuthor-angaben momentan noch verfallen.
Soll ich das dann anpassen oder nicht?

Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Erst mal nicht anpassen. Das sind schwerwiegendere Anpassungen, die auch mit Herrn Kim abgesprochen werden sollten. Es sind doch viele Personen die mit dem Translatoren arbeiten und wir sollten zum Einen aufpassen, dass das nicht auseinander läuft, zum anderen, dass sie auch funktionieren. Erst vor Kurzen gab es einen Fall, dass der Batch-Export-Translator angepasst wurde. Offensichtlich wurde diese Anpassung nicht an alle MitarbeiterInnen verteilt, so dass eine Kollegin dann keinen Multi-Upload mehr machen konnte.
Dieser Translator ist auch insofern ein Spezialfall, als ein Sacherschließer einige Hefte nachkatalogisiert haben wollte. Leider hatten die Hefte ziemlich viele Artikel. 
In meinen Augen würde es in diesem Fall genügen, wenn nur der Verfasser der Rezension geliefert wird. Dieser aber schon und nicht etwa die oder der Verfasser des rezensierten Werks. Wenn dem Sacherschließer daran gelegen ist, diese ebenfalls zu erfassen, kann er es ja tun. Hat er aber bis jetzt nicht gemacht.

**Comment by kdr154** [comment]
Nachtrag: den Import-Tranlator können Sie natürlich gerne anpassen, beim Export-Translator würde ich aber Rücksprache halten.

**Comment by socheres** [comment]
Fix durch @helenanebel: Autoren/Herausgeber des rezensierten Werkes werden vor dem Titel vorangestellt. Nur Reviewer werden als VerfasserIn ausgegeben.

**Comment by kdr154** [comment]
Welchen Translator soll man denn hier nehmen? Mir wird der Multi-Wrapper und der Open Journal System Standard angeboten. Bei beiden ist es noch wie zuvor: 
Bsp:
https://jps.library.utoronto.ca/index.php/renref/article/view/31623
sieht bei beiden folgendermaßen aus:


![grafik](https://user-images.githubusercontent.com/29707105/117127916-04630100-ad9d-11eb-889f-99a741a73228.png)

**Comment by helenanebel** [comment]
Lieber kdr154,

in der Tat, ich hatte mal wieder nicht bedacht, dass die Entwicklungsumgebung andere Ergebnisse produziert als das Browser-Plugin.
Das müsste dann mit dem obigen Commit gefixt sein.
Entschuldigen Sie die Umstände.

Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Hat sich noch nichts verändert. Sind den die Überarbeitungen überhaupt schon  in meinem Translatorverzeichnis angekommen?

**Comment by helenanebel** [comment]
Lieber kdr154,

wie vorher beschrieben muss socheres zuerst meine Änderungen akzeptieren, danach werden diese dann ausgeliefert. Ich habe darauf momentan noch keinen Einfluss; ich nehme an, dass socheres die Issues auf "ready for testing" setzt, sobald diese in Ihrem Verzeichnis sind.

Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Die vorletzte PR hatte ich bestätigt und alle Translator-Order aktualisiert. Die neue PR steht noch aus.

**Comment by kdr154** [comment]
Danke für die Info. Dann warten wir noch ein bisschen.

**Comment by kdr154** [comment]
Mit dem Multi_Wrapper sieht die Sache super aus:
Bsp:
https://jps.library.utoronto.ca/index.php/renref/article/view/29534

![grafik](https://user-images.githubusercontent.com/29707105/127999509-23597f28-5baf-4e35-9066-66f3254427a1.png)

mit dem ubtue_open_journal_systems_standard hingegen nicht:

![grafik](https://user-images.githubusercontent.com/29707105/127999679-b1b9a1cd-57ac-4a0f-9ed1-2a555a087a81.png)

**Comment by helenanebel** [comment]
Lieber @kdr, die Anpassungen hatte ich am Multi-Wrapper vorgenommen. Gerne passe ich noch den Standard an, da wir uns ja zwischenzeitlich auf diesen als unseren Standard geeinigt hatten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel 
Ich habe das Label Ready for testing entfernt. Bitte setz es einfach wieder, wenn Du die Anpassung am Translator ubtue_open_journal_systems_standard gemacht hast und wieder getestet werden kann. :-)

**Comment by IxKo** [comment]
Danke, ist gut umgesetzt:
![image](https://user-images.githubusercontent.com/57000004/141979684-4c668ae3-9037-4839-988e-e0c05030c07a.png)

Auch die Rezensionen werden automatisch erkannt und getagt.
