### ISSUE TITLE
ISSN 0718-3399 | Política criminal | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1423]
Das Abstract enthält immer auch die Keywords. Z. B. hier:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-33992019000100419&lng=en&nrm=iso&tlng=en

![grafik](https://user-images.githubusercontent.com/29707105/109981764-82ede480-7d01-11eb-85c8-7d37401a8c68.png)

Gibt es neben den Abstracts in zwei Sprachen noch ein drittes in einer weiteren Sprache, werden zwei zu einem zusammengezogen und ein weiters zweites erstellt:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-33992019000100549&lng=en&nrm=iso&tlng=en

![grafik](https://user-images.githubusercontent.com/29707105/109982805-8a61bd80-7d02-11eb-97c6-5d7e7ea7ce6c.png)

**Comment by jriedl** [comment]
Aktualisierter Translator auf nu.

**Comment by kdr154** [comment]
Das  ist gelöst.
