### ISSUE TITLE
ISSN 0718-3399 | Política criminal | Keywords 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1424]
In der Regel wird ein Set an Keywords erstellt, das einer der zwei Seiten entnommen wird, in denen das Abstract existiert:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-33992019000100520&lng=en&nrm=iso&tlng=en

![grafik](https://user-images.githubusercontent.com/29707105/109983625-4d49fb00-7d03-11eb-9c70-ac8557ad2986.png)

In der Regel werden die englischen erfasst, die spanischen vernachlässigt.

Gelegtlich aber werden gar keine erstellt, obwohl es sie gibt. z. B. hier:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-33992019000100376&lng=en&nrm=iso&tlng=en

![grafik](https://user-images.githubusercontent.com/29707105/109984445-12949280-7d04-11eb-869a-e3918f2b5491.png)

Darüber hinaus werden sie auch immer mit in das Abstract aufgenommen.

**Comment by jriedl** [comment]
Aktualisierter Translator auf nu.

**Comment by kdr154** [comment]
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-33992019000100047&lng=en&nrm=iso&tlng=en
In diesem Fall werden die Keywords immer noch nicht übernommen. Kein Tag 650:

![grafik](https://user-images.githubusercontent.com/29707105/112299010-aae4be00-8c97-11eb-8e50-90564e6e919f.png)

**Comment by jriedl** [comment]
Aktualisierter Translator auf nu.

**Comment by kdr154** [comment]
Die Probleme sind behoben.
