### ISSUE TITLE
1467-8519 | Bioethics | 4950 doppelt https://doi.org/

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1429]
**URL**
https://onlinelibrary.wiley.com/toc/14678519/2021/35/3?campaign=woletoc

**Ausführliche Problembeschreibung**
In 4950 wird doppelt https://doi.org/ geschrieben, weil der DOI bereits mit diesem String in Zotero abgegriffen wird:

![image](https://user-images.githubusercontent.com/57000004/110122213-9a8ba280-7dbf-11eb-9069-f864025c7a35.png)

Und das führt dann zu:
`\n4950 https://doi.org/https://doi.org/10.1111/bioe.12820$xR$3Volltext$4ZZ$534`

**Comment by IxKo** [comment]
Wird bei mir immer noch doppelt ausgegeben.

**Comment by kdr154** [comment]
Dasselbe beim Journal of addictions & offender counseling
https://onlinelibrary.wiley.com/loi/21611874
Ebenfalls Wiley:
![grafik](https://user-images.githubusercontent.com/29707105/110308956-0b6dcd00-8001-11eb-83fa-b9ff6554e0be.png)

**Comment by socheres** [comment]
für zotkat testen.

**Comment by jriedl** [comment]
Es handelt sich hier um ein Translatorproblem: Die DOI darf nicht als URL angegeben werden (vgl Feld MARC 24). Habe es jetzt behoben und auf nu eingespielt.

**Comment by IxKo** [comment]
Danke, für das semi-automatische Verfahren ist der Fehler behoben!

**Comment by IxKo** [comment]
Beim Testen auf Nu mit TRY RSS wird es auch nicht mehr doppelt ausgeführt:
![image](https://user-images.githubusercontent.com/57000004/110788333-c4850f00-826e-11eb-9a02-be9a00664897.png)


Wie wird 4950 $xR dann eigentlich erzeugt? In unseren gelieferten Marc-Daten finde ich dazu keine Information/kein Unterfeld.
