### ISSUE TITLE
Analecta Cracoviensia

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#143]
Bei dieser Zeitschrift kommt immer die 0 ins Feld Ausgabe. Sie wird nicht benötigt und sollte unterdrückt werden.  Beispiel eines Aufsatzes:
http://czasopisma.upjp2.edu.pl/analectacracoviensia/article/view/2405

**Comment by shadeMe** [comment]
Gilt das allgemein für alle Zeitschriften oder nur für diese? Wenn es der erstere wäre, können wir die Änderung auf der Harvester-Ebene (im Gegensatz zu der Translator-Ebene) umsetzen.

**Comment by kdr154** [comment]
Das gilt nicht für alle Zeitschriften, aber auch nicht nur für diese. Möglicherweise aber für alle, die mit dem Translator Open Journal Systems bearbeitet werden und die analog gezählt werden.

**Comment by kdr154** [comment]
Auch nach einem aktualisieren des OJS Translators vom Repositiorium steht die 0 weiterhin im Feld Ausgabe

**Comment by kdr154** [comment]
gelöst
