### ISSUE TITLE
ISSN 1572-8315 | Journal of experimental criminology | Fehlende Artikel Krimdok live

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1430]
Von diesem Heft: https://link.springer.com/journal/11292/volumes-and-issues/16-4
fehlen der 1., 2., 4. und 6. Artikel.
Beim aktuellen Heft https://link.springer.com/journal/11292/volumes-and-issues/17-1
sind alle vorhanden.

Nun weiß ich nicht, da es die erste automatische Einspielung bei dieser Zeitschrift war, ob dies darauf zurückzuführen ist, dass nur das aktuelle Heft eingespielt werden soll, oder ob es ein grundsätzlicher Fehler des Harvesters ist. Die Einspielung hat am Freitag auf Samstag stattgefunden. Nachgeliefert wurde nichts.

**Comment by jriedl** [comment]
Das hängt wohl mit dem RSS-Feed zusammen. Eine Anfrage an den Verlag wegen Freischaltung des Crawling-Verfahrens läuft.

**Comment by jriedl** [comment]
Kommunikation mit dem Verlag hat ergeben, dass eine API auf Artikelebene existiert. Beispiel-Sample für diese Zeitschrift (JSON): 

[journal_of_experimental_criminology_sample.txt](https://github.com/ubtue/DatenProbleme/files/6228894/journal_of_experimental_criminology_sample.txt)

 In meinen Augen ist die Qualität hoch und könnte mit einer geeigneten Integration in den ZTS verwendet werden, allerdings wäre die Bitte, das gerade im Vergleich zum aktuellen Ansatz noch einmal zu überprüfen.

**Comment by kdr154** [comment]
Wie soll das überprüft werden?

**Comment by jriedl** [comment]
Am besten wahrscheinlich Stichproben aus obiger Datei mit den Ergebnissen von tryURL für die gleiche DOI vergleichen. Das eigentliche Problem von "durchrutschenden" Artikeln sollte durch die API gelöst sein, da hier die Hefte immer vollständig nachgewiesen sind. Die Frage ist, ob es derzeit mit dem Scraping-Ansatz _essentielle_ Felder gibt, die uns so verloren gehen, da sie in den `JSON`-Daten nicht vorhanden sind.

**Comment by kdr154** [comment]
Inzwischen sind alle Artikel vorhanden.
