### ISSUE TITLE
ISSN 0043-2040 | Wege zum Menschen | Titelzusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1431]
**URL**
https://www.vr-elibrary.de/doi/10.13109/weme.2021.73.2.99

**Ausführliche Problembeschreibung**
Der Titelzusatz wird nicht nach Zotero übernommen.
Single-Dl, Translator: Atypon Journals

**Comment by IxKo** [comment]
Ich nehme Option 2 mit den Zusatztiteln :-)

**Comment by socheres** [comment]
Dieses Issue wurde bereits gefixt.

**Comment by IxKo** [comment]
Passt nun, danke!
