### ISSUE TITLE
Allgemein: Lizenzinformation lizenzpflichtig ZZ

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1432]
Momentan werden nur reine lizenzfreie Zss mit einer Lizenzinformation in 4950 $4 (Marc 856z) eingespielt.

Alle anderen Zss erhalten keine Lizenzinformation in 4950 $4. Es wäre jedoch gut, wenn diese Zss $4ZZ für lizenzpflichtig erhielten, da die Lizenzinformation seit einem Jahr eine Pflichtangabe ist (siehe Screenshot).

![image](https://user-images.githubusercontent.com/57000004/110330257-dcb21f80-801d-11eb-9390-ffce1c515736.png)

Dazu müsste die zweite Zeile bei jedem Datenfeld 856 ergänzt werden:
```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="z">Lizenzpflichtig</subfield>
```

**Comment by jriedl** [comment]
Auf nu. Für die kostenfrei-Einspielung hinterlegen wir in 856$z `LF`. In Analogie bin ich jetzt davon ausgegegangen, dass hier auch `ZZ` geliefert werden soll und die Umsetzung auf den String `Lizenzpflichtig` durch das BSZ erfolgt. Es werden wie besprochen alle nicht-`LF`-Artikel mit `ZZ` getagged.

**Comment by IxKo** [comment]
Dann muss diese Lieferung mit dem BSZ abgeklärt werden @socheres ?

**Comment by jriedl** [comment]
Was zeigen denn die heute Nacht eingespielten Daten in der Testdatenbank an?

**Comment by IxKo** [comment]
Ach Verzeihung! Dass bereits eine Änderung auf Nu vorgenommen wurde, war mir nicht klar.
Die Test-Daten von heute haben alle $4ZZ
![image](https://user-images.githubusercontent.com/57000004/111287086-2a90de00-8643-11eb-9abd-895bb965c0b0.png)

Allerdings auch die OA-Artikel wie bspw. https://onlinelibrary.wiley.com/doi/10.1111/moth.12682:
![image](https://user-images.githubusercontent.com/57000004/111287192-46947f80-8643-11eb-97b0-efec1672017e.png)

**Comment by jriedl** [comment]
Erscheint mir dann etwas inkonsistent, dass "LF" zulässig ist und korrekt zu "kostenfrei" umgesetzt, "ZZ" aber literal übernommen wird. Wir können natürlich "Lizenzpflichtig" selbst eintragen, wenn es ohne großen Aufwand durch das BSZ anpassbar ist, erscheint mir das als die saubere Lösung. 
Im Fall von https://onlinelibrary.wiley.com/doi/10.1111/moth.12682 erhalten ich bei Tests kein "LF" vom Translator, deshalb wird "ZZ" gesetzt.

**Comment by IxKo** [comment]
@jriedl Das Ergebnis $4ZZ oder $4LF im K10plus ist korrekt.
Laut dem MARCxml-Format müssten wir es eigentlich anders liefern, aber es wurde wohl mit dem BSZ geklärt, dass wir es so liefern können und der Wert dann wohl 1 zu 1 übernommen wird. 

Ganz korrekt wäre:
`<subfield code="z">Kostenfrei</subfield>`
oder
`<subfield code="z">Lizenzpflichtig</subfield>`


Zu den OA-Artikeln:
Wenn der Translator LF liefert, wird es **nicht** mit ZZ überschrieben. Ich habe es soeben auf Nu mit Beispielen von Brill, Sage und T&F getestet.
Also sieht nun alles gut aus!
Vielen Dank!
