### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Artikelnummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1433]
In einem Fall wird die Artikelnummer erfasst, im anderen nicht.
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/issues
Bei der Issue in Progress wird 936 mit $y gelöst: 
![grafik](https://user-images.githubusercontent.com/29707105/110347609-150f2900-8031-11eb-80eb-27abb9dd915e.png)

Bei der abgeschlossenen Ausgabe fehlt es: 

![grafik](https://user-images.githubusercontent.com/29707105/110347737-32dc8e00-8031-11eb-936c-b7ff1d872b53.png)

Artikelnummer sollten aber prinzipiell anders gelöst werden. Mit $i.
Siehe #1416

**Comment by jriedl** [comment]
$i sollte jetzt verwendet werden.

**Comment by kdr154** [comment]
wird verwendet.
