### ISSUE TITLE
ISSN 1749-4915 | Journal for the study of religion, nature and culture | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1434]
Anstelle des Abstracts wird im Feld Zusammenfassung der Titel wiederholt:
https://journals.equinoxpub.com/JSRNC/article/view/42736
![grafik](https://user-images.githubusercontent.com/29707105/110438432-a96f9f00-80b6-11eb-96d7-bb58700710e7.png)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
bei mir läut der Translator gar nicht bei diesem Artikel, es wird stattdessen ein anderer verwendet. Könnten Sie das bei sich ausprobieren und mir mitteilen, ob das Problem bei Ihnen ebenfalls auftritt?
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Ich bin mir ziemlich sicher, dass der Download damals mit dem ubtue_equinox-Translator gemacht wurde. Dieser wird mir aber nicht mehr angeboten. 
Im Multi-DL führt sowohl der Multi-Wrapper als auch der OJS_Standard zum Abbruch.
Im Single funktioniert der OJS (nicht der Standard, der führt zum Abbruch).  Allerdings fehlt hier das Abstract. Den Equinox gibt es hier ebenfalls nicht.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
wie wir gestern festgestellt haben, gibt es zwei Layouts bei Equinox, das "ursprüngliche" und das OJS-Layout. Ich habe jetzt den ubtue_Open Journal Systems Standard für diesen Fall angepasst. Dieser müsste Ihnen dann, sobald Herr Kim Ihre Translators geupdated hat, auch angezeigt werden. Der Equinox-Translator greit bei den OJS-URLs gar nicht mehr, weil diese einem anderen Muster folgen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @kdr154 , lieber @socheres , liebe @IxKo ,
ich würde empfehlen, dass wir einen der OJS-Translator als unseren "Standard" auswählen, also entweder Standard oder Multi-Wrapper, sodass dann die Verbesserungen alle in einem Translator vorgenommen werden und auch immer dieser verwendet wird. Sonst gibt es hier glaube ich häufig Verwirrung.
Ich setze diesbezüglich mal auf "for meeting discussion".
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
@helenanebel die Änderung könnte Seiteneffekt haben z.B. bei https://verbumetecclesia.org.za/index.php/ve/article/view/2076 bricht ab.

**Comment by helenanebel** [comment]
Lieber @socheres ,
bei dieser Zeitschrift sind ganz viele verschiedene Probleme aufgetreten, ich habe das gefixt. Die Tests funktionieren jetzt alle.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Eine Sache ist nicht wirklich schön. Dort, wo kein eigentliches Abstact gibt, steht der Titel im Abstract. Das entspricht aber der Vorlage. In meinen Augen kann man es so lassen.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich vermute, dass das Absicht ist, da bei Rezensionen die rezensierte Ressource noch genauer beschrieben wird als im eigentlichen Titel. Wirklich schön ist das nicht, aber wenn da mehr als nur der Titel steht, ist es schwierig, das Abstract zu löschen, weil der Anfang ja auch zufällig gleich sein könnte, obwohl es ein richtiges Abstract ist.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Das lassen wir so und entfernen es bei Bedarf manuell

**Comment by RelBibRetroKat** [comment]
Bei der letzten Ausgabe der Zeitschrift wurden die Untertitel doppelt eingespielt (PPNs 1763826694  1763826872   1763827011. Es ist bei der Sacherschließung aufgefallen. Ich weiß nicht, wer das Heft bearbeitet hat. Wenn nur ein bestimmter Translator verwendet werden soll, müßte man ggf. eine Bemerkung in Zeder machen.
