### ISSUE TITLE
Abrufzeichen krzom für die Kriminologie

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1435]
Es müsste folgender Code erzeugt werden:
```

<datafield tag="887" ind1=" " ind2=" ">
<subfield code="a">
Autor in der Zoterovorlage [Nachname, Vorname] maschinell zugeordnet
</subfield>
<subfield code="2">krzom</subfield>
</datafield>

```

**Comment by socheres** [comment]
Beim GND-Lookup-Match für Krimdok muss statt "ixzom" "krzom" heißen. @jriedl @mtrojan-ub könnt Ihr das bitte ändern?

**Comment by socheres** [comment]
@mtrojan-ub ist die Änderung bereits auf ub28?

**Comment by mtrojan-ub** [comment]
Ja, der Code wurde am Montag auf ub28 eingespielt.

**Comment by IxTheoKm** [comment]
Die Einspielungen haben aber im K10plus alle noch ixzom.

**Comment by mtrojan-ub** [comment]
Ich habe versucht, einen entsprechenden Fall zu finden. In den aktuellen Live-Daten `krimdok_zotero_210325_001.xml` habe ich folgendes Beispiel entdeckt:

![grafik](https://user-images.githubusercontent.com/26873381/112651171-6d756180-8e4c-11eb-885c-f8ffc0c27e26.png)

Dieser Teil (... maschinell zugeordnet...) scheint also korrekt zu sein.

Wenn man in den gelieferten KrimDok-Daten nach `ixzom` sucht, springt allerdings etwas anderes ins Auge, und zwar im Kontext `ORCID`:
![grafik](https://user-images.githubusercontent.com/26873381/112651453-b1686680-8e4c-11eb-817b-7a55f187a021.png)


In der globalen Section der zotero_harvester.conf befindet sich aktuell folgende Zeile:
`add_marc_field_887                         = "8873 \037aorcid: %orcid% | taken from website\0372ixzom"`

Durch diese Einstellung wird `ixzom` bei allen Zeitschriften gesetzt, egal ob IxTheo oder KrimDok. Ist das die Stelle auf die sich das gemeldete Problem bezieht?

Falls ja => ich bin mir nicht sicher ob es in der Conf bereits möglich ist, solche Einstellungen auf Gruppenebene durchzuführen. Eine Lösungsmöglichkeit wäre, das ggf. einzuführen.

**Comment by kdr154** [comment]
Scheint so zu sein

**Comment by jriedl** [comment]
Anpassung im Code und in Config auf nu. Nach erfolgreichem Test würde  Einspielung auf ub28 erfolgen.

**Comment by kdr154** [comment]
Im Zusammenhang mit der Orcid wird jetzt ebenfalls krzom gesetzt.
