### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1436]
Rezensionen werden nicht getagt:
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/vol/64/suppl/C
https://www.sciencedirect.com/science/article/pii/S1756061620304894

![grafik](https://user-images.githubusercontent.com/29707105/110463152-d67d7b00-80d1-11eb-8351-673b5e692ff4.png)

**Comment by jriedl** [comment]
Tritt mit tryURL für https://www.sciencedirect.com/science/article/pii/S1756061620304894 derzeit auf nu nicht mehr auf.

**Comment by kdr154** [comment]
Passt auch.
