### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1437]
Abstracts werden bei den Artikeln von abgeschlossenen Ausgaben abgeschnitten:
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/issues
https://www.sciencedirect.com/science/article/pii/S1756061620304870

![grafik](https://user-images.githubusercontent.com/29707105/110463496-4429a700-80d2-11eb-9c9f-0403fb75c693.png)

Bei den Ausgaben "In progress" hingegen nicht: 
https://www.sciencedirect.com/science/article/abs/pii/S1756061621000021

![grafik](https://user-images.githubusercontent.com/29707105/110464136-0e38f280-80d3-11eb-87e1-16a3d3f1dceb.png)

**Comment by jriedl** [comment]
Tritt mit tryURL für https://www.sciencedirect.com/science/article/pii/S1756061620304870 auf nu derzeit nicht mehr auf.

**Comment by kdr154** [comment]
Ist nicht  mehr der Fall.
