### ISSUE TITLE
ISSN 1876-763X | International journal of law, crime and justice | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1438]
https://www.sciencedirect.com/journal/international-journal-of-law-crime-and-justice/issues
Keywords werden bei den abgeschlossenen Ausgaben nicht erfasst:
https://www.sciencedirect.com/science/article/pii/S1756061620300227

![grafik](https://user-images.githubusercontent.com/29707105/110464755-d41c2080-80d3-11eb-9f8a-b92815f3c342.png)

Marc 650 fehlt.

Bei den Ausgaben "In progress" hingegen schon:

https://www.sciencedirect.com/science/article/abs/pii/S1756061621000021

![grafik](https://user-images.githubusercontent.com/29707105/110464979-22c9ba80-80d4-11eb-9f9f-2ee7e3177d68.png)

**Comment by jriedl** [comment]
Tritt mit tryURL bei https://www.sciencedirect.com/science/article/pii/S1756061620300227 derzeit nicht mehr auf.

**Comment by kdr154** [comment]
Auch bei einem kompletten Durchlauf nicht mehr.
