### ISSUE TITLE
ISSN 0181-6799 Réforme, humanisme, renaissance DOI fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#144]
Bei dieser ZS wird der DOI nicht mit übertragen. Er finder sich unten auf der Seite
Beispiel eines Aufsatzes:
https://www.cairn.info/revue-reforme-humanisme-renaissance-2018-2-page-9.htm

**Comment by kdr154** [comment]
Nicht mehr Bestand von nu? Vgl. #145

**Comment by kdr154** [comment]
Fehlt immer noch.

**Comment by shadeMe** [comment]
Funktioniert auf meiner Seite. Bitte den Translator "Cairn.info" aktualisieren.
![Screenshot_20190402_123859](https://user-images.githubusercontent.com/214450/55396588-83453a00-5544-11e9-9ba8-1c4ede595d27.png)

**Comment by kdr154** [comment]
Gelöst
