### ISSUE TITLE
ISSN 1552-8448 | Violence against women | Schlagwort Article Commentary

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1440]
Bei diesem Artikel https://journals.sagepub.com/doi/full/10.1177/1077801220958491 wird das Sachschlagwort "Article Commentary" erzeugt. 
![grafik](https://user-images.githubusercontent.com/29707105/111132862-2482fa80-857a-11eb-8aaa-7258d295c1f7.png)

Wenn, dann sollte es ein Formalschlagwort sein.
Wobei ich nicht erkennen kann, woher der Harvester seine Information bezieht.

**Comment by IxKo** [comment]
@kdr154 Ich habe es in die Liste unserer Form-SW eingetragen: https://github.com/ubtue/zotero-enhancement-maps/blob/master/marc655_keywords.txt

**Comment by kdr154** [comment]
Danke! Dann kann ich schließen.
