### ISSUE TITLE
ISSN 1043-1578 | Social justice | Nicht zur Zeitschrift gehörende Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1441]
Betrachte ich mir die Einspielung vom 13./14.3 2021 fällt auf, dass nur Artikel eingespielt wurden, die nicht zu der Zeitschrift Social Justice gehören, aber mit dieser verknüpft werden:
![grafik](https://user-images.githubusercontent.com/29707105/111139656-ac203780-8581-11eb-9bb8-5bf74864d8a0.png)

Unter den Delivered Records ist  dies auch gut zu erkennen:
![grafik](https://user-images.githubusercontent.com/29707105/111139846-ec7fb580-8581-11eb-8db4-be0c2d3a3902.png)

Taylor & Francis, Sage, Wiley, Springer.

Etwa folgender:
![grafik](https://user-images.githubusercontent.com/29707105/111140785-07065e80-8583-11eb-9c3e-3c9400e12cce.png)

Wie kommt dies zustande? Bis zu diesem Zeitpunkt wurden nur Artikel heruntergeladen, die auch wirklich zu dieser Zeitschrift gehören.
Heruntergeladen mit RSS von Ebsco: 
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26jid%3dJUS%26site%3dehost-live

**Comment by jriedl** [comment]
Wie besprochen: Der hinterlegte Feed enthält Suchlinks, die keine Ergebnisse mehr liefern und aufgrund der "SmartText Searching"-Funktionalität von EBSCO werden andere Artikel aus anderen Zeitschriften angezeigt und falsch eingespielt. Ohne einen funktionierenden Feed scheint eine Lösung nicht möglich. Die Website der Zeitschrift http://www.socialjusticejournal.org enthält aber als aktuelle Ausgabe 46/4, während die Ausgabe 45 offenbar von 2018 und die Ausgabe 44 von 2017 ist, sodass sich die Frage stellt, ob hier überhaupt noch neue Ausgaben erscheinen.

**Comment by jriedl** [comment]
Auf nu ist jetzt eine Version des EBSCO-Translators, die versucht, ein Auftreten von "SmartText Searching" zu erkennen und in diesem Fall keine Artikelergebnisse zurückliefert.

**Comment by kdr154** [comment]
Hat in meinen Augen leider nicht geklappt, wenn ich mir diesen CLI Output ansehe. Er enthält URLs wie die folgenden: 
http://journals.sagepub.com/doi/10.1177/1476750312464792 Sage!
https://linkinghub.elsevier.com/retrieve/pii/S0190740911002271 Elsevier!
http://doi.wiley.com/10.1002/piq.20053 Wiley!

800 geharvestet und keinen verworfen:

![grafik](https://user-images.githubusercontent.com/29707105/111487968-1a5b2a80-8739-11eb-845e-fb0b6c75f0d6.png)

**Comment by jriedl** [comment]
Problem ist, dass zwar der EBSCO-Translator korrekt keine Ergebnisse zurückliefert, der Translation Server eben dann auf Biegen und Brechen andere Translators durchprobiert, bis er irgendetwas bekommt. (Reproduzierbar z.B. mit "Try URL" und http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3deue%26bquery%3dJN%2b%2526quot%253bSocial%2bJustice%2526quot%253b%2bAND%2bDT%2b%25252220191001%252522%2bNOT%2bPM%2bAOP%26site%3dehost-live). Im Prinzip muss man den Feed als kaputt betrachten, da er keine korrekten Links mehr enthält. Zusammen mit der Tatsache, dass es 2020 offenbar keinerlei Neuerscheinungen mehr gab, ist die Frage, ob wir die Zeitschrift nicht einfach rausnehmen. Die alten korrekten Sachen sind ja eingespielt.

**Comment by kdr154** [comment]
Nach der Besprechung am Montag habe ich die Zeitschrift bereits aus dem Live-Betrieb herausgenommen. Als Produktionsverfahren ist jetzt Test eingetragen. Das liefert im Augenblick aber auch nur irritierende und falsche Daten. Solange nichts neues kommt. 
In meinen Augen können wir es ganz herausnehmen. Wir können einen Email-Alert einrichten, der uns benachrichtigt, sobald ein neues Heft erscheint. Wenn er nicht schon eingerichtet ist.

**Comment by jriedl** [comment]
Danke - erscheint mir momentan als die sinnvollste Option.

**Comment by kdr154** [comment]
Ok! Habe es ganz  herausgenommen und einen Alert eingerichtet.
