### ISSUE TITLE
ISSN 1552-8049 | Journal of religion, spirituality & aging (T&F) | fehlende Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1442]
**URL**
https://www.tandfonline.com/toc/wrsa20/33/2

**Ausführliche Problembeschreibung**
Von dem aktuellen Heft ist nur ein Artikel in den Test-Daten gelandet (IxTheo#2021-03-10#E3FFDE8590AC187F4F9869C219DC303DDC4AA94A)

**Comment by IxKo** [comment]
Ähnlich bei ISSN 2161-4504 | Journal of pastoral theology (T&F):
Hier wurden 3 Artikel von insgesamt 7 eingespielt worden.

**Comment by jriedl** [comment]
Das hängt wohl mit der Online-First-Behandlung zusammen. Wie in 
- http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=244
- http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=265 
- http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=127 

am schwarzen Punkt in Delivery State zu erkennen, waren diese Artikel offenbar bereits anfangs des Monats zum ersten Mal im RSS-Feed zu finden, allerdings noch ohne Heftangabe. Um ein überflüssiges tägliches Harvesten zu verhindern, werden diese dann als Online-First bei uns in der Datenbank eingetragen. Nach Ablauf des hinterlegten Erscheinungsintervalls wird der Online-First-Status gelöscht und es erfolgt dann ein erneutes Harvesten, so dass dann eine Einspielung erfolgen würde. Es wäre aber zu überlegen, ob wir im Testmodus für solche Fälle einen manuellen Reset des Online-First-Status implementieren, um eine korrekte Einspielung testen zu können

**Comment by IxKo** [comment]
Was bedeutet das für den Live-Betrieb? Würden die Aufsätze des aktuellen Heftes dann erst nach x Monaten eingespielt?

**Comment by jriedl** [comment]
Laut `zotero_harvester.conf` beträgt das `zotero_update_window` bei dieser Zeitschrift 137 Tage, das ist in der Tat etwas lang. Wir müssen die richtige Mitte zwischen tausenden immer wieder wiederholten täglichen Online-First-Downloads und dem anschließenden Verwerfen und dem Verlust von Artikeln durch Verschwinden aus dem RSS-Feed und/oder einer extrem verzögerten Einspielung finden. Eine Lösungsmöglichkeit wäre, das Intervall auf das Minimum von zotero_update_window und z.B. 30 Tagen zu setzen.

**Comment by IxKo** [comment]
Wenn man davon ausgeht, dass nicht das komplette Heft mal Online-First war: Könnte man dann nicht sagen, dass das Intervall resettet wird, sobald nur ein neuer Aufsatz eingespielt wird?

**Comment by IxKo** [comment]
Nun gibt es auch eine Zs, von der gar kein Aufsatz aufgrund Online First eingespielt wurde: Political Theology ISSN 1743-1719

**Comment by jriedl** [comment]
Es besteht jetzt auf nu in der Oberfläche die Möglichkeit, Online-First-Artikel für Testzeitschriften zu resetten (probeweise für einen Record bereits erfolgt - vgl. http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=244).Eine Implementierung von "Resetten der Online-First-Artikel bei Lieferung eines neuen Records und damit ein erneuter Download der OF-Artikel am nächsten Tag" scheint im Prinzip möglich, allerdings würden dann Fälle wie "Political Theology" trotzdem außen vor bleiben. Wie ist denn die Hefterscheinung bei "Political Theology" aufgefallen?

**Comment by IxKo** [comment]
> Wie ist denn die Hefterscheinung bei "Political Theology" aufgefallen?
Es kam gestern eine E-Mail zur neuen Heft-Erscheinung und ich wollte dann heute prüfen, ob das ganze Heft eingespielt ist.
Wenn wir diese E-Mail-Benachrichtigungen hätten, würden wir es nicht so schnell mitbekommen.

**Comment by IxKo** [comment]
Auch bei Sage gibt es nun ein Heft, das gar nicht eingespielt wird, weil alle neuen Artikel den Status Online First haben: http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=61

**Comment by jriedl** [comment]
Auf nu gibt es ja nun die Möglichkeit, OF-Aufsätze manuell zu resetten. Für deren "bessere" Behandlung ist derzeit ein Pull-Request offen, der sicherstellt, dass die OF-Einträge nach spätetens 14 Tagen zurückgesetzt und damit ein erneuter Downloadversuch unternommen wird, damit hier die Intervalle nicht zu lang werden. Dieser wird voraussichtlich heute im Laufe des Tages auf nu eingespielt. Es erscheint sinnvoll, mit dem Livesetzen noch so lange zu warten, bis wir entscheiden, die Änderungen der vergangangenen Zeit auch auf ub28 einzuspielen. Falls es allerdings dringend notwendig ist, kann es aus technischer Sicht auch unmittelbar erfolgen.

**Comment by kdr154** [comment]
Habe von der Zeitschrift "Journal of religion, spirituality & aging" zwei Artikel zurückgesetzt, einen Online-First und einen bereits gelieferten um zu sehen, was morgen passiert.

**Comment by jriedl** [comment]
"Ageing and frailty" war ein ursprünglicher OF-Artikel, der wegen OF-Reset heute Nacht dann in der Datei der gelieferten Aufsätze war. Er sollte dehalb mit aktuellem Einspieldatum heute in der Test-DB zu finden sein.

**Comment by kdr154** [comment]
Wenn ich es richtig verstanden habe scheitert der Download daran, dass es den Artikel bereits in der Datenbank mit OF-Status gibt. Aber jetzt ist er doch einem Heft zugewiesen. Kann man das nicht so einrichten, dass sobald ein Artikel eine Band/Heft-Zuordnung hat, der Mechanismus, den der OF-Status auslöst, außer Kraft gesetzt wird?

**Comment by jriedl** [comment]
Bislang war es so (und ist es auf ub28 derzeit noch), dass jede Nacht alle potentiellen Artikelkandidaten (also alles, wovon noch nicht bekannt war, dass es wirklich Richtung BZS geliefert wurde) heruntergeladen wurden. Damit wurden täglich eine sehr große Anzahl von Artikeln erst heruntergeladen und dann sofort wieder verworfen (wg. OF). Um das zu verhindern, wird jetzt über die OF-Aufsätze Buch geführt und diese werden nicht noch einmal heruntergeladen. Damit ist eine Änderung des Status natürlich für uns erst einmal nicht mehr erkennbar. Um eine mögliche Überführung in einen Heftartikel aber dennoch mitzubekommen, wird der OF-Status in regelmäßigen Abständen gelöscht. Ursprünglich diente dazu das `update_window`, aber wie sich an diesem konkreten Beispiel hier gezeigt hat, ist das z.T. viel zu lange (OF-Veröffentlichung kurz vor Hefterscheinung, nächstes Heft voraussichtlich erst in Monaten). Deshalb erfolgt die Löschung zukünftig nach der Häflte des Updatewindows oder nach 14 Tagen, je nachdem, was der kleinere Wert ist. Dieser Einspieluungsverzug sollte  hoffentlich in der Praxis für den Livebetrieb tolerabel sein. Zum Testen besteht die Möglichkeit des manuellen Resets.

**Comment by IxKo** [comment]
Schließe, da es geklärt ist, und die Problematik mit den OF-Artikeln einhergeht.
