### ISSUE TITLE
ISSN 1460-3586 | Journal of material culture | keine Test-Daten harvester.conf

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1443]
**Ausführliche Problembeschreibung**
Ich habe die Zs gestern auf prode=zotat gesetzt und sie hat einen RSS-Link in Zeder. Trotzdem sieht sie heute in der harvester.conf so aus:

![image](https://user-images.githubusercontent.com/57000004/111309792-93d11b00-865c-11eb-84b5-8205fa90a430.png)

Es wurden dementsprechend auch keine Test-Daten eingespielt.

Dauert es länger als eine Nacht bis Änderungen von Zeder übertragen werden?
Oder muss man händisch etwas in der conf anpassen? So wie bspw. das newly-Flag entfernen

**Comment by jriedl** [comment]
Der obere Teil ist nur ein Kommentar (erkennbar am `'#` am Zeilenanfang). Die Zeitschrift kommt weiter unten noch einmal vor und hier ist sie neu synchronisiert (mit RSS-Eintrag). @mtrojan Können wir den oberen Eintrag einfach entfernen oder hat der noch eine Bedeutung?

**Comment by IxKo** [comment]
Vielen Dank, das habe ich übersehen.
Aber es ist in der Tat etwas verwirrend und kann, wenn man mal schnell etwas nach sehen will - und die Raute-Zeichen übersieht -zu Falschinformationen führen.
