### ISSUE TITLE
Sabinet Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1444]
**URL**
https://journals.co.za/toc/oldtest/current

**Ausführliche Problembeschreibung**
Es wird kein Sabinet-Translator mehr angeboten - weder im Multi- noch Single-DL.

Im Multi wird mir nur ubtue_University of Chicago Press Journal angeboten und beim DL passiert nichts.
Im Single wird mir der Atypon angeboten und dabei werden die Autoren nicht als Nachname, Vorname geladen und es wird keine ISSN geladen.

Warum wird der Sabinet-Translator (https://github.com/ubtue/zotero-translators/blob/master/ubtue_Sabinet.js) nicht angeboten?

**Comment by IxKo** [comment]
Der Translator wird nun angeboten.
Es wird jedoch keine ISSN übertragen und die Keywords fehlen.

**Comment by socheres** [comment]
Keywords fehlen auch im Quelltext.

**Comment by IxKo** [comment]
Der Translator wird mir noch nicht an erster Stelle angeboten, sondern erst nach Translator Chicago Press

>socheres commented 3 hours ago
Keywords fehlen auch im Quelltext.

Es gibt Hinweise zu den Keywords im Quelltext und sie finden sich auch auf der Artikel-Seite, allerdings in einer Extra-Sektion auf der Seite (Bsp-Artikel-URL: https://journals.co.za/doi/abs/10.17159/2312-3621/2020/v33n1a5) 

![image](https://user-images.githubusercontent.com/57000004/115244322-1e0d1300-a124-11eb-922d-52ce9e29838c.png)

**Comment by IxKo** [comment]
Danke, es passt nun fast alles, der Translator wird mir nun auch an erster Stelle angeboten.
Nur die **ISSN** kommt nicht nach Zotero.

Die Artikel hätten zusätzlich zum DOI auch einen **Handle**. Für Handle gibt es wie beim DOI ein eigenes Pica-Feld bei Online-Katalogisaten: 2052.
Wäre hier eine Umsetzung möglich?

**Comment by socheres** [comment]
ISSN sollte jetzt mitkommen.
Handle ist leider nicht in RIS sowie als strukturierte Metadaten auf Webseiten enthalten. Webscraping sollte man in diesem Fall nicht machen.
```
        TY  - JOUR
         T1  - 
         Reading trauma narratives : insidious trauma in the story of Rachel, Leah, Bilhah and Zilpah (Genesis 29-30) and Margaret Atwood’s The Handmaid’s Tale
         
         AU  - Claassens Juliana
         Y1  - 2020/10/01
         PY  - 2020
         DA  - 2020/10/01
         N1  - doi: 10.17159/2312-3621/2020/v33n1a3
         DO  - 10.17159/2312-3621/2020/v33n1a3
         T2  - Old Testament Essays
         JF  - Old Testament Essays
         JO  - Old Testament Essays
         SP  - 10
         EP  - 31
         VL  - 33
         IS  - 1
         PB  - Old Testament Society of South Africa (OTSSA)
         M3  - doi: 10.17159/2312-3621/2020/v33n1a3
         UR  - https://doi.org/10.17159/2312-3621/2020/v33n1a3
         Y2  - 2021/06/09
         ER  - 
```

**Comment by IxKo** [comment]
ISSN nun vorhanden, danke!
