### ISSUE TITLE
ISSN 1552-6933 | International journal of offender therapy and comparative criminology | Lizenzfrei auf ub28

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1448]
Das Merkmal "Lizenzfrei" bei einzelnen Aufsätzen wird auf ub28 nicht umgesetzt.
Bsp.:
https://journals.sagepub.com/toc/ijoe/65/5
https://journals.sagepub.com/doi/full/10.1177/0306624X20983748

![grafik](https://user-images.githubusercontent.com/29707105/111585159-330e2380-87bf-11eb-8860-d796b3906342.png)

**Comment by jriedl** [comment]
Wie am Montag durch IT angesprochen, sind eine ganze Reihe Änderungen wegen der aktuell laufenden Testphase noch nicht auf ub28 eingespielt. (vgl. auch #1449, #1450)

**Comment by kdr154** [comment]
Ok, dann lösche ich die Aufsätze in der Winibw und resette, sobald die Änderungen auf ub28 eingepielt sind. Auch #1449, #1450

**Comment by kdr154** [comment]
LF wird gesetzt
