### ISSUE TITLE
ISSN 0181-6799 Réforme, humanisme, renaissance - Bandangabe in der Umsetzung nicht korrekt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#145]
Der Zusatz "N° " bei der Bandangabe sollte bei der Übertragung in den SWB entfernt werden.
Beispiel eines Aufsatzes:
https://www.cairn.info/revue-reforme-humanisme-renaissance-2018-2-page-9.htm

**Comment by kdr154** [comment]
Die Zeitschrift scheint mir nicht mehr zum Bestand auf nu zu gehören.

**Comment by shadeMe** [comment]
Diese Zeitschrift wird im Moment bei dem automatischen Verfahren nicht ausgewertet, weil sie im Zeder keinen RSS-Feed hat. Deswegen habe ich den Translator direkt angepasst.

**Comment by kdr154** [comment]
Problem besteht weiterhin. Wird mit Embedded Metadata von Zotero abgegriffen. Gibt es einen anderen Translator?

**Comment by shadeMe** [comment]
Ja, er sollte "Cairn.info" heißen. Er befindet sich auf [unserem Repositorium](https://github.com/ubtue/zotero-translators).

**Comment by kdr154** [comment]
Translator habe ich aktualisiert und für den DOI passt die Geschichte jetzt. Aber hier hat man wieder das Problem, dass das was im Feld Ausgabe steht, in das Feld Band muss. Zudem gibt es bei dieser ZS auch noch eine Heftzählung im Rahmen eines Jahres. Diese sollte dann in das Feld Ausgabe. Etwa: Band 86 Ausgabe 1, Band 86 Ausgabe 2, Band 87 Ausgabe 1 Band 87 Ausgabe 2 ....

**Comment by shadeMe** [comment]
@kdr154 Betrifft die Band-Ausgabe Verwechselung alle Zeitschriften, die auf Cairn.info erscheinen, oder nur einzelne Zeitschriften? Wenn es das erstere wäre, können wir den Translator dementsprechend anpassen, indem er die zwei Angaben immer gewechselt. Sonst ist es nicht sinnvoll, das Problem automatisch zu lösen.

**Comment by kdr154** [comment]
Nein, aber es gibt in meinen Augen möglicherweise ein Kriterium, wann dies der Fall ist und wann nicht.
Der Fehler tritt dort nicht auf, wo der Begriff "Tome" dabei steht, Etwa hier:
https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2018-4.htm
und hier:
https://www.cairn.info/revue-nouvelle-revue-theologique-2019-2.htm
dort, wo nichts derartiges verzeichnet ist, tritt er auf. Z. B. hier:
https://www.cairn.info/revue-reforme-humanisme-renaissance-2018-2.htm
und hier:
https://www.cairn.info/revue-histoire-monde-et-cultures-religieuses-2017-4.htm

**Comment by kdr154** [comment]
Stimmt jetzt
