### ISSUE TITLE
Keine Einspielung von Zeitschriften, die am 17.03 in das vollautomatische Verfahren aufgenommen wurden (Krimdok)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1451]
Am 17.03 habe ich drei Zeitschriften live geschaltet:

ISSN 1552-6933 International journal of offender therapy and comparative criminology
ISSN 2157-6475 International journal of comparative and applied criminal justice 
ISSN 1556-3855 International criminal justice review 

Von keiner wurde irgend etwas eingespielt.

**Comment by jriedl** [comment]
Laut der Anzeige auf nu und dem Inhhalt von `krimdok_zotero_210317_001.xml` wurden Artikel hochgeladen.

http://ub28.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=18
http://ub28.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=16
http://ub28.uni-tuebingen.de/zotero_cgi?action=show_downloaded&id=15

Die Datei `krimdok_zotero_210317_001.xml` findet sich auch im `loaded`-Verzeichnis auf dem BSZ-FTP-Server, sollte also bearbeitet sein. @socheres: Falls sie tatsächlich (wahrscheinlich mit dem Einspieldatum 17.3. oder 18.3. nicht zu finden sind), wäre es wohl sinnvoll, beim BSZ anzufragen.

**Comment by kdr154** [comment]
Es wurden am 17./18. schon Artikel eingespielt, aber nicht von den genannten Zeitschriften.

**Comment by jriedl** [comment]
Besteht theoretisch die Möglichkeit, dass Sie im Rahmen der Löschungen zu #1448, #1449, #1450 aus Versehen mit entfernt wurden?

**Comment by kdr154** [comment]
Daran liegt es. Tut mir leid für die Verwirrung.
