### ISSUE TITLE
ISSN 1934-9645 | Journal of spirituality in mental health | Reihenfolge der Verfasser Taylor & Francis live

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1453]
Sind die Verfasser in der Vorlage mit dem Und-Zeichen "&" gelistet, wird immer der Verfasser, der hinter dem "&" steht, zum ersten Verfasser und wird in Pica 3000 Marc 100 gesetzt. 

Gerade anders herum wäre richtig.

Immer der zuerstgenannte müsste in Marc 100, Pica 3000.

Beispiele:
https://www.tandfonline.com/doi/full/10.1080/19349637.2019.1620668

Mark Lusk, Sam Terrazas, Janette Caro, Perla Chaparro & Delia Puga Antúnez

wird in der Winibw:

![grafik](https://user-images.githubusercontent.com/29707105/112271220-f2108600-8c7a-11eb-933b-9855e2d08e8c.png)

https://www.tandfonline.com/doi/full/10.1080/19349637.2019.1626319

Maria Clara Kreis & Joanna Crammond

wird in der Winibw:

![grafik](https://user-images.githubusercontent.com/29707105/112271418-313ed700-8c7b-11eb-8e43-d39eefd0af04.png)

Das gilt generell für Taylor & Francis. Auch hier:

https://www.tandfonline.com/doi/full/10.1080/1462317X.2021.1885832

![grafik](https://user-images.githubusercontent.com/29707105/112272596-b70f5200-8c7c-11eb-94f3-91b5c4c9796c.png)

**Comment by jriedl** [comment]
Das Problem, dass der letzte Autor in MARC 100 landet, besteht allgemein und kam mit commit a64265bd09f31f83bb2a514becded59345531383. Pullrequest mit Fix ist offen.

**Comment by kdr154** [comment]
Besteht allgemein bei Taylor & Francis. Bei Sage ist dies nämlich nicht der Fall.

**Comment by IxKo** [comment]
Bei Brill scheint es auch der Fall zu sein: Bsp. IxTheo#2021-03-25#90D9E006073AECF4C5C69D34DE11C33FFAC9110C

**Comment by jriedl** [comment]
Auf nu und ub28.

**Comment by kdr154** [comment]
Auf nu passt es.
