### ISSUE TITLE
ISSN 1572-543X | Exchange (Brill) | fehlender Namenszusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1454]
**URL**
IxTheo#2021-03-23#6C1F8750BB1FBD0ED0370D1E265890D246C464F0
https://doi.org/10.1163/1572543X-12341585

**Ausführliche Problembeschreibung**
Das "van" im Namen von Wouter Theodoor van Veelen wurde bei der Einspielung nicht übernommen:
![image](https://user-images.githubusercontent.com/57000004/112287573-cdbda500-8c8c-11eb-9bda-4057ba2fb573.png)

**Comment by kdr154** [comment]
Das schien mir auch bei den Taylor & Francis Einspielungen der Fall zu sein.

https://www.tandfonline.com/toc/rech20/10/1?nav=tocList
Die Präfixe scheinen zu fehlen. In diesem Fall nicht eindeutig zu klären, weil die Autoren verknüpft sind:
https://www.tandfonline.com/doi/abs/10.1080/2222582X.2020.1848443
![grafik](https://user-images.githubusercontent.com/29707105/112289464-a10a8d00-8c8e-11eb-9227-2f38ba638c3f.png)

https://www.tandfonline.com/doi/abs/10.1080/2222582X.2020.1854048

![grafik](https://user-images.githubusercontent.com/29707105/112289729-d7480c80-8c8e-11eb-8566-fc08298df502.png)

**Comment by mtrojan-ub** [comment]
Aktueller Test mit dieser Zeitschrift auf nu:
![grafik](https://user-images.githubusercontent.com/26873381/112839895-fd124e80-909e-11eb-8a3e-5c71dac6aefa.png)

Das findet man auch so in einer aktuelleren Lieferung ans BSZ:
ixtheo_zotero_210323_001.xml

Wird das ggf. BSZ-seitig beim Import normalisiert?

**Comment by kdr154** [comment]
Es ist auch bei Taylor & Francis der Fall. 
In der Einspielung vom 6.4. fehlen bei den Autoren von diesem Artikel die Präfixe:
https://www.tandfonline.com/doi/full/10.1080/0048721X.2021.1865616

![grafik](https://user-images.githubusercontent.com/29707105/113686753-e6d04800-96c7-11eb-8923-1f8c383ee024.png)

**Comment by socheres** [comment]
der Fehler wurde BSZ-seitig behoben (sieh eMail Datum: Dienstag, 13. April 2021 um 11:55).

**Comment by kdr154** [comment]
Bei der Einspielung vom 28./29. 4. war der Namenszusatz bei T&F vorhanden.

**Comment by IxKo** [comment]
> Bei der Einspielung vom 28./29. 4. war der Namenszusatz bei T&F vorhanden.

Super, demnach kann der Fall wohl geschlossen werden.
Danke!
