### ISSUE TITLE
1572-543X | Exchange | orcid & open access tag "lf" 

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1455]
Ein weiterer Fall, der allerdings nichts mit der Problematik von oben zu tun hat:

Hier wurde ein falscher Johannes Merz verknüpft.
Der verknüpfte Name ist identisch, es scheint sich jedoch nicht um ein und dieselbe Person zu handeln:
IxTheo#2021-03-23#F410203C26AA33D681E526FAEB0A7B9396AF795F
https://doi.org/10.1163/1572543X-12341583
![image](https://user-images.githubusercontent.com/57000004/112290324-681ee800-8c8f-11eb-92bd-dc22027a35ef.png)
3000 Merz, Johannes$7gnd141902280$BVerfasserIn$4aut

![image](https://user-images.githubusercontent.com/57000004/112290952-ff843b00-8c8f-11eb-943e-8a2e6c9da5c8.png)
Die ORCID-Seite ist leider leer.

Der falsch verknüpfte ist ein Johannes Merz geboren 1929. Ich bezweifle stark, dass dieser Herr nun aktiv in Texas englische Artikel zu Jesus-Filmen schreibt.
Das fand ich zu dem Texaner: https://www.researchgate.net/profile/Johannes-Merz-2

Da der Fall zeigt, dass es zu automatischen Fehl-Verknüpfungen kommen kann und man demnach eh alles überprüfen muss, möchte ich nochmal fragen, ob es nicht gefahrloser wäre auf diese Automatik zu verzichten?

_Originally posted by @IxKo in https://github.com/ubtue/DatenProbleme/issues/1446#issuecomment-805668875_

**Comment by IxKo** [comment]
Die ORCID kommt beim Testen auf Nu nun mit.

**Comment by kdr154** [comment]
Live auch
