### ISSUE TITLE
Keine Einspielung neu live geschalteter Zeitschriften am 24./25. 3.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1456]
Heute, 24./25. 3. wurden keine neuen Artikel eingespielt. Weder von IxTheo noch von Krimdok. Keine von den neu live geschalteten, aber auch keine von bereits aktiven.

**Comment by jriedl** [comment]
Es kam zu einem Abbruch auf ub28 aufgrund eines angeblich ungültigen `note`-Felds vom Translation-Server. Da es sich um einen älteren Artikel einer seit längerem aktiven SAGE-Zeitschrift handelt und gestern keine Änderungen an ub28 vorgenommen wurden, muss das weiter untersucht werden.

**Comment by jriedl** [comment]
Ein Fehler mit dem fraglichen Datensatz https://journals.sagepub.com/doi/abs/10.1177/0886260520983304?ai=2b4&mi=ehikzz&af=R  ist nicht reproduzierbar. Eine ZTS-Abfrage sieht eigentlich unverdächtig aus:
[error_record.txt](https://github.com/ubtue/DatenProbleme/files/6204819/error_record.txt)
allerdings hätte ich ein `notes`-Array mit einzelnen `note`-Einträgen erwartet.
Die manuelle Abfrage
```bash
/usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/test" "--output-filename=xiNAJA.xml" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://journals.sagepub.com/doi/full/10.1177/0886260520983304" "Journal of interpersonal violence : concerned with the study and treatment of victims and perpetrators of physical and sexual violence"
```
auf der Kommandozeile hat sowohl auf nu als auch auf ub28 zu einem Ergebnis geführt. Da der Artikel vom 20. Dezember ist und sich unverdächtig in früheren Logs findet, gehe ich Stand jetzt davon aus, dass es sich bei dem Abbruch um um einen Einzelfall handelt. Sollte sich das heute Abend nicht bestätigen, würde ich darum bitten, das "Journal of interpersonal violence" bis zu einer endgültigen Klärung aus dem Test- und Livebetrieb herauszunehmen.

**Comment by kdr154** [comment]
Scheint mir geklärt, da am 24.4. Einspielungen stattgefunden haben.
