### ISSUE TITLE
ISSN 1556-1836 | Terrorism and political violence | review als Keyword

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1458]
https://www.tandfonline.com/doi/full/10.1080/09546553.2021.1880235
Das Keyword "review" wird nicht in 650 gesteckt sondern bekommt ein ein Tag 655. Der Satz landet dann in der Error-Files:
![grafik](https://user-images.githubusercontent.com/29707105/112595958-6c701000-8e0b-11eb-9122-fedce782ffa9.png)

![grafik](https://user-images.githubusercontent.com/29707105/112596014-83166700-8e0b-11eb-802e-4496eedc7799.png)

![grafik](https://user-images.githubusercontent.com/29707105/112596082-9aedeb00-8e0b-11eb-8198-7ccae42d4bad.png)

**Comment by jriedl** [comment]
Das liegt daran, dass `review` in `marc655_keywords.txt` steht und deshalb dorthin verschoben wird. Das sollte im Allgemeinen wohl auch nicht aufgegeben werden. Da es sich bei diesem Artikel (und allgemein bei den Einträgen von  https://www.tandfonline.com/keyword/Review) offenbar nicht um Rezensionen handelt, wäre der Vorschlag, dieses Keyword einfach zu entfernen. Eine entprechende Anpassung findet sich nun in `zotero_harvester.conf`

**Comment by kdr154** [comment]
Ok! Aber mittels der Anpassung der harvester.conf sollte er doch Morgen eingespielt werden?

**Comment by jriedl** [comment]
Der Titel wurde ja gestern Abend eingespielt. Da es sich aber um ein allgemeineres Problem zu handeln scheint (#1305, #1470, #1471)  bestehen folgende Möglichkeiten: Wir wählen auch bei den anderen Zeitschriften den hier gewählten Weg und verwerfen das fehlerhafte 655-Feld und damit das Keyword. Oder wir führen ein Flag ein, das auf Zeitschriftenebene die Behandlung von Review als Rezension verhindert.

**Comment by kdr154** [comment]
Dieses mal ohne "review" als Schlagwort in 650 oder als fehlerhafter Eintrag in 655. Über das beste Verfahren im Allgemeinen sollte diskutiert werden.

**Comment by socheres** [comment]
#1470
