### ISSUE TITLE
ISSN 1547-3201 | Religious education | Rezensionen (T&F live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1459]
https://www.tandfonline.com/toc/urea20/116/1?nav=tocList

Bei diesem Heft werden die Rezenionen nicht erkannt. (habe es bei der aktuellen Einspielung manuell ergänzt)

**Comment by kdr154** [comment]
Weder auf nu noch auf ub28.

**Comment by kdr154** [comment]
Auch nicht bei der Einspielung von 2.4.

https://www.tandfonline.com/doi/full/10.1080/00344087.2020.1863069

![grafik](https://user-images.githubusercontent.com/29707105/113665260-75839b80-96ad-11eb-9b06-40519a08b91f.png)

**Comment by socheres** [comment]
@jriedl zts liefert als item.type "review" zurück. In XML-Output dagegen wird kein Rezensionsfeld erzeugt. Weißt du woran das liegen könnte? "Book Review" ist auch vorhanden und müsste ja demnach auch matchen: https://github.com/ubtue/zotero-enhancement-maps/blob/623eab066a3a4a097adfcc21a51ee0ccf15c3404/zotero_harvester.conf#L48 
```
Converting item 10 [Religious education ...] | https://www.tandfonline.com/doi/full/10.1080/00344087.2020.1863069?af=R {11562551096765495708}
use online ISSN "1547-3201" with online PPN "334925541"
Using single configured language: eng
post-processed author first name = 'Jason A.', last name = 'Miller', title = '', affix = ''
keyword matched review pattern
keyword matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1080/00344087.2020.1863069,
	item_type: review,
	title: On Christian Teaching: Practicing Faith in the Classroom,
	short_title: On Christian Teaching,
	publication_title: Religious education : an interfaith journal of spirituality, growth and transformation,
	volume: 116,
	issue: 2,
	pages: 184-185,
	date: 2021-03-15,
	doi: 10.1080/00344087.2020.1863069,
	language: eng,
	issn: 1547-3201,
	superior_ppn: 334925541,
	superior_type: 2,
	ssg: 3,
	creators: [
		{
			first_name: Jason A.,
			last_name: Miller,
			type: author,
		},
	],
	keywords: [ Book Review, Book Reviews ],
}
custom field '5203 a%abs%' has missing values for placeholder '%abs%'
custom field '5203 a%abs1%' has missing values for placeholder '%abs1%'
custom field '8873 aorcid: %orcid% | taken from website2ixzom' has missing values for placeholder '%orcid%'
erased field '650a' due to removal filter '(?i)^Book\s+Reviews?$'
erased field '650a' due to removal filter '(?i)^Book\s+Reviews?$'
erased field '650a' due to removal filter '(?i)^Book\s+Reviews?$'
Generated record with hash '89F9936F5DB7BD848277B66ECB6910A61E459162'

Conversion complete
```

**Comment by kdr154** [comment]
Es heißt dort aber "Book reviews" mit "s"!

**Comment by jriedl** [comment]
Es gibt für diese Zeitschrift folgenden Eintrag in der conf:
`remove_marc_field_650a    = (?i)^Book\s+Reviews?$`
`zotero_review_regex       = (?i)^Book\s+Reviews?$`
d.h. der entsprechende Eintrag wird gelöscht, bevor er nach 655 verschoben werden kann.

**Comment by kdr154** [comment]
Ändert es etwas, wenn man die Reihenfolge der Einträge umkehrt?

**Comment by jriedl** [comment]
Selbst wenn, macht man damit Annahmen, die ein Implementierungsdetail darstellen, auf das man sich nicht verlassen sollte.

**Comment by kdr154** [comment]
Aber es befinden sich auf der Seite https://www.tandfonline.com/doi/full/10.1080/00344087.2020.1863069 gar keine Keywords. 
Vielmehr ist in der 3. Zeile des Quelltexts der Eintrag zu finden, dass es sich um ein Dokument von Typ "book-review" handelt:

![grafik](https://user-images.githubusercontent.com/29707105/113831216-a801c700-9787-11eb-9902-1d85aba493dd.png)

**Comment by kdr154** [comment]
Dieselbe Problematik bei ISSN 1756-0748 "Practical Theology". Ebenfalls T&F

**Comment by socheres** [comment]
#1469 #1471 #1477 es ist kein Translator-Problem. ZTS liefert bei allen das Keyword "Book Review" bzw. "Book Reviews" und der Regex matcht beide Varianten also mit und ohne Endbuchstabe "s". Bisher hatte `remove_marc_field_650a = (?i)^Book\s+Reviews?$` keine Auswirkung auf das Erkennen von Rezensionen. Wurde hier etwas harvesterseitig geändert?

**Comment by jriedl** [comment]
Die angepasste Version des Harvesters ist jetzt auf nu.

**Comment by kdr154** [comment]
Bei Religious Education und Practical Theology stimmt jetzt alles.
