### ISSUE TITLE
1759-8818 Sociology of religion Fehlende Felder beim Mehrfachdownload 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#146]
Bei folgendem Artikel: https://academic.oup.com/socrel/article/80/1/45/5040146
fehlen im Rahmen des Mehrfachdownloads zusätzlich Band, Ausgabe und Seitenzahlen

**Comment by shadeMe** [comment]
Ich kann es nicht reproduzieren, auch beim Mehrfachdownload (mit https://academic.oup.com/socrel/issue/80/1 getestet). Wahrscheinlich wird der falsche Translator bzw. DOI oder Embedded Metadata anstatt Oxford Academic, ausgewählt. Bitte probiere nochmal, die Translators nochmal zu aktualisieren (und wie üblich, den Browser/Zotero-Client in der richtigen Reinfolge neuzustarten).

PS: Auf nu tut's auch.

**Comment by kdr154** [comment]
gelöst
