### ISSUE TITLE
Einspielungen Taylor & Francis unvollständig oder sie finden nicht statt.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1460]
ISSN 1556-1836 Terrorism and political violence
https://www.tandfonline.com/toc/ftpv20/33/2?nav=tocList
Bei der Einspielung dieses Hefts am Freitag fehlen die Artikel ab Seite 433. Sie wurden auch in den darauffolgenden Tagen nicht eingespielt.

ISSN 1751-8342 Material religion
https://www.tandfonline.com/toc/rfmr20/17/1?nav=tocList
habe ich am Freitag auf zota gesetzt.
Von dieser Zeitschrift wurde gar nichts eingespielt.
Wohingegen das Heft von Religion ISSN 1096-1151, gleichzeitig live gesetzt, komplett eingespielt wurde.

In allen Fällen sind die fehlenden Artikel Bestandteil des aktuellen Feeds

**Comment by jriedl** [comment]
- 1556-1836: Per Stichprobe überprüft: "Sharia Compliant: A User’s Guide to Hacking Islamic Law" wurde am 22.3. als OF erkannt und wird deshalb erst nach Ablauf des Zeitfensters für OF-Artikel wieder heruntergeladen.
- 1751-8342 steht laut Zeder und conf auf zotat.

**Comment by kdr154** [comment]
zu 1751-8342 stimmt. Da wurden die Änderungen nicht gespeichert.

**Comment by socheres** [comment]
@IxKo Können Sie bitte noch einmal überprüfen, ob der Fall gelöst ist. Issues zu Online First ist mittlerweile schon gelöst.

**Comment by IxKo** [comment]
Problem scheint nicht mehr vorhanden.
Die Hefte der beiden Krim-Zss sehen aus meiner Sicht vollständig erfasst aus.
