### ISSUE TITLE
Brill ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1461]
**URL**
https://doi.org/10.1163/15700747-bja10031
IxTheo#2021-03-25#EDC621C8CBE1FE9435F1AA4F37C1DFCBBA304D79

**Ausführliche Problembeschreibung**
Hier wurde die ORCID-ID nicht als Hinweis ins entsprechende Feld eingespielt.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/1455

**Comment by IxKo** [comment]
ORCID vorhanden beim Test auf Nu
