### ISSUE TITLE
ISSN 1743-1670 | Black theology : an international journal |Rezensionen  (Taylor & Francis)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1464]
https://www.tandfonline.com/toc/yblt20/18/3?nav=tocList
https://www.tandfonline.com/doi/full/10.1080/14769948.2020.1842160

Rezensionen werden nicht erkannt. Es fehlt Marc21-Tag 655

![grafik](https://user-images.githubusercontent.com/29707105/112989261-0108a400-9165-11eb-9ea9-25cd980abd28.png)

**Comment by socheres** [comment]
auf nu 655 MARC-Feld "Rezension" vorhanden.

**Comment by kdr154** [comment]
Live auch
