### ISSUE TITLE
ISSN 2331-253X | Journal of disability and religion | Körperschaft als Verfasser (Taylor & Francis)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1465]
**URL**
https://doi.org/10.1080/23312521.2020.1743223
IxTheo#2021-03-29#ED81C6794B5EC125D0E3BC76A6AF239910AD89C1

**Ausführliche Problembeschreibung**

![image](https://user-images.githubusercontent.com/57000004/112991980-07e4e600-9168-11eb-98c2-32bf7664659e.png)

![image](https://user-images.githubusercontent.com/57000004/112992065-21862d80-9168-11eb-8479-bf08b383ce47.png)

Die Körperschaft wurde geteilt in zwei Felder eingetragen: ein Teil in 3010 und ein Teil in 3110

Wie kann man solche Nicht-Personen-Verfasser abgreifen?
Und wieso landet ein Teil der Körperschaft sogar in einem Feld, was wir bisher noch nicht genutzt haben?

**Comment by socheres** [comment]
> Die Körperschaft wurde geteilt in zwei Felder eingetragen: ein Teil in 3010 und ein Teil in 3110
> 
> Wie kann man solche Nicht-Personen-Verfasser abgreifen?

T&F-Translator ruft zuerst Bibtex auf, anschließend zusätzlich RIS um fehlende Datenfelder wie ISSN etc. abzugreifen. Verfasserangaben werden nun via RIS abgegriffen.  PR muss noch von @jriedl bestätigt werden.

> Und wieso landet ein Teil der Körperschaft sogar in einem Feld, was wir bisher noch nicht genutzt haben?

ich weiß auch nicht warum. @jriedl  @mtrojan-ub vermute liegt am Harvester.

**Comment by IxKo** [comment]
Passt nun auf Nu
