### ISSUE TITLE
ISSN 1552-8049 | Journal of religion, spirituality & aging | Zusatztitel (Taylor & Francis)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1466]
**URL**
IxTheo#2021-03-29#A4956B85FAF6DF51305EDDB2011B7C4E5AD36E3A
https://doi.org/10.1080/15528030.2020.1850604

**Ausführliche Problembeschreibung**

![image](https://user-images.githubusercontent.com/57000004/112996987-fbaf5780-916c-11eb-8177-2e6ed4aa4a83.png)

![image](https://user-images.githubusercontent.com/57000004/112997023-0669ec80-916d-11eb-96a3-e0f7c5f4c7a0.png)

Der Zusatz zum Sachtitel wird nicht abgegriffen.

**Comment by socheres** [comment]
@IxKo bitte auf ub28 testen.

**Comment by IxKo** [comment]
Zusatztitel beim Test mit Try url auf ub28 nun dabei.
