### ISSUE TITLE
ISSN 0974-2891 | International journal of cyber criminology | DOI und https://doi.org Krimdok live

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1467]
http://www.cybercrimejournal.com/index.html
http://www.cybercrimejournal.com/AkanleShadarevol14issue1IJCC2020.pdf

1. Der DOI in Pica 2051 wird falsch ausgegeben. Er enthält den Zusatz http://dx.doi.org/
2. Entsprechend wird die URL in 4950 falsch aufgelöst. Hier wird das "http..." gedoppelt: 
   4950 https://doi.org/http://dx.doi.org/10.5281/zenodo.3738962$xR$3Volltext$4LF$534

Im Ganzen sieht der Satz so aus:

Eingabe: TUKRIM:02-02-21 Änderung: TUKRIM:29-03-21 15:59:13 Status: TUKRIM:02-02-21
0100 1746677279
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
0575 mkri
1100 2020
1500 eng
1505 $erda
2051 http://dx.doi.org/10.5281/zenodo.3738962
2240 KXP: 1746677279
3000 !1016613768!Akanle, Olayinka ; ID: gnd/1155275470$BVerfasserIn$4aut
3010 Shadare, Babajide Richard$BVerfasserIn$4aut
4000 Why has it been so difficult to Counteract Cyber Crime in Nigeria Evidence from an Ethnographic Study
4070 $v14$j2020$a1$p29-43
4241 Enthalten in!574353399!International journal of cyber criminology. - Tirunelveli, 2007- ; ZDB-ID: 2442372-5$x202000000140001971
4950 https://doi.org/http://dx.doi.org/10.5281/zenodo.3738962$xR$3Volltext$4LF$534
4950 http://www.cybercrimejournal.com/AkanleShadarevol14issue1IJCC2020.pdf$xH$3Volltext$4LF$534
5056 2,1
5520 |s|Yahoo Plus
5520 |s|Yahoo boys security cybercrime
5520 |g|Ibadan
5520 |g|Nigeria
8910 $aixzom$bAutor in der Zoterovorlage [Akanle, Olayinka] maschinell zugeordnet
E001 02-02-21 : l01
7100 $B2619$Jn
7811 KrimDok#2021-02-01#BA3758CF80A9371CBF1F8013CDEE2CB5632E3924
7901 TUKRIM:02-02-21
7902 02-02-21
7903 02-02-21 06:15:31.000
8012 zota
7800 3847530127

**Comment by kdr154** [comment]
Auf nu in Ordnung.

**Comment by kdr154** [comment]
Leider scheinen sich solche Fälle zu häufen. Bekam gerade den Hinweis zu der bei Erudit publizierten Zeitschrift "Criminologie":
1505 $erda
2051 https://doi.org/10.7202/1074193ar
2240 KXP: 1747441767
3000 Laforest, Marty$BVerfasserIn$4aut
3010 Rioux-Turcotte, Jessica$BVerfasserIn$4aut
3010 St-Yves, Michel$BVerfasserIn$4aut
4000 Détecter l’appelant dissimulateur au service d’urgence 9-1-1 : une analyse discursive et interactionnelle de la tromperie
4070 $v53$j2020$a2$p193-218

4241 Enthalten in!373755422!Criminologie. - Montréal : Presses de l'Univ., 1975- ; ZDB-ID: 2126751-0$x202000000530002807
4950 https://doi.org/https://doi.org/10.7202/1074193ar$xR$3Volltext$4LF$534
4950 https://www.erudit.org/en/journals/crimino/2020-v53-n2-crimino05749/1074193ar/$xH$3Volltext$4LF$534

kann man dieses Problem nicht global lösen? Oder wurde es global gelöst und dieser Hinweis ist obsolet?

**Comment by kdr154** [comment]
Auf ub28 ist es aber immer noch so:

![grafik](https://user-images.githubusercontent.com/29707105/113714288-86053780-96e8-11eb-8c03-2f980dd73b56.png)

**Comment by jriedl** [comment]
Das wurde vor einiger Zeit (global) umgesetzt und ist auch seit einiger Zeit produktiv, die letzte Einspielung vom 20.5. sieht gut aus.

**Comment by kdr154** [comment]
Ja, aktuelle Einspielungen sehen gut aus.
