### ISSUE TITLE
0392-2855 Analecta Augustiniana Angabe in Feld Heft in Feld Band umleiten 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#147]
https://dialnet.unirioja.es/ejemplar/507204
Bei dieser ZS sollte die Zählung im Feld Band ausgegeben werden statt im Feld Ausgabe

**Comment by kdr154** [comment]
Kann die Zeitschrift auf nu nicht mehr finden

**Comment by kdr154** [comment]
Auch kein RSS, daher nicht auf nu. Aber Problem existiert immer noch

**Comment by shadeMe** [comment]
Es schient, auf meinem Rechner zu funktionieren. Ist dein lokaler Dialnet Translator aktuell?
![Screenshot_20190402_123538](https://user-images.githubusercontent.com/214450/55396292-d965ad80-5543-11e9-8b5e-30dec3f82cbb.png)

**Comment by kdr154** [comment]
gelöst

**Comment by IxKo** [comment]
Problem tritt wieder auf mit ubtue_Dialnet.js
![image](https://user-images.githubusercontent.com/57000004/226941149-c81c1296-7bd9-40d9-8315-a6807679c8c8.png)

**Comment by IxKo** [comment]
Problem ist noch nicht behoben:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/d4f1a9d3-25fa-4474-aa37-7789b694017d)
