### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | Review

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1470]
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1785844

Die Datei  marc655_keywords.txt ist problematisch. So wird durch sie bewirkt, dass ein Artikel, der als Review gekennzeichnet wird, als Rezension in Pica 1131 getagt wird.

![grafik](https://user-images.githubusercontent.com/29707105/113252796-9a020100-92c4-11eb-9760-0b4e3c2a585e.png)

Wie man unschwer erkennen kann, handelt es sich bei dem oben erwähnten Artikel um keine Rezension, sondern um eine Sichtung der Literatur zu einem bestimmten Thema.

**Comment by kdr154** [comment]
Dieser Artikel besitzt immer noch das Tag 655 für Rezensionen.

![grafik](https://user-images.githubusercontent.com/29707105/114516884-1b9b4c80-9c3e-11eb-94e0-5177d94a3f21.png)

**Comment by socheres** [comment]
nach PR-Bestätigung durch @jriedl werden nur solchen mit "Book Review" in der section heading als Rezension gekennzeichnet. Mit "marc655_keywords.txt" steuern wir die Indikatoren (siehe Issue #1305)

**Comment by jriedl** [comment]
Habe den PR gemerged. An der Grundproblematik des Bedeutungsspektrums von "review" im Englischen (Rezension und Übersicht) ändert das aber vermutlich zunächst einmal nichts,  da "review" ja in `marc655_keywords.txt` hinterlegt ist. Was zu überlegen wäre ist, ob man die neue `rewrite_marc_field_XXX`-Funktionalität (vgl. Doku in `zotero_harvester.conf`) nutzt, um bei Zeitschriften, in denen bekanntermaßen keine Rezensionen  vorkommen auf ein "unproblematisches" Keyword mapped. Das sollte aber noch einmal besprochen werden.

**Comment by socheres** [comment]
in #1229 wurde entschieden nur "Book Review" als Rezensionen  aufzunehmen. `marc655_keywords.txt` hat ja eine ganz andere Funktion, nämlich, die Keywords-Indikatoren in 655 von "|s|" in "|f|" zu ändern.

**Comment by jriedl** [comment]
Diese Datei wurde erst Ende Februar von @mtrojan eingeführt infolge der Diskussion in #1305.

**Comment by kdr154** [comment]
Weitere Beispiele wo die marc655_keyword.txt zu Problemen führt sind in der Einspielung 13./14. 4. der Krimdok zu finden:

![grafik](https://user-images.githubusercontent.com/29707105/114661903-16023d00-9cf8-11eb-9b59-5968ba670d65.png)

![grafik](https://user-images.githubusercontent.com/29707105/114662012-44801800-9cf8-11eb-9727-3cff9ab4d0b7.png)

![grafik](https://user-images.githubusercontent.com/29707105/114662062-5d88c900-9cf8-11eb-97f8-fa72a63943ec.png)

![grafik](https://user-images.githubusercontent.com/29707105/114662117-74c7b680-9cf8-11eb-9ce1-ed8523931cb1.png)

**Comment by jriedl** [comment]
Es scheint, es überschneiden sich hier unterschiedliche Stränge:
(A)
1. Welche Keywords gelten als Rezension und sollten deshalb als 655 "Rezension" getagged werden?
2. Welche Keywords sollten als Formschlagwort (also mit Indikator 4) in 655 hinterlegt werden?
3. In welchen Fällen darf ein Keyword "review" _nicht_ als Formschlagwort und auch _nicht_ als Rezension behandelt werden, da es einen Überblicksartikel bezeichnet und in welcher Kategorie (650/655?) muss es dann landen?
4. Welche Anpassungen sind an den QS-Einstellungen nötig, damit korrekt zugeordnete 655-Felder nicht aussortiert werden ?

Wir haben derzeit parallel unterschiedliche Ansätze:
(B)
1. Der Translator liefert den `item.type` Review => 655 Rezension
2. Durch `zotero_review_regex` => 655 Rezension
3. In `marc655_keywords` => Das Keyword wird von vornherein in 655 ( mit Indikator 4) geschrieben. 

Jetzt gibt es aber Kombinationen, die sich so nicht sinnvoll behandeln lassen, insbesondere (A3 - B3), d.h. ein Keyword "review", das _keine_ Rezension bezeichnet. Da "review" in diesem Fall wegen des Eintrags in `marc655_keywords` unmittelbar nach 655 geschrieben wird, ist es allerdings für die 650-Schlagwörter "verloren", obwohl es eventuell dort verbleiben sollte und durch einen aussagekräftigeren Term ersetzt werden sollte. Dafür sollte es wahrscheinlich schon ausreichen, "review" aus der `marc655_keywords` zu entfernen und mittels `rewrite_marc_field_XXX` zu ersetzen. Und in den anderen Fällen würde "review" doch eine Rezension bezeichnen und sollte einen 655-Rezensionseintrag bekommen, oder?
Deshalb allgemein: Lassen sich hier widerspruchsfreie Regeln angeben, wie hier in Zukunft verfahren werden soll?

**Comment by kdr154** [comment]
Vielleicht würde es genügen, in den QA-Settings die Bedingungen für das Feld 655 dahingehend zu ändern, dass die Subfield $0 und $2 auf "sometimes" gesetzt werden. Jetzt stehen sie auf "always". Es gibt in den genannten Fällen, die zu einem Error führen, aber keine Unterfelder $0 und $2.  Sondern nur das $a.

Das würde bedeuten, dass diese Inhalte unverknüpft in 1131 geschrieben werden. In der Format-Dokumentation heißt es zu diesem Feld: "Die Eingabe erfolgt in der Regel als Verknüpfung zur GND (Gemeinsame Normdatei)." In der Regel, aber nicht notwendigerweise. Nun gibt es eine erweiterte Liste, in der alle Einträge aufgelistet werden, die in 1131 zugelassen sind. Andere sind nicht erlaubt.

Eine mögliche Lösung könnte darin bestehen, dass man die Einträge in der marc655_keywords in Einträge aus der oben genannten erweiterten Liste übersetzt und diese dann unverknüpft in 1131 schreibt.

**Comment by jriedl** [comment]
Die 655 Behandlung ist direkt in `validate_harvested_records` integriert. Ich habe jetzt die Bedingung so abgeschwächt, dass die genannten Fälle  nicht mehr in den Error-Files landen. Das ist ab sofort auf nu und ub28 aktiv. Aber noch einmal zum Verständnis: Dürfen in 655 tatsächlich nur normierte Inhalte stehen und die momentan in `marc655_keywords` stehenden Terme dürften eigentlich nicht unverändert übernommen werden?

**Comment by kdr154** [comment]
So ist es. Es sei denn, einer der Begriffe die abgesehen von "Rezension" in 655 geliefert werden, stimmt mit einem der Liste überein. Das ist in meinen Augen so gut wie nie der Fall.

Hier die Seite der Doku:
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=1131&kattype=Standard

Das ist die Liste:
https://wiki.dnb.de/download/attachments/106042227/AH-007.pdf

**Comment by jriedl** [comment]
Macht dann der ganze `marc655_keywords`-Ansatz, wie er derzeit implementiert ist und verwendet wird, überhaupt noch Sinn, oder sollten diese Formschlagwörter dann nicht in einem ganz anderen Feld landen?

**Comment by kdr154** [comment]
Das würde ich nicht sagen. Das wäre eine Möglichichkeit, sich aus der Problematik zu schleichen. Was in diesem Issue diskutiert wird, sind zum Teil keine Schlagwörter, sondern kennzeichnen den Dokumenttyp. 
Sie gehören in diesem Fall ganz richtig in Marc 655. Nur sind es eben keine Rezensionen, sondern von  einem anderem Typ Dokument.
So wie sie hier stehen dürften sie nicht in Pica 1131 stehen.  Hinzu kommt, dass sie in der Error-Datei landen, weil die QA-Settings bei Marc 655 die Unterfelder $0 und $2 erwarten, die in diesem Fall nicht vorhanden sind.

Was in #1458 diskutiert wird ist der Fall, dass es dort das Keyword "review" gibt, welches allein wegen der Nomenklatur "review" nicht in 650 ausgegeben wird sondern ein 655 Rezension erzeugt, was falsch ist. Es sollte in diesem Fall auch als Schlagwort ausgegeben werden. So wie es dort zu sehen ist, sogar als Sachschlagwort.

In #1305 wird diskutiert dass ein am Rand zu findender Begriff "Review Article" der dort wie hier ein Feld Marc 655 erzeugt, in ein Formschlagwort (nicht in ein Sachschlagwort) überführt wird. Was dort wohl gelungen ist. Mit einem Marc 655-Feld, bei dem der erste Indikator leer bleibt und der 2. den Wert 4 besitzt.

So wie es in den beiden Beispielen aus der Krimdok steht, ist es im Grunde genommen korrekt und es sollte ein Formalschlagwort 5520 |f| Article Commenatry erzeugt werden, im anderen Fall |f| review. Jedenfalls wenn man #1305 folgt. Tut es aber nicht, sondern es gibt die Fehlermeldung.

**Comment by jriedl** [comment]
Ich denke nicht, dass sich hier irgendwer aus irgendwas schleicht, sondern es geht darum, an diese unterschiedlichen Problematik einen Knopf zu bekommen. Die Problematik des QS und der Error Files sollte ja mittlerweile behoben sein. Warum es in dieser Hinsicht geht, ist doch, in welchen PICA-Feldern die von uns in 655 gelieferten MARC-Daten landen. Wenn für die Einträge in `marc655_keywords` durch den Indikator 4 sichergestellt ist, dass sie ohnehin nicht in 1131, sondern in einem anderen PICA-Feld landen, das kein normiertes Vokabular verlangt, besteht überhaupt kein Problem. Außer "Rezension" erzeugen wir derzeit kein 655 Feld mit Indikator 7 und dieses verfügt dann über die notwendigen Inhalte. Andernfalls scheint allerdings nicht klar, wie die in `marc655_keywords` hinterlegten Terme auf die Liste der zulässigen Begriffe in PICA 1131 gemapped werden sollen, da sie schlicht nicht zusammenpassen. 

Was weiterhin noch offen ist, ist der Eintrag "review" in  `marc655_keywords` im Anschluss an Frage A3 oben. Hier wäre eben zu überlegen, diesen aus der Liste herauszunehmen, da es Fälle gibt, in denen "review" nicht Rezension, sondern Übersicht bedeutet und dann sollte es wohl entweder so in **650** abgelegt werden oder (evtl. besser) durch ein anderes, präziseres Schlagwort ebenfalls in 650 ersetzt werden. Falls review tatsächlich für Rezension steht, sollte das über den `zotero_review_regex` erkannt werden, denn dann wird auch das 655-Renzensions-Tag vollständig eingefügt.

Nachtrag zu QS: Die QS-Einstellungen always für die 0- und 2- Unterfelder können bestehen bleiben, da sie sich nur auf Rezensions-Artikel i.e.S. (record_type: review) bezieht und hier müssen sie auch vorhanden sein

**Comment by kdr154** [comment]
Das erklärt aber nicht, warum es in den beiden von der KrimDok genanntent Fällen zu einem Fehler kommt. Keineswegs war es meine Absicht, dies negativ zu konnotieren. Ich würde in dem Fels 1131 nur eine Alternative zu 5520 sehen. 
Wenn review Alternativ immer für Literaturbericht stünde, wäre das eine Lösung. In dem einen Fall ist review aber auch eher kein Formalschlagwort, wie es review als Übersicht ist, sondern ein Sachschlagwort.

**Comment by jriedl** [comment]
> Das erklärt aber nicht, warum es in den beiden von der KrimDok genanntent Fällen zu einem Fehler kommt.

Die hier genannten Krimdok-Fehler sind doch von heute Nacht. Die Ursache war, dass `validate_harvested_records`, das ja den Fehler erzeugt, bislang davon ausgegangen ist, dass in 655 nur "Rezension" mit allen zugehörigen Feldern stehen darf. Genau das wurde heute behoben und sowohl auf nu als auch auf ub28 eingespielt, d.h. zukünftig sollte das nicht mehr in der Errors-Datei landen.

>Ich würde in dem Fels 1131 nur eine Alternative zu 5520 sehen. Wenn review Alternativ immer für Literaturbericht stünde, wäre das eine Lösung. In dem einen Fall ist review aber auch eher kein Formalschlagwort, wie es review als Übersicht ist, sondern ein Sachschlagwort.

Sachschlagwörter stehen doch in 650, deshalb ja der Vorschlag "review/Review" aus `marc655_keywords` herauszunehmen und z.B. mit `rewrite_marc_field_650a=(?i)^review$ ||| Literaturbericht` (im Fall von #1458) zu ersetzen:

![image](https://user-images.githubusercontent.com/13135579/114737495-5f2dad80-9d47-11eb-9ed5-ae15eff53324.png)

 Falls die Mischung von deutschen und englischen Schlagwörtern nicht gewünscht ist, könnte man sich da auch eine andere englische Terminologie überlegen. 

Und falls review tatsächlich Rezension bedeutet, fügt man eben auf Zeitschrifteneben eine `zotero_review_regex` hinzu.

**Comment by kdr154** [comment]
Es handelt sich nur in einem Fall um ein Sachschlagwort (#1458), in den beiden Fällen der KrimDok und in den in #1305 diskutierten Fall handelt es sich aber nicht um Schlagwörter, sondern um die Bezeichnung von Dokumententypen, wovon einer mit Review bezeichnet wird, der aber keine Rezension ist. Und wenn da etwas abgelegt werden sollte, gehört es korrekterweise in 1131.

**Comment by jriedl** [comment]
Die Fälle lassen sich nicht beliebig kombinieren: Wenn "review/Review" in `marc655_keywords` bleibt, kann zwar noch die Begrifflichkeit geändert werden (mit `rewrite_marc_field_655a`), aber das Feld 655 und der Indikator 4 ist dann fix. Damit ist eine Lösung wie oben in dem Screenshot nicht mehr möglich. Um in 1131 zu landen, muss doch der Indikator 7 sein und hier gibt es nur den Fall Rezension und das geht nicht über `marc655_keywords`, sondern entweder über den Translator direkt oder den `zotero_review_regex`. Der offene Punkt von #1305 bezieht sich nach meinem Verständnis nur noch auf die QS-Settings, was gelöst ist und die Position von "Review Article" in 655 auch nicht ändern würde. Ich sehe die große Gefahr, dass wir hier, wenn wir das jetzt wieder alles aufschnüren, mit großem Aufwand Anpassungen für Einzelfälle machen und dauerhaft Listen im Code pflegen müssen, die uns dann zu einem späteren Zeitpunkt an anderen Stellen wieder auf die Füße fallen. Vorschlag wäre, das am Montag noch einmal kurz zu besprechen.,

**Comment by kdr154** [comment]
Einverstanden

**Comment by kdr154** [comment]
Das ist glaube ich ausdiskutiert.
