### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | Autoren Blacklist

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1472]
Ich stelle allmählich unsere Blacklist und Mapping-Tabellen wirklich infrage.
Hier: https://www.tandfonline.com/doi/full/10.1080/01416200.2019.1635434
wird das "Jo" vom Namen "Jo Pearce" entfernt, weil in der author_name_blacklist.txt der Eintrag "JO" existiert. Für was soll dieses Kürzel denn stehen.
Die Folge ist: 
![grafik](https://user-images.githubusercontent.com/29707105/113254396-ccacf900-92c6-11eb-91db-9af932554ec4.png)

**Comment by socheres** [comment]
laut #1412 dürften solche Titel nicht eingespielt werden, sondern in errors landen und anschließend manuell erfasst.

**Comment by socheres** [comment]
@IxKo das Problem ist bereits behoben, oder?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem wurde schon länger behoben, es ist jetzt auch auf NU alles korrekt, bitte testen.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Der Fall tritt nicht mehr auf, da die Black-List sehr verschlankt wurde.
