### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | Autorenverküpfung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1473]
Hier https://www.tandfonline.com/doi/full/10.1080/01416200.2021.1878760 
wurde ein 2011 verstorbener Theologe verküpft. 

![grafik](https://user-images.githubusercontent.com/29707105/113257493-fd8f2d00-92ca-11eb-8748-364ba6fbf417.png)

Habe inzwischen die Verknüpfung rückgängig gemacht und den Hinweis in 8910 entfernt.

**Comment by socheres** [comment]
Hier handelt es sich um einen postum publizierten Artikel des o.g. Verfassers. Daher alles richtig.

**Comment by kdr154** [comment]
stimmt
