### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Abstracts (Open Journal Systems Standard)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1474]
Wenn es kein Abstract gibt, wird eine in 4207 auf ein Bild verwiesen. In diesem Fall sollte das Abstract nicht ausgegeben werden.
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/voices-of-the-voiceless-religion-communism-and-the-keston-archive-edited-by-zoe-knox-and-julie-degraffenried-pp-xviii-98-incl-42-colour-and-blackandwhite-ills-waco-tx-baylor-university-press-2019-2995-978-1-4813-1123-6/A91005C289B9C07961756C7347E99FB8

![grafik](https://user-images.githubusercontent.com/29707105/113818463-150d6080-9778-11eb-8034-2783ea865b9d.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
da Sie wahrscheinlich testen müssten, erwähne ich Sie schonmal. Ist aber noch nicht ready for testing.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
könntest du das eventuell testen?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Die jpg-Links treten nicht mehr auf, danke!
