### ISSUE TITLE
ISSN 2077-1444 | Religions | Artikel-ID

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1475]
Die Artikel von dieser Zeitschrift besitzen immer eine Artikel-ID. Schön wäre es, wenn man die in Marc 936 $i schreiben könnte.
https://www.mdpi.com/2077-1444/12/4/254
![grafik](https://user-images.githubusercontent.com/29707105/113827221-53f4e380-9783-11eb-895c-343361de7d72.png)

Der Eintrag im Quelltext, dass es sich bei der "254" um die erste Seite (firstpage) handelt, ist nicht zutreffend

**Comment by IxKo** [comment]
https://github.com/ubtue/DatenProbleme/issues/1412#issuecomment-883998133
Das Unterfeld für die Artikelnummern müsste - sobald wir es mitliefern - auch in den QA-Settings für diese Zs eingetragen werden.

**Comment by kdr154** [comment]
War bereits eingetragen

**Comment by IxKo** [comment]
Bei mir schaut es auf Nu so aus:
![image](https://user-images.githubusercontent.com/57000004/126460849-9addee14-6878-4742-83ac-8b8157033a26.png)

Seitenangaben h sollte gar nicht mehr vorkommen und das Unterfeld i für die Artikelnummern sollte auf always definiert werden, sobald das mit dem Translator klappt.

So sieht im Produktions-System das Feld 936 aus, wenn eine Artikelnummer (369) angegeben ist:
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">12</subfield>
<subfield code="j">2021</subfield>
<subfield code="e">6</subfield>
<subfield code="i">369</subfield>
</datafield>
```

**Comment by kdr154** [comment]
Auf nu stand das "j" immer noch statt dem "i". Habe es geändert. Setze die Sachen auf nu zurück und löschen die Aufsätze.

**Comment by kdr154** [comment]
Na zumindest mal ein paar.

**Comment by IxKo** [comment]
Wir liefern in unseren XML-Daten noch gar kein Unterfeld i für die Artikelnummern mit:

![image](https://user-images.githubusercontent.com/57000004/126476182-5197c07b-4647-4f76-9792-a6f66ee62c9f.png)

Das heißt, der Translator müsste erst angepasst werden.

**Comment by kdr154** [comment]
Siehe #1515 #1433 #1416

**Comment by IxKo** [comment]
Liebe @helenanebel ,
in den QA-Settings sollte es schon korrekt sein:
![image](https://user-images.githubusercontent.com/57000004/173778413-23682ddf-61df-48a4-a378-476aa234eaa9.png)
Ich habe nun 936i von Sometimes auf Always umgestellt, sodass die Daten nun bei fehlender Artikelnummer in den Errors landen.

Momentan wird ohne Artikelnummer in die Test-DB eingespielt (IxTheo#2022-06-14#392D4F6C43506FCB60880E03A57562F3A715C9F5):
![image](https://user-images.githubusercontent.com/57000004/173778623-34341cc5-50ef-48af-bec8-bbe8f80c876b.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
der zotero_harvester wirft dieses Feld offensichtlich weg:
suppression regex '.*' matched metadata field 'pages' value '254'
Warum das passiert, kann ich leider nicht sagen, die o.g. Regex führt wohl dazu, dass das Feld entfernt wird.
Das bedeutet, dass es auf jeden Fall vom Translator übernommen wird.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
> Liebe @IxKo , der zotero_harvester wirft dieses Feld offensichtlich weg: suppression regex '.*' matched metadata field 'pages' value '254' Warum das passiert, kann ich leider nicht sagen, die o.g. Regex führt wohl dazu, dass das Feld entfernt wird. Das bedeutet, dass es auf jeden Fall vom Translator übernommen wird. Viele Grüße, Helena Nebel

@jriedl Könnten Sie sich das bitte anschauen?

**Comment by helenanebel** [comment]
Ach so, ich hatte das in einem anderen Issue so verstanden, dass wenn in der conf steht, dass h ignoriert werden soll, dann automatisch i belegt wird. Dann kann ich auch den Translator anpassen.

**Comment by jriedl** [comment]
In der conf kann man ja nicht hinterlegen, dass h ignoniert werden soll. Der Harvester muss halt irgendwie erkennnen können, ob die Angabe in pages eines Seitenzahl oder eine Artikel-ID ist.

**Comment by helenanebel** [comment]
Ja, ich meinte auch die QA-Settings.

**Comment by jriedl** [comment]
Mir kommt gerade, eventuell kann man das Umschreiben ohne Translator-Anpassung in der Conf machen. Probiere es und gebe Rückmeldung.

**Comment by jriedl** [comment]
Ja, funktioniert: `override_json_field_pages = article %org%`. Habe es so in die conf eingecheckt.
