### ISSUE TITLE
ISSN 1096-1151 | Religion | Open Access vs Full Access

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1478]
https://www.tandfonline.com/toc/rrel20/51/2?nav=tocList

Hier werden die Artikel unterschieden in Open Access (Gelb-Braun geöffnetes Schlüsselsymbol) 
Bsp.: https://www.tandfonline.com/doi/full/10.1080/0048721X.2021.1865600

und Full Acces (Grüner Haken)
Bsp.: https://www.tandfonline.com/doi/full/10.1080/0048721X.2020.1868383

Nur die mit dem grünen Haken werden als Lizenzfrei (LF) in 4950 eingespielt, die mit dem gelb-braunen geöffneten Schlüssel hingegen nicht, sondern mit "ZZ", somit lizenzpflichtig.

Im Grunde müsste in beiden Fällen $4LF in 4950 stehen.

**Comment by thefass** [comment]
Kann es sein, dass full access dann erscheint, wenn man eine Lizenz hat? Im Grunde müßt man mal von zuhause prüfen (ohne eine VPN Verbindung ins UniNetz), was für eine Kennzeichnung dann bei full access Titeln erscheint.

**Comment by kdr154** [comment]
Diese Überlegung mit der Lizenz habe ich auch angestellt. Den Fall ohne VPN-Verbindung werde ich gleich mal testen.

**Comment by kdr154** [comment]
Es ist so, wie Sie vermutet haben. Die mit dem grünen Haken sind wohl über die Uni-Lizenz frei zugänglich und die anderen (gelb-braun) sind OA.

Das bedeutet aber, dass die Aufsätze genau falsche herum eingespielt werden. Die mit dem grünen Haken müssten "ZZ" bekommen, die anderen "LF".

Hinzu kommt noch, dass die Einleitung und der letzte Artikel, "Correction", auch ohne VPN einen grünen Haken haben und frei zugänglich sind. Bei allen anderen, die mit VPN einen grünen Haken besitzen, ist ohne VPN kein Symbol irgendereiner Art zu sehen.

Diese ist aber von weitreichender Konsequez. So werden alle Artikel von Zeitschriften, von denen die Uni eine Lizenz besitzt, als Lizenfrei und frei zugänglich eingespielt, obwohl sie es in Wirklichkeit nicht sind. Zumindest die Zeitschriften von Taylor & Francis.

**Comment by socheres** [comment]
In der Quelldatei "ixtheo_zotero_210411_001" ist der oben erwähnte OA-Artikel (Gelb-Braun geöffnetes Schlüsselsymbol) https://www.tandfonline.com/doi/full/10.1080/0048721X.2021.1865600 als "LF" markiert. Vielleicht liegt es an dem Konverter vom BSZ. Um das herauszufinden, müsste man betreffendes Heft in WinIBW manuell löschen und auf ub28 ein Reset durchführen und neu einspielen. @kdr154 Haben Sie ein Beispiel, bei dem ein "Full Access"-Artikel als "LF" eingespielt worden ist?

**Comment by thefass** [comment]
> Dies ist aber von weitreichender Konsequez. So werden alle Artikel von Zeitschriften, von denen die Uni eine Lizenz besitzt, als Lizenfrei und frei zugänglich eingespielt, obwohl sie es in Wirklichkeit nicht sind. Zumindest die von den Zeitschriften von Taylor & Francis.

Das darf nicht passieren! Weder bei T&F Zss, noch bei anderen Verlagen.

**Comment by kdr154** [comment]
Kommando zurück. Es hat alles seine Richtigkeit. Es tut mir leid, für diese Verwirrung gesorgt zu haben.

**Comment by socheres** [comment]
Das ist und wird auch nie passieren. Denn nach der bisherigen Logik werden nur OA-Artikel mit dem Tag "Open Access" als "LF" gekennzeichnet.

**Comment by kdr154** [comment]
Dann schließe ich.
