### ISSUE TITLE
ISSN 2589-0433 | Annuarium Historiae Conciliorum | Berichts- und Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1479]
https://brill.com/view/journals/ahc/49/2/ahc.49.issue-2.xml?utm_source=eToC&utm_medium=email&utm_campaign=Content_Alerts

Im Prinzip sollten alle Aufsätze in  Pica 4070 dem Berichtsjahr 2019 zugeordnet werden 49.2019,2.

Und alle Aufsätze das Erscheinungsjahr 2020 in Pica 1100 besitzen.

Tatsächlich werden sieben Aufsätze als 2019 erschienen ausgegeben. Wodurch 4070 stimmt, 1100 aber nicht
Sechs werden als 2020 erschienen ausgegeben. Wodurch 1100 stimmt, 4070 hingegen nicht!

![grafik](https://user-images.githubusercontent.com/29707105/114715727-add14c80-9d33-11eb-8e51-ff821006dd14.png)

**Comment by socheres** [comment]
auf ub28 ist wie hier beschrieben
https://github.com/ubtue/DatenProbleme/issues/1078#issue-673424963
das Berichtsjahr richtig ausgegeben.
http://ub28.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_rsQFNw/ixtheo/dYjLrx.xml
Bitte Aufsätze in der Testdatenbank löschen, auf nu diese Zss. resetten und neu einspielen.

**Comment by kdr154** [comment]
Reset durchgeführt aber die Zeitschrift sollte aus dem Testbetrieb herausgenommen werden, da sie ab 2020 bei Aschendorff unter einem leicht veränderten Titel erscheint. Siehe:
https://zdb-katalog.de/title.xhtml?idn=1224689674&direct=true&view=full

**Comment by socheres** [comment]
@kdr154 Bitte schließen, falls die Zeitschrift nicht mehr im Zotaut getestet wird.

**Comment by kdr154** [comment]
Ok.
