### ISSUE TITLE
Jr. oder Jr als Titulatur bei Namen werden falsch interpretiert

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#148]
Das bei amerikanischen Namen häufig anzutreffende Jr., bei einem fehlenden abschließenden "." Jr, für Junior, wird fälschlicherweise als Vorname interpretiert, so dass der Name falsch angesetzt wird.
Etwa bei folgendem Feed; https://www.tandfonline.com/doi/full/10.1080/0735648X.2018.1559029?af=R
wird in Datafield 700, analog wäre das auch der Fall in 100, aus Richard K. Moule Jr. in Marc21-xml:
`<subfield code="a">Jr, Richard K. Moule</subfield>`
richtig wäre:
```
<subfield code="a">Moule, Richard K.</subfield>
<subfield code="c">Jr.</subfield>
```

**Comment by kdr154** [comment]
Beim halbautomatischen Verfahren ist es immer noch der Fall. Im vollautomatischen Verfahren lässt sich der Sachverhalt bei dieser ZS nicht mehr überprüfen, da inzwischen ein neues Heft erschienen ist.

**Comment by shadeMe** [comment]
Ach, das ist ja schade, weil die Umsetzung nur beim vollautomatischen Verfahren zu nutzen ist - Wir haben die Funktionalität direkt im Harvester eingebaut, weil sie auf der Ebene des Translators nicht richtig realisierbar ist.

**Comment by shadeMe** [comment]
Ich setze dieses Issue nochmal auf 'ready for testing', weil keine weitere Anpassungen erforderlich sind.

**Comment by kdr154** [comment]
Das Problem besteht weiterhin.

**Comment by shadeMe** [comment]
Hmm, gibt es ein paar Beispiele zum Testen?

**Comment by kdr154** [comment]
Ein weiteres Beispiel:

https://journals.sagepub.com/doi/full/10.1177/2050303217732131

 

Morello SJ, Gustavo

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Madeesh Kannan <notifications@github.com> 
Gesendet: Dienstag, 2. April 2019 13:17
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Jr. oder Jr als Titulatur bei Namen werden falsch interpretiert (#148)

 

Hmm, gibt es ein paar Beispiele zum Testen?

**Comment by kdr154** [comment]
Ein weiteres Beispiel:
https://journals.sagepub.com/doi/full/10.1177/2050303217732131

Morello SJ, Gustavo

**Comment by shadeMe** [comment]
Gibt es andere Titular-Abkürzungen zu berücksichtigen bzw. außer Jr, Sr und SJ?

**Comment by kdr154** [comment]
Fr. (für Frater), Sr (für Schwester oder Sister). und die ganze Liste auf Wikipedia, die du schon gefunden hattest: 
https://de.wikipedia.org/wiki/Liste_der_Ordensk%C3%BCrzel_(r%C3%B6misch-katholisch)
Wobei man zumindest bei Fr. vorsichtig sein sollte.  Könnte auch ein abgekürzter Vorname sein. Ich denke, es ist besser, die Liste zu erweitern, wenn man darauf stößt und sich sicher sein kann.

**Comment by kdr154** [comment]
Hier ist es S.j. was als Nachname übertragen wird
https://webapp.uibk.ac.at/ojs2/index.php/EJPR/article/view/2601

**Comment by kdr154** [comment]
Problem besteht weiterhin, sowohl beim ersten, als auch beim letzten Beispiel

**Comment by kdr154** [comment]
Auch so ein Fall. Hier wird OSB zum Nachnamen und "Father Godfrey Mullen" zum Vornamen:
https://www.tandfonline.com/doi/full/10.1080/0458063X.2018.1478588

**Comment by shadeMe** [comment]
Kannst du mir bitte die ISSNs der jeweiligen Zeitschriften, die davon betroffen sind, posten?

**Comment by kdr154** [comment]
Auch hier werden Titel und Namensbestandteile absolut unzutreffend umgesetzt:
https://www.tandfonline.com/doi/full/10.1080/00344087.2016.1125193
Der Titel Dr. wird als Nachname interpretiert, der gesamte Rest: Siebren Miedema Prof Em als Vorname

**Comment by kdr154** [comment]
Bei dieser ZS, auch die ZS, auf die sich der vorherige Comment bezieht, wird der Begriff "Editor" beim Verfasser mitübertragen:
ISSN 1547-3201 Religious Education
Beispiel: https://www.tandfonline.com/doi/full/10.1080/00344087.2018.1480206

**Comment by shadeMe** [comment]
Bereit zum Testen.

**Comment by shadeMe** [comment]
Ist das Problem immer noch nicht gelöst? Wenn nicht, brauche ich Beispiele, bei denen es auftritt.

PS: Nochmal zur Information - Diese Titulatur-Problematik wird nur beim automatischen Verfahren funktionieren. Beim halbautomatischen Verfahren _müssen_ die Namen händisch korrigiert werden

**Comment by kdr154** [comment]
Dann müssen wir es schließen
