### ISSUE TITLE
ISSN 2210-5956 | Journal of Sufi Studies | Doppelnamen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1480]
Hier werden die Doppelnamen nicht korrekt aufgelöst:
https://brill.com/view/journals/jss/9/1/article-p106_4.xml

![grafik](https://user-images.githubusercontent.com/29707105/114826287-9a6fc100-9dc7-11eb-8c9e-c4c802ebe57f.png)

https://brill.com/view/journals/jss/9/1/article-p153_7.xml

![grafik](https://user-images.githubusercontent.com/29707105/114826374-b83d2600-9dc7-11eb-9e88-66d2bbffa9bc.png)

**Comment by socheres** [comment]
weder HTML-Quelltext noch die dort angebotenen Metadaten lösen die Doppelnamen korrekt auf. Daher ist eine maschinelle Zuordnung leider nicht möglich. Solche Fälle mit mehr als 3 Vornamen könnte man vllt. über Regex-QA-Setting abfangen.

```
TY  - JOUR
TI  - Transposing Metaphors and Poetics from Text to World: The Theo-Poetics of L?h?r??s ?Mystical Commentary? on ??fi??s Love Lyrics
JO  - Journal of Sufi Studies
AU  - Takacs, Axel Marc Oaks
PY  - 25 Mar. 2021
DA  - 25 Mar. 2021
PB  - Brill
CY  - Leiden, Niederlande
UR  - https://brill.com/view/journals/jss/9/1/article-p106_4.xml
DO  - https://doi.org/10.1163/22105956-BJA10008
VL  - 9
IS  - 1
SP  - 106
EP  - 144
LA  - English
ER  - 
```

**Comment by socheres** [comment]
#1483
