### ISSUE TITLE
ISSN 2210-5956 | Journal of Sufi Studies | Todessymbol Bestandteil des Namens und Vorname

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1481]
Hier wird der symbolische Hinweis, dass eine Person bereits verstorben ist, zum Bestandteil des Nachnamens.

https://brill.com/view/journals/jss/9/1/article-p52_3.xml

![grafik](https://user-images.githubusercontent.com/29707105/114826746-28e44280-9dc8-11eb-8c16-3ad6c69726cc.png)

Darüber hinaus wird der abgekürzte erste Vorame "Th." verworfen.

**Comment by socheres** [comment]
auf http://benu.ub.uni-tuebingen.de/zotero_cgi korrekt. Nach PR-Bestätigung durch @jriedl kann getestet werden.
```
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="4">aut</subfield>
<subfield code="a">Homerin, Th. Emil</subfield>
<subfield code="e">VerfasserIn</subfield>
</datafield>
```

**Comment by socheres** [comment]
@kdr154 schließe dieses Issue #1483
