### ISSUE TITLE
ISSN 0720-6259 | Pastoraltheologie | Multi-DL und Zusatztitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1484]
**URL**
https://www.vr-elibrary.de/toc/path/110/4

**Ausführliche Problembeschreibung**
Der angebotene Translator "ubtue_University of Chicago Press Journal" für den Multi-DL öffnet zwar das Auswahl-Fenster der Artikel, doch diese werden danach nicht nach Zotero übertragen.

Im Single-DL wird der Translator "Atypon" angeboten. Hier werden die Zusatztitel nicht mit übertragen.

Gleiches gilt für die Zs "Göttinger Predigt-Meditationen" https://www.vr-elibrary.de/toc/gpre/75/3

**Offenbare Lösungen**
Schön wäre für die Seiten ein funktionierender Multi-DL.

**Comment by socheres** [comment]
@IxKo über RSS-Feed Funktion in Zotero-Client können die aktuellen Daten im Multi-DL geladen werden. https://www.vr-elibrary.de/page/feeds.jsp?utm_source=Anzeige&utm_medium=organic&utm_campaign=Conversion-Gruppen%C3%BCbergreifend-Anzeige%20eTOC
Zeitschriften von V&R sollten wir demnächst im Zotaut testen.

**Comment by IxKo** [comment]
Bei dem Vorgang über RSS kommen die Zusatztitel der Aufsätze aber auch nicht mit!

Es ist auch nicht abzuschätzen, wann die V&R-Zss mit zota live gehen werden. Noch testen wir diese nicht und haben noch T&F vor uns.
In der Zwischenzeit sollten sie aber ohne viel Mehraufwand mit dem halbautomatischen Verfahren erfasst werden können.

**Comment by socheres** [comment]
Bin gerade dabei ein Translator zu schreiben.

**Comment by socheres** [comment]
Bitte ausgiebig testen. Englische Zusammenfassung kann leider nicht heruntergeladen werden.

**Comment by IxKo** [comment]
Daten sehen gut aus, vielen Dank!
