### ISSUE TITLE
ISSN 2628-5819 | Gottesdienst : Information u. Handreichung der liturgischen Institute Deutschlands, Österreichs | ISSN oder Titel der Publikation

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1485]
https://www.herder.de/gd/hefte/archiv/2021/4-2021/
https://www.herder.de/gd/hefte/archiv/2021/4-2021/gottesdienst-im-pandemiemodus-teil-2/

Bei dieser Zeitschrift wird weder eine ISSN noch der Titel der Publikation übertragen. Eine Zuordnung zur Gesamtaufnahme und zur physischen Form ist daher weder über die ISSN noch über den Zeitschriftentitel möglich.

![grafik](https://user-images.githubusercontent.com/29707105/115826639-83eee880-a40b-11eb-83a7-99c79ad3e7ef.png)

**Comment by socheres** [comment]
ubtue_herder Translator muss noch überarbeitet werden. Viele Felder wie z.B. ISSN, Abstracts bei anderen Herder-Zeitschriften werden auch nicht übernommen.
https://www.herder.de/bn-nf/hefte/archiv/2021/188-2021/und-es-waren-hirten-in-demselben-land-vom-verstaendnis-der-hirten-zu-einer-neuen-hermeneutik-der-lukanischen-weihnachtsgeschichte-teil-2/

**Comment by kdr154** [comment]
Danke, @IxTheoKm hat nachgefragt.

**Comment by socheres** [comment]
ISSN ist im Quelltext nicht vorhanden, daher über den Zeitschriftentitel mit PPN verknüpfen. Bitte "journal_title_to_ppn.map" ggfs. "publication_title_to_physical_form.map" ergänzen.

**Comment by kdr154** [comment]
Hatte ich bereits gemacht. Jetzt wird der Titel geliefert. Daher klappt es nun auch.
