### ISSUE TITLE
Test-DB (K10plus) Aufsätze als Oax <leader>

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1487]
**URL**
Beispiel:
IxTheo#2021-04-19#8A3C8A95AB5A6AE8D016E42D9F2B67A95B643BFC

**Ausführliche Problembeschreibung**
Unsere Daten werden seit 19.04. (EInspieldatum ab 20.04.) als Oax-Sätze in die Test-DB des BSZ eingespielt und nicht mehr als Osn-Aufnahmen.
Die Live-Einspielungen scheint es nicht zu betreffen

In den Marcxml-Daten der WinIBW steht 
`<leader> nam a22 2 4500</leader>`
Unsere gelieferte Daten sehen jedoch so aus: 
`<leader>00000nab a22004452  4500</leader> 
` 

Auch interessant: Wenn ich einen Datensatz in der Live-DB des K10plus ansehe, den wir entweder als Osn mit Zotkat oder zota einspielen, dann heißt der leader:
`<leader> naa a22 2 4500</leader>
`

**Offenbare Lösungen**
Das sollte mit dem BSZ geklärt werden.

**Comment by IxKo** [comment]
Ist das Label "Einspielung_Zotero_AUTO" nur für Live-Einspielungen gedacht oder auch für die Test-Einspielungen?

**Comment by kdr154** [comment]
Da läuft was schief beim BSZ. Das "m" im leader bei "nam" statt "nab" bedeutet, dass es sich um eine Monografie/Exemplar handelt, nicht um einen unselbständigen Teil eines fortlaufenden Sammelwerks wie bei "b".
Die Folge ist u. a., dass diese Titel nicht mehr in der Kurzanzeige einer Zeitschrift erscheinen.
Die Daten, die wir ans BSZ liefern, sind definitiv korrekt. 
Vgl. einen Leader der Lieferung von heute:
![grafik](https://user-images.githubusercontent.com/29707105/116364682-bed68f00-a804-11eb-9d62-862066357277.png)

Der wird in die Testdatenbank so eingespielt:

![grafik](https://user-images.githubusercontent.com/29707105/116365010-1d9c0880-a805-11eb-825c-28523518510d.png)

![grafik](https://user-images.githubusercontent.com/29707105/116365099-36a4b980-a805-11eb-9c05-713d6d767879.png)

**Comment by kdr154** [comment]
Den 2. Teil mit einem Leader <leader> caa a22 2 4500</leader> finde ich so nicht. Beziehungsweise scheint es mir der Leader der Gesamtaufnahme zu sein.

**Comment by IxKo** [comment]
>Den 2. Teil mit einem Leader <leader> caa a22 2 4500</leader> finde ich so nicht. Beziehungsweise scheint es mir der Leader der Gesamtaufnahme zu sein.

Ja, wo ich den her kopiert habe, ist mir auch gerade schleierhaft. Der erste Buchstabe sollte n sein - habe es angepasst.

**Comment by socheres** [comment]
BSZ-Konverter wurde angepasst.

**Comment by kdr154** [comment]
Danke, heute wurde wieder mit Osn eingespielt.
