### ISSUE TITLE
Pica Export-Translator für Retrokatalogisierungs-Projekte

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1488]
Abrufzeichen „ixrk“ ergänzt.
`ixzs$aixzo$ixrk`

**Comment by socheres** [comment]
@IxKo Bitte testen. Single und Batch.

**Comment by IxKo** [comment]
Funktioniert, vielen Dank!

**Comment by kdr154** [comment]
Bekomme eine Fehlermeldung weil das "a" vor "ixrk" fehlt:
8012 ixzs$aixzo$ixrk

**Comment by kdr154** [comment]
Bitte umgehend korrigieren!

**Comment by IxKo** [comment]
>Soll das Abrufzeichen bei jedem Artikel einer Zeitschrift angehängt werden, die für Retrokatalogisierung vorgesehen ist?

@kdr154 
Das Abrufzeichen soll bei Projekten verwendet werden, bei denen retrospektiv für FID Theologie katalogisiert wird.

**Comment by kdr154** [comment]
Was heißt das f ür die Aufsätze?

**Comment by IxKo** [comment]
Alle theologischen Aufsätze, die im Zuge eines Retro-Projektes katalogisiert werden, erhalten zusätzlich das Abrufzeichen ixrk

**Comment by kdr154** [comment]
Das Abrufzeichen wird aber an alle Aufsätze angehängt, auch an solche, die aktuell katalogisiert werden, deren Zeitschrift für das Projekt vorgesehen ist.

**Comment by IxKo** [comment]
Ach so jetzt verstehe ich das Problem:
@socheres 
Bitte nur bei den Export-Formaten: Retrokat_PicaSWB_batch.js und Retrokat_PicaSWBixzs.js die Abrufzeichen ixzs**$a**ixzo**$a**ixrk vergeben lassen.
Die Export-Formate PicaK10plus_batch und -Single nur ixzs**$a**ixzo

Die Anpassung hat sich wohl auch auf die regulären Export-Formate ausgewirkt.

**Comment by kdr154** [comment]
Korrektur: Es scheint mir einfach an alle Aufsätze angehängt zu werden, die mit Zotero katalogisiert werden.
Habe gerade "Brill Research Perspectives in Religion and Psychology" Zeder-ID 3542 aufgenommen. In der Spalte "retro" steht dort ein Fragezeichen "?". Es haben aber alle Aufsätze, die ich katallogisiert habe das Abrufzeichen "ixrk" bekommen.

**Comment by kdr154** [comment]
Der PicaSWB_batch Exporttranslator steht nicht mehr zur Verfügung.  Es sieht mir so aus, als ob dieser einfach in Retrokat_PicaSWB_batch.js umbenannt wurde, und hier der fehlerhafte Eintrag ergänzt wurde. Denn diesen habe ich in meiner Zotero-App als Exporttranslator vorgefunden. 
Ich habe mir erlaubt in meinem Translator-Verzeichnis daraus die fehlerhafte Ergänzung "$ixzr" zu entfernen, um wieder vernünftig arbeiten zu können. 
Im Übrigen kann dieser "Retrokat_PicaSWB_batch.js" ja nicht der einzige Export-Translator bleiben.
Die Lösung ist ja einfach. Den Retrokat_PicaSWB_batch.js kopieren, einen als PicaSWB_batch benennen und den fehlerhaften Eintrag in einem zu korrigieren, uns in dem anderen zu löschen.

**Comment by socheres** [comment]
> Die Anpassung hat sich wohl auch auf die regulären Export-Formate ausgewirkt und evtl. auch auf weitere?

Eigentlich nicht. Wie aus PR https://github.com/socheres/Zoterobearbeitung/commit/7885a1ca80212c9a5901a608c4a63de9f3bd771d zu entnehmen ist, wurden  andere Pica-Export-Skripten nicht angepasst.

**Comment by kdr154** [comment]
Aha!
