### ISSUE TITLE
ISSN 2468-3493 | Brill Research Perspectives in Theology | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1489]
Keywords werden ncht erfasst:
https://brill.com/view/journals/rpth/3/4/article-p1_1.xml

![grafik](https://user-images.githubusercontent.com/29707105/116082721-07bf0400-a69c-11eb-97dd-52106e0e9c9a.png)

**Comment by socheres** [comment]
Kann diese Brill-Zss. nicht im Zotaut erfasst werden?

**Comment by kdr154** [comment]
Diese Zeitschrift ist ab dem Jahr 2021 keine Zeitschrift mehr, sondern eine Reihe. Das gilt im Überigen für alle Brill Research Perspectives ...  Die Heft haben dann keine ISSN mehr, sondern eine ISBN. Dann auch eine andere Gesamtaufnahme. Sie können das mit den Keywords auch bleiben lassen. Ich erfasse gerade alle Brill Research Perspectives ... komplett. Und ich bin fast fertig. Es gibt sie noch nicht so lange. Die ältesten Hefte datieren aus dem Jahr 2017, manche haben noch später begonnen, 2019 z. B. Es erscheint auch immer nur ein Aufsatz pro Heft. Die Sache ist nur die, ob das nicht ein prinzipielles Problem des Brill-Translators für das halbautomatische Verfahren ist.

**Comment by kdr154** [comment]
Im halbautomatsichen Verfahren wird mir lediglich der Embedded Metadata-Translator angeboten. Dieser liefert die Keywords nicht. Der Translator Brill_Journals steht nicht zur Auswahl.

**Comment by kdr154** [comment]
Bekomme den Translator Brill_Journals immer noch nicht angeboten.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/719#issuecomment-831872531

**Comment by kdr154** [comment]
Keywords sind nun dabei.
