### ISSUE TITLE
ISSN 2167-776x | Journal of Pastoral Care & Counseling | Issues

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1490]
Bei dieser Zeitschrift enthält der Band 75 ein Supplementheft 1 und ein reguläres Heft 1.
https://journals.sagepub.com/loi/PCC?expanded=75

![grafik](https://user-images.githubusercontent.com/29707105/116247375-13c5c700-a76b-11eb-8c9d-957f6ae563f7.png)

Am 18./19. 3. wurde das Supplement eingespielt. Das reguläre Heft steht bis heute aus, obwohl am 13.4. eine Mail über dessen Erscheinen kam.
Das deckt sich auch mit den Angaben auf den Webseiten über das Erscheinen der Aufsätze der einzelnen Hefte. 
Nun enthält der RSS-Feed bis heute nur die Aufsätze des Supplement 1. Die des regulären Artikel sind nicht enthalten.
https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=pcca&type=etoc&feed=rss
Für mich stellt sich die Frage, soll man reguläre Heft manuell katalogisieren und damit eventiell Dubletten erzeugen, oder warten, ob die reguläre Ausgabe doch noch Eingang in den Feed findet.

**Comment by socheres** [comment]
@kdr154 Sind in der Zwischenzeit neue Hefte eingespielt worden?

**Comment by kdr154** [comment]
@socheres Nein.

**Comment by kdr154** [comment]
Am Freitag 18.6. wurde Heft 2 eingespielt, Heft 1 hingegen immer noch nicht.

**Comment by IxKo** [comment]
1_suppl wurde am 18/19.03. eingespielt wie kdr154 im ersten Comment schrieb.
Im K10plus wurde in 4070 $nS manuell ergänzt. Leider habe ich nicht mehr in Erinnerung, ob $n1_suppl da stand oder nichts.

**Comment by socheres** [comment]
Weil in der Kurztitelanzeige $nS fehlte, habe ich 1_suppl mit Heft 1 verwechselt. Ich habe noch die orcid manuell nachgetragen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ist dieses Issue noch aktuell?
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Ist das noch aktuell?

**Comment by IxKo** [comment]
Ist nicht mehr aktuell.
