### ISSUE TITLE
Taylor & Francis?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1493]
Was ist mit Taylor & Francis los?
ISSN 2153-5981 Religion, Brain & Behavior ist jetzt bereits die Dritte Zeitschrift heute, von der keine Daten geliefert werden, weil das Timeout überschritten wurde:

Harvesting URL 2 [Religion, Brain & Be...] | https://www.tandfonline.com/doi/full/10.1080/2153599X.2021.1919365?af=R {5645027897817967694}
Sending request to translation server: https://www.tandfonline.com/doi/full/10.1080/2153599X.2021.1919365?af=R
failed to fetch response from the translation server! error: Timeout was reached

Item 2 [Religion, Brain & Be...] | https://www.tandfonline.com/doi/full/10.1080/2153599X.2021.1919365?af=R {5645027897817967694} download failed! error: Timeout was reached (response code = 28)

Ganz down scheint der Server ja nicht zu sein, kamen doch bei der ersten Zeitschrift heute morgen drei Online-First-Artikel zurück.
Kann es sein, dass uns Taylor&Francis gesperrt hat? Kann dem bitte jemand nachgehen?
Im Übrigen erhalte ich dasselbe Ergebnis auf nu und auf ub28.

**Comment by jriedl** [comment]
Zumindest bei der ersten URL gab es einen Abbruch aufgrund der Untertitel-Behandlung. Auf nu ist jetzt eine aktualisierte Version. Bitte nochmals testen.

**Comment by kdr154** [comment]
Alle drei laufen jetzt durch.

**Comment by jriedl** [comment]
Aktueller Stand dann jetzt auch auf ub28.

**Comment by kdr154** [comment]
Danke, dann schalte ich zwei live,  bei einer gibt es noch ein anderes Problem.
