### ISSUE TITLE
ISSN 1445-7377 | Indo-Pacific Journal of Phenomenology | Artikel-ID

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1494]
https://www.tandfonline.com/toc/ripj20/20/1?nav=tocList
Bei dieser Zeitschrift wird wieder die Artikel-ID statt der Seitenzahlen geliefert.
Statt 936 $h sollte 936 $i erzeugt werden.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das müsste jetzt eigentlich funktionieren, es wurde schon länger von @socheres umgesetzt und funktioniert auch auf NU.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, funktioniert.
@jriedl: Wenn ich in den QA-Settings das Feld 936 i (für Artikelnummern) ergänzen möchte, müssen dann auch alle anderen Unterfelder von 936 für alle 3 Typen (Artikel, Review, Notes) festgelegt werden?

Und nur wenn es auf Nu festgelegt ist, wird es nicht automatisch bei einer ub28-Aktualisierung auf ub28 übertragen?

Ich frage, weil es doch recht viel Zeit in Anspruch nimmt, wegen einer Unterfeld-Änderung 3x alle Unterfelder zu ändern und das dann nochmal auf ub28:

![image](https://user-images.githubusercontent.com/57000004/154945995-06ba300c-93c1-46bd-8895-14dbf4fd475e.png)

**Comment by jriedl** [comment]
Wenn es für alle drei Fälle gleich ist, sollte es genügen, das für normale Artikel einzutragen, die anderen Typen greifen dann darauf zurück. Im Bezug auf die Übertragung hatte ich vor Längerem einmal Scripte zum Aus- und Einspielen entwickelt, die kamen aber bislang nicht zum Einsatz. Ob das sinnvoll ist, hängt auch davon ab, wieviele manuelle Regeln es auf ub28 gibt, die nicht auf nu sind.
