### ISSUE TITLE
ISSN 1468-2265 | The Heythrop Journal | Rezensionen, Seitenzahlen (Wiley)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1497]
https://onlinelibrary.wiley.com/toc/14682265/2021/62/3?campaign=woletoc

https://onlinelibrary.wiley.com/doi/10.1111/heyj.13918

Rezensionen werden nicht getagt. Der Begriff "Book Review" befindet sich aber auch auf der Seite.

Es werden immer zwei Seitenzahlen ausgegeben. Bei Artikeln, die sich auf einer Seite befinden, sollte nur eine ausgegeben werden.

Beide Mängel in dem Beispiel zu finden.

**Comment by socheres** [comment]
"RezensionstagPica" ist als Tag im importierten Datensatz enthalten und wird auch entsprechend im Pica 1131 !106186019! richtig umgesetzt.
```
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2021\n1131 !106186019!\n1500 eng\n1505 $erda\n2051 10.1111/heyj.13918\n3000 !769396259!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [Madigan, Patrick] maschinell zugeordnet\n\n4000 Phantasia in Aristotle\u2019s Ethics$dReception in the Arabic, Greek, Hebrew and Latin Traditions. Edited by Jakob Leth Fink. Pp. 175, London/NY, Bloomsbury, 2019, \u00a380.75/$114.00.\n4070 $v62$j2021$a3$p599\n4241 Enthalten in!320573052!\n4950 https://doi.org/10.1111/heyj.13918$xR$3Volltext$4ZZ$534\n4950 https://onlinelibrary.wiley.com/doi/abs/10.1111/heyj.13918$xH$3Volltext$4ZZ$534\n5056 1\n5520 \nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");
```

**Comment by kdr154** [comment]
Bei mir nicht:
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2021\n1500 eng\n1505 $erda\n2051 10.1111/heyj.13918\n3000 !769396259!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [Madigan, Patrick] maschinell zugeordnet\n\n4000 Phantasia in Aristotle\u2019s Ethics$dReception in the Arabic, Greek, Hebrew and Latin Traditions. Edited by Jakob Leth Fink. Pp. 175, London/NY, Bloomsbury, 2019, \u00a380.75/$114.00.\n4070 $v62$j2021$a3$p599-599\n4241 Enthalten in!320573052!\n4950 https://doi.org/10.1111/heyj.13918$xR$3Volltext$4ZZ$534\n4950 https://onlinelibrary.wiley.com/doi/abs/10.1111/heyj.13918$xH$3Volltext$4ZZ$534\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

**Comment by helenanebel** [comment]
Lieber @kdr154 , bei mir wird es beim Batch-Verfahren ebenfalls richtig exportiert: application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2021\n1131 !106186019!\n1500 eng\n1505 $erda\n2051 10.1111/heyj.13918\n3000 !769396259!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [Madigan, Patrick] maschinell zugeordnet\n\n4000 Phantasia in Aristotle\u2019s Ethics$dReception in the Arabic, Greek, Hebrew and Latin Traditions. Edited by Jakob Leth Fink. Pp. 175, London/NY, Bloomsbury, 2019, \u00a380.75/$114.00.\n4070 $v62$j2021$a3$p599\n4241 Enthalten in!320573052!\n4950 https://doi.org/10.1111/heyj.13918$xR$3Volltext$4ZZ$534\n4950 https://onlinelibrary.wiley.com/doi/abs/10.1111/heyj.13918$xH$3Volltext$4ZZ$534\n5056 1\n5520 \nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");
und der Tag ist dementsprechend ebenfalls vorhanden. Fehlt der Tag auch im Zotero-Export? Wir können gerne auch heute Nachmittag im Anschluss an das Zotaut-Meeting nochmal sprechen.

**Comment by kdr154** [comment]
Mein Beispiel ist doch das Ergebnis des Exports.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
entschuldigen sie, ich meinte den Zotero-Import. Aber wir sollten wahrscheinlich einfach heute Nachmittag nochmal draufschauen.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Das Problem mit den doppelten Seitenzahlen bei einseitigen Dokumenten ist, wie man sehen kann, auch nicht behoben: p599-599.
Fehlt beim Import.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
hatten wir das Problem nicht neulich im Meeting behoben?
Viele Grüße, Helena

**Comment by kdr154** [comment]
Das war die Sache, dass der Standard Wiley Translator vor dem ubtue_wiley angeboten wird. Und wenn man nicht aufpasst, kommt es zu dem Fehler. Mit dem ubtue_wiley ist alles korrekt.
Hatte @socheres nicht gebeten, die Priorität der Translatoren zu ändern. Das wäre echt von Vorteil.

**Comment by helenanebel** [comment]
Das ist bereits so eingestellt, der ubtue-Translator hat 99 und der andere 100 als Priorität, allerdings in Ihrem Verzeichnis noch nicht. Wahrscheinlich hat @socheres die Translatoren noch nicht aktualsiert.

**Comment by kdr154** [comment]
was die Daten anbelangt, sind die Mängel behoben.
