### ISSUE TITLE
ORCID halbautomatisches Verfahren

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1499]
Es sollte eine Möglichkeit gefunden werden, auch im halbautomatischen Verfahren die ORCID zu erfassen und einzuspielen.
Ein Beispiel, wo eine ORCID vorhanden ist: 
https://www.ejournals.eu/Studia-Religiologica/2020/Numer-53-4-2020/art/18056/

**Comment by socheres** [comment]
#1496 
ToDo:
- [ ] ORCID
- [ ] customise PICA-Export-Translator for ORCID
