### ISSUE TITLE
ISSN 2352-8230 | Philosophia Reformata | Heft wird nicht eingespielt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1500]
Es findet keine Einspielung des Bandes 86.2021,1 statt.
https://brill.com/view/journals/phir/86/1/phir.86.issue-1.xml?utm_source=eToC&utm_medium=email&utm_campaign=Content_Alerts
E-Mail-Benachrichtigung über das Erscheinen des Hefts 5.5.
Heft ist Inhalt des aktuellen RSS-Feeds
https://brill.com/journalissuetocrss/journals/phir/phir-overview.xml

**Comment by jriedl** [comment]
Hängt wohl mit dem Vorkommen von Kleinbuchstbaben in der DOI bei diesen Artikeln zusammen: Artikel wurden in diesem Fall zwar heruntergeladen, allerdings fälschlich als bereits geliefert eingeordnet und deshalb nicht weiter verarbeitet . Eine angepasste Version findet sich auf nu und ub28. Sollte morgen bei der Einspielung sichtbar sein.

**Comment by kdr154** [comment]
wurde heute eingespielt.
