### ISSUE TITLE
ISSN 2169-1304 | Theological Studies | Erneute Einspielung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1502]
Am 12.5 wurden vier Sätze erneut eingespielt, die bereits am 11.4. eingespielt wurden:

12.5. IxTheo#2021-05-11#5598670A45ED8D9347B5B8297DBC5C9E6CE6FADB
11.4. IxTheo#2021-04-10#5598670A45ED8D9347B5B8297DBC5C9E6CE6FADB

12.5. IxTheo#2021-05-11#B66B20CDDAB9032C016A50BE8D0B68A2D3BF3275
11.4. IxTheo#2021-04-10#B66B20CDDAB9032C016A50BE8D0B68A2D3BF3275

12.5. IxTheo#2021-05-11#B5E57E8E65D25AE85D153B90B5D6591BD1DC07C2
11.4. IxTheo#2021-04-10#B5E57E8E65D25AE85D153B90B5D6591BD1DC07C2

12.5. IxTheo#2021-05-11#4DAF28782AEC347028174D65D3F64692F1409803
11.4. IxTheo#2021-04-10#4DAF28782AEC347028174D65D3F64692F1409803

**Comment by jriedl** [comment]
Die zugehörigen DOIs sind 
- https://doi.org/10.1177/00405639211003277c 
- https://doi.org/10.1177/00405639211003277d
- https://doi.org/10.1177/00405639211003376e
- https://doi.org/10.1177/00405639211003376c
d.h. das ist eine Nachwehe des in der Vergangenheit inkorrekten Trackings bei DOIs mit Kleinbuchstaben (vgl. #1500) und sollte zukünftig nicht mehr auftreten.

**Comment by kdr154** [comment]
ok
