### ISSUE TITLE
ISSN 2665-9484 | Trajecta | ISSN (ingenta)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1503]
**URL**
https://www.ingentaconnect.com/content/aup/traj/2020/00000029/00000002

**Ausführliche Problembeschreibung**
Hier kommt im Single-DL die ISSN nicht nach Zotero rüber.
Schön wäre auch ein funktionierender Multi-DL

**Comment by IxKo** [comment]
Mir wird nun kein spezifischer Translator mehr angeboten (nur die üblichen Verdächtigen: Embedded Metadata, DOI und Web Page)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das liegt daran, dass sich hier die URL geändert hat: https://www.aup-online.com/content/journals/07788304/29/2 und diese nicht mehr dem zugrundegelegten Muster entspricht. Ich passe das an.
Viele Grüße, Helena Nebel

**Comment by thefass** [comment]
Stimmen die Angaben in Zeder, z.B. Spalte rss oder b_zot noch? Wenn nicht, bitte anpassen/Infos in den Spalten löschen. In der Historie sind die Infos ja erhalten, in den Spalten sollten sie immer aktuell sein

**Comment by socheres** [comment]
Diese Zeitschrift wird nicht mehr auf Ingenta-Plattform betrieben, daher sollte man hier einen neuen Translator schreiben.

**Comment by IxKo** [comment]
Ja, stimmt. Der Link, den ich eingangs genannt habe, enthält zwar noch "ingenta" leitet aber dann auf aup weiter.

Die Zs wird zwar über EBSCO/ATLA indexiert. Es existiert jedoch nicht wie üblich eine Übersichtsseite der Zss mit Jahrgängen und Heften.
Daher wäre ein Translator für die Seite einfacher zur Katalogisierung. 
Es gibt auch eine weitere Zss (z=376), die ebenfalls auf AUP geführt wird.

Mit dem **DOI-Translator** geht Multi-DL. Bei den Daten fehlen jedoch die Keywords. Wenn kein Translator wegen zwei Zss geschrieben werden soll, könnte man diese auch manuell (Copy & Paste in ein Word-Dokument und Suchen&Ersetzen der Trennzeichen mit Absatzmarken und dann Copy&Paste nach Zotero).

>Stimmen die Angaben in Zeder, z.B. Spalte rss oder b_zot noch? Wenn nicht, bitte anpassen/Infos in den Spalten löschen. In der Historie sind die Infos ja erhalten, in den Spalten sollten sie immer aktuell sein
Der RSS musste gelöscht werden. Die anderen Spalten passe ich an, sobald klar ist, wie zukünftig die Daten erfasst werden können/sollen.

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres ,
da war nicht viel anzupassen, ich habe jetzt einen neuen Translator "ubtue_AUP" auf Basis von Embedded Metadata angelegt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel Prima, funktioniert gut, danke!
