### ISSUE TITLE
OJS-Translators

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1504]
**URL**
https://www.sanisidoro.net/publicaciones/index.php/isidorianum/issue/view/11

**Ausführliche Problembeschreibung**
Translators: 
(ubtue_Open Journal Systems Multi-Wrapper) (Verbesserungen wurden in ubtue_Open Journal Systems Standard gemacht)
ubtue_Open Journal Systems Standard

- [x] Auf den Artikel-Webseiten befinden sich **Abstracts**, die nicht übernommen werden.

Bei dieser OJS-Zs gibt es zudem die Option, die Seite auf Englisch umzustellen und so die englischen Keywords und Abstracts sowie den Paralleltitel zu sehen.
Ist es möglich, auch diese Informationen mit einem Translator abzugreifen?

- [x] Zumindest das **englische Abstract** scheint im spanischen HTML vorhanden zu sein in <meta name="DC.Description" xml:lang="en" content="...

- [x] und der **Paralleltitel** in <meta name="DC.Title.Alternative" xml:lang="en" content="...

Nur die Keywords wohl nicht.

Der Paralleltitel müsste ins Pica-Feld 4002. Hierfür gibt es meiner Erfahrung nach noch kein geeignetes Feld in Zotero bzw. noch keine technische Umsetzung.

_____
ORCID wird sogar auch übernommen und die Rezensionen getagt.

**Comment by socheres** [comment]
Anpassung ubtue_Open Journal Systems Standard:
- [x] Paralleltitel mit Nicht-Sortierzeichen #1250 
- [x] beide Abstracts
- [x] Keywords mindestens in english
- [x] ORCID im Feld "Call Number" #1499 
- [x] Rezensionen

**Comment by IxKo** [comment]
Sieht alles sehr gut aus!
ORCID kommt auch mit, Paralleltitel noch nicht

**Comment by socheres** [comment]
Die Sprache muss leider intellektuell nochmal geprüft werden. .
Englische Paralleltitel werden nur bei den spanischen Originaltitel erzeugt. Z.B. https://www.sanisidoro.net/publicaciones/index.php/isidorianum/article/view/146 hier kommen Paralleltitel mit und wird auch in Pica richtig umgesetzt. 
```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020
1500 spa
1505 $erda
2051 10.46543/ISID.2029.1053
3000 Fernández, Teresa Bejarano$BVerfasserIn$4aut
4000 Parábolas, altruismo espontáneo y coherencia cognitiva. Analizando la eficaz construcción de algunas parábolas
4002 Parables, Spontaneous Altruism and Cognitive Coherence. Analyzing the effective construction of some parables
4070 $v29$j2020$a2$p13-36
4207 Several resources used in the construction of a group of parables coincide with points that current science focuses on. 1) The fact that the situation of others is perceived in a more objective way, with fewer biases, than one’s own situation. 2) The “spontaneous altruism”, which pushes towards automatic helpful behaviors. 3) The strong influence that language can have in modulating attention, both that of others and one’s own. 4) Cognitive coherence, which intervenes in self-control, both moral self-control and that which is at the service of the subject’s own interests. In analyzing the effect of these points on the parables at issue, I try to show that human communicative skills are there at their best to facilitate the hearer’s decision, and that this facilitation process is completely different from manipulations of any kind., Varios recursos empleados en la construcción de un grupo de parábolas coinciden con puntos que la ciencia actual enfoca. 1) El hecho de que la situación ajena es percibida de un modo más objetivo, con menos sesgos, que la situación propia. 2) El “altruismo espontáneo”, que empuja a conductas automáticas de ayuda. 3) La enorme influencia que el lenguaje puede ejercer para modular la atención, tanto la ajena como la propia. 4) La coherencia cognitiva, que interviene en el autocontrol, tanto el autocontrol moral como el que está al servicio de los propios intereses del sujeto. Al analizar el efecto de esos puntos en las parábolas en cuestión, intento mostrar que las capacidades comunicativas humanas están allí funcionando al máximo para facilitar la decisión del oyente, y que esa facilitación o ayuda es diferente por completo a las manipulaciones de cualquier tipo.
4241 Enthalten in!1758153822!
4950 https://doi.org/10.46543/ISID.2029.1053$xR$3Volltext$4LF$534
4950 https://www.sanisidoro.net/publicaciones/index.php/isidorianum/article/view/146$xH$3Volltext$4LF$534
5056 1
5520 |s|altruismo espontáneo
5520 |s|castigo altruístico
5520 |s|coherencia cognitiva
5520 |s|decisión moral
5520 |s|parábolas
8910 orcid:0000-0002-0037-549X | author=Autores/as Teresa Bejarano Fernández Universidad de Sevilla  | taken from website
E* l01
7100 $Jn
8012 ixzs$aixzo
```

**Comment by IxKo** [comment]
Ok, vielen Dank!
Dann passt nun alles, was zu machen ist.
