### ISSUE TITLE
ISSN 0142-064X | Journal for the Study of the New Testament | Paralleltitel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1506]
Im halbautomatischen Verfahren wird in diesem Fall ein Pica-Feld 4002 mit einem parallelen Titel, in diesem Fall ausschließlich mit einer parallelen Veranttwortlichkeitsangebe erzeugt, die wohl auf dem Eintrag im Zoterofeld "Extra" basiert.
https://journals.sagepub.com/toc/jnta/43/3
https://journals.sagepub.com/toc/jnta/43/3
Zotero:
![grafik](https://user-images.githubusercontent.com/29707105/119621267-31d42500-be06-11eb-8357-644bc16ec1e6.png)

Winibw:

![grafik](https://user-images.githubusercontent.com/29707105/119621356-4e705d00-be06-11eb-89fd-2d375423b174.png)

Das sollte nicht sein. Der Eintrag ist überflüssig und formal nicht korrekt.
Kann es sein, dass dies mit der neueren Entwicklungen am OJS-Translator zusammenhängt?
Lösche das Feld in der Winibw.

**Comment by socheres** [comment]
Ja, das hat etwas mit dem #1504 zu tun. Ich habe den betreffenden Code zunächst auskommentiert und die Verzeichnisse akutualisiert. Für Paralleltitel werde ich ein anderes Feld verwenden, das noch nicht belegt ist. Vielleicht "Signatur".

**Comment by kdr154** [comment]
Ok, dann schließe ich.
