### ISSUE TITLE
ISSN 2196-8020 | Kerygma und Dogma | Summary (V&R Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1507]
https://www.vr-elibrary.de/toc/kedo/67/2
Bei den Artikeln mit englischen Abstract bleibt immer der Begriff "Summary" stehen. Da das nächste Wort ohne Blank folgt, ist dies etwas störend.
https://www.vr-elibrary.de/doi/10.13109/kedo.2021.67.2.148
![grafik](https://user-images.githubusercontent.com/29707105/119675524-67483500-be3d-11eb-9afb-541b58716cc7.png)

Bei den Artikel mit deutschem Abstract hingegen wurde der Begriff "Zusammenfassung" entfernt.
https://www.vr-elibrary.de/doi/10.13109/kedo.2021.67.2.101
![grafik](https://user-images.githubusercontent.com/29707105/119675808-a6768600-be3d-11eb-8551-4d5787c1fd16.png)

Es wäre nicht schlecht, wenn man dies auch für die englischen Abstracts so einrichten könnte.

**Comment by socheres** [comment]
Zur Erinnerung: auf ub28 sind die Translators noch nicht aktualisiert. Vor Live-Schaltung wie besprochen @jriedl informieren.

**Comment by kdr154** [comment]
"Summary" wird entfernt.
