### ISSUE TITLE
ISSN 0012-2157 | Dialogue : a journal of Mormon thought | Selektiv greift nicht

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1508]
Bei dieser Zeitschrift greift das Kriterium ausw=selek nicht. D. h. im Lokalsatz wird kein Abrufzeichen dafür gesetzt.
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26bquery%3dJN%2b%2526quot%253bDialogue%253a%2bA%2bJournal%2bof%2bMormon%2bThought%2526quot%253b%2bAND%2bDT%2b20210301%2bNOT%2bPM%2bAOP%26type%3d1%26searchMode%3dAnd%26site%3dehost-live
Zeder-ID=1442

**Comment by socheres** [comment]
Welcher Export-Translator haben Sie benutzt? Wenn Sie "Selektiv_PicaK10plus_batch" ausgewählt haben, wird das Selektionskriterium für den BSZ-Abzug "SSG 0 bzw. 1" beim Pica-Export nicht hinzugefügt.

**Comment by kdr154** [comment]
Den "PicaK10plus_batch". Sollte ich "Selektiv_PicaK10plus_batch" nehmen? War aber bei den letzten beiden nicht nötig.

**Comment by socheres** [comment]
Ja, unbedingt "Selektiv_PicaK10plus_batch" verwenden, wie auch hier #1129 (siehe eMail vom 10.Mai.2021 08:54"

**Comment by kdr154** [comment]
Ok, beim nächsten Mal. Aber jetzt ergänze ich das Abrufzeichen "NABZ" manuell. Das geht schneller als alles wieder neu einzuspielen und 5056 zu ergänzen.

**Comment by kdr154** [comment]
Warum wird die SSG-Nummer nicht gesetzt?

**Comment by socheres** [comment]
Da die Aufsätze selektiv ausgewertet werden soll, wird die SSG-Nummer nachträglich gesetzt.

**Comment by kdr154** [comment]
Oh ja, eigentlich klar. Danke!

**Comment by IxKo** [comment]
Beim Export-Translator Selektiv_PicaK10plus_batch wird fälschlicherweise das Abrufzeichen ixrk für das Retrokatalogisierungsprojekt Theologie mit ausgegeben. 
Das muss entfernt werden.

**Comment by IxKo** [comment]
Mit dem selektiven Export-Translator werden jetzt korrekt nur noch Abrufzeichen ixzo und ixzs vergeben. 

Die Zs wurde in Zeder am 22.06. auf aus=voll umgestellt, daher schließe ich.
