### ISSUE TITLE
ISSN 0425-340X | Estudio agustiniano | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1510]
https://revistas.agustinosvalladolid.es/index.php/estudio/issue/view/3
Beim Multi-DL bekomme ich die Fehlermeldung "Es ist ein Fehler aufgetreten ..." und der DL bricht ab.
Das ist sowohl beim Multi-Wrapper als auch beim Open_Journals_System_Standard der Fall.
Beim Single-DL bekomme ich diese Fehlermeldung ebenfalls. Allerdings werden Daten heruntergeladen.
Bei diesen fehlen lediglich die Keywords. Darüber hinaus wird das englische Abstract übertragen.
Hier ist meine Vermutung, dass zuerst der DL mit der OJS_Standard versucht wird, dann aber der Embedded Metadata genommen wird.

**Comment by socheres** [comment]
Multi-DL mit "Open_Journals_System_Standard" sollte funktionieren.

**Comment by kdr154** [comment]
Mit dem Open_Journal_Systems_Standard klappt der Download jetzt.
Allerdings:

- [ ] -fehlen die Keywords



- [ ] bei englischsprachigen Artikeln stimmt die Angabe im Feld Sprache nicht:

https://revistas.agustinosvalladolid.es/index.php/estudio/article/view/9

![grafik](https://user-images.githubusercontent.com/29707105/121510371-d732ef80-c9e7-11eb-8f6b-8f16dcebf1f7.png)

**Comment by socheres** [comment]
@IxKo im zotkat muss die Sprache manuell überprüft werden. Kandidat für Crawling-Verfahren?

**Comment by IxKo** [comment]
@socheres 
Ich habe es in b_zot vermerkt.
Wie genau Zss in das Crawling-Verfahren überführt werden, muss aus meiner Sicht genauer geklärt werden.
