### ISSUE TITLE
ISSN 2196-8020 | Kerygma und Dogma | Keine Einspielung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1511]
http://www.vr-elibrary.de/action/showFeed?type=etoc&feed=rss&jc=kedo
Diese ZS wurde am 27.5 auf vollautomatisch gesetzt. Bis heute fand keine Einspielung statt.

In den enhancement maps kann ich keinen Hindernisgrund erkennen:

![grafik](https://user-images.githubusercontent.com/29707105/121019640-ea537e80-c79f-11eb-8003-bd14379dace2.png)

Trotzdem hat sie hat auf ub28 den delivery status None:

![grafik](https://user-images.githubusercontent.com/29707105/121019380-a9f40080-c79f-11eb-82ec-a1f063ba0477.png)

**Comment by jriedl** [comment]
Das ist ein Problem mit dem RSS-Feed. Im Gegensatz zu nu, wo dieser abrufbar ist, kommt  auf erhält man auf ub28 beim Versuch des manuellen Download des Feeds ein `HTTP request sent, awaiting response... 403 Forbidden`, d.h. es scheint, als sei die IP gesperrt. Dies müsste also direkt mit dem Anbieter abgeklärt werden.

**Comment by kdr154** [comment]
Wer sollte das machen?

**Comment by kdr154** [comment]
@socheres dann sollte aber das Gesamtpaket von Vandenhoeck gleich mitverhandelt werden.

**Comment by kdr154** [comment]
Vandenhoeck & Ruprecht ist von Brill übernommen worden:
https://www.vandenhoeck-ruprecht-verlage.com/aktuelles/brill-uebernimmt-vandenhoeck-ruprecht#
Deshalb lohnt es sich wahrscheinlich nicht, hier noch weiter daran zu arbeiten.

**Comment by socheres** [comment]
mit dem RSS-Feed https://www.journaltocs.ac.uk/index.php?action=browse&subAction=pub&publisherID=1046&journalID=40313&pageb=1&userQueryID=87994&sort=&local_page=1&sorType=&sorCol=1 funktioniert der Download. Dementsrprechend ändere ich die RSS-Feeds von V&R in ZEDER. @IxKo bitte alle Zeitschriften von V&R auf "prode=zotat" umstellen.

**Comment by socheres** [comment]
@IxKo aktuelle Aufsätze sind leider nicht im FEED-Dienst "journaltocs" enthalten, daher bitte nicht auf zotat umstellen. Hier könnten wir das eMail-Verfahren anwenden.

**Comment by IxKo** [comment]
Ich habe den RSS-Feed der Zs genommen und in Zeder eingetragen.
Vermutlich sollte es nun funktionieren.

-> Überprüfung Test-DB

**Comment by IxKo** [comment]
Nicht mehr aktuell, ich schließe.
