### ISSUE TITLE
GND-Lookup

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1512]
https://brill.com/view/journals/mist/38/1/article-p1_1.xml?body=pdf-44182

Bei diesen beiden Personen hätte man eigentlich erwarten können, dass sie per GND-Lookup verknüpft werden:
Hintersteiner, Norbert PPN 749708840
Nagy, Dorottya PPN 614754755

wurden sie aber nicht.

Hier auch nicht: PPN 784247331 ; 768265169

**Comment by socheres** [comment]
Es gab tatsächlich einen kleinen Fehler im Lookup-URL. Im Zotkat werden sie verknüpft. Zur Info @helenanebel @IxKo

**Comment by kdr154** [comment]
Ein Test auf ub28 führt noch nicht zu dem gewünschten Ergebnis.

![grafik](https://user-images.githubusercontent.com/29707105/121041486-19272000-c7b3-11eb-8324-cbd1ac122221.png)

**Comment by helenanebel** [comment]
Lieber @socheres , liebe @IxKo ,
soll ich dann die bisher erstellten Records für Retrokat nochmal neu erstellen, sobald das Problem behoben ist?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
> Ein Test auf ub28 führt noch nicht zu dem gewünschten Ergebnis.
> 

Die enhancemap wird nächtlich aktualisiert. Jetzt müsste das Problem behoben sein. Könnten Sie @kdr154 nochmal testen?

**Comment by kdr154** [comment]
Ja, jetzt klappt es.

**Comment by socheres** [comment]
> Lieber @socheres , liebe @IxKo ,
> soll ich dann die bisher erstellten Records für Retrokat nochmal neu erstellen, sobald das Problem behoben ist?
> Viele Grüße, Helena Nebel

Ja, bitte.
