### ISSUE TITLE
ISSN 1934-1504 | Quaker history | Rezensionen (Muse - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1514]
Rezensionen werden nicht  getagt
https://muse.jhu.edu/issue/44583
https://muse.jhu.edu/article/793304

![grafik](https://user-images.githubusercontent.com/29707105/121533184-546a5e80-ca00-11eb-90ce-20ca7cced2fa.png)

**Comment by IxKo** [comment]
Beide werden nun mit Test TRY URL auf ub28 als Rezensionen erkannt.
