### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review | Ecumenical chronicle (Wiley - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1517]
Diese ZS enthält Beiträge, bei denen ich mich frage, ob man sie verwerfen soll, oder nicht. Es handelt sich dabei um Grußadressen, kurze Reflexionen, Statements, Kongressberichte und -ankündigungen  ..., die in einem Artikel gesammelt werden, ohne dass die Artikel einen eigenen Titel besitzen.
In dem vorliegenden Heft 73.2021,1
https://onlinelibrary.wiley.com/toc/17586623/2021/73/1
handelt es sich um die folgenden drei Artikel:
https://onlinelibrary.wiley.com/doi/10.1111/erev.12592
https://onlinelibrary.wiley.com/doi/10.1111/erev.12594
https://onlinelibrary.wiley.com/doi/10.1111/erev.12593

Sie sind auch insofern problematisch, da, weil sie keinen Verfasser besitzen, statt dessen ein beliebieger (?) Textschnipsel als Verfasser gesetzt wird:
![grafik](https://user-images.githubusercontent.com/29707105/121542397-6819c300-ca08-11eb-865a-cc695c65d98f.png)

![grafik](https://user-images.githubusercontent.com/29707105/121542497-7962cf80-ca08-11eb-84bd-11d0ea832ec1.png)

![grafik](https://user-images.githubusercontent.com/29707105/121542617-939cad80-ca08-11eb-894e-1e748bb8cb98.png)

Analog auch bei anderen Artikeln in dieser Zeitschrift, die keinen Verfasser besitzen.
Z.B.

https://onlinelibrary.wiley.com/doi/10.1111/erev.12578

![grafik](https://user-images.githubusercontent.com/29707105/121544961-63eea500-ca0a-11eb-874e-34d3d24eb6e4.png)

**Comment by thefass** [comment]
Die Kurzbeiträge sind immer unter dem selben "Titel" (ist eher eine Rubrik) abgelegt. Inhaltlich sind sie m.E. relevant und sollten mit aufgenommen werden

**Comment by socheres** [comment]
das Problem mit Verfasserangaben sollte nach PR-Bestätigung durch @jriedl gelöst sein.

**Comment by kdr154** [comment]
Das Tag bleibt erhalten, wenn auch ohne Inhalt.
![grafik](https://user-images.githubusercontent.com/29707105/121888369-33fc1600-cd18-11eb-855d-ef384911c365.png)

**Comment by jriedl** [comment]
Das Einfügen eines leeren 100-Feldes durch den Harvester ist behoben und demnächst auf ptah, allerdings scheint das Grundproblem mit den Autoren im Wiley-Translator nicht behoben:
![Screenshot from 2021-06-15 10-49-55](https://user-images.githubusercontent.com/13135579/122024878-1e92f480-cdc9-11eb-84c8-939709686079.png)

**Comment by socheres** [comment]
Bei mir mit dem aktuellen Wiley-Translator schon.
![image](https://user-images.githubusercontent.com/1545743/122045428-04afdc80-cdde-11eb-9fc5-4b4a8ed11fdc.png)

**Comment by kdr154** [comment]
Bekomme auf nu in den Fällen, in denen es keinen Verfasser gibt, nur falsche Angaben:

![grafik](https://user-images.githubusercontent.com/29707105/122048122-31192800-cde1-11eb-9a49-ec66ec0a80a4.png)

![grafik](https://user-images.githubusercontent.com/29707105/122048216-49894280-cde1-11eb-83a5-b161ab28b4be.png)

to be continued

**Comment by jriedl** [comment]
Ist sichergestellt, dass das die letzte von uns gemergedte Version ist und nicht eventuell Zotero ein Autoupdate  mit den "offiziellen" Translators gemacht hat? 

> Bei mir mit dem aktuellen Wiley-Translator schon.
> ![image](https://user-images.githubusercontent.com/1545743/122045428-04afdc80-cdde-11eb-9fc5-4b4a8ed11fdc.png)

**Comment by socheres** [comment]
Ja, ich habe die zuletzt gemergte Version ausgewählt. Wie du @jriedl sicherlich kennst, kann man im Scaffold das Translator-Verzeichnis auswählen, daher ist ein Autoupdate ausgeschlossen. Zurzeit kann ich aber leider nicht mit benu testen.

**Comment by kdr154** [comment]
In Zotero sehen die Sachen gut aus, nicht jedoch auf nu.
dort kommt es immer zu einem Abbruch wegen Timeout.
Bei Try RSS ist es immer der 18. Satz, bei dem abgebrochen wird, bei Try URL wird gar nichts geliefert.
![grafik](https://user-images.githubusercontent.com/29707105/122051238-a803f000-cde4-11eb-934c-e8c82798b2ca.png)

**Comment by kdr154** [comment]
Auffallend ist, dass die Rezension nicht unter den Sätzen ist, die geharvestet werden. Kann es sein, dass die zum Abbruch führt? In Zotero ist bei der Rezension kein Schlagwort enthalten.

**Comment by jriedl** [comment]
> Ja, ich habe die zuletzt gemergte Version ausgewählt. Wie du @jriedl sicherlich kennst, kann man im Scaffold das Translator-Verzeichnis auswählen, daher ist ein Autoupdate ausgeschlossen. Zurzeit kann ich aber leider nicht mit benu testen.

Das Update würde dann in das ausgewählte Verzeichnis erfolgen. Ist in Zotero die Einstellung "Edit -> Preferences -> Advanced -> "Automatically check for updated translators and styles" deaktiviert? 

Momentan gibt es ja nach aktuellem Kenntnisstand keinen Unterschied zwischen deiner lokalen und der auf nu aktiven Version.

**Comment by socheres** [comment]
Danke für diesen Hinweis! Bei mir war "Automatically check for updated translators and styles" aktiviert und deshalb konnte den Fehler nicht reproduzieren.

**Comment by jriedl** [comment]
> Auffallend ist, dass die Rezension nicht unter den Sätzen ist, die geharvestet werden. Kann es sein, dass die zum Abbruch führt? In Zotero ist bei der Rezension kein Schlagwort enthalten.

Laut zts.log gibt es bei https://onlinelibrary.wiley.com/doi/10.1111/erev.12592 einen Fehler und danach einen Timeout. Der Fehler mit https://onlinelibrary.wiley.com/doi/10.1111/erev.12515 ist auch in Scaffold reproduzierbar.

**Comment by socheres** [comment]
> Laut zts.log gibt es bei https://onlinelibrary.wiley.com/doi/10.1111/erev.12592 einen Fehler und danach einen Timeout. Der Fehler mit https://onlinelibrary.wiley.com/doi/10.1111/erev.12515 ist auch in Scaffold reproduzierbar.

Ja, das kann ich auch reproduzieren. Ich arbeite an einer Lösung.

**Comment by kdr154** [comment]
Läuft nun auf nu durch.
