### ISSUE TITLE
ISSN 1469-9737 | Mental health, religion and culture | SSG-Nummer (T&F live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1518]
Hier wird kein  Marc21 084, die SSG-Nummer geliefert, obwohl sie in der harvester.conf und in Zeder hinterlegt ist. Die Folge: alle Artikel landen in der Error-Files.
https://www.tandfonline.com/toc/cmhr20/24/3?nav=tocList

![grafik](https://user-images.githubusercontent.com/29707105/121870033-ecb75a80-cd02-11eb-86c3-8c4a48585bd9.png)

![grafik](https://user-images.githubusercontent.com/29707105/121870178-107aa080-cd03-11eb-9c8a-208b4296ae53.png)

**Comment by jriedl** [comment]
Das liegt an `selective_evaluation = true`,  in diesem Fall darf ja kein ssgn mehr gesetzt werden. Hier müssten wir die weitere Behandlung im QS noch absprechen.

**Comment by kdr154** [comment]
Das habe ich soeben auch festgestellt. Für die selektiv auszuwertenden Zeitschriften müsste 084 auf sometimes gesetzt werden. Wollte ich gerade machen, kann aber auch noch das Meeting heute nachmittag abwarten.

**Comment by jriedl** [comment]
Evtl. besteht die Möglichkeit, das im Code zu lösen, damit es nicht in jedem Fall manuell angepasst werden muss.

**Comment by kdr154** [comment]
Wäre nicht schlecht. Allein in der Zeder-Instanz Ixtheo gibt es 326 Zeitschriften, die selektiv ausgewertet werden sollen.

**Comment by IxKo** [comment]
Über die QA-Settings scheint es nicht zu funktionieren. Ich habe bei einer anderen selektiv auszuwertenden Zs auf NU getestet (ISSN 2514-0582 , The Journal of Egyptian Archaeology) und dort die QA-Settings für 084 (Subfield 2 und a) erst auf IGNORE gesetzt und als das am nächsten Tag nicht zu dem gewünschten Ergebnis geführt hat, habe ich auf SOMETIMES gesetzt.

Das führte aber auch nur zu den gleichen Error-Log-Eintragungen: 
>required 084-field is missing
record with URL 'https://doi.org/10.1177/0307513320978412' already in database with the same hash ...

Was genau bedeutet der zweite Punkt?
kdr154 hat gestern die Error-Datensätze auf NU erst auf "Delivered manually" gesetzt und danach resettet, aber auch das führt zu diesen Error-Log-Einträgen.

@jriedl @socheres

**Comment by jriedl** [comment]
Werde dem nachgehen.

**Comment by mtrojan-ub** [comment]
Es sieht nach einem Bug aus und wir arbeiten an einer Lösung; diese wird voraussichtlich am Montag auf nu eingespielt.
Die Info (record with URL ... already in database with the same hash) ist nur für Debugging-Zwecke. Wir speichern ja den aktuellen Lieferzustand in der Datenbank, dabei wird geprüft ob der Datensatz komplett neu in die DB eingefügt wird, oder sich ggf. lediglich der Zustand eines bestehenden Eintrags verändert.

**Comment by jriedl** [comment]
Eine aktualisierte Version ist jetzt auf nu eingespielt. Neben der Korrektur der QS-Logik, sollten ab dem nächsten Pipeline-Durchlauf auch die QS-Anpassungen für Zeitschriften mit selektiver Auswertung automatisch vorgenommen werden.

**Comment by kdr154** [comment]
Gilt das auch für die in #1521 behandelte Problematik bei fehlenden Verfassern? 

Denn obwohl dort alles bei den QA-Settings von Marc 100 auf sometimes steht, sind am 20.6. alle Sätze in den Error-Files gelandet wegen den nicht vorhandenen Verfassern. 

Validating record IxTheo#2021-06-20#DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91...
Record IxTheo#2021-06-20#DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91 is invalid:
required 100-field is missing
record with URL 'https://doi.org/10.1177/03090892211001738' already in database with the same hash (DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91)

**Comment by IxKo** [comment]
Seit 22.6. wurden in die Test-DB mehrere Hefte von selektiv auszuwertenden Zss mit dem Abrufzeichen NABZ eingespielt und ohne SSG.

Ich frage mich nur, wozu es das Abrufzeichen braucht?

**Comment by IxTheoKm** [comment]
Das Abrufzeichen NABZ verhindert die Auslieferung des Datensatzes (bei selektiv auszuwertenden Zeitschriften). 
Wenn er ausgeliefert werden soll, muss im K10plus 5056 ergänzt und NABZ gelöscht werden.

**Comment by IxKo** [comment]
Die Datensätze werden mit keinerlei Abzugskriterium mehr ausgeliefert (weder 0575 mteo noch 5056)
Bsp:
![image](https://user-images.githubusercontent.com/57000004/123641678-c9bc9880-d822-11eb-9f77-ed8600214a12.png)

Oder reicht der Exemplarsatz schon aus, dass ein Datensatz im IxTheo landet?

**Comment by kdr154** [comment]
Nein, der Lokalsatz reicht nicht aus, aber 5056 und/oder 0575 müssen nachträglich bei selektiv auszuwertenden Zeitschriften ergänzt werden.

**Comment by IxKo** [comment]
Aber was ist nun der Sinn von NABZ?
Dass ein:e Fachreferent:in erkennt, dass hier was selektivert werden muss? Das bringt mich gleich zur nächsten Frage: Wie erfahren das die Fachreferent:innen?

Bei einer Live-Einspielung, bei der noch 0575 und 5056 mitgeliefert worden sind, ist der Datensatz im IxTheo gelandet.
Demnach verhindert NABZ nicht, dass ein Datensatz im IxTheo landet: https://ixtheo.de/Record/1757452893

**Comment by kdr154** [comment]
Ich glaube, @socheres ist deswegen mit dem BSZ in Kontakt.

**Comment by IxTheoKm** [comment]
NABZ verhindert die Auslieferung der Datensätze (sofern keine Abzugskriterien in 0575 oder 5056 für IxTheo vorhanden sind).
NABZ-Datensätze für selektiv auszuwertende Zeitschriften müssen dann im K10plus auf Relevanz geprüft werden: was für IxTheo/RelBib geliefert werden soll, muss nachträglich 5056 erhalten und 8012 NABZ muss gelöscht werden.
Vgl. Mail "Default-Lieferung ohne Exemplarsatz" (zuletzt 07.06.2021).

**Comment by kdr154** [comment]
Ja, aber wenn weder 0575 noch 5056 vorhanden sind, wird doch sowieso nichts an den IxTheo geliefert.

**Comment by IxTheoKm** [comment]
Dann ist aber nicht klar, ob das schlicht vergessen wurde, oder ob gezielt nur eine Auswahl getroffen wird.

**Comment by socheres** [comment]
> Ja, aber wenn weder 0575 noch 5056 vorhanden sind, wird doch sowieso nichts an den IxTheo geliefert.

Auch ohne 0575 und 5056 werden die Datensätze an uns geliefert, da BSZ zwei Abzugsroutinen hat: 1x Titeldaten mit den Selektionskriterien und 1x Titel- und Lokalsätze. Durch das Abrufzeichen "NABZ" im Exemplardatensatz werden Titel aus dem Abzug ausgeschlossen (siehe eMail vom  01.06.2021 10:56)

**Comment by IxKo** [comment]
Sollte dann für das halbautomatische Verfahren auch das Abrufzeichen NABZ vergeben werden?

**Comment by socheres** [comment]
Liebe @IxKo @kdr154 @IxTheoKm Danke für Ihre Kommentare! Habe "NABZ" auch für Zotkat ergänzt.

**Comment by kdr154** [comment]
Scheint gelöst siehe #1508
