### ISSUE TITLE
ISSN 1936-1351 | American journal of criminal justice | URL mehrfach apiquery

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1519]
Manchmal wird der DOI zweimal in einen URL aufgelöst. Z.B. hier:

https://link.springer.com/article/10.1007/s12103-020-09550-4

![grafik](https://user-images.githubusercontent.com/29707105/121908093-f655b800-cd2c-11eb-8a7e-58c516318038.png)

Manchmal existiert nur ein URL. Z. B. hier:

https://link.springer.com/article/10.1007/s12103-020-09561-1

![grafik](https://user-images.githubusercontent.com/29707105/121908381-3ddc4400-cd2d-11eb-9cf5-7f4386dde1bc.png)

**Comment by jriedl** [comment]
Zukünftig wird nur noch die Harvester-generierte DOI-URL verwendet. Beispiele in den vier testweise gestern erneut auf nu eingespielten Artikeln.

**Comment by kdr154** [comment]
Kann man schließen?

**Comment by jriedl** [comment]
Falls kein Problem mehr aufgefallen ist, ja.
