### ISSUE TITLE
ISSN 1476-6728 | Journal for the study of the Old Testament | QA-Settings ub28

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1521]
https://journals.sagepub.com/toc/jota/45/5
Probleme mit den individuell definierten QA-Settings gibt es auch hier. Vgl. #1518 
Habe gestern auf ub28 alle Einstelllungen für die Verfasser Field tag 100 gesetzt. Trotzdem landen alle Sätze wieder wegen fehlendem Tag 100 in den Error-Files. Die individuell definierten QA-Settings scheinen nicht zu greifen

Validating record IxTheo#2021-06-15#DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91...
Record IxTheo#2021-06-15#DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91 is invalid:
required 100-field is missing
record with URL 'https://doi.org/10.1177/03090892211001738' already in database with the same hash (DC09430DC70FFF7CCE628BFF7DDDB700DD2ADE91)

![grafik](https://user-images.githubusercontent.com/29707105/122184735-cc1b0c00-ce8c-11eb-8af9-17596d78332c.png)

**Comment by kdr154** [comment]
Zumindest was diese Zeitschrift anbelangt haben die Anpassungen im Hinblick auf die QA-Settings nichts gebracht. Es ist wieder heute (21./22. 6.) wieder alles wegen fehlender Einträge im Feld 100 in den Error-Files gelandet:

Validating record IxTheo#2021-06-21#1B1723EB767D35EDB734B17D084E69D631D839DE...
Record IxTheo#2021-06-21#1B1723EB767D35EDB734B17D084E69D631D839DE is invalid:
required 100-field is missing
record with URL 'https://doi.org/10.1177/03090892211001735' already in database with the same hash (1B1723EB767D35EDB734B17D084E69D631D839DE)

![grafik](https://user-images.githubusercontent.com/29707105/122880874-cca71d00-d33a-11eb-9fd9-0927df8d4d77.png)

**Comment by jriedl** [comment]
Die Änderungen sind derzeit nur auf nu eingespielt. Nach Testphase können wir es nach ub28 rüberziehen.

**Comment by IxKo** [comment]
Beim Testen auf NU mit Try RSS schienen die XML-Daten zu Heft 5 korrekt:

![image](https://user-images.githubusercontent.com/57000004/124447336-8a8dca80-dd81-11eb-90ee-ab8a14425f99.png)

**Comment by IxKo** [comment]
Der Rubrikentitel wurde bei der heutigen Live-Einspielung nicht in den K10plus übertragen, obwohl die XML-Daten im Default-Ordner so aussehen:

IxTheo#2021-07-06#1B1723EB767D35EDB734B17D084E69D631D839DE
```
<datafield tag="246" ind1="1" ind2=" ">
<subfield code="a">Booklist 2021 </subfield>
<subfield code="i">Rubrikentitel</subfield>
</datafield>
```

Eine Überprüfung von Test-Einspielungen fand scheinbar nicht statt, bevor die Zss auf zota gesetzt wurde.

**Comment by jriedl** [comment]
Ist hier noch etwas offen bzw. hat das überhaupt etwas mit QS zu tun, oder nicht eher mit der Behandlung von 246$i im BSZ-Konverter?

**Comment by IxKo** [comment]
Das beschriebene Eingangsproblem betraf die Problematik fehlender 100-Felder, wodurch Heft 5 immer vollständig in den Errors landete.
Das passiert nun nicht mehr, ich schließe daher.
