### ISSUE TITLE
ISSN 2617-3697 | Journal for Religion, Film and Media (JRFM) | Problematik

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1522]
Diese Zeitschrift ist insgesamt problematisch. Die besten Ergebnisse erzielt man in Single-DL mit dem Translator Embedded Metadata. Bei diesem fehlt lediglich der Zusatztitel und man muss die Verdoppelung der Seitenzahlen bereinien (13–32-13–32).
Beim Multi-DL bricht sowohl der OJS-Standard als auch der Multiwrapper ab. 
Der OJS-Standard bricht auch im Single-DL ab. 
Beim "normalen" OJS fehlt im Single-DL zusätzlich zu den genannten Problemen Seitenzahlen und Zusatztitel auch noch das Abstract. 
Der Zusatztitel kommt lediglich beim DOI-Translator mit. Dann fehlen aber Band, Heft, Seitenzahlen, Sprache und die ISSN.

**Comment by socheres** [comment]
https://jrfm.eu/index.php/ojs_jrfm/issue/view/13

**Comment by helenanebel** [comment]
Lieber @kdr154 , lieber @socheres ,
der OJS-Standard müsste jetzt reibungslos funktionieren inklusive Keywords und Rezensionen im Single- und Multi-DL.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Funktioniert alles. Wobei ich mich frage, ob man für die Artikel "Dance Video Review" und "Exhibition Review" wirklich das Rezensionstag verbeben soll. Ich hätte nichts dagegen.

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich hatte mich das auch gefragt, in der GND steht in in der Definition "Kritische Besprechung von Werken", also wäre das Video wohl drin, bei der Ausstellung bin ich mir nicht sicher.

**Comment by kdr154** [comment]
Bei den Rezensionen haben wir bisher einen ziemlich engen Begriff gepflegt. Wenn wir den hier auch anwenden, sollten tatsächlich nur die "Book reviews" als Rezension getagt werden.

**Comment by helenanebel** [comment]
Ich setzte mal auf "for meeting discussion".
