### ISSUE TITLE
ISSN 2295-9025 | Sacris Erudiri | Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1523]
https://www.brepolsonline.net/toc/se/2020/59
Der ubtue_Brepols-Translator behandelt diese Seite wie im Single-DL. D. h. ein Multi-DL wird gar nicht angeboten.

Auf der Webseite ist nur das Symbol für den Single-DL zu sehen: 
![grafik](https://user-images.githubusercontent.com/29707105/122364521-1e762e80-cf5a-11eb-8589-f2e86ee83346.png)

Mit dem Atypon ist es soweit in Ordnung, bis auf dass die Sprache fehlt. Aber auch hier fehlt das Ordner-Symbol für den Multi-DL. Er führt aber trotzdem einen Mehrfach-DL durch.

**Comment by kdr154** [comment]
Funktioniert nun. Ein bisschen störend ist, dass der Begriff "Abstract" zu Beginn des Abstracts ohne Blank mit dem ersten Wort des eigentlichen Abstracts verbunden ist.
https://www.brepolsonline.net/doi/abs/10.1484/J.SE.5.124510
![grafik](https://user-images.githubusercontent.com/29707105/122887947-a89b0a00-d341-11eb-8af7-1011a4778dbd.png)

**Comment by socheres** [comment]
Beim Exportieren wird "Abstract" gelöscht.

**Comment by kdr154** [comment]
Jetzt wird \n4207 beim Export 2-Mal gesetzt:
Export:

![grafik](https://user-images.githubusercontent.com/29707105/123260509-ee98cf00-d4f5-11eb-88c4-c9411e7981a4.png)


Zotero:

![grafik](https://user-images.githubusercontent.com/29707105/123260591-04a68f80-d4f6-11eb-833d-f368156c4f57.png)

**Comment by socheres** [comment]
wenn Sie den Datensatz in WiniBW hochladen, verschwindet die leere Kategorie 4207.

**Comment by kdr154** [comment]
ok, dann schließe ich
