### ISSUE TITLE
ISSN 2077-1444 | Religions | LF

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1524]
Das Merkmal lizenzfrei "LF" wird von dem Translator MDPI_Journals nicht übernommen, obwohl es in Zeder verankert ist.
https://www.mdpi.com/2077-1444/12/5/368

![grafik](https://user-images.githubusercontent.com/29707105/122540340-d2de8600-d028-11eb-974a-e5202704cea3.png)

**Comment by socheres** [comment]
"LF"-Übernahme aus ZEDER funktioniert nur im Zotaut. Im Zotkat bitte Lizenzinfo hier https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map ergänzen.

**Comment by kdr154** [comment]
War bereits enthalten. Da beim DL keine ISSN heruntergeladen wird, muss das möglicherweise über den Translator geregelt werden. Entweder direkt oder der Translator muss so angepasst werden, dass beim DL die ISSN mitkommt.

**Comment by kdr154** [comment]
Jetzt mit ISSN LF
