### ISSUE TITLE
ISSN 1203-1542 | Neuer Translator für Koop-Partner | Open Journal System Standard Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1525]
**URL**
https://jhsonline.org/index.php/jhs

**Ausführliche Problembeschreibung**
Könnte hier für unsere Kooperationspartner ein Translator entwickelt werden damit es nicht manuell katalogisiert werden muss?
(betrifft Mail vom 16.06.2021 von Herrn KP. S.)

**Comment by socheres** [comment]
Multi-DL ist mit "Open Journal System Standard.js" möglich und wird an erster Stelle angeboten. Können Sie @IxKo bitte damit testen?

**Comment by IxKo** [comment]
Funktioniert, vielen Dank!
Die Seitenangaben und Artikelnummern müssen leider den PDFs entnommen werden, da sie nicht auf den Webseiten angegeben sind.
