### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion | LF + ORCID (Springer live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1526]
Bei dieser Zeitschrift gibt es gelegtlich Artikel, die Open Access sind. 
Hier müsste in Marc  856 $z "kostenfrei" statt "Lizenzpflichtig" gesetzt  werden.
https://link.springer.com/journal/11153/volumes-and-issues/89-3?utm_source=toc&utm_medium=email&utm_campaign=toc_11153_89_3&utm_content=etoc_springer_20210518
https://link.springer.com/article/10.1007/s11153-020-09783-7

**Comment by IxKo** [comment]
Diese Zs ist live und das Problem sollte daher schnell behoben werden.
Außerdem werden die ORCIDs nicht übertragen: https://link.springer.com/article/10.1007/s11153-020-09772-w

**Comment by IxKo** [comment]
ORCID ist bei aktuellen Einspielungen nun dabei.
