### ISSUE TITLE
ISSN 2153-8441 | American Catholic Philosophical Quarterly | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1529]
Die Rezensionen werden nicht getagt.
https://www.pdcnet.org/collection-anonymous/browse?fp=acpq&fq=acpq%2FVolume%2F8905%7C95%2F8999%7CIssue%3A+1%2F
https://www.pdcnet.org/acpq/content/acpq_2021_0095_0001_0153_0155

Hier fehlt die 1131:
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2021\n1500 eng\n1505 $erda\n2051 10.5840/acpq20219515\n3000 Jacobs, James M.$BVerfasserIn$4aut\n4000 From Human Dignity to Natural Law$dAn Introduction. By Richard Berquist. Foreword by Steven J. Jensen\n4070 $v95$j2021$a1$p153-155\n4241 Enthalten in!372353592!\n4950 https://doi.org/10.5840/acpq20219515$xR$3Volltext$4ZZ$534\n4950 https://www.pdcnet.org/pdc/bvdb.nsf/purchase?openform&fp=acpq&id=acpq_2021_0095_0001_0153_0155$xH$3Volltext$4ZZ$534\n5056 1\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
der Fall ist sehr komplex, bitte weiterhin die Rezensionen manuell taggen. Das ist mit @socheres so abgesprochen.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Liebe @helenanebel hierfür haben wir doch noch eine Lösung gefunden. Ich habe den Translator angepasst.

> Lieber @kdr154 ,
> der Fall ist sehr komplex, bitte weiterhin die Rezensionen manuell taggen. Das ist mit @socheres so abgesprochen.
> Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Sehr schön. Rezensionen werden getagt.
