### ISSUE TITLE
ISSN 2161-8534 American Catholic Studies Titel wird als Teil des Names interpretiert

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#153]
Auch hier haben wir wie in #148 das Problem, dass der Titel, in diesem Fall die Mitgliedschaft in einer Ordensgemeinschaft (CM steht hier wohl für Congregatio Missionis), als Bestandteil des Namens interpretiert wird in der Form, dass CM zum Nachnamen wird.
Vgl. http://muse.jhu.edu/article/714933 im XML-File

**Comment by shadeMe** [comment]
Leider steht als Verfasser die Angabe 'John E. Rybolt CM' in den gelieferten Metadaten. Da das Kennzeichen je nach Ordensgemeinschaft beliebig sein kann (und man kann es systematisch auch nicht erkennen), wäre solche Fälle schwierig zu lösen/vermeiden, finde ich.

**Comment by kdr154** [comment]
Über eine Liste mit in Frage kommenden Abkürzungen, SJ, Fr ...? Kommt leider immer mal wieder vor.

**Comment by thefass** [comment]
Könnte das genutzt werden?
https://www.wikidata.org/wiki/Q6853908

**Comment by kdr154** [comment]
Das ist super!

**Comment by kdr154** [comment]
Das ursprüngliche Problem ist gelöst, und wenn es allgemein, bei alles Zeitschriften und Beiträgen umgesetzt wird, super!
Allerdings werden hier die Rezensionen nicht erkannt.  Erstelle ein eigenes Issue
