### ISSUE TITLE
ISSN 2428-3606 | Revue d'Etudes Augustiniennes et Patristiques | Paralleltitel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1531]
Ich habe den Eindruck, dass das Zotero-Feld "Standort im Archiv" dazu ausgewählt wurde, den Paralleltitel zu beinhalten. 
Wenn dem so sein sollte, so scheint auch dies keine gute Lösung zu sein.
https://www.brepolsonline.net/toc/rea/2021/66/2
https://www.brepolsonline.net/doi/abs/10.1484/J.REA.5.125875

Bei dieser Zeitschrift wird bei jedem Aufsatz der Begriff "world" in dieses Feld geschrieben: 

![grafik](https://user-images.githubusercontent.com/29707105/122947297-575b3c80-d37a-11eb-80d6-afccc9723876.png)

Das hat zur Folge, dass dieser Begriff im Pica-Feld 4002 als Paralleltitel erscheint:

![grafik](https://user-images.githubusercontent.com/29707105/122947701-a4d7a980-d37a-11eb-86ff-75a0c4257a98.png)

**Comment by socheres** [comment]
Habe die PICA-Translators so angepasst, dass der Paralleltitel nur bei bestimmten Zeitschriften #1504 erzeugt wird. Damit sollte keine Seiteneffekte mehr auftreten siehe auch #1506

**Comment by kdr154** [comment]
Hat aber auch sein Gutes, wenn man es weiß. Bei dieser Zeitschrift:
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3d30h%26jid%3dATSF%26site%3dehost-live
Wird der Paralleltitel in das Feld "Publication" geschrieben:

http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3d30h%26AN%3d150399898%26site%3dehost-live

![grafik](https://user-images.githubusercontent.com/29707105/123061882-54a92780-d40c-11eb-8d88-281729586003.png)

Von dort lässt er sich leicht in das Feld "Standort im Archiv" kopieren und erspart sich so nachträgliche Arbeit.
