### ISSUE TITLE
ISSN 1827-7365 | Rivista di Storia del Cristianesimo | ISSN_to_language_code.map

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1532]
Ist es so beabsichtigt, dass der Eintrag in der Mapping-Tabelle ISSN_to_language_code.map bestimmend ist und die Festlegung, die man in Zotero getroffen hat, überschreibt?
Bei dieser Zeitschrift ist dies so. Hier ist in der Mapping-Tabelle "ita" hinterlegt. Die Festlegung auf "spa" in Zotero wird mit "ita" überschrieben. 
Bsp.
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3d30h%26AN%3d150399905%26site%3dehost-live

Zotero:
![grafik](https://user-images.githubusercontent.com/29707105/123063869-114fb880-d40e-11eb-9765-46848dd7431e.png)

Winibw:

![grafik](https://user-images.githubusercontent.com/29707105/123063979-2b899680-d40e-11eb-8ab8-d3646ad7c447.png)

**Comment by socheres** [comment]
> Ist es so beabsichtigt, dass der Eintrag in der Mapping-Tabelle ISSN_to_language_code.map bestimmend ist und die Festlegung, die man in Zotero getroffen hat, überschreibt?
> Bei dieser Zeitschrift ist dies so. Hier ist in der Mapping-Tabelle "ita" hinterlegt. Die Festlegung auf "spa" in Zotero wird mit "ita" überschrieben.

Ja, deshalb sollte die Sprache nur bei einsprachigen Zeitschriften in der Mapping-Tabelle hinterlegt werden.

**Comment by kdr154** [comment]
Danke, dann nehme ich den Eintrag heraus.
