### ISSUE TITLE
ISSN 2312-3621 | Old Testament Essays | Translator DOI, Tags, ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1534]
**URL**
https://ote-journal.otwsa-otssa.org.za/index.php/journal/issue/view/22

Translator ubtue_Open Journal Systems Multi-Wrapper.js

**Ausführliche Problembeschreibung**
Folgende Daten werden nicht nach Zotero übertragen:
- DOI
- Tags
- ORCID-ID

(Sprache wird teils falsch übermittelt (immer en), dies ist aber schon in den HTML-Daten falsch hinterlegt.)

**Sonstiges**
Soll die ORCID beim halb-automatischen Verfahren überhaupt unbedingt miterfasst werden?

**Comment by socheres** [comment]
Weise dieses Issue @helenanebel zu. ORCID-ID sollte miterfast werden.

**Comment by helenanebel** [comment]
Lieber @socheres ,
wie genau sollte die ORCID-ID übernommen werden?
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe die Änderungen eingearbeitet.
Viele Grüße, Helena

**Comment by IxKo** [comment]
Ein Artikel hat nun Tags (https://ote-journal.otwsa-otssa.org.za/index.php/journal/article/view/437), doch alle Artikel haben weiterhin keine.
DOI und ORCID kommen auch weiterhin nicht mit.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
bitte erst testen, wenn auch "Ready for Testing"
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
P.S. bitte nicht mehr den Multi-Wrapper verwenden, sondern den OJS-Standard. Falls dieser nicht angeboten wird, das ebenfalls bitte melden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Die ORCID wird nun als Notiz mit den Autoreninformationen übernommen.

DOI und Tags fehlen noch.
Die Tags stehen auf den Artikelseiten rechts unter "Keywords"

**Comment by helenanebel** [comment]
Liebe @IxKo ,
Tags und DOI sind jetzt drin, allerdings sind die DOIs nicht valide.
Viele Grüße, Helena Nebel

**Comment by thefass** [comment]
Es scheint, dass die DOIs erst dann resolven (=valide werden), wenn die Artikel zusätzlich auf Scielo eingestellt sind. 
Z.B. https://ote-journal.otwsa-otssa.org.za/index.php/journal/article/view/292
Aber nicht alle früheren Jahrgänge sind anscheinend zusätzlich in Scielo (und haben überhaupt keinen DOI): https://ote-journal.otwsa-otssa.org.za/index.php/journal/article/view/180
Am besten eienr von Ihnen fragt mal bei den Herausgebern an, was für eine DOI Politik die haben

**Comment by socheres** [comment]
@IxKo aktuelle Daten sind auch auf Scielo zu finden. http://www.scielo.org.za/scielo.php?script=sci_abstract&pid=S1010-99192021000100002&lng=en&nrm=iso&tlng=en Gibt es ein Grund, warum Scielo nicht als Quelle verwendet wird? DOI scheint noch nicht aktiviert worden zu sein.

**Comment by IxKo** [comment]
@socheres Die Bitte kam von Innsbruck (Mail vom 22.6.).
Ich hatte mich für diese Plattform entschieden, da sie die "offiziellere" ist und eine moderne Oberfläche bietet und zusätzlich die ORCID und die normale URL liefert (die auf die OJS-Plattform führt), da der DOI (noch) nicht funktioniert.
Zudem ist es eine OJS-Plattform, für die bereits zwei Translators existieren mit denen ein Multi-DL möglich ist. Bei Scielo wird mir nicht einmal ein Multi-DL angeboten.
Auf der OJS-Seite haben die Keywords einen eindeutigen HTML-Tag "citation_keywords".
Bei Scielo muss Single-DL gemacht werden und bei jedem letzten Keyword muss manuell der Punkt entfernt werden.

**Comment by IxKo** [comment]
> Tags und DOI sind jetzt drin, allerdings sind die DOIs nicht valide.
> Viele Grüße, Helena Nebel

Danke sieht nun alles gut aus!
