### ISSUE TITLE
ISSN 1939-3881 | Cross Currents | Rezensionen und DOI (Muse - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1536]
- [x] Renzensionen werden nicht getagt:

- [x] DOI wird nicht erfasst.

https://muse.jhu.edu/issue/44709
Beispiel:

https://muse.jhu.edu/article/795002

![grafik](https://user-images.githubusercontent.com/29707105/123078843-a9a06a00-d41b-11eb-90cf-a4ffb9fa8987.png)

**Comment by socheres** [comment]
wenn die Daten auf Nu korrekt sind, sollte man sie erneut einspielen, also resetten bzw. in WiniBW löschen.

**Comment by kdr154** [comment]
Test mit TryURL soeben nicht erfolgreich. DOI war vorhanden, Rezensionstag nicht.

**Comment by kdr154** [comment]
Jetzt ist auch das Rezensionsfeld dabei.
