### ISSUE TITLE
ISSN 1468-2400 | International Journal of Systematic Theology | Rezensionen (Wiley - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1537]
Rezensionen bekommen auch hier das überflüssige Schlagwort "Book Review, Book Review".
https://onlinelibrary.wiley.com/doi/10.1111/ijst.12467
![grafik](https://user-images.githubusercontent.com/29707105/123097510-80d69f80-d430-11eb-9cdd-60dc4dc85555.png)

**Comment by socheres** [comment]
die Bereinigung ist direkt über harvester.conf möglich  und sollte auch dort gemacht werden. `remove_marc_field_650a    = (?i)^Book\s+Reviews?$`

**Comment by socheres** [comment]
Lieber @kdr154, hierfür gibt es eine globale Einstellung. Ich habe sie nun geändert. Bitte morgen nochmal testen.

**Comment by kdr154** [comment]
Vielen Dank für den Hinweis. Habe nun den Eintrag in die harvester.conf gemacht. Kann doch dort stehen bleiben oder soll ich ihn wieder entfernen?

**Comment by socheres** [comment]
nach Telefonat mit @jriedl globale Anpassung wieder rückgängig gemacht. Tag wird über Translator bereinigt.

**Comment by socheres** [comment]
bitte auf NU testen.

**Comment by kdr154** [comment]
Auf nu ist der Eintrag nicht mehr vorhanden.
