### ISSUE TITLE
-- | -- | ubtue_Wiley Online Library

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1541]
Lieber @socheres , lieber @kdr154 , liebe @IxKo ,

ich bearbeite gerade den Wiley-Translator und mir ist aufgefallen, dass viele Tests (vor meinen Änderungen) mittlerweile andere Ergebnisse bringen.
-	statt nur DOIs werden ganze Resolving-URLs übernommen, soll ich das so ändern, dass wieder nur der DOI eingetragen wird?
-	Es werden die Print-Erscheinungsdaten, nicht mehr die Online-Erscheinungsdaten übernommen. Welche sollen übernommen werden?

Viele Grüße,
Helena Nebel

**Comment by kdr154** [comment]
https://onlinelibrary.wiley.com/toc/14679809/2021/45/2

**Comment by socheres** [comment]
Wir hatten uns entschieden auf $n zu verzichten.

**Comment by IxKo** [comment]
Ja, wir hatte uns darauf geeignet, immer das Berichtsjahr auch als Erscheinungsjahr zu nehmen, selbst wenn das Erscheinungsjahr abweicht, siehe #1078

**Comment by helenanebel** [comment]
Lieber @kdr , liebe @IxKo , lieber @socheres ,
ich hatte vergessen, die fragliche URL anzueben, tut mir sehr leid:
https://onlinelibrary.wiley.com/doi/10.1002/3527603018.ch17
Ich weiß nicht, ob Buchkapitel überhaupt für uns relevant sind, wollte aber sichergehen.
Der DOI ist im Quelltext enthalten, deshalb frage ich. Dann übernehme ich ihn.
Bei der Publikation handelt es sich um ein Buchkapitel, es geht also nicht um ein Berichts- vs. Erscheinungsjahr, sondern darum, dass das Buch deutlich früher in Print erschienen ist als Online.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Liebe @helenanebel,
ich glaube, wir alle hier sind von einer Zs ausgegangen und auch vom voll-automatischen Verfahren, da Wiley ein Kandidat dafür ist.
Wie kommt denn ein Buch in das semi-automatische Verfahren? Wir bearbeiten mit Zotero bisher nur Zss. Oder sollst Du eine Möglichkeit für nicht fortlaufende Ressourcen ergründen?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das ist eine der "Tests", die in den Translators hinterlegt sind, um sicherzustellen, dass diese noch wie vorgesehen funktionieren. Wenn das keine Rolle spielt, kann ich das einfach so lassen. Ich bearbeite dieses Issue: ubtue/DatenProbleme#1239 , ist das dann eventuell auch nicht mehr relevant?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Meiner Meinung nach sollten die Translator für das halb-automatische Verfahren weiterhin funktionstüchtig sein, da es beim vollautomatischen Verfahren immer wieder vorkommen wird, dass etwas halb-automatisch katalogisiert werden muss.
Also bleibt es relevant :)

**Comment by kdr154** [comment]
Viel Erfolg bei #1239. Das ist für mich eines der Rätsel bei der Zotero-Bearbeitung. Schließlich hat man etwa soweit, dass es funktioniert. Dann funktioniert es beim nächsten mal nicht mehr. Und es wäre wirklich hilfreich, wenn die Autoren dort bei den Kurzrezensionen wieder mitkämen. Denn Kurzrezensionenen gibt es dort jede Menge

**Comment by socheres** [comment]
Das liegt daran, dass es seit 17.05.2021 für Wiley einen neuen Translator gibt. https://github.com/socheres/Zoterobearbeitung/commit/fb7ba3fa8ed18b50737161b7830dc886946900fa#diff-9e0ec05872fa93c98b163653b8412975c8d778ba8da24afa250039a9d4778185
Liebe @helenanebel, z.I. der Codeblock für Rezensionserkennung fehlt in der ubtue-Version. #1239 

```
			var primaryHeading = ZU.xpathText(doc, '//span[@class="primary-heading"]');
			if (primaryHeading.match(/book\sreview/i)) {
				item.tags.push("RezensionstagPica");
			}
			if (item.pages.match('-')) {
				var pages = item.pages.split('-');
				if (pages[0] == pages[1]) {
					item.pages = pages[0];
				}
			}
```

**Comment by helenanebel** [comment]
Lieber @socheres ,
bei mir ist der Block enthalten, es ist auch die aktuelle Version, ich habe vor dem Bearbeiten einen Pull durchgeführt.
Viele Grüße, Helena Nebel
