### ISSUE TITLE
ISSN 1549-6538 | The journal of religion | Rezensionen (UCP Journals - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1545]
https://www.journals.uchicago.edu/doi/10.1086/712900
https://www.journals.uchicago.edu/toc/jr/2021/101/2

Die Rezensionen werden nicht getagt

![grafik](https://user-images.githubusercontent.com/29707105/123272815-640a9c80-d502-11eb-89c3-b66b62a77f21.png)

**Comment by kdr154** [comment]
Behoben. Könnte live gehen, wenn der Translator auf ub28 dem von nu entspricht.

**Comment by socheres** [comment]
Lieber @jriedl, UCP hat kein Issue mehr. Kannst du bitte ub28 aktualisieren?

**Comment by jriedl** [comment]
@socheres: Das wurde ja am Dienstag angesprochen. Wenn das OK im Bezug auf die selektive Auswertung kommt, könnten wir Anfang nächster Woche die Updates einspielen.

**Comment by socheres** [comment]
> @socheres: Das wurde ja am Dienstag angesprochen. Wenn das OK im Bezug auf die selektive Auswertung kommt, könnten wir Anfang nächster Woche die Updates einspielen.

Diese Zeitschrift wird laut ZEDER nicht selektiv ausgewertet. Was meinst du damit?

**Comment by jriedl** [comment]
Ein Update auf ub28 zieht ja dann alle Änderungen mit, deshalb brauchen wir im Vorfeld auf nu einen stabilen, durchgetesteten Zustand für alle ausstehenden Änderungen.

**Comment by IxKo** [comment]
Beim Test auf ub28 mit TRY RSS wird die Rezension nun erkannt.
