### ISSUE TITLE
ISSN 2167-2040 | Journal of Korean religions | Rezensionen (Muse - live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1546]
https://muse.jhu.edu/article/791144

Rezensionen werden nicht getagt.

![grafik](https://user-images.githubusercontent.com/29707105/123384472-bd231080-d594-11eb-84c5-918fcbd8c114.png)

**Comment by socheres** [comment]
Können Sie bitte auf ub28 und auf Nu testen.

**Comment by kdr154** [comment]
Auf nu ist das Tag vorhanden, auf ub28 nicht. Ich habe auf live gesetzt, weil die Daten in der Testdatenbank korrekt waren.

**Comment by socheres** [comment]
Lieber @kdr154, ich habe nochmal überprüft; die Translators zwischen ub28 und Nu unterscheiden sich nicht. Können Sie bitte sicherheitshalber nochmal auf ub28 testen und im Log schauen mit welchem Translator der Datensatz heruntergeladen worden ist?

**Comment by kdr154** [comment]
Ich habe es jetzt mit TryURL und mit TryRSS getestet. In beiden Fällen Fehlanzeige. Zu den Einträgen im Log kann ich nichts sagen. In beiden Fällen bekomme ich die Meldung "The log file does not exist".

**Comment by socheres** [comment]
Danke. Dann ist das ein Fall für @jriedl Kannst du dieses Problem bitte einmal genauer ansehen?

**Comment by IxKo** [comment]
Ein Test auf ub28 erkennt den Artikel nun als Rezension.
