### ISSUE TITLE
ISSN 2628-5819 | Gottesdienst : Information u. Handreichung der liturgischen Institute Deutschlands, Österreichs | Ausgabe und Datum

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1547]
https://www.herder.de/gd/hefte/archiv/2021/13-2021/
In einigen Fällen wird eine falsche Angabe der Ausgabe übertragen. In den meisten Fällen stimmt dann auch das Datum nicht.

https://www.herder.de/gd/hefte/archiv/2021/13-2021/balthasar-fischer-preis-2022/

![grafik](https://user-images.githubusercontent.com/29707105/123590324-c6a5b600-d7ea-11eb-96eb-75790857d48b.png)

https://www.herder.de/gd/hefte/archiv/2021/13-2021/liedwettbewerb-1700-jahre-sonntag-zwischenbilanz/

![grafik](https://user-images.githubusercontent.com/29707105/123590426-ed63ec80-d7ea-11eb-9284-5883ffa26de3.png)

https://www.herder.de/gd/hefte/archiv/2021/13-2021/einfuehrungen-zu-den-schriftlesungen-13-2021/

![grafik](https://user-images.githubusercontent.com/29707105/123590587-1d12f480-d7eb-11eb-82a1-23444652f166.png)

Hier stimmt das Datum.

https://www.herder.de/gd/hefte/archiv/2021/13-2021/3000-jahre-alte-burn-out-prophylaxe/

![grafik](https://user-images.githubusercontent.com/29707105/123590064-6f9fe100-d7ea-11eb-8899-c85a13249a11.png)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
ich habe das Issue und Datum korrigiert & die Rezensionen werden jetzt auch erkannt.
Viele Grüße, Helena Nebel

**Comment by kdr154** [comment]
Bei mir immer noch dasselbe Resultat. Dort, wo der Titel eine Zahl enthält, wird diese in das Feld Ausgabe und Datum übernommen.

![grafik](https://user-images.githubusercontent.com/29707105/125249220-45bfe180-e2f5-11eb-98e8-28e57e53ec28.png)

**Comment by helenanebel** [comment]
Lieber @kdr154 ,
bei mir geht es, ich habe es eben nochmal getestet. Lieber @socheres , könnten Sie mal bei sich testen?
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
![grafik](https://user-images.githubusercontent.com/49190455/125250628-c501e500-e2f6-11eb-83a9-3caaaa989118.png)

**Comment by socheres** [comment]
Sorry! Ich hatte die lokalen Verzeichnisse nicht aktualisiert. Jetzt sollte es auch für @kdr154 funktionieren.

**Comment by kdr154** [comment]
Stimmt. Ist nun korrekt.
