### ISSUE TITLE
ISSN 2162-3937 | Journal of ecumenical studies | Rezensionen (Muse - Live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1548]
Hier haben wie dieselbe Problematik wie in #1546, dass die Rezensionen live und auf ub28 nicht getagt werden, und sie im Gegensatz dazu auf nu getagt werden.
https://muse.jhu.edu/issue/44638

**Comment by IxKo** [comment]
Beide Rezensionen werden beim Test auf ub28 nun als Rezensionen ausgezeichnet.
