### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Lizenzfreie Artikel (CUP - Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1549]
Gelegentlich sind lizenfreie Artikel eingestreut. Diese sollte in 856 $z "LF" enthalten. 
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/issue/6016CCBC8B5596C94C91D3D6581EAB1C
Etwa hier: 
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/charity-as-social-justice-antonio-rosmini-and-the-great-irish-famine/7D177F707EA3722731C61AE58DB601F6

Hier:
https://www.cambridge.org/core/journals/business-ethics-quarterly/issue/753E298609F509C955DB26C233F019DE
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/ethics-of-the-attention-economy-the-problem-of-social-media-addiction/1CC67609A12E9A912BB8A291FDFFE799

![grafik](https://user-images.githubusercontent.com/29707105/124087816-ad9f3e00-da52-11eb-99a9-87007e8c2901.png)

Ist es auch der Fall. Das Problem scheint auch für Cambridge University Press global zu sein.

**Comment by IxKo** [comment]
ISSN 1469-7637 (CUP) | Hash 3ABA10DAA4972203891CD2CB79F07A785952DB09 (https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/charity-as-social-justice-antonio-rosmini-and-the-great-irish-famine/7D177F707EA3722731C61AE58DB601F6) in Test-DB gelöscht und auf Nu resettet.

**Comment by IxKo** [comment]
Wurde nun als LF eingespielt:
![image](https://user-images.githubusercontent.com/57000004/125082051-00b66800-e0c7-11eb-8e80-922f21e08a6d.png)
