### ISSUE TITLE
ISSN 2031-5929 Annali di Scienze Religiose falsche Sprache in Tag 041

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#155]
https://www.brepolsonline.net/doi/abs/10.1484/J.ASR.5.116193?af=R
Dieser Artikel ist auf italienisch, in 041 steht aber eng

**Comment by kdr154** [comment]
Muss ich in diesm Fall etwas aktualisieren? Bei einem aktuellen Testlauf steht in 041 immer noch eng wo ita stehen sollte.

**Comment by shadeMe** [comment]
Es schient, dass die [ISSN-Language-Code](https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map) Mapping fälschlicherweise die Sprache übersteuert, die der Translator ergibt. Da wir jetzt die neue Heuristik und die Sprache-Angabe vom Zeder haben, frage ich mich, ob wir diese zusätzliche Mapping überhaupt noch brauchen.

Jedenfalls passe ich den Code an, sodass die Mapping nur als die letzte Option gebraucht wird bzw. wenn wir weder eine Sprache vom Translator geliefert bekommen noch sie automatisch erkennen können.

**Comment by shadeMe** [comment]
Sollte behoben sein.

**Comment by kdr154** [comment]
Gelöst
