### ISSUE TITLE
ISSN 1573-0395 | Journal of Indian Philosophy | Lizenzfreie Artikel (Springer -  Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1551]
https://link.springer.com/journal/10781/volumes-and-issues/49-2
Ein Teil der Artikel ist Lizenzfrei diese sollten in 856 $z "LF" enthalten

**Comment by socheres** [comment]
gefixt: https://github.com/ubtue/DatenProbleme/issues/1526

**Comment by IxKo** [comment]
In neuen Einspielungen in der Test-DB werden LF-Artikel gekennzeichnet.
