### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion | LF-Artikel (OUP - live)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1554]
Hier gibt es gelegentlich Artikel, die OA sind. Diese sollten in 936 $z den Wert "Kostenfrei" haben.
Bei diesem Heft:
https://academic.oup.com/socrel/issue/82/3
dieser Artikel:
https://academic.oup.com/socrel/article/82/3/281/6177665

Dieser eine fehlerhafte Artikel wird nach der Einspielung korrigiert. Testen kann man dann auf nu und ub28.

**Comment by IxKo** [comment]
LF-Aufsätze werden auf Nu erkannt.
@jriedl: Bitte diesen Stand auf ub28 übertragen, da die Zs schon auf zota steht.

**Comment by IxKo** [comment]
Ist auf ub28 umgesetzt, danke!
