### ISSUE TITLE
ISSN 2748-6419 | AABNER Advances in ancient, biblical, and Near Eastern research | orcid

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1555]
https://ojs3.uni-tuebingen.de/ojs/index.php/beabs/issue/view/130
https://ojs3.uni-tuebingen.de/ojs/index.php/beabs/article/view/785
Die Orcid verursacht in der Winibw einen Fehler:
![grafik](https://user-images.githubusercontent.com/29707105/123911913-ab6ab000-d97c-11eb-9194-80bfed9a6148.png)

![grafik](https://user-images.githubusercontent.com/29707105/123912010-cc330580-d97c-11eb-9734-05400bc524a7.png)

So sieht es in Zotero aus. Import-Translator ist der ubtue_Open_Journal_Systems_Standard.js

![grafik](https://user-images.githubusercontent.com/29707105/123912859-d6093880-d97d-11eb-9830-d8be4475e9ef.png)

Da fehlt folgender Teil nach 8910: $aixzom$b und möglicherweise auch noch das Blank nach "orcid:"
siehe: 
![grafik](https://user-images.githubusercontent.com/29707105/123944154-2217a580-d99d-11eb-967f-34e9c5675379.png)

Der Fehler tritt in allen Fällen auf, in denen eine Orcid abgegriffen wird.

**Comment by IxKo** [comment]
Bei mir wird diese Information nun gar nicht mehr mit dem Export-Translator aus Zotero übernommen.

Außerdem scheint es, dass bei mehreren Autor:innen alles in einem Feld landen würde:
So sieht es in Zotero Feld "Signatur" aus bei 4 ORCIDs:

$aixzom$borcid: 0000-0003-0706-4480 | author=Izaak Jozias de Hulster Valérie Nicolet Institut Protestant de Théologie http://orcid.org/0000-0001-9070-0585 Ronit Nikolsky University of Groningen http://orcid.org/0000-0002-3771-8062 Jason M. Silverman University of Helsinki http://orcid.org/0000-0002-0240-9219 | taken from website
(Link: https://doi.org/10.35068/aabner.v1i1.781)


Ein weiteres Problem zum Ausbesser:
Es werden mit dem ubtue_Open_Journal-Systems_Standard nicht die **Zusatztitel** übernommen (bspw. https://doi.org/10.35068/aabner.v1i1.785)

**Comment by kdr154** [comment]
Bis auf die Sache mit dem Single-DL kann ich alles bestätigen.
Orcid wird beim Export verworfen
Zusatztitel fehlt
Mehrere Personen landen in einem Orcid-Feld (da wollte ich abwarten, aber es ist auch nach der Überarbeitung noch der Fall)
Der Eintrag für die Orcid enthält Daten, die in meinen Augen nicht angezeigt werden sollten: .st0...
![grafik](https://user-images.githubusercontent.com/29707105/123983478-328f4680-d9c4-11eb-9bb5-c33fda2e81c5.png)

**Comment by socheres** [comment]
Liebe @IxKo @kdr154, die Feldstruktur 8910 hat sich etwas geändert. Ist das so in Ordnung?

```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2021
1500 eng
1505 $erda
2051 10.35068/aabner.v1i1.783
3000 Hulster, Izaak Jozias de$BVerfasserIn$4aut
3010 !720760259!$BVerfasserIn$4aut 
8910 $aixzom$bAutor in der Zoterovorlage [Nicolet, Valérie] maschinell zugeordnet
3010 Nikolsky, Ronit$BVerfasserIn$4aut
3010 Silverman, Jason M.$BVerfasserIn$4aut
4000 Inaugural AABNER editorial
4070 $v1$j2021$a1$p1-12
4207 Wir als Gründungsmitglieder und Chefredaktion erläutern unsere Beweggründe und Ziele sowie die redaktionellen Prinzipien der neu gegründeten, auf ‚Forum-Peer-Review‘ basierenden Open-Access Zeitschrift AABNER.
4241 Enthalten in!1758930020!
4950 https://aabner.org/ojs/index.php/beabs/article/view/783$xH$3Volltext$4LF$534
4950 https://doi.org/10.35068/aabner.v1i1.783$xR$3Volltext$4LF$534
5056 1
5520 |s|Bible.
5520 |s|Open access
5520 |s|academic publishing
5520 |s|ancient Near East
5520 |s|diamond open access
5520 |s|ethics
5520 |s|meta- criticism
5520 |s|peer review
8910 $aixzom$bIzaak Jozias de Hulster Göttingen http://orcid.org/0000-0003-0706-4480
8910 $aixzom$bJason M. Silverman University of Helsinki http://orcid.org/0000-0002-0240-9219
8910 $aixzom$bRonit Nikolsky University of Groningen http://orcid.org/0000-0002-3771-8062
8910 $aixzom$bValérie Nicolet Institut Protestant de Théologie http://orcid.org/0000-0001-9070-0585
E* l01
7100 $Jn
8012 ixzs$aixzo
```

**Comment by kdr154** [comment]
Aus meiner Sicht spricht nichts dagegen.

**Comment by IxKo** [comment]
Aus meiner Sicht spricht auch nichts dagegen.

**Comment by socheres** [comment]
OK. Dann kann das Issue geschlossen werden, richtig?

**Comment by kdr154** [comment]
Wenn dann alles passt. Wie ist es mit dem Zusatztitel?

**Comment by IxKo** [comment]
Ja, der Zusatztitel wird weiterhin nicht übertragen.

**Comment by kdr154** [comment]
Z. B. hier: https://ojs3.uni-tuebingen.de/ojs/index.php/beabs/article/view/787

**Comment by IxKo** [comment]
Die Zusatztitel kommen nun mit.
Bei den Zusatzinformationen werden auch Informationen übertragen, wenn keine ORCID vorhanden ist (URL: https://ojs3.uni-tuebingen.de/ojs/index.php/beabs/article/view/785)

![image](https://user-images.githubusercontent.com/57000004/124439686-03892400-dd7a-11eb-8618-cb9eedaece89.png)

**Comment by socheres** [comment]
Bitte nochmal testen.

**Comment by IxKo** [comment]
Nun kommt nur noch die Person mit dem ORCID-Link mit und es steht zum Schluss ein Hinweis:

> 8910 $aixzom$bSebastian Fink Universität Innsbruck http://orcid.org/0000-0002-6270-8368 | taken from website
