### ISSUE TITLE
ISSN 0022-4189 | The Journal of Religion | Notiz doi: führt zu Feld 8910

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1558]
**URL**
https://doi.org/10.1086/714141

**Ausführliche Problembeschreibung**
Durch die Notiz "doi: ..." in Zotero wird Feld 8910 erzeugt.

![image](https://user-images.githubusercontent.com/57000004/124491533-af029a80-ddb3-11eb-9fc9-d570d0e34a68.png)

--->>>

![image](https://user-images.githubusercontent.com/57000004/124491469-a01be800-ddb3-11eb-83cc-13265f38c334.png)

Das Feld 8910 sollte mit dieser Information gar nicht erst erzeugt werden.

**Comment by socheres** [comment]
Ich habe dies auf Pica-Exportseite angepasst.

**Comment by socheres** [comment]
Liebe @helenanebel, Sie können es noch auf der Importseite beheben. DOI gehört eigentlich nicht in das Notizfeld.

**Comment by helenanebel** [comment]
Lieber @socheres ,
das kann ich machen!
Liebe @IxKo ,
bitte erst schließen, wenn ich geändert habe.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich kann das Problem momentan nicht reproduzieren.
Könntest du nochmal schauen, ob das immer noch auftritt bei der URL oben?
Viele Grüße, Helena

**Comment by IxKo** [comment]
Das Problem, dass die DOI-Notiz beim Export aus Zotero ein Feld 8910 erzeugt, besteht nicht mehr.

Beim Import nach Zotero wird jedoch weiterhin eine DOI-Notiz erstellt:
![image](https://user-images.githubusercontent.com/57000004/126174770-2e9f9fce-fabd-4477-8be4-9e62fe876770.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem müsste dann behoben sein, bitte auf "ready for testing" warten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Problem behoben, danke!
