### ISSUE TITLE
ISSN 1804-6444 | Journal of European Baptist Studies (OJS) | Titelzusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1559]
**URL**
https://jebs.eu/ojs/index.php/jebs/issue/view/75

**Ausführliche Problembeschreibung**
Die Titelzusätze werden nicht nach Zotero übertragen.

Translator: ubtue_OJS_Standard im Multi-DL

**Comment by socheres** [comment]
Liebe @helenanebel, bitte den OJS Standard anpassen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe die Titelzusätze ergänzt und außerdem Rezensionstag hinzugefügt.
Viele Grüße, Helena

**Comment by IxKo** [comment]
Titelzusätze sind nun dabei und die Rezensionen werden tatsächlich auch erkannt. Vielen Dank!
