### ISSUE TITLE
ISSN 2451-2141 | Philosophy and Canon Law | Neuer Translator (Ceeol)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1560]
**URL**
https://www.ceeol.com/search/journal-detail?id=1266

**Ausführliche Problembeschreibung**
Kann für diese Zs ein neuer Translator erstellt werden?

Dies ist eine Bitte vom 23.06 von Kooperationspartnern.

**Comment by socheres** [comment]
Es gibt bereits ein Translator "Central and Eastern European Online Library Journals.js" für diese Webseite.

**Comment by IxKo** [comment]
Danke, er wurde mir aber heute Morgen nicht angezeigt. Und ich hatte zur Sicherheit die Translator aktualisiert und die Seite mehrfach neu geladen.
