### ISSUE TITLE
ISSN 2176-0985 | Mandrágora | LF 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1561]
Das Merkmal "LF" wird nicht übernommen: 
![grafik](https://user-images.githubusercontent.com/29707105/125299743-b8e34b00-e329-11eb-9d77-dbd9d2db1925.png)

https://www.metodista.br/revistas/revistas-metodista/index.php/MA/issue/view/572

Translator ubtue_Open_Journal_Systems_Standard. 
Single-DL

**Comment by socheres** [comment]
@IxKo das ist eine OA-Zeitschrift. Bitte die ISSN hier ergänzen: https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map
