### ISSUE TITLE
ISSN 1540-6385 | Dialog : a journal of theology | Physical form Wiley Test

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1563]
Das aktuelle Heft wurde in der Einspielung vom 12./13. 7. komplett an die Druckausgabe gehängt:

![grafik](https://user-images.githubusercontent.com/29707105/126116159-3993ce59-f8c5-464b-88c5-ffefd91e495d.png)

im Grunde genommen gehört es an die Online-Ausgabe.
Auf nu kann man sehen, dass das Feld für die ESSN leer ist:
![grafik](https://user-images.githubusercontent.com/29707105/126115389-c50658d0-0db4-4589-a154-9921408a4a17.png)

Obwohl sie sowohl in Zeder vorhanden ist.
![grafik](https://user-images.githubusercontent.com/29707105/126115841-7daed75b-f337-4de7-ac0b-19122e0d19e1.png)

In den enhancement-maps hingegen fehlt sie: 

![grafik](https://user-images.githubusercontent.com/29707105/126116018-67c06b58-2aaa-4ea9-aa82-fed999d4a60e.png)

**Comment by jriedl** [comment]
Das wird bei der Synchronisation von Zeder in die `zotero_harvester.conf` aussortiert, da es nicht als gültige ISSN erkannt wird. Vermutlich funktioniert es, wenn die führende `0` in Zeder entfernt wird.

**Comment by kdr154** [comment]
Na klar. Hätte mir eigentlich auch auffallen sollen. Die führende "0" wurde entfernt.

**Comment by kdr154** [comment]
Das ist geklärt.
