### ISSUE TITLE
ISSN 2199-4625 | Journal of Religious Education | OA-Artikel Springer Test

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1564]
Die OA-Artikel werden nicht erkannt:

https://link.springer.com/article/10.1007/s40839-021-00142-w

![grafik](https://user-images.githubusercontent.com/29707105/126118206-5f718746-9a94-4a2e-b50b-a95ca4fed13e.png)

**Comment by jriedl** [comment]
Angepasster Translator auf nu.

**Comment by kdr154** [comment]
Das sieht gut aus.
