### ISSUE TITLE
ISSN 2213-8617 | Oriente Moderno | fehlender Artikel RSS (Brill)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1565]
**URL**
https://doi.org/10.1163/22138617-12340246

**Ausführliche Problembeschreibung**
Dieser Artikel (Titel: Marriage quandaries in Central Asia) wurde nicht eingespielt. Er taucht auf ub28 nicht auf. 

Ich habe ihn halb-automatisch erfassen müssen.

**Comment by jriedl** [comment]
Scheint nicht im RSS-Feed vorhanden: https://brill.com/journalissuetocrss/journals/ormo/ormo-overview.xml

**Comment by IxKo** [comment]
Schließe, da ein solches Problem von unserer Seite nicht automatisch kontrolliert werden kann.
In einem solchen Fall kann es nur intellektuell erkannt und nachkatalogisiert werden.
