### ISSUE TITLE
ISSN 1437-1618 | Ethik in der Medizin | OA-Artikel Springer Test

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1566]
Bis auf Ausnahmen sind die Artikel OA. Dies wird nicht erkannt.
https://link.springer.com/journal/481/volumes-and-issues/33-2
https://link.springer.com/article/10.1007/s00481-021-00634-1

![grafik](https://user-images.githubusercontent.com/29707105/126156131-e69e1b60-d398-4c1b-9699-b21a7305519d.png)

**Comment by jriedl** [comment]
Angepasster Translator auf nu.

**Comment by kdr154** [comment]
Das sieht gut aus.
