### ISSUE TITLE
ISSN 1568-5330 | Vetus Testamentum | Keywords doppelt (Brill)

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1568]
**URL**
https://brill.com/view/journals/vt/71/3/article-p365_5.xml
IxTheo#2021-07-19#D063093441A48EA4B672958246B4992EC08FAAE7

**Ausführliche Problembeschreibung**
Die Keywords werden doppelt eingespielt:

![image](https://user-images.githubusercontent.com/57000004/126333503-0d99c6bd-4342-4118-aef8-1b4bc017d9e2.png)

**Comment by socheres** [comment]
Kann auf nu getestet werden.

**Comment by IxKo** [comment]
Okay, habe in der Test-DB das letzte Heft von 
<html>
<body>


Annuarium historiae conciliorum : internationale Zeitschrift für Konziliengeschichtsforschung | 0003-5157 | 2589-0433 | 130129313 | 1007306068 | RSS | TEST
-- | -- | -- | -- | -- | -- | --



</body>
</html> gelöscht und auf Nu resettet.

**Comment by IxKo** [comment]
Es wurden keine doppelten Keywords eingespielt.
Beim Test auf ub28 scheinen ebenfalls keine Doppelungen in den Daten enthalten:
![image](https://user-images.githubusercontent.com/57000004/126605942-53592ebd-2fac-46aa-933e-c0236a74f439.png)
