### ISSUE TITLE
ISSN 2077-1444 | Religions | RegEx (Test)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1569]
Das sollte doch nicht zu einem Fehler führen:
100: contents of subfield $a(Clausén, Marie) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

https://www.mdpi.com/2077-1444/12/7/464

Alle weiteren hier auch nicht:
100: contents of subfield $a(Sherma, Rita D.) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

100: contents of subfield $a(Stepanenko, Walter Scott) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

100: contents of subfield $a(Haker, Hille) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

100: contents of subfield $a(Ungureanu, Camil) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

100: contents of subfield $a(Jakobsen, Johnny Grandjean Gøgsig) did not match regex "^(?!(?:(\s*)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$) \p{P}"

**Comment by jriedl** [comment]
Das beruht auf einem Missverständnis - beim im https://github.com/ubtue/DatenProbleme/issues/1412#issuecomment-884125999 angegebenen Regex gehört ist das `\p{P}` in der nächsten Zeile eine Erläuterung und darf nicht miteingetragen werden.

**Comment by kdr154** [comment]
Ok, dann nehme ich diesen Teil heraus.
