### ISSUE TITLE
ISSN 2473-3725 | The Thomist | Ordenskürzel Muse Live

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#1570]
Bei den Verfasserangaben in Pica 3000 werden die Ordenskürzel mit übernommen:
Z. B.:
https://muse.jhu.edu/article/797123
![grafik](https://user-images.githubusercontent.com/29707105/126599930-aaa40525-deac-41b0-af95-483c4dc7b6c1.png)

**Comment by socheres** [comment]
@IxKo `O.p.` ist in der Mapping vorhanden https://github.com/ubtue/zotero-enhancement-maps/blob/master/author_name_blacklist.txt
Wegen casesensitive nicht gefiltert?

**Comment by IxKo** [comment]
Es kommt beim Testen mit Punkt rüber, da in der Mapping nur O.p (also ohne letzten Punkt) stand.
![image](https://user-images.githubusercontent.com/57000004/140715703-8d949983-fcf1-449a-9608-e68519e5b29b.png)

Ich habe nun in der Mapping "O.P." ergänzt.
Allerdings kann für die Zukunft nicht ausgeschlossen werden, dass bspw. eine Person solch abgekürzte Vornamen hat, die dann entfernt werden.

Woher nimmt der Translator den Namen?
Im Quelltext gibt es eine Stelle, in der das O.P. nicht im gleichen Tag wie der Name steht. Dadurch könnten solche Fälle doch ganz umgangen werden, oder nicht?
![image](https://user-images.githubusercontent.com/57000004/140716212-4eef2927-1b0b-455d-8095-9115f3fa2620.png)

**Comment by jriedl** [comment]
Hat die bestehende Lösung irgendwann in den vergangenen Jahren dann noch einmal zu Problemen geführt?

**Comment by IxKo** [comment]
Die bestehende Lösung scheint die Blacklist zu sein. Ob dabei Initialen gelöscht worden sind, die hätte bleiben sollen, kann man nicht herausfinden ohne jeden Datensatz mit der Vorlage abzugleichen.
Auf die andere Frage wurde nie eingegangen.
