### ISSUE TITLE
ISSN 1467-8519 | Bioethics (Wiley) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1573]
**URL**
https://doi.org/10.1111/bioe.12883
IxTheo#2021-07-28#F713369D3F1C30C6EB64467B2E7E627C180E2625

**Ausführliche Problembeschreibung**
Die ORCIDs werden nicht erfasst.

**Comment by socheres** [comment]
auf nu kann getestet werden.

**Comment by IxKo** [comment]
Die beiden vorhandenen ORCIDs werden auf Nu erfasst.
