### ISSUE TITLE
ISSN 1468-0025 | Modern Theology (Wiley) | Titelzusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1575]
**URL**
https://doi.org/10.1111/moth.12677
IxTheo#2021-08-03#C70198F9AB307DEA1764BD8335BFDE4F22A7A4AF

**Ausführliche Problembeschreibung**
Der Zusatztitel wurde nicht mit eingespielt.

Sowohl auf Nu als auch auf ub28 wird er nicht erfasst.

Der Titel ist etwas anders als die anderen Titel im Heft:
Auf der Heft-Übersichtsseite:
![image](https://user-images.githubusercontent.com/57000004/128165352-3e95565d-adfc-4ab9-b79b-b358163defbd.png)

Auf der Artikel-Seite:
![image](https://user-images.githubusercontent.com/57000004/128165286-72bbfb32-2bbf-48cc-a65b-9c651cc761cd.png)

Dagegen ein eigentlich ähnlicher Artikel im gleichen Heft (https://doi.org/10.1111/moth.12679):
![image](https://user-images.githubusercontent.com/57000004/128165440-fd5f8ccf-0813-4bfd-b1d2-8424d484dffd.png)
![image](https://user-images.githubusercontent.com/57000004/128165503-3cc1e0b4-4cf3-4459-a486-719a12d6a8e2.png)

Dementsprechend ist auch der HTML-Quellcode anders und der Zusatztitel wird in einem gesonderten Meta-Feld aufgeführt.

**Comment by IxKo** [comment]
Wird auf Nu nun erfasst, auf ub28 noch nicht.
Die Zs wurde jedoch schon live gestellt.

**Comment by socheres** [comment]
@jriedl kannst du bitte die Translators auch auf ub28 aktualisieren?

**Comment by jriedl** [comment]
Ist passiert.

**Comment by IxKo** [comment]
Danke, wird au ub28 nun auch korrekt ausgegeben. (getestet mit Try url)
