### ISSUE TITLE
ISSN 1534-0708 | The catholic historical review (Muse) | auszuschließende Titel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1578]
**URL**
https://doi.org/10.1353/cat.2021.0017
IxTheo#2021-08-06#3F69F96B7497C12FD3F128DF03FE381F7A6D7C9C

**Ausführliche Problembeschreibung**
@socheres @thefass 
Kann dieser Artikel "**Notes and Comments**" grundlegend ausgeschlossen werden?
Ich bin keine Fachreferentin und habe keine genauen Vorgaben, was ausgeschlossen werden sollte und was nicht.

Und sollte aus dieser Liste 
((Editorial|Guest\s+Editorial)|(A?\s?(Word)?\s?From\s+the\s+Editors?)|(Editors?\W?s?\s+(Notes?|Introduction|Preface))|(Introduction|Foreword)|((Front|Back)\s+Matter)|(Contributors)|(Books\s+Received)|(New\s+Books)|(About\s+This\s+Issue)|(Issue\s+Information)|(Contents)|(Preliminary\s+Material)|(Indexes\s+Vol\W)|(Abstracts?|Notes\s+On\s+Contributors)|(Einleitung)|(Inhalt)|(Inhaltsverzeichnis\s?(Heft)?)|(Associate?s+Editors?)|(Publisher\Ss\s+Notes?)|(List\s+of\s+Contributors)|(Table\s+of\s+Contents?)|(Announcements?))$

**Comment by IxKo** [comment]
Ein weiteres Beispiel, diesmal bei einer Taylor $ Francis-Zs: https://doi.org/10.1080/15363759.2021.1960047 Titel: Selected Dissertations on Christian Higher Education

**Comment by IxKo** [comment]
Ein weiterer Titel mit der Frage, ob dieser grundlegend ausgeschlossen werden soll:
Regnum Notice for April 2021 issue
https://journals.sagepub.com/doi/full/10.1177/02653788211008281

**Comment by IxKo** [comment]
Noch ein Titel mit der gleichen Frage:
**Book Notes**
https://onlinelibrary.wiley.com/doi/10.1111/erev.12608

**Comment by socheres** [comment]
Für Fachcommunity sind es interessante Notizen z.B. https://doi.org/10.1353/cat.2021.0017 Ich werde dies in der Fachreferatsrunde besprechen.

**Comment by socheres** [comment]
zur Info für nächste Fachreferatsrunde @thefass

**Comment by socheres** [comment]
in der Fachreferatsrunde wurde beschlossen, Datensätze wie die oben erwähnten "Notizen" jeglicher Art mit aufzunehmen.
@IxKo Würden Sie die Liste wie folgt anpassen:

((Editorial|Guest\s+Editorial)|(A?\s?(Word)?\s?From\s+the\s+Editors?)|(Editors?\W?s?\s+(<s> Notes?|</s>Introduction|Preface))|(Introduction|Foreword)|((Front|Back)\s+Matter)|(Contributors)|(Books\s+Received)|(New\s+Books)|(About\s+This\s+Issue)|(Issue\s+Information)|(Contents)|(Preliminary\s+Material)|(Indexes\s+Vol\W)|(Abstracts?|<s>|Notes\s+On\s+Contributors</s>)|(Einleitung)|(Inhalt)|(Inhaltsverzeichnis\s?(Heft)?)|(Associate?s+Editors?)|<s>(Publisher\Ss\s+Notes?)|</s>(List\s+of\s+Contributors)|(Table\s+of\s+Contents?)|(Announcements?))$

**Comment by IxKo** [comment]
Ich habe es angepasst.
Vielen Dank für die Klärung!

**Comment by IxKo** [comment]
Ich möchte auch nicht riskieren, dass ungewollte Artikel ohne Autorenname eingespielt werden, die noch nicht auf der Exclude-List stehen. Durch die QA-Settings/Error-Datei hat man hier eine gute Filterung, um möglicherweise unerwünschte Titel vor Einspielen zu prüfen.

Es ist abzuwägen, welcher Aufwand größer ist: Die Notes manuell nachkatalogisieren oder permanent die eingespielten Datensätze ohne Verfasserangabe auf unerwünschte Titel prüfen und zu löschen und dabei der Gefahr zu unterliegen, Titel zu übersehen.

Eine White-List von Titeln ist wahrscheinlich auch keine Alternative.
Ich schlage vor, erstmal den Aufwand bis Ende November zu beobachten.

**Comment by IxKo** [comment]
Weitere Beispiele:

- Verzeichnis der Mitarbeiter https://doi.org/10.1628/zevkr-2019-0042 (ähnlich zu Notes on Contributors)
- Libri ad Directionem missi https://doi.org/10.2143/BIB.102.2.3289506 (ähnlich zu Books received)
- Contributors https://doi.org/10.2143/EP.28.2.3289671 (ähnlich zu Notes on Contributors))

**Comment by IxKo** [comment]
Geklärt im Meeting:
Es wird alles aufgenommen außer Titel=Editorial und Titel wie Front oder Back Matter

**Comment by IxKo** [comment]
Änderung der Conf.
Folgende Titel werden weiterhin **ausgeschlossen**:

- Editorial
- Guest Editorial
- A Word From the Editors
- From the Editors Desk
- Editors Introduction
- Editors Preface
- Introduction
- Foreword
- Front Matter
- Back Matter
- About This Issue
- Issue Information
- Contents
- Indexes Vol
- Einleitung
- Inhalt
- Inhaltsverzeichnis
- Table of Contents
- Volume Contents


Nachfolgende Titel werden künftig **aufgenommen** (zusätzlich zu allen Titeln mit "Notes"):

- Books Received
- New Books
- Preliminary Material
- List of Contributors
- Index JJJJ
- Associate Editors
- Announcements
- Call for Papers


@socheres Könnten Sie bitte kurz drüber schauen, ob das so in Ordnung geht?

**Comment by IxKo** [comment]
Und sollen Call for Papers auch aufgenommen werden? @socheres
