### ISSUE TITLE
2781 | Journal of religion, media and digital culture | Bei RetroKat mit zotk fehlt Datum und Publikation

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1579]
**URL**
https://brill.com/view/journals/rmdc/rmdc-overview.xml

**Ausführliche Problembeschreibung**
Die Zeitschrift wird ab 9(2029,3) mit zota katalogisiert. Bei der Retrokatalogisierung mit zotk werden Datum und Publikation nicht heruntergeladen. Online-Publication date ist auf Website.

**Offenbare Lösungen**
Wie kann man das Problem lösen?

**Comment by socheres** [comment]
das Problem ist behoben, bitte testen: https://github.com/socheres/Zoterobearbeitung/commit/afefcc7b9d51608cf147a8efbdd2dd8291dc500c

**Comment by RelBibRetroKat** [comment]
Getestet. Problem behoben. Vielen Dank

**Comment by socheres** [comment]
Ich schließe dann das Issue.
