### ISSUE TITLE
ISSN 2162-6499 Augustinianum Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#158]
Vgl. #150 ebenfalls PDCnet. Hier wie dort wird kein Sprachcode (Tag 041) geliefert, was bei den nicht englischen Artikeln zu einer falschen Angabe oder einer Fehlermeldung führen wird.

**Comment by shadeMe** [comment]
Das ist die Problematik, die ich in meiner heutigen Email beschrieben habe. Ich füge sie hier einfachheitshalber hinzu:

> Wir arbeiten gerade an einem Mechanismus für die automatische Erkennung eines Datensatzes anhand deren Titel und Abstract. Wir können ihn dann verwenden, wenn der Translator keine Sprache zurückgibt. Dennoch ist es nur eine Heuristik, die nicht 100-prozentig genau ist. Von daher wäre es sinnvoll, die Sprache(n) einer Zeitschrift auch im Zeder einzutragen (sagen wir in einer "lang" Spalte). Dann haben wir eine Rückfallebene zur Auswertung.

**Comment by thefass** [comment]
Es gibt in zeder schon eine Spalte für die Sprache: spr
Es kann sein, dass sie nicht immer ausgefüllt ist, aber dann muss das ergänzt werden

**Comment by kdr154** [comment]
Die Aufsätze in dieser ZS erscheinen leider in vielen Sprachen. Englisch, Französisch, Italienisch und Spanisch habe ich in Zeder eingetragen.

**Comment by kdr154** [comment]
Nach dem Harvesting erscheint bei mir jetzt eine leere XML-Datei

**Comment by shadeMe** [comment]
@kdr154 Ich habe's gerade gefixt. Bitte nochmal probieren.

**Comment by kdr154** [comment]
Stimmt, auch die Sprachbezeichnungen in den Testdaten sind korrekt
