### ISSUE TITLE
zotero_harvester Namensprocessing [alle ZS betroffen]

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1585]
Bei Datensätzen mit einem einteiligen Personennamen, z.B. "Manitonquat" im Datensatz mit der URL https://journals.sagepub.com/doi/10.1177/004057368203900107, wird der Name komplett gelöscht, das JSON sieht folgendermaßen aus:
{
			first_name: ,
			last_name: ,
			type: author,
}
Über den normalen Zotero-Download kommt der folgende Datensatz heraus:
![grafik](https://user-images.githubusercontent.com/49190455/132467024-22b4f615-ec3b-430a-8abe-5f1159be830b.png)
Dieser Name sollte nach RDA-Regelwerk in MARC-Feld 100, Unterfeld a, mit den Indikatoren '0' und ' ' übernommen werden; ein Komma sollte in diesem Fall nicht ergänzt werden.
Zudem möchte ich darauf hinweisen, dass diese Erfassungspraxis geistige Schöpfer*innen benachteiligt, deren Namen nicht dem westlichen Schema entsprechen.
Bitte um Kenntnisnahme & Kommentierung durch:
@IxKo , @socheres , @RelBibRetroKat , @jriedl , @mtrojan-ub

Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Datensätze mit bestimmten Namensmustern landen in Errors-Dateien und werden dann halbautomatisch im zotkat-Verfahren katalogisiert. Wenn das Problem in Retroprojekt auftritt, bitte mit @IxKo zusammen überlegen, wie man am Besten vorgeht.

**Comment by helenanebel** [comment]
Lieber @socheres , auf BENU landet nichts in Error-Dateien, sondern die Datensätze enthalten nur ' , ' im Namensfeld. Das sollte m.E. unabhängig davon, was in Error-Dateien landet, nicht geschehen.

**Comment by jriedl** [comment]
Die Ursache ist, dass offenbar Zotero-seitig der `creator` in solchen Fällen nicht mehr im `firstName`/`lastName`-Schema zurückgeben wird, sondern mittlels `name`. Im Handling im Harvester wird bei nur einem Namen dann grundsätzlich nur der Vorname gesetzt. Warum diese Entscheidung getroffen wurde, ist mir nicht bekannt, ist habe es für den Augenblick so belassen.
