### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift : RvT | RSS-Feed-Problem

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#1588]
Der RSS-Feed ist kaputt:
https://tidsskrift.dk/rvt/gateway/plugin/WebFeedGatewayPlugin/rss

Am Anfang des Feeds über dem XML Root Element befindet sich ein Script-Tag (vermutlich wegen Cookie Consent):
Dadurch wird die XML-Datei beschädigt und kann nicht mehr gelesen werden.

```
<script src="//cookie-script.com/s/2d58d2b3a13b0eb49ff32a57dc77c4ab.js"></script>
<?xml version="1.0" encoding="utf-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	xmlns="http://purl.org/rss/1.0/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:prism="http://prismstandard.org/namespaces/1.2/basic/"
	xmlns:cc="http://web.resource.org/cc/">
```

**Comment by mtrojan-ub** [comment]
Der Fehler führt dazu dass der Harvesting-Durchlauf auf Nu am Ende einen Fehler meldet:
> *** ZTS_HARVESTER DELIVERY PIPELINE FAILED ***

**Comment by mtrojan-ub** [comment]
Angeschrieben, bislang noch keine Reaktion.

Das PIPELINE FAILED Problem scheint übrigens laut weiteren Nachforschungen ein anderes Problem zu sein.

**Comment by IxKo** [comment]
Auf nu mit Try RSS kommt folgende Fehlermeldung:

> Harvesting feed 1 [Religionsvidenskabel...] | https://tidsskrift.dk/rvt/gateway/plugin/WebFeedGatewayPlugin/rss2 {6500523116725515861}
> problem parsing XML document for RSS feed 'https://tidsskrift.dk/rvt/gateway/plugin/WebFeedGatewayPlugin/rss2': Error while parsing syndication format: Xerces SAXParseException on line 2: XML or TEXT declaration must start at line 1, column 1

Ich schließe das Issue, weil die Zs. momentan nicht im Test ist.
