### ISSUE TITLE
ISSN 1893-0271 | Teologisk tidsskrift | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1590]
**URL**
https://www.idunn.no/tt/2021/02

Einzel-Artikel-Beispiel:
https://www.idunn.no/tt/2021/02/da_gud_forlot_gud_jesu_vei_til_doeden_og_dens_betydning_for

angebotener und genutzter **Translator** im Multi-DL:
ubtue_Nordic Journal of Religion and Society

**Ausführliche Problembeschreibung**

- [x] Paralleltitel
Auf der Artikelseite gibt es einen übersetzten Titel "When God left God: The significance of the death of Jesus"
Dieser sollte nach Zotero übernommen werden und dann in den K10plus in das Feld 4002 für den Paralleltitel

- [x] #1603 (Sprache nicht auf Seite hinterlegt, also nicht lösbar)
Die Sprache der meisten Artikel ist norwegisch. Zotero erfasst sie aber alle als englisch. Könnte hier vielleicht etwas gemacht werden?

- [x] Trennung zweier Abstracts
Beide Abstracts werden erfasst, aber nicht automatisch voneinander getrennt.

**Comment by IxKo** [comment]
@helenanebel 
Vielen Dank, sieht fast alles gut aus. Nur wenn man die Daten als Single exportiert, wird beim Paralleltitel eine Leerzeile erzeugt:
![image](https://user-images.githubusercontent.com/57000004/141330102-5ead40e4-24cc-4500-9bf7-01d8cb9fc99e.png)

Beim Batch ist es nicht so.
Die Sprache Norwegisch wird nun auch importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
da waren noch Tags drin, die dazu geführt haben.
Das dürfte jetzt nicht mehr der Fall sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Gelöst, danke!

**Comment by IxKo** [comment]
@socheres 
Der Import-Translator "ubtue_Nordic Journal of Religion and Society.js" ist in meinem Ordner. Der Translator wird mir jedoch nicht auf der Webseite angeboten - nur der Atypon.
Woran liegt das? Ich habe die Translators aktualisiert.

**Comment by socheres** [comment]
Wir können es uns heute nachmittags beim IKR-Zoom-Meeting gemeinsam ansehen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die URL sowie der gesamte Seitenquelltext haben sich geändert, dadurch passt die Regex nicht mehr auf die URL, einzelne Artikel werden auf der Issue-Seite nicht mehr gefunden und auf der Artikelseite sind die Metadaten nicht mehr in strukturierten Tags vorhanden. Man müsste für diese Seite einen komplett neuen Translator schreiben.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Liebe @helenanebel, kann dann ein neuer Translator oder der alte angepasst werden? Oder sind die Metadaten nun so murks, dass es nicht geht?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe einen neuen Translator "ubtue_Idunn" geschrieben, dieser müsste funktionieren.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
da die Sprachen nicht auf der Seite hinterlegt sind, wäre es gut, für diese ISSN (nor) und die ISSN von "Nordic Journal of Religion and Society" (eng) einen Eintrag in der Conf zu hinterlegen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Beim Export wird das zweite Abstract vom anderen getrennt. Allerdings fehlt beim zweiten ein Leerzeichen nach dem Pica-Feld:
![image](https://user-images.githubusercontent.com/57000004/159220784-8308ac38-7727-4d37-b139-38ad248109d9.png)

https://doi.org/10.18261/issn.1893-0271-2021-04-02

**Comment by helenanebel** [comment]
Liebe @IxKo ,
dürfte jetzt nicht mehr der Fall sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Vielen Dank, ist nun behoben.

**Comment by IxKo** [comment]
Liebe @helenanebel , könnten die Rezensionen noch gekennzeichnet werden?
Sie stehen in der Rubrik "Bokanmeldelse" und sind auf den Artikel-Seiten als "Book Review" angegeben:
![image](https://user-images.githubusercontent.com/57000004/162196102-dfabcb9a-85bf-4c8c-a0d0-d20284c0a166.png)
