### ISSUE TITLE
Z1838/Z2070 (Journal of Religion and Society) | Zotkat Eignungsprüfung | Abstract fehlt 

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1596]
**URL**
http://moses.creighton.edu/JRS/toc/Archive.html

**Ausführliche Problembeschreibung**
Abstract fehlt.

**Offenbare Lösungen**
Translator "Journal of Religion and Society.js" anpassen

**Comment by socheres** [comment]
Aufgrund der gleichen Translator-ID wurde der lokale Translator mit der offiziellen Version überschrieben.

**Comment by IxKo** [comment]
Nun werden die PDF-Links übertragen.
Die Handles können nicht abgegriffen werden?
Wenn nicht, muss man sie immer manuell ergänzen.

**Comment by IxKo** [comment]
Die Bandangabe und der Publikationstitel fehlen.
Zudem wird immer ein Tag "Journal Article" generiert:
![image](https://user-images.githubusercontent.com/57000004/141982660-92abf69c-f89d-4328-996f-8bed00a5c8a0.png)

Und im DOI-Feld steht der Resolving-Link des Handles.
Es müsste für den Handle ein Sonder-Feld oder eine Notiz erstellt werden, damit der Handle mit angepassten Export-Translators im Feld 2052 ausgegeben wird.

Er verhält sich fast gleich zum DOI, bloß statt Feld 2051 wird das Feld 2052 belegt:
2052 10504/129192
4950 http://hdl.handle.net/10504/129192$xR$4LF

**Comment by socheres** [comment]
https://github.com/socheres/Zoterobearbeitung/commit/b34492d3365477e71a0413e48cfe528440ede555

**Comment by IxKo** [comment]
Es sieht schon sehr gut aus!
Es müsste noch die **Bandangabe** übertragen werden und gerne auch der **Publikationstitel**.

Die Resolving-URL des Handles sollte als **$xR** statt $xH gekennzeichnet werden.

**Comment by IxKo** [comment]
Noch eine Frage zu der SSG-Nummer:
Das Journal hat in Zeder die Eintragung ber=FG_1
und die Supplements FG_0

Ist das so gewollt?

**Comment by socheres** [comment]
> Noch eine Frage zu der SSG-Nummer: Das Journal hat in Zeder die Eintragung ber=FG_1 und die Supplements FG_0
> 
> Ist das so gewollt?

@Gazeller wenn Ihr wollt, könnt Ihr auch die Zeitschrift Z1838 mit "FG_0"(=SSG 0) versehen. Für mich sind beide "0/1"

**Comment by IxKo** [comment]
Danke, passt nun alles.
