### ISSUE TITLE
ISSN 1573-6571 | Journal of religion and health (Springer) | Verfasser ORCID und Open Access Angabe (LF) fehlen im Translator

### ISSUE THREAD

**Issue by IxTss** [ubtue/DatenProbleme#1598]
**URL**
https://link.springer.com/journal/10943/volumes-and-issues/60-5

**Ausführliche Problembeschreibung**
Die ORCID der VerfasserInnen und die Angabe für Open Access (LF) fehlen im Translator.
Beispiel-Artikel (LF und Orcid vorhanden): [https://link.springer.com/article/10.1007/s10943-021-01246-1](https://link.springer.com/article/10.1007/s10943-021-01246-1)

**Comment by IxKo** [comment]
Bei mir werden zudem im Pica-Single-Export HTML-Tags bei den ORCIDS eingefügt:
![image](https://user-images.githubusercontent.com/57000004/137755407-5784ec2b-3e0a-481d-9e3e-504a191e6e88.png)

Den Fall hat IxTss seltsamerweise nicht.
