### ISSUE TITLE
SSOAR_MARC 21 Feld 024 $a

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#16]
Alle Einträge mit dem Präfix "oai:gesis.izsoz.de:document/..." bezeichnen nur die Herkunft der Metadaten.
Sie dürfen m.E. nicht in den Titeldaten abgelegt werden.

Die Identifier in Feld 001 sollen im lokalen PICA-Feld 7811 abgelegt werden.
Sollen diese Einträge ebenfalls als Identifier lokal abgelegt werden?

**Comment by kdr154** [comment]
024 ind1=8 bezeichnet eine unspezifische Art einer Standardnummer. Sollte daher kein Problem sein.

**Comment by IxTheoKm** [comment]
Nach Rücksprache mit dem BSZ soll 024 $a mit Präfix "oai:gesis.izsoz.de:document/" in den Exemplardaten für lokale Projekte abgelegt werden: Marc 938 $l $8 1 (PICA 8521).

Beispiel:
```
<datafield tag="024" ind1="8" ind2=" ">
<subfield code="a">oai:gesis.izsoz.de:document/3674</subfield>
```

**Comment by IxTheoKm** [comment]
Okay
