### ISSUE TITLE
ISSN 2565-7070 Biblica falsche Sprachbezeichnung bei einem Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#160]
unerklärlich, warum bei diesem Artikel französisch (fre) in 041 erscheint.
http://poj.peeters-leuven.be/content.php?url=article&id=3285368

**Comment by kdr154** [comment]
Hier ist der Language code weiterhin nicht immer richtig:
Hier http://poj.peeters-leuven.be/content.php?url=article&id=3284714&journal_code=BIB
müsste es eng sein statt ger
hier: http://poj.peeters-leuven.be/content.php?url=article&id=3284715&journal_code=BIB
eng statt ita

**Comment by shadeMe** [comment]
Das Problem liegt wahrscheinlich dran, dass der Titel zu kurz ist. Wenn die Heuristik auch die Zusammenfassung auswertet, wird die richtige Sprache erkannt. Ich passe sie so an, dass sie die Zusammenfassung zusätzlich berücksichtigt, wenn weniger als 5 Wörter im Titel stehen. 

Allerdings müssen wir beachten, dass die Heuristik wird nie 100-prozentig richtig sein und es immer wieder Fälle geben wird, in denen die beste Vermutung falsch ist.

**Comment by shadeMe** [comment]
@kdr154 Bitte nochmal testen.

**Comment by kdr154** [comment]
ok
