### ISSUE TITLE
ISSN 1573-0697 | Journal of Business Ethics (Springer) | Reihenfolge Autor:innen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1600]
**URL**
https://link.springer.com/article/10.1007%2Fs10551-020-04518-0

**Ausführliche Problembeschreibung**
Die Autor:innen werden nicht in der korrekten Reihenfolge mit dem Pica-Translator (sowohl Batch als auch Single) exportiert, obwohl sie in der Zotero-Anwendung in korrekter Reihenfolge sind:

![image](https://user-images.githubusercontent.com/57000004/138270686-83906bd1-b1c4-44b4-8ee9-9cf708235f7e.png)

![image](https://user-images.githubusercontent.com/57000004/138270768-a4686b43-4352-417e-9eb7-fb9f0d9f4035.png)

![image](https://user-images.githubusercontent.com/57000004/138270888-7eddb835-5f0d-4806-bb35-75718924eca3.png)

**Comment by IxKo** [comment]
@helenanebel Im Single-Export werden sie in richtiger Reihenfolge ausgegeben.

**Comment by helenanebel** [comment]
Liebe @IxKo , dann versuche ich mal, den Batch entsprechend anzupassen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
es müsste jetzt auch mit dem Batch funktionieren, ich habe diese Datensätze erstellt: 
f abl ixzo bud 2021-11-12
und hier waren alle in der richtigen Reihenfolge.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Die Translators sind nun lokal auch aktualisiert worden und kann getestet werden.

**Comment by IxKo** [comment]
Gelöst, danke!
