### ISSUE TITLE
ISSN 1434-5935 | Journal of religious culture = Journal für Religionskultur (Goethe-Universität Frankfurt/M)

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1601]
**URL**
http://publikationen.ub.uni-frankfurt.de/solrsearch/index/search/searchtype/series/id/16137/start/0/rows/10/sortfield/year/sortorder/descDie Harvest URL

**Ausführliche Problembeschreibung**
Es werden beim Einzel-Download nur Autor, Titel, Sprache und URL heruntergeladen.
Es fehlen Publikation, Ausgabe, Seiten, Datum,DOI, ISSN

**Offenbare Lösungen**
Eventuell gibt es noch keinen Translator für diese Plattform

**Comment by RelBibRetroKat** [comment]
Liebe Helena Nebel,
vielen Dank für den Translator. Publikation, Band, Sprache sind gut. Es wird der Link der URN eingespielt. Vermutlich ist diese - im Gegensatz zum DOI - nicht in 2050 einzuspielen? Heruntergeladen werden die Aufsätze als Einzeldownload. Ein Mehrfachdownload habe ich nicht gesehen.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
können Sie auf dieser Seite: http://publikationen.ub.uni-frankfurt.de/solrsearch/index/search/searchtype/series/id/16137/start/0/rows/**50**/sortfield/year/sortorder/desc nicht herunterladen?
Für die Einspielung der URN haben wir noch kein System, man könnte das aber theoretisch einführen.
@socheres , soll ich da etwas entwickeln, dass man die URN in item.notes mit "urn:[urn]" übergibt und diese dann im Export mit herüberkommt?
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena Nebel,
nein, ich kann nur von der Seite der einzelnen Aufsätze herunterladen. Ich warte gerne darauf, dass die URN auch exportiert wird.
Viele Grüße
Sybille Deselaers

**Comment by socheres** [comment]
> @socheres , soll ich da etwas entwickeln, dass man die URN in item.notes mit "urn:[urn]" übergibt und diese dann im Export mit herüberkommt?

Ja, gerne. Aber auch 4950 mit dem Präfix:https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=2050&katalog=Standard&adm=1
Bsp.:
2050 urn:nbn:de :101:1-2012052110172
4950 http://nbn-resolving.de/urn:nbn:de :101:1-2012052110172$xR$3Volltext$534

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
ich habe die Anpassung vorgenommen, die URN müsste dann jetzt rüberkommen, wenn Ready for Testing gesetzt wurde.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
![Journal of religious culture](https://user-images.githubusercontent.com/51993589/144397631-2ad4ec41-b019-4b88-a664-eaaea910d72e.jpg)
Ich habe heute ca. 40 Aufsätze zum Test heruntergeladen. Wie man auf dem Bild sieht, wurde überwiegend die Nummer des Aufsatzes in "Band" aufgenommen, bei den allerneusten aber in "Ausgabe" und das Jahr in "Band". Ideal ist die Nummer des Aufsatzes in "Band". Die URN kam als extra-Angabe und wurde nicht in den K10plus eingespielt. Die Sprachbezeichnung "tr" für Türkisch wurde so übernommen und nicht in "tur" umgewandelt. Es wird auf der Website in "Seitenzahl" die Gesamtzahl der Seiten angegeben, die nicht in Zotero in "Seiten" übernommen wird. Wenn es auf der Webseite Angaben in "Bemerkungen" gibt, versucht Zotero statt des Translators "Embedded Metadata" anzuwenden und die Angaben können nicht heruntergeladen werden. Beispiele: Nr. 244 http://publikationen.ub.uni-frankfurt.de/frontdoor/index/index/docId/50456, Nr. 244a http://publikationen.ub.uni-frankfurt.de/frontdoor/index/index/docId/50823 und Nr. 250 http://publikationen.ub.uni-frankfurt.de/frontdoor/index/index/docId/51319

**Comment by IxTheoKm** [comment]
Ich weiß nicht, ob ich es richtig verstehe, aber für durchgehende Nummern von Aufsätzen gibt es inzwischen ein eigenes PICA-Unterfeld $i (siehe im Handbuch für unselbständige Werke Kapitel 2.1.4.7 $i - Artikel-ID von Online-Publikationen).

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
jetzt müssten auch Sprache + Bandangabe richtig sein, ich habe mit den ersten 40 Aufsätzen getestet.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Seitenangabe und Sprache sind jetzt korrekt. Vielen Dank für die Verbesserung. Es handelt sich aber tatsächlich um Artikelnummern.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
ich habe die Artikel-IDs in $i hinzugefügt. Sie werden über Notizen übernommen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @socheres ,
könnten Sie hier auch auf ready for testing setzen?
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena Nebel,

ich habe heute nochmal vier Artikel heruntergeladen. Die Artikelnummer kommt jetzt in $i, aber auch in $v. Ich sende anbei einen Screenshot von den Aufnahmen im K10plus
![Journal of religious culture_2021-12-17](https://user-images.githubusercontent.com/51993589/146561213-da64db26-2a0f-4517-87fc-db3ab0a4889a.jpg)

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
ja, das habe ich so gelassen, weil Sie meinten, es wäre gut für den Überblick, aber natürlich stört es dann in $v. Dann entferne ich das noch.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Artikelnummern getestet. Alles in Ordnung. Vielen Dank für die Hilfe und Grüße Sybille Deselaers
