### ISSUE TITLE
DOI-Notiz bei Translator ubtue_vandenhoeck_ruprecht

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1605]
**URL**
https://www.vr-elibrary.de/toc/gpre/74/1

**Ausführliche Problembeschreibung**
Der DOI wird in Zotero als zusätzliche Notiz übertragen.
Dies kann gerne entfallen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe den RIS-Translator angepasst, der intern aufgerufen wird. Dieser hat die DOI ergänzt. Jetzt müssten alle Notizen, die DOIs mit dem Prefix "doi: " enthalten, entfernt werden.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Liebe @helenanebel, Ihre Anpassung an dem RIS-Translator habe ich wieder rückgängig gemacht. Stattdessen habe ich den RIS-Translator aus der offiziellen Version übernommen.

**Comment by IxKo** [comment]
Die DOIs kommen weiterhin als Notiz mit.

**Comment by helenanebel** [comment]
Liebe @IxKo , 
da meine Änderungen nicht übernommen wurden, kann ich leider nichts machen! @socheres wird das sicher lösen können!
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, ist gelöst.
