### ISSUE TITLE
ISSN 2056-5666 | Christianity & literature (Muse) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1606]
**Bsp-URL**
 IxTheo#2021-11-01#F6C2F56364DE964C5C32A3677A5923B67B228825
https://muse.jhu.edu/article/835551

**Ausführliche Problembeschreibung**
Die Rezensionen wurden nicht erkannt

**Comment by socheres** [comment]
auf nu kann getestet werden.

**Comment by IxKo** [comment]
Danke, wird auf Nu korrekt erkannt.
Bitte die Änderungen schnellstmöglich auf ub28 bringen, da die Zs bereits live geschalten wurde.

**Comment by socheres** [comment]
> Danke, wird auf Nu korrekt erkannt.
> Bitte die Änderungen schnellstmöglich auf ub28 bringen, da die Zs bereits live geschalten wurde.

@jriedl könntest du die Änderung auch auf ub28 nachziehen? Danke.

**Comment by jriedl** [comment]
Reicht Montag?

**Comment by jriedl** [comment]
Eingespielt.
