### ISSUE TITLE
Problem beim LookUp-Verfahren

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1608]
Lieber @socheres , liebe @IxKo ,

bei dieser URL: https://doi.org/10.1628/004435413X13835622623393 funkioniert die Verknüpfung nicht, obwohl der Autor in der GND vorhanden ist (gnd/120841940) und auch der einzige Theologe mit diesem Namen ist. Allerdings hat er auch unter einem Pseudonym veröffentlicht (gnd/1200377338) und ich vermute, dass das hier zu Problemen führt.
Ich weiß nicht, wie der LookUp genau funktioniert, aber eventuell könnte man die Pseudonyme ausschließen.

Viele Grüße, Helena

**Comment by socheres** [comment]
Das Problem liegt woanders und nicht am Lookup. Im halbautomatischen Verfahren wird der Autor mit einem GND-Datensatz verknüpft. Bin weiterhin auf der Fehlersuche.

**Comment by socheres** [comment]
Die Lookup-URL von [zota](https://github.com/ubtue/zotero-enhancement-maps/blob/77a7f7b4e2d26137d391389bcd8f457ae1f30f83/zotero_harvester.conf#L73) ins zotkat übernommen und getestet. 
```
//Lookup für Autoren
                if (authorName[0] != "!") {
                    var lookupUrl = "https://swb.bsz-bw.de/DB=2.104/SET=70/TTL=1/CMD?SGE=&ACT=SRCHM&MATCFILTER=Y&MATCSET=Y&NOSCAN=Y&PARSE_MNEMONICS=N&PARSE_OPWORDS=N&PARSE_OLDSETS=N&IMPLAND=Y&NOABS=Y&ACT0=SRCHA&SHRTST=50&IKT0=8991&TRM0=theolog*&ACT1=-&IKT1=8991&TRM1=1[0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8][0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9][0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9]&ACT2=*&IKT2=3040&TRM2=" + authorName;
```
Hier das Export-Ergebnis. Es wird mit dem richtigen Satz verknüpft. Es kann also nicht an dem Lookup liegen.

```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2013
1500 ger
1505 $erda
2051 10.1628/004435413X13835622623393
3000 !080920276!$BVerfasserIn$4aut 
8910 $aixzom$bAutor in der Zoterovorlage [Rohls, Jan] maschinell zugeordnet
4000 Thomas Manns »Doktor Faustus« und die Theologie
4070 $v110$j2013$a4$p439-474
4207 Thomas Mann's »Doktor Faustus« is based on the old Lutheran novel combining the biography of a former student of Protestant theology with that of a composer of the 20th century. Protestant theology as well as the music of this century are characterised by an antihumanism which culminates in the Second World War. The connection between antihumanism and German culture is interpreted as a pact with the Devil which ends in the madness of the hero of the novel and the question whether there is any grace for the hero and his country.
4241 Enthalten in!505951835!
4950 https://doi.org/10.1628/004435413X13835622623393$xR$3Volltext$4ZZ$534
5056 1
E* l01
7100 $Jn
8012 ixzs$aixzo
```

**Comment by jriedl** [comment]
Die "Zeitschrift  für Theologie und Kirche" ist aber doch offenbar gar nicht im Zotaut-Verfahren. 
Auffällig ist:

`https://swb.bsz-bw.de/DB=2.104/SET=70/TTL=1/CMD?SGE=&ACT=SRCHM&MATCFILTER=Y&MATCSET=Y&NOSCAN=Y&PARSE_MNEMONICS=N&PARSE_OPWORDS=N&PARSE_OLDSETS=N&IMPLAND=Y&NOABS=Y&ACT0=SRCHA&SHRTST=50&IKT0=8991&TRM0=theolog*&ACT1=-&IKT1=8991&TRM1=1[0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8][0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9][0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9]&ACT2=*&IKT2=3040&TRM2=Rohls,Jan`
ergibt

![image](https://user-images.githubusercontent.com/13135579/142888257-74a6c6cf-da1d-4726-8271-4c7e79c3e4cf.png)

Wenn man das Leerzeichen nach dem Komma des Autorennamens (mit `+` oder `%20` ) mit übergibt, scheint es zu funktionieren:

![image](https://user-images.githubusercontent.com/13135579/142889204-8295c32b-d792-4792-be5b-c379fc03a1b5.png)

Der Harvester erzeugt den Namen allerdings mit Leerzeichen. Gibt es einen Config-Eintrag, mit dem man testen kann?

**Comment by jriedl** [comment]
Mit Conf-Eintrag der Zeitschrift von Benu und tryUrl:
![image](https://user-images.githubusercontent.com/13135579/142891821-17679065-bbc0-4db8-80ee-5ef28627a1f3.png)

**Comment by jriedl** [comment]
Die fehlende URL kann eventuell an anderen Translators auf nu liegen.

**Comment by socheres** [comment]
Danke @jriedl Kannst du bitte benu, nu, ub28 dementsprechend anpassen. Denn der GND-Lookup funktioniert nur dann zuverlässig, wenn man das Leerzeichen nach dem Komma in codierter Form übergibt. Oder?

**Comment by jriedl** [comment]
Da die Namen vom Harvester selbst zusammengestellt werden und ein Leerzeichen enthalten, ist das unproblematisch. Wie oben zu sehen, funktioniert die Abfrage.

**Comment by socheres** [comment]
Ach so. Dann lag es an dem fehlenden Config-Eintrag. OK.

**Comment by socheres** [comment]
@helenanebel nach dem Testen bitte Issue schließen.

**Comment by helenanebel** [comment]
Okay, vielen Dank!
