### ISSUE TITLE
ISSN 1783-1652 | Ons geestelijk erf (Peeters) | Doppelheft-Trennzeichen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1610]
**URL**
0711709B6775468D4ED1AB478370B2DA1737FA73
https://poj.peeters-leuven.be/content.php?url=article&id=3289673

**Ausführliche Problembeschreibung**

> Validating record IxTheo#2021-11-07#0711709B6775468D4ED1AB478370B2DA1737FA73...
> Record IxTheo#2021-11-07#0711709B6775468D4ED1AB478370B2DA1737FA73 is invalid:
> 936: contents of subfield $e(3-4) did not match regex "^\d+(/\d+)?$"

![image](https://user-images.githubusercontent.com/57000004/140723071-5aef3b90-9220-474e-b365-e04461dba43e.png)

Die Doppelheft-Zählung sollte mit Schrägstrich 3/4 getrennt werden.

**Comment by IxKo** [comment]
Danke, ist auf Nu nun korrekt. Auf ub28 noch nicht.

**Comment by socheres** [comment]
> Danke, ist auf Nu nun korrekt. Auf ub28 noch nicht.

Wenn der Test auf nu erfolgreich abgeschlossen ist, wenden Sie sich bitte gleich an @jriedl , damit die Änderungen auch auf ub28 vorgenommen werden können.
