### ISSUE TITLE
Keine Auswahl von ubtue-Translators

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1611]
**URL**
Bei allen Plattformen werden mir die ubtue-Translators nicht mehr angeboten.

Nur beispielhaft !! :
Peeters
https://poj.peeters-leuven.be/content.php?url=issue&journal_code=CS&issue=1&vol=36

Brill
https://brill.com/view/journals/jesh/61/5-6/jesh.61.issue-5-6.xml

Vandehoeck & Ruprecht
https://www.vr-elibrary.de/toc/gpre/74/1

Und gab es für die Sage-Plattform nicht auch einen ubtue-Translator - schließlich sind die Sage-Zss auf zota gesetzt?
Bzw. sollte es nicht für alle Plattformen von denen wir katalogisieren eigene ubtue-Translators geben?

**Comment by socheres** [comment]
Die lokalen Translator-Ordner wurden gestern von mir aktualisiert. Mir wird die ubtue-Translators angeboten. Sicherheitshalber die Translators über die Connector-Einstellung "Advanced > Update Translators" einmal updaten und bitte noch einmal testen. "ubtue_Sage Journals.js" ist auch in ihrem Verzeichnis vorhanden.

**Comment by IxKo** [comment]
Danke, die Translators werden mir wieder angezeigt.
Ich hatte allerdings vor dem Öffnen dieses Issues die Translators über die Erweiterungsoptionen aktualisiert gehabt und das mehr als einmal und die Seiten aktualisiert.
Daher verstehe ich das nicht so recht.
