### ISSUE TITLE
Änderung der Conf. bzgl. auszuschließender Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1612]
Änderung der Conf.
Folgende Titel werden weiterhin **ausgeschlossen**:

- Editorial
- Guest Editorial
- A Word From the Editors
- From the Editors Desk
- Editors Introduction
- Editors Preface
- Introduction
- Foreword
- Front Matter
- Back Matter
- About This Issue
- Issue Information
- Contents
- Indexes Vol
- Einleitung
- Inhalt
- Inhaltsverzeichnis
- Table of Contents
- Volume Contents

Nachfolgende Titel werden künftig **aufgenommen** (zusätzlich zu allen Titeln mit "Notes"):

- Books Received
- New Books
- Preliminary Material
- List of Contributors
- Index JJJJ
- Associate Editors
- Announcements
- Call for Papers

@socheres Könnten Sie bitte kurz drüber schauen, ob das so in Ordnung geht?

_Originally posted by @IxKo in https://github.com/ubtue/DatenProbleme/issues/1578#issuecomment-963261249_

**Comment by IxKo** [comment]
Und sollen Call for Papers auch aufgenommen werden? @socheres

**Comment by socheres** [comment]
wie in der Abteilungsbesprechung vom 09.12.2021 besprochen, sollen ab 2022 in allen Verfahren (Zotkat, Zotaut, ImageWare, manuelle Kat.) nur noch diese beiden Titel ausgeschlossen werden:

- Front Matter
- Back Matter

@thefass @Gazeller @relhei @AleAprile @IxKo @IxTheoKm @RelBibRetroKat @IxGe einverstanden?
Für RetorkatPorjekt von @helenanebel wird die Datensätze nachgeliefert.

@IxKo würden Sie die conf-Datei anpassen? Danke.

**Comment by IxKo** [comment]
@socheres Ich kann sie anpassen, sobald es beschlossen ist und keine Person Einwände hat.
Wenn es erst ab nächsten Jahr gemacht werden soll, kann ich es allerdings erst am 10. Januar umstellen.

**Comment by relhei** [comment]
Wir (@Gazeller und ich) haben nichts dagegen, danke!

**Comment by thefass** [comment]
dito: einverstanden

**Comment by helenanebel** [comment]
@socheres , @IxKo ich bin einverstanden, würde aber noch weitere Rubriken ausschließen, wie List of Contributors, Werbung/Anzeigen bzw. Announcements, Table of Contents bzw. Inhaltsverzeichnisse. Das würde ja auch in der Realität niemand als eigene Ressource erfassen, denke ich.

**Comment by IxGe** [comment]
Ich war in der Abteilungsbesprechung zu diesem Punkt nicht mehr anwesend.
Vermutlich geht es doch um .... alle AUTOMATISCHEN Verfahren .... bei denen die Vorlage nicht vorliegt? Bei der Zeitschriftenkatalogisierung mit ImageWare wird man kein Editorial mit diesem Titel und ohne greifbaren Inhalt aufnehmen
 - oder wurde das heute beschlossen?

**Comment by IxKo** [comment]
> @socheres , @IxKo ich bin einverstanden, würde aber noch weitere Rubriken ausschließen, wie List of Contributors, Werbung/Anzeigen bzw. Announcements, Table of Contents bzw. Inhaltsverzeichnisse. Das würde ja auch in der Realität niemand als eigene Ressource erfassen, denke ich.

Da stimme ich zu. Es gibt deutlich noch mehr Titel als die beiden (Front Matter, Back Matter), die ausgeschlossen werden sollten.
zB.
* Issue Information - TOC https://anthrosource.onlinelibrary.wiley.com/doi/10.1111/etho.12269
* MANY THANKS TO BIOETHICS REVIEWERS https://onlinelibrary.wiley.com/doi/full/10.1111/bioe.12972
* TOC https://onlinelibrary.wiley.com/doi/10.1002/cvj.12108
* Guidelines for Authors https://onlinelibrary.wiley.com/doi/10.1002/cvj.12107
* Contents to Volume 28 (2021) https://brill.com/view/journals/ils/28/4/article-p459_459.xml
* List of Referees https://www.tandfonline.com/doi/full/10.1080/13537903.2021.2007631
* Announcement Herman Dooyeweerd Prize 2022 https://brill.com/view/journals/phir/86/2/article-p137_137.xml
* Indexes Vol. 124 https://journals.sagepub.com/doi/10.1177/0040571X211056804


Wenn alle Notes aufgenommen werden, dann wird auch so etwas erfasst:
* Notes and News https://www.tandfonline.com/doi/full/10.1080/00310328.2021.1995243

**Comment by helenanebel** [comment]
@IxKo , genau, so etwas meinte ich. Notes würde ich immer aufnehmen, weil die nicht grundsätzlich irrelevant sind.

**Comment by socheres** [comment]
Ich bin dafür, dass wir alles aufnehmen, außer den beiden von mir genannten.

**Comment by socheres** [comment]
> Ich war in der Abteilungsbesprechung zu diesem Punkt nicht mehr anwesend. Vermutlich geht es doch um .... alle AUTOMATISCHEN Verfahren .... bei denen die Vorlage nicht vorliegt? Bei der Zeitschriftenkatalogisierung mit ImageWare wird man kein Editorial mit diesem Titel und ohne greifbaren Inhalt aufnehmen
> 
> * oder wurde das heute beschlossen?

hier soll auch @thefass eine Entscheidung treffen.

**Comment by IxKo** [comment]
Nun ist das Jahr 2022. Ist hier eine endgültige Entscheidung getroffen worden?

**Comment by IxKo** [comment]
Notes-RegEx in Conf den oben genannten Titeln angepasst.
Nur noch Front/Back Matter werden ausgeschlossen.

Bekanntgabe während der Abteilungsbesprechung, dass dies auch beim halbautomatischen Verfahren eingehalten werden soll, und danach Versenden einer Mail an die Betreffenden.
