### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion (Oxford Academic) | ORCID und LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1614]
**URL**
https://academic.oup.com/socrel/article/82/4/426/6054784
IxTheo#2021-11-10#254E6F2D72608B3EE8C2FDEC758F240E162A0E80

**Ausführliche Problembeschreibung**
Die ORCIDs der drei Personen wurden nicht übertragen.

Ebenso wurde nicht erkannt, dass es sich um einen lizenzfreien Artikel handelt.

Die Zs wurde schon auf zota gesetzt..

**Comment by helenanebel** [comment]
Liebe @IxKo ,
diese ZS kann jetzt getestet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, sieht auf Nu gut aus und kann auf ub28 übertragen werden.
Könnte auch der Translator für das halbautomatische Verfahren noch angepasst werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das für das halbautomatische Verfahren übernommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt
