### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion (Oxford Academic) | Komplette Rezension als Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1615]
**URL**
IxTheo#2021-11-10#F02C01411B65E1E3C5DE07A75F0B4A9A38168468
https://academic.oup.com/socrel/article/82/4/527/6358063

**Ausführliche Problembeschreibung**
Bei der Rezension wurde einfach der ganze Rezensionstext als Abstract übermittelt.
Hier sollte gar kein Abstract stehen.

Die Zs steht bereits auf zota.

**Comment by socheres** [comment]
Können Sie bitte auf nu bzw. benu nochmal testen? Im Zotero-Standalone bzw. Scaffold kann ich den Fehler leider nicht reproduzieren (Extract wird hier abgeschnitten). Ich bin auch über VPN ins Uni-Netz eingeloggt.
```
12:06:18 Returned item:
           {
             "itemType": "journalArticle"
             "creators": [
               {
                 "firstName": "Daniel Azim"
                 "lastName": "Pschaida"
                 "creatorType": "author"
               }
             ]
             "notes": []
             "tags": [
               {
                 "tag": "Book Review"
               }
             ]
             "seeAlso": []
             "attachments": [
               {
                 "title": "Full Text PDF"
                 "mimeType": "application/pdf"
               }
               {
                 "title": "Snapshot"
                 "mimeType": "text/html"
               }
             ]
             "title": "Islam on Campus: Contested Identities and the Cultures of Higher Education in Britain, by ALISON SCOTTBAUMANN, MATHEW GUEST, SHURUQ NAGUIB, SARIYA CHERUVALLIL-CONTRACTOR, and AISHA PHOENIX"
             "url": "https://academic.oup.com/socrel/article/82/4/527/6358063"
             "abstractNote": "This work, produced by a five-scholar research team, argues that a climate of suspicion and surveillance undermines the university experience of Muslims in the"
             "date": "2021/11/10"
             "publicationTitle": "Sociology of Religion"
             "journalAbbreviation": "Sociol Relig"
             "volume": "82"
             "issue": "4"
         -   "publisher": "Oxford Academic"
             "DOI": "10.1093/socrel/srab041"
             "pages": "527-528"
             "ISSN": "1069-4404"
             "language": "en"
             "libraryCatalog": "academic.oup.com"
         -   "accessDate": "CURRENT_TIMESTAMP"
             "shortTitle": "Islam on Campus"
           }
```

**Comment by IxKo** [comment]
Auf Nu (tryl url) kommt ebenfalls der ganze Text als Abstract mit: 

![image](https://user-images.githubusercontent.com/57000004/142423441-237a45a1-c420-4ada-aac9-bbb4e6026192.png)

**Comment by IxKo** [comment]
In neuen Einspielungen passiert es ebenfalls: IxTheo#2023-11-09#EC08D8FB6A0F5845485ADB4A64DABD9363B1A24E
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/de17c283-fb13-4fa3-b567-9cd86a819075)

**Comment by IxKo** [comment]
Auch bei IxTheo#2024-04-05#81E63FFB8BA5B0ECF87A0925F7E16237BFCB65B3 und IxTheo#2024-04-05#D913595A896BACB97F1B0F4565D0840DC30FA161 ist es wieder passiert.

**Comment by IxKo** [comment]
Danke, auf nu werden keine Abstracts mehr bei Rezensionen erzeugt.

In #851 wurde es allerdings auch als Problem gemeldet. Ich hatte das Issue dann nur geschlossen, weil es ein sehr altes Issue war und ich gebeten wurde, alte Issues zu schließen.
Warum diese Zs. trotz des Problems damals auf zota gesetzt wurde, ist für mich nicht mehr nachvollziehbar.
