### ISSUE TITLE
ISSN 2165-9214 | Journal of religion, media and digital culture (Brill) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1618]
**URL**
IxTheo#2021-11-12#E5E83C6BA1D689D1EDB85CC6B38FBF099696AB3C
https://brill.com/view/journals/rmdc/10/2/article-p350_350.xml

**Ausführliche Problembeschreibung**
Die Rezensionen in diesem Heft wurden nicht erkannt.

**Comment by IxKo** [comment]
In vorherigen Einspielung gab es da kein Problem und die Rezensionen wurden erkannt. Beispiel: IxTheo#2021-08-09#3A6F8A64CBC45B5A656641E12DE57ECC7F033D18

Wieso werden sie es plötzlich nicht mehr? So etwas sollte nicht passieren.

**Comment by socheres** [comment]
Bislang werden nur "Book review" als Rezension erkannt, aber nicht "Review Article". `if (reviewEntry && reviewEntry.match(/book\sreview/i))` Hier die HTMLquelltest:

```
 <dd class="articlecategory inline c-List__item c-List__item--secondary text-metadata-value">
                
                        
            Review Article
        
                    
            </dd>
```
view-source:https://brill.com/view/journals/rmdc/10/2/article-p350_350.xml

**Comment by IxKo** [comment]
In der PDF-Vorschau wird es unter Book Reviews aufgeführt, daher sollte es als Rezension getagt werden.

**Comment by socheres** [comment]
Die implementierte Logik kennt keine PDF-Vorschau:smile:Daher sollten wir es dabei belassen und uns an die von dem Verlag vergebenen Tags halten. Ansonsten werden auch "Quasi-Resenzionen" als Rezension erkannt und die Diskussion geht von vorne wieder los:smile: Siehe auch https://github.com/ubtue/DatenProbleme/issues/1305#issuecomment-766790674

**Comment by socheres** [comment]
Liebe @IxKo kann dieses Issue geschlossen werden?
