### ISSUE TITLE
ISSN 2633-0695 | Journal for Interdisciplinary Biblical Studies | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1623]
**URL**
https://jibs.group.shef.ac.uk/archive/volume-3/

Einzel/Hinterlegte Links zu den Aufsätzen:
https://hcommons.org/deposits/item/hc:40073/

**Ausführliche Problembeschreibung**
Die Zs wird von Innsbruck erschlossen.
Für diese Seite wird kein Translator angeboten.
Die einzige Möglichkeit, die Daten mit Zotero zu erfassen, ist einzeln per DOI-Translator. Allerdings müssen danach einige Informationen manuell ergänzt werden (ISSN, Band, Seitenangabe) und der "Autor" Journal for Interdisciplinary Biblical Studies muss entfernt werden.

**Comment by socheres** [comment]
Nach erfolgreichem Test bitte Innsbrucker benachrichtigen.

**Comment by IxKo** [comment]
Die **Heftzählung** wird nicht importiert und auch das Feld, um welche **Publikation** es sich handelt ist leer.

Des Weiteren wird der **DOI** nicht in Kurzform sondern als Resolving-Link übertragen, wodurch er als Link in Feld 2051 übertragen wird. In dem Feld muss aber die Kurzform des DOIs stehen.

**Comment by IxKo** [comment]
Danke, passt alles, nur der Publikationsname wird weiterhin nicht übertragen.
Es wäre schön, wenn dieser immer mitkäme, um in Zotero auf Anhieb zu sehen, um welche Zs es sich handelt.
