### ISSUE TITLE
ISSN 0173-0339 | Religionspädagogische Beiträge | Titel-Wiederholung und Pseudo-Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1625]
**URL**
https://rpb-journal.de/index.php/rpb/issue/view/39

**Translator**
ubtue_Open Journal Systems Standard.js

**Ausführliche Problembeschreibung**
Der Zusatztitel wiederholt sich, bspw. hier: https://rpb-journal.de/index.php/rpb/article/view/103
![image](https://user-images.githubusercontent.com/57000004/143249013-6cb87f33-3e80-4cad-a384-535302baab34.png)

Außerdem werden bei Rezensionen als Abstracts drei Minusstriche importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich kann beide URLs nicht öffnen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel 
Seltsam, bei mir ging es eben. Vielleicht war die Seite heute Mittag down?
![image](https://user-images.githubusercontent.com/57000004/144080484-17f8a9be-3e09-4f12-a565-0cf68a72dc94.png)

**Comment by helenanebel** [comment]
Liebe @IxKo  ,
ich habe den Translator bearbeitet, es wird jetzt vor dem Anfügen des Untertitels geprüft, ob dieser bereits übernommen wurde.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke!
