### ISSUE TITLE
ISSN 0718-9273 | Veritas (ScieELO) | falscher Titel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1633]
**URL**
https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-92732016000100006&lng=en&nrm=iso&tlng=es

**Import-Translator**
  ubtue_SciELO.js (Einzel-Import)
  
**Ausführliche Problembeschreibung**
Es wird fälschlicherweise der englische Paralleltitel als Titel erfasst, statt der spanische:

![image](https://user-images.githubusercontent.com/57000004/143876049-51cf5855-78f3-4793-abcb-9e15bd5a6842.png)

![image](https://user-images.githubusercontent.com/57000004/143875954-61f76287-2b73-427e-9485-db7ebf160474.png)

**Comment by socheres** [comment]
Liebe @IxKo hier ist die Sache etwas kompliziert.
Der von Ihnen angegebene Link ist die englische Webseite "lng=en":
https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-92732016000100006&lng=en&nrm=iso&tlng=es
Im Quellcode ist der Titel dann auch auf englisch
`meta xmlns="" name="citation_title" content="Metaphysical presuppositions for a sound critical historiography applied to the biblical text">`
Zudem hat der spanische Titel im HTML-Code kein eindeutiges Muster, so dass man ihn ohne Seiteneffekte übernehmen könnte.
Man muss leider die spanische Webseite aufrufen, um den Titel auf spanisch zu übertragen "lng=sn":
https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-92732016000100006&lng=sn&nrm=iso&tlng=es
Im Quellcode sieht dann so aus:
`<meta xmlns="" name="citation_title" content="Presupuestos metafísicos de una sana historiografía crítica aplicada al texto bíblico">`
Der englische Paralleltitel müsste dann manuell hinzugefügt werden. @helenanebel haben Sie vielleicht eine Lösung?

**Comment by helenanebel** [comment]
Lieber @socheres ,
ich würde die BibTex-Datei aufrufen: 
https://www.scielo.cl/scielo.php?download&format=BibTex&pid=S0718-92732016000100001
Die pid ist ja bekannt und in der BibTex steht auch bei der englischen Anzeige der korrekte Titel.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Liebe @helenanebel Das ist eine gute Idee. Ja, gerne können Sie den Translator so anpassen, wenn die Bibtex-Datei immer den korrekten Originaltitel enthält. Paralleltitel müsste man aber manuell ergänzen, oder? Außerdem fehlt die Bandnummer in der bibtex, so dass Sie den Aufruf von Embedded Metadata unverändert lassen sollten.

```
@article{CASAS RAMIREZ2016,
   title = {{Entre la oscuridad y el silencio: ciegos y sordomudos en el mundo de la Biblia}},
   journal = {{Veritas}},
   author={Casas Ram\~A\-rez, Juan Alberto},
   ISSN = {0718-9273},
   language = {es},
   URL = {http://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-92732016000100001&nrm=iso},
   year = {2016},
   month = {03},
   pages = {09 - 32},
   publisher = {scielocl},
   crossref = {10.4067/S0718-92732016000100001},
   }
```

**Comment by helenanebel** [comment]
Lieber @socheres ,
ja, ich würde nur den Titel aus der BibTex holen, den Rest würde ich so lassen.
Dann wäre der englische Titel ja sowieso da & den würde ich dann in den Paralleltitel verschieben, falls er sich von Titel in der BibTex unterscheidet.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Noch zur Info: bite beim Testen alle in Test vorhandenen Links markieren und updaten.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das behoben, der Paralleltitel kommt jetzt in 4002 mit. Soll ich mich noch darum kümmern, dass ein Multi-DL möglich ist?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
> Liebe @IxKo , ich habe das behoben, der Paralleltitel kommt jetzt in 4002 mit. Soll ich mich noch darum kümmern, dass ein Multi-DL möglich ist? Viele Grüße, Helena Nebel

Danke, das wäre wunderbar und würde die Arbeit erleichtern.

Beim Testen ist mir Folgendes aufgefallen:

* Es wird keine **Sprache** eingetragen. Ich nehme an, die Information ist nicht abgreifbar?

* Und beim Export werden **HTML-Tags** bei Paralleltitel und Abstract gesetzt:
![image](https://user-images.githubusercontent.com/57000004/144411169-c85578c9-4b79-40b8-820f-5dec911284c2.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
hier gibt es keine Sprachangabe, es müsste ein Eintrag für die Sprache in der Mapping-Liste stehen, da sonst der Export fehlschlägt, weil keine Sprache gefunden wird.
Lieber @socheres ,
könnte man dafür einen Workaround finden? Der einfache Abbruch ohne genaue Fehlermeldung ist etwas unbefriedigend, weil man dann ewig Debuggen muss. Könnte man dann in den Batch-Upload-Translator ein Popup-Fenster integrieren, was den*die Bearbeiter*in darauf hinweist, was das Problem ist? Dann kann man anhand dieses Fensters gleich ein entsprechendes Issue mit der Problembeschreibung anlegen. Soll ich das machen?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Wenn ich das richtig sehe, gibt es In der Bibtex das Feld Sprache. Das mit dem "Batch-Upload-Translator" habe ich nicht verstanden. Beim Batch-Upload in WiniBW gibt es eine Validierung von WinIBW-Programm selbst. Vielleicht besprechen wir dies im Zotaut-Meeting.

**Comment by helenanebel** [comment]
LiebeR @IxKo , @socheres ,
Habe ein Sprachtag im HTML gefunden. 
Für den Titel benötige ich leider statt BibTex Ris, weil BibTex nicht utf-8-codiert ist & deshalb die spanischen Buchstaben mit Diakritika falsch wiedergibt. Im Ris ist leider keine Sprache enthalten.
Ich habe die Probleme behoben, Multi-DL mache ich noch.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, passt nun!
