### ISSUE TITLE
ISSN 1745-5235 | Studies in Christian Ethics (SAGE) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1635]
**URL**
[Die Harvest URL](https://journals.sagepub.com/doi/10.1177/0953946815623013)

**Import-Translator**
  ubtue_SAGE Journals.js
  
**Ausführliche Problembeschreibung**
Der Artikel kann weder im Einzel- noch Multi-Import geladen werden. Der Translator bricht mit einem Fehler ab.

![image](https://user-images.githubusercontent.com/57000004/143877612-80d8ffe1-e578-4b33-b421-796032ac8a82.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe den Fehler korrigiert.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Vielen Dank!
