### ISSUE TITLE
ISSN 0081-6175 | Studi e Materiali di Storia delle Religioni | Sprache

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1636]
**URL**
 	http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3d30h%26AN%3d149156264%26site%3dehost-live

**Import-Translator**
  EBSCOHost.js
  
**Ausführliche Problembeschreibung**
Häufig ist eine Sprache angegeben, die aber nicht importiert wird:

![image](https://user-images.githubusercontent.com/57000004/144028861-be4052c6-5f4d-41cf-8252-f1ff3eb53fa4.png)

![image](https://user-images.githubusercontent.com/57000004/144029000-7a090c62-f2c2-47d4-949e-1e5cb5cf51a7.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Sprache kommt jetzt korrekt in Zotero. Allerdings stimmt das im Batch-Export nicht:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map:
0393-8417=ita # Studi e materiali di storia delle religioni (SMSR)
Hier wird deshalb immer ita gesetzt.
Das evtl. ändern.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel Danke für den Hinweis! Ich habe den Eintrag aus der Mapping-Liste entfernt.

**Comment by IxKo** [comment]
Danke, die Sprache wird nun importiert.

Dafür fiel mir jetzt etwas anderes auf: Der Publikationsname der Zs wird in Zotero nur angegeben, wenn der Titel auf Englisch ist. Bei anderssprachigen Titeln, wird der übersetzte englische Aufsatztitel in das Feld übertragen:

![image](https://user-images.githubusercontent.com/57000004/144213572-6f8006c7-4d9a-4262-bd55-d296cfd7ca6b.png)

Die Information des übersetzten Titels könnte als Sucheinstieg in Feld 3260. Dafür müsste aber der Export-Translator auch angepasst werden, da wir das Feld bisher nicht mit Zotero genutzt haben.
Die Übersetzung selbst scheint nicht in der Vorlage auffindbar, es scheint also eine Zusatzinformation von der Plattform selbst zu sein.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
4212 wird nun belegt: 4212 Übersetzung des Haupttitels:  The book of Leviticus and its historical-literary origins in the society of post-exilic Israel: Sacral institutions as an instrument of ethnic-religious self-definition., das wird dann auch im Katalog angezeigt.
Finde ich besser als 3260 & wir ebenfalls indexiert.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, die Sprache wird nun importiert.

**4212** wird beim Batch-Export belegt, aber nicht beim **Single-Export**.

Und im Feld "**Publikation**" in Zotero steht weiterhin der übersetzte englische Aufsatztitel.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Feld Publikation wird m.E. beim Export nicht verwendet.
Der Single-Export wurde nicht angepasst. Benötigen wir diesen?
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das Feld "Publikation" angepasst.
viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe zwei neue Issues aufgemacht:
ubtue/DatenProbleme/issues/1648
ubtue/DatenProbleme/issues/1647
falls diesbezüglich sonst alles erledigt ist, kann das Issue auch geschlossen werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Das Feld Publikation ist nun okay, ebenso die Sprache.
Die Notiz für den übersetzten Artikel führt beim Batch-Upload zu HTML-Tags:
![image](https://user-images.githubusercontent.com/57000004/146573129-42d6cf0a-7f0f-4e14-9e79-01ab4703d3be.png)

Und im Single-Export wird das 4212-Feld nicht erzeugt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das müsste jetzt behoben sein.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo, 
eigentlich der Batch-Translator bei nur einem Datensatz jetzt einen Single-Export machen, das müsste auch schon ready for testing sein: ubtue/DatenProbleme/issues/1647
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel 
Danke! Ja, der Batch-Translator verhält sich bei einem einzelnen Datensatz nun wie der Single.
Eine Anpassung des Single-Translators wäre also nicht mehr notwendig.
Das muss allerdings noch mit anderen Katalogisierenden geklärt werden und ich weiß noch nicht wie sich das auf Kooperationspartner auswirkt.
Dieses Thema muss wie viele andere dann nächstes Jahr besprochen werden oder ihr klärt es nächsten Montag :-) Ich setze es schonmal auf "for meeting discussion".
