### ISSUE TITLE
ISSN 1877-8372 | Oriens | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1637]
**URL**
IxTheo#2021-11-25#189CE33D7B4384C243FBE89271ABE609885CA120
https://doi.org/10.1163/18778372-12340005

IxTheo#2021-11-25#63272E9389799D675F462ED8F65D85254F6AF1AB
https://doi.org/10.1163/18778372-12340006

IxTheo#2021-11-25#B7F8B530FBE112F31FE8D4E99341DE5A2415F4F0
https://doi.org/10.1163/18778372-12340004

**Import-Translator**
  ubtue_Brill.js
  
**Problembeschreibung**
Die beiden Abstracts werden nicht voneinander getrennt eingespielt.

**Comment by IxKo** [comment]
Wird auf Nu nun korrekt getrennt, auf ub28 noch nicht.

**Comment by socheres** [comment]
Liebe @IxKo, bitte in solchen Fällen (Live-Einspielung) nach erfolgreichem Test @jriedl um Update auf ub28 bitten.

**Comment by IxKo** [comment]
> Liebe @IxKo, bitte in solchen Fällen (Live-Einspielung) nach erfolgreichem Test @jriedl um Update auf ub28 bitten.

Okay

----
@jriedl Bitte um Update auf ub28.

**Comment by IxKo** [comment]
Passt nun, danke!
