### ISSUE TITLE
ISSN 1874-8945 | Social Sciences and Missions (Brill) | Sprache

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1639]
**URL**
https://brill.com/view/journals/ssm/34/3-4/article-p441_13.xml
Hash auf ub28: B8F7C959B3BDCA2D5858E32AABBFE939E30FB50D
  
**Import-Translator**
  ubtue_Brill.js
  
**Problembeschreibung**
Der Datensatz landet in den Errors, weil als Sprache Spanisch erkannt wird (da der rezensierte Titel ein Spanischer ist). Der Translator liefert aber korrekt Sprache "fra". 
![image](https://user-images.githubusercontent.com/57000004/145428379-c469eee0-0655-48c2-bfa7-6a6d99e15d9b.png)

Ich glaube es gibt noch keine Einstellung, mit der immer die mitgelieferte Sprache genommen werden soll?
Wenn beim Testen festgestellt wird, dass die Sprache in den Metadaten bereits korrekt ist, können wir doch auf die automatische Spracherkennung anhand des Titels verzichten, oder?

**Comment by jriedl** [comment]
Ist mittlerweile umgesetzt - vgl. die Doku zu zotero_expected_languages:
```ini
#- Force language returned from the translator (modifier =)
#     - There will be no detection, the language language determined in the translator will be used if it matches
#       one of the language paramaters given in this parameter. Otherwise no language is set.
#     - Make sure to quote the righthand side of the expression in this case to prevent clashes with ini assignment.
#       (i.e. e.g. zotero_expected_languages = "=eng,fre")
```
Wichtig sind die Anführungszeichen in diesem Fall.

**Comment by IxKo** [comment]
@jriedl 
Ich habe in Zederspalte sprz als Wert "=eng,fre" eingetragen. Es wird jedoch nicht in die conf übernommen, dort steht weiterhin:
zotero_expected_languages = ?eng,fre
force_language_detection  = true

Habe ich die Zeder-Eintragung falsch gemacht?

**Comment by IxKo** [comment]
@jriedl 
Die Eintragung aus Zeder wurde nicht in die conf übernommen:
![image](https://user-images.githubusercontent.com/57000004/152516681-a48b9ac8-8dcd-431b-b614-513c1f25e8a0.png)

---
Ich habe bei einer Zs (2210-5956 | Journal of Sufi Studies (Brill) aus Issue #1669) mal auf Nu mit Try URL und Additional Config die Eintragung aus Zeder "=eng,fre" getestet und es klappt:

![image](https://user-images.githubusercontent.com/57000004/152517221-b9346ebe-c57a-4432-9d81-4487f07dceaf.png)

**Comment by IxKo** [comment]
Wenn eine Sprache vom Translator kommt, die nicht in Zeder gesetzt ist, verhält es sich auch korrekt:
![image](https://user-images.githubusercontent.com/57000004/152517596-51282115-cc92-423b-bc31-4bef35c82f2b.png)

**Comment by IxKo** [comment]
Auch bei einem anderen Fall (ISSN 2232-1969) scheint die Zeder-Eintragung in Spalte sprz nicht übernommen zu werden:
Die Eintragung in Zeder habe ich gestern so geändert gehabt:
![image](https://user-images.githubusercontent.com/57000004/156338665-3462103f-5a8d-42a6-9aa1-34c509077d04.png)

In der Conf steht jedoch heute weiterhin:
![image](https://user-images.githubusercontent.com/57000004/156338937-bebca25d-91c5-4d2f-a6c5-cf666a5f371e.png)

**Comment by IxKo** [comment]
Okay, ich habe nun in Zeder die Anfühungszeichen entfernt (betraf momentan 7 Zeilen).

**Comment by IxKo** [comment]
Wurde mittlerweile korrekt mit 1500 fre eingespielt.
