### ISSUE TITLE
ISSN 1743-0623 Fieldwork in Religion Tag 007

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#164]
"tu" in 007 scheint mir bei diesen Aufsätzen nicht gerechtfertigt, da sie allen einen DOI besitzen und somit eine elektronische Ressource sind. tu in 007 steht für einen nicht näher spezifizierten Text.

In den Aufsätzen von https://api.equinoxpub.com/issues/FIR/current.rss
findet sich in 007:
`<controlfield tag="007">tu</controlfield>`
In meinen Augen sollte es analog zu den anderen Ressourcen so sein:
`<controlfield tag="007">cr|||||</controlfield>`

Auch bei ISSN 1463-9955 Implicit Religion der Fall. 
https://api.equinoxpub.com/issues/IR/current.rss
Ebenfalls Equinox. 
Scheint daher was Equinoxspezifisches zu sein.

Ob man es bei tu belassen kann, kann ich nicht sagen.

**Comment by shadeMe** [comment]
007 wird anhand der ISSN eingefüllt bzw. "tu" für Print und "cr" für Online. Das Problem scheint daran zu liegen, dass die Print und Online ISSN Nummer der Zeitschriften im Zeder falsch eingetragen wurden. Im Falle von _Fieldwork in Religion_, sind die beiden ISSN gleich (ist das überhaupt möglich?) und deswegen kann der Harvest nicht zwischen den zwei unterscheiden. Bei _Implicit Religion_ gibt es erstens keine Online ISSN und daher wird die Print ISSN benutzt.

Mein Vorschlag wäre die entsprechenden Zeder-Einträge zu korrigieren und in diesem Issue kurz Bescheid zu geben, damit wir unsere Konfiguration aktualisieren können.

**Comment by thefass** [comment]
Die ZDB ist seit Stunden nicht erreichbar, so dass man dies nicht kontrollieren kann.
Allerdings ist in Zeder auch die PPPN falsch, habe ich korrigiert
@shadeMe : gleiche ISSN für print und online kann vorkommen. Deswegen gibt es ja auch die ZDB Nummer, wo print und online Ausgabe immer mit einer eigenen ZDB Identnummer versehen sind. ISSN können unzuverlässig sein

**Comment by thefass** [comment]
ISSNs sind korrigiert

**Comment by kdr154** [comment]
ESSN bei Implicit Religion eingetragen

**Comment by kdr154** [comment]
gelöst
