### ISSUE TITLE
Allgemein:  Trennzeichen zum Zusatztitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1641]
**URL**
https://www.degruyter.com/document/doi/10.1515/zfr-2021-0009/html
  
**Import-Translator**
  ubtue_.DeGruyterjs
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Im halbautomatischen Zotero-Verfahren wird idR der erste Doppelpunkt im Titel als Trennzeichen $d für den Zusatztitel umgewandelt und exportiert.

In vielen Fällen ist diese Trennung auch zutreffend und in vielen anderen Fällen auch nicht.

Daher mein Vorschlag: Auf dieses Trennzeichen kann wie beim vollautomatischen Verfahren verzichtet werden und der Titel wird 1 zu 1 übernommen.
Katalogisierende können - wenn sie das möchten - das Trennzeichen manuell selbst setzen.
Es erspart in Zukunft völlig falsch gesetzte Trennzeichen, wie in diesem Fall:
![image](https://user-images.githubusercontent.com/57000004/145839977-bf4a5ba6-9791-40bd-8f35-f34f0958df38.png)

**Wenn in den Quelldaten, die der Translator importiert, bereits zwischen Haupt- und Zusatztitel unterschieden wird, kann das Trennzeichen direkt vom Import-Translator gesetzt werden und nach Zotero importiert werden**
Gleiches sollte dann aber auch für das vollautomatische Verfahren und deren Translators möglich sein.

Es soll nur nicht mehr nur aufgrund des Vorhandenseins eines Doppelpunktes beim Export ein solche Trennung erfolgen.

**Comment by IxTheoKm** [comment]
Ich stimme dem Vorschlag unbedingt zu! Im Englischen werden m.W. Bibelstellen mit Doppelpunkt statt mit Komma angegeben. Diese würden durch den Doppelpunkt auch auseinandergerissen werden.

**Comment by socheres** [comment]
> Ich stimme dem Vorschlag unbedingt zu! Im Englischen werden m.W. Bibelstellen mit Doppelpunkt statt mit Komma angegeben. Diese würden durch den Doppelpunkt auch auseinandergerissen werden.

Doppelpunkt zwischen den Zahlen werden nicht ersetzt `:(?!\d)\s*`. Das hatten wir irgendwann schon angepasst.

**Comment by socheres** [comment]
>Daher mein Vorschlag: Auf dieses Trennzeichen kann wie beim vollautomatischen Verfahren verzichtet werden und der Titel wird 1 zu 1 übernommen.
Katalogisierende können - wenn sie das möchten - das Trennzeichen manuell selbst setzen.

Liebe @IxKo schreiben Sie diesbezüglich bitte eine  Rundmail an alle Katalogisierende (auch an Krimdok!).

**Comment by IxKo** [comment]
Danke, es funktioniert wie gewünscht.

@socheres  @helenanebel 
Wie erkenne ich, ob bereits beim Import-Translator eine korrekte Trennung möglich ist, weil die Metadaten zwischen Haupt- und Zusatztitel unterscheiden?

**Comment by socheres** [comment]
wir sollten generell keine Trennzeichen "$d" setzen, auch wenn dies möglich ist. Der Translator soll auf jeden Fall so angepasst werden, dass der Zusatztitel mit Doppelpunkt+ein Leerzeichen in das Titelfeld übernommen wird.

**Comment by IxKo** [comment]
Und warum sollte in solch klaren Fällen, bei denen Haupt- und Zusatztitel bereits in unterschiedlichen HTML-Tags getrennt werden, kein $d gesetzt werden, sondern ein Doppelpunkt+Leerzeichen?

**Comment by socheres** [comment]
das Setzen von Trennzeichen erfolgt exportseitig im Pica-Skript. Mann kann dies aber auch importseitig machen und den Zusatztitel ins Feld item.notes schreiben und später beim Export wieder zusammenführen. Es ist eher die Frage nach dem Verhältnis von Aufwand und Nutzen. Wenn es konkrete Beispiele geben sollte, dann bitte ein Issue eröffnen. Wir könnten dann das Issue uns in einem der Zotaut-Treffen klären.

**Comment by IxKo** [comment]
Ok, dann schaue ich, ob ich in Zukunft einen Beispiel-Fall finde und öffne ein Issue.
