### ISSUE TITLE
ISSN 2385-8907 | Edinost in Dialog (DOAJ) | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1642]
**URL**
https://www.doaj.org/toc/2385-8907?source=%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%222335-4127%22%2C%222385-8907%22%5D%7D%7D%5D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%2C%22track_total_hits%22%3Atrue%7D
  

einzelner Artikel:
https://www.doaj.org/article/33b71862dc9e4f9cb2c45c0e51aeada1

**Import-Translator**
 DOAJ.js
  (Einzel-Import)
  
**Problembeschreibung**
Für diese Website wird mir nur im Einzel-Import ein Translator angeboten.
Nutze ich diesen, werden folgende Informationen schon korrekt übermittelt:

- [x] Autor und Titel
- [x] Band, Heft, Seitenangabe, Jahr
- [x] DOI
- [x] ISSNs

und folgende nicht:

- [x] **Abstract** (es wird ein allgemeines Abstract der Zs, statt das Abstract des Artikels importiert: "DOAJ is a community-curated online directory that indexes and provides access to high quality, open access, peer-reviewed journals.")
- [x] **Keywords** werden nicht übertragen
- [x] URL sollte die Artikel-URL sein und nicht die PDF-DOI
- [x] //Sprache wird falsch als "en" importiert//

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ein Multi-Download wird auf der Seite nicht unterstützt, da die Artikelanzeige über ein Skript generiert wird. Ich kann über https://doaj.org/api/v2/search/articles/issn:2335-4127?page=1&pageSize=50&sort=title:desc&callback=myjsonp (die API) einen Multi-DL ermöglichen, falls das gewünscht ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel Wenn ein Multi-Import verhältnismäßig zu viel Arbeitsaufwand ist, dann reicht auch ein Single-Import.
Das weiß ich leider nicht, daher habe ich es nur mit-erwähnt :-)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe einen neuen Translator ubtue_DOAJ geschrieben. Er geht über die API und ermöglicht so auch Multi-DL.
Leider ist die Sprache in den Metadaten sowohl im HTML als auch im Output der Schnittstelle nicht enthalten. Ebenso wird immer der englische Titel angegeben, der Haupttitel laut PDF ist aber in den von mir kontrollierten Fällen slowenisch.
Der Originaltitel ließe sich durch eine zusätzliche Abfrage der Seite https://www.teof.uni-lj.si/publications/unity-and-dialogue innerhalb des Translators noch abgreifen, falls das gewünscht ist, die Sprache sollte dann m.E. am Besten über eine Conf gesetzt werden.
Viele Grüße, Helena Nebel
