### ISSUE TITLE
1972-2516 | Mythos: rivista di storia delle religioni | Zählung in Band statt in Ausgabe

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1644]
https://journals.openedition.org/mythos/

  
ubtue_OpenEdition Journals
  ubtue_....js
  Mehrfach-Import
  
Die Zählung wird in Ausgabe übertragen. Korrekt wäre die Zählung in Band, da jährlich eine Ausgabe erscheint

**Comment by RelBibRetroKat** [comment]
Die Zählung ist jetzt in Band, aber die Aufnahmen werden mit Absätzen in den Translator übertragen, s. Anlage
![Mythos Rivista](https://user-images.githubusercontent.com/51993589/147095538-2b9cb7e0-59cf-4998-a847-9a7ca5ad12f1.jpg)

**Comment by socheres** [comment]
Das steht im Zusammenhang mit dem Issue #1647 
Wenn Sie einen Batch-Export durchführen, bitte mehr als ein Eintrag aus Zotero exportieren, dann sollte alles wie vorher aussehen.

**Comment by IxKo** [comment]
Wird nun in Band übertragen:

![image](https://user-images.githubusercontent.com/57000004/226585267-6d7a9c14-64f1-4e75-9888-2267dd7ca88f.png)
