### ISSUE TITLE
ISSN 0580-1400 | Münchener theologische Zeitschrift (E/A) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1645]
**URL**
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000023198%26site%3dehost-live
  
**Import-Translator**
  EBSCOhost.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Es ist nicht möglich Daten zu importieren. Der Translator bricht ab.

Gleiches Problem betrifft auch ISSN 0340-6210 | Luther (http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000003420%26site%3dehost-live)

![image](https://user-images.githubusercontent.com/57000004/146339540-f39de6bd-d756-431e-9fcb-b5531a701b1c.png)

**Comment by IxKo** [comment]
Ebenfalls Probleme macht es bei der Zs 2385-8907 | Edinost in dialog
Hier klappt es dann mit Einzel-Import, allerdings verhält sich dieser eher wie ein Multi, da sich ein weiteres Fenster öffnet, in dem dann der einzelne Aufsatz nochmal ausgewählt werden muss. Die Seitenangabe kommt dabei nicht mit.
![image](https://user-images.githubusercontent.com/57000004/148964150-f7e1220a-f84a-4921-9359-75a152bb626d.png)

**Comment by helenanebel** [comment]
Liebe @IxKo , 
es handelt sich offensichtlich um eine andere Zeitschrift, nicht um die Münchner theologische Zeitschrift. Bitte eine passende URL posten oder ein neues Issue aufmachen.
viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem sollte jetzt aber behoben sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, Translator bricht nicht mehr ab.
