### ISSUE TITLE
Batch-Translator für Single-Download anpassen

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1647]
Der Batch-Translator soll so angepasst werden, dass beim Export aus Zotero, falls nur ein Datensatz exportiert wird, der Export zu dem Single-Translators analog ist, bei mehreren Datensätzen der des Batch-Exports.
Dadurch soll der Single-Export durch einen eigenen Translator obsolet werden.

**Comment by helenanebel** [comment]
Lieber @socheres ,
ich habe das angepasst, wenn Sie vorher den letzten Pull Request mergen, der auch den Batch-Translator betrifft, kann ich das ebenfalls pushen.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Liebe @helenanebel, habe den letzten PR gemergt und die Translators aktualisiert.

**Comment by helenanebel** [comment]
Lieber @socheres , liebe @IxKo ,
die Nicht-ASCII-Zeichen müssten jetzt auch beim Single-Export korrekt rüberkommen.
Viele Grüße, Helena Nebel
