### ISSUE TITLE
Fehlermeldung provozieren beim Upload in die WinIBW

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1648]
Falls in 5056 kein SSG-Kennzeichen gesetzt wird, die Sprache oder die PPN des übergeordneten Werkes fehlen, soll im Export-Skript sowohl für Single- als auch für Batch-Export eine Fehlermeldung für die WinIBW provoziert werden.
Für den Batch-Export kann ein Fehlermeldungsfenster implementiert werden, für den Single-Export ein ungültiges Feld mit der entsprechenden Information, das beim Abspeichern des Datensatzes zu einer Fehlermeldung führt.
Ich kümmere mich darum; zur Kenntnisnahme: @IxKo , @socheres

**Comment by helenanebel** [comment]
Liebe @IxKo , 
jetzt erscheint jedesmal eine Warnung bzw. es werden beim Single-Export Felder generiert, die eine ungültige Feldnummer haben und eine Angabe zum fehlenden Feld enthalten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Vielen Dank!

Im Hinblick auf eine zukünftige neue Mapping-Liste für selektiv auszuwertende Zss, müsste die Fehlermeldung dann ausgehebelt werden.

Bei selektiv soll das Feld 5056 fehlen und als zusätzliches Abrufzeichen wird NABZ vergeben.
