### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1650]
**URL**
https://jeac.de/ojs/index.php/jeac/article/view/831
https://jeac.de/ojs/index.php/jeac/article/view/844

**Import-Translator**
  ubtue_Open Journal Systems Standard.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Die vorhandene ORCID auf der Artikel-Seite wird nicht nach Zotero übertragen.

**Comment by helenanebel** [comment]
Liebe @IxKo , 

bei mir funktioniert hier alles reibungslos und die ORCID kommt auch mit.
Ich weiß deshalb nicht genau, was das Problem ist.
@socheres , könnten Sie bitte die Translator bei IxKo nochmal updaten?

Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,

ich habe noch Abstracts entfernt, die nur aus ", " bestehen.

Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert nun alles!
