### ISSUE TITLE
Zusammenführung von Pica-Export-Translators Batch und Single

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1652]
@helenanebel 
Danke! Ja, der Batch-Translator verhält sich bei einem einzelnen Datensatz nun wie der Single.
Eine Anpassung des Single-Translators wäre also nicht mehr notwendig.
Das muss allerdings noch mit **anderen Katalogisierenden** geklärt werden und ich weiß noch nicht wie sich das auf **Kooperationspartner** bzw. deren genutzten Export-Translator auswirkt.
Dieses Thema muss wie viele andere dann nächstes Jahr besprochen werden oder ihr klärt es nächsten Montag :-) Ich setze es schonmal auf "for meeting discussion".

_Originally posted by @IxKo in https://github.com/ubtue/DatenProbleme/issues/1636#issuecomment-996850972_

**Comment by IxKo** [comment]
Ich habe gerade ein kleines Problemchen festgestellt:
Wenn ich diesen Aufsatz http://journals.openedition.org/zjr/1964 mit dem Batch-Translator als Single exportiere, dann werden die Umlaute nicht korrekt "übersetzt":
Bspw. in den Schlagwörtern:
5520 |s|Materialit\u00e4t
5520 |s|Religion und Popul\u00e4rkultur
(Aber auch z.B. im Abstract)

**Comment by socheres** [comment]
https://github.com/socheres/Zoterobearbeitung/pull/50/commits/083f3864869858498ccace784ef478dbcde64110

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres ,
könnten Sie dann bitte nach dem Merge den zuständigen Personen mitteilen, dass der Batch-Translator jetzt auch Single exportiert? Danach könnte man dann die jeweiligen Single-Translator entfernen, das erleichtert auch die Updates.

**Comment by IxKo** [comment]
Die Zeichen-Problematik ist nun behoben. Danke!

**Comment by IxKo** [comment]
Es gibt doch noch ein kleines Problem mit den Zeichen:
![image](https://user-images.githubusercontent.com/57000004/149944189-ba86c61a-cc98-4d5a-8f29-af2c54affbf3.png)

https://onlinelibrary.wiley.com/doi/abs/10.1111/erev.12609

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Anführungszeichen dürften jetzt nicht mehr maskiert werden!
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Gelöst, danke!

**Comment by IxKo** [comment]
@socheres 
Ist der Export-Translator auch für alle anderen Katalogisierenden (Frau Eg., Frau Des., Herr Sei.) aktualisiert worden damit ich eine Rund-Mail an sie senden kann?

Und sollte er vielleicht noch eine Namensänderung in Zotero erhalten, z. B. einfach nur PicaK10plus ? Da er nun sowohl Batch als auch Single kann?

**Comment by socheres** [comment]
Ja. Es werden immer alle Dateien auf einmal aktualisiert. Hier die Ordner, die aktualisiert werden:

/Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_eg/translators  /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_km/translators  /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_ko/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_alb/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_tss/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_mz/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_neb/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_des/translators /Volumes/ZE020110/Fachinformationsdienste/Zoterobearbeitung/zotero_ikr/translators  /Volumes/ZE020110/FID-Projekte/Zoterobearbeitung/zotero_schwal /Volumes/ZE020110/FID-Projekte/Zoterobearbeitung/zotero_albr

Andere Fragen sollten wir dann in der Zotaut-Sitzung klären.

**Comment by IxKo** [comment]
Die selektiv auszuwertenden Zss sollten ebenfalls Berücksichtigung finden, sodass der Export-Translator für das selektive Verfahren nicht mehr nötig ist.
Ich habe bereits in [zotero-enhancement-maps](https://github.com/ubtue/zotero-enhancement-maps)/ISSN_to_SSG_zotkat.map alle ISSNs eingetragen in der Form ISSN=NABZ

**Comment by IxKo** [comment]
@socheres Ich habe in die [zotero-enhancement-maps](https://github.com/ubtue/zotero-enhancement-maps)/ISSN_to_Abrufzeichen_zotkat.map BILDI- und KALDI-Zss eingetragen. 
Mit 2518-4628=BILDI # Neotestamentica habe ich getestet und es wird weder der Sammlungscode noch die korrekten Abrufzeichen erzeugt.

**Comment by socheres** [comment]
> @socheres Ich habe in die [zotero-enhancement-maps](https://github.com/ubtue/zotero-enhancement-maps)/ISSN_to_Abrufzeichen_zotkat.map BILDI- und KALDI-Zss eingetragen.
> Mit 2518-4628=BILDI # Neotestamentica habe ich getestet und es wird weder der Sammlungscode noch die korrekten Abrufzeichen erzeugt.

Liebe @helenanebel, dies ist im Skript noch nicht umgesetzt. Würden Sie es übernehmen? Danke.

**Comment by helenanebel** [comment]
Lieber @socheres ,
ich bin gerade dabei.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
sobald gemergt wurde, wird dann auch NABZ gesetzt.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Merge ist abgeschlossen. Kann nun getestet werden.

**Comment by IxKo** [comment]
Es scheint nun alles wie gewünscht zu funktionieren, danke.

**Comment by IxKo** [comment]
Ich hoffe am Montag. Setze es auf Meeting-Discussion, um zu fragen, ob diesen neuen tollen Export-Translator nun alle anderen auch nutzen dürfen.

**Comment by IxKo** [comment]
> Ich hoffe am Montag. Setze es auf Meeting-Discussion, um zu fragen, ob diesen neuen tollen Export-Translator nun alle anderen auch nutzen dürfen - einschließlich Innsbruck.

@socheres Da kommenden Montag das Meeting wohl nicht stattfinden wird: Könnten Sie die Frage eventuell hier beanworten?
Es ist relevant, da ich ab dem 7. März Herrn Trä. einlerne.

**Comment by IxKo** [comment]
Wird Herr Trä. Zotero-Ordner auch automatisch aktualisiert wie die anderen?

**Comment by socheres** [comment]
bitte den Dateinamen noch umbenennen in "zotero_trae". Ich nehme ihn dann in die  Aktualisierung auf.

**Comment by IxKo** [comment]
> bitte den Dateinamen noch umbenennen in "zotero_trae". Ich nehme ihn dann in die Aktualisierung auf.

Lieber @socheres, 
ich habe den Ordnernamen von "zotero_trä" in "zotero_trae" umbenannt.

**Comment by socheres** [comment]
"zotero_trae" aufgenommen und aktualisiert > ubute_pica3

**Comment by socheres** [comment]
> Ja, den zusammengeführten Pica-Export-Translator können wir zunächst intern verwenden und eine Weile noch im Live-Betrieb "testen". Im zweiten Schritt dann Mitte und Ende März dann auch Innsbruck mitteilen. Ich habe eine neue Datei "ubtue_pica3.js" mit dem Label "ubtue_Pica3.js" hochgeladen und die lokalen Verzeichnisse aktualisiert.

Liebe @IxKo, der zusammengeführte Pica-Export-Translator heißt "ubtue_Pica3.js". Die beiden anderen "PicaSWB..."-Translators werde ich dann nach der Umstellung aus den lokalen Verzeichnissen löschen.

**Comment by IxKo** [comment]
Ok, danke. Kooperationspartner aus I scheinen schon damit zu arbeiten.
