### ISSUE TITLE
ISSN 2517-4797 | Studia liturgica (SAGE) | zota-Produktionsverfahren

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1655]
**URL**
https://journals.sagepub.com/loi/stl
  
Gleiches gilt für:
ISSN 2514-0582 | The Journal of Egyptian Archaeology (SAGE)
  
**Problembeschreibung**

Ich habe gestern beide Zss auf prodf=zota gesetzt, doch es gab keine Einspielungen.
Teste ich auf ub28 mit TRY RSS passiert nichts.
Aber auch bei anderen SAGE-Zss, die schon live sind, liefert TRY RSS keine Ergebnisse. 
Es scheint mir also an SAGE zu liegen.

**Comment by jriedl** [comment]
Die Fehlermeldung auf Harvester-Seite ist, dass der RSS-Typ nicht erkannt wird. Wenn man sich die ausgespielte Seite ansieht, erkennt man, dass SAGE offenbar mittlerweile eine Cloudflare-Funktionalität zur Verhinderung von DDos-Angriffen benutzt, die zunächst nicht mehr den RSS-Feed, sondern eine Webseite mit eingebettetem JS-Code ausspielt. Damit funktioniert es im Browser, aber eben nicht mehr bei nichtinteraktiven Abfragen. Gab es mit SAGE in der Vergangenheit bereits Kontakt im Bezug auf unser Harvesting, so dass wir hier vielleicht ausgenommen werden könnten?

**Comment by thefass** [comment]
m.W, hatten wir diesbzgl. noch keinen Kontakt zu Sage

**Comment by IxKo** [comment]
Die Zss sind nun eingespielt. Ich hatte vergessen die Spalte z_type auszufüllen.
Die Spalte ist relativ neu und ich hatte sie in meiner alten Zeder-Ansicht noch nicht eingeschalten. Dies fiel mir gestern bei einer ersten Einführung für IxTss auf.

Trotzdem scheint man mit TRY RSS nicht testen zu können.
