### ISSUE TITLE
ISSN 2567-9384 | Jahrbuch der Religionspädagogik (V&R) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1656]
**URL**
https://www.vr-elibrary.de/doi/book/10.13109/9783666703034
  
**Import-Translator**
  ubtue_vandenhoeck_ruprecht.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Könnte hier der Translator angepasst werden? Ein Multi-Import wird mir nicht angeboten und der Single-Import bricht ab.
Es könnte daran liegen, dass es online eine Reihe ist bzw. nicht die typische Zss-Struktur aufweist.
Im K10plus wurde die Reihe jedoch in eine Abv/Obv-Aufnahme umgewandelt. Aus diesem Grund soll nun geprüft werden, ob sie künftig mit Zotero bearbeitet werden kann (momentan wird sie manuell erfasst).

**Comment by IxKo** [comment]
Der Translator ubtue_vandehoeck_ruprecht.js bricht im Multi- und Single-Import ab.
![image](https://user-images.githubusercontent.com/57000004/151556039-e6d90259-f379-4ffe-94a4-64862a72d5e5.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
eigentlich dürfte das nicht passieren. Ich habe meine Änderungen nochmal gepusht.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Probleme bestehen weiterhin.
Außerdem stellt er den einen Titel seltsam dar:
![image](https://user-images.githubusercontent.com/57000004/153004263-f210dd80-c159-44dc-85c9-9fa431356dff.png)

**Comment by IxKo** [comment]
Klappt nun alles wunderbar. Vielen Dank!

**Comment by IxKo** [comment]
Klappt nun schon sehr gut.

Nur bei einem Autor hatte der Import ein Problem mit dem Buchstaben č :
![image](https://user-images.githubusercontent.com/57000004/158547009-15d371bb-0e04-4508-ab6e-d50dec5f5014.png)

**Comment by helenanebel** [comment]
Liebe @IxKo,
ja, leider hat der RIS-Import-Translator, der da intern verwendet wird, so seine Probleme mit Sonderzeichen.
Ich habe nun eingebaut, dass zusätzlich das BibTex heruntergeladen wird, da dieses die Zeichen korrekt widergibt.
Dadurch dauert der Download jetzt einige Zeit.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun passt es
