### ISSUE TITLE
ISSN 0082-7118 | Tyndale bulletin | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1657]
**URL**
Heft: https://tyndalebulletin.org/issue/3567
Aufsatz: https://tyndalebulletin.org/article/27746-show-me-the-money-jesus-visual-aids-and-the-tribute-question
  
**Import-Translator**
  Getestet im Einzel-Import mit Embedded Metadata
  
**Problembeschreibung**
Die Zs wird momentan über E/A erfasst und ist dort nicht aktuell. Zudem möchte unser Kooperationspartner die Zs erfassen, der keinen Zugriff auf E/A hat.
Auf der Herausgeber-Seite konnte ich im Einzel-Import mit dem Translator Embedded Metadata bereits gute Daten gewinnen (es fehlen nur die ISSN sowie die angezeigten Keywords und das Abstract (letzteres ist als Popup-Fenster in der Heft-Übersicht abrufbar)).

Könnte hier eventuell ein neuer Translator geschrieben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe einen Translator geschrieben. Leider ist ein Multi-DL nicht möglich, da die Artikel-URLs nicht im Seitenquelltext enthalten sind.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
@helenanebel Danke, der Einzel-Import mit dem Translator TyndaleBulletin funktioniert gut.
Einen ubtue_ Translator gibt es nicht, oder? Zumindest wird mir keiner angeboten.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
es gibt keinen "allgemeinen" Translator, deshalb habe ich diesen nicht ubtue_ genannt.
@socheres , sollte dieser trotzdem umbenannt werden?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
> @socheres , sollte dieser trotzdem umbenannt werden?
Nein. Das kann so bleiben.

**Comment by IxKo** [comment]
Ok, danke für die Info.

**Comment by IxKo** [comment]
Der Translator gibt nun nach einer längeren Wartezeit einen Fehler aus:
![image](https://user-images.githubusercontent.com/57000004/165478631-e7eb7a6b-ef5d-43f0-8f6c-e04bea01d993.png)

Der Artikel ist dann trotzdem nach Zotero importiert. 
https://tyndalebulletin.org/article/29031-the-oath-formulas-of-matthew-23-16-22-as-evidence-for-a-pre-70-date-of-composition-for-matthew-s-gospel

Könnte das eventuell behoben werden? @helenanebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich kann den Fehler nicht reproduzieren, bei mir funktioniert es ohne Probleme.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Liebe @helenanebel,
ich auch nicht mehr! Zum Glück beweist der Screenshot, dass es ihn zumindest mal gab..
