### ISSUE TITLE
ISSN 2353-4877 | Ecumeny and law (CEEOL) | KF statt LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1658]
**URL**
https://www.ceeol.com/search/journal-detail?id=60
  
**Import-Translator**
  Central and Eastern European Online Library Journals.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Die Zs-Aufsätze sind nach Registrierung kostenlos 
Die [ ISSN_to_licence.map ](https://github.com/ubtue/zotero-enhancement-maps/blob/c594a6fdeb64bbbe23eb056807ab5f42ddd57be6/ISSN_to_licence.map) sollte daher um den Wert KF (=Kostenfrei zugänglich nach Registrierung) erweitert werden.

Die Zs wird vom Koop-Partner KALDI erschlossen.

**Comment by IxKo** [comment]
Gleiches gilt für die ISSN 2451-2141 | Zs Philosophy and Canon Law

**Comment by IxKo** [comment]
In Zeder sollte dieser Wert evtl. auch hinterlegbar sein. Hier geht momentan nur ZZ, LF oder KW

**Comment by thefass** [comment]
DAs kann ich veranlassen. Wenn wir schon ändern: gibt es noch andere Werte, die in die Spalte oacc?
Was bedeutet der Wert KF?

**Comment by thefass** [comment]
Sehe ich erst jetzt: KF == Kostenfrei zugänglich nach Registrierung

**Comment by socheres** [comment]
CCEOL ist zugänglich nur innerhalb DE (Nationallizenzen) und bevor man da was ändert, sollten beide vorangegangenen issues mit berücksichtigt werden, vor allem die Funktion von JOP: https://github.com/ubtue/DatenProbleme/issues/998 und https://github.com/ubtue/DatenProbleme/issues/979

**Comment by IxKo** [comment]
Ich würde hier nochmal zurückrudern wollen (wobei man solche Fälle in Zukunft nicht ausschließen kann):

Scheinbar gibt es eine weitere Plattform, auf der die Zs mit DOI seit 2019 geführt wird und dort muss man sich nicht erst registrieren:
https://www.journals.us.edu.pl/index.php/EL/issue/archive

Die Seite ist noch nicht als Quelle aufgeführt. Ich werde es Frau Schil. melden.
Diese Quelle sollte dann auch zukünftig als Katalogisierungsquelle für Zotero genutzt werden. 
@socheres: Mir wird hier kein Mehrfach-Import angeboten und beim Einzel-Import fehlt die ORCID-Information.

Für die andere Zs "Philosophy and Canon Law" (ISSN 2451-2141) scheint es seit 2019 eine OJS Plattform zu geben, die auch noch nicht in der ZDB eingetragen ist: https://www.journals.us.edu.pl/index.php/pcl/issue/archive
@socheres: Hier wird mir der ubtue_Open Journal Systems Multi-Wrapper.js angeboten. Die ORCID kommt aber nicht mit.

Ich gebe Innsbruck Bescheid.

**Comment by socheres** [comment]
KF-Fälle sind dynamisch, wie man in diesem Beispiel sehen kann; D.h. sie können sich je nach Quelle jederzeit ändern, weshalb es am Besten ist, die Lizenzanzeige bzw. Abfrage über JOP durchzuführen. Sonst müssen wir immer im Auge behalten, ob sich die Lizenzinfo geändert hat und dementsprechend auch den Datensatz in der Datenbank updaten. @IxKo Was die beiden Translators-Anpassungen angeht, legen Sie bitte ein separates Issue an.

**Comment by IxKo** [comment]
> KF-Fälle sind dynamisch, wie man in diesem Beispiel sehen kann; D.h. sie können sich je nach Quelle jederzeit ändern, weshalb es am Besten ist, die Lizenzanzeige bzw. Abfrage über JOP durchzuführen. Sonst müssen wir immer im Auge behalten, ob sich die Lizenzinfo geändert hat und dementsprechend auch den Datensatz in der Datenbank updaten. @IxKo Was die beiden Translators-Anpassungen angeht, legen Sie bitte ein separates Issue an.

Das ist abhängig von der Quelle bzw. URL. In diesen Beispielen ist die Quelle CEEOL und hier trifft KF zu. Auch an der Gesamtaufnahme der Zs ist für die CEEOL-Quelle die Lizenz KF hinterlegt.
Die neue Quelle, über die wir nun zukünftig die Aufsätze katalogisieren sollten, ist hingegen LF. Weshalb nun KF vorerst nicht gebraucht wird - es ist allerdings für die Zukunft nicht auszuschließen.

Die Mapping-Liste, über die wir solche Angaben steuern, ist sehr statisch und setzt eine gleichbleibende Katalogisierungsquelle voraus, von der zu einem Zeitpunkt x die Information in der Liste hinterlegt worden ist und die dann alle Aufsätze der Zs betreffen.
Bisher deckt die Mapping-Liste auch nur reine LF-Zss ab. Alles andere wird mit ZZ katalogisiert - außer der Translator ist soweit angepasst, dass er einzelne OA-Artikel erkennt.

Wenn Sie eine Idee haben, wie über JOP die Lizenzangabe beim Katalogisieren automatisch generiert werden könnte, wäre das hilfreich.
Ansonsten möchte ich festhalten, dass wir in erster Linie in den K10plus-Verbund katalogisieren. Auch andere Bibliotheken dürfen unsere Katalogisate nachnutzen. Dafür ist der K10plus gedacht. Daher sollten auch keine falschen Informationen von uns katalogisiert werden. 
Was wir nachträglich mit dem "Grunddaten" aus dem K10plus im IxTheo-System machen, ist eine ganz andere Sache.
