### ISSUE TITLE
XXXX-XXXX | The Journal of Gods and Monsters | Katalogisierung ohne ISSN

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1659]
**URL**
https://godsandmonsters-ojs-txstate.tdl.org/godsandmonsters/index.php/godsandmonsters/index
  
**Import-Translator**
  ubtue_Open Journals System Standard.js
  (Einzel- und Mehrfach-Import)
  Mehrfach-Import
**Problembeschreibung**
Die Zeitschrift hat keine ISSN. Kann ich sie über eine fingierte ISSN herunterladen, z.B. XXXX-XXXX oder 0000-0000 herunterladen?

**Comment by socheres** [comment]
Liebe @IxKo, wäre es ausreichend, Publikationstitel hier einzutragen? https://github.com/ubtue/zotero-enhancement-maps/blob/master/publication_title_to_physical_form.map

**Comment by IxKo** [comment]
Es gibt nur wenige Mapping-Listen, die über den Publikationstitel gesteuert werden: **physische Form** und **PPN**. 

Es würden dann die Zuordnung zur **SSG** fehlen (was dann zu einer Fehlermeldung führt) und auch die **Lizenz**-Information LF bei dieser Zs (=OA-Zs) würde fehlen.
Ersteres führt beim BatchUpload zu dieser Fehlermeldung:
![image](https://user-images.githubusercontent.com/57000004/150746386-1b3c9da0-72e0-403c-ba3e-de45ec8295b6.png)


Hier nebensächlich: Es gibt auch keine Liste für die **Sprache**.

**Comment by RelBibRetroKat** [comment]
Ich habe die Zeitschrift jetzt mit fingierter ISSN 0000-0000 katalogisiert und dies in Zeder vermerkt. Muss dies noch irgendwo anders festgehalten werden?

**Comment by IxKo** [comment]
> Ich habe die Zeitschrift jetzt mit fingierter ISSN 0000-0000 katalogisiert und dies in Zeder vermerkt. Muss dies noch irgendwo anders festgehalten werden?

An diese Idee hatte ich auch gedacht. Aber dann muss man manuell in Zotero in jeden Datensatz erst die fingierte ISSN eintragen.
Eine Liste fingierter ISSN sollte zusätzlich angelegt werden, um zu wissen, welche fingierten ISSNs bereits für welche Zs vergeben sind. Vielleicht kann man hier eine einfache Text-Datei bei den Mapping-Listen ergänzen.

@socheres 
Komfortabler wäre es, wenn für solche Fälle auch passende Mapping-Listen zur Verfügung gestellt werden könnten.

**Comment by socheres** [comment]
Danke fürs Mitdenken. In Zotkat haben die Werte in "ISSN_to_xxx" den Datentyp "string", also Zeichenkette. D.h. es muss nicht unbedingt eine numerische Zahl als Wert hinterlegt werden. Wichtig ist, dass der in der Mapping-Liste eingetragene Wert mit dem des ISSN-Feldes in Zotero übereinstimmt. In diesem Fall kann ich den Translator so anpassen, dass der Publikationstitel dieser Zeitschrift ins Zotero-ISSN-Feld übertragen wird. Dann bleibt das Verfahren auch wie bisher. @IxKo einverstanden?

**Comment by IxKo** [comment]
> Danke fürs Mitdenken. In Zotkat haben die Werte in "ISSN_to_xxx" den Datentyp "string", also Zeichenkette. D.h. es muss nicht unbedingt eine numerische Zahl als Wert hinterlegt werden. Wichtig ist, dass der in der Mapping-Liste eingetragene Wert mit dem des ISSN-Feldes in Zotero übereinstimmt. In diesem Fall kann ich den Translator so anpassen, dass der Publikationstitel dieser Zeitschrift ins Zotero-ISSN-Feld übertragen wird. Dann bleibt das Verfahren auch wie bisher. @IxKo einverstanden?

Trotzdem müsste die/der Katalogisierende erst in Zotero bei jedem Datensatz in das Feld "ISSN" einen Wert manuell einfügen - ob das jetzt eine fingierte ISSN oder der Publikationstitel ist - ändert nichts an dem zusätzlichen Arbeitsschritt.

Und dass einfach der Wert aus dem Feld "ISSN" genügt, kann ich so nicht bestätigen.
Ich habe es Ihnen im letzten Meeting gesagt, dass bspw. bei zwei ISSN im Zotero-Feld drei Einträge in der Mapping-Liste gemacht werden **müssen** (zwei ISSN + je eine Zeile für eine der ISSN), andernfalls greift es nicht.

Ich habe zur Veranschaulichung nun in die ISSN_to_physical_form.map den Wert 100=A eingetragen.
![image](https://user-images.githubusercontent.com/57000004/150783184-ab0d85fa-caba-418d-8e63-a41b65b56821.png)

Wenn ich nun bei einem Datensatz in meinem Zotero die ISSN in 100 ändere, greift diese Mapping-Liste trotzdem nicht.

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres , liebe alle,
im Export-Translator prüft eine Funktion "cleanISSN", die prüft, ob es sich bei der übergebenen ISSN um eine ISSN handeln kann, die übergebene ISSN MUSS also eine valide ISSN sein die aus 7 Ziffern + einer Prüfziffer besteht:
Zur Berechnung der Prüfziffer wird zunächst die absteigend von 8 bis 2 gewichtete Quersumme a der ersten sieben Stellen berechnet (achtmal erste Stelle plus siebenmal zweite Stelle etc.). Die Prüfziffer p berechnet sich nun folgendermaßen:
    p = { 0 falls  a mod 11 = 0 
           11 − ( a mod 11 ) sonst}
Die Prüfziffer p = 10 wird als das Zeichen X dargestellt.
Es steckt also eine Komplexe Überprüfung dahinter, und die Tatsache, dass 0000-0000 funktioniert, ist vermutlich purer Zufall gewesen.
Falls jemand Interesse hat, kann ich das System gerne nochmal erläutern.
Wir könnten auch einen Nummernkreis mit ungültigen "IXtheo-ISSNs" festlegen und diese im Export-Translator von der Prüfung ausschließen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
"Erfundene" ISSNs sollen immer mit "IXTH" beginnen und dann eine Zahl bekommen, die noch nicht vergeben wurde. Diese ISSNs sollen nicht mit cleanISSN geprüft werden.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat , liebe @IxKo , lieber @socheres ,
ich habe jetzt als ISSN für diese ZS IXTH-0001 eingetragen und den Export-Translator entsprechend angepasst. Das funktioniert jetzt. Falls weitere ähnliche Fälle vorkommen, immer eine Zahl höher zählen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Mit der fingierten ISSN in den Mapping-Listen klappt es. Ich habe, um hier die Übersicht der bereits vergebenen ISSNs zu wahren, eine Datei "Übersicht fingierte ISSNs IXTH-####" angelegt: 
https://github.com/ubtue/zotero-enhancement-maps/blob/0bf921c54c30a42f9ea2749dbb72ac0a4e30eaad/%C3%9Cbersicht%20fingierte%20ISSNs%20IXTH-%23%23%23%23
Übersicht fingierte ISSNs IXTH-####

Was noch nicht klappt: Die fingierte ISSN wird beim Import nicht nach Zotero übertragen, man muss sie also manuell in die Felder eintragen und hier ist Zotero leider nicht benutzerfreundlich. Es ist nicht möglich einen gleichen Wert bei mehreren Datensätzen gleichzeitig zu bearbeiten, sondern es muss für jede Zeile einzeln vorgenommen werden. 

War es denn so gedacht, dass die fingierte ISSN direkt mit importiert wird?

**Comment by helenanebel** [comment]
Liebe @IxKo , falls eine fingierte ISSN für eine spezifische ZS eingetragen werden soll, dann sollte das jeweils dafür angefordert werden. Ich ändere den Translator für diese ZS dann entsprechend. Für "The Journal of Gods and Monsters" werde ich den Translator entsprechend anpassen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
> Liebe @IxKo , falls eine fingierte ISSN für eine spezifische ZS eingetragen werden soll, dann sollte das jeweils dafür angefordert werden. Ich ändere den Translator für diese ZS dann entsprechend. Für "The Journal of Gods and Monsters" werde ich den Translator entsprechend anpassen. Viele Grüße, Helena Nebel

Okay, danke für den Hinweis. Ich notiere es mal in der Liste der fingierten ISSNs.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das ist glaube ich schon getestet, kann das geschlossen werden?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Funktioniert mit der fingierten ISSN. Danke!
