### ISSUE TITLE
ISSN 1548-1352 | Ethos (Wiley) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1661]
**URL**
https://anthrosource.onlinelibrary.wiley.com/doi/full/10.1111/etho.12311
 773D1891FE1E3FF561C5B67B85E6E19F4572187F

**Import-Translator**
  ubtue_Wiley Online Library.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Die ORCID-Information wird nicht importiert.
Fehlt auch beim Test auf ub28

![image](https://user-images.githubusercontent.com/57000004/150540125-ba9f9e40-4b4b-4564-b3f4-187c4c3ec46e.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ist das jetzt für zota oder zotk? Das ub28 verwirrt mich.

**Comment by IxKo** [comment]
@helenanebel Im Grunde für beide Verfahren. Die Zs ist live zota. Diesen Aufsatz musste ich allerdings manuell erfassen, weil er in den Errors aufgrund fehlender Seitenangabe gelandet ist.

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres , die ORCID steht in diesem Fall einfach im Text des Artikels, auch eine Zuordnung zum Autor ist nicht gegeben:
![grafik](https://user-images.githubusercontent.com/49190455/155974908-44cb2d2d-be2e-4947-98a9-388b203679a0.png)
Ich würde das nicht in einen Translator übernehmen, weil nie klar wäre, worauf sich eine solche ORCID, die irgendwo im Text vorkommt, bezieht.
Was meinen Sie dazu?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
`ul class="rlist sm-account` ist innerhalb von eindeutigen `div class="author-info accordion-tabbed__content" data-db-target-of="a1" aria-labelledby="a1_Ctrl" role="region" id="a1"`, daher sollte m.W. bei mehr als eine ORCID-ID die Zuordnung zum Autor möglich sein. 
```
<div class="author-info accordion-tabbed__content" data-db-target-of="a1" aria-labelledby="a1_Ctrl" role="region" id="a1">
                     <p class="author-type mb-1">Corresponding Author</p>
                     <p class="author-name">Gil Hizi</p>
                     <ul class="rlist sm-account">
                        <li class="sm-account__item"><a class="sm-account__link" title="Link to email address" href="mailto:ghizi@uni-koeln.de"><i aria-hidden="true" class="icon-ic_mail_solid"></i><span>ghizi@uni-koeln.de</span></a></li>
                     </ul>
                     <ul class="rlist sm-account">
                        <li class="sm-account__item"><a target="_blank" class="sm-account__link" href="https://orcid.org/0000-0001-7567-0875"><i aria-hidden="true" class="icon-orcid"></i><span>orcid.org/0000-0001-7567-0875</span></a></li>
                     </ul>
                     <p>Universität zu Köln</p>
                     <p>email: <a class="corr-email" title="Link to email address" href="mailto:ghizi@uni-koeln.de"><span>ghizi@uni-koeln.de</span></a></p><a class="moreInfoLink" href="/action/doSearch?ContribAuthorRaw=Hizi%2C+Gil">Search for more papers by this author</a></div>
```

**Comment by helenanebel** [comment]
Lieber @socheres ,
im Seitenquelltext des von IxKo angegebenen Artikel finde ich im Seitenquelltext genau eine ORCID, diese steht im Text, wie ich es oben angegeben habe. Könnten Sie mir bitte für diesen Artikel ebenfalls sagen, wo ich die ORCID in strukturierter Form finden kann?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Ok. Es geht um den ersten Link. Hier könnte man so vorgehen, dass wenn es nur einen Autor gibt, die ORCID aus dem Text übernommen wird, bei mehr als einem Autor keine Übernahme. Wenn diese Fälle nicht häufiger vorkommen, dann tendiere ich eher dazu, sie nicht zu übernehmen.

**Comment by helenanebel** [comment]
Lieber @socheres ,
das Problem ist, dass auch in diesem Fall eigentlich nicht sichergestellt ist, dass sich die ORCID auf den*die Autor*in bezieht, sie könnte sich z.B. auch auf den*die Autor*in des rezensierten Werkes o.ä. beziehen. Deshalb würde ich persönlich sie in diesem Fall gar nicht übernehmen, falls @IxKo mir da zustimmt. Sie hatte ja oben auch geschrieben, dass das ein Sonderfall ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Da es sich hier um einen Sonderfall handelte und eine eindeutige Zuordnung nicht gewiss ist, würde ich auch sagen, dass wir hier auf die ORCID-Information verzichten.
Ich schließe daher.
