### ISSUE TITLE
Export-Translator |f| Book Reviews

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1662]
**URL**
https://anthrosource.onlinelibrary.wiley.com/doi/full/10.1111/etho.12311
  
**Import-Translator**
  ubtue_Wiley Online Library.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Es wird beim Import ein Tag "Book Review" erzeugt. Beim Export wird dieses seltsamer in 5520 |f|Book Review*s* (Mehrzahl) umgewandelt und es wird kein 1131 erzeugt.
Es sollte besser das Tag "RezensionstagPica" erzeugt werden, dass beim Export in 1131 !Rezension! umgewandelt wird.

Mir fiel das in der Vergangenheit auch schon mal an anderer Stelle auf.
Es sollten alle Translators dahingehend mal überprüft werden.

**Comment by IxKo** [comment]
Das Tag Book Review wird nun als 1131 !Rezension! und zusätzlich als 5520 |f|Book Review erfasst.
Letzteres sollte entfernt werden, bzw. : 

> Es sollte besser das Tag "RezensionstagPica" erzeugt werden, [...] 

Wenn ich als Katalogisierende erkenne, dass es sich um eine Rezension handelt, würde ich das RezensionstagPica ergänzen, was dann zu 2x 1131 führt. Mit 5520 |f| ist es dann dreifach gekennzeichnet.

**Comment by socheres** [comment]
1131 !Rezension! wird nun nur beim Tag "RezensionstagPica" erzeugt.

**Comment by IxKo** [comment]
Es ist eine Rezension und sollte daher 1131 !Rezension! erhalten.
Es wird sogar unter "Book Reviews" geführt und hat keinen eigenständigen Titel:
![image](https://user-images.githubusercontent.com/57000004/153009715-87bd9263-5144-47d5-a94d-92504d453238.png)

> Es sollte besser das Tag "RezensionstagPica" erzeugt werden, dass beim Export in 1131 !Rezension! umgewandelt wird.

**Comment by IxKo** [comment]
Danke, passt!
