### ISSUE TITLE
2183-2803 | Social Inclusion (Cogitatio Press)  | Abstract wird nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1663]
[**URL**](https://www.cogitatiopress.com/socialinclusion/index)

  
**Import-Translator**
  ubtue_Open Journal Systems Multi Wrapper.js
  (
![Social Inclucion](https://user-images.githubusercontent.com/51993589/151143393-d4e45ef7-1dd9-444a-a8d1-5e0e7fc1e48f.jpg)
Mehrfach-Import)
  
Wie im Screen Shot ersichtlich werden einige Artikel mit Titel im Zotero-Download angezeigt. Diese sind für alle Hefte (vom ersten Jahrgang bis zu den neueren) dieselben. Die Artikel des jeweiligen Heftes werden nur einmal mit "View Abstract" und nochmal mit "Download" heruntergeladen. "View Abstract" enthält dieselben Daten wie "Download" nur fehlt der DOI. Mit keinem Download kommt der Artikel mit, obwohl er auf derselben Seite steht wie die Keywords, die vollständig heruntergeladen werden.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat .
ich habe das behoben, es müsste jetzt der Translator "ubtue_Open Journal Systems Standard" angeboten werden, dieser zeigt die richtigen Artikel an.
Den Multi-Wrapper verwenden wir eigentlich nicht mehr, @socheres , ich denke, es wäre sinnvoll, diesen zu löschen.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
> Den Multi-Wrapper verwenden wir eigentlich nicht mehr, @socheres , ich denke, es wäre sinnvoll, diesen zu löschen.
gelöscht.

**Comment by socheres** [comment]
@IxKo bitte auch BILDI mitteilen.

**Comment by RelBibRetroKat** [comment]
Mehrfachdownload jetzt problemlos. Vielen Dank für die Verbesserungen.
