### ISSUE TITLE
DAKAR-Kooperation (IKR Export-Skripte) | Anpassung nach der Schulung vom 27.1.2022

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1664]
**Export-Translator**
ikr_batch_amtsblatt
ikr_batch_artikel

**Problembeschreibung**
- [x]  wenn das 30xx-Feld | 4241-Feld (Verknüpfung zum ÜW) keine PPN-Nummer, sondern Buchstaben enthält, dann ohne Anführungszeichen exportieren
- [x] 7100 nur einmal exportieren und Leerzeile vor Dollar-Zeichen `7100 $Jn`
- [x] 67xx unterhalb des Exemplardatensatzes exportieren 
- [x] 1131 !106186019! exportieren, wenn der Titel wie folgt anfängt `[Rezension von..`

**Comment by socheres** [comment]
Liebe @IxKo, würden Sie bitte die Anpassungen testen. Bei mir hat alles gut funktioniert.
Außerdem bei Rezensionen muss die Anleitung "01 - Anleitung 1 - Zotero Group.pdf" auf der Seite 6 etwas präzisiert werden:

> c)  Alle anderen Felder (inkl. ISSN) analog zu denen bei den Aufsätzen.

Änderungsvorschlag:

> c) ISSN - hier wird die PPN des übergeordneten Werks (Zeitschrift) eingetragen.

**Comment by IxKo** [comment]
### **ikr_batch_amtsblatt**

Alle bekannten Fehler bestehen bei mir weiterhin:
1. **6700**er Felder werden weiterhin über dem Exemplarsatz exportiert (was zu einer Fehlermeldung führt).
2. **7100** wird weiterhin doppelt und über dem Exemplarsatz erzeugt (was zu einer Fehlermeldung führt).

**_Beispielfall 2:_**
![image](https://user-images.githubusercontent.com/57000004/152153209-a7b50733-85e9-4574-872f-a94eee846704.png)
![image](https://user-images.githubusercontent.com/57000004/152153320-cffcfcc4-30d6-435e-9889-6e60bde5c28e.png)

**Comment by socheres** [comment]
Die Translator auf ihrem lokalen Verzeichnis waren nicht auf dem neuesten Stand, obwohl ich sie eigentlich aktualisiert hatte. Wie auch immer, testen Sie bitte erneut. Danke.

**Comment by socheres** [comment]
Liebe @IxKo, habe nun die Erstetzen-Funktion für die Formschlagwörter `#n` und `#r` auch gefixt. Bitte testen Sie auch dies.

**Comment by IxKo** [comment]
Bei mir taucht weiterhin der Fehler mit den Feldern 6700 und 7100 über dem Exemplarsatz auf:

![image](https://user-images.githubusercontent.com/57000004/152360908-1a4b224f-a461-4f06-af23-3feb8c5f9129.png)

**Comment by IxKo** [comment]
> abe nun die Erstetzen-Funktion für die Formschlagwört

Bei `#N` wird nun 5520 |f|Norm$ADE-Tue135-3/21-fid1-DAKR-MSZK erzeugt und
bei `#R `wird nun 5520 |f|Rechtsprechung$ADE-Tue135-3/21-fid1-DAKR-MSZK erzeugt.

**Comment by socheres** [comment]
> Bei mir taucht weiterhin der Fehler mit den Feldern 6700 und 7100 über dem Exemplarsatz auf:
> 
Sorry. Jetzt müsste das Problem nicht mehr auftauchen.
ikr_batch_amtsblatt.js
![image](https://user-images.githubusercontent.com/1545743/152385806-213ff7ae-922b-4359-825c-ffdf1d3083c7.png)

ikr_batch_artikel.js
![image](https://user-images.githubusercontent.com/1545743/152385917-b89c5ecb-86e8-4ae7-9a80-a9495b2978ed.png)

**Comment by thefass** [comment]
> Bei `#N` wird nun 5520 |f|Norm$ADE-Tue135-3/21-fid1-DAKR-MSZK erzeugt und
> bei `#R `wird nun 5520 |f|Rechtsprechung$ADE-Tue135-3/21-fid1-DAKR-MSZK erzeugt.

Bitte auf dem Schirm haben, dass das dann jährlich angepaßt wird. 22 >>23
müßte eigentlich jetzt schon 22 sein

**Comment by IxKo** [comment]
- [X] Die Problematik mit 7100 und 6700 ist behoben.

- [ ] Bei der KNA müssen die Felder hinsichtlich O-Aufnahmen angepasst werden:
0500 Osn, 0501 Text$btxt, 0502 Computermedien$bc, 0503 Online-Ressource$bcr

- [ ] Bei 5580 und 5520 muss das Jahr hochgezählt werden (s. vorheriges Kommentar von thefass).

- [ ] Ich konnte bis eben noch mit LogIn Münster testen. Nun erscheint aber folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/57000004/152498379-882d48f1-1924-450e-ba37-be0f9589632c.png)

**Comment by socheres** [comment]
Das Jahr wird automatisch hochgezählt.

**Comment by IxKo** [comment]
KNA-Artikel werden nun als O-Aufnahmen erstellt.
Das Jahr bei den Feldern 5580 und 5520 gibt nun Jahr 22 an.

Bei ikr_batch_artikel wird weiterhin die ISSN in 4241 angegeben, was keiner PPN entspricht und zu eienr Fehlermeldung in der WinIBW führt.
Bsp.:  \n4241 Enthalten in!0947-8094! ausgegeben

**Comment by socheres** [comment]
Nach der Anleitung werden KNA-Artikel mit "ikr_batch_amtsblatt.js" exportiert.

**Comment by socheres** [comment]
> Beim **ikr_batch_artikel** wird weiterhin die ISSN in 4241 angegeben, was keiner PPN entspricht und zu einer Fehlermeldung in der WinIBW führt. Bsp.: \n4241 Enthalten in!0947-8094!

Hier die Beispiele für Zeitschriftenaufsatz und Rezension:
 
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Asn\n0501 Text$btxt\n0502 ohne Hilfsmittel zu benutzen$bn\n0503 Band$bnc\n0575 DAKR\n1100 2021\n1500 ger\n1505 $erda\n3000 Oberverwaltungsgericht L\u00fcneburg$BVerfasserIn$4aut\n4000 Zur Ber\u00fccksichtigung des Gleichheitsgrundsatzes bei der Erhebung eines besonderen Kirchgeldes, 10 LA 38/20\n4070 $v27$j2021$a1$p149\n4241 Enthalten in!186450966!\n5056 1\n5520 |f|Rechtsprechung$ADE-Tue135-3/22-fid1-DAKR-MSZK\n5580 !106096745!\n5580 !241913497!\n5580 $ADE-Tue135-3/22-fid1-DAKR-MSZK\nE* l01 \n6700 !1442053283!\n6701 !1442053313!\n7100 $Jn\n8012 mszk");
application.activeWindow.pressButton("Enter");

application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Asn\n0501 Text$btxt\n0502 ohne Hilfsmittel zu benutzen$bn\n0503 Band$bnc\n0575 DAKR\n1100 2021\n1500 ger\n1505 $erda\n3000 Oberverwaltungsgericht L\u00fcneburg$BVerfasserIn$4aut\n4000 Zur Ber\u00fccksichtigung des Gleichheitsgrundsatzes bei der Erhebung eines besonderen Kirchgeldes, 10 LA 38/20\n4070 $v27$j2021$a1$p149\n4241 Enthalten in!186450966!\n5056 1\n5520 |f|Rechtsprechung$ADE-Tue135-3/22-fid1-DAKR-MSZK\n5580 !106096745!\n5580 !241913497!\n5580 $ADE-Tue135-3/22-fid1-DAKR-MSZK\nE* l01 \n6700 !1442053283!\n6701 !1442053313!\n7100 $Jn\n8012 mszk");
application.activeWindow.pressButton("Enter");

**Comment by IxKo** [comment]
Nun werden die ISSN - sofern sie in den Mapping-Listen hinterlegt sind - korrekt umgesetzt.

@socheres Für Beiträge in Sammelwerken etc. - also keine Zss-Aufsätze - muss Frau Kle. den Export für Amtsblätter verwenden? 
In der Anleitung werden Beiträge in Sammelwerken/Reihen erwähnt. Und hier soll anders als bei Zss-Aufsätzen die PPN des übergeordneten Werkes in das Feld Publikation geschrieben werden.

**Comment by socheres** [comment]
https://github.com/socheres/Zoterobearbeitung/commit/644b0b8b6d5d0b5da9ab674fa2733ec0f031d0a9

**Comment by socheres** [comment]
@IxKo wie eben per Zoom gesprochen, habe ich bis auf "KNA" und "Kirchen- und Staatskirchenrecht" in den Code aufgenommen. Ein neuer Translator "ikr.js" befindet sich nun bei allen Verzeichnissen. Bitte testen!

**Comment by IxKo** [comment]
Bei Nicht-Amtsblättern, sondern Artikeln aus Zss (mit ISSN, Publikationsfeld leer) wird die erste Person korrekt mit 3000 ausgeliefert, eine weitere Person aber mit 3110.

Weitere Tests kann ich erst morgen machen.

**Comment by socheres** [comment]
Ich habe die ISSNs bei 3010 und 3100 nachgetragen. Jetzt sollte es funktionieren. @IxKo bitte testen.

**Comment by IxKo** [comment]
Wenn eine Rezension (Magazin-Artikel) keine PPN im Feld Publikation hat, ist das das Ergebnis;
![image](https://user-images.githubusercontent.com/57000004/155685173-db1209b1-6071-42fc-96c5-5deac1b748bd.png)

**Comment by socheres** [comment]
> Bei Zss-Aufsätzen werden Personen als Körperschaften (3100, 3110) exportiert, korrekt wäre in den meisten Fällen 3000, 3010.

Mit welcher ISSN haben Sie getestet?
Bei mir werden Zeitschriftenaufsätze korrekt exportiert:

Hier das Testergebnis mit 2520-0089
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Asn\n0501 Text$btxt\n0502 ohne Hilfsmittel zu benutzen$bn\n0503 Band$bnc\n0575 DAKR\n1100 2019\n1500 ger\n1505 $erda\n3000 !704838117!$BVerfasserIn$4aut\n3010 !7048331313!$BVerfasserIn$4aut\n4000 Dies ist der erste Titel\n4070 $v56$j2019$a2$p12-16\n4241 Enthalten in!559076819!\n5056 1\nE* l01 \n7100 $Jn\n8012 mszk");
application.activeWindow.pressButton("Enter");

mit 2366-6722:
application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Asn\n0501 Text$btxt\n0502 ohne Hilfsmittel zu benutzen$bn\n0503 Band$bnc\n0575 DAKR\n1100 2019\n1500 ger\n1505 $erda\n3000 !704838117!$BVerfasserIn$4aut\n3010 !7048331313!$BVerfasserIn$4aut\n4000 Dies ist der erste Titel\n4070 $v56$j2019$a2$p12-16\n4241 Enthalten in!186450966!\n5056 1\nE* l01 \n7100 $Jn\n8012 mszk");
application.activeWindow.pressButton("Enter");

**Comment by socheres** [comment]
Bisher sind folgende ISSNs im Code eingetragen:

['2520-0089', '2366-6722', '1868-7369', '2304-4896', '0948-0471', '0034-9372', '2612-3746', '0022-6858', '2364-2416', '2450-4629', '0341-1915', '0721-880X', '0934-8603', '0943-7525', '0949-7137', '0179-7387', '2196-0119', '0514-6496', '2708-7417']

**Comment by socheres** [comment]
> Wenn eine **Rezension** (Magazin-Artikel) keine PPN im Feld Publikation hat, ist das das Ergebnis;

@IxKo Ja, das kann passieren, wenn das rezensierte Werk noch nicht in k10+ vorhanden ist(keine PPN). In einem solchen Fall könnte man beim Import in Winibw eine Fehlermeldung erzeugen mit einem Hinweis wie "bitte hier das rezensierte Werk in der Form xxx, xxx, xxx, ein".

**Comment by IxKo** [comment]
> > Wenn eine **Rezension** (Magazin-Artikel) keine PPN im Feld Publikation hat, ist das das Ergebnis;
> 
> @IxKo Ja, das kann passieren, wenn das rezensierte Werk noch nicht in k10+ vorhanden ist(keine PPN). In einem solchen Fall könnte man beim Import in Winibw eine Fehlermeldung erzeugen mit einem Hinweis wie "bitte geben Sie hier das rezensierte Werk in der Form xxx, xxx, xxx, ein".

Ist es denn obligatorisch für Münster, dass bei Rezensionen immer die PPN des rezensierten Werkes eingetragen wird?
Sonst sollte es einfach zu gar keinem Fehler führen.

**Comment by IxKo** [comment]
> 



> > Bei Zss-Aufsätzen werden Personen als Körperschaften (3100, 3110) exportiert, korrekt wäre in den meisten Fällen 3000, 3010.
> 
> Mit welcher ISSN haben Sie getestet? Bei mir werden Zeitschriftenaufsätze korrekt exportiert:
> 


Das war bei ISSN 0947-8094.

Wie wollen Sie es bei den Zss ohne ISSN (z.B. KNA) lösen?

**Comment by socheres** [comment]
0947-8094 ist ja nicht enthalten, daher wird sie in 3100 bzw. 3110 exportiert. Bei KNA siehe [hier](https://github.com/socheres/Zoterobearbeitung/blob/a6aaaeaab023ce896a57ae89f9df7a5c9bef358c/zotero_master/translators/ikr.js#L495)

**Comment by IxKo** [comment]
Ich habe mal die ganze ikr-Bibliothek nach Excel exportiert und Duplikate in der Spalte ISSN entfernt. Übrig blieben diese ISSNs:
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/qubpn01/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/qubpn01/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ISSN
--
 
0179-7387
2248-9789
1234-5432
2032-5215
0023-1827
0012-4257
0341-1915
0943-7525
0721-1937
0947-8094
1120-6462
0392-2359
0026-976
0022-6858
0034-9372
0044-2690
0948-0471
0323-4142
2196-0119
10626549
0721-880X
0946-3178



</body>

</html>

**Comment by socheres** [comment]
Folgende ISSNs sind nicht im Codeblock enthalten, die 30xx steuert. Im Codeblock sollten nur Zeitschriften aufgelistet sein. Welche der fehlenden ISSNs sollte ich hinzufügen?
2248-9789
1234-5432
2032-5215
0023-1827
0012-4257
0341-1915
0721-1937
0947-8094
1120-6462
0392-2359 Kaldi
0026-976 (sic!)
0044-2690
0323-4142
10626549
0946-3178
2032-5215 Köln
 0023-1827  (geklammert) ist ein Amtsblatt.

**Comment by IxKo** [comment]
Folgende sollten aufgenommen werden, da sie laut Zeder-Eintrag von ikr formal erschlossen werden sollen.
Die anderen habe ich entfernt.

2248-9789
1234-5432
0341-1915
0721-1937
0947-8094
1120-6462
0026-976 (sic!) -> 0026-976X da fehlte das X hinten, ist aber so in der Zotero-Group eingetragen worden
0044-2690
0323-4142
0946-3178

**Comment by socheres** [comment]
die oben erwähnte ISSNs habe ich nun hinzugefügt.

**Comment by IxKo** [comment]
Beim Prüfen der ISSNs in der Mapping-Liste ISSN_to_superior_ppn.map habe ich festgestellt, dass ISSN 1234-5432 eine Fake-ISSN ist und in der Zotero-Group für zwei Test-Daten angewendet wurde. Diese können Sie also wieder aus Ihrem Codeblock entfernen, wobei es wahrscheinlich eh keine Auswirkungen hat, wenn sie enthalten bleibt.

**Comment by IxKo** [comment]
Bei KNA wird ein:e Autor:in als 3100 exportiert, obwohl es sich nicht um ein Amtsblatt handelt.

**Comment by socheres** [comment]
30xx wird durch die ISSN-Liste im Code gesteuert. Wenn die ISSN von "Revue de droit canonique" im Code nicht vorkommt, dann wird der Wert im Autorenfeld nach 3100 exportiert.
In der Zotero Group libraries unter Freiburg > Revue de droit canonique finde ich leider keinen Beispieldatensatz, aus dem ich die ISSN entnehmen kann. Ich habe aber folgende ISSN gefunden und hinzugefügt: 0556-7378. Ist sie richtig?

Hier die ISSN-Liste:
['2520-0089', '2366-6722', '1868-7369', '2304-4896', '0948-0471', '0034-9372', '2612-3746', '0022-6858', '2364-2416', '2450-4629', '0341-1915', '0721-880X', '0934-8603', '0943-7525', '0949-7137', '0179-7387', '2196-0119', '0514-6496', '2708-7417', '2248-9789', '0341-1915', '0721-1937', '0947-8094', '1120-6462', '0026-976X', '0044-2690', '0323-4142', '0946-3178']

**Comment by IxKo** [comment]
Sollte nicht besser alles, was über ISSN gesteuert wird mit 30xx exporitert werden?

Die Amtsblätter werden - wenn ich es richtig verstehe - ja sowieso nur mittels Publikation-PPN exportiert und haben keine ISSN.
Für was ist die eigene ISSN-Liste in dem Export-Code noch relevant?

**Comment by socheres** [comment]
> Sollte nicht besser alles, was über ISSN gesteuert wird mit 30xx exporitert werden?

Ja, das ist auch der Fall. Die Autoren werden ins Feld 3000 geschrieben, wenn die ISSN bzw. wenn keine ISSN vorhanden die PPN in dieser [Liste](https://github.com/socheres/Zoterobearbeitung/blob/40ea8218c41f8a9edf9f9c80ecf1a33e452e797e/zotero_master/translators/ikr.js#L494) erscheint.

> Die Amtsblätter werden - wenn ich es richtig verstehe - ja sowieso nur mittels Publikation-PPN exportiert und haben keine ISSN. Für was ist die eigene ISSN-Liste in dem Export-Code noch relevant?

Ja, die Amtsblätter haben keine ISSN, daher werden die Autoren auch ins 3100 Feld geschrieben.

Es gibt aber auch andere PPN-[Liste](https://github.com/socheres/Zoterobearbeitung/blob/40ea8218c41f8a9edf9f9c80ecf1a33e452e797e/zotero_master/translators/ikr.js#L263) im Code für O-Aufnahmen.

**Comment by IxKo** [comment]
> In der Zotero Group libraries unter Freiburg > Revue de droit canonique finde ich leider keinen Beispieldatensatz, aus dem ich die ISSN entnehmen kann. Ich habe aber folgende ISSN gefunden und hinzugefügt: 0556-7378. @IxKo Ist sie richtig?

Ja, diese ist korrekt.

**Comment by IxKo** [comment]
Funktioniert. Ich habe die Anleitung angepasst und der Kooperationspartnerin Bescheid gegeben.
Das Issue war bereits geschlossen.
