### ISSUE TITLE
ISSN 2365-6565 | Ethik und Gesellschaft (OJS-Tue) | läuft in zotat nicht

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1665]
**URL**
https://www.ethik-und-gesellschaft.de/ojs/index.php/eug/issue/view/109/showToc
  
**Import-Translator**
  Ethik und Gesellschaft.js
  
eingetragener RSS-Feed 
https://www.ethik-und-gesellschaft.de/ojs/index.php/eug/gateway/plugin/WebFeedGatewayPlugin/rss

**Problembeschreibung**
Die Zs funktioniert auf Nu nicht - weder Try RSS noch URL.

**Comment by IxKo** [comment]
Ok, dann beobachten wir es.

**Comment by jriedl** [comment]
Anfrage an P&E - Rückmeldung: Mit der Zeitschrift besteht aktuell ein Problem, an einer Lösung wird gearbeitet.

**Comment by IxKo** [comment]
Der Webauftritt scheint gewandert zu sein.
Die aktuelle Web-Oberfläche scheint nicht Zotero-fähig, da es keine gesonderten Artikel-Seiten gibt, sondern die Artikel-Links direkt auf das PDF führen: https://open-journals.uni-tuebingen.de/ojs/index.php/eug/issue/archive

**Comment by thefass** [comment]
Ja, das stimmt. Das war/ist ein internes Problem. EuG war auf OJS 1.x, dort funktionierte irgendwann das Schnelleinreichungsplugin nicht mehr und damit das heft überhaupt publiziert werden konnte, wurden die Metadaten händisch auf die statische Startseite eingestellt. Deswegen lösen auch die DOIs nicht auf. Mittlerweile sind sie von A.B. auf OJS 3.x migriert. Nun müssen die Hefte, die nur auf der Startseite verlinkt sind, richtig ins Publikationssystem eingegeben werden. Erst dann funktioniert zotaut wieder

**Comment by thefass** [comment]
Das neueste Heft Nr. 2 (2022): Narrative der Sozialpolitik – Narrative der Sozialstaatskritik wurde jetzt wieder normal über den Redaktionsweg eingepflegt.

Nur auf der Startseite händisch eingestellt sind bisher die Hefte 1.2022 (Wohnvermögen) und 2.2021 (Friedensethik und Geopolitik). Diese müssen vom Herausgeber auch noch über den Redaktionsweg eingepflegt werden.

**Comment by IxKo** [comment]
Das neueste Heft war mit Zotero bearbeitbar.
Da Seitenzahl und DOI aus dem PDF entnommen werden müssen, ist sie vorerst nicht für zota geeignet.
