### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity (OJS-Tue) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1666]
**URL**
https://jeac.de/ojs/index.php/jeac/article/view/850
IxTheo#2022-02-01#E2F46544944859666612316458ECD1AF98DB4A48

**Problembeschreibung**
Die ORCID-Informationen werden nicht erfasst.

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres ,
wieder einmal ein typisches Beispiel dafür, wie unökonomisch es ist, Translator für verschiedene Verfahren auseinanderzuentwickeln, beim zotk-Translator war das längst implementiert.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Mit try URL wird mir auf Nu noch keine ORCID-Info angegeben.
@helenanebel  Müssen Deine Anpassungen erst durch jemand anderes umgesetzt/aktiviert werden?

**Comment by jriedl** [comment]
War ich gerade am Schreiben: Nu ist aktuell. Das Problem scheint zu sein, dass bei dieser URL der falsche Translator (Open Journal Systems anstatt  der jetzt angepasste ubtue_Open_Journal_Systems_Standard verwendet wird.

**Comment by jriedl** [comment]
Dann sollte eben die Priorität und der Match-String angepasst werden oder der Standardtranslator entfernt werden.
