### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity (OJS-Tue) | Rezension

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1667]
**URL**
https://doi.org/10.25784/jeac.v3i0.847
IxTheo#2022-02-01#A8091533B3258A46337963B041675CF5EC2851D3

**Problembeschreibung**
Rezensionen werden nicht erkannt.

**Comment by helenanebel** [comment]
Liebe @IxKo , lieber @socheres ,
Und auch dieses Feature war - mit sehr geringfügigen Unterschieden - bereits im zotk-Translator implementiert.
viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by IxKo** [comment]
Danke, wir sowohl auf Nu als auch auf ub28 als Rezension erkannt.
