### ISSUE TITLE
ISSN 2210-5956 | Journal of Sufi Studies (Brill) | Sprache

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1669]
**URL**
https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details
35B11D835D3645B15B3D6E9FA6F1CE1E5E4E197E
  
**Problembeschreibung**
Der Titel ist den Errors gelandet aufgrund fehlendem Sprachcodes.
Beim Testen auf ub28 mit TRY URL erhielt ich folgende Meldung:

> Zotero Logger initialized!
> 
> 
> 
> Queued journal 'Journal of Sufi Studies' | DIRECT @ https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details
> set download-delay for domain 'brill.com' to 5000 ms
> 
> 
> Harvesting URL 1 [Journal of Sufi Stud...] | https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details {7422778265239728523}
> Sending request to translation server: https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details
> Successful response from translation server for request: https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details, response code: 200
> Harvest successful
> 
> 
> 
> 
> Converting item 1 [Journal of Sufi Stud...] | https://brill.com/view/journals/jss/10/1-2/article-p29_3.xml?ebody=article%20details {7422778265239728523}
> use online ISSN "2210-5956" with online PPN "717295125"
> couldn't convert record: unable to normalize language: "oc"
> Conversion complete

Was bedeutet "couldn't convert record: unable to normalize language: "oc""?

**Comment by jriedl** [comment]
Das ist der Sprachcode für Okzitanisch, der war bislang nicht in unserer Sprachmappingliste hinterlegt. Ist jetzt auf nu und ub28 behoben.

**Comment by IxKo** [comment]
Danke für die Erklärung, die Sprache scheint nun normiert zu werden:
![image](https://user-images.githubusercontent.com/57000004/152515558-8af0f425-13ad-4ee5-8dd0-a34e6e697408.png)

Allerdings ist sie nicht korrekt. Ich würde daher den Zeder-Wert sprz auf "=eng,fre" setzen.
