### ISSUE TITLE
ISSN 2396-9407 International Bulletin of Mission Research Zeichensatzprobleme

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#167]
Zeichensatzprobleme, hier etwa im Abstract (Tag 520):
https://journals.sagepub.com/doi/abs/10.1177/2396939318800565
aber auch sonst an anderen Stellen, in anderen Aufsätzen dieser ZS

**Comment by mtrojan-ub** [comment]
Es gab ein Update des Zotero Translation Server, das angeblich Probleme mit Zeichenkodierungen beheben soll. Wir haben es heute Vormittag eingespielt. Treten die Probleme noch auf?

**Comment by kdr154** [comment]
gelöst

**Comment by kdr154** [comment]
Es scheint behoben zu sein. Ich habe alle diesbezüglichen Zss. getestet und die Issues geschlossen.

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Mario Trojan <notifications@github.com> 
Gesendet: Donnerstag, 7. Februar 2019 11:19
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2396-9407 International Bulletin of Mission Research Zeichensatzprobleme (#167)

 

Es gab ein Update des Zotero Translation Server, das angeblich Probleme mit Zeichenkodierungen beheben soll. Wir haben es heute Vormittag eingespielt. Treten die Probleme noch auf?
