### ISSUE TITLE
ISSN 1748-0922 | Religious studies review (Wiley) | Autor

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1670]
**URL**
https://onlinelibrary.wiley.com/doi/abs/10.1111/rsr.15317
IxTheo#2021-10-30#5A41E54853C1BA8B25367B11A668FC32848115A2
  
**Problembeschreibung**
Hier wurde ein Verfasser angegeben, obwohl es gar keinen gibt:
![image](https://user-images.githubusercontent.com/57000004/152180684-58b1cce5-a5ee-44ce-a6b8-492bdc83e28d.png)

**Comment by socheres** [comment]
Kann den Fehler weder im Scaffold noch auf Nu reproduzieren. @IxKo Können Sie bitte auch auf Nu mit try_url testen?

```
16:06:37 Returned item:
           {
             "itemType": "journalArticle"
             "creators": []
             "notes": []
             "tags": [
               {
         -       "tag": "Shari‘a"
         +       "tag": "Islam"
               }
               {
         -       "tag": "Islam"
         +       "tag": "Jurisprudence"
               }
               {
         -       "tag": "Secularism"
         +       "tag": "Law"
               }
               {
         -       "tag": "Jurisprudence"
         +       "tag": "Secularism"
               }
               {
         -       "tag": "Law"
         +       "tag": "Shari‘a"
               }
             ]
             "seeAlso": []
             "attachments": [
               {
                 "title": "Snapshot"
                 "mimeType": "text/html"
               }
             ]
             "itemID": "https://doi.org/10.1111/rsr.15317"
             "title": "Symposium: Socio-legal Studies of Islam"
             "publicationTitle": "Religious Studies Review"
             "volume": "47"
             "issue": "3"
             "pages": "315-320"
             "DOI": "10.1111/rsr.15317"
             "url": "https://onlinelibrary.wiley.com/doi/abs/10.1111/rsr.15317"
         -   "_eprint": "https://onlinelibrary.wiley.com/doi/pdf/10.1111/rsr.15317"
             "date": "2021"
             "ISSN": "1748-0922"
         -   "bookTitle": "Religious Studies Review"
             "language": "en"
             "libraryCatalog": "ubtue_Wiley Online Library"
         -   "accessDate": "2022-02-04T15:06:37Z"
             "shortTitle": "Symposium"
           }
16:06:37 Translation successful
```

**Comment by socheres** [comment]
Woher die Zeichenfolge "Religion, Constituting" kommt, ist mir ebenfalls ein Rätsel.
@helenanebel @jriedl woran könnte das liegen? Mit `Z.debug(getAuthorNameShortReview(doc))` bekomme ich auch nichts zurück.

**Comment by helenanebel** [comment]
Lieber @socheres ,
dieser Autor wird durch diesen Code generiert: 
if (!item.creators[0] && item.ISSN == "1748-0922") {
				let author = ZU.xpathText(doc, '//section[@class="article-section__content"]/p[last()-1]/i');
				if (author) {
					item.creators.push(ZU.cleanAuthor(getAuthorName(author), 'author', false));
				}
			}
Das hatte ich eingebaut, dass bei dieser ZS die Kurzrezensionen einen Verfasser erhalten, siehe Issue ubtue/DatenProbleme/issues/1239.
Ich habe das jetzt so geändert, dass dieser Zweig nur durchlaufen wird, wenn das Tag "Book Review" gesetzt wurde:
if (!item.creators[0] && item.ISSN == "1748-0922" && item.tags.includes("Book Review")) {
				let author = ZU.xpathText(doc, '//section[@class="article-section__content"]/p[last()-1]/i');
				if (author) {
					item.creators.push(ZU.cleanAuthor(getAuthorName(author), 'author', false));
				}
			}
ich habe beide Fälle getestest und das müsste jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by IxKo** [comment]
Danke, es scheint auf Nu und ub28 mit Try url kein Verfasser-Feld mehr mitzukommen.

Nur zur Dokumentation ein ähnlicher Fall: 
IxTheo#2022-01-20#99AB7597C573169850FAA84BF253CCA96123D44A
![image](https://user-images.githubusercontent.com/57000004/155279882-9868dc1e-0c71-472e-a315-39055d906513.png)
