### ISSUE TITLE
Nachweis von OA-Artikel aus dial uclouvain Repositorium

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#1671]
**URL**

https://dial.uclouvain.be/pr/boreal/en/search/site/sm_departement%3A%22SSH~~RSCS%20-%20Institut%20de%20recherche%20Religions%2C%20spiritualit%C3%A9s%2C%20cultures%2C%20soci%C3%A9t%C3%A9s%22?f%5B0%5D=sm_type%3AArticle%20de%20p%C3%A9riodique%20%28Journal%20article%29&f%5B1%5D=sm_accessibility.marc%3AAcc%C3%A8s%20libre
   
**Problembeschreibung**
Nachweis von OA-Manifestation in IxTheo mit dem Link zum Volltext:

https://ixtheo.de/Record/1767869924 (lizenzpflichtig über Peeters)

https://dial.uclouvain.be/pr/boreal/object/boreal:244535 (Zugang direkt über "DOWNLOAD" bzw. über den Tab "attached files"; über handle oder doi > führt  wieder zu Peeters)

**Comment by socheres** [comment]
- [ ] automatische Verknüpfung zur Online-Gesamtaufnahme
- [ ] Dublettenchek via handle

**Comment by socheres** [comment]
Hierzu gab es ein Meeting: https://slides.com/timotheuskim/deck-6/fullscreen
Wie wir hier weiter vorgehen wollen, muss noch gemeinsam entschieden werden. Zur Info @thefass @IxTheoKm

**Comment by helenanebel** [comment]
Lieber @socheres ,
kann dieses Issue geschlossen werden?
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Die Daten aus uclouvain Repositorium wurden erfolgreich in den IxTheo einspielt. Hier die Datensätze: https://ixtheo.de/Search/Results?lookfor=rs%3Arplv&type=AllFields&limit=20&botprotect=
