### ISSUE TITLE
 2413-3558 | Chabaršy - Eurasian Journal of Religious studies | falscher Translator? fehlen Autoren, Band, Ausgabe, Seiten, DOI, ISSN - Keywords in Abstract 

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1672]
https://bulletin-religious.kaznu.kz/index.php/relig/index

  
**Import-Translator**
  ubtue_Open Journal Systems Standard.js
 Mehrfach-Import nicht möglich
  
Bei Einzel-Import wird versucht PKP Import zu nutzen und bei den Angaben fehlen Autoren, Band, Ausgabe, Seiten, DOI, ISSN. Die Keywords sind im Abstract angegeben

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat , jetzt müsste alles funktionieren. Allerdings ist die ISSN offensichtlich nicht in der Mappingliste hinterlegt, weshalb der Satzstatus und 4241 beim Export nicht belegt werden.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
falls weitere Verbesserungen notwendig sind, bitte immer "ready for testing" entfernen und "back to IT" hinzufügen. So habe ich leichter im Blick, woran ich noch arbeiten muss.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe helananebel,

die kazachischen Titel können nicht mehr mit Mehrfachdownload heruntergeladen werden, z.B. https://bulletin-religious.kaznu.kz/index.php/relig/article/view/201. Auch beim Einzeldownload wird nicht Open Journals System Standard verwendet, sondern PKP Katalog Systems, wobei etliche Angaben fehlen (Autoren, Band, Ausgabe, ISSN).
Sowohl bei Mehrfach- als auch bei Einzeldownload fehlt immer der DOI.
