### ISSUE TITLE
1822-4539 | Religija ir kultūra | Kürzel für Sprache wird falsch übertragen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1673]
[**URL**]https://www.zurnalai.vu.lt/religija-ir-kultura/index

  
**Import-Translator**
  ubtue_Open Journal System Standard.js
  (Einzel-Import)
  
Die Bezeichnung für die Sprache Litauisch wird in Zotero mit "lt" angegeben und unverändert in den K10plus übertragen. Die korrekte Bezeichnung für Litauisch im K10plus ist "lit".

**Comment by IxKo** [comment]
Liebe @RelBibRetroKat , ich habe die Sprache in der [zotero-enhancement-maps](https://github.com/ubtue/zotero-enhancement-maps)/language_to_language_code.map nachgetragen.

**Comment by helenanebel** [comment]
Liebe @IxKo , kann man dann hier auf ready_for_testing setzen? Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet. Sprachkürzel wird korrekt eingespielt.
