### ISSUE TITLE
ISSN 2196-6265 | Jahrbuch für Christliche Sozialwissenschaften | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1674]
**URL**
https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/311
  
**Import-Translator**
  ubtue_Jahrbuch für christliche Sozialwissenschaften.js
  (Mehrfach-Import)
  
**Problembeschreibung**
Der Mehrfach-Import bricht ab. Einzel-Import scheint möglich.

**Comment by socheres** [comment]
Inzwischen gibt es erfreulicherweise eingebettete Metadaten zu OJS-Zeitschriften aus Münster. Daher können die Aufsätze regulär über OJS-Translator (ojs-standard)heruntergeladen werden. Ich lösche "ubtue_Jahrbuch für christliche Sozialwissenschaften.js" dann aus dem Translator-Ordner

**Comment by IxKo** [comment]
Funktioniert nun mit dem ubtue_Open Journal Systems Standard

**Comment by IxKo** [comment]
Doch noch ein kleines "Fehlerchen":
Der doi wird zusätzlich als Notiz erfasst, was beim Export dazu führt:
![image](https://user-images.githubusercontent.com/57000004/153216814-9cf9487e-f2d9-49cf-9cbb-0866577377cf.png)

**Comment by socheres** [comment]
Wenn man den oben verlinkten Aufsatz nach Zotero lädt, enthält das Notiz-Feld keine DOI. Dies hat etwas mit dem PicaSWB-Skript zu tun und der Link im Screenshot führt zu V&R:https://www.vr-elibrary.de/doi/book/10.13109/9783666703034
Liebe @IxKo bitte hier ein neues Issue aufmachen!

**Comment by IxKo** [comment]
> Verzeihen Sie, ich weiß nicht wie es passieren konnte, ich wollte ein ganz anderes Issue wiederöffnen.
