### ISSUE TITLE
ISSN 1804-6444 | Journal of European Baptist studies (OJS-Tue) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1675]
**URL**
https://jebs.eu/ojs/index.php/jebs/article/view/921
 
  
**Problembeschreibung**
Die OCRID wird auf nu und ub28 nicht erfasst.

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by IxKo** [comment]
Danke, ist auf Nu und ub28 nun vorhanden.
