### ISSUE TITLE
ISSN 1804-6444 | Journal of European Baptist studies (OJS-Tue) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1676]
**URL**
https://jebs.eu/ojs/index.php/jebs/article/view/326
  
**Problembeschreibung**
Rezensionen werden auf nu und ub28 nicht gekennzeichnet.

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by IxKo** [comment]
Danke, wird auf Nu und ub28 erkannt.
