### ISSUE TITLE
ISSN 2504-5156 | Vulgata in Dialogue (OJS-Tue) | Rezension

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1678]
**URL**
https://vulgata-dialog.ch/ojs/index.php/vidbor/article/view/185
  
  
**Problembeschreibung**
Die Rezension wird nicht als solche auf nu und ub28 erkannt.

**Comment by jriedl** [comment]
Woran würde man denn bei dem Artikel erkennen, dass es sich um eine Rezension handelt? Oder sind aufgrund des Untertitels alle Artikel immer Rezensionen? Dann sollte man es mit einem `add_marc_field_655` auf Zeitschriftenebene in der Config lösen können.

**Comment by IxKo** [comment]
Er ist unter der Rubrik "Rezensionen". Das sollte - denke ich - Translator-seitig behoben werden können.

**Comment by helenanebel** [comment]
Liebe @IxKo , die Änderungen sind jetzt auf NU.

**Comment by IxKo** [comment]
Wird leider noch nicht erkannt auf Nu

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das müsste durch ubtue/DatenProbleme/issues/1677 behoben sein, sobald das auf NU ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke wird nun erkannt!
