### ISSUE TITLE
ISSN 2698-5446 | Im Dialog (OJS-Tue) | RSS

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1679]
**URL**
https://imdialog.akademie-rs.de/ojs/index.php/idadrs/gateway/plugin/WebFeedGatewayPlugin/rss

Archiv-Seite: https://imdialog.akademie-rs.de/ojs/index.php/idadrs/issue/archive

  
**Problembeschreibung**
Try rss liefert nur eine gelbe Seite. Könnte hier ein ähnlicher Fall vorliegen wie bei #1665 ?
Wobei ein Test mit einer Artikel-Seite mit Try URL Daten zu liefern scheint.

![image](https://user-images.githubusercontent.com/57000004/153233058-2b783383-e25e-4812-baaa-c162d132db42.png)

**Comment by jriedl** [comment]
Response-Code 200 bedeutet "OK". Es wird keine Ausgabe erzeugt, da die Artikel alle "online first" sind.
![image](https://user-images.githubusercontent.com/13135579/153249362-60bd0d4b-76f5-424b-b574-6e75c962b4c4.png)

**Comment by IxKo** [comment]
Danke, dass der Code 200 für OF-Artikel steht, war mir nicht klar.

**Comment by jriedl** [comment]
Nein, das hat nichts miteinander zu tun: das ist ein sog. HTTP-Status-Code, der etwas darüber aussagt, ob der Download erfolgreich war, dass es sich um OF-Artikel handelt liegt daran, im "Endprodukt" bestimmte Felder nicht befüllt sind.
