### ISSUE TITLE
ISSN 2513-1389 | Zeitschrift für christlich-jüdische Begegnung im Kontext | Seitenangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1681]
**URL**
https://zfbeg.org/ojs/index.php/cjbk/issue/view/28
  
**Import-Translator**
  ubtue_Open Journal Systems Standard.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Bei der Seitenangabe wird der Ausdruck "S." mit importiert sowie am Ende ein Punkt-Zeichen, was dann zum gleichen Export führt. Korrekte Angabe ist ohne "S." und Punkt am Ende und einfach nur die arabische Ziffer.
![image](https://user-images.githubusercontent.com/57000004/153588584-8c96c642-ce44-47f2-809f-ce88fda7dc33.png)
![image](https://user-images.githubusercontent.com/57000004/153588726-b02e0fa5-b3bf-41e2-91a3-a68533499ac7.png)

**Comment by IxKo** [comment]
Hier ist der Fehler leider plötzlich wieder aufgetaucht:
https://doi.org/10.25786/zfbeg.v0i01-02.793
![image](https://user-images.githubusercontent.com/57000004/153621909-2baf8a44-9403-46a9-9d88-ac8428e7a572.png)

**Comment by IxKo** [comment]
Problem besteht weiterhin

**Comment by socheres** [comment]
Bei mir sehen die Daten gut aus und Ihr Skript hat auch das gleiche Änderungsdatum wie die Master-Datei. Würden Sie noch via Connector-Einstellung die Translators aktualisieren und dann erneut testen.

**Comment by IxKo** [comment]
Leider besteht das Problem mit der Seitenangabe 01-07 weiterhin bei mir:
![image](https://user-images.githubusercontent.com/57000004/154102363-8f36d56f-6f39-4c3c-8a19-eec1149ec6f2.png)
![image](https://user-images.githubusercontent.com/57000004/154102428-3356f0e2-c759-4421-b562-03c0cb5b676a.png)

Was meinen Sie mit " via Connector-Einstellung"? Ich aktualisiere die Import-Translator über das Web-Browser-Add-on und der Export-Translator wird über meinen Ordner von Ihnen aktualisiert.

**Comment by socheres** [comment]
Jetzt sollte es funktionieren. Ich hatte die Änderung im Code aaskommentiert gehabt. Mit "via Connector-Einstellung" meine ich genau das "Web-Browser-Add-on".

**Comment by IxKo** [comment]
Danke, nun passt es!
