### ISSUE TITLE
ISSN 2312-878X | Missionalia | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1682]
**URL**
https://missionalia.journals.ac.za/pub/article/view/358
  
**Import-Translator**
  ubtue_Open Journal Systems Standard.js
  (Einzel- und Mehrfach-Import)
  
**Problembeschreibung**
Die ORCID-Information links auf der Seite wird nicht nach Zotero übertragen.

**Comment by helenanebel** [comment]
Liebe @IxKo,
da hat sich mal wieder ein Translator eingeschlichen, der nicht verwendet werden sollte. Ich habe diesen gelöscht, dadurch müsste es dann nach der Aktualisierung auch auf NU gehen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ist jetzt auch auf NU.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Beim Multi-Import wird mir leider nur der Translator COinS angeboten. 
Beim Single-Import der ubtue_open Journal Systems Standard. Ist vielleicht auch nur Einzel-Import möglich?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
bei mir geht das, könntest du es nochmal versuchen?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun klappt auch Multi bei mir!
