### ISSUE TITLE
Zweites Abstract übergeben

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1683]
@IxKo , @socheres , @jriedl 
http://benu.ub.uni-tuebingen.de/pywrapper.py?key=429_0098

Im Issue https://github.com/ubtue/DatenProbleme/issues/971 wurde angegeben, dass das zweite Abstract, wenn es mit dem Präfix "abs:" als Notiz übergeben wird, vom zotero_harvester in ein Feld 520 geschrieben wird.
Leider passiert das auf BENU in diesem Fall nicht. Muss das Feld anders übergeben werden?

viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Hier findet sich ein Beispiel für das Übergeben mehrerer Abstracts https://github.com/ubtue/zotero-translators/blob/master/ubtue_Peeters.js (nach "abs1" suchen). 
Im Pywrapper-Fall ist das Ergebnis, das vom Translationserver zurückkommt:
```json
"note": "<p>abs:My aim is to examine the constitution of the human subjectivity in the kierkegaardian religious stage. This process implicates principles that operate inwardly and make the individual goes beyond the limits of him/herself towards a S elf t hat transcends its natural possibilities. I discuss the Self as a relation’s relating itself to itself, based on the problem of have established itself or have being established by another, the core theme of «The Sickness Unto Death». From the religious viewpoint these possibilities must be recognized as the paradox of determination of the human being as spirit through which he/she becomes a Self before God. Nobody arrives at that position without relating to other people in their condition of diversity regarding the Self. In that condition the Other must be recognized as a First-Thou instead of a second-I. And then the Other becomes the Neighbour in relation to whom the Self — mediated by religious love — impels itself while deepen itself in itself.</p>"
```
D.h., das ist in einen Paragraphen eingepackt und wird deshalb natürlich nicht erkannt. Müsste wohl im Translator selbst angepasst werden.

**Comment by helenanebel** [comment]
Super, vielen Dank!
