### ISSUE TITLE
Allgemein: QA - RegEx für Seitenangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1684]
**URL**
https://doi.org/10.1002/hast.1330
IxTheo#2022-02-11#3742D2EBFE411F10D432DC4893ABA94F07B8D4E6
  
**Problembeschreibung**
Könnte für das Marc-Feld 936 $h eine Regex eingestellt werden, die nur Zahlen erlaubt und Zahlen verbunden mit Bindestrich?

erlaubte Beispiele:

- 1
- 234
- 56-78

Damit würden solche Angaben dann in den Errors landen:
![image](https://user-images.githubusercontent.com/57000004/154308063-2154b0a1-0aa8-4b1c-a4a5-30d6c03240b6.png)

**Comment by jriedl** [comment]
Auf nu und ub28.

**Comment by IxKo** [comment]
Danke!
