### ISSUE TITLE
ub28 läuft nicht

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1686]
### Problembeschreibung
ub28 scheint gar nicht mehr zu funktionieren und seit 14.02. sind auch keine Dateien mehr automatisch eingespielt worden.

#### CLI output:
![image](https://user-images.githubusercontent.com/57000004/154672794-f50fee69-4ddc-4ac5-ae57-fe38f8e82176.png)

#### Server logs:
![image](https://user-images.githubusercontent.com/57000004/154673166-f806356a-6e64-4532-b42f-766a4c108f6e.png)

**Comment by socheres** [comment]
Lieber @jriedl, wie @IxKo festgestellt hat, wurden außer Retrokat-Daten seit dem 13. bzw. 14.02. (in K10+) keine Daten vom Havester heruntergeladen. Brill ist außerdem nicht von der "DDoS protection" betroffen. Kannst du bitte prüfen, was der Grund dafür sein könnte.

**Comment by jriedl** [comment]
Sind Probleme mit der Firewall als Nachwehen der Server-Migration. Wir arbeiten seit heute morgen an einer Lösung.

**Comment by jriedl** [comment]
Für den regulären Anwendungsbetrieb behoben.

**Comment by jriedl** [comment]
Ein Problem gelöst, nächstes aufgetreten...

**Comment by jriedl** [comment]
Sollte behoben sein.

**Comment by jriedl** [comment]
Jeden Tag etwas Neues: Gestern Abend gab es jetzt Probleme mit dem Zugriff auf das Netzlaufwerk.

**Comment by IxKo** [comment]
Danke, heute wurden 115 neue Datensätze eingespielt. Das System scheint also wieder zu laufen. Schönes Wochenende
