### ISSUE TITLE
IxTheo - Datensätze mit leeren Unterfeldern

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#1687]
In folgenden Datensätzen meldet die IxTheo MARC Pipeline ein leeres Unterfeld, bitte bei Gelegenheit prüfen und bereinigen:

|PPN|Feld|
|---|---|
|1119644100|246|
|1663070113|505|
|1663375291|505|
|166337581X|505|
|1662502745|505|
|1101808187|249|
|1616178736|246|

**Comment by IxTheoKm** [comment]
Bitte prüfen: sind alle o.g. Datensätze jetzt korrekt angekommen? 
Für 1663375291 und 166337581X habe ich keine Rückmeldung über die Durchführung der Korrektur bekommen.

**Comment by IxTheoKm** [comment]
Ich habe 1663375291 und 166337581X heute nochmals geprüft und selber Hand angelegt: offensichtlich wurden die nicht korrigiert. Jetzt müssten sie in Ordnung sein.

Bei 1101808187 gibt es jetzt kein Feld 249 mehr, statt dessen zweimal 246 mit verschiedenen Unterfeldern. 
@mtrojan-ub Ist das korrekt? Dann kann ggf. das Issue geschlossen werden.

**Comment by mtrojan-ub** [comment]
Für die alten PPNs tauchen keine Fehlermeldungen mehr auf, dafür gibt es jetzt eine neue:
1662502745 (505t)

**Comment by IxTheoKm** [comment]
Der Datensatz ist im K10plus inzwischen korrekt: er hat nur einmal
505 80$tDeus desafia seu povo a louvá-lo : (o louvor a Deus ontem, hoje e amanhã)$rAndrew H. Bartelt

Die Korrektur ist nicht angekommen, weil der Satz kein IxTheo-Selektionskriterium hatte (habe ich jetzt ergänzt). Er wurde wohl anfangs nur wegen dem verknüpften Aufsatz ausgeliefert.

Es werden sicher immer wieder solche Fälle kommen. 
Wie sollen wir zukünftig mit solchen Datenbereinigungs-Issues umgehen?
Schließen nach Bereinigung der Fälle und wieder öffnen, wenn neue auftauchen?

**Comment by mtrojan-ub** [comment]
Ja, wir können den Issue gerne schließen und melden uns wieder, wenn neue Fälle auftreten. Vielen Dank!
