### ISSUE TITLE
IxTheo - Datensätze mit nicht-wiederholbaren MARC-Tags

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#1688]
Diese Datensätze enthalten mindestens einen Tag doppelt, den es in MARC21 nun einmal geben darf (non-repeatable). Handelt es sich um ein Datenproblem, oder muss ggf. der Export beim BSZ angepasst werden?

[non-repeatable.log](https://github.com/ubtue/DatenProbleme/files/8123111/non-repeatable.log)

**Comment by IxTheoKm** [comment]
Stichproben sind definitiv unsere Falscherfassungen/-einspielungen:
z.B. 
- Mehrfacheinspielung von PICA-Feld 3000 = MARC 100, das nicht wiederholbar ist
- Nicht-Hochzählen von Unterfeld $T in PICA-Feldern 3000/4000 bei Nicht-Lateinischen Schriftzeichen.

Die Daten müssen im K10plus korrigiert werden.

**Comment by IxTheoKm** [comment]
Datensätze wurden z.T. korrgiert. 
Für einige stehen noch Korrekturen nach K10plus-Mailboxen aus.

**Comment by IxTheoKm** [comment]
Datensätze wurden vollständig korrigiert (11.03.2022).

Issue schließen und ggf. wieder öffnen, wenn neue Fälle auftauchen?

**Comment by mtrojan-ub** [comment]
Vielen Dank! Ich schließe
