### ISSUE TITLE
ISSN 2504-5156 | Vulgata in Dialogue (OJS-Tue) | Sprache

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1694]
#### URL
https://vulgata-dialog.ch/ojs/index.php/vidbor/article/view/812
B1308AB7C3F75BF43B3787EB3F1BAC6CDBCC42A5
  
### Problembeschreibung
Der Aufsatz landete in den Errors, weil als Sprache "baq" erkannt wurde, obwohl mir der Titel ziemlich Deutsch erscheint: 

![image](https://user-images.githubusercontent.com/57000004/155541511-c585891a-02f1-4708-8f9a-153308361c75.png)

**Comment by helenanebel** [comment]
Liebe @IxKo , darum sollte sich @jriedl kümmern.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Da in diesem Fall ohnehin klar ist, dass das unter Harvester und damit in meinen Verantwortungsbereich fällt, wäre ich dankbar, wenn eine solche "Arbeitszuteilung" per Github zukünftig unterbleibt.

**Comment by helenanebel** [comment]
Da in diesem Fall kein Label gesetzt wurde, das darauf hindeutet, war ich mir nicht sicher, ob IxKo das weiß. Ich dachte, es wäre einfacher, das gleich zu kommunizieren, dass die Aufgabe so schnell wie möglich bearbeitet werden kann. Dann unterlasse ich es zukünftig, dich zu erwähnen.

**Comment by jriedl** [comment]
Wird von `tika` tatsächlich in diesem Fall als `eu` (also baskisch) gelabelt. Falls der Fall häufiger auftritt, könnte als Workaround `zotero_expected_languages = ?title+abstract:eng,ger,fre` dienen. Mit der größeren Textmenge wird es zumindest in diesem Fall korrekt erkannt.

**Comment by IxKo** [comment]
> Wird von `tika` tatsächlich in diesem Fall als `eu` (also baskisch) gelabelt. Falls der Fall häufiger auftritt, könnte als Workaround `zotero_expected_languages = ?title+abstract:eng,ger,fre` dienen. Mit der größeren Textmenge wird es zumindest in diesem Fall korrekt erkannt.

Das würde leider bei diesem franz. Artikel https://vulgata-dialog.ch/ojs/index.php/vidbor/article/view/821 zur Sprache ger führen, da das Abstract auf Deutsch ist.
