### ISSUE TITLE
2413-3558 | Chabaršy - Eurasian Journal of Religious studies | Kürzel für Kazachisch fehlt in Liste

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1695]
[#### URL](https://bulletin-religious.kaznu.kz/index.php/relig/index)

  
#### Import-Translator
ubtue_Open Systems Standards.js
(Mehrfach-Import)
  
Für Titel in kazachischer Sprache wird in Zotero das Kürzel kk gesetzt. Es wird beim Einspielen in 1500 nicht in "kaz" geändert.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat , es wäre gut, wenn man immer eine konkrete URL zum Testen angibt anstatt der Einstiegs-URL der Zeitschrift. Sonst muss ich immer erst einen passenden Artikel suchen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Beispiel-URL: https://bulletin-religious.kaznu.kz/index.php/relig/article/view/199

**Comment by RelBibRetroKat** [comment]
Dank für die Änderung. Werde konkreten Link demnächst berücksichtigen.
