### ISSUE TITLE
ISSN 2605-3357 | Vergentis (OJS) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1696]
#### URL
https://vergentis.ucam.edu/index.php/vergentis/article/view/234
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die Keywords (spanisch und englisch) werden nicht nach Zotero als Tags übertragen. 
Die englischen werden ins Abstract übernommen mit einem harten Absatz:
![image](https://user-images.githubusercontent.com/57000004/156175671-0d777710-8000-4c02-bbb9-30b9b97b17df.png)

Seltsamerweise werden sie hier (https://vergentis.ucam.edu/index.php/vergentis/article/view/233) als Zotero-Tags importiert. Allerdings hat es hier auf der Webseite nur englische Keywords, die dort zweimal dargestellt werden. In Zotero tauchen sie auch nochmals im Abstract auf.

Als OJS-Zs wäre sie für die Zukunft auch ein zota-Kandidat.

- [ ] Koop Bescheid geben

**Comment by helenanebel** [comment]
Liebe @IxKo ,
Keywords müssten jetzt mitkommen, auch das zusätzliche Abstract habe ich noch übernommen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe die Punkte entfernt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt, danke!
