### ISSUE TITLE
ISSN 0106-6749 | Kritisk forum for praktisk teologi (PubPub) | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1697]
#### URL
https://www.kfpt.dk/krit-164
Archiv-Seite: https://www.kfpt.dk/tidligerenumre
  
#### Import-Translator
PubPub.js
(nur Einzel-Import)
  
### Problembeschreibung
Könnte der Translator angepasst werden?
Es fehlen beim Import die ISSN und die Band-Angabe.
![image](https://user-images.githubusercontent.com/57000004/156173651-35a976ae-496c-41c6-8e15-a3a448403c15.png)

Es wird zwar Bibtex unter "Cite" angeboten, jedoch nicht als Datei sondern nur als reiner Text. So einen Import nach Zotero zu gestalten, scheint sehr umständlich.
![image](https://user-images.githubusercontent.com/57000004/156174021-3c100b67-f160-4ee2-8b67-3ab3d08edd7a.png)

Die Zs wurde bisher manuell an der Print-Aufnahme katalogisiert. Sie erscheint jedoch nicht mehr in gedruckter Form.

**Comment by IxKo** [comment]
Der Zusatztitel "om frivilligstrategi og ledelse i uKirke" wurde hier nicht importiert: https://www.kfpt.dk/pub/6yrg0nu9/release/1
![image](https://user-images.githubusercontent.com/57000004/158988303-c5981fcb-b84f-4b6b-beab-f45550cbea98.png)

Oder auch hier: https://www.kfpt.dk/pub/aacy9xdy/release/1
Kann man da etwas machen?

**Comment by helenanebel** [comment]
Liebe @IxKo lieber @socheres  ,
das geht leider nicht, da z.B. im Artikel https://www.kfpt.dk/pub/krit-163-indledning/release/2 im Seitenquelltext an der selben Stelle die Autoren stehen und es keine Möglichkeit gibt, das zu unterscheiden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ok, dann passt es so, danke!
