### ISSUE TITLE
ISSN 0003-3286 | Anglican theological review (SAGE) | zweiter DOI:

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1698]
#### URL
https://journals.sagepub.com/doi/10.1177/00033286211056815
  
#### Import-Translator
ubtue_.SAGE jorunals.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Beim Export wird ein zweiter DOI mit Einleitung "doi:" ins Feld 2051 übertragen:
![image](https://user-images.githubusercontent.com/57000004/156180474-bcd7c7ca-ef9a-499e-a3ce-a7744354b02c.png)

Dies kommt daher, weil eine Notiz mit importiert wird:
![image](https://user-images.githubusercontent.com/57000004/156181166-1fa8c269-d68c-4d03-97ef-e58d927296f0.png)

Könnte diese Notiz unterdrückt werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe die Notiz entfernt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke sehr!
