### ISSUE TITLE
ISSN 1475-4967 | Middle East policy (Wiley) | Doppelheft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1699]
#### URL
https://onlinelibrary.wiley.com/doi/full/10.1111/mepo.12580
  
#### Import-Translator
ubtue_Wiley Online Library.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Das Doppelheft wird nicht in korrekter Form mit Schrägstrich 3/4 sondern mit Bindestrich importiert.
Betrifft beide Verfahren.

Da die Zs auf zota gesetzt ist, landete das ganze Heft deshalb in den Errors.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe beide Translator angepasst.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ist jetzt auch auf NU.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert nun im halbautomatischen Verfahren wie gewünscht.

@jriedl Ich kann es leider nicht auf Nu testen, da ich einen Fehler erhalte bei TRY URL:
![image](https://user-images.githubusercontent.com/57000004/160351525-0c37ce4a-3c05-4a3a-950b-d1ca73b04a35.png)

**Comment by jriedl** [comment]
Reproduzierbar auf nu, ub28, lokal und mittels curl-Abfrage. Ist das gleiche Problem wie bei SAGE (#1655, #1668), d.h. der Cloudflare DDos-"Schutz" schlägt zu: `DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>`.

**Comment by IxKo** [comment]
Das Doppelheft wird nun auch auf ub28 korrekt mit Schrägstrich ausgegeben.
