### ISSUE TITLE
ISSN 1758-6631 International Review of Mission Rezensionsproblematik

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#170]
Bei dieser ZS werden ausnahmslos alle Artikel als Rezensionen gekennzeichnet, Tags 655 und 935 sind immer mit den entsprechenden Werten gesetzt. 
Wahrscheinlich zurückzuführen auf das Wort Review im Titel des ZS.
Es handelt sich aber überwiegend um ganz normale Aufsätze. 
Erst gegen Ende des Feeds sind auch einige Rezensionen gelistet.

**Comment by kdr154** [comment]
Das generelle Problem ist gelöst. Die Rezensionen sollten aber dennoch erkannt werden.

**Comment by shadeMe** [comment]
Nach welchen Mustern sollten wir bei dieser Zeitschrift suchen? Das von EquinoxPub scheint hier nix zu bringen.

**Comment by kdr154** [comment]
In diesem Fall sind die Aufsätze auf den jeweiligen Webseiten als Book Review gekennzeichnet. Z. B.:
https://onlinelibrary.wiley.com/doi/10.1111/irom.12251
Eine andere Möglichkeit wäre die Seite eines einzelnen Heftes als Ganzes zu scannen. Diese ist in diesem Fall in Sektionen unterteilt. Eine davon ist Book Reviews:
https://onlinelibrary.wiley.com/toc/17586631/2018/107/2

**Comment by kdr154** [comment]
Klappt noch nicht ganz. Die Rezenionen von Buda und Amos sind nicht als solche getagt, die von Williams und Chaillot hingegen schon

**Comment by kdr154** [comment]
Der Parser bricht nach wenigen Sekunden ab. Der Feed als solcher sieht auch etwas seltsam aus.

**Comment by kdr154** [comment]
gelöst
