### ISSUE TITLE
ISSN 1745-2538 | Journal of Asian and African Studies (Sage) | neues Heft keine Einspielung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1700]
#### URL
https://journals.sagepub.com/toc/JAS/current
  
### Problembeschreibung
Die Zs ist auf ub28 rot markiert. Es gibt bereits ein neues Heft, welches nicht eingespielt wird.
Es liegt vermutlich an dem gleichen Fehler wie im Issue #1668 , da es mit Try rss ebenfalls nicht läuft.

**Comment by jriedl** [comment]
Ja, scheint die allgemeine Sage-Problematik zu sein. Rot bedeutet in diesem Fall, dass das Lieferfenster überschritten wurden. Gilt auf ub28 auch für   [Review and expositor : an international Baptist journal](https://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=raeb&type=etoc&feed=rss) und [Culture and religion : an interdisciplinary journal](https://www.tandfonline.com/feed/rss/rcar20), bei letzter ist tryRSS aber möglich.

**Comment by IxKo** [comment]
Review and Expositor ist eine SAGE-Zs. Hier besteht also auch die Problematik, aber es gibt auch noch kein aktuelleres Heft als das eingespielte. 
Culture und Religion hingegen ist eine Wiley-Zs. Hier ist einfach noch kein aktuelleres Heft da.

Die Hefte erscheinen teilweise nicht so regelmäßig, dass es immer mit dem Lieferfenster passt.

**Comment by socheres** [comment]
Immer noch keine Antwort von Sage. Habe eine Erinnerungsemail geschickt.

**Comment by socheres** [comment]
Das Problem scheint gelöst zu sein. Das letzte Heft von Review and Expositor wurde bereits in IxTheo eingespielt.

**Comment by IxKo** [comment]
Das neue Heft wurde eingespielt, ja. 
Ob das Problem nun für die Zukunft gelöst ist, wird sich zeigen.
Try RSS scheint weiterhin nicht zu funktionieren. Wie dann aber Daten generiert werden konnte, ist mir nicht klar.

Ich schließe vorerst.
