### ISSUE TITLE
ISSN 2428-3606 | Revue d'Etudes Augustiniennes et Patristiques (Brepols) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1701]
#### URL
https://www.brepolsonline.net/toc/rea/2021/67/1
  
#### Import-Translator
ubtue_Brepols.js
(Mehrfach-Import)
  
### Problembeschreibung
Beim Mehrfach-Import bricht der Translator ab:

![image](https://user-images.githubusercontent.com/57000004/157419170-f457f547-e212-4d47-b8c3-bce8037d2190.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem sollte jetzt nicht mehr auftreten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke!
