### ISSUE TITLE
ISSN 2077-1444 | Religions | Artikel-ID

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1702]
#### URL
https://doi.org/10.3390/rel12100897
  
#### Import-Translator
MDPI Journals.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Könnte hier der Import-Translator angepasst werden, so dass die Artikelnummern korrekt importiert werden und nicht als Seitenangabe. Beim Export sollte $i für die Artikelnummern eingestellt werden.

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
die ArtikelID müsste jetzt korrekt übertragen werden.
Viele Grüße, Helena Nebel

**Comment by DowntownOcean** [comment]
Vielen Dank @helenanebel , funktioniert einwandfrei.

Herzliche Grüße,
Kenny Albrecht
