### ISSUE TITLE
ISSN 1918-6371 | Toronto Journal of Theology (utp) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1703]
#### URL
https://www.utpjournals.press/toc/tjt/37/2
  
#### Import-Translator
ubtue_University of Toronto Press.js
(Mehrfach-Import)
  
### Problembeschreibung
Der Mehrfach-Import bricht ab:

![image](https://user-images.githubusercontent.com/57000004/157472742-7b0f7a31-f129-4226-aa15-9f497a69a65f.png)

**Comment by helenanebel** [comment]
Lieber @IxKo ,
ich habe das Problem behoben und Renezsionstags ergänzt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt nun.
Ist es vielleicht auch noch möglich, dass einzelne OA-Artikel wie dieser hier https://www.utpjournals.press/doi/full/10.3138/tjt-2021-0016 erkannt werden?

**Comment by socheres** [comment]
Liebe @helenanebel, schicken Sie mir noch einen PR für zotkat, damit ich commiten kann?

**Comment by helenanebel** [comment]
Lieber @socheres ,
ich wollte noch einige Issues bearbeiten, sodass Sie alles auf einmal prüfen können.
Ich schicke Ihnen den PR dann im Laufe des Vormittags.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke!
