### ISSUE TITLE
zotero_expected_languages wird nicht berücksichtigt

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1704]
https://www.jstor.org/stable/42909827
  
### Problembeschreibung
mit der conf:

[Wesley and Methodist studies : WMS_ a publication of the Manchester Wesley Research Centre and O]
zeder_id = 1236
zeder_modified_time = "2019-04-28 09:36:01"
print_ppn = 641390882
online_ppn = 823700518
online_issn = 2291-1723
print_issn = NV
zotero_type = CRAWL
zotero_group = IxTheo
zotero_delivery_mode = TEST
zotero_expected_languages = fre,eng
zotero_url = https://www.jstor.org/journal/weslmethstud
zotero_max_crawl_depth = 2
zotero_crawl_url_regex = (jstor\.org\/stable\/10\.\d{4,5}\/[ie])|(\/journal\/weslmethstud\?decade=)|(jstor\.org\/stable\/10\.\d{4,5}\/weslmethstud.+issue)
zotero_extraction_regex = \/stable\/(?!(pdf|10\.\d{4,5}\/[ie]|10\.\d{4,5}\/$|.+issue))

wird auf BENU die Sprache "wel" generiert, obwohl diese nicht in zotero_expected_languages enthalten ist. Dies ist auch bei zahlreichen weiteren Artikeln mit anderen Sprachen der Fall. Muss die conf in diesem Fall anders aussehen, um außer den Sprachen Französisch und Englisch alle zu verwerfen?

Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Ursprünglich ist man wohl einmal davon ausgegangen, dass Zotero in (fast?) allen Fällen eine Sprache liefert: Wenn kein Modifier verwendet wird, ist die Spracherkennung ein Abgleich zwischen der von Zotero zurückgelieferten Sprache und der hinterlegten Sprache. Wird von Zotero keine Sprache zurückgeliefert (wie hier der Fall), wird die Harvesterseitig erkannte verwendet. Das ermöglicht ein Setzen des Sprachcodes auch Fällen, in denen  `zotero_expected_languages` nicht gesetzt ist (im KrimDok-Kontext offenbar häufig). Bei der Verwendung von '?', , also im konkreten Fall `?eng,fre` wird überprüft, ob die erkannte Sprache zu den hinterlegten passt. Ich habe es nun allerdings weiterhin so angepasst, dass die Konsistenz auch ohne Modifier überprüft wird, wenn `zotero_expected_languages` existiert.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
vielen Dank!
Leider kommt bei dem Beispiel oben bei mir immer noch die Sprache "wel", wenn ich das auf BENU teste.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Einspieung erfolgt nachher zusammen mit den zusätzlichen Sprachen.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
jetzt funktioniert alles! Vielen Dank!
