### ISSUE TITLE
ISSN 1890-7008 | Nordic journal of religion and society (Idunn) | ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1705]
#### URL
https://www.idunn.no/toc/njrs/34/2
  
#### Import-Translator
ubtue_.Idunn.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die ISSN der ZS wird nicht nach Zotero importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ISSN wird jetzt anhand der URL erkannt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke!
