### ISSUE TITLE
ISSN 2196-8284 | Wege zum Menschen | Translatorabbruch

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1707]
#### URL
https://www.vr-elibrary.de/toc/weme/74/1
  
#### Import-Translator
ubtue_vandenhoeck_ruprecht.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Der Translator bricht beim Mehrfachimport ab.
Der Einzelimport funktioniert problemlos.

Beim Einzelimport von Editorial und Bücherschau wird der Translator abgebrochen.

![image](https://user-images.githubusercontent.com/101199276/159431915-049b395e-c449-4823-aa9e-ec6d1ac83d85.png)

In Zotero wird die Namensform falsch übernommen (Vorname wird als Nachname übertragen und Nachname als Vorname).

![image](https://user-images.githubusercontent.com/101199276/159438687-b88845a4-6cc8-47e9-becc-b214471ac546.png)

**Comment by helenanebel** [comment]
Liebe*r @SchwXC ,
der Download sollte jetzt nicht mehr abbrechen und die Namen sollten rüberkommen.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe Frau Nebel,

der Download funktioniert ohne Probleme.

Danke und viele Grüße
Sarah Schwaldt
