### ISSUE TITLE
ISSN 2628-5762 | Biblische Notizen (Herder) | ISSN, Abstract-Absatz, Heft=Band

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1708]
#### URL
https://www.herder.de/bn-nf/hefte/archiv/2022/192-2022/
  
#### Import-Translator
ubtue_Herder.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung

- [x] Die ISSN wird nicht nach Zotero importiert.
- [X] Bei der Zusammenfassung wird ein Absatz übernommen, was beim Export zu Fehlern führt. 

- ![image](https://user-images.githubusercontent.com/57000004/159877876-d47b30fa-8550-456f-8251-7da4887a1c89.png)
- [x] Die Heftzählung ist durchgängig und es gibt keine Bandzählung. Laut Katalogisierungsregeln müsste daher die Heftzählung in das Feld der Bandzählung. Wäre es möglich, dies Translator-seitig zu lösen? 

![image](https://user-images.githubusercontent.com/57000004/159878235-a4060c71-591e-480e-8f9e-c67ca9c779e3.png)

- [x] https://github.com/ubtue/DatenProbleme/issues/1708#issuecomment-1098026479

- [x] _Memo an mich: Zeder prodf=zotk ändern + Koop_

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Abstract müsste jetzt korrekt sein und die ISSN mitkommen.
Das mit der Bandzählung habe ich jetzt im Translator gelöst, allerdings wäre es m.E. auf Dauer sinnvoll, das im Export zu lösen, dass immer, wenn es eine Ausgabe, aber keinen Band gibt, die Angabe als Bandzählung verwendet wird.
Oder führt das dann an anderer Stelle zu Problemen?
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
> Das mit der Bandzählung habe ich jetzt im Translator gelöst, allerdings wäre es m.E. auf Dauer sinnvoll, das im Export zu lösen, dass immer, wenn es eine Ausgabe, aber keinen Band gibt, die Angabe als Bandzählung verwendet wird.
Oder führt das dann an anderer Stelle zu Problemen?

Ich habe kein konkretes Beispiel, könnte mir aber vorstellen, dass es ZSs gibt, die keine Bandzählung haben und keine durchgängige Heftzählung, sondern nach bspw. 4 Heften im Jahr wieder bei 1 anfangen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müssten beide Autoren mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, danke, alles passt nun 👍

**Comment by IxKo** [comment]
Die Probleme treten wieder auf:
ISSN wird nicht importiert und die durchgängige Heftzählung müsste in die Bandangabe.

- [ ] ISSN
- [ ] Heftzählung laut Katalogisierungshandbuch in Bandausgabe

**Comment by IxKo** [comment]
Danke, das Wesentliche ist behoben.

Bei den Buchvorstellungen wird seltsamerweise nun als Band "buchvorstellungen/192" anstatt Band 192 importiert.
Und wäre es möglich, dass es direkt als Rezension gekennzeichnet wird?

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/7ead62f9-47f8-4d71-9068-b07c2efdb509)

**Comment by mara-spiess** [comment]
Buchvorstellungen sollten nun automatisch mit dem RezensionstagPica gekennzeichnet und die Bandangabe bereinigt sein.

**Comment by IxKo** [comment]
> Buchvorstellungen sollten nun automatisch mit dem RezensionstagPica gekennzeichnet und die Bandangabe bereinigt sein.

Danke, passt!
