### ISSUE TITLE
Edinburgh University Press | LF

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1711]
#### URL
1. https://www.euppublishing.com/doi/abs/10.3366/hlps.2021.0269
2. https://www.euppublishing.com/doi/abs/10.3366/inr.2021.0317
 

#### Import-Translator
ubtue_Edinburgh University Press Journals.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Auf der Seite von Edinburgh University Press gibt es teils frei zugängliche Titel.
Diese werden leider nicht vom Translator als LF gekennzeichnet.

In der ersten URL hat die UB die Zeitschrift nicht lizensiert. Hier sieht man in der Heftübersicht, welche Artikel frei zugänglich sind.  (https://www.euppublishing.com/toc/hlps/20/2)

In der zweiten URL haben wir die Zeitschrift lizensiert. Leider ist es hier nicht mehr auf den ersten Blick erkennbar, dass manche Artikel frei zugänglich sind. Hier ist alles mit s (subscribed) gekennzeichnet. (https://www.euppublishing.com/toc/inr/72/2)
Da ich zur Zeit aus dem Homeoffice arbeite, habe ich die VPN Verbindung deaktiviert und auf die Webseite zugegriffen. Hier wurden nun einige Artikel als f markiert. 
![image](https://user-images.githubusercontent.com/101199276/160094785-9aa80fd9-6bca-4ebb-9c5f-04c55e870874.png)

Hier ist noch eine Heftseite mit F und OA markierten Seiten. (https://www.euppublishing.com/toc/jqs/24/1)
![image](https://user-images.githubusercontent.com/101199276/160095870-c27795ed-3a92-4f97-9ff3-885ce5f72f01.png)

Gibt es eine Möglichkeit, dass der Import-Translator diese Artikel erkennt und diese kennzeichnet?

**Comment by helenanebel** [comment]
Liebe*r @SchwXC ,
jetzt müssten die OA- und frei zugänglichen Artikel gekennzeichnet werden.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe Frau Nebel,

die Artikel werden jetzt gekennzeichnet.

Allerdings wird bei https://www.euppublishing.com/toc/inr/72/2 "The declaration of Arbroath in print, 1680-1705" (s. Bild oben) noch nicht gekennzeichnet, dass der Artikel frei verfügbar ist.

Da ich zur Zeit nicht mehr im Homeoffice bin, kann die restlichen Titel nicht außerhalb des Uninetzes auf OA/F überprüfen.

Danke für Ihre Bemühungen und die Anpassung.

Sonnige Grüße
Sarah Schwaldt

**Comment by helenanebel** [comment]
Liebe @SchwXC ,
ich glaube, ich hatte Ihre Translator nicht angepasst, weil diese auf einem anderen Verzeichnis lagen. Bitte testen Sie nochmal, jetzt müssten diese eigentlich aktualisiert worden sein.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe @helenanebel ,

leider werden die F Artikel noch nicht entsprechend übernommen.

Viele Grüße, SchwXC

**Comment by helenanebel** [comment]
Liebe @SchwXC ,
ich habe das Problem verstanden. Die Daten, die Sie gerne übernommen hätten, sind im Seitenquelltext nicht vorhanden, solange man sich im Uninetz befindet, und könnnen deshalb nicht übernommen werden.
Ich schließe das Issue.
Viele Grüße, Helena Nebel
