### ISSUE TITLE
ISSN 1527-9472 | Buddhist-Christian Studies | Heftzählung/Ausgabe

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1712]
#### URL
https://muse.jhu.edu/issue/46811
  
#### Import-Translator
ubtue_Project MUSE.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Beim Import in Zotero wird die Bandangabe auch als Heftnummer übernommen. Diese Zeitschrift erscheint jährlich und hat keine Heftnummern.

![image](https://user-images.githubusercontent.com/101199276/160127357-69b64f41-721a-4d73-be6b-9d87eed2ec00.png)

Wäre es möglich, den Translator so anzupassen, dass die Heftnummern nicht in Zotero übertragen werden?

**Comment by helenanebel** [comment]
Liebe*r @SchwXC ,
das müsste gelöst sein.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe Frau Nebel,

das Problem ist behoben.

Vielen Dank und sonnige Grüße
Sarah Schwaldt
