### ISSUE TITLE
ISSN 1527-9472 | Buddhist-Christian Studies | Seitenangaben

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1713]
#### URL
https://muse.jhu.edu/issue/46811
  
#### Import-Translator
ubtue_Project MUSE.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Wenn ein Artikel nur eine Seite hat, wird die Zahl als "von" und als "bis" eingetragen.

![image](https://user-images.githubusercontent.com/101199276/160128423-f6a9601c-2203-4532-90da-8c9bd7d67301.png)

Ist es möglich, dies abzuändern, sodass doppelt vergebene Seitenzahlen nur ein Mal angegeben werden?

**Comment by helenanebel** [comment]
Liebe*r @SchwXC ,
das müsste gelöst sein.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe Frau Nebel,

das Problem ist leider noch nicht behoben.

Viele Grüße
Sarah Schwaldt

**Comment by SchwXC** [comment]
Liebe @helenanebel ,

leider ist das Problem bei mir noch nicht behoben.

viele Grüße
SchwXC
