### ISSUE TITLE
ISSN 1527-9472 | Buddhist-Christian Studies | Review

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1714]
#### URL
https://muse.jhu.edu/issue/46811
  
#### Import-Translator
ubtue_Project MUSE.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Bei Übertragen in Zotero wird der Tag für die Rezension nicht übertragen.

![image](https://user-images.githubusercontent.com/101199276/160129300-bea36a86-37e6-4c3b-b2bf-fdadb9558b04.png)

Könnte man den Translator so abändern, dass Reviews automatisch gekennzeichnet werden?

**Comment by helenanebel** [comment]
Liebe*r @SchwXC ,
das müsste gelöst sein.
Viele Grüße, Helena Nebel

**Comment by IxTheoEg** [comment]
Vielen lieben Dank. Es klappt, wir (M. & IxKo) haben geprüft.
