### ISSUE TITLE
ISSN 1540-6385 | Dialog : a journal of theology (Wiley) | Translator-Abbruch und fehlender Artikel in zota

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1715]
#### URL
https://onlinelibrary.wiley.com/doi/10.1111/dial.12675
  
#### Import-Translator
ubtue_Wiley Online Library.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Der Translator bricht hier ab.
Bei anderen Artikeln des Heftes nicht.

Der Artikel hätte auch vollautomatisch schon eingespielt sein müssen. Er taucht aber nicht auf ub28 auf.
Die anderen Artikel des Heftes wurden automatisch im Juli letzten Jahres eingespielt.
Die SE meldete, dass dieser Artikel fehlt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
für Zotk habe ich das behoben.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun tritt der Fehler nicht mehr auf.
Allerdings wurde die Autorin nicht mit importiert. Könnte das noch behoben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müsste die Autorin mitkommen und auch alle Keywords (es wurde nur eines übernomen)
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun stimmt alles! 👍
