### ISSUE TITLE
ISSN 1467-8519 | Bioethics (Wiley) | Neues Heft nicht auf ub28

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1716]
#### URL
https://onlinelibrary.wiley.com/toc/14678519/2022/36/3
  
### Problembeschreibung
Das neueste Heft wurde nicht eingespielt und findet sich nicht auf ub28, obwohl es im RSS-Feed ist.

TRY RSS auf ub28 führte zudem zu einer Fehlerseite.

**Comment by IxKo** [comment]
Gleiches gilt für die Wiley-ZS History Compass

**Comment by jriedl** [comment]
vgl. #1699.
