### ISSUE TITLE
ISSN 0040-5671 | Theologische Literaturzeitung (THLZ) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1718]
#### URL
Heft: http://www.thlz.com/inhaltsverzeichnisse/?heft=2022_3
Rezension: http://www.thlz.com/artikel/22374/?inhalt=heft%3D2022_3%23r1
  
#### Import-Translator
keiner angeboten
  
### Problembeschreibung
Ist es möglich für diese Website einen Import-Translator zu entwickeln?

Zitat thefass:

> Link muss vermutlich gebastelt werden (leider kein DOI oder ähnliches, müssen wir mit leben).
> Beispiel: http://www.thlz.com/artikel/14986
> Seitenquellcode Zeile 88
> <p class='login_hinweis'  style='color:#990000;'>Für den Recherche-Zugang ist ein Passwort nötig.</p><div class='formular login_form'><p>Bitte geben Sie hier Ihre Zugangsdaten ein.</p><form id='loginform' action='/artikel/14986/?inhalt=heft%3D2012_3%23r1' method='POST'>
>

**Comment by helenanebel** [comment]
Liebe @IxKo ,
der neue Translator ubtue_thlz müsste funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
- [ ] Die Namen werden leider nicht nach Nach- und Vorname getrennt. Kann das behoben werden?

![image](https://user-images.githubusercontent.com/57000004/163181242-3a218fa2-51a6-429b-b5e8-0f87f230296f.png)

- [ ] Und könnte der Monat noch in eine Zahl umgewandelt werden?

- [ ] Und die Bandangabe wird nicht korrekt importiert. Statt dem Jahr 2022 müsste 147 als Wert für Band importiert werden.

**Comment by helenanebel** [comment]
Liebe @IxKo,
das müsste mit dem nächsten Update dann funktionieren.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Alles perfekt nun, danke! 👍
