### ISSUE TITLE
ISSN IXTH-0002 | Journal of the Grace Evangelical Society (Z=580) | ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1719]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26jid%3d8HAF%26site%3dehost-live
  
#### Import-Translator
ubtue_EBSCOhost.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Bitte für diese ZS die fingierte ISSN "IXTH-0002" einrichten.
Die ZS hat selbst keine ISSN.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das im Translator eingerichtet.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke! 👍
