### ISSUE TITLE
ISSN 2748-6419 | AABNER Advances in ancient, biblical, and Near Eastern research (OJS) | Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1722]
#### URL
https://aabner.org/ojs/index.php/beabs/article/view/825
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Es wird nicht das Abstract von der Webseite importiert sondern das:

![image](https://user-images.githubusercontent.com/57000004/161071778-63aca2b0-b54d-44bd-b313-14f358421859.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das müsste dann jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Tut es, danke sehr! 👍
