### ISSUE TITLE
ISSN 0035-2160 | Revue des Questions Scientifiques | Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1723]
#### URL
https://www.rqs.be/app/views/revue.php?id=549&publication=3206
  
#### Import-Translator
ubtue_Revue des Questions Scientifiques.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Durch ein fehlendes Leerzeichen zwischen Feld-Nr. 4207 und dem Abstracts kommt es beim Einspielen zu folgender Fehlermeldung:
![image](https://user-images.githubusercontent.com/57000004/161100415-ad38ecd9-1bf2-4814-9b79-760759fdaae7.png)
![image](https://user-images.githubusercontent.com/57000004/161100840-c3268af7-3388-4338-9687-530487c25d60.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das behoben & die Abstracts müssten jetzt auch komplett sein (die waren in einigen Fällen abgeschnitten).
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Passt nun alles, vielen Dank! 👍
