### ISSUE TITLE
ISSN 2385-2062 | Biblica (Peeters) | Notes

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1724]
#### URL
https://doi.org/10.2143/BIB.102.3.3289786
Hash auf Nu: DC43BF009E1EFFCC55F46BF1765F249BA78A122A
  
### Problembeschreibung
Der Titel "Recensiones" hat u.a. als Fehlermeldung, dass Marc-Feld 100 fehlt.
Eigentlich sollte dieser Fehler nicht erscheinen, weil der Titel in der RegEx für Notes vorkommt:

`(?i)(^((Publisher\W?s?\s+Note)|(Notes\s+and\s+News)|(Contributor\s+Notes)|(Marginalia)|(Patrons\WPhilip\s+Hefner\s+Fund)|(Vorwort)|(Acknowledgments)|(Journal\s+of\s+Jesuit\s+Studies)|(Biblical\s+Interpretation)|(Recensiones)|(Libri\sad\sDirectionem\smissi)|(Book\sReviews?)|(Notes\s?)|(Book\sNotes)|(Editorial|Guest\s+Editorial)|(A?\s?(Word)?\s?From\s+the\s+Editors?)|((Editor\W?s)?\W?\s+?(Introduction|Preface))|(Introduction|Foreword)|(Editors\s+and\s+Authors)|(Books\s+Received)|(New\s+Books)|(About\s+This\s+Issue)|(Issue\s+Information)|(Contents?)|(Preliminary\s+Material)|(Indexes\s+Vol\W)|(Einleitung)|(Inhalt)|(Inhaltsverzeichnis\s?(Heft)?)|(Associate?s+Editors?)|(List\s+of\s+Contributors)|(Table\s+of\s+Contents?)|(From\s+the\s+Editor\W?s\s+Desk)|(Call\s+for\s+Papers\s+)|(Volume\s+Contents?)|(Index\s+(\d{4})?)|(Guidelines?\s+for\s+Authors)|(Toc)|(Issue\s+Information\s+\W\s+TOC))$|^((Announcements?)|(List\s+of)|(MANY\s+THANKS\s+TO)|(Zum\sGedenken\san)|(Recent\sTitles\sfrom)|(Indexes)|(Contents?\s+to\s+Vol)|(Index(es)?\s+Vol)|(About\s+the)|(Remerciements\s+aux\s+évaluateurs)|(RRT)|(Doctoral\s+dissertation\s+notices)))
`
![image](https://user-images.githubusercontent.com/57000004/161269455-09ad72b1-e78a-4f6c-94f9-a4c04539cfd3.png)

**Comment by IxKo** [comment]
Die Notes scheinen auf Nu und in der Test-DB zu funktionieren. Könnte das System auf ub28 übertragen werden samt der QA-Settings?

**Comment by jriedl** [comment]
Nachtrag: Mir war noch aufgefallen, dass für das "Indo-Pacific Journal of Phenomenology" offenbar auch für die `non articles` Regeln eingetragen wurden. Das sollte (ebenso wie für die Rezensionen) nicht notwendig sein, da die Regeln "vererbt" werden, wenn keine spezifischere vorliegt, d.h. im Regelfall sollte eine Anpassung bei den `regular articles` genügen.

**Comment by IxKo** [comment]
Danke!
Ja, als ich die Einstellungen für die ZS "Indo-Pacific Journal of Phenomenology" machte, war mir noch nicht bekannt, dass es reicht, die spezifischen Einstellungen für die "regular articvles" nur zu machen (https://github.com/ubtue/DatenProbleme/issues/1494#issuecomment-1046773774)
