### ISSUE TITLE
ISSN 0035-7812 | Römische Quartalschrift (Herder) | ISSN, Band, Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1725]
#### URL
https://www.herder.de/rq/hefte/aktuelles-heft/
  
#### Import-Translator
ubtue_Herder.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung

- [x] Die ISSN wird nicht nach Zotero übertragen.
- [x] Die Bandangabe steht im Ausgabenfeld.
- [x] Die Heftzählung fehlt.

![image](https://user-images.githubusercontent.com/57000004/161990227-49c0d7d4-c4d8-48e0-bc8c-e071214a33da.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müsste alles korrekt rüberkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, danke! 👍
