### ISSUE TITLE
ISSN 1097-6566 | Stone-Campbell journal | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1726]
#### URL
http://www.stone-campbelljournal.com/

http://www.stone-campbelljournal.com/the_journal/research/volume-24-issue-1/240104/

### Problembeschreibung

Könnte für diese Seite ein Translator gebastelt werden?
Die ZS wird momentan über E/A erfasst an die O-Aufnahme..

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe für die Zeitschrift einen neuen Translator geschrieben. Dieser funktioniert nur im Multi-Download.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Nur zwei Kleinigkeiten wären zu verbessern:

- [ ] Bei einem Seitenumfang von 1 Seite müsste der Bindestrich noch entfernt werden.
- [ ] Und bei dem Abstract sind Umbrüche enthalten.

![image](https://user-images.githubusercontent.com/57000004/166424411-fd3d1d2f-abb2-44d3-8f4a-977d091889aa.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
um die Umbrüche kann ich mich kümmern, der Bindestrich ist da deshalb, weil der Seitenumfang nicht ermittelbar ist. Bei den anderen Artikeln werden die Seitenangaben aus der ersten Seite des nächsten Artikels generiert, beim letzten Artikel ist das nicht möglich. Frau Kellmeyer meinte, in dem Fall sollte man da lieber einen offenen Bindestrich setzen, dass die Nutzer*innen nicht denken, der Artikel wäre sehr kurz, obwohl das gar nicht der Fall ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ok, danke für die Erklärung!

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollten die Zeilenumbrüche nicht mehr drin sein!
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Behoben, vielen Dank!

**Comment by IxKo** [comment]
Im aktuellen Heft werden fast gar keine Abstracts importiert. Und bei einem Artikel wird zwar eines importiert, aber das scheint nicht zum Artikel zu gehören: http://www.stone-campbelljournal.com/the_journal/research/volume-24-issue-2/240203/
![image](https://user-images.githubusercontent.com/57000004/185171077-d9423cf6-a4da-402b-adb1-ec11953261fb.png)
![image](https://user-images.githubusercontent.com/57000004/185171194-57db2970-e313-49df-b327-5249de788866.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Abstracts sollten jetzt korrekt rüberkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun passt es wieder! :-)
