### ISSUE TITLE
ISSN 1100-2298 | Svensk exegetisk årsbok (exegetiskasallskapet) | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1727]
#### URL
https://www.exegetiskasallskapet.se/sea86
  
  
### Problembeschreibung
Ist für diese Seite eventuell etwas für den Mulit-Import möglich?
Die ZS wird zurzeit über E/A erfasst an die O-Ausgabe.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
der Seitenquelltext ist leider für eine automatische Verarbeitung vollkommen ungeeignet strukturiert.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Schade, danke fürs Prüfen!
