### ISSUE TITLE
ISSN 0275-5270 | Word & world | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1728]
#### URL
https://wordandworld.luthersem.edu/issues.aspx?issue_id=166
  
  
### Problembeschreibung
Könnte für diese Seite ein neuer Import-Translator gebastelt werden?
Momentan wird die ZS über E/A an die O-Aufnahme katalogisiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Struktur des Seitenquelltexts eignet sich nicht für eine automatische Verarbeitung über Zotero.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator Word&World müsste es funktionieren.
Seitenzahlen sind leider keine vorhanden auf der Seite.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Dankeschön!
Die Seitenzahlen müssen manuell gesetzt werden, in b_zot vermerkt.
