### ISSUE TITLE
ISSN 0022-2097 | The journal of Jewish studies | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1729]
#### URL
https://www.jjs-online.net/archives/contents
  

### Problembeschreibung
Kann für diese Seite ein neuer Translator entwickelt werden?
Leider scheint es pro Heft nicht eine einzelne Webseite zu geben, sondern ist auf einer Gesamt-Archiv-Seite integriert.
Oder über eine Suche nach einem Volume: https://www.jjs-online.net/contents/search/searchme:/year:/type:all/volume:73/fpage:

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe den Translator ubtue_JJS für diese Zeitschrift geschrieben.
Der Multi-DL funktioniert nur über die Suche, nicht über die Contents-Seite, da hier die URLs nicht aufgelistet sind.
z.B. https://www.jjs-online.net/contents/search/searchme:/year:2022/type:all/volume:73/fpage: funktioniert. Der Einstieg in die Suche ist über https://www.jjs-online.net/archives/search möglich.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt, vielen Dank! 👍
