### ISSUE TITLE
ISSN 1757-2479 Journal for Research into Freemasonry and Fraternalism Falscher Language Code

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#173]
Folgender Artikel: https://journals.equinoxpub.com/index.php/JRFF/article/view/36814
besitzt in 041 einen falschen Language Code eng statt fre. Das Abstract ist zwar auf Englisch, der Titel und das Dokument selbst sind aber auf Französisch.

**Comment by shadeMe** [comment]
Das gleiche Problem wie [hier](https://github.com/ubtue/DatenProbleme/issues/162#issuecomment-464093897). Wie wollen wir denn vorgehen?

**Comment by kdr154** [comment]
In meinen Augen sollte der Titel Vorrang vor dem Abstract haben. Zumindest bei dieser Zeitschrift

**Comment by kdr154** [comment]
Gelöst
