### ISSUE TITLE
ISSN 1530-5228 | Journal for Cultural and Religious Theory | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1730]
#### URL
https://jcrt.org/archives/20.1/index.html

  
### Problembeschreibung
Könnte hier ein neuer Translator entwickelt werden?
Die ZS wird momentan über E/A an die O-Ausgabe katalogisiert und ist LF.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Struktur des Seitenquelltexts eignet sich nicht für eine automatische Verarbeitung über Zotero.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ok, schade und danke fürs Prüfen!

Dann aber ein neues Problem: Der Import über EBSCO bricht ab. (https://web.p.ebscohost.com/ehost/results?vid=1&sid=8fa25522-6631-40ad-8b1a-28aba1f592e9%40redis&bquery=JN+%22Journal+for+Cultural+and+Religious+Theory%22+AND+IK+%2220220101+00021+00001%22&bdata=JmRiPXJlaCZ0eXBlPTEmc2VhcmNoTW9kZT1BbmQmc2l0ZT1laG9zdC1saXZl)

**Comment by IxKo** [comment]
siehe #1796
