### ISSUE TITLE
ISSN 1520-7307 | The Southern Baptist journal of theology | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1731]
#### URL
https://equip.sbts.edu/category/publications/journals/journal-of-theology/sbjt-252-summer-2021/
https://equip.sbts.edu/publications/calvins-view-of-angels/
  
### Problembeschreibung
Ist es hier möglich einen neuen Translator zu schreiben? 
Seitenangaben müssen sehr wahrscheinlich manuell ergänzt werden.

Die LF-ZS wird momentan über E/A erfasst und an die O-Ausgabe katalogisiert. E/A ist dabei scheinbar 1 Heft in Verzug.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator ubtue_SBJT müsste es funktionieren.
Seitenzahlen sind leider keine vorhanden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, sieht gut aus!
