### ISSUE TITLE
Globale QA für 936 h : Seitenangabe nur in arabischen Ziffern - römische Zahlen in $y

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1732]
Laut der [Formatdokumentation](https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4070&kattype=Standard#$p) darf die Seitenangabe nur in arabischen Ziffern angegeben werden.

In den globalen QA-Settings ist es mit der RegEx abgedeckt:
` ^\d+(-\d+)?$`

@socheres :
Durch die Non-Articles wird es vermehrt zu Inhalten kommen, deren Seitenangaben aus römischen Zahlen bestehen (Bsp.: https://brill.com/view/journals/jjs/9/1/article-pi_i.xml?ebody=article%20details). Diese müssten in arabische Ziffern umgewandelt werden und die römischen Zahlen müssten in 4070 $y (nach Vorlageform) mit allen anderen Angaben (Band, Jahr, Heft) umgewandelt werden.
Normalerweise sogar mit der Bandbezeichnung wie bspw. "vol."
Man könnte es aber vereinheitlichen und die Vorlageformen weglassen wie in diesem Bsp.: 
![image](https://user-images.githubusercontent.com/57000004/162441907-9005a4e6-759c-4fb7-ab62-239f45b1de0d.png)

4070 $v9$j2022$a1$p1-4$y9(2020,1), S. i-iv
`<datafield tag="936" ind1="u" ind2="w"><subfield code="d">9</subfield><subfield code="j">2022</subfield><subfield code="e">1</subfield><subfield code="h">1-4</subfield><subfield code="y">9(2020,1), S. i-iv</subfield></datafield>`

**Comment by jriedl** [comment]
Bezug auf ursprüngliche Anmerkung im Issue: Der regex war bisher auf nu und ub28 `^\d+(-\d+)?$`. Auf nu wurde er jetzt testweise auf `^[1-9](?:\d+)?(\W[1-9](?:\d+)?)?$` angepasst.

**Comment by socheres** [comment]
> Laut der [Formatdokumentation](https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4070&kattype=Standard#$p) darf die Seitenangabe nur in arabischen Ziffern angegeben werden.
> 
> In den globalen QA-Settings ist es mit der RegEx abgedeckt: ` ^\d+(-\d+)?$`
> 
> @socheres : Durch die Non-Articles wird es vermehrt zu Inhalten kommen, deren Seitenangaben aus römischen Zahlen bestehen (Bsp.: https://brill.com/view/journals/jjs/9/1/article-pi_i.xml?ebody=article%20details). Diese müssten in arabische Ziffern umgewandelt werden und die römischen Zahlen müssten in 4070 $y (nach Vorlageform) mit allen anderen Angaben (Band, Jahr, Heft) umgewandelt werden. Normalerweise sogar mit der Bandbezeichnung wie bspw. "vol." Man könnte es aber vereinheitlichen und die Vorlageformen weglassen wie in diesem Bsp.: ![image](https://user-images.githubusercontent.com/57000004/162441907-9005a4e6-759c-4fb7-ab62-239f45b1de0d.png)
> 
> 4070 $v9$j2022$a1$p1-4$y9(2020,1), S. i-iv `<datafield tag="936" ind1="u" ind2="w"><subfield code="d">9</subfield><subfield code="j">2022</subfield><subfield code="e">1</subfield><subfield code="h">1-4</subfield><subfield code="y">9(2020,1), S. i-iv</subfield></datafield>`

Das müsste sowohl translatorseitig als auch harvesterseitig in der Pipeline gefixt werden. Liebe @jriedl und @helenanebel, könnt Ihr das übernehmen?

**Comment by jriedl** [comment]
Danke für die Erläuterung.

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
Da ist wohl beim Eintragen was mit dem Escapen schiefgegangen, der Ausdruck muss `^[1-9](?:\d+)?(\W[1-9](?:\d+)?)?$` (nicht `^[1-9](?:d+)?(W[1-9](?:d+)?)?$`) heißen. Ist auf nu aktualisiert.

**Comment by jriedl** [comment]
Auf ub28.

**Comment by IxKo** [comment]
Verspätetes Danke!
