### ISSUE TITLE
ISSN 2050-3040 | Critical Research on Religion (SAGE) | OF bei Non-Articles

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1733]
#### URL
https://doi.org/10.1177/20503032221075377
 ub28: 9D7B12763A087BDD34DCB02485432B9FB72E1C9B

### Problembeschreibung
Dieser Non-Article ist in den Errors gelandet. Es handelt sich um einen OF-Artikel.
Er landet in den Errors, weil die Daten für eine Zugehörigkeit zu einem Band/Heft noch fehlt.

![image](https://user-images.githubusercontent.com/57000004/162988265-a194aad3-1ed6-45c3-a0ac-982987daf181.png)

![image](https://user-images.githubusercontent.com/57000004/162988591-439d662b-657e-4ac8-aebf-60c64dca5ac5.png)

Sollte er nicht besser als OF erkannt werden?

**Comment by jriedl** [comment]
Momentan greift die OF-Erkennung explizit nur bei den Records, die Artikel sind, also genau nicht bei den Notes. Falls man immer davon ausgehen kann, dass Notes mit einer Band/Heft-Angabe geliefert werden und sie sich diesbezüglich nicht von Artikeln unterscheiden, kann man dieses Kriterium rausnehmen.

**Comment by jriedl** [comment]
Wie besprochen, wurde die OF-Einschränkung nun entfernt. Der aktuelle Stand findet sich auf nu.

**Comment by IxKo** [comment]
Ich glaube, es funktioniert noch nicht, denn es müsste bei diesem Artikel ([https://doi.org/10.1177/00033286221078801](https://doi.org/10.1177%2F00033286221078801)) auf Nu mit Try url unter "Records" Skipped (online-first): 1 anstatt 0 erscheinen.

![image](https://user-images.githubusercontent.com/57000004/169971303-bba4f978-5456-4968-a5ef-48e013f14062.png)

Bei einem normalen Artikel (https://doi.org/10.1177/00033286221079226) aus diesem Heft, der ebenfalls OF ist, wird es bei Try url korrekt erkannt:
![image](https://user-images.githubusercontent.com/57000004/169971637-14514683-bb30-41ed-a053-34f0467fd232.png)

**Comment by jriedl** [comment]
Das war dann ein Missverständnis. Laut dem Screenshot zu Beginn des Issues habe ich es so interpretiert, dass es um die Auszeichnung als OF in der "Delivered records"-section geht. Bei dem letzten Kommentar geht es darum, dass OF-Notes-Records gar nicht erst erstellt werden. Die Anpassung für Letzteres ist nun auf nu.

**Comment by jriedl** [comment]
Der Unterschied ist das "Include Online First" in der graphischen Oberfläche, das ja normalerweise nicht aktiv ist. Wenn die OF-Records aber immer sofort verworfen würden, würden sie jeden Tag wieder heruntergeladen. Deshalb sind die OF bei den automatisierten Durchläufen auf nu und ub28 eingebunden und werden bis zu einem "Reset" des Artikels nicht mehr heruntergeladen. ub28 wurde gerade aktualisiert.
