### ISSUE TITLE
ISSN 2657-3555 | European journal for the study of Thomas Aquinas (Sciendo) | Translator-Verfügbarkeit

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1734]
#### URL
https://sciendo.com/issue/EJSTA/39/1
  
#### Import-Translator
ubtue_Sciendo.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Der ubtue-Sciendo.js Translator wird mir nicht angeboten, obwohl er in meinem Zotero-Ordner ("W:\Fachinformationsdienste\Zoterobearbeitung\zotero_ko\translators\ubtue_Sciendo.js") vorhanden ist.

Auch ein Update der Translators über die Erweiterungsoptionen half nicht.

**Comment by IxKo** [comment]
Auch bei der ZS "Perichoresis" (ISSN 2284-7308) wird mir der Translator nicht angeboten.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollte der Translator wieder funktionieren. LF-Tags, Keywords und Rezensionskennzeichnungen habe ich auch gleich übernommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt, danke!
