### ISSUE TITLE
ISSN 0023-9054 | Laval théologique et philosophique (Erudit) | Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1736]
#### URL
https://www.erudit.org/fr/revues/ltp/2020-v76-n3-ltp06576/1084136ar/
  
#### Import-Translator
Erudit.js
(nur Einzel-Import möglich)
  
### Problembeschreibung
Das zweite (englische) Abstract wird nicht nach Zotero importiert.

![image](https://user-images.githubusercontent.com/57000004/165303200-653ce814-cdc3-4a35-a867-2ce892d0b422.png)

![image](https://user-images.githubusercontent.com/57000004/165303769-0048ba9a-48f1-44cb-b777-e9250116a4d7.png)

**Comment by IxKo** [comment]
Danke, klappt.
Ein Mehrfach-Import ist bei der Seite generell nicht möglich, oder? @helenanebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
hier sollte jetzt auch Multi-DL möglich sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert!
