### ISSUE TITLE
ISSN 0023-9054 | Laval théologique et philosophique (Erudit) | URI

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1737]
#### URL
https://id.erudit.org/iderudit/1084136ar
  
#### Import-Translator
Erudit.js
(nur Einzel-Import möglich)
  
### Problembeschreibung
Die Website bietet neben einem DOI auch einen URI an.
Gibt es eine Möglichkeit diesen anstatt der "normalen" URL abzugreifen?

![image](https://user-images.githubusercontent.com/57000004/165306287-979aea30-a848-4665-8fbf-12f61634510a.png)

![image](https://user-images.githubusercontent.com/57000004/165306402-64dd5f89-bcd0-4648-9823-7cc5e2233f2f.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die URI müsste jetzt nach Zotero übernommen werden.
Viele  Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert!
