### ISSUE TITLE
JSTOR-Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1739]
#### Beispiel-URL
https://www.jstor.org/stable/e27086990?refreqid=fastly-default%3A9bf308856e6cc3c1b62b9f25894270d4
  
### Problembeschreibung
Es wird kein Translator für den Multi-Import angeboten und auch ein Einzel-Import ist nicht mehr möglich.
(Memo: betrifft auch Koop)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das müsste jetzt wieder funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Wunderbar, tut nun, danke!
