### ISSUE TITLE
ISSN 1783-1423 | Ephemerides Theologicae Lovanienses | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1740]
#### URL
Nu-Hash: 13C3135FC56CEE97E2CDE7B249337A0C91FFF68E
https://poj.peeters-leuven.be/content.php?url=article&id=3290286
  
### Problembeschreibung
Der Titel "Book Reviews" wird auf Nu nicht als Rezension gekennzeichnet.
![image](https://user-images.githubusercontent.com/57000004/166450667-1a8b9385-e22e-4d8a-9792-bed0ea1b058c.png)

**Comment by jriedl** [comment]
Für die non-arcticles wird wie für die Rezensionen das wird intern das Feld `metadata_record->item_type` verwendet. Implizit wurde/wird davon ausgegangen, dass ein Artikel nicht gleichzeitig eine Rezension und ein non-article sein kann. Aktuell findet sich im `zotero_notes_regex`  noch der Ausdruck `...|Book\sReviews?|...`. Es werden also beide Fälle gematched und der letzte "gewinnt". Wird der Ausdruck aus `zotero_notes_regex` entfernt, wird die Rezension wie erwartet ausgezeichnet.

**Comment by IxKo** [comment]
Für die Titel "Recensiones", die sowohl Notes als auch Rezensionen sind, wurde es irgendwie behoben: https://github.com/ubtue/DatenProbleme/issues/1685#issuecomment-1057090419

Das Problem wird auch bei dem Titel "Études critiques" (auch Rezensionen ohne Autor:innen-Vermerk -> kein Marc 100a): https://github.com/ubtue/DatenProbleme/issues/1741

**Comment by IxKo** [comment]
Ich habe den Titel in der globalen zotero_review_regex ergänzt.
Ich hatte vergessen, dass die Zeile auch für Titel gilt. Demnach müsste der Titel zumindest morgen als 655 Rezension gekennzeichnet werden.

**Comment by IxKo** [comment]
Stimmt, als ich "Recensions" ergänzt hatte, war "Recensiones" schon da, und dann kam ich wohl durcheinander.

Es gibt momentan vier Titel, die sowohl keine Autorenangabe haben als auch Rezensionen sind:
- Book Reviews
- Recensiones
- Recensions
- Études critiques

**Comment by jriedl** [comment]
Der Code wurde nun so angepasst, dass die Eigenschaft Note und Rezension nun zusammen auftreten können. Aktueller Stand auf nu.

**Comment by IxKo** [comment]
> Der Code wurde nun so angepasst, dass die Eigenschaft Note und Rezension nun zusammen auftreten können. Aktueller Stand auf nu.

Danke, es funktioniert auf Nu. Bitte auch auf ub28 übertragen.

**Comment by jriedl** [comment]
Update erfolgt Anfang nächster Woche.

**Comment by jriedl** [comment]
Aktueller Stand ist nun auf ub28 eingespielt.

**Comment by IxKo** [comment]
Danke, passt!
