### ISSUE TITLE
alle ZS | [auf BENU: Feld 773 $g fehlt] [auf NU: Konvertierung schlägt fehl]

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1742]
#### URL
https://journals.openedition.org/asr/3570
  
#### Import-Translator
ubtue_OpenEdition Journals
  
### Problembeschreibung
Das Feld 773 $g fehlt in der auf BENU generierten MarcXML-Datei. Es wäre gut, wenn dieses wie bisher wieder mitgeliefert werden könnte, da es für die Generierung der modifizierten Anzeigeform relevant ist.
Auf NU schlägt die Konvertierung des Records fehl, der Fehlermeldung nach zu urteilen, könnte dies mit den römischen Seitenzahlen zu tun haben.

Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Auf benu gab es beim Harvester keine Änderungen seit Ende März, insfern sollte sich an der Logik nichts geändert haben.
Wie und mit mit welcher Zeitschrift wurde denn auf nu getestet? Mit "Revue des sciences religieuses" wird mit obiger URL bei tryURL ein Record erstellt, allerdings ist das ja wohl eine andere Zeitschrift (rsr statt asr), das gibt es in der reguären conf aber offenbar gar nicht.

**Comment by jriedl** [comment]
Nachtrag: Die Erzeugung von 773$g hat derzeit das Vorhandensein einer Volume-Angabe zur Voraussetzung, diese scheint hier nicht vorzuliegen.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
vielen Dank für die Erläuterung. Dann liegt es daran. Auf NU funktioniert es mittlerweile, das war wohl gestern vor der Änderung noch nicht so.
Es wäre sehr gut, wenn auch in solchen Fällen ohne Volume-Angabe 936 $y, da sonst aus den Angaben nicht hervorgeht, dass ursprünglich römische Seitenzahlen vorgelegen haben.
Die 773 $g wäre gut, weil dann auch im RetroTheo die entsprechende Angabe in 936 $y belegt werden kann.
Falls das möglich ist, wäre eine kurze Rückmeldung schön, ansonsten würde ich das in meinem Skript entsprechend anpassen, dass die Angaben dann entsprechend aus den anderen Feldern übernommen werden.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Auf nu gab es gestern keine Änderungen. Die 936$y-Logik mit römischen Ziffern sollte bereits auf nu vorhanden sein. Für benu sollte dies mit dem nächsten Update mitkommen, hier würde ich falls möglich gerne die Migration auf Ubuntu (vsl. nächste Woche) abwarten. Für 773$g müsste geklärt werden, wie die Anzeige aussehn sollte, falls "volume" nicht vorhanden ist, also z.B. dann das Issue vor der Jahreszahl?

**Comment by helenanebel** [comment]
Lieber @jriedl 
Tatsächlich muss in diesem Fall die Issue-Nummer als Volume übernommen werden lt. Katalogisierungsregel. Ich habe das im Translator geändert, damit wird jetzt auch $g wieder generiert. Das war mein Fehler.
Bei mir wird allerdings für die o.g. URL $y trotzdem nicht generiert:
![grafik](https://user-images.githubusercontent.com/49190455/166639015-3ae47523-00ad-43bb-9a19-61ced75cb47d.png)
Wenn die Seitenzahlen in arabische Zahlen konvertiert werden, sollte $y belegt werden: "Die Angabe im Unterfeld $p muss immer in arabischen Ziffern erfasst werden. Liegt eine Seitenzählung in nicht ausschließlich arabischer Zählung vor, wird empfohlen, das Unterfeld $y zu belegen" (siehe https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiZq76QsMX3AhVQ_rsIHWDzD8gQFnoECCYQAQ&url=https%3A%2F%2Fopus.k10plus.de%2Ffrontdoor%2Fdeliver%2Findex%2FdocId%2F415%2Ffile%2FK10plus_Unselbststaendige_Werke.pdf&usg=AOvVaw1_wH4XBv3TABX6KtQwYkO_)
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Bedeutet das, dass das Issue nun translatorseitig nun als Volume ausgespielt wird? Dann scheint eine Änderung, dass 773$g im Harvester bereits erzeugt wird, wenn das Issue existiert, als die sauberere, weil allgemein gültige Lösung. Wo kommt der Screenshot her (nu?, benu?). Auf benu sind die letzten 936-Änderungen noch nicht drin, da wir mittlerweile einiges an Code haben, der auf CentOS nicht mehr übersetzt. Deshalb die Bitte, hier zu warten, bis nächste Woche der neue benu ganz aufgesetzt ist.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
in dem Fall, wenn es nur eine Angabe zum Issue gibt, wird diese grundsätzlich als Volume erfasst. Es wäre sicherlich gut, das so zu implementieren, dann wäre es auch nicht nötig, das jeweils im Translator zu ändern.
Der Screenshot kommt von BENU, das Feld 936 sieht aber auf NU im Ergebnis genau gleich aus, auch hier wird $y nicht generiert.
Eventuell wurde die Änderung im Translator von Issue- zu Volumeangabe auf NU bereits umgesetzt oder der Harvester auf NU macht diese Änderung automatisch.
Es wäre auf jeden Fall sehr gut, wenn die Angabe von $y dann nach der Änderung auf BENU eingeführt werden kann.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Wie genau wurde auf nu getestet? (tryUrl? mit Auswahl welcher Zeitschrift?). 936$y wird nur erzeugt, vorher bereits 773$g erzeugt wurde und römische Ziffern in den pages sind. Bezüglich der Volume/Issue-Behandlung sollte es keinen Unterschied zwischen nu und benu geben. Für den Fall, wo es nur ein Issue gibt, würde nun das Format  `issue (year), S. pages` für 773$g integrieren.

**Comment by helenanebel** [comment]
Gestestet wurde auf NU mit tryURL und Default, da die ZS nicht hinterlegt ist.
In diesem Fall sind römische Ziffern in den pages, deshalb sollte auch $y generiert werden.
773 $g wurde auf NU nicht generiert, sondern nur auf BENU.
Es wäre schön, wenn $g dann in dem Format ausgegeben werden könnte.

**Comment by jriedl** [comment]
Das erklärt ja dann das Verhalten: Auf benu gibt es zwar 773$g, aber noch nicht die Logik für 936$y. Auf nu wird kein 773$g erzeugt, deshalb wird die 936$y-Logik gar nicht erst aktiv. Sollte nach den 773$g-Anpassungen für die Issue-Behandlung dann auf nu funktionieren.

**Comment by jriedl** [comment]
Anpassungen jetzt auf nu.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
vielen Dank, das sieht sehr gut aus.
Ich lasse das Issue dann noch offen, bis die Änderungen auch auf BENU sind.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Auf benu-neu.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
funktioniert nun auch auf BENU. Vielen Dank.
Viele Grüße, Helena Nebel
