### ISSUE TITLE
2055-222X | Occasional papers on religion in Eastern Europe (George Fox University) | Herunterladen Abstract

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1747]
[URL](https://digitalcommons.georgefox.edu/ree/vol42/)

  
#### Import-Translator
COinS
(Einzel-Import)
  
Abstract wird nicht heruntergeladen, obwohl auf Website

(ebenso bei 2009-7379  | International Journal of Religious Tourism and Pilgrimage (Dublin Institute of Technology) - ebenfalls Einzelimport mit COinS)

**Comment by RelBibRetroKat** [comment]
Linkbeispiel für Artikel von International Journal of Religious Tourism and Pilgrimage
https://arrow.tudublin.ie/ijrtp/vol10/iss1/2/

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
vielen Dank!

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
handelt es sich bei der ersten Zeitschrift um eine Open-Access-Zeitschrift?
Dann könnte ich das im Translator hinterlegen.
viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena,

Occasional papers on religion in Eastern Europe ist eine Open Access-Zeitschrift. Es ist in den Zotero-enhancement-maps hinterlegt.

Viele Grüße

Sybille

Von: helenanebel ***@***.***>
Gesendet: Mittwoch, 25. Mai 2022 11:25
An: ubtue/DatenProbleme ***@***.***>
Cc: Deselaers, Sybille ***@***.***>; Mention ***@***.***>
Betreff: Re: [ubtue/DatenProbleme] 2055-222X | Occasional papers on religion in Eastern Europe (George Fox University) | Herunterladen Abstract (Issue #1747)


Liebe @RelBibRetroKat<https://github.com/RelBibRetroKat> ,
handelt es sich bei der ersten Zeitschrift um eine Open-Access-Zeitschrift?
Dann könnte ich das im Translator hinterlegen.
viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
ach so, vielen Dank!
Ich habe einen neuen Translator ubtue_georgefox_tudublin.js geschrieben, mit diesem müssten alle Metadaten übertragen werden und die Artikel-ID wird auch korrekt importiert.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet, auch für International Journal of Religious Tourism and Pilgrimage. Funktioniert gut. Vielen Dank
