### ISSUE TITLE
Bitte um Anpassung der Anzeige im IxTheo

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1748]
Liebe Kolleg*innen,
@AleAprile und ich würden gerne hinter den URLs einer bestimmten Plattform (ePeriodica), deren Aufsätze hinter einer Moving Wall liegen und dann Open Access verfügbar werden, die Angabe einblenden, ab wann diese URLs tatsächlich genutzt werden können. Wir würden diese Bemerkung gerne irgendwo unterbringen.
https://www.e-periodica.ch/digbib/view?pid=rtp-003:2021:153::436
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Zusammenfassung Vorschläge aus dem Meeting:
- Feld 866 belegen mit einer Bemerkung, in der das drinsteht und die Links entfernen (Problem: alle Datensätze müssten jede Nacht geprüft werden, ob das Embargo abgelaufen ist)
- Feld 866 belegen mit einer Bemerkung und diese hinter den Links in 856 im IxTheo einblenden (Problem: die Bemerkung wird mit dem Ablauf des Embargos obsolet)
- Feld 866 belegen und Feld 856 nicht belegen, die 856 erst mithilfe der Daten aus 856 belegen, wenn die Links gültig werden (Problem: Links fehlen im K10plus dauerhaft)
- Feld 856 $y belegen (Problem: die Bemerkung wird mit dem Ablauf des Embargos obsolet)

**Comment by jriedl** [comment]
Wie besprochen: Derzeit wird 856y im IxTheo nicht angezeigt. Es gibt bereits eine ganze Reihe von Einträgen mit 856y, allerdings recht heterogen bzw. es wirkt z.T redundant zu $x/$3: [856y.txt](https://github.com/ubtue/DatenProbleme/files/8652207/856y.txt).

**Comment by helenanebel** [comment]
Lieber @jriedl , lieber @socheres ,
welche Option wäre denn deiner/Ihrer Meinung nach zu bevorzugen? Ich würde vorschlagen, 856 $y zu belegen und in die Anzeige zu übernehmen.
Es wäre ja vermutlich auch möglich, wenn das erwünscht ist, nur zwei Mal im Jahr die Datensätze mit einem in 856 $y angegebenen Embargo zu prüfen und bei Ablauf des Embargos $y zu entfernen und $z zu LF zu ändern.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Das Problem bei einer reinen Generierung aus 866 ohne Belegung von 856 ist, dass im K10plus der Link nie angezeigt werden würde, da ja kein Link in 4950 vorhanden ist.

**Comment by jriedl** [comment]
> Das Problem bei einer reinen Generierung aus 866 ohne Belegung von 856 ist, dass im K10plus der Link nie angezeigt werden würde, da ja kein Link in 4950 vorhanden ist.

Aber wäre das nicht genau der Vorteil, dass bei Nachnutzung von anderen Systemen nicht sichergestellt sein muss, dass $y tatsächlich angezeigt wird. Für "uns" könnten wir ja sogar ein "selbstdefniertes" 856-Unterfeld anstatt $y verwenden, dann hätten wir die "Schrott"-Einträge aus den anderen Datensätzen schon mal weg, bzw. müssen sie nicht gesondert behandeln. Und in regelmäßigen Abständen könnte dann ein Skript laufen, das im K10Plus Einträge nach Embargoablauf von LOK866 ins "echte" 856 schiebt.

**Comment by helenanebel** [comment]
Wir wollen ja eigentlich nicht, dass im K10plus gar keine Links angezeigt werden.

**Comment by jriedl** [comment]
Aber solange sie ohnehin nicht funktionieren, nützen sie doch auch nichts. Und wenn sie funktionieren, würden sie so mit einem bestimmten Zeitversatz angezeigt.

**Comment by helenanebel** [comment]
Können wir denn sicherstellen, dass in regelmäßigen Abständen beim BSZ ein Skript läuft, das im K10Plus Einträge nach Embargoablauf in 4950 schiebt? Wenn wir das sicherstellen können, dann können wir das machen.

**Comment by jriedl** [comment]
Nein, das war ja oben die Frage, ob das geht. @socheres

**Comment by jriedl** [comment]
> Können wir denn sicherstellen, dass in regelmäßigen Abständen beim BSZ ein Skript läuft, das im K10Plus Einträge nach Embargoablauf in 4950 schiebt? Wenn wir das sicherstellen können, dann können wir das machen.

@helenanebel Falls es nicht oder nur schwierig geht, wäre die Lösung, 856$y zu verwenden und diesem Fall betroffenen y-Einträge in ein anderes Feld zu kopieren und nur dieses anzuzeigen, akzeptabel?

**Comment by helenanebel** [comment]
Ja, natürlich, das fände ich gut. Wäre es in diesem Fall aber nicht besser, wenn man einfach $y nur unter ganz bestimmten Bedingungen anzeigt? Also z.B. in 866 hinterlegt, dass $y angezeigt werden soll?

**Comment by jriedl** [comment]
> Ja, natürlich, das fände ich gut. Wäre es in diesem Fall aber nicht besser, wenn man einfach $y nur unter ganz bestimmten Bedingungen anzeigt? Also z.B. in 866 hinterlegt, dass $y angezeigt werden soll?

Damit würde die Trennung zwischen Anzeigelogik und Daten aufgebrochen und es ist eine spezielle Funktion beim Import notwendig. Ein Kopieren kann im Vorfeld in der Pipeline stattfinden, danach kommen nur noch Standardmechanismen zum Einsatz.

**Comment by socheres** [comment]
Ich bin für Option 3 "Feld 866 belegen und Feld 856 nicht belegen, die 856 erst mithilfe der Daten aus 866 belegen, wenn die Links gültig werden (Problem: Links fehlen im K10plus dauerhaft)". Das 856-Feld können wir dann nach Embargoablauf mit dem WinIbw-Skript anreichern.

**Comment by helenanebel** [comment]
Lieber @jriedl , lieber @socheres ,

gut, dann generiere ich ein entsprechendes Feld 866 mit EMBARGO#[TT.MM.JJJJ]#[URL]# in den entsprechenden Daten und entferne alle Felder 856.

Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @jriedl , lieber @socheres ,
ich habe jetzt die ersten entsprechenden Datensätze in die Test-Datenbank der WinIBW eingespielt. 
Einer sieht z.B. so aus:
0100 1791705162
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
0575 mteo
1100 2021
1500 ger
1505 $erda
2051 10.5169/seals-953594
2240 KXP: 1791705162
3000 Kähler, Sophia$7gnd1160741816$BVerfasserIn$4aut
4000 Who is who in Babylonia? : Identity and belonging in the prayer for the Babylonian city (Jer 29:7)
4070 $v77$j2021$a2$p102-119
4241 Enthalten in[!1742830242!](pica3://cbst7.k10plus.de:1790,1,67062/?%5Czoe+IDN+1742830242)Theologische Zeitschrift / Universität Basel$bTheologische Fakultät ; ID: gnd/2023663-3. - Basel : Reinhardt, [1945]- ; ZDB-ID: 3048623-3$x202100000770002898
5056 1
8910 $aixzom$bAutor in der Zoterovorlage [Kähler, Sophia] maschinell zugeordnet
E001 24-05-22 : l01
**4802 EMBARGO#01.01.2023#https://doi.org/10.5169/seals-953594**
7100 $BTü 135$Jn
7811 IxTheo#2022-05-19#0C1DE6A7605494ED0970B88974957518BB91FCDC
7901 TUIXTH:24-05-22
7902 24-05-22
7903 24-05-22 07:34:31.000
8012 ixzs$aixrk$azota
7800 4041667143
ist das so in Ordnung?

Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Aus meiner Sicht ja. Bitte kurzer Hinweis, wenn ein erster Datensatz in unseren (MARC-)Bestand eingeflossen ist, dann kann das Rewriting getestet werden.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
es sind jetzt Datensätze vorhanden, z.B. https://ixtheo.de/Record/1805983857 und weitere an dieser Zeitschrift.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Auf ptah.

**Comment by helenanebel** [comment]
Vielen Dank, sieht gut aus!
