### ISSUE TITLE
ISSN 2699-3414 | Berliner Theologische Zeitschrift (DeGruyter) | OA, Zusatztitel, Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1749]
#### URL
https://www.degruyter.com/document/doi/10.1515/bthz-2021-0004/html
  
#### Import-Translator
ubtue_DeGruyter.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung

- [x] Der OA-Aufsatz wird nicht als solcher mit Notiz in Zotero gekennzeichnet.
- [x] Der Zusatztitel wird nicht nach Zotero importiert.
- [x] Es wird nur das deutsche Abstract importiert.

![image](https://user-images.githubusercontent.com/57000004/167793312-b12b971d-64c4-46d6-8f3e-c81cc689da44.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
es sollte jetzt alles stimmen.
Viele Grüße, Helena Nebel
