### ISSUE TITLE
Translator für neue Plattform "Scholary Publishing Collective"

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1750]
#### Bsp-URL
https://scholarlypublishingcollective.org/psup/biblical-research/issue/31/4
  
#### Import-Translator
???
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Könnte für diese Plattform ein Translator für das halbautomatische Verfahren entwickelt werden?

Es hat meist Abstract und Keywords: https://doi.org/10.5325/bullbiblrese.31.4.0478

Beispiel für Rezension: https://doi.org/10.5325/bullbiblrese.31.4.0578

**Comment by helenanebel** [comment]
Liebe @IxKo ,
der neue Translator ubtue_scholarlypublishing müsste alle Daten übertragen, auch Keywords, Abstracts und Rezensionen.
Single- und MultiDL.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke! Funktioniert wunderbar!
