### ISSUE TITLE
ISSN 2284-7308 | Perichoresis (Sciendo) | Titel kursiv 

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1751]
#### URL
1) https://doi.org/10.2478/perc-2021-0022
2) https://doi.org/10.2478/perc-2021-0021
  
#### Import-Translator
ubtue_Sciendo.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Es werden nur Titelteile ohne kursiver Schrift importiert:
**Fall 1**
![image](https://user-images.githubusercontent.com/57000004/167823155-534f9c13-3015-4902-821b-6198cced101d.png)
![image](https://user-images.githubusercontent.com/57000004/167823319-5463a9dd-0f09-4a0d-9abe-4ead07684aa3.png)

**Fall 2**
![image](https://user-images.githubusercontent.com/57000004/167823768-bb5a71d5-6e8e-42f2-89e8-ea77d112be0f.png)
![image](https://user-images.githubusercontent.com/57000004/167823874-eba94c4b-2b93-41d1-b57e-da0ce8237405.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollten die Titel komplett nach Zotero importiert werden!
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun kommt das Kursive mit - allerdings wird es beim Mehrfach-Import in der Auswahl nicht angezeigt, aber das ist nicht schlimm:
![image](https://user-images.githubusercontent.com/57000004/173837780-311fc3dc-9d3e-422e-b786-d43139c102f3.png)
