### ISSUE TITLE
ISSN 2413-3027 | Journal for the study of religion (SciELO) | Abstract und Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1752]
#### URL
http://www.scielo.org.za/scielo.php?script=sci_abstract&pid=S1011-76012021000200002&lng=en&nrm=iso&tlng=en
  
#### Import-Translator
ubtue_SciELO.js
(nur Einzel-Import möglich)
  
### Problembeschreibung
Das Abstract wird nicht nach Zotero importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Abstract müsste jetzt mitkommen und Multi-DL müsste auch möglich sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert alles!
