### ISSUE TITLE
Absturz WinIBW Batch-Upload

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1753]
### Problembeschreibung
Die WinIBW ist mir heute schon zweimal abgestürzt, obwohl ich nur 16 Datensätze über Batch-Upload geladen habe.
Es erscheint dann dieses Fehlermeldungs-Fenster:

![image](https://user-images.githubusercontent.com/57000004/168043082-c3eda0fe-9d7b-4be1-bfc7-42203441304d.png)

Danach schließt sich das Programm und danach muss man prüfen, welche der x Datensätze vor dem Absturz eingespielt wurden und welche nicht.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
wir können daran leider nichts ändern.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Schade
