### ISSUE TITLE
ISSN 2053-6712 | Secularism and Nonreligion | ORCID, Artikelnummern, Ausgabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1754]
#### URL
https://secularismandnonreligion.org/articles/10.5334/snr.151/#
  
#### Import-Translator
Ubiquity Journals.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung

- [x] Die Autor:innen haben teils eine ORCID-Angabe. Diese wird noch nicht nach Zotero importiert.

![image](https://user-images.githubusercontent.com/57000004/168046297-9b6504dc-2477-48cd-9dd8-3c81dd54a1e6.png)

- [x] Die Artikel haben Artikelnummern, die als Seitenangabe importiert werden.
- [x] Es wird eine Ausgabe/Heftzählung importiert, obwohl es keine gibt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
sowohl im Seitenquelltext: 
![grafik](https://user-images.githubusercontent.com/49190455/170975396-c48db031-2fe9-49d6-8305-732f78cf348e.png)
als auch in der angegebenen Zitierweise:
![grafik](https://user-images.githubusercontent.com/49190455/170975467-2d2b3405-4ef7-487f-a9fd-62b97aaeec1f.png)
wird ein Issue genannt. Soll dieses dann tatsächlich nicht übernommen werden?
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ArtikelID und die ORCID müssten mit "ubtue_Ubiquity Journals" jetzt korrekt rüberkommen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe die Heftzählung entfernt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, passt alles!
