### ISSUE TITLE
1527-6457 | Journal of global buddhism | DL von Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1755]
#### URL
http://www.globalbuddhism.org/jgb/index.php/jgb/issue/view/38
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Mehrfach-Import)
  
### Problembeschreibung
Die Rezensionen werden beim Multi-Import nicht berücksichtigt bzw. sind nicht auswählbar:
![image](https://user-images.githubusercontent.com/57000004/168054961-3e698acc-e2dc-4e38-8ece-1c4c235041e8.png)

**Comment by IxKo** [comment]
Danke, sie sind beim Mehrfach-Import nun gelistet, allerdings werden sie noch nicht als Rezensionen getagt.

**Comment by helenanebel** [comment]
Liebe @IxKo .
nun müssten die Rezensionen auch gekennzeichnet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, hat alles wunderbar geklappt!
