### ISSUE TITLE
ISSN 0718-4727 | Revista Cultura y Religión (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1756]
#### URL
https://www.revistaculturayreligion.cl/index.php/revistaculturayreligion/article/view/1032
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die ORCIDs werden nicht nach Zotero importiert.

![image](https://user-images.githubusercontent.com/57000004/168273719-605e2b3f-f8b6-44a2-8df6-72166c756f54.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ORCIDS müssten jetzt übernommen werden.
Viele Grüße, Helena Nebel
