### ISSUE TITLE
ISSN 0776-3824 | Kernos (Open Edition) | DOI

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1757]
#### URL
https://journals.openedition.org/kernos/3913
  
#### Import-Translator
ubtue_OpenEdition Journals.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Der DOI wird nicht nach Zotero importiert. Bei den Artikeln wie diesen: https://journals.openedition.org/kernos/3881 hingegen schon.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
der DOI müsste jetzt mitkommen.
Viele Grüße, Helena Nebel
