### ISSUE TITLE
ISSN 0555-9308 | Zeitschrift für Pastoraltheologie | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1759]
#### URL
https://www.uni-muenster.de/Ejournals/index.php/zpth/article/view/3180
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Könnten die beiden Abstracts voneinander getrennt werden?
![image](https://user-images.githubusercontent.com/57000004/168613399-feffe15e-39c3-48c3-ab67-3a3bea05acec.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
leider sind die beiden Abstracts nur durch einen Zeilenumbruch getrennt, ich habe diesen jetzt für diese Zeitschrift durch \n4207 ersetzt. Es kann allerdings sein, dass das zu unerwünschten Effekten führt, bitte beachten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, doch es scheint das n zu fehlen:
![image](https://user-images.githubusercontent.com/57000004/173861483-0bea278d-76a7-4fea-ad10-16112950ec3f.png)

**Comment by IxKo** [comment]
Sehr gut, jetzt fehlt nur noch ein Leerzeichen nach dem zweiten 4207-Feld ;-)
![image](https://user-images.githubusercontent.com/57000004/178987866-df8db800-8f54-4a36-9e2e-c512467b51b9.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das Leerzeichen ergänzt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt, danke!
