### ISSUE TITLE
ISSN 2047-7058 Journal for the Academic Study of Religion Html-Code

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#176]
In der XML-Datei dieser ZS findet sich immer mal wieder Html-Code, etwa im Abstract von 
https://journals.equinoxpub.com/index.php/JASR/article/view/35224

**Comment by kdr154** [comment]
Ich habe jetzt den Cache im Firefox gelöscht, den aktuellen Translator vom Repository geholt, aber leider gibt es jetzt noch größere Probleme insofern, als der Translator jetzt gar nicht mehr zu funktionieren scheint. Im Firefox öffent sich jetzt kein Fenster mehr, das den Download anzeigt. Es wird zwar etwas in Zotero übertragen, die Daten sind aber rudimentär. Außer einem Titelsnippet und der URL kommt nichts an.

**Comment by shadeMe** [comment]
Ganz komisch. Ich habe gerade die obige URL getestet und sie hat auch heute nicht funktioniert. Die Fehlermeldung weist aber auf ein serverseitiges Problem hin. Es kann einfach dran liegen.

**Comment by shadeMe** [comment]
Das Serverproblem scheint gelöst zu sein. Bitte nochmal testen (auf nu und lokal).

**Comment by kdr154** [comment]
Der HTML-code bei oben genanntem Aufsatz findet sich weiterhin im Abstract.

**Comment by kdr154** [comment]
ok
