### ISSUE TITLE
ISSN 2617-1953 | Limina (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1760]
#### URL
https://limina-graz.eu/index.php/limina/article/view/131
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die ORCID-Angabe wird nicht nach Zotero importiert.
![image](https://user-images.githubusercontent.com/57000004/168774478-ef1fbba1-68ff-44aa-9d74-05ffba4da12b.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ORCID sollte jetzt mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, ORCID ist nun dabei!
