### ISSUE TITLE
ISSN 2174-0887 | Anuario de Historia de la Iglesia (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1762]
#### URL
https://revistas.unav.edu/index.php/anuario-de-historia-iglesia/article/view/42867
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die ORCID-Angabe wird nicht nach Zotero importiert.
![image](https://user-images.githubusercontent.com/57000004/168826017-6f7f4d8d-8c78-4135-abb0-9494fd4ac7d2.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ORCID sollte jetzt mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, tut sie!
