### ISSUE TITLE
ISSN 2174-0887 | Anuario de Historia de la Iglesia (OJS) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1763]
#### URL
https://revistas.unav.edu/index.php/anuario-de-historia-iglesia/article/view/42910
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung

Die Rezensionen (Reseñas:) werden noch nicht mit dem RezensiontagPica gekennzeichnet. Könnte man das machen?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müssten die Rezensionen gekennzeichnet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, wird gekennzeichnet!
