### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift (OJS) | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1764]
#### URL
https://tidsskrift.dk/rvt/article/view/132100
  
#### Import-Translator
ubtue_Open Journal Systems Standard.js
(Einzel- und Mehrfach-Import)
  
### Problembeschreibung
Die beiden Abstracts werden nicht voneinander getrennt importiert und exportiert.
![image](https://user-images.githubusercontent.com/57000004/169009748-e3beac47-d32e-4370-a0e0-3966b7db9e91.png)

Auch auf Nu nicht: 
![image](https://user-images.githubusercontent.com/57000004/169009818-5d9a30c5-b0a9-4494-bbb9-5906149a29ed.png)

Außerdem wird an erster Stelle (auch beim Mehrfach-Import) der ubtue_Tidsskrift angeboten, der nicht zu funktionieren scheint.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müssten die beiden Abstracts getrennt werden.
Es wir davor noch ein leeres Feld 4207 generiert, dieses allerdings sollte keine Probleme machen, ich habe es getestet.
Viele Grüße, Helena Nebel
P.S. Falls das auch auf NU geändert werden soll, bitte das entsprechende Label setzen.

**Comment by IxKo** [comment]
Danke, passt nun, und ein leeres Pica-Feld ist kein Problem.
Bitte auch Nu umsetzen, da die OJS-Plattformen irgendwann in der Zukunft auch auf zota geprüft werden.
Habe hoffentlich das korrekte Label dafür ergänzt.

**Comment by IxKo** [comment]
Perfekt, danke!
