### ISSUE TITLE
2617-3697 | Journal for religion, film and media | Zeder-Translator wird nicht vorgeschlagen

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1765]
#### URL
https://jrfm.eu/index.php/ojs_jrfm/issue/view/15
  
#### Import-Translator
  Mehrfachimport:
  ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
In der Gesamtübersicht wird der in Zeder angegebene Translator ubtue_Open Journal Systems Standard.js nicht als Translator auf der Webseite vorgeschlagen, sondern nur der Translator ubtue_PKP Catalog Systems.js.
Wenn man einen Artikel auswählt, kann man einen Einzelimport mit ubtue_Open Journal Systems Standard.js starten.

Ist es möglich, den Mehrfachimport mit ubtue_Open Journal Systems Standard.js zu ermöglichen?

**Comment by helenanebel** [comment]
Liebe @SchwXC ,
der Mehrfachimport mit ubtue_Open Journal Systems Standard.js müsste jetzt möglich sein.
Viele Grüße, Helena Nebel

**Comment by SchwXC** [comment]
Liebe @helenanebel  ,
der Mehrfachimport funktioniert nun problemlos.

Danke und viele Grüße
SchwXC
