### ISSUE TITLE
ISSN 1947-8224 |  US catholic historian (MUSE) | römische Seitenangabe Umfang 1

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1766]
#### URL
https://muse.jhu.edu/article/855307
Hash 793DE569491030AE436D8EF6FC44A7E3C6A32185
  
### Problembeschreibung

Die römische Seitenangabe wird umgewandelt.
Allerdings umfasst der Datensatz nur eine Seite, die jedoch als Seitenumfang (von bis) durch einen Bindestrich angegeben wird:

```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">40</subfield>
<subfield code="e">2</subfield>
<subfield code="h">1-1</subfield>
<subfield code="j">2022</subfield>
<subfield code="y">40 (2022), 2, Seite i-i</subfield>
</datafield>

```

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das kann jetzt auf NU getestet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun wird nur noch wie es ist, die eine Seite angegeben.
