### ISSUE TITLE
Allgemein: QA-Settings 936 y für römische Seitenangaben

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1767]
### Problembeschreibung
Könnte bitte für das Marc-Feld 936 in den QA-Settings das Unterfeld y als "Sometimes" für alle ZSs hinterlegt werden?
Es wird von uns erzeugt, wenn eine Seitenangabe römische Ziffern aufweist, und kann im Grunde bei jeder ZS mal auftreten.

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
Auf ub28.

**Comment by IxKo** [comment]
Danke!
