### ISSUE TITLE
ISSN 1469-901X | Religious Studies (Cambridge) | OA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1768]
#### URL
https://www.cambridge.org/core/journals/religious-studies/article/new-epistemological-case-for-theism/2DB0673A95B5D023B187B77071E7C93C
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js

  
### Problembeschreibung
Könnten solche einzelnen OA-Artikel bitte als OA erkannt werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müsste der Artikel gekennzeichnet werden und die ORCID sollte ebenfalls mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Perfekt, danke!
