### ISSUE TITLE
ISSN 1469-901X | Religious Studies (Cambridge) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1769]
#### URL
https://www.cambridge.org/core/journals/religious-studies/article/mark-r-wynn-spiritual-traditions-and-the-virtues-living-between-heaven-and-earth-oxford-oxford-university-press-2020-pp-272-6500-hbk-isbn-9780198862949/B88496DF2A80365A7B40063086B357E8
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js

  
### Problembeschreibung
Rezensionen werden nicht erkannt.
Auch auf Nu nicht.

**Comment by helenanebel** [comment]
Anpassung für halbautomatischen Translator:
if (ZU.xpathText(doc, '//dd[@class="col content" and contains(., "Book Review")]') != null) {item.tags.push("RezensionstagPica");}

**Comment by jriedl** [comment]
BItte noch PR für zotaut.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das kann jetzt auf NU & im halbautomatischen Verfahren getestet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert bei beiden Verfahren, und auch schon auf ub28.
