### ISSUE TITLE
ISSN 2049-7563 Journal for the Cognitive Science of Religion HTML

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#177]
Html-Code in 520 bei folgendem Aufsatz:
https://journals.equinoxpub.com/index.php/JCSR/article/view/35722
In 245 hingegen sind die Zeichen umgesetzt

**Comment by kdr154** [comment]
Immer noch drin, etwa hier: 
```
<datafield tag="520" ind1="3" ind2=" ">
<subfield code="a">Turner&rsquo;s Definition and Explanation of Religion</subfield>
```

**Comment by shadeMe** [comment]
Kann nicht reproduzieren. Bitte nochmal test.

**Comment by kdr154** [comment]
Bei diesem Aufsatz: https://journals.equinoxpub.com/index.php/JCSR/article/view/35722
in 520 immer noch vorhanden.

**Comment by shadeMe** [comment]
Das scheint ein Translation-Sever Problem zu sein. Ich setze das Issue auf 'blocked' bis wir ein Lösung finden.

**Comment by shadeMe** [comment]
Gelöst.

**Comment by kdr154** [comment]
ok
