### ISSUE TITLE
ISSN 1469-901X | Religious Studies (Cambridge) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1770]
#### URL
https://www.cambridge.org/core/journals/religious-studies/article/logos-logic-and-maximal-infinity/AAB308630357002F2AA956212FE1643D
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js

  
### Problembeschreibung
Die OCRID wird nicht nach Zotero importiert.
Auch auf Nu nicht.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
im halbautomatischen Verfahren wird die ORCID bei mir mitimportiert. Bitte nochmal testen.
Viele Grüße, Helena

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das kann jetzt auf NU & im halbautomatischen Verfahren getestet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke ist auf Nu und halbautomatisch nun dabei.
Bitte noch auf ub28

**Comment by jriedl** [comment]
Alle im Zusammenhang mit dem PR gemergedten Translatoränderungen sind jetzt auf ub28 eingespielt.
