### ISSUE TITLE
ISSN 1468-0025 | Modern theology (Wiley) | Anmerkungssternchen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1771]
#### URL
https://doi.org/10.1111/moth.12760
hash IxTIxTheo#2022-04-15#BC4C6DD0D73863FC11369E25383E29BFEE16FFFF
    
### Problembeschreibung
Die Anmerkungssternchen am Ende des Titels sollen bitte nicht eingespielt werden:

![image](https://user-images.githubusercontent.com/57000004/170013576-bbc29619-8f9d-4ad9-8554-90683c55c659.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das kann jetzt auf NU getestet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert auf NU, und scheinbar auch auf ub28 - sofern man mit der normalen URL testet und nicht mit dem DOI.
