### ISSUE TITLE
ISSN 1522-5658 | The journal of religion & society (Creighton University) | Ab Bd 20. 2018 Fehler beim Herunterladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1772]
(http://moses.creighton.edu/JRS/toc/Archive.html)

  
#### Import-Translator ub_tue Journal of religon and Society
  Mehrfachimport:
<Name von genutzten Translator (siehe auch: https://github.com/ubtue/zotkat-translators oder Zeder p_zot3)>

  
Die Aufsätze der Jg. 24.2022-21.2019 konnten problemlos heruntergeladen werden. Ab 20. 2018 können einzelne Aufsätze nicht mehr heruntergeladen werden, (Meldung: Ein Fehler ist aufgetreten beim Versuch, diesen Eintrag zu speichern...), ab 18.2016 kann kein Aufsatz mehr heruntergeladen werden.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das müsste jetzt funktionieren, ich habe mit drei Jahrgängen getestet.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
bei mir funktioniert es. Können Sie nochmal testen?
Viele Grüße, Helena Nebel
