### ISSUE TITLE
ISSN 0009-6407 | Church History (Cambridge) | Seiten

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1773]
#### URL
https://doi.org/10.1017/S0009640721002407
  
#### Import-Translator
  Einzel- und Mehrfachimport:
[ubtue_Cambridge Core.js](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Cambridge%20Core.js)

  
### Problembeschreibung
Bei einem Seitenumfang von einer Seite wird ein Seitenumfang von bis importiert und auch so exportiert:

![image](https://user-images.githubusercontent.com/57000004/170238620-54d2a07a-56c3-433b-9e6e-f3f4f9813293.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt behoben sein.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Wunderbar, passt nun, danke sehr!
