### ISSUE TITLE
Allgemein: Personen Look-up

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1774]
#### URL
https://doi.org/10.1017/S000964072100250X

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js
  
### Problembeschreibung

Hier wurde mit einer Person (gnd/1158503814) verknüpft, die seit 10 Jahr verstorben ist:
![image](https://user-images.githubusercontent.com/57000004/170244785-5d6c91e0-4a42-43f0-a899-6755f111bf4d.png)

![image](https://user-images.githubusercontent.com/57000004/170244563-289d1418-b49b-43a3-acf0-b5ed3f174ea8.png)

**Comment by IxKo** [comment]
Und hier wurde eine falsche Person (gnd/124305768) mit gleichen Namen verknüpft: 
https://doi.org/10.1017/S0009640722000555
![image](https://user-images.githubusercontent.com/57000004/170253515-e23d5f69-6a47-4a30-afc8-d6754b21f299.png)

![image](https://user-images.githubusercontent.com/57000004/170253655-3c944cf8-376a-4898-b912-9e4eab87aaeb.png)
https://www.theology.ox.ac.uk/people/professor-mark-edwards-0

Der korrekte Herr ist aber dieser: https://www.arbor.edu/faculty/mark-edwards/
Der noch keinen GND-Satz hatte.

**Comment by IxKo** [comment]
Ein anderer Fall aus dem zota-Verfahren:
IxTheo#2022-10-11#3E6C4F72DD72844DE8E14E31E1CCF91913713C33

Hier wurde mit einer Zahnärztin verknüpft gnd/1015067522
![image](https://user-images.githubusercontent.com/57000004/195818246-94f40488-bc00-4496-92d3-a7aaac0015c4.png)
8910 $aixzom$bAutor in der Zoterovorlage [Adamczyk, Katarzyna] maschinell zugeordnet

**Comment by IxKo** [comment]
Hier wurde eine Person verknüpft, die bereits verstorben ist:
https://www.cairn.info/revue-nouvelle-revue-theologique-2023-3-page-372.htm

3000 [!135641985!](pica3://cbs.k10plus.de:1035-1036,1,198796/?%5Czoe+IDN+135641985)Balthasar, Hans Urs$cvon *1905-1988* ; ID: gnd/118506323

**Comment by IxTheoKm** [comment]
Ist das nicht in diesem Fall korrekt? Da wurde scheinbar ein alter Text abgedruckt.
Oder soll das Look-up nie Lebensdaten vor dem aktuellen Datum berücksichtigen?

**Comment by socheres** [comment]
Beim Lookup werden Personen ab 1900 berücksichtigt(nur bei IxTheo). Hier der Lookup-Parameter für IxTheo https://github.com/ubtue/zotero-enhancement-maps/blob/3d6ca9568e90b7fc3241a74ff4ca198e133e91a1/zotero_harvester.conf#L75 und für RelBib https://github.com/ubtue/zotero-enhancement-maps/blob/3d6ca9568e90b7fc3241a74ff4ca198e133e91a1/zotero_harvester.conf#L80 und für KrimDok https://github.com/ubtue/zotero-enhancement-maps/blob/3d6ca9568e90b7fc3241a74ff4ca198e133e91a1/zotero_harvester.conf#L86
