### ISSUE TITLE
ISSN 1827-790X | Rivista di storia della Chiesa in Italia (vitaepensiero) | Neuer Translator

### ISSUE THREAD

**Issue by IxTheoEg** [ubtue/DatenProbleme#1775]
> die letzt verfügbare Aufsatzdaten sind vom 2018. Neuer Translator für diese Zss. lohnt sich nicht. @kdr154 bitte Issue schließen.
> 
> _Originally posted by @socheres in https://github.com/ubtue/DatenProbleme/issues/605#issuecomment-610351459_

Könnte bei dieser ZS bitte nochmals versucht werden, einen neuen Translator zu entwickeln? Mittlerweile sind schon mehrere neue Hefte erschienen (Link: 
https://www.vitaepensiero.it/scheda-fascicolo_contenitore_digital/autori-vari/rivista-di-storia-della-chiesa-in-italia-2021-2-001783_2021_0002-371437.html

LG IxTheo/Eg

**Comment by helenanebel** [comment]
Liebe @IxTheoEg ,
der neue Translator ubtue_vitaepensiero müsste alle Daten mitnehmen. Seitenzahlen sind leider nicht verfügbar.
Viele Güße, Helena Nebel

**Comment by IxTheoEg** [comment]
Liebe  Frau Nebel,

im Feld 4070 sollte keine $v-Angabe mit dem Jahr stehen. Das müsste geändert werden. 
Was eventuell noch ergänzt werden könnte ist der Zusatz mit $t für die Seitenangabe.

Vielen lieben Dank

IxTheo/Eg

**Comment by helenanebel** [comment]
Liebe @IxTheoEg ,
die Bandangabe habe ich entfernt, die Gesamtzahl der Seiten ist auf der Seite des Artikels nicht vorhanden, sondern nur auf der Übersichtsseite und kann deshalb nicht übernommen werden.
Viele Grüße, Helena Nebel

**Comment by IxTheoEg** [comment]
Bitte versuchen Sie im Translator, die Bandangabe in Feld 4070 noch zu ergänzen.
Vielen Dank
IxTheo, eg

**Comment by socheres** [comment]
Außer Heftnummer sehe ich keine Bandangabe in der Vorlage. Oder meinen Sie, dass die Heftnummer in die Bandangabe übernommen werden sollte?

**Comment by mara-spiess** [comment]
@IxTheoEg @IxKo Die Bandnummer ist nicht in den Metadaten vorhanden.

**Comment by IxKo** [comment]
Ok, muss dann manuell ergänzt werden. Ist in ZEDER vermerkt.
