### ISSUE TITLE
ISSN 2077-1444 | Religions | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1776]
#### URL
https://www.mdpi.com/2077-1444/13/6/474
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_MDPI Jorunals.js

  
### Problembeschreibung
Die ORCID-Angabe wird nicht übertragen.

**Comment by helenanebel** [comment]
An Helena Nebel:
(Anpassung für Zota für ORCID notwendig)
for (let authorSpan of ZU.xpath(doc, '//div[contains(@class, "art-authors")]/span')) {
			let name = ZU.xpathText(authorSpan, './/span[contains(@class, "__name")]');
			let orcid = ZU.xpathText(authorSpan, './/a[contains(@href, "orcid")]/@href');
			if (orcid != null) {
					item.notes.push({note: name + ' | orcid:' + orcid.match(/https?:\/\/orcid.org\/(.+)$/)[1] + ' | taken from website'});
				}
			}
		let toReplace = (item.title + item.abstractNote).match(/(&#\d+;)/g);
		if (toReplace != null) {
		for (let charCode of toReplace) {
			let char = String.fromCharCode(parseInt(charCode.match(/\d+/)[0]));
			item.title = item.title.replace(charCode, char);
			item.abstractNote = item.title.replace(charCode, char);
		}
		}
		item.title = item.title.replace(/&[lr][sd]quo;/g, "'");

**Comment by IxKo** [comment]
Danke, die ORCID wird nun importiert.
