### ISSUE TITLE
ISSN 1660-5578 | Hermeneutische Blätter (OJS) | Band+Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1780]
#### URL
https://www.hermeneutische-blaetter.uzh.ch/article/view/3077
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Es fehlen einige Angaben:

- [x] Band
- [x] Heft

**Comment by helenanebel** [comment]
Liebe @IxKo ,
hatte nicht @thefass bei die Herausgeber gebeten, das anzupassen?
Falls ja, würde ich lieber darauf warten, als einen Workaround zu schreiben, weil das immer fehleranfällig ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, hat er. Warten wir mal ab.

**Comment by thefass** [comment]
Antwort: sie sind dran, es braucht aber seine Zeit, da das neben anderen Aufgaben erledigt werden muss

**Comment by socheres** [comment]
> Antwort: sie sind dran, es braucht aber seine Zeit, da das neben anderen Aufgaben erledigt werden muss

es scheint, dass die Band- und Heftnummern nicht direkt in die OJS eingegeben werden. Es ist suboptimal, aber sie sind in den Z3988 Metadaten vorhanden, und habe die fehlenden Angaben von dort übernommen.

**Comment by IxKo** [comment]
Bei dem eingangs genannten Heft klappt alles.

Doch bei diesem Doppel-Heft (1/2) wird nur eine einzelne Heftnummerierung (1) importiert:
https://www.hermeneutische-blaetter.uzh.ch/issue/view/254
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/cc2c2c0a-3fd9-4822-9123-221d25b9529e)

**Comment by IxKo** [comment]
Danke, beides kommt nun korrekt mit.
