### ISSUE TITLE
ISSN 1660-5578 | Hermeneutische Blätter (OJS) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1781]
#### URL
https://www.hermeneutische-blaetter.uzh.ch/article/view/3077

  
### Problembeschreibung

Beim Testen auf Nu werden die Keywords nicht übertragen.

**Comment by jriedl** [comment]
Betrifft auch #1778, #1779, #1780: Problem ist die `detectWeb()`-Funktion in beiden OJS-Translators (ubtue und normal), diese prüfen derzeit auf das Vorhandensein eines `script`-Tags mit einer Referenz auf `/lib/pkp/js`. Diese scheint bei dieser OJS-Instanz nicht (mehr)  vorhanden. Deshalb erfolgt ein Fallback auf COinS. Wird diese Abfrage entfernt, funktioniert es. Als Workaround wäre zusätzlicher Test auf `/lib/pkp/lib` möglich - das ist im Seitenquelltext vorhanden.

**Comment by jriedl** [comment]
Nachtrag: Das Heftproblem (cf. #1778) ist damit nicht gelöst.
