### ISSUE TITLE
ISSN 1612-9520 | Neue Zeitschrift für Systematische Theologie und Religionsphilosophie (De Gruyter) | Abstract & Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1782]
#### URL
https://www.degruyter.com/document/doi/10.1515/nzsth-2022-0006/html
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_DeGruyter.js

### Problembeschreibung
Es werden nur das engl. Abstract und die engl. Keywords übertragen, die deutschen fehlen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
sollte jetzt beides in Deutsch und Englisch mitkommen.
Viele Grüße, Helena Nebel
