### ISSUE TITLE
ISSN 2194-508X | Zeitschrift für Religionswissenschaft (De Gruyter) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1783]
#### URL
https://www.degruyter.com/journal/key/zfr/29/2/html
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_DeGruyter.js

  
### Problembeschreibung
Die als "öffentlich zugänglich" gekennzeichneten Artikel werden nicht als LF erkannt - die Open Access-Artikel hingegen schon:
![image](https://user-images.githubusercontent.com/57000004/174979184-551d281c-6a58-4513-aee4-79a0be67e888.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
diese Artikel sollten jetzt ebenfalls getagt werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, werden getagt!
