### ISSUE TITLE
ISSN 2295-3027 | Studia Canonica (Peeters) | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1785]
#### URL
https://poj.peeters-leuven.be/content.php?url=article&id=3290159
IxTheo#2022-05-11#42CEE04C2D3500D7484E7CF925C7F2993DBF4B94

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Peeters.js

  
### Problembeschreibung
Die Abstracts werden nicht korrekt voneinander getrennt.

Außerdem wird im zotk-Verfahren keine ISSN übertragen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollten die Abstracts korrekt rüberkommen.
viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Hier war es ja nicht möglich, dass die beiden Abstracts voneinander getrennt werden können, oder?

**Comment by helenanebel** [comment]
Ist nicht auf ready for testing ;-)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollten die Abstracts auch im vollatuomatischen Verfahren korrekt rüberkommen. Es gibt allerdings, da der Seitenquelltext schlecht formatiert ist, Ausnahmen. Ich würde von einer Übernahme ins vollautomatische Verfahren abraten.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke sieht nun gut aus:
![image](https://user-images.githubusercontent.com/57000004/205275022-bbfff997-2bb1-45a4-8197-fc2294208042.png)
