### ISSUE TITLE
ISSN 1863-0502 | Theo-Web | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1786]
#### URL
https://www.theo-web.de/ausgaben/2021/20-jahrgang-2021-heft-2
  
#### Import-Translator
  keiner
  
### Problembeschreibung
Könnte für diese ZS bitte ein Translator entwickelt werden?
Momentan ist es sehr aufwendig und den einzigen Weg, den ich fand, ist über Einzel-Import mit dem Translator DOI, der nicht als erster angeboten wird, bei dem einige Informationen fehlen (bspw. Bandangabe und Keywords) und der auch noch nach dem Klick erst ein gesondertes Fenster öffnet, in welchen der Artikel nochmals ausgewählt werden muss.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator ubtue_TheoWeb sollte alles rüberkommen, aber nur über Multi-DL möglich, da keine Seitenangaben auf den Artikelseiten vorhanden sind.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Dankeschön!
