### ISSUE TITLE
The Innes Review | Edinburgh University Press | ORCID

### ISSUE THREAD

**Issue by SchwXC** [ubtue/DatenProbleme#1787]
#### URL
https://www.euppublishing.com/toc/inr/72/2
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Edinburgh University Press Journals.js

  
### Problembeschreibung

Beim Import in Zotero werden die ORDICs der Autoren leider nicht übernommen. Könnte dies bitte angepasst werden?

![image](https://user-images.githubusercontent.com/101199276/177494889-8db4f089-cacd-4c09-8598-ae66ca365f3b.png)

![image](https://user-images.githubusercontent.com/101199276/177495070-07276b38-f199-491e-bb0a-5519ab7e3e67.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
bitte testen, wenn auf ready_for_testing.
Viele Grüße, Helena Nebel
