### ISSUE TITLE
ISSN 2653-1372 | Reformed Theological Review (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1788]
#### URL
https://rtrjournal.org/index.php/RTR/article/view/308
  
#### Import-Translator
  Einzel- und Mehrfachimport:
(ubtue_Open Journal Systems Standard.js)

  
### Problembeschreibung
Die ORCID-Angabe wird nicht importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müsste die ORCID mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, vielen Dank!
