### ISSUE TITLE
Einspielungen 4950 $534 ohne $3Volltext

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1789]
#### URL

- IxTheo#2022-07-09#971B149BD459B18D8FFDB5F5D54F601FD2C5F1F3
https://doi.org/10.1177/00145246221099755
(ZS The expository times (SAGE))

- IxTheo#2022-07-08#136910FB2351425A362143652657C2250603F48E
https://brill.com/view/journals/vt/72/3/article-p355_1.xml
(ZS Vetus Testamentum (Brill))

MARC-Daten:
```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://brill.com/view/journals/vt/72/3/article-p355_1.xml</subfield>
<subfield code="z">ZZ</subfield>
</datafield>

```
  
### Problembeschreibung
Seit dem 7.7. scheint etwas nicht mit den Einspielungen beim Feld 4950 (URL) zu stimmen.
Es wird neuerdings das Unterfeld $B1 mitgeliefert.
Dafür fehlt nun $3Volltext, was nicht weiter schlimm wäre, wenn wir nicht $534 (den dazugehörigen Code zu Volltext) mitliefern würden. Die Unterfelder $3 und $5 müssen in Abhängigkeit zueinander vorhanden sein. Das Vorhandensein von nur einem der beiden führt zu einer Fehlermeldung, wenn man einen Datensatz bearbeiten will:
![image](https://user-images.githubusercontent.com/57000004/178299544-c6180ca9-d66e-42ba-9ecb-66b48653f796.png)

Man könnte $3Volltext + $534 ganz weglassen, da es sich bei dem Feld 4950 um eine URL zum Volltext handelt.

MARC-Daten wie wir bisher geliefert haben:
IxTheo#2022-07-01#E039070A1EB84AC1EF6F996C4BEC0213F67FEC0D
```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://onlinelibrary.wiley.com/doi/abs/10.1111/moth.12771</subfield>
<subfield code="z">ZZ</subfield>
</datafield>
```
Da ich zu den Problemfällen in unseren MARC-Daten auf die feierabendliche Schnelle keinen Unterschied sehe, scheint es ein Problem seitens des BSZ zu sein..?

**Comment by jriedl** [comment]
> scheint es ein Problem seitens des BSZ zu sein..?

Würde auch ein Konverter-Problem vermuten. Auf unserer Seite hat es ja hier der letzten Zeit diesbezüglich keine Änderungen gegeben.

**Comment by socheres** [comment]
Vermutlich liegt das Problem BSZ-seitig. Würden Sie @IxKo eine eMail an den support schreiben und mich mit ins CC setzen?
