### ISSUE TITLE
ISSN 0003-2980 | Andrews University Seminary Studies (Andrews University Press) | Fehlender Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1790]
#### URL
(https://digitalcommons.andrews.edu/auss/vol58/iss2/)

  
#### Import-Translator
  Einzel- und Mehrfachimport:
 Nur Einzelimport: COinS

  
### Problembeschreibung
Es fehlt ein passender Translator für den Mehrfachimport

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
mit dem neuen Translator ubtue_AUSS müsste der Download funktionieren.
Leider kommt dabei eine Fehlermeldung, die von dem intern aufgerufenen COins-Translator herrührt, ich kann diese allerdings nicht beheben, sie führt aber auch nicht zu einem Abbruch.
Viele Grüße, Helena Nebel
