### ISSUE TITLE
ISSN 0269-1205 | Literature and Theology (Oxford) | Berichtsjahr

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1791]
#### URL
https://academic.oup.com/litthe/issue/35/4
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Oxford Academic.js

### Problembeschreibung
Das Heft hat als Berichtsjahr **2021**. Allerdings wird überall als Jahr das Erscheinungsjahr online importiert:

![image](https://user-images.githubusercontent.com/57000004/179511311-02a76c4d-1d32-4c2c-8b97-382377cc54fd.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Berichtsjahr sollte jetzt korrekt übernommen werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke sehr!
