### ISSUE TITLE
ISSN 2035-3545 | Diritto ecclesiastico (LibraWeb) | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1792]
#### URL
ZS-Seite: http://www.libraweb.net/sommari.php?chiave=308
aktuelles Heft: http://www.libraweb.net/articoli.php?chiave=202130804&rivista=308
  
#### Import-Translator
  Einzel- und Mehrfachimport:
DOI.js
  
### Problembeschreibung
Könnte man für diese Seite einen angepassten Translator entwickeln?
Der angebotene Standard-Translator DOI funktioniert zumindest schon einmal im Multi-Import und nimmt ein paar Informationen mit:
![image](https://user-images.githubusercontent.com/57000004/179523948-4110fc3e-680f-47db-bab4-f037afe71f85.png)

Es fehlen nur Seiten- und Bandangabe.

Wurde von Kooperationspartnern, die diese ZS momentan manuell erfassen, erfragt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator "ubtue_libraWeb" müsste es im Multi-DL gehen.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die römische Bandzählung sollte jetzt umgerechnet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke!

**Comment by IxKo** [comment]
Translator wird mir nicht mehr angeboten (siehe auch gleiche Plattform #2071)

**Comment by IxKo** [comment]
Danke, er wird wieder angeboten!
