### ISSUE TITLE
ISSN 2282-2828 | Archivio giuridico (Stem Muchi Editore) | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1793]
#### URL
ZS: https://www.mucchieditore.it/index.php?option=com_virtuemart&view=productdetails&virtuemart_product_id=249&virtuemart_category_id=23
Heft: https://www.mucchieditore.it/index.php?option=com_virtuemart&view=productdetails&virtuemart_product_id=3539
  
#### Import-Translator
  Einzel- und Mehrfachimport:
DOI.js
  
### Problembeschreibung
Könnte man für diese Seite einen angepassten Translator entwickeln?
Der angebotene Standard-Translator DOI funktioniert zumindest schon einmal im Multi-Import und nimmt ein paar Informationen mit:
![image](https://user-images.githubusercontent.com/57000004/179527560-05c92eb6-0f34-4063-ab14-5eff95d90972.png)

Es fehlen nur Seitenangaben.

Wurde von Kooperationspartnern, die diese ZS momentan manuell erfassen, erfragt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator ubtue_mucchieditore (nur im Multi-DL) werden auch die Seitenzahlen übernommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Dankeschön!
