### ISSUE TITLE
ISSN 0021-2423 | Istina (Eb/At) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1794]
#### URL
https://web.p.ebscohost.com/ehost/results?vid=1&sid=5762d0e4-6074-4125-b231-b44e33fcc830%40redis&bquery=JN+%22Istina%22+AND+IK+%2220220101+00067+00001%22&bdata=JmRiPXJlaCZ0eXBlPTEmc2VhcmNoTW9kZT1BbmQmc2l0ZT1laG9zdC1saXZl
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Der Translator bricht sowohl beim Mehrfach- als auch Einzelimport ab.
![image](https://user-images.githubusercontent.com/57000004/179970203-f3a3e7ec-c1d9-4054-8278-7f73828016c9.png)

**Comment by helenanebel** [comment]
Redi-BW-Adresse: http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000003346%26site%3dehost-live

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem dürfte jetzt nicht mehr bestehen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, es klappt wieder, und irgendein fleißiges Bienchen hat heute sogar schon die Hefte erfasst.
