### ISSUE TITLE
ISSN 0570-1953 | L'Annee canonique (cairn) | Band/Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1795]
#### URL
https://www.cairn.info/revue-l-annee-canonique-2018-1.htm
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cairn.info.js
  
### Problembeschreibung

Könnte hier die römische Bandangabe "LIX" in 59 umgewandelt und in das Feld Band importiert werden?
Und auch für zukünftige Fälle?

Momentan wird keine Bandzählung importiert, dafür eine Heftzählung "1". Da die ZS nur einmal im Jahr erscheint und bisher immer nur eine Bandangabe, aber nie eine Heftzählung, erfasst wurde, sollte die 1 nicht importiert werden. 

- [ ] (Koop KALDI informieren)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren!
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert!
