### ISSUE TITLE
1530-5228 | The journal for cultural and religious theory | Problem mit Translator

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1796]
[#### URL](https://web.p.ebscohost.com/ehost/command/detail?vid=0&sid=0bc9aed8-5782-4f5c-9c8d-fa65150bff77%40redis&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#jid=ATLA0001487460&db=reh)

  
#### EBSCOhost
  Mehrfachimport:
<Name von genutzten Translator (siehe auch: https://github.com/ubtue/zotkat-translators oder Zeder p_zot3)>

  
Aufsätze können nicht heruntergeladen werden, da Meldung zu Problemen mit Translator

**Comment by RelBibRetroKat** [comment]
Ebso Link: https://web.s.ebscohost.com/ehost/command/detail?vid=0&sid=23e2d000-aaa3-4204-826f-903d5ed1c5ad%40redis&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#db=reh&jid=ATLA0001487460
von der Website funktioniert Zotero nicht (Translator [ubtue_EBSCOhost.js])
Download bricht mit Fehlermeldung ab.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem dürfte jetzt nicht mehr bestehen.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Das Problem ist behoben. Katalogisierung mit Zotero läuft problemlos.

**Comment by DowntownOcean** [comment]
Gleiches Problem tritt wieder auf, Fehlermeldung beim Einzel- und Mehrfachimport

**Comment by mara-spiess** [comment]
@DowntownOcean Wurde hier schon getestet?

**Comment by DowntownOcean** [comment]
@mara-spiess Scheint einwandfrei zu funktionieren, ich schließe das Issue
