### ISSUE TITLE
ISSN 0075-2541 | Jahrbuch für Antike und Christentum (Eb/ASP) | Bandangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1799]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26jid%3d3A0R%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Die Bandangabe wird beim Import in das Ausgabenfeld importiert, wodurch es dann als Heftzählung exportiert wird.

**Comment by helenanebel** [comment]
Liebe @IxKo  ,
das Problem dürfte jetzt nicht mehr bestehen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt und danke für den Hinweis bzgl. der Sprache!
