### ISSUE TITLE
ISSN 1467-8519 | Bioethics (Wiley) | hochgestellte Zeichen TEL

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1800]
#### URL
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1467-8519.2005.00422.x
  IxTheo#2021-12-10#7A7D361B1EF96ACC07F301AF4DF0FFEBB4F92AA4  (Retro-Projekt)

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Wiley Online Library.js
(auch beim "Offiziellen")

  
### Problembeschreibung
Beim Import wird "TEL" im Wort "INTELLIGENCE" hochgestellt:
![image](https://user-images.githubusercontent.com/57000004/184604849-593052d0-9fbc-4327-9584-552f141988dc.png)

Wird auch beim Export übernommen:
![image](https://user-images.githubusercontent.com/57000004/184605105-a15fec05-112d-4e2c-acd9-24a4a1bde9cd.png)

Gleiches passiert beim Test auf NU und ub28

**Comment by jriedl** [comment]
Da nu/ub28 betroffen, habe ich es mir angeschaut: Ist ein Fehler im BibTex-Subtranslanslator, bei dem die Zeichenfolge `TEL` durch das Unicode-Telefonsymbol (\u2121) ersetzt wird (vgl. [hier](https://github.com/ubtue/zotero-translators/blob/5ba668a2ac867fe6156a1fd082843606aa90a68e/BibTeX.js#L2688)). Da für unseren Anwendungsfall wahrscheinlich in keinem Fall einschlägig, habe ich die Zeile auskommentiert. Aktueller Stand auf nu.

**Comment by IxKo** [comment]
Danke, tritt beim Test auf NU nun nicht mehr auf.

**Comment by IxKo** [comment]
In diesem Fall wurde wieder ein hochgestelltes TEL eingespielt, es handelt sich wieder um eine Wiley-ZS:
IxTheo#2022-08-29#8743E62B1007E03D4D3600A67E67589710A355F4
![image](https://user-images.githubusercontent.com/57000004/190078482-e2dd1255-fff2-44f7-8a70-b6c2046a52d1.png)

Auf NU tritt der Fehler nicht auf, nur auf ub28 und beim Import im halbautomatischen Verfahren.

**Comment by jriedl** [comment]
Aktueller Stand auf ub28 - Problem tritt bei beiden Datensätzen nicht mehr auf.

**Comment by IxKo** [comment]
Ich kann es auf ub28 nicht testen. Beim Result-File erscheint nur ein gelbes Fenster mit roten Rahmen.

TRY URL
https://onlinelibrary.wiley.com/doi/abs/10.1111/zygo.12804
Zygon
![image](https://user-images.githubusercontent.com/57000004/195100607-846a2416-4ab6-4bd6-9956-2851477c5a93.png)

Auch TRY RSS klappt nicht.

**Comment by jriedl** [comment]
Wenn man `https://onlinelibrary.wiley.com/doi/abs/10.1111/zygo.12804` per Hand (= im Browser) aufruft, erkennt man, dass hier zunächst ein Cloudflare Bot-Protection-Schutz aktiv ist und dann erst die Weitererleitung erfolgt. Deshalb wahrscheinlich wie oben in den Logs zu sehen der HTTP-Fehler 503 (= Zugriff verweigert), d.h. die Website kann schon nicht heruntergeladen werden. Dieser Botschutz scheint gerade auf vielen Seiten aktiv zu werden (Cloudflare umfasst wohl mittlerweile 20% des gesamten Internet). Schade ist, dass wir eigentlich bei Wiley gewhitelisted sein sollten. @socheres: Gab es da seit den letzten Mails im Mai noch einmal Kontakt?

**Comment by jriedl** [comment]
Nach Hinweis von @helenanebel: Aktuell ist der Zugriff wieder möglich - tryURL mit `https://onlinelibrary.wiley.com/doi/abs/10.1111/zygo.12804` auf ub28 hat ein Ergebnis geliefert. Kann entweder bedeuten, dass nach nach Anschlagen eines Cloudflare-Schutzmechanismus nur temporär gesperrt wird (bzw. die Botdetection erst bei Vorliegen weiterer Voraussetzungen, z.B. zu viele Zugriffe dann für ein ganzes (Sub-)Netz aktiv wird) oder dass das Whitelisting mittlerweile auf diesen Dienst übertragen wurde. Falls unsere Maschinerie grundsätzlich den Bottest (der ja rechnerbezogen zu sein scheint) bestehen würde, hätten wir kein Problem, das erscheint aber unwahrscheinlich.

**Comment by IxKo** [comment]
Danke, auf ub28 ist es beim Testen nun nicht mehr aufgetreten!

@helenanebel Im halbautomatischen Verfahren wird noch weiterhin das hochgestellte TEL importiert.

**Comment by IxKo** [comment]
Danke, alles behoben!
