### ISSUE TITLE
ISSN 2447-7443 |  Vox scripturae | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1801]
#### URL
http://www.voxscripturae.com.br/edition/51/volume-xxvii-number-2-september-2019
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Ist es möglich für diese Seite einen neuen Translator zu schreiben?

Momentan wird über Eb/At katalogisiert. Dort kommen DOIs mit, die scheinbar auf eine alte OJS-Plattform verweisen (wenn man lange wartet), wo aber nichts (mehr) ist. Keine der DOIs scheint zu funktionieren...

Die Verlagsseite ist lizenzfrei.

Der HTML-Code eines Aufsatzes sieht so aus:
```	<h4>God and happiness in Epicurus</h4>
	<span class="volume">Deus e a felicidade em Epicuro</span>
	<div class="rb">
	<a class="auth">Adriano da Silva Carvalho</a>
	<a class="pags">16 págs.</a>
	<a href="download/51/384/god-and-happiness-in-epicurus" target="_blank" class="down">Download (pt)</a>
```

Tag h4 müsste in 4002 Paralleltitel
Tag span class=volume ist der Titel

auth =AutorIn (mehrere AutorInnen scheinen mit "e" getrennt zu werden: `<a class="auth">William Felipe Zacarias e Euler Renato Westphal</a>`)
pags müsste in ein Unterfeld $t, da es nur die Gesamtseitenzahl darstellt.

href ist der Link zum PDF.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
im Multi-DL müsste jetzt mit ubtue_voxscripturae alles übernommen werden, was da ist.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert!
