### ISSUE TITLE
ISSN 0194-3448 | American journal of theology and philosophy | Scholarly Publishing Collective | Feld 4207 - kein Abstract, sondern Aufsatztext (vermutlich)

### ISSUE THREAD

**Issue by IxTheoEg** [ubtue/DatenProbleme#1802]
URL: 
(https://scholarlypublishingcollective.org/uip/ajtp/article-abstract/42/3/35/297737/Experiments-with-Non-Violence-King-s-Stride-Toward?redirectedFrom=fulltext)

  
Import-Translator: ubtue_Silverchair.js
Mehrfachimport: Translator meldet Fehler
Einzelimport: ubtue_scholarlypublishingcollective

  
Liebe Frau Nebel,

in Feld 4207 wird nicht der Abstract des Aufsatzes angegeben, sondern (vermutlich) der Aufsatztext.

Würden Sie für mich bitte prüfen?

![image](https://user-images.githubusercontent.com/102959630/186678674-c2ac559a-1868-4b47-b031-0bc92ed49989.png)

Vielen lieben Dank - ich hoffe, ich habe alles richtig gemacht  :-).

Lieber Gruß

IxTheo/Eg

**Comment by helenanebel** [comment]
Liebe @IxTheoEg ,
das passiert, weil das im Seitenquelltext unter "description" steht. Ich habe jetzt für diese Zeitschrift alle Abstractangaben entfernt, falls das noch für weitere Zeitschriften gilt, müsste man das dann jeweils separat machen.
Viele Grüße, Helena Nebel

**Comment by mara-spiess** [comment]
@IxTheoEg @IxKo Kann dieses Issue geschlossen werden?

**Comment by IxKo** [comment]
Es wird kein Volltext mehr als Abstract importiert.
