### ISSUE TITLE
ISSN 1542-3050 | Journal of Pastoral Care & Counseling (SAGE) | Personenname

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1803]
#### URL
https://doi.org/10.1177/15423050221092317
IxTheo#2022-06-05#183A50CADD159C74F5DDC8AF85767CF4B82BB9C2

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SAGE Journals.js
  
### Problembeschreibung
![image](https://user-images.githubusercontent.com/57000004/186909807-26598fd6-b760-477f-acf9-69d0b9500685.png)

Patrick ist der Vorname, er wird aber zusammen mit dem Nachnamen Heard als ein Nachname aus zwei Worten eingespielt.
Ebenfalls im halbautomatischen Verfahren.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
leider steht das so im RIS:

AU  - Patrick Heard, Clark
AU  - Scott, Jared
AU  - Yeo, Rev’d Stephen

D.h. da kann man auch mit dem Translator nicht viel daran ändern, weil man sonst wieder andere Namen verändern würde.

Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Okay, dann ist es nicht zu ändern, danke!
