### ISSUE TITLE
ISSN 2385-8907 | Edinost in Dialog (DOAJ) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1806]
#### URL
Einzel: 
https://doaj.org/article/8b2cecaad39145b68b9b47f294e31f55

Mehrfach (Klick bei "Articles"): 
https://doaj.org/toc/2385-8907?source=%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%222335-4127%22%2C%222385-8907%22%5D%7D%7D%5D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%2C%22track_total_hits%22%3Atrue%7D
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_DOAJ.js
(Koop)
  
### Problembeschreibung
siehe auch #1642 

Beim Mehrfach-Import stehen viele Artikel nicht zur Auswahl, die eigentlich auf der Seite sind:
![image](https://user-images.githubusercontent.com/57000004/189607022-d0a7a721-b557-4744-97ae-524556a103ee.png)

Beim Einzel-Import wird eine Fehlermeldung erzeugt:
![image](https://user-images.githubusercontent.com/57000004/189607255-d714c8e8-bbf9-47d6-8133-0c44a0e275d5.png)
Bei mir wird trotzdem der Artikel importiert, bei den Kooperationspartnern wohl nicht.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das so eingerichtet, dass man jeweils das Jahr auswählen muss:
![grafik](https://user-images.githubusercontent.com/49190455/194854938-8c880586-9627-4724-9a09-f1899a7c3c94.png)
Dann sollten die Artikel des jeweiligen Jahres korrekt rüberkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ok, dann vermerke ich es so in Zeder, danke!
