### ISSUE TITLE
ISSN 1018-1539 | Österreichisches Religionspädagogisches Forum (OJS) | Zusatztitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1807]
#### URL
https://oerf-journal.eu/index.php/oerf/article/view/318

IxTheo#2022-08-30#01922C5BC6330CCA568A34C99745894327B6C05C

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Sowohl im vollautomatischen als auch im halbautomatischen Verfahren werden die Zusatztitel nicht übernommen.

![image](https://user-images.githubusercontent.com/57000004/189885754-5e3a7756-3797-447f-8fba-5af20cefa9b1.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollten die Zusatztitel auch im zota-Verfahren mitkommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Passt, vielen Dank!
