### ISSUE TITLE
ISSN 2033-4273 | ET-Studies (Peeters) | ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1808]
#### URL
https://poj.peeters-leuven.be/content.php?url=article&id=3290787
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_peeters.js

  
### Problembeschreibung
Die ISSN wird nicht nach Zotero importiert, wodurch die Mapping-Listen nicht greifen.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ISSN sollte jetzt mitkommen und Book Reviews wird auch als Rezension gekennzeichnet.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, passt alles!
