### ISSUE TITLE
Ergänzung von Abrufzeichen in 953

### ISSUE THREAD

**Issue by helenanebel** [ubtue/DatenProbleme#1812]
Liebe alle, lieber @socheres , lieber @thefass , liebe @IxKo , liebe @IxTheoKm ,

wäre es möglich, den zotero_harvester so anzupassen, dass man in der zotero_harvester.conf Sammlungscodes übergeben kann? 
Also z.B.
zotero_cod = BIIN,KALD
Könnte dazu führen, dass zusätzlich zum Feld

```<datafield tag="935" ind1=" " ind2=" "><subfield code="a">mteo</subfield></datafield>```

die Felder
```<datafield tag="935" ind1=" " ind2=" "><subfield code="a">BIIN</subfield></datafield>```
und 
```<datafield tag="935" ind1=" " ind2=" "><subfield code="a">KALD</subfield></datafield>```
generiert werden. 
Es wäre gut, wenn diese Angaben aus der Spalte deri in Zeder generiert werden könnten.

Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Hallo @jriedl ,
ich wusste nicht, dass die Bibliothekar*innen solche Informationen im vollautomatischen Verfahren übergeben können und dann ein Post-Processing ausgeführt wird. Dann ist das ja alles geklärt.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Können Sie nicht. Postprocessing bedeutet hier nur, dass es nach Abschluss des Harvesting und nicht als Teil des Harvesters selbst ausgeführt wird (z.B. als Teil des Harvester-Aufruf-Skripts).

**Comment by helenanebel** [comment]
Hallo @jriedl ,
sehr gut. Dann wird @IxKo sicher wissen, wie das funktioniert.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ich weiß nur von den Mapping-Listen im halbautomatischen Zotero-Verfahren, die für die Kooperationspartner den Sammlungscode und die Abrufzeichen steuern.

Im vollautomatischen Verfahren weiß ich von keiner Möglichkeit.

**Comment by jriedl** [comment]
So langsam hoffe ich, die Issuenummer 1812 hat keine symbolische Bedeutung aus den napoleonischen Kriegen...
Meine Aussage oben bezog sich auf den Kontext, dass für die geharvesteten Records ohnehin irgendeine Form von Nachbearbeitung stattfinden muss (wie RetroKat) und damit ein weiterer Aufruf aus einem vorhandenen Aufrufskript leicht integrierbar ist. Falls, wie es sich nun offenbar herauskristallisiert, es sich um eine grundsätzliche Featureerweiterung handeln soll, die auch in das bisherige Aufnahme- und Testschema für (alle) Zotaut-Zeitschriften passen soll, ist es dann wahrscheinlich doch sinnvoller, das innerhalb des Harvesters zu lösen, weil es dann in der Config-Datei klar erkennbar ist. 

Die Integration selbst ist prinzipiell mit den Ausdrucksmöglichkeiten der Config-Datei bereits möglich (geht natürlich auch ohne Unterfeld 2 und soll nur demonstrieren, dass auch weitere Unterfelder möglich sind):
```
add_marc_field_XXX   = "935  \037aBIIN\0372LOK"
add_marc_field_XX1   = "935  \037aKALD\0372LOK"
```

![image](https://user-images.githubusercontent.com/13135579/195083521-1568db22-7502-4d00-b959-21d60ee9efe2.png)

Wäre also noch zu klären, ob tatsächlich eine eigene Direktive nötig und ob und wie die Integration in `zeder_to_zotero_importer` (also die Zeder/Harvester-Config Synchronisation) erfolgen soll. Prinzipiell erscheint mir für allgemeine Featurerequests eine mündliche Vorabklärung immer sinnvoll um Missverständnisse wie in diesem Fall zu vermeiden.

**Comment by helenanebel** [comment]
Lieber @jriedl ,
aus dem Grund hatte ich die obigen Tags gesetzt, diese würde ich nicht setzen, wenn es nur um das Projekt RetroTheo ginge. Das war auch mit Herr Faßnacht so abgesprochen, dass ich das gleich für alle Verfahren beantrage. Welche Tags wären denn in dem Fall korrekt gewesen, dann kann ich diese ändern und beim nächsten Mal gleich korrekt setzen?
Es tut mir sehr leid, dass mein Issue offensichtlich missverständlich formuliert war.
Viele Grüße, Helena Nebel

**Comment by jriedl** [comment]
Ja, das mit den Tags ist mir im Nachhinein dann auch aufgefallen. Ich halte das Problem aber für grundlegender - wir haben mittlerweile derart viele Projektbeteiligte, dass Arbeiten "auf Zuruf" (und ohne Kenntnis des Kontextes, was vorher in anderen Situationen besprochen wurde) eigentlich keine sinnvolle Vorgehensweise mehr scheint. Vielleicht wäre es ja möglich, hier einmal grundsätzlich ein klares Prozedere zu definieren, über welche Wege Feature Requests zukünftig laufen sollen, erspart langfristig wahrscheinlich allen eine Menge Frust und schlechte Laune.

**Comment by thefass** [comment]
@jriedl Das ist eine gute Idee, damit uns der eigene Erfolg nicht auffrißt. Denn gute Laune während der Arbeit sollte nicht verloren gehen oder wieder neu hergestellt werden.

**Comment by IxTheoKm** [comment]
Nebenbemerkung:
Achtung! KALD und BIIN sind keine lokalen Abrufzeichen! 
Sie stehen im selben PICA-Feld 0575 wie mteo.

**Comment by jriedl** [comment]
Die zusätzliche Direktive `additional_selectors` und die Synchronisationslogik von Zeder in die Config ist mittlerweile implementiert. Nach Behebung der Indikatorenproblematik auf BSZ-Seite können wir das sukzessive auf Test- und Liveservern einspielen.

**Comment by jriedl** [comment]
Wie angekündigt ist der aktuelle Stand jetzt auf nu eingespielt, d.h. die neue Direktive `additional_selectors` (vgl. Doku in https://github.com/ubtue/zotero-enhancement-maps/blob/master/zotero_harvester.conf) wird nun unterstützt und heute Abend wird zum ersten Mal automatische Synchronisation der zusätzlichen Abrufzeichen aus Zeder in die Conf stattfinden. Sollten morgen keine Probleme gemeldet werden, kann die Einspielung auf ub28 erfolgen und das dort momentan deaktivierte automatische Update der `zotero_harvester.conf` wieder eingeschaltet werden.

**Comment by IxKo** [comment]
@jriedl
Auf Nu werden die Sammlungscode beim Testen mit den Zotero-Harvester ausgegeben.
Allerdings in ein weiteres Datafield 935.

Das Feld ist aber nicht wiederholbar. Es müsste daher als weiteres Unterfeld a in das bereits vorhandene 935 mteo, was wir immer im zota-Verfahren ausspielen:

Beispiel:
```
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="a">mteo</subfield>
<subfield code="a">BIIN</subfield>
</datafield>
```

**Comment by jriedl** [comment]
Das war so die Spezifikation (vgl. oben):
> Könnte dazu führen, dass zusätzlich zum Feld
> 
> `<datafield tag="935" ind1=" " ind2=" "><subfield code="a">mteo</subfield></datafield>`
> 
> die Felder `<datafield tag="935" ind1=" " ind2=" "><subfield code="a">BIIN</subfield></datafield>` und `<datafield tag="935" ind1=" " ind2=" "><subfield code="a">KALD</subfield></datafield>` generiert werden.

Im Kontext der Bibelgesellschaft ist der Fall aber schon einmal aufgetreten (BIIN + mteo), d.h. es wurde in der hier umgesetzten Form eingespielt. Entscheidend ist ja, was der Konverter daraus macht und wie die eingespielten Daten aussehen. In der Testdatenbank müssten die Daten mit `f enr bbi* or bre*` (danke an @IxTheoKm )aktuell noch auffindbar sein. Passt es da? Ansonsten müsste eine Einspielung einer BIIN-Zeitschrift abgewartet werden.

**Comment by IxKo** [comment]
> In der Testdatenbank müssten die Daten mit f enr bbi* or bre* (danke an @IxTheoKm) aktuell noch auffindbar sein. Passt es da?

Ja, die Daten sind noch in der Test-DB und hier wird nur ein Pica-Feld 0575 mit beiden Codes erzeugt:
![image](https://user-images.githubusercontent.com/57000004/197964133-7cdf55ef-017e-4566-8cb2-e606d25d32bc.png)

Demnach führt das BSZ die Marc-Felder zusammen und es ist alles gut.

**Comment by jriedl** [comment]
Das ist gut. Dann spricht nicht mehr dagegen, das Update auf ub28 einzuspielen und die Conf-Update wieder zu aktivieren, oder?

**Comment by IxKo** [comment]
Ja, es spricht nichts dagegen.

**Comment by jriedl** [comment]
Auf ub28.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
wir spielen auch die Abrufzeichen in 8012 als separate 935-Felder ein und diese werden dann jeweils in ein Unterfeld $a hinzugefügt.
Aus diesem Grund hatte ich (glücklicherweise korrekt) geschlossen, dass die Daten in den 935-Feldern ohne LOK dann wahrscheinlich auch so verarbeitet werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ich ergänze das Label für das **halbautomatische Verfahren**. Da es hier noch Klärungsbedarf gibt:
Bisher wird im zotk-Verfahren in der [Mapping-Liste ISSN_to_Abrufzeichen_zotkat ](https://github.com/ubtue/zotero-enhancement-maps/blob/c367a3ba553673811d2489e8e73cecdef1291434/ISSN_to_Abrufzeichen_zotkat.map) zwar der Sammlungscode für 0575 gesteuert, **aber auch die Abrufzeichen der Kooperationspartner** (zB. 8012 inzs$ainzo ), da diese die ZSen mit Zotero erfassen.

Bei einer Zederabfrage kat=ixtheo efor=ixtheo prodf=zotk deri=BIIN scheint es jedoch auch ZSen zu geben, die nicht von den Kooperationspartner erfasst werden, aber wo auch ein Sammlungscode gewünscht ist.
Das decken wir aber momentan im Verfahren nicht ab.

**Comment by helenanebel** [comment]
@helenanebel weitere gewünschte Anpassungen:
-BIIN, KALD werden nicht korrekt gesetzt
-automatische Personenverknüpfung für Kriminologie ohne Einschränkungen
- 2,1 soll ab sofort  für die Kriminologie verwendet werden, das muss in die Mapping-Liste eingetragen werden
- Die freien Schlagwörter aller Zeitschriften sollten in 5520 eingetragen werden.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die o.g. Änderungen habe ich vorgenommen, man sollte dann noch in der Mappingsliste die 2,1 hinterlegen, ansonsten wird aber auch wie üblich der Fehler angezeigt.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Es scheint alles zu funktionieren (0575 und 8012 für inzo und krzo).
Vielen Dank!
Die beiden genannten Mapping-Listen wurden gelöscht.
