### ISSUE TITLE
ISSN 0014-2239 | Etudes théologiques et religieuses (Cairn.Info) | ISSN wird nicht übernommen

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1813]
#### URL
https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2022-3.htm
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cairn.info.js
  
### Problembeschreibung
ISSN wird beim Import in Zotero nicht übernommen

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
jetzt sollte die ISSN übernommen werden.
Viele Grüße, Helena Nebel
