### ISSUE TITLE
ISSN 0179-7239 | Kirche und Israel (VR) | wirre Personennamen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1814]
#### URL
Heft: https://www.vr-elibrary.de/toc/kiis/37/1
1 Bsp.-Artikel: https://www.vr-elibrary.de/doi/10.13109/kiis.2022.37.1.12
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_vandenhoeck_ruprecht.js

### Problembeschreibung
Die Personennamen werden sehr wirr importiert:

![image](https://user-images.githubusercontent.com/57000004/194891186-8b8eee5f-fde9-4ffe-92b6-039f9b60fba6.png)

_Memo: Koop I_

**Comment by IxKo** [comment]
Danke, sieht deutlich besser aus =)

Dass er hier aus dem abgekürzten zweiten Vornamen den Nachnamen bildet, ist nicht änderbar, oder?
https://www.vr-elibrary.de/doi/10.13109/kiis.2022.37.1.28
![image](https://user-images.githubusercontent.com/57000004/195085269-ad8ba1b9-63e1-4e5e-a89e-c4078c8989a7.png)
![image](https://user-images.githubusercontent.com/57000004/195085386-30654941-bbc6-4817-a57f-0772304926c3.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
ich habe das gefixt, jetzt sollte alles wieder normal aussehen (hoffentlich)
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, nun sieht nichts mehr wirr aus! :-)
