### ISSUE TITLE
zota-Einspielungen: Erscheinungsjahr

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1816]
#### URL
IxTheo#2022-10-11#4F041F96E4CCE65F521EF6B58E461432443203FC
IxTheo#2022-10-10#30BDD7E19348AFEA78BD9EF2A2272626B9C18B14
  
### Problembeschreibung
Seit gestern (11.10.) werden die zota-Einspielungen ohne Pica-1100 (Erscheinungsjahr) eingespielt.

Ich glaube, es liegt nicht an uns, da unsere Quell-Daten das Marc-Feld 264 enthalten.

Ich möchte es trotzdem ausschließen, bevor ich den k10plus-Support benachrichtige.

**Comment by jriedl** [comment]
Auf unserer Seite sind keine Änderungen bekannt - 264$c wird meines Wissens seit Beginn der Einspielungen so gesetzt). Seit gestern scheint ja  beim BSZ das 2022.3-Format zu gelten, eventuell gab es deshalb auf BSZ-Seite Änderungen.

**Comment by IxKo** [comment]
Ok, dann melde ich es gleich dem K10plus-Support. Danke!

**Comment by jriedl** [comment]
Für 264$c wird zukünftig mit Indikator 2 = 1 erzeugt. Sukzessive Einspielung auf den Servern nach Behebung der aktuellen Konverterproblematik auf BSZ-Seite.

**Comment by IxKo** [comment]
Die zota-Einspielungen werden wieder wie gewohnt mit Erscheinungsjahr in 1100 eingespielt.
