### ISSUE TITLE
ISSN 0951-8207 | Journal for the Study of the Pseudepigrapha (SAGE) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1817]
#### URL
https://journals.sagepub.com/doi/10.1177/09518207221115929
IxTheo#2022-09-29#7849DD848AD54E5FBDE434C23A49856620D1DBBB

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SAGE Jorunals.js

  
### Problembeschreibung
Es handelt sich um einen Open-Access-Artikel, der sowohl im voll- als auch halbautomatischen Zotero-Verfahren nicht als LF erkannt wird.

**Comment by helenanebel** [comment]
Liebe @IxKo .
LF und Orcid sollten jetzt gesetzt werden.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
LF und Orcid sollten jetzt auch im zota gesetzt werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Liebe @helenanebel ,
es kommen leider noch keine Notizen nach Zotero, die LF und ORCID steuern.
Viele Grüße

**Comment by IxKo** [comment]
Danke, passt alles!
