### ISSUE TITLE
ISSN 1468-2303 | History and Theory (Wiley) | Anmerkungssternchen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1820]
#### URL
https://onlinelibrary.wiley.com/doi/full/10.1111/hith.12269
IxTheo#2022-09-20#FE53D0FDAFE11089DCA244EC9D56837A23623B20
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Wiley Online Library.js

  
### Problembeschreibung
Das Sternchen nach dem Titel wird in beiden Verfahren übernommen, obwohl es sich nur um ein Anmerkungssternchen handelt und kein Bestandteil des Titels ist.

![image](https://user-images.githubusercontent.com/57000004/195355785-52487e14-90c6-48cc-a76a-6b60024d7a3e.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Anmerkungssternchen werden jetzt im halbautomatischen Verfahren entfernt.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Anmerkungssternchen werden jetzt im vollautomatischen Verfahren ebenfalls entfernt.
Viele Grüße, Helena Nebel
