### ISSUE TITLE
ISSN 2532-2990 | The Journal of CESNUR | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1821]
#### URL
https://cesnur.net/archives/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner (Es ging wohl mal mit DOI+Zauberstab, doch diese Funktion scheint bei der Zoteroanwendung generell nicht mehr zu funktionieren.)

  
### Problembeschreibung
Kann für diese Seite ein Translator entwickelt werden? Die einzelnen Artikel haben ausgewiesene DOIs.

- [ ] IxTheoEg informieren

**Comment by IxKo** [comment]
Es kann der Translator DOI verwendet werden. Es müsste aber die Band- und Heft-Zählung angepasst werden:
![image](https://user-images.githubusercontent.com/57000004/196963092-bd5e1f4f-9318-47c8-addc-cc43ca74f5e6.png)

Und er wird nicht als erster Translator angeboten.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt müsste es funktionieren. Die letzten Issues sollten über den Translator ubtue_cesnur.info heruntergeladen werden können, die von 2021 müssen über ubtue_cesnur_2021.info heruntergeladen werden (das liegt daran, dass man nicht mehr als 40 Artikel herunterladen kann).
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Vielen Dank, kann das auch noch für die Supplement-Seite eingerichtet werden? https://cesnur.net/supplements/

**Comment by IxKo** [comment]
Danke, klappt nun auch mit dem Supplement und $n
