### ISSUE TITLE
ISSN 2468-5542 | Journal of Islamic ethics (Brill) | arabische Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1822]
#### URL
https://doi.org/10.1163/24685542-12340068
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Brill.js

  
### Problembeschreibung
Die arabischen Keywords werden nicht nach Zotero importiert und auch nicht beim vollautomatischen Verfahren erfasst:

`<meta content="الحيوانات" property="article:tag"/>
	
		
		<meta content="ابن سينا" property="article:tag"/>
	
		
		<meta content="الفلسفة" property="article:tag"/>
	
		
		<meta content="أخلاقيات الحيوان" property="article:tag"/>
	
		
		<meta content="العناية الإلهية" property="article:tag"/>
	
		
		<meta content="الغائية" property="article:tag"/>`

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Keywords sollten jetzt im halbautomatischen Verfahren übernommen werden.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Keywords sollten jetzt auch im vollautomatischen Verfahren übernommen werden.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Ja, danke, auf Nu werden sie nun übernommen.
Auf ub28 noch nicht.

**Comment by IxKo** [comment]
Klappt nun auch auf ub28, danke!
