### ISSUE TITLE
ISSN 0049-3449 |  Teología y vida (SciELO) | Fehlermeldung

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1824]
#### URL
https://github.com/ubtue/DatenProbleme/issues?q=is%3Aissue+Teolog%C3%ADa+y+vida
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SciELO.js

  
### Problembeschreibung
Artikel werden normal vorgeladen (Artikel erscheinen in grau), kommen aber nicht in Zotero an. Stattdessen kommt folgende Fehlermeldung:

"Ein Fehler ist aufgetreten beim Versuch, diesen Eintrag zu speichern. Siehe Problembehebung für Übersetzer für weitere Informationen."

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
die Fehlermeldung sollte behoben sein, die Abstracts sollten jetzt in getrennte Felder 4207 abgelegt werden und die doppelten Autoren habe ich ebenfalls entfernt.
Viele Grüße, Helena Nebel
