### ISSUE TITLE
ISSN 2159-6808 | Journal of Religion and Violence (PDC) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1825]
#### URL
https://www.pdcnet.org/collection-anonymous/browse?fp=jrv&fq=jrv%2fVolume%2f8999%7c1%2f8999%7cIssue%3a+1%2f
https://www.pdcnet.org/jrv/content/jrv_2013_0001_0001_0007_0020

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Philosophy Documentation Center.js

  
### Problembeschreibung
Der Translator bricht sowohl im Einzel- als auch Mehrfachimport ab.
![image](https://user-images.githubusercontent.com/57000004/199508171-1b40d85b-7060-4b6f-9318-a5a313e5a38c.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das Problem sollte jetzt behoben sein.
Da keine Online-ISSN hinterlegt ist, wird die Print-ISSN übernommen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt nun!
