### ISSUE TITLE
ISSN 2163-6214 + 2051-3623 | Anglican theological review + Missiology | ub28 gelb

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1827]
### Problembeschreibung

Auf der ub28-Zotero Harvesting Oberfläche werden die beiden ZSen als gelb (=Warning) angezeigt. Bei den einzelnen Datensätzen ist jedoch keiner als gelb gekennzeichnet.
Könnte es etwas mit den schwarzen Online-First-Artikeln zu tun haben?

**Comment by jriedl** [comment]
> Könnte es etwas mit den schwarzen Online-First-Artikeln zu tun haben?

Da scheint davon unabhängig und deutlich subtiler zu sein: Zur Analyse: Eine Zeitschrift ist gelb, wenn sich in der Datenbank Datensätz mit Fehlern finden. Dies ist für beide Zeitschriften auch der Fall. Für "Missiology" fehlt für die DOI `https://doi.org/10.1177/00918296221106809` der Autor. Dies wurde auch mehrere Male detektiert. Das Problem ist aber, dass in der gleichen Zeitschrift auch die DOI `https://journals.sagepub.com/doi/10.1177/00918296221106809a` (mit **a** am Schluss) gibt - hier fehlte ebenfalls der Autor und die wurde manuell hochgeladen. Da das Tracking des Uploads (um bei der DOI-Behandlung nicht von unterschiedlichen URL-Schematas zu abstrahieren), die Abfrage der URL mit einem `LIKE %doi%` gemacht hat (was bedeutet, dass implizit davon ausgegangen wurde, dass die DOI Prefix-frei ist (also keine DOI genauso lautet, iwe eine andere DOI, die sich dann aber am Ende unterscheidet, was mit obigem Beispiel widerlegt ist), ist der Tracker davon ausgegangen, dass es für https://doi.org/10.1177/00918296221106809 bereits ein Eintrag existiert. Deshalb wurde kein Eintrag in der Tabelle `delivered_marc_records_urls` angelegt und da ein Artikel in der Übersicht nur angezeigt wird, wenn dies der Fall ist, taucht er dort momentan nicht auf.

**Comment by jriedl** [comment]
Auf nu ist nun eine Version installiert, die die DOI-Präfix-Problematik lösen sollte. Falls hier beim Durchlauf heute Abend keine anderweitigen Probleme auftreten, werde ich es morgen auf ub28 installieren und die Fehlermeldungen für die beiden Zeitschriften dort löschen.

**Comment by jriedl** [comment]
Anpassungen wie oben beschrieben nun auf ub28, d.h. aktuell sind beide Zeitschriften grün, d.h. die beiden Zeitschriften sind aktuell grün, nach dem nächsten Harvestdurchlauf der Zeitschriften sollten aber die beiden fraglichen Record dann ganz regulär als gelb auftauchen.

**Comment by IxKo** [comment]
Vielen Dank!
Die mysteriösen Artikel tauchen nun auf und sind gelb gekennzeichnet.
