### ISSUE TITLE
ISSN 1570-0585 | Arabica (Brill) | Doppelheft-Zählung 

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1829]
#### URL
https://doi.org/10.1163/15700585-12341653
  
### Problembeschreibung
Auf ub28 werden die meisten Artikel des neuesten Heftes 4/5 aufgrund der RegEx-Anforderung 936 $e als Errors gekennzeichnet.

![image](https://user-images.githubusercontent.com/57000004/201146544-d2c80b15-253d-4e58-9420-1b5cb1497b82.png)

Es wundert mich, da ein einzelner Artikel aus demselben Heft diese Problematik nicht hatte und korrekt mit Trennzeichen / bei der Heftzählung eingespielt wurde: IxTheo#2022-11-09#183B004365DE6B0ABD03C1E923073756BFDEB5C6

**Comment by jriedl** [comment]
Laut Screenshot ist die Heftangabe 4-5 und entspricht damit korrekterweise nicht dem Regex.

________________________________
From: IxKo ***@***.***>
Sent: Thursday, November 10, 2022 5:08:19 PM
To: ubtue/DatenProbleme
Cc: Subscribed
Subject: [ubtue/DatenProbleme] ISSN 1570-0585 | Arabica (Brill) | Doppelheft-Zählung (Issue #1829)


URL

https://doi.org/10.1163/15700585-12341653

Problembeschreibung

Auf ub28 werden die meisten Artikel des neuesten Heftes 4/5 aufgrund der RegEx-Anforderung 936 $e als Errors gekennzeichnet.

[image]<https://user-images.githubusercontent.com/57000004/201146544-d2c80b15-253d-4e58-9420-1b5cb1497b82.png>

Es wundert mich, da ein einzelner Artikel aus demselben Heft diese Problematik nicht hatte und korrekt mit Trennzeichen / bei der Heftzählung eingespielt wurde: IxTheo#2022-11-09#183B004365DE6B0ABD03C1E923073756BFDEB5C6

**Comment by jriedl** [comment]
Dass der eine Artikel korrekt eingespielt wurde, hängt wahrscheinlich damit zusammen, dass er frei zugänglich ist. Laut Log wurde hier ubtue_brill verwendet (der das Rewriting von '-' auf '/' beherrscht), für die anderen  kam (evtl. aufgrund einer Brill-seitigen Umleitung) der Standard-Brill-Translator zum Einsatz, der das nicht kann. Muss noch geklärt werden, warum genau das passiert.

**Comment by jriedl** [comment]
Wie vermutet ist da eine Umleitung auf `abstract/view` erfolgt. Habe auf nu einen angepassten `ubtue_Brill`  mit diesem zusätzlichen Target eingespielt. Falls es morgen keine Auffälligkeiten gibt, wandert es auf ub28.

**Comment by jriedl** [comment]
Aktueller Stand seit gestern auf ub28, allerdings findet sich im Logfile der gestrigen Einspielung die Fehlermeldung, dass der Feed nicht heruntergeladen werden konnte (dies galt scheinbar für alle Brill-Feeds gestern). Manuell ist es für diese Zeitschrift aktuell von ub28 aus möglich, so dass der Durchlauf heute Abend abgewartet werden muss.

**Comment by jriedl** [comment]
Arabica ist auf ub28 jetzt grün.

**Comment by IxKo** [comment]
Wunderbar, vielen Dank!
