### ISSUE TITLE
ISSN 1863-0502 | Theo-Web | Endseitenberechnung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1830]
#### URL
https://www.theo-web.de/ausgaben/2022/21-jahrgang-2022-heft-2
  
#### Import-Translator
  Mehrfachimport:
ubtue_TheoWeb.js

  
### Problembeschreibung
Bei dieser ZS werden die Seitenangaben nur bei der Heftübersicht angezeigt und auch nur die Anfangsseite eines Artikels.
Beispiel:
Artikel 1 beginnt auf S. 1
Artikel 2 beginnt auf S. 7

Der Translator schafft es automatisch eine Endseite zu erzeugen, indem er die Anfangsseite des nächsten Artikels als Endseite festlegt. (Beispiel Artikel 1: 1-7)
Könnte man das anders berechnen, sodass er als Endseite die Anfangsseite des nächsten Artikels - 1 berechnet, sodass es im Beispiel bei Artikel 1: Seite 1-6 wird?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert super!
