### ISSUE TITLE
ISSN 2637-7500 | Socio-historical examination of religion and ministry (shermjournal) | Neuer Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1831]
#### URL
https://www.shermjournal.org/vol-4-no-1
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner
  
### Problembeschreibung
Bitte prüfen, ob für diese Zeitschrift ein Translator angelegt werden kann. Wenn, dann wahrscheinlich nur Einzelimport möglich, da Titel nicht im Seitenquelltext der Übersicht auftauchen

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt auch funktionieren.
Viele Grüße, Helena Nebel
