### ISSUE TITLE
ISSN 1868-8020 | Early christianity (Mohr Siebeck) | Import-Abbruch

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1832]
#### URL
https://www.mohrsiebeck.com/zeitschrift/early-christianity-ec
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Mohr Siebeck.js

### Problembeschreibung
Beim Speichern werden alle Artikel grau angezeigt, dann bricht der Import ab. Keine Fehlermeldung.

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
ich kann leider nicht herausfinden, was das Problem ist. Wenn man allerdings den Artikel "Table of Contents" nicht mit herunterlädt, dann funktioniert es.
Ich vermute, dass das Problem mit dem intern aufgerufenen COinS-Translator und der nicht resolvenden DOI zusammenhängt. Leider kann ich da nichts machen.
Viele Grüße, Helena Nebel

**Comment by DowntownOcean** [comment]
@helenanebel Das gleiche Problem hatte ich jetzt zwischenzeitlich auch anderswo, dann werde ich die "Table of Contents" in Zukunft einfach manuell katalogisieren
