### ISSUE TITLE
ISSN 2792-3045 | Archivo agustiniano (Provincia) | Neuer Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1833]
#### URL
https://www.agustinosvalladolid.es/estudio/investigacion/archivoagustiniano/archivofondos/archivo2022.html
  
#### Import-Translator
  Einzel- und Mehrfachimport:
 Keiner

### Problembeschreibung
Kann für diese Website ein neuer Translator angelegt werden?

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
unter der URL https://dialnet.unirioja.es/ejemplar/614208 wären die Metadaten verfügbar und dafür gibt es bereits einen Translator. Die URLs gehen jeweils auf das PDF auf der oben genannten Seite.
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
unter der URL https://dialnet.unirioja.es/ejemplar/614208 wären die Metadaten verfügbar und dafür gibt es bereits einen Translator. Die URLs gehen jeweils auf das PDF auf der oben genannten Seite.
Viele Grüße, Helena Nebel

**Comment by DowntownOcean** [comment]
Okay @helenanebel , ich hatte die Zeitschrift nur gerade auf die Onlineausgabe umgestellt und wollte die Qualität zur Druckausgabe halten. Dialnet scheint nicht ganz vollständig zu sein. Hab gerade gesehen, dass bis jetzt aber auch nur Artikel katalogisiert wurden, die auch auf Dialnet sind, dementsprechend werde ich das auch nehmen.

**Comment by thefass** [comment]
@DowntownOcean Heißt das, dass wir nicht alle Artikel eines Heftes erfassen können, da nicht alle Artikel in Dialnet eingestellt werden? Das wäre schlecht

**Comment by DowntownOcean** [comment]
@thefass Ich bin mir nicht sicher, ob die zusätzlichen Artikel für uns relevant/erfassungswürdig sind, da sie unter "Texte und Glossar" stehen. Ich wollte bei Herr Cloutier dementsprechend nochmal nachfrage.

**Comment by DowntownOcean** [comment]
@thefass Die Verlagsseite ist laut Frau Nebel leider nicht für einen Translator geeignet. Ich werde aber einen Vermerk in Zeder machen, dass die auf Dialnet fehlenden, zusätzlichen Texte in Zukunft händisch bei der Katalogisierung nachgetragen werden. Herzliche Grüße, Kenny Albrecht
