### ISSUE TITLE
ISSN 1554-3897 | African Journal of Criminology and Justice Studies (umes) | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1837]
#### URL
https://wwwcp.umes.edu/ajcjs/vol-13-issue-1-spring-2020/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung

Kann hier ein neuer Translator geschrieben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit ubtue_umes sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert.
