### ISSUE TITLE
ISSN 1552-6119 | Child Maltreatment (SAGE) | Abstract fehlt

### ISSUE THREAD

**Issue by Krimis** [ubtue/DatenProbleme#1838]
#### URL
https://journals.sagepub.com/doi/abs/10.1177/1077559596001001007
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SAGE Journals.js

  
### Problembeschreibung
Abstract wird nicht importiert

**Comment by helenanebel** [comment]
Liebe @Krimis ,
jetzt sollte das Abstract importiert werden.
Viele Grüße, Helena Nebel

**Comment by Krimis** [comment]
Vielen Dank und viele Grüße
