### ISSUE TITLE
ISSN 2468-5542 | Journal of Islamic ethics (Brill) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1840]
#### URL
https://brill.com/view/journals/jie/6/2/article-p257_5.xml
https://brill.com/view/journals/jie/6/2/article-p284_6.xml

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Brill.js

  
### Problembeschreibung
Die ORCID-Angabe wird nicht importiert.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die Orcid sollte jetzt mitkommen.
Viele Grüße, Helena Nebel
