### ISSUE TITLE
ISSN 2150-9301 | Religion and Society (Berghahn) | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1843]
#### URL
https://www.berghahnjournals.com/view/journals/religion-and-society/religion-and-society-overview.xml
  
#### Import-Translator
  Einzel- und Mehrfachimport:
kein ubtue-Translator, nur Embedded Metadata, DOI..

  
### Problembeschreibung
Könnte für diese Seite ein Import-Translator fürs halbautomatische Verfahren geschrieben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem Translator ubtue_BerghahnJournals sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt wunderbar. Sogar LF und Rezensionen werden erkannt!
