### ISSUE TITLE
ISSN 2375-5814 | The Asbury Journal | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1844]
#### URL
https://place.asburyseminary.edu/asburyjournal/vol77/iss2/
  
#### Import-Translator
  Einzelimport:
COins

  
### Problembeschreibung
Könnte für diese Website ein neuer Translator bereitgestellt werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit ubtue_Asbury Journal sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
danke, funktioniert.
Obwohl eine Fehlermeldung erscheint, importiert es die Einträge nach Zotero:
![image](https://user-images.githubusercontent.com/57000004/206505392-5a5839fe-742b-4642-bf01-eee88ee782c7.png)
