### ISSUE TITLE
1046-8064 | Research in the social scientific study of religion (Brill) | Schriftenreihe, ubtue_Brill.js funktioniert nicht

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1846]
[#### URL](https://brill.com/display/serial/RSSR?alreadyAuthRedirecting)

  
#### ubtue_Brill.js
  Einzel- und Mehrfachimport:
<Name von genutzten Translator (siehe auch: https://github.com/ubtue/zotkat-translators oder Zeder p_zot3)>

  
###Schriftenreihe, es wird nur das ganze Heft, nicht die Artikel heruntergeladen.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
der Download von Monografien ist in unserem Verfahren nicht vorgesehen.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Danke für Info und Grüße, Sybille Deselaers
