### ISSUE TITLE
ISSN 0378-7931 | Déviance et Société (Cairn) | weitere Abstracts und Absätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1848]
#### URL
https://www.cairn.info/revue-deviance-et-societe-2022-3-page-289.htm
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cairn.info.js

  
### Problembeschreibung
Die weiteren Abstracts (deutsch und spanisch) werden nicht importiert.

Außerdem wird das französische Abstract mit sehr vielen Absätzen importiert, die beim Export stören:
![image](https://user-images.githubusercontent.com/57000004/206456546-49422711-7f31-48d6-8641-94d1546fb7d0.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke sehr, funktioniert wunderbar!
