### ISSUE TITLE
ISSN 0378-7931 | Déviance et Société (Cairn) | weitere Tags/Schlagworte

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1849]
#### URL
https://www.cairn.info/revue-deviance-et-societe-2022-3-page-289.htm
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cairn.info.js
  
### Problembeschreibung
Die anderen Tags/Schlagworte auf deutsch und spanisch werden nicht importiert.
![image](https://user-images.githubusercontent.com/57000004/206457142-bce057e9-bf92-4246-a7c0-7e7dc0c713c4.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, sind nun dabei!
