### ISSUE TITLE
ISSN 0378-7931 | Déviance et Société (Cairn) | LF-Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1850]
#### URL
https://www.cairn.info/revue-deviance-et-societe-2017-3.htm
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cairn.info.js

  
### Problembeschreibung
Die Artikel dieses Heftes sind alle frei verfügbar.
Könnte diese Information direkt mit der Notiz LF: importiert werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Super, funktioniert. Vielen Dank!
