### ISSUE TITLE
ISSN 1988-7949 | International E-Journal of Criminal Sciences (OJS) | Bandangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1852]
#### URL
https://ojs.ehu.eus/index.php/inecs/issue/view/1906
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung
Diese ZS hat eine durchgängige Heftzählung ohne zusätzliche Bandangabe, weswegen die Zählung in die Bandangabe laut Handbuch muss. Könnte das beim Import oder Export entsprechend für diese ZS angepasst werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt!
