### ISSUE TITLE
ISSN 1988-7949 | International E-Journal of Criminal Sciences (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1853]
#### URL
https://ojs.ehu.eus/index.php/inecs/article/view/23905
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die ORCID-Angabe des Autors wird nicht nach Zotero importiert. Könnte das angepasst werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, die ORCID kommt nun mit!
