### ISSUE TITLE
ISSN 1043-500X | Journal of Offender Monitoring (CRI) | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1854]
#### URL
https://civicresearchinstitute.com/online/issue.php?pid=13
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Könnte für diese Website ein neuer Translator geschrieben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
mit dem neuen Translator ubtue_CRI sollte es gehen.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Super, vielen Dank!
