### ISSUE TITLE
ISSN 1534-0708 | The Catholic Historical Review (MUSE) | Einzel-Import

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1857]
#### URL
Heft: https://muse.jhu.edu/issue/48567
einzelner Artikel: https://muse.jhu.edu/pub/16/article/871985
  
#### Import-Translator
 Mehrfachimport:
ubtue_Project MUSE.js

  
### Problembeschreibung
Es wird mir kein Einzel-Import auf einer Artikel-Seite angeboten.

Könnte das behoben werden?

**Comment by helenanebel** [comment]
Liebe @IxKo ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Vielen Dank, klappt!
