### ISSUE TITLE
1710-825X | Canadian Journal of Buddhist Studies  | Kein Download möglich

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1858]
#### Embedded Metadata
  Einzel- und Mehrfachimport:
<Name von genutzten Translator (siehe auch: https://github.com/ubtue/zotkat-translators oder Zeder p_zot3)>

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
mit dem Translator ubtue_CJBS sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, klappt.
