### ISSUE TITLE
0128-4878 | Intellectual discourse (verm. OJS) | Seitenzahlen werden nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1859]
#### Open Journal Systems Standard
  Mehrfachimport:

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das müsste daran liegen, dass bei den von mir geprüften Artikeln auch keine Seitenzahlen angegeben sind. Falls es einen konkreten Aufsatz gibt, bei dem Seitenzahlen angegeben sind, die allerdings nicht importiert werden, diesen bitte angeben.
Viele Grüße. Helena Nebel

**Comment by RelBibRetroKat** [comment]
Verstanden und Dank. Viele Grüße Sybille Deselaers
