### ISSUE TITLE
ISSN 2045-9238 | Law, Crime and History (PubPub) | Neuer Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1860]
#### URL
https://lawcrimehistory.pubpub.org/currentissue
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner 

### Problembeschreibung
Bitte neuen Translator anlegen, falls möglich

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
der Translator ubtue_PubPub sollte jetzt in fast allen Fällen gute Ergebnisse liefern; da Seitenzahlen, Autoren und Titel allerdings im Seitenquelltext nicht getrennt eingesehen werden können, kommt es manchmal vor, dass Autoren und Titel nicht sauber getrennt werden und Teile der Autoren im Titel landen oder vice versa.
Deshalb sollte hier immer besonders aufgepasst werden.
Viele Grüße, Helena Nebel

**Comment by DowntownOcean** [comment]
Danke @helenanebel. Ich vermerke das Problem bei Zeder.
