### ISSUE TITLE
1574-9282 |  International journal of Hindu studies (Springer) | bei Retrokatalogisierung Fehler beim Download

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1861]
[#### URL](https://www.springer.com/journal/11407)

  
####ubtue_Springer Link
  Mehrfachimport

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das sollte jetzt wieder funktionieren.
Viele Grüße, Helena Nebel
P.S. Bitte jeweils das Produktionsverfahren der betreffenden Zeitschrift angeben.

**Comment by RelBibRetroKat** [comment]
Getestet. Funktioniert. Danke. Viele Grüße Sybille Deselaers
