### ISSUE TITLE
 ISSN 2079-5971 | Oñati Socio-legal Series (OJS) | Mehrsprachige Abstracts

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1862]
#### URL
https://opo.iisj.net/index.php/osls/issue/view/118
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

### Problembeschreibung
Die Abstracts sind in mehreren Sprachen verfügbar, werden aber in 4207 nicht getrennt

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel
