### ISSUE TITLE
ISSN 2079-5971 | Oñati Socio-legal Series (OJS) | DOI

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1863]
#### URL
https://opo.iisj.net/index.php/osls/issue/view/118
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

### Problembeschreibung
DOI wird nicht erkannt, wird bei Zeder in die Zusammenfassung importiert

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
das sollte jetzt funktionieren.
Viele Grüße, Helena Nebel
