### ISSUE TITLE
ISSN 2334-3745 | Perspectives on Terrorism (JSTOR) | URL 

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1864]
#### URL
https://www.jstor.org/stable/e27168610
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_JSTOR.js

### Problembeschreibung
URL der Artikel wird beim Export nicht übertragen

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
die ISSN ist nicht in der Mappingsliste hinterlegt, URLs werden beim Export nur generiert, wenn der Satzstatus O** ist.
Wenn die ISSN hinterlegt ist, sollte es klappen (auch 4241 und 5056 werden bisher nicht generiert).
Viele Grüße, Helena Nebel
