### ISSUE TITLE
ISSN 2385-779X | Revista de victimología (Dialnet) | URL

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1865]
#### URL
https://dialnet.unirioja.es/ejemplar/615367
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Dialnet.js

### Problembeschreibung
URL der Artikel wird beim Export nicht übertragen

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
wie im anderen Issue (https://github.com/ubtue/DatenProbleme/issues/1864) muss ein Eintrag in der Mappingliste hinterlegt sein, der den Satzstatus O** steuert.
Viele Grüße, Helena Nebel
