### ISSUE TITLE
2009-7409 | Journal of the Irish Society for the Academic Study of Religions (University College Cork) | Download nicht möglich (Embedded Metadata)

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1868]
#### URL
https://jisasr.org/volume-8-2021/
  
#### Import-Translator
  Mehrfachimport angestrebt
<Zeitschrift neu, jetzt "Embedded Metadata", aber Autor, Titel, Seitenzahlen, Link zu PDF auf Website>

  
### Problembeschreibung
Zeitschrift neu, jetzt "Embedded Metadata", aber Autor, Titel, Seitenzahlen,  Link zu PDF auf Website>

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
der Translator ubtue_jisasr funktioniert für die Mehrzahl der Bänder und Artikel, allerdings können einige Artikel nicht mitgenommen werden und Band 1 ist ebenfalls nicht möglich.
Leider ist der Seitenquelltext so schlecht formatiert, dass eine bessere Übernahme nicht möglich ist.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet. Dank für neuen Translator. Viele Grüße, Sybille Deselaers
