### ISSUE TITLE
2571-242X  |  e-Rhizome Palacký University Olomouc | Zeitschrift neu, jetzt "Save to Zotero (DOI)"

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1869]
#### URL
https://www.e-rhizome.upol.cz/
  
#### Import-Translator
 Mehrfachimport angestrebt:
<Zeitschrift neu, jetzt "Save to Zotero (DOI)">

  
### Problembeschreibung
Zeitschrift neu, Autor, Titel, Ausgabe, Seitenzahl, Link, Abstract online, vermutlich neuer Translator?

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
mit dem Translator ubtue_erhizome sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet. Download der Daten funktioniert, Vokale mit diakritischen Zeichen wie ü, á, š, ě werden als � dargestellt. Gibt es dafür eine Lösung? Viele Grüße, Sybille Deselaers

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das ist ein Problem in Zotero, mit dem gleichen Translator im Einzel-Download kommen die Diakritika korrekt rüber. Darauf habe ich leider keinen Einfluss.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Ist vermerkt. Vielen Dank und Grüße, Sybille Deselaers
