### ISSUE TITLE
2532-6740 |  Occhialì: rivista sul Mediterraneo islamico (Università della Calabria) | Zeitschrift neu, jetzt "Embedded Metadata"

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1870]
#### URL
https://rivistaocchiali.com/
  
#### Import-Translator
  Mehrfachimport angestrebt
<Jetzt "Embedded Metadata">

  
### Problembeschreibung
Zeitschrift neu, jetzt "Embedded Metadata", aber Autor, Titel, Link zu PDF auf Website

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
der Seitenquelltext ist ungeeignet für eine Verarbeitung mit Zotero.
Viele Grüße, Helena Nebel
