### ISSUE TITLE
1866-069X | Medaon: Magazin für Jüdisches Leben in Forschung und Bildung (Qucosa) | Fehlende Angaben bei Einzeldownload

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1871]
#### URL
https://nbn-resolving.org/urn:nbn:de:bsz:14-qucosa2-343555
  
#### Translator: COinS
  Mehrfachimport: Fehlermeldung: Nutzung von Embedded Metadata statt COinS
<Name von genutzten Translator (siehe auch: https://github.com/ubtue/zotkat-translators oder Zeder p_zot3)>

###Mehrfachimport: Fehlermeldung: Nutzung von Embedded Metadata statt COinS
Einzeldownload (auch Translator COinS): Es fehlen URN, Keywords, Link und unter Erstveröffentlichung steht korrektes Erscheinungsjahr

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
mit dem Translator ubtue_qucosa sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena,

beim Herunterladen wird mir immer der Translator COinS angezeigt, obwohl ich bereits mehrfach aktualisiert habe.

Viele Grüße

Sybille Deselaers

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das Issue ist noch nicht auf "ready for testing".
Viele Grüße, Helena Nebel

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
jetzt kann getestet werden.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Beim Test wird die urn heruntergeladen, aber ich kann die Daten nicht von Zotero in bsz_biblitheken.js kopieren

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das lag daran, dass die URL nicht mitgenommen wurde. Jetzt sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet, Aufsatzdaten werden eingespielt, korrektes Erscheinungsjahr steht in Erstveröffentlichung. Viele Grüße, Sybille Deselaers

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
das Erscheinungsjahr ist für diese Plattform korrekt. Für eine bibliothekatisch richtige Übertragung mit 1109/4048 usw. ist unsere Infrastruktur leider nicht ausgelegt, das macht der Export-Translator nicht.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena Nebel,
vielen Dank für die Info. Vermerkt. Viele Grüße, Sybille Deselaers
