### ISSUE TITLE
ISSN 1813-3495 | SIAK-Journal (www.bmi.gv.at) | Neuer Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1872]
#### URL
https://www.bmi.gv.at/104/Wissenschaft_und_Forschung/SIAK-Journal/SIAK-Journal-Ausgaben/Jahrgang_2022/Ausgabe_3.aspx
  
#### Import-Translator
  Einzel- und Mehrfachimport:

  
### Problembeschreibung
Kann hier ein neuer Translator angelegt werden?

**Comment by helenanebel** [comment]
Lieber @DowntownOcean ,
mit dem Translator ubtue_siak sollte es im Multi-DL funktionieren.
Viele Grüße, Helena Nebel

**Comment by DowntownOcean** [comment]
Funktioniert alles, danke @helenanebel
