### ISSUE TITLE
2643-9247 | American religion (Projekt MUSE) | Es werden keine Titeldaten heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1874]
[#### URL]https://muse.jhu.edu/journal/825

  
#### Import-Translator
  Mehrfachimport:
ubtue_Project MUSE

  
### Trotz Freischaltung für Unibibliothek Tübingen und Einloggen in Account für indextheologicus werden keine Titeldaten heruntergeladen.
Es ist in Zeder der Link für JSTOR hinterlegt, aber dort sind nicht alle Ausgaben eingestellt.

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
bei mir funktioniert der Download. Kommt bei dir eine Fehlermeldung?
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Liebe Helena,
ich habe jetzt vermerkt, dass man den Translator "gründlich" aktulisieren muss. Es hat danach funktioniert. Sorry und Grüße, Sybille Deselaers
