### ISSUE TITLE
1982-8136  |  Debates do NER (OJS) | Band und Ausgabe werden nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1875]
#### URL
https://seer.ufrgs.br/index.php/debatesdoner/index
  
#### Import-Translator
  Mehrfachimport:
Open Journal System Standard

  
### Problembeschreibung
Band und Ausgabe werden nicht heruntergeladen

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
jetzt sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet. Funktioniert. Vielen Dank und Grüße, Sybille Deselaers
