### ISSUE TITLE
2532-1676 | Nuovo giornale di filosofia della religione (OJS) | Band und Ausgabe werden nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1876]
#### URL
https://journals.uniurb.it/index.php/NGFR/index
  
#### Import-Translator
 Mehrfachimport:
Open Journal System Standard

  
### Problembeschreibung
Band und Ausgabe werden nicht heruntergeladen

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
die Daten sind leider im Seitenquelltext nicht hinterlegt und können auch über die DOI nicht fehlerfrei heruntergeladen werden.
Diese und das Datum müssten händisch korrigiert/ergänzt werden.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Danke für die Prüfung und Grüße, Sybille Deselaers
