### ISSUE TITLE
2336-4483  | Sacra: studentský religionistický časopis (Masarykova Univ.) | Handle wird nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1877]
#### URL
https://journals.phil.muni.cz/sacra/
  
#### Import-Translator
  Einzelimport:
Open Journal System Standard

  
### Problembeschreibung
Handle wird nicht heruntergeladen

**Comment by helenanebel** [comment]
Liebe @RelBibRetroKat ,
jetzt sollten die Handles mitkommen.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet und funktioniert. Vielen Dank, Sybille Deselaers
