### ISSUE TITLE
2962-665X | Indonesian journal of religion, spirituality and humanity (State Islamic University (UIN) Salatiga) |  Seitenzahl wird nicht heruntergeladen

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#1878]
#### URL
https://e-journal.iainsalatiga.ac.id/index.php/ijoresh/issue/view/347
  
#### Import-Translator
  Mehrfachimport:
Open Journal System Standard

  
### Problembeschreibung
Seitenzahl wird nicht heruntergeladen

**Comment by helenanebel** [comment]
Lirbe @RelBibRetroKat ,
jetzt sollten die Seitenzahlen übernommen werden.
Viele Grüße, Helena Nebel

**Comment by RelBibRetroKat** [comment]
Getestet und funktioniert problemlos. Vielen Dank.
