### ISSUE TITLE
ISSN 2166-8094 | Journal of Theoretical and Philosophical Criminology (Ebsco) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1879]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dpdh%26jid%3dTEO%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Der Import bricht ab.
![image](https://user-images.githubusercontent.com/57000004/208440650-cf85ac22-94a8-487f-86a7-0740ab29056c.png)

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollte der Download funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, funktioniert!
