### ISSUE TITLE
ISSN 2340-4256 | Cauriensia (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1880]
#### URL
https://cauriensia.es/index.php/cauriensia/article/view/477
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die ORCID wird nicht importiert.
Außerdem wird der Translator nicht als erster angeboten.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
die ORCID sollte jetzt mitkommen & der Translator als erster angeboten werden.
Viele Grüße. Helena Nebel

**Comment by IxKo** [comment]
Danke, die ORCID kommt mit und der Translator wird auch als erster angeboten.

Allerdings wird die/der Verfasser:in zweimal importiert:
![image](https://user-images.githubusercontent.com/57000004/209132926-8c45c680-92e4-49fc-95c5-d37b8bfedd9f.png)

**Comment by IxKo** [comment]
Auch das Abstract wird zweimal importiert, was nicht ganz so schlimm ist, da das unnötige Abstract sowieso gelöscht werden muss:
![image](https://user-images.githubusercontent.com/57000004/209134098-aaeaf95f-5303-45e3-b34c-91044c7faad0.png)
Aber es wird auch eine unnötige Übersetzung des Titels übertragen, die ebenfalls manuell gelöscht werden sollte.

**Comment by IxKo** [comment]
Probleme bestehen weiterhin.
Zudem wird bei einem anderen Aufsatz im gleichen Heft die ORCID nicht importiert: https://cauriensia.es/index.php/cauriensia/article/view/456

**Comment by IxKo** [comment]
Danke, größtenteils behoben.

Die Rezensionen werden noch nicht automatisch gekennzeichnet, wäre das möglich? 
Und zusätzlich die beiden anderen Punkte?

- [ ] RezensionstagPica
- [ ] Rezensions-Abstract entfernen: "Reseña de libro\n4207 Reseña de libro\n4207"
- [ ] übersetzten Titel entfernen, denn es gibt keinen übersetzten Titel bei den Rezensionen

**Comment by IxKo** [comment]
Nun erhalten alle Beiträge das Tag RezensionstagPica. Es sind aber nicht alles Rezensionen wie bspw. der Beitrag https://doi.org/10.17398/2340-4256.16.19

Das überflüssige Abstract bei der Rezension wird hingegen weiterhin und nun mit einleitender Wendung "undefined" importiert: 

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/8f6c0fd0-2384-4432-b12f-a0417487601c)
