### ISSUE TITLE
ISSN 2340-4256 | Cauriensia (OJS) | Keywords und Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1881]
#### URL
https://cauriensia.es/index.php/cauriensia/article/view/498
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung

- [x] Die Keywords werden nicht importiert bzw. sie landen beim Abstract.

- [x] Die beiden Abstracts werden nicht voneinander getrennt.

**Comment by helenanebel** [comment]
Liebe @IxKo ,
jetzt sollte es funktionieren.
Viele Grüße, Helena Nebel

**Comment by IxKo** [comment]
Danke, passt!

**Comment by IxKo** [comment]
Keywords kommen wieder nicht mit.

**Comment by IxKo** [comment]
Danke, passt nun wieder!
