### ISSUE TITLE
ISSN 1584-7624 | Sacra Scripta (CEEOL) | Keywords Umlaute

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1882]
#### URL
https://www.ceeol.com/search/article-detail?id=148736
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Central and Eastern European Online Library.js

  
### Problembeschreibung
Wenn sich Umlaute in einem Keyword befinden, wird dieses gesplittet - im Beispiel Väter:

![image](https://user-images.githubusercontent.com/57000004/211277033-3eb89869-cd82-49ca-af8d-730168e0bffa.png)

Die ZS wurde im Retro-Katalogisierungsprojekt erfasst.

**Comment by socheres** [comment]
das war auch der Fall beim abstract. Habe den Fehler behoben.

**Comment by IxKo** [comment]
Danke, das Problem besteht nicht mehr.
