### ISSUE TITLE
ISSN 0362-1529 | Traditio (Cambridge) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1883]
#### URL
https://www.cambridge.org/core/journals/traditio/article/defense-of-the-carolingian-defense-of-medicine-introduction-translation-and-notes/B2CDF22B95C180B601853EFCB32DC596
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js
  
### Problembeschreibung
Die Keywords aus den Metadaten `<meta name="citation_keywords" content="`
werden nicht korrekt beim Semikolon getrennt, sondern zerpflückt:
![image](https://user-images.githubusercontent.com/57000004/211339124-be1aeb52-10f3-48e2-8383-7b005efef054.png)

Es ist zudem die Frage zu stellen, ob die Keywords aus diesen Metadaten genommen werden sollten. In der HTML-Anzeige sind es deutlich weniger:
![image](https://user-images.githubusercontent.com/57000004/211339385-6c2c32bb-bfdc-4fd5-b4ef-9701139d8c42.png)

**Comment by socheres** [comment]
Translator wurde nur für diese Zeitschrift angepasst. wenn auch andere Zeitschriften von Cambridge ebenfalls betroffen sind, melden Sie dies bitte.

**Comment by IxKo** [comment]
Danke, das Problem tritt nicht mehr auf!
