### ISSUE TITLE
ISSN 1467-9744 | Zygon (Wiley) | Nicht-Titelbestandteile

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1884]
#### URL
https://onlinelibrary.wiley.com/doi/full/10.1111/zygo.12843
 IxTheo#2022-12-11#879394D9332BAC866673A4F30D958921E5AC5224

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Wiley Online Library.js

  
### Problembeschreibung

Es werden Bestandteile in den Titel übertragen, die meines Erachtens nicht zum Titel gehören:

![image](https://user-images.githubusercontent.com/57000004/211596982-c5bcca0f-9203-4c84-8ab2-35774ad8b60a.png)
![image](https://user-images.githubusercontent.com/57000004/211597521-e21826d9-635d-4b81-abb4-b40e628a7cea.png)

**Comment by socheres** [comment]
Leider steht es so im Quelltext drin. Da kann man nichts machen. das Feld citation_subtitle ist in der Regel richtig belegt. Z.B.    view-source:https://onlinelibrary.wiley.com/doi/10.1111/erev.12580 `<h3 class="citation__subtitle">Comparing Orthodox Responses to Vatican II</h3>` Daher schließe ich das Issue.

```
<h3 class="citation__subtitle">with Zachary Ardern, “The Contentious Compatibility of Evolution and Design: Introduction to the Book Symposium”; David H. Glass, “An Evaluation of the Biological Case for Design”; Meghan D. Page, “Thomist or Tumblrist: Comments on <i>The Compatibility of Evolution and Design</i> by E. V. R. Kojonen”; Peter Jeavons, “The Design of Evolutionary Algorithms: A Computer Science Perspective on the Compatibility of Evolution and Design”; Denis R. Alexander, “Evolution, Chance, Necessity, and Design”; Bethany N. Sollereder, “Response to <i>The Compatibility of Evolution and Design</i>”; Mats Wahlberg, “Divine Design and Evolutionary Evil”; and Erkki V. R. Kojonen, “Response: The Compatibility of Evolution and Design.”</h3>
```

**Comment by IxKo** [comment]
Dann würde ich diese Zs. aus dem zota-Verfahren zurücknehmen. Denn die Titel müssen alle manuell korrigiert werden.
