### ISSUE TITLE
ISSN 2633-0695 | Journal for Interdisciplinary Biblical Studies (jibs) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1885]
#### URL
https://jibs.hcommons.org/archive/volume-4/volume-4-issue-3/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Die Website-Struktur scheint sich geändert zu haben. Der Translator _ubtue_Journal for Interdisciplinary Biblical Studies.js_ wird nicht angeboten.
Die ZS wird von Innsbruck erschlossen (siehe Mail vom 11.01.23).

Könnte der vorherige Translator wieder in Gang gesetzt bzw. angepasst werden?

**Comment by socheres** [comment]
Wegen der Webseitenstruktur werden beim Multi-DL überall "Download PDF"  anstelle der Titel angezeigt, diese sind jedoch vollständig.

**Comment by IxKo** [comment]
Funktioniert, danke!
