### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity (OJS-Tue) | neues Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1887]
#### URL
https://jeac.de/ojs/index.php/jeac/issue/view/88
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Es ist seit bald einen Monat (17.12.22) ein neues Heft 2022,4 erschienen. Es ist jedoch noch nicht eingespielt.

Stimmt vielleicht wieder irgendetwas mit den OJS-Tue-Feeds nicht?
Wenn ich den Feed (https://jeac.de/ojs/index.php/jeac/gateway/plugin/WebFeedGatewayPlugin/rss) in einem RSS-Reader eingebe, werden mir die Artikel vom neuen Heft angezeigt.

Mit TRY RSS auf ub28 wird kein File erzeugt und im CLI Output heißt es: "could not download RSS feed"

**Comment by jriedl** [comment]
Das Problem war/ist das auf Anbieterseite verwendete Zertifkat: Es handelt sich um ein Let's encrypt-Zertifikat, das  `curl`, die Softwarebibliothek, die sich im Zotero-Harvester um den Download kümmert und auch der Translationsserver, nicht verifizieren konnten und deshalb abgebrochen haben (Browser sind diesbezüglich scheinbar nachlässiger bzw. können noch zusätzliche Wege nutzen, deshalb ist die Anzeige dort erfolgreich). Leider findet sich benötigte Zertifikat auch nicht in den aktuellen Zertifikats-Standardpacketen. Durch manuelle Integration ist es nun auf nu und ub28 auf dem Hostsystem selbst (`lets-encrypt-r3.pem` als `crt` in /usr/local/share/ca-certificates + update-ca-certifcates) und im Translationserver (extra_certs) integriert.

**Comment by thefass** [comment]
@jriedl Was meint Anbieterseite? Die Zeitschrift läuft auf unserer OJS Instanz. Müßten also wir etwas in Bezug auf die Zertifikate unternehmen?

**Comment by jriedl** [comment]
Das Problem ist/war das fehlende Überprüfbarkeit des Zertifikats R3 (vgl. https://letsencrypt.org/certificates/). Anfrage an P&E läuft.

**Comment by IxKo** [comment]
Danke!
Band 4 (2022) wurde heute eingespielt.
