### ISSUE TITLE
ISSN 0896-8039 | Anglican & episcopal history (EBSCO) | Translator URL

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1889]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000003195%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Beim Import der Daten aus EBSCO werden keine URLs importiert.
Dies hat zur Folge, dass Export (Einzel- und Mehrfach-Export) aus Zotero nicht funktioniert.

Das trifft auf alle EBSCO-ZSen zu.

**Comment by IxKo** [comment]
Bitte rückgängig machen.

Nun werden die redi-bw-Links bei den EBSCO-ZSen, die wir an die O-Aufnahme katalogisieren, nicht erzeugt und dadurch nicht im Exemplar-Satz hinterlegt.

**Comment by socheres** [comment]
redi link wird nun importiert.

**Comment by IxKo** [comment]
Danke!
Nun müsste es noch so konfiguriert werden, dass der redi-bw-Link nur bei O-Aufnahmen in Feld 7133 im Exemplarsatz exportiert wird, aber nicht bei A-Aufnahmen.

**Comment by socheres** [comment]
redi-bw-link wird nur bei O-Aufnahmen in Feld 7133 erzeugt, sonst nicht.

**Comment by IxKo** [comment]
Danke, passt nun!
