### ISSUE TITLE
ISSN 2053-7158 | Correspondences | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1892]
#### URL
https://correspondencesjournal.com/volume-10/issue-1/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Könnte für diese ZS-Website ein neuer Translator geschrieben werden?
Momentan wird die ZS mit ImWa bearbeitet und laut Zeder-Bemerkungsfeldern aufwändig überarbeitet.

**Comment by IxKo** [comment]
Danke, funktioniert schon teilweise.

Die **Abstracts** kommen noch nicht mit (Bsp.: https://correspondencesjournal.com/21303-2/)

Und wenn ein Beitrag keine "eigene Seite" hat, sondern nur einen Link zum PDF-Download wird keine URL importiert und eventuell erscheint auch eine Fehlermeldung beim Import. Das ist z. B. bei einem Heft mit einigen Rezensionen der Fall: https://correspondencesjournal.com/volume-9/issue-1/
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/65c706d0-a07e-41e2-8b8f-67e3bbaee67a)

Ein PDF-Link müsste auch anders exportiert werden: 
Bsp.: 4950 https://correspondencesjournal.com/ojs/ojs/index.php/home/article/download/125/124 _(hier eigentlich kein Leerzeichen, nur für GitHub)_ **$qapplication/pd**f$xH$4LF _(oder ZZ je nach Eintragung in der Mapping-Liste)_

**Comment by PaulaHaehndel** [comment]
Soweit ich das verstehe, ist das kein Link zu einer Volltextdatei, deswegen wird er vorläufig nicht mit exportiert, sondern gar kein Link.
Der Rest ist jetzt hoffentlich behoben.

**Comment by IxKo** [comment]
Danke, Abstract und Jahr werden nun importiert.
Bzgl. der PDF-Links habe ich eine Bemerkung in ZEDER b_zot gemacht.

Vielen Dank!

**Comment by PaulaHaehndel** [comment]
Danke.

**Comment by IxKo** [comment]
Behoben, danke!
