### ISSUE TITLE
ISSN 1814-2036 | Mitteilungen zur Christlichen Archäologie | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1895]
#### URL
http://[www.austriaca.at/micha_collection?frames=yes](http://www.austriaca.at/micha_collection?frames=yes)
  
#### Import-Translator
  Einzelimport:
Embedded Metadata.js

  
### Problembeschreibung
Kann für diese Webseite ein passender Translator entwickelt werden?

**Comment by socheres** [comment]
bitte diesen Link als Quelle in Zeder eintragen ohne "?frames=yes": https://www.austriaca.at/micha_collection

**Comment by socheres** [comment]
"Titelei", "INHALTSVERZEICHNIS" und "MITARBEITER/INNEN DIESES BANDES" werden bei der Artikelauswahl ausgeschlossen.

**Comment by IxKo** [comment]
Danke, doch die Titel sollen nicht ausgeschlossen werden laut https://github.com/ubtue/DatenProbleme/issues/1612#issuecomment-989742273, daher bitte nicht translator-seitig ausschließen

**Comment by socheres** [comment]
es werden nur Artikel mit DOIs zur Auswahl angeboten und aufgrund der uneinheitlichen HTML-Struktur ist es leider nicht möglich, die ausgeschlossenen Artikel mit anzuzeigen, da sonst auch beliebig viele Links auf der Seite angeboten würden, die nicht zum Artikel führen. Bitte vermerken Sie daher in ZEDER, dass Artikel ohne DOI nicht erfasst werden sollen.
