### ISSUE TITLE
ISSN 1748-0922 | Religious studies review (Wiley) | Interview als Rezension

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1898]
#### URL
 IxTheo#2023-01-30#CB00846033838997E1129ED273F9527EC1D19AEA
https://onlinelibrary.wiley.com/doi/full/10.1111/rsr.16200
  
 
### Problembeschreibung
Der Artikel bzw. das Interview wurde als Marc-655/Pica-1131 Rezension eingespielt, obwohl es keine ist.

Im halbautomatischen Verfahren mit dem Translator ubtue_Wiley Online Library.js wird der Titel nicht als Rezension gekennzeichnet.

**Comment by IxKo** [comment]
Auch weitere Artikel wurden als Rezensionen gekennzeichnet, obwohl sie keine sind.
Beispiel:
IxTheo#2023-01-30#DA168FCADD0FE94556EE70594661043A631C2B0C
https://doi.org/10.1111/rsr.16197

**Comment by jriedl** [comment]
Liegt wohl an: `zotero_review_regex       = .*`
in der Konfiguration der Zeitschrift in der `zotero_harvester.conf`.

**Comment by IxKo** [comment]
Das ist nicht so gut, denn nicht alle Artikel der ZS sind Rezensionen.

Ist es nicht möglich, die Rezensionen Translator-seitig zu kennzeichnen?

@socheres 
Die Review Essays (Bsp.: https://onlinelibrary.wiley.com/doi/10.1111/rsr.15882) wollten Sie nicht als Rezensionen gekennzeichnet haben, oder?
Möglicherweise sollten bei dieser ZS nur die Short Reviews als Rezensionen gekennzeichnet werden?

**Comment by jriedl** [comment]
Das weitere Vorgehen im Zusammenhang mit den Translators bei Zotaut sollte grundsätzlich besprochen werden.

**Comment by IxKo** [comment]
Behoben
