### ISSUE TITLE
ISSN 2521-179X Theological Reflections: Euro-Asian Journal of Theology Language Code

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#190]
Überwiegend wird ein nicht zulässiger Language Code übertragen. 
Z. B 
```
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">uk</subfield>
</datafield>
```
oder
```
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">ru</subfield>
</datafield>
```
bei anderen Aufsätzen wiederum der korrekte:
```
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">eng</subfield>
</datafield>
```

**Comment by shadeMe** [comment]
Das ist wegen falschen/nicht normalisierten Metadaten auf der Webseite. Normalerweise wird es automatisch von dem Harvester korrigiert, wenn es für 'uk' einen Eintrag in diese [Mapping](https://github.com/ubtue/zotero-enhancement-maps/blob/master/language_to_language_code.map) gibt, was momentan noch fehlt. Ich füge ihn dazu hin aber ich glaube, Chang-Whae wollte sowieso die Mapping aktualisieren.

**Comment by kdr154** [comment]
Gelöst
