### ISSUE TITLE
ISSN 0959-6410 | Islam and Christian–Muslim Relations (Taylor and Francis) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1902]
#### URL
https://doi.org/10.1080/09596410.2022.2143228
https://doi.org/10.1080/09596419008720928
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung
Die Rezensionen werden nicht mit dem PicaRezensionstag importiert.
Stattdessen wird zweimal 5520 |f|Book Review exportiert:

![image](https://user-images.githubusercontent.com/57000004/217545417-a3a4c191-5283-4309-9be7-0d986a3156f5.png)

**Comment by socheres** [comment]
wird picaseitig umgesetzt.

**Comment by IxKo** [comment]
Nun wird nur noch einmal "Book Review" importier, es sollte aber stattdessen "RezensionstagPica" importiert werden, damit es als 1131 Rezension in den K10plus exportiert werden kann.
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/d7cc2fea-8f7b-40f8-b570-6f6026a6b5d5)

**Comment by IxKo** [comment]
Ich persönlich finde es besser, wenn es dabei bleiben würde, dass nur ein definiertes Tag beim Export zu 1131 !Rezension! führen würde und nicht noch ein weiteres Tag eingeführt wird. Dies verkompliziert alles nur.
Die Katalogisierer:innen haben sich das RezensiosntagPica als Favorit in ihrer Zotero-Anwendung gespeichert. Dadurch erkennt man nach einem Import sofort, ob Einträge automatisch als Rezensionen schon getagt worden sind.
Würde man diesen Vorgang ändern, müssten alle in Kenntnis gesetzt werden und die Anleitung angepasst werden.

Zudem wird jetzt "Book Review" zusätzlich zu 1131 mit 5520 |f|Book Review exportiert, was nicht nötig ist.

**Comment by IxKo** [comment]
Gelöst, vielen Dank!
