### ISSUE TITLE
ISSN 1052-4533 | The studia Philonica annual (JSTOR) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1906]
#### URL
https://www.jstor.org/stable/j.ctv256d6br
  
#### Import-Translator
  Mehrfachimport:
ubtue_JSTOR.js
Aber kein Ordner-Symbol.
  
### Problembeschreibung
Könnte hier der Translator angepasst werden?
Im k10plus wird die Serie als Abv-Aufnahme geführt. Die Seite bietet einen Export in Zotero an, doch werden die Aufsätze dann als Buchkapitel gelistet, statt als Zeitschriftenartikel

_Anfrage Kooperationspartner_

**Comment by IxKo** [comment]
Dass ein Export angeboten wird, erwähnte ich bereits eingangs.
Dass dieser Export die Aufsätze als Buchteile in Zotero importiert anstatt als Zs.-Artikel erwähnte ich auch.

Die Ausgangsproblematik besteht also weiterhin und es hat sich nichts geändert.

**Comment by socheres** [comment]
Die Multi-Erkennung mit Connector, da die DOIs für einzelne Buchkapiteln keine echten DOIs sind.  Z.B. führen die DOIs mit dem Suffix "..br.1", "..br.2" führen zurück zum Buch. Bitte laden Sie die Beiträge über Export-Funktion wie oben im Screenshot nach Zotero. Pica3-Translator wurde für den Datentyp "Buchkapitel" angepasst und kann analog zu den Aufsätzen verwendet werden.

**Comment by socheres** [comment]
> Es wäre nützlich gewesen, mir die Information mitzuteilen, dass die ISSN der Zs. in das Feld "ISBN" manuell überall eingetragen werden muss.

ISBN muss nicht manuell eingetragen werden, sie sind in RIS enthalten und kommen automatisch mit.

```
TY  - CHAP
TI  - Front Matter
A2  - Runia, David T.
A2  - Sterling, Gregory E.
DB  - JSTOR
DO  - 10.2307/j.ctv256d6br.1
EP  - iv
PB  - The Society of Biblical Literature
PY  - 2021
SN  - 9780884145516
SP  - i
T2  - The Studia Philonica Annual XXXIII, 2021
T3  - Studies in Hellenistic Judaism
UR  - http://www.jstor.org/stable/j.ctv256d6br.1
Y2  - 2023/11/29/
ER  - 
```

> Dennoch ist das Ergebnis nicht zufriedenstellend: Feld 2000 (ISBN) wird exportiert, was nicht in einen unselbständigen Datensatz gehört. Der DOI wird nicht exportiert.

Pica3-Translator angepasst:Feld 2000 wird nicht mehr exportiert.
DOI nicht, aber die stable-URL von JSTOR kommen mit. Diese ist ausreichend und daher geeignet für zotkat.

> Die Daten der Export-Funktion seitens JSTOR sind jedoch auch nicht vollständig, und da kein Import-Translator erstellt werden kann, schließe ich.

Welche Datenfelder fehlen?

**Comment by IxKo** [comment]
> > Es wäre nützlich gewesen, mir die Information mitzuteilen, dass die ISSN der Zs. in das Feld "ISBN" manuell überall eingetragen werden muss.
> 
> ISBN muss nicht manuell eingetragen werden, sie sind in RIS enthalten und kommen automatisch mit.

Es muss jedoch die ISSN der Zs. eingetragen werden. Eine ISBN nützt nichts, da sie sich beim nächsten Band wieder ändert.

> ```
> TY  - CHAP
> TI  - Front Matter
> A2  - Runia, David T.
> A2  - Sterling, Gregory E.
> DB  - JSTOR
> DO  - 10.2307/j.ctv256d6br.1
> EP  - iv
> PB  - The Society of Biblical Literature
> PY  - 2021
> SN  - 9780884145516
> SP  - i
> T2  - The Studia Philonica Annual XXXIII, 2021
> T3  - Studies in Hellenistic Judaism
> UR  - http://www.jstor.org/stable/j.ctv256d6br.1
> Y2  - 2023/11/29/
> ER  - 
> ```
> 
> > Dennoch ist das Ergebnis nicht zufriedenstellend: Feld 2000 (ISBN) wird exportiert, was nicht in einen unselbständigen Datensatz gehört. Der DOI wird nicht exportiert.
> 
> Pica3-Translator angepasst:Feld 2000 wird nicht mehr exportiert. DOI nicht, aber die stable-URL von JSTOR kommen mit. Diese ist ausreichend und daher geeignet für zotkat.
> 

Das ISBN-Feld wird bei mir immer noch als Pica-Feld 2000 exportiert.
Wenn ein DOI in den Zitationsdaten angegeben wird, sollte er auch miterfasst werden.

> > Die Daten der Export-Funktion seitens JSTOR sind jedoch auch nicht vollständig, und da kein Import-Translator erstellt werden kann, schließe ich.
> 
> Welche Datenfelder fehlen?

Die Bandangabe fehlt.
Zudem fehlen die Zusatztitel.

Da kein Import-Translator möglich ist, ist es in meinen Augen nicht Zotero-geeignet.

**Comment by socheres** [comment]
> Es muss jedoch die ISSN der Zs. eingetragen werden. Eine ISBN nützt nichts, da sie sich beim nächsten Band wieder ändert.

D.h. die einzelnen Beiträge sollen nicht an dem Band, sondenr an der Gesamtaufnahme der Zss.-Serie angehängt werden, richtig? Im Zoterofeld "Reihe" steht "Studies in Hellenistic Judaism". Könnte man nicht über "journal_title_to_ppn.map" die Verknüfpung zum ÜW herstellen?

> Das ISBN-Feld wird bei mir immer noch als Pica-Feld 2000 exportiert. Wenn ein DOI in den Zitationsdaten angegeben wird, sollte er auch miterfasst werden. (Tut in diesem Fall aber nichts zur Sache, da an die A-Aufnahme katalogisiert werden würde.)

Ich war zu schnell. Die lokalen Translators sind nun aktualisiert. Warum erfassen wir diese Beiträge als A-Aufnahme? Die Vorlage ist doch Online.

> Die Bandangabe fehlt. Zudem fehlen die Zusatztitel.

Es müssen nur die fehlenden Felder manuell in Zotero erfasst werden. Besser als alles manuell zu erfassen.

> Da kein Import-Translator möglich ist, ist es in meinen Augen nicht Zotero-geeignet.

Das verstehe ich nicht ganz, da die Daten ohne großen Aufwand in Zotero geladen werden können.

**Comment by IxKo** [comment]
> > Es muss jedoch die ISSN der Zs. eingetragen werden. Eine ISBN nützt nichts, da sie sich beim nächsten Band wieder ändert.
> 
> D.h. die einzelnen Beiträge sollen nicht an dem Band, sondenr an der Gesamtaufnahme der Zss.-Serie angehängt werden, richtig? Im Zoterofeld "Reihe" steht "Studies in Hellenistic Judaism". Könnte man nicht über "journal_title_to_ppn.map" die Verknüfpung zum ÜW herstellen?
> 

Ja, es soll an die Zs.-Gesamtaufnahme katalogisiert werden.
Ja, man könnte über journal_title_to_ppn.map eine Verknüpfung zum übergeordneten Werk machen. Es müssen aber auch noch andere Informationen über die Mapping-Listen hergestellt werden als nur das.

> > Das ISBN-Feld wird bei mir immer noch als Pica-Feld 2000 exportiert. Wenn ein DOI in den Zitationsdaten angegeben wird, sollte er auch miterfasst werden. (Tut in diesem Fall aber nichts zur Sache, da an die A-Aufnahme katalogisiert werden würde.)
> 
> Ich war zu schnell. Die lokalen Translators sind nun aktualisiert. Warum erfassen wir diese Beiträge als A-Aufnahme? Die Vorlage ist doch Online.
> 
Feld 2000 wird nicht mehr exportiert.

Es gibt unterschiedliche Gründe, warum wir etwas als A-Aufnahme erfassen. In diesem Fall gibt es nur eine A-Aufnahme der Zs.

> > Die Bandangabe fehlt. Zudem fehlen die Zusatztitel.
> 
> Es müssen nur die fehlenden Felder manuell in Zotero erfasst werden. Besser als alles manuell zu erfassen.
> 

Das Fehlen von Zusatztiteln kann bei Zotero schnell übersehen werden und dann fehlen sie im Katalogisat. Bei einer manuellen Katalogisierung würde das wahrscheinlich eher nicht passieren.

> > Da kein Import-Translator möglich ist, ist es in meinen Augen nicht Zotero-geeignet.
> 
> Das verstehe ich nicht ganz, da die Daten ohne großen Aufwand in Zotero geladen werden können.
