### ISSUE TITLE
zota Einspielung 16.12.2022 nicht im K10plus

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1907]
#### Hash Beispiel
IxTheo#2022-12-16#513EDF4241844BF450E87EC4428D9E55C99B2A2D
  
### Problembeschreibung
Die Daten von "ixtheo_zotero_221216_001.xml" scheinen nicht eingespielt, bzw. irgendwie auf seitens des BSZ Verschütt gegangen zu sein. Denn ich finde sie nicht mit der Hash-Suche ENR

Im Zotero Harvester sind sie grün hinterlegt, sie finden sich jedoch nicht im K10plus.

**Comment by jriedl** [comment]
Die Datei findet im loaded-Verzeichnis auf dem BSZ-FTP-Server, von unserer Seite scheint also alles wie geplant gelaufen sein. Ebenso die Krimdok-Datei von diesem Datum. Bei dieser ist seltsam, dass z.B. https://krimdok.uni-tuebingen.de/Record/1820372898#details erstmalig im November eingespielt wurde, aber wie man in LOK-035 sieht, es aber offenbar mehrfache weitere Uploads gegeben hat und auch aktuell steht dieser Artikel zusammen mit vielen anderen der Zeitschrift auf ub28 auf "manually reset". Bzgl. IxTheo: Anfrage ans BSZ läuft.

**Comment by IxKo** [comment]
Datensätze IxTheo#2021-12-16#... (Summe 63) wurden vom BSZ neu eingespielt.
