### ISSUE TITLE
ISSN 2156-7689 | Politics, Religion and Ideology (T&F) | falsche ISSN

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1910]
#### URL
https://www.tandfonline.com/doi/abs/10.1080/14690760008406926
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung
es wird eine falsche ISSN (1469-0764) nach Zotero importiert. Diese gehört zur Vorgänger-Zeitschrift "Totalitarian movements and political religions".

**Comment by socheres** [comment]
Der Artikel von oben ist aus dem Heft 1. 2010, daher schon richtig. Hier die Vorgänger-Zss. ab 2000-2010 https://zdb-katalog.de/title.xhtml?idn=024076546&view=full und Nachfolger-Zss. ab 2011 https://zdb-katalog.de/list.xhtml?t=2156-7689&key=iss&asc=false
