### ISSUE TITLE
zota Einspielung 22.03.2023 nicht im K10plus

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1913]
#### Beispiel-Hash
IxTheo#2023-02-22#199A6F545291D135AD11E8E3C385EA1CF10D8463
  
### Problembeschreibung
Wahrscheinlich aufgrund des CBS-Ausfalls: Die MARCXML-Datei wurde nicht eingespielt.

**Comment by jriedl** [comment]
Für diesen Tag ja, die Datei wurde von uns nochgeladen. Für die folgenden Tage gab es ein Problem mit dem Zugriff auf das Produktivverzeichnis auf dem Netzlaufwerk, so dass kein Upload erfolgt ist, das Problem wird hoffentlich heute behoben.

**Comment by IxKo** [comment]
Die 7 Daten aus der Datei vom 22.2. sind eingespielt.
