### ISSUE TITLE
ISSN 2056-5666 | Christianity & literature (Muse) | fehlender Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1915]
#### URL
https://muse.jhu.edu/pub/1/article/873930
  
### Problembeschreibung
Dieser Artikel wurde nicht eingespielt.
Er taucht auch nicht auf der Oberfläche des Zotero Harvester auf.
Im aktuellen RSS-Feed wird er nicht gelistet, was vermutlich die Ursache ist.

**Comment by IxKo** [comment]
Im nun neuen Heft ebenfalls: https://muse.jhu.edu/pub/1/article/910037

**Comment by jriedl** [comment]
Falls wir an RSS festhalten wollen, ist wohl eine Lösung ohne Korrektur auf Verlagsseite nicht möglich.

**Comment by IxKo** [comment]
@socheres Sollte die Zs. dann aus dem zota-Verfahren genommen werden?

**Comment by socheres** [comment]
@IxKo Bitte keine Artikel nacherfassen, die im RSS-Feed fehlen. Inhaltlich sind sie auch nicht so wichtig.

**Comment by IxKo** [comment]
Ob es inhaltlich relevant ist, kann ich nicht entscheiden.
Diese Entscheidung widerspricht jedoch https://github.com/ubtue/DatenProbleme/issues/1612#issuecomment-989742273, dass alles erfasst werden soll, was nicht "Front Matter" oder "Back Matter" heißt.
Eine konsequenteres Vorgehen wäre wünschenswert, statt mit Ausnahmen bei einzelnen Zs. anzufangen.

**Comment by socheres** [comment]
Die Entscheidung in beiden Fällen ist pragmatischer Natur, d.h. wir wollen ebene keine weiteren Kriterien aufstellen, die das automatische Verfahren erschweren.

**Comment by IxKo** [comment]
@socheres Beim aktuellen Heft 74.2025,1 fehlen 16 Art.

1. https://doi.org/10.1353/chy.2025.a960717
2. https://doi.org/10.1353/chy.2025.a960718
3. https://doi.org/10.1353/chy.2025.a960720
4. https://doi.org/10.1353/chy.2025.a960721
5. https://doi.org/10.1353/chy.2025.a960723
6. https://doi.org/10.1353/chy.2025.a960724
7. https://doi.org/10.1353/chy.2025.a960726
8. https://doi.org/10.1353/chy.2025.a960728
9. https://doi.org/10.1353/chy.2025.a960729
10. https://doi.org/10.1353/chy.2025.a960732
11. https://doi.org/10.1353/chy.2025.a960733
12. https://doi.org/10.1353/chy.2025.a960734
13. https://doi.org/10.1353/chy.2025.a960735
14. https://doi.org/10.1353/chy.2025.a960736
15. https://doi.org/10.1353/chy.2025.a960737
16. https://doi.org/10.1353/chy.2025.a960738

Sind die auch alle nicht relevant?
Dazwischen sind gleiche Einträge, die eingespielt worden sind wie bspw. https://doi.org/10.1353/chy.2025.a960731
