### ISSUE TITLE
ISSN 2077-1444 | Religions | Person wird zu zwei

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1916]
#### URL
1DCCAFE96B9679F689F2026FBECFDF2991A114D7
https://doi.org/10.3390/rel14030311
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_MDPI Journals.js

  
### Problembeschreibung
Der Datensatz wurde zurecht nicht eingespielt, da er die Person zu zwei Personen gemacht hat und dabei die vermeintlich zweite Person aus einem Nachnamen mit einem Buchstaben bestand:

> Record IxTheo#2023-02-27#1DCCAFE96B9679F689F2026FBECFDF2991A114D7 is invalid:
700: contents of subfield $a(R, Karel) did not match regex "^(?!(?:(\s*(?:,\s*)?)|(\s*,\s*?\S+)|(\S(\.?)\s*,\s*\S+)|(.*,\s*[\p{P}-]\S+))$)"

Auch im halbautomatischen Verfahren macht er zwei draus:
![image](https://user-images.githubusercontent.com/57000004/221912054-0e02addb-5118-4487-81da-1375a9ab8a38.png)

**Comment by IxKo** [comment]
Ein weiterer Fall: IxTheo#2023-09-21#9955FABEA3700D5B380FFA76222F5C7BF0BFDF7C
aus der Person "Renate Marian van Dijk-Coombes" wurden 2:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/40f2693e-15d0-4de0-9f3d-0054c38d9573)

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
Auf ub28. Hinweis für die Rückportierunng im halbautomatischen Verfahren: vgl. https://github.com/ubtue/zotero-translators/pull/262/files

**Comment by mara-spiess** [comment]
Sollte nun auch im halbautomatisch Verfahren funktionieren.
