### ISSUE TITLE
ISSN 2224-7963 | The journal of the European Pentecostal Theological Association | RSS

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1919]
#### URL
https://www.tandfonline.com/loi/yjpe20

RSS:
https://www.tandfonline.com/feed/rss/yjpe21

  
### Problembeschreibung
Der RSS aktualisiert nicht (Stand Volume 41, 2021 - [Issue 2]), weswegen auch die letzten beiden Hefte (Volume 42)  nicht eingespielt worden sind.

**Comment by jriedl** [comment]
Offenbar muss der Feed in Zeder auf den oben angegebenen angepasst werden - in `zotero_harvester.conf` steht aktuell noch https://www.tandfonline.com/feed/rss/yjpe20.

**Comment by IxKo** [comment]
Ich habe den Feed in ZEDER nun eingetragen.

**Comment by IxKo** [comment]
Mit dem neuen RSS hat es geklappt.
Allerdings handelt es sich beim neuen RSS um eine Nachfolger-ZS. Ich bitte um das Anlegen einer neuen ZEDER-Zeile und trage dort den neuen RSS ein. Bei der "alten" ZS habe ich prodf=? gesetzt damit sie aus dem zota-Verfahren ist.
