### ISSUE TITLE
ISSN 0254-4407 Zwingliana Language Code

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#192]
Sprache des Titels und des Language Code differieren:
Der Titel kommt in verschiedenen Sprachen vor (ger, eng), der Language Code ist aber immer "eng".

**Comment by shadeMe** [comment]
Laut Zeder müssen alle Artikel im Deutschen sein oder? Dann können wir unbeschränkt die Sprache auf "ger" setzen.

**Comment by kdr154** [comment]
Bei dieser Zeitschrift gibt es mehrere Probleme. Die mit den Book Reviews gliedere ich aus und öffne ein eigenes Issue.
Manchmal ist das Problem mit dem Language Code schlicht nicht zu lösen.
In diesem Fall: http://www.zwingliana.ch/index.php/zwa/article/view/2493
ist der Titel überwiegend Latein, da es sich um den Titel eines auf Latein geschriebenen Werks handelt. Der Aufsatz möglicherweise auf Deutsch, man weiß es ohne Vorlage nicht, in 041 getagt als Englisch.
An anderer Stelle ist er einfach falsch:
http://www.zwingliana.ch/index.php/zwa/article/view/2500
in 041 ebenfalls als Englisch getagt, obwohl der Titel klar als Deutsch erkennbar sein sollte.
Ebenso hier: http://www.zwingliana.ch/index.php/zwa/article/view/2488

**Comment by shadeMe** [comment]
Was die Sprache angeht, gibt es zurzeit leider keine alternative Lösung, die besser als unsere jetzige Heuristik funktioniert.

**Comment by thefass** [comment]
@kdr154 bitte in Zeder vermerken, dass die Spracher händisch geprüft/korrigiert werden muss

**Comment by shadeMe** [comment]
Können wir dieses Issue dann schließen?

**Comment by kdr154** [comment]
Machen wir
