### ISSUE TITLE
ISSN 2332-886X | Criminology, Criminal Justice, Law & Society (Scholastica) | Neuer Translator

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#1927]
#### URL
https://ccjls.scholasticahq.com/issue/3769
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

### Problembeschreibung
Könnte für diese Website ein neuer Translator angelegt werden?

**Comment by kyushutea** [comment]
Probleme behoben, danke
