### ISSUE TITLE
ISSN 1553-0604 | Jewish Quarterly Review (MUSE) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1928]
#### URL
OA:
https://muse.jhu.edu/pub/56/article/861820
IxTheo#2022-08-09#95BE469357D60285645C23F82C01A90F7CBD33D9

FREE:
https://muse.jhu.edu/pub/56/article/871328
IxTheo#2022-11-30#C5742F0C74844134A96F2ACBC7A767F56F370962

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Project MUSE.js

  
### Problembeschreibung
Die beiden Artikel werden im zota- und zotk-Verfahren nicht als lizenzfrei erkannt.
Sie müssten in Pica-4950 $4 bzw. MARC-856 $z entsprechend so gekennzeichnet werden.

**Comment by jriedl** [comment]
Auf nu findet sich nun eine Version, die in den Artikelangaben als "Open Access" | Yes gekennzeichnete Beiträge als LF tagged. Woraus folgt Free Access im zweiten Fall, wenn OA explizit als No angegeben wird? Handelt es sich hier um freie Zugänglichkeit nach Embargo?

**Comment by IxKo** [comment]
Wie es auf nu ist, ist es korrekt (OA: yes -> LF). BItte auch auf ub28

Die als "free" gekennzeichneten Artikel sind wohl nur für eine gewisse Zeit zugänglich, daher ist es korrekt wenn sie ZZ für lizenzpflichtig erhalten.

**Comment by jriedl** [comment]
ub28 ist nun auf dem aktuellen Stand.

**Comment by IxKo** [comment]
nu und ub28 scheinen sich nicht gleich zu verhalten:
Auf nu wird der OA-Artikel als LF gekennzeichnet, aber auf ub28 beim Testen noch nicht.

**Comment by jriedl** [comment]
> Laut den Server Logs beginnt nu mit dem Translator RIS und ub28 mit ubtue_Springer
> (Getestet mit TRY URL)

Das ist vermutlich jeweils von früheren Tests - entscheidend sind ja die jeweils letzten Einträge in der Logdatei. Beide starten mit einem MUSE-spezifischen Translator, allerdings wird dieser auf ub28 offenbar aufgrund von eines Timeouts beim Aufruf eines Untertranslators abgebrochen  - mit dem zweiten aufgerufenen Translator ist der Aufruf dann erfolgreich. Das lässt sich z.T. auch bei einem manuellen Download der Seite beobachten und leider spricht aktuell nichts dafür, dass es an Faktoren liegt, die wir auf unserer Seite beeinflussen können. Bisher wurde es auch nur im Zusammenhang mit MUSE und ub28 beobachtet. Als Workaround werden aufgrund des nun vereinheitlichten Handlings von ubtue_Project Muse und Project Muse LF und DOI auf beiden Systemen generiert.

**Comment by IxKo** [comment]
Bei einem erneuten Test wird der Artikel auf ub28 nun als LF gekennzeichnet.
