### ISSUE TITLE
ISSN 0004-0665 Archivum Franciscanum Historicum Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#193]
Falsche Daten in Feld Zusammenfassung beim halbautomatischen Verfahren. 
Bei folgendem Aufsatz: https://dialnet.unirioja.es/servlet/articulo?codigo=6801377
steht folgendes im Feld Zusammenfassung von Zotero:
Autoría: François Delmas-Goyon.
Localización: Archivum Franciscanum Historicum. Nº. 3, 2018.
Artículo de Revista en Dialnet.
Abgesehen davon, dass es inhaltlich falsch ist, kann das Verfahren nicht mit Zeilenumbrüche in umgehen, was bedeutet, dass es entweder zum Abbruch kommt, oder dass man die Daten manuell nachbearbeiten muss.
Das ist im Übrigen die zweite Zeitschrift auf Dialnet heute, bei der die Daten so aussehen.

**Comment by shadeMe** [comment]
Hmm, das auch kann ich nicht reproduzieren. Gibt es andere Beispiele?
![screenshot_20190215_145336](https://user-images.githubusercontent.com/214450/52861044-85d50700-3131-11e9-9205-80b07b706bc8.png)

**Comment by shadeMe** [comment]
Wie sieht es bei dieser Webseite jetzt aus?

**Comment by kdr154** [comment]
Jetzt ist es ok.
