### ISSUE TITLE
ISSN 0963-7494 | Religion, state & society (Wiley) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1937]
#### URL
https://doi.org/10.1080/09637494.2023.2180240
IxTheo#2023-03-24#9290BF247D8896020BED7CD84E1B8C6B5D141282

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js
  
### Problembeschreibung
Es handelt sich um einen OA-Artikel, daher sollte er in Marc-856 als LF gekennzeichnet werden.

Im halbautomatischen Verfahren wird er als LF gekennzeichnet, doch in der zota-Einspielung wurde er es nicht.

**Comment by jriedl** [comment]
Der `ubtue_Taylor and Francis+NEJM.js` stammt aus `zotkat-translators` und hat bislang innerhalb des Zotaut-Repositories nicht existiert. Einziger Unterschied zu Taylor and Francis+NEJM.js in `zotero-translators` (dem Zotaut-Translator-Repository) ist die im Dezember 2022 eingefügte Änderung mit der LF-Erkennung. `ubtue_Taylor and Francis+NEJM.js` wurde nun nach zotero-translators übernommen und der aktuelle Stand ist auf nu und ub28.

**Comment by IxKo** [comment]
Danke, wird auf ub28 nun als LF gekennzeichnet:
![image](https://user-images.githubusercontent.com/57000004/228264603-f1de1efd-b029-4997-960e-7b313abd551e.png)

**Comment by IxKo** [comment]
Ich prüfe alle zota-Wiley-Einspielungen und korrigiere manuell zu LF.
Dabei fiel mir auf, dass die LF-Erkennung bei OA-Artikeln in der Vergangenheit (vor über einem Jahr) funktioniert hatte.
Datensatz vom Januar 2022: IxTheo#2022-01-12#1AA6C3230EFDE603D68433298AA13038A4F3AFA3

Ich frage mich, wieso es irgendwann die OA-Artikel nicht mehr erkannt hat.
Kann das nachvollzogen werden, um eventuell in Zukunft solche "Aussetzer" früher zu erkenne?

**Comment by jriedl** [comment]
Es gab ja vorher bereits ein Kriterium für die Kennzeichung als OA, aber das hat dann eben offenbar nicht mehr gegriffen. Das ist ein konzeptionelles Problem des Scrapings von Webseiten (so man nicht ausschließlich auf standardisiert in der Seite hinterlegte Metadaten zurückgreifen kann). Wenn sich der strukturelle Aufbau der Seite ändert, weil bestimmte Informationen jetzt anders repräsentiert werden, kommt es zu Fehlern.

**Comment by IxKo** [comment]
Ok, vielen Dank für die Antwort.
