### ISSUE TITLE
ISSN 2044-2696 | Theology (SAGE) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1938]
#### URL
https://doi.org/10.1177/0040571X231160499
IxTheo#2023-03-17#A782838236C333A61E80DD11792D7756BEA186D2
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SAGE Journals.js

  
### Problembeschreibung
Der Artikel ist frei verfügbar und sollte daher als LF gekennzeichnet werden.
Er wurde jedoch nicht als LF eingespielt und auch im halbautomatischen Verfahren wird er nicht als LF gekennzeichnet.

**Comment by jriedl** [comment]
Anpassung innerhalb des Zotaut-Repo. Aktueller Stand auf nu.

**Comment by IxKo** [comment]
Wird auf nu als LF gekennzeichnet:
![image](https://user-images.githubusercontent.com/57000004/228259558-9fe10125-f857-43ec-be72-d8b96f14f7d9.png)

Bitte noch für ub28 umsetzen.

**Comment by jriedl** [comment]
Das Kriterium in diesen Fall ist aktuell das Vorhandensein des grünen geöffneten Schlosses. Im Gegensatz zu anderen Kriterien ím SAGE-Kontext, die auf alternativen Text zurückgreifen können, der ausdrücklich "Open Access" o.ä. erwähnt, ist hier noch die Frage offen, ob das wirklich in allen Fällen OA bedeutet oder, da das Schloss jetzt bei Stichprobem bei auffällig vielen Artikeln von SAGE vorhanden ist, hier z.B. das in infolge einer IP-Freischaltung erfolgt. @IxKo: Existiert eventuell noch ein ein weiteres, sichereres Kriterium?

**Comment by IxKo** [comment]
Das Kriterium des grünen Schlosses würde wohl alle Artikel als LF erfassen?

**Comment by jriedl** [comment]
Vielen Dank.
> Leider wird der "Free Access"-Artikel beim Zugriff über die IP der UB-Tü nicht mehr ersichtlich als "free" bezeichnet und es steht einfach "Available Access" dran als wäre der Artikel gekauft:

Das könnte kompliziert werden, da evtl. Freischaltungen an eine Tübinger IP gebunden sind und wir auch nicht so einfach eine "externe" IP nutzen können.

**Comment by jriedl** [comment]
Unter der Voraussetzung, dass damit nicht andere relevante Informationen verloren gehen, scheint mir ein explizites Blacklisting von nu und ub28 für die Volltextzugriffsfunktionalität durch SAGE aktuell der sinnvollste Weg.

**Comment by socheres** [comment]
Hier würde ich nur "Open Access" als LF kennzeichnen. Alles andere "Free Access|Avaiable Access" ohne LF.

**Comment by IxKo** [comment]
Bei Taylor und Francis gibt es das gleiche Problem, dass es explizit OA-Artikel gibt und freie Artikel:
https://www.tandfonline.com/toc/cjbv20/42/3?nav=tocList
Ohne UB-VPN:
![image](https://user-images.githubusercontent.com/57000004/228844027-f03b6a42-0085-4404-80ba-2d1689d6a5a8.png)

Mit UB-VPN:
![image](https://user-images.githubusercontent.com/57000004/228844507-c57afb0f-1550-4fe7-97ac-484c87edbbe4.png)

**Comment by socheres** [comment]
Nach telefonischer Rücksprache mit @jriedl: OA-Artikel werden weiterhin als "LF" gekennzeichnet. Dahingegen Artikel mit "Free Access" sollen nicht gesondert als "LF" gekennzeichnet werden, da die Unterscheidung "Free Access" und "Avaiable Access" nur IP-basiert möglich ist und für uns keinen Mehrwert darstellt.

**Comment by IxKo** [comment]
Da technisch nicht einfach umsetzbar, können und werden die Free Access-Artikel weiterhin nicht als LF gekennzeichnet.
Solche Artikel könnten nur manuell erkannt und bearbeitet werden.

**Comment by IxKo** [comment]
("Fürs Protokoll")
Bei Brill gibt es ebenfalls freie Artikel (https://brill.com/view/journals/jet/35/2/jet.35.issue-2.xml). In diesem Heft sind die letzten beiden Artikel frei zugänglich:
![image](https://user-images.githubusercontent.com/57000004/233076933-c3f20a54-0cb2-4591-95e2-18dc2e98d06f.png)

**Comment by IxKo** [comment]
Und hier ist sogar ein ganzes Heft bei Brill mit uneingeschränkten Zugang, was jedoch als $4ZZ eingespielt wurde:
https://brill.com/view/journals/rrj/26/1/rrj.26.issue-1.xml

**Comment by IxKo** [comment]
Auch bei Wiley hat es ein ganzes Heft, welches als "Free Access" auf der Seite gekennzeichnet ist, und wir als $4ZZ einspielen.

**Comment by jriedl** [comment]
Wäre der ursprünglich angedachte Ansatz mit den "nichtprivilegierten" IPs dann noch einmal zu überlegen?

**Comment by IxKo** [comment]
Ich protokolliere nur einige Fälle.
Die Entscheidung fiel bereits.

**Comment by socheres** [comment]
Bei Brill kann man doch die "Free Access"-Artikel unabhängig vom IP-Zugang(z.B. UB-IP) von den kostenpflichtigen Artikeln - ebenfalls "Free Access" da der Zugang durch UB  erworben wurde - unterscheiden. Habe daher den Translator angepasst.

>"pf:selectedLanguage" : "German",
  "pf:sitegenUUid" : "1322817920249626639",
  "pf:accountNumber" : "3894",
  "pf:contentCategory" : "nlm-article",
  "pf:associatedContentSets" : "BR,all,1570-9256,journals-TRIAL-REL-2000-2023,ifp:all,JET,jet,free-public,0922-2936",
  "pf:authorized" : "authorized",
  "pf:contentName" : "Developing a Research Tool for Investigating Religious Knowledge as Part of Religious Literacy: The Questionnaire \u2013 First Results \u2013 Possibilities for International Comparisons",
  "pf:titleParentIdentifier" : "0922-2936",
  "pf:authenticationStatus" : "logged-in",
  "pf:chunkIdentifier" : "10.1163/15709256-20231146",
  "pf:contentParentName" : "Journal of Empirical Theology",
  "pf:authAccountNumber" : "3894"
>
>
