### ISSUE TITLE
ISSN 2504-5156 | Vulgata in Dialogue (OJS-Tue) | fehlende Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1939]
#### URL
https://vulgata-dialog.ch/ojs/index.php/vidbor/issue/view/89
 
### Problembeschreibung
Von Band 6 wurden nur 2 Artikel eingespielt. Die restlichen scheinen nicht auf ub28 zu sein.

Ich katalogisiere sie nun nach.

**Comment by IxKo** [comment]
Vom Special Issue (https://vulgata-dialog.ch/ojs/index.php/vidbor/issue/view/90) finden sich momentan auch nur 2 Artikel auf ub28 als OF

**Comment by jriedl** [comment]
Im verwendeten Feed (https://vulgata-dialog.ch/ojs/index.php/vidbor/gateway/plugin/WebFeedGatewayPlugin/rss) finden sich offenbar aktuell nur die zwei OF-Links.

**Comment by jriedl** [comment]
Da scheinen IDs/DOIs für die deutsche und englische Version doppelt vergeben worden zu sein:
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/003e25e5-265a-4ac1-b329-afd58e26edfd)
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/854915ef-ddf7-402e-9df1-46ae0c5bec3c)

**Comment by jriedl** [comment]
Rückmeldung durch P&E liegt vor: DOI-Vergabe offenbar korrekt, da jeweils nur eine englische Version des Artikeltextes vorhanden.

**Comment by IxKo** [comment]
Danke, ich habe es mir eben auch angeschaut.
Je nachdem welche Sprache man oben rechts für die Website wählt, wird der Original-Titel oder der übersetzte Titel angezeigt.

Das hatte ich übersehen als ich die Einspielungen anhand des Titels mit der Heft-Seite abgeglichen hatte.

Danke für die Klärung!
