### ISSUE TITLE
ISSN 1783-1806 Studies in Interreligious Dialogue ISSN fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#194]
Bei folgender ZS kommt im halbautomatischen Verfahren keine ISSN mit:
http://poj.peeters-leuven.be/content.php?url=journal&journal_code=SID

**Comment by shadeMe** [comment]
Es scheint, dass die ISSN in den Metadaten nicht vorhanden ist, auf die der Translator zugreift.

**Comment by kdr154** [comment]
Das ist bei Peeters oft, möglicherweise immer der Fall. ISSNs sind nur auf der Homepage oder Eingangsseite  der jeweiligen Zeitschrift zu finden. Da das Pica-Skript in diesen Fällen limitiert ist, muss man einige Informationen, Sprache (sofern nicht Englisch), Lizenz bei kostenlosen, manuell nachtragen muss.

**Comment by shadeMe** [comment]
Ja, das kann man leider nicht auf der Ebene des Translators lösen. Somit kann dieses Issue nun geschlossen werden.

**Comment by kdr154** [comment]
ok
