### ISSUE TITLE
ISSN 1741-2005 | New blackfriars (Cambridge) | Verfasser Initial

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1946]
#### URL
IxTheo#2023-04-19#5DAE582254BA10ADB6949E512672111A4BDA271C
https://doi.org/10.1111/nbfr.12831
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js

  
### Problembeschreibung
Das Initial "S." des zweiten Vornamens wurde zum Bestandteil des Nachnamens.

Auch im halbautomatischen Verfahren wird es falsch importiert.

![image](https://user-images.githubusercontent.com/57000004/233939032-d2a0c4e8-94f7-40ab-a3e4-6faf90213bb6.png)

**Comment by mara-spiess** [comment]
Ist hier vielleicht der falsche Link reingerutscht? Auf der angegebenen Seite finde ich den Verfasser nicht und es wird ein anderer Translator (ubtue_Cambridge Core) vorgeschlagen.

**Comment by IxKo** [comment]
> Ist hier vielleicht der falsche Link reingerutscht? Auf der angegebenen Seite finde ich den Verfasser nicht und es wird ein anderer Translator (ubtue_Cambridge Core) vorgeschlagen.

Tatsächlich, Wiley stimmte nicht, korrekte/r Plattform/Translator ist Cambridge.
Das Problem mit dem Initial scheint aber mittlerweile behoben.
