### ISSUE TITLE
ISSN 2748-6419 | AABNER Advances in ancient, biblical, and Near Eastern research (OJS) | Zusatztitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1948]
#### URL
https://aabner.org/ojs/index.php/beabs/article/view/877
IxTheo#2023-04-01#BF43D918EA3BB38FCCE6B97653B9944CFA45F44A
  
### Problembeschreibung

Der Zusatztitel "Examining Significance of Sarah’s Beauty in The Genesis Apocryphon 20:2-9" wurde nicht eingespielt.

**Comment by jriedl** [comment]
Die Metadaten auf der Website enthalten den Untertitel nicht, so dass die Frage ist, was wir als verbindlichen Titel annehmen.
![image](https://user-images.githubusercontent.com/13135579/236226795-1e0fd860-69e8-403b-a682-5e6f6d9630d3.png)
Da dieser Fall in der Vergangenheit bereits in anderem Kontext aufgetreten ist, habe ich die zugehörige ISSN jetzt ebenfalls für diese Speziallogik hinzugefügt. Auf nu.

**Comment by IxKo** [comment]
Im halbautomatischen Verfahren kommt der Untertitel mit, wenn ich mit dem ubtue_Open Journal Systems Standard-Translator importiere.

**Comment by IxKo** [comment]
Bei einem Test auf Nu kommt der Zusatztitel nun mit. Bitte auch auf ub28

**Comment by jriedl** [comment]
Aktueller Stand auf ub28.

**Comment by IxKo** [comment]
Danke!
