### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion (Oxford Academic) | OA nicht gekennzeichnet

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1949]
#### URL
https://doi.org/10.1093/socrel/srac021
IxTheo#2023-04-28#794A67064B9EB9DAC2842E0D0ED5A073ADE9110B
  
### Problembeschreibung

Der Artikel ist Open Access, wurde aber nicht als solcher (LF) eingespielt, sondern mit $4ZZ für lizenzpflichtig.

**Comment by jriedl** [comment]
Aktuell weder lokal noch auf ub28 reproduzierbar:
![image](https://user-images.githubusercontent.com/13135579/236220073-4723ac37-5852-445e-a89a-068923e027fc.png)

**Comment by IxKo** [comment]
Könnte dies etwas mit Online First zu tun haben?
Denn es wurde nachweislich bei der Einspielung nicht gekennzeichnet und ich denke in der letzten Woche wurde in diesem Bereich auch nichts im vollautomatischen Verfahren angepasst.

Werden die OF-Artikel nochmals ganz neu geholt?

**Comment by IxKo** [comment]
Dann wurde der Lizenzstatus wohl nachträglich vom Verlag geändert.
