### ISSUE TITLE
ISSN 1862-5886 Zeitschrift für junge Religionswissenschaft Band im Feld Ausgabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#195]
hier wieder das bereits bekannte Phänomen, dass beim halbautomatischen Verfahren die Bandangabe im Feld Ausgabe von Zotero zu finden ist.
Beispielaufsatz: https://journals.openedition.org/zjr/1071

**Comment by shadeMe** [comment]
Leider ist sind die eingebeteten Metadaten auf der Webseite falsch. Ich habe versucht, eine strukturierte Kennzeichnung der Ausgabe/Bandangabe auf der Oberfläche zu finden aber keine ist mir aufgefallen. Von daher ist es ganz schwierig solche Fehler automatisch zu erkennen, zumindest bei dieser Zeitschrift.

**Comment by shadeMe** [comment]
@kdr154 Könner wir dies denn schließen?

**Comment by kdr154** [comment]
Schließe
