### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion (Oxford Academic) | Rezensionskennzeichnung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1950]
#### URL
https://doi.org/10.1093/socrel/srac036
IxTheo#2023-04-28#582F90FA0052113CEE657DC3F66A7045B037CE89
  
### Problembeschreibung

Die Rezension wurde nicht als solche bei der Einspielung gekennzeichnet.

**Comment by jriedl** [comment]
Aktuell weder lokal noch auf ub28 reproduzierbar:
![image](https://user-images.githubusercontent.com/13135579/236222453-d746ae13-3cbd-4f21-869b-dff4bbfebfa4.png)

**Comment by IxKo** [comment]
Ok
