### ISSUE TITLE
ISSN 0021-325X Ius Canonicum ISSN und Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#196]
Bei dieser ZS kommt im halbautomatischen Verfahren die ISSN nicht mit:
https://www.unav.edu/publicaciones/revistas/index.php/ius-canonicum/issue/archive
zudem wird beim Verfasser die Institution, bei der er beschäftigt ist, übertragen. Die sollte entfallen.
Bsp.:
Bei diesem Aufsatz: https://www.unav.edu/publicaciones/revistas/index.php/ius-canonicum/article/view/33140
steht im Feld Autor: Thierry Pontificia Università della Santa Croce im Feld des Vornamens.
Es sollte dort aber nur Thierry stehen.

**Comment by shadeMe** [comment]
Die ISSN ist leider auf der Webseite nirgends zu finden. Den anderen Fehler wird behoben.

**Comment by kdr154** [comment]
Das folgende Problem besteht bei mir weiterhin:
Bei diesem Aufsatz: https://www.unav.edu/publicaciones/revistas/index.php/ius-canonicum/article/view/33140
steht im Feld Autor: Thierry Pontificia Università della Santa Croce im Feld des Vornamens.
Es sollte dort aber nur Thierry stehen.

**Comment by shadeMe** [comment]
Der neue Translator funktioniert bei mir. Sind deine lokalen Translators aktuell? Er nennt sich "ubtue_Universidad de Navarra.js" in unserem Repositorium.

**Comment by kdr154** [comment]
gelöst

**Comment by socheres** [comment]
@shadeMe bitte noch Titel auf englisch scrapen. `<meta name="DC.Title.Alternative" xml:lang="en" content="The Preliminary Phase of the New Nullity Proceedings"/>`in item type "shortTitle".

**Comment by shadeMe** [comment]
Der "Universidad de Navarra" Translator funktioniert wie erwartet.

![Screenshot_20191010_150826](https://user-images.githubusercontent.com/214450/66571582-d50ff200-eb6f-11e9-9042-d1a209e79bf9.png)

**Comment by kdr154** [comment]
Der Translator "Universidad de Navarra" steht bei mir in der Auswahl nicht zur Verfügung. In Zeder sehe ich den Eintrag, dass diese ZS von kaldi formalerschlossen werden soll. Funktionieren sollte es m. E. aber schon.

**Comment by shadeMe** [comment]
Den Translator kann man hier finden - https://github.com/ubtue/zotero-translators/blob/master/ubtue_Universidad%20de%20Navarra.js

**Comment by kdr154** [comment]
Ich habe den oben genannten Translator in mein Translatorverzeichnis kopiert, den Browser geschlossen, in den Preferences ein Update der Translator durchgeführt. Er wird nicht erkannt. Von keiner getesteten Zeitschrift, die von der Universidad de Navarra gehostet wird,

**Comment by shadeMe** [comment]
Ich habe den Translator gerade eben aktualisiert.

**Comment by socheres** [comment]
@kdr154 Was funktioniert hier nicht?

**Comment by kdr154** [comment]
Das aktuelle Heft erscheint immer auf den Seiten der Universidad de Navarra. Hier gibt es folgende Probleme.
1. Das Abstract wird nicht erfasst
2. Ein Ordenskürzel wird zu einem Namen
Vgl. https://revistas.unav.edu/index.php/ius-canonicum/article/view/39118

![grafik](https://user-images.githubusercontent.com/29707105/78527948-82418b00-77de-11ea-9092-27bcf7b0808f.png)

Die Zeitschrift soll aber laut Zeder von Kaldi ausgewertet werden. Vgl Zeder Z=1564
Wie die das machen, weiß ich nicht.

**Comment by thefass** [comment]
Die Zeitschrift wird mit OJS gemacht. Siehe Quelltext:
<meta name="generator" content="Open Journal Systems 3.1.2.1">

Die Daten sollten von dort geholt werden. Wenn das mit Zotero nicht geht, dann muss Kaldi das manuell machen

**Comment by thefass** [comment]
Es war schon entschieden, dass Kaldi diese Zss übernimmt. Hatte ich nicht mehr auf dem Schirm. Sorry. Ich habe die Korrespondenz dazu in Zeder 1564 Spalte dok verlinkt.

**Comment by socheres** [comment]
sie kann halbautomatisch erfasst werden. Abstract und Ordenskürzel können - wie bei einigen Zss. im halbautomatischen Verfahren auch der Fall ist - manuell ergänzt bzw. korrigiert werden. @kdr bitte Punkt 1. und 2. in ZEDER vermerken. Zumindest das Problem 1. kann später behoben werden.

**Comment by thefass** [comment]
Dann könnte das ein schönes Beispiel sein, den Innsbrucker Kollegen das halbautomatische Verfahren zu erklären, so dass auch sie mit Zotero arbeiten und die Vorteile davon nutzen können

**Comment by socheres** [comment]
ToDo:

- [ ] Zotkat-Schulung für Innsbruck

**Comment by kdr154** [comment]
Kann man eine Videokonferenz organisieren?

**Comment by kdr154** [comment]
Wird von Kaldi formalerschlossen. Das aktuelle Heft hat Vorläufigkeitsstatus (Articulos aceptados) und besitzt keine Seitenzahlen. Sonst sehen die Daten mit dem Open_Journal_Systems_Standard-Translator gut aus.

**Comment by kdr154** [comment]
ToDo steht noch aus.
