### ISSUE TITLE
ISSN 2595-5977 | Revista Eclesiástica Brasileira (OJS) | Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1962]
#### URL
https://revistaeclesiasticabrasileira.itf.edu.br/reb/article/view/4738
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung

Die beiden Abstracts werden nicht voneinander getrennt:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/5b3bde4a-fdfe-42b4-a0a9-1a5fcb1024fd)

**Comment by IxKo** [comment]
Danke, werden nun getrennt:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/65cadf0d-4e54-4eb3-8974-262a49597fee)

**Comment by socheres** [comment]
Doppelpunkt vor dem Abstract wird nun auch entfernt.
