### ISSUE TITLE
ISSN 2617-1953 | Limina | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1965]
#### URL
https://unipub.uni-graz.at/limina/periodical/titleinfo/8653308
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Kann für diese Seite ein neuer Translator geschrieben werden?

**Comment by IxKo** [comment]
Funktioniert schon ganz gut.

Könnte noch Folgendes importiert/geändert werden:

- [ ] ISSN 2617-1953
- [ ] DOI
- [ ] Schlagwörter als Tags
- [ ] Es wird das engl Abstract importiert und als Notiz nochmals das engl. statt dem dt. Abstract: http://dx.doi.org/10.25364/17.6:2023.1.14

**Comment by IxKo** [comment]
Die Schlagwörter kommen noch immer nicht mit und auch das zweite dt. Abstract wird nicht importiert. Dafür wird das engl. Abstract nun nicht mehr doppelt importiert.

Was mir nun zusätzlich noch auffiel: Es gibt teilweise ORCIDs, die auch nicht importiert werden. Ich habe es bei meinem vorherigen Kommentar als Punkt ergänzt.

**Comment by PaulaHaehndel** [comment]
Ich verstehe nicht, warum die Schlagwörter nicht mitkommen, in meinen Test sind sie immer vorhanden.

**Comment by IxKo** [comment]
Ich nehme den Translator ubtue_Uni_Graz

Bis auf die Keywords kam alles mit.

Der Mehrfach-Import hat jedoch nicht geklappt, und jetzt scheint auch der Einzel-Import (getestet bei http://dx.doi.org/10.25364/17.6:2023.1.3) zu streiken:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/6885ce1d-74a4-4566-bb1c-6302faa39c28)

**Comment by IxKo** [comment]
Danke, der Import bricht nicht mehr ab.
Danke auch für die Fehlersuche bzgl. der Keywords.
