### ISSUE TITLE
ISSN 2769-1616 | Journal of Pentecostal and charismatic Christianity (T&F) | falsches M&M

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1966]
#### Hash
IxTheo#2023-05-30#8137B81ED50BBB03226425CECD2E37D525D06208
https://doi.org/10.1080/27691616.2023.2184451 

### Problembeschreibung
Der Datensatz wurde nicht eingespielt. Es wurde lediglich an einen völlig anderen Datensatz (PPN 1842678795) zu einer anderen Zs. ein Exemplardatensatz ergänzt, und wahrscheinlich 5056 1 ergänzt:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/bd8b126e-d479-447f-bbd9-6103e491fc43)

Hier scheint beim M&M etwas schief gelaufen zu sein.
Außer dem Haupttitel "Editorial", den Seitenzahlen 1-2 und dem Jahr 2023 stimmt nichts überein.

Ich habe das Editorial nun manuell katalogisiert (PPN 1846994713), den Exemplardatensatz umgesigelt und "5056 1" und "0575 mteo" aus dem anderen Datensatz entfernt.

**Comment by IxTheoKm** [comment]
Das ist das leidige M&M-Problem, für das es immer noch keine Lösung gibt - und wenn ich die letzten Besprechungen richtig verstehe, wohl auch nicht geben wird. Wir hatten in der Vergangenheit schon einigen Datenverlust durch Merge mit völlig anderen Datensätzen.

**Comment by IxKo** [comment]
Nun ist ein weiteres Editorial genau an diesem Datensatz wieder gemerged worden:
https://www.tandfonline.com/doi/full/10.1080/14622459.2023.2215156 
IxTheo#2023-05-30#8137B81ED50BBB03226425CECD2E37D525D06208
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/65bbdaa2-4fd3-4844-991f-370ad664e506)

Das andere habe ich schon manuell "entzweit".

Könnte dann eventuell das M&M vom BSZ deaktiviert werden? Wenn es so wahllos merged, macht es nur Mehrarbeit.

**Comment by socheres** [comment]
Liebe/r @jriedl @IxKo, könnten wir für die in diesem Issue https://github.com/ubtue/DatenProbleme/issues/1612#issue-1051081278 erwähnten Titeleien ein "add_marc_field._912$aNOMM" in der globalen Einstellung einführen, um M&M zu umgehen?

**Comment by jriedl** [comment]
Es exisitiert ja bereits der `zotero_notes_regex`  und der `zotero_review_regex` - denkbar wäre hier, zusätzlich zu den dadurch ohnehin im Code eingefügten Feldern noch `NOMM` zu setzen. Vor Codeanpassungen sollte aber abschließend entschieden werden, ob das dann der diesbezüglich dauerhaft gewählte Ansatz ist,  bzw. ob `NOMM` nicht für Zotaut _immer_ gesetzt werden sollte.

**Comment by socheres** [comment]
@IxKo Wie ist Ihre Meinung? Ist es sinnvoll, "NOMM" für alle Zotaut-Datensätze zu verwenden oder nur für "notes" und "review"?

**Comment by IxKo** [comment]
`NOMM` nur allein bei "notes" und Rezensionen zu setzen, löst das hier in diesem Issue genannte Problem wahrscheinlich nicht.
Die beiden Editorials - bei denen der Merge auftrat- fielen wahrscheinlich nicht unter "notes", da sie einen Autor haben.
Der "notes"-Regex soll meines Wissens dort greifen, wo es kein Autorenfeld gibt, und es dadurch sonst in den Errors landen würde, oder greift der "notes"-Regex bereits vorher?

Bei der Willkür des BSZ-M&M scheint es mir nicht ausgeschlossen, dass es auch andere sich wiederholende bzw. oft vorkommende Titel betreffen kann, die eventuell nicht durch die "notes"-Regex abgedeckt sind.

**Comment by jriedl** [comment]
Für die Kennzeichnung als "notes" ist zunächst einmal nur der reguläre Ausdruck maßgeblich. Es wird dann das Tag `NOT` im Record gesetzt, was im QS-Kontext bedeutet, dass die Existenz eines Autors nicht mehr gefordert wird, damit hier keine false positives auftreten. Im Bezug auf `NOMM` würde das aber keine Rolle spielen. Es stellt sich aber natürlich die Frage, ob eine generelles Setzen nicht dennoch die nachhaltigere Lösung wäre.

**Comment by jriedl** [comment]
Wie besprochen jetzt auf nu die angepasste Version mit grundsäztlichem Einfügen von 912$aNOMM.

**Comment by IxKo** [comment]
Ich habe heute in den QA-Settings bei der Zs. "Revue des études byzantines"  (Z=1757) die QA-Settings um Feld 912a ergänzt, da das "NOMM" wohl über dieses Feld generiert wird und es bisher nicht in den QA definiert war.

**Comment by jriedl** [comment]
Die aktuelle Version mit unterdrücktem M&M ist nun auch auf ub28 installiert.

**Comment by IxKo** [comment]
Danke, hat geklappt.
