### ISSUE TITLE
Rezensionen wichtige Änderung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#197]
1140 uwre wird es im neuen K10plus nicht mehr geben. Statt dessen müssen wir die Kategorie 1131 belegen. Vielleicht am besten verbal mit dem Begriff "Rezension"und nicht als PPN Verknüpfung.

Dies bedeutet, folgender Code muss gestrichen werden
```
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="c">uwre</subfield>
</datafield>
```
Statt dessen sollten wir im Fall von Rezensionen folgendes setzen:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
</datafield>
```

**Comment by kdr154** [comment]
Frau Kellmeyer macht mich darauf aufmerksam, dass im K10plus die Eingabe in Feld 1131 in der Regel als Verknüpfung zur GND (Gemeinsame Normdatei) erfolgt. Folglich sollten wir es so belassen, wie bereits in #132 beschrieben:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!209083166!</subfield>
<subfield code="0">(DE-576)</subfield>
</datafield>
```

**Comment by IxTheoKm** [comment]
Welche Auswirkungen das PPN-Konzept in K10plus in diesem Fall (und in allen anderen relevanten Fällen) hat, kann ich mangels tieferem Verständnis der Exportinformationen auf den Seiten https://wiki.k10plus.de/display/K10PLUS/Allgemeines+zur+Datenbereitstellung nicht ermessen.

Grundsätzlich gewinnen bei den Altdaten die GBV-PPNs in PICA-Feld 0100 = MARC 001, die SWB-PPNs werden zusätzlich in eigenen Feldern abgelegt.
Bei Neuerfassungen gibt es nur noch neue, gemeinsame PPNs in 0100 = 001:
![k10plus_ppns](https://user-images.githubusercontent.com/17004223/53400557-6c904e00-39ae-11e9-908b-1923f5e89a3b.JPG)

Wenn ich die Tabellen von der Seite https://wiki.k10plus.de/display/K10PLUS/Exportformate richtig verstehe, bleibt es im SWB-eigenen Feld für die SWB-PPNs bei MARC-Feld 001. Das interpretiere ich so, dass der SWB die GBV-PPNs gar nicht ausliefert!
Damit könnten wir bei der alten SWB-PPNs bleiben.

Da die PPN-Frage alle Anwendungen betrifft, mache ich dafür nochmal ein eigenes Issue auf:
https://github.com/ubtue/tuefind/issues/547

**Comment by kdr154** [comment]
Im K10plus werden die Daten in Zukunft folgendermaßen ausgeliefert:
655 7$aRezension$0(DE-588)4049712-4$0(DE-627)106186019$0(DE-576)209083166$2gnd-content
d. h. GND-Identnummer: (DE-588)4049712-4
als auch GBV-PPN: (DE-627)106186019
als auch SWB-PPN: (DE-576)209083166
sind vorhanden

**Comment by kdr154** [comment]
Damit ist ein Teil wahrscheinlich richtig ungesetzt.

Legt man das obige Beispiel zugrunde, das da lautet:
655 7$aRezension$0(DE-588)4049712-4$0(DE-627)106186019$0(DE-576)209083166$2gnd-content
und das auf der Marc-Ansicht im K10plus basiert, müsste 655 (möglicherweise, da ich nicht weiß, inwieweit diese Ansicht formal mit dem Code korrelliert, den wie liefern sollen) das Tag 655 für Rezensionen so aussehen:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
<subfield code="0">(DE-588)4049712-4</subfield>
<subfield code="0">(DE-627)106186019</subfield>
<subfield code="0">(DE-576)209083166</subfield>
<subfield code="2">gnd-content</subfield>
</datafield>

```
das gilt aber nur für die Daten, die vor der Migration in den SWB eingespielt werden. Da aus diesem Projekt keine Daten vor der Migration in den SWB eingespielt werden, ist das Ganze obsolet. Wie gesagt, wissen wir aber noch nicht, welche Werte bei neu im K10plus angelegten Daten verlangt werden.
Deshalb bin ich der Auffassung, wir sollten im Augenblick die Option zurückstellen, das Feld 1131 in der Form einer Verknüpfung zu erstellen, und statt dessen einstweilen das Feld verbal befüllen. Das ist ebenfalls gestattet, die Verknüpfung ist lediglich die bevorzugte Form. 

Das hieße in meinen Augen, der Code bei Rezensionen sollte einstweilen wie folgt lauten:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
</datafield>
```
Wenn wir wissen, wie der Code für die Verknüpfung aussehen muss, kann man den entsprechenden Teil austauschen. Ich vermute, das ist kein Problem und besser, als das Spekulieren und ewige hin und her.

**Comment by ruschein** [comment]
Da wir genau das machen wie im vorherigen Kommentar beschrieben, die Verknüpfungen sind ja nicht möglich, denke ich, wie sind soweit fertig, oder?

**Comment by kdr154** [comment]
Allerdings sollten Rezensionen schon in der Form:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
</datafield>
```
getagt werden.

**Comment by kdr154** [comment]
ok

**Comment by kdr154** [comment]
Da nun migriert wurde, könnten wir den Normdatensatz für Rezensionen in 1131 verankern und 
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">Rezension</subfield>
</datafield>
```
austauschen gegen
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
106186019 ist die GND-PPN für Rezensionen.  Der Bezug zur GND-Nummer wird normalerweise im Zuge der Verknüpfung automatische erzeugt und in 1131 verbal verankert, so dass weitere Unterfelder überflüssig sein sollten. Der subfield code 0 wie ober dargestellt möglicherweise auch.

**Comment by kdr154** [comment]
Gelöst
