### ISSUE TITLE
ISSN 1745-5308 | The Expository times (SAGE) | fehlender Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1970]
#### URL
https://doi.org/10.1177/00145246221133914

  
### Problembeschreibung
Der Aufsatz wurde nicht eingespielt und findet sich nicht auf ub28

Mit TRY RSS wird jedoch ein Datensatz über den Feed generiert.

**Comment by jriedl** [comment]
Wurde offenbar im Rahmen des Durchlaufs gestern Abend eingespielt.

**Comment by IxKo** [comment]
Ja, danke.
Wie kam es zu diesen Verzug? Laut Artikel-Seite gibt es den Aufsatz seit Januar online.
Liegt es an dem RSS?
