### ISSUE TITLE
ISSN 2056-7731 | Baptist quarterly (tandf) | fehlender Eintrag

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1977]
#### URL
https://doi.org/10.1080/0005576X.2023.2186019
  
### Problembeschreibung

Dieser Eintrag fehlt in den Einspielungen zu Volume 54, Issue 3 (2023) und auch auf ub28.
Kann der Grund dafür ermittelt werden?

**Comment by jriedl** [comment]
Ein manueller Download von ub28 funktioniert und die DOI ist im RSS-Feed vorhanden. In den OF-Dateien findet sich die Datei die Datei seit März, letztmalig am 19.6., damit sind Der Eintrag findet sich in den Logs der vergangenen Tage, allerdings ist die DOI/URL heute in der Trackingdatenbank bereits bekannter und ausgelieferter URLs nicht auffindbar. Da die OF-Einträge der Trackingdatenbank gelöscht werden und wir hier aktuell genau in der Größenordnung der nächsten Iteration sind, sollte die Einspielung heute Abend noch abgewartet werden.

**Comment by jriedl** [comment]
Jetzt vorhanden

**Comment by IxKo** [comment]
Ok, danke. Dann werde ich zukünftig einen Tag warten ehe ich ein solches Issue aufmache.
