### ISSUE TITLE
ISSN 1469-9737 | Mental health, religion and culture (tandf) | fehlender Eintrag

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1978]
#### URL
https://doi.org/10.1080/13674676.2022.2149718

  
### Problembeschreibung
Der Aufsatz Volume 25, 2022 Issue 10 wurde nicht eingespielt und findet sich auch nicht auf ub28.

**Comment by jriedl** [comment]
Ebenfalls letztmalig in der OF-Datei vom 19.6., deshalb Stand jetzt analog zu #1977.

**Comment by IxKo** [comment]
Sind die OF-Artikel nicht ebenfalls auf ub28 mit schwarzem Punkt geführt?

**Comment by jriedl** [comment]
Ja, im Regelfall schon, aber nicht innerhalb des Zeitraums, wo beim Durchlauf am letzten Abend erkannt wurde, dass das OF-Intervall, das einen neuen Downloadversuch verhindert, abgelaufen ist (und damit der Artikel aus der Trackingdatenbank gelöscht wird, damit er eben noch einmal heruntergeladen werden kann) und der nächsten Ausführung der Pipeline am folgenden Abend.

**Comment by jriedl** [comment]
Jetzt vorhanden

**Comment by IxKo** [comment]
Danke!

**Comment by IxKo** [comment]
Ich hoffe dieses Mal nicht das OF-Zeitfenster erwischt zu haben, da ich den Artikel schon länger als einen Tag vermisse:

https://doi.org/10.1080/13674676.2023.2237909
Titel: Role of religion in posttraumatic growth among population exposed to armed conflict: a systematic review
Autor: Irfan Fayaz

Er ist nicht auf ub28 aufgeführt und nicht eingespielt.

In meinem RSS-Feed-Reader wurde er mir aber im August angezeigt, weshalb er wohl mal im RSS-Feed auftauchte:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/67fe9330-8c53-41c0-89ba-fa7ed09c6d0d)

**Comment by jriedl** [comment]
Eine Testgenerierung auf nu und ub28 mit der der DOI als URL läuft problemlos durch (mit vollständigen Heftangaben ). Der aktuelle Feed (https://www.tandfonline.com/feed/rss/cmhr20) enthält den Artikel aber nicht. Vermutlich ist er also mit dem "Erscheinen" aus dem Feed verschwunden (andere Artikel aus Heft 26 wurden ja Ende Oktober, Anfang November eingespielt). Da aber offenbar nicht alle Artikel des Hefts unmittelbar nach Veröffentlichung eines neuen Hefts im Feed auftauchen, besteht eventuell etwas Hoffnung, dass er zu einem späteren Zeitpunkt selbst wieder seinen Weg in den Feed findet. Ansonsten müsste T&F angefragt werden.
