### ISSUE TITLE
ISSN 0254-4407 Zwingliana Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#198]
Book reviews werden nicht als solche erkannt und getagt (Tag 655), aber mit dem Schlagwort Book review versehen.
Bsp.:
```
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="4">aut</subfield>
<subfield code="a">Peter, Niklaus</subfield>
</datafield>
<datafield tag="245" ind1="0" ind2="0">
<subfield code="a">Conrad Ulrich, Die Familie Ulrich von Zürich, 2016</subfield>
</datafield>
<datafield tag="264" ind1=" " ind2=" ">
<subfield code="c">2017</subfield>
</datafield>
<datafield tag="520" ind1="3" ind2=" ">
<subfield code="a">No abstract available.</subfield>
</datafield>
<datafield tag="650" ind1=" " ind2="4">
<subfield code="a">book review</subfield>
</datafield>
```

**Comment by kdr154** [comment]
Lässt sich leider nicht überprüfen, da das aktuelle Heft keine  Book Reviews hat. Oder gibt es einen Weg?

**Comment by shadeMe** [comment]
Keinen, der mir gerade einfällt, befürchte ich.

**Comment by kdr154** [comment]
Im halbautomatischen Verfahren funktioniert nur der Einzeldownload. Dort muss man die entsprechenden Tags sowieso manuell ergänzen. Darüber hinaus sollte die 0 die ins Zotero-Feld Ausgabe geschrieben wird, unterdrückt werden.
Die Frage ist, ob diese ZS nicht für das vollautomatische Verfahren geeignet ist.

**Comment by shadeMe** [comment]
Der [Open Journal Systems Multi-Wrapper](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Open%20Journal%20Systems%20Multi-Wrapper.js) Translator unterstürzt Multidownload bei dieser Webseite.

**Comment by kdr154** [comment]
Multidownload funktioniert jetzt.

**Comment by shadeMe** [comment]
Funktioniert auf meinem Rechner. Wird wahrscheinlich nach ein paar Neustarten des Rechners/Browsers/Zotero-Clients funktionieren.

![Screenshot_20191016_113525](https://user-images.githubusercontent.com/214450/66907094-11789d80-f009-11e9-9b88-2fb1255b3aed.png)

**Comment by kdr154** [comment]
Webseite nicht erreichbar 2020-05-06

**Comment by IxKo** [comment]
Bei mir funktioniert der OJS Multi-Wrapper nicht, obwohl ich ihn auswähle.

**Comment by socheres** [comment]
> Book reviews werden nicht als solche erkannt und getagt (Tag 655), aber mit dem Schlagwort Book review versehen.
> Bsp.:

das oben beschriebene Problem im Zotaut ist behoben, aber kann wegen der Unerreichbarkeit der Webseite nicht getestet werden. http://www.zwingliana.ch/index.php/zwa

@kdr154 bitte mit Zotkat testen.

**Comment by socheres** [comment]
Die Webseite ist immer noch nicht erreichbar "Database connection failed!"

**Comment by kdr154** [comment]
Sollte man da nicht bei den Betreibern mal nachfragen? Ich habe diese Seite in der Zwischenzeit bereits mehrere Male versucht aufzurufen, nie war sie erreichbar.

**Comment by IxTheoKm** [comment]
http://www.zwingliana.ch/index.php/zwa ist heute erreichbar.

**Comment by IxKo** [comment]
Single-DL funktioniert, Multi-Wrapper funktioniert nicht.

Mit Nu werden die Rezensionen getagt, aber auch das Schlagwort "book review" wird erfasst, sowie das Pseudo-Abstract:

![grafik](https://user-images.githubusercontent.com/57000004/91267099-e4416380-e772-11ea-92eb-0f01e2e4b7db.png)


Auf Nu werden die Einträge "Personenregister" und "Titelblatt, Impressum, Inhalt" mit Autor "N, N." erfasst. Diese sollten herausgefiltert werden. Ebenso das "Geleitwort".

**Comment by socheres** [comment]
enhancement_maps ergänzt. Bitte auf Nu nochmal testen. Für Zotkat bitte mit "Open Journal Systems Standard.js" testen.

**Comment by IxKo** [comment]
Zotkat Translator funktioniert.

- [ ] Auf Nu wird weiterhin das Pseudo-Abstract "No abstract available." ausgegeben.

- [ ] Bei Rezensionen ist nun das Keyword "book review" nicht mehr enthalten, aber die Rezensionen werden nicht mehr mit dme Formschlagwort getagt.

Die nicht relevanten Titel wurden herausgefiltert.

**Comment by socheres** [comment]
mit "Try URL": http://www.zwingliana.ch/index.php/zwa/issue/view/216 getestet.
Beim aktuellen Heft Bd. 45 gibt es keine Rezensionen.

**Comment by socheres** [comment]
@mtrojan-ub bitte nach merge "ready for testing" hinuzufügen.

**Comment by kdr154** [comment]
Zotaut: Rezensionen besitzen jetzt Tag 655 und auch 650 bool review wird nicht vergeben.

**Comment by kdr154** [comment]
Zotkat: Rezensionstag muss manuell gesetzt werden, aber:
im Multi-DL ist die Seitenangabe nicht korrekt, die Endseitenzahl wird 2x ausgegeben:

![grafik](https://user-images.githubusercontent.com/29707105/91697234-0e2ec780-eb71-11ea-945d-d877ae84d296.png)

und als Sprache wird immer "en" vergeben. Leider sind die Aufsätze nicht durchgehend auf Deutsch.
Im Single-DL wird der Translator Open Joural Systems Standard nicht angeboten. Mit dem Open Journal  Systems-Translator ist die Angabe der Seitenzahlen korrekt, als Sprache wird aber auch hier "en" vergeben.

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by kdr154** [comment]
Für zotaut sieht die Sache (Book Reviews, Sprache) jetzt gut aus, bei zotkat bestehen die Probleme weiter (Tag book review, Sprache, Pseudo-Abstract).

**Comment by socheres** [comment]
In den eingebetteten Metadaten steht durchgängig als Sprache "en", daher nicht über Translator lösbar (siehe ZEDER Vermerk b_zot). Bitte beim Testen "Open Journal Systems Standard.js" verwenden. Soll diese Zeitschrift retrospektiv bis 1897 nacherfasst werden? Frage an die Runde @thefass @IxTheoKm

**Comment by thefass** [comment]
in der kommenden FID Periode werden viele Zss retrospektiv ausgewertet. Dazu wurde schon eine Auswahl getroffen, die Zss gehört dazu.
Man findet die Zss Auswahl für eine retrospektive Erfassung in Zeder Spalte retro2 > fid2021

**Comment by kdr154** [comment]
Im Zotkat-Verfahren werden die Rezensionen nun getagt und es gibt keine Pseudo-Abstracts mehr. Da die Sache mit der Sprache nicht gelöst werden kann, sind die Probleme aus meiner Sicht gelöst.

**Comment by socheres** [comment]
ich schließe.
