### ISSUE TITLE
ISSN 0008-8501 | Catholica (Ebsco) | Band

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1983]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26bquery%3dJN%2b%2526quot%253bCatholica%2526quot%253b%2bAND%2bDT%2b20230101%2bNOT%2bPM%2bAOP%26type%3d1%26searchMode%3dAnd%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js
  
### Problembeschreibung
Die Bandangabe "77" wurde nicht importiert.
Allerdings bin ich unsicher, ob es überhaupt möglich ist, da ich auf EBSCO keine sehe.
Bisher wurde es laut K10plus mit Zotero katalogisiert und in den Katalogisaten ist die Bandangabe nachgewiesen. Es kann sein, dass sie immer manuell nachgetragen wurde. Es findet sich jedoch kein Hinweis in ZEDER b_zot.

**Comment by socheres** [comment]
Bandangabe finde ich weder auf der HTML noch in RIS & Co. Daher muss sie manuell erfasst werden. Bitte in ZEDER vermerken.
