### ISSUE TITLE
ISSN 0010-3713 | Communio viatorum (etf) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1987]
#### URL
https://web.etf.cuni.cz/ETFN-162.html#7
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Könnte für diese Seite eventuell ein Translator geschrieben werden?

Folgende Informationen sollten dabei nach Zotero importiert werden:

- [x] ISSN 0010-3713
- [x] Titel mit Zusatz
- [x] Autor
- [x] Bandangabe in arabischen Ziffern
- [x] Heftzählung
- [x] Seitenangaben
- [x] Sprache, falls sich eine korrekte pro Aufsatz in den HTML-Metadaten finden lässt, andernfalls wäre die überwiegende (eng) Sprache ausreichend, sodass bei Abweichung davon weniger angepasst werden muss
- [x] Abstract
- [x] Keywords
- [x] URL zum Aufsatz
- [x] DOI
- [x] automatische Erkennung von Rezension durch Kennzeichnung mit Tag "RezensionstagPica" https://doi.org/10.14712/00103713.2022.3.7

Momentan scheint die Seite keine Volltexte anzubieten, weshalb wir weiterhin an die Print-Aufnahme (Abv) katalogisieren würde.
Eventuell ändert sich dieser Zustand aber in Zukunft mal.

**Comment by PaulaHaehndel** [comment]
Sprache wird nicht aus den HTML-Daten extrahiert, sodass sie standardmäßig auf "eng" gesetzt wird.

PS: Die Liste ist sehr praktisch.

**Comment by IxKo** [comment]
Danke! Das meiste funktioniert schon.
Nur die Keywords werden nicht importiert - und - das habe ich oben in der Liste ergänzt - eine automatische Erkennung der Rezensionen wäre schön.

**Comment by IxKo** [comment]
Keywords und dementsprechend das Rezensionstag kommen nun mit, danke sehr!
