### ISSUE TITLE
ISSN 1853-9106 | DavarLogos (OJS) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1988]
#### URL
https://doi.org/10.56487/dl.v22i1.1080
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung

Die Keywords nach "Palabras clave" werden nicht nach Zotero importiert.
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/81bc4234-a61b-4b0e-b376-40638177dba1)

**Comment by IxKo** [comment]
Jetzt kommen sie mit, jedoch als ein einziges Tag und werden nicht getrennt:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/26cca186-f169-4535-8e8b-0f7f723dcbf0)

**Comment by IxKo** [comment]
Könnten sowohl das engl. als auch das span. Abstract importiert werden?
Ebenso bei den Keywords?

Und könnte auch der Paralleltitel mit importiert werden?

**Comment by socheres** [comment]
Paralleltitel und span. Abstract ja, aber engl. Keywords leider nicht möglich, da diese nicht im Quellcode enthalten sind.

**Comment by IxKo** [comment]
Danke, die beiden Abstracts werden importiert, der Paralleltitel aber noch nicht.

**Comment by socheres** [comment]
Nun sollte der Paralleltitel mitkommen.

**Comment by IxKo** [comment]
Nun kommt in den Notizen ein "translated title" mit, aber er scheint nicht exportiert zu werden. Er sollte in 4002

Bei diesem Aufsatz: https://publicaciones.uap.edu.ar/index.php/davarlogos/article/view/1078 wird wiederum gar keine Notiz zum Paralleltitel importiert.

**Comment by socheres** [comment]
engl. und span. Paralleltitel werden nun importiert. Falls Paralleltitel in weiteren Sprachen erscheinen, bitte melden.

**Comment by socheres** [comment]
> engl. und span. Paralleltitel werden nun importiert. Falls Paralleltitel in weiteren Sprachen erscheinen, bitte melden.

weitere Sprachen werden nun importiert`//meta[@name="DC.Description"][@*=("es") or @*=("en") or @*=("fr") or @*=("it") or @*=("pt")]/@content`
