### ISSUE TITLE
ISSN 170178811 | Quaderni di diritto ecclesiale | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1992]
#### URL
https://www.quadernididirittoecclesiale.org/rivista/qde2023-2
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Ist es eventuell im Bereich des Möglichen einen Translator für diese Seite zu erstellen?

Viele Informationen sind nicht abzugreifen:

- [x] ISSN
- [x] Titel
- [x] Autor:in
- [x] Seitenzahl
- [x] Band in arabischen Ziffern
- [x] Jahr
- [x] Heft

Es wird nur die Anfangsseite eines Artikels aufgeführt. Eventuell könnte mit der Anfangsseite des nächsten Artikels minus 1 der Umfang berechnet werden.
Die Autor:innen eines Aufsatzes werden immer mit "di" eingeführt.

Links zu PDF-Dateien gibt es nur bei älteren Jahrgängen (<2017) oder beim Editorial oder den Abstracts.

**Comment by IxKo** [comment]
Danke sehr! Der Translator funktioniert schon fabelhaft für diese nicht so fabelhafte Seite :-)

Bei dem Aufsatz: 
139 - L'iter storico e redazionale di Praedicate evangelium
di Roberto Interlandi
ist der Autor nicht importiert worden und stattdessen Teil des Titels: `L'iter storico e redazionale di Praedicate evangeliumdi Roberto Interlandi`

Zudem enden die Titel oft mit "di" (ital.=von), was in dem Fall dann Bestandteil der Verantwortlichkeitsangabe (Verfasser:innen-Angabe lt. Vorlageform) ist - und teils auch "a cura di" (lt. meiner Recherche ital. für herausgegeben von).

Falls man das noch verbessern kann, wäre es schön, aber wenn es die Seite nicht hergibt, dann kommt ein Bearbeitungshinweis in ZEDER. Die Zs. muss sowieso mit der Print-Vorlage abgeglichen und entsprechend überarbeitet werden.

**Comment by PaulaHaehndel** [comment]
Fehler wie bei "Roberto Interlandi" werden auf der Seite immer wieder auftauchen und auch das Autoren zu den falschen Titeln zugeordnet werden, kann passieren.
Dass das "di" am Ende des Titels steht, ist behoben und auch für das konkrete Beispiel "Roberto Interlandi" sollte es jetzt eigentlich funktionieren.
Das "a cura" wird jedoch nicht automatisch zu Herausgeber umgesetzt.

**Comment by IxKo** [comment]
Vielen Dank!
