### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1993]
#### URL
https://doi.org/10.1007/s11153-023-09868-z
IxTheo#2023-07-14#AC5C0243822CA5FBDA75737DD5AC39AFCCC07B81
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Springer Link.js

  
### Problembeschreibung

Der Artikel ist Open Access. Er wurde allerdings nicht mit 4950 $4LF eingespielt.
Und auch im halbautomatischen Verfahren wird er nicht als LF gekennzeichnet.

**Comment by IxKo** [comment]
Danke im halbautomatischen Verfahren behoben.

Im vollautomatischen noch nicht.

**Comment by jriedl** [comment]
Angepasste Version of auf nu.

**Comment by IxKo** [comment]
Danke, scheint auch schon auf ub28
