### ISSUE TITLE
ISSN 2602-2435 | Dinî araştırmalar | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1994]
#### URL
https://dergipark.org.tr/tr/pub/da/issue/78000
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Ist es möglich für diese Seite einen neuen ubtue-Translator zu schreiben?

- [x] Autor
- [x] Titel + Zusatz
- [x] Quellenangaben: Jahr, Band, Heft
- [x] Abstract
- [x] Keywords
- [x] ORCID
- [x] ISSN
- [x] Rezensionserkennung (KİTAP İNCELEMESİ)
- [x] im Code findet sich auch noch der engl. Paralleltitel, das engl. Abstract und wahrscheinlich auch engl. Keywords

**Comment by IxKo** [comment]
Getestet mit ubtue_dini_arastimaler.js
(Ist es gewollt, dass der Translator ähnlich aber nicht gleich zur Zs. heißt und dass er nicht den Namen der Plattform widerspiegelt?)

Der Translator wird mir nur im Mehrfachimport angeboten, jedoch nicht im Einzelimport. Könnte das noch angeboten werden?
Weiterhin fehlen ORCID, Rezensionserkennung (wenn möglich) und zusätzliche engl. Metadaten.

**Comment by socheres** [comment]
Translatorname habe ich in "ubtue_dergipark.js" geändert.

**Comment by IxKo** [comment]
War das auch ein Versehen, dass das Issue geschlossen wurde, obwohl noch nicht geprüft worden ist... ?

**Comment by IxKo** [comment]
Translator funktioniert, danke, ich schließe.
