### ISSUE TITLE
ISSN 0717-6295 | Teología y vida (OJS) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#1997]
#### URL
https://doi.org/10.7764/TyV642.E2
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Es werden die span. Keywords importiert, aber nicht die englischen.

**Comment by IxKo** [comment]
Bei diesem Fall: https://doi.org/10.7764/TyV642.C1
wurden Keywords importiert, die gar keine sind.
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/818bf2a3-fe0f-4a2d-be47-34b19823a371)

**Comment by socheres** [comment]
Je nach Spracheinstellung sind die Keywords nur in einer Sprache im Quellcode hinterlegt, daher leider nicht möglich. Bitte beim Download der Daten die Spracheinstellung auf Englisch stellen. Bitte das Issue schließen.

**Comment by IxKo** [comment]
Alle Keywords (span.+engl.) sind in den HTML-Metadaten unter <div class="list-group-item keywords"> aufgelistet. Aber wahrscheinlich sind das keine strukturierten Metadaten.

Im zweiten Fall werden weiterhin Keywords importiert, die nicht zum Datensatz gehören, sondern zur Zs.
Die gleichen Keywords werden auch bei einer Rezension importiert: https://doi.org/10.7764/TyV642.PL1

**Comment by socheres** [comment]
> Je nach Spracheinstellung sind die Keywords nur in einer Sprache im Quellcode hinterlegt, daher leider nicht möglich. Bitte beim Download der Daten die Spracheinstellung auf Englisch stellen. Bitte das Issue schließen.

corrigendum: dieser Kommentar bezog sich auf dieses Issue hier https://github.com/ubtue/DatenProbleme/issues/1988

**Comment by socheres** [comment]
> Alle Keywords (span.+engl.) sind in den HTML-Metadaten unter `<div class="list-group-item keywords">` aufgelistet. Aber wahrscheinlich sind das keine strukturierten Metadaten.
> 
> Im zweiten Fall werden weiterhin Keywords importiert, die nicht zum Datensatz gehören, sondern zur Zs. Die gleichen Keywords werden auch bei einer Rezension importiert: https://doi.org/10.7764/TyV642.PL1

behoben siehe https://github.com/ubtue/zotkat-translators/commit/9ed326eec8f4cd1b346fe24aed557a8944907aeb

**Comment by socheres** [comment]
> Bei diesem Fall: https://doi.org/10.7764/TyV642.C1
> wurden Keywords importiert, die gar keine sind.
> ![image](https://user-images.githubusercontent.com/57000004/258144439-818bf2a3-fe0f-4a2d-be47-34b19823a371.png)

diese stehen so in den Metadaten drin `<meta name="keywords" content="Teología, Reflexión teológica, Dios, Fe religiosa,  Facultad de Teología de la Pontificia Universidad Católica de Chile" />r` m.E. kann man so stehen lassen.

**Comment by IxKo** [comment]
Danke, ich habe einen Kommentar zur Bearbeitung in ZEDER hinterlegt. Denn manche Keywords müssten zu zwei geteilt werden.
