### ISSUE TITLE
OJS-Prio ISSN 2628-0000 International Academy of Practical Theology. Conference Series - Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#200]
Hier kommen beim halbautomatischen Verfahren die keywords nicht mit

**Comment by shadeMe** [comment]
Gibt es ein paar Beispiele? Ich sehe keine Keywords auf der [Webseite](https://iapt-cs.org/ojs/index.php/iaptcs/issue/view/13).

**Comment by kdr154** [comment]
Sieht so aus, als ob ich das, was unterhalb von Abstract steht, als Keywords aufgefasst habe.
