### ISSUE TITLE
ISSN 2035-7583 | Rivista di storia e letteratura religiosa (Torrossa) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2003]
#### URL
https://access.torrossa.com/de/resources/an/2193197?digital=true
  Heft: https://access.torrossa.com/de/resources/an/5521608
  
### Problembeschreibung
Kann für diese Zs. und Plattform ein neuer Translator entwickelt werden?

**Comment by socheres** [comment]
Translator zunächst nur für diese Zeitschrift

**Comment by IxKo** [comment]
Mir wird kein neuer Translator angeboten.

**Comment by IxKo** [comment]
Folgende Daten werden nicht importiert:

ISSN
Band
Heft
Permalink (stattdessen wird die "normale" URL importiert)

Zudem werden im Zotero-Feld "Publikation" nochmals die Titel importiert, was verwirrend ist.

Auf die Schnelle konnte ich über ZEDER vier weitere Zs. ausmachen, die möglicherweise vom ImWa-Verfahren oder nachteiligen Plattformen wie EBSCO ins Zotero-Verfahren überführt werden könnten, weil sie auf der Plattform Torrossa nachgewiesen sind:

ISSN 0392-1581: Ricerche di storia sociale e religiosa https://www.torrossa.com/en/resources/an/5474695
ISSN 1827-7365: Rivista di storia del cristianesimo https://www.torrossa.com/en/resources/an/5451157
ISSN 0393-8417: Studi e materiali di storia delle religioni https://www.torrossa.com/en/resources/an/5451206
ISSN 0394-9397: Religioni e società https://www.torrossa.com/de/resources/an/5563004

Zur Feststellung weiterer Zs. auf der Plattform wäre ein zeitintensiver systematischer Abgleich mit ZEDER notwendig.

**Comment by socheres** [comment]
Permalink wird nicht aufgelöst. Außerem führt er zur kostenpflichtigen Seite [Permalink: http://digital.casalini.it/10.1400/292884](http://digital.casalini.it/10.1400/292884), daher habe ich so belassen. Als Permalink gibt es die DOI

**Comment by IxKo** [comment]
Ich habe zwei Stichproben beim aktuellsten Heft gemacht und bei mir lösen die Permalinks auf:
http://digital.casalini.it/10.1400/292883

Daher würde ich diese weiterhin bevorzugen.

**Comment by IxKo** [comment]
Mir wird noch immer kein Import-Translator angeboten:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/2c604a18-0664-4d7d-bfa7-4c3e7a7507e9)

**Comment by socheres** [comment]
Welche URL? Bei mir wird "ubtue_torrossa.js"-Translator angeboten hier https://www.torrossa.com/en/resources/an/5500139?qt=any_keyword_search&q=rivista+di+storia++letteratura&rows=50&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+desc&start=0&page=0&publisher_code=FF6950&type=Search&itemnumber=0&rows_original=50&uri_original=%2Fen%2Fsearch%2Frivista%2520di%2520storia%2520%2520letteratura UND auch https://www.torrossa.com/en/resources/an/5500139

**Comment by IxKo** [comment]
> Welche URL? Bei mir wird "ubtue_torrossa.js"-Translator angeboten hier https://www.torrossa.com/en/resources/an/5500139?qt=any_keyword_search&q=rivista+di+storia++letteratura&rows=50&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+desc&start=0&page=0&publisher_code=FF6950&type=Search&itemnumber=0&rows_original=50&uri_original=%2Fen%2Fsearch%2Frivista%2520di%2520storia%2520%2520letteratura UND auch https://www.torrossa.com/en/resources/an/5500139

Die URLs, welche ich eingangs in diesem Issue angegeben habe.

**Comment by IxKo** [comment]
Danke, passt nun.
