### ISSUE TITLE
ISSN 2542-4246 | International Journal of Asian Christianity (Brill) | neuestes Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2007]
#### URL
https://brill.com/view/journals/ijac/6/2/ijac.6.issue-2.xml
  

### Problembeschreibung

Das aktuelle Heft (Band 6 (2023): Ausgabe 2 (Aug 2023)) ist mit dem zota-Verfahren noch nicht eingespielt, obwohl es seit letzter Woche im RSS-Feed ist.

**Comment by jriedl** [comment]
Manuelles Ausführen auf nu und ub28 ergibt keine Auffälligkeiten, die aktuellen Artikel werden erzeugt - der hinterlegte Feed ist allerdings https://brill.com/view/journals/ijac/ijac-overview.xml. Im Log des Durchlaufs von letzter Nacht werden noch die Artikel der vorherigen Hefts als übersprungen aufgeführt, die finden sich im aktuellen Feed nun aber gar nicht mehr. Eventuell also einfach eine unglückliche Überschneidung hinsichtlich der Aktualisierung des ijac-overview-Feeds durch den Verlag, die erst nun unmittelbar stattgefunden hat. Einspielung heute Abend sollte abgewartet werden. Analog #2008, #2009.

**Comment by jriedl** [comment]
Wie es aussieht, wurden die drei neuen Asugaben gestern Abend eingespielt (vgl. auch #2008, #2009).

**Comment by IxKo** [comment]
Danke, die Hefte sind eingespielt.
Ich entwickle wohl langsam ein Talent, genau an solchen Überschneidungstagen ein Issue zu öffnen.
Ich schließe auch die anderen beiden.
