### ISSUE TITLE
OJS-Prio ISSN 2365-6565 Ethik und Gesellschaft

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#201]
Gilt für das halbautomatische Verfahren:
Sowohl im Single als auch beim Multidownload:
Die Bandangabe steht im Zoterofeld Ausgabe, sollte aber im Feld Band stehen. Die "0", die dort steht, kann verworfen werden.
Seitenangaben fehlen - dies wird wohl nur manuell zu lösen sein, da man sie dem PDF entnehmen muss
Beim Multidownload fehlt zusätzlich das Abstract
Das Abstract ist zweisprachig. Ich kann mich erinnern, dass wir da für eine ZS die bei Vandenhoeck erscheint, bereits eine Lösung haben.

**Comment by kdr154** [comment]
Bis auf die Seitenzahlen ist die Sache gelöst. Da die Seitenzahlenproblematik noch diskutiert wird, lasse ich das Issue noch offen.

**Comment by kdr154** [comment]
Wollen wir uns nicht darauf verständigen, es kommt ja immer wieder mal vor, dass man dann, wenn keine Seitenzahlen auf den Webseiten stehen, bzw. dass man sie den PDFs entnehmen muss, diese manuell einfügen muss? Dann würde ich dieses Issue schließen.

**Comment by shadeMe** [comment]
Ja, in solchen Fällen muss die Seitenanzahl händisch ergänzt werden.

**Comment by kdr154** [comment]
Seitenzahlen müssen in diesen Fällen manuell ergänzt werden
