### ISSUE TITLE
ISSN 2282-2828 | Archivio Giuridico Filippo Serafini (Torrossa) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2013]
#### URL
https://www.torrossa.com/en/resources/an/5570728

Artikel: https://www.torrossa.com/en/resources/an/5570739
  
#### Import-Translator
  Einzelimport:
Embedded Metadata.js

  
### Problembeschreibung
Könnte für diese Seite ein Translator entwickelt werden?

_(Koop)_

Gleiche Website und bereits nach neuem Translator angefragt: #2003

**Comment by IxKo** [comment]
Die Bandangabe müsste umgewandelt werden von römischen in arabische Ziffern.

Die Rezensionen "Recensioni" werden nicht automatisch erkannt, könnte das angepasst werden?

Der Permalink (Bsp. http://digital.casalini.it/10.53148/AG202302003) wird nicht importiert, stattdessen der "normale" Browser-Link (https://www.torrossa.com/de/resources/an/5570746).

Ist es gewollt, dass der Translator ein "r" weniger hat als der Plattformname?
(getestet mit ubtue_torossa.js)

**Comment by IxKo** [comment]
Bitte keine Issues schließen, die noch nicht geprüft sind.

Nun sieht fast alles gut aus, doch was jetzt verloren gegangen sind, sind die Autor:innen. Bei keinem Datensatz wird eine Person als Autor importiert.

**Comment by socheres** [comment]
> Bitte keine Issues schließen, die noch nicht geprüft sind.

War wohl ein Versehen. 	

> Nun sieht fast alles gut aus, doch was jetzt verloren gegangen sind, sind die Autor:innen. Bei keinem Datensatz wird eine Person als Autor importiert.

Hm...die Autorenangaben im Quelltext sind nun überall leer. Verstehe ich auch nicht warum sie verschwunden sind. 
<meta name="citation_author" content="" />

**Comment by IxKo** [comment]
Danke, scheint alles zu passen.
