### ISSUE TITLE
ISSN 0036-3537 | Salmanticensis (Dialnet) | Paralleltitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2015]
#### URL
https://dialnet.unirioja.es/servlet/articulo?codigo=9077514
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Dialnet.js

  
### Problembeschreibung
Es existiert ein englischer Paralleltitel "Theological Assessment of Separated Christians According to the Pre-Vatican II Council Theology" . Könnte dieser bitte mitimportiert werden?

**Comment by IxKo** [comment]
Danke, doch könnte der Paralleltitel bitte in das Pica-Feld 4002?
Momentan wird es als 4212 Übersetzung des Haupttitels: ... importiert und exportiert.

In diesem Fall ist es ein Paralleltitel, der adäquat zum Haupttitel auf der Titelseite angegeben wird, weswegen Feld 4002 korrekt ist.

**Comment by mara-spiess** [comment]
Paralleltitel sollte nun im Feld 4002 statt 4212 importiert werden.

**Comment by IxKo** [comment]
Danke, behoben!
