### ISSUE TITLE
ISSN 1533-791X | Logos (MUSE) | Supplement-Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2020]
#### URL
https://muse.jhu.edu/issue/51391
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Project MUSE.js

  
### Problembeschreibung
Bei dem Heft handelt es sich um ein Supplement. Es wurde jedoch als "normales" Heft eingespielt.

Als Sonderheft müsste es in Pica-4070 zusätzlich $nSupplement erhalten:

- 4070 $v26$j2023$a5$nSupplement$p5-6

In Marc: 
```
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">In: </subfield>
<subfield code="t">Logos : a journal of catholic thought and culture</subfield>
<subfield code="x">1533-791X</subfield>
<subfield code="w">(DE-627)326178740</subfield>
<subfield code="g">26 (2023), 5, Supplement, Seite 5-6</subfield>
</datafield>

```
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">26</subfield>
<subfield code="e">5</subfield>
<subfield code="f">Supplement</subfield>
<subfield code="h">5-6</subfield>
<subfield code="j">2023</subfield>
</datafield>
```

Kann das Supplement als solches erkannt werden?
Und dann in den Error-Daten landen, sodass es manuell geprüft und katalogisiert wird? Oder sollte ein anderer Weg gewählt werden?

-----
In den MARCXML-Format in der WinIBW sieht es nochmal anders aus:
Teils sind Daten in der Reihenfolge anders und teilst Datenfelder mit anderen Indikator gemischt.

```
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">Enthalten in</subfield>
<subfield code="t">Logos</subfield>
<subfield code="d">Baltimore, Md. : Johns Hopkins Univ. Press, 1997</subfield>
<subfield code="g">26(2023), 5, Supplement, Seite 5-6</subfield>
<subfield code="h">Online-Ressource</subfield>
<subfield code="w">(DE-627)326178740</subfield>
<subfield code="w">(DE-600)2041131-5</subfield>
<subfield code="w">(DE-576)266818943</subfield>
<subfield code="x">1533-791X</subfield>
<subfield code="7">nnns</subfield>
</datafield>

<datafield tag="773" ind1="1" ind2="8">
<subfield code="g">volume:26</subfield>
<subfield code="g">year:2023</subfield>
<subfield code="g">number:5</subfield>
<subfield code="g">supplement:Supplement</subfield>
<subfield code="g">pages:5-6</subfield>
</datafield>


<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">26</subfield>
<subfield code="j">2023</subfield>
<subfield code="e">5</subfield>
<subfield code="f">Supplement</subfield>
<subfield code="h">5-6</subfield>
</datafield>
```

**Comment by jriedl** [comment]
In diesem konkreten Fall kommt der überwiegende Teil der Angaben aus der Umleitung auf die Zitationsseite (z.B. https://muse.jhu.edu/view_citations?type=article&id=904235), wo dann die RIS-Informationen ausgewertet werden (	
<pre>
<p>TY  - JOUR
T1  - The State of Catholic Studies
A1  - MacKenzie, Raymond N.
JF  - Logos: A Journal of Catholic Thought and Culture
VL  - 26
IS  - 5
SP  - 5
EP  - 6
PY  - 2023
PB  - Logos: A Journal of Catholic Thought and Culture
SN  - 1533-791X
UR  - https://muse.jhu.edu/pub/82/article/904235
N1  - Volume 26, Number 5, Supplement 2023
ER  - 
</p>
</pre>
d.h. man käme nur über das Auswerten von N1 (was der RIS-Translator in "notes" umsetzt) an die Information heran und es garantiert natürlich niemand, dass das langfristig funktioniert.
Eine in den Muse-Translator integrierte Testumsetzung wäre:
 ```js
function isSupplement(item) {
	if (!item.notes)
	    return false;
	for (let note of item.notes) {
		 if (!note.hasOwnProperty("note"))
		     continue;
	     if (note["note"].match(/.*Supplement.*/i))
	         return true;
	}
	return false;
}
```
und anschließend könnte man die Issue-Angabe z.B. folgendermaßen ungültig machen, d.h. es sollte dann in den Errors landen:

```js
if (isSupplement(item))
    item.issue = item.issue + " (Supplement)";
```
Sieht testweise dann so aus:

![image](https://github.com/ubtue/DatenProbleme/assets/13135579/fc60a0a5-4615-473d-b06e-fef5d61d1728)

![image](https://github.com/ubtue/DatenProbleme/assets/13135579/46fa7f8e-9a61-4c8f-a15f-263a2428b9e2)

**Comment by socheres** [comment]
> d.h. man käme nur über das Auswerten von N1 (was der RIS-Translator in "notes" umsetzt) an die Information heran und es garantiert natürlich niemand, dass das langfristig funktioniert.

Wir sollten sowohl N1 aus RIS als auch die HTML als Fallback auswerten `<li class="designation"><span><a href="[/issue/51391](view-source:https://muse.jhu.edu/issue/51391)">Volume 26, Number 5, Supplement 2023</a></span></li>`

**Comment by jriedl** [comment]
Version mit Erkennung aus RIS nun auf nu. Lösung damit aber aktuell lediglich für die MUSE. Eine automatische Weiterverarbeitung im Harvester (Überführung in 936$f + 773 18) ist zu überlegen, falls die Konstellation mit dem Supplement häufig und eindeutig behandelbar auftritt.

**Comment by socheres** [comment]
Kannst du bitte deinen commit mit diesem Issue verlinken?

**Comment by jriedl** [comment]
ubtue/zotero-translators#264

**Comment by IxKo** [comment]
Beim Testen auf Nu mit Try URL scheint es kein Ergebnis anzuzeigen, was in den Errors landen könnte:

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/14544045-eb17-4558-a75c-0d20c1ad5b83)
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/f2cbc8b4-9500-41b9-a94e-b5b6532872f6)

**Comment by jriedl** [comment]
> und es garantiert natürlich niemand, dass das langfristig funktioniert.

Hier hat sich mittlerweile die ganze Seitenstruktur geändert und im Gegensatz zu oben/früher werden liefert https://muse.jhu.edu/view_citations?type=article&id=904235 die RIS-Angaben nun nicht mehr direkt, die sind jetzt als Fließtext ins Endnote-Feld gewandert: 
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/ca77f0a6-4e62-4432-8e56-2c4f70e47b82)
Bei allen anderen Zitationsformaten scheint die Supplement-Angabe zu fehlen. Kann dem hoffentlich in den nächsten Tagen nachgehen.

**Comment by jriedl** [comment]
Angepasste Version auf nu - vgl. z.B. tryURL für https://muse.jhu.edu/article/904236.

**Comment by IxKo** [comment]
Das sieht gut aus 
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/db40dc93-83e5-4e5c-9438-9ebcb1e5f5d5)

Durch die QA würde es dann in den Errors landen und es kann intellektuell bearbeitet werden.

**Comment by IxKo** [comment]
Ist mittlerweile auch auf ub28.
Falls nochmals ein solches Supplement kommen sollte, müsste es in den Errors landen.
