### ISSUE TITLE
ISSN 2504-5156 | Vulgata in Dialogue (OJS-Tue) | Sonderhefte

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2023]
#### URL
1. Sonderheft:
https://vulgata-dialog.ch/ojs/index.php/vidbor/issue/view/90

2. Sonderheft:
https://vulgata-dialog.ch/ojs/index.php/vidbor/issue/view/98
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung

Beide Sonderhefte werden im Zotero Harvesting als OF gekennzeichnet.
Da das erste schon länger in diesem Zustand ist, und durch die fehlenden Bandangabe in den Error-Dateien landen würde - wenn es denn aus dem OF-Status käme - habe ich es halbautomatisch erfasst.

Doch bisher sind die Daten als OF gekennzeichnet, wodurch ich auf der Oberfläche für alle Zs. nicht erkenne, dass bei der Zs. etwas nicht stimmt, da sie grün gekennzeichnet wird, und es dann nur durch systematische Prüfung mitbekomme.

Beim 2. Sonderheft gibt es zusätzlich ein ganz anderes Problem:
Die Aufsätze sind nicht als einzelne Daten auf der Seite aufgeführt, sondern nur das komplette Heft (welches im Zotero Harvester als OF gelandet ist). Hier muss ich allgemein klären, wie damit aus Katalogisierungssicht zu verfahren ist.

Aufgrund dieser Sonderfälle ist nun auch die Frage, ob die Zs. aus dem zota-Verfahren genommen werden soll.
Andererseits kann so etwas wohl auch bei jeder anderen Zs.-Publikation in Zukunft vorkommen.

**Comment by IxKo** [comment]
@socheres 
Soll hier auch schon ein neues Label gesetzt, weil es sich um eine OJS-Zs. aus der UB-Tübingen-Liste handelt? Oder in diesem Fall nicht, weil es eine theologische Zs. ist, die in ZEDER erfasst ist? Und falls ein Label gesetzt werden soll, wie sollte es dann heißen?

**Comment by thefass** [comment]
Unsere theologischen OJS Zss sollten in Zeder bleiben

**Comment by thefass** [comment]
> Beim 2. Sonderheft gibt es zusätzlich ein ganz anderes Problem:
> Die Aufsätze sind nicht als einzelne Daten auf der Seite aufgeführt, sondern nur das komplette Heft (welches im Zotero Harvester als OF gelandet ist). Hier muss ich allgemein klären, wie damit aus Katalogisierungssicht zu verfahren ist.

Das ist wirklich ganz schlecht. Müssen die m.E. nachkatalogisieren

**Comment by thefass** [comment]
> > Beim 2. Sonderheft gibt es zusätzlich ein ganz anderes Problem:
> > Die Aufsätze sind nicht als einzelne Daten auf der Seite aufgeführt, sondern nur das komplette Heft (welches im Zotero Harvester als OF gelandet ist). Hier muss ich allgemein klären, wie damit aus Katalogisierungssicht zu verfahren ist.
> 
> Das ist wirklich ganz schlecht. Müssen die m.E. nachkatalogisieren

Da war ich zu schnell, ohne mir das angeschuat zu haben. Das 2. Sonderheft ist ja eine Monographie (mit einzelnen Kapiteln des selben Autors und nicht mit Aufsätzen verschiedener Auoren) und müßte m.E, wie ein E-book katalogisiert werden

**Comment by socheres** [comment]
> @socheres Soll hier auch schon ein neues Label gesetzt, weil es sich um eine OJS-Zs. aus der UB-Tübingen-Liste handelt? Oder in diesem Fall nicht, weil es eine theologische Zs. ist, die in ZEDER erfasst ist? Und falls ein Label gesetzt werden soll, wie sollte es dann heißen?

Bitte vorerst nur für die "UB-Zss." ohne ZEDER-Eintrag neues Label "UBZss" vergeben (Vorschlag).
Zu der Sondernummer: @jriedl Wenn die Artikel der Sondernummer den Status "Warning"(gelb) hätten, könnte man sie auf ub28 gut erkennen und dann auch manuell katalogisieren > "Deliver manually" in der Spalte "actions". Wäre das möglich, wenn ich den Translator für diese Zss. so anpasse, dass bei Sondernummern ein bestimmter Wert z.B. im Feld "notes" hinzugefügt wird?

**Comment by socheres** [comment]
Lese gerade in Issue #2020  @IxKo hatte schon diese Idee und @jriedl der Umsetzungsvorschlag 😄 🎉 
> Kann das Supplement als solches erkannt werden?
Und dann in den Error-Daten landen, sodass es manuell geprüft und katalogisiert wird? Oder sollte ein anderer Weg gewählt werden?

**Comment by socheres** [comment]
Hier müsste zusätzlich zur Lösung in https://github.com/ubtue/DatenProbleme/issues/2020#issuecomment-1785499498 eine fiktive Band- oder Heftnummer vergeben werden. Z.B. "sondernummer 1"

**Comment by coeh** [comment]
Wie das gelöst wird, wäre auch für OJS-Italien interessant, wo sich das Problem der monographischen Supplemente ebenfalls stellt (wenngleich möglicherweise in umgekehrter Reihenfolge, d.h. Supplemente werden erst katalogisiert und kommen dann in OJS). Über das dortige Problem ist @IxKo auch orientiert; für mich wäre es sehr hilfreich, wenn wir alle zusammen darüber im Gespräch bleiben.

**Comment by jriedl** [comment]
Ich versuche aktuell nur noch einmal die einzelnen Aspekte zusammenzufassen/auseinanderzuhalten: Auftreten kann der Fall einer 
 - _Falscheinspielung_ (vgl. #2020) und einer 
 - _Nichteinspielung_ (vgl. der Fall hier, da nie der Zustand erreicht wird, in dem alle notwendigen bibliographischen Informationen vorliegen, bleibt dauerhaft der OF-Status erhalten). 
 
Alle Fälle automatisiert zu behandeln, scheint nicht realistisch, wüschenswert wäre, wenn zumindest erkannt würde, dass ein weiteres Heft vorliegt, das einer manuellen oder sonstigen Behandlung bedarf. Eine Erkennung von Supplementen/Sonderheften ist zwar theoretisch im Translator möglich, praktisch besteht aber das Problem, dass das erstens für jeden Translator gesondert angepasst werden müsste und es keinerlei Standard/Garantie dafür gibt, wie das hinterlegt wird, d.h. im Prinzip kann sich das von Zeitschrift zu Zeitschrift (selbst mit dem gleichen Translator) unterschiedlich sein und sich auch beliebig unangekündigt ändern. Deshalb stellt sich die Frage, ob sich ein Ansatz finden lässt, der 1.) stabil ist 2.) skaliert.

**Comment by jriedl** [comment]
Lösungsvorschlag für den Fall der Nichteinspielung hier: Das Kriterium für OF (keine Band/Heftangabe) gilt nicht mehr für Records, die über Seitenangaben verfügen - diese sollten dann von der "normalen" QS erkannt werden und so leichter auffallen.

**Comment by socheres** [comment]
OF-Artikel sollten noch keine Seitenangaben haben. Z.B. https://journals.sagepub.com/toc/CRR/0/0 Die Frage ist, ob das für alle OF-Artikel gilt? Wenn ja, sollten wir das wie von @jriedl vorgeschlagen umsetzen.

**Comment by IxKo** [comment]
Hier ist ein OF-Beispiel mit Seitenangaben (1-37, wird so nach Zotero importiert): 
https://www.tandfonline.com/doi/full/10.1080/14788810.2023.2211506?scroll=top&needAccess=true

**Comment by jriedl** [comment]
Das scheint allerdings keine zotaut-Zeitschrift zu sein und auch issue und volume werden hier (falsch) mitgeliefert:
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/0c7f1006-ac58-4d69-a4f6-d66af73e2b5e)
Der Artikel würde ja ebenfalls in den Errors hängenbleiben. Ist das ein systematisches Problem von T&F?

**Comment by jriedl** [comment]
Nachtrag: Solche Fälle könnten wir versuchen, translatorseitig abzufangen.

**Comment by socheres** [comment]
> Nachtrag: Solche Fälle könnten wir versuchen, translatorseitig abzufangen.

Summa summarum gibt es in diesem Fall keine Lösung, die "stabil und skalierbar" ist. Wichtiger ist, dass die Pseduo-OF-Artikel (=Sonderhefte ohne Band- und Heftnummer) in den Erros landen und erkannt werden. Daher sollten wir das Kriterium für OF global ändern. (OF = keine Band- und Heftnummer && Seitenangaben). Wenn nach dieser Änderung fälschlicherweise echte OF-Artikel in den Errors-Datensätzen auftachen, dann lösen wir das Problem von Fall zu Fall translatorseitig. @jriedl ist der Code für die Bedingung OF hardcodiert oder kann die Änderung auch von uns vorgenommen werden?

**Comment by jriedl** [comment]
> > Nachtrag: Solche Fälle könnten wir versuchen, translatorseitig abzufangen.
> 
> Summa summarum gibt es in diesem Fall keine Lösung, die "stabil und skalierbar" ist.

Wir erkennen zumindest durch eine geringfügige Anpassung an einer einzigen Stelle eine ganze Klasse Fällen.  Das von @IxKo erwähnte Beispiel liefert inkonsistente Daten, so etwas sollte möglichst nahe an der Quelle behoben werden, deshalb der Vorschlag mit dem Translator. Die OF-Erkennung ist Teil des Validierungsprogramms und damit hardcodiert. 

Eine angepasste Version findet sich nun auf nu.

**Comment by IxKo** [comment]
Ich weiß nicht genau wie ich hier testen soll.
Ich habe in Nu den ersten Link mit TRY URL getestet und heraus kam dies:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/a4d8b419-711e-4bb4-83f7-096d4eed9cca)

Wenn ich es nicht falsch deute, wurde alles als OF erkannt?
Wie müsste es denn aussehen, wenn alles in den Error-Dateien landen würde - müsste die Anzahl der Datensätze dann unter "Skipped (exclusion filter): 0" angezeigt werden?

**Comment by jriedl** [comment]
Das ist tatsächlich durch direktes Aufrufen in Oberfläche nicht testbar, da die Änderung im Validator ist und also eine Testzeitschrift notwendig wäre, die sich analog verhält und dann ein entsprechender abendlicher Durchlauf abgewartet werden muss. Falls hier kein Testfall einfach zu identifizieren ist, müssten wir es in nächster Zeit einfach so auf ub28 einspielen.

**Comment by IxKo** [comment]
Sollte sich etwas geändert haben?
Die betroffenen Heft-Beiträge sind weiterhin als OF auf ub28 gekennzeichnet und nicht in als Errors.

**Comment by jriedl** [comment]
Das dürfte erst sichtbar werden, wenn ein einschlägigeer OF-Record das OF-Rücksetz-Intervall erreicht hat und erneut heruntergeladen wird.

**Comment by jriedl** [comment]
Auf nu findet sich nun eine Version, die Records dann nicht mehr als OF kennzeichnet, wenn 936$h vorhanden ist und einer 1-4 stelligen Seite oder einem Seitenbereich entspricht. Irgendwelche Identifier in 936$h sollten damit nicht mehr zu einer Aufnahme in die Errors. führen. Für Einzelfälle ist ja bereits bekannt, dass auch bei OF-Artikeln plausible Seitenzahlen hinterlegt werden. Vielleicht lässt sich hier aber in den nächsten Tagen abschätzen, ob die Fehlerkennungsquote im Verhältnis zur ursprünglichen Zielsetzung noch tolerabel ist.

**Comment by IxKo** [comment]
Scheinbar ist der Stand nun auch auf ub28.
Mehrere Taylor&Francis-Zs. haben nun OF-Artikel in den Error-Dateien gelistet (bspw. "Politics, Religion and Ideology" (ISSN 2156-7697, "Mental health, religion and culture" (ISSN  1469-9737), "Journal of beliefs & values" (ISSN 1469-9362)).

Auch bei einer SAGE-Zs. finden sich nun zwei OF-Artikel in den Errors: "Journal of cross-cultural psychology" (ISSN 1552-5422).

Daher bitte die Erkennung von OF-Artikeln wieder rückgängig machen.

**Comment by jriedl** [comment]
> Scheinbar ist der Stand nun auch auf ub28.

Da die Implementierung bereits mehrere Monate zurückliegt, ist dieser Stand im Rahmen der regulären Updates auch auf das Produktivsystem gewandert.

> Daher bitte die Erkennung von OF-Artikeln wieder rückgängig machen.

Dann sind wir aber eben wieder am Ausgangstand von November. Bringt nochmals die Frage auf, ob gerade für die großen Verlage die Auswertung der Website ein langfristig stabiles Verfahren ist und wir nicht "im Kreis" entwickeln. Denkbar wäre noch, dass man die hier umgesetzte Funktionalität über eine Direktive in Config-Datei nur für ausgewählte Zeitschriften freischaltet, bei denen sie absehbar den gewünschten Effekt hat.

**Comment by IxKo** [comment]
Fakt ist, über 50 IxTheo-Zs. sind nun auf ub28 gelb.
Einige Stichproben ergaben, dass es mit dieser Problematik zu tun hat. Demnach ist der momentane Zustand nicht die Lösung.

Die Vulgata in Dialogue erscheint einmal im Jahr. Entweder man entscheidet sich, sie aus dem zota-Verfahren zu nehmen, oder man setzt sie zurück ins Test-Verfahren und versucht es mit Ihren Vorschlag, spezifische OF-Erkennungen nur für ausgewählte Zs. über die conf zu definieren.

**Comment by jriedl** [comment]
Auf nu und ub28 findet sich nun eine angepasste Version, bei der in `zotero_harvester.conf` die Direktive `pages_not_online_first` unterstützt wird, mit der auf Zeitschriftenebene die angepasste OF-Logik explizit aktiviert werden kann. Es wird dann ein Pseudo-Tag "PNO" gesetzt, das im Rahmen der Validierung ausgewertet wird. Standardmäßig hat das Vorhandensein von Seitenangaben nun keinen Einfluss mehr auf die OF-Auszeichnung. Für "Vulgata in Dialogue" ist das Flag bereits in der Config gesetzt und sollte heute Abend im Rahmen des automatischen Updates eingespielt werden.

**Comment by IxKo** [comment]
Vielen Dank, nun sind nur noch 2 Zs. gelb.
Eine davon scheint noch Probleme mit der OF-Erkennung zu haben ("Rural Theology" ISSN 2042-1273). 
Ich würde sie noch beobachten und ansonsten ein neues Issue für sie öffnen.

**Comment by IxKo** [comment]
Noch als Ergänzung:
Ich habe das monografische Sonderheft und ein Artikel aus dem anderen Sonderheft auf ub28 einzeln resettet und heute ist es wie gewünscht in den Errors gelandet.
Ich setze sie nun auf manually delivered, da sie schon manuell erfasst worden sind.
