### ISSUE TITLE
ISSN 1860-8213 | bildungsforschung (OJS) | Band/Heft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2029]
#### URL
https://bildungsforschung.org/ojs/index.php/bildungsforschung/article/view/175
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Jorunal Systems Standard.js

  
### Problembeschreibung

Die Heftzählung "1" wird in das Feld für die Band-Angabe importiert, müsste jedoch in das Feld "Ausgabe"

**Comment by socheres** [comment]
Retrospektive Band- und Heftzählung in den strukturierten Daten unterschiedlich, daher intellektuell prüfen und erfassen (siehe eMail 27.11.2023 at 10:54)

**Comment by IxKo** [comment]
Ok, ich schließe das Issue dann später, da ich es in ZEDER vermerken möchte.

@thefass Wissen Sie, wann die ZEDER-Instanz für die UB-Zs. fertig ist?
Solche Zs.-bezogenen Hinweise zur Bearbeitung dokumentiere ich gerne an einen zentralen Ort.

**Comment by thefass** [comment]
> @thefass Wissen Sie, wann die ZEDER-Instanz für die UB-Zs. fertig ist?

Leider kann ich dazu noch keine Aussage Treffen.

**Comment by IxKo** [comment]
Ok, dann schließe ich das Issue.

**Comment by thefass** [comment]
Nach Auskunft des ITlers kann die neue Instanz nicht mehr auf dem alten Server aufgesetzt werden, der neue Server ist in Vorbereitung
