### ISSUE TITLE
ISSN 2272-9011 Études théologiques et religieuses Abstract Halbautomatisches Verfahren

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#203]
Hier gibt es die Abstracts in zwei Sprachen. Übertragen wird aber nur eines. Gut wäre, wenn beide mitkämen.

**Comment by kdr154** [comment]
Immer noch nur eines

**Comment by shadeMe** [comment]
Funktioniert wie erwartet - https://www.cairn.info/revue-etudes-theologiques-et-religieuses-2005-4-page-525.htm?contenu=resume. Bitte den lokalen Translator aktualisieren.

![Screenshot_20190619_104019](https://user-images.githubusercontent.com/214450/59750173-a5ff0900-927e-11e9-9e34-9a22f8c45023.png)

**Comment by kdr154** [comment]
Gelöst
