### ISSUE TITLE
ISSN 0098-9444 | Biblical archaeology review | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2030]
#### URL
https://library.biblicalarchaeology.org/issue/fall-2023/
  
#### Import-Translator
Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung

Wäre es möglich für diese Seite einen Translator zu schreiben?

Ich vermute Seitenangaben sind keine in den Metadaten vorhanden?

**Comment by socheres** [comment]
Ja, keine Seitenangaben und keine Keywords. Wenn Sie es trotzdem wünschen, kann ich einen Translator schreiben.

**Comment by IxKo** [comment]
Ja, bitte. 
Die Seite ist die offizielle Verlagsseite und wir katalogisieren momentan über EBSCO an die Print-Aufnahme.

**Comment by IxKo** [comment]
Danke, die Jahresangabe fehlt noch.

**Comment by IxKo** [comment]
Danke, Jahresangabe kommt nun mit.
