### ISSUE TITLE
ISSN 0022-0469 | The journal of ecclesiastical history (Cambridge) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2033]
#### URL
https://doi.org/10.1017/S0022046923000593
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Cambridge Core.js

  
### Problembeschreibung

Es werden Keywords übernommen, die nicht existieren bzw. sich nicht auf den Text beziehen.
Sie werden als "citation_keywords" im Quellcode geführt, sind da aber wohl fälschlicherweise vom Verlag enthalten.

Es scheint sich dabei um das Abkürzungsverzeichnis der Referenzen zu handeln.

Daher bitte den Import-Translator  anpassen, sodass keine Keywords importiert werden. 

(Problem wurde von @IxGe gemeldet)

**Comment by IxGe** [comment]
aus meiner Sicht sind sie zu Recht in den citation keywords - nur sollten diese grundsätzlich nicht ausgewertet werden, da es sich um Stichwörter aus dem Literaturverzeichnis handelt, genauer gesagt aus dem Abkürzungsverzeichnis

**Comment by IxKo** [comment]
Zudem habe ich noch eine zusätzliche Frage:
5 der 109 betroffenen Datensätze haben das Abrufzeichen "zota"
Der gemeldete Datensatz als Beispiel von IxGe ebenso, weshalb ich erst davon ausging, es sei eine zota-Zs. Ist sie aber nicht.

Nun wollte ich mir die gelieferte xml-Dateien ansehen (alle sind IxTheo#2020-02-28#..), es findet sich keine xml-Datei dazu im Default-Ordner (W:).

Beispiel: IxTheo#2020-02-28#26D568C5B0B582EBB3F0666D7674131261E02DC5
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/7176705b-a7a5-4988-8690-a0f93f04c726)

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/0686bb1e-98a1-4dc1-8af7-41e173e416b0)

**Comment by jriedl** [comment]
Das Default-Verzeichnis geht gar nicht so weit zurück. In Default_Test gibt es `zotero_ixtheo_200228_001.xml`, darin scheinen die Records mit diesen Hashes vorhanden. Bleibt natürlich die Frage, auf welchen Wegen diese Datei die Inhalte in die Produktivdatenbank gekommen sind.

**Comment by mara-spiess** [comment]
Die Keywords sollten nun im ZotKat Verfahren nicht mehr importiert werden.

**Comment by IxKo** [comment]
Danke, passt!
