### ISSUE TITLE
ISSN 2293-7374 | Renaissance and Reformation (OJS) | Verfasser:innen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2035]
(gemeldet von @IxTheoEg)
#### URL
https://jps.library.utoronto.ca/index.php/renref/issue/view/2781
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Es werden keinerlei Verfasser:innen importiert, bei keinem Eintrag.

**Comment by IxKo** [comment]
Danke, Personennamen kommen nun mit.

Allerdings kommt auch die Bezeichnung "applicable, Author not" mit:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/bb2e4138-5cff-4d2d-ae2c-d83ae96cad04)

Kann das angepasst werden? Oder würde auch die Enhancement Map [author_name_blacklist.txt](https://github.com/ubtue/zotero-enhancement-maps/blob/master/author_name_blacklist.txt) greifen?

Falls nicht, wird ein Vermerk in ZEDER für die Bearbeitung gemacht.

**Comment by mara-spiess** [comment]
Einträge ohne AutorIn sollten nun ohne falsche Angaben importiert werden.

**Comment by IxKo** [comment]
Behoben, danke!
