### ISSUE TITLE
ISSN 2161-8534 | American catholic studies (MUSE) | Errors DOI

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2037]
#### URL
https://muse.jhu.edu/issue/51204
  
  
### Problembeschreibung

Das Heft befindet sich schon lange Zeit in den Error-Daten, da bei MUSE abgewartet werden muss bis der DOI vorhanden ist.
Der DOI ist nach meinen letzten Beobachtungen mindestens seit letzten Donnerstag vorhanden.

Die Artikel landen jedoch weiterhin in den Errors wegen Feld 024 (DOI)

**Comment by jriedl** [comment]
Das liegt daran, dass der ubtue_Project MUSE-Translator noch von einer anderen Seitenstruktur (mit durchnummerierten Tabs) ausgeht und hier versucht RIS-Informationen abzurufen. Deshalb kommt die DOI nicht mit. Da für diese Zeitschrift Embedded Metadata vorhanden ist, findet sich auf nu nun eine angepasste Version des Translators, die Ihre Grunddaten mittels EM anstatt RIS bezieht. Produktiv eingesetzt werden sollte diese jedoch nur, wenn vorher sichergestellt ist, dass bei allen MUSE-Zeitschriften die Seitenstruktur entsprechend geändert hat.

**Comment by IxKo** [comment]
@jriedl 
Wie genau stelle ich das als Laie für die restlichen 14 MUSE-Zs. im vollautomatischen Zotero-Verfahren fest?
Müsste ich auf Nu bei jeder Zs. eine URL mit DOI testen und schauen, ob der DOI mitkommt?

**Comment by jriedl** [comment]
Eine Sache ist mir noch aufgefallen: Für [Cross currents : the journal of the Association for Religion and Intellectual Life](http://muse.jhu.edu/feeds/latest_articles?jid=784) sind gestern heruntergeladene Artikel an der Regexprüfung für die Autoren gescheitert, obwohl sie eigentlich plausibel aussehen. Ich gehe dem nochmals nach.

**Comment by jriedl** [comment]
> Eine Sache ist mir noch aufgefallen: Für [Cross currents : the journal of the Association for Religion and Intellectual Life](http://muse.jhu.edu/feeds/latest_articles?jid=784) sind gestern heruntergeladene Artikel an der Regexprüfung für die Autoren gescheitert, obwohl sie eigentlich plausibel aussehen. Ich gehe dem nochmals nach.

Da ist auf Zeitschriftenebene eine Regel hinterlegt, diese enthält am Anfang ein Leerzeichen (erkennbar am Tooltip).

**Comment by IxKo** [comment]
> > Eine Sache ist mir noch aufgefallen: Für [Cross currents : the journal of the Association for Religion and Intellectual Life](http://muse.jhu.edu/feeds/latest_articles?jid=784) sind gestern heruntergeladene Artikel an der Regexprüfung für die Autoren gescheitert, obwohl sie eigentlich plausibel aussehen. Ich gehe dem nochmals nach.
> 
> Da ist auf Zeitschriftenebene eine Regel hinterlegt, diese enthält am Anfang ein Leerzeichen (erkennbar am Tooltip).

Danke, ich habe die individuelle Regex bei 100/700 gelöscht. Sie existiert global.
Die Zs. "Cross Currents" befindet sich noch nicht im vollautomatischen Zotero-Verfahren bzw. auf ub28, demnach hat es nicht den Live-Betrieb betroffen.

**Comment by jriedl** [comment]
> Die Zs. "Cross Currents" befindet sich noch nicht im vollautomatischen Zotero-Verfahren bzw. auf ub28, demnach hat es nicht den Live-Betrieb betroffen.

War auch nur im Kontext des MUSE-Tests gedacht.

**Comment by IxKo** [comment]
> Vielen Dank für die Überprüfung. Das sind ja beides RSS-Zeitschriften, d.h. es wird davon ausgegangen, dass der Aufruf des Translators einzelne Artikel bekommt. Das ist bei tryURL mit einer Heftseite nicht der Fall (Translator - multiple). Wenn man einzelne Artikel mit tryURL probiert, scheint es sich wie gewünscht zu verhalten.

Das war aber nicht immer so. Ich meine, früher öfters mit TRY URL ganze Heft-Seiten getestet zu haben.

>Dass "The Thomist" als RSS nicht funktioniert hat, könnte mit der großen Anzahl der insgesamt beim Test heruntergeladenen Artikel zusammenhängen. Aktuell ist ein tryRSS zwar langsam, aber es kommt nach 100s ein Ergebnis mit 18 Records.

Danke, beim 3. Anlauf heute hat es bei mir auch geklappt.

Ich hatte heute aber auch bei MUSE zwei Abfragen "Ich bin kein Roboter". Daran hätte es auch noch liegen können.
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/4dce8cd1-0e27-41f9-8d28-80b5492aeafd)

Ansonsten scheint nun alles erstmal zu laufen wie es soll, danke.
