### ISSUE TITLE
ISSN 0003-3286 | Anglican Theological Review (SAGE) | OF in Errors

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2038]
#### URL
https://doi.org/10.1177/00033286231209714
 
  
### Problembeschreibung

Dieser sowie weitere Online First Artikel landen in den Errors statt als OF auf ub28 gekennzeichnet zu werden
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/9824790c-b164-4c91-b3a5-7a3a4916cdab)

**Comment by jriedl** [comment]
vgl. #2023 - hier haben wir die Regel eingeführt, das OF nicht OF ist, wenn Seitenangaben vorhanden sind, d.h 936$h existiert: z.B. 7F0807578CED13281DBB097D8D60FE4307B6DF70
```<datafield tag="936" ind1="u" ind2="w">
<subfield code="h">00033286231209714</subfield>
<subfield code="j">2023</subfield>
</datafield>
```
Diesen Fall hier könnte man eventuell noch durch eine Mustererkennung abfangen, bei #2039 wird es schwierig.

**Comment by jriedl** [comment]
vgl. auch #2039 - scheint bislang wieder auf die Füße gefallen zu sein.

**Comment by IxKo** [comment]
Ja, danke.
Es scheint auch nichts eingespielt worden zu sein, was nicht hätte eingespielt werden sollen.
