### ISSUE TITLE
ISSN 1469-2961 | Asian philosophy (T & F) | Latest Article in Errors

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2039]
#### URL
https://doi.org/10.1080/09552367.2024.2271663
  
  
### Problembeschreibung

Der Latest Article wird nicht als OF auf ub28 gekennzeichnet sondern landet in den Error-Daten.

Betrifft auch andere T&F-Zs.

**Comment by jriedl** [comment]
vgl. #2023, #2038: OF gilt aktuell nicht als OF, wenn Seitenangaben vorhanden, allerdings C47DEE589F16B6CA591D64785241C9043D62F32C:
```<datafield tag="936" ind1="u" ind2="w">
<subfield code="h">1-11</subfield>
<subfield code="j">2023</subfield>
```

**Comment by IxKo** [comment]
Der Fall hat sich mittlerweile von selbst gelöst, da er zwischenzeitlich kein OF-Artikel mehr ist und eingespielt wurde.
