### ISSUE TITLE
ISSN 2406-4726 Nouvelle Revue Théologique Abstract und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#204]
Hier liefert der Translator beim halbautomatischen Verfahren weder Abstracts (in diesem Fall wieder zweisprachig), noch die Keywords

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift gibt's keine DOIs auf der Webseite der Artikel (z.B https://www.cairn.info/revue-nouvelle-revue-theologique-2019-2-page-244.htm).

**Comment by shadeMe** [comment]
Gefixt. Bitte den Translator "Cairn.info" aktualisieren.

**Comment by kdr154** [comment]
gelöst
