### ISSUE TITLE
ISSN 2375-5814 | The Asbury Journal | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2040]
#### URL
https://place.asburyseminary.edu/asburyjournal/vol78/iss2/3/
  
#### Import-Translator
Nur Einzel-Import möglich:
ubtue_Asbury Journal.js

  
### Problembeschreibung

Der Import bricht ab und versucht mit den COinS-Translator zu importieren:

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/e1ca6a59-111c-4c5b-99cb-c517404d63a7)

(gemeldet von @IxTheoEg)

**Comment by IxKo** [comment]
Danke, behoben.

**Comment by IxTheoEg** [comment]
Guten Morgen Andrea,

danke für die Info.

Sehen wir uns morgen und geht es dir wieder besser?

Einen schönen Tag und

liebe Grüße

Martina E.
------
Eberhard Karls Universität Tübingen
Universitätsbibliothek
Fachinformationsdienste (FID) – IxTheo
Wilhelmstr. 32 · 72074 Tübingen · Germany
Telefon +49 7071 29-74693
***@***.******@***.***>
Home-Office (Montag, Dienstag und Donnerstagnachmittag): 07032 1230727
------



Von: IxKo ***@***.***>
Gesendet: Dienstag, 19. Dezember 2023 08:27
An: ubtue/DatenProbleme ***@***.***>
Cc: Egeler, Martina ***@***.***>; Mention ***@***.***>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2375-5814 | The Asbury Journal | Translator-Abbruch (Issue #2040)


Danke, behoben.
