### ISSUE TITLE
ISSN 1018-1539 | Österreichisches Religionspädagogisches Forum (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2041]
#### URL
https://oerf-journal.eu/index.php/oerf/article/view/384
IxTheo#2023-11-15#9E10C6DB64CF419E080EC7AEB33572D5751B6765
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die ORCID-Angabe wird nicht übertragen.

Auch bei zota-Einspielungen nicht.

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Danke, ORCID kommt auf nu mit

**Comment by IxKo** [comment]
> Danke, ORCID kommt auf nu mit

Kommt aber noch nicht auf ub28 mit und auch noch nicht im halbautomatischen Zotero-Verfahren.

**Comment by jriedl** [comment]
Aktueller Stand nun auf ub28.

**Comment by IxKo** [comment]
> https://oerf-journal.eu/index.php/oerf/article/view/384

Danke, ORCID kommt nun auch auf ub28 mit.

**Comment by mara-spiess** [comment]
Meinen Tests nach funktioniert es mittlerweile auch im halbautomatischen Verfahren, @IxKo könntest du das nochmal überprüfen?

**Comment by IxKo** [comment]
Ja, klappt nun auch im halbautomatischen Verfahren!
