### ISSUE TITLE
ISSN 1741-2005 | New blackfriars (Wiley) | Hochgestellte Zahl als Titelteil

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2042]
#### URL
https://doi.org/10.1111/nbfr.12870
IxTheo#2023-11-13#FE01054C9203C382D1E790145203BB13AC52A02C
  
  
### Problembeschreibung
Die Fußnoten-Zahl am Titel-Ende wurde miteingespielt. Sie gehört nicht zum Titelbestandteil.
Könnte der Translator so angepasst werden, dass so etwas nicht passiert? 

Im halbautomatischen Zotero-Verfahren wird sie nicht importiert.

**Comment by jriedl** [comment]
Aktuell nicht reproduzierbar:
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/24087ee4-a64b-40c6-8f5c-fb1aba73a6e6)

**Comment by IxKo** [comment]
Ok, danke, dann hat sich das Problem wohl zwischenzeitlich selbst gelöst.
