### ISSUE TITLE
ISSN 1467-9418 | Reviews in religion and theology (Wiley) | Liste Books reviewed

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2045]
#### URL
https://doi.org/10.1111/rirt.14287
IxTheo#2023-11-24#86E69091604DF7C10A197AE6C714CF62BAB5619E 

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Wiley Online Library.js
  
### Problembeschreibung

Der Datensatz wurde mit 1131 Rezension eingespielt.
Es handelt sich jedoch nicht um eine Rezension, sondern lediglich eine Liste von Werken.

Bitte sowohl im halb- als auch vollautomatischen Verfahren anpassen.

**Comment by jriedl** [comment]
Der Titel des Artikels ist "Books Reviewed", Durch Beachtung der 'word boundary' wird es nun durch den Translator kein Rezensionstag mehr erzeugt. Aktuelle Version auf nu. Allerdings ist "Books Reviewed" auch ein machendes Pattern des `zotero_review_regex`  in `zotero_harvester.conf`. Ist wohl eine Abwägungssache, ob man das herausnehmen soll.

**Comment by IxKo** [comment]
In der conf taucht es soweit ich erkennen kann nicht auf, oder ich stehe eventuell auf dem Schlauch:
`zotero_review_regex  = (?i)^(Book\s+Reviews?|Recensiones|Recensions|Études\scritiques|Boekbesprekingen|Comptes\srendus|Rezension\szu|Shorter\sReviews)`

Es ist jedoch Bestandteil für die `zotero_notes_regex`.

**Comment by jriedl** [comment]
Nein, sorry, mein Fehler. Damit erfolgt mit dem aktuellen Stand  für obigen Artikel keine Rezensionsauszeichnung in 655 mehr:
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/ffd5780d-4b69-43f5-a963-cc79d214b832)

**Comment by IxKo** [comment]
Danke, wird auf Nu nicht mehr als Rezension erkannt. Bitte auf ub28 übertragen.

Im halbautomatischen wird es noch als Rezension gekennzeichnet.

**Comment by jriedl** [comment]
Aktueller Stand ist auf ub28.

**Comment by IxKo** [comment]
Danke, behoben.

**Comment by IxKo** [comment]
Wird aber noch im halbautomatischen Verfahren als Rezension importiert.
