### ISSUE TITLE
ISSN 1552-146X | The Hastings Center report (Wiley) | Artikel nicht in Einspielung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2047]
#### URL
https://doi.org/10.1002/hast.1508
  

### Problembeschreibung

Der Aufsatz wurde nicht eingespielt. Mit TRY RSS auf ub28 wird er auch nicht aufgeführt.
Womöglich ist er nicht im RSS enthalten gewesen?
Dass es dem OF-Zeitfenster geschuldet sein könnte, würde ich ausschließen, da die restlichen Aufsätze des Heftes vor über einen Monat eingespielt worden sind.

Ich habe den Aufsatz manuell nacherfasst.

**Comment by jriedl** [comment]
Im in der zotero_harvester.conf hinterlegten RSS-Feed für die Zeitschrift wird der Artikel nicht aufgeführt.

**Comment by IxKo** [comment]
Ok, dann schließe ich. Nacherfasst wurde er schon.
