### ISSUE TITLE
ISSN 2627-6062 | Journal of Ethics in Antiquity and Christianity (OJS-Tue) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2048]
#### URL
https://jeac.de/ojs/index.php/jeac/article/view/1252
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung
Die ORCID-Angabe wird falsch importiert und dementsprechend auch exportiert:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/c4d0e7de-0aa2-40c9-9178-7790d961aa1d)

**Comment by Martina-Dae** [comment]
Tritt der Fehler noch auf?

**Comment by IxKo** [comment]
> Tritt der Fehler noch auf?

Ja, der Fehler tritt noch auf.
![image](https://github.com/user-attachments/assets/a6892705-8b3e-46af-b130-b7c0eb0f4b09)

**Comment by Martina-Dae** [comment]
komisch...hier kommt das richtig raus:
![image](https://github.com/user-attachments/assets/3d56ea14-72fd-48ef-8e19-cea1af0d981b)
Ich schaue es mir nochmal an

**Comment by IxKo** [comment]
Normalerweise müsste die ORCID-Info so aussehen:
`orcid:0000-0003-1595-7991 | Fergus Ryan | taken from website` (https://doi.org/10.25365/exf-2023-2-2)

**Comment by Martina-Dae** [comment]
Ach, dann fehlt noch der Autor. Danke!

**Comment by Martina-Dae** [comment]
Funktioniert es jetzt?

**Comment by IxKo** [comment]
Es hat sich leider noch nichts geändert.
Mein Translator ubtue_Open Journal Systems Standard.js wurde in meinem Verzeichnis zuletzt am 12.08. geändert:
![image](https://github.com/user-attachments/assets/fc6ecd0a-5561-498e-a3cc-9898684099b5)
Eventuell liegt es daran und die Translator-Anpassung ist bei mir noch nicht angekommen.

**Comment by Martina-Dae** [comment]
@mara-spiess Kannst du die Verzeichnisse bei Gelegenheit aktualisieren? Sorry...

**Comment by socheres** [comment]
Die Verzeichnisse wurden von mir aktualisiert.

**Comment by IxKo** [comment]
Danke, der Fehler ist behoben!
