### ISSUE TITLE
ISSN 1743-0623 Fieldwork in Religion Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#205]
Verstehe nicht, warum das System beim halbautomatischen Verfahren nicht auf den equinox-Translator zurückgreift, sondern den OpenJournalSystem Translator verwendet.

**Comment by shadeMe** [comment]
Anscheinend haben sie die URL der Webseite ein bisschen geändert, somit kann der Equinox-Translator sie nicht mehr erkennen. Ich passe den Translator entsprechend an.

**Comment by kdr154** [comment]
Gelöst
