### ISSUE TITLE
ISSN 2195-9773 | Philosophy, Theology and the Sciences (Mohr Siebeck) | LF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2050]
#### URL
https://www.mohrsiebeck.com/artikel/polarization-and-compromise-101628ptsc-2023-0004?no_cache=1
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Mohr Siebeck.js

  
### Problembeschreibung
Der Artikel ist frei zugänglich, doch die freizugänglichen Artikel werden noch nicht automatisch als LF gekennzeichnet.
Ist es möglich, das zukünftig zu ändern?

**Comment by mara-spiess** [comment]
related to https://github.com/ubtue/DatenProbleme/issues/2143

**Comment by mara-spiess** [comment]
Jetzt sollten auch die Open Access Artikel korrekt gekennzeichnet werden.

**Comment by IxKo** [comment]
Passt, danke!
