### ISSUE TITLE
ISSN 2269-479X | Revue d'Histoire et de Philosophie religieuses | Translator-Fehler

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2051]
#### URL
https://classiques-garnier.com/revue-d-histoire-et-de-philosophie-religieuses-2023-4-103e-annee-n-4-varia-penser-plus-imaginer-mieux.html
  
#### Import-Translator
  Einzelimport:
ubtue_RHPR.js	

  
### Problembeschreibung
Beim Import (nur Einzelimport wird angeboten) erscheint eine Fehlermeldung, es wird dennoch etwas importiert.
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/e3afdfb1-044a-4eda-8a0f-69ba8c88cff4)

Allerdings sind hierbei die Daten falsch oder fehlen, da ein anderer Import-Translator stattdessen genutzt wurde:
* die Seitenangaben stimmen nicht
* die Band- und Heftzählung fehlt

(gemeldet von @IxTheoEg)

**Comment by mara-spiess** [comment]
@IxKo Der Issue kann jetzt getestet werden :)

**Comment by IxKo** [comment]
Danke, behoben!
