### ISSUE TITLE
ISSN 2161-007X | Counseling and Values (Brill) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2052]
#### URL
https://brill.com/view/journals/cvj/68/2/article-p125_1.xml?ebody=article%20details
  
#### Import-Translator
ubtue_Brill.js

  
### Problembeschreibung
Im vollautomatischen Verfahren (nu+ub28) werden die ORCID-Informationen nicht angegeben.

**Comment by jriedl** [comment]
Auf nu.

**Comment by jriedl** [comment]
Update auf ub28 erfolgt nach Abschluss der Translation-Server-Testphase auf nu.

**Comment by IxKo** [comment]
Danke, passt auf beiden!
