### ISSUE TITLE
ISSN 1756-073X | Practical Theology (T&F) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2055]
#### URL
https://www.tandfonline.com/doi/full/10.1080/1756073X.2023.2288524
https://doi.org/10.1080/1756073X.2023.2286739
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

### Problembeschreibung

Die Einträge sind nicht auf ub28 zu finden, obwohl sie im RSS vorhanden sind:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/841c8b9d-17d0-432f-bcda-4032caae72bc)
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/d3c25c29-9aba-4838-817b-4d983c2aaa80)

Beim testen mit TRY RSS auf ub28 werden sie jedoch nicht im Ergebnis aufgeführt.

Ich habe einen Tag gewartet, um ein mögliches OF-Fenster auszuschließen.
Nun wollte ich sie halbautomatisch nacherfassen, doch alle Translators scheinen ein Problem damit zu haben:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/188956c4-0c46-4312-9057-3045466b7f4a)

**Comment by jriedl** [comment]
Es gibt bereits auf Translatorebene ein Problem mit dem Download der Zitationsinformationen im RIS-Format, wo bei der Abfrage ein HTTP-Fehler 500 (="Internal Server Error" auf T&F-Seite auftritt):

![image](https://github.com/ubtue/DatenProbleme/assets/13135579/66e9ef73-839b-48f1-b9f6-3092195aaa59)

Bei einem direkten Aufruf von https://www.tandfonline.com/action/downloadCitation?doi=10.1080/1756073X.2023.2286739 im Browser öffnet ein Klick auf den "Download Citations"-Button eine leere Seite. 

Meldung an T&F scheint sinnvoll, falls keine zeitnahe Reaktion, eventuell Verzicht auf RIS, um wenigstens die Basisinformationen zu bekommen? Allerdings scheint das gemäß den "delivered records" auf ub28 kein Problem zu sein, das grundsätzlich alle Artikel betrifft.

Analog #2058

**Comment by jriedl** [comment]
Analog #2056.

**Comment by jriedl** [comment]
Die T&F Homepage scheint gefixt zu sein, Download obiger DOI im Zotero-Client funtkioniert und DOI ist mittlerweile auch "grün" auf ub28.

**Comment by IxKo** [comment]
Danke, beide Einträge sind auf ub28 und funktionieren auch beim halbautomatischen Zotero-Import.
