### ISSUE TITLE
ISSN 2331-2521 | Journal of Disability & Religion (T&F) | Lizenzstatus

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2057]
#### URL
https://doi.org/10.1080/23312521.2022.2133788
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung
Der Eintrag ist in den zota-Errors gelandet.
Beim halbautomatischen Nacherfassen wird er mit der Notiz "LF:" importiert, was zu 4950 $4LF führt.
Doch der Artikel ist lizenzpflichtig. Hier sollte also keine Notiz erzeugt werden.

**Comment by mara-spiess** [comment]
Der Fehler kann von mir leider nicht rekreiert werden, @IxKo bitte nochmal testen ob es sich von alleine behoben hat. Danke!

**Comment by IxKo** [comment]
Danke, tatsächlich wird LF nicht mehr importiert.
