### ISSUE TITLE
ISSN 2331-2521 | Journal of Disability & Religion (T&F) | Translator-Abbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2058]
#### URL
https://doi.org/10.1080/23312521.2023.2292458
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js
  
### Problembeschreibung
Der Eintrag ist nicht in den zota-Einspielungen. Er ist aber im RSS:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/741c4996-a260-4bf3-b3c1-c5dcc4e3290e)

Beim Versuch den Eintrag halbautomatisch mit Zotero nachträglich zu erfassen, bricht der Translator ab:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/2f244eea-4825-426f-b3f8-f2320119d11b)

**Comment by jriedl** [comment]
Obige DOI aktuell "grün" auf ub28.

**Comment by IxKo** [comment]
Danke, klappt nun auch wieder im halbautomatischen Verfahren
