### ISSUE TITLE
ISSN 2175-5841 Horizonte Einzeldownload und Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#206]
Leider funktioniert beim halbautomatischen Verfahren nur der Einzeldownload. Vielleicht kann man da was machen. Ist ja eine OJS-Zeitschrift
Bei den Seitenzahlen wird nur die erste Seite eines Aufsatzes übertragen. Die letzte muss man manuell ergänzen.

**Comment by shadeMe** [comment]
Ich brauche ein Paar Beispiele.

**Comment by kdr154** [comment]
So sieht die Seite eines Heftes aus:
http://periodicos.pucminas.br/index.php/horizonte/issue/view/1067/showToc
so ein Aufsatz
http://periodicos.pucminas.br/index.php/horizonte/article/view/P.2175-5841.2018v16n51p1004

**Comment by shadeMe** [comment]
Steht die letzte Seite des Artikels irgendwo auf der Webseite? Ich sehe nur die erste Seite.

**Comment by kdr154** [comment]
Nein, man müsste die Seitenzahlen aus dem Inhalsverzeichnis berechnen oder die PDF-Datei aufrufen

**Comment by kdr154** [comment]
Mehrfachdownload ist jetzt möglich, die Seitenzahlen muss man weiterhin manuell ergänzen

**Comment by shadeMe** [comment]
Richtig. Wir können das Issue jetzt schließen.

**Comment by kdr154** [comment]
Schließe
