### ISSUE TITLE
ISSN 2366-0597 | Forum Exegese und Hochschuldidaktik | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2060]
#### URL
https://elibrary.narr.digital/xibrary/start.xav?zeitschriftid=vvaa#__xibrary__%2F%2F*%5B%40attr_id%3D%27vvaa72%27%5D__1706168743567
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Narr.js

  
### Problembeschreibung
Der Translator wird nicht mehr angeboten, weder beim Heft noch bei einer Artikelseite.

_Hinweis: Anfrage von Koop-Partner_

**Comment by mara-spiess** [comment]
@socheres Die Webseite scheint die Metadaten nur noch dynamisch zu generieren. In der Wayback Machine habe ich mir [ältere Versionen der Verlagsseite](https://web.archive.org/web/20220619050208/https://elibrary.narr.digital/journal/aaa/47/1) angesehen, in der das noch nicht so gewesen zu sein schien und für die der Translator vermutlich entwickelt wurde. Ich nehme an das für diese neue Version kein Translator funktionieren wird?

**Comment by socheres** [comment]
Im Scaffold kann ich die URL auch nicht öffnen. Über den Button "Share link" oben rechts auf der Webseite ist die persistente URL angegeben, aber auch mit diesem Link baut die Webseite nicht auf. Über den RIS-Download können die Metadaten aber nach Zotero geladen werden.

![image](https://github.com/ubtue/DatenProbleme/assets/1545743/25e5bfa3-28a0-40bc-b23d-7fe4e0b90e4b)

**Comment by mara-spiess** [comment]
@IxKo Kannst du den Kooperationspartnern mitteilen dass für die Webseite nur noch über den direkten Zitierbutton mit Zotero katalogisiert werden kann? Leider funktioniert das nur für den Einzelimport. Danke!

**Comment by IxKo** [comment]
Ok, ich habe dem Kooperationspartner Bescheid gegeben und die Besonderheiten in ZEDER vermerkt.
