### ISSUE TITLE
ISSN 2473-3725 | The Thomist (MUSE) | keine Einspielung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2064]
#### URL
https://muse.jhu.edu/issue/51643
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Project MUSE.js

### Problembeschreibung
Es gibt wieder ein Problem mit der Zs. (schon einmal angesprochen: https://github.com/ubtue/DatenProbleme/issues/2037#issuecomment-1845635774)

Ich habe am 30.01.24 bei der Zs. die QA-Einstellungen für 024 (DOI) entfernt, da es nun scheinbar keine mehr seit 2 Heften gibt. (Die QA wurde mal so eingestellt, weil die DOIs verspätet kamen.)
Doch leider befinden sich die Daten zum aktuellen Heft (2024,1) noch immer in den Errors.

Bei mehrfachen Versuchen mit TRY RSS werden keinerlei MARCXML-Daten erzeugt.
Mit einer Aufsatz-URL klappt es hingegen.

**Comment by jriedl** [comment]
Ein Problem scheint zu sein, dass nach einer relativen geringen Anzahl an Requests eine Weiterleitung auf eine Verfikationsseite erfolgt `(3)(+0000001): Translate: <title>Project MUSE -- Verification required!</title> ` bzw. z.B. `(3)(+0000032): Translators: Looking for translators for https://muse.jhu.edu/verify?url=%2Fpub%2F16%2Farticle%2F900225`, auf denen ein Capcha gelöst werden müsste. Im RSS sind aber mehrere Hefte hinterlegt. @socheres: Gab es mit MUSE einmal eine offizielle Vereinbarung bzw. könnten wir hier gewhitelisted werden?

**Comment by socheres** [comment]
eMail-Anfrage an MUSE läuft!

**Comment by IxKo** [comment]
Es scheint wieder zu funktionieren.
