### ISSUE TITLE
ISSN 0973-5089 | International journal of criminal justice sciences | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2066]
#### URL
https://www.ijcjs.com/volume-detail.php?id=37
  
#### Import-Translator
  Einzel- und Mehrfachimport:
  Keiner

  
### Problembeschreibung
Ist es möglich für diese Seite einen Translator zu entwickeln?

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_IJCJS

**Comment by kyushutea** [comment]
Der Translator funktioniert. Danke!
