### ISSUE TITLE
ISSN 1086-3184 | Journal of early Christian studies (MUSE) | DOI bei Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2067]
#### URL
https://doi.org/10.1353/earl.2023.a915035
IxTheo#2024-02-12#6C2082A1E3946AED8E57B7F4C35B1DAF953DD4BF

  
### Problembeschreibung
Der DOI und Resolving-Link wurde nicht miterfasst.
Bei den normalen Artikeln schon, aber nicht bei den Rezensionen.

**Comment by jriedl** [comment]
Das ist einer der Fälle, in denen sich der Translation-Server "empfindlicher" verhält als der Zotero-Client, weshalb ubtue_Project MUSE in bestimmten Konstellationen abgebrochen hat. Der dann in der Hierarchie danach kommende allgemeine  Project MUSE-Translator hat die DOIs nicht extrahiert. Angepasste Version von ubtue_Project MUSE auf nu.

**Comment by IxKo** [comment]
Danke, scheint auf Nu zu funktionieren (getestet mit TRY RSS: 49 Einträge und 49x "doi.org" gefunden).

Auf ub28 spuckt es eine leere gelbe Seite aus.

**Comment by jriedl** [comment]
Aktueller Stand auf ub28.

**Comment by IxKo** [comment]
Danke, passt!
