### ISSUE TITLE
ISSN 0074-0160 Anthologica annua Band und Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#207]
halbautomatisches Verfahren
Hier steht die Bandangabe wieder im Feld Ausgabe. Sie muss ins Feld Band
Die Zusammenfassung (Abstract) beinhaltet den Inhalt, der auf der Seite des jeweiligen Aufsatzes steht. Das darf nicht in das Feld Zusammenfassung geschrieben werden

**Comment by shadeMe** [comment]
Ein Beispiel brauche ich, um das Problem zu reproduzieren.

**Comment by kdr154** [comment]
https://dialnet.unirioja.es/servlet/articulo?codigo=6732372
https://dialnet.unirioja.es/servlet/articulo?codigo=6732373

**Comment by shadeMe** [comment]
Hier stellt sich die gleiche Frage wie bei Cairn.info - Gibt es hier auch ein Kriterium, wonach der Translator sich orientieren könnte?

**Comment by kdr154** [comment]
Der Wert 64 z. B. hinter Numero oder No, wie es beim einzelnen Aufsatz steht, soll in Zotero einfach nicht in das Feld Ausgabe, sondern in das Feld Band.
Was das Abstract betrifft.  Hier wird das, was auf der Seite des jeweiligen Aufsatzes steht, als Zusammenfassung interpretiert und in das Feld Zusammenfassung in Zotero geschrieben. Warum?

**Comment by shadeMe** [comment]
Was das Abstract anbelangt, tut es nur so, wenn der "Embedded Metadata" Translator anstatt dem "Dialnet" Translator aufgerufen wird. Manchmal wird der Zotero Browser-Connector den Translator beim ersten Versuch falsch auswählen. Normalerweise löst sich das Problem von selbst, wenn die Webseite neu geladen wird.

**Comment by kdr154** [comment]
Was das Abstract anbelangt, ist die Sache jetzt in Ordnung. Die Bandangabe steht aber weiterhin im Feld Ausgabe.

**Comment by shadeMe** [comment]
Bei den zwei obigen URLs scheint der Translator auf meiner Seite zu funktionieren. Gibt's andere, bei denen er immer noch nicht funktioniert?

**Comment by kdr154** [comment]
Ist in Ordnung
