### ISSUE TITLE
ISSN 2035-6455 | Historia religionum (LibraWeb) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2071]
#### URL
https://www.libraweb.net/articoli.php?chiave=202304901&rivista=49
  
#### Import-Translator
laut ZEDER ubtue_LibraWeb.js

  
### Problembeschreibung
Der Translator "ubtue_LibraWeb.js" wird nicht mehr angeboten.

Es wird "DOI" angeboten, doch hier bricht der Import ab.

(gemeldet von @IxTheoEg)

**Comment by mara-spiess** [comment]
Der Translator sollte wieder angeboten werden, sind die restlichen Funktionen des Translators problemfrei?

**Comment by IxKo** [comment]
Mir wird leider noch kein ubtue-Translator auf der Seite angeboten.

**Comment by mara-spiess** [comment]
Die lokalen Verzeichnisse waren noch nicht aktualisiert, entschuldigung!

**Comment by mara-spiess** [comment]
Identisch zu https://github.com/ubtue/DatenProbleme/issues/1792

**Comment by IxKo** [comment]
Passt, danke!
