### ISSUE TITLE
ISSN 0974-2891 | International journal of cyber criminology | Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2072]
#### URL

https://cybercrimejournal.com/issue-view.php?id=5
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

  
### Problembeschreibung

Könnte für diese Seite ein Translator entwickelt werden?
Dois und Seitenzahlen müssten manuell aufgenommen werden.

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_Cyber_Criminology
Aufgrund einer Änderung im Publikationsformat können die Issues leider erst ab "IJCC-July - December 2021" mit dem Translator bearbeitet werden.

**Comment by kyushutea** [comment]
Funktioniert, danke für die Info!
