### ISSUE TITLE
ISSN 0012-1223 | Deutsches Archiv für Erforschung des Mittelalters (harrassowitz) | neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2077]
#### URL
https://mgh-da.harrassowitz-library.com/issue/MGH-DA/2023/1
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung

Könnte für diese Zs./Plattform ein Translator angeboten werden?

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_Harrassowitz_Deutsches_Archiv_fuer_Erforschung_des_Mittelalters.js

**Comment by IxKo** [comment]
Vielen Dank!
