### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift (OJS) | Band

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2078]
#### URL
https://tidsskrift.dk/rvt/article/view/141855
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung

Die Bandangabe wird fälschlicherweise in da Feld Ausgabe importiert und damit fälschlicherweise als Heftzählung exportiert.
Könnte das bitte angepasst werden?

**Comment by mara-spiess** [comment]
Wird die Bandnummer momentan korrket importiert?

**Comment by IxKo** [comment]
> Wird die Bandnummer momentan korrket importiert?

Nein, die Band-Nr. wird in das Zotero-Feld "Ausgabe" importiert, was beim Export in Unterfeld 4070 $a für die Heftzählung führen würde.
Sie müsste in das Zotero-Feld "Band"

**Comment by IxKo** [comment]
Behoben, danke!
