### ISSUE TITLE
ISSN 0026-587X | Miscellanea Francescana (EBSCO) | weiteres Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2079]
#### URL
https://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26AN%3d174805065%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Das italienische Abstract wird nicht importiert, nur das englische.

Gemeldet von: @IxTheoEg

**Comment by mara-spiess** [comment]
@IxKo Gibt es Beispiele für Zeitschriften bszw. Translator bei denen mehrere Abstracts importiert werden?

**Comment by IxKo** [comment]
ubtue_Cairn.info.js bspw. bei der Zs. "Nouvelle revue théologique"

**Comment by IxKo** [comment]
Danke, die Abstracts werden nun mitimportiert.

Allerdings bricht beim Mehrfach-Import der Import ab, soll ich dafür ein neues Issue öffnen?

**Comment by IxKo** [comment]
> Allerdings bricht beim Mehrfach-Import der Import ab, soll ich dafür ein neues Issue öffnen?
Das Problem des Import-Abbruchs wurde mittlerweile gelöst.
