### ISSUE TITLE
ISSN 2340-0080 | Estudios penales y criminologicos (PKP) | ORCID

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2081]
#### URL
https://doi.org/10.15304/epc.43.8650
  
#### Import-Translator
  Einzelimport:
ubtue_PKP Catalog Systems.js

  
### Problembeschreibung
ORCID wird nicht importiert. Beim ubtue_Open Journal Systems Standard.js hingegen schon, dieser wird auch als erster Translator angeboten. Mehrfachimport funktioniert mit ubtue_PKP Catalog Systems.js nicht.

**Comment by Martina-Dae** [comment]
Besteht das Problem noch immer? Bei mir wird sowohl mit Open Journal Systems Standard.js als auch mit PKP Catalog Systems.js die Orcid ausgegeben: 
![image](https://github.com/user-attachments/assets/f523c4a7-7acc-4280-a35c-47380e4e3094)

**Comment by kyushutea** [comment]
Siehe Klärungsbedarf: https://github.com/ubtue/DatenProbleme/issues/2084#issuecomment-2304598178

Beim Einzelimport mit ubtue_Open Journal Systems Standard.js wird die ORCID importiert.
Beim Einzelimport mit ubtue_PKP Catalog Systems.js wird die ORCID nicht importiert.

**Comment by Martina-Dae** [comment]
Wurde die translator-Verwendung mittlerweile geklärt (vgl. #2084) ?

**Comment by kyushutea** [comment]
Die ORCID wird nun mitgeliefert, somit hat sich das Issue geklärt. Danke!
