### ISSUE TITLE
ISSN 2473-3725 | The Thomist (MUSE) | Jahr

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2083]
#### URL
https://muse.jhu.edu/issue/51643
IxTheo#2024-02-19#964C2F30BA9154F6B7D4C341B75ACA92E3007F5F
 
  
### Problembeschreibung
Das Heft mit Erscheinungsjahr 2024 ist mit Jahr 2023 eingespielt worden.

Im halbautomatischen Verfahren mit dem Translator ubtue_Project MUSE:js wird das Jahr korrekt als 2024 importiert.

**Comment by jriedl** [comment]
Ist wohl eine Folge von #2037 - da bei Artikeln nur ein Date-Feld existiert, wird dieses aus den Embedded Metadata-Feld ` `citation_online_date` befüllt  - hier steht ein Datum aus 2023. Eine angepasste Version des Translators,, die das Date-Feld mit dem `citation_year` überschreibt, findet sich auf nu.

**Comment by IxKo** [comment]
Danke, ist auf nu nun korrekt. Bitte noch auf ub28

**Comment by jriedl** [comment]
Aktueller Stand nun auf ub28.

**Comment by IxKo** [comment]
Danke, passt!
