### ISSUE TITLE
ISSN 2332-886X | Criminology, Criminal Justice, Law & Society | Keywords

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2085]
#### URL
https://ccjls.scholasticahq.com/issue/8495
  
#### Import-Translator
  Mehrfachimport:
ubtue_CCJLS.js

  
### Problembeschreibung
Bei dem Test für die vollautomatische Einspielung mit Zotero wurden die Keywords in die Test-DB nicht mitgeliefert.

#### URL
https://ccjls.scholasticahq.com/article/90807-the-illusion-of-supremacy-a-theory-of-indifference

#### Import-Translator
  Einzelimport:
ubtue_CCJLS.js

### Problembeschreibung

Beim Einzelimport werden die Keywords mitgeliefert. Ein Mehrfachimport funktioniert im halbautomatischen Verfahren nicht.

**Comment by jriedl** [comment]
Extraktion bei zotaut über Embedded Metadata. Dieser verwirft Keywords, falls nicht als Untertranslator aufgerufen. Angepasste Version ubtue_Embedded Metadata mit Ausnahme für diese Zeitschrift nun auf nu.

**Comment by kyushutea** [comment]
Vielen Dank funktioniert, auch auf ub28.
