### ISSUE TITLE
ISSN 0008-1795 | Calvin theological journal (EBSCO) | Zusatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2086]
#### URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26jid%3dATLA0000003241%26site%3dehost-live
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

  
### Problembeschreibung
Beim Improtieren wird nach dem Titel zusätzlich immer der Zs.-Titel ": Calvin Theological Journal" angefügt:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/a1b59ab7-c875-474a-b640-99a42f0bd576)

(gemeldet von @IxTheoEg)

**Comment by IxKo** [comment]
Das Issue betrifft alle Zs., die wir über EBSCO katalogisieren (>50)

**Comment by mara-spiess** [comment]
Die EBSCO Zeitschriften lassen sich leider nicht im Scaffold öffnen, auch nicht mit Hilfe einer lokalen .htm Datei.

**Comment by jriedl** [comment]
Es lässt sich öffnen, wenn man eine Seite manuell speichert und die Script-Tags aus dem HTML entfernt.
![image](https://github.com/user-attachments/assets/aca7e50c-c8af-43af-969d-a1fed2a68b66)

**Comment by mara-spiess** [comment]
@jriedl Den ersten Tests von @kyushutea nach sind die Titel nun korrekt. In den ISSN fehlt allerdings der Bindestrich, ob das bereits so war können wir nicht nachvollziehen. In den entsprechenden Mapping Listen sind die ISSN auf jeden Fall immer mit Bindestrich aufgeführt.

**Comment by jriedl** [comment]
Das ist aber unabhängig von den ORCID-Listen. Mit der in der Mail angegebenen URL erkennt man, dass das ISSN Problem offenbar bereits im Zotero-"Original"-Translator auftritt. Sollte sich aber durch z.B. 
```js
if (item.ISSN && item.ISSN.length == 8)
    item.ISSN = item.ISSN.substring(0,4) + '-' + item.ISSN.substring(4);
```
leicht beheben lassen.

**Comment by mara-spiess** [comment]
Ich würde die Rückkehr von @IxKo abwarten um herauszufinden wie bisher mit den ISSN umgegangen wurde und falls notwendig den Translator anpassen. 
Auch um dieses Issue zu schließen würde ich das finale Feedback von @IxKo abwarten, da eine Großzahl von Translators betroffen sind.

**Comment by jriedl** [comment]
Ok.

**Comment by IxKo** [comment]
> @jriedl Den ersten Tests von @kyushutea nach sind die Titel nun korrekt. In den ISSN fehlt allerdings der Bindestrich, ob das bereits so war können wir nicht nachvollziehen. In den entsprechenden Mapping Listen sind die ISSN auf jeden Fall immer mit Bindestrich aufgeführt.

Ich habe durch viele Tests irgendwann selbst herausgefunden, dass die importierte ISSN ohne Bindestrich funktioniert, und dass für die Mapping-Listen nur die erste importierte ISSN (teilweise werden zwei ISSNs importiert) relevant ist, diese aber in den Mapping-Listen immer mit Syntax 1234-1234 angegeben werden muss.

**Comment by IxKo** [comment]
Der Zs.-Titel wird nun nicht mehr als Titel-Anhang importiert, danke!

**Comment by socheres** [comment]
> > @jriedl Den ersten Tests von @kyushutea nach sind die Titel nun korrekt. In den ISSN fehlt allerdings der Bindestrich, ob das bereits so war können wir nicht nachvollziehen. In den entsprechenden Mapping Listen sind die ISSN auf jeden Fall immer mit Bindestrich aufgeführt.
> 
> Ich habe durch viele Tests irgendwann selbst herausgefunden, dass die importierte ISSN ohne Bindestrich funktioniert, und dass für die Mapping-Listen nur die erste importierte ISSN (teilweise werden zwei ISSNs importiert) relevant ist, diese aber in den Mapping-Listen immer mit Syntax 1234-1234 angegeben werden muss.

Die importierte ISSN (=Zoterofeld "ISSN") wird mit der Funktion ZU.cleanISSN https://github.com/ubtue/zotkat-translators/blob/4f24e7a22298f3f6d3cf54584d03d60e3fc2450b/ubtue_pica3.js#L343 auf Richtigkeit geprüft und setzt dabei automatisch einen Bindestrich. https://github.com/zotero/zotero/blob/4b3d0054e571bb91e61d1d981be0c5c42db63686/chrome/content/zotero/xpcom/utilities.js#L360-L384
Diese validierte ISSN wird dann mit den ISSN-Konkordanzen in den zotero-enhancement-maps verglichen. D.h. wenn in den Konkordanzen nur eine Schreibweise, nämlich ISSN ohne Bindestrich, eingetragen wäre, würde der entsprechende Wert nicht übernommen. In den Konkordanzen sind aber bisher alle Varianten, also mit und ohne Bindestrich eingetragen.
