### ISSUE TITLE
ISSN 0718-3399 | Política criminal (SciELO) | ORCID

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2088]
#### URL
https://doi.org/10.4067/S0718-33992023000200500
Test-DB: KrimDok#2024-01-31#04BB595BEC70EB5C6EF37FE9586EA75345E4CB72
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_SciELO.js

nu:
SciELO.js
  
### Problembeschreibung

- [x] Halbautomatisch: 

Beim Einzelimport wird die ORCID nicht importiert.

- [X] Vollautomatisch: 

Die ORCID wird nicht eingespielt.

**Comment by jriedl** [comment]
Auf nu

**Comment by kyushutea** [comment]
Danke, auf nu funktionierts. Können Sie es auch für ub28 freischalten?

**Comment by kyushutea** [comment]
Danke, auf nu und ub28 funktionierts.
