### ISSUE TITLE
ISSN 2633-8084 | Journal of Criminology (Sage) | OF als Error erkannt

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2089]
#### URL
https://journals.sagepub.com/doi/10.1177/26338076231223580

Hash: 428C0C555A662C8C8D7678B94E348D11344BA7C3
  
### Problembeschreibung

Beim Testen der Zeitschrift sind die OF Aufsätze in nu gelb (Errors). Sie müssten normalerweise schwarz sein, oder?

**Comment by jriedl** [comment]
Das Vorhandensein einer Seitenangabe unterbindet die Kennzeichnung als OF. Hier werden offenbar IDs hinterlegt. Hier wurde nun der entsprechende Regex auf nu so nachgeschärft, dass er IDs, die definitiv länger sind als eine einzelne Seitenangabe den Test nicht mehr bestehen.
