### ISSUE TITLE
ISSN 2413-3027 Journal for the study of religion Abstract und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#209]
halbautomatisches Verfahren
hier: http://www.scielo.org.za/scielo.php?script=sci_issues&pid=1011-7601&lng=en&nrm=iso
werden die Keywords und das Abstract nicht übertragen

**Comment by shadeMe** [comment]
Ich habe jetzt [mehrere Translators](https://github.com/ubtue/zotero-translators/pull/68/files) angepasst, die lokal aktualisiert werden müssen.

**Comment by kdr154** [comment]
Passt
