### ISSUE TITLE
ISSN 1469-9540 | Journal of intercultural studies (T&F) | Error 655 review

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2090]
#### URL
https://doi.org/10.1080/07256868.2023.2254725
Hash: 9674E0FCED7F7DF59708B16A2799E7CEABD1161A
  
 
### Problembeschreibung

Der Datensatz ist in den Errors gelandet, weil das Keyword "review" statt in Feld 650 in Feld 655 importiert wird und hierbei entsprechende Unterfelder fehlen.
Es sollte aber in Feld 650.

Außerdem wird Feld 655 Rezension erzeugt.
Dies ist aber nicht korrekt. Denn es handelt sich hierbei um keine Rezension.

**Comment by jriedl** [comment]
Da überlagern sich zwei Aspekte: "review" steht in `zotero-enhancement-maps/marc655_keywords.txt`, deshalb wir es von 650 nach 655 verschoben. Weiterhin ist es Teil globalen `zotero_review_regex` in `zotero_harvester.conf`, deshalb wird weiterhin das vollständige 655-Rezensionsfeld erzeugt. Da mit dem `zotero_review_regex` eine eigene Behandlungslogik für Rezensionen existiert, scheint der Eintrag in den marc655_keywords eigentlich nicht mehr sinnvoll zu sein und wirkt wie ein Relikt aus einer frühen Entwicklungsstufe oder macht als Eintrag nur außerhalb des zotaut-Verfahrens Sinn. Automatisch zu erkennen, dass es sich bei diesem Artikel trotz des Keywords nicht um einen Rezension handelt, scheint eigentlich nicht möglich, "review" deshalb aus der zotero_regex-Liste zu nehmen, ist m.E. nicht sinnvoll.

**Comment by IxKo** [comment]
Danke für die Info. Ich habe "Review" und "review" aus der [marc655_keywords.txt](https://github.com/ubtue/zotero-enhancement-maps/blob/master/marc655_keywords.txt) Mapping-Liste entfernt und der Datensatz wurde eingespielt.
