### ISSUE TITLE
ISSN 1945-7073 | Violence and victims (Springer Publishing Connect) | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2093]
#### URL
https://connect.springerpub.com/content/sgrvv/39/1
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

  
### Problembeschreibung
Ist es möglich einen Translator zu entwickeln?

**Comment by mara-spiess** [comment]
Der neue Translator "ubtue_Springer_Publishing.js" kann nun getestet werden.

**Comment by kyushutea** [comment]
Funktioniert, danke!
