### ISSUE TITLE
ISSN 1836-2206 | Trends & issues in crime and criminal justice | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2094]
#### URL
https://www.aic.gov.au/publications/tandi/tandi688
https://www.aic.gov.au/publications/tandi
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

  
### Problembeschreibung
Ist es möglich einen Translator zu entwickeln?

**Comment by mara-spiess** [comment]
@kyushutea Neuer Translator ubtue_trends_and_issues_criminology

**Comment by kyushutea** [comment]
Die Artikel ID (Beispiel: "artikelID:684") werden als Tags in Zotero angegeben.

**Comment by mara-spiess** [comment]
@kyushutea Die artikelID wird jetzt als Notiz statt als Tag hinzugefügt.

**Comment by kyushutea** [comment]
Funkioniert, danke!
