### ISSUE TITLE
ISSN NV | Addiction and Criminology | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2095]
#### URL
https://www.alliedacademies.org/addiction-criminology/archive/aara-volume-6-issue-6-year-2023.html
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

  
### Problembeschreibung
Kann man einen Translator entwickeln? Falls möglich, müsste eine fingierte ISSN "KRIM-0001" verwendet werden. Eventuell könnte der Titel der Enhancement-maps angepasst werden, da dort "IXTH-" steht.

**Comment by socheres** [comment]
PR gemergt.

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_Allied_Academies

**Comment by kyushutea** [comment]
Fehlende Daten:
- [ ] Seitenangaben
- [ ] Fiktive ISSN

Fehlerhafter Import:
- [ ] LF: in Tags

Da es eine rein lizenzfreie Zeitschrift ist, kann man den Lizenzstatus in der Github Enhancement Map hinterlegen.

Kann man die Artikel mit Großbuchstaben normalisieren?
Beispiel:
https://www.alliedacademies.org/articles/a-study-on-financial-cyber-crimes-trends-patternsand-its-effects-in-the-economy-28127.html

**Comment by mara-spiess** [comment]
@jriedl Könnte wie hier gewünscht der Titel der [enhancement map für die fingierten ISSNs](https://github.com/ubtue/zotero-enhancement-maps/blob/master/%C3%9Cbersicht%20fingierte%20ISSNs%20IXTH-%23%23%23%23) geändert werden, da jetzt nicht mehr nur IXTH- ISSNs beinhaltet sind?

**Comment by jriedl** [comment]
Der Hinweis auf die IT in der Datei scheint sich rein auf die Behandlung innerhalb des Translators zu beziehen, ist also nicht i.e.S. IT-spezifisch. Sie wird m.W. ausschließlich im zotkat-Kontext genutzt, d.h. ich weiß nicht, ob exakt dieser Dateiname an irgendeiner Stelle dort vorausgesetzt wird - das müsste @socheres beantworten.

**Comment by mara-spiess** [comment]
Ich habe die Änderung mit @socheres abgesprochen, der Dateiname hat scheinbar keinen weitere Einfluss.

**Comment by mara-spiess** [comment]
@kyushutea Das LF Tag wurde entfernt, die fiktive ISSN ergänzt und Artikel mit Großbuchstaben werden jetzt normalisiert. Der Lizenzstatus ist nun in der Enhancement Map hinterlegt. Die Seitenzahlen können wie bereits besprochen leider nicht importiert werden.

**Comment by kyushutea** [comment]
Funktioniert, danke!

**Comment by kyushutea** [comment]
Der Translator funktioniert, aber Zotero scheint die Änderungen mit der fingierten ISSN "KRIM-0001" über die Enhancement Maps nicht zu übernehmen.

**Comment by socheres** [comment]
Lag am Pica3-Exporttranslator. Jetzt sollte er die Werte aus Enhancementmap übernehmen.

**Comment by kyushutea** [comment]
Funktioniert! Vielen Dank für die schnelle Bearbeitung.
