### ISSUE TITLE
ISSN 2045-8525 | African journal of law and criminology | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2096]
#### URL
https://www.topjournals.co.uk/ajlc-vol-13-2-2023
  
#### Import-Translator
  Einzel- und Mehrfachimport:
Keiner

  
### Problembeschreibung
Kann man dafür einen Translator entwickeln?

**Comment by mara-spiess** [comment]
@jriedl Kann das Label "New Translator" frei für alle Issues genutzt werden, bei den ein neuen Translator angefragt wird? Oder geht es konkret um die Issues, bei denen dann auch tatsächlich einer entwickelt wird bzw. wurde? Ich hatte angefangen es zu vergeben um die bereits vorhandenen Issues optisch direkt besser einordnen zu können, wollte sicherheitshalber aber nochmal nachfragen und die Label wenn notwendig wieder entfernen.

**Comment by jriedl** [comment]
Da das in der Vergangenheit offenbar nicht systematisch vergeben wurde, spricht da wohl nichts dagegen, da so zu verwenden, wie es Ihnen sinnvoll scheint.

**Comment by mara-spiess** [comment]
Da die Webseite leider sehr inkonsistent und rudimentär ist, kann meiner Einschätzung nach leider kein Translator entwickelt werden. Die einzigen spezifischen CSS-Selectors die genutzt werden können ist die Schriftart, die sich von Issue zu Issue ändert.
