### ISSUE TITLE
ISSN 2232-1969 | Al-Bayan (Brill) | Paralleltitel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2097]
#### URL
https://doi.org/10.1163/22321969-20240148

- [x] zotk
- [X] zota

#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Brill.js

### Problembeschreibung
Könnte bitte der Titel im lateinischen Alphabet unterhalb des arabischen Titels als Paralleltitel in 4002 im- und exportiert werden?

### Problembeschreibung
Könnte bitte der Titel im lateinischen Alphabet unterhalb des arabischen Titels als Paralleltitel in `<datafield tag="246" ind1="3" ind2="1"><subfield code="a">` importiert werden?

**Comment by jriedl** [comment]
Ist absehbar, dass es sich hierbei um eine dauerhafte Umstellung und nicht um einen (eventuell fehlerhaft erfassten) Einzelfall handelt? Offenbar wurde in der Vergangenheit auch bei arabischen Texten der Haupttitel in Englisch angegeben (vgl. z.B.  https://brill.com/view/journals/jqhs/15/1/article-p115_6.xml / https://ixtheo.de/Record/1561963836).

**Comment by IxKo** [comment]
Absehbar ist es nicht. Doch im Heft davor ist es ähnlich.

Die Übersetzung aber in Klammern beim Titel anzugeben (wie bei der Verlagslieferung), halte ich für nicht korrekt.

**Comment by jriedl** [comment]
Sollte nach dem nächsten automatischen Update der zotero_harvester.conf heute Abend auf nu testbar sein.

**Comment by IxKo** [comment]
> Sollte nach dem nächsten automatischen Update der zotero_harvester.conf heute Abend auf nu testbar sein.

Auf nu wird es nun umgesetzt, danke.
Allerdings wird es auch bei Titeln umgesetzt, die keinen Paralleltitel haben. Hier wird als Titel "null" generiert:
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/02e06a7b-28ff-49b2-92ff-bdc529ab109e)
Könnte das noch behoben werden?

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Danke, funktioniert auf nu. Bitte auch auf ub28.

**Comment by jriedl** [comment]
Aufgrund des gestrigen Updates ist die Anpassung bereits Teil des aktuellen Standes auf ub28 (vgl. z.B. https://doi.org/10.1163/22321969-20230142)

**Comment by IxKo** [comment]
> Aufgrund des gestrigen Updates ist die Anpassung bereits Teil des aktuellen Standes auf ub28 (vgl. z.B. https://doi.org/10.1163/22321969-20230142)

Danke, stimmt.

**Comment by IxKo** [comment]
Bei einer anderen Brill-Zs. "Zeitschrift für medizinische Ethik" wurde Feld 246 auch mitgeliefert.
Es scheint jedoch seitens des BSZ nicht ganz korrekt umgesetzt worden zu sein:
Die Datensätze haben im K10plus sowohl 246 31 wie wir es liefern und es wird in Pica-Feld 4002 übernommen.
Aber es wird auch ein Feld 246 33 erzeugt, dass in Pica-Feld 3260 resultiert. Letzteres kommt aber nicht von uns.

Ich werde den Support schreiben.

**Comment by mara-spiess** [comment]
Kann jetzt auch für zotk getestet werden.

**Comment by IxKo** [comment]
Wird im halbautomatischen Verfahren mit der Notiz `additional_title:The Syntactic Interpretation in al-Frrāʾs Book “The Meanings of the Qurʾān”: Its Manifestations and Rules` importiert.
Beim Export passiert damit aber scheinbar gar nichts. Es wird kein Feld 4002 erzeugt.

In der Vergangenheit bei anderen Fällen wurde die einleitende Wendung `Paralleltitel:` verwendet.
Wenn ich das manuell in der Notiz abändere würde es zwar ein Feld 4002 erzeugt werden, jedoch unschön mit Tags (< >):
![image](https://github.com/user-attachments/assets/f68b5eac-ce2b-490d-b6c0-6b973a684417)

**Comment by mara-spiess** [comment]
Ich habe 'additional_titel' zu 'Paralleltitel' korrigiert. Bitte erneut testen.

**Comment by IxKo** [comment]
> Ich habe 'additional_titel' zu 'Paralleltitel' korrigiert. Bitte erneut testen.

Danke, das hat geholfen.

**Comment by IxKo** [comment]
Das BSZ hat sich bei mir noch nicht zurückgemeldet, warum zusätzlich 3260 belegt wird.
Die Belegung beider Pica-Felder 4002 (Paralleltitel) und 3260 (abweichender Titel / Sucheinstieg) scheint mir insgesamt jedoch nicht problematisch.
