### ISSUE TITLE
ISSN 1759-8818 | Sociology of religion (Oxford Academic) | URL-Struktur dx.doi

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2098]
#### URL
https://doi.org/10.1093/socrel/srad014
IxTheo#2024-04-05#B843F34BD9E7F7C61313E3DB00C9432B9550989F
  
### Problembeschreibung
Zur "normalen" Resolving-URL des DOI mit Präfix "doi.org" wird zusätzlich ein Resolving-Link mit dem veralteten Präfix "dx.doi" erzeugt.

Die veraltete Variante bitte nicht zusätzlich erfassen.

Besser wäre zusätzlich die URL der Artikel-Seite wie es wohl vorher auch mal war:
 IxTheo#2023-05-24#D2D96EE25DBE4272EBE6EBC87E2D686406DD8335

**Comment by jriedl** [comment]
Es wird nun nur noch die DOI direkt extrahiert

> Besser wäre zusätzlich die URL der Artikel-Seite wie es wohl vorher auch mal war:

Dies wurde ja offenbar Verlagsseitig auf die DOI angepasst

**Comment by IxKo** [comment]
Danke, auf nu wird nur noch der Resolving-Link mit doi.org generiert.
Bitte noch auf ub28 bringen.


>> Besser wäre zusätzlich die URL der Artikel-Seite wie es wohl vorher auch mal war:

> Dies wurde ja offenbar Verlagsseitig auf die DOI angepasst

Meinten Sie dass es translatorseitig angepasst wurde? Im halbautomatischen Verfahren wird nur der DOI importiert und mit doi.org exportiert und auch keine Browser-URL im-/exportiert.
Ich meinte, dass zusätzlich die Browser-URL besser fände, da ich oft sehe, dass DOIs nicht auflösen.

**Comment by jriedl** [comment]
Aktueller Stand jetzt auf ub28 (damit auch Anpssung für #1615).
 
> Meinten Sie dass es translatorseitig angepasst wurde? 

Nein, gemeint war, dass im Gegensatz zu früher nun offenbar dx.doi...  durch den Verlag als URL-Angabe hinterlegt wird, aber genau das wollen wir ja nicht haben. Im Prinzip ist der Sinn der DOI ja auch, eine sich potentiell ändernde URL dahinter "wegzuabstrahieren". 

Im halbautomatischen Verfahren wird nur der DOI importiert und mit doi.org exportiert und auch keine Browser-URL im-/exportiert.

Genauso wurde es hier auch umgesetzt.

**Comment by IxKo** [comment]
Danke, passt auch auf ub28

**Comment by IxKo** [comment]
Das Problem ist mit der heutigen Einspielung teilweise wieder aufgetreten.
Beispiele: IxTheo#2024-06-06#FAB8C4082D38E04A26E490764CFFBFF3154039E7, IxTheo#2024-06-06#FE6EBA7C813F35327A0EE6D0C4869061373AE187

Seltsamerweise aber nicht bei allen Datensätzen: IxTheo#2024-06-06#52E3ED0D66FED1466B8A3792A0574CE662F149DD, IxTheo#2024-06-06#0EF17EB1B73C89632F31A5A9C0E53CE68580ED7A

**Comment by jriedl** [comment]
Aktuell auf nu und ub28 nicht reproduzierbar.

![image](https://github.com/ubtue/DatenProbleme/assets/13135579/225b69af-bcfe-4d34-bc77-90c2698d5916)

![image](https://github.com/ubtue/DatenProbleme/assets/13135579/14f197ac-7831-4575-b09c-b6c2b59967cb)

Bitte Nachricht bei erneutem Auftreten.

**Comment by jriedl** [comment]
Nachtrag nach Log-Analyse ub28 am Beispiel 10.1093/socrel/srad019: Der am 6.6. für  den Download verwendete Link  kommt aktuell im RSS-Feed nicht mehr vor (Artikel ist noch vorhanden). Der damals verwendete Link wird auch auf den gleichen Link aufgelöst wie die DOI und somit kommt korrekt der Oxford-Academic-Translator zum Einsatz. Am 6.6 blieb aber nur EM Translator mit der höchsten Priorität übrig.

**Comment by IxKo** [comment]
In neuer Einspielung scheint das Problem nun nicht mehr zu bestehen.
