### ISSUE TITLE
ISSN 2699-8440 | Sexual Offending | Fehlende Keywords

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2099]
#### URL
https://sotrap.psychopen.eu/index.php/sotrap/article/view/13147
  
### Problembeschreibung
Beim Test auf Nu kamen keine Keywords mit.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kyushutea** [comment]
Funktioniert, danke!
