### ISSUE TITLE
SSOAR_MARC 21 Feld 773 subfield code="7"

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#21]
Es kommt insgesamt 23 mal vor und zwar immer dann , wenn "Historical Social Research" das übergeordnete Sammelwerk ist.
Der Inhalt ist immer "nnas",
wobei das "s" an der 4. Stelle darauf verweist, dass das übergeordnete Werk ein Sammelwerk ist.

   1.  Die 1., 2., und 3. Stelle ist in der MARC 21 Dokumentation bisher jedoch nur als Füllzeichen definiert.
    Woher also die ersten drei Buchstaben "nna"?

   2.  wieso gibt es das subfield code="7" nur dann, wenn "Historical Social Research" das übergeordnete Sammelwerk ist?

**Comment by ruschein** [comment]
@kdr154 Ihre Fragen können nur von SSOAR beantwortet werden.  Wir erzeugen die Daten nicht sondern reichen die Daten nur so durch wie wir sie von SSOAR bekommen.

**Comment by IxTheoKm** [comment]
field code="7"\>nnas\</subfield\> kann m.E. entfallen. 
Das übergeordnete Sammelwerk wird durch Subfield w verlinkt, dadurch ist eine "Definition" des übergeordneten Werk in Subfield 7 nicht nötig.

**Comment by IxTheoKm** [comment]
Bitte 773 <subfield code="7">nnas</subfield> löschen

**Comment by IxTheoKm** [comment]
In Ordnung
