### ISSUE TITLE
ISSN 1869-3296 Journal of Ancient Judaism Tabulatoren im Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#210]
halbautomatisches Verfahren
Bei dieser Zeitschrift werden beim Abstract eine Unmenge von Tabulatoren übertragen. Diese sind überflüssig und führen zum Abbruch in der WinIBW.

**Comment by shadeMe** [comment]
Ich brauche ein Beispiel fürs Testing.

**Comment by kdr154** [comment]
Hier z. B.:
https://www.vr-elibrary.de/doi/abs/10.13109/jaju.2018.9.2.201#.XLhrPsRCRaQ
Das sieht im Browser und in Zotero ganz manierlich aus, aber wenn man den Satz in einen Editor kopiert, sieht man die vielen leeren Blöcke sofort

**Comment by shadeMe** [comment]
Hmm, ich kann es leider nicht reproduzieren. Wenn ich mich richtig dran erinnere, habe ich dieses Problem schon behoben. Ist der Translator aktuell? In der neuesten Version des Translators sollte der Text ```x.textContent.replace(/\s+/g, " ")``` in Zeile 243 stehen.

![Screenshot_20190418_150650](https://user-images.githubusercontent.com/214450/56363092-b0077b80-61eb-11e9-8dec-1d45fb7c2625.png)

**Comment by kdr154** [comment]
Der aktuelle tuts
