### ISSUE TITLE
ISSN 2699-8440 | Sexual Offending | Rezensionserkennung

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2100]
#### URL
https://sotrap.psychopen.eu/index.php/sotrap/article/view/12693

  
### Problembeschreibung

Beim Test auf Nu wurden keine Rezensionen erkannt.

**Comment by jriedl** [comment]
Auf nu

**Comment by kyushutea** [comment]
Funktioniert, danke!
