### ISSUE TITLE
ISSN 2699-8440 | Sexual Offending | ORCID

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2101]
#### URL
https://sotrap.psychopen.eu/index.php/sotrap/article/view/9965

  
### Problembeschreibung

ORCIDs der Personen kommen nicht mit.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kyushutea** [comment]
Danke, auf nu funktionierts. Können Sie es auch für ub28 freischalten?

**Comment by kyushutea** [comment]
Funktioniert, danke!
