### ISSUE TITLE
ISSN 1573-0751| Crime, Law and Social Change (Springer) | OF als Error 

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2102]
#### URL
https://link.springer.com/article/10.1007/s10611-024-10149-7

  
### Problembeschreibung

Die Online First Artikel landen auf nu in den Errors (gelb), sollten aber eigentlich schwarz sein.

**Comment by jriedl** [comment]
Das Vorhandensein von Seitenangaben verhindert eine Kennzeichnung als OF (das wurde in einem anderen Kontext offenbar mal extra so definiert). Diese werden aber hier vom Verlag mitgeliefert wird, auch wenn hier offenbar der Umfang codiert wird:
![image](https://github.com/ubtue/DatenProbleme/assets/13135579/ddac4e90-82a3-498b-95e1-6e210d26c8ab)
Es ist m.E. nicht sinnvoll, hier die Kriterien wieder zu verändern.

**Comment by kyushutea** [comment]
Gelöst durch: https://github.com/ubtue/DatenProbleme/issues/2023#issuecomment-2095910706
