### ISSUE TITLE
ISSN 2413-3108 | South African crime quarterly (OJS) | ORCIDs fehlen

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2103]
#### URL
https://journals.assaf.org.za/index.php/sacq/article/view/12891

KrimDok#2024-04-11#C96EE63FDC83F64BBDA7C91921F7ED2582659B76
  
### Problembeschreibung

Bei der Einspielung in die Test-DB fehlen die ORCIDs.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kyushutea** [comment]
Danke, auf nu funktionierts. Können Sie es auch für ub28 freischalten?

**Comment by kyushutea** [comment]
Funktioniert, danke!
