### ISSUE TITLE
ISSN 2413-3108 | South African crime quarterly (OJS) | Rezenionserkennung

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2104]
#### URL
https://journals.assaf.org.za/index.php/sacq/article/view/6347
   
### Problembeschreibung
Beim Test auf nu wurde diese Rezension nicht erkannt. Es gibt kein Titelmuster für Rezensionen.

**Comment by jriedl** [comment]
Auf nu.

**Comment by kyushutea** [comment]
Danke, auf nu funktionierts. Können Sie es auch für ub28 freischalten?

**Comment by kyushutea** [comment]
Funktioniert, danke!
