### ISSUE TITLE
ISSN 2590-3268 | NTT Journal for Theology and the Study of Religion (AUP) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2105]
#### URL
https://www.aup-online.com/content/journals/25426583/browse
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_AUP.js

  
### Problembeschreibung
Die Aufsätze werden alle als "Eintragsart Website" importiert. Dadurch fehlen in Zotero einige Felder wie bspw. die notwendige ISSN.
Auch die ORCID (Bsp. https://doi.org/10.5117/NTT2024.1.001.KELL) scheint momentan nicht importiert zu werden.

(Gemeldet von @IxTheoEg)

**Comment by mara-spiess** [comment]
Für diesen Translator sind Anpassungen im größeren Stil notwendig, um auch die anderen Zeitschriften des Verlags bearbeiten zu können.

**Comment by mara-spiess** [comment]
@IxKo Kann überprüft werden ob die vier Zeitschriften die aktuell auf Zeder für diesen Translator angegeben sind, aktuell sind?

**Comment by IxKo** [comment]
> @IxKo Kann überprüft werden ob die vier Zeitschriften die aktuell auf Zeder für diesen Translator angegeben sind, aktuell sind?

Wir werten laut ZEDER aktuell 3 Zs. mit dem Translator aus (ZEDER-Abfrage: kat=jkl prodf=zotk !ever:dis p_zot3:aup)

- 376 ist aktuell
- 601 müsste das aktuelle Heft noch erfasst werden
- 2734 müssen viele Hefte nacherfasst werden (gehört zu diesem Issue)

**Comment by mara-spiess** [comment]
Issue identisch zu https://github.com/ubtue/DatenProbleme/issues/2049

**Comment by mara-spiess** [comment]
Der Translator sollte nun für alle drei ZS alle relevanten Angaben importieren. Bitte auch den identischen Issue testen/schließen.

**Comment by IxKo** [comment]
Band, Heft und Jahr werden noch nicht importiert.

Zudem wird bei den Rezensionen ein Pseudo-Abstract importiert, könnte das nicht importiert werden?

**Comment by mara-spiess** [comment]
Die Informationen sollten nun vollständig sein.

**Comment by IxKo** [comment]
Vielen Dank, passt alles!
