### ISSUE TITLE
ISSN 2363-9849 | Journal for Deradicalization (OJS/PKP) | Fehlendes Abstract

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2108]
#### URL
https://journals.sfu.ca/jd/index.php/jd/article/view/809

  
### Problembeschreibung
Bei der Einspielung in die Test-DB fehlt das Abstract.

**Comment by jriedl** [comment]
Sollte  im Rahmen des Anpassungen für #2099 ebenfalls behoben sein.

**Comment by jriedl** [comment]
Würde ein Update auf ub28 vornehmen, sobald die anderen "ready for testing" durch sind. Wenn keine inhaltlichen Punkte offen sind, muss übrigens "back to IT" nicht gesetzt werden.

**Comment by jriedl** [comment]
Danke für's Testen und die Entfernung des Labels. Die Gesamtheit der Translatoränderungen findet sich nun auch auf ub28.

**Comment by kyushutea** [comment]
Funktioniert, danke!
