### ISSUE TITLE
ISSN 2363-9849 | Journal for Deradicalization (OJS/PKP) | Fehlende Keywords

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2109]
#### URL
https://journals.sfu.ca/jd/index.php/jd/article/view/809
 

  
### Problembeschreibung

Bei der Einspielung in der Test-DB wurde pro Artikel nur ein Keyword übernommen.

**Comment by jriedl** [comment]
Auf nu jetzt Version von EM, die im Gegensatz zum Standardverhalten des Übersprungens der EM-Keywords bei vorhandenen RDF-Keywords diese dennoch ausliest, falls nur höchstens ein Keyword vorhanden ist.

**Comment by kyushutea** [comment]
Danke, auf nu funktionierts. Können Sie es auch für ub28 freischalten?

**Comment by kyushutea** [comment]
Funktioniert, danke!
