### ISSUE TITLE
ISSN 1703-289X The Journal of Religion and Popular Culture Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#211]
Halbautomatisches Verfahren
Hier kommen die Keywords nicht mit

**Comment by shadeMe** [comment]
@kdr154 Kannst Du bitte auch eine oder zwei Beispiel-URLs zusätzlich in die Issues reinschreiben, die sich um das Halbautomatisches Verfahren handeln? Das wäre sehr hilfreich beim Testing.

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift sehe ich keine Keywords auf der Webseite ([Ausgabe](https://muse.jhu.edu/issue/40201)). Wo kann ich sie finden?

**Comment by kdr154** [comment]
Ich nehme eine andere Quelle:
https://www.utpjournals.press/loi/jrpc
Das ist im Übrigen auch der eigentliche Publisher

**Comment by kdr154** [comment]
Weiterhin keine Keywords

**Comment by kdr154** [comment]
Kommen jetzt doch
