### ISSUE TITLE
ISSN 1550-4409 | Applied Psychology in Criminal Justice (SHSU) | Neuer Translator

### ISSUE THREAD

**Issue by kyushutea** [ubtue/DatenProbleme#2111]
#### URL
https://apcj.shsu.edu/journal/index.php?mode=view&item=168
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Es wird kein Import Translator angeboten. Könnte einer entwickelt werden?

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_APCJ

**Comment by mara-spiess** [comment]
Kleine Verbesserungen wurden implementiert.

**Comment by kyushutea** [comment]
Translator funktioniert, danke!
