### ISSUE TITLE
ISSN 2509-9965 | International Journal of Latin American Religions (Springer) | Mehrfach-Import

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2117]
#### URL
https://link.springer.com/journal/41603/volumes-and-issues/7-2
  
#### Import-Translator
Einzelimport:
ubtue_Springer Link.js

  
### Problembeschreibung
Könnte für diese Seite ein Mehrfachimport angeboten werden? Ein Einzel-Import wird angeboten.

Mindestens 8 weitere Zs. könnten davon betroffen sein (ZZ: 367, 823, 1042, 1428, 1430, 1525, 1754, 1877)

**Comment by Martina-Dae** [comment]
Bitte prüfen

**Comment by IxKo** [comment]
Vielen Dank, passt.
