### ISSUE TITLE
ISSN 1573-6679 | Pastoral Psychology (Springer) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2118]
#### URL
https://doi.org/10.1007/s11089-023-01119-2
  
#### Import-Translator
  Einzelimport:
ubtue_Springer Link.js

### Problembeschreibung
Es werden von 6 ORCID-Angaben nur 3 importiert:

![image](https://github.com/ubtue/DatenProbleme/assets/57000004/c700a13d-7ca6-45f6-b466-1ec94341f96b)

**Comment by Martina-Dae** [comment]
Sollte jetzt funktionieren.

**Comment by IxKo** [comment]
Bei mir werden momentan noch immer nur 3 ORCIDs importiert.
Der Translator ubtue-Springer Link.js scheint in meinem Verzeichnis aber auch noch nicht aktuell, wenn ich das richtig sehe.

**Comment by Martina-Dae** [comment]
@mara-spiess kannst du die Verzeichnisse aktualisieren?

**Comment by socheres** [comment]
Die Verzeichnisse wurden von mir akutalisiert.

**Comment by IxKo** [comment]
Danke, alle 6 ORCIDs kommen nun korrekt mit:
![image](https://github.com/user-attachments/assets/b5f12197-c54c-4353-9feb-ca32c555ba2b)
