### ISSUE TITLE
ISSN 2326-2176 | Journal of the Society of Christian Ethics (PDC) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2121]
#### URL
https://doi.org/10.5840/jsce202412394
https://www.pdcnet.org/jsce/content/jsce_2023_0043_0002_0267_0288
  
### Problembeschreibung
Die ORCID wird auf nu und ub28 nicht erzeugt.

- [x] nu
- [x] ub28

**Comment by jriedl** [comment]
Auf nu. Fälle mit mehreren Autoren und nur einem vorhandenen ORCID-Link werden dem letzten Autor zugeorndet (vgl. z.B. https://www.pdcnet.org/jsce/content/jsce_2023_0043_0002_0399_0415), Fälle mit mehreren ORCID-Angaben haben sich aktuell nicht finden lassen, hier würde die ORCID-Extraktion nicht ausgeführt.

**Comment by IxKo** [comment]
Ein Beispiel mit mehr als einer ORCID scheint es noch nicht zu geben, es ist aber für die Zukunft nicht auszuschließen.

Was nicht funktioniert:
Es kann nicht pauschal eine ORCID der letztgenannten Person zugeordnet werden. Dadurch entstehen falsche Zuordnungen.
Beispiel: https://www.pdcnet.org/jsce/content/jsce_2020_0040_0002_R007_R009
![image](https://github.com/ubtue/DatenProbleme/assets/57000004/631dd20d-276f-4e78-9d0c-6fbe9becbadf)

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Danke
