### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion (Springer) | OF

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2122]
#### URL
https://doi.org/10.1007/s11153-024-09904-6
Hash: 16CA0D871F0F21B53808CC45869BA287B975B509
  
  
### Problembeschreibung
Die OF-Artikel landen in den Errors. Auch das conf-Feld "pages_not_online_first = true" zu hinterlegen, hat an dem Status bisher nichts geändert.
Die OF-Artikel haben Seitenangaben, aber keine Band- und Heftzählung.

Was müsste erst angepasst werden, damit sie auf Zotero Harvesting als OF markiert werden?

**Comment by jriedl** [comment]
`pages_not_online_first = true` hat ja aber den gegenteiligen Effekt, d.h. ein Artikel, der eigentlich OF ist, ist es nicht, weil plausible Seitenangaben vorhanden sind. Das ist hier der Fall. D62E0C4BAF36EF03B90F9FBAAC79D566D04B8A86, der am 10.5. das letzte Mal heruntergeladen wurde, hat ebenfalls bereits ein PNO-Tag. Das sollte eigentlich nur der Fall sein, wenn `pages_not_online_first = true`. Wann wurde das erstmalig gesetzt?

**Comment by IxKo** [comment]
Am 15.5. habe ich `pages_not_online_first = true` erstmalig gesetzt.
Davor waren sie aber auch schon nicht als OF im Harvester gekennzeichnet, sondern in den Errors.
Aber ich scheine die Information zu `pages_not_online_first` in der conf missverstanden zu haben. Ich entferne es bei der Zs. wieder.
Allerdings bleibt dann das Problem wie davor, dass die OF-Artikel in den Errors landen.

**Comment by jriedl** [comment]
Es konnten Fälle auftreten, in denen das PNO-Tag erzeugt wurde, obwohl `pages_not_online_first` nicht gesetzt war. Eine angepasste Version findet sich nun auf nu und ub28.

**Comment by IxKo** [comment]
Es sieht wieder weniger gelb auf ub 28 aus.
Nur beim ""International journal for philosophy of religion" ist noch ein einzelner gelber Punkt, der meiner Meinung da nicht hingehört: Hash D62E0C4BAF36EF03B90F9FBAAC79D566D04B8A86

**Comment by jriedl** [comment]
Das ist so ein Beispiel für eine "Artikelleiche". Der zugehörige Datensatz wurde am 10.5. das letzte Mal heruntergeladen und ist nun offenbar aus dem Feed verschwunden, d.h. er wird voraussichtlich in diesem Zustand bleiben. Möglichkeiten sind entweder, ihn auf "Delivered manually" zu setzen oder ihn händisch aus der DB zu löschen.

**Comment by jriedl** [comment]
Der Eintrag D62E0C4BAF36EF03B90F9FBAAC79D566D04B8A86 ist nun entfernt.

**Comment by IxKo** [comment]
Vielen Dank, es sieht nun alles wieder super auf ub28 aus!

Nur eine Frage zu der "Artikelleiche":
Wenn man diese auf delivered manually gestellt hätte, und irgendwann wäre der Artikel nochmals im Feed gekommen und diesmal einem Heft zugeordnet: Wäre er dann nochmals auf ub28 aufgetaucht?

Bei der Kriminologie gibt es nämlich noch eine solche Leiche: ISSN 1936-1351 | American journal of criminal justice | Hash CF91629616AF28FEED81BAF73372422A713D8F57

**Comment by jriedl** [comment]
"Delivered manually" bedeutet, dass der entsprechende Artikel vom automatischen Verfahren dauerhaft nicht mehr beachtet wird. Ich habe den Record nun aus der DB entfernt, d.h. sollte er tatsächlich zukünftig wieder auftauchen, sollte er ganz normal eingespielt werden.

**Comment by IxKo** [comment]
> Ich habe den Record nun aus der DB entfernt, d.h. sollte er tatsächlich zukünftig wieder auftauchen, sollte er ganz normal eingespielt werden.

Vielen Dank!

Info @kyushutea
