### ISSUE TITLE
ISSN 2397-1770 | Quaker Studies (openlibhums) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2124]
#### URL
https://quakerstudies.openlibhums.org/issue/1243/info/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung

Ist es möglich für diese Plattform einen Translator bereitzustellen?

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_Quaker_Studies.js

**Comment by IxKo** [comment]
Danke, funktioniert schon sehr gut!

Könnte die Zusatzzeile mit Punkt im Abstract eventuell noch entfernt werden?
![image](https://github.com/user-attachments/assets/b8d37d0a-fb0b-4fcb-9dc9-c728de1a2f53)

**Comment by IxKo** [comment]
Und [hier](https://doi.org/10.3828/quaker.2023.28.2.5) hat es Keywords etwas zerrissen. Kann das Translator-seitig behoben werden?
![image](https://github.com/user-attachments/assets/2469a836-c856-48d2-8f70-301f52351fbe)

**Comment by mara-spiess** [comment]
Da es sich bei den Keywords um einen Einzelfall handelt, würde ich hier keine Änderung im Translator implementieren. Bei allen anderen Artikeln ist das Format der Keywords standarditisiert, hier scheint es sich wirklich nur um einen vereinzelten Fehler des Autors zu handeln.

**Comment by mara-spiess** [comment]
Das Abstract sollte jetzt bereinigt sein.

**Comment by IxKo** [comment]
Danke, passt nun!
