### ISSUE TITLE
ISSN 2199-4625 | Journal of Religious Education (Springer) | Rezensionserkennung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2129]
#### URL
https://doi.org/10.1007/s40839-024-00223-6
IxTheo#2024-06-06#E1775636F6476BE307A19D8E0EE8AED842B15741
  
  
### Problembeschreibung
Die Rezension wurde nicht erkannt. Es gibt kein Titelmuster.

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Danke, funktioniert auch schon auf ub28
