### ISSUE TITLE
Zeder ID 830 ISSN 1871-7691 PentecoStudies Metadaten lassen sich nicht von Equinox herunterladen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#213]
Bisher katalogisieren wir über EBSCO (Academic Search Premier). Das ist aber umständlich, insofern wir das Abstract von Equinox (url1) übernommen haben. 
Equinox bietet aber auf der Seite eines einzelnen Aufsatzes Dublin Core Metadaten an, die perfekt sind. Es ist bis jetzt aber nicht möglich, alle Metadaten von Equinox zu übernehmen. Wenn man die Daten von der Seite mit den Dublin Core Metadaten übernimmt, fehlen Abstract und Keywords. Kann man da vielleicht was machen, dass Equinox als Quelle genommen werden kann?

**Comment by thefass** [comment]
Equinox als Verlag ist auf jeden Fall eine bessere und zukunftssicherere Quelle als Ebsco als Aggregator. Zudem wir noch andere Equinox Zss haben.

**Comment by shadeMe** [comment]
Gibt es Beispiele, wobei die Abstract und Keywords fehlen?

**Comment by kdr154** [comment]
Nehmen wir mal folgende Ausgabe:
https://www.equinoxpub.com/home/journals/PENT/PENT-view-issue/?id=2527
und davon folgenden Artikel, denn Multi geht nicht:
https://www.equinoxpub.com/home/journals/PENT/PENT-view-abstract/?id=32072
Dort befindet sich links unten der Button Dublin Core Metadata View Metadata
Clickt man darauf öffnet sich folgende Seite:
https://www.equinoxpub.com/home/journals/PENT/PENT-view-abstract/?id=32072
Diese kann man über den Zotero Connector des Browsers in Zotero speichern
Die Seite zeigt alles an, was man benötigt. 
In Zotero fehlen dann aber das Abstract und die Keywords. Beides als Metadata items auf obiger Seite gekennzeichnet

**Comment by kdr154** [comment]
Abstract und Keywords fehlen weiterhin

**Comment by shadeMe** [comment]
Auf meinem Rechner, kommen sie schon mit. Ist der lokale Translator aktuell?

![Screenshot_20190619_103434](https://user-images.githubusercontent.com/214450/59749832-0e011f80-927e-11e9-9047-8a564a55afc3.png)
![Screenshot_20190619_103452](https://user-images.githubusercontent.com/214450/59749861-19ece180-927e-11e9-90ab-792ea597748e.png)

**Comment by kdr154** [comment]
Ist aktuell, aber der Equinox-Translator wird in diesem Fall gar nicht aktiviert

**Comment by shadeMe** [comment]
Ist es immer noch der Fall, dass der Equinox-Translator nicht aktiviert?

**Comment by kdr154** [comment]
Ist aktiviert und Abstract und Keywords sind dabei. Allerdings dauert es sehr lange, bis der Translator aktiviert wird
