### ISSUE TITLE
ISSN 2791-4658 | Ex fonte (OJS) | Schlagwörter

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2132]
#### URL

Testdaten: IxTheo#2024-06-11#206520FC2476BB7BF2259AA5FA7C81534BC507F0
https://doi.org/10.25365/exf-2024-3-2
  
### Problembeschreibung

Die Schlagwörter werden nicht nach MARCXML portiert.

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Vielen Dank, passt. Bitte noch auf ub8, danke!

**Comment by jriedl** [comment]
Aktueller Stand der Translators nun auf ub28.

**Comment by IxKo** [comment]
Danke, passt!
