### ISSUE TITLE
ISSN 0033-1767 | Protestantesimo (EBSCOhost) | Translator-Fehler

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2134]
URL
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3dreh%26AN%3dATLAiFZK240506000003%26site%3dehost-live

Import-Translator
Einzel- und Mehrfachimport:
ubtue_EBSCOhost.js

Problembeschreibung
Der Translator bringt sowohl im Mehrfach- als auch im Einzel-Import eine Fehlermeldung.

(gemeldet von @IxTheoEg)

siehe auch #2133

**Comment by IxKo** [comment]
Gleiches Problem auch bei einer anderen EBSCO-Zs.
Der Translator müsste dringend angepasst werden, da wir sehr viele Zs. darüber erfassen (lt. ZEDER 58 insgesamt).

**Comment by jriedl** [comment]
Anmerkung: Das vorherige Verhalten mit dem Fehler scheint  nicht der Zotero-eigenen Doku (https://www.zotero.org/support/dev/translators/coding#web_translators) zu entsprechen: 

"`Zotero.Utilities.xpath(elements, xpath, [namespaces])`
Evaluates the specified XPath on the DOM element or array of DOM elements given, with the optionally specified namespaces. If present, the third argument should be object whose keys represent namespace prefixes, and whose values represent their URIs. Returns an array of matching DOM elements, or null if no match. (Added in Zotero 2.1.9)"

Falls sich hier das Verhalten möglicherweise in späteren Versionen wieder ändert, sollte wahrscheinlich noch defensiver getestet werden: 
```js
if (abstractCandidates && abstractCandidates.length) ...
```

**Comment by IxKo** [comment]
Danke, funktioniert nun.
