### ISSUE TITLE
ISSN 0020-9643 | Interpretation (SAGE) | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2136]
#### URL

- https://doi.org/10.1177/00209643241244455

IxTheo#2024-06-17#FF4E6357FD249B9840BD73A2F819EAB0CE22C64E

- https://doi.org/10.1177/00209643241244452

IxTheo#2024-06-17#4997591AF61984E35EFE14660CC8FECFD4DCF1DD

  
### Problembeschreibung

Die beiden Rezensionen wurden nicht mit 1131 Rezension eingespielt.
Es existiert kein Titelmuster.

**Comment by jriedl** [comment]
Auf nu.

**Comment by IxKo** [comment]
Vielen Dank, klappt auf nu, bitte noch auf ub28.

**Comment by jriedl** [comment]
Aktueller Stand auf ub28.

**Comment by IxKo** [comment]
Vielen Dank!
