### ISSUE TITLE
ISSN 1860-8213 | bildungsforschung (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2137]
#### URL
https://bildungsforschung.org/ojs/index.php/bildungsforschung/article/view/996
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die ORCID von Herrn Wegner wurde falsch Frau Wahner zugewiesen.

**Comment by socheres** [comment]
Der Fehler liegt im Quelltext, daher kann der Translator ihn nicht beheben. Die ORCID wird dem Namen zugeordnet, der direkt davor steht. Da diese Zeitschrift bisher keine ORCID vergeben hat, sollten wir den Fehler weiterhin beobachten. Also, Issue noch nicht schließen.

**Comment by IxKo** [comment]
#2175
