### ISSUE TITLE
ID 2296 ISSN 0031-8159 Philosophische Rundschau Abstract, Sprache, URL

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#214]
Ein Translator für folgende Zeitschrift wäre ein Gewinn:
https://www.mohrsiebeck.com/zeitschrift/philosophische-rundschau-phr
Beim Einzeldownload fehlen jetzt Abstract, Sprache und URL

**Comment by ruschein** [comment]
@kdr154 Warum wäre es ein Gewinn?  Ist das Volumen groß?  Gibt es andere Zeitschriften, die wir wollen, die die gleiche Seiten struktur aufweisen? ...

**Comment by kdr154** [comment]
Ein Gewinn wäre es insofern, dass man diese Dinge nicht alle per c&p händisch übertragen muss, zudem nicht all die Fehler, die trotzdem noch drin sind, e.g. unvollständige Seitenzahlen korrigieren muss. Ich bin einigermaßen erstaunt. Werde aber in Zukunft anders formulieren. Etwa: hier muss sofort ein Translator erstellt werden, und zwar einer, der auch gleich beim ersten Mal funktioniert ....
Ich gehe davon aus, dass alle Zeitschriften, die bei Mohr Siebeck erscheinen, die gleiche Struktur aufweisen. Meine aber man kann dann nicht davon ausgehen, dass die Daten bei allen Zeitschriften von diesem Verlag einwandfrei sind. Wenn ich nur daran denke, wie das bei Equinox läuft. Bei jeder Zeitschrift muss dort der Translator neunangepasst werden.

**Comment by kdr154** [comment]
Auch Mohr Siebeck:
https://www.mohrsiebeck.com/en/journal/religion-in-the-roman-empire-rre
hier fehlt das Abstract

**Comment by kdr154** [comment]
Es hat sich nichts verändert

**Comment by shadeMe** [comment]
Bitte den 'ubtue_Mohr Siebeck.js' Translator nochmal aktualisieren.

**Comment by kdr154** [comment]
Es hat sich weiterhin nichts geändert

**Comment by shadeMe** [comment]
Oh je! Das ist wahrscheinlich das Problem, wobei der Zotero-Browser-Connector den richtigen Translator nicht erkennt. Ich habe dafür keine Lösung bisher gefunden, die konsistent funktioniert. Manchmal geht es, wenn man den Browser und Zotero-Client in einer bestimmten Reihenfolge neustartet aber manchmal doch nicht. Ich kann nur vorschlagen, dass du immer wieder versuchst.

**Comment by kdr154** [comment]
Bei neueren Versuchen wurde der richtige Translator genommen.
