### ISSUE TITLE
ISSN 1095-9270 | The International Journal of Nautical Archaeology (T&F) | Lizenz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2141]
#### URL
https://doi.org/10.1080/10572414.2023.2295670
  
#### Import-Translator
  Einzel- und Mehrfachimport:
{ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung

Der Artikel wird mit Notiz LF importiert. Er ist aber nicht lizenzfrei.

Das hier wäre ein LF-Artikel der Zs.: https://doi.org/10.1080/10572414.2023.2295466

**Comment by mara-spiess** [comment]
Leider kann ich diesen Fehler nicht rekreieren, bzw. wird keiner der beiden Artikel bei mir mit der Notizen LF exportiert. @jriedl Wurde hier schon etwas gemacht oder das Label "ready for testing" nur versehentlich vergeben?

**Comment by jriedl** [comment]
Ich war wegen #2140 ursprünglich davon ausgegangen, dass sich der Fehler auch auf zotaut bezieht und wollte als Feedback geben, dass sich der Fehler hier (ebenfalls) nicht nachvollziehen lässt. Dann fiel auf, dass dieses Issue nur als zotkat gelabelt ist. Deshalb war das "ready for testing" nur kurz gesetzt.

**Comment by mara-spiess** [comment]
@IxKo Besteht dieser Fehler bei der Bearbeitung in zotk immer noch?

**Comment by IxKo** [comment]
Danke, behoben!
