### ISSUE TITLE
ISSN 1092-1311 | Journal of Religion & Film | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2142]
#### URL
https://digitalcommons.unomaha.edu/jrf/vol28/iss1/
  
#### Import-Translator
  Einzelimport:
Embedded Metadata.js

  
### Problembeschreibung

Könnte für diese Zs. bitte ein Mehrfach-Importtranslator angeboten werden?

**Comment by IxKo** [comment]
Die Artikel haben Artikel-IDs.

**Comment by mara-spiess** [comment]
Neuer Translator: ubtue_Journal_Religion_Film

**Comment by IxKo** [comment]
Danke, passt!
