### ISSUE TITLE
ISSN 1868-7377 | Zeitschrift für Theologie und Kirche (Mohr Siebeck) | Translatorabbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2143]
#### URL
https://www.mohrsiebeck.com/heft/zeitschrift-fuer-theologie-und-kirche-2-2024-0044-3549/
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Mohr Siebeck.js

  
### Problembeschreibung
Ein Import der Daten ist sowohl im Mehrfach- als auch Einzel-Import nicht möglich.

**Comment by coeh** [comment]
Mohr Siebeck hat kürzlich seine Website neu aufgesetzt und kämpft dort insgesamt noch mit diversen "Kinderkrankheiten". Möglicherweise ist auch dieses Problem dadurch verursacht.

**Comment by mara-spiess** [comment]
@jriedl Der aktuelle Translator scheint sich an einer veraltete Version der Webseite zu orientieren. Mit Embedded Metadata bekommt man bereits sehr gute und vollständige Ergebnisse, weshalb mein Vorschlag wäre einen neuen Translator basierend auf EM zu schreiben, der dann auch den Mehrfach Import ermöglicht und eventuell Kleinigkeiten anpasst.

**Comment by jriedl** [comment]
Ok. Für die Einzelartikel bekommt man die Informationen über EM, für multiple scheint es auf den ersten Blick nur recht generische Selektoren zu geben, aber damit muss man wohl leben. Da ja davon auszugehen ist, das der alte Translator ohnehin dauerhaft nicht mehr funktioniert, kann die alte Datei für den neuen Translator verwendet werden.

**Comment by mara-spiess** [comment]
Der Translator sollte nun wieder funktionieren.

**Comment by IxKo** [comment]
Danke, Import funktioniert!
