### ISSUE TITLE
ISSN 0386-720X | Bulletin of the Nanzan Institute for Religion and Culture | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2145]
#### URL
https://nirc.nanzan-u.ac.jp/journal/3/issue/347
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_nirc.js

  
### Problembeschreibung

Der Import bricht ab.

**Comment by IxKo** [comment]
Danke, geht wieder!

**Comment by IxKo** [comment]
Noch eine Kleinigkeit mit großer Auswirkung:
Könnte beim Import die ISSN 0386-720X importiert werden?

Momentan wird die ISSN 0304-1042 importiert, die zu einer anderen Zs. (Japanese journal of religious studies) gehört.

**Comment by mara-spiess** [comment]
ISSN sollten jetzt korrekt importiert werden. Falls andere Zeitschriften des Verlages bearbeitet werden sollen bitte Bescheid geben, damit für diese noch die korrekte ISSN im Translator hinterlegt werden kann.
