### ISSUE TITLE
ISSN 1568-5195 | Islamic Law and Society | falsche Kennzeichnung LF 

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2146]
#### URL
https://doi.org/10.1080/13537903.2024.2378601
  
#### Import-Translator
  Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung
Der Artikel wird mit der Notiz "LF:" importiert, obwohl er auf der Seite nicht als OA gekennzeichnet und auch nicht frei zugänglich ist.

**Comment by jriedl** [comment]
Anmerkung, da die Zeitschrift regulär im Zotaut-Verfahren ist: Hier lässt sich der Fehler nicht reproduzieren:
![image](https://github.com/user-attachments/assets/5034c911-9fbb-4950-8cd7-6443af773757)

**Comment by IxKo** [comment]
Ja, das hatte ich geprüft, sonst hätte ich zusätzlich auch ein Label für das vollautomatische Verfahren vergeben.
Oder sollte besser auch der Ausschluss vom jeweils anderen Verfahren genannt werden?

**Comment by jriedl** [comment]
Nein, alles gut. Ich hatte es aufgrund der Mail geprüft, da sind die Labels ja nicht erkennbar, und erst dann gesehen, dass es nur zotkat-gelabelt ist. Damit die Information, dass der zotaut-Translator das Problem nicht zeigt, nicht verloren geht, habe ich mich dann aber entschieden, trotzdem einen Kommentar zu schreiben.

**Comment by mara-spiess** [comment]
Identisch zu https://github.com/ubtue/DatenProbleme/issues/2141

**Comment by IxKo** [comment]
Danke, wird nicht mehr als LF gekennzeichnet!
