### ISSUE TITLE
ISSN 1743-1670 | Black theology (T&F) | Importabbruch

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2148]
#### URL
https://www.tandfonline.com/doi/full/10.1080/14769948.2020.1792744
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
### Problembeschreibung
Der Import funktioniert nicht.
![image](https://github.com/user-attachments/assets/ae72f1ff-9bf8-43be-bad3-f1a14a73cb3a)
![image](https://github.com/user-attachments/assets/434ab7d3-4c89-434c-9256-f2d422d6d502)

**Comment by mara-spiess** [comment]
Es scheinen alle Zeitschriften der Plattform Taylor & Francis betroffen zu sein.

**Comment by jriedl** [comment]
Der T & F-Translator versucht Bibtex & RIS Zitationen herunterzuladen. Das schlägt fehl. Wenn man die entsprechende POST-Abfrage mit curl simuliert, werden eine ganze Reihe u.a. Cloudflare-Scripte ausgespielt. Ein Download über den Browser schlägt hier lokal ebenfalls fehl (evtl Bezug zu  dem in  #2140 Beschriebenen):
https://www.tandfonline.com/action/downloadCitation => nach z.B. 10.1080/10572414.2023.2295670 suchen => explizit anwählen = > "Download citations" => RIS Format =>
![image](https://github.com/user-attachments/assets/65a9d721-dbe2-403e-a086-e8497e09a968)

**Comment by jriedl** [comment]
@socheres: Kann evtl. mit T&F abgeklärt werden, ob ein skriptbasierter Zugriff auf den "Citation Manager"  überhaupt noch unterstützt wird und falls nein, was eine Alternative wäre?  `curl -v -L -X POST -d 'downloadFileName=citation&direct=true&include=abs&doi=10.1080/10572414.2023.2295670&format=ris' https://www.tandfonline.com/action/downloadCitation` liefert lokal HTTP 500, auf zwar HTTP 200, aber dennoch keine sinnvollen Ergebnisse, sondern ebenso wieder eine Seite mit einer Unzahl an Scripteinbindungen. Zotaut ist von dem Problem ebenfalls betroffen, genauso der letzte Stand des "offiziellen" T&F-Translators von Zotero.

**Comment by socheres** [comment]
Der Atypon-Translator funktioniert auch nicht. Ich würde noch abwarten und dann bei T&F nachfragen. Hoffentlich nur ein temporäres Problem.

**Comment by jriedl** [comment]
Ok, aber selbet wenn die Server-Errors und Sperrungen zeitnah behoben werden sollten, stellt die scriptbasierte Erzeugung der Seite ein Problem dar.

**Comment by IxKo** [comment]
Danke, ja, es funktioniert wieder.
