### ISSUE TITLE
ISSN 2153-9650 bzw 1947-6566 The Journal of Medieval Religious Cultures DOI, Keywords, Eckige Klammern

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#215]
Halbautomatisches Verfahren
Bei dieser Zs gibt es die Möglichkeit, die Metadaten von JStor oder von Muse zu beziehen.
JStor: https://www.jstor.org/journal/jmedirelicult
Muse: http://muse.jhu.edu/issue/39841
Auf JStor findet man einen DOI und Keywords, beides fehlt auf Muse. Deshalb schlage ich vor, dass wir die Daten von JStor holen. 
JStor liefert allerdings die ISSN der Druckausgabe: 1947-6566
Man müsste bei JStor:
diese ISSN mit der PPN der Online-Ausgabe (=62761227X) verbinden
den DOI erfassen
die Keywords erfassen
dann ist das Abstract in eckige Klammern gefasst und es geht der Begriff ABSTRACT voraus.
Der Teil [ABSTRACT] sollte aus dem Abstract entfernt werden

**Comment by kdr154** [comment]
Das Abstract kommt jetzt mit. Die keywords fehlen weiterhin.

**Comment by kdr154** [comment]
Keywords fehlen weiterhin. Liegt es möglicherweise daran, dass sie hier Topics genannt werden?
https://www.jstor.org/stable/10.5325/jmedirelicult.45.1.0029?seq=1#page_scan_tab_contents

**Comment by shadeMe** [comment]
Bei mir werden sie mitgeliefert. Bitte nochmal prüfen, ob die aktuellste Version des Translators vom Browser verwendet wird.

![Screenshot_20190523_161603](https://user-images.githubusercontent.com/214450/58260067-139a4100-7d76-11e9-93e7-9aaf96284d0a.png)

**Comment by kdr154** [comment]
Passt jetzt
