### ISSUE TITLE
ISSN 0010-3713 | Communio viatorum (etf) | Translatorfehler

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2152]
#### URL
https://web.etf.cuni.cz/ETFN-752.html
  
#### Import-Translator
Mehrfachimport:
ubtue_etf.js
  
### Problembeschreibung

Der angebotene Translator gibt einen Fehler aus:
![image](https://github.com/user-attachments/assets/71f7c4b6-bf38-4710-8c72-5af1c96c170a)

(gemeldet von @IxTheoEg)

**Comment by mara-spiess** [comment]
Der Translator sollte nun wieder funktionieren.

**Comment by mara-spiess** [comment]
Nun sollten hoffentlich alle Hefte bearbeitet werden können :)

**Comment by IxKo** [comment]
Können sie nun, danke :-)
