### ISSUE TITLE
ISSN 0032-9622 | Proche-Orient chrétien (Cairn) | Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2154]
#### URL
https://shs.cairn.info/revue-proche-orient-chretien-2019-1?lang=fr
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Cairn.info.js

  
### Problembeschreibung
Es wird kein Translator mehr angeboten.
Eventuell hat sich die Website-Struktur geändert.

Betrifft auch 8 weitere Zs.

**Comment by mara-spiess** [comment]
@socheres Da das Layout der Website scheinbar komplett geändert wurde, wäre mein Vorschlag den bisherigen RIS-Translator mit einem Embedded Metadata Translator zu ersetzen, der schon nahezu fehlerfrei funktioniert.

**Comment by socheres** [comment]
ja, einverstanden.

**Comment by mara-spiess** [comment]
Der Translator sollte nun im Einzel- und Mehrfachimport funktionieren.

**Comment by IxKo** [comment]
Das Abstract wird nicht importiert (Bsp. https://shs.cairn.info/revue-proche-orient-chretien-2019-1-page-30?lang=fr&tab=resume)

**Comment by mara-spiess** [comment]
Nun sollten auch Abstracts importiert werden. Mehrere Abstracts werden getrennt: https://shs.cairn.info/revue-etudes-theologiques-et-religieuses-2024-2-page-313?lang=fr

**Comment by IxKo** [comment]
Danke, behoben.
