### ISSUE TITLE
ISSN 1745-5235 | Studies in Christian Ethics (SAGE) | OA

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2156]
- [x] zotk
- [x] zota nu
- [x] zota ub28

#### URL
https://doi.org/10.1177/09539468241258994
Hash: IxTheo#2024-09-10#2863899C44EA219BB434C57869E4652252D76B86
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_SAGE Journals.js

  
## zota
Der Datensatz ist OA, wurde allerdings nicht mit LF gekennzeichnet.

## zotk
Wird auch beim halbautomatischen Verfahren nicht als LF gekennzeichnet.

**Comment by jriedl** [comment]
Für zotaut auf nu.

**Comment by IxKo** [comment]
Danke, scheint bei den Stichproben-URLs, die ich auf nu mit TRY URL gemacht habe, zu funktionieren.

**Comment by mara-spiess** [comment]
OpenAccess Erkennung nun auch für ZotKat implementiert

**Comment by IxKo** [comment]
Danke wird auf ub28 und im halbautomatischen Zotero-Verfahren nun als LF gekennzeichnet.
