### ISSUE TITLE
ISSN 1918-6371 Toronto journal of theology Ausgabe, Band, Seiten, ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#216]
Halbautomatisch
Beim Download der Metadaten von folgender Seite: https://www.utpjournals.press/loi/tjt
fehlen Ausgabe, Band, Seitenzahlen und auch die ISSN, die leider nicht bei den einzelnen Bänden und Aufsätzen zu finden ist.

**Comment by shadeMe** [comment]
Ich kann gerade auf die verlinkte Webseite nicht zugreifen. Es scheint ein Server-Problem zu sein.

**Comment by shadeMe** [comment]
Sollte jetzt gehen.

**Comment by kdr154** [comment]
Ausgabe, Band, Seitenzahlen fehlen weiterhin. Zudem wird das Abstract abgeschnitten. Etwa bei folgendem Artikel:
https://www.utpjournals.press/doi/full/10.3138/tjt.2018-0005

**Comment by shadeMe** [comment]
Funktioniert wie erwartet auf meiner Seite. Wird die neueste Version des Translators (ubtue_University of Toronto Press.js) benutzt?

![Screenshot_20190524_112712](https://user-images.githubusercontent.com/214450/58317857-f5d0e880-7e16-11e9-938b-b1bcb2930788.png)

PS: Ein Vorschlag - Normalerweise verweise ich in jedem von mir bearbeiteten Issue auf den Pull-Request, der das Issue behebt. Es sieht so aus:
![Screenshot_20190524_113453](https://user-images.githubusercontent.com/214450/58318410-fc139480-7e17-11e9-9727-45dec1007ab8.png)

Wenn es auf der Seite "Merged" steht, kann man auf den Link klicken, um zu sehen, welche Dateien geändert wurden (dort steht eine "Files Changed" Ansicht). Die dort gezeigten Dateien sind diejenigen, die in deinem lokalen Verzeichnis aktualisiert werden müssen.

**Comment by kdr154** [comment]
Beim Einzeldownload wird nun der richtige Translator benutzt und die Daten sind damit auch gut und richtig.
Beim Multidownload greift das System bei mir auf den Atypon Translator zurück, welcher unzureichende Daten liefert. 
Vielleicht kann man das noch ändern?

**Comment by shadeMe** [comment]
Bei welcher Multidownload-URL geht es nicht? Ich habe es gerade über [diese URL](https://www.utpjournals.press/toc/tjt/34/2) probiert und der Zotero-Browser-Connector wählt den richtigen Translator beim Multidownload. Steht er überhaupt in der Liste, wenn du auf den Zotero Knopf rechtsklickst?

**Comment by kdr154** [comment]
Jetzt greift das System auf den richtigen Translator zurück, Universiy of Toronto Press. Aber es stimmt immer noch was nicht. Nun öffnet sich das Fenster zur Auswahl der Aufsätze zwei mal, wenn man alle auswählt. Dann werden die Daten auch zwei mal übertragen. Einmal sind sie korrekt, das 2. Paket ist fehlerhaft, wie mir scheint, mit den ursprünglichen Fehlern.
Wenn man gezielt Aufsätze auswählt, also nicht die Option "select all" wählt, ist alles gut.

**Comment by kdr154** [comment]
Alles gut stimmt nicht. Es fehlt die ISSN. Die ist aber auch nur auf der Eingangsseite zu finden, nicht bei den einzelnen Bänden oder Artikeln. 
Dieser Misstand lässt sich aber über eine Zuordnung von Zeitschriftentitel zur PPN umgehen. Wird bei den Peeters Zeitschriften auch so gemacht.

**Comment by shadeMe** [comment]
Das Problem mit dem Multidownload Fenster sollte jetzt behoben sein. Was die ISSN angeht, muss sie von dem Pica-Exporter ausgefüllt werden. Der Translator kann nur auf die Metadaten zugreifen, die bei den einzelnen Artikeln zu finden sind.

**Comment by kdr154** [comment]
Sieht jetzt alles gut aus bis auf den Umstand, dass gelegentlich Teile ins Abstract geraten, die wir nicht brauchen. Bei Artikeln wie diesen:
https://www.utpjournals.press/doi/abs/10.3138/tjt.2018-0115
wird der Teil "Video abstract .... see this video" auch ins Abstract integriert. Wenn es keinen Weg gibt, dies mittels des Translators zu eliminieren, schließen wir das Issue

**Comment by shadeMe** [comment]
Das schient nur bei dem "Embedded Metadata" Translator zu passieren. Auf meinem Rechner, liefert der UTP-Translator die richtige Zusammenfassung.

**Comment by kdr154** [comment]
Bei dem Versuch jetzt wurde der University of Toronto Press Translator genommen und bis auf die ISSN sind jetzt alle Daten vorhanden

**Comment by shadeMe** [comment]
Gut, dann können wir das Issue jetzt schließen, da wir mit der ISSN von der Seite des Translators nicht weitermachen können:

> Das Problem mit dem Multidownload Fenster sollte jetzt behoben sein. Was die ISSN angeht, muss sie von dem Pica-Exporter ausgefüllt werden. Der Translator kann nur auf die Metadaten zugreifen, die bei den einzelnen Artikeln zu finden sind.

**Comment by kdr154** [comment]
ok
