### ISSUE TITLE
ISSN 2532-2990 | The Journal of CESNUR | Fehlende Artikel im Import

### ISSUE THREAD

**Issue by ixtheoOr** [ubtue/DatenProbleme#2163]
#### URL
https://cesnur.net/archives/
  
#### Import-Translator
Mehrfachimport:
ubtue_cesnur.info.js
  
### Problembeschreibung
Das Heft 2024,4 hat 10 Artikel, davon werden nur 7 importiert.

**Comment by mara-spiess** [comment]
Dieser Translator funktioniert anhand der DOIs der Artikel. Leider funktionieren die DOIs der ersten drei Artikel in diesem Issue nicht - das ist entweder eine Frage der Zeit und sie werd in den kommenden Tagen noch freigeschaltet, oder ein Fehler den man bei der Zeitschrift melden muss.
