### ISSUE TITLE
ISSN 2053-6712 | Secularism and Nonreligion | Translator

### ISSUE THREAD

**Issue by ixtheoOr** [ubtue/DatenProbleme#2164]
#### URL
https://secularismandnonreligion.org/issue/archive
  
#### Import-Translator
Einzel und Mehrfachimport:
ubtue_Ubiquity Journals.js
  
### Problembeschreibung
Der Translator wird sowohl im Einzel- als auch Mehrfachimport nicht angeboten.

**Comment by ixtheoOr** [comment]
Der Einzel- und Mehrfachimport funktionieren, danke!
Es fehlen die Keywords und die Seitenzahlen. Können die mit importiert werden?

**Comment by mara-spiess** [comment]
Die Keywords sind nun ergänzt - wie besprochen können die Seitenzahlen leider nicht importiert werden.

**Comment by ixtheoOr** [comment]
Keywords werden importiert, danke!
