### ISSUE TITLE
ISSN 1545-0031 | PaleoAnthropology (OJS) | Ex.-Satz-URL

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2166]
#### URL
https://paleoanthropology.org/ojs/index.php/paleo/article/view/564
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die Artikel haben keinen DOI, daher scheint keine URL in den Exemplardatensatz exportiert zu werden.
Bitte die URL in den Exemplardatensatz übernehmen.

**Comment by thefass** [comment]
Stimmt die Aussage, dass die Artikel keine DOI haben noch?
Siehe: https://paleoanthropology.org/ojs/index.php/paleo/article/view/1095 > DOI: 10.48738/2024.iss1.1095

**Comment by thefass** [comment]
Wenn ältere Artikel keine DOI haben, dann müssen wir mit @axelubtue sprechen. Da sollten natürlich überall DOIs vorhanden sein

**Comment by IxKo** [comment]
DOIs finden sich erst ab Jg. 2010 in der Fußzeile der PDF-Dateien.

**Comment by IxKo** [comment]
Ich schließe das Issue, da ich ab 2010 die DOIs aus den PDF-Dateien entnehmen kann.
Für die Artikel vor 2010 habe ich die URLs manuell im Ex.-Satz nachgetragen.
Damit ist das Ausgangsproblem dieses Issues hinfällig.
