### ISSUE TITLE
ISSN IXTH-0005 | Jahrbuch des Fachbereichs Evangelische Theologie der Goethe-Universität Frankfurt am Main (Opus Frankfurt) | Import

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2168]
#### URL
https://www.uni-frankfurt.de/149034713/03___Jahrbuch_2023
  
#### Import-Translator
Einzelimport:
ubtue_OPUS_uniFrankfurt.js

  
### Problembeschreibung
Könnte für die Seite ein Mehrfachimport angeboten werden?

In der Mapping-Liste für fingierte ISSNs habe ich die Publikation mit IXTH-0005 hinterlegt.
Diese **ISSN** müsste auch im Einzel-Import übernommen werden.

Im Einzel-Import wird zudem der **DOI** und die **ORCID** noch nicht importiert. (https://publikationen.ub.uni-frankfurt.de/frontdoor/index/index/docId/80419)

**Comment by mara-spiess** [comment]
@jriedl Auch hier scheint es mir die effizienteste Lösung, den bisherigen (eher komplizierten) RIS-Translator mit einem Web Translator basierend auf Embedded Metadata zu ersetzen. Dies würde auch den Mehrfachimport ermöglichen, der momentan dadurch verhindert wird das der aktuelle Translator anhand der URL auf die RIS Datei zugreift - die Übersichtsseite https://www.uni-frankfurt.de/149034713/03___Jahrbuch_2023 verwendet aber anstatt der URLs die DOIs. Die Ergebnisse von EM sind außerdem vollständiger als die des RIS-Translators. Es wird abgesehen von diesem Jahrbuch nur eine Zeitschrift mit dem Translator bearbeitet.

**Comment by jriedl** [comment]
Spricht aus meiner Sicht nichts dagegen.
________________________________

**Comment by IxKo** [comment]
Vielen Dank!
