### ISSUE TITLE
ISSN 1918-6371 | Toronto journal of theology | Translator

### ISSUE THREAD

**Issue by ixtheoOr** [ubtue/DatenProbleme#2169]
#### URL
https://utppublishing.com/toc/tjt/40/2
  
#### Import-Translator
Mehrfachimport:
ubtue_University of Toronto Press.js
  
### Problembeschreibung
Bei der Zeitschrift wir der Translator ubtue_Atypon_Journals angeboten, laut Zeder müsste es ubtue_University of Toronto Press.js sein, dieser Translator steht aber nicht zur Auswahl.

**Comment by mara-spiess** [comment]
Es scheint sich nicht nur die URL sondern auch das Layout und die Metadaten der Webseite geändert zu haben. @jriedl @socheres Der einfachste Weg scheint es mir einen neuen Web Translator aufzusetzen, Embedded Metadata funktioniert bereits recht gut.

**Comment by jriedl** [comment]
Im alten Translator werden drei Zeitschriften explizit gemapped (The Journal of Religion and Popular Culture, Toronto Journal of Theology, Canadian Journal of Criminology and Criminal Justice), falls das für die anderen beiden genauso gilt, spricht m.E. nichts gegen eine Ersetzung.

**Comment by mara-spiess** [comment]
Für das Canadian Journal of Criminology and Criminal Justice besteht das Problem genauso, das Journal of Religion and Popular Culture wird aktuell über eine andere Plattform und einen anderen Translator bearbeitet (s. https://muse.jhu.edu/journal/559)

**Comment by jriedl** [comment]
Ok, danke für die Abklärung.

**Comment by mara-spiess** [comment]
Die neue Version des Translators kann nun getestet werden.

**Comment by ixtheoOr** [comment]
Funktioniert, danke!
