### ISSUE TITLE
Datenbank Historical Abstracts with Full Text auf EBSCO

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#217]
Bei Zeitschriften, die von Historical Abstracts with Full Text auf EBSCO erfasst werden, wird der Alternate Title bei Aufsätzen in das Zotero-Feld "Publikation" übertragen. 
Konkret aufgefallen ist es mir bei diesen beiden Zeitschriften:
http://web.b.ebscohost.com/ehost/command/detail?vid=0&sid=b19dda73-1f04-4a55-9a7e-5eb7092e1bac%40pdc-v-sessmgr02&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#jid=ATSH&db=30h
und
http://web.b.ebscohost.com/ehost/command/detail?vid=0&sid=e4cbd0d8-e397-4aa7-89e5-7803e822feba%40pdc-v-sessmgr05&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#jid=ATSF&db=30h
Dies führt dazu, dass die Zuordnung ISSN SSG-Nummer nicht mehr richtig funktioniert. In diesem Fall wird immer der Standardwert übergeben. Dies ist bei mir die 1, sollte aber bei der ZS Studi e Materiali di Storia delle Religioni die 0 sein. In der Konkordanz ISSN_to_SSG.map ist dies auch so definiert.

Ein Datensatz für einen Aufsatz sieht beispielsweise so aus:
http://web.b.ebscohost.com/ehost/command/detail?vid=0&sid=b19dda73-1f04-4a55-9a7e-5eb7092e1bac%40pdc-v-sessmgr02&bdata=JnNpdGU9ZWhvc3QtbGl2ZQ%3d%3d#jid=ATSH&db=30h
Der Alternate Title THE MILIZIA AS A "MANIERA DI VIVERE" OF THE JESUITS: MISSION, MARTYRDOM, OBEDIENCE.
wird in das Feld Publikation in Zotero übertragen. Hier sollte aber der Titel der Zeitschrift stehen, In diesem Fall Studi e Materiali di Storia delle Religioni

**Comment by shadeMe** [comment]
Die obigen Links funktionieren bei mir nicht - Bei EBSCOHost muss man einen Permalink generieren, um ihn weitergeben zu können. Die Funktionalität steht rechts auf der Artikel Ansicht.

![Screenshot_20190517_153828](https://user-images.githubusercontent.com/214450/57931895-dafff080-78b9-11e9-8746-8491d232575c.png)

**Comment by kdr154** [comment]
Ist auch so in Zeder verankert. Im Fall von Studi e Materiali di Storia delle Religioni ist es:
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3d30h%26jid%3dATSH%26site%3dehost-live

**Comment by socheres** [comment]
bei mir kommt alles richtig. @kdr154 bitte nochmal überprüfen.

**Comment by kdr154** [comment]
Das Problem scheint nicht mehr zu existieren
