### ISSUE TITLE
ISSN 0036-9764 | Scripta theologica (OJS) | Rezensionserkennung

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#2171]
#### URL
https://revistas.unav.edu/index.php/scripta-theologica/issue/view/1815

#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
### Problembeschreibung
Rezensionen werden in Zotero nicht automatisch gekennzeichnet, dafür steht immer "Book Review" im Abstract, was manuell gelöscht werden muss. Gibt es eventuell eine Möglichkeit beides zu beheben?

**Comment by mara-spiess** [comment]
Die Rezensionen scheinen auch alle den unnötigen Tag "." zu erhalten, soll dieser entfernt werden?

**Comment by DowntownOcean** [comment]
Ja, bitte auch entfernen, der ist mir auch gerade aufgefallen

**Comment by mara-spiess** [comment]
Die gewünschten Änderungen liegen jetzt vor.
