### ISSUE TITLE
ISSN 2317-4307 | Revista de cultura teológica (OJS) | Autoren werden nicht erkannt

### ISSUE THREAD

**Issue by DowntownOcean** [ubtue/DatenProbleme#2172]
#### URL
https://revistas.pucsp.br/index.php/culturateo/issue/view/2949
  
#### Import-Translator
Einzel- und Mehrfachimport:

ubtue_Open Journal Systems Standard.js

### Problembeschreibung
Autoren werden nicht erkannt

**Comment by mara-spiess** [comment]
Die Autoren sollten nun normal erkannt werden.

**Comment by DowntownOcean** [comment]
Mit dem Translator ubtue_Open Journal Systems Standard.js werden bei mir weiterhin keine Autoren übertragen. Jetzt wird mir aber der Translator ubtue_PKP Catalog Systems.js angeboten, der einwandfrei funktioniert. Erstellt den exakt gleichen Datensatz aber mit Autoren. Könnte man den einfach als präferierten Translator einstellen oder führt das später eventuell noch zu Problemen?

**Comment by DowntownOcean** [comment]
Autoren werden jetzt erkannt, bitte noch Abstracts dazunehmen

**Comment by mara-spiess** [comment]
Ich entferne außerdem auch unnötige "Keywords", siehe zB https://revistas.pucsp.br/index.php/culturateo/article/view/66744

**Comment by DowntownOcean** [comment]
Funktioniert jetzt alles, danke
