### ISSUE TITLE
ISSN 0448-8954 | Japanese religions | Neuer Translator

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2174]
#### URL
https://nccisjpnew.wixsite.com/nccisjp/%E8%A4%87%E8%A3%BD-vol-45-3
  
#### Import-Translator
Einzel- und Mehrfachimport:
keiner

  
### Problembeschreibung
Könnte für diese Website ein neuer ubtue-Translator entwickelt werden?

Metadaten:

- [ ] Titel
- [ ] Titelzusatz
- [ ] Verfasser
- [ ] Jahr
- [ ] Seiten
- [ ] Band
- [ ] Heft
- [ ] Sprache
- [ ] Rezensionserkennung

**Comment by mara-spiess** [comment]
Es sieht leider so aus als wäre die Webseite sehr inkonsistent aufgebaut und die Daten müssten mit rudimentären Selektoren ausgewählt werden, was fehleranfällig wäre. Hier scheint mir ein Translator nicht sinnvoll.
