### ISSUE TITLE
ISSN 1545-0031 | PaleoAnthropology (OJS) | ORCID

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2175]
#### URL
https://doi.org/10.48738/2023.iss2.1089
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die ORCID-Angaben werden nicht importiert.

**Comment by IxKo** [comment]
Wahrscheinlich ist es beim TUUB-Login gar nicht sinnvoll, dass sie dann mit 8910 ixzom... exportiert werden.
Ich werde sie daher manuell erfassen.

**Comment by mara-spiess** [comment]
Kann das Issue dann geschlossen werden?

**Comment by IxKo** [comment]
Wahrscheinlich
