### ISSUE TITLE
ISSN 1545-0031 | PaleoAnthropology (OJS) | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2176]
#### URL
https://doi.org/10.48738/2023.iss2.1089
  
#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js

  
### Problembeschreibung
Die Keywords werden nicht getrennt, sondern als ein "Block" importiert.

**Comment by mara-spiess** [comment]
Da es sich hier um einen Einzelfall handelt und der Translator schon sehr weitläufig ist, sollte das Problem nicht auf Translatorseite sondern manuell behoben werden.
