### ISSUE TITLE
ISSN 1745-5251 | Journal of pentecostal theology (Brill) | fehlender Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2177]
- [ ] zota ub28

#### URL
https://doi.org/10.1163/17455251-bja10059

## zota
Der Artikel wurde nicht eingespielt und findet sich auch nicht auf ub28 

Wenn ich den Feed (https://brill.com/journalissuetocrss/journals/pent/pent-overview.xml) im Browser aufrufe, wird mir der Artikel dort angezeigt:
![image](https://github.com/user-attachments/assets/f9e92b39-1191-4e90-b89b-8ce1bd336d16)

**Comment by jriedl** [comment]
Der Artikel wird im RSS erkannt und verarbeitet, letztmalig gestern Abend. Allerdings wird er dann jeweils als Duplikat verworfen, da die DOI doppelt vergeben wurde: "Toward a More Trinitarian Understanding of Atonement: The Role of the Holy Spirit in Calvin’s Atonement Theology" (A39A866D2707E6C7F158BC4FF4577AAAF29C7FDD -geliefert am 4.3.24) hat bereits die DOI [10.1163/17455251-bja10059](https://doi.org/10.1163/17455251-bja10059) (vgl. PPN 1882447360).

**Comment by IxKo** [comment]
Danke für die Detektivarbeit!
Dann ändere ich bei dem Art. die Heftzählung.

Es ist eigenartig, dass sie den Art. erst in Heft 1 führten und nun scheinbar in Heft 2 verschoben haben.

**Comment by jriedl** [comment]
Ok, solange es im RSS ist, wird es dann weiter "leerlaufen". Es gehen zwar tatsächlich offenbar sowohl DOI als auch die direkte Verlinkung von PPN 1882447360 auf "Prophetic mediums", da der usprüngliche Artikel aber anders verschlagwortet war (aktuell  prophecy; mediumship; ancestors; intercultural theology; plural pneumatology auf der Anbieterseite vs. Atonement,  Trinity, Pneumatology, John Calvin im Record), könnte es auch sein, dass es hier ein Fehler in der Verlagsdatenbank vorliegt und der ursprünglingliche Artikel einfach verloren gegangen ist.

**Comment by IxKo** [comment]
Ja, ich habe mich mittlerweile auch dazu entschieden, den ursprünglichen Eintrag im Vorläufigkeitsstatus mit ungültigen URLs (gesonderten Feld) und dem Hinweis, dass der Eintrag von der herausgebenden Institution entfernt worden ist, zu belassen.

Den anderen erfasse ich dann manuell nach.

Bei einem so großen Verlag wundert mich der Vorfall. Normalerweise würden sie einen Retraction notice herausgeben und der andere Art. würde seine eigene neue DOI erhalten.
