### ISSUE TITLE
ISSN 0717-4675 Veritas Band/Ausgabe und Abstract 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#218]
Halbautomatisch:
hier:
https://scielo.conicyt.cl/scielo.php?script=sci_issues&pid=0718-9273&lng=en&nrm=iso
wie im Übrigen auch auf EBSCO
http://www.redi-bw.de/db/ebsco.php/search.ebscohost.com/login.aspx%3fdirect%3dtrue%26db%3daph%26jid%3d5EWL%26site%3dehost-live
wieder das Problem, dass die Bandangabe in das Zotero-Feld "Ausgabe" geschrieben wird. 
Bei den Daten von Scielo fehlt das Abstract, 
bei denen von EBSCO der DOI

**Comment by shadeMe** [comment]
Bei EBSCO gibt es keinen DOI auf der Webseite (weder auf der Oberfläche noch in den eingebetteten Metadaten). Auf meinem Rechner kommt das Abstract bei SciElo mit (Strg + Umsch + R um die Seite neu zu laden).

**Comment by kdr154** [comment]
Bei mir leider nicht. Auch nicht nach einem erneuten herunterladen des Translators, dem Schließen des Browsers und von Zotero und nach einem akualisieren der Translator. Zudem steht jetzt die Bandbezeichnung wieder im Feld Ausgabe. Die zumindest vorübergehend korrekterweise im Feld Band stand.

**Comment by kdr154** [comment]
Jetzt ist es gut bei Scielo
