### ISSUE TITLE
ISSN 2084-4077 | Studia Religiologica (e-journals) | Neuer Translator

### ISSUE THREAD

**Issue by Rel-Koe** [ubtue/DatenProbleme#2180]
#### URL
https://ejournals.eu/czasopismo/studia-religiologica/numer/tom-56-numer-3

https://ejournals.eu/czasopismo/studia-religiologica/artykul/przynaleznosc-bez-wiary-bulgarska-tozsamosc-prawoslawna-a-literaturoznawstwo
  
#### Import-Translator
Einzelimport:
keiner

  
### Problembeschreibung
Könnte für diese Website ein neuer ubtue-Translator entwickelt werden?

Metadaten:

- [ ] Titel
- [ ] Titelzusatz
- [ ] Verfasser
- [ ] Jahr
- [ ] Seiten
- [ ] Band
- [ ] Heft
- [ ] Sprache
- [ ] DOI
- [ ] Abstract
- [ ] Keywords
- [ ] ORCID
- [ ] Paralleltitel

**Comment by mara-spiess** [comment]
Für diese Zeitschrift wird eigentlich DOI.js genutzt, siehe https://github.com/ubtue/DatenProbleme/issues/2119. Hierbei treten allerdings einige Probleme auf, an denen momentan gearbeitet wird.
