### ISSUE TITLE
ISSN 1988-4265 | Hispania Sacra | Rezensionserkennung, Seitenzahlen

### ISSUE THREAD

**Issue by ixtheoOr** [ubtue/DatenProbleme#2181]
URL
https://hispaniasacra.revistas.csic.es/index.php/hispaniasacra/issue/view/90
  
Import-Translator
Einzel- und Mehrfachimport:
ubtue_Open Journal Systems Standard.js
  
Problembeschreibung
Bitte prüfen, ob die Rezensionen automatisch erkannt werden können. Beim aktuellen Heft 76(2024,153) ist das nicht der Fall!

Außerdem gibt es scheinbar beim neuen Heft keine Seitenzahlen mehr, dafür eine Artikelnummer (zumindest deute ich das so...).

**Comment by ixtheoOr** [comment]
Da es in den letzten Heften immer mehr als 10 Rezensionen gab, fände ich das schon mal hilfreich...

**Comment by mara-spiess** [comment]
Es werden jetzt alle Titel die eine ISBN beinhalten automatisch als Rezension markiert, vielleicht sollte man das in Zeder vermerken falls sich eine Ausnahmefall reinschleicht.

**Comment by ixtheoOr** [comment]
Im aktuellen Heft (76.2004,153) gibt es 12 Rezensionen, alle mit ISBN. In Zotero kommen aber nur acht Rezensionen mit der automatischen Markierung an. Die restlichen vier werden nicht erkannt.

**Comment by ixtheoOr** [comment]
Passt, danke!
