### ISSUE TITLE
Personen-Lookup

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2183]
#### URL
https://revista.abib.org.br/EB/article/view/1018
  
### Problembeschreibung

Die Person "Toseli, Cecília" wurde beim Export mit ubtue_Pica3.js nicht mit dem GND-Datensatz gnd/1136311327 verknüpft.
Woran liegt das?
![image](https://github.com/user-attachments/assets/ed5940a7-9091-4bd3-8176-0b78e1729ed4)

Die Person ist im GND-Datensatz eine Theologin und bei der Namenssuche (auch unscharfe Suche) fand ich auch nur diesen einzigen Treffer.

**Comment by socheres** [comment]
Das liegt an dem accent aigu beim Buchstaben "í" (Cecília). MIt normalem "i" findet man den Datensatz: https://swb.bsz-bw.de/DB=2.104/SET=70/TTL=1//CMD?SGE=&ACT=SRCHM&MATCFILTER=Y&MATCSET=Y&NOSCAN=Y&PARSE_MNEMONICS=N&PARSE_OPWORDS=N&PARSE_OLDSETS=N&IMPLAND=Y&NOABS=Y&ACT0=SRCHA&SHRTST=50&IKT0=3040&TRM0=Toseli,%20Cecilia&ACT1=*&IKT1=2057&TRM1=*&ACT2=*&IKT2=8991&TRM2=(theolog*%7Cneutestament*%7Calttestament*%7Ckirchenhist*)&ACT3=-&IKT3=8991&TRM3=1%5B0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%5D%5B0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%5D%5B0%2C1%2C2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%5D&COOKIE=Us998,Pbszgast,I2017,B20728+,SY,NRecherche-DB,D2.104,Efc70084a-0,A,H,R134.2.163.50,FY

**Comment by IxKo** [comment]
Demnach wird das Zeichen bei dem Lookup-Vorgang nicht normalisiert wie in der WinIBW?

Dann mache ich im GND-Datensatz eine Verweisungsform mit Akzent.

**Comment by socheres** [comment]
Man könnte darüber nachdenken, beim Lookup die Namen zu normalisieren und dann zu übergeben.

**Comment by IxKo** [comment]
Mit der Verweisungsform wird sie nun beim Look-Up auch automatisch verknüpft.
Somit lag es am diakritischen Zeichen.
