### ISSUE TITLE
zota-Einspielungen: Abrufzeichen tiep nur bei verbaler Erfassung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2185]
- [x] zota nu
- [x] zota ub28

#### URL
Beispiele ( => gewünschtes Ergebnis) :

- 1 Person (automatisch verknüpft) https://doi.org/10.2143/ETL.99.3.3292101 (=> ohne tiep)
- 2 Personen (beide automatisch verknüpft) https://doi.org/10.1177/00405639241287855 (=> ohne tiep)
- 2 Personen (1 automatisch verknüpft, 1 verbal) https://doi.org/10.1353/cat.2024.a927998 (=> mit tiep)
- 4 Personen (1 davon automatisch verknüpft) https://doi.org/10.1163/18712428-10303017 (=> mit tiep)
  
  
## zota
Wäre es möglich, dass das Abrufzeichen "tiep" (MARC 935) nur gesetzt wird, wenn es mindestens eine Person gibt, die nur verbal (Klartext) erfasst ist? 
Das heißt, wenn MARC 100 oder 700 rein verbal belegt ist und nicht automatischen mit einem GND-Datensatz verknüpft worden ist?

**Comment by jriedl** [comment]
Eine entsprechend angepasste Version findet sich auf nu.

**Comment by jriedl** [comment]
ub28 wurde nun ebenfalls aktualisiert.
