### ISSUE TITLE
ISSN 2284-7308 | Perichoresis (Sciendo) | Translatorprobleme

### ISSUE THREAD

**Issue by ixtheoOr** [ubtue/DatenProbleme#2186]
#### URL
https://sciendo.com/issue/PERC/22/4

#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Sciendo.js

### Problembeschreibung
Der Mehrfachimport funktioniert nicht und beim Einzel-Import tritt ein Fehler auf und es wird der allgemeine Embedded Metadata.js verwendet und nicht der auf uns angepasste ubtue.
Der Fehler tritt bei allen Heften auf.

(gleiches Problem wie hier schon mal gemeldet: https://github.com/ubtue/DatenProbleme/issues/2127)

**Comment by mara-spiess** [comment]
In Absprache mit @ixtheoOr und @IxKo scheint das Problem nur aufzutreten, wenn die Zeitschrift via Zeder aufgerufen wird. Mit bspw. dem Link aus diesem Issue liegt das Problem nicht vor, auch ein reload der webseite behebt das Problem.

**Comment by ixtheoOr** [comment]
Ich hab die Info in Zeder eingetragen!
