### ISSUE TITLE
ISSN 2169-2335 | International journal of philosophy and theology (T&F) | Doppelheft

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#2189]
- [x] zota nu
- [x] zota ub28

#### URL
https://doi.org/10.1080/21692327.2024.2340963
Hash auf ub28: 192E05E7A97C7DB2F547AE20B2F633DC52FD3E4F

#### Import-Translator
Einzel- und Mehrfachimport:
ubtue_Taylor and Francis+NEJM.js

  
## zota
Der Artikel erscheint in einem Doppelheft. Doppelhefte müssen mit Schrägstrich angegeben werden. So ist es auch in den QA gesetzt.
Doch im MARC-Format wird die Heftzählung mit Bindestrich erzeugt, weswegen die Artikel von dem Heft in den Errors landen.

Könnte die Doppelheftzählung bitte mit Schrägstrich / angegeben werden, damit die Artikel die QA passieren können?

**Comment by IxKo** [comment]
Aus irgendeinem Grund wird der übersetzte Titel zusätzlich als Abstract in 4207 exportiert:
![image](https://github.com/user-attachments/assets/b14333bc-4ebd-49de-b1f2-fbbc226df81e)

**Comment by IxKo** [comment]
Danke, Problem ist auf nu gelöst, bitte noch auf ub28.

@jriedl, soll dafür das Label hier auf "back to it" gesetzt werden?

**Comment by jriedl** [comment]
Ist jetzt auch auf ub28.

> @jriedl, soll dafür das Label hier auf "back to it" gesetzt werden?

In solchen Fällen, wo das zeitlich eng beisammen liegt und das weitere Vorgehen aus der Konversation klar ist, vermutlich nicht nötig.

**Comment by IxKo** [comment]
Passt, danke.
