### ISSUE TITLE
SSOAR_ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#22]
Manche Dokumente enthalten auf ihren SSOAR-Seiten eine ISSN:
https://www.ssoar.info/ssoar/handle/document/9880
Sie wird jedoch nicht abgegriffen. Ist dies nicht möglich?

Antwort/Frage ruschein: Das ist ein Artikel. Ich dachte, dass im BSZ ISSNs nur in den übergeordneten Werken stehen. Oder übersehen ich da etwas?

Antwort kdr154: Ist die ISSN der übergeordneten Einheit. In diesem Fall das Forum Qualitative Sozialforschung. Die ISSN müsste, wenn ich das der Dokumentation richtig entnehme, in dem bisher in der SSOAR-Daten nicht vorkommenden Feld 022 abgelegt werden.

**Comment by ruschein** [comment]
@kdr154 Untergeordnete Werke enthalten im BSZ nie eine ISSN.  Außerdem liefert SSOAR die ISSN nicht mit aus über OAI-PMH zumindest mit dem MARC-XML-Format.
