### ISSUE TITLE
ISSN 2627-6062 Journal of Ethics in Antiquity and Christianity Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#220]
Halbautomatisches Verfahren
Bei den Artikeln wird das Abstract nicht mir übertragen

**Comment by shadeMe** [comment]
Beispiel URL(s) bitte.

**Comment by kdr154** [comment]
https://jeac.de/ojs/index.php/jeac/issue/view/14
https://jeac.de/ojs/index.php/jeac/article/view/97
https://jeac.de/ojs/index.php/jeac/article/view/107

**Comment by shadeMe** [comment]
Ich habe für diese Webseite einen neuen Translator geschrieben, der 'ubtue_JEAC.js' heißt.

**Comment by kdr154** [comment]
Sehr gut!
