### ISSUE TITLE
ISSN 2295-6093 Augustiana Peeters Zeitschrift Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#221]
Halbautomatisch
Bei dieser ZS hat das System Probleme mit dem Abstract. Es wird nach einigen Zeichen oder Worten einfach abgeschnitten,
https://poj.peeters-leuven.be/content.php?url=journal.php&journal_code=AUG
https://poj.peeters-leuven.be/content.php?url=article&id=3285680&journal_code=AUG
https://poj.peeters-leuven.be/content.php?url=article&id=3285681&journal_code=AUG

**Comment by shadeMe** [comment]
Das kann ich mit den obigen Links nicht reproduzieren. Ist es der Peeters Translator, der aufgerufen wird?

**Comment by kdr154** [comment]
Ist der Peeters Translator. Aber jetzt ist das Abstract vollständig
