### ISSUE TITLE
ISSN  2046-5734 Medieval Mystical Theology Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#223]
hier wird wieder die Ordensbezeichnung zum Nachnamen
Beispielaufsatz:
https://www.tandfonline.com/doi/full/10.1080/20465726.2016.1257626

**Comment by shadeMe** [comment]
Die zusätzliche Verarbeitung der Autornamen ist leider nur für das automatische Zotero-Verfahren verfügbar.

**Comment by shadeMe** [comment]
m.E können wir dieses Issue jetzt schließen.

**Comment by kdr154** [comment]
gemacht
