### ISSUE TITLE
ISSN 2507-0428 Liber Annuus Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#224]
Halbautomatisch
Bei dieser Zeitschrift wird das Abstract nicht übertragen, weder beim multi-, noch beim singledownload
Beispielheft:
https://www.brepolsonline.net/toc/la/2017/67

**Comment by kdr154** [comment]
Beim Multi ist es jetzt dabei. Bein Single fehlt es weiterhin

**Comment by shadeMe** [comment]
Funktioniert auf meinem Rechner. Der Translator, der benutzt wird, lautet "Atypon Journals".

![Screenshot_20191011_115451](https://user-images.githubusercontent.com/214450/66642906-f0d1d180-ec1d-11e9-93bf-2265ea60d55d.png)

**Comment by kdr154** [comment]
Beim Multi nimmt die Erweiterung bei mir den Liverpool University Press Translator. Dann passt es, Im Single steht nur der Atypon zur Verfügung, Dann fehlt das Abstract, auch wenn man den Atypon im Multi nimmt.
Wollen wir es so belassen oder noch weiter daran arbeiten?

**Comment by kdr154** [comment]
Ich denke wir sollten hier schließen
