### ISSUE TITLE
ISSN 2590-3268 NTT Journal for Theology and the Study of Religion - Fehlermeldung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#225]
Halbautomatisch: 
Beim Versuch, die Daten über die Browsererweiterung im Singleverfahren zu speichern, bekommt man folgende Fehlermeldung:
Ein Fehler ist aufgetreten beim Speichern mit IngentaConnect.

**Comment by shadeMe** [comment]
Funktioniert bei mir.

![Screenshot_20190726_143555](https://user-images.githubusercontent.com/214450/61951912-b8254300-afb2-11e9-8978-9bedad35b987.png)

**Comment by kdr154** [comment]
Fehler tritt bei mir weiterhin auf. Nutze jetzt die Option Reference Export, die auf der Webseite angeboten wird

**Comment by kdr154** [comment]
Gelöst
