### ISSUE TITLE
ISSN 2156-4795 American Journal of Theology & Philosophy DOI und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#226]
halbautomatisch
Bei dieser ZS werden DOI und Keywords nicht mit übertragen
https://www.jstor.org/journal/amerjtheophil

**Comment by shadeMe** [comment]
Funktioniert schon bei mir. Bei Single- und Multi-Download.

![Screenshot_20190726_143213](https://user-images.githubusercontent.com/214450/61951744-33d2c000-afb2-11e9-914c-1fac6e03fab9.png)
![Screenshot_20190726_143154](https://user-images.githubusercontent.com/214450/61951746-346b5680-afb2-11e9-882f-75d6b1a198c1.png)

**Comment by kdr154** [comment]
Gelöst
