### ISSUE TITLE
Änderung der  Angabe Kostenfrei (LF) von Marc21 Feld 936 zu 856

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#227]
Das Unterfeld:
`<subfield code="z">Kostenfrei</subfield>`
ist bisher Teil des Tags 936.
Das muss mit der Umstellung auf K10Plus in der gleichen Form nun unter die Kategorie 856
Die Angabe in 936 entfällt

**Comment by shadeMe** [comment]
Welche Indikatoren hat denn das Feld? Laut der [LOC Doku](https://www.loc.gov/marc/bibliographic/bd856.html), sollte sie '4' und ' ' sein oder?

**Comment by kdr154** [comment]
ind1="4" ind2="0"
4 steht für HTTP
0 für Resource
Die BSZ-Konkordanz benennt den Inhalt des Feldes mit den Indikatoren 4 und 0 mit:
URL zum Volltext, URL

**Comment by kdr154** [comment]
Gelöst
