### ISSUE TITLE
SSOAR_MARC 21 Feld 110/710

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#23]
\<subfield code="**4**"\>edt\</subfield\>
Die Beziehungskennzeichnung (hier edt=HerausgeberIn) steht nur in RDA-Aufnahmen.
Trotzdem ausliefern und ggf. beim Import in den SWB ignorieren?

**Comment by ruschein** [comment]
@kdr154 Wie sollte das bei RAK-Aufnahmen aussehen?

**Comment by IxTheoKm** [comment]
Lt. Rücksprache mit dem BSZ sollen trotzdem alle Beziehungskennzeichen (auch in MARC-Feld 100 und 700) mitgeliefert werden!
