### ISSUE TITLE
ISSN 1740-7931 British Journal of Religious Education Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#234]
Bei den Rezensionen fehlt Marc21 Tag 655:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
In diesem Fall steht "Book review" über jedem Artikel. Zudem ist die Sektion mit dem Begriff "Book Review" gekennzeichnet

**Comment by kdr154** [comment]
655 fehlt weiterhin

**Comment by shadeMe** [comment]
Gibt es ein paar Beispiele?

**Comment by kdr154** [comment]
Gelöst
