### ISSUE TITLE
ISSN 1468-2265 The Heythrop Journal Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#235]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
Nur daran zu erkennen, dass es die Sektion "Book Reviews" in den einzelne Ausgaben gibt.

**Comment by shadeMe** [comment]
Auf der [Webseite](https://onlinelibrary.wiley.com/toc/14682265/0/0) finde ich keine Sektion "Book Reviews". Gibt es Beispiel-URLs, bei denen es mit dem Begriff "Book Reviews" o.Ä gekennzeichnet ist?

**Comment by kdr154** [comment]
Die oben angegebene Webseite beinhaltet die Early Views. In den Heften gibt es die Sektion "Book Reviews" sehr wohl: https://onlinelibrary.wiley.com/toc/14682265/2019/60/4. Die Early Views liegen auch auf einem anderen Pfad als die einzelnen Hefte. Dies kann auch eine Möglichkeit sein, die Early Views zu übergehen. Denn wenn wir die auch aufnehmen, haben wir später lauter Dubletten.

**Comment by kdr154** [comment]
Gelöst
