### ISSUE TITLE
ISSN 2050-8557 Horizons : the journal of the College Theology Society Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#237]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
Hier gibt es die Sektion "Book Reviews".
Weiter fällt mir auf, dass alle Reviews Seitenangaben mit dem Begriff "pages" im Titel enthalten.

**Comment by kdr154** [comment]
Gelöst

**Comment by kdr154** [comment]
In der aktuellen Einspielung vom 19.5.2020 werden nicht alle Rezensionen erkannt. Diese z. B. nicht:
https://www.cambridge.org/core/journals/horizons/article/catholic-theology-by-tracey-rowland-new-york-bloomsbury-t-t-clark-2017-256-pages-9000/F4678EB2B0D08CF6618768A570F50E5A
IxTheo#2020-05-18#611E1E61D2AF996F3109D56963B770C66B8BB05A
Scheint mir durch die Heuristik zu rutschen.  Denn sie ist soweit ich sehe die Einzige

**Comment by socheres** [comment]
> https://www.cambridge.org/core/journals/horizons/article/catholic-theology-by-tracey-rowland-new-york-bloomsbury-t-t-clark-2017-256-pages-9000/F4678EB2B0D08CF6618768A570F50E5A

mit "Try URL" getestet und der Artikel wird als Review erkannt.

Augmented metadata record: MetadataRecord {
	url: https://www.cambridge.org/core/journals/horizons/article/catholic-theology-by-tracey-rowland-new-york-bloomsbury-t-t-clark-2017-256-pages-9000/F4678EB2B0D08CF6618768A570F50E5A,
	item_type: review,
	title: Catholic Theology. By Tracey Rowland. New York: Bloomsbury T & T Clark, 2017. 256 pages. $90.00.,
	short_title: Catholic Theology. By Tracey Rowland. New York,
	publication_title: Horizons,

**Comment by kdr154** [comment]
Wenn man den Titel allein testet ist das so. Wenn man das ganze Heft 47.2020,1 testet, fällt auf, dass nur 20 Artikel erfasst werden. Was bedeutet dass dieser, da er sehr weit hinten steht, bei einem Test des ganzen Hefts nicht erfasst wird.

**Comment by socheres** [comment]
mit "Try RSS" getestet und der Artikel wird als review erkannt.

Converting item 49 [Horizons : the journ...] | https://dx.doi.org/10.1017/hor.2020.12?rft_dat=source%3Ddrss {7623575824708282112}
use online ISSN "2050-8557" with online PPN "618791159"
post-processed author first name = 'Kristin', last name = 'Colberg', title = '', affix = ''
added GND number 1067104216 for author Colberg, Kristin (SWB lookup)
title matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://www.cambridge.org/core/journals/horizons/article/catholic-theology-by-tracey-rowland-new-york-bloomsbury-t-t-clark-2017-256-pages-9000/F4678EB2B0D08CF6618768A570F50E5A,
	item_type: review,
	title: Catholic Theology. By Tracey Rowland. New York: Bloomsbury T & T Clark, 2017. 256 pages. $90.00.,
	short_title: Catholic Theology. By Tracey Rowland. New York,
	publication_title: Horizons,
	volume: 47,
	issue: 1,
	pages: 191-193,
	date: 2020-06-01,
	doi: 10.1017/hor.2020.12,
	language: eng,
	issn: 2050-8557,
	superior_ppn: 618791159,

**Comment by socheres** [comment]
@kdr154 bitte nochmal testen und Issue schließen

**Comment by kdr154** [comment]
Wieder nur 20. Aber er wird ja im Einzeltest erkannt.
