### ISSUE TITLE
ISSN 1890-7008 Nordic journal of religion and society - keine Daten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#244]
Die Ergebnisseite enthält keine Daten.

**Comment by kdr154** [comment]
Jetzt enthält das Result file Daten, sie sind jedoch unbrauchbar. Der Harveste scheint mir nur auf den Titel der einzelnen Hefte zuzugreifen, wie er auf der Seite des Feeds steht, und sonst auf so gut wie nichts. Es gibt keine Titel, Verfasser, Seitenangaben, Heftnummern ....

**Comment by shadeMe** [comment]
Ach so. Es scheint, dass die Zss einen eigenen Translator braucht. Wird geschrieben.

**Comment by kdr154** [comment]
Gelöst
