### ISSUE TITLE
ISSN 2259-0285 Revue des sciences religieuses

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#249]
Die Daten sind nicht zu gebrauchen. Wie sie zustande kommen kann ich nicht sagen, sondern nur ein wenig vermuten. Der Harvester scheint mir die Titel der einzlnen Hefte, die auf der Seite des Feeds sind, als Titel einzelner Aufsätze zu interpretieren und daraus einzelne Records zu generieren.

**Comment by kdr154** [comment]
Es ist schon besser. Dennoch erscheint mir diese Zeitschrift weiterhin sehr schwierig.
Mir fällt auf:
Rezensionen werden nicht erkannt. Das bedeutet, die entsprechenden Einträge im Tag 655 fehlen. Diese stehen in einer Sektion die mit "Recensions" überschrieben ist. Das Ende dieser Sektion ist dann keine neue Sektion, sondern im ersten Heft, das abgearbeitet wird, ein neues Heft.
Abstracts: diese werden in zwei Sprachen abgegriffen. Stehen jedoch in einem Tag 520. Hier müsste 520 wiederholt werden.
Nachdem das erste Heft abgearbeitet worden ist, wird ein neues Heft aufgegriffen. In meinen Daten beginnt der Harvester mit Heft 92.2018,4. Dann nimmt er Heft 92.2017,3 in Angriff. Bei diesem wird der Titel des Hefts wieder als Aufsatz interpretiert und ein entsprechender record angelegt. Mehr aber nicht. Auf diesen Eintrag folgt ein Editorial das zu Heft 91.2017, 1 gehört. Dieses wird dann abgearbeitet. Darauf wird für das Heft 91.2017,3 wieder als Aufsatz angelegt. Unter anderem mit einem Abstract, das aus den Einträgen "philosophie, histoire, christianisme". Woher das kommt, erschließt sich mir im ersten Moment nicht.
Soweit mal für jetzt.

**Comment by kdr154** [comment]
1. keywords fehlen
2. Rezensionen erhalten jetzt das Keyword-Tag 650 statt den Code für Rezensionen: 
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield> 
<subfield code="0">(DE-588)</subfield> 
</datafield>

**Comment by kdr154** [comment]
Es hat sich nichts geändert.

**Comment by socheres** [comment]
bitte prüfen, ob akutelle Metadaten 2020 heruntergeladen werden.

**Comment by kdr154** [comment]
Dazu habe ich bereits gestern einige Issues angelegt. U. a. auch zu dieser Frage. Nein. Das Heft, das gestern eingespielt wurde, war 92.2018,2

**Comment by socheres** [comment]
Wenn das Problem mit Keywords und Tag 650 bzw. 655 behoben sind, bitte diesen Issue schließen. Bzgl. RSS-Problematik beobachten wir weiterhin in #950.

**Comment by kdr154** [comment]
schließe
