### ISSUE TITLE
ISSN 0049-3449 Teología y vida - der Feed an sich

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#253]
Der Feed is völlig veraltet. Abgearbeitet wird die Ausgabe 57.2016,3. Das aktuelle Heft bei Scielo ist aber 60.2019,1

**Comment by shadeMe** [comment]
Gibt es eine aktuelle URL für den RSS-Feed dieser Zeitschrift?

**Comment by kdr154** [comment]
Der auf der Webseite scheint mir aktuell zu sein. Heute dort angeclickt:
https://scielo.conicyt.cl/rss.php?pid=0049-3449&lang=es
liefert die aktuellen Aufsätze. Sah so aus, als ob der in Zeder einen bestimmten Zustand wiedergab

**Comment by kdr154** [comment]
Daten sind jetzt die aktuellen
