### ISSUE TITLE
ISSN 1469-7637 The journal of ecclesiastical history : JEH Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#262]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
Leider sehe ich hier kein weiteres eindeutiges Kriterium, als dass die Rezensionen in der Sektion "Reviews" stehen.

**Comment by kdr154** [comment]
Das mit den Rezensionen in der Sektion "Reviews" ist gelöst. Leider gibt es hier noch die Sektion "Review Article", in der ebenfalls Rezensionen stehen. Habe ich leider übersehen. Diese bitte auch mit 655 taggen.

**Comment by shadeMe** [comment]
Das geht leider nicht, weil es auf den Seiten der "Review Articles" keine zusätzliche Metadaten oder Muster gibt, mit denen es erkannt werden kann, dass der Artikel zu der Sektion gehört. Die anderen Rezensionen haben zumindest eine Bezeichnung wie Seitenanzahl z.B. "Pp. xx + 310" im Titel.

**Comment by kdr154** [comment]
Dann schließe ich das Issue
