### ISSUE TITLE
ISSN 1475-5629 Culture and religion Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#265]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Sie stehen in diesem Fall in der Sektion "Book Review", zudem ist jeder Artikel mit dem Begriff "Book Review" überschrieben.

**Comment by kdr154** [comment]
655 fehlt weiterhin

**Comment by shadeMe** [comment]
Es gibt keine Rezensionen im RSS-Feed gerade oder? Ich sehe nur 5 Datensätze, die ausschließlich in der Sektion "Original Articles" stehen.

**Comment by kdr154** [comment]
In dem Feed schon, in der ein oder anderen Ausgabe, nicht in allen, gibt es die schon.
Z. B.: https://www.tandfonline.com/toc/rcar20/20/1?nav=tocList

**Comment by kdr154** [comment]
Kann im Augenblick nicht geklärt werden, da die Daten keine Ausgabe beinhalten, in der es Rezensionen gibt.

**Comment by socheres** [comment]
Testen älterer RSS-Link jetzt im Tab "Try URL" möglich. Habe https://www.tandfonline.com/toc/rcar20/20/1?nav=tocList getestet und Rezension wird nun richtig getaggt > Tag 655

**Comment by socheres** [comment]
- [ ] Zota-Kandidat

**Comment by kdr154** [comment]
danke, dann schließe ich

**Comment by IxKo** [comment]
Rezensions-Tag fehlt weiterhin:

**URLs**
- https://www.tandfonline.com/doi/full/10.1080/14755610.2019.1572099
- https://www.tandfonline.com/doi/full/10.1080/14755610.2019.1572293

In den Titeln gibt es kein Muster. Auf der Heft-und der Artikel-Seite werden sie als "Book review" bzw. "Book Review" gekennzeichnet.

**Comment by socheres** [comment]
@mtrojan-ub habe den Translator angepasst. Nach commit bitte "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by IxKo** [comment]
Danke, werden nun erkannt.
