### ISSUE TITLE
SSOAR_MARC 21 Feld 700/710

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#27]
In Aufsätzen werden teilweise die Herausgeber der Sammelbände geliefert, die nur beim Sammelband erfasst werden müssten.

Bsp.:
**oai:gesis.izsoz.de:document/18839**

Autor des Aufsatzes:
\<datafield tag="**100**" ind1="1" ind2=" "\>
\<subfield code="a"\>Joas, Hans\</subfield\>
\<subfield code="4"\>aut\</subfield\>

Herausgeber des Sammelbandes:
\<datafield tag="**700**" ind1=" " ind2=" "\>
\<subfield code="a"\>Schulte, Werner\</subfield\>
\<subfield code="4"\>edt\</subfield\>
\</datafield\>
\<datafield tag="**710**" ind1="1" ind2=" "\>
\<subfield code="a"\>Deutsche Gesellschaft für Soziologie (DGS)\</subfield\>
\<subfield code="4"\>edt\</subfield\>

**oai:gesis.izsoz.de:document/12270**

Autoren des Aufsatzes:
\<datafield tag="**100**" ind1="1" ind2=" "\>
\<subfield code="a"\>Holtgrewe, Ursula\</subfield\>
\<subfield code="4"\>aut\</subfield\>
\<datafield tag="**700**" ind1="1" ind2=" "\>
\<subfield code="a"\>Kerst, Christian\</subfield\>
\<subfield code="4"\>aut\</subfield\>

Herausgeber des Sammelbandes:
\<datafield tag="**700**" ind1=" " ind2=" "\>
\<subfield code="a"\>Kleemann, Frank\</subfield\>
\<subfield code="4"\>edt\</subfield\>
\</datafield\>
\<datafield tag="**700**" ind1=" " ind2=" "\>
\<subfield code="a"\>Matuschek, Ingo\</subfield\>
\<subfield code="4"\>edt<\/subfield\>

**Comment by shadeMe** [comment]
Wie unterscheidet man zwischen Autoren und Herausgebern? Ist der Inhalt von 700/710$4 immer "edt" bei Sammelbänden (und dementsprechend immer "aut" bei Aufsätzen)?

**Comment by IxTheoKm** [comment]
$4**edt** = Herausgeber
$4**aut** = Autor

Dieser Kennzeichen stehen für die **Funktion** der Person unabhängig davon, ob es sich um einen Aufsatz oder um ein Sammelwerk handelt. In der Regel haben Aufsätze aber keinen Herausgeber!
"aut" könnte allerdings sowohl in Aufsätzen als auch in Sammelwerken vorkommen.

**Comment by IxTheoKm** [comment]
Ergänzung: 
in der Aufnahme einer **Monographie eines Autors** können Personen sowohl mit "aut" als auch mit "edt" vorkommen, wenn der Text eines Autors von einer anderen Person herausgegeben wurde.
