### ISSUE TITLE
ISSN 0026-587X Miscellanea Francescana von Dialnet Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#272]
Halbautomatisch,
Link zu einer Ausgabe der ZS: https://dialnet.unirioja.es/ejemplar/510247
kann man das, was hier in das Zoterofeld Zusammenfassung geschrieben wird, unterdrücken? Denn es handelt sich um keine Zusammenfassung.

**Comment by shadeMe** [comment]
Bei mir hat keiner der Artikel dieser Ausgabe irgendwas im Feld "Zusammenfassung". Was taucht bei dir auf?

**Comment by kdr154** [comment]
Das Phänomen tritt nicht mehr auf, auch bei einer anderen ZS auf Dialnet nicht mehr. Ggf. muss man das Issue wieder öffnen.

**Comment by kdr154** [comment]
hier tritt das Phänomen wieder auf:
https://dialnet.unirioja.es/ejemplar/509395
Im Feld Zusammenfassung steht bei folgendem Artikel:
https://dialnet.unirioja.es/servlet/articulo?codigo=6797622
Folgendes;

Autoría: Loredana Sist.
Localización: Orientalia. Nº. 2, 2018.
Artículo de Revista en Dialnet.

Das ist der Inhalt auf der Einzelseite unterhalb des Titels

**Comment by shadeMe** [comment]
![Screenshot_20191011_115947](https://user-images.githubusercontent.com/214450/66643267-a1d86c00-ec1e-11e9-9b22-3242b58853a5.png)

Tritt nicht bei mir auf. Solange der "Dialnet" Translator benutzt wird, wird das Zusammenfassung Feld leer sein.

**Comment by kdr154** [comment]
Ist behoben
