### ISSUE TITLE
ISSN 1689-8311 European journal for philosophy of religion Tag 084 SSG-Nummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#274]
In 084 $a steht die SSG-Nummer. In diesem Fall muss es die "0" sein, statt der "1".
Dies scheint mir aber eine Frage von allgemeiner Natur zu sein. Ich meine, dass bei allen Zeitschriften bisher die "1" gesetzt wurde und nicht differenziert wird zwischen 0, 1 und 0$a1. Die Lösung kann sich demnach nicht auf die Lösung bei dieser Zeitschrift beschränken.

Die Information ist abgelegt im Zeder-Feld "ber", und zwar in der Form FG_0, FG_1, FG_0/1 und -?-
Was in Pica umgesetzt werden muss in 0 (FG_0), 1 (FG_1), 0$a1 (FG_0/1). 
-?- bedeutet, dass dies in Zeder noch nicht festgelegt wurde, in Pica wird dann der Standardwert 1 gesetzt.

In Marc21 sieht es so aus:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">1</subfield>
<subfield code="2">ssgn</subfield>
</datafield>
```
Bei 0 und 1 ist der Fall klar. Bei FG_0/1 müsste in meinen Augen das Unterfeld $a wiederholt werden. Würde heißen:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">0</subfield>
<subfield code="a">1</subfield>
<subfield code="2">ssgn</subfield>
</datafield>
```
-?-  muss entweder in Vorfeld bereinigt werden oder ebenfalls in den Wert 1 umgewandelt werden.
Die Umsetzung ins Pica-Format 5056 0$a1 müsste bei der Umwandlung von Marc21 in Pica geschehen.

Leider ist es so, dass sich die Belegung des Feldes 5056 bei der Gesamtaufnahme einer Zeitschrift im K10Plus von der der dazugehörenden Aufsätze unterscheiden kann.

**Comment by shadeMe** [comment]
Ich passe den Harvester so an, dass wenn die SSGN-Nummer "0$a1" heißt, wird sie in MARC21 als folgendes umgesetzt:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">0</subfield>
<subfield code="a">1</subfield>
<subfield code="0">ssgn</subfield> 
</datafield>
```

**Comment by kdr154** [comment]
Bei ssgn muss mit der "2" eingeleitet werden. Also
`<subfield code="2">ssgn</subfield> `
und nicht
`<subfield code="0">ssgn</subfield> `

**Comment by kdr154** [comment]
gelöst
