### ISSUE TITLE
ISSN 1689-8311 European journal for philosophy of religion Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#275]
Ältere Heft enthalten Rezensionen, was anhand der hier behandelten Ausgabe nicht getesten werden kann:
z. B.:
https://webapp.uibk.ac.at/ojs2/index.php/EJPR/issue/view/225
Wie man sehen kann, stehen sie in einer Sektion "Book Reviews and Notices"

**Comment by kdr154** [comment]
Wie gesagt, kann man es mittels des aktuellen Feeds nicht testen. Dieser enthält nur zwei Einträge, beides keine Rezensionen. Was soll man da machen? Schließen oder warten?

**Comment by shadeMe** [comment]
Vom Translator her, werden Rezensionen richtig getaggt. Und anhand dieses [Artikels](https://webapp.uibk.ac.at/ojs2/index.php/EJPR/article/view/2653), erkennt der Harvester sie auch richtig. Daher schließe ich es.
