### ISSUE TITLE
ISSN 1545-6935 History of religions Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#276]
Eine immer wieder anzutreffende Erscheinung sind Seitenzahlen in römischen Ziffern (I, II, V, i, iv ...) Nach RDA sollen ausschließlich arabische Ziffern verwendet werden. Hinzu kommt, dass sie mal groß (II) mal klein (ii) geschrieben sind. Lohnt es sich hier eine Konkordanz zu erstellen? Wenn ja, in welcher Form?
In diesem Heft findet sich leider auch noch eine von-bis Angabe mit gleichen Seitenzahlen, bei der es auch nur eine Zahl sein sollte: ii-ii (obwohl auf der Seite nur ii steht) sollte sein 2 und sonst nichts:
Der Titel In memoriam hier: https://www.journals.uchicago.edu/toc/hr/2019/58/4

`<subfield code="h">ii-ii</subfield>` -> `<subfield code="h">2</subfield>`
Dies wurde meines Wissen bei der arabischen Zählung bereits umgesetzt

**Comment by shadeMe** [comment]
Ich schreibe was auf der Harvester-Seite, um römische Ziffer in arabische Ziffer umzuwandeln. Was das zweite Problem angeht, erkennt der Harvester bereits, wenn die von-bis Seitenangabe die gleichen Zahlen beinhaltet, und korrigiert sie bei der MARC21-Umsetzung.

**Comment by kdr154** [comment]
Gelöst
