### ISSUE TITLE
ISSN 1469-2147 Cambridge quarterly of healthcare ethics Fehlermeldungen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#283]
Hier bekommt man vom Harvester viele Fehlermeldungen Object not found und Error 404, obwohl die XML-Datei gut aussieht.

**Comment by shadeMe** [comment]
Schient richtig zu funktionieren. Bitte nochmal versuchen.

**Comment by kdr154** [comment]
Sehe jetzt auch keine Fehlermeldungen mehr
