### ISSUE TITLE
ISSN 2161-4504 Journal of pastoral theology Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#293]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```
Sie stehen in der Sektion "Reviews". Zudem ist jede Rezension mit "Book review" überschrieben

**Comment by kdr154** [comment]
Bei den beiden Rezensionen in Heft 29.2019,1 fehlt 655. Statt dessen ist eine aus der Abteilung Latest Articles damit getaggt. Bei einer weiteren aus dieser Abteilung, die in der Sektion "Book Review" und nicht "Book Reviews" steht, fehlt er ebenfalls.

**Comment by shadeMe** [comment]
Was ist die URL der falsch getaggte Artikel?

**Comment by kdr154** [comment]
https://www.tandfonline.com/doi/full/10.1080/10649867.2019.1636510

**Comment by kdr154** [comment]
gelöst
