### ISSUE TITLE
ISSN 2046-5734 Medieval mystical theology Mix aus Latest Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#295]
Die Daten enthalten Artikel, die keinem Heft zugeordnet sind (Latest Article) und solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292

**Comment by kdr154** [comment]
Aktuell sind keine Online First Artikel mehr enthalten
