### ISSUE TITLE
ISSN 2046-5734 Medieval mystical theology Rezensionen Tag 650

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#297]
Bei den Rezensionen wird hier ein Schlagwort "Book Reviews" generiert. 
Dieses sollte allerdings der LOC Marc21 Dokumentation zufolge in Feld 655 stehen, und nicht in 650, da es sich um ein Formschlagwort handelt.
Statt:
```
<datafield tag="650" ind1=" " ind2="4">
<subfield code="a">Book Reviews</subfield>
</datafield>

```
müsste es sein:
```
<datafield tag="655" ind1=" " ind2="4">
<subfield code="a">Book Reviews</subfield>
</datafield>
```
Das gilt analag auch für das Schlagwort "Peer reviewed"

**Comment by shadeMe** [comment]
Das "Book Reviews" Schlagwort ist nicht Teil der Metadaten sonder von der Translator generiert. Es ist tatsächlich nur ein Hinweis für den Zotero-Harvester und wird automatisch gelöscht, nachdem der Harvester es erkennt und demzufolge den Datensatz als Rezension umsetzt.

**Comment by kdr154** [comment]
Gelöst
