### ISSUE TITLE
SSOAR_MARC 21 Feld 856 $s

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#30]
In 856 $s steht in 691 Fällen " bytes" ohne Inhalt.

Beispiel:
col_collection_102070000000011

Das sollte m.E. - abweichend von 561 https://github.com/ubtue/DatenProbleme/issues/26 - entfallen, da die Information fehlt.

**Comment by kdr154** [comment]
40 Fälle sind stehen geblieben

**Comment by jriedl** [comment]
Ist behoben: krim_ssoar-20181018.xml an der üblichen Stelle.

**Comment by IxTheoKm** [comment]
Okay
