### ISSUE TITLE
ISSN 1466-769x Nursing philosophy Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#301]
Bei allen Artikeln stehen Seitenangaben in 773 und/oder in 936, die damit nichts zu tun haben sondern einer anderen Information auf den Webseiten entnommen sind. 
Etwa: `<subfield code="g">20 (2019), 3, Seiten e12261</subfield>`
bei folgendem Artikel: https://onlinelibrary.wiley.com/doi/10.1111/nup.12261

**Comment by shadeMe** [comment]
Ebenso wie bei #303.

**Comment by kdr154** [comment]
Ebenfalls weglassen oder unterdrücken

**Comment by kdr154** [comment]
Gelöst
