### ISSUE TITLE
ISSN 2077-1444 Religions / Molecular Diversity Preservation International (MDPI) Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#303]
Die Angaben zu den Seitenzahlen in 773 $g und 936 $h haben nichts mit den tatsächlichen Seitenzahlen zu tun, sondern basieren auf einer Zahl, die hinter der Angabe zur Ausgabe auf der Webseite des Artikels steht. Beispielsweise:
`<subfield code="g">10 (2019), 7, Seiten 419</subfield>`
bei folgendem Artikel:
https://www.mdpi.com/2077-1444/10/7/419

**Comment by shadeMe** [comment]
Eine genauere Angabe scheint es nicht zu geben bei dieser Webseite/Zeitschrift.

**Comment by kdr154** [comment]
Auch ein Fall für $y. Ich denke, es handelt sich um eine Zahl, die die Artikel hochzählt. Solange man nicht weiß, um was es sich handelt, würde ich sagen: weglassen

**Comment by kdr154** [comment]
Gelöst
