### ISSUE TITLE
ISSN 2199-4625 Journal of Religious Education Mix aus Latest Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#304]
Daten enthalten sowohl Titel, die einem Heft zugeordnet sind, als auch solche, bei denen das nicht der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302

**Comment by kdr154** [comment]
Keine Online First mehr
