### ISSUE TITLE
ISSN 2199-4625 Journal of Religious Education Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#305]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Rezensionen sind daran zu erkennen, dass auf der Seite einer Ausgabe der Eintrag mit "BookReview" überschrieben ist. Auf der Webseite für die Rezension selbst findet sich dazu nichts.
Vgl.
https://link.springer.com/journal/40839/66/3
und
https://link.springer.com/article/10.1007/s40839-018-0072-x

**Comment by shadeMe** [comment]
Nochmal wie bei #317.

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift müssen Rezensionen händisch getaggt werden..

**Comment by kdr154** [comment]
Wird auch geschlossen. Dann sollte aber diese ZS, wie auch #315 und #317 von der Liste für das automatische Verfahren genommen werden.
