### ISSUE TITLE
ISSN 1872-0226 Contemporary Islam: Dynamics of Muslim Life Mix aus Latest Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#308]
Daten enthalten Titel, die keinem Heft zugeordnet sind, als auch solche, die dies sind

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304

**Comment by kdr154** [comment]
Keine Online First mehr
