### ISSUE TITLE
ISSN 1872-0226 Contemporary Islam: Dynamics of Muslim Life Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#309]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>

```
Rezensionen sind daran zu erkennen, dass ihr Eintrag in der Gesamtübersicht eines Heftes mit "ReviewPaper" überschrieben ist. Auf der Webseite für die Rezension selbst findet sich kein solcher Eintrag.
Der Titel von Rezenionen wird, soweit ich es überblicke, mit den Worten "Review of ..." eingeleitet. 
Es gibt dann aber auch Titel wie: "Correction to: Review of ...". Was keine Rezension ist. Ein zuverlässiges Kriterium ist diese Wendung somit nur, wenn sie zu Beginn des Titels steht.

**Comment by kdr154** [comment]
Muss zurückgestellt werden, da das aktuelle Heft keine Rezensionen besitzt und die hier als solche getaggten aus der Abteilung Online First stammen

**Comment by shadeMe** [comment]
Meinst du, dass Online First Artikel und Rezensionen einander ausschließen bzw. sie nicht als solche getaggt werden dürfen?

**Comment by kdr154** [comment]
Nein, das ist überhaupt kein Problem. Sie sollten nur als solche erkannt werden. Da sie hier sowohl bei den einzelnen Ausgaben als auch als Online First immer mit ReviewPaper überschrieben sind, sollte dies ja der Fall sein. Ob und wie wir die Online First Artikel ausschließen, ist eine andere Frage, die mit der Kennzeichnung als Rezension nichts zu tun hat

**Comment by shadeMe** [comment]
Okay. Dann können wir dieses Issue schließen, wenn der Harvester die jetzigen Rezensionen richtig taggt.

**Comment by kdr154** [comment]
Ja
