### ISSUE TITLE
ISSN 2196-8802 International Journal of Dharma Studies Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#311]
Das, was in 773 $g und 936 $h steht sind keine Seitenzahlen und auch nicht die Gesamtzahl der Seiten eines Artikels sondern die Artikelnummer. 
https://link.springer.com/journal/40613/5/1

**Comment by shadeMe** [comment]
Außer der Artikelnummer gibt es auf den einzelnen Seiten keine andere Angabe zu den Seitenzahlen.

**Comment by kdr154** [comment]
Siehe dazu #323

**Comment by kdr154** [comment]
Gelöst
