### ISSUE TITLE
ISSN 1574-9282 International Journal of Hindu Studies Mix aus Online First und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#313]
In den Daten befinden sich Titel, die keinem Heft zugeordnet sind, und solche, bei denen das der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308

**Comment by kdr154** [comment]
Keine Online First mehr
