### ISSUE TITLE
ISSN 1574-9282 International Journal of Hindu Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#314]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

In dieser Zeitschrift gibt es Sammelrezensionen, die den Titel "Book Reviews" tragen
https://link.springer.com/article/10.1007/s11407-019-09252-5
Dies ist nicht nur in dieser Ausgabe der Fall, sondern auch in den anderen.

**Comment by kdr154** [comment]
Muss zurückgestellt werden, da das aktuelle Heft keine Rezensionen enthält

**Comment by socheres** [comment]
dito #844

**Comment by kdr154** [comment]
Rezensionen werden getagt
