### ISSUE TITLE
ISSN 1574-9282 International Journal of Hindu Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#315]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Eine zweite Form von Rezensionen in dieser Zeitschrift sind Artikel, die in der Artikelliste einer Ausgabe mit "ReviewPaper" überschrieben sind:
https://link.springer.com/journal/11407/22/3
Auf der Seite für den jeweiligen Artikel finden man diesen Hinweis nicht:
https://link.springer.com/article/10.1007/s11407-018-9243-3

**Comment by shadeMe** [comment]
Das gleiche Problem wie bei #317.

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift müssen Rezensionen händisch getaggt werden.

**Comment by kdr154** [comment]
Dann wird auch dieses geschlossen
