### ISSUE TITLE
ISSN 1573-0395 Journal of Indian Philosophy Mix aus Online First Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#316]
Die Daten enthalten Artikel, die noch keiner Ausgabe zugeordnet sind, und solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313

**Comment by kdr154** [comment]
Keine Online First mehr
