### ISSUE TITLE
ISSN 1573-0395 Journal of Indian Philosophy Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#317]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Rezensionen sind auf der Titelliste eines Heftes mit "ReviewPaper" überschrieben. 
https://link.springer.com/journal/10781/47/3
Auf der Seite für den Artikel findet sich kein solcher Hinweis
https://link.springer.com/article/10.1007/s10781-019-09388-z

**Comment by shadeMe** [comment]
Bei dieser Zeitschrift müssen Rezensionen händisch getaggt werden, befürchte ich.

**Comment by shadeMe** [comment]
Meiner Meinung nach können wir dieses Issue schließen.

**Comment by kdr154** [comment]
In Ordnung
