### ISSUE TITLE
ISSN 1528-6924 Journal of Religious & Theological Information Mix aus Latest Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#318]
Die Daten enthalten Aufsätze, die keinem Heft zugeordnet sind, und solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316

**Comment by kdr154** [comment]
Keine Online First mehr
