### ISSUE TITLE
Sabinet ISSN 0254-8356 Jewish believers in Paul’s letter to the Romans Tag 773 $g

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#32]
$g ist falsch und unvollständig.
Hier: `<subfield code="g">volume: 52</subfield>`
Müsste lauten;
`<subfield code="g">52(2018) , 1, S. 1-40</subfield>`

**Comment by mtrojan-ub** [comment]
Kann jetzt getestet werden. Aber die ISSN habe ich in unserer Harvester-Konfiguration nicht gefunden - bezieht sich der Issue stattdessen 2518-4628 (Neotestamentica)? Dort kommt ein Artikel mit dem selben Namen vor.

**Comment by kdr154** [comment]
773 bei ISSN 2518-4628 sieht jetzt gut aus. 936 auch. Die ISSN bezieht sich auf Neotestamentica. Die ISSN in diesem Projekt immer auf das übergeordnete Werk, die Zeitschrift. Der Titel in der Regel, aber nicht immer, auf einen einzelnen Aufsatz in einer Zeitschrift. So hatten wir es besprochen. Das macht auch Sinn, da bei es bei verschiedenen Aufsätzen in einer ZS zu unterschiedlichen Problemen kommen kann.
