### ISSUE TITLE
ISSN 1478-1913 The Muslim World Mix aus Early View Artikel und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#321]
Die Daten enthalten Titel, die noch nicht in eine Ausgabe intergriert sind, und solche, bei denen das der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318

**Comment by kdr154** [comment]
Keine Online First mehr
