### ISSUE TITLE
ISSN 1943-1562 Psychology of religion and spirituality

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#322]
Das Harvesting liefert keine Daten. Der Link auf Zeder führt zu Ebsco. Die Artikel und Ausgaben sind aber gelistet auch beim Herausgeber: https://psycnet.apa.org/PsycARTICLES/journal/rel/11/2
Die Daten dort sehen gut aus. Möglicherweise muss man erst mal einen Translator schreiben.
Die Links vom Feed führen auf keine Seite, von der es weiter geht. 
Bsp.: https://psycnet.apa.org/record/2019-25624-001

**Comment by shadeMe** [comment]
Anscheinend wird der Harvester von dem Server blockiert. Ich schreibe an die PsycNet-Verwaltung und erkläre was wir genau machen. 

Ich setze das Issue derzeit auf "blocked".

**Comment by shadeMe** [comment]
Diese Zeitschrift ist leider für das vollautomatische Verfahren nicht geeignet. Beim halbautomatischen Verfahren funktioniert der bereits existierende "APA PsycNET" Translator gut.

**Comment by kdr154** [comment]
Dann schließe ich.
