### ISSUE TITLE
ISSN 2053-6712 Secularism and Nonreligion Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#323]
Die Seitenzahlen, die hier ausgegeben werden sind in Wirklichkeit die Artikelnummern, die in der Übersicht eines Heftes zu finden sind:
https://secularismandnonreligion.org/8/volume/8/issue/0/

**Comment by shadeMe** [comment]
Das ist leider die einzige Angabe, die dem Translator zur Verfügung steht.

**Comment by kdr154** [comment]
Nun gut, dann dürfen sie aber nicht als Seitenzahlen erscheinen. Für diese Fälle müsste/könnte man in Marc 936 ein weiteres Unterfeld $y generieren, in dem man Informtionen, die standardmäßig nicht abgedeckt sind, unterbringen kann. Der Inhalt von $y kommt im K10Plus zur Anzeige, die anderen Angaben z. B. 936 $d, $e ... werden maskiert. D. h., man müsste in diesen Fällen diese Informationen alle in $y unterbringen. Bei der hier behandelten Zeitschrift etwa $y2019, Artikel 8:1 usw.
Über alle bearbeiteten Zeitschriften gesehen, bei denen $y angelegt werden müsste, hat man dann natürlich Varianten, die im jeweiligen Fall definiert werden müssten. Aber denkbar und sinnvoll wäre das schon.

**Comment by kdr154** [comment]
Ok, aber $y sollten wir nicht aus den Augen verlieren, denn diese ZS ist nicht die einzige, bei der das zur Anwendung kommen könnte. Aus meiner Sicht eines Laien kann ich mir vorstellen, dass dies zu programmieren kein übertriebener Aufwand ist. Ich schließe das Issue
