### ISSUE TITLE
ISSN 1874-6349 Acta Analytica Mix aus Online First und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#325]
Die Daten enthalten Artikel, die keinem Heft zugeordnet sind und solche, bei denen das der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318 #321

**Comment by kdr154** [comment]
Keine Online First mehr
