### ISSUE TITLE
ISSN 1572-8609 The journal of ethics : an international philosophical review Mix aus Online First und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#326]
Daten enthalten sowohl Titel, die keinem Heft zugeordnet sind, als auch solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318 #321 #325

**Comment by kdr154** [comment]
Keine First Online Artikel mehr
