### ISSUE TITLE
ISSN 1478-0542 History compass Seitenzahlen in 773 und 936

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#327]
Das was hier als Seitenangabe steht sind keine Seitenzahlen, sondern eine Angabe, die sich auf etwas anderes bezieht.
https://onlinelibrary.wiley.com/toc/14780542/2019/17/7

**Comment by shadeMe** [comment]
Ich sehe leider keine andere Angabe, die wie Seitenzahlen aussieht.

**Comment by kdr154** [comment]
Nur im PDF. Aber diese Angabe, wahrscheinlich die Wiley-interne Nummer des Dokuments, darf nicht als Seitenzahl auftauchen.

**Comment by kdr154** [comment]
Gelöst
