### ISSUE TITLE
ISSN 1478-0542 History compass Mix aus Early View Artikeln und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#328]
Die Daten enthalten sowohl Titel, die einem Heft zugeordnet sind, als auch solche, bei denen dies noch nicht der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318 #321 #325 #326

**Comment by kdr154** [comment]
Keine Online First Artikel mehr
