### ISSUE TITLE
ISSN 2009-7379 The international journal of religious tourism and pilgrimage

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#329]
Die XML-Datei enthält keine Daten, wie auch der Feed selbst. Die Zeitschrif selbst scheint aber noch aktiv zu sein.
https://arrow.dit.ie/ijrtp/vol7/iss3/

**Comment by shadeMe** [comment]
Diese Zeitschrift ist leider ungeeignet für das RSS-Verfahren. Ich schalte sie auf der Oberfläche aus.

**Comment by kdr154** [comment]
ok
