### ISSUE TITLE
Sabinet ISSN 0254-8356 Jewish believers in Paul’s letter to the Romans Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#33]
Die Seite auf Sabinet zeigt Keywords:
https://journals.co.za/content/journal/10520/EJC-fc330b739?TRACK=RSS
Diese sollten, wenn ich die Dokumentation richtig interpretiere, in diesem Fall in der folgenden Form übernommen werden:
```
<datafield tag="650" ind1=" " ind2=" ">
<subfield code="a">Faithfulness of God</subfield>
usw.

```

**Comment by mtrojan-ub** [comment]
@shadeMe : bitte prüfen, die keywords erscheinen nicht in Zotero. Ist hier ein Translator notwendig? (sollen wir für Issues mit Translator-Anpassung ein weiteres Label einführen?)

**Comment by kdr154** [comment]
Ja, das wäre ein Desiderat. Vielleicht ein Label mit dem Namen "Translator!"

**Comment by shadeMe** [comment]
Implementiert in ubtue/zotero-translators#25.

**Comment by shadeMe** [comment]
@kdr154 Haben Sie die Translators manuell per Copy-Paste aktualisiert? Ein normaler Git-Pull funktioniert in dem jetzigen Zustand nicht, weil die Änderungen noch nicht gemergt geworden sind. Wenn es allerdings der erste Fall wäre, ist es echt komisch, weil sie auf meinem Rechner schon funktionieren. Es kann dran liegen, dass entweder Zotero oder Ihr Webbrowser die alten Versionen der Translators gecacht hat.

Koennten Sie bitte den Zotero-Connector Browser-Plugin neuinstallieren und/oder Ihren Browser cache leeren?

**Comment by kdr154** [comment]
@shadeMe Ehrlich gesagt weiß ich gar nicht wo der aktualisierte  Translator zu finden ist und wie er heißt. Einen Translator für Sabinet kann ich nicht finden und wenn ich dem Link oben folge, komme ich zu dem Translator von Scielo, und dieser scheint mir vor langer Zeit aktualisiert worden zu sein.

**Comment by mtrojan-ub** [comment]
Bitte nochmal testen. Keywords sind jetzt auch da, allerdings in 653, wie in #66 gewünscht.

**Comment by kdr154** [comment]
Gelöst
