### ISSUE TITLE
ISSN 2055-7981 British Catholic history Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#330]
Bei den Rezensionen fehlt Marc21 Tag 655:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Rezensionen findet man in dieser Zeitschrift als Review Article und Book Review. Sie stehen in den entsprechenden Sektionen
"Review Article"
"Book Review"
Die Rezensionen in der Sektion "Book Review" haben, zumindest in der aktuellen Ausgabe, alle die Zeichenfolge "ISBN:" im Titel

**Comment by kdr154** [comment]
Bei den Rezensionen in der Sektion "Review Article" fehlt 655 weiterhin. Die Sektion "Book Review" ist ok.

**Comment by shadeMe** [comment]
Hier befindet sich das gleiche Problem wie bei #262.

**Comment by kdr154** [comment]
Dann schließe ich das auch
