### ISSUE TITLE
ISSN 1468-0025 Modern theology Mix aus Early View und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#332]
Daten enthalten Titel, die noch keinem Heft zugeordnet sind, und solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318 #321 #325 #326 #332

**Comment by kdr154** [comment]
Keine First Online Artikel mehr
