### ISSUE TITLE
ISSN 1740-7931 British journal of religious education : BJRE Mix aus Latest Articles und Standardartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#336]
Daten enthalten sowohl Titel, die keinem Heft zugeordnet sind, als auch solche, bei denen dies der Fall ist.

**Comment by socheres** [comment]
dito #285 #290 #292 #295 #299 #302 #304 #308 #313 #316 #318 #321 #325 #326 #332 #335

**Comment by kdr154** [comment]
Keine Online First Artikel mehr
