### ISSUE TITLE
Sabinet ISSN 0254-8356 Jewish believers in Paul’s letter to the Romans  handle

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#34]
Die Seite hat zwar keinen DOI, aber einen handle. Dieser müsste wie folgt übernommen werden

```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10520/EJC-fc330b739</subfield>
<subfield code="2">hdl</subfield>
```

zusätzlich sollte/könnte 856 vergeben werden:
```
<datafield tag="856" ind1="4" ind2=" ">
<subfield code="u">https://hdl.handle.net/10520/EJC-fc330b739</subfield>

```

**Comment by mtrojan-ub** [comment]
@shadeMe : Handle erscheint nicht in Zotero, Translator Anpassung notwendig. Was machen wir damit? Ähnlich #33

**Comment by ruschein** [comment]
@mtrojan-ub Den neuen, von mir implementierten, Mechanismus verwenden und das Handle im "notes" Feld durchreichen.

**Comment by shadeMe** [comment]
Implementiert in ubtue/ub_tools#2244 und ubtue/zotero-translators#25.

**Comment by mtrojan-ub** [comment]
Handle kommt jetzt auch mit, bitte nochmal testen.

**Comment by kdr154** [comment]
Gelöst
