### ISSUE TITLE
ISSN 1689-8311 European journal for philosophy of religion Nur Online First

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#345]
Die getesteten Daten enthalten nur First online Artikel

**Comment by shadeMe** [comment]
Was ist das Problem dabei?

**Comment by kdr154** [comment]
Da wir die wahrscheinlich nicht aufnehmen, sollten die Testdaten schon auch Artikel aus den einzelnen Ausgaben haben. Sonst kann man keine endgültiges Urteil fällen.

**Comment by shadeMe** [comment]
Ach so. Die Online-First werden trotzdem beim Test- und Produktionsverfahren unbedingt ignoriert. Nur auf der Weboberfläche werden sie zwecks des Testens geharvestet.

Ich denke, für sowas brauchen wir kein Issue zu offnen, weil es nicht um ein Datenproblem geht.

**Comment by kdr154** [comment]
Na ja, aber abgeschlossen ist diese ZS ja noch nicht, da wir keine gültigen Testdaten haben,

**Comment by shadeMe** [comment]
Okay, dann setze ich das Issue auf "blocked".

**Comment by shadeMe** [comment]
@kdr154 Wie sieht es jetzt bei diesen Blocked Issues aus?

**Comment by kdr154** [comment]
Die Daten enthalten jetzt Aufsätze, die Heften zugeordnet sind. 
Allerdings ist der Wert in 935 falsch, Es muss bei dieser ZS mteo sein und nicht mkri
```
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="a">mkri</subfield>
</datafield>
```

**Comment by kdr154** [comment]
935 ist jetzt korrekt
