### ISSUE TITLE
ISSN 2657-3555 European Journal for the Study of Thomas Aquinas Abstract Keywords ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#346]
https://content.sciendo.com/view/journals/ejsta/ejsta-overview.xml
Diese ZS ist neu und soll aufgenommen werden. Im halbautomatischen Verfahren fehlen das Abstract, die Keywords und die ISSN.
Die ISSN befindet sich in dem Frame auf der rechten Seite, Abstract und Keywords auf den Seiten der einzelnen Aufsätzen.

**Comment by shadeMe** [comment]
Ich habe einen neuen Translator geschrieben, der "ubtue_Sciendo.js" heißt.

**Comment by kdr154** [comment]
Habe den Translator heruntergeladen, alles geschlossen und aktualisiert, aber der Sciendo Translator ist dem System unbekannt.

**Comment by kdr154** [comment]
Gelöst
