### ISSUE TITLE
Sabinet ISSN 0254-8356 Jewish believers in Paul’s letter to the Romans Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#35]
Der Language code fehlt. Die Sprache steht auf der Seite ganz unten. Language: English. Muss in das Marc21-Feld 041.
In der folgenden Form:

```
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">eng</subfield>
</datafield>
```

Die Sprachbezeichnungen sind normiert: http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/inhaltserschliessung/sprachenCodesDeutsch.pdf?__blob=publicationFile

Eventuell macht es Sinn eine Konkordanz für vorkommenden Sprachen zu schreiben.

**Comment by ruschein** [comment]
@kdr154 Bitte verwenden Sie Issue-Titel, die das Problem beschreiben: Z.B. "Language Code Fehlt bei Zeitschrift XYZ" etc.  Ich kann mir unter Ihren Titeln leider nichts vorstellen.

**Comment by mtrojan-ub** [comment]
Beim aktuellen Test auf nu steht "eng" in 041a, also müsste das bereits so funktionieren.

**Comment by kdr154** [comment]
gelöst
