### ISSUE TITLE
ISSN 2309-9089 Acta Theologica Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#350]
Von dieser Seite:
https://journals.co.za/content/journal/theolog/browse?page=previous-issues
kommen die Keywords nicht mit.
Zudem funktioniert nur der Einzeldownload

**Comment by shadeMe** [comment]
Bitte den "ubtue_Sabinet.js" Translator vom Repo aktualisieren.

**Comment by kdr154** [comment]
Sehr gut, auch der Multidownload funktioniert
