### ISSUE TITLE
ISSN 2386-7442 Collectanea Christiana orientalia : CCO - nicht verlinkte Artikel und Beiträge

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#351]
Die Beiträge, die keinen Link besitzen, z.  B. Rezensionen, aber nicht nur die, werden nicht erfasst.
hier z. B.:
https://www.uco.es/revistas/index.php/cco/issue/view/66
fehlt alles, was nach der Sektion Articulos kommt.

**Comment by shadeMe** [comment]
Der Translator kann Beiträge leider nicht erfassen, die keine Einzelseite besitzen.

**Comment by shadeMe** [comment]
@kdr154 Dieses Issue kann geschlossen werden.

**Comment by kdr154** [comment]
Geschlossen
