### ISSUE TITLE
ISSN 0101-3130 Estudos teológicos Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#354]
Rezensionen werden nicht als solche getagt:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Sie stehen in der Sektion "Resenhas"
http://periodicos.est.edu.br/index.php/estudos_teologicos/issue/view/296

**Comment by kdr154** [comment]
Vgl. #446

**Comment by shadeMe** [comment]
@kdr154 Wir brauchen einen RSS Feed für diese Zeitschrift.

**Comment by kdr154** [comment]
ungeeignet für das automatische Verfahren
