### ISSUE TITLE
ISSN 2161-007X Counseling and Values Zeitproblematik

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#357]
Bei dieser Zeitschrift ist der Vorgang des Crawlens auch nach über 8 Stunden nicht abgeschlossen. Wenn ich mich richtig erinnere, werden unsere PCs in der Nacht heruntergefahren und wieder neu gestartet, wenn man sie laufen lässt. Ich habe den Vorgang deshalb bei jedem Test abgebrochen. Lasse ihn aber heute mal über Nacht laufen.

**Comment by shadeMe** [comment]
Es gibt mehrere Ursachen dafür. Primär ist die Anzahl der Hefte und Bände - Der Harvester berücksichtigt alle Hefte von 1950 bis 2019, die jeweils durchschnittlich 10 Artikel beinhalten. Außerdem müssen wir das Harvesting-Verfahren künstlich verlangsamen, damit wir nicht blockiert werden.

Meines Erachtens sollten wir zunächst versuchen, wenigere Hefte zu harvesten.
