### ISSUE TITLE
ISSN 1370-6020 Intams review Exitcode 1 und disNach

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#358]
Intams review ist der Vorgänger und existiert aktuell nicht mehr. Möglicherweise ist das der Grund, dass der Harvester aussteigt.
Seit 2017 heißt die Zeitschrift Marriage, Families & Spirituality (E-ISSN 2593-0486):
https://poj.peeters-leuven.be/content.php?url=journal&journal_code=INT
Dort sind alle Ausgaben zu finden, auch die des Vorgängers Intams Review
Hierzu auch #422

**Comment by shadeMe** [comment]
Kannst du bitte auch den Zeder-Eintrag aktualisieren?

**Comment by kdr154** [comment]
Zeder ist völlig korrekt! Steht auf disnach (Erscheinen eingestellt, Nachfolger), mit der ZDB-Nummer des Nachfolgers

**Comment by shadeMe** [comment]
@kdr154 Bitte nochmal testen.

**Comment by kdr154** [comment]
Crawl läuft jetzt problemlos. Die Daten sind jedoch die von 1999-2010. Die brauchen wir nicht, da dieser Vorgänger des aktuellen Titels (s. o.) komplett erfasst ist.
Für den Nachfolger, siehe #422, ist RSS aktiviert. Dort bricht der Harvester jedoch bereits nach 2 Sekunden ab.
Dieser Eintrag hier kann in meinen Augen von der Liste des Harvesters genommen werden, es sei denn, es ließen sich auch die aktuellen Hefte des Nachfolgers damit erfassen und sofern man die Probleme mit dem RSS-Feed des Nachfolgers nicht in den Griff bekommt.

**Comment by kdr154** [comment]
Problem mir #422 existiert weiter, 1370-6020 Intams weiter Bestand des Harvesters.

**Comment by kdr154** [comment]
Intams nicht mehr bestandteil des Harvesters
