### ISSUE TITLE
Allgemein Sondersammelgebietsnummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#36]
Es muss eine Lösung gefunden werden, wie die Aufsätze/Zeitschriften den Sondersammelgebieten zugeordnet werden können, da sie nicht in den Aufsätzen selbst enthalten sind.
Im Fall der FIDs Theologie und Religionswissenschaft haben wir die "0" für die Religionswissenschaft und die "1" für die Theologie. In manchen Fällen vergeben wir beides "0; 1"
Sie gehört in das Marc21 Tag 084 in der Form:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">1</subfield>
<subfield code="2">ssgn</subfield>
</datafield>
```

**Comment by mtrojan-ub** [comment]
Dafür gibt's schon eine Implementation mit Map-Datei, siehe:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_SSG.map

Können Sie uns eine Beispiel-ISSN nennen die in dieser Liste korrekt enthalten ist, bei der die SSG-Nummer aber **nicht** korrekt übernommen wurde?

**Comment by kdr154** [comment]
Bei allen! Der Tag 084 kommt in keiner der Dateien vor. Im Übrigen ist diese Mapping-Tabelle ziemlich, wenn nicht sogar völlig, nutzlos. Alle ZS, die ich getestet habe, und die in den Bereich Krimdok fallen, waren in der Liste nicht enthalten. Aber auch Zeitschriften, die sich bei uns im IxTheo in der laufenden Bearbeitung befinden, wie z. B. Veritas, sind in der Mapping-Tabelle nicht enthalten. Zudem sind in den Testdaten Prio1-Zeitschriften, d. h. Zeitschriften, die erst noch aufgenommen werden sollen. Für diese existiert in der Regel noch gar kein Mapping.
Aber die Tatsache, dass die Zuordnung mittels eine solchen Mapping-Tabelle vorgenommen werden kann, deutet ja die Lösung schon an.

**Comment by kdr154** [comment]
Was meinen Sie damit? Wie soll das geschehen?:
"Ich würde Sie darum bitten, dass sie bei einer der Zeitschriften das Mapping eintragen und den Issue schließen, sofern das Mapping dann erfolgreich ist."

**Comment by mtrojan-ub** [comment]
Soweit ich weiß, haben Sie Schreibzugriff auf das zotero-enhancement-maps repository und die darin enthaltene ISSN_to_SSG.map, richtig? (war glaube ich ursprünglich mit Herrn Kim so besprochen)

- Suchen Sie sich eine Zeitschrift aus, die Sie testen wollen (z.B. 2196-7954 - Journal of Ancient Judaism  die ISSN ist noch nicht in der Map enthalten).
- Bitte tragen Sie dann die ISSN mit der passenden SSG-Nummer in die Datei ein
- Geben Sie mir dann bitte bescheid, damit ich die Map auf unserem Testserver neu auschecke
- Dann führen Sie einen Testlauf mit der o.g. Zeitschrift durch und prüfen, ob die SSG jetzt korrekt ankommt

Falls Sie keinen Schreibzugriff haben, können Sie mir auch alternativ in diesem Einzelfall die SSG-Einstellung für diese Zeitschrift zukommen lassen, dann nehme ich es selbst in die Map mit auf. (Dann müssten wir noch klären wie die Pflege der Map in Zukunft genau aussieht)
Falls noch etwas unklar ist, können wir das auch gerne telefonisch besprechen!

**Comment by kdr154** [comment]
Ist so. 

Das Eintragen dauert aber, denn ich habe den Eindruck, es betrifft so gut wie alle ZS in diesem Projekt. Leider entspricht die Struktur nicht der, dich ich für IxTheo pflegen muss. Aber durch ein Austausch- und Bereinigungsverfahren könnte ich Sie in die entsprechende Form bringen. Dann hätte man zumindest aus meiner Sicht eine aktuelle Datei. Und das bisschen KrimDok ist in meiner auch enthalten. 

Im Übrigen sehe ich, dass manchen Zeitschriften keine SSG-Nummer zugeordnet ist. Bei den Zeitschiften im Index Theologicus ist dies auch so. Der Standardwert ist hier die "1", steht für die Theologie. Das heißt auch, dass Zeitschriften, die nur in den Index Theologicus sollen, gar keinen Eintrag in der Sektion SSG-Mapping benötigen. Ist dies in dieser Konkordanz auch so?

 

Mit freundlichen Grüßen

Klaus-Dieter Rosenkranz

 

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Mario Trojan <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 16:46
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Assign <assign@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Allgemein Sondersammelgebietsnummer (#36)

 

Soweit ich weiß, haben Sie Schreibzugriff auf das zotero-enhancement-maps repository und die darin enthaltene ISSN_to_SSG.map, richtig? (war glaube ich ursprünglich mit Herrn Kim so besprochen)

*	Suchen Sie sich eine Zeitschrift aus, die Sie testen wollen (z.B. 2196-7954 - Journal of Ancient Judaism die ISSN ist noch nicht in der Map enthalten).
*	Bitte tragen Sie dann die ISSN mit der passenden SSG-Nummer in die Datei ein
*	Geben Sie mir dann bitte bescheid, damit ich die Map auf unserem Testserver neu auschecke
*	Dann führen Sie einen Testlauf mit der o.g. Zeitschrift durch und prüfen, ob die SSG jetzt korrekt ankommt

Falls Sie keinen Schreibzugriff haben, können Sie mir auch alternativ in diesem Einzelfall die SSG-Einstellung für diese Zeitschrift zukommen lassen, dann nehme ich es selbst in die Map mit auf. (Dann müssten wir noch klären wie die Pflege der Map in Zukunft genau aussieht)
Falls noch etwas unklar ist, können wir das auch gerne telefonisch besprechen!

**Comment by kdr154** [comment]
Lieber Herr Trojan, 

 

habe mich getäuscht. Es ist doch jeder Zeitschrift eine SSG-Nummer zugeordnet.

 

Mit freundlichen Grüßen

Klaus-Dieter Rosenkranz

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Mario Trojan <notifications@github.com> 
Gesendet: Mittwoch, 7. November 2018 16:46
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Assign <assign@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] Allgemein Sondersammelgebietsnummer (#36)

 

Soweit ich weiß, haben Sie Schreibzugriff auf das zotero-enhancement-maps repository und die darin enthaltene ISSN_to_SSG.map, richtig? (war glaube ich ursprünglich mit Herrn Kim so besprochen)

*	Suchen Sie sich eine Zeitschrift aus, die Sie testen wollen (z.B. 2196-7954 - Journal of Ancient Judaism die ISSN ist noch nicht in der Map enthalten).
*	Bitte tragen Sie dann die ISSN mit der passenden SSG-Nummer in die Datei ein
*	Geben Sie mir dann bitte bescheid, damit ich die Map auf unserem Testserver neu auschecke
*	Dann führen Sie einen Testlauf mit der o.g. Zeitschrift durch und prüfen, ob die SSG jetzt korrekt ankommt

Falls Sie keinen Schreibzugriff haben, können Sie mir auch alternativ in diesem Einzelfall die SSG-Einstellung für diese Zeitschrift zukommen lassen, dann nehme ich es selbst in die Map mit auf. (Dann müssten wir noch klären wie die Pflege der Map in Zukunft genau aussieht)
Falls noch etwas unklar ist, können wir das auch gerne telefonisch besprechen!

**Comment by mtrojan-ub** [comment]
Lieber Herr Rosenkranz,

> "Leider entspricht die Struktur nicht der, die ich für IxTheo pflegen muss"

In welcher Form pflegen Sie es denn aktuell? Können wir die Mapping Datei vielleicht auch automatisch aus der Struktur erzeugen die Sie pflegen? (z.B. aus Zeder-Feldern)
Das SSG-Mapping haben wir aus Zotkat übernommen, weil es dort schon in dieser Form existierte, bevor wir mit dem Projekt angefangen haben. Vielleicht ist das aber auch der falsche Weg und wir finden eine einfachere Lösung?

Viele Grüße
Mario Trojan

**Comment by mtrojan-ub** [comment]
So langsam kommt Licht ins Dunkel!

Das mit der Mapping-Pflege an unterschiedlichen Stellen hatten wir schon vor mehreren Monaten mit @socheres thematisiert. 
Damals haben wir gemeinsam eine Version des PicaSWB.js entwickelt, die die o.g. Map als Datenquelle nimmt, damit man das nicht an 2 Stellen pflegen muss.
Allerdings ist diese Version noch nicht live gegangen. (Das war mir bislang nicht bewusst)

@socheres wird das Thema übernehmen und kommt zu den Details direkt auf Sie zu. 

Sorry, dass es hier so viel Verwirrung gab!

**Comment by IxTheoKm** [comment]
Gemäß Besprechung vom 24.09.2019 soll die Spalte "ber" aus ZEDER  mit der Mapping-Tabelle abgeglichen werden. Bei Diskrepanzen muss der Stand jeweils angepasst werden. 
ZEDER soll Master-Datei sein, und die Mapping-Datei nach Möglichkeit daraus aktualisiert werden.

**Comment by shadeMe** [comment]
Die Ergebnisse des Abgleiches findet man im Anhang.

[ssgn_comparison.txt](https://github.com/ubtue/DatenProbleme/files/3651986/ssgn_comparison.txt)

**Comment by thefass** [comment]
es gibt zwei Zeder Instanzen:
eine für IxTheo/RelBib > Instanz: ixtheo
eine für KrimDok > Instanz:krim

**Comment by shadeMe** [comment]
Entschuldigung, ich habe die KrimDok Zeder Instanz vergessen. Die KrimDok Erbegnisse: 
[ssgn_comparison.txt](https://github.com/ubtue/DatenProbleme/files/3652634/ssgn_comparison.txt)

**Comment by kdr154** [comment]
Aber meines Wissens nur eine Mapping-Tabelle, und zwar:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_SSG.map
Die enthält keine KrimDokdaten

**Comment by thefass** [comment]
Zeilen 121-127 und viele weitere sind Kriminologie. Alle wo FID-KRIM-DE-21 steht
