### ISSUE TITLE
ISSN 2312-878X Missionalia Fehlende Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#361]
Die Liste der Artikel, die beim Crawlen erfasst werden, ist unvollständig. Um nicht zu sagen, das meiste fehlt. So wird etwa aus Heft 46 (2018), 3 nur ein Artikel erfasst , aus 42 (2014), 3 ebenfalls nur einer und aus 41 (2013), 2 zwei.
Abgesehen davon ist die Qualität der Daten gut.

**Comment by kdr154** [comment]
Es stimmt weiterhin nicht. Manche Hefte sind vollständig erfasst. Andere nicht. So werden z. B. von Heft 41 (2013), 2 nur der 2. und der 7. Aufsatz erfasst. Diese werden aber an mehreren Stellen zwischendurch wiederholt. 
Die Abfolge der Erfassung geht zudem wild durcheinander, was das Prüfen extrem erschwert. Z. B,ein Aufsatz von 2013, dann ein Heft aus 2018 komplett, dann wieder zwei Aufsätze von 2014 usw. usf.

**Comment by shadeMe** [comment]
Die Abfolge der Erfassung kann ich leider ich beeinflussen, weil es leider von der Darstellung der Webseite abhängt. Auf meinem Rechner werden zwar all Hefte soweit ich es sehe vollständig erfasst aber manche Artikel werden zufolge der Webseite-Darstellung trotzdem wiederholt. Ich werde den Fehler beheben.

**Comment by kdr154** [comment]
Jetzt wird zwar nur ein Heft gescannt, die Artikel sind aber vollständig und die Daten sind korrekt
