### ISSUE TITLE
ISSN 0890-2461 Philosophy and Theology unvollständig?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#364]
Die Daten sind gut, allerdings frage ich mich, warum von den 29 Artikeln von Heft 30,2 nur 9 erfasst wurden

**Comment by kdr154** [comment]
Der nun eingestellte Suchlauf dauert zu lang. Habe ihn jetzt nach über 6 Stunden abgebrochen.

**Comment by shadeMe** [comment]
Ich habe das Problem jetzt nähere geguckt und festgestellt, dass diese Zeitschrift für Crawlen nicht geeignet ist. Es liegt daran, dass das Archiv als ein Suchtrefferliste dargestellt ist. Dies führt der Harvester in eine endloses Schleife, woraus er nicht entkommen kann.

Diese Problematik betrifft eventuell alle von PDCnet gehosteten Zeitschriften. RSS-Feeds wäre dem in diesen Fällen vorzuziehen.

**Comment by shadeMe** [comment]
@kdr154

**Comment by kdr154** [comment]
RSS ist auf dem Harvester eingestellt. Ich schließe dieses Issue
