### ISSUE TITLE
ISSN 0034-429X Renaissance and reformation XML-Datei leer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#365]
Im Ergebnis steht: Disallowed by robots.txt

**Comment by shadeMe** [comment]
Leider sieht es so aus, als ob wir von dem Verlagsserver blockiert wurden. Ich werde diese Zeitschrift temporär deaktivieren.

**Comment by thefass** [comment]
@socheres oder @kdr154: Bitte Verlag kontaktieren

**Comment by socheres** [comment]
@kdr154 bitte alle Crawling-Zeitschriften überprüfen, ob es RSS-Feed gibt und @shadeMe melden. bei dem oben genannten Verlag müsste RSS geben.
