### ISSUE TITLE
ISSN 1133-0104 Anuario de historia de la Iglesia

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#369]
https://www.unav.edu/publicaciones/revistas/index.php/anuario-de-historia-iglesia/issue/archive
Es gibt zwar einen Translator Universidad de Navarra, dieser steht mir im Multidownload nicht zur Verfügung. Im Single muss man ihn jedes Mal mittels Rechstclick im Menu aktivieren. Standardmäßig wird sowohl im Single als auch im Multi der Translator EquinoxPub genommen. Vgl. #372
Zudem wird keine ISSN geliefert. Ich sehe aber auch keine, weder auf der Übersicht, noch auf den Seiten der einzelnen Artikel

**Comment by kdr154** [comment]
Auch hier steht er nicht zur Verfügung. Vgl. #444 und #443

**Comment by shadeMe** [comment]
Es gibt eine neue Version des Translators - https://github.com/ubtue/zotero-translators/blob/master/ubtue_Open%20Journal%20Systems%20Multi-Wrapper.js.

**Comment by socheres** [comment]
Der Multiwrapper Translator funktioniert und die Daten sehen auch gut aus. Bitte nochmal testen.

**Comment by kdr154** [comment]
Der Multiwrapper funktioniert, allerdings fehlt das Abstract. Zudem ist die ZS OA, und da keine ISSN übertragen wird, kann dies nicht über das System umgesetzt werden.

**Comment by socheres** [comment]
Wie wir bereits mit andere  Zss. bereits verfahren, können Sie den Publikationstitel [hier](https://github.com/ubtue/zotero-enhancement-maps/blob/master/publication_title_to_physical_form.map) eintragen. Da Multiwrapper ein globaler Translator für OJS-Plattform ist, muss der Abstract leider von Hand in Zotero ergänzt werden.

**Comment by kdr154** [comment]
ok
