### ISSUE TITLE
Allgemein Lokaldaten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#37]
Vorübergehend zurückgestellt. Das betrifft die Abrufzeichen, etwa zota, (Marc21-Feld 935, Pica 8002) und das Bibliothekssigel IxTheo (Marc21-Feld 852, Pica 7100)

**Comment by mtrojan-ub** [comment]
In Absprache mit @ruschein wird der Issue geschlossen, da "vorübergehend zurückgestellt". Bitte Issue erneut öffnen mit genauer Definition, sobald wir konkret aktiv werden können.

**Comment by IxTheoKm** [comment]
Unter https://github.com/ubtue/DatenProbleme/issues/456 wieder geöffnet
