### ISSUE TITLE
ISSN 0104-0529 Revista de cultura teológica 773 $g fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#371]
Bei den records, die bei dieser ZS tatsächlich Aufsätze abbilden (vgl. #367), wird kein $g in 773 gebildet

**Comment by shadeMe** [comment]
Ich glaube, dass diese Zeitschrift keine gültige Band Nr. hat, weswegen 773$g nicht generiert wird.

**Comment by shadeMe** [comment]
@kdr154 Dieses Issue kann geschlossen werden.

**Comment by kdr154** [comment]
Ok
