### ISSUE TITLE
ISSN 0966-7350 Feminist Theology Translatorauswahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#372]
https://journals.sagepub.com/toc/fth/current
Bei dieser ZS nimmt die Zotero-Browsererweiterung den Translator Liverpool University Press Online statt Sage Journals. Das führt zu dem Fehler, dass an das Ende des Titels ein Doppelpunkt gesetzt wird, den man entfernen muss. Bei dem Translator Sage Journals ist dies nicht der Fall. Man kann den richtigen Translator manuell auswählen, aber: kann man die nicht so anpassen, dass automatisch der richtige genommen wird?
Ähnliches und gleiches Problem wie bei #369

**Comment by shadeMe** [comment]
Das ist nochmal das übliche Problem wie [hier](https://github.com/ubtue/DatenProbleme/issues/245#issuecomment-512247702).

**Comment by kdr154** [comment]
Was wollen wir hier machen? Weiter abwarten oder schließen?

**Comment by kdr154** [comment]
Der Sage-Translator wird jetzt erkannt und auch genommen. Allerdings fehlen die Keywords.
Beispielsweise hier: https://journals.sagepub.com/doi/full/10.1177/0966735019857196

**Comment by shadeMe** [comment]
Doch. Geht es, wenn die Seite über Strg+Shift+R aktualisiert/neu geladen wird?

![Screenshot_20191017_112444](https://user-images.githubusercontent.com/214450/66996269-bad69680-f0d0-11e9-9921-817cbcd8849d.png)

**Comment by kdr154** [comment]
Jetzt sind sie dabei. Schließe
