### ISSUE TITLE
ISSN 2305-445X Scriptura 773$g und 936$e (Heftzählung)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#375]
Der Band von 2019 118 (2019) hat in der Vorlage (Webseite) keine Heftzählung, in 773$g und 936$e steht aber eine "1". Mein Eindruck ist, dies wird automatisch so generiert? 
Leider ist die Vorlage sehr uneinheitlich. Es gibt Jahre, in denen nur ein Band erscheint. Z. B. 2013, 2014, 2015, 2016.
Dann gibt es Jahre, in denen mehrere Bände erscheinen und die Bände fortlaufend weiter gezählt werden, aber nicht zwischen Heften unterschieden wird: Vol 109 (2012), Vol 110 (2012), Vol 111 (2012).
Dann gibt es Jahre, in denen mehrere Hefte (!) von einem Band erscheinen, die dann auch gezählt werden: Vol 116, NO 1 (2017), Vol 116, NO 2 (2017)

**Comment by shadeMe** [comment]
Der Translator nimmt nur die Metadaten auf, die auf jeweiliger Webseite stehen, egal ob sie richtig oder falsch sind. Solche Fehler müssen leider händisch korrigiert werden.

**Comment by kdr154** [comment]
Dann schließe ich
