### ISSUE TITLE
ISSN 2305-445X Scriptura Sprache (Tag 041)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#376]
Die Sprache wird z. T. nicht richtig erkannt:
http://scriptura.journals.ac.za/pub/article/view/1387
ist in Afrikaans (afr) verfasst, in 041 steht aber eng

**Comment by kdr154** [comment]
Umgestellt auf RSS
Stimmt aber weiterhin nicht
http://scriptura.journals.ac.za/pub/article/view/1387
ist afr in 041 steht aber eng

**Comment by mtrojan-ub** [comment]
In Absprache mit @shadeMe wurden mehrere Konfigurationen getestet. Selbst wenn wir die automatische Spracherkennung erzwingen und auf das Titelfeld beschränken, erhalten wir kein zuverlässiges Ergebnis. Die Sprache muss in diesem Fall wohl leider von Hand korrigiert werden.

**Comment by kdr154** [comment]
Ich gehe dann davon aus, dass die automatische Spracherkennung in anderen Fällen funktioniert.
