### ISSUE TITLE
ISSN 2305-445X Scriptura Abstract (Tag 520)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#377]
Da wo der Text in einer von dem Englischen abweichenden Sprache verfasst worden ist, ist das Abstract in beiden Sprachen vorhanden, sie werden aber unter einem Tag 520 abgespeichert.
Z. B. hier: http://scriptura.journals.ac.za/pub/article/view/1387

**Comment by shadeMe** [comment]
Da die beiden Zusammenfassungen als ein einzelner Text im Markup vorkommen, können wir es leider nicht (zuversichtlich) erkennen, wann eine endet und die andere beginnt. Von daher müssen sie händisch korrigiert werden.

**Comment by kdr154** [comment]
Dann müssen wir das Issue schließen
