### ISSUE TITLE
PDCnet ISSN 2159-6808 Journal of Religion and Violence PDCnet allgemein

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#38]
Die Zeitschriften, die auf PDCnet gehostet werden, müssen in meinen Augen leider zurückgestellt werden. Sie gehören zu den kompliziertesten, die mit Zotero bearbeitet werden. Entsprechend sind die Metadaten.
Der Titel der Aufsätze, Tag 245, lautet immer "Philosophy Documentation Center". Auch alle weiteren bibliographische Daten wie Verfasser, Band, Seitenzahl, Jahr, Titel des übergeordneten Werks fehlen. In 835 ist zwar der Link zum Volltext abgelegt, doch das ist wenig hilfreich angesichts der Defizite. Und ich befürchte, das sieht bei den anderen Zeitschriften auf dieser Plattform nicht anders aus.

**Comment by shadeMe** [comment]
Das Problem mit der Webseite ist wie bei #52 - die Dateien werden über _lazy loading_ geliefert. Von daher ist sie eher fürs semi-automatische Verfahren geeignet. Auf jeden Fall habe ich einen neuen Translator für PDCnet in dem Pullrequest angelegt.

**Comment by mtrojan-ub** [comment]
Der neue Translator ist jetzt drin, bitte ausprobieren.

**Comment by kdr154** [comment]
Nein, das klappt noch nicht. Weiterhin website. Die Daten sehen genauso aus wie beim ersten Versuch

**Comment by mtrojan-ub** [comment]
@shadeMe : bitte nochmal prüfen. Habe den "ubtue_Philosophy Documentation Center.js" Translator installiert, aber im Browser greift er nicht, z.B. bei dieser Seite:
https://www.pdcnet.org/collection/show?id=jrv_2018_0006_0001_0001_0010&file_type=pdf

**Comment by shadeMe** [comment]
![screenshot_20181108_120958](https://user-images.githubusercontent.com/214450/48195195-3e2f2a00-e34f-11e8-86a9-c2542d20d7a8.png)

Auf meinem Rechner sieht der Datensatz gut aus. Ich glaube, das Problem an der Browser- oder Zotero-cache liegt - Manchmal werden Änderungen nicht eingespielt. Normalerweise löst es sich von selbst, wenn ich Zotero und meinem Browser (in der Reinfolge) neustarte. Allerdings habe ich bemerkt, Chrome hat mehr Probleme damit als Firefox.

**Comment by mtrojan-ub** [comment]
... der Translator funktioniert jetzt manuell, aber mit dem Zotero Translation Server kämpfen wir noch :sweat_smile:

**Comment by mtrojan-ub** [comment]
Im Server ist es das selbe Problem wie bei #54, weil es sich um eine spezielle Art der Weiterleitung handelt. Wir warten noch auf eine Aussage von Zotero, wie wir am besten damit umgehen sollen.

```
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <meta property="og:url" content="https://www.pdcnet.org/pdc/bvdb.nsf/purchase?openform&amp;fp=jrv&amp;id=jrv_2018_0006_0001_0032_0051">
    <meta property="og:type" content="website">
    <meta property="og:locale" content="en_US">
    <meta property="og:title" content=" - Philosophy Documentation Center ">
    <meta property="og:description" content="">
    <meta property="og:site_name" content="pdcnet.org">
    <meta property="og:image" content="https://www.pdcnet.org/collection-anonymous/pdf2image?pdfname=jrv_2018_0006_0001_0032_0051.pdf&amp;file_type=png">
    <meta property="og:updated_time" content="2018-11-20T07:56:19+00:00">

        <title> - Philosophy Documentation Center </title>

        <link rel="shortcut icon" href="images/favicon.ico" type="image/vnd.microsoft.icon">
        <link rel="icon" href="images/favicon.ico" type="image/vnd.microsoft.icon">
        <link rel="stylesheet" href="css/base.css" type="text/css" media="screen, projection">

<script language="JavaScript">
                var NTPT_PGEXTRA='Access_Method=Regular&Access_Type=Controlled&Event_Type=No_License&Event_Detail=PDF_Redirect&Section_Type=Article&Data_Type=Journal&Item_Data_Type=Article&Date/Time=2018-11-20 07:56:19&IP_Address=134.2.66.55&User_Agent=ub_tools/zotero (see https://ixtheo.de/crawler)&Site_ID=individual&Site_Name=anonymous&Title=Journal of Religion and Violence&Item_Title=The Rhetoric of Violence in the Buddhist Tantras&Publisher=Philosophy Documentation Center&URI=https%3A%2F%2Fwww.pdcnet.org%2Fcollection%2Fshow%3Fid%3Djrv_2018_0006_0001_0032_0051%26file_type%3Dpdf&YOP=2018&Authors=David B. Gray&DOI=10.5840/jrv20185149&ISBN=&Print_ISSN=2159-6808&Online_ISSN=';
        </script>

        <!-- BEGIN: Scholarly iQ Page Tag -->
        <script language="JavaScript" src="//pdctag.scholarlyiq.com/siqpagetag.js"></script>
        <noscript>
        <img src="//pdctag.scholarlyiq.com/siqpagetag.gif?js=0" height="1" width="1" border="0" hspace="0" vspace="0" alt="">
        </noscript>
        <!-- END: Scholarly iQ Page Tag -->
</head>

<body></body>
```

**Comment by mtrojan-ub** [comment]
Wir konnten das Umleitungsproblem in diesem Fall (PDCnet) über den Translator lösen. Bitte nochmal ausprobieren!

**Comment by kdr154** [comment]
Sehr gut! Gelöst
