### ISSUE TITLE
ISSN  2295-6093 Augustiniana Exitcode 1

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#381]
**URL**
Die Harvest URL

**Ausführliche Problembeschreibung**
Was ist das Problem?

**Offenbare Lösungen**
Wie kann man das Problem lösen?

**Comment by kdr154** [comment]
Wurde auf RSS ungestellt, Harvesting wird aber auch hier abgebrochen. Nach 2 Sekunden mit Unexpected errors were encountered during the harvesting process

**Comment by shadeMe** [comment]
Harvesting funktioniert jetzt wieder. Bitte nochmal testen.

**Comment by kdr154** [comment]
Der elementare Fehler besteht aber weiter:
http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_wXfIfw/ixtheo/LxHs68.xml
Zuerst den beheben, dann kann weiter getestet werden

**Comment by kdr154** [comment]
Läuft wieder
