### ISSUE TITLE
ISSN 0101-3130 Estudos teológicos Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#383]
http://periodicos.est.edu.br/index.php/estudos_teologicos/issue/archive
Rezensionen werden nicht als solche getagt:

```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

Sie stehen in der Sektion "Resenhas"

**Comment by shadeMe** [comment]
Vgl #446.

**Comment by kdr154** [comment]
Dieselbe ZS wie in #446. Schließe dieses Issue
