### ISSUE TITLE
ISSN 2295-5186 Theoforum Exitcode 1

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#384]
Peeters hat uns wohl auch gesperrt.

**Comment by kdr154** [comment]
Umgestellt auf RSS. Der Harvester steigt nicht mehr aus. Jetzt werden aber alte Daten abgegriffen 45.2014,2 und die Daten sind unvollständig und sie weisen jede Menge überflüssiger Einträge auf, in denen im Titel lediglich "Peeters online journals" steht. Darüber hinaus auch Probleme bei 041 (Sprache)

**Comment by shadeMe** [comment]
Ja, der RSS Feed schient ganz veraltet zu sein. Gibt es einen anderen RSS Link für diese Zeitschrift?

**Comment by kdr154** [comment]
Sieht nicht so aus
