### ISSUE TITLE
ISSN  2295-6093 Augustiniana RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#388]
https://poj.peeters-leuven.be/RSS/AUG.xml

**Comment by kdr154** [comment]
Umgestellt auf RSS
Keine aktuellen Daten, 67.2017,3-4 hier.

**Comment by shadeMe** [comment]
Jetzt scheint es Artikel vom März 2018 zu geben.

**Comment by kdr154** [comment]
Der Harvester liefert aber weiterhin nur 67.2017,3-4

**Comment by shadeMe** [comment]
Ja, das Datum im Feed verweißt auf 2018, obwohl die Artikel aus 2018 sind. Es kann wohl sein, dass dieser RSS-Feed veraltet ist und nicht mehr aktualisiert wird.

**Comment by kdr154** [comment]
Das liegt dann nicht in unserer Hand. Ich schließe
