### ISSUE TITLE
ISSN 2386-7442 Collectanea Christiana orientalia RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#389]
https://www.uco.es/revistas/index.php/cco/notification/notificationFeed/rss2/262216512549ae2662c6e2

**Comment by kdr154** [comment]
Umgestellt auf RSS ok.
Jetzt werden aber die Rezensionen nicht erfasst. Zudem ein Artikel zum Schluss, der keinem Band zugeordnet ist.
Auffällig ist darüber hinaus, dass seit dem Firefox Update die RSS Feeds nicht mehr im Browser angezeigt werden, sondern als unbrauchbare lokale XML-Datei

**Comment by shadeMe** [comment]
Die Rezensionen haben anscheinend keine Seiten (https://www.uco.es/revistas/index.php/cco/issue/view/67). Da können wir gar nicht anfangen. Bei den anderen Artikeln gibt es keine Band Angabe.

**Comment by kdr154** [comment]
Jetzt ist die XML-Datei leer. Wir haben bereits mindestens ein weiteres Issue #351 zu dieser ZS geschlossen, wo wir das Problem nicht lösen konnten. Deshalb ist diese ZS in meinen Augen ebenfalls nicht für das vollautomatische Verfahren geeignet.
