### ISSUE TITLE
Springer ISSN 1572-8447 Ethical theory and moral practice

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#39]
Alle Artikel in diesem Feed sind Online First Article, die noch keinem Heft zugewiesen sind und folglich noch nicht katalogisiert werden können.

**Comment by mtrojan-ub** [comment]
Gibt's da ein ToDo für uns?

**Comment by kdr154** [comment]
Müssen wir erst noch in einer DB hier bei uns besprechen.

**Comment by shadeMe** [comment]
Vgl. #100.

**Comment by kdr154** [comment]
Auf first online wollten wir erst mal verzichten. Diese Artikel bitte übergehen

**Comment by kdr154** [comment]
Fehler bei der Verarbeitung. XML-Datei enthält keine Daten

**Comment by shadeMe** [comment]
Laut des Inhalt des Log-Dateis wurden alle Artikel, die gerade im RSS-Feed aufgelistet sind, übersprungen, weil sie Online-First Artikel sind. Angesichts deines letzten Kommentares habe ich gedacht, dass wir's zurzeit so machen wollten. Oder habe ich dich missverstanden?

**Comment by kdr154** [comment]
Das ist richtig. Dann passt es ja so.
