### ISSUE TITLE
ISSN 0024-7324 Lumen Vitae RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#391]
https://poj.peeters-leuven.be/RSS/LV.xml

**Comment by kdr154** [comment]
Umgestellt auf RSS, aber:
Result file kann nicht geprüft werden, da Firefox einen Fehler meldet:
http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_gcT94G/ixtheo/hcczmr.xml

**Comment by shadeMe** [comment]
Der Fehler wurde behoben. Bitte nochmal testen.

**Comment by kdr154** [comment]
Es ist zwar ein etwas älteres Heft, das gescannt wurde, die Daten sehen aber gut aus.
