### ISSUE TITLE
Vandenhoeck ISSN 2196-7954 Jews and Drama Tag 100/700

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#40]
Beide Verfasser landen im Marc21-Tag 700, statt einer in 100 der andere in 700. 
Zudem ist die Reihenfolge gegenüber der Webseite vertauscht
https://www.vr-elibrary.de/doi/abs/10.13109/jaju.2017.8.2.146#.W9c3f8QxlaQ

**Comment by mtrojan-ub** [comment]
Diese Vorgehensweise wurde bei einem Meeting so festgelegt.
Wenn wir exakt einen Author haben, so liefern wir ihn in 100.
Wenn wir mehr als einen Author haben, so liefern wir alle gleichberechtigt in 700. 

Das mit der Reihenfolge werde ich aber gerne noch prüfen.

**Comment by mtrojan-ub** [comment]
ist gefixt, bitte testen

**Comment by kdr154** [comment]
Ich will das mal so stehen lassen. Frau Kellmeyer ist sich nicht 100% sicher, ob es so gemeint war, wie Sie schreiben. Aber wir machen dass jetzt so und wenn von höherer Stelle Einwände kommen, müssen wir da eben noch mal ran. Das mit der Reihenfolge stimmt jetzt. Schließe den Issue als gelöst.
