### ISSUE TITLE
Skrif en Kerk (ISSN 0257-8891) und ISSN 2074-7705 Verbum et Ecclesia RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#403]
https://verbumetecclesia.org.za/index.php/ve/gateway/plugin/WebFeedGatewayPlugin/atom
Skrif en Kerk ist auch so eine disNach Geschichte. Die Zeitschrift ist in Verbum et Ecclesia aufgegangen (andere ISSN) und die Artikel finden sich alle auf der Homepage von Verbum et Ecclesia
Vorgänger hat eine andere PPN (170545032). Muss bei Retrokatalogisierung berücksichtigt werden. Ebenso die physische Form (O/A-Aufnahme). Zumindest muss das geklärt werden, was unter Umständen eine neue Gesamtaufnahme nötig macht.

**Comment by shadeMe** [comment]
Was soll ich dabei tun? Einfach den Link austauschen?

**Comment by kdr154** [comment]
Ja. Für alle zukünftigen Aufsätze ist das unproblematisch. Sollten wir einmal Retrokatalogisieren ist es komplizierter. Auch hier gilt dieser Link. Für die Aufsätze vor 21 (2000) greift aber die oben beschriebene Problematik.

**Comment by kdr154** [comment]
Ich würde Skrif en Kerk (ISSN 0257-8891) aus nu herausnehmen und für das halbautomatische Verfahren vorsehen und Verbum et Ecclesia (2074-7705) auf nu belasen.

**Comment by kdr154** [comment]
Result file kann nicht geprüftr werde, da ich bei dessen Aufruf lediglich eine Fehlermeldung erhalte:
http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_fdKqv0/ixtheo/dNPHou.xml

**Comment by shadeMe** [comment]
Ich hab auch die Fehlermeldung ein paar Male gekriegt aber danach hat es wohl gut funktioniert - http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_q8HHFa/ixtheo/pWh6Th.xml

**Comment by kdr154** [comment]
Skrif en Kerk wurde herausgenommen

**Comment by kdr154** [comment]
Verbum et Ecclesia wird jetzt geharvestet. Es werden aber leider nur 10 Artikel von über 20 in Band 40.2019,2 erfasst.

**Comment by shadeMe** [comment]
Leider verfügt der RSS-Feed nur über die zehn Artikel. Da können wir von unserer Seite nicht weitermachen.

**Comment by kdr154** [comment]
Dann wir hier auch geschlossen
