### ISSUE TITLE
ISSN 1095-9270 The International Journal of Nautical Archaeology RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#405]
Kann bei dieser ZS keinen Bezug zur Theologie, Relwi oder Kriminologie erkennen. Schlage vor, diese ZS herauszunehmen und zurückzustellen.
https://onlinelibrary.wiley.com/action/showFeed?jc=10959270&type=etoc&feed=rss

**Comment by kdr154** [comment]
Auf nu entfernt

**Comment by kdr154** [comment]
Bitte wieder in nu für den Test bereitstellen

**Comment by kdr154** [comment]
Doch nicht

**Comment by kdr154** [comment]
Abschließend soll die Zeitschrift doch ausgewertet werden. Deshalb die Bitte, sie auf nu wieder für den Testbetrieb bereitstellen.

**Comment by shadeMe** [comment]
Vgl. #465.

**Comment by kdr154** [comment]
Läuft wieder
