### ISSUE TITLE
Vandenhoeck ISSN 2196-7954 Jews and Drama 773 $g + $p

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#41]
773 $g falsch und unvollständig
Vgl. #32 und #46

**Comment by kdr154** [comment]
Ich frage mich, woher das $p in 773 kommt. Ich finde es in dieser Form in keiner Dokumentation als ein Marc21-Tag. Vermute aber, dass hier die Zeitschriften-Abkürzung abgegriffen wird, die in Zotero in diesem Fall aufgeführt wird. Das die Zeitschriften-Abkürzung übertragen wird, ist aber die Ausnahme. Und sollte es so sein, kann man in meinen Augen auf $p in 773 verzichten. Wenn es nicht in irgendeiner Form umgesetzt wird, kann es stehen bleiben, sonst müsste es raus. Das müsste uns aber das BSZ beantworten.
Sonst sieht 773 korrekt aus und 936 auch.
Frau Katz vom BSZ hat bereits geantwortet und bittet darum $p in 773 ganz wegzulassen und gar nicht mit zu liefern

**Comment by mtrojan-ub** [comment]
Habe 773p entfernt, bitte nochmal testen.

**Comment by kdr154** [comment]
Gelöst
