### ISSUE TITLE
ISSN 1743-1654 Journal of Adult Theological Education Erscheinen eingestellt und RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#414]
Mit 13,2016,2 Erscheinen eingestellt. Aufgegangen in:
Practical Theology, ISSN 1756-0748, PPN 585507937
=Zeder ID 854. Für diese ZS ist RSS bereits aktiviert, aber kein Crawlen. 
https://www.tandfonline.com/feed/rss/yprt20
Wobei im Augenblick der Tenor der ist, dass wir in diesem Fall das RSS Verfahren nehmen.
Dort sind auch alle Ausgaben einschließlich der des Vorgängers Journal of Adult Theological Education gelistet.
ISSN und Titel austauschen. Für Retrokatalogisierung müssen wir uns später kurzschließen

**Comment by shadeMe** [comment]
Kann ich diesen Eintrag einfach vom Harvester-Config löschen? Dann bleibt nur "Practical theology".

**Comment by kdr154** [comment]
Bitte löschen
