### ISSUE TITLE
ISSN 0967-8948 Diskus disNach

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#416]
disNach
aktuell ist ISSN 0967-8948 Journal of the British Association for the Study of Religions
Dafür ist RSS bereits aktiviert

**Comment by shadeMe** [comment]
Worum geht das Problem hier?

**Comment by kdr154** [comment]
Diesen Eintrag aus dem Harvester entfernen

**Comment by kdr154** [comment]
entfernt
