### ISSUE TITLE
ISSN 2011-9771 Revista Albertus Magnus RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#418]
https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4

**Comment by kdr154** [comment]
RSS steht jetzt zur Verfügung, allerdings bricht der Harvester nach 3 Sekunden mit folgendem Output ab:
Processing section "Revista Albertus Magnus".
feed_url: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4


Processing feed URL: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4 (RSS 2.0):
	Title: Revistas Universidad Santo Tomás - Colombia Notificaciones
	Link: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
	Description: 
Extracted metadata from 0 page(s).

**Comment by kdr154** [comment]
Erneut Abbruch nach 3 Sekunden mir folgendem Code:

Processing section "Revista Albertus Magnus".
feed_url: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4


Processing feed URL: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4 (RSS 2.0):
	Title: Revistas Universidad Santo Tomás - Colombia Notificaciones
	Link: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
	Description: 
Extracted metadata from 0 page(s).

**Comment by mtrojan-ub** [comment]
Eben nochmal getestet, es wurde erfolgreich eine XML-Datei mit 10 Einträgen generiert.
(habe auch das Issue-Label geändert, es war noch Crawl statt RSS gesetzt).

**Comment by kdr154** [comment]
Dann passt es ja. 
Mein Test war ebenfalls erfolgreich
