### ISSUE TITLE
ISSN 0776-3824 Kernos RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#419]
https://journals.openedition.org/kernos/backend?format=rssnumeros

**Comment by mtrojan-ub** [comment]
Habe eben nochmal getestet:
- 084 ist mittlerweile gesetzt
- 935 mteo ebenfalls
- 856 Kostenfrei => das fehlt immer noch. Das liegt aber vermutlich daran, dass es für die ISSN keine passenden Eintrag in der ISSN_to_licence.map gibt.
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map

**Comment by mtrojan-ub** [comment]
Die Map-Änderung wurde über Nacht per cronjob heruntergeladen, jetzt taucht auch 856z Kostenfrei auf.

**Comment by kdr154** [comment]
Leider bricht bei mir jetzt der Harvester wieder ab. Auf jeden Fall bekomme ich als Result file lediglich eine leere gelbe Seite.

**Comment by mtrojan-ub** [comment]
Das scheint wohl ein serverseitiges Problem zu sein.

http://journals.openedition.org/kernos/2474
![grafik](https://user-images.githubusercontent.com/26873381/75136909-6b3f5180-56e6-11ea-9e1f-e0c61543760b.png)

**Comment by kdr154** [comment]
XML-Datei vorhanden
