### ISSUE TITLE
ISSN 1469-9737 Mental health, religion and culture

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#420]
https://www.tandfonline.com/feed/rss/cmhr20

**Comment by kdr154** [comment]
RSS vorhanden
Auch hier fehlt 084 mit der SSG-Nummer (0) und mteo in 935

**Comment by mtrojan-ub** [comment]
SSG 0 und mteo sind mittlerweile vorhanden.

**Comment by kdr154** [comment]
Stimmt, schließe
