### ISSUE TITLE
ISSN 2520-4696 European Journal of Philosophy, Culture and Religion RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#421]
https://ajpojournals.org/journals/index.php/EJPCR/gateway/plugin/WebFeedGatewayPlugin/rss2

**Comment by kdr154** [comment]
Umgestellt auf RSS
es fehlt die SSG-Nummer (0) in 084, der subfield code "z">Kostenfrei<, der Code für Sammlungen kann noch nicht definiert werden, da Prio1

**Comment by mtrojan-ub** [comment]
084 ist jetzt vorhanden, für "Kostenfrei" fehlt wohl ebenfalls der Eintrag in der ISSN_to_licence.map

**Comment by kdr154** [comment]
Mappingtabelle ergänzt

**Comment by mtrojan-ub** [comment]
856z Kostenfrei ist nun ebenfalls vorhanden

**Comment by kdr154** [comment]
Stimmt
