### ISSUE TITLE
ISSN 2602-2435 Dini Araştırmalar RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#423]
http://dergipark.ulakbim.gov.tr/da/notification/notificationFeed/rss2/1689151261554db3060b035

**Comment by kdr154** [comment]
Ein Harvester über RSS wird nach 4 Sekunden abgebrochen:

Processing section "Dinî araştırmalar : dört aylık bilimsel dergi".
feed_url: http://dergipark.ulakbim.gov.tr/da/notification/notificationFeed/rss2/1689151261554db3060b035


Processing feed URL: http://dergipark.ulakbim.gov.tr/da/notification/notificationFeed/rss2/1689151261554db3060b035
[ERROR-UNKNOWN] for 'http://dergipark.ulakbim.gov.tr/da/notification/notificationFeed/rss2/1689151261554db3060b035': Download problem for "http://dergipark.ulakbim.gov.tr/da/notification/notificationFeed/rss2/1689151261554db3060b035": Couldn't connect to server
Extracted metadata from 0 page(s).
Unexpected errors were encountered during the harvesting process

**Comment by mtrojan-ub** [comment]
Ich kann den Feed auch nicht im Browser öffnen (Verbindung fehlgeschlagen). Ist die URL noch aktuell?

**Comment by kdr154** [comment]
Nein, habe in Zeder rss und url geändert

**Comment by mtrojan-ub** [comment]
Jetzt läuft das Harvesting durch..

Die Artikel scheinen gemischt Türkisch / Englisch zu sein, ich habe die Einstellung für die Spracherkennung entsprechend angepasst.

**Comment by kdr154** [comment]
Sieht gut aus, allerdings sollten in 041 die Kürzel tur und eng stehen.

**Comment by mtrojan-ub** [comment]
Das sollte jetzt passen.

Wir versuchen jetzt auch ohne spezielle Konfiguration für eine Zeitschrift die 2-4 stelligen Sprachcodes aus dem Translator auf einen gültigen englischen 3-stelligen Sprachcode fürs BSZ zu mappen. Das kann sich also auch positiv für andere Zeitschriften mit diesem Problem auswirken.

**Comment by kdr154** [comment]
Findet man hier https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by kdr154** [comment]
Passt.
