### ISSUE TITLE
ISSN 0101-3130 Estudos teológicos Exitcode 1 und leere XML-Datei

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#424]
Estudos teológicos bricht einen ersten Testversuch mit Exitcode 1ab, bei einen 2. wird nach 3 Sekunden einen leere XML-Datei geliefert.

**Comment by shadeMe** [comment]
Es sieht so aus, als wäre wir vom Server blockiert werden. Gibt es einen RSS-Feed für diese Zeitschrift?

**Comment by shadeMe** [comment]
@kdr154 Nochmal zur Erinnerung.

**Comment by kdr154** [comment]
Aus anderen Gründen wird auf das automatische Verfahren verzichtet
