### ISSUE TITLE
ISSN 0024-7324 Lumen vitae Tag 007

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#425]
Tag 007 hat den Wert "tu" statt "cr|||||"

**Comment by shadeMe** [comment]
Diese Zeitschrift braucht eine Online-ISSN, die weder im Zeder noch im ISSN-Poral nicht zu finden ist.

**Comment by shadeMe** [comment]
@kdr154

**Comment by kdr154** [comment]
Es gibt aber keine. Dann schließen?

**Comment by thefass** [comment]
Kann man die Print-ISSN in das Feld eissn übernehmen?

**Comment by kdr154** [comment]
Das kann man machen, wenn es formal gesehen auch nicht ganz korrekt ist. In der WinIBW steht diese aber in der Gesamtaufnahme der Onlineausgabe in Pica 2013, bei der Druckausgabe in 2010. Wenn das nicht zu Problemen führt, ist das eine Möglichkeit. Dann, wenn die Verknüpfung zur richtigen Gesamtausgabe über die PPN hergestellt wird. In 773 $w steht aber in den getesteten Daten die PPN der Druckausgabe. ...

**Comment by kdr154** [comment]
Können wir mal so versuchen. Die ISSN taucht ja bei den Aufsätzen nicht auf, sondern nur in der Gesamtaufnahme. Ich habe die 0024-7324 ins Zeder-Feld essn eingetragen

**Comment by kdr154** [comment]
Sieht gut aus. Die Aufsätze werden mit der Online-Ausgabe verknüpft.
Allerdings fehlt auch hier wieder die SSG-Nummer in 084 (1) und der Code für die Sammlung in 935 (mteo). In diesem Fall ist kat in Zeder mit IxTheo belegt.

**Comment by mtrojan-ub** [comment]
Momentan lässt sich der Feed gar nicht mehr Harvesten.

Die Erkennung des RSS-Formats scheitert daran dass es sich um einen RSS Feed handelt der nicht in UTF-8 vorliegt. Wir werden voraussichtlich morgen einen Fix einspielen und dann testen ob es noch weitere Probleme gibt.

**Comment by mtrojan-ub** [comment]
Der Feed kann jetzt wieder geharvested werden, 084 (1) und 935 (mteo) sind ebenfalls vorhanden.

**Comment by kdr154** [comment]
Sieht so aus als ob jetzt alles stimmt.
