### ISSUE TITLE
ISSN 2312-878X Missionalia Titel (Tag 245) 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#426]
Bei einem Aufsatz fällt mir auf, dass der Titel nicht richtig erfasst wird. Bei diesem Aufsatz:
http://missionalia.journals.ac.za/pub/article/view/48
wird der Titel so erfasst:
```
<datafield tag="245" ind1="0" ind2="0">
<subfield code="a">| Wrogemann</subfield>
</datafield>
```

**Comment by kdr154** [comment]
Lässt sich schwer abschließend beurteilen, da dieses man ein völlig anderes Heft geharvestet wurde. Aber ich sehe keine überflüssigen Zeichen mehr

**Comment by kdr154** [comment]
Muss die Sache mit der SSG-Nummer, dem Code für Sammlungen und der Angabe kostenfrei bei jeder Zeitschrift extra eingerichtet werden? Denn hier fehlen die Angaben auch wieder.

**Comment by mtrojan-ub** [comment]
Wollte es eben testen aber der RSS-Feed ist scheinbar nur eine leere Datei?
http://missionalia.journals.ac.za/pub/gateway/plugin/WebFeedGatewayPlugin/rss2

**Comment by kdr154** [comment]
Stimmt. Bei mit gibt keines der drei angebotenen Formate, RSS2, RSS und Atom etwas zurück. Auf Scielo wird nichts angeboten. In diesem Fall wird man die ZS entfernen, oder abwarten müssen, ob sich was ändert.

**Comment by socheres** [comment]
@kdr154 wie ist der aktuelle Stand bei diesem Issue? Können Sie bitte nochmal testen und die Probleme zusammenfassen?

**Comment by kdr154** [comment]
Der Fehler tritt in der Form nicht mehr auf. Ich glaube hier können wir schließen.
