### ISSUE TITLE
ISSN 1188-7109 Théologiques tag 084 und 935

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#429]
Tag 007 hat den Wert "tu" statt "cr|||||"

**Comment by kdr154** [comment]
Tag 007 ist gelöst, aber 084 (SSG) und 935 (Code für Sammlungen) fehlen

**Comment by mtrojan-ub** [comment]
Laut #387 ist diese Zeitschrift nicht mehr Bestandteil der Harvesterliste, daher schließe ich den Issue.
