### ISSUE TITLE
ISSN 2294-6209 Byzantion Sprache (041) deutsch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#432]
Deutsch wird nicht immer erkannt. Hier fre statt ger:
https://poj.peeters-leuven.be/content.php?url=article&id=3117809&journal_code=BYZ
Hier ist es richtig:
https://poj.peeters-leuven.be/content.php?url=article.php&id=3117811&journal_code=BYZ

**Comment by kdr154** [comment]
Weiterhin so

**Comment by socheres** [comment]
Sprache wurden bei allen 19 Aufsätzen richtig erkannt. Bitte nochmal testen und den Issue schließen.

> Zotero Harvester Metrics:
	Journals: 1
		Direct: 0
		RSS: 1
			Skipped: 0
		Crawl: 0
	Crawls: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 19
		Successful: 19
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 19
		Successful: 19
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 0
		Skipped (already delivered): 0

	Successfully generated records per group:
		IxTheo: 19

**Comment by kdr154** [comment]
Hier
IxTheo#2020-04-06#5FD551A43F4DE20341429690128FBBD7217BF3E5
steht fälschlicherweise fre in 041 statt de

![grafik](https://user-images.githubusercontent.com/29707105/78557438-162c4a80-7811-11ea-89e6-9135d3db9f8c.png)

**Comment by kdr154** [comment]
Nicht zu lösen. Siehe #849
