### ISSUE TITLE
ISSN 1468-2303 History and Theory Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#433]
Rezensionen werden nicht erkannt. (Tag 655)
Sie stehen in dem getesten Feed (Ausgabe 58.2019,2) in der Sektion Review Essays.
In anderen Ausgaben gibt es auch die Sektion Review Article und Books in Summary

**Comment by kdr154** [comment]
In der jetzt getesteten Ausgabe stehen sie in der Sektion Review Essays. Sie werden weiterhin nicht als solche getagt.

**Comment by socheres** [comment]
Auf Nu ist die ISSN 1468-2303 nicht mehr vorhanden

**Comment by kdr154** [comment]
Haben wir rausgenommen, da die Auswertung laut Zeder selektiv erfolgen soll. Vgl. #485
