### ISSUE TITLE
ISSN 1862-5886 Zeitschrift für junge Religionswissenschaft Tag 773g

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#435]
Es wird kein 773 g generiert

**Comment by shadeMe** [comment]
Das ist wegen der fehlenden Band-Angabe in den Metadataen.

**Comment by shadeMe** [comment]
Wir können dieses Issue schließen, denke ich. Von unserer Seite können wir nichts machen.

**Comment by kdr154** [comment]
Aber vielleicht den Translator, hier nimmt die Erweiterung Embedded Metadata, für das halbautomatische Verfahren anpassen. 
Die Bandangabe sollte ins Zoterofeld Band. Sie befindet sich jetzt im Feld Ausgabe
Das Abstract sollte unterdrückt werden. Hier wird der Anfang des Volltextes ins Feld Zusammenfassung geschrieben

**Comment by shadeMe** [comment]
Hmm, tatsächlich soll der "OpenEdition Journals" Translator für diese Zeitschrift benutzt werden - Er nimmt die Band/Ausgabe Felder richtig auf. Die Problematik mit der Zusammenfassung wird demnächst gehoben (aber nur beim vollautomatischen Verfahren).

**Comment by kdr154** [comment]
Der OJS Translator ist für die Browsererweiterung in diesem Fall noch immer keine Option

**Comment by kdr154** [comment]
Seitenangaben finden sich nur im PDF-Dokument. Diese stimmen zudem nicht mit dem Umfang des Dokuments überein.
