### ISSUE TITLE
ISSN 1862-5886 Zeitschrift für junge Religionswissenschaft Seitenangabe Tag 936 h

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#436]
Keine Seitenangabe auf den Webseiten. Nur im PDF. Deshalb kein 936 h
Muss man wohl so stehen lassen. Ebenso wie 773 g?

**Comment by shadeMe** [comment]
Was schient hier das Problem zu sein? Ich sehe weder 936$h noch 773$g in dem MARC-XML Datei.

**Comment by shadeMe** [comment]
@kdr154

**Comment by kdr154** [comment]
Ungeeignet für vollautomatisches Verfahren, Verbesserung für das halbautomatische Verfahren angestrebt. Siehe #435
