### ISSUE TITLE
ISSN 1862-5886 Zeitschrift für junge Religionswissenschaft Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#438]
In Heft 12.2017 und davor gibt es Rezensionen. Der Testlauf deckt aber nur die beiden neuesten Ausgaben ab, in denen keine enthalten sind.
Kann man den Testlauf auf weitere Hefte ausdehnen, um dies zu testen?

**Comment by shadeMe** [comment]
Gerade nicht aber ich habe ein Muster (im Titel steht "XXX Seiten") aufgedeckt, mit dem Rezensionen erkannt werden können. Ich passen entsprechend den Translator an und setze dieses Issue derzeit auf "blocked".

**Comment by socheres** [comment]
> ein Muster (im Titel steht "XXX Seiten") 

ist umgesetzt

**Comment by kdr154** [comment]
In den Testdaten sind keine Rezensionen. Abwarten oder Schließen?

**Comment by kdr154** [comment]
In der Einspielung in die Testdatenbank (4.5.2020) erkannt.
