### ISSUE TITLE
ISSN 2305-0853 In die Skriflig Fehlende Artikel?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#441]
Es wird nur eine (kleine) Auswahl der Artikel in der einzelnen Heften erfasst.
Jahrgang 2019, Band 53 Heft 1: 3 von 30
Jahrgang 2019, Band 53 Heft 2: 1 von 1 Sonderfall, das Heft besteht nur aus diesem einen Artikel
Jahrgang 2019, Band 53 Heft 3: 3 von 8
Jahrgang 2019, Band 53 Heft 4: 3 von 7

**Comment by shadeMe** [comment]
Der RSS-Feed hat derzeit 10 Einträge und nur die werden vom Harvester erfasst.

**Comment by shadeMe** [comment]
@kdr154

**Comment by kdr154** [comment]
Die Auswahl dessen, was erfasst wird, bleibt dunkel. Bei dem gerade durchgeführten Harvesting werden querbeet aus den Heften 1, 2 und 3 von Band 53 der ein oder der andere Artikel erfasst, ohne dass man ein System erkennen kann.
Darüber hinaus hat man auch hier das Problem, dass nur die Gesamtseitenzahl eines Artikels erfasst werden kann.
In meinen Augen ein Fall für das halbautomatische Verfahren.

**Comment by kdr154** [comment]
Mappingtabellen für das halbautomatische Verfahren ergänzt
