### ISSUE TITLE
ISSN 2305-0853 In die Skriflig OA

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#442]
Die Zeitschrift ist Open Access. Steht auch so in Zeder.
Würde in 856 $z erfordern:
```
<datafield tag="856" ind1="4" ind2="0">
.
.
<subfield code="z">Kostenfrei</subfield>
</datafield>
```

**Comment by shadeMe** [comment]
Die ISSN dieser Zeitschrift müsste dann im ISSN_to_licence.map eingetragen werden.

**Comment by shadeMe** [comment]
@kdr154

**Comment by kdr154** [comment]
Geschlossen
