### ISSUE TITLE
ISSN 2340-4256 Cauriensia Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#443]
Kann man dafür einen Translator schreiben?
http://cauriensia.es/index.php/cauriensia/issue/archive
Vielleicht geht auch RSS Harvesting

**Comment by shadeMe** [comment]
Bei dieser Webseite funktioniert der [Open Journal Systems Multi-Wrapper](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Open%20Journal%20Systems%20Multi-Wrapper.js) Translator.

**Comment by kdr154** [comment]
Leider steht er in diesem Fall bei mir nicht zur Verfügung

**Comment by shadeMe** [comment]
Die Keywords lassen sich einigermaßen extrahieren aber die anderen Angaben sind leider in keine strukturierte Art und Weise dargestellt. Von daher ist es schwierig, sie zuverlässig zu erkennen/extrahieren. Ich schreibe jedenfalls einen neuen Translator für die Keywords.

**Comment by shadeMe** [comment]
Der neue Translator - https://github.com/ubtue/zotero-translators/blob/master/ubtue_Cauriensia.js

**Comment by socheres** [comment]
@kdr154 der Translator ist soweit angepasst (Ausgabe und Abstract). Bitte testen und den Issue schließen.

**Comment by kdr154** [comment]
Das Feld Ausgabe ist korrekt, die Abstracts sind in beiden Sprachen vorhanden. Schöner wäre es allerdings gewesen, wenn die Begriffe "Resumen" und "Abstract" getilgt worden wären. Aber man muss beim Abstract sowieso nacharbeiten: \n4207 zwischen den Teilen ergänzen.
Die Keywords fehlen allerdings weiterhin.
