### ISSUE TITLE
ISSN 2386-7442 Collectanea Christiana Orientalia

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#444]
Beim Multidownload steht der OJS-Translator nicht zur Verfügung. Es wird dann der Equinox-Translator genommen mit der Folge, dass Abstract, Sprache und Keywords fehlen. Darüber hinaus steht im Feld Ausgabe fälschelicherweise die 0. Es fällt auf, dass in diesem Fall die Print-ISSN 1697-2104 genommen wird.
Beim Einzeldownload will das System zunächst den Equinox-Translator nehmen, stellt dann aber, nach einer kurzen Fehlermeldung, auf den OJS-Translator um. Dann sind die Daten gut.
Die Zeitschrift ist auch Bestandteil des automatischen Verfahren. Im Augenblick noch Teil des Crawlens. Die Daten hier sind gut, bis auf die Probleme mit den nicht verlinkten Artikeln (siehe #351). Allerdings gibt es hier einen RSS-Feed, der noch nicht eingetragen ist.

**Comment by shadeMe** [comment]
Bei dieser Webseite funktioniert der [Open Journal Systems Multi-Wrapper](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Open%20Journal%20Systems%20Multi-Wrapper.js) Translator.

**Comment by kdr154** [comment]
Den Multi-Wrapper kann man jetzt zwar aufrufen, jedoch funktioniert er nicht richtig. Das Fenster zur Auswahl der Aufsätze wird immer zweimal angezeigt, wählt man dann alle aus, passiert nichts weiter, wählt man einen aus, bekommt man eine Fehlermeldung. Der Aufsatz wird dann zwar trotzdem übertragen, die Daten sind aber nicht gut: keine keywords, kein abstract, die 0 überflüssigerweise im Feld Ausgabe.

**Comment by shadeMe** [comment]
Die Translators bzw. die Dateien, die in dem obigen [Pull-Request](https://github.com/ubtue/zotero-translators/pull/101) geändert wurden, müssen bei dir lokal aktualisiert werden.

**Comment by kdr154** [comment]
Nach dem Umweg Rechtsclick steht der Multi-Wrapper jetzt zwar zur Verfügung und man kann ihn auch auswählen und die Einträge auswählen. Es geschieht aber nichts, kein Download, bzw. es wird das Fenster erneut angezeigt und dann noch ein weiteres mit einem Eintrag "no title found"

**Comment by kdr154** [comment]
Ich hoffe andere haben mehr Glück. Bei mir hat sich nichts geändert.

**Comment by socheres** [comment]
- [x] bereit für Zotkat
Collectanea Christiana Orientalia auswählen
![grafik](https://user-images.githubusercontent.com/1545743/81937392-db79b700-95f3-11ea-9a1d-4abbe94df997.png)
- [x] Rezension als Magazinartikel erkannt
- [x] Tag "Book Reviews" bei Rezensionen 
- [x] Tag "Kongressbericht" bei `/Seminario|Conferences|Congress|Congreso/g`
- [ ] Zotaut-Kandidat

**Comment by kdr154** [comment]
Es funktioniert keiner der Translatoren die angeboten werden. Am besten ist noch COinS

**Comment by socheres** [comment]
@kdr154 gab es bei Ihnen  "Collectanea Christiana Orientalia" zur Auswahl? @theo-ko könnten Sie auch noch testen? Bei mir hat alles gut funktioniert.

**Comment by kdr154** [comment]
gab es.

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Kim, Timotheus Chang-whae <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 15:56
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2386-7442 Collectanea Christiana Orientalia (#444)

 

@kdr154 <https://github.com/kdr154>  gab es bei Ihnen "Collectanea Christiana Orientalia" zur Auswahl? @theo-ko <https://github.com/theo-ko>  könnten Sie auch noch testen? Bei mir hat alles gut funktioniert.

**Comment by theo-ko** [comment]
Der Multi-Export funktioniert bei mir auch nicht, nur der Einzel. Beim Multi kann ich zwar alle Artikel auswählen, dann kommt das Fenster nochmal und dann ein Fenster mit [no title found] als Auswahl.

Ich kann keine unterschiedlichen Translator auswählen. Es steht nur EquinoxPub in Klammern beim Add-On-Button für den Multi- und Einzel-Export.
Beim Einzel-Export schien alles übernommen worden zu sein (hebräische Zeichen, Abstract, Keywords, Sprache, DOI etc.)

**Comment by socheres** [comment]
Sie müssen die Seite neuladen und den Translator über Add-On-Einstellung (im Browsermenu Extras > Add-ons > Zotero > Einstellungen) aktualisieren.
![image](https://user-images.githubusercontent.com/1545743/81945258-2ac4e500-95fe-11ea-9c7b-bbd2a44ed902.png)
Am Besten auch Zotero neustarten.

**Comment by theo-ko** [comment]
@socheres Hat geklappt. Allerdings wird in Zotero "Ausgabe 0" angegeben, dies führt in der WinIBW dann zu 4070 $v16$j2019**$a**$p81-98. Da keine Heft-Nr. existiert, sollte gar kein $a ausgegeben werden.

**Comment by kdr154** [comment]
Stimmt, es klappt. Es ist nur irritierend, dass man im Download-Fenster, wo man auswählen kann, keinen Titel angezeigt bekommt, sondern als Titel nur "PDF".
Drei der Rezensionen wurden bei mir als Dokumenttyp Magazinartikel heruntergeladen, MIHOC, Wellhofer und Yoles, die anderen beiden als Zeitschriftenartikel.
Das Feld "Ausgabe" bleibt bei mir leer.

**Comment by theo-ko** [comment]
@kdr154 Das ist seltsam, bei mir wurden die Rezensionen alle als Zeitschriftenartikel in Zotero angezeigt. Und bei der Ausfürhung des Add-On-Buttons wurden mir alle gefundenen Artikel im Download-Fenster normal angezeigt.
Nun habe ich es nochmal testen wollen, und jetzt habe ich wieder Probleme mit dem Download.

**Comment by socheres** [comment]
@theo-ko eigentlich ist der Translator "Collectanea Christiana Orientalia" auf ihrem Laufwerk "zotero_ko" aktuell. Können Sie bitte nochmal testen? Am Besten Browser und Zotero neustarten und falls im Hintergrundprozessor noch Zotero läuft, dort das Programm auch beenden.

**Comment by socheres** [comment]
Um Rezensionsfelder wie z.B. Feld `1131 !106186019!` in PICA+ zu erzeugen, braucht man als Dokumenttyp "magazineArticle" . Bei allen Jahrgängen bis auf 2019 kommt das Wort "ISBN" im Rezensionstitel vor. Als Muster wird folgenden Regex verwendet `/ISBN|Verlag|Press/g`. "Verlag" und "Press" könnte aber auch im Titel vorkommen, daher sollten die heruntergeladenen Metadaten in Zotero vor dem BatchUpload kurz überprüft werden.

**Comment by kdr154** [comment]
Ich muss den Translator "Collectanea Christiana Orientila" ebenfalls manuell auswählen. Standardmäßig wird Equinox verwendet.

**Comment by kdr154** [comment]
Die anderen beiden Rezensionen von Forness und Albarracín werden dann aber nicht erkannt.

**Comment by kdr154** [comment]
Habe weiterhin keinen "Collectanea Christiana Orientalia"-Translator. Nur Coins und Doi im Multi, zusätzlich Open Journal Systems und Embedded Metadata im Single

**Comment by IxKo** [comment]
Mir wird beim aktuellen Band (https://www.uco.es/revistas/index.php/cco/issue/view/67) ein Translator (ubtue_collectanea...) angeboten.
Es passiert jedoch nichts, wenn ich ihn auswähle.

**Comment by kdr154** [comment]
Oh, bei mir jetzt auch. Der Download funktioniert auch gut. Allerdings ohne die Resenhas.

**Comment by socheres** [comment]
bei mir funktioniert der Download und die Daten sehen gut aus. Die Rezensionen müssen zurzeit einzel heruntergeladen werden, da der Titel nicht verlinkt ist.

**Comment by socheres** [comment]
@kdr154 bitte in ZEDER vermerken, dass die Rezensionen "Resenhas" einzeln heruntergeladen werden müssen. Wenn soweit alles ok ist, bitte schließen.

**Comment by kdr154** [comment]
In ZEDER vermerkt.
