### ISSUE TITLE
ISSN 2325-4793 Journal of septuagint and cognate studies Sprache (Tag 041)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#445]
Es wird generell Englisch in 041 ausgegeben.
https://poj.peeters-leuven.be/content.php?url=article&id=3285073&journal_code=JSCS
ist aber französisch
https://poj.peeters-leuven.be/content.php?url=article.php&id=3285071&journal_code=JSCS
deutsch

**Comment by kdr154** [comment]
Die Spracherkennung bleibt nach wie vor fehlerhaft. Etwa hier:
```
<datafield tag="041" ind1=" " ind2=" ">
<subfield code="a">ger</subfield>
</datafield>
<datafield tag="100" ind1="1" ind2=" ">
<subfield code="4">aut</subfield>
<subfield code="a">Mielcarek, Krzysztof</subfield>
</datafield>
<datafield tag="245" ind1="0" ind2="0">
<subfield code="a">Septuagint Studies in Poland:  Recent Trends and Current Status</subfield></datafield>
```

**Comment by mtrojan-ub** [comment]
Habe die Zeitschrift neu heruntergeladen. Unter den ersten 20 werden lediglich 3 falsch erkannt. Da es sich um eine Heuristik handelt ist keine 100%ige Trefferchance zu erwarten.

@ruschein kann potenzielle weitere Optimierungsmöglichkeiten am Besten einschätzen, ich habe ihn im Issue mit aufgenommen.

**Comment by ruschein** [comment]
@kdr154 Bitte das Issue schließen.

**Comment by kdr154** [comment]
gut
