### ISSUE TITLE
ISSN 1814-2036 Mitteilungen zur christlichen Archäologie

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#447]
Ich sage mal: angesichts der Vorlage ist das Ergebnis ziemlich gut!
Auf das Abstract (Tag 520) kann im Grunde genommen immer verzichtet werden. Es besteht immer aus dem Inhaltsverzeichnis des jeweiligen Hefts, aus dem der erfasste Artikel stammt.
Nur bei dem in jedem Heft vorkommenden Titel "Inhaltsverzeichnis" macht es Sinn. Verwirft man diesen "Artikel", kann man bei dieser ZS ganz auf die Abstracts verzichten.
Dann gibt es eine ganze Reihe von in jedem Heft wiederkehrenden records (="Artikel"), die man auch verwerfen könnte. Das sind:
Titelei
Inhaltsverzeichnis (s. o.)
Vorwort
Mitarbeiter/innen des Bandes
dann nicht in jedem Heft vorhanden, aber gelegentlich auch als separater Eintrag vorhanden:
I. Abteilung ...
II. Abteilung ...
@thefass was meinen Sie? Vorwort ja, alles andere weg? Oder das Inhaltsverzeichnis auch beibehalten? Oder alles weg, was gerade an records erwähnt wurde?

**Comment by shadeMe** [comment]
@thefass Kannst du kurz erklären?

**Comment by thefass** [comment]
Vorwort ja, auf alles andere kann verzichtet werden

**Comment by kdr154** [comment]
Es hat sich so gut wie nichts geändert. Bis auf den Titel mit dem Titel "Vorwort" sollten alle folgenden Titel (=Aufsätze) verworfen werden:

Titelei
Inhaltsverzeichnis
Mitarbeiter/innen dieses Bandes
Mitarbeiter dieses Bandes

soweit ich sehe, alles in Großbuchstaben

dann auch die, die mit einer oder mehreren römischen Ziffer beginnen, in der Regel werden die mit einem großen "I" (wie in Igel, kein l wie in lesen) dargestellt. Dann folgt ein Punkt ".",dann ein Leerzeichen " ", dann das Wort "Abteilung" in Großbuchstaben, direkt gefolgt von einem ":". Dann wieder ein Leerzeichen und beliebiger Text. Am Ende steht dann das Wort "page" gefolgt von Ziffern.

Beispiel: II. ABTEILUNG: Literaturbericht page 13

Titel (=Aufsätze), die diesem Muster folgen, sollten verworfen werden.

**Comment by kdr154** [comment]
Verfahren wird nicht mehr angewandt
