### ISSUE TITLE
ISSN 0890-2461 Philosophy & theology Tag 084 und 935

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#448]
Tag 007 hat den Wert "tu" statt "cr|||||".

**Comment by mtrojan-ub** [comment]
Das liegt daran dass die Online ISSN fehlt. In Zeder ist das Feld "essn" ebenfalls leer.
http://www-ub.ub.uni-tuebingen.de/zeder/?instanz=ixtheo#suche=Z%3D843

**Comment by mtrojan-ub** [comment]
Jetzt sieht's gut aus!

**Comment by kdr154** [comment]
Stimmt
