### ISSUE TITLE
Equinox ISSN 1757-2479 Les tableaux sur toile du Grand Temple de la rue du Persil à Bruxelles (1878–79)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#45]
Equinox ist leider auch ein Publisher, bei dem die Aufbereitung der Daten große Probleme bereitet. Es wäre ein vorrangiges Anliegen, für diesen Verlag einen Translator für  Zotero zu schreiben, da dieser Verlag einiges führt, was für den IxTheo und RelBib wichtig und relevant ist. 
Was die Daten dieser Zeitschrift und dieses Aufsatzes anbelangt: Sie sind so mangelhaft, dass ich diese Zeitschrift, möglicherweise auch alles, was auf dieser Plattform publiziert wird, zurückstellen würde, wenn keine Möglichkeit gefunden wird, die Daten besser abzugreifen.
Es fehlt:
100 / 700 - der Verfasser und die weiteren Verfasser
Band, Heft, Jahr, Seitenzahlen - alles in 773 bzw 936 unterzubringen
024 - der DOI
041 - der Language Code ist, wird, wie man an diesem Fall sieht, nicht richtig wiedergegeben
935 (website), trifft in diesem Fall nicht zu
es handelt sich auch nicht um eine integrierende Ressource - Leader code nai
...

**Comment by shadeMe** [comment]
Implementiert in ubtue/zotero-translators#28.

**Comment by ruschein** [comment]
@kdr154 Das neue Tag ist von mir.  Es ist die Zeder-ID.  Das können Sie ignorieren, wir löschen es automatisch heraus bevor wir die Daten an das BSZ schicken.   Das Feld wird benutzt in einer Datenbank wo eine Historie der ans BSZ ausgelieferten gespeichert wird.

**Comment by shadeMe** [comment]
Gefixt durch ubtue/zotero-translators#32.

**Comment by mtrojan-ub** [comment]
So, jetzt funktionierts hoffentlich endlich :sweat_smile:
bitte nochmal ausprobieren!

**Comment by kdr154** [comment]
Soweit sehen die Daten gut aus, bis auf die immer noch nicht umgesetzte Form von 650 und eine Sache mit dem Abstract, die mir hier auffällt. Schließe Issue 45 und mache für die Keywords und das Abstract hier jeweils ein eigenes auf.
