### ISSUE TITLE
ISSN 2295-5186 Theoforum Sprache (Tag 041)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#452]
Ein schwieriger Fall. Ich beschreibe ihn trotzdem
Dieser Artikel: https://poj.peeters-leuven.be/content.php?url=article&id=3115478&journal_code=TF
ist auf Englisch verfasst. In 041 wird aber fre für französisch ausgegeben. Zurückzuführen wahrscheinlich darauf, dass der Untertitel französisch ist, weil er ein auf französisch verfasstes Werk nennt.
Die oben genannte Webseite unterscheidet zwischen Title und Subtitle, womit man schon eine Möglichkeit hätte, die richtige Sprachbezeichnung auszuwählen.

**Comment by shadeMe** [comment]
Ja, bei diesem Fall gibt es leider keine gute Lösung. Der Translator nimmt auch den Untertitel im Title mit auf und von daher ist es dem Harvester schwierig, die Sprache (ohne Abstract) automatisch zu erkennen.

**Comment by shadeMe** [comment]
Muss händisch korrigiert werden. Wir können dieses Issue schließen.

**Comment by kdr154** [comment]
ok
