### ISSUE TITLE
ISSN 2308-0698 Religija. Cerkovnoe. Obščestvo = Religion. Church. Society

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#454]
http://rcs-almanac.ru/en/almanac/
Kann man dafür einen Translator schreiben?

**Comment by shadeMe** [comment]
Ich habe's versucht aber leider ist diese Webseite zu unstrukturiert, um Metadaten zu erzeugen. Sogar hat der DOI Resolver/CrossRef keine Treffer.

**Comment by socheres** [comment]
@kdr bitte diesen Issue schließen.

**Comment by kdr154** [comment]
In Ordnung!
