### ISSUE TITLE
Tag 852 $a ISIL

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#456]
Lt. Protokollnotizen MARC21-Besprechung vom 26.06.2018 liefern wir die jeweilige ISIL für die Lokaldaten in Feld 852 mit. Daraus werden im K10plus Lokalsätze generiert.

Abhängig von den Abrufzeichen in 935 $a (siehe https://github.com/ubtue/DatenProbleme/issues/455) lauten die ISILs:

935 $a mteo = 852 $aDE-Tue135
935 $a mkri = 852 $aDE-2619

**Comment by kdr154** [comment]
Es werden neue Daten geliefert
