### ISSUE TITLE
CUP ISSN 2163-3088 THE NEW GENEALOGY OF RELIGIOUS FREEDOM 773 $g

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#46]
Unvollständig und formal falsch. Es fehlen Heft, Jahr, Seitenzahlen.
Analog zu #32 und #41

**Comment by kdr154** [comment]
Es fehlt weiterhin die Heftzählung in 773 g

**Comment by mtrojan-ub** [comment]
Seltsam, in Zotero selbst sieht es richtig aus. Nehme an dass die Ursache die selbe ist wie bei #49

**Comment by kdr154** [comment]
Gelöst
