### ISSUE TITLE
Tag 650 falsch belegt

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#461]
Die PPN-Verknüpfung zu "Rezension" steckt im falschen MARC-Feld 650 = PICA 5520. Dort werden nicht-normierte Schlagwörter unverknüpft erfasst.

Rezension gehört in MARC-Feld **655** = PICA 1131:

655 7$aRezension$0(DE-588)4049712-4$0(DE-627)106186019$0(DE-576)209083166$2gnd-content

**Comment by shadeMe** [comment]
Bei Rezensionen sieht das 655 Feld gerade so aus: 655 7$a!106186019!$0(DE-588). Vgl #197. Stimmt das nicht mehr?

**Comment by kdr154** [comment]
Bei #456
#458
#459
#460
#461 und #463 
handelt es sich um eine Prüfung einer Einspielung aus der Repository des BSZ mit von uns geliefertern Daten, die mit dem Kommando:
f bbg osx bud 2019-09-20 
aus der Kommandozeile der Testdatenbank aufgerufen werden können. Wir haben um eine neue Einspielung mit frischen, neuen, anderen Daten gebeten um sicher sein zu können, dass das, was sich im Repository des BSZ befindet, dem aktuellen Stand entspricht.
Aber unabhängig davon kann man sich trotzdem Gedanken machen, warum das ein oder andere so aussieht, wie es sich darstellt.

**Comment by socheres** [comment]
gelöst. siehe #662
