### ISSUE TITLE
ISSN 0101-3130 Estudos teológicos  Falsche Jahresangabe in 936 und 773

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#462]
gelegentlich wird das Jahr in 936 und 773 nicht richtig ausgelesen.
Bsp. die Aufsätze aus dem Heft 55(1) stammen alle aus dem Jahr 2015. 
http://periodicos.est.edu.br/index.php/estudos_teologicos/issue/view/276
In 936 und 773 steht aber 2016.
Ist bei diesem Heft durchgehend falsch

**Comment by ruschein** [comment]
@kdr154 Ist das dann bei allen Jahrgängen um Eins versetzt?  Falls nicht sollenten wir diese Zeitschrift as dem vollautomatischen Verfahren nehmen.

**Comment by kdr154** [comment]
Nein, soweit ich gesehen habe, stimmt es sonst. Mir ist auch unklar, woher diese Information in diesem Fall geommen wird. Auf der Seite finde ich nur 2015

**Comment by shadeMe** [comment]
Bei dieser Webseite bzw. dieser Ausgabe ist die Datum-Angabe in den eingebetteten Metadaten einfach falsch.

**Comment by kdr154** [comment]
ok
