### ISSUE TITLE
Default Lieferweg Testdaten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#463]
Ich habe die 961 Datensätze durchgesehen und fasse zusmammen, was mir aufgefallen ist.
Pica 0575 (mkri,mteo) fehlt bei den Daten von IxTheo immer, bei Krimdok immer vorhanden
Pica 1500 (Sprache):
wenn die 1500 fehlt, dann bei Daten aus dem Bereich KrimDok, aber nicht bei allen
Pica 1505 fehlt immer
Pica 3000 und 3010 Verfasser werden nie verknüpft, aber
Pica 8910 wird jeden Verfasser erzeugt
Pica 4000 Verantwortlichkeitsangabe $h fehlt
Pica 4070 und 4241 fehlt, nur vorhanden bei folgenden Zeitschriften:
Criminal justice and policy review (Sage), aber nur 1 Titel, kommt über KrimDok
Reviews in religion and theology (Wiley), kommt über IxTheo
Journal of Law and Religion (CUP), kommt über IxTheo
Pica 5056 fehlt immer
Book reviews:
Werden nur erkannt bei der Zeitschrift "Reviews in religion and theology". Diese ZS besteht ausschließlich aus Reviews.
Die Verknüpfung zum Normdatensatz für Rezensionen steht aber fälschlicherweise in Pica 5520 statt in 1131
Gelegentlich kommt Book Review auch in verbaler Form als Schlagwort in 5520 vor
Andere Reviews werden nicht erkannt, obwohl es offensichtlich welche sind
Gelegentlich überflüssige Aufnahmen, wo z.B. das Titelblatt erfasst worden ist. Bsp. Satz 928
Lokaldaten:
Pica 7100 $j J muss groß geschrieben werden
Pica 7901 Katagisierungsquelle immer TUIXTH
Pica 8012 falsche Abrufzeichne imwa
Exemplarsatz: E001 ... Datum formal falsch (Fehlermeldung beim Speichern), ISIL und ELN fehlen

**Comment by IxTheoKm** [comment]
Zu Feld 1505:
Lt. Absprache werden die Aufnahmen wie alle Einspielungen der Verlage und aus als RAK-Aufnahmen eingespielt, daher entfällt 1505 $erda

4000 $h sollte m.W. entfallen, da nicht gesichert ist, wie die Vorlageformen lauten. Verlagseinspielungen werden ebenso behandelt.

Ich hatte gestern Einzel-Issues zu dieser Zusammenfassung erstellt. Sollen die dann geschlossen werden?
https://github.com/ubtue/DatenProbleme/issues/456
https://github.com/ubtue/DatenProbleme/issues/458
https://github.com/ubtue/DatenProbleme/issues/459
https://github.com/ubtue/DatenProbleme/issues/460
https://github.com/ubtue/DatenProbleme/issues/461

**Comment by socheres** [comment]
@kdr154 diesen Issue bitte schließen. Die o.g. Probleme tauchen mittlerweile nicht mehr auf.

**Comment by kdr154** [comment]
ok
