### ISSUE TITLE
ISSN 2284-3515 Aisthema Abstract, Keywords, Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#464]
Abstract, Keywords und Sprache werden in diesem Fall nicht geliefert.
Vorsicht bei den Abstracts. Das besteht z. T. aus mehreren Absätzen. Diese sollten zu einem geschlossenen Absatz zusammengefasst werden.

**Comment by shadeMe** [comment]
Der [Open Journal Systems Multi-Wrapper](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Open%20Journal%20Systems%20Multi-Wrapper.js) Translator liefert alle obigen Felder ohne Problem.

**Comment by kdr154** [comment]
Sehr gut!
