### ISSUE TITLE
RSS Feeds

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#465]
Ich habe wegen der fehlerhaften Darstellung der RSS Feeds im Firefox Kontakt mit der IT aufgenommen.
Laut Herrn Neugebauer stellen die RSS Feeds ein Format dar, dass, bis auf den IE, von keinem Browser mehr unterstützt wird.
Die gewohnte Darstellung lässt sich nur über ein AddOn (Feedbro) erreichen.
Für mich stellt sich damit auch die Frage, ob unser Konzept, neue Aufsätze mittels RSS Feeds zu erfassen, überhaupt zukunftsträchtig ist.

**Comment by shadeMe** [comment]
Hier handelt es sich nur um die Darstellung der XML-Dateien. Das Problem liegt an einem Bug, der sich seit gestern in den Harvester hereingeschlichen ist. Den Bug haben wir jetzt erkannt aber er wird erst am Montag behoben, wenn Herrn Ruscheinski wieder da ist.

In der Zwischenzeit, können die XML-Dateien trotzdem angezeigt werden, in dem "view-source:" am Anfang der URL gehängt wird. Zum Beispiel: `view-source:http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_hzypZb/ixtheo/F6Vjqk.xml`.

**Comment by kdr154** [comment]
Das sind zwei verschiedene Dinge. Die result files nach einem Suchlauf lassen sich wieder darstellen. Das war hier aber nicht gemeint. 
Gemeint ist die Ansicht eines Feeds im Browser. Was man jetzt erhält ist ein XML-Struktur. 
Zuvor war es eine Webseite mit Links, die man anclicken konnte und zu dem entspechenden Artikel geleitet wurde. Dies ist jetzt nur noch im IE der Fall.
Die Frage die ich damit verbinde ist: warum sollen die Verlage in Zukunft diese Feeds überhaupt noch anbieten, wenn die meisten User damit nichts mehr anfangen können.

**Comment by ruschein** [comment]
@kdr154 Das Problem was die Anzeige der XML-Struktur anbelangt, ist das Mozilla bei Firefox, wie zuvor schon Google bei Chrome, die eingebaute Unterstützung für RSS entfernt hat.  Vielleicht gibt es da irgendwelche Addons?

**Comment by shadeMe** [comment]
Das Problem mit der Darstellung ist jetzt behoben. Was die Browser-Unterstützung von RSS Feeds angeht, geht es nur um die eingebaute Anzeige solcher Feeds. Das Standard an sich wird trotzdem unterstützt. Es gibt auch verschiedene "RSS Reader" Apps, die ausschließlich dafür entwickelt werden. Von daher besteht keine große Gefahr, dass das Format von den Verlagsseiten zukünftig veraltet wird.

**Comment by kdr154** [comment]
>>Das Problem mit der Darstellung ist jetzt behoben. Was die Browser-Unterstützung von RSS Feeds >>angeht, geht es nur um die eingebaute Anzeige solcher Feeds
Genau das war ja das Problem, weswegen ich das Issue angelegt habe. Das macht das Testen leider umständlicher und aufwändiger. Ein Link auf die Eingangsseite der Hefte wäre hilfreich.
>Es gibt auch verschiedene "RSS Reader" Apps, die ausschließlich dafür entwickelt werden
Habe ich so geschrieben
>Von daher besteht keine große Gefahr, dass das Format von den Verlagsseiten zukünftig veraltet wird.
Abwarten.

**Comment by socheres** [comment]
@kdr154 Issue bitte schließen.

**Comment by kdr154** [comment]
ok
