### ISSUE TITLE
ISSN 0024-7324 Lumen Vitae Marc21 887 wird immer vergeben

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#466]
Das Tag 887 wird immer vergeben, unabhängig davon, ob ein entsprechender Verfasser existiert oder er das entsprechende Niveau besitzt (mindestens tp3).
Wird dies generell so gehandhabt?
Bsp. ISSN 0024-7324 Lumen  Vitae folgender Aufsatz:
https://poj.peeters-leuven.be/content.php?url=article&id=3285247&journal_code=LV
In den Testdaten steht aber:
```
<datafield tag="887" ind1=" " ind2=" ">
<subfield code="a">Autor in der Zoterovorlage [Roselli, Michele] maschinell zugeordnet</subfield>
<subfield code="2">ixzom</subfield>
</datafield>
```
Im K10plus existiert kein Personensatz Roselli, Michele, in der GND nur ein Tn3-Satz
Auch daran zu erkennen, dass bei Marc21 100 kein $0 vergeben wird.

**Comment by socheres** [comment]
@shadeMe Tag 887 NUR bei positiver Zuordnung des Autoren-Lookup generieren.

**Comment by kdr154** [comment]
Gelöst
