### ISSUE TITLE
ISSN 1095-9270 The International Journal of Nautical Archaeology Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#467]
Rezensionen Tag 655 werden nicht erkannt. Sie stehen in der Sektion Reviews. 
Weiteres Erkennungsmerkmal: in dem getesteten Heft 48.2019,2 besitzen alle eine ISSN im Titel

**Comment by kdr154** [comment]
Werden weiterhin nicht getagt.

**Comment by socheres** [comment]
@kdr154 finde diese Zss. ist nich mehr auf "Nu". Wird sie nicht mehr erfasst?

**Comment by kdr154** [comment]
Nicht mehr über nu, da Auswertung selektiv
