### ISSUE TITLE
ISSN 2295-6093 Augustiniana Spracherkennung fehlerhaft (Tag 041)

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#471]
hier:
https://poj.peeters-leuven.be/content.php?url=article&id=3275098&journal_code=AUG
wird fre statt eng geliefert. Sonst stimmts.

**Comment by kdr154** [comment]
Ist weiterhin fehlerhaft. Hier: https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
liefert der Harvester ger statt eng

**Comment by kdr154** [comment]
Bleibt problematisch, wieder eine falsche Zuordnung.

**Comment by socheres** [comment]
Könnten Sie nochmal testen. Zumidest bei dem erwähnten Artikel wird die Sprache richtig erkannt.
```
Zotero Logger initialized!



Queued journal 'Journal for the study of religion, nature and culture'
| DIRECT @
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
set download-delay for domain 'poj.peeters-leuven.be' to 1000 ms


Harvesting URL 1 [Journal for the stud...] |
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
{8171315134928528308}
Harvest successful




Converting item 1 [Journal for the stud...] |
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
{8171315134928528308}
use online ISSN "1749-4915" with online PPN "549634886"
post-processed author first name = 'Evgenïa', last name = 'Moiseeva',
title = '', affix = ''
language set to default language 'eng'
Augmented metadata record: MetadataRecord {
        url: https://poj.peeters-leuven.be/content.php?url=article,
        item_type: journalArticle,
        title: The Inner Life of Sinners: Saint Augustine on Penance as
disciplina morum,
        short_title: The Inner Life of Sinners,
        abstract_note: Repentance emerged as an important theme in
Augustine’s works as early as 392 and continued to attract his
attention for the rest of his life. While in Augustine’s later works
his interest in repentance as a sacramental rite was largely
stimulated by his responsibility as a bishop for the reconciliation of
sinners, in early works written during the time of Augustine’s
priesthood, significant attention is devoted to the personal dimension
of penance. This essay explores Augustine’s discourse on penance as a
process of personal moral renewal, based on the works he wrote during
his priesthood. After reviewing the background and context of
Augustine’s thinking on repentance, the article discusses three
topics, namely, the relation between penance and will, emotions in the
contrite soul, and the role of humility in the process of moral
renewal. It will be shown that Augustine’s insight in human psychology
resulted in a profound understanding of the moral dimension of penance.,
        publication_title: Augustiniana,
        volume: 69,
        issue: 1,
        pages: 29-54,
        date: 2019-01-01,
        doi: 10.2143/AUG.69.1.3286701,
        language: eng,
        issn: 1749-4915,
        superior_ppn: 549634886,
        superior_type: 2,
        ssg: 1,
        creators: [
                {
                        first_name: Evgenïa,
                        last_name: Moiseeva,
                        type: author,
                },
        ],
}
Generated record with hash 'A3FCF75166F14B92552EE1D63A5E3372480884E9'

Conversion complete


Generated 1 record(s) for item 1 [Journal for the stud...] |
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
{8171315134928528308}



Zotero Harvester Metrics:
        Journals: 1
                Direct: 1
                RSS: 0
                        Skipped: 0
                Crawl: 0
        Crawls: 0
                Successful: 0
                Unsuccessful : 0
                Cache Hits : 0
        Harvests: 1
                Successful: 1
                Unsuccessful : 0
                Cache Hits : 0
                Skipped (already harvested): 0
                Skipped (already delivered): 0
        Records: 1
                Successful: 1
                Unsuccessful: 0
                Skipped (online-first): 0
                Skipped (early-view): 0
                Skipped (exclusion filter): 0
                Skipped (already delivered): 0

        Successfully generated records per group:
                IxTheo: 1
```

**Comment by kdr154** [comment]
Der Titel, an dem der Fehler festgestellt wurde, ist jetzt nicht mehr enthalten.
Aber hier: https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG
stimmt es auch nicht. Geliefert wird ger statt eng

**Comment by socheres** [comment]
Ihr Beispiel 
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG 
habe ich getestet und bekam "eng". Meinen Sie einen anderen Artikel?

**Comment by kdr154** [comment]
Ja, ich habe die aktuellen Daten auf nu getested. Bei dem Artikel, zu dem der Link in dem Beitrag ober Ihrem führt, stimmt es nicht. Wie gesagt geliefert wird ger statt eng hier:
https://poj.peeters-leuven.be/content.php?url=article&id=3286701&journal_code=AUG

**Comment by socheres** [comment]
Können Sie bitte ein Screenshot hochladen?

**Comment by kdr154** [comment]
![grafik](https://user-images.githubusercontent.com/29707105/81950025-bee57b00-9603-11ea-84ef-cd7ec183a88d.png)

**Comment by socheres** [comment]
Das ist aber wirklich merkwürdig, dass wir unterschiedliche Ergebnisse bei derselben Abfrage bekommen. Wie haben Sie getestet? Ich habe auf Nu mit "Try URL" getestet. Vielleicht haben Sie im Reiter "Try RSS" getestet? Wenn ja, mit welchem RSS-Link?
![image](https://user-images.githubusercontent.com/1545743/81951984-27355c00-9606-11ea-9004-7b39faf6266a.png)

**Comment by kdr154** [comment]
Mit try RSS. Ist das nicht richtrig. Ich gehe folgendermaßen vor:
In nu gebe ich die ISSN ein. Dann bleibt eine Zeile stehen:
![bbb](https://user-images.githubusercontent.com/29707105/82018755-35c35800-9686-11ea-9eab-e516259ca797.png)
Hier klicke ich auf Try Rss (rot umrandet), von dort werde ich weitergeleitet auf eine Seite, wo ich den Button Daten absenden anklicke. Dann läuft das Harvesting. Am Ende klicke ich dann in der 3. Zeile auf Download Result File. Dann wird mir das Ergebnis angezeigt.

**Comment by kdr154** [comment]
Wenn ich den eingangs erwähnten Fall mit Try URL teste, stimmt die Sprache jetzt (eng)

**Comment by socheres** [comment]
Welchen RSS-Link hatten Sie als Abfragewert?

**Comment by kdr154** [comment]
https://poj.peeters-leuven.be/RSS/AUG.xml

**Comment by socheres** [comment]
@mtrojan-ub Try URL und Try RSS liefern unterschiedliche Ergebnisse. Mit Try URL bekommt man "eng", aber mit Try RSS "ger". Haben beide Modi nicht dieselbe Einstellung im Harvester?

**Comment by mtrojan-ub** [comment]
Try RSS: ger
Try URL: Hängt davon ab ob "Journal" korrekt ausgewählt wurde
- "Default": eng
- "Augustiniana : tijdschrift voor de studie van Sint Augustinus en de Augustijnenorde": ger

**Comment by socheres** [comment]
D.h. die Spracherkennung im Harvester ist in diesem Fall fehlerhaft? Wörter im Titel sowie Abstract sind eindeutig englisch, aber wird trotzdem als "ger" ausgegeben.

**Comment by mtrojan-ub** [comment]
Aktuelle Konfiguration für diese Zeitschrift:
`zotero_expected_languages = *eng,fre,ger,ita`

Sieht so aus als ob die Heuristik in diesem Fall die Sprache nicht richtig erkennt. Wenn ich mir die anderen Artikel so anschaue, sieht es aber ohnehin so aus als ob es auch manchmal Deutsche Titel mit englischem Abstract gibt. Wäre es da bei dieser Zeitschrift nicht besser die Konfiguration zu ändern und die Spracherkennung auf den Titel einzuschränken?

`zotero_expected_languages = *title:eng,fre,ger,ita`

Beispiel:

> Titel:
> Et potest hoc iubere Deus?: Abraham und Isaak in den Predigten des Augustinus. Mit einer Neuedition von Augustinus, Sermo 2
>
> Abstract:
> This article provides a critical edition of Augustine’s Sermo 2 on Abraham and Isaac. The text of this sermon has come down to us incomplete, since the longest version, provided by the collection Sancti catholici patres (s. XII), is not more but a composition of the mutilated text of the Collectio Lugdunensis (cc. an. 700) and an excerpt in Bede’s Collectanea in Apostolum. Thus, to the difference of the previous edition by Lambot (CCSL 41A), the collection Sancti catholici patres cannot be invoked as an independent textual witness and the critical edition has to be based only on the Collectio Lugdunensis and Bede’s excerpts. This new evaluation of the transmission requires several modifications of the text. In addition, this article compares the structure and motives of Sermo 2 to Sermo 2A, a homily on Abraham and Isaac that was recently reascribed to Augustine.

**Comment by socheres** [comment]
@ruschein Spracherkennung ist bei dieser Zeitschrift auf den Titel eingeschränkt `zotero_expected_languages = *title:eng,fre,ger,ita`, wird aber im u.g. Beispiel trotzdem falsch erkannt. Warum ist der Score-Wert "ger" höher als "eng"?

The 
Inner 
Life 
of 
Sinners: 
Saint 
Augustine 
on 
Penance 
as 
disciplina 
morum

```
Converting item 3 [Augustiniana : tijds...] | http://poj.peeters-leuven.be/content.php?url=article&id=3286701 {2895786046330268278}
use online ISSN "2295-6093" with online PPN "786668970"
post-processed author first name = 'Evgenïa', last name = 'Moiseeva', title = '', affix = ''
forcing automatic language detection, reason: conf setting
generated too few ngrams (226 < 400)!
eng scored :0.675345
fre scored :0.668809
ger scored :0.690329
ita scored :0.638090
automatically detected language to be 'ger'
Augmented metadata record: MetadataRecord {
	url: https://poj.peeters-leuven.be/content.php?url=article&id=3286701,
	item_type: journalArticle,
	title: The Inner Life of Sinners: Saint Augustine on Penance as disciplina morum,
	short_title: The Inner Life of Sinners,
	abstract_note: Repentance emerged as an important theme in Augustine’s works as early as 392 and continued to attract his attention for the rest of his life. While in Augustine’s later works his interest in repentance as a sacramental rite was largely stimulated by his responsibility as a bishop for the reconciliation of sinners, in early works written during the time of Augustine’s priesthood, significant attention is devoted to the personal dimension of penance. This essay explores Augustine’s discourse on penance as a process of personal moral renewal, based on the works he wrote during his priesthood. After reviewing the background and context of Augustine’s thinking on repentance, the article discusses three topics, namely, the relation between penance and will, emotions in the contrite soul, and the role of humility in the process of moral renewal. It will be shown that Augustine’s insight in human psychology resulted in a profound understanding of the moral dimension of penance.,
	publication_title: Augustiniana : tijdschrift voor de studie van Sint Augustinus en de Augustijnenorde,
	volume: 69,
	issue: 1,
	pages: 29-54,
	date: 2019-01-01,
	doi: 10.2143/AUG.69.1.3286701,
	language: ger,
	issn: 2295-6093,
	superior_ppn: 786668970,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Evgenïa,
			last_name: Moiseeva,
			type: author,
		},
	],
}
Generated record with hash 'A47DDCC5107BD8F20F4E538D925AC9F3AB6A00E3'

Conversion complete
```

**Comment by ruschein** [comment]
Das im Einzelnen anzuschauen macht nicht viel Sinn.  Die Wörter werden in N-Gramme zerhackt und diese gegen die N-Gramme der einzelnen Sprachen verglichen.  Das ist in diesem Fall einfach Zufall, dass die deutschen N-Gramme näher an den N-Grammen des Titles sind.  Die angewandte Methode ist statistischer Natur, d.h., es wird immer wieder Fälle geben wo die falsche Sprache zugewiesen wird.  Das einzige was man versuchen könnte ist bessere Trainings-Korpora für die verschiedenen Sprachen zu erstellen um die N-Gramme zu verbessere gegen die verglichen wird.  Dies ist etwas aufwendig und selbst dann wird es ab und zu Falschzuweisungen geben.  Wir könnten auch andere Heuristiken ausprobieren.  Das kann aber viel Entwicklungsaufwand bedeuten und auch andere Heuristiken wären nicht 100% zuverlässig.

**Comment by kdr154** [comment]
Ich lasse offen, aber für den Augenblick ist dieses Issue abgeschlossen.

**Comment by kdr154** [comment]
@socheres Kann man dieses Issue schließen?

**Comment by socheres** [comment]
ja. ich schließe.
