### ISSUE TITLE
ISSN 2159-6875 Jonathan Edwards Studies Verfasserangabe nicht zulässig Tag 100

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#473]
In diesem Fall:
https://jestudies.yale.edu/index.php/journal/article/view/355
wird der Eintrag "The Editors" zur Verlasserangabe.
Das muss unterdrückt werden.
Zudem die Angabe in 887 Autor in der Zoterovorlage [Editors, The] maschinell zugeordnet

**Comment by shadeMe** [comment]
Wollen wir alle Einträge ignorieren, die "The Editors" als Verfasser haben? Oder nut die entsprechenden Felder im Datensatz bzw. 100/700/887?

**Comment by kdr154** [comment]
Nur die Einträge in 100 ... Die Texte können durchaus relevant sein.

**Comment by kdr154** [comment]
Gelöst
