### ISSUE TITLE
ISSN 1759-8818 Sociology of Religion Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#474]
Bei dieser ZS wird das Abstract gelegentlich übertragen, oft aber auch nicht.
Beispielsweise gerade eben hier: https://academic.oup.com/socrel/issue/79/1
Kann es daran liegen, dass die einzelnen Elemente zu langsam laden? Auffällig, wenn man sich das Abstract manuell anzeigen lässt.

**Comment by socheres** [comment]
Um welchen Aufsatz geht es hier? Bitte immer Beispielartikel angeben.

**Comment by kdr154** [comment]
Lässt sich an der genannten Ausgabe nicht mehr reproduzieren. Es sind alle dabei.
Allerdings werden auch alle Extracts (Auszüge) wie ein Abstract behandelt. Das sind sie nicht. Vor allem aber werden die Texte nur angerissen. Bei diesem Aufsatz z. B.:
https://academic.oup.com/socrel/issue/79/1
wird das: 

![grafik](https://user-images.githubusercontent.com/29707105/81949253-eb4cc780-9602-11ea-88d7-aeb7c262af22.png)

so in Zotero übertragen:


![grafik](https://user-images.githubusercontent.com/29707105/81949077-b2acee00-9602-11ea-971b-a404f0d6d80e.png)

**Comment by socheres** [comment]
Ich schaue mir den Translator näher an, vielleicht kann man den Translator so anpassen, dass bei "Extract" das Feld "Zusammenfassung" nicht befüllt wird. Ich gehe davon aus, dass der Datensatz in Zotero händisch korrigiert wird.

**Comment by socheres** [comment]
"Extract" werden entfernt.

**Comment by kdr154** [comment]
Das stimmt. Gut ist es aber leider immer noch nicht, weil da, wo es wirklich ein Abstract gibt, hinter dem Wort "Abstract" zu Beginn der Zusammenfassung ein Absatz gesetzt wird und Leerzeichen eingefügt werden. Zwar wird das Wort "Abstract" getilgt, der Absatz und die Leerzeichen führen aber zu einem Fehler:
https://academic.oup.com/socrel/issue
https://academic.oup.com/socrel/issue

![grafik](https://user-images.githubusercontent.com/29707105/88555518-3a15d500-d028-11ea-8072-048f25b99273.png)


![grafik](https://user-images.githubusercontent.com/29707105/88555595-4ac64b00-d028-11ea-8cfb-d0c64506bc24.png)

**Comment by socheres** [comment]
Habe den "PicaSWB_batch.js" angepasst. Bitte testen.

**Comment by kdr154** [comment]
Jetzt ist es gut!
