### ISSUE TITLE
ISSN 1469-7637  Journal of Ecclesiastical History Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#477]
Bei dieser Zeitschrift werden die Keywords in unzulässiger Art und Weise auseinandergerissen. 
Etwa bei folgendem Artikel: 
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/leviticus-deuteronomy-and-henry-viii/156161AF73E6C4E51BD1EA90C5B5B938
entsteht folgendes:
\n5520 |s|<
\n5520 |s|British Library
\n5520 |s|Calendar of letters
\n5520 |s|Corpus juris canonici
\n5520 |s|Graz 1879-81
\n5520 |s|James Gairdner and R. H. Brodie
\n5520 |s|Letters and papers
\n5520 |s|Liber extra (followed by the numbers of liber
\n5520 |s|London 1862-1964
\n5520 |s|London 1864-1920
\n5520 |s|Oxford dictionary of national biography
\n5520 |s|P. De Gayangos and others
\n5520 |s|The National Archives
\n5520 |s|dispatches and state papers relating to negotiations between England and Spain
\n5520 |s|ed. Emil Friedberg
\n5520 |s|ed. G. A. Bergenroth
\n5520 |s|ed. J. S. Brewer
\n5520 |s|foreign and domestic of the reign of Henry VIII
\n5520 |s|https://www.archive.org>
\n5520 |s|ii
\n5520 |s|titulus and capitulum)

**Comment by socheres** [comment]
@kdr154 die Vorlage liefert falsche Keywords, daher muss sie manuell bereinigt bzw. gelöscht werden. Bitte den Issue schließen. 
![image](https://user-images.githubusercontent.com/1545743/79573751-67fd8c00-80bf-11ea-860e-8b406076c536.png)

**Comment by kdr154** [comment]
Ich schließe
