### ISSUE TITLE
ISSN 2294-6209 Byzantion Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#479]
Comptes rendus ist ein Beitrag, der Rezensionen enthält. Diese Beiträge sollten alle mit dem Tag 655 für Rezensionen gekennzeichnet werden
Hier etwa folgender Beitrag https://poj.peeters-leuven.be/content.php?url=article&id=3117812&journal_code=BYZ

**Comment by socheres** [comment]
Nach[ Merge](https://github.com/ubtue/ub_tools/pull/3389) kann getestet werden.

**Comment by kdr154** [comment]
Hier ist das nicht der Fall:
IxTheo#2020-04-07#9D23153AB2E9CCD1239051E3F7B64CA3ECFC8E32

**Comment by socheres** [comment]
@kdr154 bitte auf Nu testen.

**Comment by kdr154** [comment]
gelöst
