### ISSUE TITLE
ISSN 2413-9467 Stellenbosch Theological Journal Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#480]
Die Seitenzahlen werden hier gedoppelt. So wie hier:
`<subfield code="g">4 (2018), 2, Seite 33–54-33–54</subfield>`

**Comment by mtrojan-ub** [comment]
Das liegt in erster Linie daran dass die Website falsche Metadaten liefert:
![grafik](https://user-images.githubusercontent.com/26873381/74955748-6720e480-5405-11ea-838a-003760b3030c.png)

Ich habe mal eine freundliche Mail an die Betreiber geschrieben, falls sie es nicht selbst anpassen müssen wir notfalls einen Translator schreiben.

**Comment by kdr154** [comment]
Danke!

**Comment by kdr154** [comment]
Hat sich nichts geändert

**Comment by socheres** [comment]
mit "Try URL" getestet.

Augmented metadata record: MetadataRecord {
	url: http://www.scielo.org.za/scielo.php?script=sci_abstract&pid=S2413-94672019000300002&lng=en&nrm=iso&tlng=en,
	item_type: journalArticle,
	title: "The message to the people of South Africa" in contemporary context: The question of Palestine and the challenge to the church,
	short_title: "The message to the people of South Africa" in contemporary context,
	abstract_note: Keywords : Palestine; Apartheid; Barmen Declaration; Liberation Theology; ecumenical movement.,
	publication_title: Stellenbosch theological journal,
	volume: 5,
	issue: 3,
	pages: 13-40,

**Comment by kdr154** [comment]
Wenn man einen einzelnen Aufsatz für sich testet, ist das Ergebnis gut. Wenn man allerdings ein ganzes Heft als URL eingibt, wird nur ein Satz geliefert, der Metadaten zu dem Heft an sich enthält, aber keine Aufsätze.

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by kdr154** [comment]
Testet man ein Heft auf nu, z. B. http://www.scielo.org.za/scielo.php?script=sci_issuetoc&pid=2413-946720200001&lng=en&nrm=iso
besteht das Ergebnis lediglich in einem Datensatz, der Metadaten zum Heft an sich enthält. Die Aufsätze werden nicht erfasst.

![grafik](https://user-images.githubusercontent.com/29707105/92391304-b0741f80-f11c-11ea-9f1b-20acd170f96d.png)

**Comment by socheres** [comment]
Mit "Open Journal Systems Standard" sehen die Seitenzahlen gut.
