### ISSUE TITLE
ISSN 2155-1723 Intermountain West Journal of Religious Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#481]
Es gibt in einigen Heften Book Reviews, die diesen Titel führen (Tag 245). Zudem ist die Sektion mit Book Review überschrieben. Die sollten noch mit dem Tag 655 versehen werden.
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>
<subfield code="0">(DE-588)</subfield>
</datafield>
```

**Comment by socheres** [comment]
Nach Merge kann getestet werden.

**Comment by kdr154** [comment]
Hier fehlt 655 weiterhin:
IxTheo#2020-04-07#FB66DA1E75019682D51DB842445AD16E57C68224

**Comment by IxKo** [comment]
@kdr154 Ich kann den Hash nirgends finden, weder in den Default_Test-Dateien noch in der Test-Datenbank

**Comment by kdr154** [comment]
Die Daten sind unbrauchbar. Es werden keine Artikel geharvestet sondern nur das Heft als solches. In meinen Augen für das vollautomatische Verfahren nicht geeignet.

**Comment by socheres** [comment]
@mtrojan-ub liegt das Problem am Multi-Detect?

**Comment by mtrojan-ub** [comment]
Multi-Detect sollte ja in RSS feeds mit zotaut keine Rolle spielen. Wenn ich das Stand jetzt gerade auf nu teste, dann sind hier durchaus einzelne Artikel enthalten. Außerdem ist auch der Artikel "Book Reviews" enthalten + mit 655 versehen. Von daher kann ich das beschriebene Problem nicht nachvollziehen.

**Comment by socheres** [comment]
@kdr154 würden Sie nochmal testen?

**Comment by kdr154** [comment]
Das Resultat bei mir ist dasselbe, wie oben bereits beschrieben: Es werden keine Artikel geharvestet sondern nur das Heft als solches.

**Comment by socheres** [comment]
Haben Sie mit RSS oder mit URL getestet?

**Comment by kdr154** [comment]
Mit URL

**Comment by socheres** [comment]
Wie sieht das Ergebnis im RSS aus?

**Comment by kdr154** [comment]
Dort werden die einzelnen Artikel erfasst, allerdings auch der Artikel "Book Reviews", der ja verworfen werden sollte: 

https://digitalcommons.usu.edu/imwjournal/vol10/iss1/

![grafik](https://user-images.githubusercontent.com/29707105/88646630-8c590380-d0c5-11ea-8a91-84d8e3f157ec.png)

**Comment by mtrojan-ub** [comment]
Das könnte behoben werden indem in der zotero_harvester.conf die exclude_if_marc_field_245a Direktive bei dieser Zeitschrift angepasst wird

**Comment by socheres** [comment]
mit "Try RSS" getestet.

MARC field for 'https://digitalcommons.usu.edu/imwjournal/vol10/iss1/7 matched exclusion filter (245a/(^IMW Journal)|(^Front Matter$)|(^Book Reviews)/)
Conversion complete
