### ISSUE TITLE
ISSN 1568-5276, 0029-5973 Numen Brill Translator

### ISSUE THREAD

**Issue by RelBibRetroKat** [ubtue/DatenProbleme#487]
Liebe Kolleg/innen,
ich habe versucht, mit Zotero die Brill-Zeitschrift "Numen : international journal for the history of religions" (1568-5276, 0029-5973) zu bearbeiten, aber es funktioniert nur der Einzeldownload und lädt die Zusammenfassung und die Tags nicht herunter.
Die Erweiterung erkennt den Brill-Translator nicht, sondern verwendet statt dessen "Embedded Metadata".
Sybille Deselaers

**Comment by socheres** [comment]
Multidownload funktioniert. @RelBibRetroKat bitte Issue schließen.
