### ISSUE TITLE
ISSN 0210-2870 Diálogo ecuménico Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#489]
bei dieser auf Dialnet erfassten Zeitschrift werden Verfasser (Autoría, Autores) und Erscheinungsvermerk (Localización) fälschlicherweise als Abstract erfasst

**Comment by kdr154** [comment]
Weiterhin so

**Comment by socheres** [comment]
das letzte Heft ist vom 2018. https://dialnet.unirioja.es/servlet/revista?codigo=10829
Muss sie retrospektiv erfasst werden? Wenn nicht, bitte händisch korrigieren.

**Comment by thefass** [comment]
ja, sie muss retrospektiv erfasst werden

**Comment by kdr154** [comment]
Das Problem besteht weiterhin. Außerdem steht sowohl in Single- als auch im Multi-DL nur der Embedded Metadata-Translator zur Verfügung, der im Multi-DL lediglich die Webseite speichert und nicht die Artikel.

**Comment by socheres** [comment]
@kdr154 wegen #1149 konnte Ihre Datei nicht aktualisiert werden. Bitte nochmal testen.

**Comment by kdr154** [comment]
Jetzt passt es.
