### ISSUE TITLE
CUP ISSN 2163-3088 THE NEW GENEALOGY OF RELIGIOUS FREEDOM Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#49]
Auf der Webseite stehen keywords am rechten Rand. Zotero überträgt sie. Das Harvesting hier jedoch nicht.
https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/new-genealogy-of-religious-freedom/A76E3285DBD0EEF59A0EB82D4F4068E7

**Comment by shadeMe** [comment]
@mtrojan-ub Das Problem scheint was mit dem Translation-Server zu tun zu haben. Ich habe die Translators in dem Docker-Container aktualisiert aber es hat nix gebracht.

**Comment by mtrojan-ub** [comment]
Kann selbst kein Problem bei uns feststellen. Der Translator liefert manuell die richtigen Daten, aber der Translation Server liefert nur leere Tags. 

Habe es an Zotero weitergemeldet, siehe zotero/translation-server#48

**Comment by mtrojan-ub** [comment]
... und wieder ein Schritt weiter:

Im RSS Feed steht nicht die o.g. URL, sondern eine DOI:
https://dx.doi.org/10.1017/jlr.2018.11?urlappend=%3Fsource=rss
Diese wird aufgelöst zu:
https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/new-genealogy-of-religious-freedom/A76E3285DBD0EEF59A0EB82D4F4068E7

Schickt man beide URLs an den Translation Server, lässt sich der Fehler reproduzieren.
Bei der ersten URL wird der CSL JSON Translator verwendet, und dieser liefert keine Tags, ein kaputtes Abstract usw.
Bei der zweiten URL ist alles OK.

Ich schätze also, dass es ein ähnliches Problem mit dem Translation Server gibt wie bei #54. Ich würde gerne erstmal abwarten, was im Zotero-Forum dazu gesagt wird und dort im Anschluss bei Bedarf diesen Fall zusätzlich melden.

**Comment by mtrojan-ub** [comment]
Laut Zotero ist es ein anderer Fall als bei den normalen Weiterleitungen. Zotero hat mittlerweile zugesagt dass sie sich selbst um das Problem mit den DOI-Weiterleitungen kümmern werden. Siehe zotero/translation-server#48

**Comment by mtrojan-ub** [comment]
Zotero hat den Fehler behoben und wir haben die Änderung eingespielt. Bitte nochmal testen! (betrifft alle Issues für 2163-3088, ich setze sie auch auf "ready for testing")

**Comment by kdr154** [comment]
Gelöst
