### ISSUE TITLE
ISSN 1754-517X Journal for Late Antique Religion and Culture Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#492]
Die Abstract werden nicht getrennt, wenn die Trennung in der Vorlage mittels Bindestrichen "-" vorgenommen wird.
Hier: 
https://jlarc.cardiffuniversitypress.org/articles/abstract/10.18573/jlarc.109/
Wo die Trennung in der Vorlage mittels Kommas "," vorgenommen wird, stimmt es.
Etwa hier: 
https://jlarc.cardiffuniversitypress.org/articles/abstract/10.18573/jlarc.107/

**Comment by socheres** [comment]
@kdr154 worum geht es hier? Im Mulit-DL mit dem Translator "Ubiquity.."  kamen alle Datensätze richtig rüber: https://jlarc.cardiffuniversitypress.org/25/volume/13/issue/0/ 
Ausgabe "0" werden beim Export entfernt.

**Comment by kdr154** [comment]
Sorry, es ging um die Keywords. Die Darstellung ist aber jetzt in beiden Fällen korrekt.
