### ISSUE TITLE
ISSN 1982-2650 Ciencias sociales y religión Jahrgangsangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#507]
Der Harvester erfasst hier bis auf 11.2009 alle Bände und Jahrgänge, die erschienen sind. Hier das Archiv:
https://seer.ufrgs.br/CienciasSociaiseReligiao/issue/archive
Dabei stimmt in den Daten die Jahrgangsanbabe von 2018-2010
Von 1999-2006 wird immer 2007 ausgegeben.
Ab 2007-2008 stimmt es wieder
Band 11 aus dem Jahr 2009 fehlt dann ganz

**Comment by kdr154** [comment]
Methode wird nicht mehr angewendet

**Comment by RelBibRetroKat** [comment]
Mehrfachdownload mit ubtue_Open Journal System Standard problemlos. Website englisch, spanisch, portugiesisch. Bei Download Abstract durchgängig englisch, Keywords in jeweiliger Sprache. Problem 1: von englischer Seite werden auch die Untertitel auf englisch heruntergeladen, bei den neuesten Jahrgängen auch von spanischer und portugiesischer. Problem 2: ab 21(2019) Artikelzählung, wird in "Seiten" heruntergeladen und in "$p$ eingespielt.

**Comment by RelBibRetroKat** [comment]
Mehrfachdownload mit ubtue_Open Journal System Standard problemlos. Website englisch, spanisch, portugiesisch. Bei Download Abstract durchgängig englisch, Keywords in jeweiliger Sprache. Problem 1: von englischer Seite werden auch die Untertitel auf englisch heruntergeladen, bei den neuesten Jahrgängen auch von spanischer und portugiesischer. Problem 2: ab 21(2019) Artikelzählung, wird in "Seiten" heruntergeladen und in "$p$ eingespielt.
