### ISSUE TITLE
Journal of historical network keine ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#511]
Die Zeitschrift hat keine ISSN. Der Harvester bricht ab mit Exitcode 1:
Processing section "Journal of Historical Network Research".

Starting crawl at base URL: https://jhnr.uni.lu/index.php/jhnr/issue/archive
Skipping URL (does not match extraction regex): https://jhnr.uni.lu/index.php/jhnr/issue/archive
set crawl-delay for domain 'jhnr.uni.lu' to 1000 ms
sleeping for 1000 ms...

Harvesting URL: https://jhnr.uni.lu/index.php/jhnr/issue/view/5
multiple articles found => trying to harvest children
Augmenting JSON...
post-processed author first name = 'Bronagh Ann', last name = 'McShane', title = '', affix = ''
ISSN and PPN could not be chosen! ISSN online: "", ISSN print: "", ISSN zotero: "2535-8863", PPN online: "", PPN print: ""
Backtrace:
  MiscUtil::GetCallStack()
  Logger::error(std::string const&)
  Logger::error(std::string const&, std::string const&)
  Zotero::SelectIssnAndPpn(std::string const&, std::string const&, std::string const&, std::string const&, std::string const&, std::string*, std::string*)
  Zotero::AugmentJson(std::string const&, std::shared_ptr const&, Zotero::SiteParams const&)
  Zotero::Harvest(std::string const&, std::shared_ptr const&, Zotero::SiteParams const&, Zotero::HarvesterErrorLogger*)
  Zotero::HarvestSite(SimpleCrawler::SiteDesc const&, SimpleCrawler::Params, std::shared_ptr const&, std::shared_ptr const&, Zotero::SiteParams const&, Zotero::HarvesterErrorLogger*, File*)
  Main(int, char**)

**Comment by kdr154** [comment]
Verfahren wird nicht mehr angewandt

**Comment by RelBibRetroKat** [comment]
Die Artikel können mit Mehrfachdownload mit ubtue_Open Journal Systems Standard heruntergeladen werden. Es ist eine ISSN vorhanden. Allerdings wird die URL ohne https:// heruntergeladen, Beispiel: //jhnr.uni.lu/index.php/jhnr/article/view/13

**Comment by socheres** [comment]
Liebe @RelBibRetroKat und @IxKo, geht es hier um zotkat?

**Comment by RelBibRetroKat** [comment]
Lieber Herr Kim, die Zeitschrift ist mit zotkat bearbeitet worden und zur Zeit aktuell. Die Frage, ob sie weiterhin mit zotkat bearbeitet wird, müßte Frau Koch entscheiden.

**Comment by IxKo** [comment]
Es geht um das zotkat-Verfahren.
Beim Import fehlt das "https:" vorne:
![image](https://user-images.githubusercontent.com/57000004/149364481-a9c3ebc3-4e39-4025-b409-fd3fc228613d.png)
 
@RelBibRetroKat Lieber immer ein neues Issue aufmachen, auch wenn das deutlich mehr Arbeit bedeutet.

**Comment by socheres** [comment]
Anders als im Zotero-Programm kann ich den Fehler im Scaffold leider nicht reproduzieren. @helenanebel bitte auch testen.

**Comment by helenanebel** [comment]
Lieber @socheres ,
bei mir wird in Scaffold auch die URL normal angezeigt.
Ich habe auch mit dem Multi-Wrapper & Embedded Metadata getestet, da ist es das selbe. 
Am Translator "ubtue_Open Journal Systems Standard" liegt es demnach nicht. Da beim Download mit "Webpage" die URL normal mitkommt, fürchte ich, dass es etwas mit dem EM-Translator zu tun haben könnte.
Viele Grüße, Helena Nebel

**Comment by socheres** [comment]
Mit "PKP Catalog Systems" und "Embedded Metadata"-Translators bekomme ich auch das selbe Ergebnis im Zotero.
Aber im Quelltext sind die urls alle ohne das Präfix "https:":
```
<meta name="DC.Identifier.URI" content="//jhnr.uni.lu/index.php/jhnr/article/view/72"/>
<meta name="citation_abstract_html_url" content="//jhnr.uni.lu/index.php/jhnr/article/view/72"/>
<meta name="citation_pdf_url" content="//jhnr.uni.lu/index.php/jhnr/article/download/72/42"/>
```
Vielleicht das Scaffold fügt das Präfix automatisch hinzu, aber Zotero nicht?

**Comment by IxKo** [comment]
Mittlerweile besteht kein Problem bei zotk
