### ISSUE TITLE
ISSN 2011-9771 Revista Albertus Magnus Abbruch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#512]
Der Harvester bricht nach 3 Sekunden ab:

Processing section "Revista Albertus Magnus".
feed_url: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4

Processing feed URL: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4 (RSS 2.0):
	Title: Revistas Universidad Santo Tomás - Colombia Notificaciones
	Link: https://revistas.usantotomas.edu.co/index.php/albertus-magnus/notification/notificationFeed/rss2/14909563855386e5477f0d4
	Description: 
Extracted metadata from 0 page(s).

**Comment by mtrojan-ub** [comment]
Das scheint ein URL-Problem zu sein.

Wenn ich die o.g. feed_url im Browser öffne erscheint eine Fehlerseite "404 Not Found".
In Zeder hat sich die Konfiguration mittlerweile geändert, aber keine der beiden anderen in Zeder hinterlegten URLs funktioniert bei mir ("Server nicht gefunden"):
p_zot2: https://www.usta.edu.coindex.php/albertus-magnus/issue/archive
url1: http://revistas.usta.edu.co/index.php/albertus-magnus/index

**Comment by kdr154** [comment]
Adresse hat sich geändert. Steht jetzt in Zeder

**Comment by mtrojan-ub** [comment]
Die URLs verweisen aber nicht auf einen RSS-Feed. Muss hier ein anderes Verfahren angewendet werden? (siehe Issue-Label "Zotero_AUTO_RSS" sowie "lrt" in Zeder)

**Comment by kdr154** [comment]
Habe einen Feed in die Spalte rss in Zeder eingetragen. Der einzige von den dreien, die auf den Seiten (Notifcaiones Vista) zu finden war, den ich öffnen konnte. In Zotero zeigt er jedoch keine Inhalte an.

**Comment by mtrojan-ub** [comment]
Die URL wurde angepasst, allerdings gibt es jetzt Probleme beim Erkennen des RSS-Formats. Wir werden es uns noch weiter anschauen.

**Comment by mtrojan-ub** [comment]
Die neue URL scheint mittlerweile ebenfalls nicht mehr verfügbar zu sein. Ich vermute, dass alle URLs auf dieser Webseite die einen längeren Hash enthalten nur Teil des Caches sind und daher nach einiger Zeit ihre Gültigkeit verlieren.

Im HTML Quelltext der Seite gibt es einen Verweis auf folgenden RSS Feed:
https://revistas.usantotomas.edu.co/index.php/albertus-magnus/gateway/plugin/WebFeedGatewayPlugin/rss2

Diesen habe ich auch auf nu mit unserem Verfahren getestet und er scheint brauchbar zu sein. Spricht etwas dagegen diesen Link zu verwenden?

(Falls OK, bitte auch in Zeder aktualisieren)

**Comment by kdr154** [comment]
Spricht nichts dagegen. Habe ihn eingetragen
