### ISSUE TITLE
ISSN 2408-9370 Journal for religion, film and media Abbruch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#516]
Der Harvester bricht nach wenigen Sekunden ab:
Processing section "Journal for religion, film and media : JRFM".

Starting crawl at base URL: https://jrfm.eu/index.php/ojs_jrfm/issue/archive
Failed to retrieve a Web page (https://jrfm.eu/index.php/ojs_jrfm/issue/archive):
Peer certificate cannot be authenticated with given CA certificates
Extracted metadata from 0 page(s).

**Comment by shadeMe** [comment]
Hmm, scheint ein Server-Problem zu sein. Wir müssen abwarten, bis es serverseitig behoben wird.

**Comment by kdr154** [comment]
Methode wird nicht mehr angewendet
