### ISSUE TITLE
ISSN 1012-8093 Acta criminologica : Southern African journal of criminology = Suider-Afrikaanse tydskrif vir kriminologie Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#521]
Nur eine Überlegung: In diesem Fall: https://journals.co.za/content/journal/10520/EJC-159795ad86 macht das System aus "Rhino poaching and South Africa"  2 Keywords. Rhino poaching und South Africa. Dabei handelt es sich um eine bei jedem Artikel wiederkehrende Erscheinung. Die letzten beiden Keywords werden nicht wie die anderen durch ein Komma getrennt, sondern durch das Wort and. Bei beiden Begriffen handelt es sich um separate Links, während das Wort and nicht Bestandteil des Links ist. Die ist bei anderen Einträgen, die eine Präposition enthalten, nicht der Fall. Hier ist dann alles Bestandteil des Links. Z. B. bei "Partnership with rural communities" und das System setzt es in ein Keyword um und nicht in "Partnership" und "rural communities". Deshalb glaube ich, dass alles korrekt ist und würde nichts ändern.
Ich weiß nicht, wie die Programmierung, die dahinter steht aussieht, aber eine allgemeine Regel würde ich nicht daraus machen. (z. B.: trenne Zeichenfolgen im Bereich keywords, die durch die Zeichenfolge "and" oder "und" verbunden sind, in separate Einträge)

**Comment by shadeMe** [comment]
Die Keywords sind einfach die Texte der Links, die im Bereich Keywords stehen. Von daher ist es nicht problematisch, wenn die letzten Keywords durch ein Trennwort getrennt sind.

**Comment by shadeMe** [comment]
Dieses Issue können wir auch schließen.

**Comment by kdr154** [comment]
ok
