### ISSUE TITLE
ISSN 1012-8093 Acta criminologica : Southern African journal of criminology = Suider-Afrikaanse tydskrif vir kriminologie handle

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#522]
Am Ende einer jeden Seite steht ein Persistent Link, der auf einem handle basiert. Das ist ein zuverlässigerer URL, als der URL zur Webseite, der jetzt in 856 steht. 
Gut wäre es, wenn man diese Adresse als zusätzliches 856 aufnehmen könnte.
Perfekt, wenn Tag 024 generiert werden könnte in der Form:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10520/EJC-15976f56a2</subfield>
<subfield code="2">handle</subfield>
</datafield>

```

**Comment by kdr154** [comment]
Tag 024 mit dem handle ist problematisch, da der handle in die Pica Kategorie 2052 gehört, und nicht wie der DOI in 2051.
Wenn das problematisch ist, in diesem Fall 024 lieber weglassen, aber die zusätzliche URL in Marc21 856 aufzunehmen, wäre auf jeden Fall gut.

**Comment by thefass** [comment]
es wäre gut, den handle mit auszugeben, aber er muss natürlich in die richtige Kategorie.
Wenn die Daten an das BSZ geliefert werden, sollte darauf hingewisen werden, dass wir eben in manchen Fällen auch 2052 beliefern

**Comment by kdr154** [comment]
Die URL des Handle steht jetzt in 856. Gut.
Ich würde in diesem Fall aber auch für einen Test mit dem BSZ versuchen 024 in der Form zu erzeugen:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10520/EJC-15976f56a2</subfield>
<subfield code="2">handle</subfield>
</datafield>
```
Der $2 code könnte es doch ermöglichen, die richtige Picakategorie 2052 zu erzeugen. Wie @thefass schreibt, sollten wir bei der Datenlieferung darauf hinweisen. Dann sehen wir ja, ob es möglich ist.

**Comment by kdr154** [comment]
ok

**Comment by kdr154** [comment]
Keine offenen Issues mehr für diese Zeitschrift: Default-Lieferweg freischalten
