### ISSUE TITLE
ISSN 1871-014X Asian Journal of Criminology Online First Articles

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#523]
All die Artikel, die keine Bandangabe (936 $d) und keine Heftzählung (936 $e) besitzen, sind Online First Artikel, zu finden hier: https://link.springer.com/journal/11417/onlineFirst, und damit noch keinem Heft zugeordnet. 
Diese wollten wir übergehen. 
Gründe die dafür sprechen. Sie werden zu einem späteren Zeitpunkt in ein Heft aufgenommen, womit man in diesem Fall eine Dublette generiert, zum anderen dann die Online First Aufnahme obsolet geworden ist. Zumindest stimmt dann der URL zur Webseite nicht mehr, da sie nicht mehr existiert. Ein darin enthaltener DOI hingegen würde weiterhin gültig sein. Ein weiterer Grund der dagegen spricht ist, dass dann und wann einer dieser Online First Artikel wieder zurückgezogen wird.
Für eine Aufnahme spricht, dass die Community an den neuesten Publikationen interessiert ist.

**Comment by shadeMe** [comment]
Die Online-First Artikel werden beim eigentlichen Test-Upload Verfahren ignoriert. Nur aufgrund des Testens werden sie auf Nu mitgeharvestet.

**Comment by shadeMe** [comment]
Wir können dieses Issue schließen, denke ich.

**Comment by kdr154** [comment]
ok, da es keine offenen Issues für diese Zeitschrift mehr gibt, kann man den Default-Lieferweg freischschalten

**Comment by socheres** [comment]
die Onlinefirst-Artikel sind im Testdaten enthalten: "zotero_krimdok_200222_001.xml". Bitte diese wie [oben](https://github.com/ubtue/DatenProbleme/issues/523#issuecomment-553476097) kommentiert  nicht auf "Default_Test" hochschieben.

**Comment by mtrojan-ub** [comment]
@socheres die Datei zotero_krimdok_200222_001.xml enthält keine Datensätze für die ISSN 1871-014X, ich nehme an die Aussage ist im falschen Issue gelandet.

**Comment by socheres** [comment]
Ja, dann schließe ich den Issue.
