### ISSUE TITLE
Wiley ISSN 1467-9418 Tags 773 $g, 936, 362

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#53]
Vgl. #32 usw #48 usw.
Es fehlen Angaben zum Jahr, Heft und zu den Seitenzahlen um die  Tags 773 und 936 richtig zu gestalten. 
362 sollte nicht in Aufsätzen erscheinen

**Comment by mtrojan-ub** [comment]
773 müsste jetzt passen, siehe #32
936 bin ich mir nicht sicher, die Änderung könnte sich aber auch darauf ausgewirkt haben. Bitte erneut testen und falls etwas fehlt, genaueres Format definieren.
zu 362 mache ich gleich noch eine Änderung

**Comment by mtrojan-ub** [comment]
362 ist gefixt, bitte testen

**Comment by kdr154** [comment]
Alles korrekt, 773, 936 und 362 nicht mehr vorhanden. Schließe als gelöst
