### ISSUE TITLE
ISSN 1743-4629 Crime Prevention and Community Safety Nachbearbeitung oder entfernen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#530]
https://link.springer.com/article/10.1057/s41300-019-00074-6
Beihaltet eine Korrektur eines anderen Aufsatzes. Im halbautomatischen Verfahren ist dies ein Fall, bei dem nachbearbeitet werden muss. Sofern es Sinn macht. 
Bei den Onlineausgaben, so auch hier, oft nicht. Der Inhalt des Artikels auf den sich die Korrekturanweisung bezieht, wurde nachträglich korrigiert, so dass dieser Artikel in der korrekten Form im Netz steht. 
Der Aufsatz mit der Korrekturangabe ist im Grunde genommen überflüssig. Man könnte ihn entfernen, da er zu Irritationen führen kann oder einfach nur Verärgerung auslösen könnte. Man kann ihn aber auch nur einfach so stehen lassen und damit etwaige unschöne Begleiterscheinungen in Kauf nehmen. Denn falsch ist es ja nicht, was drin steht.
Leider kann man auch hier keine allgemeine Regel bilden.
Das ist aber das einzige, was mir an dieser Zeitschrift auffällt. Bei dieser Zeitschrift kann man den Default Lieferweg einschalten.

**Comment by shadeMe** [comment]
Ich ändere bei dieser Zeitschrift derzeit nichts und lasse sie einfach so, wie sie ist.

**Comment by kdr154** [comment]
ok Default Lieferweg einschalten
