### ISSUE TITLE
ISSN 1552-3586 Criminal Justice Policy Review 936 mkri, Online First, Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#532]
Die Verdoppelung des Tags 935 mkri wurde bereits bei den anderen getesteten Zeitschriften vermerkt. Ich gehe davon aus, dass das global gelöst wird und ich es nicht jedes mal wieder erwähnen muss. Wenn nicht, bitte Rückmeldung.
Auch hier wieder Online First Artikel. Da diese jedoch beim Weiterverabeiten entfernt werden, ist dies kein Problem.
Bedenken habe ich bei den Rezensionen. Leider gibt es in dem getesteten Heft und auch unter den Online First keine. Sie sind auch selten, kommen aber in anderen Heften vor. Z. B. in 30.2019,5
https://journals.sagepub.com/toc/cjpa/30/5
Wenn keine Gelegenheit besteht, ein solches Heft zu testen, müssen wir es auf gut Glück wagen.

**Comment by shadeMe** [comment]
Das wird nicht problematisch sein. Der SagePub Translator tagt Artikel, die auf der Webseite im Bereich "Book Review" vorkommen, als Rezensionen. Solange die Harvester-Konfiguration der Zeitschrift entsprechend einmal angepasst wird, um es zu berücksichtigen, werden alle künftige Rezensionen richtig erkannt.

**Comment by kdr154** [comment]
ok
