### ISSUE TITLE
ISSN 1478-6028 Criminal Justice Studies 935 mkri, Online First, Corrigendum

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#533]
Hier sollte die Verdoppelung von 935 mkri bereinigt werden, Online First sehe ich für kein Problem an und beim Corrigendum, nicht Bestand der getesten Ausgabe, sondern in 31.2018,2, https://www.tandfonline.com/toc/gjup20/31/2?nav=tocList ist es derselbe Fall wie in #530 . Drin lassen oder entfernen

**Comment by shadeMe** [comment]
Wie im #530. Ich lasse diese Zss wie sie ist.

**Comment by kdr154** [comment]
ok
