### ISSUE TITLE
ISSN 2346-2108 Derecho penal y criminología - Abbruch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#536]
Der Harvester bricht nach kurzer Zeit ab:
Processing section "Derecho penal y criminología : revista del Instituto de Ciencias Penales y Criminológicas de la Universidad Externado de Colombia".
feed_url: https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss

Processing feed URL: https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss
[ERROR-UNKNOWN] for 'https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss': Problem parsing XML document for "https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss": Error while parsing syndication format: Xerces SAXParseException on line 2: comment or processing instruction expected
Extracted metadata from 0 page(s).
Unexpected errors were encountered during the harvesting process

**Comment by shadeMe** [comment]
Der RSS-Feed ist derzeit fehlerhaft. Wir müssen es abwarten.

PS: Da diese Zeitschrift beim Test-Verfahren derzeit nicht aktiviert ist, neheme ich den "high priority" Label ab.

**Comment by jriedl** [comment]
Der Feed scheint nicht mehr das Problem zu sein, es erfolgt ein Download von Einzelartikeln. Allerdings bricht die Konversion ab, da keine online_ppn hinerlegt ist. Diese existiert aber:  644735910. Nachtragen hat bei einem lokalen Test zu einer erfolgreichen Erstellung einer XML-Datei geführt.

**Comment by socheres** [comment]
@kdr154 bitte auf Nu testen.

**Comment by kdr154** [comment]
Ist weiterhin so. Zumindest wenn man ein Heft von dieser Seite testet: https://revistas.uexternado.edu.co/index.php/derpen/issue/archive. Die Ergebnisdatei ist leer.

Der Fehler scheint mir hier zu liegen:

![grafik](https://user-images.githubusercontent.com/29707105/88626719-5c9d0200-d0ab-11ea-9212-4007fbcd428b.png)

**Comment by socheres** [comment]
ePPN "644735910" ist in ZEDER schon vorhanden. @jriedl kannst du dir den Fall nochmal anschauen?

**Comment by jriedl** [comment]
Die Zeitschrift hat in `zotero_harvester.conf` den delivery_mode NONE. Offenbar erfolgt in diesem Fall kein automatischer Abgleich mit Zeder (vgl. `update_zotero_enhancement_maps.sh`). @mtrojan Ist das so beabsichtigt?

**Comment by jriedl** [comment]
Nachtrag: Gerade sehe ich, dass offenbar kein Zusammenhang mit dem delivery mode besteht, sondern der Update-Aufruf von `zeder_to_zotero_importer`  für bereits existierende Einträge einen Feld-Filter hat.

**Comment by socheres** [comment]
@mtrojan-ub wie ist der aktuelle Stand?

**Comment by jriedl** [comment]
Online PPN jetzt per Hand in `zotero_harvester.conf` hinzugefügt.
