### ISSUE TITLE
ISSN 2194-7899 Health & Justice Tag 936 $g 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#537]
In 936 $g wird die Gesamtseitenzahl abgelegt. Was der Harvester hier aber abgreift, ist die Artikelnummer.
z. B. https://healthandjusticejournal.biomedcentral.com/articles/10.1186/s40352-019-0097-6
hier der entsprechende Code:
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">7</subfield>
<subfield code="e">1</subfield>
<subfield code="g">16</subfield>
<subfield code="j">2019</subfield>
</datafield>
```
Tatsächlich hat dieser Artikel 16 Seiten, was man nur dem PDF entnehmen kann

**Comment by shadeMe** [comment]
Hier können wir nicht weitermachen, wenn die Seitenangabe der Seite falsch ist. Wir können dieses Issue schließen.

**Comment by kdr154** [comment]
Dann muss diese Zeitschrift aus dem vollautomatischen Verfahren herausgenommen werden.

**Comment by kdr154** [comment]
ok
