### ISSUE TITLE
Ebscohost ISSN 1216-7827 Shaman

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#54]
Harvesting wird nach wenigen Sekunden abgebrochen mit dem Hinweis:
ERROR Existcode: 1

**Comment by mtrojan-ub** [comment]
Teilproblem wird behoben durch ubtue/ub_tools#2247

**Comment by kdr154** [comment]
Bricht bei mir aber wiederum ab

**Comment by mtrojan-ub** [comment]
ist auch noch nicht fertig! wie gesagt, nur ein Teilproblem ist behoben. Issue stand auch noch nicht auf "ready for testing".

**Comment by mtrojan-ub** [comment]
Ist scheinbar ein Problem im Translation Server mit der Weiterleitung.
Habe es an Zotero gemeldet, siehe zotero/translation-server#49
