### ISSUE TITLE
Ingenta ISSN 2057-4525 Freedom as a 'Way of Seeing' Tag 773 $w

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#56]
`<subfield code="w">(DE-576)43402676X</subfield>`
hier wird auf die SWB-PPN der Druckausgabe des übergeordneten Werks verwiesen, richtig oder besser wäre die PPN der Online-Ausgabe: 
502164646
Zumal auch in $x die ISSN der Online- Ausgabe steht:
`<subfield code="x">2057-4525</subfield>`

**Comment by mtrojan-ub** [comment]
gefixt, bitte nochmal testen

**Comment by kdr154** [comment]
Gelöst
