### ISSUE TITLE
ISSN 2044-8333 Legal and Criminological Psychology Early View

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#565]
Die Artikel, die in 936 (und auch in 773) die Zeichenfolge n/a in einem Subfield haben, sind Early View Artikel und sollten nicht eingespielt werden.
Bsp.:
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">n/a</subfield>
<subfield code="e">n/a</subfield>
```

**Comment by shadeMe** [comment]
Ich passe den Harvester entsprechend an. Allerdings werden solche Datensätze nur bei den Test- und Produktionsverfahren unterdrückt und nicht auf Nu (zwecks des Testens).

**Comment by kdr154** [comment]
ok Default-Lieferweg freischalten
