### ISSUE TITLE
ISSN 1477-2728 Policing and Society Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#568]
Rezensionen werden nicht mit 655 getagt.
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield> 
<subfield code="0">(DE-588)</subfield>
</datafield>

```
Sie stehen in der Sektion Book Review(s), sind mit Book review überschrieben und besitzen im Titelzusatz eine ISBN. 
https://www.tandfonline.com/toc/gpas20/29/9?nav=tocList

**Comment by shadeMe** [comment]
Gibt es einen bestimmte Artikel, der als Rezension getagt werden soll aber doch nicht wird? Ich habe es kurz getestet und es gibt mindestens einen Datensatz, der richtig getagt wurde.

**Comment by kdr154** [comment]
Bei diesem (aktueller Suchlauf), fehlt das Tag:
https://www.tandfonline.com/doi/full/10.1080/10439463.2019.1678621

**Comment by kdr154** [comment]
ok, Default Lieferweg freigeben
