### ISSUE TITLE
Ingenta ISSN 2057-4525 Freedom as a 'Way of Seeing' Tag 935

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#57]
Tag 935 ist inhaltlich falsch: 
```
<datafield tag="935" ind1=" " ind2=" ">
<subfield code="c">website</subfield>
```
und wird bei "normalen" Aufsätzen nicht benötigt

**Comment by mtrojan-ub** [comment]
Liegt daran dass der Translator den Typ "webpage" meldet, siehe #59.

Soll 935c in irgend einem anderen Fall gesetzt werden? Wenn ja, wie? Oder sollen wir es komplett entfernen?

**Comment by kdr154** [comment]
Schwierig. In 935 stehen Abrufzeichen. Wir haben darüber in der Besprechung bei Ihnen gesprochen. Es betrifft die Frage, ob man Aufsätze, die Rezensionen sind, in irgend einer Form ausfindig machen kann, um für diese dann das Abrufzeichen "uwre" zu vergeben. Das könnte in der Form geschehen, dass man nach Schlüsselbegriffen sucht, z. B. "review", oder dass man auf Rubriken/Sektionen trifft wie z. B. "Buchbesprechungen". Wenn ich mich richtig erinnere, haben wir uns darauf geeinigt, die Frage erst einmal zurückzustellen und sie gesondert zu untersuchen. 
Das wäre dann in meinen Augen aber auch eine nachgelagerte Sache. Eine Frage wenn..., dann 935 $c generieren mit dem Abrufzeichen uwre. Zudem müsste noch ein Feld 655 generiert werden, das den Link zur entsprechenden PPN des GND-Satzes enthält.
Solange diese Fragen nicht geklärt sind, sollten wir das gesamte Feld 935 komplett entfernen

**Comment by mtrojan-ub** [comment]
OK, dann werden wir es erstmal entfernen. 

Falls wir eines Tages genau definieren können wie das befüllt werden soll, können wir das dann im Rahmen eines neuen Issues bearbeiten. Ich setze dieses auf ready for testing sobald die Änderung aktiv ist.

**Comment by mtrojan-ub** [comment]
so, 935 wurde entfernt, bitte testen!

**Comment by kdr154** [comment]
Gelöst
