### ISSUE TITLE
ISSN 0718-3399 Política criminal 935 mkri

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#572]
935 mkri immer doppelt. Bitte nur einmal

**Comment by kdr154** [comment]
Auch hier Abbruch des Harvesting mir Exitcode 2

**Comment by shadeMe** [comment]
Bitte nochmal versuchen - Er war wegen des Aktualisierung des Harvesters, die ich vor kurzem getätigt habe.

**Comment by kdr154** [comment]
ok
