### ISSUE TITLE
ISSN 1741-3095 Punishment & Society 936 mkri

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#579]
935 mkri immer doppelt. Bitte nur einmal.

**Comment by kdr154** [comment]
Beim Testen Abbruch mit Exitcode 2:
Processing section "Punishment & society".
feed_url: http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=puna&type=etoc&feed=rss


Processing feed URL: http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=puna&type=etoc&feed=rss
http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=puna&type=etoc&feed=rss (RDF):
	Title: SAGE Publications: Punishment & Society: Table of Contents
	Link: 
	Description: Table of Contents for Punishment & Society. List of articles from both the latest and ahead of print issues.


Feed Item: The epistemology of algorithmic risk assessment and the path towards a non-penology penology
set crawl-delay for domain 'journals.sagepub.com' to 1000 ms
sleeping for 1000 ms...

Harvesting URL: https://journals.sagepub.com/doi/abs/10.1177/1462474518802336?ai=2b4&mi=ehikzz&af=R
Augmenting JSON...
post-processed author first name = 'Yoav', last name = 'Mehozay', title = '', affix = ''
post-processed author first name = 'Eran', last name = 'Fisher', title = '', affix = ''
use online ISSN "1741-3095" with online PPN "302467211"
Augmented JSON: { "notes": [  ], "ubtue": { "ssgNumbers": "FG_2,1", "date_normalized": "2019-12-01", "date_raw": "December 1, 2019", "issn_online": "1741-3095", "harvest_url": "https:\/\/journals.sagepub.com\/doi\/abs\/10.1177\/1462474518802336?ai=2b4&mi=ehikzz&af=R", "isil": "DE-2619", "journal_name": "Punishment & society", "comments": [ "normalized date to: 2019-12-01", "changed \"language\" from \"en\" to \"eng\"", "Added author GND number 1120956145 for author Mehozay, Yoav" ], "ppn_online": "302467211", "issn_print": "1462-4745", "ppn_print": "265545161" }, "journalAbbreviation": "Punishment & Society", "issue": "5", "publicationTitle": "Punishment & Society", "DOI": "10.1177\/1462474518802336", "ISSN": "1462-4745", "date": "December 1, 2019", "tags": [ { "tag": "algorithms", "type": 1 }, { "tag": "big data", "type": 1 }, { "tag": "episteme", "type": 1 }, { "tag": "managerial movement", "type": 1 }, { "tag": "penology", "type": 1 }, { "tag": "risk assessments", "type": 1 } ], "title": "The epistemology of algorithmic risk assessment and the path towards a non-penology penology", "libraryCatalog": "SAGE Journals", "accessDate": "2019-11-20T14:41:35Z", "language": "eng", "abstractNote": "Risk assessments are increasingly carried out through algorithmic analysis. In this article, we argue that algorithmic risk assessment cannot be understood merely as a technological advancement that improves the precision of previous methods. Instead, we look at algorithmic risk assessment as a new episteme, a new way of thinking and producing knowledge about the world. More precisely, we argue that the algorithmic episteme assumes a new conception of human nature, which has substantial social and moral ramifications. We seek to unravel the conception of the human that underlies algorithmic ways of knowing, specifically with regard to the type of penology it informs. To do so, we recall the history of criminological knowledge and analytically distinguish algorithmic knowledge from the two previous epistemes that dominated the field – the rational and pathological epistemes. Under the algorithmic episteme, consciousness, reason, and clinical diagnosis are replaced by a performative conception of humanness, which is a-theoretical, predictive, and non-reflexive. We argue that the new conceptualization assumed by the algorithmic episteme leads to a new type of penology which can be described as lacking a humanistic component, bringing Malcolm Feeley and Jonathan Simon’s “new penology” to fruition as a non-penology penology.", "url": "https:\/\/doi.org\/10.1177\/1462474518802336", "volume": "21", "pages": "523-541", "key": "DDBMF543", "itemType": "journalArticle", "version": 0, "creators": [ { "gnd_number": "1120956145", "firstName": "Yoav", "lastName": "Mehozay", "creatorType": "author" }, { "firstName": "Eran", "lastName": "Fisher", "creatorType": "author" } ] }
use online ISSN "1741-3095" with online PPN "302467211"
Harvested 1 record(s) from https://journals.sagepub.com/doi/abs/10.1177/1462474518802336?ai=2b4&mi=ehikzz&af=R of which 1 records were new records.


Feed Item: Affect and authority in immigration detention
sleeping for 1000 ms...

Harvesting URL: https://journals.sagepub.com/doi/abs/10.1177/1462474518803321?ai=2b4&mi=ehikzz&af=R
Augmenting JSON...
post-processed author first name = 'Mary', last name = 'Bosworth', title = '', affix = ''
use online ISSN "1741-3095" with online PPN "302467211"
Augmented JSON: { "notes": [  ], "ubtue": { "ssgNumbers": "FG_2,1", "date_normalized": "2019-12-01", "date_raw": "December 1, 2019", "issn_online": "1741-3095", "harvest_url": "https:\/\/journals.sagepub.com\/doi\/abs\/10.1177\/1462474518803321?ai=2b4&mi=ehikzz&af=R", "isil": "DE-2619", "journal_name": "Punishment & society", "comments": [ "normalized date to: 2019-12-01", "changed \"language\" from \"en\" to \"eng\"" ], "ppn_online": "302467211", "issn_print": "1462-4745", "ppn_print": "265545161" }, "journalAbbreviation": "Punishment & Society", "issue": "5", "publicationTitle": "Punishment & Society", "DOI": "10.1177\/1462474518803321", "ISSN": "1462-4745", "date": "December 1, 2019", "tags": [ { "tag": "affect", "type": 1 }, { "tag": "authority", "type": 1 }, { "tag": "immigration removal centres", "type": 1 }, { "tag": "legitimacy", "type": 1 }, { "tag": "liberalism", "type": 1 }, { "tag": "staff", "type": 1 } ], "title": "Affect and authority in immigration detention", "libraryCatalog": "SAGE Journals", "accessDate": "2019-11-20T14:41:39Z", "language": "eng", "abstractNote": "Drawing on a long-term research project across a number of British Immigration Removal Centres (IRCs), this article considers the relationship between authority and affect. In contrast to much criminological literature on the prison, which advances a liberal political account in which power is constantly negotiated and based on mutual recognition, in detention, this article suggests, staff authority rests on an abrogation of their self rather than engagement with the other. Officers turn away (deny) and switch off (emotionally withdraw) from those before them in order to do their job. In these terms, we bear witness to the affective nature of wielding power at the border. Operating without a clear basis of moral legitimacy, officer testimonies make clear, is painful and corrosive, for staff and for detainees. It may work, in other words, but at what cost?", "url": "https:\/\/doi.org\/10.1177\/1462474518803321", "volume": "21", "pages": "542-559", "key": "W8VN7ZVW", "itemType": "journalArticle", "version": 0, "creators": [ { "firstName": "Mary", "lastName": "Bosworth", "creatorType": "author" } ] }
use online ISSN "1741-3095" with online PPN "302467211"
Harvested 1 record(s) from https://journals.sagepub.com/doi/abs/10.1177/1462474518803321?ai=2b4&mi=ehikzz&af=R of which 1 records were new records.


Feed Item: The return of the suppressed: Exploring how emotional suppression reappears as violence and pain among male and female prisoners
sleeping for 1000 ms...

Harvesting URL: https://journals.sagepub.com/doi/abs/10.1177/1462474518805071?ai=2b4&mi=ehikzz&af=R

**Comment by shadeMe** [comment]
Bitte nochmal versuchen. Sollte jetzt funktionieren.

**Comment by kdr154** [comment]
ok
