### ISSUE TITLE
Ingenta ISSN 2057-4525 Freedom as a 'Way of Seeing' Abstract fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#58]
Auf der Website befindet sich ein Abstract (Marc21 Tag 520): 
https://www.ingentaconnect.com/content/uwp/jrhlc/2018/00000004/00000001/art00002

Wäre schön, wenn dies mitkommen würde

**Comment by mtrojan-ub** [comment]
@shadeMe : Abstract landet nicht in Zotero, bitte Translator prüfen/anpassen

**Comment by shadeMe** [comment]
Gefixt in ubtue/zotero-translators#25.

**Comment by mtrojan-ub** [comment]
bitte nochmal testen

**Comment by kdr154** [comment]
Gelöst
