### ISSUE TITLE
ISSN 1461-7439 Theoretical Criminology Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#585]
Rezensionen werden nicht mit 655 getagt:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield> 
<subfield code="0">(DE-588)</subfield> 
</datafield>
```
Sie stehen in der Sektion Book reviews und der Titel wird mit "Book review:" eingeleitet

**Comment by kdr154** [comment]
Klappt weiterhin nicht. Statt dessen wird ein keyword "Book Review" erzeugt. Dieses bitte löschen

**Comment by kdr154** [comment]
Immer noch dasselbe. Kein 655, dafür 650 mit Book review. 
Ist aber keine Test Zeitschrift.

**Comment by socheres** [comment]
Nach Merge kann getestet werden.

**Comment by kdr154** [comment]
Hier KrimDok#2020-04-07#13BCE6DF8CECE10D4187905AE20D81EC791DB006
gibt es zwar das Sachschlagwort Book Review in 650
![grafik](https://user-images.githubusercontent.com/29707105/78655764-bdb78480-78c6-11ea-874b-49f12a7aceed.png)
aber kein 655.
In der conf ist auch keine Austauschroutine von 650 abgelegt:
![grafik](https://user-images.githubusercontent.com/29707105/78655960-fd7e6c00-78c6-11ea-9aa5-d394e6ba1464.png)

**Comment by socheres** [comment]
Diese Zeitschrift ist nicht mehr in der harvester_config enthalten. In ZEDER auf "zotat" gesetzt.
- [ ] zotero_review_regex    = "^Book Reviews?$"
- [ ] remove_marc_field_650a = "^Book Reviews?$"

**Comment by kdr154** [comment]
gelöst

**Comment by theo-ko** [comment]
> 
> 
> Diese Zeitschrift ist nicht mehr in der harvester_config enthalten. In ZEDER auf "zotat" gesetzt.
> 
>     * [ ]  zotero_review_regex    = "^Book Reviews?$"
> 
>     * [ ]  remove_marc_field_650a = "^Book Reviews?$"

@socheres Wenn ich auf Nu Try-rss bei dieser Zs durchführe und bei "Additional config" Ihre genannten Angaben eingebe, wird das überflüssige Schlagwort in 650 entfernt. Kann ich dann auch davon ausgehen, dass Sie es in der "live" config-Datei noch anpassen, sodass es in Zukunft korrekt ausgeführt wird?

**Comment by socheres** [comment]
@koch Danke. Die Infos sind nun ergänzt. @kdr Da der Issue geschlossen war, habe ich erneut geöffnet. Noch folgendes zu prüfen:

- [ ] prüfen auf zota-Eignung
- [ ] wenn geeignet, Zss. auf "zota" in ZEDEr setzen

**Comment by kdr154** [comment]
Immer noch 650 Book review. Etwa hier:
KrimDok#2020-05-18#60F3F8244DABF649B054A7BAFD0BE1B6FD8D1EAA

**Comment by theo-ko** [comment]
Es besteht noch ein Problem mit Initialien, siehe #963 und der allgemeinen Frage bzgl 1505 $erda, siehe #962 
Erst nach dieser Klärung, könnte die Zs auf zota gesetzt werden.

**Comment by kdr154** [comment]
Im Hinblick auf die Rezensionen muss die Ergänzung in der conf nicht Book reviews heißen sondern Book review ohne s. So ist die Bezeichnung auf den Seiten von Sage.  Also:
* [ ]  zotero_review_regex    = "^Book Review?$"

* [ ]  remove_marc_field_650a = "^Book Review?$"

Sonst greift der Ausdruck nicht.

**Comment by socheres** [comment]
@mtrojan-ub kannst du dir bitte das mit dem Regex näher anschauen. Dass der Regex `/^Book Reviews?/` die Strings "Book review" oder "Book Review" mit abgedeckt,  ist verständlich, aber mit dem end matches $ `/^Book Review?$/` müsste der Harvester den Artikel nicht als Rezension ausgeben, wird aber trotzdem gemacht. 
![image](https://user-images.githubusercontent.com/1545743/82300986-e64b9780-99b7-11ea-878d-d75d9764028a.png)

**Comment by mtrojan-ub** [comment]
Da der short_title "Book review" und nicht "Book Review" ist, liegt es wahrscheinlich an der Groß/Kleinschreibung.

**Comment by kdr154** [comment]
650 Book review wird nicht mehr vergeben. Dieser Punkt ist gelöst.

**Comment by socheres** [comment]
@mtrojan-ub ich habe oben ein "s" vergessen. Ich meine mit `/^Book Reviews?$/ ` werden die Artikel trotzdem als Rezensionen erkannt. So auch in [harvester_config](https://github.com/ubtue/zotero-enhancement-maps/blob/0d7353a2fe48464658aa6be71d543c87acefd216/zotero_harvester.conf#L259).

**Comment by mtrojan-ub** [comment]
> ... müsste der Harvester den Artikel nicht als Rezension ausgeben, wird aber trotzdem gemacht.

Aktuell ist Folgendes konfiguriert:
- `remove_marc_field_650a = "^Book Reviews?$"`
- `zotero_review_regex    = "^Book Reviews?$"`

zotero_review_regex wird auf verschiedene Felder angewendet, siehe
https://github.com/ubtue/ub_tools/blob/21d7d4942b978ef1fe8414e6aab072a70f42b338/cpp/lib/src/ZoteroHarvesterConversion.cc#L645

- title (hier "Book review: Jeffrey Lane, The Digital Street")
- short title (hier "Book review")
- abstract note (hier nicht vorhanden)
- keywords (hier "Book Review")

Es passiert also Folgendes:
- zotero_review_regex wendet den Regex `^Book Reviews?$` an und findet einen Treffer im Keyword "Book Review", somit wird der Datensatz als 655 Rezension gekennzeichnet
- Danach wird das Keyword 650 "Book Review" entfernt

**Comment by socheres** [comment]
@mtrojan-ub wenn der Regex `^Book Reviews?$ `case sensitive ist, dann ist es nicht besser `^Book (R|r)eviews?$ ` bzw. noch besser "$" wegzulassen?  `^Book (R|r)eviews?`

**Comment by mtrojan-ub** [comment]
Ja klar kann man `(R|r)` verwenden wenn man beide Groß/Kleinschreibungen erlauben möchte. Das `$` weglassen hängt eben davon ab ob die Titel/Keywords etc. eben an dieser Stelle für einen Treffer zwingend enden sollen oder nicht

**Comment by kdr154** [comment]
Ausgabedatei leer mit folgender Fehlermeldung von nu:

Zotero Logger initialized!



Queued journal 'Theoretical criminology : an international journal' | DIRECT @ https://journals.sagepub.com/toc/tcra/24/2
set download-delay for domain 'journals.sagepub.com' to 1000 ms


Harvesting URL 1 [Theoretical criminol...] | https://journals.sagepub.com/toc/tcra/24/2 {17416198408114639619}
multiple articles found => trying to harvest children


Item 1 [Theoretical criminol...] | https://journals.sagepub.com/toc/tcra/24/2 {17416198408114639619} download failed! error: translation server returned an invalid multiple-match response! (response code = 500)

**Comment by jriedl** [comment]
Der Abruf über RSS (nicht DIRECT) liefert Ergebnisse zurück.

**Comment by socheres** [comment]
@kdr154 bitte testen

**Comment by kdr154** [comment]
Bei dieser Ausgabe: https://journals.sagepub.com/toc/tcra/24/3
Wird der Artikel Book Review https://journals.sagepub.com/doi/full/10.1177/1362480620930023
korrekt getagt.
Beim Review Essay: https://journals.sagepub.com/doi/full/10.1177/1362480620930028
fehlt die 655 jedoch.

![grafik](https://user-images.githubusercontent.com/29707105/90863362-30fdf680-e38f-11ea-8691-8ec529ef41d9.png)

**Comment by socheres** [comment]
Converting item 10 [Theoretical criminol...] | https://journals.sagepub.com/doi/abs/10.1177/1362480620930028?ai=2b4&mi=ehikzz&af=R {687477387244066078}
use online ISSN "1461-7439" with online PPN "320645681"
post-processed author first name = 'Rod', last name = 'Earle', title = '', affix = ''
title matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1177/1362480620930028,
	item_type: review,
	title: Review essay: ‘They think it’s all over. . .’,
	short_title: Review essay,
	publication_title: Theoretical criminology : an international journal,
	volume: 24,
	issue: 3,
	pages: 543-548,
	date: 2020-06-10,
	doi: 10.1177/1362480620930028,
	language: eng,
	issn: 1461-7439,
	superior_ppn: 320645681,
	superior_type: 2,
	ssg: 4,
	creators: [
		{
			first_name: Rod,
			last_name: Earle,
			type: author,
		},
	],
}
Generated record with hash 'A4E15CFEE68FF320976678B93ADB46AE8E212011'
Mit Try RSS getestet.
Conversion complete


Generated 1 record(s) for item 10 [Theoretical criminol...] | https://journals.sagepub.com/doi/abs/10.1177/1362480620930028?ai=2b4&mi=ehikzz&af=R {687477387244066078}
