### ISSUE TITLE
Ingenta ISSN 2057-4525 Freedom as a 'Way of Seeing' DOI fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#59]
DOI (Marc21 Tag 024) kommt nicht mit:
https://www.ingentaconnect.com/content/uwp/jrhlc/2018/00000004/00000001/art00002

**Comment by shadeMe** [comment]
Gefixt im ubtue/zotero-translators#25.

**Comment by mtrojan-ub** [comment]
bitte nochmal testen

**Comment by kdr154** [comment]
Gelöst
