### ISSUE TITLE
ISSN 2163-3088 Journal of Law and Religion leader 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#592]
im Leader muss nab (Sammelwerk) stehen, nicht naa (Monographie)

**Comment by shadeMe** [comment]
Das scheint bei den Artikeln der Fall zu sein, die als Rezensionen getagt werden. Der Harvester nimmt an, dass alle Rezensionen Monographien sind (ist so seit einem Jahr). Ist diese Annahme dann falsch? Handelt es sich hier um nur diese Zeitschrift oder um all Zeitschriften?

**Comment by kdr154** [comment]
Tatsächlich ist dies auch bei anderen Zeitschriften der Fall. Ich nehme an bei allen, wenn der Harvester so eingestellt ist. Die Annahme ist dann falsch, wenn es sich bei dem übergeordneten Werk um eine Zeitschrift handelt. Bei unseren Daten ist dies im Augenblick immer der Fall. 
Anders ist das, wenn es sich bei dem übergeordneten Werk um eine Monographie handelt. Dann ist das a an der 3. Stelle richtig. In den getesteten Daten ist das nicht der Fall. Im Prinzip ist dies aber, später, auch mal denkbar. Vielleicht war das auch bei den SSOAR Daten so?
In unseren Daten muss aber, unabhängig davon, ob es sich um eine Rezension oder um einen normalen Aufsatz handelt, an der 3. Stelle immer das b stehen.

**Comment by kdr154** [comment]
ok, Default Lieferweg freigeben
