### ISSUE TITLE
ISSN 2159-6808 Journal of Religion and Violence Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#593]
Rezensionen werden nicht mit 655 getagt.
Sie stehen in der Sektion Book Reviews

**Comment by shadeMe** [comment]
Auf die Information über die Sektion eines Artikels kann der Translator leider nicht zugreifen. Es gibt auch kein besonderes Muster bei Rezensionen, das wir erkennen könnten. Ein Autor-Name steht zwar in mehreren Titeln aber das ist auch nicht möglich, zu erkennen. Von daher müssen die Rezensionen dieser Zeitschrift händisch getagt werden.

Heißt das, diese Zss für das vollautomatische Verfahren nicht geeignet ist? Sie ist gerade für das Test-Verfahren vorgesehen.

**Comment by kdr154** [comment]
Im Grunde genommen ist sie nicht geeignet.

**Comment by kdr154** [comment]
Das funktioniert weiterhin nicht. Damit bleibt es bei dem Status nicht geeignet, es sei denn, man nimmt den Aufwand in Kauf, bei dieser Zeitschrift jede neue Einspielung komplett zu überprüfen und die entsprechenden Sätze zu ergänzen.

**Comment by shadeMe** [comment]
Ach so, Entschuldigung, ich hab gedacht, dass ich die Zeitschrift aus der Konfig gelöscht hatte. Ich lösche sie jetzt. 

Dieses Issue können wir schließen.

**Comment by socheres** [comment]
@shadeMe ein Workaround wie das funktionieren könnte. [Hier](https://github.com/ubtue/zotero-translators/blob/master/ubtue_Philosophy%20Documentation%20Center.js) der UB-Translator. Allerdings tut der item.tags.push nicht nicht. Zumindest der Multidownload ist angepasst. 

```
function detectWeb(doc, url) {
  // TODO: adjust the logic here
  if (url.includes('/jrv/')) {
    return "JournalArticle";
  } else
  if (url.includes('/collection-anonymous/')) {
    return "multiple";
  }
  return false;
}

function getSearchResults(doc) {
	var items = {};
	var found = false;
	var rows = ZU.xpath(doc, '//*[contains(concat( " ", @class, " " ), concat( " ", "purchase", " " ))]')
	for (let i=0; i<rows.length; i++) {
		let href = rows[i].href;
		let title = ZU.trimInternal(rows[i].textContent);
		if (!href || !title) continue;
		found = true;
		items[href] = title;
	}
	return found ? items : false;
}

function doWeb(doc, url) {
  if (detectWeb(doc, url) == "multiple") {
    Zotero.selectItems(getSearchResults(doc, false), function (items) {
      if (items) ZU.processDocuments(Object.keys(items), scrape);
    });
  } else
  {
    scrape(doc, url);
  }
}

function postProcess(doc, item) {
	
	let reviwTag = ZU.xpath(doc, '//*[contains(concat( " ", @class, " " ), concat( " ", "rl_category", " " ))]');
    if (reviewTag && reviewTag.length) {
        for (let val in reviewTag) {
            let node = reviewTag[val];
		if (node.textContent.trim().match(/Book Reviews/)) {
			item.tags.push('Book Review');
        	break;
			}
		}
    }
		item.complete();
}

function scrape(doc) {
	var translator = Zotero.loadTranslator("web");
	translator.setTranslator("951c027d-74ac-47d4-a107-9c3069ab7b48");
	translator.setDocument(doc);
	translator.setHandler("itemDone", function (t, i) {
		i.itemType = "journalArticle";
		postProcess(doc, i);
		i.complete();	
	});
	translator.translate();
}
```

**Comment by socheres** [comment]
- [x] Multiple-Download in Zotkat
Falls Rezensionen "Reviews" mit aufgenommen werden soll, dann bitte in Zotero Dokumenttyp in "MagazineArticle" ändern.

**Comment by kdr154** [comment]
Danke, das ist ein wichtiger Hinweis, der die Bearbeitung sehr erleichtert!

**Comment by socheres** [comment]
@kdr154 bitte nochmal testen. Bitte noch Beispiel-URL angeben.

**Comment by kdr154** [comment]
Scheint mir nicht mehr auf nu zu sein.
Beispiel-URL https://www.pdcnet.org/collection-anonymous/browse?fp=jrv&fq=jrv%2FVolume%2F8995%7C5%2F8997%7CIssue%3A%203%2F
Homepage https://www.pdcnet.org/jrv/Journal-of-Religion-and-Violence

**Comment by socheres** [comment]
Rezensionen nicht automatisch erkennbar, daher ungeeignet für Zotaut-Verfahren. Ich schließe.
