### ISSUE TITLE
ISSN 1743-1719 Political Theology Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#594]
Rezensionen werden nicht mit 655 getagt. Statt dessen erhalten sie in 650 das Schlagwort Book Reviews. Dieses entfernen
Etwa hier: https://www.tandfonline.com/doi/full/10.1080/1462317X.2019.1688225

**Comment by shadeMe** [comment]
@kdr154 Kannst du bitte die "ready for testing" issue nochmal testen?

**Comment by kdr154** [comment]
ok, Default-Lieferweg freischalten
