### ISSUE TITLE
ISSN 2629-8619  FUGE - Journal für Religion & Moderne Brill-Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#596]
Besteht die Möglichkeit den Brill-Translator so anzupassen, dass er auch bei dieser Zeitschrift funktioniert:
https://brill.com/view/serial/FUGE
Die Zoteroerweiterung kennt in diesem Fall den neuen Brill-Translator nicht, sondern nimmt statt dessen Embedded Metadata.
In diesem Fall fehlt die ISSN sowie die Bandangabe

**Comment by socheres** [comment]
Hier handelt es sich um einen Sammelband (ISBN), daher ist die Anpassung nicht möglich. @kdr bitte den Issue schließen.

**Comment by kdr154** [comment]
ok
