### ISSUE TITLE
ISSN 1743-1719 Political Theology Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#597]
Das Heft, welches im aktuellen Suchlauf geharvestet wird, besitzt keine Rezensionen, andere, z.B. 20.2019,6 schon. 
Deshalb kann man die Zeitschrift mit den aktuellen Daten nur unter Vorbehalt für das automatische Verfahren freischalten.
Es sei denn, man löst Folgendes:
Die aktuellen Daten beinhalten aber auch die Latest Articles.
Und hier ist zu erkennen, dass die Rezensionen nicht mit 655 getagt sind. Es fehlt bei diesen Artikeln demnach:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield> 
<subfield code="0">(DE-588)</subfield> 
<subfield code="2">gnd-content</subfield> 
</datafield>
```
Auf der anderen Seite wird das Schlagwort Book Reviews in Tag 650 vergeben. Dieses kann dann entfallen. Sonst müsste ein weiteres Tag 655 erzeugt werden. Wie im übrigen auch für das Formschlagwort Peer reviewed

**Comment by shadeMe** [comment]
Bei Latest Articles besteht das Problem darin, dass der Translator Rezensionen nur dann erkennt, wenn die Sektion "Book Review" heißt. Sonst steht auf der Seite jeweiliges Artikels keine eindeutige Angabe, die darauf hinweiss. Wie wollen wir hier weitermachen?

Das Schlagwort "Book Reviews" wird immer entfallen bei der Umsetzung in MARC-XML. In welchem Artikel kommt "Peer reviewed" vor?

**Comment by kdr154** [comment]
Ich schlage vor, wie verschieben die Sache mit Peer reviewed als Schlagwort bis zur nächsten Lieferung, da eine Suche jetzt nach einem entsprechenden Artikel zu aufwändig ist. Es sei denn, man könnte das als eine globale Routine einbauen.
Auf die Sache mit den Rezensionen in dieser Zeitschrift muss man ebenfalls in Zukunft achten.
Deshalb gibt bei dieser Zeitschrift nichts mehr zu tun und sie sollte mit geliefert werden
