### ISSUE TITLE
ISSN 1467-9418 Reviews in Religion & Theology Rezensionen 2

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#599]
Bei dem Artikel Books Reviewed: https://onlinelibrary.wiley.com/doi/10.1111/rirt.13639
handelt es sich ebenfalls um eine Rezension. Hier fehlt das Tag 655:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!106186019!</subfield>  GND-PPN für Rezensionen
<subfield code="0">(DE-588)</subfield> Authority record control number (GND)
<subfield code="2">gnd-content</subfield> Quelle 
</datafield>
```

**Comment by shadeMe** [comment]
Laut der Konfiguration müssen diese Datensätze bzw. Issue Information, Books Received, Books Reviewed unterdrückt werden. Aber wegen einem Bug wurden sie trotzdem geharvestet. Soll ich jetzt den Bug beheben oder wollen wir doch die Datensätze behalten?

**Comment by kdr154** [comment]
Die Artikel haben einen sehr begrenzten Inforrmationswert. Ich würde die Datensätze verwerfen, d. h. den Bug beheben.

**Comment by kdr154** [comment]
ok, Default Lieferweg freischalten
