### ISSUE TITLE
SSOAR_RDA

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#6]
Sollen die Titel als RDA-Titel ausgeliefert werden?
Dann 040 $e rda (siehe auch Feld 773!)
Verlagsdaten, Kölner und ImageWare-Daten wurden nicht als RDA-Daten eingespielt!

**Comment by thefass** [comment]
MF: Anfrage ans BSZ, ob RDA oder RAK, am 23.7. per Mail gestellt

**Comment by thefass** [comment]
Antwort BSZ: Lieferung als RAK!
