### ISSUE TITLE
ISSN 2196-6265 Jahrbuch für Christliche Sozialwissenschaften Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#600]
Bei dieser Zeitschrift funktioniert weder der Multi-Wrapper (multi) noch der OJS Translator (single). Kann man da was machen?

**Comment by kdr154** [comment]
Kann keine Verbesserung erkennen. Selbst wenn man durch manuelle Auswahl der Translator Daten nach Zotero bekommt, sind diese so schlecht und rudimentär, dass es sich nicht lohnt.

**Comment by socheres** [comment]
- [x] Multiple-Download

**Comment by IxKo** [comment]
@socheres Bei mir klappt es nicht, muss bei meinen Translator-Ordner erst etwas aktualisiert werden? Kann ich das irgendwie selbständig machen?

**Comment by kdr154** [comment]
Man kann jetzt den Translator ub_Jahrbuchs (kleiner Schreibfehler hier das s) für Christliche Sozialwissenschaften aufrufen. Funktioniert Multi wie Single. Allerdings fehlen in beiden Modi die Seitenzahlen. Sonst sieht es gut aus.

**Comment by socheres** [comment]
Bei mir sind die Seitenzahlen vorhanden. Am Besten Zotero und Translator neustarten und nochmal in Batch exportieren.

**Comment by IxKo** [comment]
Bei mir sind teilweise die kryptishen Seitenzahlen in Zotero vorhanden, aber bei manchen Artikeln ist die Seitenangabe leer, weil auf der Heft-Seite diese Angaben ebenfalls fehlen.

**Comment by kdr154** [comment]
Ist bei mir genauso
kryptisch: 
![grafik](https://user-images.githubusercontent.com/29707105/86219241-35bddf80-bb82-11ea-8406-478fcbb327af.png)

**Comment by socheres** [comment]
nach Pica-Export werden die kryptischen Seitenzahlen automatisch entfernt. Titel ohne Seitenangaben auf der Webseite müssen - falls in PDF vorhanden - manuell nacherfasst werden.

**Comment by kdr154** [comment]
Jetzt kommen gar keine Seitenzahlen mehr und im Singlemodus wird der Artikel als Webseite gespeichert

**Comment by socheres** [comment]
> Jetzt kommen gar keine Seitenzahlen mehr und im Singlemodus wird der Artikel als Webseite gespeichert

Können Sie mir bitte noch den URL mitteilen?

**Comment by socheres** [comment]
Haben Sie übrigens das richtige Translator ausgewählt? Angeboten wird als Default "Multi-Wrapper"

**Comment by socheres** [comment]
bei mir kommen die Seitenangaben mit. @IxKo können Sie auch testen?

**Comment by kdr154** [comment]
Gerade noch einmal mit beiden Translatoren getestet. Keine Seitenzahlen

**Comment by IxKo** [comment]
> 
> 
> bei mir kommen die Seitenangaben mit. @IxKo können Sie auch testen?

Bei mir kommen wie geschrieben die kryptischen Seitenzahlen, die dann im Script/WinIBW "normal" ausgegeben werden.
Habe den Translator ubtue_Jahrbuchs für christliche Sozialwissenschaften im Multi-DL verwendet.
oder sollte ich was anderes testen?

**Comment by IxKo** [comment]
Ich sehe gerade, dass kdr den Band 59 getesetet hat und ich habe Band 60 getestet.
Bei Band 59 habe ich auch keine Seitenangaben.

**Comment by socheres** [comment]
Habe den Translator angepasst. Jetzt müsste Seitenangaben ohne kryptische Zeichen in beiden Bänden im Multi-DW richtig mitkommen. Vor dem Test Translator via AddOn aktualisieren.

**Comment by kdr154** [comment]
In Bd. 59 kommen sie nur beim Multi-Wrapper mit beim Translator Jahrbuch für christliche Sozialwissenschaft nicht. In Band 60 kommt es zum Abbruch dort, wo keine Seitenzahlen vorhanden sind. Bei beiden Translators. Aber bei den anderen Artikeln sind sie bei beiden dabei.

**Comment by socheres** [comment]
haben Sie den Translator über AddOn aktualisiert? @IxKo ist bei Ihnen auch der Fall?

**Comment by kdr154** [comment]
Das hatten Sie doch geschrieben.

**Comment by socheres** [comment]
@mtrojan-ub in Scaffold sind die Seitenangaben alle vorhanden, aber mit Zotero-Client nicht. Vielleicht liegt es an `"priority": 80,
	"inRepository": false,`?

**Comment by IxKo** [comment]
Bei Band 59 kommen die Seiten bei mir im Multi-DL mit dem Translator Jahrbuch... mit.
Bei Band 60 bricht der Vorgang ab, bei allen Translators (OJS; Equinox und Jahrbuch für christl. Sozi.wiss.)

**Comment by mtrojan-ub** [comment]
Ich kann die Ursache noch nicht lokalisieren aber der Translator wird mir im Browser bei dieser Seite nicht zur Auswahl angeboten. Der target regex könnte zwar noch verbessert werden, aber das ist nicht der Grund warum es nicht funktioniert.

`^https?://(www)?\\.uni-muenster\\.de/Ejournals/index\\.php/jcsw`
=>
`^https?://(www\\.)?uni-muenster\\.de/Ejournals/index\\.php/jcsw`

**Comment by socheres** [comment]
@kdr154 bitte hier nochmal testen.

**Comment by kdr154** [comment]
Jetzt wird mir der Multi-Wrapper nicht mehr angeboten. Ich nehme den Jahrbuch für christliche Sozialwissenschaft, denn Default ist jetzt EquinoxPub. 
Die Seitenzahlen sind im Multi-DL da, aber er bricht immer noch dort ab, wo es keine Seitenzahl gibt. Konkret in Band 60 beim Artikel "Public service ..."
![grafik](https://user-images.githubusercontent.com/29707105/86364166-173a1000-bc78-11ea-896b-bb9dfb0ac34c.png)

**Comment by socheres** [comment]
Habe den Fehler behoben. Bitte nochmal testen.

**Comment by socheres** [comment]
Muss noch eine Kleinigkeit ändern. Bitte noch nicht testen

**Comment by kdr154** [comment]
Jetzt läuft er durch, aber ich habe wieder keine Seitenzahlen, weder bei Ausgabe 59 noch bei 60.

**Comment by socheres** [comment]
jetzt müsste es bei beiden Bänden 59, 60 klappen. Bitte nochmal testen.

**Comment by kdr154** [comment]
Ja jetzt klappt es!  Dann schließe ich.

**Comment by IxKo** [comment]
Ich habe gerade mit Band 55 (https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/JCSW55) getestet und bei mir kommt das Jahr und die Seitenzahlen nicht mit.

**Comment by kdr154** [comment]
Hallo Andrea,

 

Du hast recht. Ich weiß nicht, was die da machen. Passen die den Translator Heft für Heft an? Bitte gleich wieder ein Issue aufmachen. Bezug nehmen auf das alte Issue und erwähnen, dass es bei mir ebenso ist. Auch nach einem Update der Translator im Browser Add-on und in Zotero.

 

Viele Grüße

Klaus

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: A. Ko. <notifications@github.com> 
Gesendet: Dienstag, 7. Juli 2020 09:38
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; State change <state_change@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2196-6265 Jahrbuch für Christliche Sozialwissenschaften Translator (#600)

 

Ich habe gerade mit Band 55 (https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/JCSW55) getestet und bei mir kommt das Jahr und die Seitenzahlen nicht mit.

**Comment by kdr154** [comment]
Beim Band 60 ist nämlich alles dabei.

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: A. Ko. <notifications@github.com> 
Gesendet: Dienstag, 7. Juli 2020 09:38
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; State change <state_change@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 2196-6265 Jahrbuch für Christliche Sozialwissenschaften Translator (#600)

 

Ich habe gerade mit Band 55 (https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/JCSW55) getestet und bei mir kommt das Jahr und die Seitenzahlen nicht mit.

**Comment by socheres** [comment]
Band 55 hat andere Struktur und dort fehlt auch noch das Datum auf der Webseite.

**Comment by kdr154** [comment]
Das stimmt, aber Ausgabe Bd 55(2014) steht auf den Seiten der einzelnen Aufsätze. Eine Jahreszahl für das Feld Datum in Zotero hätte man. 
Schade nur, da wir vorhatten, alle Bände bis Band 1 zu erfassen. In diesem Fall müsste man erst einmal detailliert sichten.

**Comment by socheres** [comment]
- [x] Führende Nullen entfernen
- [x] Berichtsjahr als Datum

@kdr154 @IxKo bitte nochmal testen.

**Comment by IxKo** [comment]
Jahr und Seitenzahlen sind nun vorhanden.
Keywords und ABstracts fehlen.

**Comment by kdr154** [comment]
Führende Nullen weiter vorhanden
Abgegriffen wird das Publikationsjahr und nicht das Berichtsjahr. Das Berichtsjahr sollte Vorrang haben.
https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/JCSW42
https://www.uni-muenster.de/Ejournals/index.php/jcsw/article/view/227

Darüber hinaus gibt es wie hier zu sehen, wieder das Problem mit den Ordenskürzeln, die als Nachname interpretiert werden.

Die Webseite des Aufsatzes:

![grafik](https://user-images.githubusercontent.com/29707105/86770043-60130f80-c050-11ea-9ae9-02363fa2e5a6.png)

Ansicht in Zotero:


![grafik](https://user-images.githubusercontent.com/29707105/86770100-74efa300-c050-11ea-9d80-de07a368b8a7.png)

Ausschnitt vom Inhaltsverzeichnis des Heftes: 

![grafik](https://user-images.githubusercontent.com/29707105/86770168-8df85400-c050-11ea-92d2-f1001c508905.png)

Konnte gerade mit @thefass sprechen. Es ist ihm ein Anliegen, dass wir die Zeitschrift komplett erfassen.

**Comment by kdr154** [comment]
Kommando zurück. Hatte nicht aktualisiert. Alles gut jetzt bis auf die Sache mit dem Ordenskürzel.

**Comment by socheres** [comment]
das mit dem Ordenskürzel kann nicht global behoben werden, bitte manuell korrigieren.

**Comment by socheres** [comment]
> Jahr und Seitenzahlen sind nun vorhanden.
> Keywords und Abstracts fehlen.

@IxKo in welchem Band fehlen die Keywords und Abstract?

**Comment by kdr154** [comment]
In Ordnung.

**Comment by IxKo** [comment]
> 
> @IxKo in welchem Band fehlen die Keywords und Abstract?

Beispielsweise in Band 55 (2014) bei diesem Artikel: https://www.uni-muenster.de/Ejournals/index.php/jcsw/article/view/1281

**Comment by kdr154** [comment]
Aber die Schlagworte fehlen auch in bei dem von mir getesteten Heft https://www.uni-muenster.de/Ejournals/index.php/jcsw/issue/view/JCSW42

![grafik](https://user-images.githubusercontent.com/29707105/86772281-fc8ae100-c053-11ea-9dc4-676ba13f720c.png)

![grafik](https://user-images.githubusercontent.com/29707105/86772319-0e6c8400-c054-11ea-8972-a5dece5d3754.png)

Theoretisch wäre auch ein Abstract denkbar. Aber da scheint mir die Seitenstruktur von Bd. 55 und Bd. 42 gleich zu sein. So dass sich das eine mit dem anderen erledigt. Sowohl beim Schlagwort als auch beim Abstract.

**Comment by socheres** [comment]
@kdr154 @IxKo Habe den Translator nochmal angepasst (Keywords, Abstract). Bitte ausgiebig testen.

**Comment by IxKo** [comment]
Abstracts und Keywords sind nun da

**Comment by kdr154** [comment]
Bei mir die Keywords auch.
