### ISSUE TITLE
Allgemein: Rezensionen (Feld 1131)

### ISSUE THREAD

**Issue by theo-ko** [ubtue/DatenProbleme#601]
**Ausführliche Problembeschreibung**
Momentan werden Rezensionen von uns noch falsch geliefert:
```
<datafield tag="655" ind1=" " ind2="7">
	<subfield code="a">!106186019!</subfield>
	<subfield code="0">(DE-588)</subfield>
	<subfield code="2">gnd-content</subfield>
</datafield>
```
In den Testdaten enstand daraus das in Pica:

> 5520 |s|!106186019! ; (DE-588) ; gnd-content

**Und so sollte es laut Befehl s marcxml in der WinIBW bei einer Rezension aussehen:**
```
<datafield tag="655" ind1=" " ind2="7">
	<subfield code="a">Rezension</subfield>
	<subfield code="0">(DE-588)4049712-4</subfield>
	<subfield code="0">(DE-627)106186019</subfield>
	<subfield code="0">(DE-576)209083166</subfield>
	<subfield code="2">gnd-content</subfield>
</datafield> 
```
Was dann hoffentlich in Pica zu diesem Ergebnis führt:

> 1131 !106186019!Rezension ; ID: gnd/4049712-4

**Comment by ruschein** [comment]
Zu beachten: DE-567 sind die alten BSZ-PPNs.  Vermutlich sollten wir das nicht ausliefern!

**Comment by theo-ko** [comment]
> Zu beachten: DE-567 sind die alten BSZ-PPNs.  Vermutlich sollten wir das nicht ausliefern!

Ich stimme zu. Die alte SWB-PPN (DE-576) steht im Pica-Feld 798 bei der K10plus PPN (DE-627). Demnach ist die Angabe wahrscheinlich redundant und nicht nötig.

**Comment by shadeMe** [comment]
@theo-ko Bitte nochmal testen.

**Comment by theo-ko** [comment]
Das Feld 655 wird nun richtig ausgegeben, sofern der Artikel als Rezension erkannt wird.
