### ISSUE TITLE
ISSN 2284-7308 Perichoresis Sciendo Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#603]
Bei dieser Zeitschrift erfasst der Translator die Webseite des Heftes und nicht die einzelnen Aufsätze. Bei den einzelnen Aufsätze erscheint dann in der Zoteroerweiterung das Ordnersymbol für den Multidownload. (Folgerichtig)? bekommt man bei Versuch die Daten zu übertragen eine Fehlermeldung. Bei allen anderen Methoden, Sciendo Translator über Rechtsklick, Embedded Metadata über Rechtsklick, Doi und Zauberstab , fehlen das Abstract (bei Sciendo und Embedded Metdata, bei Doi und Zauberstab muss es aufwändig korrigiert werden) und die Keywords.

https://content.sciendo.com/view/journals/perc/16/1/perc.16.issue-1.xml

**Comment by socheres** [comment]
to do:
- [ ] Translator angepasst
- [ ] Multidownload
- [ ] Änderung ZEDER Spalte bildi

**Comment by socheres** [comment]
@thefass @kdr154 diese Zeitschrift und alle anderen theologischen Zeitschriften auf der [Scielo-Plattform](https://content.sciendo.com/browse?subSite=sciendo&t=TL&type_2=journal&type_4=book) können im Zotkat-Batchverfahren katalogisiert werden. Daher sollte IxTheo die Zeitschrift übernehmen.

**Comment by kdr154** [comment]
Beim Multidownload mit dem Sciendo Translator ist jetzt alles da, bis auf die Keyword. Darüber hinaus wird die Zeitschrift als Ganzes in den Download integriert. Diesen Eintrag muss man aus der Liste entfernen, sonst bekommt man einen Fehler und der gesamte Download schlägt fehl.
Eine andere Zeitschrift, die auf Sciendo gehostet wird, hat aber noch große Probleme gemacht.

**Comment by socheres** [comment]
- [x] Keywords
- [x] Multiple

**Comment by IxKo** [comment]
Funktioniert, es muss bei der Auswahl nach Zotero der Eintrag "Perichoresis" abgewählt werden, sonst passiert nichts.

**Comment by IxKo** [comment]
Nachtrag: Die Abstracts kommen leider mit Html-Tags (<section class="abstract"><h2 class="abstractTitle text-title my-1" id="d895e2">Abstract</h2><p>) in Zotero
