### ISSUE TITLE
Allgemein: mehrere Autor:innen Verantwortlichkeitsangabe $h in Pica 4000

### ISSUE THREAD

**Issue by theo-ko** [ubtue/DatenProbleme#604]
Bei Artikeln, die von mehreren Autor:innen verfasst wurden, wird nur der erste in der Verantwortlichkeitsangabe im Feld 4000 $h übernommen.

Könnte man alle Verfasser:innen dort übertragen?

Beispiel:
Pica
`4000 Teologia Sacramentaria$hPierpaolo Caspani, Tommaso Castiglioni, Marco Paleari`

MARC
`245 10$aTeologia Sacramentaria$cPierpaolo Caspani, Tommaso Castiglioni, Marco Paleari`

MARCXML
`<datafield tag="245" ind1="1" ind2="0"><subfield code="a">Teologia Sacramentaria</subfield><subfield code="c">Pierpaolo Caspani, Tommaso Castiglioni, Marco Paleari</subfield></datafield>`

**Comment by socheres** [comment]
Aufsätze werden nun ohne $h erfasst.
