### ISSUE TITLE
ISSN 1827-790X Rivista di Storia della Chiesa in Italia Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#605]
Kann man für diese ZS einen Translator schreiben? Bei der Übernahme der Daten mittels DOI fehlen die Keywords, das Abstract und die Sprache.
Bsp. für einen Artikel: https://www.vitaepensiero.it/scheda-articolo_digital/antonella-deglinnocenti/un-frammento-inedito-della-vita-s-iohannis-gualberti-di-gregorio-di-passignano-bhl-4400-001783_2018_0002_0343-369506.html
für ein Heft: https://www.vitaepensiero.it/scheda-fascicolo_contenitore_digital/autori-vari/rivista-di-storia-della-chiesa-in-italia-2018-2-001783_2018_0002-369505.html

**Comment by socheres** [comment]
die letzt verfügbare Aufsatzdaten sind vom 2018. Neuer Translator für diese Zss. lohnt sich nicht. @kdr154 bitte Issue schließen.

**Comment by kdr154** [comment]
gemacht
