### ISSUE TITLE
ISSN 0040-568X Theologische Revue OJS-Translator

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#607]
Wieder die Bitte, eine ZS in das automatische Verfahren aufzunehmen:
Zeder ID 1156
http://www.theologische-revue.de/
und sie einstweilen halbautomatisch zu erfassen.
Es handelt sich wiederum um OJS-Zeitschrift, aber leider klappt die Datenübernahme überhaupt nicht.
Weder multi, noch single und auch nicht über DOI und Zauberstab

**Comment by mtrojan-ub** [comment]
Auf der Seite gibt es einen RSS-Feed:
https://www.uni-muenster.de/Ejournals/index.php/thrv/gateway/plugin/WebFeedGatewayPlugin/rss2

Habe ihn mal fürs Testing auf nu freigeschaltet, sieht auf den ersten Blick recht brauchbar aus. Welche Felder sind denn konkret falsch?

**Comment by kdr154** [comment]
halbautomatisch kann lediglich ein Snapshot gespeichert werden. Ein Translator wird nicht angeboten.
nu teste ich gleich.

**Comment by kdr154** [comment]
Beim nu bestehen die Probleme darin, dass keine Seitenzählung existiert und dass die Heftzählung nicht nummerisch erfolgt, sondern über die Angabe des Monats, in der die Hefte erscheinene (bisher Januar, Februar). Vermute, soll so weitergeführt werden.
Sonst sehen die Daten gut aus.

**Comment by socheres** [comment]
Bis der Translator angepasst wird, Zotkat-Verfahren über[ RSS-Feed](https://www.uni-muenster.de/Ejournals/index.php/thrv/gateway/plugin/WebFeedGatewayPlugin/atom) anwenden. @shadeMe Weder mit ZU.xpath noch doc.querySelectorAll können Metadaten erkannt werden.

**Comment by socheres** [comment]
- [x] Neuer Translator "Theologische Revue"
- [x] Multiple-Download für Zotkat
- [x] Artikel als Rezensionen "magazineArticle" erkannt
@kdr154 @theo-ko bitte ausführlich testen.
- [ ] Verbesserungsvorschläge

**Comment by theo-ko** [comment]
Ich kann nur Snapshots speichern, wenn ich das Add-On benutze.

Außerdem:
Versuche ich die Artikel durch Anlegen des RSS-Feeds in Zotero zu speichern, erhalte ich eine Fehlermeldung, wenn ich in Zotero die vom Feed gefundenen Artikel in meine Bibliothek überführen will: 
![Zotero RSS](https://user-images.githubusercontent.com/57000004/82334658-90431800-99e8-11ea-91dc-b09482d82c7c.PNG)

**Comment by kdr154** [comment]
Bis auf die fehlende Seitenzählung sehen die Daten auf nu nun gut aus. 
Da es keine Heftzählung gibt, sondern statt dessen nach Monaten unterschieden wird (Januar, Februar, März, April) müsste ein $y kreiert werden.
Rezensionen gibt es in der aktuellen Ausgabe keine.

**Comment by socheres** [comment]
> Ich kann nur Snapshots speichern, wenn ich das Add-On benutze.
> 
> Außerdem:
> Versuche ich die Artikel durch Anlegen des RSS-Feeds in Zotero zu speichern, erhalte ich eine Fehlermeldung, wenn ich in Zotero die vom Feed gefundenen Artikel in meine Bibliothek überführen will:
> ![Zotero RSS](https://user-images.githubusercontent.com/57000004/82334658-90431800-99e8-11ea-91dc-b09482d82c7c.PNG)
Bitte diesen Link verwenden: https://www.uni-muenster.de/Ejournals/index.php/thrv/index
statt: http://theologische-revue.de
Wird der Translator "Theologische Revue" nicht angeboten? Zotero Connector aktualisieren und Zotero neustarten.
![image](https://user-images.githubusercontent.com/1545743/82336099-74d90c80-99ea-11ea-8ce0-bbaaea8a7339.png)

**Comment by kdr154** [comment]
Halbautomatisch diesselben Problematik wie auf nu. Allerdings geht nur Single. Wobei man den OJS-Translator manuell auswählen muss. Standardmäßig will das System Equinox verwenden. Dann kommt eine Fehlermeldung dass statt dessen auf den OJS-Translator zurückgegriffen wird.

**Comment by kdr154** [comment]
Nach einem Update wird er angeboten und ein Magazin-Artikel gespeichert. Es sind aber keine Rezensionen.

**Comment by socheres** [comment]
Diese Zeitschrift ist eine reine Rezensionszeitschrift, daher sollen alle als Rezensionen erfasst werden.

**Comment by kdr154** [comment]
Ok, dann stimmt es.

**Comment by theo-ko** [comment]
@kdr154 
> Da es keine Heftzählung gibt, sondern statt dessen nach Monaten unterschieden wird (Januar, Februar, März, April) müsste ein $y kreiert werden.

$y muss nicht belegt werden, der Monat kann im Unterfel $m erfasst werden.
Ich sehe viele Rezensionen.


@socheres 
> Bitte diesen Link verwenden: https://www.uni-muenster.de/Ejournals/index.php/thrv/index
> statt: http://theologische-revue.de
> Wird der Translator "Theologische Revue" nicht angeboten? Zotero Connector aktualisieren und Zotero neustarten.
Mit diesem Link geht es und es wird auch der Translator der Zs angeboten.
Ich glaube aber, es gibt ein Problem mit Zotero und den Magazin-Artikeln. Der DOI wird nicht übernommen.
Wenn ich manuell mal irgendeinen normalen Artikel auf Magazin-Artikel umstelle, erhalte ich auch die Meldung von Zotero, dass DOIs entfernt werden.

**Comment by kdr154** [comment]
Bei mir ist das mit dem  DOI auch so.

**Comment by theo-ko** [comment]
Generell ist beim Übertrag in den K10plus einiges falsch, bzw. bereits beim Kopieren von Zotero ins Skript:

- 0500 sn  -> O fehlt
- DOI fehlt 
- in 4000 wird $d für Zusatztitel erzeugt, obwohl das doch bei allen automatischen Verfahren nicht mehr gesetzt werden soll.
- 4241 Enthalten in -> PPN zur Zs fehlt
- 4261 Rezension vonTheologische Revue -> das ist falsch und dieses Feld sollte überhaupt nicht erzeugt werden
- in 4950 wird zweimal die gleiche URL ausgegeben

**Comment by socheres** [comment]
diese Zeitschrift nehmen wir als ersten Testfall in zotkat auf, falls sie ins Zotaut aufgenommen werden kann. Hier muss der PICA-Translator angepasst werden.

ToDo Zotaut:
- [ ] Rezensionen taggen
- [ ] Unterfel $m erzeugen

**Comment by thefass** [comment]
Achtung: die Zeitschrift ist eine Rezensionszeitschrift. Jedes Heft hat aber auch einen fachlichen Aufsatz, der keine Rezension ist.
Diese hatten wir bisher auch schon immer im IxTheo nachgewiesen:
https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A306590859&type=AllFields&filter%5B%5D=%7Eformat%3A%22Article%22

**Comment by kdr154** [comment]
Der Monat für $m muss erfasst werden.

**Comment by socheres** [comment]
> Achtung: die Zeitschrift ist eine Rezensionszeitschrift. Jedes Heft hat aber auch einen fachlichen Aufsatz, der keine Rezension ist.
> Diese hatten wir bisher auch schon immer im IxTheo nachgewiesen:
> https://ptah.ub.uni-tuebingen.de/Search/Results?lookfor=superior_ppn%3A306590859&type=AllFields&filter%5B%5D=%7Eformat%3A%22Article%22

Ja, das stimmt, dass die sog. "Leitartikel" nicht immer Rezensionen sind.

**Comment by mtrojan-ub** [comment]
Wo genau soll $m in zotaut hinzugefügt werden? 264? 773? 936?

**Comment by IxKo** [comment]
Es müsste in **936** als <subfield code="c">[M]</subfield> 
und in **773** als <subfield code="g">[Jahrgang](]JJJJ]), [MMM]., Seite [x-y]</subfield>

Bei 936 muss der Monat als Zahl geschrieben sein und 
bei 773 muss der Monat als deutsche Kurzform mit Punkt aufgeführt werden (außer März und Mai, die ausgeschrieben ohne Punkt)

**Comment by socheres** [comment]
@mtrojan-ub bei "Leitartikel" soll der Tag "Book Reviews" nicht erzeugt werden. Gibt es hierfür bereits einen Translator für Zotaut? Ich habe einen Translator für Zotkat geschrieben, der aber noch angepasst werden muss. Z.B. "ZU.xpath" bei Leitartikel etc.

**Comment by socheres** [comment]
@mtrojan-ub der Leitartikel wird jetzt nicht mehr als "Book Review" getaggt. Bitte um review. Siehe Testbeispiele https://github.com/socheres/translators/commit/a35dc6c8d4d722adb287c49b193bd5ad4be4a9ab

**Comment by mtrojan-ub** [comment]
siehe Kommentare im Pull Request

**Comment by socheres** [comment]
- [x] New Translator (Leitartikel werden nicht als "Book review" getaggt.
- [x] remove_marc_field_650a & zotero_review_regex 
- [x] Münsteraner um Eingabe der Seitenangaben und Heftnummer gebeten
- [x] Zeitschrift auf "zotat"
- [ ] Seitenangaben und Heftnummer in den Seitenquelltext vorhanden

**Comment by socheres** [comment]
- [x] Monatsnamen in Nummern ändern 
- [x] Erfassung des Monats in Unterfeld $m in Pica gemäß [Erfassungsregel ](https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4070&katalog=Standard#$m) (siehe unten das Beispiel)
- [x] Anpassung von "PicaSWB_batch.js" und "PicaSWBixzs.js"
- [x] in "zot" ändern
- [ ] auf Seitenangaben verzichten "for meeting discussion"
- [ ] testen

> Zur Heftzählung: Wir haben absichtlich in der Online-Ausgabe der ThRv auf die Angabe mit Nummern verzichtet, da es ja noch die gedruckte Ausgabe der ThRv gibt, die bereits in Nummern gezählt wird. Um sich davon abzuheben, wird die Online-Ausgabe mit Monatsnamen ausgezeichnet. Diese Auszeichnung dient der besseren Orientierung, denn gedruckt erscheint die ThRv "nur" sechs Mal jährlich, während die Online-Ausgabe 12 Mal jährlich erscheint. Um also nicht beide Ausgaben miteinander zu verwechseln, die unterschiedliche Zählung. Um es an einem Beispiel zu verdeutlichen: Aus den Online-Ausgaben von Januar und Februar wird dann die gedruckte Nummer "1". Somit ist beides gut unterscheidbar.
Deswegen können, zweitens, auch keine Seitenzählungen vorgenommen werden. Die gedruckte Nummer wird separat von Aschendorff gesetzt, da haben wir keinen Einfluss drauf. Deshalb gibt es de facto auch keine Seitenzählung bei der Online-Nummer: Wir beginnen die Seitenauszeichnung bei jeder Rezension neu, d.h. jede Rezension fängt erneut bei 1 an. Daher gibt es keine fortlaufende Nummerierung für ein ganzes Heft. Und bei Seitenangaben jeweils nur "1 bis 3 oder 4" würde keinen Sinn ergeben, daher verzichten wir auf diese Auszeichnung. (eMail vom 3.07.2020)

```
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1131 !106186019!
1500 ger
1505 $erda
2051 10.17879/thrv-2020-2643
3000 !082664773!$BVerfasserIn$4aut 
8910 $aixzom$bAutor in der Zoterovorlage [Förster, Hans] maschinell zugeordnet
4000 Huebner, Sabine$dPapyri and the Social World of the New Testament
4070 $v116$j2020$m3
4241 Enthalten in!1687426953!
4950 https://www.uni-muenster.de/Ejournals/index.php/thrv/article/view/2643$xH$4LF
5056 1
5520 
E* l01
7100 $Jn
8012 ixzs$aixzo
```

**Comment by thefass** [comment]
>     * Seitenangaben und Heftnummer in den Seitenquelltext vorhanden

Ich finde die Übernahme von Seitebzahlen wichtig. Erstens kann man dann einschätzen wie lang eine Rezension ist und zweitens ist das auch ein Signal, dass die Rezension auch zitiert werden kann (und dann auch in ein Literaturvrwaltungsprogramm aufgenommen werden kann).e
Ein drittes Argument ist, dass die PDFs ja Seitenzahlen haben.
Eine nicht durchgehende Seitenpaginierung ist bei OJS übrigens öfter zu finden, so auch bei o-bib.
Dass die Seitenangaben nicht mit der gedruckten Ausgabe übereinstimmen ist unproblematisch, die Nutzer zitieren bei online Ausgabe ja auch den Link/DOI und dann ist klar, dass die online Ausgabe gemeint ist.

**Comment by socheres** [comment]
die Seitenangaben sind NICHT in den Seitenquelltexten vorhanden! Daher muss sie ggfs. manuell erfasst werden.

**Comment by socheres** [comment]
@thefass es sind noch weitere Zeitschriften davon betroffen z.B. #680 #676 #733 #96 dort fehlen auch die Seitenangaben in PDF.

**Comment by thefass** [comment]
Ok, manuelles Nachtragen sollten wir nicht machen. Bei den OJS Zss in Münster könnte man die Kollegen dort bitten, das auch in OJS einzutragen, dann wäre sie vorhanden

**Comment by socheres** [comment]
siehe Kommentar oben https://github.com/ubtue/DatenProbleme/issues/607#issuecomment-654932377 Die Münsteraner wollen keine Seitenangaben erfassen

> Und bei Seitenangaben jeweils nur "1 bis 3 oder 4" würde keinen Sinn ergeben, daher verzichten wir auf diese Auszeichnung. (eMail vom 3.07.2020)

**Comment by IxTheoKm** [comment]
Es gäe auch die Möglichkeit, die Gesamt_anzahl_ der Seiten in 4070 $t anzugeben, wenn sie aus der Seitenangabe in $p nicht erkennbar bzw. gar nicht vorhanden ist. 
Wenn aber die Anzahl nicht geliefert wird, wäre das auch nur manuell nachzutragen, also wohl nicht angebracht.

**Comment by socheres** [comment]
@IxTheoKm @thefass Gesamtanzahl der Seiten wird nicht geliefert. Da es keine offenen Fragen mehr gibt, bitte @IxKo @kdr154 nach dem Testen Issue schließen.

**Comment by kdr154** [comment]
Bis vor wenigen Minuten war noch alles in Ordnung. Jetzt wird mir kein Translator mehr angeboten.

**Comment by socheres** [comment]
bei mir schon. In diesem Fall am Besten Translators in Zotero Client & Addons nochmal aktualisieren und die Webseite neuladen.
![image](https://user-images.githubusercontent.com/1545743/86904267-ba73a500-c110-11ea-8cc4-8c1d3e251b96.png)

**Comment by socheres** [comment]
@IxKo können Sie bitte auch testen?

**Comment by IxKo** [comment]
Mir wird auch keiner angeboten (weder Multi noch Single), habe überall ein Update gemacht.

Beim Add-on habe ich folgende Fehlermeldung in der Konsole:
![grafik](https://user-images.githubusercontent.com/57000004/86908690-3a047280-c117-11ea-8c06-aa54be741fbf.png)
Ich weiß nicht, ob das relevant ist.

**Comment by socheres** [comment]
Es lag an dem Dateinamen. Im Ordner "zotero_ro" und "zotero_ko" habe ich die Datei "Theologische Revue.js" in "ubtue_Theologische Revue.js" geändert. Bitte nochmal testen.

**Comment by IxKo** [comment]
Mir wird weiterhin kein Translator angeboten.
Nun habe ich folgende Fehler:
![grafik](https://user-images.githubusercontent.com/57000004/86910061-615c3f00-c119-11ea-9b27-1e6eeaf14cd4.png)

**Comment by kdr154** [comment]
Ebenso

**Comment by socheres** [comment]
In einem VC geklärt. Translator wird angeboten und kann getestet werden.

**Comment by kdr154** [comment]
Kann aus meiner Sicht geschlossen werden. $m in 4070 wird im Ixtheo verbal ausgegeben. Bsp. $m5 im IxTheo Mai.
