### ISSUE TITLE
ISSN 2199-4471 Religion in the Roman Empire Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#608]
Es wird immer Deutsch als Sprache ausgegeben, wobei die Artikel immer auf Englisch sind
https://www.mohrsiebeck.com/zeitschrift/religion-in-the-roman-empire-rre

**Comment by kdr154** [comment]
Immer noch so.

**Comment by socheres** [comment]
in solchen Fällen bitte "ISSN_to_language_code.map" ergänzen. z.B. [hier](https://github.com/ubtue/DatenProbleme/issues/676#issuecomment-630599994)

**Comment by kdr154** [comment]
Aber richtig: nicht ger sondern eng muss da drin stehen. Steht jetzt auch so in ISSN_to_language_code.map, doch leider wird weiterhin fälschlicherweise de übertragen

**Comment by socheres** [comment]
Fehler im "PicaSWB_batch.js" bzw. "PicaSWBixzs.js" behoben. Jetzt übernimmt der Translator die Sprache aus ISSN_to_language_code.map

**Comment by kdr154** [comment]
Danke, sieht richtig aus.

**Comment by kdr154** [comment]
Sonst: Erfordert nach Neukonfiguration (siehe Mail @socheres vom 3.6.2020) "ISSN_to_language_code.map" zu ergänzen, oder den Wert in das Zoterofeld Sprache einzutragen, da es keinen Default-Wert mehr gibt.
