### ISSUE TITLE
ISSN 1868-8020 Early Christianity Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#609]
Es wird immer Deutsch als Sprache ausgegeben, wobei die Artikel auf Englisch sind.
https://www.mohrsiebeck.com/zeitschrift/early-christianity-ec

**Comment by kdr154** [comment]
Immer noch so.

**Comment by socheres** [comment]
dito #608

**Comment by IxKo** [comment]
Ist bei mir noch immer der Fall.
Außerdem wird "de" nicht in "ger" umgewandelt beim Import in die WinIBW. Gleiches Problem mit "en" (siehe #999)

**Comment by kdr154** [comment]
Erfordert nach Neukonfiguration (siehe Mail @socheres vom 3.6.2020) "ISSN_to_language_code.map" zu ergänzen, oder den Wert in das Zoterofeld Sprache einzutragen, da es keinen Default-Wert mehr gibt.
