### ISSUE TITLE
Scielo ISSN 0718-9273 The living body and transcendental subjectivity in the phenomenology of Edmund Husserl - Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#61]
Beide Verfasser werden in das Marc21-Tag 700 geschrieben, das Feld für die weiteren Verfasser einer Schrift, statt der 1. in 100 und der 2. (und alle weiteren) in 700
Vgl. #40

**Comment by mtrojan-ub** [comment]
... ist so gewollt, Erklärung siehe #40

**Comment by kdr154** [comment]
Gelöst
