### ISSUE TITLE
ISSN 1868-6788 Jewish Studies Quarterly Sprache 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#610]
Es wird immer Deutsch als Sprache ausgegeben, wobei alle Artikel auf Englisch sind.
https://www.mohrsiebeck.com/zeitschrift/jewish-studies-quarterly-jsq

**Comment by kdr154** [comment]
Immer noch so

**Comment by socheres** [comment]
dito #608 #609

**Comment by IxKo** [comment]
Das Problem besteht weiterhin. Außerdem wird aus dem "de" in Zotero kein "ger" im K10plus gemacht.

**Comment by socheres** [comment]
Sprache beim Download nicht zuverlässig, daher bitte die [Mapping ](https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map) ergänzen. siehe auch
https://github.com/ubtue/DatenProbleme/issues/608#issuecomment-630829376

**Comment by IxKo** [comment]
Nach Hinzufügen in der Mapping-Liste wird nun 1500 eng ausgegeben.

**Comment by kdr154** [comment]
Erfordert nach Neukonfiguration (siehe Mail @socheres vom 3.6.2020) "ISSN_to_language_code.map" zu ergänzen, oder den Wert in das Zoterofeld Sprache einzutragen, da es keinen Default-Wert mehr gibt.
