### ISSUE TITLE
ISSN 2294-1088 Revue d'Histoire Ecclésiastique Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#611]
Sprache fehlerhaft oder gar nicht vorhanden
https://www.brepolsonline.net/toc/rhe/2019/114/3-4

**Comment by socheres** [comment]
Zeitschrift ist mehrsprachig, daher muss weiterhin die Sprache manuell ergänzt werden.
- [ ] Kandidat für Zotaut?

**Comment by socheres** [comment]
@kdr154 @theo-ko bitte überprüfen, ob Zeitschriften von BREPOLS ins Zotaut-Verfahren übernehmen werden kann.

**Comment by kdr154** [comment]
Kandidat? Im Prinzip schon. Die Seiten sind für alle Zeitschriften gleich aufgebaut.

**Comment by theo-ko** [comment]
Laut Zeder gibt es bei vier Zeitschriften eine Bemerkung, dass die Sprache gegegenfalls manuell angepasst werden müsse, was aus meiner Sicht nicht nach Kandidaten für das automatische Verfahren klingt?

**Comment by kdr154** [comment]
Das stimmt, Ist ja auch von @socheres so vermerkt (s. o.).  Warum dann die Frage nach zotaut? Abstract ist oft auch mehrsprachig. Das konnte von der IT gelöst werden, meine ich mich zu erinnern. Abgesehen davon halte ich Brepols für einen Kandidaten und setzte auf die IT.

**Comment by socheres** [comment]
Zur Info: im Zotaut-Verfahren kann die Sprache des Aufsatzes anhand einer Berechnung aus Titel und/oder Abstract automatisch erkannt werden, daher ist eine mehrsprachige Zeitschrift ohne Sprachangabe für die Übernahme ins Zotaut-Verfahren geeignet.

**Comment by theo-ko** [comment]
@kdr154 Einige der Zeitschriften haben jedoch tiefp J (wobei es auch bei anderen Zs im Testverfahren so ist), ist das ein Problem?

**Comment by kdr154** [comment]
Frage an @socheres und @thefass

**Comment by socheres** [comment]
Die Nachverknüpfung der Autoren mit Normdaten bei Zeitschriften "tiefp=J" kann/soll nach der der Einspielung erfolgen und die Benachrichtigung solcher Datensätze können über Alertfunktion in IxTheo eingerichtet werden.

**Comment by socheres** [comment]
für Zotkat dito #608 #609 #610

**Comment by IxKo** [comment]
Sprache fehlt weiterhin beim Zotkat-Verfahren.

**Comment by kdr154** [comment]
Erfordert nach Neukonfiguration (siehe Mail @socheres vom 3.6.2020) "ISSN_to_language_code.map" zu ergänzen, oder den Wert in das Zoterofeld Sprache einzutragen, da es keinen Default-Wert mehr gibt.
