### ISSUE TITLE
ISSN 1461-7404 Social Compass Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#612]
https://journals.sagepub.com/loi/SCP
hier, wie generell bei Sage, wird keine Sprache mitgliefert.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/611#issuecomment-610464904

**Comment by socheres** [comment]
dito #608 #609 #610 #611

**Comment by kdr154** [comment]
#612 vgl. #613

**Comment by socheres** [comment]
besteht das Problem auch im Zotaut-Verfahen?

**Comment by IxKo** [comment]
Bei Try RSS auf Nu wird bei dieser Zs als Sprache eng im Result File ausgegeben.

**Comment by kdr154** [comment]
Gut, aber wenn eine Sage-ZS im zotkat-Verfahren bearbeitet wird, muss die "ISSN_to_language_code.map" ergänzt werden, oder der Wert in das Zoterofeld Sprache eingetragen werden, da es keinen Default-Wert mehr gibt.

**Comment by socheres** [comment]
@kdr154 ggfs. schließen.

**Comment by kdr154** [comment]
Man muss die Sprache manuell eintragen. Hier https://journals.sagepub.com/doi/full/10.1177/0037768620921705 wäre fre vonnöten. Geliefert wird im Single-DL, nur dieser geht ja bei Sage, en.
