### ISSUE TITLE
ISSN 1461-7404 Social Compass Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#613]
Bei dieser Zeitschrift fehlen die Keywords:
https://journals.sagepub.com/doi/full/10.1177/0037768619868418
Möglicherweise ebenfalls ein generelles Problem mit den Daten von Sage

**Comment by socheres** [comment]
Translator
- [ ] Keywords
- [ ] alle Sage Zeitschriften ins Zotaut-Verfahren übernehmen

**Comment by kdr154** [comment]
Keywords sind da. 
Z. Zt. haben wir die Zeitschriften im Testverfahren auf "zotat" gesetzt
Sind alle Sage Zeitschriften auf nu? Oder spielt das keine Rolle.

**Comment by kdr154** [comment]
zotaut werden die Keywords erfasst, zotkat nicht.

**Comment by socheres** [comment]
Bitte nochmal testen.  ![image](https://user-images.githubusercontent.com/1545743/82335234-59213680-99e9-11ea-9986-101d33f1ea02.png)

**Comment by kdr154** [comment]
Keywords nun enthalten
