### ISSUE TITLE
ISSN 1461-7404 Social Compass Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#614]
hier gibt es das Abstract in zwei Sprachen. Übertragen wird aber nur eines.
https://journals.sagepub.com/doi/full/10.1177/0037768619868418

**Comment by kdr154** [comment]
In meinen Daten findet sich weiterhin nur eins.

**Comment by mtrojan-ub** [comment]
Die Translators auf nu waren nicht aktuell, ich habe sie soeben aktualisiert. Da es im Zotero Datenmodell nur ein einzelnes Feld für den Abstract gibt werden beide Abstracts vom Translator ins selbe Zotero-Feld geschrieben und später dann zusammen in einem einzelnen 520a Feld ausgeliefert.

**Comment by kdr154** [comment]
Im Einzeldownload werden jetzt beide übertragen, beim Mehrfachdownload nur eines

**Comment by mtrojan-ub** [comment]
Da sind scheinbar ebenfalls 2 verschiedene Translator beteiligt.

a) https://journals.sagepub.com/doi/full/10.1177/0037768619868419
b) https://journals.sagepub.com/toc/SCP/current

Bei a) wird der bekannte "SAGE Journals" translator verwendet, bei b) ein Translator namens "Atypon Journals" da der "SAGE Journals" ähnlich #632 nicht auf das Schema matcht.

**Comment by mtrojan-ub** [comment]
@socheres : Da es ja auch im Original-Translator Probleme gibt, wie gehen wir damit um? Sollen wir einen Issue in zotero/translators dazu aufmachen?

Hinweis: Es gab erst im Dezember seitens Zotero eine Änderung an diesem Translator aufgrund von Erkennungsproblemen, siehe zotero/translators#2077

**Comment by mtrojan-ub** [comment]
Es wird bereits an einer Lösung gearbeitet, siehe zotero/translators#2121

**Comment by kdr154** [comment]
vollautomatisch werden beide Sprachen erfasst, halbautomatisch nicht.

**Comment by socheres** [comment]
@kdr154 @theo-ko bitte auf Zota-Eignung prüfen.

**Comment by kdr154** [comment]
041 immer eng, obwohl viele Artikel fre
Etwa:
IxTheo#2020-05-19#07C82B1B19B66CF9271AB495326046C25DE7F652

**Comment by kdr154** [comment]
Abstract in zwei Sprachen vorhanden. Sie werden aber in einem Tag 520 zusammengefasst. Vgl. ebenfalls IxTheo#2020-05-19#07C82B1B19B66CF9271AB495326046C25DE7F652

**Comment by socheres** [comment]
@kdr154 dieses Issue kann doch geschlossen werden, oder?

**Comment by kdr154** [comment]
Nicht wirklich. Auf nu sind beide Sprachfassungen vorhanden, allerdings weiterhin unter einem 520.
Im halbautomatischen Verfahren wird immer noch nur eine übertragen.
Beispiel-URL https://journals.sagepub.com/doi/full/10.1177/0037768620921705

**Comment by socheres** [comment]
@kdr154 Im Zotkat kommen beide Abstract mit. Bitte nochmal testen. Im Zotaut bitte erst nach commit testen. @mtrojan-ub bitte nach comiit auf "ready for Testing" setzen.

**Comment by kdr154** [comment]
Im zotkat sind beide dabei

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by kdr154** [comment]
In Zotaut weiterhin nur eines.

**Comment by socheres** [comment]
bitte auf benu testen.

**Comment by kdr154** [comment]
Es sind jetzt beide vorhanden.
