### ISSUE TITLE
ISSN 1750-0230 Studies in World Christianity Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#615]
Das Abstract wird abgeschnitten
https://www.euppublishing.com/toc/swc/25/3

**Comment by socheres** [comment]
Translator:
- [ ] Abstract nicht mehr 
- [ ] 12 Zeitschriften von[ Edinburgh](http://www-ub.ub.uni-tuebingen.de/zeder/?instanz=ixtheo#suche=Edinburgh) ins Zotaut-Verfahren übernehmen

**Comment by socheres** [comment]
Diese Zeitschrift ist bereits auf Nu (= Zotaut)

**Comment by kdr154** [comment]
Abstract wird nicht mehr abgeschnitten. Aber es wird die Information "About this Journal"

![grafik](https://user-images.githubusercontent.com/29707105/78759039-51e52280-797f-11ea-9b45-49b73a89acc8.png)

ebenfalls mit ins Abstract übernommen. Bei allen Beiträgen! Das sollte immer unterbleiben.

![grafik](https://user-images.githubusercontent.com/29707105/78759267-b0aa9c00-797f-11ea-80df-82c8de70d426.png)

**Comment by socheres** [comment]
> Abstract wird nicht mehr abgeschnitten. Aber es wird die Information "About this Journal" ebenfalls mit ins Abstract übernommen. Bei allen Beiträgen! Das sollte immer unterbleiben.

Nicht bei allen, sondern nur bei den Artikeln ohne eigenen Abstract.

**Comment by kdr154** [comment]
was ist dann das hier:
This paper explores and discusses the socio-political approach in the theological thinking of the Chinese Protestant pastor Samuel Lamb. Lamb does not appear interested in changing society or politics, as he considers the Christian life to be in distinct contrast with the ways of the world. Nevertheless, both his emphasis on a pious Christian life and his exhortation regarding eternal rewards encourage deliberate efforts to witness to Christ in the world, therefore leading the church to become a socio-political group in socialist China. Lamb thus in effect proposes a radical Christian response to the Communist socio-political context., The journal is concerned through its articles and book reviews to promote creative thinking and lively scholarly interchange in the interpretation of all aspects of Christianity as a world religion. Articles from historical, theological, and social scientific perspectives are equally welcome. Whilst the primary interest of the journal is in the rich diversity of Christian life and thought found in Africa, Asia, Latin America, Oceania, and eastern Europe, contributions that reflect on channels of influence in either direction between Christianity in the majority world and western Europe or North American will also be considered., Alexander Chow, School of Divinity, University of EdinburghEmma Wild-Wood, School of Divinity, University of Edinburgh, Afe Adogame, Princeton Theological SeminaryBrian Stanley, School of Divinity, University of Edinburgh, Kirsteen Murray, School of Divinity, University of Edinburgh, Terry Barringer, Cambridge Centre for Christianity Worldwide, Cambridge, J. Kwabena Asamoah-Gyadu, Trinity Theological Seminary, GhanaPaul Freston, Balsillie School of International Affairs and Wilfrid Laurier University, Waterloo, CanadaSebastian Kim, Fuller Theological SeminaryPeter Phan, Georgetown University, USADana Robert, Boston University, USAHeather J. Sharkey, University of Pennsylvania, USAMarina Wang, The Chinese University of Hong Kong, Hong KongCorey Williams, Leiden University, The Netherlands, Studies in World Christianity is abstracted and indexed in the following:, Worship, Technology and Identity: A Deaf Protestant Congregation in Urban ChinaMark McLeister
Published in Studies in World Christianity 25.2, Copyright © 2020. Edinburgh University Press.

Bei folgendem Artikel:
https://www.euppublishing.com/doi/abs/10.3366/swc.2020.0279

Man muss schon genauer hinschauen um zu erkennen, dass der Inhalt von About this journal nahtlos an das Abstract angeschlossen wird!

become a socio-political group in socialist China. Lamb thus in effect proposes a radical Christian response to the Communist socio-political **context., The journal is concerned throu**gh its articles and book reviews to promote creative thinking and lively scholarly interchange in the

**Comment by socheres** [comment]
@kdr154 Danke fürs Testen. @shadeMe Kannst du bitte diesen Fall mal anschauen.

**Comment by socheres** [comment]
@mtrojan-ub bitte Pullrequest reviewen und Docker neuaufbauen. @kdr154 bitte nochmal testen.

**Comment by kdr154** [comment]
Abstracts sehen jetzt gut aus!
