### ISSUE TITLE
ISSN 2342-7256 Temenos Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#616]
Das letzte und das erste Wort bei einem Zeilenumbruch wird zu einem Wort zusammengeszogen. D. h., man muss ein Blank dazwischen manuell ergänzen.
https://journal.fi/temenos/article/view/87825
hier z. B. wird aus Danish newspaper Danishnewspaper usw.

**Comment by mtrojan-ub** [comment]
Der "Open Journal Systems" Translator wurde entsprechend angepasst.

**Comment by kdr154** [comment]
Sieht jetzt gut aus.
