### ISSUE TITLE
ISSN 1758-6623 The ecumenical review Titelzusatz 245 $b

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#617]
Hier wird der Titelzusatz nicht mit übertragen. Also das, was bei den Titeln hinter dem Doppelpunkt steht. 
marcxml 245 $b
https://onlinelibrary.wiley.com/toc/17586623/2020/72/1

**Comment by socheres** [comment]
@kdr154 bitte Label "Zotero_Semi-Auto" nicht fürs Zotaut-Verfahren vergeben.

**Comment by kdr154** [comment]
Ist jetzt ok!
