### ISSUE TITLE
Scielo ISSN 0718-9273 The living body and transcendental subjectivity in the phenomenology of Edmund Husserl - 936 Bandangabe

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#62]
Die Bandangabe steht fälschlicherweise im Subfield $e, dem Feld für die Heftnummer
```
<datafield tag="936" ind1=" " ind2=" ">
<subfield code="e">40</subfield>

```
statt in $d
müsste also lauten:
```
<datafield tag="936" ind1=" " ind2=" ">
<subfield code="d">40</subfield>
```

**Comment by mtrojan-ub** [comment]
Bitte testen. Ich habe das jetzt für alle Zeitschriften auf ub_tools Seite geändert. (Es könnte im Einzelfall auch sein, dass ein einzelner Translator das versehentlich ins falsche Feld schreibt und das dann nur bei einer einzelnen Zeitschrift falsch ist - war aber in diesem Fall scheinbar nicht so).

**Comment by kdr154** [comment]
Gelöst

**Comment by kdr154** [comment]
Bandangabe steht weiterhin fälschlicherweise in $e statt in $d

**Comment by mtrojan-ub** [comment]
Wir haben uns die Seite und den Translator nochmal näher angeschaut. Der Translator nimmt die Daten von der Webseite mittels des allgemeinen "Embedded Metadata" Translators, und fügt eigene Daten hinzu die nicht in den Metadaten vorhanden sind (z.B. das Abstract).

Dass die Werte vertauscht sind liegt daran, dass die Seite sie verkehrt herum in den Metadaten deklariert hat.

![grafik](https://user-images.githubusercontent.com/26873381/48271695-2cc44b80-e43d-11e8-8428-80e6e8f1a324.png)

Ich werde mal eine Mail an die Betreiber der Seite schreiben.

**Comment by mtrojan-ub** [comment]
Der Betreiber hat sich gemeldet und versichert, dass die Informationen aus seiner Sicht so korrekt sind:

> Dear Mario,
> 
> Thank you for your email, I inform you that the value of citation_issue is correct. The journal is formed by number and not by volume, for this reason it is not feasible to make any modification to what is indicated by the journal.
> 
> Best regards,
> 
> Web Master – SciELO - Chile
> Programa de Información Científica
> Comisión Nacional de Investigación 
> Científica y Tecnológica CONICYT
> 
> Ministerio de Educación | Gobierno de Chile

Jetzt stellt sich die Frage wie wir damit umgehen - passen wir den Translator an, oder doch eher unseren Harvester?
Herr Rosenkranz, können Sie einschätzen ob es noch weitere Zeitschriften gibt bei denen eine Issue-Nummer, aber kein Volume vorhanden ist?

**Comment by IxTheoKm** [comment]
Nur als Zusatzinfo:
es gibt einige wenige Zeitschriften, die _anstatt_ der Volume- und Heftzählungen nur eine _durchlaufende_ Heftzählung haben. In diesen Fällen werden Heftzählungen lt. Erfassungsvorgaben im SWB wie Volume-Zählungen erfasst, auch wenn in einem Jahr mehrere Hefte erscheinen.
Beispiel:
PPN 038886383 Aletheia (ISSN 1242-0832)
https://ephese.net/publications/revue-aletheia

Das kann auch der Fall bei Zeitschriften sein, für die jährlich nur ein Heft erscheint. Diese Fälle kommen häufig vor. Da hängt dann wohl davon ab, ob die Herausgeber/Verlage die Zählung als Heft- oder Bandzählung bezeichnen/liefern.

**Comment by kdr154** [comment]
Das kommt immer mal wieder vor. In dem vorliegenden Fall liegt es wahrscheinlich daran, dass No, Numero, Number .... vom Translator als Heftzählung interpretiert wird. Ich habe über dieses Problem denke ich schon in einem anderen Issue geschrieben. Bei Dialnet haben wir dasselbe Problem. Was man da besser anpasst, schwer zu sagen, weil No .... an anderer Stelle auch das Heft bezeichnen kann. @shadeMe hat sich der Frage im Zusammenhang mit dem Dialnet-Translatot möglicherweise bereits angenommen.

**Comment by kdr154** [comment]
Ich glaube, dass es besser wäre, den Translator anzupassen.

**Comment by mtrojan-ub** [comment]
Ergänzende Frage dazu: Wie soll 773g strukturiert werden, wenn es keinen Band gibt?
(momentan spielen wir 773g gar nicht aus, wenn kein Band angegeben wurde)

**Comment by kdr154** [comment]
Ich denke mal es ist kein Problem, wenn in diesen Fällen 773g nicht ausgegeben wird

**Comment by kdr154** [comment]
Leider ist der Fall komplizierter. Hier vermischen sich zwei Probleme.
In dem Beispiel ober handelt es sich um den Fall, den Frau Kellmeyer beschrieben hat:
es gibt einige wenige Zeitschriften, die anstatt der Volume- und Heftzählungen nur eine durchlaufende Heftzählung haben. In diesen Fällen werden Heftzählungen lt. Erfassungsvorgaben im SWB wie Volume-Zählungen erfasst, auch wenn in einem Jahr mehrere Hefte erscheinen.
Die Heftzählung muss in diesem Fall in 936 e. 
Das Problem besteht darin, dass der Translator Angaben wie Numero, Number, Nummer, Nr., No. ... grundsätzlich als Heftangabe interpretiert. 
Dummerweise gibt es auch den Fall in der Form: Band 10, 2017, Nummer 4.  In diesem Fall ist es richtig, die Angabe Nummer 4 als Heftzählung zu interpretieren.
Auch dann, wenn es keine durchlaufende Heftzählung gibt, also:
2016, Nr. 1, 2016 Nr. 2, 2016, Nr. 3 ...
2017, Nr. 1, 2017 Nr. 2, 2017, Nr. 3 ...
Eine Frage der Heuristik also

**Comment by kdr154** [comment]
Es macht nichts aus, wenn $g in 773 fehlt. Wichtig ist, dass über 773 die Verknüpfung zur übergeordneten Einheit hergestellt wird. 
In 936 sollte die durchlaufende Zählung (zum Problem Numero ... siehe oben) aber in $d stehen. Dies ist noch nicht der Fall, siehe:
```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="e">40</subfield>
<subfield code="h">9-28</subfield>
<subfield code="j">2018</subfield>
</datafield>
```

**Comment by mtrojan-ub** [comment]
Die gestrige Änderung zu 936 ist erst jetzt auf dem Testserver aktiv, bitte nochmal ausprobieren!

**Comment by kdr154** [comment]
Jetzt stimmt es. 
Leider habe  ich mich in einem Comment oben vertippt. Deshalb schicke ich es wieder zurück.
Ich habe folgendes geschrieben:
es gibt einige wenige Zeitschriften, die anstatt der Volume- und Heftzählungen nur eine durchlaufende Heftzählung haben. In diesen Fällen werden Heftzählungen lt. Erfassungsvorgaben im SWB wie Volume-Zählungen erfasst, auch wenn in einem Jahr mehrere Hefte erscheinen.
**Die Heftzählung muss in diesem Fall in 936 e.**
Das ist falsch und muss natürlich heißen:
**Die Heftzählung muss in diesem Fall in 936 d.**
Ich bitte das zu entschuldigen!
Das was danach folgt stimmt dann wieder.
Man hat also das Problem, dass die Heftzählung einmal in $d stehen sollte (bei einer durchlaufenden Zählung ohne eine gleichzeitige Bandzählung), das andere Mal in  $e (dann, wenn die nur die Hefte eines Jahrgangs immer wieder mit 1 beginnend gezählt werden. Auch dann, wenn keine Bandzählung vorhanden ist).
Aber was den konkreten Fall hier anbelangt, hier stimmt es jetzt.

**Comment by kdr154** [comment]
Gelöst
