### ISSUE TITLE
ISSN 2169-1304 Theological studies Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#621]
Keywords kommen nur im Singledownload mit.
https://journals.sagepub.com/toc/tsja/80/4

**Comment by socheres** [comment]
als "zotat" in ZEDER gespeichert.

**Comment by socheres** [comment]
nach Aufnahme der Zeitschrift in "zota" bitte den Issue schließen.

**Comment by socheres** [comment]
@kdr154 Im Einzel-DL bearbeiten. Bitte in ZEDER vermerken und schließen.

**Comment by kdr154** [comment]
vermerkt
