### ISSUE TITLE
ISSN 2056-998X International journal of christianity & education Abstract und Keywords beim Mehrfachdownload

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#630]
Die ZS International journal of christianity & education steht exemplarisch für alle Zeitshriften von Sage. Leider werden beim Mehrfachdownload das Abstract und die Keywords nicht mit übertragen. Das funktioniert nur, wenn man die Seite eines Aufsatzes aufruft und dann die Daten speichert.

**Comment by socheres** [comment]
dito #613

**Comment by socheres** [comment]
@kdr154 Bitte alle Sage-Zeitschriften in ZEDER auf den Wert "zotat" setzen.

**Comment by kdr154** [comment]
gemacht. Bei zwei ZS stand Auswertung selektiv. Dort habe ich es unterlassen.

**Comment by socheres** [comment]
@kdr154 bitte Issue schließen.

**Comment by kdr154** [comment]
Ich schließe
