### ISSUE TITLE
ISSN 2056-998X International journal of christianity & education Datum

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#631]
Mehrfachdownload und Einzeldownload unterscheiden sich hier. Beim Einzeldownload wird ein Aufsatz richtig zugeordnet. Möglicherweise wird hier die Angabe auf der rechten Seite (Article available in:) ausgewertet. Die Jahresangabe kann aber differieren, wenn der Artikel bereits ein Jahr zuvor publiziert wurde. Diese Angabe findet man auch auf den Seiten eines Aufsatzes, unterhalb der Titel- und Verfasserangabe. 
Beim Mehrfachdownload wird die zweite Angabe ausgewertet, die sich auch auf der Übersichtsseite (Table of Contents) befindet. Beim Einzeldownload die erste. Dies hat zur Folge, dass man beim Mehrfachdownload Pica 4070 ggf. korrigieren muss, beim Einzeldownload Pica 1100. 
Ich stelle das mal so dar, obwohl ich mir bewusst bin, dass dies nicht so einfach, wenn überhaupt, zu lösen ist, da beide Angaben aus dem Wert, der im Zoterofeld Datum steht, generiert werden und bis jetzt nur dieser eine Wert zur Auswertung zur Verfügung steht.

**Comment by socheres** [comment]
@kdr154 diese Zeitschrift ist auch von Sage. Vielleicht tritt der Fehler nicht mehr auf.

**Comment by kdr154** [comment]
Leider immer noch. Das Problem ist im Augenblick glaube ich nicht zu lösen.

**Comment by socheres** [comment]
@IxKo @kdr154 @IxTheoKm @jriedl @mtrojan-ub wenn das Veröffentlichungsdatum des Artikels vom Veröffentlichungsdatum der Ausgabe abweicht, dann wird das Veröffentlichungsdatum der Ausgabe sowohl in PICA+ 4070 als auch in 1100 ausgegeben. Z.B.:https://journals.sagepub.com/doi/full/10.1177/2056997119868248
"First Published August 19, 2019" > 2020
![image](https://user-images.githubusercontent.com/1545743/88785878-11115380-d192-11ea-911e-5c4344627dd7.png)
dito #931 #917 #1031
Dies gilt für beide Verfahren: Zotkat und Zoaut.
Im Zotkat mit Mulit-DL via Atypton-Translator steht im Zotero-Feld "date" leider das Veröffentlichungsdatum des Artikels.  Multi-DL mit Sage-Translator funktioniert nicht und weiß auch nicht, woran das liegt. Auf jeden Fall kann ich den Fehler nicht selbst fixen. **Daher beim Zotkat im Einzel-DL via Sage-Translator erfassen**

**Comment by socheres** [comment]
@mtrojan-ub betrifft Sage-Translator. Bitte nach commit "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
pull request wurde gemergt, issue stand aber zuvor bereits auf ready for testing

**Comment by kdr154** [comment]
Im Single-DL ist es korrekt. Da Mullti nicht in Frage kommt und m. W. die Zeitschriften von Sage wegen ihrer unterschiedlichen Struktur für Zotaut nicht geeignet ist, kann man das Issue in meinen Augen schließen. Im Zotaut-Verfahren wird immer das First published-Datum genommen. D. h., Pica 1100 und 4070 sind mal richtig, mal falsch.

**Comment by kdr154** [comment]
Die Artikel werden jetzt sowohl im Multi, als auch im Single-DL wie beschlossen in das Berichtsjahr datiert.
