### ISSUE TITLE
Automatische Einspielung vom 06.02

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#632]
Unter den Daten der Einspielung vom 6.2 befinden sich zahreiche Artikel, die keine Band-, Heft- und Seitenzahlen besitzen. Dies sind alles Online first Artikel, vornehmlich aus der Zeitschrift International Criminal Justice Review, die wir eigentlich ausschließen wollten.

**Comment by socheres** [comment]
Offizielle Translatorversion von SageJournals  https://github.com/zotero/translators/blob/master/SAGE%20Journals.js lädt alle Angaben im Multiple korrekt herunter. @mtrojan-ub bitte unseren Translator nochmal anpassen [ubtue/DatenProbleme/issues](https://github.com/ubtue/DatenProbleme/issues/614 )

**Comment by mtrojan-ub** [comment]
Das Problem besteht auch im Original-Translator.
Es gilt nicht pauschal für alle Datensätze sondern hängt von der URL ab:
a) https://journals.sagepub.com/doi/full/10.1177/1057567719896160
b) https://journals.sagepub.com/doi/10.1177/1057567719896160

Im Fall b) erkennt der Translator nicht, dass er für die Website zuständig ist. Daher wird stattdessen der Embedded Metadata Translator verwendet (lässt sich manuell reproduzieren).

**Comment by socheres** [comment]
dann müsste man den Regex von detectWeb anpassen, dass der im Fall b) auch der SageJournals Translator aufgerufen wird, oder?

**Comment by kdr154** [comment]
Der offizielle Translator ist auch in Bezug auf die Keywords nicht die perfekte Lösung. Bearbeite gerade das neueste Heft von Misssiology https://journals.sagepub.com/toc/misb/48/1 damit.
Hier gibt es zwar nur ein Abstract, aber beim Mehrfachdownload fehlen die Keywords.

**Comment by socheres** [comment]
@kdr154 Wenn das Feld Sprache beim Zotero-Download fehlt, dann bitte in der [Mapping](https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map) nachschauen, ob dort die ISSN eingetragen ist. @mtrojan-ub Bei Keywords muss der Translator angepasst werden.

**Comment by socheres** [comment]
Online-First Problematik ist gelöst. @kdr154 bitte den Issue schließen.

**Comment by kdr154** [comment]
geschlossen
