### ISSUE TITLE
ISSN 1527-9472 Buddhist Christian studies Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#633]
https://muse.jhu.edu/issue/41034

Die Keywords fehlen sowohl beim Mehrfach- als auch beim Einzeldownload

**Comment by socheres** [comment]
ToDo:
- [ ] Keywords
- [ ] Auf Nu "TEST"
- [ ] Prüfen ob weitere Zeitschriften ins Zotaut übernommen werden kann.

**Comment by socheres** [comment]
@mtrojan-ub kannst du den Pull https://github.com/ubtue/zotero-translators/pull/115 bestätigen?

**Comment by kdr154** [comment]
Keywords fehlen bei den Daten von Muse weiterhin, sowohl bei single als auch bei multi.

**Comment by socheres** [comment]
@kdr154 Ihre ProjectMuse-Datei habe ich nun auch ausgetauscht. Jetzt sollte es funktionieren.

**Comment by kdr154** [comment]
Leider nein

**Comment by socheres** [comment]
Bei mir schon.
![image](https://user-images.githubusercontent.com/1545743/78759749-6544bd80-7980-11ea-8e25-cf52f114e1cc.png)

Starten Sie bitte Zotero neu und nochmal testen.

**Comment by socheres** [comment]
@theo-ko können Sie auch mal testen? Hier der Link:https://muse.jhu.edu/issue/41034

**Comment by theo-ko** [comment]
@socheres Bei mir kommen die Keywords beim Multi-DL mit.

**Comment by kdr154** [comment]
Bei mir nicht. Habe alles geschlossen und aktualisiert. Mehrfach. Mein Muse Translator ist von gestern Abend 18:31

**Comment by socheres** [comment]
@theo-ko Können Sie auch andere Muse-Zeitschriften, die wir auswerten, testen?

**Comment by socheres** [comment]
> Bei mir nicht. Habe alles geschlossen und aktualisiert. Mehrfach. Mein Muse Translator ist von gestern Abend 18:31

Ihre Datei ist aktuell. Vielleicht läuft Zotero noch im Hintergrundprozessor weiter. Vielleicht PC neustarten?
![image](https://user-images.githubusercontent.com/1545743/78761941-92469f80-7983-11ea-8a13-d2530eea5aae.png)

**Comment by theo-ko** [comment]
@socheres Ich habe ein paar Zs stichprobenartig geprüft, die über MuseProject geharvestet werden und bei diesen kamen die Keywords mit. Nun habe ich leider die Meldung von Muse: 
Too Many Requests
Your IP has exceeded our limit of 60 page requests per minute.
Please try again later, and at a slower request rate.

**Comment by kdr154** [comment]
Hatte zum Schluss auch Probleme. Musste immer bestätigen, kein Roboter zu sein.

**Comment by socheres** [comment]
Ok. Bisherige Tests genügend. Bitte diese Zeitschrift und eventuell andere Muse-Zeitschriften auf "zotat" in ZEDER setzen.

**Comment by theo-ko** [comment]
@socheres gemacht

**Comment by socheres** [comment]
> ToDo:
> 
> * [x]  Keywords
> * [x]  Translator Pull an Master
> * [x]  Auf Nu "TEST"
> * [x]  Prüfen ob weitere Zeitschriften ins Zotaut übernommen werden kann.

@theo-ko @kdr154 bei einigen Zeitschriften fehlt die Spalte "rss" in ZEDER. Bitte noch nachtragen sowie den vorhanden RSS-Link prüfen.

**Comment by theo-ko** [comment]
@kdr154 Bei zwei Zeitschriften ist der RSS nicht von der Seite Muse, sondern einmal ebscohost und einmal tandfonline. Kann ich in die Spalte einen zweiten RSS-Link eintragen mit einem bestimmten Trennzeichen oder muss ich den vorhandenen überschreiben und sollte den alten RSS-Link in die Bemerkung schreiben?

**Comment by kdr154** [comment]
@theo-ko überschreiben

**Comment by theo-ko** [comment]
@socheres RSS-Links sind eingetragen

**Comment by socheres** [comment]
Ok. @kdr154 bitte Issue schließen.

**Comment by kdr154** [comment]
Done
