### ISSUE TITLE
ISSN 2161-8062 Bulletin of the American Schools of Oriental Research Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#634]
Keyword fehlen sowohl beim Mehrfach-, als auch beim Einzeldownload
https://www.journals.uchicago.edu/toc/basor/2019/382/+

**Comment by socheres** [comment]
@shadeMe einige Translator lässt sich leider in Scaffold nicht testen, obwohl der Translator über Connector-Button problemlos heruntergeladen werden können. Beim detecteWeb wird multiple angeboten, aber nach Auswahl bekomme ich im Editor folgende Meldung angezeigt:

```
16:39:08 Translation using Atypon Journals failed: 
         TypeError: url.match(...) is null
         
         scrape@chrome://zotero/content/xpcom/translation/translate_firefox.js line 425 > eval:195:12
         fetchArticles/<@chrome://zotero/content/xpcom/translation/translate_firefox.js line 425 > eval:186:3
         processDoc@chrome://zotero/content/xpcom/utilities_translate.js:217:12
         Zotero.Utilities.Translate.prototype.processDocuments/</<@chrome://zotero/content/xpcom/utilities_translate.js:240:14
         Zotero.HTTP</this.processDocuments/funcs</</<@chrome://zotero/content/xpcom/http.js:1118:16
         
         url => https://www.journals.uchicago.edu/toc/basor/2019/381/+
```

**Comment by mtrojan-ub** [comment]
Das Test-Problem in Scaffold konnte ich reproduzieren, nach mehreren Tests hat sich herausgestellt dass es sich um ein Cookie-Problem handelt. Wenn man das Cookie nicht akzeptiert gibt es eine Sperre auf der Website die verhindert dass die Unterseiten aufgerufen werden. (Dann findet der Translator statt der richtigen URL nur eine allgemeine "cookie consent" URL, und da diese keine DOI beinhaltet tritt das url.match Problem auf.)

Falls der Fehler auftritt und das Cookie-Fenster in Scaffold nicht mehr erscheint, am besten im Scaffold-Browser manuell auf eine der Unterseiten klicken (z.B. "Full Text") und dann die ursprüngliche URL erneut in die Scaffold-Browserzeile kopieren und laden.

Bei mir kam es danach nicht mehr zu dem url.match Fehler.

**Comment by socheres** [comment]
@mtrojan-ub danke für den Tipp.

**Comment by socheres** [comment]
- [ ] ins zotaut überführen
- [ ] "Atypton Translator" Pullrequest an ubtue_translator

**Comment by socheres** [comment]
@kdr154 nach Testen bitte "zotat" auf Nu setzen.

**Comment by kdr154** [comment]
Zs nicht mehr auf nu zu finden!

**Comment by kdr154** [comment]
Keywords fehlen weiterhin.

**Comment by socheres** [comment]
"zotat" gesetzt.

**Comment by socheres** [comment]
nach Aufnahme der Zeitschrift in "zota" bitte den Issue schließen.

**Comment by mtrojan-ub** [comment]
Ich setze es nochmal auf ready for testing weil der translator heute in einem pull request verändert wurde.

**Comment by IxKo** [comment]
Test mit Nu TRY URL=https://www.journals.uchicago.edu/toc/basor/2019/382/+
(alles ohne gekennzeichnetem X ist fehlerhaft)
- [ ] Front Cover/Front Matter werden erfasst, sollten aber unterdrückt werden.
- [ ] Rezensionen werden nicht richtig getagt, erhalten nur Keyword "Book Reviews"
- [ ] Abstracts werden nicht korrekt erfasst, sondern nur mit dem Inhalt "b.c.e."
- [ ] Keywords werden abgeschnitten (aufgrund des Kommas?):
**Vorlage:** 
Keywords: Vounous Bowl, Prehistoric Bronze Age, Cyprus, Alambra.
**Resultat:**
![grafik](https://user-images.githubusercontent.com/57000004/83010386-79b84480-a018-11ea-802c-8fc88fd05adc.png)

Trifft auch beim Versuch mit semi-auto.-Verfahren zu.

**Comment by socheres** [comment]
Beim Einzel-DL wird DOI-Translaotor und beim Multi-DL Atypton-Translator verwendet.

**Comment by socheres** [comment]
Translator "ubtue_University of Chicago Press Journal.js" ist nun neu für Zotkat und Zotaut. Bitte für Zotkat testen.

**Comment by kdr154** [comment]
Zotat gesetzt. Für zotkat muss die Sprache über die Mapping-Tabelle festgelegt werden.
@IxKo Bandangabe genügt zur Unterscheidung.

**Comment by socheres** [comment]
> Für Zotaut ist Multi-DL nicht wichtig, da der Harvester immer Einzelabfrage macht. Daher bitte nach commit durch @kdr154 auf "zotat" umstellen. @kdr154 bitte nach commit "ready for Testing" hinzufügen.
sorry. Das muss hier @mtrojan-ub statt "kdr154" heißen. Bitte nach  commit durch @mtrojan-ub das Label "ready for Testing" hinzufügen. Ich stellte wieder auf "zot" in ZEDER. @IxKo @kdr154 bitte Testen, ob beide DL-Modi funktionieren.

**Comment by IxKo** [comment]
Beide DL-Modi im zotkat-Verfahren funktionieren.

**Comment by mtrojan-ub** [comment]
ready for testing

**Comment by kdr154** [comment]
Funktionieren
