### ISSUE TITLE
Untertitel mit $b vom Haupttitel trennen

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#635]
**URL**
generell

**Ausführliche Problembeschreibung**
Ist ein Untertitel im Titel vorhanden, wird dieser durch einen Doppelpunkt vom Haupttitel getrennt.
Dieser Doppelpunkt muss durch $b ersetzt werden.

> 245 14$aEin "Zusammengehen ohne Zusammenkommen"$bder Entstehungsprozess des intellektuellen Netzwerkes um die Zeitschrift Die Kreatur$cEnrico Rosso

Ausnahmen sind die Bibelstellen im Titel z.B. Mt 23:19 oder Joh. 3:16 

> 245 10$aTwo "Mothers" in 5 Ezra 2:1-32$cTheodore A. Bergren

Weitere Ausnahmen könnten bei Review-Artikel im Titel auftreten.

> 245 10$aBook review: McCleary, R., McDowall, D., & Bartos, B. J. (2017). Design and Analysis of Time Series Experiments. Oxford University Press

**Offenbare Lösungen**
Beim semiautomatischen Zotkat wie folgt gelöst:

> var titleStatement = "";
        if (item.shortTitle == "journalArticle") {
            titleStatement += item.shortTitle;
            if (item.title && item.title.length > item.shortTitle.length) {
                titleStatement += "$d" + ZU.unescapeHTML(item.title.substr(item.shortTitle.length).replace(/:(?!\d)\s*/,''));
            }
        } else {
            titleStatement += item.title.replace(/:(?!\d)\s*/,'$d');
        }

**Comment by IxTheoKm** [comment]
Ausnahmen können bei Rezensionen auch häufig diejenigen Titelfassungen ohne einleitende Wendungen sein. Bsp.:
PPN 1576206440
Étienne Wolff, Hg.: Littérature, politique et religion en Afrique vandale, ...
PPN 1576206394
Christoph Joest: Die Mönchsregeln der Pachomianer, ...

Weitere Ausnahmen sind andere einleitende Wendungen, die für sich allein aber nicht den Haupttitel bilden, sondern nur mit dem nach Doppelpunkt folgenden Text.
Bsp.:
1523165251
Nachtrag zu: Der Versöhnungstag in der Bibel...
PPN 1572015500
Erratum zu: Das religionswissenschaftliche Dreieck...
PPN 1567873901
Editorial: „Special Focus on Holm Tetens’s ‚Thinking God‘ (‚Gott denken‘)“

**Comment by ruschein** [comment]
Da es außer den Beispielen, die Fr. Kellmeyer aufgeführt hat, noch beliebieg viele andere Verwendungen von Doppelpunkten gibt, die keine Trennung von Haupt- und Nebentitlen implizieren, halte ich es für ziemlich gewagt, automatisch anzunehmen, dass Dopplepunkte etwas deratiges implizieren.  Es gibt vermutlich auch sehr viele Bibelstellenreferenzen mit Kürzeln in verschiedenen Sprachen die dann auch zu Fehlern führen würden. Deshalb rate ich davon ab so eine Heuristik zu implementieren!

**Comment by thefass** [comment]
Das ist eine - leider - sehr schwierige Situation. Egal wie wir uns entscheiden, wird ein Teil der Daten regelwidrig erfasst sein. 
Entweder wir haben die Untertitel im auotmatischen Zotero-Verfahren nie getrennt in den richtigen Kategorien oder wir trennen Titelangaben an Stellen, an denen sie nicht getrennt werden dürfen.
Eine Entscheidungshilfe dürfte sein, wie oft welcher Fall vorkommt.
Oder anders gefragt: was ist das kleinere Übel, in denen dann evt. manuell korrigiert werden müßte.

Die Bibelstellen sind ein häufiger Fall, aber hier ist der : ja immer von einer Zahl umgeben, das könnte man erkennen. Die Fälle wie Hg:, Nachtrag zu:, Erratum zu:, Editorial: könnten auch ausprogrammiert werden.

Nicht erkennen könnten wir wohl Fälle wie
Christoph Joest: Die Mönchsregeln der Pachomianer, ...

**Comment by IxTheoKm** [comment]
Vielleicht eine Entscheidungshilfe:
aus den genannten Gründen haben wir die De Gruyter- und Brill-Daten _ohne_ $b eingespielt!
(Anfangs war sogar der Punkt als Erkennungsmerkmal definiert worden - was natürlich zu einem noch gruseligeren Ergebnis geführt hat.)

**Comment by socheres** [comment]
Ok. Dann verzichten wir auf die Trennung von Haupt- und Nebentiteln. Für die Nutzer ist es auch nicht von Belang. In Vufind wird allerdings der Zusatztitel mit $b nur in der Kurztitelanzeige als Doppelpunkt dargestellt, aber nicht in der Volltitelanzeige. https://ixtheo.de/Record/1688138382.

**Comment by thefass** [comment]
ok.
das Darstellungsproblem in der Volltitelanzeige habe ich in einem eigenen Issue thematisiert

**Comment by ruschein** [comment]
Danke!
