### ISSUE TITLE
add subfield e in 100/700 with the relator "VerfasserIn"

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#636]
**Ausführliche Problembeschreibung**
Das Beziehungskennzeichen <subfield code="e">VerfasserIn</subfield> muss hinzugefügt werden.
Z.B. Ein Datensatz mit Beziehungskennzeichen im Unterfeld "e"

>  <datafield tag="100" ind1="1" ind2=" ">
        <subfield code="a">Tirres, Christopher D.</subfield>
        <subfield code="e">VerfasserIn</subfield>
        <subfield code="0">(DE-588)1056889519</subfield>
        <subfield code="0">(DE-627)79418412X</subfield>
        <subfield code="0">(DE-576)406338256</subfield>
        <subfield code="4">aut</subfield>
        </datafield>  

**Offenbare Lösungen**

Betrifft die Codezeile:
https://github.com/ubtue/ub_tools/blob/bb53a37c6a928e04e8c18e432ae7e5826d859433/cpp/lib/src/ZoteroHarvesterConversion.cc#L790

`subfields.appendSubfield('e', "VerfasserIn");`

**Comment by kdr154** [comment]
Bei Marc 700 Pica 3010 kann man sich nicht sicher sein, ob es sich um einen Verfasser handelt. Hier stehen z.B. die Herausgeber, oder ein Interviewer ....
Auch in 100/3000 kann ein Interviewter stehen

**Comment by socheres** [comment]
@kdr154 Kommt es auch in Aufsätzen vor? Können Sie Beispiel-PPNs dafür liefern?

**Comment by kdr154** [comment]
Zufälligerweise heute einige gemacht, etwa:
 PPN 1690048719
oder
1690039884
In 700/3010 gibt es auch noch z. B. Mitwirkende, IllustratorIn ...

**Comment by socheres** [comment]
Ok. Dann wie bei Brill-Daten kein Unterfeld "e" erzeugen. Scheinbar ist das Beziehungskennzeichen bei maschinellen Einspielung nicht verpflichtend.
