### ISSUE TITLE
ISSN 2214-1332 Journal of Jesuit Studies Ordenskürzel als Bestandteil des Namens

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#637]
In diesem Fall wird das Ordenskürzel S. J. zum Nachnamen:
https://brill.com/view/journals/jjs/7/1/article-p11_11.xml

**Comment by socheres** [comment]
Probleme mit Titulatur scheint in zotaut-Verfahren gelöst zu sein. @shadeMe @mtrojan-ub bitte noch das Beispiel "S.J." - mit Punkt nach J - mit in den [Code](https://github.com/ubtue/ub_tools/blob/b30b69522935f076a3098286e703698d4f52bd0e/cpp/lib/src/ZoteroHarvesterConversion.cc#L406-L407) aufnehmen.

@kdr154 bitte 
- [ ] alle Bril-Zeitschriften auf "zotat" setzen 
- [ ] RSS-FEED in ZEDER überprüfen.

**Comment by kdr154** [comment]
Bei den Problemen mit der Titulator im zotaut bin ich mir nicht sicher. Meines Wissens konnte es nicht abschließend geklärt werden. In meinen Augen ist bei den Brill-Zeitschriften noch ein Testlauf notwendig.

**Comment by kdr154** [comment]
Brill scheint mir RSS abgeschafft zu haben. Jedenfalls finde ich es nicht.

**Comment by kdr154** [comment]
zotat gesetzt

**Comment by socheres** [comment]
@theo-ko können Sie bitte @kdr154 bei der RSS-Suche unterstützen. Auf der Webseite steht die Rubrik "eTOC", aber man muss sich registrieren (z.B. mit Funktionsemail). Alternativ auch in http://www.journaltocs.hw.ac.uk recherchieren.

**Comment by theo-ko** [comment]
@socheres In Zeder ist bei einigen Brill-Zs in der Spalte RSS bereits die xml-Seite zum Overview der Zs eingetragen. Ist das für das automatische Verfahren als RSS Feed ausreichend? Beispiel: https://brill.com/journalissuetocrss/journals/chrc/chrc-overview.xml

**Comment by theo-ko** [comment]
@socheres Habe die RSS/etoc-Links eingetragen. Nur bei Reihen und Datenbanken nicht, denn hier scheint es so etwas nicht zu geben.

**Comment by kdr154** [comment]
Wie haben bereits einen Funktionsaccount eingerichtet bei Brill. Ich bin dort bereits für viele Zeitschriften registriert und bekomme regelmäßig Mails über neu erschienen Ausgaben. Das sind aber mails und keine RSS Feeds

**Comment by ruschein** [comment]
Sollten wir noch einen anderen Modus unterstützen im dem wir Emails auswerten anstatt RSS-Feeds?

**Comment by ruschein** [comment]
Wir könnten auch eine Brücke einbauen mit der wir aus den Emails selbst einen RSS-Feed machen.

**Comment by theo-ko** [comment]
@kdr154 Ich habe mich an bereits eingetragene etocrss.xml Links gehalten und dort die Kürzel der Zeitschriften wie sie auf Brill sind abgeändert. Einige der dadurch neu generierten Links habe ich in Outlook als RSS-Abo getestet und Outlook hatte nicht gemeckert und RSS Feeds ausgespuckt.

**Comment by kdr154** [comment]
Das würde in meinen Augen Sinn machen

**Comment by kdr154** [comment]
Ja, die eingetragenen funktionieren. Aber auf den Seiten von Brill gibt es keine mehr und ich habe daher Zweifel, ob sie aktualisiert werden.

**Comment by ruschein** [comment]
Dann solltest Du das mit Martin besprechen.  Ich stelle mir das so vor: Wir haben irgendwo eine Email-Inbox.  Dort gehen die Emails ein.  Dann haben wir einen Cronjob der periodisch mit IMAP die Inbox leert und sich die neuen Mails holt.  Dann haben wir ein kleines, von mir geschriebenes Programm, das mit einem konfigurierbaren, regulären Ausdruck die Links aus den einzelnen Emails herauszieht und daraus das XML für einen RSS-Feed bastelt.  Das ist vermutlich nicht schwer.  Ich schätze die Arbeit auf 3 bis 5 Tage meiner Zeit.

**Comment by kdr154** [comment]
Prima. Dort laufen alle ein, die ich abonniert habe. Die Adresse ist ixtheo-alerts@ub.uni-tuebingen.de
Vor allem habe ich und bin dabei, alles was von Ebsco per Feed aboniert war auf Mail notification umzustellen, weil die meisten Feeds von dort nicht mehr aktualisiert werden.
Das betrifft aber nicht nur Ebsco.

**Comment by ruschein** [comment]
Ich spreche in ein paar Minuten mal selbst mit Martin darüber.

**Comment by kdr154** [comment]
Und da Ebsco nicht für das Harvesten geeignet ist, ist das ein Problem. Aber ein lösbares in meinen Augen.

**Comment by kdr154** [comment]
Wenn man eine Email-Auswertung von diesen Konto macht, muss die mit Bedacht geschehen. Man kann nicht einfach den Inhalt des Posteingangs löschen, weil dort auch andere Sachen eingehen und auch Benachrichtigung über Zeitschriften, die nicht für das automatische Verfahren geeignet sind.

**Comment by ruschein** [comment]
@kdr154 Dann sollte man 2 Email-Konten benutzen.  Eventuell geht es auch mit einem aber es wird dann möglicherweise etwas komplizierter.

**Comment by kdr154** [comment]
@ruschein Ja, eines ausschließlich für das vollautomatische Verfahren. Müsste man eantragen.

**Comment by socheres** [comment]
@ruschein @kdr154 @thefass @theo-ko bei Brill soll vorerst mit bestehenden RSS-Feeds getestet werden. Das neue Verfahren über eMail behalten wir im Auge und besprechen gemeinsam nach Bedarf zu einem späteren Zeitpunkt.

**Comment by thefass** [comment]
ok

**Comment by kdr154** [comment]
Feed korrigiert, Der alte verwies auf eine andere Zeitschrift.

**Comment by socheres** [comment]
Zum eMail-Verfahren werde ich ein neues Issue an und schließe dieses Issue.
