### ISSUE TITLE
ISSN 2516-6301 Scottish Church History Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#638]
Die Abstracts werden abgeschnitten:
https://www.euppublishing.com/toc/sch/48/1

**Comment by socheres** [comment]
dito #615 @shadeMe @mtrojan-ub auch hier ist  das Testen mit Scaffold wegen Fehlermeldung nicht möglich. siehe #634

**Comment by socheres** [comment]
nach Aufnahme der Zeitschrift in "zota" bitte den Issue schließen.
