### ISSUE TITLE
ISSN 2516-6301 Scottish Church History vollautomatisch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#639]
Diese ZS soll nach Möglichkeit in das vollautomatische Verfahren aufgenommen werden. Habe des RSS-Feed in Zeder eingetragen.

**Comment by mtrojan-ub** [comment]
Wurde übernommen und kann auf nu getestet werden.
(Für späteren automatischen Betrieb bitte falls möglich in Zeder noch "freq" nachtragen).

**Comment by kdr154** [comment]
Die Rezensionen werden nicht mit 655 getagt.
Außer, dass die Seite in die Sektionen Articles und Reviews unterteilt ist, kann ich kein klar zu erkennendes Unterscheidungsmerkmal zwischen Rezensionen und Artikeln ausmachen. Nur folgendes:
1. Bei einem Artikel findet sich der Hinweis (ed), dass es sich beim Verfasser um einen Herausgeber handelt. Das ist aber kein durchgängiges Unterscheidungsmerkmal. 
2. Der Titel bei den Rezensionen beginnt mit dem Namen des Verfassers des rezenierten Werkes, gefolgt von einem Komma. Aber wie soll das die Maschine erkennen können. Und was, wenn das mal nicht der Fall ist.
3. Die Rezensionen besitzen kein Abstract. Im Gegensatz zu allen Artikeln in diesem Heft. Was aber, wenn dies nicht immer der Fall ist?
Erstaunlich, dass die Keywords übernommen werden. Die finde ich nur im PDF.

**Comment by socheres** [comment]
@kdr154 @theo-ko bitte Zeitschriften von www.euppublishing.com auf "zotat" setzen und RSS-Feeds überprüfen.

dito #615 bislang hat @shadeMe diese Sachen bearbeitet. @mtrojan-ub kannst du bitte einen Blick darauf werfen?

ToDo, um "Reviews"-Rubrik als Rezensionen zu taggen:
- [ ] "Reviews" als Keyword pushen. Bsp.[ hier](https://github.com/socheres/translators/blob/70b3011ea9f913ccd0d55c5b13db62b4e9456241/ubtue_Tidsskrift.js#L77-L86)
```
    let sidebarVals = ZU.xpath(doc, '//div[@class="value"]');
    if (sidebarVals && sidebarVals.length) {
        for (let val in sidebarVals) {
            let node = sidebarVals[val];
            if (node.textContent.trim().match(/Anmeldelser/)) {
                item.tags.push('Book Review');
                break;
            }
        }
    }
```
- [ ] zotero_review_regex in [Config](https://github.com/socheres/ub_tools/blob/e7dc375277cce8bf643fd42fbc9e9db91948c550/cpp/data/zotero_harvester.conf#L5150-L5160) hinzufügen
- [ ] remove_marc_field_650a in Config hinzufügen

**Comment by theo-ko** [comment]
@socheres Alle Zs (Summe 5) waren bereits in Zeder auf zotat gestellt. RSS scheinen zu funktionieren.

**Comment by socheres** [comment]
@mtrojan-ub hier der Pullrequest https://github.com/ubtue/zotero-translators/pull/116

**Comment by IxKo** [comment]
Habe eine Rezension auf Nu über Try URL (https://www.euppublishing.com/doi/abs/10.3366/sch.2020.0026?af=R) getestet und die Rezension wird weiterhin nur mit dem Schlagwort "Book Reviews" in 650 gekennzeichnet, aber nicht in 655 als Rezension getagt.

**Comment by socheres** [comment]
die Aktualisierung der Translator muss noch von @mtrojan-ub auf Nu aufgespielt werden. Für Zotkat aber kann schon jetzt getestet werden.

**Comment by socheres** [comment]
@mtrojan-ub kannst du bitte nach Aktualisierung das Label "ready for testing" taggen?

**Comment by mtrojan-ub** [comment]
Translators auf nu+ub28 wurden aktualisiert => ready for testing

**Comment by IxKo** [comment]
Beim Testen eines Heftes (URL=https://www.euppublishing.com/toc/sch/49/1)
- [x] Rezensionen werden richtig getagt 
- [x] Abstracts
- [x] Keywords

- [ ] Aber Artikel "Front Matter" wurde beim Testen mit dem Heft-URL mitgeliefert.
Das sollte unterdrückt werden.

**Comment by kdr154** [comment]
gelöst
