### ISSUE TITLE
ISSN 2294-9321 Judaïsme Ancien - Ancient Judaism Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#640]
https://www.brepolsonline.net/toc/jaaj/2019/7
Sofern vorhanden, gibt es hier das Abstract in zwei Sprachen. Es wäre schön, wenn beide übertragen werden würden, und nicht nur die erste Fassung.

**Comment by socheres** [comment]
@kdr Wie sieht es im Zotaut-Verfahren aus?

**Comment by kdr154** [comment]
Wird nur der erste erfasst.

**Comment by socheres** [comment]
hier wird beim Multiple-Download "DOI.js" und bei Einzeldownload "Atypton.js" verwendet. Hier brauchen wir einen neuen Brepols-Translator.

**Comment by socheres** [comment]
"ubtue_Brepols.js" neuer Translator für Brepols-Zeitschriften. Bitte für Zotkat testen. Für Zotkat erst nach Commit durch @mtrojan-ub testen.

**Comment by kdr154** [comment]
Für Single-DL ist die Frage gelöst. Multi scheint mir der Commit durch @mtrojan-ub noch zu fehlen. Hier dasselbe Problem wir bei #1152
