### ISSUE TITLE
ISSN 1741-3095 Punishment & Society Sprachcode tag 041

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#641]
In den Testdaten wird der Sprachcode nicht richtig umgeetzt. Ausgegeben wird en statt eng. 
Dieser Fehler ist bereits in den von uns gelieferten Daten vorhanden. Zumindest wenn man einen Testlauf auf nu macht.
PPN auf dem Testserver ist 3537338139

**Comment by mtrojan-ub** [comment]
Der fix für #423 hat das Problem wohl für diese Zeitschrift ebenfalls behoben.

**Comment by kdr154** [comment]
Passt.
