### ISSUE TITLE
ISSN 1741-3095 Punishment & Society Online First und Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#642]
Dieser Artikel: PPN 3537338139 auf dem BSZ Testserver, ist ein OnlineFirst Artikel.
vgl. https://journals.sagepub.com/toc/PUN/0/0
Die wollten wir eigentlich ausblenden.
Er ist zudem eine Rezension. Das wird nicht erkannt.

**Comment by mtrojan-ub** [comment]
Welchem Titel (z.B. 245a) entspricht diese PPN genau? (Auf den BSZ Testserver haben wir keinen Zugriff)

Zum Thema Rezension => in der Log tauchen für unterschiedliche Titel mehrfach Meldungen auf wie z.B. "keyword matched review pattern" und "erased field '650a' due to removal filter '^Book Reviews?$'". 
Was genau wird in diesem Fall (oben genannte PPN/Titel?) nicht erkannt bzw. was müsste anders sein?

**Comment by kdr154** [comment]
Auf den Testserver gelangt man, wenn man den Befehl pica3://cbst6.gbv.de:1690-1692 in der WinIBW eingibt. Dann die üblichen Login-Daten eingeben. Habe ich bereits Johannes geschrieben. Oder habt ihr gar keinen Zugriff auf die WinIBW?
Ist aber auch nicht notwendig, da wir jetzt ja ein Abbild der Daten, die von euch ans BSZ geliefert werden, auf W:\FID-Projekte\Default_Test haben. So können wir feststellen, ob der Fehler auf unserer Seite liegt, oder auf der des BSZ.
In diesm Fall sind es Fehler, die eindeutig bei uns zu verorten sind. Es sei denn, das BSZ hat einen Filter, der die Online-First Artikel herausfiltert.
Die Daten, auf die ich mich bezogen habe,  sind die, die man auf W:\FID-Projekte\Default_Test unter zotero_krimdok_200219_001.xml findet.
So wie sie dort liegen, wurden  Sie auch in den Testserver des BSZ eingespielt.

**Comment by mtrojan-ub** [comment]
Einen Zugriff auf die WinIBW haben wir in der Entwicklung nicht. 
Die Daten die in Default_Test landen haben eine von uns generierte PPN die beim Import vom BSZ ersetzt wird. Unsere interne PPN wird dabei in ein LOK-Feld verschoben. Daher können wir die PPN aus der BSZ-Test-DB in der Entwicklung keinem Datensatz zuordnen.

In Default_Test ist momentan nur ein einzelner Datensatz zu dieser Zeitschrift für diese ISSN:
KrimDok#2020-02-18#D0E8384A37E4281D256B32817EE2618370DEA8B6
David J Harding, Jeffrey D Morenoff and Jessica JB Wyse. On the Outside: Prisoner Reentry and Reintegration
https://doi.org/10.1177/1462474520904992

Ist das der Artikel der nicht hätte ausgespielt werden dürfen? (Der ist jedoch in 655a als "Rezension" markiert)

**Comment by mtrojan-ub** [comment]
Potenziell von #648 betroffen

**Comment by kdr154** [comment]
Ja

**Comment by socheres** [comment]
@kdr154 bitte testen und ggfs. Issue schließen.

**Comment by kdr154** [comment]
Sieht beides gut aus jetzt.
