### ISSUE TITLE
ISSN 0771-7776 Sacris Erudiri Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#643]
Hier
https://www.brepolsonline.net/toc/se/2019/58
liegt das Abstract gelegentlich in zwei Sprachen vor.
Bsp. hier: https://www.brepolsonline.net/doi/abs/10.1484/J.SE.5.119447
Schön wäre es, wenn beide übertragen werden würden.
Vgl. #640 Derselbe Publisher

**Comment by socheres** [comment]
@kdr154 dito #640

**Comment by kdr154** [comment]
genauso. Nicht alle Artikel haben zwei, aber dort wo, nur das erste.

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/640#issuecomment-633609335

**Comment by kdr154** [comment]
Im Single-DL werden nun beide Sprachvarianten erfasst. 
Im Multi-DL sind die Daten komplett unzulänglich.  Erstelle ein neues Issue.
