### ISSUE TITLE
ISSN 0771-7776 Sacris Erudiri Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#644]
https://www.brepolsonline.net/toc/se/2019/58
Es findet keine Spracherkennung bei den Aufsätzen statt. Das Feld Sprache bleibt in Zotero leer

**Comment by socheres** [comment]
@kdr154 diese Zeitschrift ist bereits auf Nu. Bitte auf Nu testen und den Issue schließen.

**Comment by kdr154** [comment]
041 ist vorhanden.
