### ISSUE TITLE
ISSN 2294-9321 Judaïsme Ancien - Ancient Judaism Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#645]
https://www.brepolsonline.net/toc/jaaj/2019/7
Es findet keine Spracherkennung bei den Aufsätzen statt. Das Feld Sprache in Zotero bleibt leer.
Vgl. #644 Derselbe Publisher

**Comment by socheres** [comment]
bitte "zotat" in Zeder hinzufügen.

**Comment by IxKo** [comment]
Auf zotat gesetzt

**Comment by socheres** [comment]
@IxKo bitte nach merge durch @mtrojan-ub testen.

**Comment by IxKo** [comment]
Im **zotkat-Verfahren** mit Multi-DL wird die Sprache mit dem Translator "ubtue-Brepols" erkannt, allerdings fehlen Jahres- und Bandangabe sowie Abstracts.
Mit dem Translator "Atypon Journals" sind die Angaben da, aber die Sprache wird nicht erkannt.

Im **zotat-Verfahren** werden überflüssige Artikel wie "Front Matter (“Table des matières”)", "Recensions" (=Sammlung von Rezensionen) und "Bulletin - Livres reçus à la rédaction" erfasst.

**Comment by socheres** [comment]
"ubtue_Brepols.js" im Zotkat nur im Single-DL verwenden. Bitte testen.

**Comment by socheres** [comment]
bitte testen.

**Comment by kdr154** [comment]
Spracherkennung findet statt.
