### ISSUE TITLE
ISSN 1532-7582 The international journal for the psychology of religion Namenszusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#646]
https://www.tandfonline.com/doi/full/10.1080/10508619.2019.1565255
Hier wird der Namenszusatz Jr. zum Nachnamen
Entsprechend hier die Zählung III
https://www.tandfonline.com/doi/full/10.1080/10508619.2019.1660573
Der Link zum Heft: https://www.tandfonline.com/toc/hjpr20/29/4?nav=tocList

**Comment by socheres** [comment]
in Zotkat bitte korrigieren. Wie sieht es in Zotaut aus?

**Comment by socheres** [comment]
bitte prüfen, ob die Zeitschrift für Zotaut geeignet ist.

**Comment by IxKo** [comment]
Der Namenszusatz "Jr" wird beim automatischen Verfahren als Beiname in Subfield c ausgegeben:
![grafik](https://user-images.githubusercontent.com/57000004/82886604-0d214500-9f47-11ea-8a02-c66e590eb233.png)
Das würde in der WinIBW zu 3000 Name, Vorname$lJr. führen. Das wäre okay.

Die Rezension (URL: https://www.tandfonline.com/doi/full/10.1080/10508619.2019.1565255), an der ich getestet habe, wird allerdings nicht ordentlich in 655 getagt, sondern nur mit SW "Book Reviews" in 650 angegeben.

**Comment by socheres** [comment]
mit "Try URL" getestet: https://www.tandfonline.com/doi/full/10.1080/10508619.2019.1565255
Rezension 655 ist vorhanden. "Correction"-Titel bitte mit aufnehmen.

**Comment by IxKo** [comment]
Die Correction-Titel sind beim Test mit Nu Try URL https://www.tandfonline.com/toc/hjpr20/29/4 vorhanden.

Herr Coleman wird mit seiner Zählung richtig erfasst:
![grafik](https://user-images.githubusercontent.com/57000004/91436516-91e26e80-e868-11ea-907a-2574e56c032d.png)

**Comment by kdr154** [comment]
In Zotkat ist beides noch falsch:

![grafik](https://user-images.githubusercontent.com/29707105/91692888-73cb8580-eb6a-11ea-9ccc-c47d5edfa2e2.png)


![grafik](https://user-images.githubusercontent.com/29707105/91692931-8776ec00-eb6a-11ea-9a23-fa7b2a71d9f9.png)

**Comment by kdr154** [comment]
Wenn in Zotkat korrigiert werden soll, kann man das Issue schließen
