### ISSUE TITLE
Mismatch Datum BSZ Testserver und Datum der Lieferung ans Repository des BSZ?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#647]
Auf W:\FID-Projekte\Default_Test finde ich heute eine Datei zotero_krimdok_200222_001.xml
Auf eine Abfrage in dem Testsystem des BSZ finde ich unter diesem Datum nichts, die Daten sind aber bei einer Abfrage nach dem 23.2. zu finden. Spielt das Wochenende da eine Rolle? Bei den Daten vom 19.2 ist keine Diskrepanz festzustellen.

**Comment by mtrojan-ub** [comment]
Bis ende letzten Jahres wurden die Daten BSZ-seitig nur wochentags importiert. Es gab jedoch am 2.12. eine Mail seitens des BSZ an @ruschein dass das ab jetzt auch am Wochenende erfolgt. Wir sind uns intern allerdings nicht sicher ob das tatsächlich auch an beiden Tagen, also Samstag + Sonntag passiert. Von unserer Seite spricht nichts dagegen bzw. wäre sogar wünschenswert.

**Comment by thefass** [comment]
@ruschein Bitte nochmal nachfragen, damit wir es wirklich genau wissen

**Comment by kdr154** [comment]
Es gibt tatsächlich eine Verschiebung um einen Tag. Die Daten die gestern ans BSZ geliefert wurden 200224 wurden heute um 4 25.02. eingespielt.

**Comment by kdr154** [comment]
Ist glaube ich geklärt
