### ISSUE TITLE
ISSN 1556-3855 International Criminal Justice Review Online First und Rezension Testeinspielung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#648]
Bei dem am 22.2 ans BSZ gelieferten und vom BSZ am 23.2 eingespielten Titel
https://journals.sagepub.com/doi/full/10.1177/1057567720908045
handelt es sich wiederum um einen Online First Artikel.
Zudem wurde der Artikel von uns zwar in 655 als Rezension getagt, vgl die Datei zotero_krimdok_200222_001.xml
im Default_Test-Verzeichnis, das ging aber bei der Einspielung durch das BSZ verloren.

**Comment by mtrojan-ub** [comment]
Laut log wurden in diesem Durchlauf mehrere Artikel aufgrund der "Online First" Bedingung übersprungen, aber dieser nicht, obwohl er weder Volume noch Issue hat.

Des Rätsels Lösung:
Die "Online First" Bedingung ist vom Zotero Item Type abhängig. Bisher waren nur "journalArticle" und "magazineArticle" dafür zugelassen. Da wir aber den Typ im Falle von Rezensionen in einem Zwischenschritt mit "review" überschreiben, wurden die Rezensionen bisher nicht als "Online First" behandelt.

Habe das jetzt umgestellt.

Betrifft also potenziell auch alle anderen Online First issues mit Rezensionen.

**Comment by kdr154** [comment]
Kann man erst was sagen, wenn nach einiger Zeit keine solchen Artikel mehr zu finden sind.

**Comment by socheres** [comment]
@mtrojan-ub siehe auch #523

**Comment by kdr154** [comment]
Sieht so aus, als ob es gelöst ist.
