### ISSUE TITLE
ISSN 2040-4867 Journal of church and state Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#649]
Was hier https://academic.oup.com/jcs/issue
in Pica 4207, Zotero Zusammenfassung übertragen wird ist kein Abstract, sondern wie auf der Seite ganz richtig vermerkt, ein Extract, ein Textsnippet aus dem Volltext.
Dies sollte nicht als Abstract interpretiert werden, so wie es hier bei allen Artikeln, auch bei den Rezensionen, geschieht. Zumal auch alle Snippets nach einigen Wörtern, unabhängig vom Abbruch in der Vorlage, abgebrochen werden.

**Comment by socheres** [comment]
In Pica 4207 stehen nicht nur Abstract. Sondern 
> [enthätl eine inhaltliche Zusammenfassung der Vorlage (Summary, Abstract usw.). ](swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4207&kattype=Standard)
**Wenn dies regelkonform ist, bitte "Extract" mit aufnehmen**

**Comment by kdr154** [comment]
Ist aber keine Zusammenfassung sondern ein Textausschnitt, in der Regel der Beginn des Textes, der dann abgebrochen wird. Kann man natürlich so stehen lassen.

**Comment by socheres** [comment]
in Zeder wird diese Zeitschrift von Kaldi erschlossen: "einh = Kaldi". Diese Zeitschrift ist aber durchaus zotaut-geeigenet. In Zeder "zotat" hinzugefügt.

**Comment by thefass** [comment]
@socheres einh = inhaltliche Erschließung, nicht formale Erschließung! efor = formale Erschließung, da steht schon ixTheo, also wir

**Comment by IxKo** [comment]
In der Einspielung vom 25.05. werden keine vermeintlichen Abstracts erfasst.
Beim Testen mit Zotero-semi findet sich auch nichts in der Zusammenfassung.
Ich schließe.
