### ISSUE TITLE
Dateneinspielung 24./25. 2.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#650]
Die Daten sehen gut aus. 
Die Sätze zum Front und Back matter:
```
<datafield tag="245" ind1="0" ind2="0">
<subfield code="a">JLR volume 34 issue 3 Cover and Front matter</subfield>
</datafield>
```
könnten auch gefiltert werden. Wobei sich mir nicht erschließt woher der Titel:
JLR volume 34 issue 3 Cover and Back matter
kommt.
in der Datei zotero_ixtheo_200224_001.xml
ist er so nicht vorhanden.

**Comment by mtrojan-ub** [comment]
In der Datei zotero_ixtheo_200224_001.xml gibt es beides

JLR volume 34 issue 3 Cover and Front matter
IxTheo#2020-02-24#F0E1EBD40CE47816E5EEBD226DCB0A76A987E98B
https://doi.org/10.1017/jlr.2020.7

JLR volume 34 issue 3 Cover and Back matter
IxTheo#2020-02-24#A6C947D4E941B5DDD7CE5BCBB9936604B5771694
https://doi.org/10.1017/jlr.2020.6

Ich habe die Konfiguration angepasst => Cover and (Front|Back) matter wird bei dieser Zeitschrift in Zukunft ignoriert.

**Comment by kdr154** [comment]
gelöst
