### ISSUE TITLE
Dateneinspielung 26./27. 2.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#652]
Die Daten sehen gut aus.
Die Einleitung von Policing & Society https://www.tandfonline.com/toc/gpas20/30/2?nav=tocList
fehlt und hätte auch mit eingespielt werden sollen. Ich nehme an, sei wurde herausgefiltert.
Kriterium für uns beim halbautomatischen Verfahren ist: wir nehmen sie mit auf, wenn sie einen eigenen Titel besitzt, also nicht nur "Einleitung", "Introduction",... heißt. Das ist hier der Fall.
In meinen Augen spricht auch nichts dagegen, sie beim vollautomatischen Verfahren generell mit aufzunehmen. Aber hier gibt es möglicherweise andere Meinungen.

**Comment by socheres** [comment]
@mtrojan-ub was sind zurzeit die Ausschlusskriterien?

**Comment by mtrojan-ub** [comment]
In unserer Log von gestern Abend taucht dazu folgender Fehler auf:
Item 2 [Policing & society :...] | https://www.tandfonline.com/doi/full/10.1080/10439463.2019.1701454?af=R download failed! error:  (response code = 0)

Ich nehme also an dass dieser Artikel nicht bewusst ausgeschlossen wurde, sondern dass es gestern beim Download ein technisches Problem gab und beim nächsten Durchlauf erneut versucht wird ihn herunterzuladen.

Spezielle Ausschlusskriterien (einen Titel-Regel o.Ä.) sind bei dieser Zeitschrift derzeit nicht konfiguriert. 
(bzw. es gibt keine Konfiguration keinen Hinweis auf "exclude_if_marc_field_245a", siehe 
https://github.com/ubtue/ub_tools/blob/7f36c7ec2443a9671dbe4d7ce8fde3c027d50f10/cpp/data/zotero_harvester.conf#L513 )

**Comment by mtrojan-ub** [comment]
Die Einleitung wurde zwar nicht erneut heruntergeladen, es gibt aber in unserer Datenbank einen Hinweis darauf, dass diese schon früher hochgeladen wurde, zu folgendem Zeitpunkt:
2020-01-31 20:05:35

Wir werden die Zotero Harvesting Testoberfläche noch so erweitern, dass man die Datenbank-Protokolle direkt einsehen kann. Das wird die Fehlersuche in solchen Fällen vereinfachen.

**Comment by mtrojan-ub** [comment]
Sofern der "Delivery Mode" nicht auf NONE gesetzt ist, kann man jetzt darauf klicken und erhält eine Übersicht aller Datensätze mit Datum/Uhrzeit der letzten Lieferung.

http://nu.ub.uni-tuebingen.de/zotero_cgi?action=show_downloaded&zeder_id=571

![grafik](https://user-images.githubusercontent.com/26873381/75682666-124b5c80-5c96-11ea-84e4-0aed47de8da5.png)

**Comment by socheres** [comment]
bei 0022-4227 "zotat" hinzugefügt.
