### ISSUE TITLE
Dateneinspielung 26./27. 2. Doppelpunkt im Titel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#653]
Viele Titel der Aufsätze der beiden Hefte bestehen aus Titel und Titelzusatz, getrennt durch einen Doppelpunkt:
https://www.tandfonline.com/toc/gpas20/30/2?nav=tocList
https://www.tandfonline.com/toc/gpcl20/26/2?nav=tocList
Korrekterweise würde der mit $d umgesetzt. Im K10Plus befindet sich hier jedoch ebenfalls ein Doppelpunkt.

**Comment by socheres** [comment]
Beim Zotaut-Verfahren werden Titel und Untertitel nicht durch $d getrennt. Daher bitte den Issue schließen.

**Comment by kdr154** [comment]
ok
