### ISSUE TITLE
Html tags im Titel

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#654]
**HASH*
IxTheo#2020-01-30#F772302E14678AB6CC812CFEE219038F80FEE0BE
 IxTheo#2020-01-30#0F8FD74B42379D50865209332D9D749545AAC490

**Ausführliche Problembeschreibung**
HTML tags muss entfernt werden

in der Testdatenbank WinIBW

> 4000 The @Book of <i>Exodus</i> : A Biography, Joel S.Baden, Princeton University Press, 2019 (ISBN 978‐0‐691‐16954‐5), xviii + 238 pp., hb 26.95

**Offenbare Lösungen**
im halbautomatischen Verfahren werden die HTML tags beim Export-Translator utnedrückt
`titleStatement += "$d" + ZU.unescapeHTML(item.title.substr(item.shortTitle.length)`

**Comment by socheres** [comment]
hier besser über Harvester zu lösen.

**Comment by kdr154** [comment]
Bedeutet das, dass wir keine Issues mehr anlegen müssen, wenn sich HTML-Tags in der Daten befindet?

**Comment by socheres** [comment]
Es wird global gelöst. Also keine Issues mehr zu html-Tags anlegen.
