### ISSUE TITLE
Dateneinspielung 27./28.2.

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#656]
... ist hängen geblieben, eine der neuen Zeitschriften hat einen crash verursacht.

![grafik](https://user-images.githubusercontent.com/26873381/75550036-4eca4e80-5a31-11ea-9775-ff0776d2b4d4.png)

**Comment by socheres** [comment]
@kdr154 die getesteten Zss. müssten alle in der Mappingtabelle enthalten sein, oder? @mtrojan-ub welche Zss. ist es?

**Comment by mtrojan-ub** [comment]
2259-0285: Revue des sciences religieuses : revue trimestrielle _ RevSR

Konkret folgender Artikel:
http://journals.openedition.org/rsr/5557

Beim Testen über die Oberfläche wird zwar eine Ausgabedatei erzeugt, aber man sieht in einem der Datensätze dass der Titel der Zeitschrift nicht nach 773a ausgegeben wird obwohl in 773x eine ISSN steht. Die Validierung vor dem Upload sorgt dann dafür dass der Prozess hängen bleibt.

Wahrscheinlich ein internes technisches Problem bei uns, ich werde es mir weiter anschauen.

Ich glaube auch dass dieser Issue noch einen Rattenschwanz nach sich ziehen wird:
1) Die Validierung sollte auch abschließend in der Testoberfläche durchgeführt werden, um solche Fehler möglichst frühzeitig zu erkennen
2) Wir brauchen besseres Error Handling um zu verhindern dass der gesamte Prozess aufgrund eines Fehlers in einem einzelnen Artikel für alle anderen Artikel/Zeitschriften hängen bleibt
3) Ist noch zu prüfen was mit den anderen Artikeln die zuvor heruntergeladen wurden passiert. Werden diese am nächsten Tag mit hochgeladen oder verschwinden sie?

**Comment by mtrojan-ub** [comment]
Der Fehler beim genannten Datensatz hängt damit zusammen, dass Zotero den Typ "webpage" liefert. Bei den anderen erlaubten Typen "journalArticle", "magazineArticle" und "newspaperArticle" lesen wir den Titel für 773t aus dem Feld "publicationTitle". Dieses Feld gibt es bei "webpage" nicht. Ich werde es so erweitern dass als Fallback das Feld "websiteTitle" verwendet wird.

**Comment by socheres** [comment]
eigentlich sollten Metadaten mit Dokumenttyp "webpage" nicht heruntergeladen werden. Auf jeden Fall ist der Issue für "meeting for discussion"

**Comment by socheres** [comment]
@mtrojan-ub der Fehler tritt nicht mehr auf, oder?

**Comment by mtrojan-ub** [comment]
Meines Wissens nach tritt der Fehler nicht mehr auf, allerdings war noch nicht final geklärt was für Dokumente mit Typ "webpage" passieren soll.

**Comment by socheres** [comment]
@mtrojan-ub kann man dieses Issue schließen? Aufsätze mit dem Dokumenttyp "Webpage" wird als Ausschluss in "Errors"-Dateien ausgegeben, oder?

**Comment by mtrojan-ub** [comment]
Nicht dass ich wüsste... da am Schluss bei der Validierung der ursprüngliche Typ nicht mehr zur Verfügung steht könnte das nur indirekt erfolgen, ich glaube aber nicht dass wir diesen Typ entsprechend kennzeichnen

**Comment by mtrojan-ub** [comment]
Im Meeting besprochen:
- Datensätze die von Zotero mit item type webpage zurückgegeben werden, sollen nicht weiterverarbeitet werden (also auch nicht in Errors-Dateien ausgegeben werden).

**Comment by mtrojan-ub** [comment]
Die Anpassung wurde soeben auf nu+benu eingespielt und kann dort getestet werden.

**Comment by kdr154** [comment]
Bekomme beim oben genannten Artikel beim Test auf benu einen Verarbeitungsfehler:
XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: http://benu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_NDevnc/ixtheo/OxDuNa.xml
Zeile Nr. 1, Spalte 1:

Aber der genannte Artikel sollte in meinen Augen sowieso ausgeschlossen werden.

**Comment by mtrojan-ub** [comment]
Ich schau's mir an, wollte aber kurz noch darauf hinweisen dass es in der zotero_harvester.conf momentan verschiedene Zeitschriften mit folgender Einstellung gibt:

`exclude_if_json_field_itemType = ^webpage$`

Das kann dann entfernt werden, weil wir diesen Typ ja mittlerweile global (hardcoded) ausgeschlossen haben.

**Comment by mtrojan-ub** [comment]
Der Fehler "Kein Wurzel-Element gefunden" wird ja auch dann angezeigt wenn eine leere Datei erzeugt wurde. (also wenn man nur 1 Artikel per Try URL herunterlädt und dieser über eine Regel gefiltert wird).

Allerdings wird der genannte Artikel aktuell nicht aufgrund der Website-Regel gefiltert (es handelt sich um einen journalArticle). 

Das sieht man an folgendem Log-Eintrag:
`MARC field for 'http://journals.openedition.org/rsr/5557 matched exclusion filter (245a/(^Éditorial)|(^Table des matières du volume)|(^Livres reçus)|(^Table des comptes rendus)/)`

Schuld ist also die aktuelle Einstellung für `exclude_if_marc_field_245a`.

**Comment by kdr154** [comment]
Dann ist ja alles korrekt. Die Artikel "Livres reçues..." sollen ja auch ausgeschlossen werden.
