### ISSUE TITLE
Scielo ISSN 0718-9273 The living body and transcendental subjectivity in the phenomenology of Edmund Husserl - Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#66]
Die Quelle hat Keywords:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0718-92732018000200009&lng=en&nrm=iso&tlng=en

Wäre schön, wenn die mitkämen. Gehören in Marc21-Tag 650 $a

**Comment by mtrojan-ub** [comment]
@shadeMe : Da muss wahrscheinlich auch der Translator angepasst werden ("SciELO"), ähnlich #33

**Comment by shadeMe** [comment]
@kdr154 Leider ist die Webseite nicht so gut strukturiert, dass wir die Keywords immer richtig extrahieren können bzw. nicht bei allen Artikeln. Wenn Sie meinen, dass es kein grosses Problem ist, kann ich den Translator dementsprechend anpassen.

**Comment by kdr154** [comment]
@shadeMe Der Aufwand muss auch in Relation zum Ertrag gesehen werden. Prinzipiell sind keywords für den User eine nicht unerhebliche Hilfe. Wenn ich mit Zotero katalogisiere, übernehme ich sie immer manuell. Ebenso wie das Abstract. Auf der anderen Seite gibt es auch Zeitschriften, die für ihre Aufsätze keine keywords uns abstracts vergeben. Das ist kein Grund, sie nicht zu erfassen.

**Comment by kdr154** [comment]
Zu den keywords im Allgemeinen. Ich habe mir die Dokumentation noch einmal angeschaut und bin zu dem Schluss gekommen, dass das Tag 653 das angemessenere für freie Schlagwörter ist.

**Comment by mtrojan-ub** [comment]
Dann bitte ich um vollständige Klärung, bevor wir hier etwas anpassen.

Wir haben monentan auch ein Mapping für bestimmte Zeitschriften hinterlegt, in denen ein anderes Feld statt 653 (bzw. dann 650) verwendet werden soll. Bitte auch klären ob das dann so erhalten bleibt, und ob die Indikatoren bzw. $2 dann ebenfalls auf einen bestimmten Wert gesetzt werden muss.
Siehe: https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_keyword_field.map

Übrigens, das finde ich seltsam: Vorher war in dieser Map als Ziel "992a" hinterlegt. Seit Juli ist "6800" hinterlegt. Das ist doch ein Pica-Feld, oder? Wäre dann in unserem Kontext sowieso nutzlos bzw. würde zu Fehlern führen...

**Comment by kdr154** [comment]
Wenn keine Quelle in vorhanden ist, das ist bei uns der Fall, erhält ind2 den Wert 4. $2 entfällt. Die Felder müssten also wie folgt aussehen:
650 ind1=" " ind2="4"
$a

Was das Mapping des Links auf Github anbelangt kann ich nichts sagen. Das betrifft die Kriminologie. 6800 ist ein Pica-Feld für lokale Schlagwörter. Wir benutzen es nicht, die Kriminologie aber möglicherweise schon.

**Comment by mtrojan-ub** [comment]
@socheres : Kannst Du bitte mal einen Blick auf diesen Issue werfen und einschätzen ob die "ISSN_to_keyword_field.map" für uns überhaupt relevant ist? (In der Map waren vorher MARC-Tags enthalten und jetzt sind es PICA-Tags).

**Comment by socheres** [comment]
Krimdok-Bsp.: PPN [326641319](https://krimdok.uni-tuebingen.de/Record/326641319#details)
keywords stehen anders als in IxTheo im Feld 680x(Pica) bzw. 689 (Marc). Wenn Krim weiterhin die Keywords in Lokaldaten halten will, muss mit BSZ abgestimmt werden, ob die Keywords in 689 ausgeliefert werden kann und dann auch richtig in PICA ankommt.

**Comment by IxTheoKm** [comment]
Die lokalen KrimDok-Keywords, die intellektuell von unseren "Kriminologen" vergeben werden, haben m.E. nichts mit den externen Keywords der Verlage zu tun. 

Keywords der Verlage sollten daher m.E. wie alle anderen auch in den üblichen MARC-Feldern 650 ff. abgelegt werden. Wenn das die "Kriminologen" anders sehen, müssten sie das melden. 

Allerdings halte ich es eher für angebracht, Keywords immer auf Titelebene zu erfassen, damit sie auch von anderen Bibliotheken genutzt werden können.

**Comment by mtrojan-ub** [comment]
Beim heutigen FID-Meeting mit @thefass und @KStelzel wurde vereinbart, dass wir die Keywords für KrimDok zunächst genauso ausliefern wir für IxTheo + alle anderen auch. Falls notwendig wird das KrimDok-Thema erst nächstes Jahr wieder aufgegriffen.

D.h. was als aktuelles ToDo für uns noch übrig bleibt ist ist die Schlagwörter auf die verschiedenen 650ff MARC-Felder zu verteilen.

**Comment by kdr154** [comment]
Gelöst
