### ISSUE TITLE
Einspielung 29.2. | ISSN 2375-3242 Church, Communication and Culture | HTML-Tags

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#660]
Einige Artikel der Einspielung besitzen HTML-Tags:
Hash:
4C1822C2851B967D578B81F929B3C8F188854E7F
49B698DDD3D75AD98FF3BC2C04EE3C4025E2B695
10EE867060AE7D6DF2F44A8C3160EB6C0E2747C2
65C23F409601DFC1E8DA50F982CCAAF9D6158BCD

**Comment by socheres** [comment]
#654
