### ISSUE TITLE
Einspielung 29.2. | ISSN 2375-3242 Church, Communication and Culture | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#661]
Hash 49B698DDD3D75AD98FF3BC2C04EE3C4025E2B695
Der Artikel ist fälschlicherweise mit dem Code eng getagt. Der Artikel ist aber auf Spanisch verfasst.
Marc 041 existiert in unseren Daten. Der Wert ist aber nicht richtig

**Comment by socheres** [comment]
hier Spracherkennung auf Titel einschränken.  
`zotero_expected_languages = title:eng,spa`

https://github.com/ubtue/ub_tools/blob/5e044cefe0f4678f471e3990679b85e0ce33c23c/cpp/data/zotero_harvester.conf#L4221-L4232

**Comment by kdr154** [comment]
gelöst

**Comment by kdr154** [comment]
Warum wird das als is open angezeigt, obwohl es geschlossen wurde?
