### ISSUE TITLE
Einspielung 29.2. | ISSN 2375-3242 Church, Communication and Culture | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#662]
Hash 
882A2146B757AEEAC55C61417C80C6EBAA44B743
4C1822C2851B967D578B81F929B3C8F188854E7F
02BDF0DC05DF49ED2A9ADB4A221B3097B6CAEC81
sind Rezensionen. Diese werden nicht als solche getagt.

**Comment by socheres** [comment]
[Translator](https://github.com/ubtue/zotero-translators/blob/d79df820c0063a2a404c2eacfcf950d4c7f9886c/Taylor%20and%20Francis%2BNEJM.js#L161-L167) erzeugt als Tag "Book Review", daher sollte das Problem behoben sein.

**Comment by kdr154** [comment]
Wenn Sie meinen. Glaube ich nicht. Es sei denn das BSZ erzeugt dann den enstsprechenden Code.  Erzeugt wird das Marcfeld 650 $a. 
Das sind keywords, und zwar Sachschlagworte. Bei Book Reviews handelt es sich um Formlschlagwörter. Auch das ist falsch. Nötig wäre ein Tag 655 mit den entsprechenden Spezifikationen
Vgl. IxTheo#2020-04-02#22BE7B2DD31E11AD2C740D9DEF576AB2A10F3C4A
https://www.tandfonline.com/toc/rchu20/5/1?nav=tocList

**Comment by socheres** [comment]
Der Tag 655 wird über Tag 650 "Book reviews" gesteuert. D.h. beim Herunterladen wird 650 "Book Reviews" absichtlich erzeugt und beim Output in MARCXML aber wieder gelöscht. Nach [Merge](https://github.com/ubtue/ub_tools/pull/662) sollte das Problem behoben sein.
```
remove_marc_field_650a    = "^Book Reviews?$"
zotero_review_regex       = "^Book Reviews?$"
```

**Comment by kdr154** [comment]
Danke für die Erklärung. Dann schließe ich

**Comment by socheres** [comment]
Bitte nochmal auf Nu testen und dann schließen. Die Änderung wurde zwischenzeitlich vom Master übernommen.

**Comment by kdr154** [comment]
655 wird jetzt erzeugt.
