### ISSUE TITLE
Dateneinspielung 29.02./01.03.

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#663]
Dieses Problem hat bei uns zu einem Absturz geführt, da die (falschen) Seitenzahlen nicht zu unserem internen Datentyp passen:

zotero/translators#2135

Zum Thema Error Handling sehe ich das gleiche Problem wie bei #656 => flächendeckende Überarbeitung notwendig. In diesem Fall ist der Fehler aufgetreten nachdem die Daten schon hochgeladen waren, d.h. ein Großteil der hochgeladenen Daten konnte nicht als hochgeladen abgespeichert werden und wird daher bei jedem Durchlauf neu herunter+hochgeladen bis das Problem beseitigt ist.

Ich werde für uns intern schnellstmöglich den Translator anpassen.

**Comment by kdr154** [comment]
Welche Artikel, Zeitschriften soll man da testen?

**Comment by socheres** [comment]
da wir nicht wissen, um welchen Fall es in diesem Issue geht, schließe ich.
