### ISSUE TITLE
Einspielung 29.2. | ISSN 2375-3242 Church, Communication and Culture | Interview

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#664]
Hash F910875412554D4D88EEF661CB71A84B908E4AA2
ist ein Interview
Nach RDA gehört der Interviewte, in diesem Fall Emily Bell, in 3000 Marc 100 und die Interviewer in 3010 bzw Marc 700
Der Satz müsste auch analog zu den Rezensionen mit der PPN für Interviews getagt werden, damit dies in Pica 1131 erscheint:
```
<datafield tag="655" ind1=" " ind2="7">
<subfield code="a">!104767812!</subfield> 
<subfield code="0">(DE-588)</subfield>
</datafield>
```

**Comment by socheres** [comment]
eine Heuristik für die Gattung "Interview" gibt es nicht. @kdr154 bitte den Issue schließen.

**Comment by kdr154** [comment]
Bitte sehr.
