### ISSUE TITLE
Einspielung 29.2. | ISSN 1539-4107 Christian higher education | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#665]
Hash 
F70E4CDD13EE2DF3DE17B42420C2386B285EBB6A
AE5E6558544954D4871FAB637C9BE04BA740B2D0
sind Rezensionen. Sie werden nicht als solche getagt.

**Comment by socheres** [comment]
[Die Bedingung](https://github.com/socheres/ub_tools/blob/44aef034d50c9f59a882955f1131df1b6b863ca7/cpp/data/zotero_harvester.conf#L3813) für Rezension ist enthalten.

**Comment by kdr154** [comment]
Jetzt passt es
