### ISSUE TITLE
Einspielung 29.2. | ISSN 1539-4107 Christian higher education | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#666]
Die Artikel haben Abstracts. Sie fehlen bzw. werden von dem Harvester gar nicht erst abgegriffen. 
Vgl. Hash 5C86A1E51831F5566A3D10C84D0B04A574010560

**Comment by socheres** [comment]
@kdr154 bitte den issue schließen

**Comment by kdr154** [comment]
Bitte sehr!
