### ISSUE TITLE
Einspielung 29.2. | ISSN 1547-3201 Religious education | Abstracts und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#667]
Auf den Webseiten der Artikel dieser Zeitschrift finden sich Abstracts und Keywords. 
Diese werden nicht abgegriffen und fehlen folglich auch in den Daten der Einspielung. Vgl. etwa Hash:
0D844718BFED5F19B3C37A44ED3E020B03A5A976

**Comment by socheres** [comment]
@kdr154 bitte den issue schließen.

**Comment by kdr154** [comment]
Also doch schließen
