### ISSUE TITLE
Einspielung 29.2. | ISSN 1547-3201 Religious education | HTML-Tags

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#668]
Bei diesem Artikel werden HTML-Tags im Titel eingespielt:
Hash: 4E17397FDA1E21616D29EE2B734419F100DBF254

**Comment by socheres** [comment]
https://github.com/ubtue/ub_tools/commit/05ed231946dec7e39c0f0bdd5ef1a971485e284b
