### ISSUE TITLE
Einspielung 29.2. | ISSN 1547-3201 Religious education | SSG-Nummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#669]
Bei den Artikeln dieser ZS ist die SSG-Nummer nicht korrekt.
In den Testdaten Pica 5056 im SWB steht nur die 0. Es müsste aber gemäß Zeder und Mapping-Tabelle 0;1 sein.
In den von uns gelieferten Daten ist dies auch der Fall. Vgl. etwa Hash F16573C3C47CEE8833637FE841C1052822CF06B7
In den von uns gelieferten Daten steht in Marc Tag 084:
```
<datafield tag="084" ind1=" " ind2=" ">
<subfield code="a">0</subfield>
<subfield code="a">1</subfield>
<subfield code="2">ssgn</subfield>
</datafield>
```
Möglicherweise muss man 084 zwei Mal vergeben, einmal mit dem Wert 0, ein weiteres Mal mit dem Wert 1?

**Comment by mtrojan-ub** [comment]
@socheres : wie besprochen bitte klären ob das Problem auf BSZ-Seite liegt bzw. ob wir ein separates 084 ausspielen müssen.
