### ISSUE TITLE
Sabinet ISSN 0254-8356 Women out of place : the women who challenged Jesus Tag 246

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#67]
Der gesamte Tag 246 kann generell entfallen und sollte nicht geliefert  werden. Jedenfalls in diesem Projekt bei allen Aufsätzen von allen Zeitschriften auf allen Plattformen.
Ich sehe keinen Fall, bei dem es sich um etwas anderes als einen Kurztitel handelt.
Beispielsweise hier:
```
<datafield tag="246" ind1=" " ind2=" ">
<subfield code="a">Women out of place</subfield>
</datafield> 
```
Hier wie überall das gesamte datafield löschen oder erst gar nicht übertragen lassen

**Comment by mtrojan-ub** [comment]
wurde entfernt, bitte ausprobieren

**Comment by kdr154** [comment]
Bei den ZS, bei denen ich es überprüft habe, gelöst
