### ISSUE TITLE
Einspielung 29.2. | ISSN 1547-3201 Religious education | Namenszusatz Bestand des Verfassernamens

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#670]
Bei folgendem Aufsatz wird die Berufsbezeichnung Rev. zu einem Bestandteil des Verfassernamens: 
0D844718BFED5F19B3C37A44ED3E020B03A5A976
Eine erfolgreiche GND-Verknüpfung wird in diesem Fall sehr unwahrscheinlich, abgesehen davon, dass diese Angabe so in 3000 auch nicht korrekt ist.
Meines Wissens war eine Mappingtabelle mit Namenszusätzen, die herausgefiltert werden sollten, bereits Gegenstand der Diskussion.

**Comment by socheres** [comment]
@kdr154 gab es dazu bereits ein Issue? Wenn ja, bitte auf diesen Issue verweisen.

**Comment by kdr154** [comment]
Vgl. Diskussion in #148
hier befindet sich ein Link auf eine Wikipedia-Datei mit Abkürzungen und der Hinweis, dass die Problematik beim vollautomatischen  Verfahren funktionieren kann.

**Comment by mtrojan-ub** [comment]
https://doi.org/10.1080/00344087.2020.1708169

Ich nehme an, das "Rev." steht für Reverend (="Hochwürden").
Wäre es sinnvoll "Rev" in die author_name_blacklist.txt aufzunehmen?

**Comment by kdr154** [comment]
Auf jeden Fall. Kommt immer mal wieder vor. Ergänze in der blacklist "Rev", "Rev". "Reverend".

**Comment by socheres** [comment]
@kdr154 kann dieses Issue geschlossen werden?

**Comment by kdr154** [comment]
Rev. steht in der blacklist. Schließe deshalb.
