### ISSUE TITLE
Einspielung 29.2. | ISSN 1743-1727 Reformation and Renaissance review | Editorial

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#673]
Das Editorial ohne Titelzusatz oder ohne eigenen Titel ist Bestandteil der Einspielung. Es besitzt allerdings einen Verfasser, der genannt wird.
Hash F3AF7C029E43EA5EC9D9F8360C151DEF390F978D

**Comment by socheres** [comment]
[Config](https://github.com/ubtue/ub_tools/blob/5e044cefe0f4678f471e3990679b85e0ce33c23c/cpp/data/zotero_harvester.conf#L3430-L3444) anpassen.
`exclude_if_marc_field_245a =^Editorial$`

**Comment by socheres** [comment]
gelöst.
> MARC field for 'https://www.tandfonline.com/doi/full/10.1080/14622459.2020.1711564?af=R matched exclusion filter (245a/^Editorial/)
