### ISSUE TITLE
Einspielung 29.2. | ISSN 1934-9645 Journal of spirituality in mental health | Keywords und Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#675]
Auf den Webseiten zu den Aufsätzen befinden sich Keywords und Abstract. Beide Elemente werden nicht erfasst.
Vgl. etwa Hash 02CA4723EBA5279C029703620F481D74D28C27C5
https://www.tandfonline.com/doi/full/10.1080/19349637.2018.1499165
Diese Zeitschrift wurde ein weiteres Mal am 2.3. eingespielt. Auch hier fehlen die Keywords und das Abstract.

**Comment by socheres** [comment]
gelöst
