### ISSUE TITLE
Einspielung 29.2. | ISSN 1478-0542 History compass | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#676]
Auf den Webseiten stehen keine Seitenzahlen, sondern das, was man eine Nummerierung der Artikel nennen könnte. Zu finden auf dem Inhaltsverzeichnis eines einzelnen Bandes.
https://onlinelibrary.wiley.com/toc/14780542/2020/18/2
Diese Problematik war schon mehrmals Gegenstand der Diskussion. 
In #323 wurde entschieden, dass man diese Nummern bei diesen Zeitschriften unterdrücken muss.
In Marc 936 findet sich kein $h. Vgl. 
Hash AAECBE95BE9EEE65C7EA1052CD967BE392A739E
An anderer Stelle  #537 wurde entschieden, diese Zeitschrift aus dem vollautomatischen Verfahren herauszunehmen. 
Dies würde ich jetzt nicht mehr so sehen. Es muss jedoch von übergeordneter Stelle entschieden werden, wie mit diesen Zeitschriften verfahren wird.

**Comment by socheres** [comment]
Weder auf der Webseite noch in den eingebetteten Daten sind Seitenzahlen vorhanden. Die Seitenzahlen stehen nur in [PDF.](https://onlinelibrary.wiley.com/doi/epdf/10.1111/hic3.12606). Ich kontaktiere mal Wiley. Diese Zss. vorerst nicht geeignet für Zotaut, obwohl die Daten bis auf Seitenzahlen gut sind. 
![image](https://user-images.githubusercontent.com/1545743/75798712-40ed3400-5d77-11ea-971a-cebd4cc30531.png)
@kdr154 Bitte diese Zss. vorerst halbautomatisch erfassen. @mtrojan-ub bitte diese Zss. deaktivieren.

**Comment by mtrojan-ub** [comment]
delivery_mode wurde von TEST auf NONE gesetzt

**Comment by kdr154** [comment]
Delivery Mode auf nu steht aktuell auf Test

**Comment by mtrojan-ub** [comment]
Ja, weil mittlerweile die Zeder-Synchronisierung aktiv ist und in Zeder prodf="zotat" gesetzt ist

**Comment by kdr154** [comment]
Auch bei den Artikel von der Einspielung am 16.5. noch der Fall.
