### ISSUE TITLE
CUP ISSN 2163-3088 THE NEW GENEALOGY OF RELIGIOUS FREEDOM Tag 024 und 856

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#68]
Ist in 024 in $a ein Wert eingetragen (doi, urn oder handle) sollte das Feld 856 $u generiert werden. Denn dieses Feld kann man anklicken und führt direkt zum Dokument.
Beispielweise sollte hier aus:
```
<datafield tag="024" ind1="7" ind2=" ">
<subfield code="a">10.1017/jlr.2018.11</subfield>
<subfield code="2">doi</subfield>
</datafield>
```

zusätzlich 
```
<datafield tag="856" ind1=" " ind2=" ">
<subfield code="u">https://doi.org/10.1017/jlr.2018.11</subfield>
</datafield>
```
generiert werden. 
In diesem Fall steht die URL auch auf der Website:
https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/new-genealogy-of-religious-freedom/A76E3285DBD0EEF59A0EB82D4F4068E7

Zur genaueren Erläuterung siehe:
https://www.loc.gov/marc/bibliographic/bd856.html

**Comment by mtrojan-ub** [comment]
gefixt, bitte nochmal testen

**Comment by kdr154** [comment]
Gelöst
