### ISSUE TITLE
ISSN 2161-8534 American Catholic Studies Namenszusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#681]
Bei dieser Zeitschrift werden die Namenszusätze, in diesem Fall Ordenskürzel, als Bestandteil des Namens interpretiert, so dass die zum Nachnamen werden
Bsp.:
https://muse.jhu.edu/article/749716
https://muse.jhu.edu/article/749715
Ist beim vollautomatischen Verfahren nicht der Fall

**Comment by socheres** [comment]
im Zotkat händisch korrigieren, bis die Zeitschrift ins Zotaut überführt wird.
