### ISSUE TITLE
Dateneinspielung 02./03.03. (2386-7442)

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#682]
Crash aufgrund eines ungültigen Eintrags in der ISSN_to_licence.map (nur ISSN ohne Lizenz)

https://github.com/ubtue/zotero-enhancement-maps/blob/288d60c92f89db6d7d5167562dfa14250f5eb50a/ISSN_to_licence.map#L55

@theo-ko, bitte korrigieren
@shadeMe, dies sollte nicht zu einem crash führen, sondern eher im update_zotero_enhancement_maps Prozess verhindert werden dass die valide lokale Kopie mit invaliden Inhalten synchronisiert wird und ggf. die zuständigen Personen benachrichtigt werden.

**Comment by theo-ko** [comment]
Habe =l in Zeile 55 ergänzt.

**Comment by mtrojan-ub** [comment]
Danke! Habe es auf nu aktualisiert, jetzt fällt auf dass der Crash eigentlich bei dieser Zeitschrift passiert:

Collectanea Christiana orientalia : CCO => 2386-7442

Ich vermute dass der RSS Feed für unser RSS Verfahren nicht geeignet ist, da es mindestens 2 Einträge mit zeitlichem Unterschied gibt die auf die selbe URL verweisen und dann pro URL mehrere results liefern:

https://www.uco.es/revistas/index.php/cco/issue/current

Vermutlich wäre das eher für das DIRECT Verfahren geeignet. Für den Moment werde ich diese Zeitschrift wieder von TEST auf NONE setzen um weitere Crashes zu verhindern.

@shadeMe, vielleicht kannst Du Dir auch hier anschauen ob man das in Zukunft besser abfangen kann.

**Comment by theo-ko** [comment]
@mtrojan-ub Was ist mit DIRECT Verfahren gemeint?

**Comment by kdr154** [comment]
Bereits mit #389 wurde beschlossen, dass diese Zeitschrift nicht für das vollautomatische Verfahren geeignet ist. Ich verstehe deshalb nicht, warum sie sich noch auf nu befindet

**Comment by mtrojan-ub** [comment]
Gut zu wissen! Die Zeitschrift war in der 2. Liste der Zeitschriften enthalten (Mail vom 27.02.), da sie noch in der Konfiguration als NONE vorhanden war habe ich sie auf TEST gesetzt. Dann nehme ich sie jetzt wieder komplett raus.

Mit DIRECT ist das dritte Verfahren neben RSS und CRAWL gemeint, nämlich dass wir täglich mittels des Zotero Servers einen Multiple-Download der o.g. URL durchführen und neue Artikel harvesten sofern welche vorhanden sind.

**Comment by mtrojan-ub** [comment]
... es kann sein dass auch andere Zeitschriften aus dieser Mail auf Test gesetzt wurden. Hätten diese ebenfalls entfernt werden sollen?

**Comment by kdr154** [comment]
Das Problem bei diesen Listen besteht darin, dass die Zeitschriften getestet wurden, aber nicht daraus hervorgeht, mit welchem Ergebnis. 
D. h., sofern möglich, wurden die Fehler bereinigt, es gab aber auch einige, bei denen wir keine Lösung gefunden haben. Das sind zwar vergleichsweise wenige, aber aus meinen Notizen geht nur hervor, dass eine Zeitschrift getesten wurde.
So wie es aussieht, wurden die, die nach dem Test als nicht geeignet eingestuft worden sind, auf nu belassen.
Meine Notizen verzeichnen nur die als nicht geeignet, die gar nicht in Frage kommen, z. B. weil das Erscheinen eingestellt wurde oder es einen Nachfolger gibt.

**Comment by socheres** [comment]
> Crash aufgrund eines ungültigen Eintrags in der ISSN_to_licence.map (nur ISSN ohne Lizenz)
> 
> https://github.com/ubtue/zotero-enhancement-maps/blob/288d60c92f89db6d7d5167562dfa14250f5eb50a/ISSN_to_licence.map#L55
> 
> @theo-ko, bitte korrigieren
> @shadeMe, dies sollte nicht zu einem crash führen, sondern eher im update_zotero_enhancement_maps Prozess verhindert werden dass die valide lokale Kopie mit invaliden Inhalten synchronisiert wird und ggf. die zuständigen Personen benachrichtigt werden.

das Problem ist jetzt behoben, daher schließe ich den Issue.
