### ISSUE TITLE
ISSN 1552-146X | The Hastings Center report | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#684]
Hier wird eine nicht aus Ziffern bestehende Seitenangabe übernommen:
Hash 51C3A1BD3ED89EF4B58604915D936A52882FA898
https://onlinelibrary.wiley.com/toc/1552146x/2020/50/1
Das Heft wurde zudem jetzt bereits zum 3. Mal eingespielt. Immer mit demselben Fehler.
Andere Beiträge hingegen werden ab der 2. Einspielung unterdrückt, bzw. an einer anderen Stelle abgelegt, z. B. der "Artikel" Contributors.

**Comment by socheres** [comment]
alle Artikel ohne Seitenzahlen ausschließen. 
Bitte in der [Codezeile](https://github.com/ubtue/ub_tools/blob/5e044cefe0f4678f471e3990679b85e0ce33c23c/cpp/data/zotero_harvester.conf#L3786-L3799) folgendes Kriterium hinzufügen
`exclude_if_marc_field_773g = "INSIDE_FRONT_COVER-INSIDE_FRONT_COVER$"`

![image](https://user-images.githubusercontent.com/1545743/75863999-a6860280-5e01-11ea-851f-5dd12468d12c.png)
