### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#685]
**URL**
http://link.springer.com/10.1007/s11562-018-0433-y

**Ausführliche Problembeschreibung**
Artikel besitzen auf den Webseiten Keywords, diese finden sich aber nicht in der Quelldatei
Bsp.Hash: IxTheo#2020-02-28#EB0FF059E1FEDF787D9A1DCFD54972986AECC240

**Comment by socheres** [comment]
@mtrojan-ub nach Aktualisierung der Translator bitte Label "ready for Testing" vergeben.

**Comment by mtrojan-ub** [comment]
Das Translator-Update wurde auf den Servern eingespielt und kann jetzt getestet werden

**Comment by IxKo** [comment]
Keywords sind nun dabei
