### ISSUE TITLE
ISSN 1552-146X | The Hastings Center report | Seitenzahlen 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#686]
Wenn die Seitenzählung nur aus einer Zahl (nicht Anzahl an Ziffern) besteht, wird sie nicht erfasst.
Bsp. Hash
11C50B49766E8A41347679BD596E24A19F9DEF83
0DAC4A77E391E4121E6FBCB247CA6997DBB66DC9

**Comment by socheres** [comment]
alle Letters-Artikel ausschließen

![image](https://user-images.githubusercontent.com/1545743/75864813-e39ec480-5e02-11ea-9a28-4ce45b848fa4.png)

**Comment by kdr154** [comment]
Bitte sehr!

**Comment by socheres** [comment]
Artikel mit "Letters" werden ausgeschlossen.
