### ISSUE TITLE
Peeters ISSN 0713-3383 Integrating Religious and Spirirual Practices with Therapeutic Leisure within the Recovery Process of Persons with Mental Disorders Tag 856

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#69]
Der Link in 856 führt ins Nichts, obwohl die Adresse existiert:
```
<datafield tag="856" ind1=" " ind2=" ">
<subfield code="u">http://poj.peeters-leuven.be/content.php?url=article&amp;id=3141797</subfield>
</datafield>
```

http://poj.peeters-leuven.be/content.php?url=article&id=3141797

Sieht mir so aus, als ob der code `&amp;` in der Adresse in 856 stört

**Comment by mtrojan-ub** [comment]
Es handelt sich nicht um einen Fehler.

Schreibt man Textdaten nach XML, so müssen bestimmte Zeichen maskiert werden (in Entites umgewandelt).
Das muss durchgeführt werden, weil diese Zeichen in XML eine besondere Bedeutung haben.

Beispiele:
```
" => &quot;
' => &apos;
& => &amp;
< => &lt;
> => &gt;
```

Wenn man also eine XML-Datei als plain text anschaut, so muss man im Hinterkopf behalten dass jeder XML Parser diese Zeichen zurück umwandeln würde. Dann stimmt auch die URL wieder.
