### ISSUE TITLE
ISSN 2199-4625 | |Journal of Religious Education | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#690]
**URL**
http://link.springer.com/10.1007/s40839-019-00082-6

**Ausführliche Problembeschreibung**
Rezensionen werden in Quelldatei nicht als solche gekennzeichnet
Bsp.-Hash:
IxTheo#2020-02-28#F852E1373E2CCB6A8546A2C229B5A81B1713299B

**Comment by IxKo** [comment]
Werden weiterhin nicht erkannt. Weder in 650, noch wie richtig in 655.

**Comment by IxKo** [comment]
Werden weiterhin nicht erkannt. Getestet mit Try RSS zum aktuellen Heft (Volume 68, Issue 1, April 2020). Hier gibt es ein BookReview, welches aber nicht getagt wird.
Muster im Titel könnte evtl. sein: "Großbuchstabe.:"
Eventuell ist das jedoch zu ungenau und bei Herausgeberwerken gibt es keine Verfasserangabe

**Comment by socheres** [comment]
@mtrojan-ub bitte nach merge "ready for testing" hinzufügen.

**Comment by IxKo** [comment]
Beim Testen auf benu wird der Artikel weiterhin nicht als Rezension erkannt.

Im HTML-Code gibt es folgende Meta-Info: <meta name="dc.type" content="BookReview">

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
