### ISSUE TITLE
ISSN 1552-146X | The Hastings Center report | Artikelauswahl bei wiederholter Einspielung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#691]
Bei den wiederholten Einspielungen dieses Heftes am 1. und 2. 3. wird folgender Artikel unterdrückt
https://onlinelibrary.wiley.com/doi/full/10.1002/hast.1086
Er findet sich auch nicht in den XML-Dateien für diese Tage.
am 28./29. hat er den Hash 11C50B49766E8A41347679BD596E24A19F9DEF83
Er kann aber durchaus drin bleiben.

**Comment by socheres** [comment]
#686 @kdr154 der Issue kann geschlossen werden
