### ISSUE TITLE
ISSN 1573-322X | Journal of agricultural and environmental ethics | Autorenname

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#692]
**URL**
http://link.springer.com/10.1007/s10806-017-9704-5

**Ausführliche Problembeschreibung**
Das Vornamen-Initial fehlt:
Letzter/4ter Autor wird in Quelldatei so ausgeliefert: "Dela Rue, .", auf der Onlineseite des Aufsatzes steht es so: "[…] & B. Dela Rue"
siehe Hash IxTheo#2020-02-28#747F19DC5CC6FB39128291E6219B2761333FE32A

**Comment by socheres** [comment]
Zotero-Client mit Springer-Link Translator alles korrekt.

![image](https://user-images.githubusercontent.com/1545743/75866623-9839e580-5e05-11ea-88b2-d23b8cd0ae86.png)

**Comment by mtrojan-ub** [comment]
Das B wird entfernt weil es auf der Blacklist steht:
https://github.com/ubtue/zotero-enhancement-maps/blob/500438c41d7c14a205a2285d3eee8d578c333fd5/author_name_blacklist.txt#L28

**Comment by socheres** [comment]
die Vorlageform bei den Namen soll grundsätzlich nicht geändert werden. Außerdem ist hier ein "B" und ein Punkt "." Die Punkte sollten auf der Blackliste mit berücksichtigt werden.

**Comment by socheres** [comment]
@mtrojan-ub In der Mapping steht nur der Buchstabe ohne Punkt. Es wird aber trotzdem zweiter Name "B." automatisch entfernt.  Bitte im Harvester auch "Punkt" mit berücksichtigen.

**Comment by mtrojan-ub** [comment]
Wahrscheinlich macht es am meisten Sinn folgende Punkte mündlich zu besprechen:

Problem ist => Wenn z.B. der Eintrag B in der Mapping steht dann würde das trotzdem auf z.B. "BB" matchen => d.h. alles was in der Mapping steht wird aktuell in sog. "Word boundaries" eingeschlossen.

Aus dem Mapping-Eintrag `B` wird also der Regex `\b(B)\b` generiert. Das matcht dann z.B. auf "B", "B ", " B", " B ", "B.", usw.

Wenn wir jetzt den Inhalt ändern ist die Frage wie das genau in den umschließenden Regex eingebettet werden muss.

**Comment by socheres** [comment]
Ok. dann verstehe ich, warum zweiter abgekürzter Vorname "B." entfernt wird. Dann lösche ich vorerst den Eintrag "B".

**Comment by IxKo** [comment]
Nach Test mit Tryl URL scheint der Fehler behoben..
