### ISSUE TITLE
ISSN 1573-322X | Journal of agricultural and environmental ethics | Keywords 

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#693]
**URL**
http://link.springer.com/10.1007/s10806-017-9704-5

**Ausführliche Problembeschreibung**
Artikel besitzen Keywords auf Webseite, diese sind aber nicht in Quelldatei
Bsp.-Hash: IxTheo#2020-02-28#747F19DC5CC6FB39128291E6219B2761333FE32A

siehe auch: #689

**Comment by socheres** [comment]
ready for testing nach #685

**Comment by IxKo** [comment]
Keywords werden nun erfasst
