### ISSUE TITLE
ISSN 1437-1618 | Ethik in der Medizin | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#694]
**URL**
http://link.springer.com/10.1007/s00481-019-00548-z

**Ausführliche Problembeschreibung**
Artikel besitzen Schlüsselwörter und Keywords auf der Webseite, sind aber nicht in Quelldatei enthalten
Bsp.-Hash: IxTheo#2020-02-28#9F6B0818975DC360A4979BFF5FA5DF511B2DB8CB 

siehe auch: #689

**Comment by socheres** [comment]
dito #693

**Comment by IxKo** [comment]
@socheres Beim Versuch Nu zu erreichen, erscheint 500 Internal Server Error.

**Comment by IxKo** [comment]
Keywords werden erfasst
