### ISSUE TITLE
ISSN 1437-1618 | Ethik in der Medizin | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#695]
**URL**
http://link.springer.com/10.1007/s00481-019-00558-x

**Ausführliche Problembeschreibung**
Rezensionen werden in Quelldatei nicht als solche gekennzeichnet
Bsp.-Hash: IxTheo#2020-02-28#80852E16EF3FD4B0CA6F7AEE27BABCE093D401FE

siehe auch: #690

**Comment by socheres** [comment]
Vorgehensweise
1. Translator anpassen damit die weiteren biblioraphischen Angaben Verlag, Ort, Seitenzahlen, ISBN mit ins Titelfeld übernommen wird.
2. Zotero review regex erweitern. 
`zotero_review_regex       = "\ISBN\g"`

![image](https://user-images.githubusercontent.com/1545743/75867398-d683d480-5e06-11ea-873b-d603e9064b38.png)

**Comment by IxKo** [comment]
Rezensionen werden weiterhin nicht erkannt, weder wird ein Keyword vergeben noch korrekt 655.

**Comment by IxKo** [comment]
Wird weiterhin nicht erkannt.

**Comment by socheres** [comment]
@mtrojan-ub nach merge "ready for testing" hinzufügen.

**Comment by IxKo** [comment]
Wird weiterhin nicht erkannt.
Im HTML-Code ist folgende Meta-Info: `<meta name="dc.type" content="BookReview">`

**Comment by IxKo** [comment]
In diesem Fall könnte es zwar mit dem Muster (Hrsg) über Regex gelöst werden, es gibt aber auch Fälle, bei dene keine Regel angewendet werden kann wi ebspw. hier: https://link.springer.com/article/10.1007/s00481-020-00594-y

Es sei denn, man täte die Jahreszahl in Klammern als Kriterium wählen, was jedoch nicht eindeutig genug ist, um es ausschließlich als Rezension zu erkennen.

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
