### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#696]
**URL**
http://link.springer.com/10.1007/s11153-019-09709-y

**Ausführliche Problembeschreibung**
Artikel besitzen Keywords auf Webseite, sind aber nicht in Quelldaten enthalten
Bsp.-Hash: IxTheo#2020-02-28#6CAB7EB510B678F48D3E89C0BC4EFA6F2D1B5F86

siehe auch: #689

**Comment by socheres** [comment]
ready for testing nach #685

**Comment by IxKo** [comment]
Keywords werden nun erfasst
