### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | Einspielungsvarianten 29.2, 1.3., 2.3.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#697]
Die folgenden Artikel wurden an allen drei Tagen eingspielt, alle anderen von diesem Heft nur am 29.2.
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717062
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717061
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717050
Das sind die letzten drei der Book reviews section
Der erste in dieser Sektion 
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717048
jedoch nur am 29.2.

**Comment by socheres** [comment]
das Problem ist etwas grundsätzliches, das behoben werden muss. Diese Fehler treten dann auf, wenn aufgrund fehlerhaften Datensätze zu einem Systemabbruch kommt. @mtrojan-ub und @shadeMe arbeiten an einer Lösung.

**Comment by socheres** [comment]
gelöst.
