### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | SSG-Nummer

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#698]
Diese ZS ist 0;1. Übertragen wird aber nur die 0, obwohl sowohl 0 als auch die 1 in Marc 84 erfasst worden sind. 
Vgl. C621CD8C876C7EB36C5E28AAD84D2052C39B88ED

**Comment by socheres** [comment]
wird bei der nächsten Einstellung behoben.
