### ISSUE TITLE
SSOAR_Leader

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#7]
nam 439 Treffer [Monographie] ***
naa 142 Treffer [Unselbständiges Werk]
nac 19 Treffer [Sammelwerk]
600 Treffer

Es sind zuviele Monographien, da:

	*** Treffer im MARC 21 Feld 500 mit $a In: … müssen „naa“ im Leader bekommen!

**Comment by ruschein** [comment]
@kdr154  Ein konkretes Beispiel wäre hilfreich.  Vermutlich ist das aber wieder ein Auslieferungsproblem.

**Comment by kdr154** [comment]
etwa: oai:gesis.izsoz.de:document/24456

**Comment by IxTheoKm** [comment]
Nach meiner Erinnerung war agbesprochen, dass "monographische" Titel - also im Leader als Monographie gekennzeichnete Titel - von uns im Leader mit naa als unselbständige Werke gekennzeichnet werden sollen, wenn in Feld 500 $a die Zeichenfolge "In: " vorliegt. (Siehe Protokollnotizen unter "Leader".)

**Comment by kdr154** [comment]
Scheint geklärt

**Comment by IxTheoKm** [comment]
Wenn im

\<datafield tag="500" ind1=" " ind2=" "\>
\<subfield code="a"\>

die Zeichenfolge **In:** UND die Zeichenfolge **(Hg.)** vorkommt,
dann wird \<leader\>     **naa** gesetzt.

Wenn im

\<datafield tag="500" ind1=" " ind2=" "\>
\<subfield code="a"\>

die Zeichenfolge **In:** OHNE die Zeichenfolge **(Hg.)** vorkommt,
dann wird \<leader\>     **nab** gesetzt.

**Comment by IxTheoKm** [comment]
Sieht jetzt weitgehend o.k. aus.
