### ISSUE TITLE
ISSN 1533-8568 | Religion and American culture | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#700]
**URL**
https://dx.doi.org/10.1017/rac.2019.13?urlappend=%3Fsource=rss

**Ausführliche Problembeschreibung**
Cover and Backmatter (Seitenangabe B1-B2) + Cover and Frontmatter (Seitenangaben F1-F4) sollen nicht aufgenommen werden

Hashs: 705BBD6CF253CEDE7C21CA88D8D03DB7AC2D4732, IxTheo#2020-02-28#D623B8075F96C5DEF52645ABEE5C273FB80D9B38

**Comment by socheres** [comment]
Config anpassen https://github.com/ubtue/ub_tools/blob/5e044cefe0f4678f471e3990679b85e0ce33c23c/cpp/data/zotero_harvester.conf#L3713-L3727
`exclude_if_marc_field_245a = `
analog zu #673

**Comment by IxKo** [comment]
Beim Test mi Nu werden beide Records noch mitgeliefert:
![grafik](https://user-images.githubusercontent.com/57000004/83253723-c1bca000-a1ad-11ea-8140-510df0c1ab8c.png)

**Comment by IxKo** [comment]
gelöst
