### ISSUE TITLE
ISSN 1740-7931 | British journal of religious education | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#701]
Folgende Artikel sind Book Reviews. Sie werden in keiner der 3  Einspielungen als solche getagt:
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717048
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717050
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717061
https://www.tandfonline.com/doi/full/10.1080/01416200.2020.1717062
Vgl. etwa Hash DECBD57980A0010E55E184CEBDA9928C295460DE

**Comment by IxKo** [comment]
Rezensionen werden weiterhin nicht in 655 getagt.

**Comment by kdr154** [comment]
Book Reviews werden nun als solche getagt.
