### ISSUE TITLE
ISSN 2054-1996 | Journal of Holy Land and Palestine Studies | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#702]
**URL**
- https://www.euppublishing.com/doi/abs/10.3366/hlps.2019.0222?af=R
- https://www.euppublishing.com/doi/abs/10.3366/hlps.2019.0210?af=R
- https://www.euppublishing.com/doi/abs/10.3366/hlps.2019.0223?af=R

**Ausführliche Problembeschreibung**

- Titel "Books received" enthält Auflistung von Büchern, die das Journal erhalten hat und bald rezensieren könnte -> sollte nicht im K10plus aufgenommen werden und hat keine Seitenangaben
IxTheo#2020-02-28#4F3AE680E00CF6DBA71808C0CDEAE771FCC9D972 
- Front Matter + Back Matter (ohne Seitenangaben) sollte nicht im K10plus aufgenommen werden
IxTheo#2020-02-28#5A9264DF710D60417EF1A0C97589BF975CBA3B22, 
IxTheo#2020-02-28#81856166CBDC00C73CEB3E6B51F5B8771E0B965A

**Comment by socheres** [comment]
analog zu #700

**Comment by IxKo** [comment]
Alles Gennante kommt beim Testen mit Nu weitehrin mit.

**Comment by IxKo** [comment]
Probleme bestehen weiterhin

**Comment by socheres** [comment]
Regex korrigiert und mit "Try URL" getestet.

```
remove_marc_field_650a     = "^Book Reviews?"
zotero_review_regex        = "^Book Reviews?"
exclude_if_marc_field_245a = "((Cover and (Front|Back) matter))|((((Front|Back) (M|m)atter)))|((Books (R|r)eceived))"
```
