### ISSUE TITLE
ISSN 1545-6978 | Journal of Near Eastern studies | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#703]
**URL**
- https://www.journals.uchicago.edu/doi/abs/10.1086/706539?af=R
- https://www.journals.uchicago.edu/doi/abs/10.1086/706540?af=R

**Ausführliche Problembeschreibung**
Front Cover + Masthead -> sollte nicht im K10plus aufgenommen werden und hat keine Seitenangaben
IxTheo#2020-02-28#AD54B276931BDFDC572259237CA23A0CEFDFF043
IxTheo#2020-02-28#7B72F5BEC33888C41DFD94BC5740F21D520EB1DE

siehe auch: #702

**Comment by socheres** [comment]
analog zu #700

**Comment by IxKo** [comment]
Beides wird nicht mehr ausgegeben.
