### ISSUE TITLE
ISSN 2054-1996 | Journal of Holy Land and Palestine Studies | free gekennzeichnete Artikel

### ISSUE THREAD

**Issue by theo-ko** [ubtue/DatenProbleme#704]
**URL**
https://www.euppublishing.com/doi/abs/10.3366/hlps.2019.0212?af=R

**Ausführliche Problembeschreibung**
Manche Artikel (Rezensionen+1 Artikel) sind mit einem roten Punkt mit f (free) oder oa (Open Access) auf der Heftseite ([https://www.euppublishing.com/toc/hlps/18/2]) versehen. Ist es möglich, dass  diese in 4950 $LF erhalten oder geht das nur global pro Zeitschrift?

IxTheo#2020-02-28#B47C48D7787C060349A8DF8F3700F384DF74F21B

**Comment by socheres** [comment]
das geht nur global. In IxTheo werden solche Artikel nachträglich über Unpaywall als OA gekennzeichnet.  @theo-ko bitte Issue schließen
