### ISSUE TITLE
ISSN 1467-8519 | Bioethics | Abstract und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#705]
Auf den Seiten finden sich Abstracts und Keywords. Beide Elemente werden nicht erfasst.
Vgl. etwa Hash EF4ECC76BFC91B9CB415796766DE3263D8ED8BF3
https://onlinelibrary.wiley.com/doi/10.1111/bioe.12622
Der Wiley Online Library Translator im halbautomatischen Verfahren erfasst diese Elemente

**Comment by socheres** [comment]
@shadeMe welche Translator benutzt Ihr beim Zotaut? Mit der offiziellen werden beides heruntergeladen.
![image](https://user-images.githubusercontent.com/1545743/75869786-611a0300-5e0a-11ea-8723-a6ad09f249f0.png)

**Comment by mtrojan-ub** [comment]
Beim aktuellen Testen mit Try URL sind sowohl Abstract als auch Keywords vorhanden.

**Comment by IxKo** [comment]
Sowohl Abstract als auch Keywords werden nun erfasst.
