### ISSUE TITLE
ISSN 1745-5219 | The Innes Review | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#706]
**URL**
- https://www.euppublishing.com/doi/abs/10.3366/inr.2019.0223?af=R
- https://www.euppublishing.com/doi/abs/10.3366/inr.2019.0241?af=R

- https://www.euppublishing.com/doi/abs/10.3366/inr.2019.0224?af=R

**Ausführliche Problembeschreibung**

- Front und Back Matter -> sollte nicht im K10plus aufgenommen werden und hat keine Seitenangaben
IxTheo#2020-02-28#B49FA97B5600CCF17C186BD4549027D3EA00D6A8
IxTheo#2020-02-28#3EF9C80DA486736FD905A9132AA680267A517FE4

- Titel="Bernard Aspinwall Prize Competition" Hier handelt es sich um keinen Aufsatz sondern um eine Wettbewerbsausschreibung -> nicht im K10plus aufnehmen
IxTheo#2020-02-28#356EA7A67C5C9A94B1BE81EEA279B1F70FE3867E

**Comment by IxKo** [comment]
@socheres 
Front und Back Matter werden nicht mehr ausgegeben. 

Aber der Titel zur Preisausschreibung schon. Ist das ein Titel den wir so hinnehmen müssen, da sowas allgemein nicht filterbar ist, weil aufgrund mangelnder Kontinuität keine Regel erstellt werden kann und es ein Einzelfall ist?

**Comment by IxKo** [comment]
Ausschreibungen für Wettbewerbe scheinen öfters vorzukommen: 
https://www.euppublishing.com/doi/abs/10.3366/ccs.2005.2.1.109
https://www.euppublishing.com/doi/full/10.3366/cult.2016.0106

Entweder nehmen wir solche "Artikel" in Kauf bei der Erfassung oder es ist kein zota-Kandidat mehr.

**Comment by socheres** [comment]
solche Notizen können auch in IxTheo eingespielt werden. Daher bitte schließen.
