### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review | Abstract und Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#707]
Vgl. #705 
Derselbe Publisher ( Wiley)
Keywords und Abstract werden nicht erfasst, im halbautomatischen Verfahren schon.

**Comment by mtrojan-ub** [comment]
mittlerweile vorhanden

**Comment by IxKo** [comment]
Sowohl Keywords als auch Abstract werden nun erfasst.
