### ISSUE TITLE
ISSN 2473-3725 | The Thomist | Ordenskürzel=Nachname

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#708]
**URL**
https://muse.jhu.edu/issue/41017

**Ausführliche Problembeschreibung**
Bsp: 
Verfasser wurde als `O.p, James Brent`  in Quelldatei erfasst; auf der Artikelseite steht: "James Brent O.P." -> Ordenskürzel wird fälschlicherweise zum Nachnamen
IxTheo#2020-02-28#4B418FD07180981F95ED573C59C42A8EF5DC341F

weitere Bsp.:
IxTheo#2020-02-28#CE8DED804F5E110A9FC0C4E19AAE0490BB9BB462
IxTheo#2020-02-28#4976F85DC15594E63B23E6BFAE7A954BF5F8B15C

**Comment by mtrojan-ub** [comment]
Grundsätzlich werden Ordenskürzel aus dem Namen entfernt bevor diese weiterverarbeitet werden. Dafür gibt es eine Blacklist. Diese war bisher noch im ub_tools repository zu finden, ich habe sie jetzt ebenfalls nach zotero-enhancement-maps umgezogen damit Ihr sie bei Bedarf selbst pflegen könnt:
https://github.com/ubtue/zotero-enhancement-maps/blob/master/author_name_blacklist.txt

Die Blacklist enthält bereits "OP", aber nicht in dieser Schreibweise "O.P.". Einen ähnlichen anderen Fall gibt es dort bereits: "SCI" und "S.C.I. di Béth.". Vermutlich ist es nicht sinnvoll, grundsätzlich in allen Fällen Punkte zwischen den Zeichen zu erlauben, oder? In diesem Fall wäre es gut wenn man die Schreibweise mit Punkt direkt in die Blacklist mit aufnimmt.

**Comment by IxKo** [comment]
Weiterhin der Fall. Da es hier O.p. (also Groß- dann Kleinschreibung) lautet, kann dann nicht daraus eine Regel erstellt werden?

**Comment by socheres** [comment]
@mtrojan-ub https://github.com/ubtue/zotero-enhancement-maps/blob/master/author_name_blacklist.txt kann diese Mapping als "case sensitiv" eingestellt und Punkt mit Escape mit berücksichtigen?

**Comment by mtrojan-ub** [comment]
Das Mapping ist bereits "case sensitive", also wenn "OP" in der Map steht dann müssen beide Zeichen Groß sein, sonst matcht er nicht. Punkte in der Datei werden bereits vor der Anwendung als Regex escaped. 

Da es bei der Beschreibung dieser Fälle sehr schnell Mißverständnisse im Matching geben kann würde ich vorschlagen das Verfahren in einem Meeting zu besprechen.

**Comment by mtrojan-ub** [comment]
Heute im zotaut Regelmeeting besprochen:
- Regex wurde auf case-insensitive umgestellt
- Schreibweisen mit Punkt wie z.B. `O.P.` müssen von Hand in die author_name_blacklist.txt eingetragen werden

**Comment by IxKo** [comment]
Beim Testen auf Nu und auf Benu erhalte ich mit Try URL nur ein gelbes Fenster mit roten Rahmen.
Das steht im CLI output, wenn ich nur den Artikel mit dem Verfasser OP teste: 

> Converting item 1 [The Thomist : a spec...] | https://muse.jhu.edu/article/734967 {5334614757208701135}
> use online ISSN "2473-3725" with online PPN "324743165"
> title matched review pattern
> Augmented metadata record: MetadataRecord {
> 	url: https://muse.jhu.edu/article/734967,
> 	item_type: review,
> 	title: God's Own Ethics: Norms of Divine Agency and the Argument from Evil by Mark C. Murphy (review),
> 	short_title: God's Own Ethics,
> 	publication_title: The Thomist : a speculative quarterly review of theology and philosophy,
> 	language: eng,
> 	issn: 2473-3725,
> 	superior_ppn: 324743165,
> 	superior_type: 2,
> 	ssg: 2,
> }
> Skipping: online-first article unconditionally
> Conversion complete

Und wenn ich die ganze Heft-Seite (https://muse.jhu.edu/issue/41017) teste, erhalte ich ebenfalls nur eine fast leere gelbe Seite.
Im CLI output steht Folgendes:


> Converting item 1 [The Thomist : a spec...] | https://muse.jhu.edu/issue/41017 {1343874986999106784}
> use online ISSN "2473-3725" with online PPN "324743165"
> Augmented metadata record: MetadataRecord {
> 	url: https://muse.jhu.edu/issue/41017,
> 	item_type: webpage,
> 	title: Project MUSE - The Thomist: A Speculative Quarterly Review-Volume 83, Number 1, January 2019,
> 	short_title: Project MUSE - The Thomist,
> 	publication_title: The Thomist : a speculative quarterly review of theology and philosophy,
> 	language: eng,
> 	issn: 2473-3725,
> 	superior_ppn: 324743165,
> 	superior_type: 2,
> 	ssg: 2,
> }
> Skipping: undesired item type "webpage"
> Conversion complete
> 

In der Conf erkenne ich kein Ausschlusskriterium eines Datensatzes:

> [The Thomist : a speculative quarterly review of theology and philosophy]
> zeder_id                  = 1334
> zeder_modified_time       = "2020-10-23 11:21:18"
> print_ppn                 = 165721154
> print_issn                = 0040-6325
> online_ppn                = 324743165
> online_issn               = 2473-3725
> zotero_type               = RSS
> zotero_group              = IxTheo
> zotero_url                = https://muse.jhu.edu/feeds/latest_issues?jid=694
> zotero_expected_languages = eng
> zotero_review_regex       = \(review\)
> zotero_delivery_mode      = TEST
> ssgn                      = FG_1
> license                   = KW
>

**Comment by mtrojan-ub** [comment]
Das hängt mit der Änderung für #656 zusammen. Da der Translator den item_type `webpage` liefert werden sie allesamt ausgeschlossen und eine leere Datei erzeugt.

**Comment by IxKo** [comment]
Kann es sein, dass Fall 1 (Einzel-Artikel) nicht das Kriterium webpage zu greifen scheint, sondern er ausgesondert wird, weil er als Online-first-Artikel erkannt wird?
Den im CLI Output stand nichts von webpage, aber von "skipping online-first-article"

Es handelt sich aber um keinen Online-first-Artikel

**Comment by mtrojan-ub** [comment]
OK, meine vorige Aussage bezog sich auf Try RSS. Wenn ich Try URL auf den ersten Fall mache (734967) dann erhalte ich ebenfalls die Meldung online first, kann es also reproduzieren.

Die Online First Regel greift immer dann, wenn der Translator weder Issue noch Volume findet. 
Der Ausschluss von "Webpage" greift zwar bevor die Online First Regel geprüft wird, allerdings wird dieser Datensatz aufgrund des Titels "The Thomist: A Speculative Quarterly Review" und der Einstellung für "zotero_review_regex" als Review eingestuft (was vorher passiert) und daher greift die Webpage Regel nicht.

Ich werde die Webpage Erkennung noch etwas weiter nach vorne setzen, so dass sie greift bevor die Erkennung von Reviews statt findet.

**Comment by mtrojan-ub** [comment]
Die Anpassung wurde auf nu+benu eingespielt. Allerdings ist auf benu ein translator im Einsatz der bei diesem Datensatz mittlerweile nicht mehr webpage sondern journalArticle liefert. Daher greift die Webpage Regel nicht. Der Typ wird im Anschluss auf Review geändert + aufgrund der fehlenden Issue+Volume Felder als online first eingestuft.

**Comment by socheres** [comment]
- [ ] Muse Zeitschriften als nächste Testkandidatin für "zotat"

**Comment by IxKo** [comment]
Der alte O.p-Fall kann auf Nu nicht getestet werden, da es bei Try URL zu einer Fehler-Seite führt.
Aber auch im aktuellen Heft (84.2020, 3) gibt es einen Autor mit Ordenskürzel Das Kürzel wird in diesem Fall übernommen:

![image](https://user-images.githubusercontent.com/57000004/121024527-97c89100-c7a4-11eb-9292-b46b90f419c5.png)

Könnte vielleicht beim Namensübertrag das Metafeld genutzt werden? Hier scheint das Ordenkürzel im Tag ausgeschlossen zu werden: 

```
<li class="author"><div class="contrib">
<a href="/search?action=search&amp;query=author:Romanus%20Cessario">Romanus Cessario</a> O.P.</di
```v></li>

**Comment by IxKo** [comment]
> * [ ]  Muse Zeitschriften als nächste Testkandidatin für "zotat" @IxKo können Sie bitte prüfen, ob Muse-Zss. für zotaut geeignet ist.

Die Muse-Zss können ins Testverfahren genommen werden. Es sind wohl auf Zeder auch schon alle auf prode=zotat gesetzt.
Auf den allerersten Blick machen die Daten schon jetzt einen guten Eindruck: 
Rezensionen scheinen erkannt zu werden 
Abstracts und Keywords werden übernommen, wenn es welche gibt
die allermeisten Muse-Zss scheinen nur auf Englisch zu sein, daher wird es wohl wenig Sprachprobleme geben

**Comment by IxKo** [comment]
Schließe, da der Fall nicht mehr testbar ist.
