### ISSUE TITLE
Allgemein: weiterer URL aus Quelldatei nicht angezeigt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#710]
**URL**
https://muse.jhu.edu/issue/41017

**Ausführliche Problembeschreibung**
Es wird immer nur ein URL im K10plus ausgegeben, obwohl in der Quelldatei ein weiterer angegeben ist:

```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.1353/tho.2019.0003</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://muse.jhu.edu/article/734966</subfield>
</datafield>
```

Bspw.:
IxTheo#2020-02-28#E3D1BCB2630E9EF2AA46C7F14F597367D2A25D35

**Comment by socheres** [comment]
In MARC "856" sollte eigentlich nur der zweite URL stehen

`<subfield code="u">https://muse.jhu.edu/article/734966</subfield>`

![image](https://user-images.githubusercontent.com/1545743/75871460-e2729500-5e0c-11ea-8684-49e9f62f95b9.png)

**Comment by theo-ko** [comment]
> In MARC "856" sollte eigentlich nur der zweite URL stehen
> <subfield code="u">https://muse.jhu.edu/article/734966</subfield>

Der DOI, der in Pica 2051 (Marc-024) steht, soll jedoch auch in Pica-4950 "aufgelöst" werden. Daher ist es korrekt, dass der DOI-URL auch in Marc-856 vorkommt.

Beispiel aus dem K10plus (PPN 1549469940):
```
024 7 $a10.15496/publikation-34654$2doi
024 7 $a10900/93268$2hdl
856 40$uhttp://www.lectio.unibe.ch/14_2/wacker_marie_theres_homme_sauvage_et_femmes_etrangeres.html$xVerlag$zKostenfrei$3Volltext
856 40$uhttp://dx.doi.org/10.15496/publikation-34654$xResolving-System$zKostenfrei$3Volltext
856 40$uhttp://hdl.handle.net/10900/93268$xResolving-System$zKostenfrei$3Volltext
```
Hier wird für jeden PI (DOI und Handle) auch ein URL-Feld in Marc-856 vergeben.

**Comment by mtrojan-ub** [comment]
Verstehe ich das richtig, dass der Harvester korrekt beide URLs in 856u einträgt und die zweite URL seitens des BSZ nicht importiert wird? Dann sollte das Label von "Fehlerquelle: Harvester" zu "Fehlerquelle: BSZ" geändert werden.

**Comment by kdr154** [comment]
In den aktuellen Testdaten sind zwei 856-Felder enthalten:

![grafik](https://user-images.githubusercontent.com/29707105/87307319-aa493480-c519-11ea-86dd-dff3ba8fc0fd.png)

**Comment by IxKo** [comment]
In den xml-Test-Dokumenten sind auch beide URLs angegeben:
![grafik](https://user-images.githubusercontent.com/57000004/87311578-b637f500-c51f-11ea-97c3-012a41d276ff.png)

Im K10plus wird aber nur ein URL übernommen:
![grafik](https://user-images.githubusercontent.com/57000004/87311728-e97a8400-c51f-11ea-8bc2-8f85ab367c57.png)

Demnach vermutet mtrojan-ub richtig, dass der Fehler wahrscheinlich beim BSZ liegt.

**Comment by socheres** [comment]
- [ ] Dummy-Datei erstellen und auf Test-Ordner hochschieben.

**Comment by IxKo** [comment]
Neue Test-Daten von Sage haben gezeigt, dass zwei URLs in der Test-DB angezeigt werden (Bsp.: IxTheo#2020-12-01#0E2574205ADC50B8A70BE6B04B1C1E4364B18720)
