### ISSUE TITLE
Allgemein: Lizenzangabe mit neuem Tag 856 -> gar keine URL-Anzeige in Pica-4950

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#712]
**URL**
https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml

**Ausführliche Problembeschreibung**
Sobald eine Lizenzangabe in der Quelldatei "generiert" wird, wird diese scheinbar als neuer Tag-856 angelgt und erscheint auch im Record als erster Tag-856. Dies scheint im K10plus zu gar keiner Anzeige der URL(s) zu führen, sondern es erscheint nur: 
4950 $xH$3Volltext$534

Quellcode:
```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="z">Kostenfrei</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.3167/arrs.2019.100113</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml</subfield>
</datafield>
```

Das Subfield $z=kostenfrei müsste - glaube ich - in die jeweiligen Tags-856 mit den vorhanden URLs, sodass diese Information auch einer URL zugeordnet werden kann:

```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.3167/arrs.2019.100113</subfield>
<subfield code="z">Kostenfrei</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml</subfield>
<subfield code="z">Kostenfrei</subfield>
</datafield>
```

**Comment by socheres** [comment]
eine Dummy-Datei hochgeschoben wie oben beschrieben: "zotero_ixtheo_dummy_200311.xml" 
Wenn die Angaben korrekt in WinIBW landen, dann bitte [Harvester](https://github.com/ubtue/ub_tools/blob/499a19f63967371e96a42dca2bcb66316eb16d46/cpp/lib/src/ZoteroHarvesterConversion.cc#L878-883) anpassen.

**Comment by mtrojan-ub** [comment]
Ich nehme an der Test war erfolgreich? Der Link auf den Harvester (siehe oben) ist die richtige Stelle aber scheint veraltet zu sein, es wird in z nicht mehr "Kostenfrei" und "Teilw. Kostenfrei" sondern "LF" und "KW" exportiert, siehe:
https://github.com/ubtue/ub_tools/blob/bb40c4f250191686798657233bdb8d125ea48178/cpp/lib/src/ZoteroHarvesterConversion.cc#L880

Ich kann das gerne so umschreiben dass die Lizeninfo direkt an den jeweiligen URLs hängt.

**Comment by mtrojan-ub** [comment]
siehe ubtue/ub_tools#3453
(ruschein ist frühestens ab Dienstag wieder im Haus)

**Comment by mtrojan-ub** [comment]
Die Änderung ist jetzt aktiv:
![grafik](https://user-images.githubusercontent.com/26873381/82869841-3635db80-9f2f-11ea-8c5b-acec44f20c89.png)

=> ready for testing

**Comment by IxKo** [comment]
Beim Testen mit URL (https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml) wurde gar kein Subfield z erzeugt:
```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.3167/arrs.2019.100113</subfield>
</datafield>
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml</subfield>
</datafield>
```
Die Zs ist ein schlechtes Beispiel:
In der ISSN_to_licence.map ist die Zs drin als 2150-9298=l # Religion and Society
Auf Zeder steht sie allerdings bei OACC auf N. In der EZB ist sie auch als kostenpflichtig drin, daher habe ich die Zeile aus der Liste nun entfernt.

Mit einer anderen Zs, die sowohl in der Mapping-Liste als auch auf Zeder OA ist, funktionierte es:
Journal of Jesuit studies
https://brill.com/view/journals/jjs/7/1/article-p11_11.xml

```
<datafield tag="856" ind1="4" ind2="0">
<subfield code="u">https://doi.org/10.1163/22141332-00701002</subfield>
<subfield code="z">LF</subfield>
</datafield>
```
Ob es auch in der WinIBW so rüberkommt wie gewollt, wird sich zeigen.

@mtrojan-ub 
Wird für das vollautomatische Verfahren nur der Zeder-Wert herangezogen und die Angaben in der Mapping-Liste ignoriert? Zumindest scheint es so.

**Comment by socheres** [comment]
m.W. werden die Werte in Zeder für Lizenzangaben noch nicht berücksichtigt. Vorerst müssen die Werte in ZEDER eingerichtet werden. Siehe https://github.com/ubtue/DatenProbleme/issues/979#issuecomment-633906274

**Comment by IxKo** [comment]
Dann griff die Mapping-Liste beim Testen gerade vermutlich nicht, weil die Zs nur mit Print-ISSN hinterlegt war statt zusätzlich mit der elektronischen ISSN.
Danke.
