### ISSUE TITLE
ISSN 0717-6295 | Teologia y vida | lizenzfrei

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#713]
**URL**
https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0049-34492019000400457&amp;lng=es&amp;nrm=iso&amp;tlng=es

**Ausführliche Problembeschreibung**
Laut Zeder ist die Zs OA bzw. lt. der Website CC-BY-NC
Die Datensätze werden jedoch in Pica-4950 nicht als kostenfrei gekennzeichnet.
In der ISSN_to_licence.map ist die pISSN aufgeführt, habe zur Sicherheit eISSN ergänzt (Zotero exportiert jedoch pISSN)
Bsp.-Hash: IxTheo#2020-02-28#9B3D33343C67C62AF0470B1E69B3F0EB60FF9A5E

siehe auch: #657

**Comment by mtrojan-ub** [comment]
kann getestet werden

**Comment by IxKo** [comment]
LF wird nun in Unterfeld z nach einem Test ausgegeben:

![grafik](https://user-images.githubusercontent.com/57000004/82902365-a52b2880-9f5f-11ea-84a7-6e778a6fef03.png)
