### ISSUE TITLE
ISSN 0717-6295 | Teologia y vida | fehlender Autor und fehlender Buchstabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#715]
**URL**
https://scielo.conicyt.cl/scielo.php?script=sci_arttext&amp;pid=S0049-34492019000400439&amp;lng=es&amp;nrm=iso&amp;tlng=es
(führt zu HTTP 500-Fehler)
Dies ist die URL im Browserfenster, wenn ich den Artikel über den DOI abrufe:
https://scielo.conicyt.cl/scielo.php?script=sci_arttext&pid=S0049-34492019000400439&lng=en&nrm=iso&tlng=en

1.  https://doi.org/10.4067/S0049-34492019000400439

1. https://doi.org/10.4067/S0049-34492019000400497

**Ausführliche Problembeschreibung**

1. Die Autoren werdenin der Quelldatei nicht angegeben.
 IxTheo#2020-02-28#1571ABEC2E03AC796165E009DB947CD1F02E06F1

4. Der erste Buchstabe des Nachnamens fehlt in der Quelldatei.
IxTheo#2020-02-28#4583F544C59FB2E5FE6F6069A337489AF1BC669C

**Comment by mtrojan-ub** [comment]
Das mit dem Buchstaben ist vermutlich das selbe Problem wie bei #888

**Comment by mtrojan-ub** [comment]
Die Änderung wurde heute eingespielt + kann jetzt erneut getestet werden (z.B. per "Try URL")

**Comment by IxKo** [comment]
Beim 2. Fall wird der Autor nun richtig ausgegeben.
Beim 1. Fall fehlen weiterhin die Autoren Fernando Berríos und Fernando Soler. (https://doi.org/10.4067/S0049-34492019000400439)

**Comment by mtrojan-ub** [comment]
Dass die Autoren komplett fehlen liegt nicht am Harvester => Translator Problem

**Comment by socheres** [comment]
Problem mit dem Translator SciELO.js

**Comment by IxKo** [comment]
Problem 1 besteht weiterhin.

**Comment by hlindeboom** [comment]
Der Translator wurde angepasst und die Änderung auf nu eingespielt.

**Comment by IxKo** [comment]
Autoren sind nun vorhanden, danke!
