### ISSUE TITLE
ISSN 2150-9301 | Religion and Society | Book reviews als ein Datensatz mit allen Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#716]
**URL**
https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml

**Ausführliche Problembeschreibung**
Hier sind unter einem Datensatz mit dem Titel "Book Reviews" alle Rezensionen des Heftes mit allen Rezensenten als Autor:innen enthalten. Es ist zu klären, ob so etwas herausgefiltert oder so belassen werden kann.
IxTheo#2020-02-28#7F163615C41C893C28FF458A6F2E12E66C06B1AD

**Comment by socheres** [comment]
Sammelrezension herausfiltern. analog zu #700

**Comment by socheres** [comment]
"Sammlung von Rezensionen" wird herausgefiltert.https://github.com/ubtue/DatenProbleme/issues/811#issuecomment-634644739

**Comment by IxKo** [comment]
Habe auf Nu versucht mit dem Link des neuen Issues (https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/religion-and-society.10.issue-1.xml) zu testen. 
Es wird aber nur das Heft als ein einziger Record erfasst, nicht die einzelnen Artikel.
Normalerweise teste ich so auf Nu. Ist das hier nicht richtig?

**Comment by IxKo** [comment]
Wenn ich nur mit der URL der Rezensionssammlung auf Nu teste, wird dies nicht herausgefiltert. Würde es herausgefilter, wäre der result File leer.

**Comment by IxKo** [comment]
Ist noch immer enthalten.

**Comment by socheres** [comment]
mit "Try URL" getestet

```
MARC field for 'https://www.berghahnjournals.com/view/journals/religion-and-society/10/1/arrs100113.xml matched exclusion filter (245a/((Book (R|r)eview))|((Book (R|r)eviews))/)
Conversion complete
```
