### ISSUE TITLE
Auffällig bei Einspielung 2020-02-29 | kaum Autor:innen-PPN-Verknüpfungen

### ISSUE THREAD

**Issue by theo-ko** [ubtue/DatenProbleme#717]
**Ausführliche Problembeschreibung**
Von 1560 Datensätzen ist nur bei einem Datensatz (KrimDok#2020-02-28#792D939E1B24F3F84A8E84E3A2B007DF44370165) ein Autor verknüpft.

**Beispiel-Stichprobe:**
Nimmt man den Autor "Metzger, Marcel" aus diesen Datensatz (IxTheo#2020-02-28#1BB908F3C8CB9CADC27CB599FA438B18D4D0907A)  und sucht im K10plus mit "per metzger, Marcel" erhält man einen Personentreffer:
005 Tpv3
006 http://d-nb.info/gnd/172256798
008 piz
011 f
035 gnd/172256798
039 pnd/172256798$vzg
043 XA-FR
100 Metzger, Marcel
548 1940$4datl
550 !104452013!Theologe ; ID: gnd/4059756-8$4berc
550 !106294369!Hochschullehrer ; ID: gnd/4025243-7$4beru
678 $bFranz. Theologe, Strasbourg, Histoire de la liturgie et des institutions chrétiennes
797 697167658
798 133125068

Trotzdem wurde Herr Metzger nicht verknüpft. Woran könnte das liegen?

**Comment by socheres** [comment]
das deckt sich mit meinen Beobachtungen. Wollte dies aber sowieso ansprechen. @shadeMe Lookup-Fuktion in Harvester funktioniert zurzeit nicht.

**Comment by theo-ko** [comment]
@socheres Das Problem scheint weiterhin zu bestehen.

**Comment by socheres** [comment]
@mtrojan-ub schaust du dir bitte diesen fall prioritär an? Ohne Autorenverknüpfung können wir nicht live gehen. Schickst du mir auch die entsprechende Code-Stelle, damit ich die Logik verstehe und ggfs. ändere.

**Comment by mtrojan-ub** [comment]
Ist behoben.

Beim SWB-Lookup gab es ein Problem da das Auslesen der PPN per Screen Scraping passiert (ähnlich wie bei den Zotero Translators) und sich die Website verändert hat. Das Feld heißt jetzt nicht mehr nur "PPN" sondern "K10plusPPN".

Außerdem führen wir ja auch noch einen GND Lookup mit der Lobid API durch. Der ist für die IxTheo-Zeitschriften bisher ebenfalls fehlgeschlagen, weil die Suchsyntax inkorrekt war (es hat etwas mit den OR-Verknüpfungen im Feld professionOrOccupation.label nicht gestimmt).

@socheres: Die commits wurden mit diesem Issue verknüpft (siehe oben), falls Du Dir den Code anschauen möchtest.

**Comment by mtrojan-ub** [comment]
PS falls Ihr es per Oberfläche nochmal testen wollt, das Beispiel ist aus der Zeitschrift "Revue des Sciences Religieuses", ISSN 2259-0285, ist heute noch reproduzierbar

**Comment by socheres** [comment]
@Hi Mario, da wir in Zotaut GND-ID statt PPN verwenden, muss du den Xpath bzw. CSS korrekt angeben.

**Comment by mtrojan-ub** [comment]
Zotaut macht 2 Abfragen:
- PPN über SWB
- GND über Lobid API

In beiden waren Fehler und beides ist behoben. Die GND über eine API abzufragen ist ja in jedem Fall sicherer als per Screen Scraping, sonst ändert das BSZ mal wieder die Seite und dann müssen wir es schon wieder korrigieren

**Comment by socheres** [comment]
OGND-Seite ändert sich nicht ständig und PPN zu scrapen, mach in Zotaut keinen Sinnn, da der Export in MARC GND-ID verlangt. Wenn OGND fehlschlägt, dann fragt man zur Sicherheit auch noch lobid-API ab. So sind wir auf sicheren Seite.

**Comment by mtrojan-ub** [comment]
OK dann muss ich den Teil nochmal umschreiben

**Comment by mtrojan-ub** [comment]
So, das Verhalten wurde geändert. Beim SWB Lookup wird jetzt nur noch die GND Nummer ausgelesen. Schlägt das SWB Lookup fehl wird versucht die GND-Nummer aus Lobid abzufragen.

**Comment by theo-ko** [comment]
In der neuen Einspielung sind mehrere AutorInnen nun verknüpft. Somit scheint der Fehler behoben zu sein.
