### ISSUE TITLE
ISSN 1572-543X | Exchange | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#719]
Sofern kein als solches gekennzeichnetes Abstract existiert, das sind alle Beiträge, die keine "Artikel" sind, wird bei dieser Zeitschrift eines generiert, dass sich aus verschiedenen Angaben zusammensetzt, die auf der Webseite zu finden ist.
Eine Ausgabe der Zeitschrift:
https://brill.com/view/journals/exch/49/1/exch.49.issue-1.xml
ein Artikel:
https://brill.com/view/journals/exch/49/1/article-p77_5.xml
Das, was im Zotero-Feld Zusammenfassung dann steht:
"Essays in Contextual Theology, written by Stephen Bevans" published on 27 Feb 2020 by Brill.

Die Frage, ob man so etwas so stehen lassen kann oder soll, sollte von anderer Stelle beantwortet werden.

**Comment by socheres** [comment]
der oben erwähne Artikel ist eine Rezension. Diesen Fall besprechen wir in der nächsten Abteilungsrunde.

![grafik](https://user-images.githubusercontent.com/1545743/75991857-5ee1a280-5ef7-11ea-94a2-e4db7ff3bc50.png)

**Comment by kdr154** [comment]
Ich habe es ganz bewusst so allgemein formuliert. Natürlich weiß ich, dass es sich um eine Rezension handelt. Was aber, wenn es Beiträge sind, die keine Rezensionen sind.

**Comment by socheres** [comment]
diese Zeitschrift ist in Nu auf "zotat" gesetzt.

**Comment by socheres** [comment]
Titel wird nicht mehr als Abstract heruntergeladen. @kdr154 Kann dieses Issue geschlossen werden?

**Comment by kdr154** [comment]
Wäre vielleicht möglich, wenn mir der Translator Brill Journals angeboten würde. Wird er aber nicht. Nicht nur  hier, sondern auch bei anderen Zeitschriften von Brill. So werden die Artikel mit Embedded Metadata heruntergeladen und dort ist es weiterhin so, dass der Titel ins Abstract geladen wird:

https://brill.com/view/journals/exch/49/1/article-p82_7.xml

![grafik](https://user-images.githubusercontent.com/29707105/116986450-15910c80-acce-11eb-8bdf-5ee365e0e985.png)

**Comment by socheres** [comment]
"ubtue_Brill" war nicht in Ihrem Verzeichnis vorhanden. Jetzt müsste es funktionieren.

**Comment by kdr154** [comment]
Jetzt passt es.
