### ISSUE TITLE
Muse ISSN 0080-5459 Franciscan Studies

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#72]
Dieser Feed liefert die Liste der letzten Ausgaben:
https://muse.jhu.edu/feeds/latest_issues?jid=457
Der Zugriff auf die Metadaten liegt dahinter.

**Comment by kdr154** [comment]
In dieser Form sicher nicht, denn der Harvester müsste zwei Stufen tiefer eingreifen. Auf der Ebene des Aufsatzes. Erst hier bekomme ich in Zotero Zugriff auf die Metadaten.
Aber ich frage mich, ob der Feed überhaupt noch weitergeführt wird. Auf den Seiten von Muse wird er für diese Zeitschrift nicht mehr angeboten

**Comment by shadeMe** [comment]
Ich habe das "Multiple"-Verfahren des Translators gefixt. Im Prinzip sollte das RSS-Verfahren jetzt ungeändert funktionieren.

**Comment by kdr154** [comment]
Es hat sich nichts geändert. Leere XML-Datei

**Comment by mtrojan-ub** [comment]
Im Log waren Timeout-Fehler erkennbar - 10 Sekunden pro Download als Limit für Zotero sind wohl in manchen Fällen doch zu wenig. Habe es auf 30 erhöht. Bitte nochmal ausprobieren!

**Comment by kdr154** [comment]
Gelöst
