### ISSUE TITLE
ISSN 1468-0025 | Modern Theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#720]
Rezensionen werden nicht als solche getagt. Vgl. etwa Hash:
AE991D2462F6B84E07A964CF70BA9A90367EFE8A
Im Heft: https://onlinelibrary.wiley.com/toc/14680025/2020/36/1
Siehe auch #709 ebenfalls Wiley

**Comment by kdr154** [comment]
Obwohl die conf entsprechend konfiguriert ist:
https://github.com/ubtue/zotero-enhancement-maps/blob/907624501e44b38032234a6c7cbf610667e90806/zotero_harvester.conf#L3799
Ist dies bei einem aktuellen Test auf nu weiterhin der Fall:
![grafik](https://user-images.githubusercontent.com/29707105/79449107-ea644e00-7fe2-11ea-865c-11150362a705.png)

**Comment by mtrojan-ub** [comment]
Ist vermutlich ein Translator Problem. Da vom Translator in den Tags "Book Review, Book Review" und nicht "Book Review" eingefügt wird matcht `zotero_review_regex       = "^Book Reviews?$"` nicht

**Comment by socheres** [comment]
mit "Try URL" getestet. `https://github.com/ubtue/DatenProbleme/issues/720`
