### ISSUE TITLE
ISSN 1468-0025 | Modern Theology | Beziehungen und Inhalte allgemein

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#721]
Dieses Heft https://onlinelibrary.wiley.com/toc/14680025/2020/36/1
besitzt eine Reihe von Elementen, die in der vollautomatischen Einspielung (bis jetzt) nicht erfasst werden
- die gegenseitige Bezugnahme, z.B. response to..., die wir in Pica über die Felder 4261 (z.b. Kritik an) und 4262 (z.B. Kritik in) dokumentieren.
- Rubrikentitel: z.B. Book Symposium (wenn es auch hier nur eine Überschrift über eine Sektion ist, vereint diese doch Artikel, die in einer Weise enger zusammengehören, als die Artikel, die in der Sektion Artikel stehen. Oft sind diese Symposien näher benannt, so dass es eindeutig ist, dass es sich um einen Rubrikentitel handelt)
Die Rubrikentitel werden in Pica 4212 für jeden Artikel, der dazu gehört, vergeben.
- Review Essays, Artikel, bei denen wir im halbautomatischen Verfahren die Verknüpfung zum rezensierten Wert herstellen.

Ich bitte um Rückmeldung, ob wir zu den oben genannten Punkten in Zukunft überhaupt noch Issues anlegen sollen

**Comment by socheres** [comment]
diese o.g. Verweise lassen sich nicht automatisieren. Bitte keine Issues mehr dazu schreiben, bis wir sie in Meeting geklärt haben.

**Comment by kdr154** [comment]
In der DB vom 5.11.2020 wurde beschlossen, dass nicht nachverknüpft wird sondern die Daten unverknüpft eingespielt und so belassen werden.
