### ISSUE TITLE
ISSN 2118-4518 | Revue d'éthique et de théologie morale | Zusatztitel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#722]
https://www.cairn.info/revue-d-ethique-et-de-theologie-morale-2019-4.htm
Die Zusatztitel werden nicht erfasst, wenn sie in einer neuen Zeile stehen

**Comment by socheres** [comment]
ubtue_cairn verwenden  #1150 #1272

**Comment by kdr154** [comment]
Zusatztitel nun dabei
