### ISSUE TITLE
ISSN 1468-2400 | International journal of systematic theology | Intruction und Issue Information

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#724]
Intruction kann auch hier übergangen werden
Hash C43A288E183CA682BF65C169F4963C1FA74A7E57
Issue Information möglicherweise auch. Jedoch befindet sich hier, wie auch in den anderen Zeitschriften von Wiley, neben allgemeinen Informationen zur Zeitschrift an sich, auch das Inhaltsverzeichnis des jeweiligen Hefts. Dies ist ein Element, das man bei der Kataloganreicherung hinzuzieht.

**Comment by socheres** [comment]
bitte immer einen persistenten Link angeben.

**Comment by IxKo** [comment]
@socheres https://doi.org/10.1111/ijst.12390 Das ist der PI zum Fall
