### ISSUE TITLE
ISSN 0014-5246 | The Expository Times | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#725]
Der Sage Journals  Translator übernimmt auch beim Einzeldownload keine Keywords. 
Etwa hier:
https://journals.sagepub.com/doi/full/10.1177/0014524619866572
https://journals.sagepub.com/toc/exta/131/6
Es ist zwar schön, dass an anderer Stelle bereits an dem Translator gearbeitet wird, aber dieser Publisher wird von uns so oft genutzt, dass sich im meinen Augen eine lokale Anpassung lohnen würde.

**Comment by socheres** [comment]
diese Zeitschrift ist auf "zotat"

**Comment by IxKo** [comment]
Solange noch nichts im Live-Betrieb ist, müssen die Aufsätze doch solange trotzdem mit anderen Verfahren erfasst werden, oder nicht?
