### ISSUE TITLE
ISSN 2153-3326 | Business ethics quarterly | Unnötige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#726]
Folgende Artikel nicht mit erfassen:
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/from-the-editor/50B8AD6C42CC279F01DBADFB15799537
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/from-the-editor/50B8AD6C42CC279F01DBADFB15799537
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/from-the-editor/50B8AD6C42CC279F01DBADFB15799537

**Comment by IxKo** [comment]
Das Editorial wird nicht mehr erfasst. Allerdings gibt es noch zwei weitere Titel, die wir nicht wollen:


   *  "BEQ volume 30 issue 1 Cover and Front matter"
   * "BEQ volume 30 issue 1 Cover and Back matter"

**Comment by IxKo** [comment]
gelöst
