### ISSUE TITLE
ISSN 2153-3326 | Business ethics quarterly | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#727]
Rezensionen werden nicht als solche getagt. Vgl. etwa:
Hash E366126868E242D2A2E5B06D64849CE7D4DDDED6

**Comment by mtrojan-ub** [comment]
... ist in der Datei zotero_ixtheo_200228_001.xml in 655a als Rezension markiert, stimmt der Hash?

![grafik](https://user-images.githubusercontent.com/26873381/82682658-e49c0100-9c4f-11ea-8b13-ad47302c8be2.png)

**Comment by IxKo** [comment]
@mtrojan-ub 
Nach einer Suche über alle Dateien im Ordner Default_Test scheint es der gefundene Datensatz zu sein. 655 Rezension wird vergeben.
Da ich das Issue nicht geöffnet habe, kann ich nicht mit Gewissheit sagen, ob vielleicht doch etwas anderes gemeint war.

**Comment by socheres** [comment]
bitte immer einen persistenten URL oder DOI angeben

**Comment by kdr154** [comment]
Aber die Rezensionen scheinen getagt.
