### ISSUE TITLE
ISSN 1437-1618 | Ethik in der Medizin | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#728]
Rezensionen werden nicht als solche getagt.
https://link.springer.com/journal/481/32/1
Etwa Hash 993AA36952E5BEFB41C9988DD4AD360EC6E45409

**Comment by IxKo** [comment]
Werden weiterhin nicht erkannt

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
