### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Seitenzahl wird nicht ausgegeben

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#729]
Bei Artikeln, die nur einen Umfang von einer Seite haben, wird die Seitenzahl zwar erfasst, aber nicht in den K10Plus ausgegeben. Vgl. 773g und 936g in
Hash D4A51A29F27BDF29018B1F0DDC999FC0C412BEB3
Vorlage: https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/writing-of-elizabeth-webb-a-quaker-missionary-in-america-16971726-edited-by-rachel-cope-and-zachary-mcleod-hutchins-pp-x-226-university-park-pa-pennsylvania-state-university-press-2019-1795-paper-978-0-271-08223-3/DBB3001565F3C84F8E9FCE4A229EA228

**Comment by socheres** [comment]
BSZ wird den Konverter anpassen.

**Comment by kdr154** [comment]
gelöst
