### ISSUE TITLE
ISSN 2397-348X | Interreligious studies and intercultural theology | Irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#730]
**URL**
https://journals.equinoxpub.com/index.php/ISIT/article/view/38939
IxTheo#2020-02-28#B9834F685BAB49FEAC24A2338942BE5C4ACA53B5

**Ausführliche Problembeschreibung**
Hier handelt es sich um Werbung, die nicht in den K10plus eingespielt werden sollte.

siehe auch: #700

**Comment by socheres** [comment]
kein klares Muster erkennbar, ob es sich um eine Werbung handelt.

**Comment by IxKo** [comment]
Das Muster könnte sein, dass das ausgegebene "Abstract" so aussieht:
"Receive 20% OFF these books when you use code ISIT19 at www.jkp.com"

**Comment by IxKo** [comment]
In den anderen vorhandenen Heften online, kam die Rubrik Advertising nicht vor. Es ist zu hoffen, dass es eine einmalige Sache war.
