### ISSUE TITLE
ISSN 2397-348X | Interreligious studies and intercultural theology | DOIs ungültig und zweiter URL fehlt in Pica-4950

### ISSUE THREAD

**Issue by theo-ko** [ubtue/DatenProbleme#731]
**Bsp.-URL**
https://journals.equinoxpub.com/index.php/ISIT/article/view/35584
IxTheo#2020-02-28#65F3AD8B7E5B62731811CE152C8885557BD691EE

**Ausführliche Problembeschreibung**
Der DOI-Link führt zur Fehlerseite DOI not found. Zudem wird der zweite URL nicht in einem weiteren Feld Pica-4950 ausgegeben. Dieser zweite URL bringt einem zum Artikel.

siehe auch: #710

**Comment by socheres** [comment]
BSZ wird den Konverter anpassen.
