### ISSUE TITLE
ISSN 1703-8804 | Laval théologique et philosophique | zusätzlicher URI

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#736]
**Bsp.-URL**
http://www.erudit.org/fr/revues/ltp/2019-v75-n1-ltp05123/1067504ar/
IxTheo#2020-02-28#304123CFF0CC69C898E7479A56267E2F35CE0D8E

**Ausführliche Problembeschreibung**
Aufsätze besitzen URI auf den Webseiten. Dieser sollte als zusätzlicher Link in Pica-4950 ausgegeben werden.

**Comment by socheres** [comment]
URI als weiterer PI aufzunehmen ist etwas aufwändig. 1x DOI 1x URL suffizient. 
``
<datafield tag="024" ind1="7" ind2=" "><subfield code="a">https://doi.org/10.7202/1067504ar</subfield><subfield code="2">doi</subfield></datafield>
``
``
<datafield tag="856" ind1="4" ind2="0"><subfield code="u">https://doi.org/https://doi.org/10.7202/1067504ar</subfield><subfield code="z">KW</subfield></datafield><datafield tag="856" ind1="4" ind2="0"><subfield code="u">https://www.erudit.org/fr/revues/ltp/2019-v75-n1-ltp05123/1067504ar/</subfield><subfield code="z">KW</subfield></datafield>
``

**Comment by IxKo** [comment]
Da mit dem DOI ein PI angegeben ist und der technische Aufwand für die Angabe des URI zu hoch ist,
schließe ich.
