### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | Kurzrezensionen nicht erkannt und ohne Seitenangabe und mit Anrisstext als Abstract

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#737]
**URL**
http://journals.openedition.org/rsr/3514
IxTheo#2020-02-28#5268FD69E811C8A0EED3B5D556658A584A1F955F

**Ausführliche Problembeschreibung**
Die Kurzrezensionen werden nicht als Rezensionen erkannt und ohne Seitenangaben ausgegeben. In der Quelldatei wurde die Seitenzahl (Umfang 1 Seite) erfasst. (siehe auch: #729)

Zudem haben sie lediglich Anrisstexte als Abstracts mit "…" am Ende.

**Comment by kdr154** [comment]
Die Sache mit den Seitenzahlen ist gelöst, die Problematik mit den Anrisstexten besteht weiter. Hier handelt es sich ausschließlich um Rezenionen. Bei regulären Artikeln besteht dieses Problem nicht.

**Comment by mtrojan-ub** [comment]
Das kommt so aus der Website:
`<meta name="DC.description" content="Le présent dossier rassemble des travaux présentés à Strasbourg le 12 mai 2017, lors de la 2e journée de l’Équipe de recherche sur le christianisme ancien et médiéval (ERCAM) appartenant à l’EA 4377 et rattachée à la Faculté de théologie catholique de notre université. Cette journée d’étude a conclu le projet quinquennal de l’ERCAM, qui portait sur « La théologie de la création : des hommes et des animaux », projet qui avait également donné lieu à un colloque international en mars 2015 sur le..." />`

Lässt sich ggf. mit einem eigenen Translator + Embedded Metadata Postprocessing beheben.

**Comment by socheres** [comment]
Sowohl in IxTheo als auch in PICA wird das Feld nicht ausschließlich für Abstract verwendet. Anrisstext kann daher so stehen bleiben. 
https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4207&katalog=Standard
> Das` Feld 4207 enthält eine inhaltliche Zusammenfassung der Vorlage (Summary, Abstract usw.).

**Comment by IxKo** [comment]
Okay, dann besteht nur noch das Problem, dass die Rezensionen nicht als solche gekennzeichnet werden.

**Comment by socheres** [comment]
wird als Rezension getagt.
