### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#738]
**URL**
1. http://journals.openedition.org/rsr/3633
IxTheo#2020-02-28#E6D4299D1AD227149AB5194A74D6EBA24FC7A61E

2. http://journals.openedition.org/rsr/7068
IxTheo#2020-02-28#69E8A3C72BE95ECC0FAF4C4170AA4AC3F682C77B

3. http://journals.openedition.org/rsr/5934
IxTheo#2020-02-28#CE75B2FB295C03EEEEE5A3A5BF64EE8A8136D97C

**Ausführliche Problembeschreibung**
1. Titel = "Éditorial"
2. Titel = "Table des matières du volume 93 (2019)" (Inhaltsverzeichnis)
3. Titel = "Livres reçus de juillet 2018 à mars 2019" (Auflistung von Büchern)

Editorial ohne besonderen Titel, Inhaltsverzeichnisse und die Auflistung der Bücher sollten nicht aufgenommen werden.

**Comment by socheres** [comment]
gleich getestet. 
https://journals.openedition.org/rsr/7165
https://journals.openedition.org/rsr/6082
https://journals.openedition.org/rsr/3634

**Comment by IxKo** [comment]
@socheres Benötige ich für Nu zum Testen eine additional Config? Denn wenn ich beispielsweise das Heft mit dem Éditorial teste, wird es weiterhin in der Datei ausgeliefert.
