### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | fehlende franz. Abstracts und franz.+engl. Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#739]
**Bsp.-URL**
http://journals.openedition.org/rsr/3514
IxTheo#2020-02-28#B22639686EA4BF6035BE3844350ADAE01F59B466

**Ausführliche Problembeschreibung**
Es fehlen die französischen Abstracts und sowohl die französischen als auch die englischen Keywords im K10plus.

Das französische Abstract befindet sich jedoch in der Quelldatei!!

**Comment by socheres** [comment]
BSZ wird den Konverter anpassen.

**Comment by socheres** [comment]
Was französische Abstract betrifft, wird BSZ den Konverter anpassen. Für Keywords muss Translator angepasst werden.

**Comment by IxKo** [comment]
Abstracts sowie Keywords befinden sich beim Test mit Nu in den Daten.
