### ISSUE TITLE
University of Bergen ISSN 1894-4183 Bergen Journal of Criminal Law & Criminal Justice

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#74]
XML-Datei unbrauchbar

**Comment by mtrojan-ub** [comment]
Bei mir wird eine leere XML-Datei erzeugt. Unten erscheint eine Fehlermeldung:

> Download problem for "https://boap.uib.no/index.php/BJCLCJ/gateway/plugin/WebFeedGatewayPlugin/rss": Peer certificate cannot be authenticated with given CA certificates

Ich schaue mal, was wir da machen können

**Comment by mtrojan-ub** [comment]
Öffnet man den RSS Feed im Browser, so wird auf ein Problem mit dem Zertifikat hingewiesen.

![grafik](https://user-images.githubusercontent.com/26873381/48065395-d7810380-e1ca-11e8-99d9-511356b083d1.png)

Vermutlich verwendet die Seite ein unsicheres SSL-Zertifikat. Können Sie die Betreiber der Webseite bitte darauf hinweisen? (wir wollen nach Möglichkeit verhindern, dass wir eine Unterstützung für unsichere SSL-Zertifikate einbauen müssen).

**Comment by kdr154** [comment]
Habe gemacht.

**Comment by kdr154** [comment]
Gelöst. Die Betreiber der Seite haben auf unsere Bitte reagiert und das Problem behoben.
