### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift | ungeteilte Abstracts

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#742]
**Bsp.-URL**
https://tidsskrift.dk/rvt/article/view/112747
IxTheo#2020-02-28#BCFBDC6F32E98A21444DF0833F410579ABC7B3EB

**Ausführliche Problembeschreibung**
Beide Abstracts (englisch und dänisch) werden in einem Pica-Feld-4207 ausgegeben statt aufgeteilt in zwei.
Außerdem werden zu Beginn die Wörter "Resumé ENGLISH ABSTRACT:" übernommen, das dänische Abstract wird mit "DANSK RESUME:" eingeleitet.

**Comment by socheres** [comment]
@mtrojan-ub kannst du dir bitte den Code reviewen?[ Commit](https://github.com/socheres/translators/commit/d26b901ce15046cfba9864636a74998ab9b97050) Vor allem Strings "DANSK RESUMÉ:" und "ENGLISH ABSTRACT:" kann ich nicht mit replace-Methode entfernen. Ansonsten tut der Translator, was er soll.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Habe jetzt die beiden Abstracts getrennt, die einleitenden Wendungen Dansk Resumé und English abstract sind aber weiterhin enthalten.

**Comment by IxKo** [comment]
Bestätige, dass die Abstracts nun in zwei separaten Feldern getrennt werden und die einleitenden Wendungen ("DANSK RESUMÉ:" und "ENGLISH ABSTRACT:") noch vorhanden sind.

**Comment by socheres** [comment]
@mtrojan-ub habe den Translator angepasst. Nach commit bitte "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by IxKo** [comment]
Sieht schon gut aus:
Beim dänischen Abstract steht am Ende jedoch noch der Ausdruck ",DANSK RESUMÉ" (mit eingeleiteten Komma):

<datafield tag="520" ind1="3" ind2=" "><subfield code="a">Med udgangspunkt i en analyse af kulten omkring den tantriske gudinde Kāmakhya fra Assam diskuteres hendes brede appeal for både lægfolk og asketer. Det specielle ved gudinden er, at hun menstruerer, og at blodet tillægges både thaumaturgiske og transformative egenskaber. For lægfolk er håbet, at det kan have positiv effekt for deres liv nu og her, for asketer at det vil sætte gang i en individuel proces med et soteriologisk mål for øje. I den forbindelse vil en skelnen imellem en hard core- og en soft core-tantrisme og deres interrelation blive præsenteret.**,DANSK RESUMÉ**</subfield>

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing
