### ISSUE TITLE
ISSN 2398-4961 | Moreana | Bandangabe+durchgängige Heftzählung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#743]
**Bsp.-URL**
https://www.euppublishing.com/doi/abs/10.3366/more.2019.0066?af=R
IxTheo#2020-02-28#8CD4A294C3FCF3F461F144EA0C86405D16B1EE96

**Ausführliche Problembeschreibung**
Zusätzlich zur Bandangabe wird eine durchgängige Heftzählung mit angegeben. Normalerweise würde so etwas im K10plus mit $y als modifizierte Anzeigeform angegeben (z. B.: $yNr. 178 (2006) = Heft 1521, Seite 63-74).
Da eine Lösung mit $y wahrscheinlich nicht angestrebt wird, sollte nur die Bandzählung (niedrigere Zahl) ausgegeben werden und die durchgängige Heftzählung (Number x) sollte aus Marc-773 und Marc-936 entfernt werden.

```
<datafield tag="773" ind1="0" ind2="8">
<subfield code="i">In: </subfield>
<subfield code="t">Moreana</subfield>
<subfield code="x">2398-4961</subfield>
<subfield code="w">(DE-627)719412811</subfield>
<subfield code="g">56 (Number 212) (2019), 2, Seite 256-260</subfield>
</datafield>
```

```
<datafield tag="936" ind1="u" ind2="w">
<subfield code="d">56 (Number 212)</subfield>
<subfield code="e">2</subfield>
<subfield code="h">256-260</subfield>
<subfield code="j">2019</subfield>
</datafield>
```

**Comment by socheres** [comment]
@mtrojan-ub soll die durchgängige Heftzählung z.B.  "(Number 212)" harvesterseitig oder translatorsseitig erfolgen? Ich finde harvesterseitig sinnvoller, da einzeln pro Zeitschrift konfiguriert werden kann.

**Comment by mtrojan-ub** [comment]
Da die Heftnummer auf der Website steht scheint mir eine Umsetzung im Translator sinnvoller.

Auf Harvester Seite wäre mir auch gar nicht klar wie man so etwas sinnvollerweise konfigurieren sollte. Einerseits müsste das ja pro Zeitschrift konfiguriert und ggf. automatisch hochgezählt werden, andererseits kann es Fälle geben wo man z.B. einen bereits heruntergeladenen Artikel später neu herunterladen möchte und dann wäre ja z.B. auch die Frage woher jetzt der Harvester an die korrekte alte Heftnummer kommt.

**Comment by IxKo** [comment]
Bandangabe wird weiterhin mit der durchgängigen Heftzählung in Klammern ausgegeben,

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
