### ISSUE TITLE
ISSN 1689-8311 | European journal for philosophy of religion | irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#745]
**URL**
https://webapp.uibk.ac.at/ojs2/index.php/EJPR/article/view/3035
IxTheo#2020-02-28#B6D6569F51FF3F068C530D2A8C1CA243E5EC6DBF

**Ausführliche Problembeschreibung**
"Editorial" ohne besonderen Titel nicht aufnehmen.

siehe auch: #700

**Comment by socheres** [comment]
Test erst nach Aktualisierung der Cofing-Datei (täglich 19h)

**Comment by IxKo** [comment]
Ist gefiltert.
