### ISSUE TITLE
ISSN 2375-5814 | The Asbury Journal | fehlende Seitenangaben

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#747]
**URL**
https://place.asburyseminary.edu/asburyjournal/vol74/iss2/6
IxTheo#2020-02-28#85968BD5EC02E4D1DC988406DAB9A0421E77722E

**Ausführliche Problembeschreibung**
Bei allen Aufsätzen fehlen die Seitenangaben in der Quelldatei.

**Comment by IxKo** [comment]
Seitenangaben fehlen weiterhin

**Comment by socheres** [comment]
Habe vergessen zu sagen, dass das Testen erst nach der Integration des neuen Translator in den Harvester durch @mtrojan-ub möglich ist.

**Comment by IxKo** [comment]
Ok, dann bitte das Label ändern, sobald man den Test durchführen kann.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by IxKo** [comment]
Seitenangabe wird beim Testen auf Nu mit diesem Artikel weiterhin nicht angeeben.
Zudem erscheint beim Feld 520 folgender seltsamer Inhalt:
`<datafield tag="520" ind1=" " ind2=" "><subfield code="a"><!--[if gte mso 9]> Normal.dotm 0 0 1 68 391 Asbury Theological Seminary 3 1 480 12.0 <![endif]--><!--[if gte mso 9]> 0 false 18 pt 18 pt 0 0 false false false <![endif]--><!--[if gte mso 9]> <![endif]--> <!--[if gte mso 10]> /* Style Definitions */ table.MsoNormalTable {mso-style-name:"Table Normal"; mso-tstyle-rowband-size:0; mso-tstyle-colband-size:0; mso-style-noshow:yes; mso-style-parent:""; mso-padding-alt:0in 5.4pt 0in 5.4pt; mso-para-margin:0in; mso-para-margin-bottom:.0001pt; mso-pagination:widow-orphan; font-size:12.0pt; font-family:"Times New Roman"; mso-ascii-font-family:Cambria; mso-ascii-theme-font:minor-latin; mso-fareast-font-family:"Times New Roman"; mso-fareast-theme-font:minor-fareast; mso-hansi-font-family:Cambria; mso-hansi-theme-font:minor-latin;} <![endif]--> <!--StartFragment--> The Asbury Journal publishes scholarly essays and book reviews written from a Wesleyan perspective. The Journal's authors and audience reflect the global reality of the Christian church, the holistic nature of Wesleyan thought, and the importance of both theory and practice in addressing the current issues of the day. Authors include Wesleyan scholars, scholars of Wesleyanism/Methodism, and scholars writing on issues of theological and theological education importance. <!--EndFragment--></subfield>`

Außerdem wird beim Testen mit einer URL eines Heftes (https://place.asburyseminary.edu/asburyjournal/vol74/iss2/) gar keiner der Artikel erfasst, sondern nur ein Datensatz für das ganze Heft.

**Comment by kdr154** [comment]
Außerdem wird beim Testen mit einer URL eines Heftes (https://place.asburyseminary.edu/asburyjournal/vol74/iss2/) gar keiner der Artikel erfasst, sondern nur ein Datensatz für das ganze Heft.
Ist bei mir genauso

**Comment by socheres** [comment]
> Außerdem wird beim Testen mit einer URL eines Heftes (https://place.asburyseminary.edu/asburyjournal/vol74/iss2/) gar keiner der Artikel erfasst, sondern nur ein Datensatz für das ganze Heft.
> Ist bei mir genauso

der Translator "ubtue_Asbury Journal" unterstützt nur im "Try RSS" das Multi-DW, aber nicht im "Try URL".

@mtrojan-ub im Zotero-Client sind die Seitenzahlen vorhanden. Translator auf ubtue ist auch aktuell. Warum diese Abweichung?
![image](https://user-images.githubusercontent.com/1545743/86228594-d9ad8800-bb8e-11ea-9d79-41408ae1a842.png)

**Comment by kdr154** [comment]
Mit Try RSS fatal error:

![grafik](https://user-images.githubusercontent.com/29707105/86241286-f358ca80-bba2-11ea-83f4-f3374d3c2012.png)

**Comment by mtrojan-ub** [comment]
@socheres , wahrscheinlich wird der Translator gar nicht gefunden weil die Dateiendung ".js" fehlt. Bitte korrigieren.

Den fatal error schaue ich mir schnellstmöglich an, das könnte an einer Änderung im Harvester von vorhin liegen.

**Comment by socheres** [comment]
@mtrojan-ub ist korrigiert.

**Comment by mtrojan-ub** [comment]
Der fatal error wurde behoben, ich melde mich nochmal sobald der Translator auf nu aktualisiert wurde.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Seitenangaben sind jetzt enthalten, jedoch kommt es in einem Fall zu einer Fehlinterpretation.
Bei folgendem Artikel: https://place.asburyseminary.edu/asburyjournal/vol74/iss2/7/
The Capital of Methodism: The New York Station: 1800-1832
werden die Jahresangaben fälschlicherweise als Seitenzahlen interpretiert:

![grafik](https://user-images.githubusercontent.com/29707105/86250505-f5298a80-bbb0-11ea-9d01-c1b963c91757.png)

auch in 773

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing
