### ISSUE TITLE
ISSN 2375-5814 | The Asbury Journal | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#748]
**URL**
1. https://place.asburyseminary.edu/asburyjournal/vol74/iss2/13
IxTheo#2020-02-28#E710429D9F57A0FBBFAA3657261B2A1C9E34F560
2. https://place.asburyseminary.edu/asburyjournal/vol74/iss2/1
IxTheo#2020-02-28#C31C65D49D4053FC508CEAB299E2102C49B1E969
3. https://place.asburyseminary.edu/asburyjournal/vol74/iss2/2
IxTheo#2020-02-28#3F75BDC92C55A308727E250D15901EAC2872850A

**Ausführliche Problembeschreibung**
1.  Titel = "Book Reviews", mehrere Rezensionen gebündelt
2. Titel = "Journal in Entirety", komplettes Heft
3. Titel = "From the Editor"

Datensätze nicht einspielen.
Sammlung von Rezensionen ist noch zu klären, ob diese so eingespielt werden können.

siehe auch: #700

**Comment by IxKo** [comment]
Fall 1 besteht noch. Im aktuellen Heft heißt es: "Book Reviews and Books Received" (https://place.asburyseminary.edu/asburyjournal/vol75/iss1/11/)

**Comment by socheres** [comment]
mit "Try URL" getestet.
```
MARC field for 'https://place.asburyseminary.edu/asburyjournal/vol75/iss1/11/ matched exclusion filter (245a/(^Book Reviews)|(^Journal in Entirety$)|(^From the Editor$)/)
Conversion complete
```

```
erased field '650a' due to removal filter '^Book Reviews?'
MARC field for 'https://place.asburyseminary.edu/asburyjournal/vol74/iss2/13 matched exclusion filter (245a/(^Book Reviews)|(^Journal in Entirety$)|(^From the Editor$)/)
Conversion complete
```
