### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion | Editorial preface

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#749]
Die Editorial preface können auch unterdrückt werden
74DD12399C5E5EC57D0AC70655932B22596D7DF8
https://link.springer.com/article/10.1007/s11153-020-09743-1

**Comment by kdr154** [comment]
Beim Testen mit den URLs, beispielsweise https://link.springer.com/journal/11153/volumes-and-issues/87-1, bekomme ich die Fehlermeldung:

XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: http://benu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_4JV6HG/ixtheo/kETuRm.xml
Zeile Nr. 1, Spalte 1:

**Comment by IxKo** [comment]
Wird nun über exclude_if_marc245a in Conf gelöst.
