### ISSUE TITLE
ISSN 1468-2265 | Heythrop journal | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#752]
Bei Artikeln von einem Umfang von nur einer Seite wird die Seitenzahl nicht in den K10plus eingespielt, obwohl in der Quelldatei  vorhanden.
Etwa Hash DC4DF72A9D0E9F8EF43E2EBEC88DBE0EE2499D61
Vgl. auch #729

**Comment by socheres** [comment]
BSZ wird den Konverter anpassen.

**Comment by kdr154** [comment]
Sollte gelöst sein
