### ISSUE TITLE
ISSN 2375-5814 | The Asbury Journal | Abstracts und Keywords in PDF-Dateien

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#754]
**URL**
https://place.asburyseminary.edu/asburyjournal/vol74/iss2/8
IxTheo#2020-02-28#19FB84A1820C9B3F6757F779F01A9EE56A727670

**Ausführliche Problembeschreibung**
Auf der Webseite des Artikels sind keine Keywords und Abstract zu sehen. Jedoch finden sich diese Informationen im PDF.
Ist es möglich dies aus den Dateien herauszuziehen und zu nutzen?

**Comment by socheres** [comment]
wenn die Angaben nur in PDF zu sehen sind, ist es nicht möglich diese abzugreifen.

**Comment by theo-ko** [comment]
Okay, schade.
Sollte dann entschieden werden, dass die Zs besser manuell bzw. halbautomatisch katalogisiert werden sollte?

**Comment by IxKo** [comment]
Sind weiterhin nicht dabei. Doch wie ich es verstanden habe, ist es sowieso nicht möglich Informationen aus der PDF-Datei zu ziehen?

**Comment by socheres** [comment]
bei OA-Zeitschriften werden wir die Volltexte durchsuchbar machen, daher kann diese Zeitschrift ohne Keywords und Abstract im Zotaut-Verfahren erfasst werden. Bitte Issue schließen.
