### ISSUE TITLE
ISSN 2197-0823 | Pastoraltheologie | Artikelauswahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#755]
Inhalt und Vorwort können entfallen. 
hier nur exemplarisch:
https://www.vr-elibrary.de/toc/path/109/2

**Comment by socheres** [comment]
hier bitte genaue Vorgaben formulieren, welche Wörter im Titel als Ausschlusskriterien gelten sollten.

**Comment by kdr154** [comment]
Inhalt$ und Vorwort$

**Comment by kdr154** [comment]
Inhalt wurde entfernt, Vorwort ist weiterhin enthalten:

https://www.vr-elibrary.de/toc/path/109/2


![grafik](https://user-images.githubusercontent.com/29707105/87304507-3442ce80-c515-11ea-82f6-d1820d051d8c.png)

**Comment by kdr154** [comment]
Gelöst
