### ISSUE TITLE
ISSN 2397-1770 | Quaker studies | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#756]
**URL**
1. https://online.liverpooluniversitypress.co.uk/doi/abs/10.3828/quaker.2019.24.2.9?ai=31h&amp;mi=3h6zu8&amp;af=R</
IxTheo#2020-02-28#E68AD9DF62E50129C5C030A0D7F4D9E25F745856
2. https://online.liverpooluniversitypress.co.uk/doi/abs/10.3828/quaker.2019.24.2.10?ai=31h&amp;mi=3h6zu8&amp;af=R
IxTheo#2020-02-28#FCE5BA4CCC8F9F8048BEFCE60F0F84290F1BF6FC

**Ausführliche Problembeschreibung**
1. Titel = "Book Reviews", Sammlung aller Rezensionen
2. Titel = "Short notices", Auflistung von Buchtiteln

Diese Titel nicht einspielen. Bzgl. der Sammlung aller Rezensionen eines Zs-Heftes, ist zu klären, ob dies doch so aufgenommen werden kann.

Siehe auch: #700

**Comment by IxKo** [comment]
Beides noch da.
Ergänze noch:
3. Titel = Editorial

**Comment by socheres** [comment]
mit "Try URL" getestet.

MARC field for 'https://online.liverpooluniversitypress.co.uk/doi/abs/10.3828/quaker.2019.24.2.9?ai=31h&mi=3h6zu8&af=R matched exclusion filter (245a/(Book Reviews)|(Short notices)|(Editorial)/)
Conversion complete

MARC field for 'https://online.liverpooluniversitypress.co.uk/doi/abs/10.3828/quaker.2019.24.2.10?ai=31h&mi=3h6zu8&af=R matched exclusion filter (245a/((Book (R|r)eviews))|((Short (N|n)otices))|(Editorial)/)
Conversion complete
