### ISSUE TITLE
ISSN 2053-6712 | Secularism and Nonreligion | Artikelnummern statt Seitenangabe

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#758]
**Bsp.-URL**
https://secularismandnonreligion.org/article/10.5334/snr.92
IxTheo#2020-02-28#8906DFCD5D47DB3D931F5C84F77BBFF05DC39899

**Ausführliche Problembeschreibung**
Bei dieser Zeitschrift fehlen die Angabe der Seiten. 
Zudem besitzen die Artikel Nummern. Im K10plus müssten diese in der Modifizierten Anzeige unter $y beschrieben werden, während die Seitenangabe immer bei 1 beginnt:
Bsp.
4070 $v33$j2018$a3/5$p1-23$yVolume 33 (2018), number 3-5, **article 4**, Seite 1-23

sieeh auch: #676

**Comment by mtrojan-ub** [comment]
Laut #676 soll ja die Zeitschrift aus dem Verfahren genommen werden.

**Comment by mtrojan-ub** [comment]
Zeitschrift steht aktuell wieder auf TEST. Die Seitenangabe fehlt weil `suppress_json_field_pages = .*` konfiguriert ist:
https://github.com/ubtue/zotero-enhancement-maps/blob/500438c41d7c14a205a2285d3eee8d578c333fd5/zotero_harvester.conf#L4709

Eine Artikelnummer spielen wir meines Wissens nach aktuell nicht aus, aber vermutlich gibt es im Zotero Datentyp kein Feld in dem sowas reingeschrieben werden könnte?

**Comment by IxKo** [comment]
Wie ist hier der Stand? Sollen solche Fälle aus dem zota-Verfahren raus?

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
