### ISSUE TITLE
Springer ISSN 1871-014X Supervised Machine Learning Approach Discovers Protective Sequence for Avoiding Sexual Victimization in Criminal Suit Documents

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#76]
Ist ein First Online Artikel. Noch keiner Ausgabe zugeordnet. Deshalb sind 773 und 936 unvollständig.
Siehe: https://link.springer.com/article/10.1007%2Fs11417-018-9273-1
First Online und bereits publizierte Artikel vermischen sich in diesem Feed.

**Comment by mtrojan-ub** [comment]
Das ist aber ein Problem des Feeds an sich, oder? Gibt's dazu ein konkretes ToDo für uns Entwickler?

**Comment by kdr154** [comment]
Gelöst
