### ISSUE TITLE
ISSN 1549-6538 | The journal of religion | Masthead

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#763]
Diese Artikel bitte unterdrücken
Hash 9A03E144F31BA1B054F03D0BCEFEE49F02AA254B

**Comment by socheres** [comment]
#761

**Comment by kdr154** [comment]
Der Artikel ist immer noch enthalten:
https://www.journals.uchicago.edu/toc/jr/2020/100/1
https://www.journals.uchicago.edu/doi/abs/10.1086/708259

![grafik](https://user-images.githubusercontent.com/29707105/87302434-af09ea80-c511-11ea-9d4e-c1a9356fe9d0.png)

**Comment by kdr154** [comment]
Immer noch enthalten:

![grafik](https://user-images.githubusercontent.com/29707105/87427259-ce237d80-c5e0-11ea-856a-8b6e93dedabf.png)

**Comment by socheres** [comment]
mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_dSlUeq" "--output-filename=FXEbvc.xml"  "--config-overrides=remove_marc_field_650a     = "^Book Reviews?$" zotero_review_regex        = "^Book Reviews?$" exclude_if_marc_field_245a = "(^(Front\|Back) (M\|m)atter)\|(^Masthead)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://www.journals.uchicago.edu/doi/abs/10.1086/708259" "The  journal of religion"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The journal of religion' \| DIRECT @ https://www.journals.uchicago.edu/doi/abs/10.1086/708259 set download-delay for domain 'www.journals.uchicago.edu' to 1000 ms   Harvesting URL 1 [The journal of relig...] \| https://www.journals.uchicago.edu/doi/abs/10.1086/708259 {18188477543926110101} Harvest successful     Converting item 1 [The journal of relig...] \| https://www.journals.uchicago.edu/doi/abs/10.1086/708259 {18188477543926110101} converted roman numeral page range 'i-i' to decimal page range '1-1' use online ISSN "1549-6538" with online PPN "329085689" Augmented metadata record: MetadataRecord { 	url: https://www.journals.uchicago.edu/doi/abs/10.1086/708259, 	item_type: journalArticle, 	title: Masthead, 	publication_title: The journal of religion, 	volume: 100, 	issue: 1, 	pages: 1, 	date: 2020-01-01, 	doi: 10.1086/708259, 	language: eng, 	issn: 1549-6538, 	superior_ppn: 329085689, 	superior_type: 2, 	ssg: 1, } MARC field for 'https://www.journals.uchicago.edu/doi/abs/10.1086/708259 matched exclusion filter (245a/(^(Front\|Back) (M\|m)atter)\|(^Masthead)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
