### ISSUE TITLE
ISSN 1890-7008 | Nordic journal of religion and society | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#764]
**URL**
1. https://www.idunn.no/nordic_journal_of_religion_and_society/2019/02
IxTheo#2020-02-28#BDCFAC09BA485C0758ED0B5229D0A85AF9F30579
2. https://www.idunn.no/nordic_journal_of_religion_and_society/2018/02
IxTheo#2020-02-28#33C14ED834072ACC6112175079BB68AA9F827813
3. https://www.idunn.no/nordic_journal_of_religion_and_society/2018/02
IxTheo#2020-02-28#680C2F92E544F46EC53EA9B556CAB6442490F7B8
4. https://www.idunn.no/nordic_journal_of_religion_and_society/2015/01
IxTheo#2020-02-28#21B755D99ACA7E1F38FEDA331F8CE05ADD4D71A3
5. https://www.idunn.no/nordic_journal_of_religion_and_society/2015/01
IxTheo#2020-02-28#F2D4A276EDE2299EA70D5DFEA614019BD1D23A98
6. https://www.idunn.no/nordic_journal_of_religion_and_society/2014/02
IxTheo#2020-02-28#EEEC4C7A369F614EDAF94EDF333E90D135BCC789
7. https://www.idunn.no/nordic_journal_of_religion_and_society/2014/01
IxTheo#2020-02-28#8E420988C0E54A91AAD1D0AE0886EB796372B4F4
8. https://www.idunn.no/nordic_journal_of_religion_and_society/2013/01
IxTheo#2020-02-28#BD32A52D0A0CD690F7E84F927E00DC2D12757DBC
9. https://www.idunn.no/nordic_journal_of_religion_and_society/2013/02
 IxTheo#2020-02-28#14BBD757FAFB1383B7560B28C12B3C804F95D6E6
10. https://www.idunn.no/nordic_journal_of_religion_and_society/2012/02
IxTheo#2020-02-28#75A5B18B722260C4BD8BB056C8226424C9D7B9F0

**Ausführliche Problembeschreibung**
1. njrs-2019-2-09 (komplettes Heft)
2. External referees 2017–2018 (Danksagung und Auflistung aller Referenten)
3. Book received (Auflistung von drei Buchtiteln)
4. Books and Journals received (Auflistung von sechs Buchtiteln)
5. Book Reviews (Sammlung von Rezensionen)
6. Book Reviews (Sammlung von Rezensionen)
7. Book Reviews (Sammlung von Rezensionen)
8. Book Reviews (Sammlung von Rezensionen)
9. Book Reviews (Sammlung von Rezensionen)
10. Book Reviews (Sammlung von Rezensionen)

Klärung, ob die Rezensionen-Sammlungen eingespielt werden sollen.
siehe auch: #700

**Comment by socheres** [comment]
mit "Try URL"getestet.

**Comment by IxKo** [comment]
4. wird noch nicht gefiltert, alle anderen schon.

**Comment by socheres** [comment]
Ist nun korrigiert. Bitte nochmal testen.
`exclude_if_marc_field_245a = "(^Book Reviews$)|(^Books (A|a)nd (J|j)ournals (R|r)eceived)|(^Books (R|r)eceived)|(^External (R|r)eferees)|(^njrs)"`

**Comment by IxKo** [comment]
Passt.
