### ISSUE TITLE
ISSN 1890-7008 | Nordic journal of religion and society | Heftnummern mit Sortierungs-Null/0 am Anfang

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#766]
**Bsp.-URL**
https://www.idunn.no/nordic_journal_of_religion_and_society/2017/01
IxTheo#2020-02-28#1559F12B7C5173D361134A3DFAB45FAF0D881134

**Ausführliche Problembeschreibung**
Die Heftnummern werden als 01 oder 02 in die Quelldatei geschrieben. Die Null am Anfang sollte jedoch entfernt werden.

**Comment by mtrojan-ub** [comment]
Führende Nullen werden jetzt entfernt

**Comment by IxKo** [comment]
Nullen sind weg!
![grafik](https://user-images.githubusercontent.com/57000004/82913264-60f35480-9f6e-11ea-8530-d7dfac8566ed.png)
![grafik](https://user-images.githubusercontent.com/57000004/82913297-6cdf1680-9f6e-11ea-99f1-a96a3dd6ffff.png)
