### ISSUE TITLE
ISSN 1549-6538 | The journal of religion | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#767]
Hash C6923CA177B7C71567D76B5847EFD23891FABB52
ist eine Rezension. Vgl. https://www.journals.uchicago.edu/toc/jr/2020/100/1
Im Gegensatz zu den Rezensionen aus der Sektion Book Reviews wird diese nicht als solche getagt.

**Comment by IxKo** [comment]
Gleiches gilt für Hash D97B4F021986CD5CEC8573FA52F4F96C11C5BEF2 (https://www.journals.uchicago.edu/doi/10.1086/714163)

**Comment by socheres** [comment]
"Review Article" sollen nicht als Rezension getagt werden.  #1229 (comment)
siehe auch https://github.com/ubtue/DatenProbleme/issues/1305#issuecomment-766790674

**Comment by IxKo** [comment]
Ok
