### ISSUE TITLE
ISSN 1890-7008 | Nordic journal of religion and society | fehlende Rezensions-Deklarierung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#768]
**Bsp.-URL**
https://www.idunn.no/nordic_journal_of_religion_and_society/2016/01
IxTheo#2020-02-28#E47A6994577AD462364EF8001B436239B7FBFAE5

**Ausführliche Problembeschreibung**
Rezensionen werden in der Quelldatei nicht als solche deklariert.
Im Jahr 2018/2019 schon. Das Muster ist etwas anders.

**Comment by socheres** [comment]
falls möglich, das geänderte Muster mitteilen.

**Comment by theo-ko** [comment]
Im Jahr 2016 schaut der Titel einer Rezension mit Rubrikentitel "Bokessay" bspw. so aus:
Frisk, Liselott, and Peter Åkerbäck. 2015. New Religion in Contemporary Sweden: The Dalarna Study in National and International Context.
Muster: . JJJJ. (Punkt Leerzeichen Jahr Punkt)

Ab 2018 Mit Rubrikentitel "Book-Review" so:
Marcus Moberg. 2017.: Church, Market, and Media: A Discursive Approach to Institutional Religious Change.
Muster: . JJJJ.:   (Punkt Leerzeichen Jahr Punkt Doppelpunkt)

Ind er Config ist es mit Doppelpunkt definiert:
`zotero_review_regex       = "(ed\\.)? [0-9]{4}\\.\\:"`

Die Frage ist aber, ob es noch relevant ist, weil es keine aktuellen Aufsätze betrifft. In den Testdaten wurden jedoch auch Daten von 2016 eingespielt.

**Comment by socheres** [comment]
Da im Zotaut nur akutelle Daten eingespielt werden, spielt es keine Rolle mehr. Daher bitte den Issue schließen.
