### ISSUE TITLE
ISSN 2074-7705 | Verbum et ecclesia | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#769]
**URL**
1. https://verbumetecclesia.org.za/index.php/ve/article/view/2076
IxTheo#2020-02-28#AB3ADD670D738069C09231592623D8796E590788
2. https://verbumetecclesia.org.za/index.php/ve/article/view/2073
 IxTheo#2020-02-28#C2B1155ED3C67A207751B1D636B89BE0534946E0

**Ausführliche Problembeschreibung**
1. Table of Contents Vol 40, No 1 (2019)
2. Acknowledgement to Reviewers

Diese Titel nicht einspielen. Zudem wurden die "Abstracts" bei diesen als "-" und "No Abstract available" eingespielt unter dem Autorennamen: "Office, Editorial"

siehe auch: #700

**Comment by socheres** [comment]
mit "Try URL" getesetet

**Comment by kdr154** [comment]
Wie der Test bei IxKo ausgefallen ist,weiß ich nicht. Bei mir sind die Dinge noch da:
![grafik](https://user-images.githubusercontent.com/29707105/84885832-dea11080-b093-11ea-8b2e-8f97f297f582.png)
Die harvester.conf regelt das nicht.

**Comment by IxKo** [comment]
@kdr154 Ich wollte das erst morgen testen, da die Config erst abends neu eingespielt wird.

**Comment by kdr154** [comment]
Ok, aber wie die config aussieht, sieht man doch heute schon. Oder nicht?

**Comment by IxKo** [comment]
Ich vermute nicht. Die Config, die ich sehe, hat keinerlei "Filter"-Eintragungen zu dieser ISSN. Daher gehe ich davon aus, dass die IT an einem anderen Ort eine Config-Datei besitzt, die dann 19 Uhr mit der tatsächlich ausgeführten aktualisiert wird. siehe #968

**Comment by kdr154** [comment]
dass die IT an einem anderen Ort eine Config-Datei besitzt - Das glaube ich nicht. Denn dann wären wir  nicht in der Lage zu berurteilen, ob es daran liegt.
Aber belassen wir es dabei.

**Comment by socheres** [comment]
siehe https://github.com/ubtue/DatenProbleme/issues/775#issuecomment-645313982

**Comment by kdr154** [comment]
Die genannten Sätze sind nicht mehr enthalten

**Comment by IxKo** [comment]
Bestätige
