### ISSUE TITLE
ISSN 2074-7705 | Verbum et ecclesia | fehlende Aufsätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#771]
**betrifft Einspielung**
https://verbumetecclesia.org.za/index.php/ve/issue/view/97
IxTheo#2020-02-28#

**Ausführliche Problembeschreibung**
Von Heft 1, Jahr 2019 wurden nicht alle Aufsätze eingespielt: Von über 50 auf der Website sind nur 5 eingespielt worden.

**Comment by socheres** [comment]
@mtrojan-ub schaust dir bitte die beiden issues an # 770 und #771

**Comment by mtrojan-ub** [comment]
Das liegt vermutlich am RSS Feed da dieser nur wenige Einträge hat

**Comment by IxKo** [comment]
In der Testdatenbank sind zu dem Heft auch 20 Artikel mit Abrufzeichen ixzo für das semi-auto. Verfahren drin (mit Erstellungsdatum vom letzten Jahr), könnte das damit zusammenhängen?

**Comment by IxKo** [comment]
Gibt es hier schon Klarheit?

**Comment by IxKo** [comment]
Da es wohl am RSS lag, schließe ich.
