### ISSUE TITLE
ISSN 1749-6276 | Medieval sermon studies | KW Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#775]
Die Artikel Society News können unterdrückt werden:
5CDF8B77B71A7D8EA42EA02BC96BD92F3D596E55
86505E3BE7D7631EE1DF8E6582D820C95FA19CC9
https://www.tandfonline.com/toc/ymss20/63/1?nav=tocList

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by kdr154** [comment]
Bei mir sind sie bei einem Test mit "Try Url" und der Einstellung Medieval Sermon Studies, also nicht Default, noch vorhanden:
![grafik](https://user-images.githubusercontent.com/29707105/84883563-f4610680-b090-11ea-8d40-6e14bb1ae2e4.png)

**Comment by socheres** [comment]
@kdr154 @IxKo haben Sie in das Feld "Additional config" den Regex aus harvester.config manuell eingegeben? Die harvester.config wird erst um 19h aktualisiert. Daher beim Testen mit "Try URL" immer den entsprechenden Regex aus harvester.config eingeben.

**Comment by kdr154** [comment]
Nicht mehr enthalten
