### ISSUE TITLE
ISSN 1743-1301 | Palestine exploration quarterly | KW Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#778]
Die Artikel Acknowledgements und PEF Lectures .... können unterdrückt werden:
064F3D51B17FC831A92F536837105D7F8C678A93
https://www.tandfonline.com/doi/full/10.1080/00310328.2019.1693178
AD72F0D860202BDCA5F668D6676703659250BE6
https://www.tandfonline.com/doi/full/10.1080/00310328.2019.1698208

**Comment by socheres** [comment]
sollen beide Wörter, die im Titelfeld vorkommen "Acknowledgements" und "PEF Lectures", unterdrückt werden?

**Comment by kdr154** [comment]
Bei dieser Zeitschrift: ja

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by kdr154** [comment]
Alles noch da! Über die harvester.conf werden diese Artikel nicht unterdrückt.

**Comment by IxKo** [comment]
Zs steht auf zota
