### ISSUE TITLE
ISSN 1743-1301 | Palestine exploration quarterly | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#780]
Rezensionen werden nicht erkannt. 
330CEF711EDBD74AF0FBCD36F7BB43561FFD1FEC
https://www.tandfonline.com/doi/full/10.1080/00310328.2019.1693177
Vgl. #777

**Comment by IxKo** [comment]
Zs steht auf zota.
Rezensionen werden erkannt
