### ISSUE TITLE
ISSN 1743-1301 | Palestine exploration quarterly | Seitenzahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#781]
Bei Artikeln von nur einer Seite im Umfang, wird die Seitenzahl nicht in den K10Plus eingespielt.
Vgl Hash D27006F9CCEDF9E431A2B6E20A449B3DC496284A

**Comment by socheres** [comment]
BSZ wird den Konverter anpassen.

**Comment by socheres** [comment]
Seitenzahl im Umfang von nur einer Seite nicht in 936 g ausgeben, sondern in 936 h. Siehe [Code](https://github.com/ubtue/ub_tools/blob/499a19f63967371e96a42dca2bcb66316eb16d46/cpp/lib/src/ZoteroHarvesterConversion.cc#L897-L902) #729 #737 #752

**Comment by kdr154** [comment]
$h ist auch richtig!!!
Es liegt am BSZ!
Vgl. IxTheo#2020-02-28#064F3D51B17FC831A92F536837105D7F8C678A93
und 
IxTheo#2020-02-28#926AE7EFF48D2FA32678480B6F00C5F09EB263D6

**Comment by socheres** [comment]
@shadeMe nach [Fix](https://github.com/socheres/ub_tools/commit/21e5341f6e2ae83aecdc772181a94d0323a99790) bitte das Label "ready for testing" setzen.

**Comment by kdr154** [comment]
Müsste jetzt stimmen
