### ISSUE TITLE
ISSN 2161-4504 | Journal of pastoral theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#787]
Rezensionen werden nicht erkannt.
Vgl. #785 ... Taylor & Francis

**Comment by socheres** [comment]
mit "Try URL" getestet. Bitte immer den Link angeben. https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745328

**Comment by kdr154** [comment]
Diese wird erkannt.
