### ISSUE TITLE
ISSN 1745-5170 | Theology & sexuality | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#791]
Rezensionen werden nicht erkannt.
Vgl. #783 .... Ebenfalls Taylor & Francis

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by kdr154** [comment]
Ein Test mit dieser URL https://www.tandfonline.com/toc/yths20/25/3?nav=tocList zeigt,
dass sie weiterhin nicht getagt werden:
![grafik](https://user-images.githubusercontent.com/29707105/84899986-b91f0180-b0a9-11ea-8245-9db6ad270761.png)

In der harvester.conf fehlt auch der entsprechende Code:
https://github.com/ubtue/ub_tools/blob/5e044cefe0f4678f471e3990679b85e0ce33c23c/cpp/data/zotero_harvester.conf#L3535

**Comment by socheres** [comment]
Sie sind in der falschen Branch. Sie müssen auf Master gehen: https://github.com/ubtue/zotero-enhancement-maps/blob/b69f9179484def325588e96690395907de0d3014/zotero_harvester.conf#L4308-L4309 Bitte beim Testen mit "Try URL" immer die betreffende Codezeile eingeben.

**Comment by kdr154** [comment]
Stimmt, ist ok jetzt.
