### ISSUE TITLE
ISSN 1502-7244 | Scandinavian journal of the Old Testament | Editorial Matters

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#795]
Editorial Matters kann wegfallen
Hash 1170DAF6BBB499589D7436CB07F593F89EF3ADDA
zumal auch hier wieder die Seitenangabe. (Umfang nur eine Seite), nicht in den K10Plus eingespielt wird.

**Comment by kdr154** [comment]
Editorial Matters weiterhin Bestandteil der Daten:
IxTheo#2020-03-30#50C8B07FBC9F4F44A9B70AD85ED1FE6353AEA0DB

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by kdr154** [comment]
ok
