### ISSUE TITLE
ISSN 1556-3537 | Anthropology of consciousness | irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#796]
**URL**
https://anthrosource.onlinelibrary.wiley.com/doi/abs/10.1111/anoc.12096?af=R
IxTheo#2020-02-28#E4683A14EE0FAC658D67E3376873CC6DEE250C6B

**Ausführliche Problembeschreibung**
Titel="Issue Information"

Diesen Datensatz nicht einspielen.

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by IxKo** [comment]
Danke, wird gefiltert
