### ISSUE TITLE
ISSN 1476-6728 | Journal for the study of the Old Testament | Abgekürzte Vornamen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#799]
Bei dieser Zeitschrift ist es so, dass der zweite Vorname immer abgekürzt wird, und zwar ohne Punkt.
Dies ist auch dann der Fall, wenn die Person drei Vornamen hat. Wie in folgendem Fall
IxTheo#2020-02-28#E1507E0FA51CF2849CC7233EE0C98C91CAB7ED7D
und zwar werden hier die beiden Initialen ohne Punkte zusammengezogen.
Um den Vorgaben für die Recherche und RDA zu genügen, müsste für diese Zeitschrift eine Regel erstellt werden, die in Marc21 100 und 700 bei einem abgekürzten Vornamen hinter den abgekürten  Vornamen einen Punkt setzt. Etwa hier:
IxTheo#2020-02-28#B32D544D13A692B71DAAAB208293C65AEA0715A0
einen Punkt setzt. 
Und in dem oben genannten Fall die beiden zusammengezogenen Intitialen trennt in [A-Z] \.\s[A-Z]\. 
Dann nämlich könnte diese Zeitschift in das Produktivverfahren aufgenommen werden. Es gibt in ihr zwar hebräische Zeichen im Titel, im Abstract und in den Keywords. Dies würden wir im vollautomatischen Verfahren in Kauf nehmen. Im Gegensatz zum Sage Translator im halbautomatischen Verfahren werden diese im vollautomatischen Verfahren korrekt wiedergegeben. Zusätzlich werden auch die Keywords erfasst, beim halbautomatischen Verfahren nur beim Einzeldownload.

**Comment by IxKo** [comment]
Problem wurde behoben und Zs ist bereits live.
