### ISSUE TITLE
Sage ISSN 1552-3594 Low Risk Offenders Under Probation Supervision Tag 856

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#80]
Tag 856 erscheint 2 Mal im record

**Comment by mtrojan-ub** [comment]
Das liegt wahrscheinlich daran, dass die URL die von Zotero geliefert wird die gleiche ist wie die, die wir uns selbst aus der DOI zusammen bauen.
Ich werde einen passenden Filter einbauen um das zu verhindern.

**Comment by mtrojan-ub** [comment]
Die doppelten 856er mit DOIs sollten nun bei allen Zeitschriften behoben sein!

**Comment by kdr154** [comment]
Gelöst
