### ISSUE TITLE
ISSN 2050-8557 | Horizons | Seitenzahl aus einer Zahl -> falsch in Quelldatei

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#801]
**URL**
https://dx.doi.org/10.1017/hor.2019.98?urlappend=%3Fsource=rss
IxTheo#2020-02-28#3B91C8197810730BD3532071472D4D9F6004F630

**Ausführliche Problembeschreibung**
Nur bei dieser Rezension kommen die Seitenzahlen nicht mit.
Die Seitenzahl 428 landet in Marc-936 $g statt in $h.

**Offenbare Lösungen**
siehe auch: #781

**Comment by theo-ko** [comment]
@socheres Ich finde keinen Dummy-Datensatz in der Testdatenbank zu dieser Zeitschrift. Insgesamt finde ich nur zwei Dummy-Datensätze ("Just test for url pagee abstract." und "Just test for Rezension.") von Max Mustermann.
Diese haben vor dem #HASH "Dummy" stehen, weshalb ich sie recherchieren kann.

**Comment by IxKo** [comment]
Problem besteht nicht mehr
