### ISSUE TITLE
ISSN 2050-8557 | Horizons | Review Essays wird nicht als Rezension erkannt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#803]
**URL**
https://dx.doi.org/10.1017/hor.2019.109?urlappend=%3Fsource=rss
IxTheo#2020-02-28#FBD0E96D3772CCB00216D65F191145B6D4D1E6D0

**Ausführliche Problembeschreibung**
Die Rezension unter der Rubrik "Review Essays" werden nicht als Rezensionen erkannt.

**Comment by socheres** [comment]
@mtrojan-ub hier ist IMO nichts möglich, weder via Translator noch harvester.config.

**Comment by mtrojan-ub** [comment]
Schwieriger Fall... es wird die erste Seite als Bild gerendert, und dort taucht "Review Essay" als Überschrift auf. Da es in den Metadaten nirgens steht kann der Harvester es auch nicht erfassen.

Evtl geht es Translator-Seitig... beim Durchsuchen der HTML-Struktur habe ich folgende Info gefunden:
```
<ul class="article-components">
<li class="source">DOI: <a href="https://doi.org/10.1017/hor.2019.109" target="_blank" class="url doi" data-test-id="reviewDOILink">https://doi.org/10.1017/hor.2019.109</a></li>
<li class="published">Published online by Cambridge University Press: <span class="date"> 05 December 2019</span></li>
</ul>
```

Man könnte also im Translator auf den reviewDOILink unterhalb von ul[@class="article-components"] prüfen und dann einen entsprechenden Tag hinzufügen

**Comment by socheres** [comment]
@mtrojan-ub kannst den Translator dann anpassen?

**Comment by mtrojan-ub** [comment]
@socheres auf Anweisung von Olaf soll ich aus Ressourcengründen nur Issues bearbeiten die "Fehlerquelle: Harvester" sind (oder in unklaren Fällen wie z.B. "Fehlerquelle: unbekannt" unterstützen)

**Comment by socheres** [comment]
> Schwieriger Fall... es wird die erste Seite als Bild gerendert, und dort taucht "Review Essay" als Überschrift auf. Da es in den Metadaten nirgens steht kann der Harvester es auch nicht erfassen.
> 
> Evtl geht es Translator-Seitig... beim Durchsuchen der HTML-Struktur habe ich folgende Info gefunden:
> 
> ```
> <ul class="article-components">
> <li class="source">DOI: <a href="https://doi.org/10.1017/hor.2019.109" target="_blank" class="url doi" data-test-id="reviewDOILink">https://doi.org/10.1017/hor.2019.109</a></li>
> <li class="published">Published online by Cambridge University Press: <span class="date"> 05 December 2019</span></li>
> </ul>
> ```
> 
> Man könnte also im Translator auf den reviewDOILink unterhalb von ul[@Class="article-components"] prüfen und dann einen entsprechenden Tag hinzufügen

auch bei Artikeln steht als outputHTML überall "reviewDOILink". Daher taugt das leider nicht als Selektionskriterium.

**Comment by mtrojan-ub** [comment]
Davon abgesehen scheint es auf der einzelnen Seite überhaupt keinen Hinweis zu geben, auch nicht in den Metadaten.

Es steht aber auf der Übersichtsseite des Issues:
![grafik](https://user-images.githubusercontent.com/26873381/86004067-076dc200-ba13-11ea-96db-26ee8da9feb9.png)

Da wir bei einem anderen Issue `ZU.doGet` entdeckt haben könnte man ja evtl von der Unterseite aus den Link zur Issue Übersichtsseite herauslesen, diese herunterladen und dort den Titel scrapen. Das halte ich aber für sehr aufwendig, weil die Übersichtsseite mehrere Unterseiten hat ("Pagination") d.h. man müsste einzeln jede weitere Seite herunterladen bis man den Titel irgendwo gefunden hat.

![grafik](https://user-images.githubusercontent.com/26873381/86004212-3d12ab00-ba13-11ea-84b9-c539d9ff8a97.png)

Bevor man diesen Aufwand betreibt könnte man alternativ erstmal den Anbieter der Website freundlich bitten eine passende Metainformation auf der Unterseite mit auszugeben.

**Comment by IxKo** [comment]
Im neuen Heft ist kein solches Review Essay enthalten. Bei dem alten Fall hier, wird es weitehrin nicht getagt.

**Comment by IxKo** [comment]
Review Essay ist keine Rezension: siehe Issue #1229
