### ISSUE TITLE
ISSN 2050-8557 | Horizons | nicht alle Artikel vom Heft eingespielt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#804]
**Bsp-URL**
https://doi.org/10.1017/hor.2019.59

**Ausführliche Problembeschreibung**
Die letzten 5 Artikel des Heftes sind nicht eingespielt worden, da sie auch nicht in der Quelldatei sind.

**Comment by socheres** [comment]
@mtrojan-ub in harvester.config wird nichts ausgeschlossen. @IxKo um welches Heft handelt es sich und welche sind diese "letzten 5 Artikel"?

**Comment by IxKo** [comment]
@sochereres Nach Überprüfung wuden die 5 fehlenden Artikel nun in die Test-Datenbank eingespielt, aber verspätet mit dem Hash-Datum IxTheo#2020-05-07#
Alle anderen Artikel zum Heft 2019, 2 wurden bereits mit dem Hash-Datum IxTheo#2020-02-28# eingespielt.

**Comment by IxKo** [comment]
Da es hier keine Reaktion gab, schließe ich.
