### ISSUE TITLE
ISSN 1918-6371 | Toronto journal of theology | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#805]
Keywords werden nicht erfasst. Weder im Single- noch im Multimodus
Etwa hier: https://utpjournals.press/doi/abs/10.3138/tjt.2019-0090

**Comment by socheres** [comment]
Im Multimodus mit Atypton-Translator (wird als erstes angeboten) beides da.

**Comment by kdr154** [comment]
Keywords fehlen weiterhin (Single und Multi)

**Comment by socheres** [comment]
mit welchem Translator haben Sie im Multi heruntergeladen? Wird Atypton nicht angeboten? Ich habe nochmal getestet und Keywords kommen mit. @IxKo Können Sie auch noch testen? Unabhängig davon ist diese Zeitschrift "zotat" und in Nu ist Keywords und Abstract vorhanden. Daher bitte den Issue schließen.

**Comment by kdr154** [comment]
Atypon, sonst gab es noch Embedded Metadata. Issue bezog sich aber auf zotkat

**Comment by IxKo** [comment]
Kann das Problem bestätigen.

**Comment by kdr154** [comment]
Danke, ich schließe
