### ISSUE TITLE
ISSN 1382-4554 | The journal of ethics | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#806]
Dieser Artikel 
IxTheo#2020-03-05#9FAC87D3E292105986A73F1D19F9B5580126BD52
ist eine Rezension, die nicht erkannt wird.
Die Webseite des Heftes sieht so aus:
https://link.springer.com/journal/10892/24/1
Die des Artikels so:
https://link.springer.com/article/10.1007/s10892-019-09308-z

**Comment by socheres** [comment]
kein Muster erkennbar.

**Comment by kdr154** [comment]
https://link.springer.com/journal/10892/24/1
Review Paper
ist aber die einzige, die ich in den letzten Ausgaben gefunden habe.

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
