### ISSUE TITLE
ISSN 2055-7981 | British Catholic history | Überflüssige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#808]
Die folgenden Artikel sollten unterdrückt werden:
IxTheo#2020-02-28#569842C5C88AE54B04B0D3162B243758C298980F
IxTheo#2020-02-28#162D5732AEA20DE023B58F4EE26D4B2C7317F614

Der Titel enthält die Worte Front matter oder Back matter.

**Comment by socheres** [comment]
Test-URL: https://www.cambridge.org/core/journals/british-catholic-history/article/bch-volume-34-issue-4-cover-and-back-matter/16734DFCC4457DB0A568E2027AB684B8
Mit "Try URL" getestet.

**Comment by kdr154** [comment]
Sieht gut aus
