### ISSUE TITLE
ISSN 2055-7981 | British Catholic history | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#809]
Eine Art der Rezension wird nicht erkannt. Der Review Article:
IxTheo#2020-02-28#EEFD2828B524D73D78D7E891380CC8D5CD8F3C22

Vgl. 
https://www.cambridge.org/core/journals/british-catholic-history/issue/2DF6080A5C724E8096A72D3525CC048A?sort=canonical.position%3Aasc&pageNum=1&searchWithinIds=2DF6080A5C724E8096A72D3525CC048A&productType=JOURNAL_ARTICLE&template=cambridge-core%2Fjournal%2Farticle-listings%2Flistings-wrapper&hideArticleJournalMetaData=true&displayNasaAds=false

**Comment by socheres** [comment]
Kein Muster erkennbar. Da alle anderen "Book reviews" richtig als Rezensionen erkannt werden und die Daten alle gut sind, sollte man bei "Review Article" eine Ausnahme machen und ihn als Aufsatzartikel einspielen.

**Comment by IxKo** [comment]
Der Rubrikentitel "Review Article" kann nicht als Merkmal genutzt werden, weil er nicht in den Daten ist?
Funktionieren Muster nur beim Titelaufbau?

**Comment by socheres** [comment]
der Rubriktitel muss auch auf der Artikelseite stehen und nicht nur auf der Listenansicht. Titelei als Muster zu nehmen, ist in diesem Fall auch ausgeschlossen ( keine ISBN noch sonstiges als Muster).

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
