### ISSUE TITLE
Sage ISSN 1552-3594 Low Risk Offenders Under Probation Supervision Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#81]
Keywords kommen nicht mit
Vgl. https://journals.sagepub.com/doi/10.1177/0093854818790299

**Comment by shadeMe** [comment]
Gefixt.

**Comment by kdr154** [comment]
Die keywords kommen jetzt und sie stehen auch in 650.
Das datafield benötigt in diesem Fall aber den Indikator 2 mit dem Wert 4. Muss in diesem Fall also beispielsweise lauten:
statt 
```
<datafield tag="650" ind1=" " ind2=" ">
<subfield code="a">domestic violence</subfield>
</datafield>
```
sollte es so aussehen

```
> <datafield tag="650" ind1=" " ind2="4">
> <subfield code="a">domestic violence</subfield>
> </datafield>

```
Darüber wurde in #66 diskutiert. Deshalb möchte ich den/das? Issue noch nicht schließen.
Die Regelung ist folgende:
Wenn es keine Informationen zur Quelle gibt, dann erhält der Indikator 2 den Wert 4
Gibt es Informationen zu Quelle, dann erhält er den Wert 7 und in $2 steht die Quelle.
Vgl. die SSOAR Daten

Möglicherweise kann man das auch mit fixen
