### ISSUE TITLE
ISSN 1875-0214 | Zutot | Haken nicht umgesetzt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#810]
Bei diesem Artikel: https://brill.com/view/journals/zuto/17/1/article-p37_4.xml
wird der Haken beim Wort zaru ͑av or dem a in den Keywords nicht richtig umgesetzt. Im Titel und im Abstract hingegen schon.

**Comment by socheres** [comment]
Mit dem Translator "embedded metadata" werden Keywords nicht heruntergeladen. Wenn Sie das Keyword "zaru ͑av" manuell kopieren, kommt vor dem Zeichen eine Leerzeile hinzu, weshalb der Haken nicht richtig umgesetzt wird. Übernehmen Sie in solchen Fällen das Wort "zaru ͑av" direkt aus dem Titelfeld. Dann sollte es klappen.
