### ISSUE TITLE
ISSN 1574-9282 | International Journal of Hindu Studies | Sammlung von Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#811]
Diese Zeitschrift enthält Sammelrezensionen. Vgl.:
IxTheo#2020-02-28#52FC92ADAFA31AE4CF711C285E1959DB075C3657
https://link.springer.com/journal/11407/23/3
Diese sollten laut @socheres in #700 und #716 herausgefiltert werden

**Comment by IxTheoKm** [comment]
@socheres 
Bitte Begrifflichkeiten klären und ggf. ändern:
"Sammelrezension" haben wir im IxTheo bisher für Rezensionen eines Autors verwendet, der in _einem_ Rezensionstext (oft mit übergeordnetem Titel) mehrere Publikationen rezensiert. Die haben wir aufgenommen!

Gemeint sind hier vermutlich eher Sammlungen von Einzelrezensionen meist verschiedener Autoren (unter einem übergeordneten Begriff wie "Book reviews", "Rezensionen" u.ä.) Nur diese sollten herausgefiltert werden. 

Wenn dem so ist, würde ich die betr. Issues umbenennen in "Sammlung von Rezensionen"

**Comment by kdr154** [comment]
Die Sammlung  von Rezensioenen ist immer noch drin:

![grafik](https://user-images.githubusercontent.com/29707105/85023988-bdb0ec00-b175-11ea-958d-22d31f7c83b1.png)

**Comment by kdr154** [comment]
Bleibt auch mit additional config exclude_if_marc_field_245a = "^Book (R|r)reviews$"

**Comment by kdr154** [comment]
Der Ausdruck hat ein r zu viel  (R|r)r

**Comment by socheres** [comment]
Ist korrigiert. Danke.

**Comment by kdr154** [comment]
passt jetzt
