### ISSUE TITLE
ISSN 1574-9282 | International Journal of Hindu Studies | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#812]
Manche Artikel besitzen keywords. Ganz am Ende der Seiten. Vgl.
IxTheo#2020-02-28#3C8A8F34E00CC1959FF212EA32066D690091625E
https://link.springer.com/article/10.1007/s11407-019-09266-z

**Comment by mtrojan-ub** [comment]
Translator-Problem

**Comment by socheres** [comment]
Zotero Logger initialized!



Queued journal 'International Journal of Hindu Studies' | DIRECT @ https://link.springer.com/article/10.1007/s11407-019-09266-z
set download-delay for domain 'link.springer.com' to 1000 ms


Harvesting URL 1 [International Journa...] | https://link.springer.com/article/10.1007/s11407-019-09266-z {3900176263227774963}
Harvest successful




Converting item 1 [International Journa...] | https://link.springer.com/article/10.1007/s11407-019-09266-z {3900176263227774963}
use online ISSN "1574-9282" with online PPN "519504976"
post-processed author first name = 'J. E.', last name = 'Llewellyn', title = '', affix = ''
added GND number 1055669302 for author Llewellyn, J. E. (SWB lookup)
expected language 'eng' but found 'en'
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1007/s11407-019-09266-z,
	item_type: journalArticle,
	title: The Modern Bhagavad Gītā: Castein Twentieth-Century Commentaries,
	short_title: The Modern Bhagavad Gītā,
	abstract_note: By the twentieth century the Bhagavad Gītā had become the single most important Hindu book. A clear indication of its popularity is that many of the major thinkers of that century wrote about it, often in book-length commentaries. In this article, we will analyze what Bal Gangadhar Tilak, Sri Aurobindo, Mohandas K. Gandhi, and Svāmī Śivānanda have to say about caste in their books about the Bhagavad Gītā. In colonial India, caste was understood to be a problem, at once critical to Indian society and critically in need of reform. A fundamental split had developed in the nineteenth century. Some social reformers condemned caste as a divisive, and therefore pernicious, institution. Others argued, on the contrary, that caste could be a force to unite social groups, if only it were properly overhauled. All but one of our twentieth-century authors advance modern reinterpretations of caste, moving it in a unifying direction. However, Śivānanda interprets the Bhagavad Gītā in a way that is traditional, striking particularly in this modern context.,
	publication_title: International Journal of Hindu Studies,
	volume: 23,
	issue: 3,
	pages: 309-323,
	date: 2019-12-01,
	doi: 10.1007/s11407-019-09266-z,
	language: eng,
	issn: 1574-9282,
	superior_ppn: 519504976,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: J. E.,
			last_name: Llewellyn,
			type: author,
			gnd_number: 1055669302,
		},
	],
	keywords: [ Bhagavad Gītā, caste, Bhimrao Ramji Ambedkar, Bal Gangadhar Tilak, Sri Aurobindo, Mohandas K. Gandhi, Svāmī Śivānanda,  ],
}
Generated record with hash 'B46D345A4C7FECBC16EB2204DB9C49808B1CB3BE'

Conversion complete


Generated 1 record(s) for item 1 [International Journa...] | https://link.springer.com/article/10.1007/s11407-019-09266-z {3900176263227774963}



Zotero Harvester Metrics:
	Journals: 1
		Direct: 1
		RSS: 0
			Skipped: 0
		Crawl: 0
	Crawls: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 1
		Successful: 1
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 1
		Successful: 1
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 0
		Skipped (already delivered): 0

	Successfully generated records per group:
		IxTheo: 1

**Comment by kdr154** [comment]
ok
