### ISSUE TITLE
ISSN 1574-9282 | International Journal of Hindu Studies | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#813]
Mit Review Article gekennzeichnete Rezensionen werden nicht als solche erkannt:
IxTheo#2020-02-28#93F611F1B58FDC934D4127A6C21BD9BFD817A399
https://link.springer.com/journal/11407/23/3 der 2, Artikel von unten

**Comment by socheres** [comment]
https://github.com/ubtue/DatenProbleme/issues/809#issuecomment-645350256

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
