### ISSUE TITLE
ISSN 2056-6107 | Journal of religious and political practice | fehlende Abstracts und Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#816]
**URL**
https://www.tandfonline.com/doi/full/10.1080/20566093.2018.1525896?af=R

**Ausführliche Problembeschreibung**
Auf der Seite hat es ein Abstract und Keywords. Diese Informationen befinden sich aber nicht in den Quelldaten.

**Comment by mtrojan-ub** [comment]
Mittlerweile beides vorhanden

**Comment by IxKo** [comment]
Ja, beides nun da!
![grafik](https://user-images.githubusercontent.com/57000004/83000857-399e9500-a00b-11ea-9c63-86038dc6847f.png)
