### ISSUE TITLE
ISSN 2196-8802 | International journal of Dharma Studies | Zs erscheint nicht mehr

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#817]
**URL**
https://internationaljournaldharmastudies.springeropen.com/

**Ausführliche Problembeschreibung**
In die Test-DB wurden Artikel aus dem Jahr 2017 eingespielt. Laut Springer wird sie nicht weitergeführt.
Daher kann sie aus dem Testverfahren genommen werden.

Es hätte auch einige Einspielungsfehler gegeben.
Da noch keine Artikel im K10plus nachgewiesen sind, werde ich die Zs in nächster Zeit mit dem halbautomatischen Verfahren einpflegen.

**Offenbare Lösungen**
Aus dem Testverfahren nehmen.
Bisher erschienene Artikel im halbautomatischen Verfahren katalogisieren.

**Comment by socheres** [comment]
Delivery_mode ist auf "none" gesetzt. https://github.com/ubtue/zotero-enhancement-maps/blob/b69f9179484def325588e96690395907de0d3014/zotero_harvester.conf#L4907
D.h. keine Zotaut-Kandidatin.
