### ISSUE TITLE
ISSN 2516-6301 | Scottish Church History | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#819]
Die Abstracts werden abgeschnitten.
Bei https://www.euppublishing.com/doi/abs/10.3366/sch.2020.0019
erhält man folgendes:
The 1843 Disruption of the Church of Scotland, which split the national church in two, was one of the most important events in Victorian Britain. The evangelical ministers who seceded from the Kirk...

**Comment by socheres** [comment]
Abstract nicht mehr abgeschnitten.
