### ISSUE TITLE
Sage ISSN 1552-3594 Criminal Justice and Behavior Online first + Regular

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#82]
Auch der Feed zu dieser Zeitschrift enthält Online first Artikel und Artikel die einem Heft zugeordnet sind

**Comment by shadeMe** [comment]
Die Online-First Problematik ist jetzt gelöst. Bitte nochmal prüfen.

**Comment by kdr154** [comment]
Der Grund warum die Issues zu den First Online Artikeln von Zeitschriften, die bei Sage erscheinen, nicht geschlossen wurden besteht in den ungültigen Seitenangaben in 936 h. Dieses Problem besteht weiterhin.

**Comment by kdr154** [comment]
Gelöst
