### ISSUE TITLE
ISSN 1476-6728 | Journal for the study of the Old Testament | Hebräisch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#820]
Dieser Fall wahrscheinlich nur beispielgebend. Es gibt Probleme bei der Umsetzung des Hebräischen. Laut @socheres liegt es an der Schreibrichtung und den Vokalzeichen.
Die Vorlage:
https://journals.sagepub.com/doi/full/10.1177/0309089219862826
Die PPN: 1692343572 hier nun schon bereinigt. Umgesetzt durch c&p. Eigenartigenweise funktioniert der direkte Import.

**Comment by socheres** [comment]
Titel lautet: אִם‎ . . . הֲ‎: A rhetorical question anticipating a negative answer:
Mit c&p ist das Problem mit der Schreibrichtung nicht gelöst.

hier die vorlage:
![image](https://user-images.githubusercontent.com/1545743/77548627-15a9c080-6eaf-11ea-907f-d587913c44d1.png)

In winibw:
![image](https://user-images.githubusercontent.com/1545743/77548587-088cd180-6eaf-11ea-8427-00092b9f3e56.png)

Das muss direkt in WinIBW eingegeben werden. Vllt. ist diese Zss. für Zotaut geeignet ist.

**Comment by kdr154** [comment]
Mit c&p meine ich doch die direkte Kopie in die WinIBW. Ich habe es doch selbst katalogisiert. Oder wohin soll das c&p denn gehen? Und ich mache es immer so. Sicher schon 50 Mal

**Comment by kdr154** [comment]
Lieber Herr Kim,

 

da wäre jetzt die Frage,  ob das immer so war. Dazu müssten wir Herrn Cloutier heranziehen. Ihm habe ich die Sachen immer zu transkribieren gegeben. Ihm ist es doch bestimmt aufgefallen, ob die Vorlage und die Darstellung in der WinIBW unterschiedlich war. Ob immer, oder manchmal oder ob das hier die Ausnahme ist.

Zur Frage zotaut. Es handelt sich um ein Zeitschrift von Sage. Das sollte möglich sein.

 

Mit freundlichen Grüßen

Klaus-Dieter Rosenkranz

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Kim, Timotheus Chang-whae <notifications@github.com> 
Gesendet: Mittwoch, 25. März 2020 15:45
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Author <author@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 1476-6728 | Journal for the study of the Old Testament | Hebräisch (#820)

 

Titel lautet: אִם‎ . . . הֲ‎: A rhetorical question anticipating a negative answer:
Mit c&p ist das Problem mit der Schreibrichtung nicht gelöst.

hier die vorlage:
 <https://user-images.githubusercontent.com/1545743/77548627-15a9c080-6eaf-11ea-907f-d587913c44d1.png> 

In winibw:
 <https://user-images.githubusercontent.com/1545743/77548587-088cd180-6eaf-11ea-8427-00092b9f3e56.png> 

Das muss direkt in WinIBW eingegeben werden. Vllt. ist diese Zss. für Zotaut geeignet ist.
