### ISSUE TITLE
ISSN 1573-0697 | Journal of business ethics | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#822]
Book reviews werden nicht erkannt.
IxTheo#2020-03-25#324AC36D80DEF98F7A8F8B2EFFE784FC9955E202
https://link.springer.com/journal/10551/163/1

**Comment by socheres** [comment]
Mit "Try URL" getestet.
-----------------
Zotero Logger initialized!



Queued journal 'Journal of business ethics' | DIRECT @ https://link.springer.com/article/10.1007/s10551-019-04357-8
set download-delay for domain 'link.springer.com' to 1000 ms


Harvesting URL 1 [Journal of business ...] | https://link.springer.com/article/10.1007/s10551-019-04357-8 {4467525770035915544}
Harvest successful




Converting item 1 [Journal of business ...] | https://link.springer.com/article/10.1007/s10551-019-04357-8 {4467525770035915544}
use online ISSN "1573-0697" with online PPN "270937129"
post-processed author first name = 'Jooho', last name = 'Lee', title = '', affix = ''
expected language 'eng' but found 'en'
title matched review pattern
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1007/s10551-019-04357-8,
	item_type: review,
	title: Review of The Mueller Report,
	publication_title: Journal of Business Ethics,
	volume: 163,
	issue: 1,
	pages: 167-172,
	date: 2020-04-01,
	doi: 10.1007/s10551-019-04357-8,
	language: eng,
	issn: 1573-0697,
	superior_ppn: 270937129,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Jooho,
			last_name: Lee,
			type: author,
		},
	],
}
Generated record with hash '2D68252D97A8D9DBB8E3B342AAB2A08284D97F60'

Conversion complete


Generated 1 record(s) for item 1 [Journal of business ...] | https://link.springer.com/article/10.1007/s10551-019-04357-8 {4467525770035915544}



Zotero Harvester Metrics:
	Journals: 1
		Direct: 1
		RSS: 0
			Skipped: 0
		Crawl: 0
	Crawls: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 1
		Successful: 1
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 1
		Successful: 1
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 0
		Skipped (already delivered): 0

	Successfully generated records per group:
		IxTheo: 1

**Comment by kdr154** [comment]
ok
