### ISSUE TITLE
ISSN 2363-6696 | Entangled Religions | Überflüssiges unvollständiges 4950 Kostenfrei

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#823]
IxTheo#2020-03-25#DC805635AA23979017FEB78B3DECD185F2A38730
Diese Aufnahme enthält 3 Einträge der Kategorie 4950 Marc 856.
Der erste ist überflüssig und möglicherweise darauf zurückzuführen, dass in der Quelldatei für das Kriterium Kostenfrei ein eigenes Tag 856 generiert wird, anstatt es als subfield $z bei den anderen beiden abzulegen.
Die Folge davon ist, dass der Hinweis Kostenfrei $4LF in Pica 4950 fehlt
Vgl. #772

**Comment by socheres** [comment]
mit "Try URL" getestet:
URL:https://er.ceres.rub.de/index.php/ER/article/view/8445
Unten im Beispiel gibt es nur zwei Einträge MARCXML 856. Woher die überflüssige erste Zeile von PICA 4950 kommt, weiß ich auch nicht. Wir beobachten einfach weiter, ob der Fall künftig auch auftritt. Ich schließe den Issue vorerst.
![grafik](https://user-images.githubusercontent.com/1545743/84905572-1f5b5280-b0b1-11ea-8366-717bd29456e3.png)
