### ISSUE TITLE
ISSN 0043-2539 | Die Welt des Islams | Titel als Abstract bei Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#824]
Hier wird bei Rezensionen der Titel das Aufsatzes ein weiteres Mal als Abstract eingefügt
![grafik](https://user-images.githubusercontent.com/29707105/77731163-ae048a00-7002-11ea-844c-63ce07b8327c.png)
https://brill.com/view/journals/wdi/60/1/wdi.60.issue-1.xml
https://brill.com/view/journals/wdi/60/1/article-p118_10.xml

**Comment by socheres** [comment]
Ist eine "Zotat"-Zss und im Zotaut wird der Titel nicht als Abstract eingefügt. Daher schließe ich den Issue. 

--------
Zotero Logger initialized!



Queued journal 'Die Welt des Islams : international journal for the study of modern Islam' | DIRECT @ https://brill.com/view/journals/wdi/60/1/article-p103_6.xml
set download-delay for domain 'brill.com' to 5000 ms


Harvesting URL 1 [Die Welt des Islams ...] | https://brill.com/view/journals/wdi/60/1/article-p103_6.xml {12762345664646949628}
Harvest successful




Converting item 1 [Die Welt des Islams ...] | https://brill.com/view/journals/wdi/60/1/article-p103_6.xml {12762345664646949628}
use online ISSN "1570-0607" with online PPN "341344516"
post-processed author first name = 'Simon Wolfgang', last name = 'Fuchs', title = '', affix = ''
Augmented metadata record: MetadataRecord {
	url: https://brill.com/view/journals/wdi/60/1/article-p103_6.xml,
	item_type: journalArticle,
	title: The New Sectarianism. The Arab Uprisings and the Rebirth of the Shiʿa-Sunni Divide, written by Geneive Abdo, 2017,
	abstract_note: "The New Sectarianism. The Arab Uprisings and the Rebirth of the Shiʿa-Sunni Divide, written by Geneive Abdo, 2017" published on 12 Mar 2020 by Brill.,
	publication_title: Die Welt des Islams,
	volume: 60,
	issue: 1,
	pages: 103-105,
	date: 2020-03-12,
	doi: 10.1163/15700607-00601P06,
	language: ger,
	issn: 1570-0607,
	superior_ppn: 341344516,
	superior_type: 2,
	ssg: 1,
	creators: [
		{
			first_name: Simon Wolfgang,
			last_name: Fuchs,
			type: author,
		},
	],
}
Generated record with hash 'BC4A2CC31CCFA499857B3D4A59AC43EA3B671DC7'

Conversion complete


Generated 1 record(s) for item 1 [Die Welt des Islams ...] | https://brill.com/view/journals/wdi/60/1/article-p103_6.xml {12762345664646949628}



Zotero Harvester Metrics:
	Journals: 1
		Direct: 1
		RSS: 0
			Skipped: 0
		Crawl: 0
	Crawls: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 1
		Successful: 1
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 1
		Successful: 1
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 0
		Skipped (already delivered): 0

	Successfully generated records per group:
		IxTheo: 1
