### ISSUE TITLE
ISSN 0043-2539 | Die Welt des Islams | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#825]
Rezensionen werden nicht erkannt.
https://brill.com/view/journals/wdi/60/1/wdi.60.issue-1.xml
Zu erkennen an der Wendung written by im Titel, oder auch edited by

**Comment by socheres** [comment]
im Zotkat werden Rezensionsen nicht automatisch erkannt. Daher schließe ich den Issue.
