### ISSUE TITLE
ISSN 0043-2539 | Die Welt des Islams | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#826]
Alle Artikel werden als in deutscher Sprache verfasst interpretiert. In meinen Augen sind sie alle auf Englisch.
https://brill.com/view/journals/wdi/60/1/wdi.60.issue-1.xml
Bsp.:
![grafik](https://user-images.githubusercontent.com/29707105/77732014-50713d00-7004-11ea-9ad6-78609cde21e6.png)

**Comment by socheres** [comment]
Translatorseitig nichts zu machen. Sie können ggfs. in der Mapping https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map eintrgagen.
