### ISSUE TITLE
ISSN 2406-4726 | Nouvelle revue théologique | DOI Keywords Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#827]
Beispielheft: https://www.cairn.info/revue-nouvelle-revue-theologique-2020-1.htm
Bitte versuchen den Translator anzupassen. Ein Multidownload ist gar nicht möglich. Beim Single wird standadamäßig der Translator Embedded Metadata genommen. Darüber hinaus steht noch der DOI-Translator im Angebot.
Bei Embedded Metadata fehlen die Keywords und der DOI, zudem ist das Abstract in zwei Sprachen vorhanden, übertragen wird aber nur eines mit jeder Menge HTML-Code.
Beim DOI-Translator fehlen das/die Abstracts und die Keywords

**Comment by socheres** [comment]
bitte als PicaK10plus_single kopieren und einzeln übertragen. Die HTML-Tags sind dann weg. Fehlende Metadaten müssen manuell ergänzt werden.
------
0500 Osn
0501 Text$btxt
0502 Computermedien$bc
0503 Online-Ressource$bcr
1100 2020$n[2020]
1500 fre
1505 $erda
3000 Bernard, Matthieu$BVerfasserIn$4aut
4000 L’Église en quête d’identité $dle deuxième voyage missionnaire de Paul (Ac 15,36-21,14)
4070 $v142$j2020$a1$p5-22
4207 Les chapitres 15 à 21 des Actes des Apôtres relatent les 2e et 3e voyages missionnaires de Paul. Sans céder à l’anecdotique, Luc propose au fil de ce récit un discernement spirituel narratif de l’identité de l’Église naissante. Ce discernement passe, au concret, par un hommage rendu à Israël, ainsi que par l’accueil généreux des personnes et institutions païennes, soumises toutefois au jugement de l’Évangile. Se dessine ainsi le projet de ce que l’on peut appeler « l’œcuménisme lucanien ».
4241 Enthalten in!736119264!
4950 https://www.cairn.info/revue-nouvelle-revue-theologique-2020-1-page-5.htm$xH
5056 1
E* l01
7100 $Jn
8012 ixzs$aixzo
