### ISSUE TITLE
ISSN  1572-8684 | International journal for philosophy of religion | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#828]
Keywords werden nicht übertragen. Sie befinden sich in der Sektion About this article.
https://link.springer.com/article/10.1007/s11153-019-09719-w
 Das ist das gleiche Problem wie z. B. bei #812 
Beides Springer Zeitschriften, hier eben im halbautomatischen Verfahren.
Sollte aber ebenfalls ein Kandidat für das vollautomatische Verfahren sein.

**Comment by socheres** [comment]
Ist eine Zotat-Zeitschrift, daher lohnt sich der Aufwand nicht.
