### ISSUE TITLE
ISSN 1871-2428 | Church history and religious culture | Titel als Abstract bei Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#829]
Vgl. #824 
Hier wird bei Rezensionen der Titel das Aufsatzes ein weiteres Mal als Abstract eingefügt
https://brill.com/view/journals/chrc/100/1/chrc.100.issue-1.xml

**Comment by socheres** [comment]
Ist eine Zotat-Zeitschrift, daher schließe ich den Issue.
