### ISSUE TITLE
ISSN 1777-5825 | Archives de sciences sociales des religions | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#834]
Bei dieser Quelle werden die Keywords nicht erfasst:
https://journals.openedition.org/assr/
Ein Aufsatz: https://journals.openedition.org/assr/50047
Sie sind zudem in mehreren Sprachen vorhanden

**Comment by socheres** [comment]
Keywords vorhanden.

**Comment by socheres** [comment]
zotat gesetzt.
