### ISSUE TITLE
ISSN 1777-5825 | Archives de sciences sociales des religions | Bandzählung

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#836]
Die Bandzählung wird hier zur Heftzählung, da diese ins Zoterofeld Ausgabe geschrieben wird, statt in das Feld Band.
Beispiel: https://journals.openedition.org/assr/50047

![grafik](https://user-images.githubusercontent.com/29707105/77999079-68153200-7332-11ea-9832-3c5b64996325.png)

![grafik](https://user-images.githubusercontent.com/29707105/77999136-7ebb8900-7332-11ea-9e64-b0fd1d41812c.png)

**Comment by socheres** [comment]
zotat
