### ISSUE TITLE
ISSN 2161-6310 | Journal of Moravian history | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#840]
Die Rezensionen werden weder bei den Daten von Muse:
etwa https://muse.jhu.edu/journal/558
noch bei denen von JStor:
etwa https://www.jstor.org/stable/10.5325/jmorahist.19.2.issue-2?refreqid=excelsior%3Aab8536bf5895e56bab343778eceea7bb
getagt.

**Comment by socheres** [comment]
mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_MtPQm4" "--output-filename=cl210Q.xml"  "--config-overrides=zotero_review_regex    = "\(review\)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://muse.jhu.edu/article/755122" "Journal of Moravian  history"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of Moravian history' \| DIRECT @ https://muse.jhu.edu/article/755122 set download-delay for domain 'muse.jhu.edu' to 1000 ms   Harvesting URL 1 [Journal of Moravian ...] \| https://muse.jhu.edu/article/755122 {1942889667422979380} Harvest successful     Converting item 1 [Journal of Moravian ...] \| https://muse.jhu.edu/article/755122 {1942889667422979380} use online ISSN "2161-6310" with online PPN "67021275X" post-processed author first name = 'Monica', last name = 'Najar', title = '', affix = '' expected language 'eng' but found 'en' title matched review pattern Augmented metadata record: MetadataRecord { 	url: https://muse.jhu.edu/article/755122, 	item_type: review, 	title: Christian Slavery: Conversion and Race in the Protestant Atlantic World by Katharine Gerbner (review), 	short_title: Christian Slavery, 	publication_title: Journal of Moravian History, 	volume: 20, 	issue: 1, 	pages: 114-116, 	date: 2020-05-14, 	language: eng, 	issn: 2161-6310, 	superior_ppn: 67021275X, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Monica, 			last_name: Najar, 			type: author, 		}, 	], } Generated record with hash '51E38EB1224B064A2DEABE1285FFA58A892503DA'  Conversion complete   Generated 1 record(s) for item 1 [Journal of Moravian ...] \| https://muse.jhu.edu/article/755122 {1942889667422979380}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
