### ISSUE TITLE
ISSN 2161-6310 | Journal of Moravian history | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#841]
Das Ergebnis eines Downloads der Rezensionen von dieser Quelle (JStor), ist für den Benutzer wertlos, da lediglich der Titel "Review" erfasst wird und es keinen Hinweis auf das rezensierte Werk gibt.
https://www.jstor.org/stable/10.5325/jmorahist.19.2.issue-2?refreqid=excelsior%3Aab8536bf5895e56bab343778eceea7bb

**Comment by socheres** [comment]
Grundsätzlich sollen Rezensionen manuell erfasst werden, wenn die Daten im Zotkat-Verfahren rudimentär sind. Ob und in welchem Umfang Rezensionen aufgenommen werden soll, steht ja noch aus.

**Comment by socheres** [comment]
bitte auch bei anderen Rezensionsartikeln testen.

**Comment by kdr154** [comment]
Perfekt
