### ISSUE TITLE
ISSN 1533-8568 | Religion and American culture | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#842]
**HASH**
IxTheo#2020-02-28#705BBD6CF253CEDE7C21CA88D8D03DB7AC2D4732
IxTheo#2020-02-28#D623B8075F96C5DEF52645ABEE5C273FB80D9B38

**Ausführliche Problembeschreibung**
Titel:
RAC volume 29 issue 3 Cover and Back matter
RAC volume 29 issue 3 Cover and Front matter

**Offenbare Lösungen**
Herausfiltern mit Schema
siehe auch #700

**Comment by kdr154** [comment]
Diese Artikel werden jetzt gefiltert
