### ISSUE TITLE
ISSN 1467-9418 | Reviews in religion and theology  | irrelevante Datensätze

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#843]
**HASH**
IxTheo#2020-03-05#0CC4A24995374F7E448801FFC9E951A4B83F5DC2
IxTheo#2020-03-05#00A1317B45198D2FE8FA1B26184FBCCEB79A04B5

**Ausführliche Problembeschreibung**
Titel:
Books Received
Books Reviewed

**Offenbare Lösungen**
Titel herausfiltern
siehe auch #700

Aufgefallen ist mir außerdem, dass diese beiden Titel zum Heft 1 gehören, die übrigen Aufsätze zu diesem Heft aber bereits mit dem Hash-Datum 2020-01-30 eingespielt wurden.

**Comment by socheres** [comment]
mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_DrDPHn" "--output-filename=OepWj9.xml"  "--config-overrides=exclude_if_marc_field_245a = "((I\|i)ssue  (I\|i)nformation)\|((B\|b)ooks (R\|r)eceived)\|((B\|b)ooks (R\|r)eviewd)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://doi.org/10.1111/rirt.13765" "Reviews in religion and  theology : RRT"
-- | --
Runtime | 5s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Reviews in religion and theology : RRT' \| DIRECT @ https://doi.org/10.1111/rirt.13765 set download-delay for domain 'doi.org' to 1000 ms   Harvesting URL 1 [Reviews in religion ...] \| https://doi.org/10.1111/rirt.13765 {1854606266422156781} Harvest successful     Converting item 1 [Reviews in religion ...] \| https://doi.org/10.1111/rirt.13765 {1854606266422156781} use online ISSN "1467-9418" with online PPN "324655193" expected language 'eng' but found 'en' Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/rirt.13765, 	item_type: journalArticle, 	title: Books Received, 	publication_title: Reviews in Religion, 	volume: 27, 	issue: 1, 	pages: 143-146, 	date: 2020-01-01, 	doi: 10.1111/rirt.13765, 	language: eng, 	issn: 1467-9418, 	superior_ppn: 324655193, 	superior_type: 2, 	ssg: 1, } MARC field for 'https://doi.org/10.1111/rirt.13765 matched exclusion filter (245a/((I\|i)ssue (I\|i)nformation)\|((B\|b)ooks (R\|r)eceived)\|((B\|b)ooks (R\|r)eviewd)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0

**Comment by IxKo** [comment]
Der Titel "Books Received" wird gefiltert, aber "Books Reviewed" noch nicht.

**Comment by socheres** [comment]
"e" hat gefehlt. Bitte testen Sie nochmal im Modus "Try URL" und wenn gefiltert wird, dann den Issue schließen. Hier die Codezeile für die Eingabe in "Additional config": `exclude_if_marc_field_245a = "((I|i)ssue (I|i)nformation)|((B|b)ooks (R|r)eceived)|((B|b)ooks (R|r)eviewed)"`

**Comment by IxKo** [comment]
Funktioniert
