### ISSUE TITLE
Testen einzelner DOIs der älteren RSS-Feeds ermöglichen

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#844]
bereits im Meeting mit @mtrojan-ub und auch @shadeMe angesprochen. Fehlerbehebung soll getestet werden können.
> Kann im Augenblick nicht geklärt werden, da die Daten keine Ausgabe beinhalten, in der es Rezensionen gibt.

_Originally posted by @kdr154 in https://github.com/ubtue/DatenProbleme/issues/265#issuecomment-514517304_

**Comment by kdr154** [comment]
Gelöst

**Comment by mtrojan-ub** [comment]
Die Funktion steht ja schon seit einer Weile zur Verfügung ("Try URL"). Gibt es dazu Änderungswünsche?
