### ISSUE TITLE
ISSN 1475-5629 Culture and religion Editorial

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#845]
Das Editorial kann entfallen:
IxTheo#2020-04-06#7C59E670AC3CED5E47F8785F077A175041DEB443
= #789

**Comment by socheres** [comment]
mit "Try URL" getestet.

**Comment by kdr154** [comment]
Den Hashtag von oben kann ich nicht finden, aber ein Test mit folgender URL
https://www.tandfonline.com/toc/ypat20/6/1?nav=tocList
zeigt, dass da Editorial weiterhin drin ist:
![grafik](https://user-images.githubusercontent.com/29707105/84891702-933f3000-b09c-11ea-84ac-5d2cefe5a9a0.png)

**Comment by socheres** [comment]
@IxKo Können Sie bitte mit "Try URL" testen. 
Test-URL: https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745320
Regex für Additional config: exclude_if_marc_field_245a = "^Editorial?$" 

Bei mir wird der Artikel ausgeschlossen!

Zotero Logger initialized!



Queued journal 'Journal of pastoral theology' | DIRECT @ https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745320
set download-delay for domain 'www.tandfonline.com' to 1000 ms


Harvesting URL 1 [Journal of pastoral ...] | https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745320 {8490231444475927455}
Harvest successful




Converting item 1 [Journal of pastoral ...] | https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745320 {8490231444475927455}
converted roman numeral page range 'v-xi' to decimal page range '5-11'
use online ISSN "2161-4504" with online PPN "845731157"
post-processed author first name = 'Larry Kent', last name = 'Graham', title = '', affix = ''
added GND number 1024055361 for author Graham, Larry Kent (SWB lookup)
post-processed author first name = 'Christie Cozad', last name = 'Neuger', title = '', affix = ''
language set to default language 'eng'
Augmented metadata record: MetadataRecord {
	url: https://doi.org/10.1080/10649867.1996.11745320,
	item_type: journalArticle,
	title: Editorial,
	publication_title: Journal of Pastoral Theology,
	volume: 6,
	issue: 1,
	pages: 5-11,
	date: 1996-06-01,
	doi: 10.1080/10649867.1996.11745320,
	language: eng,
	issn: 2161-4504,
	superior_ppn: 845731157,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Larry Kent,
			last_name: Graham,
			type: author,
			gnd_number: 1024055361,
		},
		{
			first_name: Christie Cozad,
			last_name: Neuger,
			type: author,
		},
	],
}
MARC field for 'https://www.tandfonline.com/doi/abs/10.1080/10649867.1996.11745320 matched exclusion filter (245a/^Editorial?$/)
Conversion complete





Zotero Harvester Metrics:
	Journals: 1
		Direct: 1
		RSS: 0
			Skipped: 0
		Crawl: 0
	Crawls: 0
		Successful: 0
		Unsuccessful : 0
		Cache Hits : 0
	Harvests: 1
		Successful: 1
		Unsuccessful : 0
		Cache Hits : 0
		Skipped (already harvested): 0
		Skipped (already delivered): 0
	Records: 1
		Successful: 0
		Unsuccessful: 0
		Skipped (online-first): 0
		Skipped (early-view): 0
		Skipped (exclusion filter): 1
		Skipped (already delivered): 0

**Comment by IxKo** [comment]
@socheres Try URL mit der URL vom Editorial und der Additional Config filtert den Titel raus.
Auch wenn ich die URL des kompletten Heftes nehme, sowie es kdr154 macht, wird der Titel gefiltert.
Es tut also das was es soll.
