### ISSUE TITLE
ISSN 0720-6259 | Pastoraltheologie | Tabulatoren

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#846]
Die Tabulatoren müssen manuell bereinigt werden, sonst kommt es bei Upload zum Abbtuch. Z. B. bei diesem Titel https://www.vr-elibrary.de/doi/10.13109/path.2020.109.1.5 finden die sich sowohl im Abstract als auch im Titel.

**Comment by socheres** [comment]
Translaotorseitig lässt sich da nichts machen.
