### ISSUE TITLE
ISSN 2056-7731 | Baptist quarterly | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#848]
Rezensionen werden nicht getagt.
Bsp. https://www.tandfonline.com/toc/ybaq20/51/2?nav=tocList
Mehrere Erkennungskriterien: die ISBN, die Überschrift "Book Review" über den einzelnen Einträgen, das Wort "by" im Titel.
Sollte in meinen Augen ins vollautomatische Verfahren.

**Comment by socheres** [comment]
in zotat geändert.

**Comment by socheres** [comment]
behoben.
