### ISSUE TITLE
ngram score for language detecting

### ISSUE THREAD

**Issue by socheres** [ubtue/DatenProbleme#849]
@mtrojan-ub der Score-Wert für Französich ist nicht nachvollziehbar. Der Titel sollte höher bewertet werden?

```
Generated 1 record(s) for item 14 [Byzantion : revue in...] | http://poj.peeters-leuven.be/content.php?url=article&id=3117808 {12391827729700574930}


Converting item 15 [Byzantion : revue in...] | http://poj.peeters-leuven.be/content.php?url=article&id=3117809 {17469321939657604787}
use online ISSN "2294-6209" with online PPN "729751163"
post-processed author first name = 'Rudolf S.', last name = 'Stefec', title = '', affix = ''
forcing automatic language detection
generated too few ngrams (159 < 400)!
eng scored :0.615897
fre scored :0.618554
ger scored :0.595016
ita scored :0.566945
spa scored :0.574343
automatically detected language to be 'fre'
Augmented metadata record: MetadataRecord {
	url: https://poj.peeters-leuven.be/content.php?url=article,
	item_type: journalArticle,
	title: Drei theologische Werke des Michael Apostoles,
	abstract_note: The present article offers a critical edition of three theological treatises by the Cretan scholar and scribe Michael Apostoles (†1478). The texts show that Apostoles, once thought to be a staunch Unionist, only gradually shifted his religious sympathies from Orthodoxy to the Union of the churches.,
	publication_title: Byzantion,
	volume: 85,
	pages: 401-429,
	date: 2015-01-01,
	doi: 10.2143/BYZ.85.0.3117809,
	language: fre,
	issn: 2294-6209,
	superior_ppn: 729751163,
	superior_type: 2,
	ssg: 2,
	creators: [
		{
			first_name: Rudolf S.,
			last_name: Stefec,
			type: author,
		},
	],
}
Generated record with hash '5FD551A43F4DE20341429690128FBBD7217BF3E5'

Conversion complete
```
---------
Hier
IxTheo#2020-04-06#5FD551A43F4DE20341429690128FBBD7217BF3E5
steht fälschlicherweise fre in 041 statt de

![grafik](https://user-images.githubusercontent.com/29707105/78557438-162c4a80-7811-11ea-89e6-9135d3db9f8c.png)

_Originally posted by @kdr154 in https://github.com/ubtue/DatenProbleme/issues/432#issuecomment-609757891_

**Comment by mtrojan-ub** [comment]
@ruschein kannst Du bitte einen Blick drauf werfen?

**Comment by ruschein** [comment]
Bei dieser Zeitschrift können anscheinend 5 verschiedene Sprachen vorkommen, darunter auch Deutsch und Französisch.  Die Sprachzuweisung mit N-Grammen ist statistischer Natur und nie 100% zuverlässig.  Der Titel hier ist sehr kurz und enthält unter anderem die N-Gramme "dre" (vom Wort "Drei") und "des" welche beide recht häufig in der französischen Sprache vorkommen.  D.h., wir haben einfach Pech gehabt!  Desto kürzer der Text, der zur Klassifikation benutzt wird, desto wahrscheinlicher sind auch Falschzuweisungen!
