### ISSUE TITLE
ISSN 1477-4623 | Literature & theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#850]
Rezensionen werden nicht getagt. 
https://academic.oup.com/litthe/issue/34/1
Abgesehen davon, dass sie in der Sektion Book Review(s) stehen fällt mir nur auf, dass, zumindest in diesem Heft, immer das Wort  "by" im Titel vorkommt. Fraglich allerdings, ob dies nicht zu anderen Fehlern führt und ein zuverlässiges Kriterium ist. Darüber hinaus besitzen die Einträge kein Abstract.

**Comment by socheres** [comment]
in zotat geändert.

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
