### ISSUE TITLE
ISSN 1467-9647 | Teaching Theology & Religion | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#853]
Rezensionen werden nicht getagt. Auf den Seiten der Aufsätze befindet sich die Überschrift Book Review und weitere Elemente, wie eine ISBN, die als Kriterien dienen können.
https://onlinelibrary.wiley.com/doi/10.1111/teth.12521

**Comment by socheres** [comment]
zotat gesetzt.

**Comment by socheres** [comment]
Mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_0lscAu" "--output-filename=plYPGd.xml"  "--config-overrides=zotero_review_regex       = \bISBN\b"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://onlinelibrary.wiley.com/doi/10.1111/teth.12521"  "Teaching theology and religion"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Teaching theology and religion' \| DIRECT @ https://onlinelibrary.wiley.com/doi/10.1111/teth.12521 set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Teaching theology an...] \| https://onlinelibrary.wiley.com/doi/10.1111/teth.12521 {9867088819214999648} Harvest successful     Converting item 1 [Teaching theology an...] \| https://onlinelibrary.wiley.com/doi/10.1111/teth.12521 {9867088819214999648} use online ISSN "1467-9647" with online PPN "320636356" post-processed author first name = 'Kristin Johnston', last name = 'Largen', title = '', affix = '' added GND number 1017456712 for author Largen, Kristin Johnston (SWB lookup) expected language 'eng' but found 'en' title matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/teth.12521, 	item_type: review, 	title: Park, Jung Eun Sophia, and Emily S. Wu, eds. Interreligious Pedagogy: Reflections and applications in honor of Judith A. Berling. Asian Christianity in the Diaspora series. Cham: Palgrave Macmillan, 2018. ISBN: 978-3319915050. xv + 119 pages. $69.99., 	short_title: Park, Jung Eun Sophia, and Emily S. Wu, eds. Interreligious Pedagogy, 	publication_title: Teaching Theology, 	volume: 23, 	issue: 1, 	pages: 54-55, 	date: 2020-01-01, 	doi: 10.1111/teth.12521, 	language: eng, 	issn: 1467-9647, 	superior_ppn: 320636356, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Kristin Johnston, 			last_name: Largen, 			type: author, 			gnd_number: 1017456712, 		}, 	], } Generated record with hash '6EE7D7EF55F6A9C8773B9FA9EADEB285D230A259'  Conversion complete   Generated 1 record(s) for item 1 [Teaching theology an...] \| https://onlinelibrary.wiley.com/doi/10.1111/teth.12521 {9867088819214999648}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
