### ISSUE TITLE
ISSN 1573-6571 | Journal of Religion and Health | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#855]
Die Rezensionen werden nicht getagt. Sie sind mit Book Review überschrieben:
https://link.springer.com/journal/10943/59/2/page/2
https://link.springer.com/article/10.1007/s10943-020-00997-7
Auf der Seite des Artikels befindet sich eine ISBN

**Comment by socheres** [comment]
@mtrojan-ub diese Zeitschrift ist in harvester.config vorhanden, aber nicht auf Nu gelistet.

**Comment by mtrojan-ub** [comment]
Bei mir wird es auf nu ganz normal angezeigt:
![grafik](https://user-images.githubusercontent.com/26873381/85032416-1b4a3600-b180-11ea-840f-6b7810cd5533.png)

**Comment by socheres** [comment]
Die Sortierung ist case sensitive und daher unabhängig von Groß- und Kleinschreibung nicht alphabetisch sortiert, daher übersehen. Jetzt habe ich sie auch gefunden.

**Comment by socheres** [comment]
mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_9EIE9i" "--output-filename=pYEq29.xml" "--config-overrides= " "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://link.springer.com/article/10.1007/s10943-020-00997-7" "Journal of religion and health"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of religion and health' \| DIRECT @ https://link.springer.com/article/10.1007/s10943-020-00997-7 set download-delay for domain 'link.springer.com' to 1000 ms   Harvesting URL 1 [Journal of religion ...] \| https://link.springer.com/article/10.1007/s10943-020-00997-7 {12658962305833121217} Harvest successful     Converting item 1 [Journal of religion ...] \| https://link.springer.com/article/10.1007/s10943-020-00997-7 {12658962305833121217} use online ISSN "1573-6571" with online PPN "320578089" post-processed author first name = 'Robert D.', last name = 'Flanagan', title = '', affix = '' keyword matched review pattern Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1007/s10943-020-00997-7, 	item_type: review, 	title: Brian S. Powers: Full Darkness: Original Sin, Moral Injury, and Wartime Violence, 	short_title: Brian S. Powers, 	publication_title: Journal of Religion and Health, 	volume: 59, 	issue: 2, 	pages: 1137-1139, 	date: 2020-04-01, 	doi: 10.1007/s10943-020-00997-7, 	language: eng, 	issn: 1573-6571, 	superior_ppn: 320578089, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Robert D., 			last_name: Flanagan, 			type: author, 		}, 	], 	keywords: [ Book Reviews ], } Generated record with hash '9E3CF3A5A4946E199FC87D271C574BCF77744D3E'  Conversion complete   Generated 1 record(s) for item 1 [Journal of religion ...] \| https://link.springer.com/article/10.1007/s10943-020-00997-7 {12658962305833121217}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
