### ISSUE TITLE
ISSN 1868-8020 | Early Christianity | Sprache

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#856]
Wenn der Titel auf Englisch ist, dann ist auch der Text auf Englisch. Im Zoterofeld Sprache steht aber immer "de"
https://www.mohrsiebeck.com/zeitschrift/early-christianity-ec?no_cache=1

Im Übrigen, auch hier kann ich kein RSS mehr finden.

**Comment by socheres** [comment]
https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_language_code.map ergänzen

**Comment by socheres** [comment]
@IxKo Können Sie bitten recherchieren, ob woanders RSS-Feed angeboten wird?

**Comment by IxKo** [comment]
@socheres Es war noch kein RSS-Feed in Zeder hinterlegt. Habe nun den von Mohr Siebeck eingetragen.

**Comment by socheres** [comment]
im Zotkat die Sprache bitte manuell korrigieren.

**Comment by socheres** [comment]
- [ ] Zotaut Prüfung
- [ ] "sprz" ergänzen

**Comment by IxKo** [comment]
Da dies nicht der nächste Test-Kandidaten ist und das Issue schon sehr alt ist, schließe ich es vorerst.
