### ISSUE TITLE
ISSN 1759-8818 | Sociology of Religion | Abstracts

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#857]
Die Abstracts enthalten nach dem Download Paragraphzeichen und Leerzeichen, die zu einer Fehlermeldung beim Upload führen und diesen verhindern,
Bsp. dieser Artikel: https://academic.oup.com/socrel/article/81/2/142/5697468
sieht so aus:

![grafik](https://user-images.githubusercontent.com/29707105/79217815-c15f8400-7e4f-11ea-9d83-c467b6549fea.png)

**Comment by socheres** [comment]
zotat gesetzt. Problembehebung im Zotkat leider nicht möglich. Wie gewohnt weiter manuell die Tabulatorenzeichen entfernen.

**Comment by IxKo** [comment]
Zs ist bereits live, Problem betrifft zotkat
