### ISSUE TITLE
ISSN 2396-9407 | International bulletin of mission research | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#858]
Book Reviews bekommen Schlagwort Book Review 650 und 5520 anstatt 655 bzw 1131.
Etwa:
IxTheo#2020-04-09#70FBBE39065E3CDB8CB858F7248B4796DB1AC306
https://journals.sagepub.com/toc/ibmd/44/2

**Comment by mtrojan-ub** [comment]
Keyword ist ja vorhanden, ich vermute also die Fehlerquelle ist nicht der Translator sondern die zotero_harvester.conf, siehe: 
https://github.com/ubtue/zotero-enhancement-maps/blob/e49c7da2e239126f9d54ce49707dfeae6409fcb1/zotero_harvester.conf#L1934

- Da zotero_review_regex nicht konfiguriert ist, führt das Schlagwort nicht dazu dass der Datensatz als Review erkannt wird, somit fehlt 655
- Da remove_marc_field_650a nicht konfiguriert ist, spielt er das 650er Feld zusätzlich als Keyword aus.

Beispiel, bei dieser Zeitschrift ist beides vorhanden:
https://github.com/ubtue/zotero-enhancement-maps/blob/e49c7da2e239126f9d54ce49707dfeae6409fcb1/zotero_harvester.conf#L1916

**Comment by kdr154** [comment]
Dann vermutlich auch hier #860

**Comment by socheres** [comment]
@mtrojan-ub hier wird trotz `remove_field_650a         = "^Book Review?` 650 nicht entfernt.

**Comment by mtrojan-ub** [comment]
`remove_field_650a` ist keine gültige Direktive, es muss `remove_marc_field_650a` heißen (ist übrigens auch bei 2 anderen Zeitschriften falsch)

**Comment by socheres** [comment]
Danke. Habe überall korrigiert.

**Comment by kdr154** [comment]
Passt
