### ISSUE TITLE
ISSN 2077-1444 | Religions | 1. Buchstabe des Verfassers fehlt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#859]
Bei diesem Artikel: 
https://www.mdpi.com/2077-1444/11/4/178
Wird der 1. Buchstabe des Nachnamens des 1, Verfassers abgschnitten: aus Büssing wird üssing:
IxTheo#2020-04-09#B09B2FC3821C10E2BE163CC481DD9364BE07EE99

**Comment by socheres** [comment]
Ist nicht mehr der Fall.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_JxpWca" "--output-filename=ESr3Qm.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://www.mdpi.com/2077-1444/11/4/178" "Religions / Molecular  Diversity Preservation International (MDPI)"
-- | --
Runtime | 5s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Religions / Molecular Diversity Preservation International (MDPI)' \| DIRECT @ https://www.mdpi.com/2077-1444/11/4/178 set download-delay for domain 'www.mdpi.com' to 1000 ms   Harvesting URL 1 [Religions / Molecula...] \| https://www.mdpi.com/2077-1444/11/4/178 {11000784573223668049} Harvest successful     Converting item 1 [Religions / Molecula...] \| https://www.mdpi.com/2077-1444/11/4/178 {11000784573223668049} suppression regex '.*' matched metadata field 'pages' value '178' use online ISSN "2077-1444" with online PPN "665435797" post-processed author first name = 'Arndt', last name = 'Büssing', title = '', affix = '' post-processed author first name = 'Stephan', last name = 'Winter', title = '', affix = '' added GND number 129017566 for author Winter, Stephan (SWB lookup) post-processed author first name = 'Klaus', last name = 'Baumann', title = '', affix = '' added GND number 138942757 for author Baumann, Klaus (SWB lookup) expected language 'eng' but found 'en' Augmented metadata record: MetadataRecord { 	url: https://www.mdpi.com/2077-1444/11/4/178, 	item_type: journalArticle, 	title: Perception of Religious Brothers and Sisters and Lay Persons That Prayers Go Unanswered Is a Matter of Perceived Distance from God, 	abstract_note: Background: Sometimes prayer life can be difficult even for very religious persons, who may experience phases of spiritual dryness, which may have a negative effect on their well-being. Methods: To address this topic, we analyzed three contrasting groups of persons (religious brothers and sisters (RBS), n = 273; Catholic lay persons (CLP), n = 716; other lay persons (OLP), n = 351) with standardized measures and investigated how often indicators of spiritual dryness were perceived within these groups and how the perception that private prayers go unanswered could be a result of this. Results: Spiritual dryness was highest in RBS compared to RLP and OLP. For RBS, perception of being spiritually empty was the best predictor of prayers going unanswered, indicating emotional/spiritual exhaustion, while in OLP, the perception that God is distant was the best predictor, indicating that, particularly in this (younger) group, spiritual doubt is of particular relevance. For CLP, feeling that God is distant, feeling abandoned by God, and feeling spiritually empty were similarly relevant predictors of feelings that prayers go unanswered. Conclusions: This knowledge may help psychologists/psychotherapists, pastoral workers, and spiritual advisors to differentiate the underlying causes of spiritual dryness (in terms of discernment) and thus support persons struggling with God, their faith, and life., 	publication_title: Religions, 	volume: 11, 	issue: 4, 	date: 2020-04-01, 	doi: 10.3390/rel11040178, 	language: eng, 	issn: 2077-1444, 	superior_ppn: 665435797, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Arndt, 			last_name: Büssing, 			type: author, 		}, 		{ 			first_name: Stephan, 			last_name: Winter, 			type: author, 			gnd_number: 129017566, 		}, 		{ 			first_name: Klaus, 			last_name: Baumann, 			type: author, 			gnd_number: 138942757, 		}, 	], 	keywords: [ prayer, unanswered prayers, spiritual dryness, distance from God, emotional exhaustion, spiritual emptiness, well-being, religious brothers and sisters, lay persons ], } Generated record with hash '540F7FE25C805EEA37DAA30B7106454E793462E7'  Conversion complete   Generated 1 record(s) for item 1 [Religions / Molecula...] \| https://www.mdpi.com/2077-1444/11/4/178 {11000784573223668049}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0
