### ISSUE TITLE
ISSN 1752-4989 | Irish Theological Quarterly | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#860]
Vgl. #858 
Book Reviews bekommen Schlagwort Book Review 650 und 5520 anstatt 655 bzw 1131.
Etwa:
IxTheo#2020-04-08#0753961ADDFB2C036E7840DC1E4EF455232C9B34
https://journals.sagepub.com/doi/full/10.1177/0021140019895657h

**Comment by socheres** [comment]
@mtrojan-ub [Theoretical criminology : an international journal] ist zwar in Harvester.config vorhanden, aber nicht in Nu.

**Comment by mtrojan-ub** [comment]
Also bei mir taucht sie ganz normal auf, siehe Screenshot:
![grafik](https://user-images.githubusercontent.com/26873381/85019349-f600fc00-b16e-11ea-883d-eb629a073360.png)

**Comment by kdr154** [comment]
Book review Problematik ist gefixt
