### ISSUE TITLE
ISSN 1745-5308 | The Expository Times | Escape Character & ?

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#861]
Hier wird der Titel mit dem Zeichen & abgeschnitten:
IxTheo#2020-04-08#8B713ED6286BB5E516230D38CDCEE7FB256D8BB6

![grafik](https://user-images.githubusercontent.com/29707105/79236561-66d52080-7e6d-11ea-9de3-7ac8edf2b073.png)

https://journals.sagepub.com/doi/full/10.1177/0014524620906098

**Comment by socheres** [comment]
- [x] Rezension 655 und 650

**Comment by socheres** [comment]
@kdr154 mit Zotero-Client wird der Titel nicht abgeschnitten. Ein Harvester-Problem?

13:59:51 Returned item:
           {
             "itemType": "journalArticle"
             "creators": [
               {
                 "lastName": "Chu"
                 "firstName": "Ann Gillian"
                 "creatorType": "author"
               }
             ]
             "notes": []
             "tags": [
               {
                 "tag": "Book Review"
               }
             ]
             "seeAlso": []
             "attachments": [
               {
                 "title": "SAGE PDF Full Text"
                 "mimeType": "application/pdf"
               }
             ]
             "title": "T&T Clark Reader in Theological Anthropology"
             "date": "März 1, 2020"
             "DOI": "10.1177/0014524620906098"
             "publicationTitle": "The Expository Times"
             "journalAbbreviation": "The Expository Times"
             "pages": "275-275"
             "volume": "131"
             "issue": "6"
         -   "publisher": "SAGE Publications Ltd"
             "ISSN": "0014-5246"
             "url": "https://doi.org/10.1177/0014524620906098"
             "language": "en"
             "libraryCatalog": "SAGE Journals"
         -   "accessDate": "2020-06-18T11:59:51Z"
           }
13:59:52 Translation successful

**Comment by kdr154** [comment]
Ein generelles, wie mir scheint.

**Comment by kdr154** [comment]
Titel jetzt vollständig
