### ISSUE TITLE
ISSN 1745-5308 | The Expository Times | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#862]
Vgl. #858 und #860 
https://journals.sagepub.com/doi/full/10.1177/0014524620906098
IxTheo#2020-04-08#8B713ED6286BB5E516230D38CDCEE7FB256D8BB6

Book reviews werden nicht getagt, werden statt dessen zum Schlagwort.
Dasselbe in #922

**Comment by kdr154** [comment]
Wie ist es hiermit?
![grafik](https://user-images.githubusercontent.com/29707105/79238569-d4824c00-7e6f-11ea-8329-84b610599d3c.png)

**Comment by socheres** [comment]
in #861 gefixt.

**Comment by kdr154** [comment]
ok
