### ISSUE TITLE
ISSN 1126-9200 | Quaderni di storia religiosa medievale | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#864]
Auf den Seiten befinden sich Keywords:
https://www.rivisteweb.it/doi/10.32052/95676
Diese werden nicht erfasst,

**Comment by socheres** [comment]
Gibt es ein RSS-Feed? Dann könnten wir diese Zeitschrift ins Zotaut übernehmen.

**Comment by kdr154** [comment]
Den möglicherweise:
https://www.rivisteweb.it/issn/1126-9200/rdf

**Comment by kdr154** [comment]
Habe ihn mal in Zeder eingetragen und auf zotat gesetzt

**Comment by socheres** [comment]
Bitte zurück auf "zot" setzen. Kein RSS-Feed und noch kein Translator.

**Comment by kdr154** [comment]
gemacht..

**Comment by socheres** [comment]
@kdr154 @IxKo Können Sie diese Zeitschrift mit dem Translator "ubtue_Qauderni..." bearbeiten?

**Comment by kdr154** [comment]
ja, kann ich

 

_________________________

 

Klaus-Dieter Rosenkranz

Eberhard Karls Universität Tübingen

Telefon: Universitätsbibliothek +49 7071 29 72963

Mobil: 0173 3194973

 

E-Mail: rosenkranz@uni-tuebingen.de

 

 

Von: Kim, Timotheus Chang-whae <notifications@github.com> 
Gesendet: Donnerstag, 9. Juli 2020 12:16
An: ubtue/DatenProbleme <DatenProbleme@noreply.github.com>
Cc: kdr154 <rosenkranz@uni-tuebingen.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ubtue/DatenProbleme] ISSN 1126-9200 | Quaderni di storia religiosa medievale | Keywords (#864)

 

@kdr154 <https://github.com/kdr154>  @IxKo <https://github.com/IxKo>  Können Sie diese Zeitschrift mit dem Translator "ubtue_Qauderni..." bearbeiten?

**Comment by IxKo** [comment]
Kann ich nur bestätigen.

**Comment by kdr154** [comment]
Auch diese Keywords werden nun erfasst.
