### ISSUE TITLE
ISSN 2397-348X | Interreligious studies and intercultural theology | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#868]
IxTheo#2020-02-28#D9E926A2152C428AA6958B49DB4F920054C99C2C
ist eine Rezension. Diese wird nicht als solche erkannt.
https://journals.equinoxpub.com/ISIT/issue/view/2799

**Comment by mtrojan-ub** [comment]
Ist die angegebene ID tatsächlich korrekt? Hier ein Screenshot des Datensatzes aus zotero_ixtheo_200228_001.xml, laut dem 655a "Rezension" bei diesem Datensatz eingefügt wurde

![grafik](https://user-images.githubusercontent.com/26873381/82676552-e1e8de00-9c46-11ea-9c07-e06a195bfb50.png)

**Comment by IxKo** [comment]
Hallo, ich kann nur bestätigen, dass der genannte Artikel als Rezension erkannt wird. Eventuell handelte es sich hier um eine Verwechslung.

**Comment by kdr154** [comment]
Ist korrekt, war aber ein Irrtum
