### ISSUE TITLE
ISSN 2397-348X | Interreligious studies and intercultural theology | Book Reviews

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#869]
Diese Rezension wird nicht erkannt:
https://journals.equinoxpub.com/ISIT/article/view/37281
https://journals.equinoxpub.com/ISIT/issue/view/2902

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for testing" hinzufügen.

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
translators auf nu wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
gelöst
