### ISSUE TITLE
ISSN 2397-348X | Interreligious studies and intercultural theology | Berichtsjahr vs Publikationsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#870]
Bei der Ausgabe 4.2020,1 kommt es in den meisten Fällen zu einer Abweichung von Publikationsjahr und Berichtsjahr, wobei mir nicht ersichtlich ist, woher der Harvester seine Information zum Publikationsjahr bezieht. In 7 von 10 Fällen wird 2019 ausgegeben, nur bei den letzten 3 Aufsätzen 2020. Auf den Seiten der einzelnen Aufsätzen steht immer 2020.
https://journals.equinoxpub.com/ISIT/issue/view/2902
2019 hier:
IxTheo#2020-04-14#C064E624E2FEE8D8C75385C192300BF214DE94A1
2020 hier:
IxTheo#2020-04-14#80237F9452442B5EFB0F39DC890E2A5E30DEDE5B
Dasselbe Phänomen hatte ich auch beim halbautomatischen Verfahren, mit dem ich diese ZS heute morgen erfasst habe.
Hier das Bild aus Zotero mit einem Publikationsdatum 2019 bei einem Aufsatz aus Heft 4.2020,1

![grafik](https://user-images.githubusercontent.com/29707105/79320050-6f7b3480-7f09-11ea-86ee-6e5f2c68e785.png)

**Comment by mtrojan-ub** [comment]
Im angezeigten "issued date" steht zwar immer 2020, aber die Website liefert DC Meta header aus die damit nicht unbedingt übereinstimmen. Die Frage ist welches Datum man genau nehmen will, daher ist es vermutlich ein Translator-Problem.

https://journals.equinoxpub.com/ISIT/article/view/40147
- Buddhism and the Religious Other: Twenty-First Century Dambulla and the Presence of Buddhist Exclusivism in Sri Lanka
- Issued Date: 14 Apr 2020
- `<meta name="DC.Date.created" scheme="ISO8601" content="2019-11-21">`
=> **2019**

https://journals.equinoxpub.com/ISIT/article/view/40611
- Islamic humanism or humanistic Islam?
- Issued Date: 14 Apr 2020
- `<meta name="DC.Date.created" scheme="ISO8601" content="2020-02-05">`
=> **2020**

**Comment by socheres** [comment]
Datum grundsätzlich als Berichtsjahr ausgeben. Ist meistens auch der Fall.

**Comment by mtrojan-ub** [comment]
Derzeit gibt es JS Probleme auf den Artikelseiten und die DC header fehlen:
![grafik](https://user-images.githubusercontent.com/26873381/85108471-0fa65000-b210-11ea-96db-0296183dc94e.png)
![grafik](https://user-images.githubusercontent.com/26873381/85108529-28166a80-b210-11ea-98f0-0972b2aac516.png)

**Comment by IxKo** [comment]
#1078

**Comment by IxKo** [comment]
@socheres Hier ist das Berichtsjahr falsch und demnach auch die Regelung aus #1078

**Comment by socheres** [comment]
anstelle des Datums aus DC.date müsste das Berichtsjahr aus Issued date abgegriffen werden`var date = ZU.xpath(doc, '//*[@id="articleDateString"]')` @mtrojan-ub @jriedl kann einer von Euch den Translator anpassen?

**Comment by kdr154** [comment]
Es wird jetzt immer das Berichtsjahr erfasst.
