### ISSUE TITLE
ISSN 2153-3326 | Business ethics quarterly | Front matter Back matter

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#871]
Artikel, die die Begriffe Front Matter und Back Matter im Titel haben (tag 245), ausschließen.
IxTheo#2020-04-03#05E926259EF11A31974C23ED5E9603FFA31A6621
IxTheo#2020-04-03#1EFA3EE2D140CF6DEEE6AAD288CCD3530BCF7733

**Comment by socheres** [comment]
`exclude_if_marc_field_245a = "(^From the Editor$)|(Cover and (Front|Back) matter)"` hinzugefügt. Bitte mit "Try URL" testen.

**Comment by socheres** [comment]
hier noch die URL:
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/beq-volume-30-issue-2-cover-and-front-matter/63716AAEDC4F2CBD263C918BCDA83E7E
https://www.cambridge.org/core/journals/business-ethics-quarterly/article/beq-volume-30-issue-2-cover-and-back-matter/DF56397298110175E471B7A60989B3CE

**Comment by kdr154** [comment]
gefixt.
