### ISSUE TITLE
ISSN 2161-1874 | Journal of addictions & offender counseling | TOC 

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#872]
Das Inhaltsverzeichnis TOC ausschließen
KrimDok#2020-04-06#884848D8CB2F53BAE915AF64E4548FFBF8FD9DCA

**Comment by socheres** [comment]
keinen Datensatz in WiniBW gefunden. Bitte immer den dazugehörigen Link angeben!

**Comment by kdr154** [comment]
PPN auf T6 3556390353
Link https://onlinelibrary.wiley.com/doi/10.1002/jaoc.12071

**Comment by socheres** [comment]
mit "Try URL" getestet.
MARC field for 'https://onlinelibrary.wiley.com/doi/10.1002/jaoc.12071 matched exclusion filter (245a/(^Guidelines for Authors$)|(^Toc$)|(^TOC$)/)
Conversion complete
