### ISSUE TITLE
ISSN 2077-1444 | Religions | Zeichensatzprobleme

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#873]
Bei diesem Artikel:
IxTheo#2020-03-24#10DB74BB748653D5CC95832746F344343F60C1B5
https://www.mdpi.com/2077-1444/11/3/151
werden im Abstract der Bindestrich zwischen den Jahreszahlen (1392–1910) und der Buchstabe ü von  Lienü nicht dargestellt.
Hier das e mit Akzent beim Wort décor im Abstract:
https://www.mdpi.com/2077-1444/11/5/230
IxTheo#2020-05-07#9C4030F1A3F5AF0DB51F902FA78E24D471781D76

**Comment by socheres** [comment]
@mtrojan-ub werden HTML entity beim MARC-Output entfernt?  Via Zotero-Client wie folgt dargestellt: 
``
Women in Joseon Korea (1392&ndash;1910) were held to high standards of virtue, which were propagated through didactic texts such as the &ldquo;Chaste and Obedient Biographies&rdquo; volume of Lien&uuml; Zhuan, the Chinese classic featuring biographies of exemplary women. Joseon women who converted to Catholicism were also educated in standards of Catholic virtue, often through the biographies of saints, which shared with the Confucian exemplar stories an emphasis on faithfulness and self-sacrifice. Yet, the differences between Confucian and Catholic standards of virtue were great enough to elicit persecution of Catholics throughout the nineteenth century. Therefore conversion would have involved evaluating one set of standards against the other and determining that Catholicism was worth the price of social marginalization and persecution. Through a comparison of the Confucian exemplar stories and Catholic saints&rsquo; stories, this paper explores how Catholic standards of virtue might have motivated conversion of Joseon women to Catholicism. This comparison highlights aspects of the saints&rsquo; stories that offered lifestyle choices unavailable to women in traditional Joseon society and suggests that portrayals of the saints&rsquo; confidence in the face of human and natural oppressors could also have provided inspiration to ease the price of conversion.
``

**Comment by mtrojan-ub** [comment]
Ja, wir entfernen aktuell HTML Tags und Entites aus dem JSON Code der uns vom Zotero Translation Server übermittelt wird. Ich werde mal prüfen ob da ein Fehler vorliegt, aber im Optimalfall sollten Entities ja schon vom Translator richtig decodiert werden.

**Comment by mtrojan-ub** [comment]
@ruschein: Es sieht so aus aus wäre HtmlUtil::DecodeEntity für unsere Zwecke nicht ausreichend. Die Liste der unterstützten HTML Entities ist unvollständig (z.B. fehlt `&ndash;`). Außerdem wird das decodierte Entity als char zurückgegeben, was ja bei Unicode Entities vermutlich auch nicht alles abbilden kann (Beispiel für Entity das korrekt decodiert aber anschließend nicht sauber in UTF-8 umgewandelt wird: `&uuml;`)
https://github.com/ubtue/ub_tools/blob/4815f4f984a09cf6cf4713343daa808309581598/cpp/lib/src/HtmlUtil.cc#L41

=> Wir brauchen eine Variante davon die für Unicode bzw. UTF8 geeignet ist. Wie gehen wir da weiter vor?

**Comment by mtrojan-ub** [comment]
@ruschein hat das DecodeEntity überarbeitet, es sieht jetzt gut aus => ready for testing

**Comment by kdr154** [comment]
Gelöst
