### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses : revue trimestrielle _ RevSR | Jahr und Heft

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#875]
Warum wurde bei der Einspielung vom 24./25. 3. gerade dieses Heft aus dem Jahr 2014 geharvestet: 88.2014,4 und nicht eines der wesentlich weiter zurückliegenden Hefte. 
Siehe https://journals.openedition.org/rsr/1091
Und warum wurde die Lücke zum Heft 91.2017,1 nicht geschlossen.
Vgl. PPN 834395193

**Comment by mtrojan-ub** [comment]
Das liegt am RSS Feed. Wir lesen ja genau die Artikel die im Feed gelistet werden.
https://journals.openedition.org/rsr/backend?format=rssnumeros

Das erste Item im Feed hat `<dc:date>2020-03-15</dc:date>`aber folgenden Titel: 
`88/4 | 2014 – La déconstruction du christianisme. Autour d'une œuvre de J.-L. Nancy`
siehe http://journals.openedition.org/rsr/8579

![grafik](https://user-images.githubusercontent.com/26873381/82879147-d5ad9b00-9f3c-11ea-8af8-45b1eb29d53e.png)

**Comment by kdr154** [comment]
ok
