### ISSUE TITLE
ISSN 1477-2744 | Psychology, crime & law | Editorial

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#877]
Das Editorial kann entfallen:
KrimDok#2020-03-17#FBE8859E823B2454112BC137AF761C62419CAB36

**Comment by socheres** [comment]
unter dem Hash finde ich nichts, aber nach langem Suchen auf Verlagsseite den genannten Artikel gefunden und config ergäntz. Bitte mit "Try URL" Testen: 
https://www.tandfonline.com/doi/full/10.1080/1068316X.2020.1729968

**Comment by kdr154** [comment]
Krim!
gefixt.
