### ISSUE TITLE
ISSN 1468-5906 | Journal for the Scientific Study of Religion | Inhaltsverzeichnis

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#878]
Das Inhaltsverzeichnis, hier mit dem Titel "Issue Information ‐ TOC" kann entfallen:
IxTheo#2020-03-17#03307BD324BED74DFFB998D15E3FBE5D22C1A829

**Comment by kdr154** [comment]
Weiterhin enthalten. Vgl.:
https://onlinelibrary.wiley.com/toc/14685906/2020/59/2


![grafik](https://user-images.githubusercontent.com/29707105/87045166-db62f580-c1f7-11ea-8040-75fe5177b942.png)

**Comment by socheres** [comment]
`exclude_if_marc_field_245a = "^Issue Information$" > exclude_if_marc_field_245a = "^Issue Information"`korrigiert

**Comment by kdr154** [comment]
gelöst
