### ISSUE TITLE
ISSN 1468-2400 | International journal of systematic theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#879]
Vgl. auch #723 
Rezensionen werden nicht erkannt. Etwa:
IxTheo#2020-03-12#8E5175067A101D3E604CB1C2B5BF602FE61DA29F
Die Seite als solche bietet dazu einige Möglichkeiten:
https://onlinelibrary.wiley.com/doi/10.1111/ijst.12400
https://onlinelibrary.wiley.com/toc/14682400/2020/22/2

**Comment by socheres** [comment]
mit "Try URL" getestet. Bis auf https://onlinelibrary.wiley.com/doi/10.1111/ijst.12398 alle 8 Rezensionen richtig gekennzeichnet.
