### ISSUE TITLE
ISSN 1469-2147 | Cambridge Quarterly of Healthcare Ethics | Front Matter Back Matter

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#880]
Artikel, die die Begriffe Front matter und Back matter im Titel führen, können entfallen:
https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/issue/33A74B80AF58E1EA5C62B054F0E217AA
IxTheo#2020-03-11#22DFF0E87F04FEA99BEEFD8FC30E27B3D1714889
IxTheo#2020-03-11#29192C0C5115274DA1BF7DA11E5A73CC313DF96F

**Comment by socheres** [comment]
mit "Try URL" getestet `exclude_if_marc_field_245a = "Cover and (Front|Back) matter$"`


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_gAS75l" "--output-filename=qvjUAJ.xml"  "--config-overrides= exclude_if_marc_field_245a = "Cover and (Front\|Back) matter$""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL"  "https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472"  "Cambridge quarterly of healthcare ethics"
-- | --
Runtime | 9s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Cambridge quarterly of healthcare ethics' \| DIRECT @ https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472 set download-delay for domain 'www.cambridge.org' to 1000 ms   Harvesting URL 1 [Cambridge quarterly ...] \| https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472 {4926849904058586167} Harvest successful     Converting item 1 [Cambridge quarterly ...] \| https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472 {4926849904058586167} converted roman numeral page range 'f1-f5' to decimal page range 'F1-F5' use online ISSN "1469-2147" with online PPN "306655039" Augmented metadata record: MetadataRecord { 	url: https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472, 	item_type: journalArticle, 	title: CQH volume 29 issue 2 Cover and Front matter, 	publication_title: Cambridge Quarterly of Healthcare Ethics, 	volume: 29, 	issue: 2, 	pages: F1-F5, 	date: 2020-04-01, 	doi: 10.1017/S0963180119000938, 	language: eng, 	issn: 1469-2147, 	superior_ppn: 306655039, 	superior_type: 2, 	ssg: 2, } MARC field for 'https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/cqh-volume-29-issue-2-cover-and-front-matter/994313408F7411962F8F042163264472 matched exclusion filter (245a/Cover and (Front\|Back) matter$/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
