### ISSUE TITLE
ISSN 1745-5235 | Studies in Christian ethics | Titulatur QC beim Verfasser

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#883]
QC ist ein Titel. Siehe https://dictionary.cambridge.org/de/worterbuch/englisch/qc
und gehört wie der Jr. in das Pica 3000 Unterfeld $l, Marc  21 100 $c und sollte bei folgendem Artikel entweder beim Nachnamen getilgt werden und entfernt werden, oder in das entsprechende Unterfeld gesetzt werden.
IxTheo#2020-04-15#59B5B2986C9254BC2734E5D42C258777B57595B2

**Comment by socheres** [comment]
@mtrojan-ub wird der Punkt jetzt im https://github.com/ubtue/zotero-enhancement-maps/blob/master/author_name_blacklist.txt berücksichtigt. Sonst werden Namen die mit B. abgekürzt werden, fälschlicherweise getilgt.

**Comment by mtrojan-ub** [comment]
Das sollten wir gemeinsam mit #708 in einem Meeting besprechen

**Comment by kdr154** [comment]
Über Blacklist gelöst.
