### ISSUE TITLE
ISSN 1573-7799 | Journal of quantitative criminology | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#885]
Die Keywords werden bei dieser Zeitschrift nicht erfasst. Ein generelles Problem bei Springer. Sie befinden sich in der Sektion "About this article" am unteren Rand. Bsp.:
KrimDok#2020-03-10#B74DB9018F0FBAB051A19095831373FC2DD2FCE4
https://link.springer.com/article/10.1007/s10940-019-09410-3

**Comment by socheres** [comment]
Keywords in Nu vorhanden. 

keywords: [ Streets, Neighborhoods, Level of aggregation, Units of analysis, Egohood, Crime ],
}
Generated record with hash '49720115A462574ED3C1F5D0FAC5FA3C7C493479'
