### ISSUE TITLE
ISSN 1573-7799 | Journal of quantitative criminology | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#886]
Das Abstract ist umfangreicher als das was geharvestet wird. Es besitzt Abschnitte mit Überschriften. Die Frage ist, ob man mit dem, was erfasst wird, zufrieden sein kann. Und wenn nicht, wie man es umsetzen kann. Z. B. indem man jeden Abschnitt in ein eigenes Feld 520 / 4070 schreibt.
Bsp.:
https://link.springer.com/article/10.1007/s10940-019-09416-x
KrimDok#2020-03-10#3235EE0DE5E7B83E7643DBF5B9D0FC441BE1E44E

**Comment by socheres** [comment]
@mtrojan-ub kannst du bitte nach commit "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Sieht perfekt aus!
