### ISSUE TITLE
ISSN 1573-322X | Journal of agricultural and environmental ethics | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#887]
Bereits in #693 
Keywords werden nicht erfasst. Sie befinden sich in der Sektion "About this article".
Bsp.: 
IxTheo#2020-03-10#4750BBE0D7FF8352D434686252C8C9972678E42A
https://link.springer.com/article/10.1007/s10806-019-09809-9
Vgl. #885

**Comment by socheres** [comment]
gelöst.
