### ISSUE TITLE
ISSN 1477-0989 | Nursing ethics | 1. Buchstabe abgeschnitten

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#888]
Bei diesem Artikel wird der 1. Buchstabe beim Nachnamen des 3. Verfassers abgeschnitten:
xTheo#2020-03-05#E15910D7C586A6C2BE9071366888443F3C572914
https://journals.sagepub.com/doi/full/10.1177/0969733019864152

**Comment by mtrojan-ub** [comment]
Hängt mit Unicode zusammen, Beispiel: `Båkman`

Das Problem liegt im Harvester. Ich habe das Problem bei mir lokal behoben und den Pull request ubtue/ub_tools#3453 geöffnet den sich @ruschein anschauen sollte (er ist frühestens am Dienstag wieder im Haus).

Das Problem hängt mit einer Funktionalität zusammen die eigentlich diverse Abkürzungen aus dem Namen entfernen soll (die Liste enthält auch "B"), und aufgrund eines Unicode Problems im RegexMatcher wird das `å` fälschlicherweise als Wortgrenze eingestuft. Da potenziell auch alle anderen Unicode-Sonderzeichen betroffen sind und die Abkürzungsliste sehr lang ist hätte dieser Bug die Autorennamen natürlich auch in vielen anderen Fällen ziemlich verunstalten können.

**Comment by mtrojan-ub** [comment]
Die Änderung wurde heute eingespielt + kann jetzt erneut getestet werden (z.B. per "Try URL")

**Comment by IxKo** [comment]
Nachname wird nun richtig ausgegeben.
