### ISSUE TITLE
ISSN 1477-0989 | Nursing ethics | Zeichen ' kann nicht dargestellt werden.

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#889]
Bei diesem Artikel fällt auf, dass das Zeichen ' im Abstract durch ein ? ersetzt wird:
https://journals.sagepub.com/doi/full/10.1177/0969733019864152
IxTheo#2020-03-05#E15910D7C586A6C2BE9071366888443F3C572914

**Comment by socheres** [comment]
@mtrojan-ub liegt an dem Translator, aber konnte den Fehler nicht via Scaffold beheben, da beim "rund doweb" keine Datensätze angezeigt wird. Es kommt lediglich die Meldung "15:23:33 Translation successful".
abstract_note: Background:The occurrence of behavioural changes and problems, and degree of paranoid thoughts, are significantly higher among people who have experienced extreme trauma such as during the Holocaust. People with dementia and traumatic past experiences may have flashbacks reminding them of these experiences, which is of relevance in caring situations. In nursing homes for people with dementia, nursing assistants are often the group of staff who provide help with personal needs. They have firsthand experience of care and managing the devastating outcomes of inadequate understanding of a person?s past experiences.Aim:The aim was to describe nursing assistants? experiences of caring for older people with dementia who have experienced Holocaust trauma.Research design:A qualitative descriptive and inductive approach was used, including qualitative interviews and content analysis.Participants and research context:Nine nursing assistants from a Jewish nursing home were interviewed.Ethical considerations:The study was approved by the Regional Ethical Review Board, Stockholm.Findings:The theme ?Adapting and following the survivors? expression of their situation? was built on two categories: Knowing the life story enables adjustments in the care and Need for flexibility in managing emotional expressions.Discussion and conclusion:The world still witnesses genocidal violence and such traumatic experiences will therefore be reflected in different ways when caring for survivors with dementia in the future. Person-centred care and an awareness of the meaning of being a survivor of severe trauma make it possible to avoid negative triggers, and confirm emotions and comfort people during negative flashbacks in caring situations and environments. Nursing assistants? patience and empathy were supported by a wider understanding of the behaviour of people with dementia who have survived trauma.,
	publication_title: Nursing Ethics,

**Comment by mtrojan-ub** [comment]
Das ist wohl tatsächlich ein Härtefall. Ich kann es soweit zurückverfolgen, dass der SAGE Journals Translator den RIS Translator aufruft. Im Zotero Client klappt das, aber in Scaffold schlägt der RIS Translator fehl bzw. kann die URL nicht matchen. Ich vermute das beim Aufruf eines weiteren Translators über den Translator Editor (ehemals Scaffold) andere Umgebungsvariablen weitergegeben werden die beim Aufruf über Zotero weitergegeben werden (oder andere Prüfungen erfolgen).

Vielleicht kann uns @zuphilip hier weiterhelfen?

(Habe auch gesehen dass die Seite Cookies verwendet und man diese akzeptieren muss, aber selbst wenn ich das mache besteht immer noch das selbe Problem).

**Comment by mtrojan-ub** [comment]
Hmm seltsam... vielleicht war es doch ein Cookie Problem? Ich habe erst das Cookie akzeptiert, dann Zotero nochmal komplett geschlossen + neu gestartet, den Translator neu geladen, und jetzt erhalte ich ein Ergebnis

![grafik](https://user-images.githubusercontent.com/26873381/86002790-25d2be00-ba11-11ea-95d3-49803ee59f32.png)

**Comment by socheres** [comment]
nach Neustart sehe ich den Datensatz im Scaffold auch, aber wenn ich abstract debuggen möchte `Z.debug(abstract)` dann steht es wieder nur "Translation sucessful". Ich wußte leider auch nicht, warum der Apostroph in Fragezeichen umgewandelt wird.

**Comment by mtrojan-ub** [comment]
Zunächst mal baut sich der SAGE Journals Translator eine neue URL zusammen, in der der Datensatz erneut im RIS Format abgefragt wird. Für diesen Datensatz ist das (`risURL `+ `?` + `post`:
https://journals.sagepub.com/action/downloadCitation?doi=10.1177%2F0969733019864152&include=abs&format=ris&direct=false&submit=Download+Citation

Öffnet man diese URL z.B. im Firefox erscheint ein Popup vom Zotero Connector:
![grafik](https://user-images.githubusercontent.com/26873381/86011507-0b9edd00-ba1d-11ea-9162-c6124f4e3805.png)

Wenn man `Cancel `auswählt kann man sich die RIS Datei herunterladen mit einem Texteditor im Original anschauen:
![grafik](https://user-images.githubusercontent.com/26873381/86011710-591b4a00-ba1d-11ea-819f-e28df4ca6878.png)

Da es sich um eine UTF-8 Datei handelt in der das Fragezeichen bereits auftaucht sehe ich es als erwiesen an, dass es sich um ein Problem seitens der Website handelt.

**Comment by kdr154** [comment]
Danke für die Erklärung. Dann kann man ja schließen. Bedeutet aber, dass man diese Fälle manuell bereinigen muss.

**Comment by socheres** [comment]
im Translator steht als Kommentar:
```
// The encoding of apostrophs in the RIS are incorrect and
// therefore we extract the abstract again from the website.
```
Ich habe dementsprechend den Xpath wie folgt angepasst `//*[contains(concat( " ", @class, " " ), concat( " ", "abstractInFull", " " ))]` und der Apostroph wird nun richtig dargestellt.
![image](https://user-images.githubusercontent.com/1545743/86015964-85859500-ba22-11ea-931c-57a874c31aa9.png)

**Comment by socheres** [comment]
https://github.com/socheres/translators/commit/b55bea5ddf03d34091606baad1b00bbb0370889a#diff-cfd9c5aeb79a6ae314f19f96d272b852

**Comment by kdr154** [comment]
Ist aber weiterhin der Fall:

![grafik](https://user-images.githubusercontent.com/29707105/87042284-bc626480-c1f3-11ea-87b9-9f0518caa426.png)

**Comment by socheres** [comment]
hier wurde der Translator nur für Zotaut gefixt, aber nicht für Zotkat. Jetzt habe ich Ihr Skript auch aktualisiert. Bitte nochmal mit beiden Verfahren testen. 
![image](https://user-images.githubusercontent.com/1545743/87051427-d7d36c80-c1ff-11ea-87dd-bbbd04cc7ee1.png)

**Comment by kdr154** [comment]
Zotaut: hier ist es noch da:

![grafik](https://user-images.githubusercontent.com/29707105/87052499-246b7780-c201-11ea-93d3-ec9073a523ab.png)

halbautomatisch sieht es gut aus. Sowohl im Single als auch im Multi

**Comment by socheres** [comment]
ok. D.h. der Translator im Harvester wurde noch nicht aktualisiert. @mtrojan-ub kannst du nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Wenn ich das in Zotero teste ist der Zeichenfehler noch da. Kann es sein dass der letzte Stand des SAGE Journals Translators noch nicht in ubtue/zotero-translators übernommen wurde?

"lastUpdated": "2020-06-23 11:43:53"
Aktuell ist kein Pull Request mehr offen

**Comment by socheres** [comment]
Ja, hatte die Änderung nur lokal, aber nicht auf Github repository hochgeladen. Ich sollte am Besten je ein Repository für Zotkat und Zotaut haben, da beide Datei nicht immer identisch sind.

**Comment by kdr154** [comment]
Apostroph im Abstract wird dargestellt.
