### ISSUE TITLE
ISSN 1572-8609 | The journal of ethics | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#891]
Bei IxTheo#2020-03-05#9FAC87D3E292105986A73F1D19F9B5580126BD52 
handelt es sich um eine Rezension.  Vgl. die Überschrift "ReviewPaper" auf der Übersicht:
https://link.springer.com/journal/10892/24/1
Wird nicht erkannt.

**Comment by socheres** [comment]
ähnlich wie #803

**Comment by IxKo** [comment]
Befindet sich noch nicht im Test-Verfahren, daher schließe ich.
