### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#893]
Beiträge aus der Sektion Review Article(s) sind Rezensionen. Dies wird hier nicht erfasst:
IxTheo#2020-04-16#C5DC30B7D61539E2A83568E4F81FDCF30236EAF0
https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/issue/5951795A103FD6D12CF5DC64896F7521
Dies ist aber die Ausnahme. Rezensionen werden in der Regel als solche getagt. Aber es kommt immer mal wieder vor, dass eine nicht getagt wird. Diese auch nicht:
IxTheo#2020-05-07#9E8992B2F352FB1E04F4DAEE7236D082F30C6783

**Comment by socheres** [comment]
@mtrojan-ub hier sehe ich keine Möglichkeit. Was denkst du? Ähnlich wie #803

**Comment by mtrojan-ub** [comment]
Hier würde ich die selbe Translator-Anpassung empfehlen wie beim anderen Issue auch

```
<ul class="article-components">
<li class="source">DOI: <a href="https://doi.org/10.1017/S0022046919001751" target="_blank" class="url doi" data-test-id="reviewDOILink">https://doi.org/10.1017/S0022046919001751</a></li>
<li class="published">Published online by Cambridge University Press: <span class="date"> 23 January 2020</span></li>
</ul>
```

**Comment by IxKo** [comment]
Ist noch kein Test-Kandidat und Review Articles sollen nicht als Rezensionen eingespielt werden laut diesem Issue-Kommentar https://github.com/ubtue/DatenProbleme/issues/1305#issuecomment-768210580
