### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Einspielung unvollständig

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#894]
In der Einspielung vom 16,/17.04.2020 wird nur ein Teil der Artikel eingespielt, die das Heft 71.2020,1 enthält. Sie enthält 24 Artikel bis zur Seite 403. Alles was danach kommt fehlt.

**Comment by socheres** [comment]
vllt. ähnlich wie #771

**Comment by IxKo** [comment]
Noch kein Test-Kandidat, daher schließe ich.
