### ISSUE TITLE
ISSN 2236-6296 | Numen | LF führt zu Fehler

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#895]
Das Merkmal LF lizenzfrei wird in ein separtes Feld 856 geschrieben. Dies führt zu in der Ausgabe zu einem zusätzlichen Feld 4950, das keinen URL enthält. Die Information LF geht verloren.
Vgl. IxTheo#2020-04-19#09356702447C070EAE43668E0C607DABB9FA247C
Wurde bereits in #657 und #712 diskutiert.

**Comment by IxKo** [comment]
Da noch kein Test-Kandidat, schließe ich.
