### ISSUE TITLE
ISSN 2236-6296 | Numen | Überflüssige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#897]
Das, was in der Sektion Apêndice steht, kann entfalllen.  in diesem Fall der Artikel:
IxTheo#2020-04-19#AB85674E47B8EE8EE2FA54714B34B289587F2969
https://periodicos.ufjf.br/index.php/numen/article/view/30283
Ebenso die Artikel:
https://periodicos.ufjf.br/index.php/numen/article/view/30281
IxTheo#2020-04-19#99ADCC6436B723C7D7474B3EE36A8766AA1BAA22
und:
https://periodicos.ufjf.br/index.php/numen/article/view/30282
IxTheo#2020-04-19#BBD3493D1F990D3A24360554DAF699D37FA6E334

**Comment by socheres** [comment]
Titel mit folgendem Regex werden ausgesclossen: `exclude_if_marc_field_245a = `"(^Expediente)|(^Editorial)|(^Nominata)"``

**Comment by socheres** [comment]
seit wann haben wir Zss. mit Crawlverfahren im Test?

**Comment by kdr154** [comment]
Sieht gut aus.

**Comment by kdr154** [comment]
Das erste Issue über das Crawlverfahren ist vom 15.10.2019 #494
