### ISSUE TITLE
ISSN 2236-6296 | Numen | Überflüssig

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#898]
Der Begriff "Resumo" am Beginn des Abstracts ist ebenfalls überflüssig:
Bsp:
IxTheo#2020-04-19#17F74541E1FED8F58B5B154889FE0C6052588085

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit Label "ready for testing" ergänzen.

**Comment by kdr154** [comment]
ZS ist ungeeignet, da Seitenzahlen fehlen.

**Comment by mtrojan-ub** [comment]
Ist das noch aktuell?

Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Denke schon, Seitenzahlen müssen dem PDF entnommen werden. Kommt in meinen Augen nur zotkat in Frage.

**Comment by socheres** [comment]
> ZS ist ungeeignet, da Seitenzahlen fehlen.
ich kann die Webseite nicht öffnen http://numen.ufjf.emnuvens.com.br/numen  
Sind die Seitenzahlen nur im PDF vorhanden?

**Comment by kdr154** [comment]
Da wird an den Webseiten gearbeitet. Die ursprünglich in Zeder stehende Adresse war nicht mehr gültig. Diese hier  http://numen.ufjf.emnuvens.com.br/numen  hat dann funktioniert. Aber jetzt kommt hier eine 404 Error. Im PDF standen die Seitenzahlen drin

**Comment by kdr154** [comment]
Habe in Zeder den Link eingetragen, mit dem ich die Webseite erreichen konnte. Es werden jedoch weder auf nu noch mit dem Zotkat-Verfahren Seitenzahlen abgegriffen. Im PDF sind die Seitenzahlen enthalten. Ein Fall für zotkat in meinen Augen.

**Comment by IxKo** [comment]
Da noch kein Test-Kandidat, schließe ich.
