### ISSUE TITLE
ISSN 2236-6296 | Numen | Seitenzahlen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#899]
Die Seitenzahlen kann man nur dem PDF entnehmen.
https://periodicos.ufjf.br/index.php/numen/issue/view/1391
https://periodicos.ufjf.br/index.php/numen/article/view/28915

**Comment by socheres** [comment]
Seitenzahl nirgends zu finden. Dann ist die Zeitschrift nicht für Zotaut geeignet. #898 #897 #896 #895 entsprechend in ZEDER geändert "prodf=zot"

**Comment by kdr154** [comment]
Danke
