### ISSUE TITLE
ISSN 2236-6296 | Numen | Berichtsjahr vs Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#900]
Berichts- und Erscheinungsjahr differieren. Deshalb ist Pica 1100 bei dieser Ausgabe nicht richtig.
Die Artikel scheinen alle erst am 18.4.2020 publiziert worden zu sein, gehören aber zum Heft 22.2019,2
Vgl. etwa:
https://periodicos.ufjf.br/index.php/numen/article/view/28968

**Comment by IxKo** [comment]
#1078
