### ISSUE TITLE
ISSN 2074-7705 | Verbum et Ecclesia | LF führt zu Fehler

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#901]
Das Merkmal LF lizenzfrei wird in ein separtes Feld 856 geschrieben. Dies führt zu in der Ausgabe zu einem zusätzlichen Feld 4950, das keinen URL enthält. Die Information LF geht verloren.
IxTheo#2020-04-20#312DCF926AC4018CB295145FC24B32C0DC4E7B08
Vgl. #895  #657 und #712

**Comment by kdr154** [comment]
Das ist ein Problem,das für alle Zeitschriften gilt, die OA sind. Ich habe gestern die Zeitschrift Religions in der Mappingtabelle eingetragen. Jetzt zeigt sich auch bei dieser Zeitschrift das Problem. Ich mache jetzt wegen diesem Problem keine neuen Issues mehr auf, weil ich davon ausgehe, wenn es einmal stimmt, es dann bei allen betroffenen Zeitschriften richtig sein wird. Sollte es gewünsc ht sein, in diesem Zusammenhang für jede Zeitschrift ein Issue anzulegen, mache ich dies natürlich gerne.

**Comment by socheres** [comment]
Jetzt wird LF in der MARCXML richtig erzeugt. Ob in PICA dementsprechend rüberkommt, beobachten wir bei den neueren Datensätze weiter.
![grafik](https://user-images.githubusercontent.com/1545743/85262471-1b8f4d80-b46e-11ea-8307-b2f8084414b1.png)

**Comment by kdr154** [comment]
Ok, dann schließe ich
