### ISSUE TITLE
ISSN 2359-8107 | Review of Ecumenical Studies Sibiu | ISSN

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#902]
Hier wird die ISSN nicht übertragen. https://content.sciendo.com/view/journals/ress/10/2/ress.10.issue-2.xml
Sie befindet sich in der Übersicht, als auch auf den Einzelseiten am rechten Rand
Beim Verfahren Doi + Zauberstab ist sie dabei

**Comment by socheres** [comment]
@kdr154 Translator ist angepasst. ISSN kommen mit. Bitte noch folgendes eintragen.
ToDo ZEDER:
- [ ] "Zotat",
- [ ] Lizenzangaben,
- [ ] RSS-Feed in Zeder eintagen

ToDo IT:
- [ ] Editorial ausschließen
- [ ] Regex für "Book reviews" (Translaotor und config anpassen)

**Comment by IxKo** [comment]
Noch nicht im Test-Verfahren, daher schließe ich.
