### ISSUE TITLE
ISSN 2359-8107 | Review of Ecumenical Studies Sibiu | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#903]
Manche Artikel haben keywords. Diese werden nicht erfasst.
Bsp.:https://content.sciendo.com/view/journals/ress/10/2/article-p141.xml?tab_body=abstract
Auffallend ist, dass nur das Multidownloadverfahren funktioniert. Beim Singledownload wird die Webseite erfasst.

**Comment by socheres** [comment]
Keywords vorhanden.
- [x] Fix Singledownload

**Comment by IxKo** [comment]
Noch nicht im Test-Verfahren, daher schließe ich.
