### ISSUE TITLE
ISSN 2359-8107 | Review of Ecumenical Studies Sibiu | Zeichenprobleme

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#904]
Die diakritische Zeichen beim Verfasser führen zu einem Fehler bei der Umsetzung im K10plus. Die Buchstaben werden durch ein Fragezeichen ersetzt.
https://content.sciendo.com/view/journals/ress/10/2/article-p290.xml

![grafik](https://user-images.githubusercontent.com/29707105/79999451-35d39c00-84bc-11ea-8f95-8243ab25e2d8.png)

Hier auch im Abstract: https://content.sciendo.com/view/journals/ress/10/2/article-p186.xml?tab_body=abstract

![grafik](https://user-images.githubusercontent.com/29707105/80000059-f2c5f880-84bc-11ea-8806-ceacb4397465.png)

Auch hier: das Zeichen unter dem s beim Nachnamen
https://content.sciendo.com/view/journals/ress/10/3/article-p458.xml
hier dasselbe:
https://content.sciendo.com/view/journals/ress/10/3/article-p373.xml
auch hier, zudem fehlt der Rundbogen über dem a beim Vornamen
https://content.sciendo.com/view/journals/ress/10/3/article-p346.xml

**Comment by socheres** [comment]
ț Ț ș Ș ă Ă
umgesetzt.

**Comment by ruschein** [comment]
Eigentlich sollte es nicht nötig sein einzelne, spezifische Schriftzeichen individuell zu unterstützen.

**Comment by socheres** [comment]
@ruschein ja, kannst du dir bitte den Code [hier](https://github.com/socheres/zotkat/blob/master/PicaSWB_batch) anschauen und Vorschläge machen?

**Comment by ruschein** [comment]
Wie wäre es Zeile 218 durch "var line = code + " " + ConvertUTF8ToANSI(value);
" zu ersetzen?  Natürlich muss man dann eine ConvertUTF8ToANSI auch in der gleichen Datei implementieren.

**Comment by thefass** [comment]
Ist geklärt, dass die WinIBW tatsächlich ANSI braucht?

**Comment by thefass** [comment]
aus Versehen geschlossen. Sorry

**Comment by kdr154** [comment]
Nun besteht ein Problem mit dem Transator. Ich kann keine einzelnen Titel mehr herunterladen. In der Menuleiste ist nur das Zotero-Ordnersymbol zu sehen, nicht aber das, welches den Download eines einzelnen Titels anstößt.
Was übertragen wird ist dann tatsächlich die Dokumentart Webseite mit rudimentären Angaben, und nicht der Artikel.

**Comment by socheres** [comment]
gelöst in #903
