### ISSUE TITLE
ISSN 1743-1719 | Political theology | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#905]
Rezensionen werden nicht erkannt. Vgl. die aktuelle Ausgabe:
https://www.tandfonline.com/toc/ypot20/21/3?nav=tocList
und die entprechenden Artikel. Beispielsweise:
IxTheo#2020-04-22#7D424FB0630FA8C7270BD458D147B90DCA2938C4

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit das Label "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
gefixt
