### ISSUE TITLE
ISSN  2471-4054 | Journal of early Christian history | Haupttitel Titelzusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#906]
Wird beim vollautomatischen Verfahren grundätzlich auf einen Unterscheidung  von Haupttitel und Titelzusatz durch $d verzichtet?
Beispielsweise hier IxTheo#2020-04-22#EBE16727CE08ED59773D3262A1AD0243E335AC07
müsste 4000 nicht so:
4000 Authority as a Criterion of Truth: Ethics, Expertise and Power in the Theological Discourse of the Late Antique East
sondern so:
4000 Authority as a Criterion of Truth$dEthics, Expertise and Power in the Theological Discourse of the Late Antique East
aussehen.
In Marcxml nicht 
`<datafield tag="245" ind1="1" ind2="0"><subfield code="a">Authority as a Criterion of Truth: Ethics, Expertise and Power in the Theological Discourse of the Late Antique East</subfield>`
sondern
`<datafield tag="245" ind1="1" ind2="0"><subfield code="a">Authority as a Criterion of Truth</subfield><subfield code="b">Ethics, Expertise and Power in the Theological Discourse of the Late Antique East</subfield>`

**Comment by IxTheoKm** [comment]
Wir hatten das Thema schon mal angesprochen: es gibt kein eindeutiges Kriterium für die Abtrennung von Titel und Zusatz: Punkt, Doppelpunkt oder Gedankenstrich können nicht herangezogen werden. Bei Verlagseinspielungen und teilweise Migrationsdaten wurde deswegen grundsätzlich darauf verzichtet (nachdem bei einer Verlagseinspielung Punkt und Doppelpunkt als Kriterium verwendet wurde und zu gruseligen Ergebnissen geführt hat!)

**Comment by kdr154** [comment]
Danke für die Klärung
