### ISSUE TITLE
ISSN 2342-7256 | Temenos | Titelzusatz

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#907]
Diese Zeitschrift wird wohl halbautomatisch im Einzeldownloadverfahren erfasst.
Bei dieser Zeitschrift gibt es unterhalb des Titlels einen ausgegrauten Zusatz:
https://journal.fi/temenos/index
Dieser wird vom Translator möglicherweise als Titelzusatz interpretiert. Auf jeden Fall wird bei den Titeln, die keinen Titelzusatz in der Titelzeile besitzen, in Zotero ein Doppelpunkt am Ende des Titels gesetzt. In den anderen Fällen nicht.
Siehe hier mit Doppelpunkt:

https://journal.fi/temenos/article/view/87824

![grafik](https://user-images.githubusercontent.com/29707105/80085325-59e4bb00-8558-11ea-8e50-7d9d3f086033.png)

hier nicht:

https://journal.fi/temenos/article/view/87828

![grafik](https://user-images.githubusercontent.com/29707105/80085575-afb96300-8558-11ea-98a5-037dfab8b4c2.png)

Der Doppelpunkt am Ende führt in der WinIBW zu einem Fehler:

![grafik](https://user-images.githubusercontent.com/29707105/80085980-4dad2d80-8559-11ea-82d9-374719cf46ae.png)

Sieht dann in VuFind etwas irritierend aus.

**Comment by socheres** [comment]
Hier kann man nichts machen. Die Seitenzahlen auf der Webseite sind auch nicht richtig. Bitte in WiniBW korrigieren. Außerdem gibt es Dubletten in WinIBW zu diesem Artikel(PPN  1688709738 hier ist die Seitenzahl richtig. PPN  1695809165 hier falsch). Zur Kenntnis auch an @IxTheoKm

**Comment by kdr154** [comment]
Dann schließe ich

**Comment by socheres** [comment]
PPN  813203716 bitte noch korrigieren (Dubletten und Seitenzahlangaben).

**Comment by kdr154** [comment]
Die Seitenzahlen konnten korrigiert werden, für die Dublette eine Mail geschrieben werden.
