### ISSUE TITLE
ISSN 2192-2284 | Hebrew bible and ancient Israel | Zeichensatzprobleme

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#908]
Hier gibt es Probleme mit der Unsetzung von Zeichen im Abstract:
https://www.mohrsiebeck.com/artikel/scribalism-and-ritual-innovation-101628hebai-2018-0027?no_cache=1

![grafik](https://user-images.githubusercontent.com/29707105/80093706-47bd4980-8565-11ea-8eb0-4b1d7a8503f0.png)

**Comment by socheres** [comment]
Zeichensatzproblem wurde global gelöst. Kommt auch richtig rüber:

application.activeWindow.command("e", false);
application.activeWindow.title.insertText("\n0500 Osn\n0501 Text$btxt\n0502 Computermedien$bc\n0503 Online-Ressource$bcr\n1100 2018$n[2018]\n1500 ger\n1505 $erda\n2051 10.1628/hebai-2018-0027\n3000 !364572183!$BVerfasserIn$4aut\n8910 $aixzom$bAutor in der Zoterovorlage [MacDonald, Nathan] maschinell zugeordnet\n\n4000 Scribalism and Ritual Innovation\n4070 $v7$j2018$a4$p415-429\n4207 The ritual texts of the Pentateuch do not always reflect actual cultic procedures of the Second Temple. Two examples are examined where this is probably the case: first, the confusion of t\u01ddn\u00fbp\u00e2 and t\u01ddr\u00fbm\u00e2 and, second, the blood manipulation of Exodus 24. A careful examination of these two examples can lead to a better appreciation of the historical cult of Israel and the effects of textualization of rituals.\n4241 Enthalten in!718594010!\n5056 1\n5520 |s|Priestly Literature\n5520 |s|blood manipulation\n5520 |s|ritual practice\n5520 |s|sacrifice\n5520 |s|textualization\nE* l01\n7100$Jn\n8012 ixzs$aixzo");
application.activeWindow.pressButton("Enter");
