### ISSUE TITLE
Falsche Anzeige nicht-lateinischer Schriftzeichen und Sonderzeichen

### ISSUE THREAD

**Issue by IxTheoKm** [ubtue/DatenProbleme#909]
Das Problem taucht unabhängig von bestimmten Zeitschriften immer wieder auf und betrifft sowohl zotkat als auch zotaut. Teilweise war das Problem lt. kdr154 schon gelöst worden, tauchte dann aber doch erneut bei derselben Zeitschrift auf. Es waren dann jedesmal zeitschriftenbezogen erneut Eingriffe durch socheres erforderlich.

Gibt es keine Möglichkeit, das Problem der Zeichensätze unabhängig von bestimmten Zeichen und unabhängig von bestimmten Zeitschriften oder Erfassungsfelder zu lösen?

Nicht-lateinische Schriftzeichen und manche Sonderzeichen werden sonst im K10plus durch Fragezeichen dargestellt (in manchen Fällen sind fallen sie lt. kdr154 komplett weg). Das fällt bei zotkat schon manchmal nicht sofort auf und erfordert sonst manuelle Nacharbeit. Bei zotaut wird es wohl ständig durchrutschen.

Beispiele für Abstracts: 
https://ixtheo.de/Record/1681948656

![Zeichensatz](https://user-images.githubusercontent.com/17004223/80097071-f3b56380-856a-11ea-97d1-2bfc5703c7e7.JPG)

![Zeichensatz2](https://user-images.githubusercontent.com/17004223/80097089-fb750800-856a-11ea-816f-9097bdea2411.JPG)

https://ixtheo.de/Record/1681948648

![Zeichensatz3](https://user-images.githubusercontent.com/17004223/80096100-586fbe80-8569-11ea-9516-a510ade117c6.JPG)

![Zeichensatz4](https://user-images.githubusercontent.com/17004223/80096121-5f96cc80-8569-11ea-90d2-fefdad602de1.JPG)

**Comment by thefass** [comment]
ja bitte nach Möglichkeit global lösen

**Comment by kdr154** [comment]
Ich denke auch an solche Saxhen wie in #904

**Comment by kdr154** [comment]
Hier z. B. wird nicht einmal ein ? erzeugt:
Vorlage: https://content.sciendo.com/view/journals/ress/11/2/article-p317.xml
In Zotero sieht noch alles korrekt aus:

![grafik](https://user-images.githubusercontent.com/29707105/80101550-d768f500-8571-11ea-85d8-b533aa71d9f4.png)

 In der WinIBW fehlt dann die Cedille unter dem s bei Dragos:

![grafik](https://user-images.githubusercontent.com/29707105/80101746-1dbe5400-8572-11ea-8e55-ec5c4f08be9c.png)

**Comment by ruschein** [comment]
Aus meiner Sicht gibt es mindestens 3 Möglichkeiten:
1) Ein Font fehlt auf Ihren lokalen Arbeitsplatzsystemen.
2) WinIBW ist schlampig programmiert und muss verbessert werden.
3) Die Daten sind falsch in der Datenbank.
4) Wir liefen defekte Daten.

3) halte ich für sehr unwahrscheinlich da wir jeden Tag Datensätze vom K10+ erhalten die viele derartige Zeichen enthalten.  Vermutlich ist es 2) oder 4).  Wir sollten mal zur Kontrolle unsere MARC-XML-Datensätze anschauen um sicherzustellen, dass es nicht 4) ist.
Ich hoffe, dass es 4) ist da wird das vermutlich relativ leicht beheben könnten!

**Comment by kdr154** [comment]
Man muss die Gesamtproblematik möglicherweise getrennt angehen. Gut wäre z.B., wenn man für das Hebräische eine Lösung finden könnte.

**Comment by socheres** [comment]
die Zeichenumsetzung wird nicht zeitschriftenabhängig, sondern global umgesetzt, wenn die in der Codezeile hinterlegt ist:
https://github.com/socheres/zotkat/blob/cc4ab685529507023dde03765c666fac0a1f7bef/PicaSWB_batch#L215
Ich füge diese Sonderzeichen erst nach Meldung durch die Katalogisierer in die Mapping hinzu. Alle Sonderzeichen des Hebräischen und Griechischen sind alle vorhanden. Bei dem Titel, wo lateinische und hebräische Buchstaben zusammen vorkommen, da gibt es Konflikte mit der Schreibrichtung der beiden Sprachen in WinIBW und hierzu habe ich auch keine Lösung gefunden.

**Comment by kdr154** [comment]
Dann wäre das hier so ein Fall:
https://poj.peeters-leuven.be/content.php?url=article&id=3286682&journal_code=SE

**Comment by kdr154** [comment]
Das hier auch: https://ojs.reformedjournals.co.za/stj/article/view/1914
Auch hier hat Herr Cloutier berichtet, dass es ein Problem mit der Schreibrichtung gibt.

**Comment by socheres** [comment]
wenn es nur ein hebräisches Wort im Titel mit anderen lateinischen Wörtern vorkommt, wird richtig angezeigt. Das Problem tritt nur bei mehr als ein hebräisches Wort wie z.B. #820

**Comment by kdr154** [comment]
Dachte mir schon, dass der Fall ähnlich liegt, obwohl der Bearbeiter nur davon sprach, dass der erste und letzte Buchstabe vertauscht seien. Vielen Dank für Ihre Mühen!

**Comment by ruschein** [comment]
Ist das jetzt nur ein Bug in WiniBW?  Wie sieht die Anzeige im Webbrowser aus?  Hier ist die Dokumentation wie das korrekt zu geschehen hat: https://en.wikipedia.org/wiki/Bidirectional_text Es ist ein komplexer Algorithmus und vermutlich ist es einfach hier einen Fehler zu machen.
Wir sollten auf jeden Fall das Problem ganz allgemein lösen, d.h., unabhängig von  den Verlagswebseiten, den spezifischen Sprachen oder gar einzelnen Zeichen!

**Comment by kdr154** [comment]
Zur Schreibrichtung siehe #820 
Sieht so aus, als ob der Fehler im Uploadprozess entsteht.

**Comment by ruschein** [comment]
Das verstehe ich nicht!  Wenn die Daten die wir erzeugen korrektes UFT-8 enthalten liegt der Fehler beim BSZ, wenn nicht müssen wir etwas bei uns korrigieren.

**Comment by kdr154** [comment]
Die WinIBW benutzt meines Wissen den ANSI Zeichencode. Insofern wundert mich das auch nicht.

**Comment by ruschein** [comment]
ANSI zu verwenden ist ein Bug!!!  Trotzdem, hier http://jsfromhell.com/geral/utf-8 sind JavaScript-Funktionen für die Konvertierung UTF-8 <-> ANSI.

**Comment by socheres** [comment]
gelöst #943 @ruschein kannst du PPN-Liste generieren, wo im Titel und Abstract mehrere Fragezeichen vorkommen (Regex). Ich kann vielleicht die Datensätze in WinIBW mit Batchskript korrigieren.

**Comment by ruschein** [comment]
Hier ist die Liste.
[double_question_mark_ppns.txt](https://github.com/ubtue/DatenProbleme/files/4620536/double_question_mark_ppns.txt)

**Comment by socheres** [comment]
welcher regex hast du verwendet?

**Comment by socheres** [comment]
Die Liste enthält auch Bücher. Ich brauche nur Aufsatztitel mit dem Abrufzeichen ixzo 
```

LOK |   |   | \|0 935      \|a ixzs    \|a ixzo
-- | -- | -- | --
```

**Comment by ruschein** [comment]
Hallo Chang-Whae,


ich habe die Liste mit folgendem Kommando erzeugt:


marc_grep ~/Daten/IxTheo/GesamtTiteldaten-200430.mrc '"245a"'|egrep  '.*\?.*\?.*'|cut -d: -f1 > double_question_mark_ppns.txt


VG,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by ruschein** [comment]
Hallo Chang-Whae,


ich habe jetzt nur die Datensätze analysiert, die im Leader als "serial component part" getaggt sind.  Das sind 541.  Das noch nach Abrufzeichen zu filtern ist ohne C++-Programm zu aufwendig bzw. bin ich mir nicht sicher ob mein marc_grep das überhaupt kann, die Syntax ist recht kompliziert...   Ob sich das lohnt?


Neue Liste ist im Anhang.


VG,

Johannes

--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by ruschein** [comment]
Hier ist die neue Kommandozeile:


marc_grep ~/Daten/IxTheo/GesamtTiteldaten-200430.mrc 'leader[7]="b" "245a"'|egrep  '.*\?.*\?.*'|cut -d: -f1 > double_question_mark_ppns.txt



--
Dr. Johannes Ruscheinski
Universitätsbibliothek Tübingen - IT-Abteilung -
Wilhelmstr. 32, 72074 Tübingen

Tel: +49 7071 29-72820
FAX: +49 7071 29-5069
Email: johannes.ruscheinski@uni-tuebingen.de

 The Sophisticate:  "The world isn't black and white.  No one does pure good or pure bad. It's all gray.  Therefore, no one is better than anyone else."
    The Zetet:  "Knowing only gray, you conclude that all grays are the same shade.  You mock the simplicity of the two-color view, yet you replace it with a one-color view..."
      —Marc Stiegler, David's Sling


________________________________

**Comment by socheres** [comment]
gelöst
