### ISSUE TITLE
Sage ISSN 1466-8025 Criminology & Criminal Justice

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#91]
Vgl.  #87

**Comment by mtrojan-ub** [comment]
856 ist gelöst (#86). 
@shadeMe : Bitte mal den Translator anschauen wegen den Keywords, siehe #88

**Comment by shadeMe** [comment]
Keywords sind gefixt.

**Comment by kdr154** [comment]
Bleibt die Frage, wie wir mit dem Mix verfahren

**Comment by shadeMe** [comment]
Die Online-First Problematik ist jetzt gelöst. Bitte nochmal prüfen.

**Comment by kdr154** [comment]
Gelöst
