### ISSUE TITLE
ISSN 1872-0226 | Contemporary Islam | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#911]
Die Artikel haben keywords, die nicht erfasst werden. Sie befinden sich in der Sektion "About this article"
Vgl. etwa:
https://link.springer.com/article/10.1007/s11562-019-00441-y
IxTheo#2020-04-23#54FBDFB3C202E40FF5B32B2103E371BF53DF3C7E

Auch dieses Problem wurde bereits mehrfach thematisiert im Zusammenhang mit Springer Zeitschriften, wie diese auch eine ist. Vgl. etwa #887, #885, #854, #828, #818, #807 
Deshalb auch hier die Frage, Es handelt sich um ein grundsätzliches Problem, das bei allen Zeitschriften auftritt, die von Springer publiziert werden. Soll jedesmal, wenn dieses Problem bei einer Spinger-Zeitschrift auftritt, ein neues Issue angelegt werden, oder nicht?

**Comment by kdr154** [comment]
Gleich die nächste Spinger Zeitschrift, bei der das so ist: 
1573-0697 Journal of business ethics
https://link.springer.com/article/10.1007/s10551-019-04228-2
IxTheo#2020-04-23#9E14F149C5E30B3C1719517DB37271257495B399

**Comment by IxKo** [comment]
Werden nun erfasst.
