### ISSUE TITLE
ISSN 1573-0697 | Journal of business ethics | Spanische Schreibweise von Maria

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#912]
Die spanische Schreibweise von Maria: Mª wird hier orthografisch eins zu eins übernommen:
https://link.springer.com/article/10.1007/s10551-018-4038-4
IxTheo#2020-04-23#2E96843CE7ECAF05D3DC447934F81CCBED7D5C3D
![grafik](https://user-images.githubusercontent.com/29707105/80189036-501f8e00-8612-11ea-9443-b439e56ee1dc.png)
Wobei ich nicht sagen kann, ob man das als Sonderzeichen werten kann.
Das RDA toolkit schreibt dazu:
"Sprache und Schrift
Erfassen Sie Namen in der Sprache und Schrift, in der sie in den Quellen erscheinen, aus denen sie entnommen sind."
Dann kann man es  so lassen. Oder?

**Comment by socheres** [comment]
@IxTheoKm @IxKo ?

**Comment by IxKo** [comment]
Ich habe keine Einwände es so zu belassen, da es mit Suche "ma" gefunden wird und der Vorlage entspricht.

**Comment by kdr154** [comment]
dann schließe ich

**Comment by IxTheoKm** [comment]
Ich stimme IxKo zu, obwohl der Vorrang für die Vorlage nicht auf die 3000er Felder zutrifft.
Relevant ist m.E dass die gelieferte/abgelegte Form ggf. die maschinelle Verknüpfung zulässt. Ich kann es nicht beurteilen, da ich das technische Verfahren dahinter nicht genau verstehe. 
@socheres Wenn das hochgestellte a recherchierbar ist, sollte es wohl aber kein Problem sein, oder?

Grundsätzlich steht in den 3000er Feldern der normierte Sucheinstieg, sprich: die Form, die in der GND als normierter Sucheinstieg gültig wäre, wenn man dort denn einen Normsatz anlegen würde. Dort stünde aber (bisher) die Form „Ma“ mit a auf der Grundlinie. Vgl. GND gnd/118073078X
http://d-nb.info/gnd/118073078X

Zur Info: Manche Verlage liefern auf a auf der Grundlinie, obwohl die Vorlage anders ist: 
https://brill.com/view/journals/dsd/6/1/article-p66_5.xml

**Comment by socheres** [comment]
Sonderzeichen in WiniBW werden als normalisierte Buchstaben indexiert, daher sehe ich da kein Problem beim GND Lookup.

**Comment by IxTheoKm** [comment]
Danke, dann schließe ich.
