### ISSUE TITLE
ISSN 1758-6623 | The ecumenical review | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#913]
Bereits in #709 diskutiert
Die Rezensionen werden nicht getagt, Statt dessen gibt es ein Schlagwort:
IxTheo#2020-04-24#42D946BA64C26B5A870CE0A7F914BF693ED49D8D
Möglicheweise muss der Eintrag in der ini überarbeitet werden.
https://github.com/ubtue/zotero-enhancement-maps/blob/c7a8d56b4e40b4cfb6c894cd279f19c30faf547c/zotero_harvester.conf#L4110

**Comment by socheres** [comment]
gelöst
