### ISSUE TITLE
ISSN 2077-1444 | Religions | Merkmal lizenzfrei nicht richtig erfasst

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#914]
Das Merkmal LF lizenzfrei wird in ein separtes Feld 856 geschrieben. Dies führt zu in der Ausgabe zu einem zusätzlichen Feld 4950, das keinen URL enthält. Die Information LF geht verloren.

**Comment by socheres** [comment]
#901

**Comment by kdr154** [comment]
Siehe #901, schließe ebenfalls
