### ISSUE TITLE
ISSN 2161-8534 | American catholic studies | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#915]
Rezensionen werden nicht erkannt:
IxTheo#2020-04-27#15D644B0442039D88495218B84FFEA8259661C74
https://muse.jhu.edu/article/753871
ini?:
https://github.com/ubtue/zotero-enhancement-maps/blob/c9a9ed43783a783e8e4a1e824a469f995b2f5199/zotero_harvester.conf#L1230

**Comment by socheres** [comment]
mit "Try URL" geteste.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_OmN7j5" "--output-filename=K9tatA.xml"  "--config-overrides=zotero_review_regex       = \(review\)"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://muse.jhu.edu/article/753871" "American catholic studies :  journal of the American Catholic Historical Society"
-- | --
Runtime | 4s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'American catholic studies : journal of the American Catholic Historical Society' \| DIRECT @ https://muse.jhu.edu/article/753871 set download-delay for domain 'muse.jhu.edu' to 1000 ms   Harvesting URL 1 [American catholic st...] \| https://muse.jhu.edu/article/753871 {12377116950651857113} Harvest successful     Converting item 1 [American catholic st...] \| https://muse.jhu.edu/article/753871 {12377116950651857113} use online ISSN "2161-8534" with online PPN "663147344" post-processed author first name = 'Susan .', last name = 'Ridgley', title = '', affix = '' title matched review pattern Augmented metadata record: MetadataRecord { 	url: https://muse.jhu.edu/article/753871, 	item_type: review, 	title: Millennial Missionaries: How a Group of Young Catholics is Trying to Make Catholicism Cool by Katherine Dugan (review), 	short_title: Millennial Missionaries, 	publication_title: American Catholic Studies, 	volume: 131, 	issue: 1, 	pages: 83-84, 	date: 2020-04-23, 	doi: 10.1353/acs.2020.0001, 	language: eng, 	issn: 2161-8534, 	superior_ppn: 663147344, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Susan ., 			last_name: Ridgley, 			type: author, 		}, 	], } Generated record with hash 'D50AC6CBC4885FC048185735EE90A5BA9FE60834'  Conversion complete   Generated 1 record(s) for item 1 [American catholic st...] \| https://muse.jhu.edu/article/753871 {12377116950651857113}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
