### ISSUE TITLE
ISSN 2161-8534 | American catholic studies | Überflüssiger Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#916]
Dieser Artikel kann weggelassen werden:
IxTheo#2020-04-27#31E6E1D50478B9376C4398ABA8D28090148F4E4E
https://muse.jhu.edu/issue/42195

**Comment by socheres** [comment]
mit "Try URL" getestet

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_TO6eK7" "--output-filename=Y2WDsu.xml"  "--config-overrides=exclude_if_marc_field_245a = "^About this Issue$""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://muse.jhu.edu/article/753870" "American catholic studies :  journal of the American Catholic Historical Society"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'American catholic studies : journal of the American Catholic Historical Society' \| DIRECT @ https://muse.jhu.edu/article/753870 set download-delay for domain 'muse.jhu.edu' to 1000 ms   Harvesting URL 1 [American catholic st...] \| https://muse.jhu.edu/article/753870 {4600568843063575432} Harvest successful     Converting item 1 [American catholic st...] \| https://muse.jhu.edu/article/753870 {4600568843063575432} converted roman numeral page range 'i-i' to decimal page range '1-1' use online ISSN "2161-8534" with online PPN "663147344" post-processed author first name = 'Brett', last name = 'Grainger', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: https://muse.jhu.edu/article/753870, 	item_type: journalArticle, 	title: About this Issue, 	publication_title: American Catholic Studies, 	volume: 131, 	issue: 1, 	pages: 1, 	date: 2020-04-23, 	doi: 10.1353/acs.2020.0000, 	language: eng, 	issn: 2161-8534, 	superior_ppn: 663147344, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Brett, 			last_name: Grainger, 			type: author, 		}, 	], } MARC field for 'https://muse.jhu.edu/article/753870 matched exclusion filter (245a/^About this Issue$/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
