### ISSUE TITLE
ISSN 0717-6295 | Teología y vida | LF führt zu Fehler

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#917]
Das Merkmal LF lizenzfrei wird in ein separtes Feld 856 geschrieben. Dies führt zu in der Ausgabe zu einem zusätzlichen Feld 4950, das keinen URL enthält. Die Information LF geht verloren.
xTheo#2020-04-27#BD37813B37F32C270AC7284E6F681CEA530D7B78

**Comment by IxKo** [comment]
siehe #713
