### ISSUE TITLE
ISSN 0717-6295 | Teología y vida | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#918]
Auf den Webseiten sind keywords zu finden. Diese werden nicht erfasst:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0049-34492020000100047&lng=es&nrm=iso&tlng=es
IxTheo#2020-04-27#018CE2F03C901C6FB0613CD7484B60AAE6FBBB23

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
gefixt.
