### ISSUE TITLE
ISSN 0717-6295 | Teología y vida | Abstract

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#919]
hier stehen auch englischsprachige Abstracts zur Verfügung (resumen en Inglés). Erfasst wird aber nur das spanische:
https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0049-34492020000100047&lng=es&nrm=iso&tlng=es
IxTheo#2020-04-27#018CE2F03C901C6FB0613CD7484B60AAE6FBBB23

**Comment by socheres** [comment]
@mtrojan-ub engl. abstract muss nochmal im Browser aufgerufen werden. Weißt du vielleicht, mit welcher ZU.Funktion eine weitere Seite aufgerufen werden kann, um einen bestimmten XpathText zu scrapen?  In diesem Fall wäre https://scielo.conicyt.cl/scielo.php?script=sci_abstract&pid=S0049-34492020000100047&lng=es&nrm=iso&tlng=en Mit ZU.processDocuments etc. versucht, allerdings ohne Ergebnis.

**Comment by socheres** [comment]
Außerdem noch die Definition von  4207 "Das Feld 4207 enthält eine inhaltliche Zusammenfassung der Vorlage (Summary, Abstract usw.)." https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=4207&katalog=Standard

**Comment by mtrojan-ub** [comment]
Habe ich selbst zwar noch nie verwendet, aber es gibt Beispiele für `ZU.doGet`, z.B. in `EIDR.js`

**Comment by kdr154** [comment]
Fehler beim Test:

XML-Verarbeitungsfehler: Kein Wurzel-Element gefunden
Adresse: http://nu.ub.uni-tuebingen.de/zotero_cgi?action=download&id=/tmp/ZtsMaps_uALSq4/ixtheo/fb9Uh5.xml
Zeile Nr. 1, Spalte 1:

**Comment by mtrojan-ub** [comment]
Der RSS Feed ist zwar vorhanden, enthält aber keine Items:
https://scielo.conicyt.cl/rss.php?pid=0049-3449&lang=es

```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
  <channel>
    <generator>Scielo RSS</generator>
    <title></title>
    <link>http:///rss.php?pid=&amp;lang=</link>
    <description>vol.  num.  lang. </description>
    <image>
      <title><![CDATA[SciELO Logo]]></title>
      <url>http:///img/en/fbpelogp.gif</url>
      <link>http://</link>
    </image>
  </channel>
</rss>
<!--transformed by PHP 07:12:12 16-12-2020-->
```

**Comment by IxKo** [comment]
ZS nicht in Test-Verfahren, schließe.
