### ISSUE TITLE
Universidad Externado de Colombia ISSN 2346-2108 Derecho penal y criminología

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#92]
Leere XML-Datei

**Comment by mtrojan-ub** [comment]
Da scheint etwas mit dem RSS-Feed nicht zu stimmen.

https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss

Ruft man den Feed im Firefox auf, so wird er auch vom Firefox nicht richtig angezeigt.
Das liegt vermutlich daran, dass am Anfang der Datei ein "<head/>" Element enthalten ist, das da nicht hingehört.

![grafik](https://user-images.githubusercontent.com/26873381/48197213-66ba2280-e355-11e8-9137-ce4699761665.png)

Gibt's für die Zeitschrift auch einen anderen RSS Feed?

**Comment by kdr154** [comment]
Diese 3 werden auf der Homepage angeboten. Sie sehen aber alle auf den ersten Blick nicht gut aus:
https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/atom
https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss2
und dieser hier, das ist der, der benutzt wird:
https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss

**Comment by mtrojan-ub** [comment]
Ich werde mal eine freundliche Mail an den Support schreiben

**Comment by thefass** [comment]
@KStelzel : Hast du Kontakt zu den Herausgebern?

**Comment by socheres** [comment]
https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss
liefert Ergebnis mit "Try URL" "Default". Habe in ZEDER den Feed und "zotat" eingetragen.

Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_9Rb3nL" "--output-filename=VsRaUM.xml" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "URL" "https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss"
-- | --
Runtime | 8s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Default Journal' \| DIRECT @ https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss set download-delay for domain 'revistas.uexternado.edu.co' to 1000 ms   Harvesting URL 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} multiple articles found => trying to harvest children caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6318 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6317 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6319 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6320 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6322 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6321 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} caching download for URL https://uexternado3.metarevistas.org/index.php/derpen/article/view/6323 @ item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} cached 7 items from a multi-result response Harvest successful     Converting item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231} use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Presentación A.', last name = 'Caballero-García', title = '', affix = '' post-processed author first name = 'Francisco', last name = 'Pérez Fernández', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6318, 	item_type: journalArticle, 	title: Conformación de la personalidad antisocial. Enfoques y perspectivas, 	abstract_note: La personalidad antisocial o violenta, ¿tiene características o circunstancias que la asocian a un riesgo anormal de sufrir un proceso patológico o de verse afectada desfavorablemente por tal proceso? ¿Qué hace que “el antisocial” o el “violento” sea un sujeto de alto riesgo? ¿Puede la sociedad protegerle de la situación de riesgo que le rodea, le ha rodeado o le rodeará en el futuro? ¿Qué aspectos de la personalidad violenta como sujeto de alto riesgo deben conocer los profesionales que garantizan la seguridad de los ciudadanos, de los servicios sociales, la medicina, el Derecho, la psicología y la educación, entre otros, para enfocar –desde su parcela de conocimiento– de una manera más eficaz sus procesos de intervención? Intentaremos aproximarnos a todas aquellas circunstancias que caracterizan la situación de riesgo de la personalidad antisocial y violenta, para conocerla mejor, y afinar en nuestras actuaciones, de cara a conseguir su integración en sociedad., 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 13-42, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.02, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Presentación A., 			last_name: Caballero-García, 			type: author, 		}, 		{ 			first_name: Francisco, 			last_name: Pérez Fernández, 			type: author, 		}, 	], } Generated record with hash '520323F15F2DBE8E452CB0DF2D51860162BB9B8A'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Revista de', last name = 'Derecho Penal y Criminología', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6317, 	item_type: journalArticle, 	title: Nota editorial, 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 9, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.01, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Revista de, 			last_name: Derecho Penal y Criminología, 			type: author, 		}, 	], } Generated record with hash '1F4306B811B1DCF05DDD51E74E57762093B12C6A'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Juana Dolores', last name = 'Santana Hernández', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6319, 	item_type: journalArticle, 	title: La oportunidad en los delitos de violencia de género, 	abstract_note: La oportunidad es uno de los elementos necesarios para que una persona cometa un delito. La mayoría de los estudios criminológicos sobre la oportunidad se centran en delitos de robo, tráfico de estupefacientes o delincuencia callejera, y son muy escasos los que estudian este aspecto de la criminología en los delitos de violencia que se cometen contra la propia familia o pareja íntima. En este trabajo nos propusimos explorar las características de la oportunidad en los casos en los cuales se cometen delitos de violencia de género y familiar. Para ello analizamos las sentencias del Tribunal Supremo de España sobre esta materia, comprendidas entre los años 2008 y 2018. Los datos revelan que en este tipo de delitos la oportunidad reviste una serie de características que la diferencia de otros delitos al producirse en un contexto donde hay, o se espera que haya, un clima de confianza, afecto y reciprocidad. En estos delitos, los agresores no solo aprovechan la oportunidad, sino que, a menudo, la preparan de antemano. Actúan en unos escenarios ocultos a la mirada de otras personas y al control social, lo que hace que sea muy difícil la prevención por parte de la víctima y de la sociedad., 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 43-75, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.03, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Juana Dolores, 			last_name: Santana Hernández, 			type: author, 		}, 	], } Generated record with hash '2E81854A65FC9E63270A8FC3AE19ECB3968CA7E2'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Miguel Camilo', last name = 'Espinosa Ardila', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6320, 	item_type: journalArticle, 	title: El apaleamiento en Roma durante el 133 a.C., 	abstract_note: En Roma, durante el año 133 a.C., la actividad legislativa del tribuno de la plebe Tiberio Sempronio Graco causó fuertes tensiones que terminaron en su ejecución y la de sus seguidores, utilizando entre otros suplicios el apaleamiento hasta la muerte. Para explicar estos suplicios se estudian las fustigaciones, apaleamientos y flagelaciones a través de los diferentes comportamientos que eran castigados o penados, develando funciones laicas, vengativas y expiatorias. De esta forma, su uso en el 133 a.C. se explica por el carácter expiatorio, teniendo en cuenta que la lex Sempronia de magistratus M. Octavio abrogando constituyó un atentado contra la sacrosanctitas tribunicia de Marco Octavio. Así, el suplicio que se utilizó evidencia que Tiberio Sempronio Graco y sus partidarios fueron considerados traidores por sus opositores, muriendo con un suplicio que expiaría el mal cometido, aunque sus comportamientos no fueron tramitados penalmente., 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 77-102, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.04, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Miguel Camilo, 			last_name: Espinosa Ardila, 			type: author, 		}, 	], } Generated record with hash 'B2BB2958851B53B14AAF0AC4D6401429E09F3FA4'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Manuel Alberto', last name = 'Leyva Estupiñán', title = '', affix = '' post-processed author first name = 'Larisbel', last name = 'Lugo Arteaga', title = '', affix = '' post-processed author first name = 'Arlín', last name = 'Pérez Duharte', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6322, 	item_type: journalArticle, 	title: Las negociaciones ilícitas como delito funcionarial. Valoraciones dogmáticas y análisis comparado, 	abstract_note: La negociación constituye un proceso y una técnica para la solución de conflictos. El pasado histórico de las negociaciones puede ser ubicado en los orígenes mismos de la humanidad. Cuando un funcionario público es parte en una negociación y se beneficia, puede cometer un delito. El tipo penal de las negociaciones ilícitas constituye un delito asociado a los entornos empresariales y al Estado. A nivel mundial, constituye una manifestación de corrupción. En la doctrina contemporánea se ubica en los títulos que recogen los delitos contra la función pública. Esta es una de las obligaciones de los Estados, por lo cual afecta de manera directa su correcto e imparcial funcionamiento., 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 133-153, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.06, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Manuel Alberto, 			last_name: Leyva Estupiñán, 			type: author, 		}, 		{ 			first_name: Larisbel, 			last_name: Lugo Arteaga, 			type: author, 		}, 		{ 			first_name: Arlín, 			last_name: Pérez Duharte, 			type: author, 		}, 	], } Generated record with hash 'E89FC529FBFDFE6DDF390FF3369F66B3A1E6D90E'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Germán', last name = 'Santillán Delgado', title = '', affix = '' post-processed author first name = 'Reynaldo', last name = 'Robles Cardoso', title = '', affix = '' post-processed author first name = 'Alfredo', last name = 'García Rosas', title = '', affix = '' forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6321, 	item_type: journalArticle, 	title: Fundamentos teóricos en la enseñanza de la teoría del delito en el sistema jurídico mexicano, 	abstract_note: En la cátedra de Teoría General del Derecho Penal es muy importante que el alumno desarrolle una actitud crítica a través del análisis de lo que el delito es, ya que en términos generales debe conocer tres teorías fundamentales, a saber: la Teoría de la Ley Penal, la Teoría del Delito y la Teoría de las Penas y Medidas de Seguridad, fundamentales en la enseñanza del Derecho Penal. Por lo que el presente artículo abordará la Teoría del Delito para explicar y comprender del delito sus elementos positivos y negativos: conducta y ausencia de conducta, tipicidad y atipicidad, antijuridicidad y causas de justificación, imputabilidad y causas de inimputabilidad, y la culpabilidad y causas de inculpabilidad, desde una perspectiva en el sistema jurídico mexicano actual, aplicada a la legislación penal en el Estado de México., 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 103-131, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.05, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Germán, 			last_name: Santillán Delgado, 			type: author, 		}, 		{ 			first_name: Reynaldo, 			last_name: Robles Cardoso, 			type: author, 		}, 		{ 			first_name: Alfredo, 			last_name: García Rosas, 			type: author, 		}, 	], } Generated record with hash 'A1BCA7C75A03C8048144CC57DD889ED555DD7F5E'  use online ISSN "Default ISSN" with online PPN "Default PPN" post-processed author first name = 'Salvador', last name = 'Ruiz Ortiz', title = '', affix = '' post-processed author first name = 'Eduardo Osuna', last name = 'Carrillo De Albornoz', title = '', affix = '' post-processed author first name = 'José María', last name = 'Mainar Ene', title = '', affix = '' post-processed author first name = 'José', last name = 'Martínez Marín', title = '', affix = '' added GND number 132489465 for author Martínez Marín, José(Lobid lookup) forcing automatic language detection, reason: empty language language set to default language 'eng' Augmented metadata record: MetadataRecord { 	url: https://uexternado3.metarevistas.org/index.php/derpen/article/view/6323, 	item_type: journalArticle, 	title: El juicio de justificación del uso de la fuerza policial: Tribunal Europeo de Derechos Humanos VS. Corte Suprema de los Estados Unidos, 	short_title: El juicio de justificación del uso de la fuerza policial, 	abstract_note: El uso de la fuerza policial es siempre un tema controvertido, y su justificación también resulta compleja en las sociedades democráticas. En este estudio se aborda el análisis de la concepción justificativa que realiza el Tribunal Europeo de Derechos Humanos y su comparación con la de la Corte Suprema Norteamericana, a través del análisis de distintas sentencias emitidas por los citados órganos jurisdiccionales. El objetivo es determinar si en los últimos años existe o no un proceso de convergencia entre las decisiones adoptadas por estos tribunales, así como la detección de patrones interpretativos, tanto comunes como divergentes, con la finalidad de realizar un análisis crítico de la justificación que realizan sobre el fenómeno, 	publication_title: Default Journal, 	volume: 39, 	issue: 107, 	pages: 155-176, 	date: 2019-12-02, 	doi: 10.18601/01210483.v39n107.07, 	language: eng, 	issn: Default ISSN, 	superior_ppn: Default PPN, 	superior_type: 2, 	ssg: 0, 	creators: [ 		{ 			first_name: Salvador, 			last_name: Ruiz Ortiz, 			type: author, 		}, 		{ 			first_name: Eduardo Osuna, 			last_name: Carrillo De Albornoz, 			type: author, 		}, 		{ 			first_name: José María, 			last_name: Mainar Ene, 			type: author, 		}, 		{ 			first_name: José, 			last_name: Martínez Marín, 			type: author, 			gnd_number: 132489465, 		}, 	], } Generated record with hash '97463829A383761CCBEDDB0022DE4FB264A3381A'  Conversion complete   Generated 7 record(s) for item 1 [Default Journal...] \| https://revistas.uexternado.edu.co/index.php/derpen/gateway/plugin/WebFeedGatewayPlugin/rss {9376612525774154231}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 7 		Successful: 7 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 7

**Comment by kdr154** [comment]
Bekomme weiterhin eine leere XML-Datei. Der Harvester scheint mir die Artikel als Webseiten zu interpretieren:
Skipping: undesired item type "webpage"

**Comment by mtrojan-ub** [comment]
Dann müsste der Translator so angepasst werden, dass er die Datensätze nicht als "webpage" sondern z.B. als "journalArticle" liefert.

**Comment by jriedl** [comment]
Auf nu finden sich eingespielte Artikel und ein tryRSS-Test liefert Ergebnisse.

**Comment by kdr154** [comment]
Bei einem tryRSS wird alles verworfen, weil die Dokumente als Webseiten interpretiert werden:
Skipping: undesired item type "webpage"

**Comment by jriedl** [comment]
Seltsam: Bei mir lokal kommen Daten zurück.
![image](https://user-images.githubusercontent.com/13135579/113163915-e9065280-9240-11eb-8060-a8576fd11424.png)


Eigentlich besteht da kein Konfigurationsunterschied.

**Comment by kdr154** [comment]
Bei einem erneuten Durchlauf ist das Ergenis auf der nicht vollkommen leer. Zumindest bekomme ich die Meldung

**Comment by kdr154** [comment]
Tatsächlich. Das wars.
Die Daten sehen gut aus. Bis auf dass keine Sprache gelieferrt wird. Habe deshalb in der Zeder-Spalte sprz "!spa" eingetragen. Ein Test mit einem additional config auf nu war erfolgreich.
Wenn nichts dagegen spricht, würde ich diese ZS auch live schalten.

**Comment by jriedl** [comment]
Bitte wegen des update-Blockers auf ub28 noch nicht live schalten.

**Comment by kdr154** [comment]
Okay!

**Comment by jriedl** [comment]
Auch hier sind die entscheidenden Änderungen mittlerweile auf dem Produktivsystem.

**Comment by kdr154** [comment]
Bekomme auf nu und auf ub28 dieselben Ergebnisse. Daten sind gut. Prio1. Was damit geschieht muss die KrimDok entscheiden.

**Comment by jriedl** [comment]
Da niemand Einspruch erhoben hat, kann diese Zeitschrift wohl live genommen werden.

**Comment by kdr154** [comment]
Habe keine Probleme damit, aber die Krimdok ist da eigen, was die Behandlung der Prio1-Zeitschriften anlangt. Informiere die KrimDok, bevor ich sie live schalte.

**Comment by jriedl** [comment]
Ok, danke.

**Comment by IxKo** [comment]
Zs ist bereits im zota/Live-Betrieb, daher schließe ich das Issue
