### ISSUE TITLE
ISSN 2413-9467 | STJ | Stellenbosch Theological Journal | Seitenzahlen doppelt

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#920]
Bei dieser Zeitschrift werden die Seitenzahlen zweimal übertragen:

![grafik](https://user-images.githubusercontent.com/29707105/80479295-17075680-894f-11ea-88fb-22376f12456d.png)

https://ojs.reformedjournals.co.za/stj/article/view/1743
https://ojs.reformedjournals.co.za/stj/issue/view/63

**Comment by socheres** [comment]
die Seiteninformationen in der Vorlage sind fehlerhaft: 
<meta name="generator" content="Open Journal Systems 3.1.2.4">
<meta name="gs_meta_revision" content="1.1"/>
<meta name="citation_journal_title" content="STJ | Stellenbosch Theological Journal"/>
<meta name="citation_journal_abbrev" content="1"/>
<meta name="citation_issn" content="2413-9467"/> 
<meta name="citation_author" content="Martien E Brinkman"/>
<meta name="citation_author_institution" content="Stellenbosch University"/>
<meta name="citation_title" content="The cinematic hidden Christ – His invisible divinity and his visible humanity"/>
<meta name="citation_date" content="2017/12/31"/>
<meta name="citation_volume" content="3"/>
<meta name="citation_issue" content="2"/>
<meta name="citation_firstpage" content="299–317"/>
<meta name="citation_lastpage" content="299–317"/>

**Comment by socheres** [comment]
Habe den Translator "Open Journal Systems.js" aktualisiert.  Testen Sie bitte auch bei anderen OJS.

**Comment by socheres** [comment]
16:27:50 Returned item:
           {
             "itemType": "journalArticle"
             "creators": [
               {
                 "firstName": "Martien E."
                 "lastName": "Brinkman"
                 "creatorType": "author"
               }
             ]
             "notes": []
             "tags": [
               {
                 "tag": "Christology"
               }
               {
                 "tag": "hidden Christ"
               }
               {
                 "tag": "immanence"
               }
               {
                 "tag": "revelation"
               }
               {
                 "tag": "symbol"
               }
               {
                 "tag": "transcendence"
               }
             ]
             "seeAlso": []
             "attachments": [
               {
                 "title": "Full Text PDF"
                 "mimeType": "application/pdf"
               }
               {
                 "title": "Snapshot"
               }
             ]
             "title": "The cinematic hidden Christ – His invisible divinity and his visible humanity"
             "publicationTitle": "STJ | Stellenbosch Theological Journal"
             "rights": "Copyright (c) 2017 Pieter de Waal Neethling Trust, Stellenbosch"
             "volume": "3"
             "issue": "2"
         -   "number": "2"
             "pages": "299-317"
             "date": "2017/12/31"
             "ISSN": "2413-9467"
             "DOI": "10.17570/stj.2017.v3n2.a13"
             "abstractNote": "If we want to reflect upon the impact of the many ‘hidden Christ’-images in modern films at a theologically responsible way, we need to incorporate that reflection into our doctrine of revelation. That will imply that we have to re-open the classical Gospel-Culture discussion. Especially in the United States we can recognize a lot of original approaches to this issue in Reformed circles (Wolterstorff, Dyrness, Begbie, Seidell, etc.). The main question to be put in this article will be: How can we develop criteria to assess the depiction of the divine in these films?"
         -   "reportType": "Text.Serial.Journal"
         -   "letterType": "Text.Serial.Journal"
         -   "manuscriptType": "Text.Serial.Journal"
         -   "mapType": "Text.Serial.Journal"
         -   "thesisType": "Text.Serial.Journal"
         -   "websiteType": "Text.Serial.Journal"
         -   "presentationType": "Text.Serial.Journal"
         -   "postType": "Text.Serial.Journal"
         -   "audioFileType": "Text.Serial.Journal"
             "language": "en"
             "url": "https://ojs.reformedjournals.co.za/stj/article/view/1743"
             "libraryCatalog": "ojs.reformedjournals.co.za"
         -   "accessDate": "CURRENT_TIMESTAMP"
           }
16:27:50 Translation successful

**Comment by kdr154** [comment]
Es sieht gut aus. Bei anderen OJS-Zeitschriften auch. Es geht hier allerdings nur im Einzeldownloadmodus. Im Multi werden hier keine Seitenzahlen übertragen. In Zeder steht aber auch z-button1

**Comment by kdr154** [comment]
Es funktioniert jetzt auch Multi. Das Problem mit den Seitenzahlen besteht allerdings weiterhin, Sowohl im Single als auch im Multi:
![grafik](https://user-images.githubusercontent.com/29707105/87040513-19a8e680-c1f1-11ea-8b8b-202432bf8612.png)

Wenn man daran nichts ändern kann, kann man schließen

**Comment by socheres** [comment]
welchen Translator haben Sie benutzt?  "Open Journal System"?

**Comment by kdr154** [comment]
Im Single OJS, im Multi den Multi-Wrapper. Im Multi wird kein anderer angeboten, im Single gibt es noch Embedded Metadata und den DOI Translator.
Beim OJS fehlt das Abstract und es wird im Fall von https://ojs.reformedjournals.co.za/stj/article/view/1743 nur ein Keyword übertragen. Bei Embedded Metadata und DOI fehlen die Keywords ganz, aber das Abstract ist dabei.

Gerade eben nach aktualisieren aller Einstellungen noch einmal getestet.

**Comment by socheres** [comment]
hier müsste man einen neuen Translator schreiben.

**Comment by socheres** [comment]
bitte mit `ubtue_Open Journal Systems Standard.js` testen.

**Comment by kdr154** [comment]
Seitenzahlen nun korrekt.
