### ISSUE TITLE
ISSN 1745-5308 | The Expository times | Rezensionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#922]
Dasselbe in #862 
Rezensionen werden nicht getagt, bekommen stattdessen ein Schlagwort:
IxTheo#2020-04-28#F719FA8ECAC361611D72FF88F27C6ADC0488CBF5
https://journals.sagepub.com/toc/exta/131/7
Ini nachbessern?
https://github.com/ubtue/zotero-enhancement-maps/blob/3176cee3986a7b3ee6bd5611d35291fd987c4cd7/zotero_harvester.conf#L3444

**Comment by socheres** [comment]
gefixt. #862
