### ISSUE TITLE
ISSN 1748-0922 | Religious studies review | Herausnehmen da Auswertung selektiv

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#923]
Bitte diese Zeitschrift aus dem vollautomatischen Verfahren herausnehmen. Sie soll nur selektiv ausgewertet werden. Prodf in Zeder wird geändert

**Comment by socheres** [comment]
bitte in Zeder ändern.

**Comment by kdr154** [comment]
Wurde bereits geändert.
