### ISSUE TITLE
ISSN 1862-5886 | Zeitschrift für junge Religionswissenschaft | OA Problematik

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#924]
OA Problematik wie z. B. schon in  #895 #657 und #712 beschreiben.
Separates marc21 856 für LF führt zu einem zusätzlichem, aber sinnfreiem Pica 4950 Feld
IxTheo#2020-05-03#62F2296CDD09A955500C85E2FC70537724B9215B

**Comment by mtrojan-ub** [comment]
Ist das ein BSZ-seitiges Problem beim Import?

**Comment by IxKo** [comment]
Inzwischen gelöst.
