### ISSUE TITLE
ISSN 1556-9330 | Youth violence and juvenile justice | Berichtsjahr vs. Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#927]
Abweichendes Berichts- und Erscheinungsjahr bei allen Aufsätzen der Ausgabe 18.2020,2
Die Zuordnung zum Berichtsjahr 2020 ist korrekt, jedoch sind alle Aufsätze bereits im Jahr 2019 publiziert worden: "First Published ...."
Vgl.: https://journals.sagepub.com/toc/yvja/18/2
Daher stellt sich die Frage, ob Marc21Tag 264 und Pica 1100 nicht den Wert 2019 besitzen sollten.
Etwa hier KrimDok#2020-04-29#CCB4D16BDB9EECE92C11C0D964EA2AABAF5BD408

**Comment by socheres** [comment]
das Problem tritt bei den sog. "First Published"-Artikeln auf, wenn das Berichts- und Erscheinungsjahr voneinander abweichen. Hier sollte der Translator angepasst werden, damit das Jahr immer als Berichtsjahr - hier 2020 - ausgegeben wird. Siehe auch #870 #900 #927 #928 #929 #930 #932 #936

**Comment by socheres** [comment]
@mtrojan-ub In SAGE Journals.js wird eigentlich diese Problematik im Code berücksichtigt. Vielleicht wird der RIS-Translator nicht aufgerufen? 
```	
ZU.doPost(risURL, post, function (text) {
		//The publication date is saved in DA and the date first
		//appeared online is in Y1. Thus, we want to prefer DA over T1
		//and will therefore simply delete the later in cases both
		//dates are present.
		//Z.debug(text);
		if (text.indexOf("DA  - ") > -1) {
			text = text.replace(/Y1  - .*\r?\n/, '');
		}
```

**Comment by mtrojan-ub** [comment]
In der Kombination SAGE Journals + RIS haben wir noch einen anderen Issue, vielleicht ist die Lösung ähnlich: #889

**Comment by IxKo** [comment]
#1078
