### ISSUE TITLE
ISSN 1556-1836 | Terrorism and political violence | Berichtjahr vs. Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#928]
Bis auf die Rezensionen haben alle Artikel ein unterschiedliches Berichts- und Erscheinungsjahr.
Die Zuordnung zum Berichtsjahr 2020 ist korrekt, das Erscheiungsjahr Marc21 Tag 264, Pica 1100 müsste aber je nach Artikel 2017 oder 2018 sein.
Vgl.: https://www.tandfonline.com/toc/ftpv20/32/3?nav=tocList
und etwa KrimDok#2020-04-29#249DE05D0173B5FF4B8F814E1F31C239AE30FDCA

**Comment by IxKo** [comment]
#1078
Trotz der Abweichung von mehr als einem Jahr, soll die Regelung, dass das Berichtsjahr zugleich auch als Erscheinungsjahr genommen wird, angewandt werden. (Telefonat mit socheres)
