### ISSUE TITLE
ISSN 1468-2265 | Heythrop journal | Berichtsjahr vs. Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#929]
Einige Artikel haben ein vom Berichtsjahr unterschiedliches Erscheinungsjahr.
Vgl. den Eintrag First published: https://onlinelibrary.wiley.com/toc/14682265/2020/61/3
Daher stellt sich die Frage, ob Marc21 264, Pica 1100 nicht einen anderen Wert haben sollten, als das Berichtsjahr. Etwa hier 2019:
IxTheo#2020-04-29#958D8A39602209BB2E4F945D3C3AA703895FF828
hier 2018:
IxTheo#2020-04-29#38888A029036B1CA7FDE79AD55065C8A1C7ECC24

**Comment by IxKo** [comment]
#1078
