### ISSUE TITLE
Sage ISSN 1556-3855 International Criminal Justice Review

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#93]
Vgl.  #87

**Comment by shadeMe** [comment]
Die Keywords sind durch ubtue/zotero-translators#28 gefixt.

**Comment by shadeMe** [comment]
Bzgl. Online-First Artikel: wie beim Meeting besprochen, harvesten wir jetzt Online-First Artikel, die einen DOI haben. Wenn es keinen gäbe, lassen wir sie ausfallen.

**Comment by kdr154** [comment]
Seht gut!
Gilt das auch für die anderen Verlage/Plattformen? Sie werden nämlich unterschiedlich gelabelt.
Bei Wiley heißen die "Early View", vgl. #107 
Bei Springer "First Online", vgl. #104 
Bei Taylor & Francis "Latest Articles", vgl. #95 
und bei Cambridge University Press "First View", vgl.:  https://www.cambridge.org/core/journals/journal-of-law-and-religion/firstview

**Comment by shadeMe** [comment]
Ja, es gilt auch für die anderen Verlage. Ich setze sie auch auf "ready for testing".

**Comment by shadeMe** [comment]
Die Online-First Problematik ist jetzt gelöst. Bitte nochmal prüfen.

**Comment by kdr154** [comment]
Gelöst
