### ISSUE TITLE
ISSN 1541-0323 | Women & criminal justice | Abweichendes Berichts- und Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#930]
In der Ausgabe 30.2020,2 haben alle Artikel ein von Berichtsjahr 2020 unterschiedliches Erscheinungsjahr 2019:
https://www.tandfonline.com/toc/wwcj20/30/2?nav=tocList
Marc21 264 müsste in diesen Fällen immer den Wert 2019 beinhalten.
Z. B. hier: KrimDok#2020-04-29#AEBF1B6829E7A1A2A3F0DA6809EBF1EB4400640C

**Comment by IxKo** [comment]
#1078
