### ISSUE TITLE
ISSN 1552-5406 | Journal of contemporary criminal justice | Abweichendes Berichts- und Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#931]
Auch hier kommt es immer wieder zu Abweichungen zwischen Berichts- und Erscheinungsjahr:
https://journals.sagepub.com/toc/ccja/36/2
Fraglich, ob Pica 1100 Marc 264 in diesen Fällen angepasst werden sollte.
Im Gegensatz zu ähnlich gelagerten Fällen bei Taylor & Francis, wo es heißt "Published online ...", heißt es hier bei Sage "First published ....", ebenso bei Wiley.
Taylor & Francis: https://www.tandfonline.com/doi/full/10.1080/09546553.2017.1377075
Sage: https://journals.sagepub.com/doi/full/10.1177/1043986219894429
Ebenso bei Wiley:
https://onlinelibrary.wiley.com/doi/10.1111/heyj.13189

**Comment by jriedl** [comment]
Da es sich hier um eine SAGE-Zeitschrift handelt, wurde das ja wahrscheinlich allgemein im Rahmen der Anpassungen am SAGE-Translator behoben.

**Comment by kdr154** [comment]
behoben
