### ISSUE TITLE
ISSN 1477-2744 | Psychology, crime & law | Abweichendes Berichts- und Erscheinungsjahr

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#932]
Alle Artikel der Ausgabe 26.2020,4 haben ein vom Berichtsjahr abweichendes Erscheinungsjahr 2019:
https://www.tandfonline.com/toc/gpcl20/26/4?nav=tocList
Hier wieder in der bei T&F üblichen Form "Published online ..."
Marc 264 und Pica 1100 müssten hier den Wert 2019 haben und nicht 2020
z. B. hier: KrimDok#2020-04-29#659587AF853FF391861C19914D1445B3C6988099

**Comment by IxKo** [comment]
#1078
