### ISSUE TITLE
ISSN 2163-3088 | Journal of Law and Religion | Editorial

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#936]
Das EDITORIAL nicht harvesten.

**Comment by socheres** [comment]
In config ergänzt, aber kann wegen fehlendem Link nicht getestet werden.

**Comment by kdr154** [comment]
Ist bei einem Test mit Ausgabe 35.2020,1 noch drin:

![grafik](https://user-images.githubusercontent.com/29707105/85414364-48c22580-b56c-11ea-9f65-561160ffffcb.png)

**Comment by socheres** [comment]
mit "Try RSS" getestet.


Command | /usr/local/bin/zotero_harvester "--min-log-level=DEBUG" "--force-downloads" "--output-directory=/tmp/ZtsMaps_74w4gu" "--output-filename=eGXOmv.xml" "--config-overrides=exclude_if_marc_field_245a = "(Cover and (Front\|Back) matter$)\|(Editorial)\|(EDITORIAL)"" "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf" "JOURNAL" "Journal of Law and Religion"
-- | --
Runtime | 24s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of Law and Religion' \| RSS @ https://www.cambridge.org/core/rss/product/id/8E27515A8B4162AD2B5762D81F70612A set download-delay for domain 'www.cambridge.org' to 1000 ms   Harvesting feed 1 [Journal of Law and R...] \| https://www.cambridge.org/core/rss/product/id/8E27515A8B4162AD2B5762D81F70612A {15589257956221779479} forcing downloads - feed will be harvested unconditionally Queued 16 items   set download-delay for domain 'dx.doi.org' to 1000 ms   Harvesting URL 2 [Journal of Law and R...] \| https://dx.doi.org/10.1017/jlr.2020.16?rft_dat=source%3Ddrss {6834948688256518408} Harvest successful     Converting item 2 [Journal of Law and R...] \| https://dx.doi.org/10.1017/jlr.2020.16?rft_dat=source%3Ddrss {6834948688256518408} use online ISSN "2163-3088" with online PPN "461908581" post-processed author first name = 'M. Christian', last name = 'Green', title = '', affix = '' Augmented metadata record: MetadataRecord { 	url: https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/editorial/4803FFD41473637126D4E5981A3BB933, 	item_type: journalArticle, 	title: EDITORIAL, 	publication_title: Journal of Law and Religion, 	volume: 35, 	issue: 1, 	pages: 1-4, 	date: 2020-04-01, 	doi: 10.1017/jlr.2020.16, 	language: eng, 	issn: 2163-3088, 	superior_ppn: 461908581, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: M. Christian, 			last_name: Green, 			type: author, 		}, 	], } MARC field for 'https://dx.doi.org/10.1017/jlr.2020.16?rft_dat=source%3Ddrss matched exclusion filter (245a/(Cover and (Front\|Back) matter$)\|(Editorial)\|(EDITORIAL)/) Conversion complete
