### ISSUE TITLE
ISSN 2163-3088 | Journal of Law and Religion | Überflüssige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#940]
Folgende Artikel ebenfalls nicht harvesten:
IxTheo#2020-02-24#F0E1EBD40CE47816E5EEBD226DCB0A76A987E98B
IxTheo#2020-02-24#A6C947D4E941B5DDD7CE5BCBB9936604B5771694
Schlüsselbegriffe könnten sein: Back Matter und Front Matter

**Comment by socheres** [comment]
Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_16ojZC" "--output-filename=UssAqo.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://doi.org/10.1017/jlr.2020.7" "Journal of Law and  Religion"
-- | --
Runtime | 7s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of Law and Religion' \| DIRECT @ https://doi.org/10.1017/jlr.2020.7 set download-delay for domain 'doi.org' to 1000 ms   Harvesting URL 1 [Journal of Law and R...] \| https://doi.org/10.1017/jlr.2020.7 {306813604902916841} Harvest successful     Converting item 1 [Journal of Law and R...] \| https://doi.org/10.1017/jlr.2020.7 {306813604902916841} converted roman numeral page range 'f1-f5' to decimal page range 'F1-F5' use online ISSN "2163-3088" with online PPN "461908581" Augmented metadata record: MetadataRecord { 	url: https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/jlr-volume-34-issue-3-cover-and-front-matter/1F0FD108D69245596F4C30C40505E50A, 	item_type: journalArticle, 	title: JLR volume 34 issue 3 Cover and Front matter, 	publication_title: Journal of Law and Religion, 	volume: 34, 	issue: 3, 	pages: F1-F5, 	date: 2019-12-01, 	doi: 10.1017/jlr.2020.7, 	language: eng, 	issn: 2163-3088, 	superior_ppn: 461908581, 	superior_type: 2, 	ssg: 1, } MARC field for 'https://doi.org/10.1017/jlr.2020.7 matched exclusion filter (245a/Cover and (Front\|Back) matter$/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
