### ISSUE TITLE
ISSN 2159-2063 | Journal for the Study of Paul and His Letters | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#942]
Keyword werden nicht erfasst. Bsp.:
https://www.jstor.org/stable/10.5325/jstudpaullett.9.1-2.0030?refreqid=excelsior%3A0f7fc93496b5c49241f8c6c019207ac4#metadata_info_tab_contents

**Comment by socheres** [comment]
Translator "JSTOR.js" greift auf RIS.js zurück und dort sind leider keine Keywords vorhanden. Der Um einen komplett neuen Translator zu schreiben, wäre der Aufwand viel zu hoch.

10:35:12 Provider: JSTOR www.jstor.org
         Database: JSTOR
         Content: text/plain; charset="UTF-8"
         
         
         TY  - JOUR
         TI  - Narration, Genre, and Pseudonymity: Reconsidering the Individuality and the Literary Relationship of the Pastoral Epistles
         AU  - Herzer, Jens
         AB  - [In the last two decades, the classical paradigm of the literary unity of the Pastoral Epistles as a three-part “Corpus Pastorale” has been challenged and defended in various ways. The discussion has accompanied a new discourse on pseudonymity and its relevance for New Testament writings. This article traces the development of the hypothesis of the Pastoral Epistles’ pseudonymity and illuminates the problems this hypothesis entails. Focusing on narrative elements and genre (such as mandata or ancient letter novel), individual traits of each letter will be discussed exemplarily in order to reconsider their relationship. Highlighting the letters’ individual profiles leads to a more refined interpretation beyond the old controversy between authenticity and pseudonymity. As a result (which cannot be a substantial part of this article), Titus and 2 Timothy can be interpreted as authentic letters of Paul, written in his last years, whereas 1 Timothy is best situated in the anti-heretic struggles of the second century AD.]
         C1  - Full publication date: 2019
         DB  - JSTOR
         DO  - 10.5325/jstudpaullett.9.1-2.0030
         EP  - 51
         IS  - 1-2
         PB  - Penn State University Press
         PY  - 2019
         SN  - 21592063, 25767941
         SP  - 30
         T2  - Journal for the Study of Paul and His Letters
         UR  - www.jstor.org/stable/10.5325/jstudpaullett.9.1-2.0030
         VL  - 9
         Y2  - 2020/06/23/
         ER  -

**Comment by kdr154** [comment]
Dann mache ich einen Bemerkung in Zeder und schließe
