### ISSUE TITLE
ISSN 1469-7637 | The journal of ecclesiastical history | Überflüssige Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#944]
Artikel mit Front matter und Back matter im Titel sollten weggelassen werden. Ebenso die Books Received:
IxTheo#2020-05-07#C75430F3B9520E87CAA54B1DDC14E1CD84C19435
IxTheo#2020-05-07#C3C511DE3839023920B99CF8423DDB26316162CE
IxTheo#2020-05-07#119922779EAF0DEBDF90DD5C52BD6A47C6B31460

**Comment by socheres** [comment]
mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_7KXW0B" "--output-filename=uAJ3Ny.xml"  "--config-overrides=exclude_if_marc_field_245a = "(Cover and  (Front\|Back) matter$)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://doi.org/10.1017/S0022046920000032" "The journal of  ecclesiastical history : JEH"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The journal of ecclesiastical history : JEH' \| DIRECT @ https://doi.org/10.1017/S0022046920000032 set download-delay for domain 'doi.org' to 1000 ms   Harvesting URL 1 [The journal of eccle...] \| https://doi.org/10.1017/S0022046920000032 {9293050430126971843} Harvest successful     Converting item 1 [The journal of eccle...] \| https://doi.org/10.1017/S0022046920000032 {9293050430126971843} converted roman numeral page range 'f1-f5' to decimal page range 'F1-F5' use online ISSN "1469-7637" with online PPN "265785375" Augmented metadata record: MetadataRecord { 	url: https://www.cambridge.org/core/journals/journal-of-ecclesiastical-history/article/ech-volume-71-issue-2-cover-and-front-matter/09A063F2DEB0F618ED96E7C4AA6E6EAA, 	item_type: journalArticle, 	title: ECH volume 71 issue 2 Cover and Front matter, 	publication_title: The Journal of Ecclesiastical History, 	volume: 71, 	issue: 2, 	pages: F1-F5, 	date: 2020-04-01, 	doi: 10.1017/S0022046920000032, 	language: eng, 	issn: 1469-7637, 	superior_ppn: 265785375, 	superior_type: 2, 	ssg: 2, } MARC field for 'https://doi.org/10.1017/S0022046920000032 matched exclusion filter (245a/(Cover and (Front\|Back) matter$)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
