### ISSUE TITLE
ISSN 1741-3079 | Probation Journal | Escape character &

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#945]
Mit dem Ampersand & bricht die Übertragung ab:
https://journals.sagepub.com/doi/full/10.1177/0264550520917228
KrimDok#2020-05-07#B401BC2D4C7C3EA9B329941A11CFF154CF5E68FF
Vgl #925 und #861

**Comment by socheres** [comment]
@mtrojan-ub @ruschein ein Harvester-Problem? siehe auch #925 #861

**Comment by mtrojan-ub** [comment]
@ruschein: Wie besprochen, es wäre gut wenn Du Dir das anschaust (HtmlUtil::ReplaceEntities).

**Comment by mtrojan-ub** [comment]
ReplaceEntities wurde überarbeitet, dieser Issue und die beiden anderen können getestet werden, ich setze alle 3 auf ready for testing

**Comment by mtrojan-ub** [comment]
#1026 gehört ebenfalls dazu

**Comment by mtrojan-ub** [comment]
#1029 auch

**Comment by kdr154** [comment]
gelöst
