### ISSUE TITLE
ISSN 1475-4541 | AJS Review | Hebräisch

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#946]
Verfasser, Titel und Seitenzahlen werden wie in der Vorlage mit hebräischen Schriftzeichen übertragen. 
IxTheo#2020-05-07#325D6007BF5E195E02E50660B5545A8C5FB211D3
https://www.cambridge.org/core/journals/ajs-review/article/view/8DCB36155021FCFEAE6D5D189706D438

**Comment by socheres** [comment]
ist dieser Issue eine Rückmeldung, dass die Zeichensätze alles korrekt übertragen wurden? wenn ja, bitte schließen.

**Comment by kdr154** [comment]
Ist in ein Hebrew Article, also ein Artikel, der auf Hebräisch geschrieben wurde.
https://www.cambridge.org/core/journals/ajs-review/issue/F29B85CC6EFEABCEBA5E35F806DB6FD2?sort=canonical.position%3Aasc&pageNum=2&searchWithinIds=F29B85CC6EFEABCEBA5E35F806DB6FD2&productType=JOURNAL_ARTICLE&template=cambridge-core%2Fjournal%2Farticle-listings%2Flistings-wrapper&hideArticleJournalMetaData=true&displayNasaAds=false
@IxTheoKm kann man das so lassen oder sollte da etwas transkribiert werden?

**Comment by IxTheoKm** [comment]
Eigentlich müsste man transkribieren. Vereinzelt sind aber auch Einspielungen und zot-Daten mit Originalschriftzeichen vorhanden (Bsp.: PPN 1692969048, 1547815612).

Das wollten die Referenten im Zusammenhang mit imwa untereinander klären (siehe Mails vom 25.03.2020 zu Zeichensatz und Transkription). Eine definitive Antwort kam bisher nicht.

**Comment by socheres** [comment]
im Zotaut haben wir uns entschieden Originalsprache nicht zu transkribieren. Im Zotkat sollten sie auch nicht traskribiert werden. Aber hier geht es um Darstellungsproblematik.

**Comment by socheres** [comment]
@thefass einverstanden?

**Comment by thefass** [comment]
ja, einverstanden
