### ISSUE TITLE
Tandfonline ISSN 2157-6475 Self-legitimacy and use of force: a quantitative study of prison officers in Slovenia Latest Article

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#95]
Auch hier der Fakt von einem Mix aus einem Heft zugeordneten und nicht zugeordneten Artikel in einem Feed.
Ähnlich dem Problem der Online first Artikel bei Sage, Hier werden sie als Latest Articles gelabelt. Mit Folgen für 773 und 936. 
In diesen Fall wird als Band- und Heftzählung jeweils die "0" übermittelt.

```
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="i">In: </subfield>
<subfield code="a">International Journal of Comparative and Applied Criminal Justice</subfield>
<subfield code="x">2157-6475</subfield>
<subfield code="w">(DE-576)338207961</subfield>
<subfield code="g">0(2018), 0, S. 1-15</subfield>
</datafield>

```
```
<datafield tag="936" ind1=" " ind2=" ">
<subfield code="d">0</subfield>
<subfield code="e">0</subfield>
<subfield code="h">1-15</subfield>
<subfield code="j">2018</subfield>
</datafield>
```

Auch hier müssen wir erst bei uns klären, wie wir mit diesen Artikeln verfahren wollen.

**Comment by mtrojan-ub** [comment]
Unabhängig vom "Mix": Sollen wir allgemein wenn Zotero als Issue bzw. Volume "0" liefert, es so behandeln als ob die Felder leer wären? (also z.B. 936 d + e gar nicht ausspielen)

**Comment by kdr154** [comment]
An anderer Stelle wurde laut Frau Kellmeyer die 0 vom BSZ immer rausgeschmissen. Deshalb wäre es tatsächich am besten, wenn wir im  Fall einer "0" diese Felder gar nicht ausspielen würden.

**Comment by mtrojan-ub** [comment]
Die 0 wird jetzt nicht mehr ausgespielt - das gilt auch für #107 .
Aufgrund des "Mix"-Themas würde ich die beiden issues mal noch nicht auf "ready for testing" setzen, sondern auf "blocked".

**Comment by kdr154** [comment]
Gelöst
