### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | alte Ausgaben

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#950]
am 13.5.2020 wurde das Heft 92.2018,2 eingespielt. Das neueste Heft auf der Webseite ist aber 94.2020,1.
Vgl. https://journals.openedition.org/rsr/4401

**Comment by mtrojan-ub** [comment]
Ich vermute der RSS Feed ist veraltet bzw. hat seltsame Inhalte, siehe #875

**Comment by kdr154** [comment]
ok
