### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | Band, Heft, Seitenzahl

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#951]
Bei einigen Artikeln werden Bandnummer, Heftnummer und Seitenzahlen nicht erfasst.
etwa: IxTheo#2020-05-12#39BF316F8A9BDF3AB6C3A2DE8BC241C02ACF076F
IxTheo#2020-05-12#977FAD5B5AC5CE34E3766354BF0DC0B9353503C1
Obwohl sie in der Vorlage vorhanden sind: https://journals.openedition.org/rsr/4866
Bei den meisten anderen jedoch schon. Z.B.:
IxTheo#2020-05-12#A1A3C2522FFC7F97D4252918671ED8699F54575E
Drei davon stehen
 in der Sektion Actualités
Der 4. sind die Livres reçus, ein Artikel, der aber weggelassen werden kann.

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for testing" hinzufügen.

**Comment by socheres** [comment]
Livres reçus wird ausgeschlossen. Mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_aHHWVg" "--output-filename=MCyVBs.xml"  "--config-overrides=exclude_if_marc_field_245a =  "(^\u00C9ditorial)\|(^Table des mati\u00E8res du volume)\|(^Livres  re\u00E7us)\|(^Table des comptes rendus)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://journals.openedition.org/rsr/7172" "Revue des sciences  religieuses : revue trimestrielle _ RevSR"
-- | --
Runtime | 3s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Revue des sciences religieuses : revue trimestrielle _ RevSR' \| DIRECT @ https://journals.openedition.org/rsr/7172 set download-delay for domain 'journals.openedition.org' to 1000 ms   Harvesting URL 1 [Revue des sciences r...] \| https://journals.openedition.org/rsr/7172 {11684916249557460504} Harvest successful     Converting item 1 [Revue des sciences r...] \| https://journals.openedition.org/rsr/7172 {11684916249557460504} use online ISSN "2259-0285" with online PPN "834395193" Augmented metadata record: MetadataRecord { 	url: http://journals.openedition.org/rsr/7172, 	item_type: webpage, 	title: Livres reçus d’avril à septembre 2019, 	abstract_note: Abel, Olivier, Le vertige de l’Europe, Genève, Labor et Fides, 2019, 180 p. Aussedat-Minvielle, Annik, Ritualia Gallica. Les rituels des diocèses français de 1480 à 1800, 2 : Formulaires et formules, t. 3 : Pénitence. Enseignement de la foi. Conseils de vie chrétienne, 2 vol., Turnhout, Brepols, 2019, 2016 p. Baeriswyl, Raphaël, Le Pacte des Idoles. Trois essais girardiens, Paris, Ad Solem, 2019, 232 p. Bernat, Chrystel – Gabriel, Frédéric (dir.), Émotions de Dieu. Attributions et appropriati..., 	publication_title: Revue des sciences religieuses, 	date: 2019-12-01, 	language: fre, 	issn: 2259-0285, 	superior_ppn: 834395193, 	superior_type: 2, 	ssg: 1, } custom field '5203 a%abs%' has missing placeholder(s) 'abs' MARC field for 'https://journals.openedition.org/rsr/7172 matched exclusion filter (245a/(^Éditorial)\|(^Table des matières du volume)\|(^Livres reçus)\|(^Table des comptes rendus)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Daten sind jetzt vollständig
