### ISSUE TITLE
ISSN 2259-0285 | Revue des sciences religieuses | Rezensionen Notes de Lecture

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#953]
"Notes de Lecture" sind ebenfalls Rezensionen. Steht so oben auf der Webseite. Etwa:
https://journals.openedition.org/rsr/4877
IxTheo#2020-05-12#FD8AB8E5268BF705D2300C9C9749E98EF68E2788
Sollten ebenfalls als Rezensionen getagt werden. Conf. ergänzen?
https://github.com/ubtue/zotero-enhancement-maps/blob/50cb7244b56962c567c8eae423ae599b20d0e378/zotero_harvester.conf#L3963

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Werden als Rezension jetzt getagt.
