### ISSUE TITLE
ISSN 2511-8617 | Kirche und Israel | Überflüssiger Artikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#955]
Der Artikel "Inhalt" kann weggelassen werden.
https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1
IxTheo#2020-05-12#24ED7EFAF7F0E1636C357ED83AB4341AB624ECC9

**Comment by socheres** [comment]
Mit "Try URL" getestet.
Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_RxfzGk" "--output-filename=mKGeQ0.xml"  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1"  "Kirche und Israel : KuI Neukirchener theologische Zeitschrift"
-- | --
Runtime | 8s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Kirche und Israel : KuI Neukirchener theologische Zeitschrift' \| DIRECT @ https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1 set download-delay for domain 'www.vr-elibrary.de' to 1000 ms   Harvesting URL 1 [Kirche und Israel : ...] \| https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1 {15345167207281660604} Harvest successful     Converting item 1 [Kirche und Israel : ...] \| https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1 {15345167207281660604} use online ISSN "2511-8617" with online PPN "880491698" Augmented metadata record: MetadataRecord { 	url: https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1, 	item_type: journalArticle, 	title: Inhalt, 	publication_title: Kirche und Israel, 	volume: 35, 	issue: 1, 	pages: 1, 	date: 2020-05-07, 	doi: 10.13109/kiis.2020.35.1.1, 	language: ger, 	issn: 2511-8617, 	superior_ppn: 880491698, 	superior_type: 2, 	ssg: 2, } MARC field for 'https://www.vr-elibrary.de/doi/10.13109/kiis.2020.35.1.1 matched exclusion filter (245a/(^Bücher$)\|(^Inhalt$)\|(^Editorial$)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
