### ISSUE TITLE
ISSN 1871-014X | Asian journal of criminology | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#956]
Keywords werden nicht erfasst. Sie stehen in der Sektion About this article.
Bsp.:
https://link.springer.com/article/10.1007/s11417-019-09298-9
KrimDok#2020-05-12#1CE4BDB9207A87274F9F4E051380AF746E5DB63D

**Comment by socheres** [comment]
Keywords vorhanden:
keywords: [ Incarcerated women, Relational agency, Prison work, Gender, Chinese prison, Temporality ],
}
Generated record with hash '1B4B35EFAA4C6D23C25F03735731A49815BE22F2'

Conversion complete
