### ISSUE TITLE
Allgemein: 1505 $erda fehlt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#962]
**URL**
Allgemein

**Ausführliche Problembeschreibung**
Bei allen Einspielungen fehlt 1505 $erda.

**Offenbare Lösungen**
```
<datafield tag="040" ind1=" " ind2=" ">
<subfield code="a">DE-627</subfield>
<subfield code="b">ger</subfield>
<subfield code="c">DE-627</subfield>
<subfield code="e">rda</subfield>
</datafield>
```

**Comment by socheres** [comment]
@IxTheoKm Sollen/Können die Zotaut-Daten als RDA-Aufnahmen eingespielt werden?

**Comment by IxTheoKm** [comment]
@socheres Die halbautomatischen Zotero-Daten und ImageWare spielen wir auch als RDA-Aufnahmen ein, obwohl sie nicht nach allen Regeln der RDA-Kunst vorliegen oder RDA-gerecht nachgearbeitet werden. 
SSOAR-Daten (und zukünftig auch CORE-Daten) haben kein Feld 1505 $erda, aber da ist die Qualität auch deutlich schlechter.

Da die Datensatzstruktur RDA-konform ist (wenn z.B. die IMD-Felder und die Beziehungskennzeichen $BVerfasserIn$4aut in den 3000er Feldern vorhanden sind) hätte ich bei Zotaut keine Bedenken, mit 1505 $erda einzuspielen

**Comment by socheres** [comment]
@mtrojan-ub bitte folgende Felder global im Outputfile schreiben
```
<datafield tag="040" ind1=" " ind2=" ">
<subfield code="a">DE-627</subfield>
<subfield code="b">ger</subfield>
<subfield code="c">DE-627</subfield>
<subfield code="e">rda</subfield>
</datafield>
```

**Comment by mtrojan-ub** [comment]
Ist geändert. Ich weise darauf hin, dass es genau so geschrieben wird wie Du es definiert hast (also z.B. die Sprache in b ist immer "ger" auch wenn in 041 z.B. "eng" stehen würde)

**Comment by socheres** [comment]
m.W. bezieht sich die Sprache "ger" nicht auf den Aufsatz.

**Comment by mtrojan-ub** [comment]
Umso besser, dann sollte es jetzt ja richtig sein.

**Comment by IxKo** [comment]
Beim Testen mit Nu wird das Feld nun mitgeliefert.
Momentan keine Test-Daten in der WinIBW, gehe aber davon aus, dass es passt.
