### ISSUE TITLE
ISSN 2077-1444 | Religions | Zeichensatzproblem

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#964]
Hier gibt es wieder ein Problem mit der Darstellung eines Zeichens.
https://www.mdpi.com/2077-1444/11/5/245
IxTheo#2020-05-15#17D320C34F139A60D59AAA34910EECAB08955939

![gugu](https://user-images.githubusercontent.com/29707105/82291057-86012980-99a8-11ea-8e11-4e12dcbd8db1.png)

![grafik](https://user-images.githubusercontent.com/29707105/82291077-96b19f80-99a8-11ea-91f7-e7f2034aa1ad.png)

Auch hier: 
https://www.mdpi.com/2077-1444/11/5/246
![grafik](https://user-images.githubusercontent.com/29707105/82291539-73d3bb00-99a9-11ea-8867-8792af72d3d8.png)

**Comment by socheres** [comment]
@ruschein @mtrojan-ub?

Hier die Vorlage:

> Abstract
This paper compares the ritual management of fortunate and unfortunate dead (hungry ghosts) by a Chinese new religious movement named Déjiāo 徳教 (lit. Teaching of Virtue), which emerged in Chaozhou (the northeast of Guangdong province) in 1939, before spreading to Southeast Asia after World War II. Based on ethnographic data collected in Chaozhou and Thailand between 1993 and 2005, the analysis reveals significant differences concerning both the ideological and performative aspects of the ritual processing of the two categories of dead. The funeral care of orphaned dead by Déjiāo conforms to the Chaozhou tradition of xiū gūgú 修孤骨, a festival of second burial allegedly devised during the Song dynasty by a local Buddhist monk; most of his sequences require the activity of mediums. Turned toward the salvation of the unfortunate dead, this festival was enriched by a universalist ambition through its adaptation to the Thai context. In doing so, it perfectly expresses the moral and religious goals of Déjiāo, one of the most active Chinese redemptive societies. View Full-Text
Keywords: Chinese funerary rites; Déjiāo 徳教; redemptive society; hungry ghosts; xiū gūgú 修孤骨 

Zotero-Client:
> This paper compares the ritual management of fortunate and unfortunate dead (hungry ghosts) by a Chinese new religious movement named D&eacute;jiāo 徳教 (lit. Teaching of Virtue), which emerged in Chaozhou (the northeast of Guangdong province) in 1939, before spreading to Southeast Asia after World War II. Based on ethnographic data collected in Chaozhou and Thailand between 1993 and 2005, the analysis reveals significant differences concerning both the ideological and performative aspects of the ritual processing of the two categories of dead. The funeral care of orphaned dead by D&eacute;jiāo conforms to the Chaozhou tradition of xiū gūg&uacute; 修孤骨, a festival of second burial allegedly devised during the Song dynasty by a local Buddhist monk; most of his sequences require the activity of mediums. Turned toward the salvation of the unfortunate dead, this festival was enriched by a universalist ambition through its adaptation to the Thai context. In doing so, it perfectly expresses the moral and religious goals of D&eacute;jiāo, one of the most active Chinese redemptive societies.

MARCXML auf Nu:

> item_type: journalArticle,
	title: Ritual Treatment of Fortunate and Unfortunate Dead by the Chinese Redemptive Society Déjiāo in Thailand,
	abstract_note: This paper compares the ritual management of fortunate and unfortunate dead (hungry ghosts) by a Chinese new religious movement named Dji鄁o 徳教 (lit. Teaching of Virtue), which emerged in Chaozhou (the northeast of Guangdong province) in 1939, before spreading to Southeast Asia after World War II. Based on ethnographic data collected in Chaozhou and Thailand between 1993 and 2005, the analysis reveals significant differences concerning both the ideological and performative aspects of the ritual processing of the two categories of dead. The funeral care of orphaned dead by Dji鄁o conforms to the Chaozhou tradition of xiū gūg� 修孤骨, a festival of second burial allegedly devised during the Song dynasty by a local Buddhist monk; most of his sequences require the activity of mediums. Turned toward the salvation of the unfortunate dead, this festival was enriched by a universalist ambition through its adaptation to the Thai context. In doing so, it perfectly expresses the moral and religious goals of Dji鄁o, one of the most active Chinese redemptive societies.,
	publication_title: Religions,
	volume: 11,
	issue: 5,
	date: 2020-05-01,
	doi: 10.3390/rel11050245,
	language: eng,
	issn: 2077-1444,
	superior_ppn: 665435797,

**Comment by ruschein** [comment]
Keine Ahnung wo das Problem hier liegt aber das HTML besteht aus UTF-8 Daten und die chinesischen Zeichen sind keine Entities.  Vermutlich haben wir ein Problem bei der Übersetzung von UTF-16 (UCS2) auf UTF-8 oder so etwas Ähnliches.

**Comment by mtrojan-ub** [comment]
Vermutlich das selbe Problem wie bei #873 (sogar die selbe Zeitschrift).

**Comment by mtrojan-ub** [comment]
Sieht ebenfalls gut aus seit dem fix für 873 => ready for testing

**Comment by kdr154** [comment]
Gelöst
