### ISSUE TITLE
ISSN 1743-4629 | Crime prevention and community safety | Keywords

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#965]
Die Artikel haben keywords in der Sektion About this article. Diese werden nicht erfasst. Z. B.:
https://link.springer.com/article/10.1057/s41300-020-00087-6#article-info
KrimDok#2020-05-16#783F37B4308B261B39FF97E412EFEB08C5C80608

**Comment by socheres** [comment]
Keywords vorhanden.

keywords: [ Colleges and universities, Property crime, Seasonality, Spatial point pattern test, Environmental criminology ],
}
Generated record with hash '07047972066704FF98E0D27BAD0F17E9306E44FC'
