### ISSUE TITLE
ISSN 1533-8568 | Religion and American culture | URL und RSS

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#967]
Die Adresse des RSS Links und die der Webseitehaben sich geändert. Bei dem Versuch die Seiten mit den Einträgen in Zeder aufzurufen bekommen ich jeweils die Meldung: Server nicht gefunden.
Die EZB hat die Adresse der Webseite bereits geändert. Auch die des RSS Links ist auf dieser Seite eine andere. Habe beides in Zeder geändert. Bin aber erstaunt dass am 19.5. überhaupt Daten eingespielt wurden, obwohl die RSS Adresse in Zeder nicht gültig gewesen sein dürfte.

**Comment by mtrojan-ub** [comment]
Das verstehe ich nicht ganz. Wenn man die History der zotero_harvester.conf im Zeitraum vom ca. 5.5. bis aktuell vergleicht stellt man fest dass sich zwar zeder_modified_time verändert hat aber die zotero_url gleich geblieben ist. Aktuell funktioniert es aber wieder. Vielleicht war die Website down und ist jetzt wieder verfügbar?

**Comment by socheres** [comment]
@kdr154 bitte nochmal testen.

**Comment by kdr154** [comment]
Hier gibt es insofern keine Probleme mehr, als die Daten geharvestet werden.
