### ISSUE TITLE
ISSN 1533-8568 | Religion and American culture | Back Matter Front Matter

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#968]
Die Artikel mit Back Matter und Front Matter im Titel bitte unterdrücken: 
https://www.cambridge.org/core/journals/religion-and-american-culture/article/rac-volume-30-issue-1-cover-and-back-matter/9BB74A4EF4C9B5D7C4EFBD890063FE76
https://www.cambridge.org/core/journals/religion-and-american-culture/article/rac-volume-30-issue-1-cover-and-front-matter/18DF38B70E070C78C7DE5018ED7C43F1
 IxTheo#2020-05-18#1ACA3CE8D08E3B0C8C617A76F7D55DBE5234411E
IxTheo#2020-05-18#2DCD7190B0AD0BCEBB40FD69B838BC03722CC151

**Comment by mtrojan-ub** [comment]
Da das per Konfiguration in der zotero_harvester.conf erreicht werden kann werde ich das Label auf "Fehlerquelle: Zotero Enhancement Maps" setzen (ich schaue auch mal die anderen Issues mit Fehlerquelle: Harvester durch und passe das Label ggf. an)

**Comment by kdr154** [comment]
Aber warum nicht auch gleich die zotero_harvester.conf anpassen?

**Comment by mtrojan-ub** [comment]
Erstmal war es wichtig großflächig die Labels zu korrigieren um einen besseren Überblick zu haben. Wenn man jetzt z.B. nur Issues mit Fehlerquelle: Zotero Enhancement Maps anzeigen lässt kann man einmal die zotero_harvester.conf öffnen und schnell viele Issues auf einmal abarbeiten. Außerdem habe ich die Anweisung nur noch Issues mit Fehlerquelle: Harvester oder Unbekannt zu bearbeiten, sowie in unklaren Fällen zu unterstützen.

**Comment by kdr154** [comment]
Danke für die Info. Habe die harvester.conf angepasst.

**Comment by kdr154** [comment]
Wird aber weiterhin ausgegeben. Dauert es bis die conf greift?

**Comment by IxKo** [comment]
Ich habe dazu eine Frage: Dürfen wir die Config-Datei selbständig ändern?

**Comment by mtrojan-ub** [comment]
Die conf wird im gleichen Zug aus github auf nu eingespielt wenn auch die neuen Daten aus Zeder abgeglichen werden (=>abends 19 Uhr)

**Comment by kdr154** [comment]
Danke

**Comment by IxKo** [comment]
@mtrojan-ub Bedeutet das, dass kdr154 und ich an der Config-Datei etwas verändern dürfen?

**Comment by mtrojan-ub** [comment]
Das sollte @socheres entscheiden

**Comment by socheres** [comment]
Auch wenn das hiesige Beispiel ohne Probleme darstellt, bitte vorerst keine Änderungen an der Config-Datei vornehmen. Ein zuviel bzw. zuwenig Klammern im Regex kann es dazu führen, dass Titel, in denen nur "Back" vorkommt, auch ausgeschlossen werden. Auch Beginning- und And-Matches muss beachtet werden. Daher bitte keine eingeständige Änderungen an Config. Sie können aber ein Regex via additional config selbst testen und im Issue als Lösung vorschlagen z.B. `exclude_if_marc_field_245a = "^((Back|Front) (M|m)atter)"`

**Comment by kdr154** [comment]
Gelöst.
