### ISSUE TITLE
Warnung in Translator für Cambridge Core

### ISSUE THREAD

**Issue by mtrojan-ub** [ubtue/DatenProbleme#97]
(3)(+0000000): Translate: resolved to https://www.cambridge.org/core/journals/journal-of-law-and-religion/article/new-genealogy-of-religious-freedom/A76E3285DBD0EEF59A0EB82D4F4068E7
(3)(+0000000): Translate: Promise not available in sandbox in _itemDone()
(3)(+0000000): Translate: Saving item
(3)(+0000001): Translate: WARNING: Zotero.done() called after translator completion with error
(3)(+0000000): ===>undefined<=== (undefined)
(3)(+0000000): Translate: Translation successful
(5)(+0000000): Translate: Running handler 0 for done
(3)(+0000000): itemToAPIJSON: Discarded field publisher: field not valid for type journalArticle

**Comment by shadeMe** [comment]
Ich glaube, diese Warnung ist eher harmlos. Außerdem scheint es, dass Zotero.done() von der Seite des Translation-Servers aufgerufen wird - Da können wir nix auf der Ebene des Translators machen.
