### ISSUE TITLE
ISSN 2428-3606 | Revue d'Etudes Augustiniennes et Patristiques | Language to Language Mapping Tabelle greift nicht

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#970]
Bei dieser Zeitschrift wird der Sprachcode in der Form de, fr ... übertragen. Eigenlich sollte dies von der Mapping-Tabelle language_to_language_code.map abgefangen werden. Tut es aber hier nicht. In den SWB wird fr, de eingespielt statt ger, fre, Wie es auch in der Mapping-Tabelle so hinterlegt ist.

**Comment by socheres** [comment]
um welche Aufsätze geht es? bitte immer Links angeben.

**Comment by socheres** [comment]
@kdr154 kann man dieses Issue schließen?

**Comment by kdr154** [comment]
Ja, der language code wird korrekt übertragen
