### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift | Rezension

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#972]
Bei folgendem Artikel handelt es sich um eine Rezension. Diese wird nicht als solche erkannt:
https://tidsskrift.dk/rvt/article/view/120416
IxTheo#2020-05-19#47727E55EF4A3CC8477D35CD2BFE3F4BEE12A8E8

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Der oben genannte Artikel wird nun getagt. Aber der darauf folgende nicht:
https://tidsskrift.dk/rvt/issue/view/8761

![grafik](https://user-images.githubusercontent.com/29707105/86140776-83d6d280-baf1-11ea-9d56-009c220f5106.png)

hier fehlt die 655:

![grafik](https://user-images.githubusercontent.com/29707105/86140862-a10ba100-baf1-11ea-85a1-ad43c54c3984.png)

**Comment by socheres** [comment]
@mtrojan-ub bitte nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
translators auf nu wurden aktualisiert => ready for testing

**Comment by kdr154** [comment]
Es handelt sich um denselben Artikel der auch in #977 noch problematisch ist. Deshalb schließe ich #977 
Das Problem existiert aber weiter: 

![grafik](https://user-images.githubusercontent.com/29707105/87056452-f3da0c80-c205-11ea-9e3c-23362fc155b9.png)

**Comment by IxKo** [comment]
https://github.com/ubtue/DatenProbleme/issues/977#issuecomment-656504832

**Comment by kdr154** [comment]
Das Rezensionsproblem wird auch in #977 behandelt. Dort vielleicht noch ausführlicher.
