### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift | OA

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#973]
Die Zeitschrift ist OA. In der Mapping-Tabelle auch so hinterlegt. Wird in 4950 aber nicht richtig umgesetzt:
![grafik](https://user-images.githubusercontent.com/29707105/82421217-01360e80-9a81-11ea-85d0-01c33cc854af.png)

**Comment by socheres** [comment]
#924

**Comment by IxKo** [comment]
Gelöst.
