### ISSUE TITLE
Language to Language Mapping Tabelle

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#974]
Die Language to Language Mapping Tabelle scheint generell nicht mehr zu greifen.
Hier auch nicht: https://brill.com/view/journals/jyt/19/1/jyt.19.issue-1.xml
Übertragen wird en, was beim Upload in eng umgesetzt werden sollte

**Comment by socheres** [comment]
da die Sprache beim Download nicht immer korrekt sind, wird die "language_to_language_mapping" nicht mehr angewandt. Daher die "ISSN_to_language" ergänzen.

**Comment by kdr154** [comment]
Wenn Sie die ISSN_to_language_code.map meinen.
Das sind doch zwei völllig verschiedene Dinge.
In der Language to Language Mapping Tabelle wird ein nach ISO 639-2/B nichtr RDA-gerechter Sprachcode in den korrekten um gewandelt. Also fr in fre und de in ger usw.
In der "ISSN_to_language" wird einer ISSN eine bestimmte Sprache zugewiesen. 
In dem vorliegenden Fall der Brill-Zeitschrift oben kam eben beides vor de und fr. Das kann ich doch mit der "ISSN_to_language"  gar nicht abdecken.

**Comment by socheres** [comment]
die Sprachangaben beim Download sind nicht immer zuverlässig. Daher bei mehrsprachigen Artikeln in "ISSN_to_language_code.map" den Wert "mult" eintragen und Sprache händisch entweder in Zotero bzw. WinIBW korrigieren bzw. nacherfassen.

**Comment by socheres** [comment]
per email geklärt.
