### ISSUE TITLE
Umwandlung Zeitschriftenartikel in Magazinartikel

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#975]
Wie schon von @IxKo bemerkt, geht bei der Umwandlung eines Zeitschriftenartikels in den Typ Magazin-Artikel der DOI verloren und 4950 wird zweimal mit demselben Wert erzeugt.
So auch hier:
https://www.euppublishing.com/toc/inr/71/1

**Comment by socheres** [comment]
Wenn man den Dokumenttyp in Zotero manuell ändert, geht der DOI verloren. Artikel werden aber als JournalArticle heruntergeladen.

**Comment by kdr154** [comment]
? Sicher werden sie als Journal Article heruntergeladen. Ist der Verlust des DOI egal?  Und was ist mit dem doppelten 4950? Das geht es schneller, mit einem Shortcut die 1131 zuergänzen.

**Comment by socheres** [comment]
Rezensionen wurde bislang nicht im Zotkat-Verfahren erfasst, daher muss sie händisch nacherfasst werden. Falls der DOI verloren geht, bitte als JournalArticle nach Pica exportieren und händisch rezensionspazifische Felder ergänzen.

**Comment by IxKo** [comment]
Es ist einfacher und schneller in der WinIBW bei jeder Rezension händisch 1131 einzutragen als  händisch den DOI und die Resolver-Adresse nachtragen zu müssen.

**Comment by socheres** [comment]
Artikel werden nicht mehr in "MagazineArticle" umgewandelt. 
ToDo:
- [ ] Bei Rezensionsartikel Keyword "Rezension" erzeugen

**Comment by socheres** [comment]
zu Rezension im Zotkat muss der Workflow grundsätzlich neu aufgesetzt werden.
