### ISSUE TITLE
ISSN 0020-157x | The Innes Review | Rezenionen

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#976]
Was beim zotaut Verfahren hilfreich ist, ist beim zotkat Verfahren nicht unbedingt erwünscht. Rezensionen bekommen ein Sachschlagwort Book Reviews.
https://www.euppublishing.com/doi/abs/10.3366/inr.2020.0248
![grafik](https://user-images.githubusercontent.com/29707105/82432358-3b5adc80-9a90-11ea-8d09-2ab2adce9842.png)

**Comment by socheres** [comment]
im Zotkat wird "Book Reviews" nicht mehr erzeugt.
