### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift | Rezension

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#977]
- [ ] 1. **URL**

https://tidsskrift.dk/rvt/article/view/120416
IxTheo#2020-05-19#47727E55EF4A3CC8477D35CD2BFE3F4BEE12A8E8
**Ausführliche Problembeschreibung**
Es handelt sich hier um eine Rezension (Sektion: Review-artikel), wird aber nicht als solche getagt.

- [x] 2.  **URL**

https://tidsskrift.dk/rvt/article/view/120479
IxTheo#2020-05-23#16B14077984EBB465ECBBC041FF51A03E81251D6
**Ausführliche Problembeschreibung**
Hier wird die Rezension erkannt, aber auch zusätzlich Marc-650/Pica-5520 |s| Book Review ausgegeben, was wir nicht wollen.

- [ ] 3.  **URL**
siehe https://github.com/ubtue/DatenProbleme/issues/977#issuecomment-656504832

## **Zusammenfassung**
Rezensionen unter der Rubrik Review-artikel fangen im Pseudo-Abstract mal mit "Review-artikel" und mal mit "Anmeldelse" an.

Teilweise kann es vorkommen, dass Rezensionen unter der Rubrik Anmeldelser im Titel nicht mit der Wendung "Anmeldelse" beginnen, dafür aber auch wieder im Pseudo-Abstract.

Daher die Lösung, die Fälle über die Regex mit dem Marc-Feld 520 statt dem Titel zu lösen.

**Comment by socheres** [comment]
gelöst #972

**Comment by IxKo** [comment]
Fall 2 wurde gelöst, bei Fall 1 warte ich auf das Label Ready for testing nach commit.

**Comment by kdr154** [comment]
Hier scheint kein RSS gefunden zu werden. Das Result File ist leer:

![grafik](https://user-images.githubusercontent.com/29707105/87039092-f1b88380-c1ee-11ea-8e9e-79e9283e3492.png)

**Comment by kdr154** [comment]
RSS gelöst. Dasselbe Problem wird in #972 behandelt. Deshalb schließe ich.

**Comment by IxKo** [comment]
Es wurden aber nicht alle Rezensionen (Review-Artikel + Anmeldelse (Rezensionen) getagt.
Habe mit Try RSS getestet.

**Comment by kdr154** [comment]
Ja, aber es ist derselbe Artikel der bereits in 972 behandelt wurde und 972 ist ja noch offen, weil nicht gelöst. Es handelt sich um die Artikel, die in der Sektion Review-artikel  stehen.

**Comment by IxKo** [comment]
Nicht nur die in der Sektion Review-Article, sondern eine Rezension aus der Sektion Anmeldelse wird auch nicht getagt, da diese nicht mit "Anmeldelse" beginnt:
![grafik](https://user-images.githubusercontent.com/57000004/87122746-cc2a8900-c285-11ea-8b56-99e71dba05ec.png)

**Comment by kdr154** [comment]
Dann ist das ein weiterer Fall, der aber urprünglich in diesem Issue nicht behandelt wurde. Im Resumé des genannten Artikel ist das Wort anmeldse zu finden. Könnte man ein neues Issue aufmachen, denn offensichtlich greift die Heuristik nicht, wenn nach anmeldse im Titel gesucht wird.

**Comment by kdr154** [comment]
Da wir hier jetzt alles diskutiert haben, schlage ich vor, wir schließen #972 und öffnen dieses hier wieder.

**Comment by kdr154** [comment]
Auch der Eingangs unter 1. URL genannte Fall ist noch nicht gelöst:



![grafik](https://user-images.githubusercontent.com/29707105/87056452-f3da0c80-c205-11ea-9e3c-23362fc155b9.png)

**Comment by socheres** [comment]
@mtrojan-ub kann man "zotero_review_regex" individuell pro Zeitschrift auch auf abstract erweitern? Ähnlich wie bei der Spracherkennung? Wir haben neulich "zotero_review_regex" für abstract deaktiviert, da manche Titel, in denen im Abstract z.B. das Wort "review.." vorkam, auch als Rezension getagt wurden. Eine zusätzliche Filteroption z.B. `zotero_review_regex_abstract = "^Anmeldelse"` wäre eine gute Lösung.
```
The list can optionally be prefixed with one of the following indicators:
#                                               "title"             - Use only the contents of the title field to predict the language.
#                                               "abstract"          - Use only the contents of the abstract note field to predict the language.
#                                               "title+abstract"    - Use the contents of both fields to predict the language.
```

**Comment by socheres** [comment]
z.I. für @kdr154 @IxKo solche Pseudo-Abstract können mit folgender Funktion unterdrückt werden:
```
suppress_json_field_XXX             - Used to ignore metadata fields returned by the Zotero translation server when their content
#                                             matches a RegEx pattern. The config key is suffixed with the name of the metadata field and
#                                             the value is a RegEx pattern.
#
#                                             The list of valid metadata field names can be accessed through the Zotero Scaffold tool (Help > List all fields for item type)
#
#                                             Example: suppress_json_field_pages = e[0-9]+
```

**Comment by mtrojan-ub** [comment]
Ich könnte mir vorstellen, dass wir es äquivalent umsetzen wie bei zotero_expected_languages.
```
The value can optionally be prefixed with one of the following indicators:
"title"                 - Use only the contents of the title field to predict the language.
"abstract"              - Use only the contents of the abstract note field to predict the language.
"title+abstract"        - Use the contents of both fields to predict the language.
If the prefix is omitted, the language detection is performed on the contents of the title field.
```

@ruschein, was meinst Du denn dazu?

**Comment by socheres** [comment]
wie ist der Stand hierzu? @ruschein @mtrojan-ub

**Comment by ruschein** [comment]
@mtrojan-ub Klingt gut! @socheres Werde ich mir heute mal anschauen da mtrojan-ub im Urlaub ist.

**Comment by ruschein** [comment]
@socheres Das mit dem optionalen Präfix ist anscheinend schon seit geraumer Zeit implementiert.

**Comment by mtrojan-ub** [comment]
@ruschein ich wüsste nicht dass das schon umgesetzt wäre.
Wie gesagt, wenn dann nur für zotero_expected_languages, aber die Frage ist ob wir es für zotero_review_regex ebenfalls so umsetzen wollen.

**Comment by mtrojan-ub** [comment]
Ergänzung: Ich habe diesen Issue in der Schulung referenziert. Im Beispiel 2 auf Folie 16 (remove_marc_field_650a) habe ich mich in der Schulung gewundert wieso folgender Eintrag nicht funktioniert:

`remove_marc_field_650a = "(?i)Book\sHistory"`

Die Vermutung war dass das (?i) als inline case modifier nicht unterstützt wird. Weitere Tests haben aber ergeben, dass die Kombination aus doppelte Anführungszeichen und Backslash beim Laden der Ini-Datei problematisch ist:

`(?i)Book\sHistory` bleibt `(?i)Book\sHistory`, damit funktioniert es
`"(?i)Book\sHistory"` wird aber zu `(?i)BooksHistory`, also der Backslash wird entfernt, daher geht quasi im Hintergrund der Regex kaputt.

Wir arbeiten an einer Lösung. Klar ist aber dass der Backslash im Ini-File eine besondere Bedeutung behalten muss, falls man z.B. in den Regex ein " matchen will sollte man das als \" escapen können. Trotzdem sollte er wohl im Fall \s nicht verloren gehen, da s ja aus Sicht der Ini-Datei keine besondere Bedeutung hat.

**Comment by IxKo** [comment]
Die Zs. wird mit zotk bearbeitet, da die Seitenzahlen manuell aus dem PDF ergänzt werden müssen.
