### ISSUE TITLE
ISSN 1745-5308 | The Expository Times | irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#978]
**URL**
https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&amp;mi=ehikzz&amp;af=R
IxTheo#2020-05-19#477BA75385D45A8F12384E1AA9251A7D31B96E6A
**Ausführliche Problembeschreibung**
Hier handelt es sich um keinen Artikel.
**Offenbare Lösungen**
Titel wie "Index of Books Reviewed" sollten herausgefiltert werden.

**Comment by socheres** [comment]
Mit "Try URL" getestet.


Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_GEFj19" "--output-filename=P7ikjU.xml"  "--config-overrides=exclude_if_marc_field_245a = "(^Index of (B\|b)ooks  (R\|r)eviewed)""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL"  "https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&mi=ehikzz&af=R"  "The Expository times"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'The Expository times' \| DIRECT @ https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&mi=ehikzz&af=R set download-delay for domain 'journals.sagepub.com' to 1000 ms   Harvesting URL 1 [The Expository times...] \| https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&mi=ehikzz&af=R {495698062348717182} Harvest successful     Converting item 1 [The Expository times...] \| https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&mi=ehikzz&af=R {495698062348717182} use online ISSN "1745-5308" with online PPN "368316432" Augmented metadata record: MetadataRecord { 	url: https://doi.org/10.1177/0014524620923188, 	item_type: journalArticle, 	title: Index of Books Reviewed, 	publication_title: The Expository Times, 	volume: 131, 	issue: 8, 	pages: 381, 	date: 2020-05-01, 	doi: 10.1177/0014524620923188, 	language: eng, 	issn: 1745-5308, 	superior_ppn: 368316432, 	superior_type: 2, 	ssg: 2, } MARC field for 'https://journals.sagepub.com/doi/abs/10.1177/0014524620923188?ai=2b4&mi=ehikzz&af=R matched exclusion filter (245a/(^Index of (B\|b)ooks (R\|r)eviewed)/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0
