### ISSUE TITLE
Allgemein: Angabe lizenzpflichtig in Pica-4950

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#979]
Seit dem 02.03.2020 ist die Angabe der Lizenzinformation in Pica-4950 Unterfeld $4 verpflichtend anzugeben.
Dies sollte wahrscheinlich auch bei maschinell eingespielten Datensätzen berücksichtigt werden.

Daher sollte darüber diskutiert werden, ob bei jeder Zeitschrift, die nicht in der Mapping-Tabelle ISSN_to_licence.map eingetragen ist, pauschal in Pica-4950 $4ZZ für lizenzpflichtig vergeben werden sollte.
Ergänzung im Feld 856 MARC XML:
`<subfield code="z">Lizenzpflichtig</subfield>`

**Comment by socheres** [comment]
mit BSZ wurde vereinbart beim Zotaut-Verfahren direkt die Kürzel statt den Anzeigtext in den Daten reinzuschreiben. 

> prima, dann kann Herr xxx einfach den Feldinhalt in unser $4 schreiben, so wie er kommt. Viele Grüße

> ja, das geht natürlich auch.  Dann nehmen wir die Kürzel statt den Anzeigetext in Marc:

Z.B. statt

```
<datafield tag="856" ind1="4" ind2="0">
                <subfield code="u">https://doi.org/10.1017/jlr.2019.26dummy2</subfield>
                                <subfield code="z">Kostenfrei</subfield>
            </datafield>
```
so
```
<datafield tag="856" ind1="4" ind2="0">
                <subfield code="u">https://doi.org/10.1017/jlr.2019.26dummy2</subfield>
                                <subfield code="z">LF</subfield>
            </datafield>
```

**Comment by IxKo** [comment]
Wenn dem so ist, muss statt "Lizenzpflichtig" "ZZ" eingetragen werden: 
`<subfield code="z">ZZ</subfield>`

**Comment by socheres** [comment]
Ja, die Lizenzinfo ist je nach Zeitschriften unterschiedlich einzutragen. In diesem Fall "ZZ". Geplant ist diese Kürzel in Zeder einzutragen. Es gibt bereits Spalten für Lizenzinformationen "liz" oder "liza". Ich werde @thefass bitten die Werte als Auswahl einrichten zu lassen. @mtrojan-ub das war noch ein ToDo und auch so von @shadeMe  gewünscht. Damit werden alle Infos zentral in Zeder gehalten.

**Comment by thefass** [comment]
@socheres Vermutlich ist eine neue Spalte sinnvoller, wäre aber auch kein Problem. Die entscheidende Frage ist: Welche Werte braucht Ihr?

**Comment by IxKo** [comment]
![grafik](https://user-images.githubusercontent.com/57000004/82808106-878b8f80-9e89-11ea-8151-02f37dfc70f6.png)
Das sind die möglichen Codes im K10plus. Die ausgegrauten werden nicht mehr vergeben.
Das Einfachste wäre nur nach konstenfrei zugänglich (Zeder-Spalte oacc=OA) und lizenzpflichtig (Zeder-Spalte oacc=N) zu differenziern und eventuell noch Nationallizenz (Zeder-Spalte liz=Nat) und teilweise kostenfrei/Moving Wall (Zeder-Spalte oacc=OAE) zu berücksichtigen.

**Comment by thefass** [comment]
Dann wären alle Werte ja schon vorhanden und müßten nur in einer Konkordanz in dei Codes umgesetzt werden. Wenn das so stimmt, bräuchte es keine neue Spalte

**Comment by socheres** [comment]
für die Code-Integration der Werte aus ZEDER ist es besser, wenn alle Werte aus einer Spalte kommen und die Werte "N", "OA", "OAE" in entsprechenden PICA-Kürzel umbenannt werden -keine zusätzliche Mapping in Code. 
N = ZZ
OA = LF
OAE = KW

Die verbleibenden PICA-Kürzel "KF" und "NL" sollen zudem als zusätzliche Werte in "oacc" integriert werden.

**Comment by socheres** [comment]
> für die Code-Integration der Werte aus ZEDER ist es besser, wenn alle Werte aus einer Spalte kommen und die Werte "N", "OA", "OAE" in entsprechenden PICA-Kürzel umbenannt werden -keine zusätzliche Mapping in Code.
> N = ZZ
> OA = LF
> OAE = KW
> 
> Die verbleibenden PICA-Kürzel "KF" und "NL" sollen zudem als zusätzliche Werte in "oacc" integriert werden.

@thefass kannst du bitte so wie oben vorgeschlagen die Werte in einer Spalte hinzufügen lassen?

**Comment by thefass** [comment]
Kürzeländerung bei Herrn R. beauftragt

**Comment by thefass** [comment]
für Zeder Instanzen ixtheo und krim umgesetzt:
N = ZZ
OA = LF
OAE = KW

**Comment by mtrojan-ub** [comment]
... ich bin nicht sicher ob ich jetzt auch kurzfristig eine Änderung im Harvester und/oder in den cronjobs machen muss weil sonst die gesamte zotero_harvester.conf kaputt geht wenn ich das nicht tue

**Comment by socheres** [comment]
ja, das Holen von Lizenzinfo aus Zeder war noch ein ToDo. @mtrojan-ub Für Cronjob-Erstellung: Du kannst direkt die Werte von ZEDER übernehmen und so im Output reinschreiben.

**Comment by mtrojan-ub** [comment]
OK, ich setze jetzt erstmal die Synchronisierung von Zeder "oacc" in die zotero_harvester.conf um. Sobald die Werte automatisch übernommen werden kümmere ich mich im zweiten Schritt darum dass der Harvester die dortigen Werte nimmt.

**Comment by mtrojan-ub** [comment]
Das Feld "license" in der zotero_harvester.conf wird jetzt automatisch aus Zeder "oacc" synchronisiert (erstmalig letzte Woche passiert), außerdem verwendet der Harvester jetzt nur noch den Wert aus der zotero_harvester.conf

=> ready for testing

**Comment by IxKo** [comment]
@mtrojan-ub Beim Testen mit Nu wird der Lizenz-Code, wie er in Zeder hinterlegt ist, mitgeliefert. 
Ich schließe sobald ich auch bei neuen Testdaten im K10plus keinen Fehler sehe. Oder soll ich bei einem neuen Problem mit dem Pica-Feld 4950 (bsp. der Herkunftscode in $x) dann besser einen neuen Issue öffnen?

Weitere Fragen:
1. Für das semi-automatische Zotero-Verfahren werden die Informationen aus Zeder nicht berücksichtigt, sondern weiterhin die [Mapping-Liste](https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map)?
2. Es gibt auch den Code KF = Kostenfrei zugänglich nach Registrierung. Soll dieser nicht vergeben werden, auch wenn es zutreffend ist?

**Comment by mtrojan-ub** [comment]
Aus meiner Sicht wäre es praktischer wenn im Fehlerfall ein neuer Issue unter Angabe von ID+ISSN geöffnet wird.

Für zotkat wird das wahrscheinlich erstmal so sein, wobei wir perspektivisch auch die Möglichkeit schaffen könnten dass die Maps für zotkat aus Zeder automatisch erstellt werden und nicht manuell gepflegt werden müssen. Das muss aber erst im Meeting mit @ruschein und @socheres thematisiert werden.

**Comment by IxKo** [comment]
Okay, vielen Dank. Dann schließe ich.
