### ISSUE TITLE
Sage ISSN 1552-6933 International Journal of Offender Therapy and Comparative Criminology

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#98]
Mix von OnlineFirst (keinem Heft zugeordnet) und Artikel die einem Heft zugeordnet sind in einem Feed Vgl. z. B. #82

**Comment by shadeMe** [comment]
Die Keywords sind durch ubtue/zotero-translators#28 gefixt.

**Comment by shadeMe** [comment]
Die Online-First Problematik ist jetzt gelöst. Bitte nochmal prüfen.

**Comment by kdr154** [comment]
Gelöst
