### ISSUE TITLE
ISSN 1813-3924 | Wiener Studien | Datensatz besteht aus mehreren Rezensionen + Autoren = Hrsg.

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#980]
**URL**
http://hw.oeaw.ac.at/8515-4inhalt
IxTheo#2020-05-19#0865C37163D7350E5044A86E7FC81A257EA91AE7
**Ausführliche Problembeschreibung**
Hier scheint das Heft nur aus Rezensionen und Kurzanzeigen zu bestehen und wird aufgrund der Angabe aus dem URL nur in einem Datensatz mit dem Titel "Rezensioenn und Kurzanzeigen" ausgegeben.
Dazu werden zwei Autoren angegeben. Schaut man ins PDF sind dies aber die Herausgeber. Autor:innen der einzelnen Rezensionen sind andere.

**Offenbare Lösungen**
Sollte dieser Datensatz/das Heft besser rausgefiltert werden, da es sich auch nicht um einen einzelnen Artikel handelt?

**Comment by kdr154** [comment]
Es gibt Ausgaben die Essays enthalten und Ausgaben, die Rezensionen enthalten. Die regulären Ausgaben können durchaus funktionieren (sehe da bei einem Test auf nu auf den ersten Blick wieder Probleme bei 041 Sprache, aber sonst sscheinen die Daten gut zu sein), die mit den Rezensionen sollten m. M. nach nicht im zotaut-Verfahren bearbeitet werden.
Übersicht über die bisher erschienene Heft: http://austriaca.at/wiener_studien_collection

**Comment by IxKo** [comment]
Im zotkat-Verfahren kann das Heft m. M. nach ebenfalls nicht bearbeitet werden. Da es nur aus einem einzigen Eintrag besteht mit einer Datei. Das müsste, manuell erfasst werden.

**Comment by kdr154** [comment]
Sehe ich auch so.

**Comment by socheres** [comment]
Nur Hefte mit dem Titel "Wiener Studien xxx - Rezensionen" http://austriaca.at/8515-4inhalt?frames=yes  sollten wenn nötig manuell katalogisiert werden. Anders geht bei diesem Heft auch nicht: http://austriaca.at/0xc1aa5576_0x003b8538.pdf Diese Hefte können im Zotaut rausgefiltert werden. Daher weiterhin zotat.

**Comment by socheres** [comment]
Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_QXUvSS" "--output-filename=kOoAu9.xml"  "--config-overrides=exclude_if_marc_field_245a = "^Rezensionen und  Kurzanzeigen""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL" "http://hw.oeaw.ac.at/8515-4inhalt" "Wiener Studien : Zeitschrift  für klassische Philologie, Patristik und lateinische Tradition"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Wiener Studien : Zeitschrift für klassische Philologie, Patristik und lateinische Tradition' \| DIRECT @ http://hw.oeaw.ac.at/8515-4inhalt set download-delay for domain 'hw.oeaw.ac.at' to 1000 ms   Harvesting URL 1 [Wiener Studien : Zei...] \| http://hw.oeaw.ac.at/8515-4inhalt {5734186997558451374} multiple articles found => trying to harvest children caching download for URL https://hw.oeaw.ac.at?arp=0x003b8538 @ item 1 [Wiener Studien : Zei...] \| http://hw.oeaw.ac.at/8515-4inhalt {5734186997558451374} cached 1 items from a multi-result response Harvest successful     Converting item 1 [Wiener Studien : Zei...] \| http://hw.oeaw.ac.at/8515-4inhalt {5734186997558451374} use online ISSN "1813-3924" with online PPN "512300593" post-processed author first name = 'Herbert', last name = 'Banner', title = '', affix = '' post-processed author first name = 'Kurt', last name = 'Smolak', title = '', affix = '' added GND number 108490270 for author Smolak, Kurt (SWB lookup) Augmented metadata record: MetadataRecord { 	url: https://hw.oeaw.ac.at?arp=0x003b8538, 	item_type: journalArticle, 	title: Rezensionen und Kurzanzeigen, 	publication_title: Wiener Studien, 	volume: 133, 	pages: 1-44, 	date: 2020-01-01, 	doi: 10.1553/wst133_rezs1, 	language: ger, 	issn: 1813-3924, 	superior_ppn: 512300593, 	superior_type: 2, 	ssg: 2, 	creators: [ 		{ 			first_name: Herbert, 			last_name: Banner, 			type: editor, 		}, 		{ 			first_name: Kurt, 			last_name: Smolak, 			type: editor, 			gnd_number: 108490270, 		}, 	], } MARC field for 'http://hw.oeaw.ac.at/8515-4inhalt matched exclusion filter (245a/^Rezensionen und Kurzanzeigen/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0

**Comment by IxKo** [comment]
Habe in Zeder b_zot Vermerk ergänzt: "Hefte "Rezensionen und Kurzanzeigen" manuell erfassen, andere Hefte sollen mit zota-Verfahren erfasst werden"
Oder sollte es lieber in b_allg vermerkt werden? @kdr154

**Comment by IxKo** [comment]
Würde das Issue schließen, wenn keiner mehr Einwände hat.

**Comment by kdr154** [comment]
b_zot ist besser. Bitte schließen.
