### ISSUE TITLE
ISSN 2077-1444 | Religions | Rezension nicht getagt

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#981]
**URL**
https://www.mdpi.com/2077-1444/11/5/252
IxTheo#2020-05-19#51F8769183E79B2F810D2D11A046DAF5024DB5BD
**Ausführliche Problembeschreibung**
Review Artikel wird nicht als Rezension getagt.

**Comment by socheres** [comment]
@mtrojan-ub nach commit "ready for Testing" hinzufügen.

**Comment by mtrojan-ub** [comment]
Translators wurden aktualisiert => ready for testing

**Comment by IxKo** [comment]
Klappt.
