### ISSUE TITLE
ISSN 2698-5446 | Im Dialog | Bandzählung

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#982]
**URL**
https://ojs2.uni-tuebingen.de/ojs/index.php/idadrs/issue/view/23

**Ausführliche Problembeschreibung**
Die Bandzählung wird als Heftzählung in Zotero übertragen. Da es sich um eine durchhgängige Nummerierung der Hefte handelt, muss die Zählung als Bandzählung katalogisiert werden.

**Offenbare Lösungen**
Statt Pica-4070 $a sollte die Zählung in $v

**Comment by socheres** [comment]
@thefass kannst du bitte die Herausgeber kontaktieren und Sie bitten, die durchhgängige Nummerierung der Hefte als Bandzähung zu erfassen. Die Zählung soll in "citation_volume" eingetragen werden statt in "citation_issue"
```
<link rel="icon" href="https://ojs2.uni-tuebingen.de/ojs/public/journals/6/favicon_de_DE.png">
<meta name="generator" content="Open Journal Systems 3.1.0.0">
<link rel="schema.DC" href="http://purl.org/dc/elements/1.1/" />
<meta name="DC.Creator.PersonalName" content="Nora Markard"/>
<meta name="DC.Date.created" scheme="ISO8601" content="2019-12-16"/>
<meta name="DC.Date.dateSubmitted" scheme="ISO8601" content="2019-12-16"/>
<meta name="DC.Date.issued" scheme="ISO8601" content="2019-12-16"/>
<meta name="DC.Date.modified" scheme="ISO8601" content="2019-12-16"/>
<meta name="DC.Description" xml:lang="de" content=""/>
<meta name="DC.Format" scheme="IMT" content="application/pdf"/>
<meta name="DC.Identifier" content="227"/>
<meta name="DC.Identifier.pageNumber" content="49-66"/>
<meta name="DC.Identifier.DOI" content="10.25787/idadrs.v0i2.227"/>
<meta name="DC.Identifier.URI" content="https://ojs2.uni-tuebingen.de/ojs/index.php/idadrs/article/view/227"/>
<meta name="DC.Language" scheme="ISO639-1" content="de"/>
<meta name="DC.Rights" content="Copyright (c) 2019 Im Dialog – Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart"/>
<meta name="DC.Rights" content=""/>
<meta name="DC.Source" content="Im Dialog – Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart"/>
<meta name="DC.Source.ISSN" content="2698-5446"/>
<meta name="DC.Source.Issue" content="2"/>
<meta name="DC.Source.URI" content="https://ojs2.uni-tuebingen.de/ojs/index.php/idadrs"/>
<meta name="DC.Subject" xml:lang="de" content="Migration"/>
<meta name="DC.Subject" xml:lang="de" content="Migrationspolitik"/>
<meta name="DC.Subject" xml:lang="de" content="Menschenrechte"/>
<meta name="DC.Subject" xml:lang="de" content="Menschenrechtstrends"/>
<meta name="DC.Subject" xml:lang="de" content="Europa"/>
<meta name="DC.Title" content="Die Bedeutung der Menschenrecht für Migrant*innen in Europa"/>
<meta name="DC.Type" content="Text.Serial.Journal"/>
<meta name="DC.Type.articleType" content="Artikel"/>
<meta name="gs_meta_revision" content="1.1"/>
<meta name="citation_journal_title" content="Im Dialog – Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart"/>
<meta name="citation_journal_abbrev" content="1"/>
<meta name="citation_issn" content="2698-5446"/> 
<meta name="citation_author" content="Nora Markard"/>
<meta name="citation_title" content="Die Bedeutung der Menschenrecht für Migrant*innen in Europa"/>
<meta name="citation_date" content="2019/12/16"/>
<meta name="citation_issue" content="2"/>
<meta name="citation_firstpage" content="49"/>
<meta name="citation_lastpage" content="66"/>
<meta name="citation_doi" content="10.25787/idadrs.v0i2.227"/>
<meta name="citation_abstract_html_url" content="https://ojs2.uni-tuebingen.de/ojs/index.php/idadrs/article/view/227"/>
<meta name="citation_keywords" xml:lang="de" content="Migration"/>
<meta name="citation_keywords" xml:lang="de" content="Migrationspolitik"/>
<meta name="citation_keywords" xml:lang="de" content="Menschenrechte"/>
<meta name="citation_keywords" xml:lang="de" content="Menschenrechtstrends"/>
<meta name="citation_keywords" xml:lang="de" content="Europa"/>
<meta name="citation_pdf_url" content="https://ojs2.uni-tuebingen.de/ojs/index.php/idadrs/article/download/227/174"/>
```

**Comment by thefass** [comment]
@socheres Ist veranlasst

**Comment by thefass** [comment]
ist geändert. Kann getestet werden. Bitte bestätigen, wenn alles klappt.

**Comment by thefass** [comment]
Die neue URL ist übringens: https://imdialog.akademie-rs.de

**Comment by IxKo** [comment]
Zählung wird nun in Bandangabe übernommen, habe den Link in Zeder ergänzt.
Seitenangaben kommen nur im Einzel-DL nach Zotero.

**Comment by thefass** [comment]
> Seitenangaben kommen nur im Einzel-DL nach Zotero.

Ist das ein generelles OJS Problem?

**Comment by socheres** [comment]
Ja, das ist leider nicht einheitlich bei OJS-Zeitschriften. Im Idealfall sind die Seitenangaben eingebettet in der Einzelansicht. Wenn es aber in der Einzelansicht gar keine Seitenangaben zu finden sind, müsste man die Seitenangaben - falls überhaupt vorhanden -  in der Trefferansicht scrapen. Fürs Multiple-Download braucht man noch zusätzliche Anpassung. Am Besten wäre es, wenn alle OJS-Betreiber folgendes Plugin installieren und die Metadaten korrekt eingeben. https://openjournalsystems.com/ojs-2-user-guide/metadata-plugins/
@kdr154 @IxKo Übrigens habe ich drei neue Translators für #600 #982 #1018 geschrieben und in Ihre Verzeichnisse kopiert. Bitte um Feedback!

**Comment by socheres** [comment]
@IxKo Prüfen Sie bitte die drei Zeitschriften auf Zotaut-Eignung (RSS etc.) und ggfs. in ZEDER auf "zotat" setzen. Die älteren Hefte müssen aber semiautomatisch bearbeitet werden.

**Comment by kdr154** [comment]
Mit dem neuen Translator sehen die Daten gut aus.

**Comment by thefass** [comment]
@socheres Das ist ja eine unserer mittlerweile 6 OJS Zss, die wir selbst machen. Bitte mit Herrn Braun Kontakt aufnehmen wegen des Plugins.

**Comment by IxKo** [comment]
- eISSN 2196-6265 | Jahrbuch für christliche Sozialwissenschaften
Die angebotenen RSS-Feeds (1.0, 2.0 und Atom) scheinen nicht zu funktionieren. Hatte versucht sie in Outlook anzulegen.

- eISSN 2698-5446 | Im Dialog
Scheint keinen RSS-Feed anzubieten.

- eISSN 1804-6444 | Journal of European Baptist Studies
Scheint auch keinen RSS-Feed anzubieten.

**Comment by socheres** [comment]
> @socheres Das ist ja eine unserer mittlerweile 6 OJS Zss, die wir selbst machen. Bitte mit Herrn Braun Kontakt aufnehmen wegen des Plugins.

Unsere haben bereits eingebettete Metadaten.

**Comment by thefass** [comment]
>     * eISSN 2196-6265 | Jahrbuch für christliche Sozialwissenschaften
>       Die angebotenen RSS-Feeds (1.0, 2.0 und Atom) scheinen nicht zu funktionieren. Hatte versucht sie in Outlook anzulegen.

Diese OJS Zss wird nicht von uns gehostet, sondern von der UB Münster. 
Die UB Münster hat auch noch andere OJS Zss, dazu schicke ich später eine Mail

**Comment by socheres** [comment]
> * eISSN 2196-6265 | Jahrbuch für christliche Sozialwissenschaften
>   Die angebotenen RSS-Feeds (1.0, 2.0 und Atom) scheinen nicht zu funktionieren. Hatte versucht sie in Outlook anzulegen.
> * eISSN 2698-5446 | Im Dialog
>   Scheint keinen RSS-Feed anzubieten.
> * eISSN 1804-6444 | Journal of European Baptist Studies
Ist vielleicht via Crawling möglich.

**Comment by IxKo** [comment]
> 
> 
> Ist vielleicht später via Crawling möglich.
Dann schließe ich das Issue.
