### ISSUE TITLE
ISSN 1545-6935 | History of religions | Irrelevanter Datensatz

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#983]
**URL**
https://www.journals.uchicago.edu/doi/abs/10.1086/710001?af=R
IxTheo#2020-05-20#29AE6B5A52A5C12DE40AEA6FB06C1608C44A0CC6

Diesen Datensatz (Titel="Front Matter") bitte unterdrücken.

siehe auch: #761

**Comment by socheres** [comment]
getestet. 
MARC field for 'https://www.journals.uchicago.edu/doi/abs/10.1086/710001?af=R matched exclusion filter (245a/(^Front (M|m)atter$)|(^Masthead$)/)
Conversion complete
