### ISSUE TITLE
ISSN 1904-8181 | Religionsvidenskabeligt tidsskrift | "KEY WORDS" als Keyword

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#984]
**URL**
https://tidsskrift.dk/rvt/article/view/120446
IxTheo#2020-05-20#8476D4572DAEE5769117C76A2C10758A76B7311C
**Ausführliche Problembeschreibung**
Bei einem Keyword steht davor "KEY WORDS":
```
<datafield tag="650" ind1=" " ind2="4">
<subfield code="a">KEY WORDS: Röster</subfield>
</datafield>
```
Es könnte sein, dass es ein Problem seitens der Website ist und es nie wieder vor kommt.

**Offenbare Lösungen**
Ein Filter könnte angelegt werden, der das vermeintliche Keyword entfernt.

**Comment by socheres** [comment]
In config sollen nur immer wiederkehrende Strings rausgefiltert werden.

**Comment by socheres** [comment]
@IxKo bitte Issue schließen.
