### ISSUE TITLE
ISSN 2042-0587 | Studies in religion | zwei Abstracts in einem Feld

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#985]
**URL**
https://journals.sagepub.com/doi/abs/10.1177/0008429819884468?ai=1gvoi&amp;mi=3ricys&amp;af=R
IxTheo#2020-05-22#060507B39796A16568341CE08B3DC2ABFB521D2C
**Ausführliche Problembeschreibung**
Was ist das Problem?
Das englische und französische Abstract sind nicht getrennt in zwei Felder, sondern werden in einem ausgegeben.
**Offenbare Lösungen**
Abstracts gesondert je in ein Feld ausgeben.

**Comment by socheres** [comment]
@IxKo @kdr154 @IxTheoKm @mtrojan-ub Die verschiedenen Seitenstruktur der Sage Journals erlaubt es nicht global zwei Abstracts in zwei Felder zu trennen. Außerdem hat das Trennen der Abstracts in zwei Felder für die Suche in IxTheo überhaupt keine Relevanz. Daher keine Issues mehr hierzu anlegen.

**Comment by IxKo** [comment]
Okay, also keine Issues zu dem Thema mehr für Sage-Zss öffnen.
