### ISSUE TITLE
ISSN 2042-0587 | Studies in religion | 1 nicht erfasster Artikel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#987]
**URL**
https://doi.org/10.1177/0008429820919394

**Ausführliche Problembeschreibung**
Dieser Artikel wurde nicht erfasst. Liegt es daran, weil es eine "Introduction" ist? Wurde es also absichtlich gefiltert?

**Comment by socheres** [comment]
@mtrojan-ub https://github.com/ubtue/zotero-enhancement-maps/blob/9c44a579625e68828c707ece74214ca27742b803/zotero_harvester.conf#L2150 ist kein Filter gesetzt, wird aber trotzdem gefiltert?

**Comment by mtrojan-ub** [comment]
Der Datensatz wird heruntergeladen (sieht man beim Testen mittels "Try RSS"), laut Validierung (validate_harvested_records) gibt es aber Mängel und daher wird die Datei nicht hochgeladen. Können wir bei unserem Meeting morgen besprechen.

**Comment by IxKo** [comment]
Ist die Ursache geklärt und kann das Issue geschlossen werden?

**Comment by mtrojan-ub** [comment]
Vermutlich wurde der passende Fehler schon vor einiger Zeit behoben. Der Datensatz wurde am 7.7. hochgeladen.

Default_Test/zotero_ixtheo_200707_001.xml
EDD7BEEB5D20FD244E9B0DA9E794FA3A391E6A61

**Comment by IxKo** [comment]
Ok, dann schließe ich.
