### ISSUE TITLE
ISSN 1572-8684 | International journal for philosophy of religion | nur 1 Artikel von 8 erfasst

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#988]
**URL**
http://link.springer.com/10.1007/s11153-020-09761-z
IxTheo#2020-05-22#D8881AE02131B57E973EB8028378F0DFE36C21B1
**Ausführliche Problembeschreibung**
Von dem Heft wurde nur 1 Artikel erfasst.
In Volume 49 Issue 1, March 2020 sind insgesamt 9 Artikel gelistet, darunter eine Rezension und ein irrelevanter Datensatz (Editorial Preface).
**Fragen**
Werden diese Artikel noch eingespielt? Wie kommt es zustande, dass in dieser Einspielung nur der eine Artikel erfasst wurde?

**Comment by socheres** [comment]
@mtrojan-ub Harvesterproblem?

**Comment by mtrojan-ub** [comment]
Die restlichen Artikel dieses Heftes wurden bereits 1 Tag zuvor hochgeladen (zotero_ixtheo_200521_001.xml)

**Comment by mtrojan-ub** [comment]
Wie beim verlinkten Issue 990 wurde Afterthoughts am Tag vorher als online first übersprungen. Da am nächsten Tag volume+issue vorhanden waren wurde er dann geharvested.

**Comment by IxKo** [comment]
Okay, danke für die Erklärung.
