### ISSUE TITLE
Wiley ISSN 2161-1874 Brief Counseling for Alcohol Misuse Among Trauma Patients Tag 856

### ISSUE THREAD

**Issue by kdr154** [ubtue/DatenProbleme#99]
Hier, wie bei allen anderen Aufsätzen in diesem Feed, gibt es zwei Einträge für 856 ohne Mehrwert
```
<datafield tag="856" ind1=" " ind2=" ">
<subfield code="u">https://doi.org/10.1002/jaoc.12049</subfield>
</datafield>
<datafield tag="856" ind1=" " ind2=" ">
<subfield code="u">https://onlinelibrary.wiley.com/doi/abs/10.1002/jaoc.12049</subfield>
</datafield>
```

**Comment by mtrojan-ub** [comment]
Bisher wird nur verhindert, dass mehrere gleiche URLs erzeugt werden.
Sollen wir alle anderen URLs weglassen, sobald es eine DOI-URL gibt?

**Comment by mtrojan-ub** [comment]
OK! Können wir die Issues dann schließen? (siehe auch #102)

**Comment by kdr154** [comment]
Gelöst
