### ISSUE TITLE
ISSN 1467-9809 | Journal of religious history | irrelevanter Datensatz "Issue Information"

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#992]
**URL**
https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R
IxTheo#2020-05-25#C9DBC21115DCBF4C1C1113373CF3317BCAACC523
**Ausführliche Problembeschreibung**
Der Titel "Issue Information" soll nicht erfasst werden.

**Offenbare Lösungen**
Den Datensatz rausfiltern.

**Comment by socheres** [comment]
Mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_160yRx" "--output-filename=vWmEA1.xml"  "--config-overrides=exclude_if_marc_field_245a = "^Issue Information$""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL"  "https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R"  "Journal of religious history"
-- | --
Runtime | 5s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of religious history' \| DIRECT @ https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Journal of religious...] \| https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R {1430483969993740321} Harvest successful     Converting item 1 [Journal of religious...] \| https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R {1430483969993740321} use online ISSN "1467-9809" with online PPN "300593295" Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575, 	item_type: journalArticle, 	title: Issue Information, 	publication_title: Journal of Religious History, 	volume: 44, 	issue: 1, 	pages: 1-2, 	date: 2020-01-01, 	doi: 10.1111/1467-9809.12575, 	language: eng, 	issn: 1467-9809, 	superior_ppn: 300593295, 	superior_type: 2, 	ssg: 1, } MARC field for 'https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12575?af=R matched exclusion filter (245a/^Issue Information$/) Conversion complete      Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 0 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 1 		Skipped (already delivered): 0

**Comment by IxKo** [comment]
@kdr154 Die Zs hat keine offenen Issues mehr.
