### ISSUE TITLE
ISSN 1467-9809 | Journal of religious history | Rezensionen

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#993]
**URL**
https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12633?af=R
IxTheo#2020-05-25#C50184D3F6B7A19C37AD80B1E02506151CCEF984
**Ausführliche Problembeschreibung**
Rezensionen werden nicht getagt, auch nicht als Keyword.

**Offenbare Lösungen**
In 655 als Rezension kennzeichnen.

**Comment by socheres** [comment]
Mit "Try URL" getestet.

Command | /usr/local/bin/zotero_harvester  "--min-log-level=DEBUG" "--force-downloads"  "--output-directory=/tmp/ZtsMaps_3hFRgy" "--output-filename=DYsAyR.xml"  "--config-overrides=zotero_review_regex       = "pp\.""  "/usr/local/var/lib/tuelib/zotero-enhancement-maps/zotero_harvester.conf"  "URL"  "https://onlinelibrary.wiley.com/doi/full/10.1111/1467-9809.12633?af=R"  "Journal of religious history"
-- | --
Runtime | 6s
Download | Result file
CLI output: | Zotero Logger initialized!    Queued journal 'Journal of religious history' \| DIRECT @ https://onlinelibrary.wiley.com/doi/full/10.1111/1467-9809.12633?af=R set download-delay for domain 'onlinelibrary.wiley.com' to 1000 ms   Harvesting URL 1 [Journal of religious...] \| https://onlinelibrary.wiley.com/doi/full/10.1111/1467-9809.12633?af=R {16377649434834779464} Harvest successful     Converting item 1 [Journal of religious...] \| https://onlinelibrary.wiley.com/doi/full/10.1111/1467-9809.12633?af=R {16377649434834779464} use online ISSN "1467-9809" with online PPN "300593295" post-processed author first name = 'Lisa K.', last name = 'Bailey', title = '', affix = '' title matched review pattern Augmented metadata record: MetadataRecord { 	url: https://onlinelibrary.wiley.com/doi/abs/10.1111/1467-9809.12633, 	item_type: review, 	title: Maya Maskarinec: City of Saints: Rebuilding Rome in the Early Middle Ages. Philadelphia: University of Pennsylvania Press, 2018; pp. x + 290., 	short_title: Maya Maskarinec, 	publication_title: Journal of Religious History, 	volume: 44, 	issue: 1, 	pages: 125-126, 	date: 2020-01-01, 	doi: 10.1111/1467-9809.12633, 	language: eng, 	issn: 1467-9809, 	superior_ppn: 300593295, 	superior_type: 2, 	ssg: 1, 	creators: [ 		{ 			first_name: Lisa K., 			last_name: Bailey, 			type: author, 		}, 	], } Generated record with hash '5A01294624F5BD3067A3E3BB31A16CC3CD2C6C71'  Conversion complete   Generated 1 record(s) for item 1 [Journal of religious...] \| https://onlinelibrary.wiley.com/doi/full/10.1111/1467-9809.12633?af=R {16377649434834779464}    Zotero Harvester Metrics: 	Journals: 1 		Direct: 1 		RSS: 0 			Skipped: 0 		Crawl: 0 	Crawls: 0 		Successful: 0 		Unsuccessful : 0 		Cache Hits : 0 	Harvests: 1 		Successful: 1 		Unsuccessful : 0 		Cache Hits : 0 		Skipped (already harvested): 0 		Skipped (already delivered): 0 	Records: 1 		Successful: 1 		Unsuccessful: 0 		Skipped (online-first): 0 		Skipped (early-view): 0 		Skipped (exclusion filter): 0 		Skipped (already delivered): 0  	Successfully generated records per group: 		IxTheo: 1
