### ISSUE TITLE
ISSN 1477-8556 | Journal of Semitic studies | Textschnipsel als Bild im Abstract/Titel

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#996]
1. **URL**
https://academic.oup.com/jss/article/65/1/61/5738634?rss=1
IxTheo#2020-05-25#D03A4FF4D90B3928CE84499CD664492C942C3101
**Ausführliche Problembeschreibung**
Im Abstract ist für hebräischen Text ein Bild mit dem Text eingefügt. Dies kann natürlich nicht in Text-Code umgewandelt werden.

2. **URL**
https://academic.oup.com/jss/article/65/1/11/5738637?rss=1
IxTheo#2020-05-25#E5CCC7BB6194C68EA883681249FC796B5B31DA9D
**Ausführliche Problembeschreibung**
Ähnlich auch in diesem Fall, nur kein Hebräisch.

3. **URL**
https://academic.oup.com/jss/article/65/1/93/5738635?rss=1
IxTheo#2020-05-25#1540AB4ED0423B9B421888E6FF31729CECD2B7F3
**Ausführliche Problembeschreibung**
Bei diesem Fall betrifft es sogar einen Teil des Titels.

**Offenbare Lösungen**
Zs scheint aufgrund der seltsamen Verlagslösung ungeeignet.

**Comment by socheres** [comment]
Titel bzw. Abstract, die ein Bild enthalten könnte vllt. rausgefiltert werden. Diese müssen aber im Zotkat nacherfasst werden. Ich kontaktiere mal den Verlag.

**Comment by IxKo** [comment]
Gibt es hier schon Neuigkeiten?

**Comment by socheres** [comment]
Hebräische Buchstaben im Titel und Abstract werden jetzt transliteriert. Z.B. https://academic.oup.com/jss/article/68/1/69/6885381 oder https://academic.oup.com/jss/article/67/1/29/6535851 Hebräisch als eingebettetes Bild kommt zwar gelegentlich im Abstract vor, aber bei der Datenübernahme kann sie ignoriert werden, da die Transliteration vorhanden ist. Bitte Überführung ins Zotaut prüfen.

**Comment by IxKo** [comment]
Die Gruppe ist noch nicht im Test-Verfahren.
