### ISSUE TITLE
ISSN 2517-4797 | Studia liturgica | Keywords

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#997]
**URL**
https://journals.sagepub.com/toc/stla/50/1
**Ausführliche Problembeschreibung**
Die Keywords werden nicht erkannt und übernommen.

Die Zs ist ein Test-Kandidat für das vollautomatische Verfahren. Solange das aber noch nicht live ist, sollten aktuelle Hefte dennoch ordentlich erfasst werden können.

**Comment by socheres** [comment]
bitte im Einzelndownload mit PicaK10plus_single bearbeiten. Im Multiple ist eine größere Umbauarbeit nötig. #614
