### ISSUE TITLE
Allgemein Zotero-Semi/zotkat: Resolving-URL

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#998]
**Ausführliche Problembeschreibung**
Allgemein scheint beim semi-automatischen Verfahren die DOI nicht im Pica-Feld 4950 als Resolving-URL (https://doi.org/{DOI]$xR) aufgelöst zu werden.

Beispiel-Zs: ISSN 2517-4797 | Studia liturgica

**Comment by kdr154** [comment]
Ist hier aber der Fall: https://journals.sagepub.com/doi/full/10.1177/0091647120911112
PPN 1700145703
![grafik](https://user-images.githubusercontent.com/29707105/84019084-1d8ee200-a981-11ea-9226-d23e453253d2.png)

**Comment by socheres** [comment]
Warum muss DOI-Link zusätzlich in 4950 resolvt werden? Hat dies Relevanz auf IxTheo-Suchoberfläche?

**Comment by IxKo** [comment]
@socheres 
Es hat Relevanz, da nur in 4950 die Lizenzinformationen eingetragen werden können.
Ich habe ein Beispiel gefunden, was mit dem semi-automatischen Zoteroverfahren katalogisiert wurde und bei dem nur der DOI vorhanden ist. Als Nutzer:in erhält man hier keinerlei Lizenzinformationen: https://ixtheo.de/Record/1699817464

Zudem soll laut der K10plus Format-Dokumentation ein PI in 4950 aufgelöst werden:

> Zusätzlich zu Feld 2051 wird in Feld 4950 die Resolving-URL eingetragen. Die Resolving-URL wird aus dem DOI gebildet, indem vor den DOI die Zeichenfolge "https://doi.org/" gestellt wird. In $x von Feld 4950 wird dann die Kennung "R" gesetzt. ([https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=2051&kattype=Standard](https://swbtools.bsz-bw.de/cgi-bin/k10plushelp.pl?cmd=kat&val=2051&kattype=Standard))

**Comment by kdr154** [comment]
Lizenzinformation fehlt in dem Bsp. ebenfalls. Darüber hinaus empfiehlt die Formatdokumentation als $x-Code das "R" und nicht das "H".
$5 uns $3 ($3Volltext$534) sollten ebenfalls gelieferrt werden, wenn ich mich richtig erinnere. Fehlt ebenfalls.

**Comment by socheres** [comment]
JOP zeigt Lizenzinformation und für IxTheo-Oberfläche kann und wird m.W. der unresolvte DOI global aufgelöst. Was die Codierung angeht, bitte einen neuen Issue schreiben. Da ist der Sachverhalt etwas kompliziert.

**Comment by IxKo** [comment]
Über JOP funktioniert zwar die Filterfunktion nach Open Access, selbst wenn nur der PI hinterlegt wurde, aber beim Eintrag würde ein:e Nutzer:in auf den ersten Blick nicht erkennen, ob es frei zugänglich ist. Man müsste immer erst drauf klicken und testen.

Ist es denn technisch schwierig umzusetzen, bei einem PI das Feld 4950 zusätzlich auszugeben?

**Comment by socheres** [comment]
ob ein Eintrag kostenfrei ist oder nicht hängt nicht von der DOI-Auflösung ab. Übrigens zeigt die Ampelfarbe von JOP-Icons direkt an, ob ein Eintrag kostenfrei zugänglich ist oder nicht. Die Lizenzinformationen tragen wir ja in Pica-Unterfeld $4 ein. Dafür ziehen wir die Infos aus ZEDER ab. Ich setze den Label "for Meeting discussion".

**Comment by IxKo** [comment]
Wo genau ist diese Ampel?
Bei diesem Eintrag (https://ixtheo.de/Record/1694813444) ist zwar der Artikel frei verfügbar und wird beim Filtern nach Open Access auch so gefunden, doch auf der Eintragsseite selbst sehe ich das nicht. Oder übersehe ich etwas?

**Comment by socheres** [comment]
https://ixtheo.de/Record/1694813444 ist eigentlich kein OA-Titel, wird aber trotzdem beim Filtern nach OA gefunden. Im Internformat sehe ich auch keinerlei OA-Lizenzangabe. Können Sie bitte hierzu noch einen Issue anlegen. Bei https://ixtheo.de/Record/1698100264 müsste JOP die Ampelfarbe direkt anzeigen, auch wenn Sie sich nicht im Uni-Netz befinden.

**Comment by kdr154** [comment]
Tut es doch. Bei mir grün

**Comment by IxKo** [comment]
Bei mir sieht es so aus:
![grafik](https://user-images.githubusercontent.com/57000004/84033009-833a9880-a998-11ea-8c5f-3b81756105e5.png)
Soll die Ampel der nach links oben deutende Pfeil sein?
Ich bin über VPN drin.

**Comment by socheres** [comment]
Ja, der mittlere Icon mit dem Pfeil zeigt die aktuelle Lizenzinfo an und beide o.g. Einträge sind korrekt. "Kostenfrei" wird in $4 (PICA 4950) hinterlegt (Zeder Lizenzinfo bzw. https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map).

**Comment by kdr154** [comment]
Gelb bedeutet, der Artikel oder die ZS ist mit Einschränkungen zugänglich. In Fall der Revue théologique de Louvain sieht es so aus, dass für das aktuelle Heft keine Online-Ausgabe zur Verfügung gestellt wird.

**Comment by IxKo** [comment]
Wenn es nur mit Einschränkung verfügbar ist, darf es aber nicht beim Filtern nach Open Access auftauche, oder doch?

**Comment by socheres** [comment]
@mtrojan-ub Schaust du Dir bitte diesen Fall an. 

> https://ixtheo.de/Record/1694813444 ist eigentlich kein OA-Titel, wird aber trotzdem beim Filtern nach OA gefunden. Im Internformat sehe ich auch keinerlei OA-Lizenzangabe. Können Sie bitte hierzu noch einen Issue anlegen. Bei https://ixtheo.de/Record/1698100264 müsste JOP die Ampelfarbe direkt anzeigen, auch wenn Sie sich nicht im Uni-Netz befinden.

**Comment by socheres** [comment]
> Wenn es nur mit Einschränkung verfügbar ist, darf es aber nicht beim Filtern nach Open Access auftauchen, oder doch?

Nein. Es ist wahrscheinlich ein Bug.

**Comment by kdr154** [comment]
Ich kann https://ixtheo.de/Record/1694813444 öffnern

**Comment by kdr154** [comment]
Die Ampelfarbe gilt für die Zeitschrift als Ganzes, nicht für den einzelnen Aufsatz.

**Comment by IxKo** [comment]
Eventuell wird er auch als OA gefiltert, weil die UB Tübingen die Zs lizensiert hat, weshalb ich Zugang habe.

**Comment by mtrojan-ub** [comment]
In TueFind wird OpenAccess beim Aufbereiten der Daten entweder über DOIs gesetzt oder vom Übergeordneten Werk an die Artikel vererbt.

![grafik](https://user-images.githubusercontent.com/26873381/84037134-702ac700-a99e-11ea-9827-d8fc7d0d3eb9.png)

siehe auch: 
- https://github.com/ubtue/ub_tools/blob/0ecc910ca6cd198261478654aa0b961ab507570b/cpp/pipelines/add_oa_urls.cc#L108
- https://github.com/ubtue/ub_tools/blob/0ecc910ca6cd198261478654aa0b961ab507570b/cpp/pipelines/add_isbns_or_issns_to_articles.cc#L130

**Comment by kdr154** [comment]
Deshalb ist Zeder Lizenzinfo bzw. https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map) nicht korrekt. Hier müsste KW stehen.

**Comment by kdr154** [comment]
Im K10Plus steht es ja auch ganz korrekt:
![grafik](https://user-images.githubusercontent.com/29707105/84038551-60ac7d80-a9a0-11ea-82f8-656146a48d03.png)
Was über 2011hinausgeht muss lizenziert werden.

**Comment by socheres** [comment]
@IxKo können Sie bitte überprüfen, ob die Lizenzinfo in ZEDER richtig ist. "ISSN_to_licence.map" wird im Zotaut nicht mehr berücksichtigt. @mtrojan-ub stimmt's? Kannst du "ISSN_to_licence.map" für Zotkat automatisch aus ZEDER generieren. Dann kann ich den Code für Zotkat überarbeiten.

**Comment by IxKo** [comment]
In Zeder (Zeile 958) ist und war bereits KW eingetragen. Die Mapping-Liste wird meines Wissens nur beim vollautomatischen Verfahren über Zeder gesteuert - nicht beim semi.

**Comment by socheres** [comment]
> In Zeder (Zeile 958) ist und war bereits KW eingetragen. Die Mapping-Liste wird meines Wissens nur beim vollautomatischen Verfahren über Zeder gesteuert - nicht beim semi.

Ja, beim Zotkat (=semi) über "ISSN_to_licence.map" und beim Zotaut über Zeder.

**Comment by socheres** [comment]
@IxKo bitte https://github.com/ubtue/zotero-enhancement-maps/blob/master/ISSN_to_licence.map ergänzen.

**Comment by IxKo** [comment]
@socheres  Spielt es eine Rolle, ob Zotero die ISSN der Zs ins Programm übernimmt?
Denn ich aabe eben einen Artikel der Zs in Zotero importiert, um dort die ISSN wie sie Zotero nimmt, in die Mapping-Liste zu schreiben, aber in Zotero ist das ISSN-Feld leer.

**Comment by kdr154** [comment]
Ist bei Peeters leider immer so!

**Comment by IxKo** [comment]
> 
> 
> Ist bei Peeters leider immer so!

Okay!

**Comment by kdr154** [comment]
Aber die Frage ist damit nicht beantwortet! Die ist entscheidend, ob es funktioniert.

**Comment by IxKo** [comment]
Stimmt, ich bekomme meinen Zotero-Eintrag aber auch nicht mit Strg+Shift+C importiert, um es in der WinIBW zu testen. Es erscheint die Fehlermeldung: 
![grafik](https://user-images.githubusercontent.com/57000004/84040813-622b7500-a9a3-11ea-9f70-bc6b043351aa.png)

**Comment by kdr154** [comment]
Die  Tabelle  journal_title_to_ppn.map enthält den entsprechenden Eintrag. Heißt in diesem Fall wohl aber, dass man ab jetzt die ISSN bei zotkat ergänzen muss

**Comment by mtrojan-ub** [comment]
> @mtrojan-ub stimmt's? Kannst du "ISSN_to_licence.map" für Zotkat automatisch aus ZEDER generieren. Dann kann ich den Code für Zotkat überarbeiten.

Das wäre bestimmt auch im Sinne von @ruschein, ich schaue mal was sich da machen lässt.

**Comment by IxKo** [comment]
Hallo, ich habe über die Angaben in Zeder nachgedacht und halte KW oft für nicht korrekt oder ich verstehe etwas falsch, z.B.:
Bei Zeder-Zeile 74, Zs "Aramaic studies" ist KW eingetragen, aber schaue ich mir die Zs-Info in der EZB an, ist die Ampel nicht grün sondern gelb, da die Moving Wall von 36 Monaten die Artikel nicht frei verfügbar macht, sondern nur für Institutsangehörige, die eine Academic-Search-Lizenz besitzen.

Demnach ist hier nichts "teilweise kostenfrei" verfügbar, für was die Lizenzinfo KW aber steht ("Teilweise kostenfrei zugänglich (überwiegender Teil oder ab bzw. vor einem bestimmten Zeitpunkt (Moving Wall) kostenfrei zugänglich)")

Auch bei dem Beispiel (Zeder-Zeile 958, Zs "Revue théologique de Louvain") in diesem Issue **hätte** ich die Angabe KW für nicht richtig gehalten, wenn die Hefte nur bis zum Jahr 2011 frei verfügbar gewesen wären und es danach nicht weiter geht. Schaut man jedoch auf die Seite so gibt es auch schon kostenlose Hefte vom Jahr 2013, weshalb es den Anschein macht als würden die Hefte nach 7 Jahren frei zur Verfügung gestellt.

Meiner Einschätzung nach müsste überall die Zeder-Information überprüft werden.

Was bei der automatischen Lizenzangabe über die Zeder-Spalte auch schade ist, sind die wenigen Artikel, die von einem Verlag als OA publiziert werden, wobei der Großteil der Artikel nicht kostenfrei ist. Diese würden dann im automatischen Verfahren bei einer ZZ-Zeitschrift laut Zeder die falsche Lizenzangabe erhalten. Es ist in solchen Fällen demnach bitter, die Lizenzangabe ausgehend von einer Zs abzuleiten. Wir katalogisieren einen Artikel und keine Zs.

Ich halte es zudem für nicht verkehrt, wenn man in Zeder die Möglichkeit hätte zwischen allen möglichen Lizenzangaben zu wählen. Momentan stehen nur 3 von 7 zur Auswahl.
