### ISSUE TITLE
Allgemein Zotero-Semi/zotkat: Sprache en

### ISSUE THREAD

**Issue by IxKo** [ubtue/DatenProbleme#999]
**Ausführliche Problembeschreibung**
Die Sprache in Zotero wird nicht von "en" zu "eng" umgewandelt.
Warum greift die Mapping-Liste language_to_language_code.map hier nicht?

DIe Lösung jede englsichsprachige Zeitschrift in ISSN_to_language_code.map einzutragen, ist etwas umständlich. Im Zotero-Feld wird die Sprache hinterlegt, nur nicht ganz korrekt.

Beispiel-Zss: 
ISSN 2161-6310 | Journal of Moravian history
ISSN 1745-5308 | The Expository times

Auch wenn diese Zss Test-Kandidaten für das vollautomatische Verfahren sind: Solange es noch nicht live läuft, sollten aktuelle Hefte dennoch ordentlich erfasst werden können.

**Comment by socheres** [comment]
via email geklärt.
